### ISSUE TITLE
Add 3rd party service discovery options in docs

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#1006]
Included script for haproxy is ok to start with, but there are different and better options that are not exposed to new users. Readme and/or docs should include them.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4046. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
