### ISSUE TITLE
Understand Marathon Doc for docker port binding in Bridge mode

### ISSUE THREAD

**Issue by tangicolin** [mesosphere/marathon#1009]
I don't understand relation  between "portMappings" field and normal marathon "ports" field. 

If you want to have a 80 to 80 mapping, i should use syntax :
```
  "docker": {
      "image": "foo",
      "network": "BRIDGE",
      "portMappings": [
        { "containerPort": 80, "hostPort": 80  }
      ]
    } 
...
```
or 
```
"docker": {
      "image": "foo",
      "network": "BRIDGE",
      "portMappings": [
        { "containerPort": 80, "hostPort": 0  }
      ]
    }
...
"ports" : [ 80 ]
...
```

If would result the same thing or not ? What is the right request ? 
And the flag requirePorts is still needed or not ? (https://github.com/mesosphere/marathon/issues/478#issuecomment-53333808)

Documentation about "servicePort" is not very clear for me. How it can be use ? Can i have some example  

Thanks for the answer.

**Comment by nixlike** [comment]
Hello, 
Have you found an answer ?

Thanks

**Comment by kolloch** [comment]
If you use portMappings, the value of ports is ignored. Do not specify it.

If you use "hostPort": 0, the host port will be dynamically assigned. Your application still has to bind to the container port.

The servicePort is only relevant if you have some service discovery setup that uses it. If you do not have an haproxy-bridge or similar set up, you do not need to worry about that. You can leave it configured to 0.

Do you have any further questions?

**Comment by kolloch** [comment]
Please reopen if that doesn't clarify things.

Please note that we appreciate pull requests for improved documentation:

https://mesosphere.github.io/marathon/docs/contributing.html

**Comment by sepiroth887** [comment]
Not sure if this applies but i think if you want to healthcheck tcp/http via marathon u need to set the ports in order to use portIndex. 

I tend to specify both docker and root section so i might be wrong and the ports get somehow indexed from the containerizer secrion

**Comment by nixlike** [comment]
Thank you @kolloch  @sepiroth887 it explains pretty much.

**Comment by kolloch** [comment]
@nixlike  thanks for the thanks :)
