### ISSUE TITLE
Way to separate auto assign port range and explicitly assigned ports

### ISSUE THREAD

**Issue by sttts** [mesosphere/marathon#1015]
Assume you have some apps with fixed ports in the app definition (app A) and some with auto assigned ports (app B). The fixed ports must be in the port ranges offered by the mesos-slaves.

If app A with the fixed port is down, the other app B with an auto-assigned port might choose the fixed port for a new task. When the fixed-port app A comes up, the port is taken already.

If the number of mesos-slaves is small or you just have bad luck, the deployment of app A might get stuck because there are no offers with its fixed port.

**Comment by diegogrecco** [comment]
I also have this problem. We are running some services like nginx and haproxy that we need to run on ports 80 and 8080 and it is declared on mesos slave range ports but If an application start and this is an available port, our container does not start due to a port conflict.

**Comment by scaldmaster** [comment]
+1

**Comment by garyelephant** [comment]
+1

**Comment by liticer** [comment]
+1, any solutions?

**Comment by jasongilanfarr** [comment]
We have separation with local_port if I'm not mistaken.
