### ISSUE TITLE
Stop deployment moved rollback button to the next line

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#1018]
![screen shot 2015-01-15 at 18 05 27](https://cloud.githubusercontent.com/assets/89186/5759793/3408b856-9ce1-11e4-9030-813067aa336e.png)

Firefox on mbp retina.

cc @aldipower

**Comment by bobrik** [comment]
Huh, just saw that "Affected apps" are empty too. Is it a bug too, @drexin?

**Comment by aldipower** [comment]
Hey @bobrik ! 
Thanx for your submission.
![bildschirmfoto - 15 01 2015 - 16 23 19](https://cloud.githubusercontent.com/assets/859154/5760163/1590ea8c-9cd3-11e4-816e-8c5c82fbdd57.png)
I've aligned the buttons to the right now.
It seems that you have increased the font size or zoom factor? At some point there is not enough space left in the table cell to have the buttons side by side. Also if you drag the window width to a small one.

**Comment by bobrik** [comment]
@aldipower I didn't change anything, everything might look huge because of retina though.

Progress column could be smaller, I doubt that you could see there something like `124325 / 152362`. Action is bigger that it could be too.

`Stop deployment` -> `Stop`, `Rollback deployment` -> `Rollback` can save some space.

Just my 2 cents.

**Comment by aldipower** [comment]
Great suggestion! :) Thank you!
![bildschirmfoto - 15 01 2015 - 16 44 24](https://cloud.githubusercontent.com/assets/859154/5760558/db33099e-9cd5-11e4-99eb-3839a1cca47f.png)

**Comment by bobrik** [comment]
:+1:

**Comment by drexin** [comment]
@bobrik Empty "Affected Apps" seems like another bug. Could you please open a ticket for this?

**Comment by bobrik** [comment]
@drexin #987 looks like duplicate that could be reopened.

**Comment by mlunoe** [comment]
I think https://github.com/mesosphere/marathon/issues/987 was already fixed

**Comment by drexin** [comment]
@mlunoe Doesn't show affected apps in my browser (Safari 8.0.2 on OSX Yosemite).

**Comment by mlunoe** [comment]
I have the same setup: (Safari 8.0.2 on OSX Yosemite):
![](https://s3.amazonaws.com/f.cl.ly/items/2u2Y3V0I3m2w2W3V353r/Image%202015-01-16%20at%2013%3A45%3A09.png)
