### ISSUE TITLE
PUT with force=yes to remove broken healthchecks did not restart task

### ISSUE THREAD

**Issue by air** [mesosphere/marathon#1022]
This was observed on Marathon 0.7.6:

1. We started 3 instances of a task with a bad TCP health check:
  - We asked for a TCP check on portIndex[0], where portIndex[0] was not actually opened by the app (we didn't use $PORT anywhere).
  - So the healthcheck was always failing (connection refused)
  - The app stayed in Deploying state (expected).
1. We decided to remove the bad healthcheck, so sent a PUT with an empty `healthcheck[]` in JSON and the `force=yes` parameter. Result:
  - Tasks kept running and did not restart
  - Healthchecks kept running and failing
  - In the app definition (GET v2/apps/foo), the healthchecks were correctly listed as [].

Expected: tasks should be restarted with the new, null healthcheck config.

**Comment by sttts** [comment]
Which version do you use? 0.7.6 or some recent development version?

**Comment by air** [comment]
0.7.6 - thanks.

**Comment by sttts** [comment]
Do you have a test system where you can test a current development version? I could provide you with a debian/ubuntu deb.

**Comment by drexin** [comment]
@air It's `force=true`, not `force=yes`.

**Comment by air** [comment]
Thanks @drexin - I typed this up on the train so that's my error, not what was actually submitted in the request.

**Comment by drexin** [comment]
Ok, I will investigate this. Thanks!

**Comment by drexin** [comment]
@air I couldn't reproduce this with current master, could you please confirm and close this ticket?

**Comment by air** [comment]
Since I don't have access to the original setup and the master appears good, I'll close for now.
