### ISSUE TITLE
Improve feedback when handling an "invalid" API payload (e.g. underscores in app ID) 

### ISSUE THREAD

**Issue by mforsyth** [mesosphere/marathon#1023]
Hi there:

I was stuck for a while today trying to figure out why Marathon wouldn't accept my POST request to start a group of apps.

I eventually figured out that underscores aren't allowed in app id's.  The problem I have is that there was no specific feedback about my request; it was just a 422 response.  There was no information about what was wrong in the logs and the response body was empty.

If you reject a request for a specific and well-defined reason, it will make for a better developer experience if you both log the problem and return it in the response body.

**Comment by drexin** [comment]
Hi @mforsyth,

what version of Marathon did you use? On the current stable version (0.7.6) it looks as follows:

```
λ curl -XPOST -H "content-type: application/json" http://10.132.179.214:8080/v2/apps -d '{
  "id": "dsdsd_dsd",
  "cmd": "tail-f/dev/null"
}'

{"errors":[{"attribute":"id","error":"path contains invalid characters (allowed: lowercase letters, digits, hyphens, \".\", \"..\")"}]}
```

**Comment by mforsyth** [comment]
@drexin Thanks for the response!  
Have just upgraded to 0.7.6 this morning and it responds exactly as you posted.  Thank you!
