### ISSUE TITLE
After scaling, old tasks are shown as "Out-of-date"

### ISSUE THREAD

**Issue by sttts** [mesosphere/marathon#1025]
When scaling an app, a new app version is created during deployment. We do not restart old tasks during scaling. Hence, the old tasks have the old app version.

The UI form today's master branch shows those old tasks as "Out-of-date".

We either have to update the version of those old tasks or avoid creating a new version.

Frontend: Add moment.js as a dependency and add relative times to version field: "Just now", "An hour ago" and "Three days ago" all in white. Hover over or click on these fields should show the version timestamp. Here the ability to copy the version number should be considered.

**Comment by mlunoe** [comment]
This is expected behaviour as with the new scale, the app configuration has changed.

**Comment by sttts** [comment]
It's not what a user expects IMO.

**Comment by sttts** [comment]
"out of date" sound like something is wrong.

**Comment by bobrik** [comment]
I agree with @sttts

**Comment by drexin** [comment]
I agree. If there's a deployment that changes anything other than the number of instances, it will replace all the tasks anyway, so there will never be an out-of-date version running.

**Comment by sttts** [comment]
Deployments which only scales, should NOT restart all the tasks. This is a lot of unnecessary load on the cluster, imagine cold caches and so on. Image you have 900 tasks running and scale to 1000. Restarting 900 for 10% more capacity is not very clever.

**Comment by drexin** [comment]
;-)

**Comment by sttts** [comment]
Would it make sense to compare the current version with the previous version up to the instances value in the UI?

**Comment by drexin** [comment]
No. As I said, there will never be two different versions running that differ in anything but the number of instances.

**Comment by sttts** [comment]
Right. But I was wondering how to get rid of the ugly yellow "Out-of-date" message in the UI. This can be done on the server during the deployment (by updating the old tasks' AppDefinition) or in the UI by a comparison.

**Comment by mlunoe** [comment]
So how do we go about this? We could rename it from "Out-of-date"? The problem we tried to solve was that the version numbers wasn't easy to parse, to see which tasks are running the current version and which are not.

**Comment by mlunoe** [comment]
@sttts and @bobrik: Would you be on board with adding moment.js (using the relative time function: http://momentjs.com/docs/#/customization/relative-time/) to say e.g. "Just now", "An hour ago" and "Three days ago" (all in white), to make it easy to parse and still communicate when each task was updated?

**Comment by sttts** [comment]
From a user's point of view relative dates would be great. In addition I would update the version in the backend when the scale step is finished. Then you have the new version for every task when the deployment is done.

**Comment by bobrik** [comment]
I'm ok with relative time if you could get absolute values in tooltip or with click (like in mesos ui).

+1 for @sttts on updating version or keeping old version for scaled tasks. Not sure what is the best option, though.

**Comment by mlunoe** [comment]
I updated the comment to reflect the frontend changes, @drexin will you add the backend changes?
