### ISSUE TITLE
Running tasks gets expunged after leader election

### ISSUE THREAD

**Issue by deric** [mesosphere/marathon#1032]
When running Marathon in distributed mode tasks are expunged after master election, then there are tasks with version from `1970`

```
    {
      "host": "",
      "ports": [],
      "startedAt": "2015-01-16T14:12:10.191Z",
      "stagedAt": "2015-01-16T08:38:07.886Z",
      "version": "1970-01-01T00:00:00.000Z",
    }
```
there's no information if this tasks is running at some server, however Marathon considers this tasks as running one. This doesn't happen when there's only one instance of Marathon running.

**Comment by drexin** [comment]
Thanks for reporting this. This is a known issue and should be fixed in current master. Please try and see if it works.

**Comment by deric** [comment]
Any chance to get a release soon?

**Comment by drexin** [comment]
We are on a good way to a release. We want to make sure that the next release willbe very robust, so we may release an RC first. That could happen as early as next week.

**Comment by lukaswelte** [comment]
@drexing I like the idea of a RC. 
Version 0.7.6 is really to buggy for a Software like Marathon, you want the "init of the cluster" to be very stable :+1:

**Comment by ConnorDoyle** [comment]
@lukaswelte granted, the 0.7.6 release was a step backward in terms of stability.  The plan is RCs for releases from now on to help avoid this in the future.

**Comment by aquamatthias** [comment]
That should be solved in the current release. Please reopen, if you still see this behavior.
