### ISSUE TITLE
Port assignment or display with a marathon deploy

### ISSUE THREAD

**Issue by kensipe** [mesosphere/marathon#1035]
With a newly provisioned cluster on GCE, Marathon 0.7.6.  Deploying tomcat with the [screencast script](https://github.com/mesosphere/docker-mesos-marathon-screencast/blob/master/tomcat-remote.json), the UI doesn't show the assigned port.   The script uses $PORT.. I've also tried $PORT0.  both fail.

**Comment by ConnorDoyle** [comment]
This has since been fixed in `master`.  See isue #888 and PR #924 that fixes it.

As a workaround, set a value for the `ports` field.

e.g.

```
{
  ...
  "ports": [0]
}
```
