### ISSUE TITLE
RFE: Respect Content-Disposition header when downloading storeUrls artifacts

### ISSUE THREAD

**Issue by alberts** [mesosphere/marathon#1037]
We're experimenting with running Docker containers where some of the configuration is generated by SaltStack after the container starts and before the main service runs.

To be able to make reusable containers, we'd like to be able to fetch the SaltStack configuration directly from our Stash repository so that it shows up in our docker_sandbox_directory when the container runs so SaltStack can run against this configuration when the container initializes.

URLs we would to configure in storeUrls look like this:

https://stash/plugins/servlet/archive/projects/foo/repos/bar?at=refs%2Fheads%2Fmaster
https://stash/plugins/servlet/archive/projects/foo/repos/bar?at=83062147a7c16f5b453fe1b7984aacc51d9a35f7

which leads to ugly names in the artifact store and presumably in the docker_sandbox_directory.

Stash returns hese headers, which seem to be ignored:

Content-Type: application/octet-stream
Content-Disposition: attachment; filename="bar-master.zip"

**Comment by alberts** [comment]
Another issue with Stash: when trying to download the raw source of a single, you have a URL like:

https://stash/projects/foo/repos/bar/browse/pillar.sls?at=HEAD&raw

urlIsValid does a HEAD, which Stash doesn't like:

< HTTP/1.1 405 Method Not Allowed

At least, if a 405 is returned, it should probably simply try a GET.

**Comment by aquamatthias** [comment]
One goal of the artifact store was, that the same url can point to different artifacts over time (e.g. a CI server etc.). For that goal we take either the strong ETag or compute the md5 Hash of the content and take that as file name. As a consequence, the original file name is lost.

One part of the validation, checks if the URL can be resolved. That is the HEAD request. If the HEAD request fails with 405, we should try the GET, I agree.
Relevant code is [here](https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/api/ModelValidation.scala#L200)

**Comment by aquamatthias** [comment]
Please reopen, if this is still a problem.
