### ISSUE TITLE
Unknown health status, deployment stuck

### ISSUE THREAD

**Issue by c089** [mesosphere/marathon#1045]
I'm currently witnessing something weird in a marathon/mesos cluster:

* I created two apps with docker containers, both configured to start a single instance
* they have been started on mesos and operate normally
* Marathon regularly sends health check requests to both, and they both answer with HTTP 200 as I can see from their logs and the marathon log: `Received health result: [Healthy(...`
* However, for one the two apps, the marathon API does not return the `tasks.healthCheckResults` array at all... and as a consequence, that service is still treated as "deploying", and the deployment is stuck.

I'm currently trying to understand how this happened but have hit a wall. I can't reliably reproduce this yet either, but have seen it before... Any help in how to go about debugging this would be appreciated.

**Comment by drexin** [comment]
We fixed a couple of deployment related bugs. Could you test it with the current master?

**Comment by c089** [comment]
I'll try to upgrade, it's just a test system anyway, but have no idea how to reproduce this one :) Guess I'll just have to wait if it happens again

**Comment by c089** [comment]
Yay, I deployed a bunch of times against rc1 and didn't see this behaviour - closing for now in the hope we won't see this again :)
