### ISSUE TITLE
Query apps and tasks based on labels.

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#1053]
See #1051.  Depends on #1052.

To implement this we should add a query language that allows us to list application that match the query. For a first release the supported conditions should be:

- [ ] Is the label key set?
- [ ] Does the label value equal some value?
- [ ] Multiple selector must match

Additional Features:

Eventually we should support something similar to kubernetes [query language](https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/labels.md#label-selectors). We need to make sure that whatever we implement now should allow us to extend it to implement the full query language without breaking existing applications that use this query language.

**Comment by jsancio** [comment]
Implemented by #1364
