### ISSUE TITLE
REST API does not document responses

### ISSUE THREAD

**Issue by air** [mesosphere/marathon#1054]
The REST responses generated by Marathon are mostly undocumented. This makes debugging difficult, and scripting with error handling nearly impossible.

The http://mesosphere.github.io/marathon/docs/rest-api.html should be updated with possible responses for each operation.

1. There will be a set of common error responses used by many API calls, e.g. `404 app does not exist`.
2. Operations like `POST /v2/apps` will have specific errors, e.g. `400 app name is already taken` or something.

Real life example: I am currently trying to create an app group by POSTing JSON to `/v2/apps`. Marathon is returning me a `200` with the current list of app metadata (exactly as if I performed a GET). I have no idea if this is an expected response for this API call, or an error.

ACs

- [ ] for each endpoint, find the list of possible HTTP error codes and a description of the response body (where applicable) 
- [ ] update the marathon docs

**Comment by pierlo-upitup** [comment]
@mwasn might be a good idea to add the reasons for closing the issue FTR.
