### ISSUE TITLE
Add app labels to UI.

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#1055]
Depends on #1051.

**Comment by pierlo-upitup** [comment]
Also: should be possible to attach these labels when creating an App from the UI.

**Comment by nathanleiby** [comment]
Do you have a design in mind for where to display this info? e.g. 

- in the config tab
- at the top level

**Comment by kolloch** [comment]
In theory, there can be a lot of labels with a lot of values. So I would suggest only showing them in the config tab (or similar first).

It might make quite some sense for some labels to be displayed top-level but that would require further thought.

**Comment by aldipower** [comment]
https://github.com/mesosphere/marathon/issues/2283

Still missing: Adding labels in the app creation dialog.

**Comment by seh** [comment]
I'd be perfectly happy being able to see the labels only in the Configuration tab.
