### ISSUE TITLE
'delete app' from the GUI does not clean up its empty groups

### ISSUE THREAD

**Issue by air** [mesosphere/marathon#1056]
To reproduce:
1. POST an app to /v2/apps with the id `mygroup/myapp`
2. Remove it (using either the GUI or REST) via `DELETE /v2/apps/mygroup/myapp`
3. Observe that the group remains with `GET /v2/groups`.

This can cause issues when you create an app, delete it, then attempt to work with the group. Most users will not realise that 1. Groups are implicitly created and 2. That they live on after the app is gone.

Potential actions:
1. When a DELETE against /v2/apps results in empty groups, delete those groups.
2. The docs might mention that POST /v2/apps will also implicitly create groups.
3. The doc http://mesosphere.github.io/marathon/docs/application-groups.html could be expanded to explain the group hierarchy, with reference to using GET /v2/groups to see what's going on.
   - A good analogy is that groups and apps act like a filesystem. When you create an app, it's like a `mkdir -p foo/bar`. When you delete `foo/bar`, the directory `foo` remains.

**Comment by air** [comment]
Ping @BenWhitehead

**Comment by aquamatthias** [comment]
@kolloch did'nt you made some improvements here?

**Comment by nugend** [comment]
I think some of this behavior is discussed in #851, however I think a decision to remove empty groups was rejected.

**Comment by kolloch** [comment]
Actually, I like more or less all proposed actions.

I'd like to add the following proposals: 
* make groups visible in the UI
* allow a GC call, maybe something like `POST /v2/groups/removeUnusedGroups`

Deleting empty groups automatically should be mostly fine but potentially has some corner cases. Marathon supports dependencies on groups, also empty groups.

**Comment by air** [comment]
Thinking about this - what are some uses of an empty group? In what circumstances would a user want one?

**Comment by aquamatthias** [comment]
Groups are 
- containers for applications
- define dependencies to other groups/applications
It would be perfectly possible to define an empty group with dependencies.

**Comment by kamilchm** [comment]
We are using groups for building "ephemeral" dev environments with generated names. After upgrading to 1.1 we saw how many of it was created in last few months making Marathon app list almost unusable :/
What about implementing empty groups GC proposed by @kolloch? We can create a PR if we agree on endpoint method and path. @aquamatthias ?

**Comment by aquamatthias** [comment]
@kamilchm The API allows deleting groups.
Adding a special `"GC"` call for empty groups is probably a bad idea.
I could think of an option when deleting an app, that also deletes the group, if it is empty.
Would that make sense?

**Comment by kamilchm** [comment]
I think this will be more consistent with implicit group creation when you you ``POST`` app with slashes in ID to ``applications``.
Right now, you don't have to create group explicitly before you create an app but you need to call delete group if you want to clean up after destroying same app.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4334. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
