### ISSUE TITLE
Clean up integration tests

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#1070]

**Comment by kolloch** [comment]
Hi @ConnorDoyle , can you add a description?

Actually, I am just preparing a PR which cleans up some things but I am not sure if that's a match ;)

**Comment by hekaldama** [comment]
Does this prevent 0.8.2 from being released?

**Comment by drexin** [comment]
No.

**Comment by hekaldama** [comment]
@kolloch, did you end up prep'ing a PR for this? Did you get any feedback on what things to clean up?

**Comment by kolloch** [comment]
Hi @hekaldama,

since @ConnorDoyle didn't provide any feedback, I don't know ;) I reworked some thinks in the tests.

I will close this issue for know. @ConnorDoyle can reopen this with details at any time.
