### ISSUE TITLE
Enable a way for a user to manually set a task as "TASK_LOST"

### ISSUE THREAD

**Issue by samccone** [mesosphere/marathon#1072]
Enable a way for a user to manually set a task as __TASK_LOST__

This is something I have been hitting a bunch, basically due to my computer shutting down, or running out of battery my VM shuts down. It puts marathon in a really odd state where I can not remove tasks. Pretty much I have to sit around and wait for marathon to figure out that a task has been lost. Which is frustrating because I have no way to manually clean this up.

I would __love__ for an endpoint to hit to manually do this instead of having to wait.

Here are the related log messages from marathon.

```
Cannot kill task xxxx of framework 20150121-074658-16842879-5050-7933-0000 (marathon-0.7.6) at scheduler-30cdeb81-bcb6-4dc3-8f4f-71786463bc6b@127.0.1.1:50439 because the slave containing this task may not have re-registered yet with this master
```

```
Jan 22 06:39:00 xxxx marathon[2862]: [2015-01-22 06:39:00,711] INFO Received status update for task xxxx_elasticsearch.ff72fb1d-a1b7-11e4-b9c6-56847afe9799: TASK_LOST (Attempted to kill an unknown task) (mesosphere.marathon.MarathonScheduler:162)
```

Thanks again for this great tool :sparkling_heart: !

**Comment by aquamatthias** [comment]
Hey @samccone thanks for the appreciation!
I guess the original problem is, that marathon does not recover from odd state.
Question: did Marathon improve with later versions? Is that still a problem?

**Comment by samccone** [comment]
It has improved more recently and I have not hit this. We can close this for now, and if anyone runs into it again this can be reopened.
