### ISSUE TITLE
Can Marathon expose internal ip of the container?

### ISSUE THREAD

**Issue by sivaramsk** [mesosphere/marathon#1075]
When mesos spawns the container, can it expose the internal ip of the container which was spawned in bridge mode?

**Comment by sttts** [comment]
What do you mean with expose here?

I am currently experimenting with Weave and Mesos. I would like to have health checks using the internal IP instead of the host IP. Is it what you mean?

**Comment by gregory90** [comment]
As far as I know it's not possible. Unless something has changed, related: #674

**Comment by aquamatthias** [comment]
Close this issue, since it duplicates #674
