### ISSUE TITLE
using a private docker image, no error feedback if .dockercfg missing

### ISSUE THREAD

**Issue by air** [mesosphere/marathon#1077]
1. You want to run a docker image and it's private in the docker registry.
2. For whatever reason you do not have a `.dockercfg` specified in your JSON. e.g.

```
{
  "id": "/dockertest",
  "instances": 1,
  "cpus": 1,
  "mem": 1024,
  "ports": [ 0 ],
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "your-org/private-image",
      "network": "HOST"
    }
  }
}
```

Expected behaviour: You receive an error message of some kind allowing you to debug the issue. Perhaps 'Docker registry authentication failed'.

Actual behaviour: The task stays in Deploying state, with no useful output in stdout or stderr.

**Comment by tnachen** [comment]
The way Mesos throw errors is still sub optimal for sure, especially around containerizer errors like this.
stdout/stderr only has task logs only if the task was able to launch.
Since .dockercfg is not there, the task couldn't even launch, so your meaningful erorr message is most likely in the slave log.
I think I'll be working on better error message transferring to frameworks around this.

**Comment by bobrik** [comment]
@tnachen is it https://issues.apache.org/jira/browse/MESOS-2020?

#1078 is the same issue, actually.

**Comment by bobrik** [comment]
@ConnorDoyle, @drexin can we show number of failed tasks for current app revision in app list? That should give a hint if app deployment is stuck or just constantly failing.

`Running / Instances` for healthy apps, `Running / Instances / Failed (red)` for apps that have failed tasks in current revision.

**Comment by ConnorDoyle** [comment]
Related: #126, #652, #951, and #968.

**Comment by sttts** [comment]
I don't like a third counter very much. What should it show? The number of failed tasks in the last minute? What we need is either some statistical view, maybe a histogram of the status of the task in the last minute. Or, maybe even better, some kind of log what marathon did for the app, but in a way that the user can understand.

**Comment by pcj** [comment]
The marathon web ui seems to lack any feedback to the user regarding the status of task deployments, though some information can be gleaned from `/var/log/syslog`.  This seems like low-hanging fruit to implement.

**Comment by themasterchef** [comment]
The lack of info as to whether my .dockercfg has been successfully retrieved by a Marathon deployment is turning a routine cluster setup with private Docker images into a rather torturous affair, with exceptionally little information available to the user. Anything that can be done to improve the error logging beyond watching an app's deployment status never change would be greatly appreciated.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3752. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
