### ISSUE TITLE
no useful feedback if a private docker repo has the wrong permissions

### ISSUE THREAD

**Issue by air** [mesosphere/marathon#1078]
1. You want to run a docker image and it's private in the docker registry.
2. Your `.dockercfg` is correct.
3. However, your docker hub repository does not have the extra permission set that you need: `publishers` must be set with either `read` or `write` permission.

Expected behaviour: You receive an error message of some kind allowing you to debug the issue. Perhaps 'Docker registry authentication failed'.

Actual behaviour: The task stays in Deploying state, with no useful output in stdout or stderr.

**Comment by bobrik** [comment]
I think this is an existing issue for mesos: https://issues.apache.org/jira/browse/MESOS-2020.

You should be able to see errors in sandbox in mesos ui, but they just go to mesos-slave logs.

**Comment by ConnorDoyle** [comment]
See #951

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4019. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
