### ISSUE TITLE
Configurable maxLaunchDelay for apps

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#1087]
Currently it is hardcoded to be [1 hour](https://github.com/mesosphere/marathon/blob/394f12fb8934c362e60f12de0b78dbf2b3116dbe/src/main/scala/mesosphere/util/RateLimiter.scala#L18). It would be nice to make it configurable per app.

Imagine running app from local docker registry. Registry could temporarily fail (net split or something) and app deployment would stuck. With configured max delay of 1 minute deployment would finish much sooner.

I've seen the delay of 1080 seconds: https://github.com/mesosphere/marathon/issues/1083#issuecomment-71196704.

I can probably come up with a PR if the idea makes sense.

**Comment by ConnorDoyle** [comment]
Sounds like a good idea to me.  Want to take a crack at it?

**Comment by bobrik** [comment]
Yep, I can try. It should be inserted where `backoff` appears.

A few questions:

1. Are we going to keep `maxLaunchDelay` as a name?
2. Are we going to keep 1h default?
3. Can you mention in readme that `protoc` should be 2.5.0, because 2.6.1 does not work with marathon?
