### ISSUE TITLE
Clarify correct way to restart Marathon

### ISSUE THREAD

**Issue by pcj** [mesosphere/marathon#1095]
I'm having trouble with marathon restarts.  With a 1 master 3 slave development cluster, I killed the marathon framework with its framework ID: 

```
curl --data "frameworkId=20150121-172344-3782837258-5050-2826-0001" -X POST http://10.132.121.225:5050/master/shutdown
```

On the mesos web console, the framework transitioned from _active_ to _terminated_.  OK, fine.  The I attempted to restart it via `sudo service marathon restart`.  Monitoring syslog with `tail -f /var/log/syslog` shows:

```
Jan 24 23:06:53 development-3657-d15 marathon[9359]: [2015-01-24 23:06:53,019] INFO Starting Marathon 0.7.6 (mesosphere.marathon.Main$:20)
23:06:57,857:9359(0x7fc337190700):ZOO_INFO@log_env@723: Client environment:os.name=Linux
Jan 24 23:06:57 development-3657-d15 marathon[9359]: 2015-01-24 23:06:57,857:9359(0x7fc337190700):ZOO_INFO@log_env@724: Client environment:os.arch=3.2.0-4-amd64
Jan 24 23:06:57 development-3657-d15 marathon[9359]: 2015-01-24 23:06:57,857:9359(0x7fc337190700):ZOO_INFO@log_env@725: Client environment:os.version=#1 SMP Debian 3.2.54-2
Jan 24 23:06:57 development-3657-d15 marathon[9359]: 2015-01-24 23:06:57,858:9359(0x7fc337190700):ZOO_INFO@log_env@733: Client environment:user.name=(null)
Jan 24 23:06:57 development-3657-d15 marathon[9359]: 2015-01-24 23:06:57,858:9359(0x7fc337190700):ZOO_INFO@log_env@741: Client environment:user.home=/root
Jan 24 23:06:57 development-3657-d15 marathon[9359]: 2015-01-24 23:06:57,858:9359(0x7fc337190700):ZOO_INFO@log_env@753: Client environment:user.dir=/
Jan 24 23:06:58 development-3657-d15 marathon[9359]: [2015-01-24 23:06:58,437] INFO Setting framework ID to 20150121-172344-3782837258-5050-2826-0001 (mesosphere.marathon.MarathonSchedulerService:69)
Jan 24 23:06:58 development-3657-d15 marathon[9359]: [2015-01-24 23:06:58,773] INFO Offering leadership (mesosphere.marathon.MarathonSchedulerService:288)
Jan 24 23:06:58 development-3657-d15 marathon[9359]: [2015-01-24 23:06:58,845] INFO Elected (Leader Interface) (mesosphere.marathon.MarathonSchedulerService:246)

Jan 24 23:06:58 development-3657-d15 mesos-master[8784]: W0124 23:06:58.911877  8806 master.cpp:1511] Completed framework 20150121-172344-3782837258-5050-2826-0001 (marathon-0.7.6) at scheduler-2d8d14e2-3a8c-4465-97bc-1ce1ea2c6684@127.0.1.1:56315 attempted to re-register
Jan 24 23:06:58 development-3657-d15 marathon[9359]: I0124 23:06:58.914346  9401 sched.cpp:736] Got error 'Completed framework attempted to re-register'
Jan 24 23:06:58 development-3657-d15 marathon[9359]: I0124 23:06:58.914590  9401 sched.cpp:1320] Asked to abort the driver
Jan 24 23:06:58 development-3657-d15 marathon[9359]: [2015-01-24 23:06:58,915] WARN Error: Completed framework attempted to re-register (mesosphere.marathon.MarathonScheduler:255)
Jan 24 23:06:58 development-3657-d15 marathon[9359]: [2015-01-24 23:06:58,916] FATAL Committing suicide (mesosphere.marathon.MarathonScheduler:260)
Jan 24 23:06:58 development-3657-d15 marathon[9359]: [2015-01-24 23:06:58,923] INFO Shutdown triggered (mesosphere.marathon.MarathonSchedulerService:159)
Jan 24 23:06:58 development-3657-d15 marathon[9359]: I0124 23:06:58.924556  9406 sched.cpp:752] Stopping framework '20150121-172344-3782837258-5050-2826-0001'

```

Specifically this **`Completed framework attempted to re-register`** error.  What does it mean and how to fix it?  

I was able to workaround by restarting the single master `sudo /etc/init.d/mesos-master restart` and then `sudo /etc/init.d/marathon start`.  However, this seems suboptimal.

I went through this trying to rename the marathon framework name by `echo 'marathon' > /etc/marathon/conf/framework_name`. And FWIW, that didn't work either.

**Comment by drexin** [comment]
If you simply want to restart Marathon, restarting the service should be sufficient. Unregistering the framework means, that all the running tasks will go away as well. Of course Marathon should handle the case where the framework ID is not valid anymore. I will keep this open to track this issue.

**Comment by drexin** [comment]
Ok, I think the behavior of Marathon is correct. It shouldn't decide to register with a new ID by itself. If you really want to have a fresh Marathon, you can just delete the state from ZooKeeper.

@ConnorDoyle WDYT?

**Comment by alberts** [comment]
@drexin Seemed to hit this error with a 5 node cluster where none of the nodes thought that it was the leader. Could you provide more details on what ZooKeeper state needs to be deleted?

**Comment by drexin** [comment]
Hi @alberts,

if you want Marathon to register with a new id, but keep the rest of its state, you have to delete `/marathon/state/frameworkId`. Be aware that if Marathon registers with a new id, it will not be able to pick up the old tasks from Mesos, so make sure you are deregistering the old Marathon id.

If you want to start with an empty Marathon, just delete `/marathon`.
