### ISSUE TITLE
Is there a changelog of exactly what has changed in the API for the 0.8RC1?

### ISSUE THREAD

**Issue by knuckolls** [mesosphere/marathon#1097]
I've been working on a marathon client library and I want to make sure that it's still 100% compatible. I saw this in the release notes and it made me think that I might need to update my client library.

"modified the representation of docker parameters to allow multiple values for the same option"
https://github.com/mesosphere/marathon/releases/tag/v0.8.0-RC1

**Comment by drexin** [comment]
The representation changed from a simple JSON object, to an array of key/value pairs to allow multiple values for a single key. Here's the relevant patch: https://github.com/mesosphere/marathon/commit/9c84e66d1cd63ce235954633148b0853959ecec9

**Comment by knuckolls** [comment]
This is very helpful. Thanks!
