### ISSUE TITLE
Health checks for deployment

### ISSUE THREAD

**Issue by neelance** [mesosphere/marathon#1099]
Hi,

is the deployment waiting for a green health status of the new tasks before it stops the old ones? We saw some behavior that suggested the contrary.

Cheers,
Richard

**Comment by bobrik** [comment]
Can be related to #1082

**Comment by sttts** [comment]
@neelance according to the code it waits for health checks when they are defined. But I believe to have seen cases where a deployment step ends early.

**Comment by ConnorDoyle** [comment]
Is this still an issue with 0.8.x?

**Comment by bobrik** [comment]
@ConnorDoyle I believe you still can see it in 0.8.0, but 0.8.1 should be good, #1082 is probably related.

@neelance you can try 0.8.1-RC1, it should fix the issue.

**Comment by sttts** [comment]
Looking at #1082 and the deployment code, I don't believe that #1082 also fixed this problem. The deployment actors only look at the `AppDefinition` whether there are health checks defined. If so, it's not enough that a task is running, but the actor waits for its health update.

**Comment by sttts** [comment]
I propose to leave this one open and watch the issue. Though I cannot remember having seen this recently.

**Comment by bobrik** [comment]
What I've seen as part of #1082: deployment finishes when health checks for new tasks are green (good), but in api and ui new tasks have unknown health check state (bad). This can be a different issue, but from UI and API it looks the same.

**Comment by sttts** [comment]
This makes sense. The api code does not see the health check actor with the wrong key, and hence it cannot query it for the task health state. So maybe the deployment were correct all the time, only the UI was wrong.

**Comment by sttts** [comment]
@drexin I think this issue can be closed then.
