### ISSUE TITLE
Deployment stuck when replacing and scaling down

### ISSUE THREAD

**Issue by sttts** [mesosphere/marathon#1100]
If "minHealthCapacity * oldApp.instances" > "maxOverCapacity * newApp.instances", there is not enough capacity to get the deployment going. E.g.:

- run an app with instances=4, minHealthCapacity=1.0. 
- now deploy a new version with instances=2.

Maximum over capacity is 2.0 * 2 = 4, 4 instances should be kept running => deployment stuck.

**Comment by bobrik** [comment]
Huh, I just got the same issue when scaling from 10 to 1 instances. :+1:
