### ISSUE TITLE
Question: Consul instead of Zookeeper?

### ISSUE THREAD

**Issue by MrMMorris** [mesosphere/marathon#1115]
Is it possible to use Consul in place of Zookeeper? I see people are using Consul with Marathon/Mesos, but is it in place of zookeeper or side-by-side? One issue I had seen was that Consul didn't support TTL, but it does now so will there be/is there support for Consul?

**Comment by xiaods** [comment]
Does it have any more benefit?

**Comment by MrMMorris** [comment]
Well I like that Consul has Consul Template (vs confd) which is tightly integrated. Also, Consul provides more than just a K/V store. It does service discovery (automatic with Registrator) and cross-datacenter as well as nice health checks. 

see http://www.consul.io/intro/vs/zookeeper.html

It seems to be a popular choice if you aren't running CoreOS (or even if you are as I've seen) and would most likely be a common request as marathon becomes more popular.

**Comment by rasputnik** [comment]
I'd tend to stick with zookeeper. Consul seems nice but it's not as battle
tested.
Plus you'll need zookeeper anyway for Mesos, so why deploy 2 things?

**Comment by MrMMorris** [comment]
> Consul seems nice but it's not as battle
> tested

That may be true, but the fact that it does more than what Zookeeper is capable of and will quickly become pretty popular like most Hashicorp offerings is a good reason to ask this question now. 

> Plus you'll need zookeeper anyway for Mesos, so why deploy 2 things?

That's the point of my question. Is there plans for Mesos/Marathon to support alternatives to Zookeeper?

**Comment by stuart-warren** [comment]
Yes Mesos is apparently adding etcd support.
https://issues.apache.org/jira/browse/MESOS-1806
Once that is done, adding Consul support shouldn't be too hard

**Comment by MrMMorris** [comment]
@stuart-warren great to hear! thanks for the info.
