### ISSUE TITLE
Invalid npm build configuration introduced in 0.8.0-RC2

### ISSUE THREAD

**Issue by BenWhitehead** [mesosphere/marathon#1119]
On TravisCI there is an issue with the npm build where the UI assets aren't being generated correctly.

See build log: https://travis-ci.org/mesosphere/marathon/builds/48611261#L313

**Comment by air** [comment]
Is this to be fixed for 0.8.0?

**Comment by drexin** [comment]
Yes.

**Comment by aldipower** [comment]
Already fixed here, but didn't reached the RC2, will be in the release:
https://github.com/mesosphere/marathon/commit/91c5dab268be1a77aeb8e3e7b90df7654ff3101b
