### ISSUE TITLE
Tag TaskInfo with app labels

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#1121]
Pending task labels support (scheduled for Mesos 0.22.0).  Task labels will be surfaced through the master's `state.json`.

See [TaskInfo labels in mesos.proto](https://github.com/apache/mesos/blob/76270a7cabfce289e4dbcb3e4a17bbb9a7326cdb/include/mesos/mesos.proto#L689).

**Comment by alberts** [comment]
@drexin Would love to see this in the next Marathon release.

**Comment by ConnorDoyle** [comment]
See PR #1337
