### ISSUE TITLE
Web UI shows tasks scaled to 0 as "Running"

### ISSUE THREAD

**Issue by lingmann** [mesosphere/marathon#1122]
Running Marathon 0.8.0-RC1, scaled an app to 0 instances, and the Web UI shows the app as "Running" in two different locations:

![screen shot 2015-01-31 at 7 06 12 pm](https://cloud.githubusercontent.com/assets/33731/5990868/5dd1d904-a97c-11e4-95d4-6626e9d8ae41.png)

![screen shot 2015-01-31 at 7 08 29 pm](https://cloud.githubusercontent.com/assets/33731/5990869/9c9b0e26-a97c-11e4-964e-b3f3b2186822.png)

This could likely be confusing for users. Is there a better way to describe the app status when it is in this state?

**Comment by lukaswelte** [comment]
Could easily be "Suspended" cause the button to scale to 0 instances is also named "Suspend"

**Comment by lukaswelte** [comment]
Thanks @aldipower.
Issue can be closed

**Comment by lingmann** [comment]
awesome, thanks! :+1:
