### ISSUE TITLE
Support log level changes at runtime

### ISSUE THREAD

**Issue by lingmann** [mesosphere/marathon#1127]
It does not appear possible to change the logging levels on non-leading Marathon instances at runtime. This would be a nice improvement to have.

**Comment by wwalker** [comment]
+1 Yes, please

**Comment by kolloch** [comment]
At least at first glance, I haven't found an easy way to configure log4j this way. Do you have suggestions?

Another approach would be to switch over to the slf4j-API internally completely and then switch from log4j to logback. Its is quite easy to make logback periodically scan the configuration file for updates. You can also reconfigure it via JMX (can't you with log4j actually?).

So what are you looking for? Changing the configuration file, using JMX or something else?

The easier it is to integrate, the better :)

**Comment by timoreimann** [comment]
Changing the configuration file would be a starter for my organization.

**Comment by jasongilanfarr** [comment]
Could be wrong but I think we have this now

**Comment by timoreimann** [comment]
@jasongilanfarr how does one do it? Is it documented somewhere?

I'd prefer to see the issue getting closed along with at least some pointer on how the requested feature can be enabled.

**Comment by jasongilanfarr** [comment]
I'm mistaken and wrong. I could swear there was a logging endpoint that supported this but couldn't find a reference in the docs. Reopening.

**Comment by timoreimann** [comment]
Thanks, Jason. Appreciated.

**Comment by bobrik** [comment]
@jasongilanfarr `/logging` endpoint is there.

**Comment by timoreimann** [comment]
FWIW, that endpoint changed things for me during runtime in the past. Maybe it's different now.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3936. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
