### ISSUE TITLE
Marathon is not deploying new docker image (changed tag or name)

### ISSUE THREAD

**Issue by neelance** [mesosphere/marathon#1136]
When an app is already running and I change the docker image to some other tag or even other image name and then push the new config to `/v2/apps`, then the web UI reflects the image change and all running tasks are replaced. Everything looks fine at first, but when I check `docker ps` on the slaves, then I can see that the new docker containers/tasks have been created from the old docker image.

**Comment by drexin** [comment]
What versions of Marathon and Mesos are you running?

**Comment by neelance** [comment]
Just checked the new RC2 and was still the same.

**Comment by lukaswelte** [comment]
Was the new docker image pulled onto the slave?

**Comment by neelance** [comment]
Mesos 0.21.1

**Comment by drexin** [comment]
What does the Mesos UI show? Have the old tasks been killed there?

**Comment by neelance** [comment]
Yes, Mesos UI shows the killed tasks and even with `docker ps -a` I can see the old and the new container that just started. But both have the same image.

**Comment by drexin** [comment]
I will try to reproduce this, thanks for reporting.

**Comment by neelance** [comment]
Okay, I've found the problem, it was at our end: Our deployment script was creating empty version entries instead of not generating this JSON field at all: `"version":"0001-01-01T00:00:00Z"`

So it's not Marathon's fault. Sorry for bothering you. Maybe marathon should reject such invalid input, what do you think?

**Comment by drexin** [comment]
Well, that is a valid date string. You don't need to send a version, Marathon will generate one for you.

**Comment by neelance** [comment]
Yeah, as I said, this wasn't on purpose. The date string itself is valid, but I don't think that someone will ever want to use such a version. So just to help other users who might run into the same issue, Marathon could reject it. Also, what is the expected behavior when I provide a version string to `POST /v2/apps`? What is the use case? Just curious.

**Comment by drexin** [comment]
If you send it with a POST, it will be used as the version for the app. If you only send an id and the version with a PUT, Marathon will fetch that version and start a rollback to that version.

**Comment by drexin** [comment]
Closing this now, as the problem has been resolved.

**Comment by neelance** [comment]
Yes, closing is fine. But I'm still a bit confused about how the behavior of Marathon is defined for this case: We were accidentally sending the same version with each POST, but different configuration (e.g. docker image). How does Marathon behave in that case? Which configuration will be used?

**Comment by neelance** [comment]
Especially confusing to me was that the frontend (web UI) was showing the new configuration values, but the backend (docker task) was apparently still using the old configuration.

**Comment by drexin** [comment]
Hm, you're right. We should look into this.

**Comment by drexin** [comment]
#1149 should fix this. Instead of posting your app, you should use PUT if you want to update it.

**Comment by neelance** [comment]
How is #1149 related to this issue? Our case wasn't using service ports at all. So is using POST on an existing app even allowed?
