### ISSUE TITLE
Add tooltip on hover to progress bars

### ISSUE THREAD

**Issue by aatumanova** [mesosphere/marathon#1137]
Add a static tooltip (http://getbootstrap.com/javascript/#tooltips) on hover to explain the meaning of the progress colors

![image](https://cloud.githubusercontent.com/assets/1326416/5784596/666a6d48-9d82-11e4-90dc-d5dddabd4b8e.png)

**Comment by aquamatthias** [comment]
Comment from Anastasia:  Reference bootstrap's tooltip top aligned for design http://getbootstrap.com/javascript/#tooltips

**Comment by pierlo-upitup** [comment]
Reference: #1499

**Comment by pierlo-upitup** [comment]
Here is the solution in action:

![out](https://cloud.githubusercontent.com/assets/1078545/8695095/6a231b44-2ae3-11e5-8310-2afb7bec3930.gif)

**Comment by aatumanova** [comment]
Nicely done @pierlo-upitup!
