### ISSUE TITLE
Too many stale http event subscribers results in crash

### ISSUE THREAD

**Issue by nugend** [mesosphere/marathon#1144]
I'm filing this right now so I remember to file it at all. I'll see if I can include some stack traces later (I cleared out the issue and the built up bad state along with it), though they might not be useful since the trace in the logs doesn't *seem* to be the proximate cause of the crash. It might be an OOM or something.

Steps to reproduce: 

1. Create about 200 or so http event subscribers. Make sure the registered endpoints don't actually work. 
2. Watch marathon crash in about 1 minute.

I had been doing some testing for a new system using marathon and didn't think about the fact that event subscribers never expire. Eventually marathon would crash and I had to restart it constantly. Because there was a report of constant crashing with 0.7.5 #834 I figured I was seeing the same thing and that with 0.8.0 the problem would go away. I couldn't see the error in the logs initially because my sysadmin restricts me from access to syslog (weird, I know), so it took me a while to realize what the problem actually was.

I modified my code to delete the event subscribers on shutdown and marathon is working perfectly now.

**Comment by drexin** [comment]
Hi @nugend,

I tried to reproduce this on 0.8.0 with no success. Have you seen this on 0.8.0?

**Comment by drexin** [comment]
Closing this for now. Please let us know when you observe this again.

**Comment by nugend** [comment]
Sorry, I didn't realize 0.8.0 was final yet. I'll try to test it out with that when we can upgrade.
