### ISSUE TITLE
Add support for app "preferences" (low priority constraints)

### ISSUE THREAD

**Issue by kutchar** [mesosphere/marathon#1174]
Currently the unmet constraints for a given app would stop the app from deployment. It would be great to have the ability to have preferences, that are basically "best effort" constraints. For example, if I have a preference to run app App-1 on host Host-1, but host Host-1 is not available, Marathon will run app App-1 on another host, but if Host-1 is available, then marathon will run the app on it.

This would help in failover scenarios as well. For example, I could have 10 slaves and 10 apps that I need to run 1 app per slave. If one of the slaves dies, then marathon will launch that app on one of the live slaves making that slave to have 2 running apps. One the failed slave is back online, I would be able to restart the failed-over app and it will go back to the original slave.

**Comment by solarkennedy** [comment]
Marathon wouldn't really be able to support this unless it was implemented on Mesos? I don't think marathon should duplicate the scheduling logic and try to second-guess where mesos is deciding to run the tasks.

To put this in a different way it could be would you say "Mesos should kill tasks if it knows it can better satisfy the constraints if re-launched"?

**Comment by kutchar** [comment]
@solarkennedy I see. So this I should cross create this issue for Mesos?

> To put this in a different way it could be would you say "Mesos should kill tasks if it knows it can better satisfy the constraints if re-launched"?

I would say this is out of scope. The preferences would only be used for launching new tasks and not "rebalancing" current running tasks.

**Comment by solarkennedy** [comment]
I understand what you mean now. Yes, marathon could do.
What if, instead of adding a new concept, it was just a new parameter or variations on the constraints, like BEST_EFFORT_GROUP_BY or something like that?

Because in the end, you are describing the situation where you would rather have marathon satisfy the instance count requirement, at the expense of the constraint asked to be imposed?

**Comment by kutchar** [comment]
BEST_EFFORT_* works and looking at the code, is very backwards compatible. Alternatively we can add an optional parameter to each constraint, so we can have hostname:UNIQUE:<priority> where default priority (if omitted) could be "ENFORCE" which would state the current behavior and other value could be "PREFER" which would mean low priority. This could let us have more options in future if needed at the cost of a lil headache now.

BTW, I wasn't quite able to understand your comment "Marathon wouldn't really be able to support this unless it was implemented on Mesos?" Aren't these constraints implemented on the Marathon side?

https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/mesos/Constraints.scala

**Comment by solarkennedy** [comment]
You are totally right, I had a misconception on how constraints were implemented.

**Comment by bhack** [comment]
Any news on this?

**Comment by bhack** [comment]
Netflix Mesos Fenzo scheduler support soft costrains. Take a look at   https://github.com/Netflix/Fenzo/blob/master/README.md

**Comment by bhack** [comment]
Related to this https://github.com/mesosphere/marathon/issues/2063

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3350. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
