### ISSUE TITLE
Potential deadlock in MarathonSchedulerActor

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#1178]
In [MarathonSchedulerActor.performAsyncWithLockFor](https://github.com/mesosphere/marathon/blob/v0.8.0/src/main/scala/mesosphere/marathon/MarathonSchedulerActor.scala#L223) calls [Semaphore.acquire](http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/Semaphore.html#acquire()) when in `blocking` mode.  The `acquire` method blocks the entire thread.  It appears that depending on how concurrent acquisition is interleaved, deadlock could occur.

**Comment by drexin** [comment]
Yes, I also came across this, see: https://github.com/mesosphere/marathon/pull/988

I seem to have forgotten to create a follow up ticket. Thanks Connor!

**Comment by sttts** [comment]
What about this patch? If `Set[PathId]` is the way to go, this better shouldn't be merged last-minute.
