### ISSUE TITLE
Disallow apps the be overwritten with a POST

### ISSUE THREAD

**Issue by drexin** [mesosphere/marathon#1180]
If a user POSTs an app with an existing id, the request should be rejected with status code 409 - Conflict.

**Comment by bobrik** [comment]
I'd love to have one endpoint to do deploys, but `PUT /v2/apps` is not very consistent endpoint now.

```
web489 ~ # curl -H "Content-type: application/json" -X PUT http://web488:8080/v2/apps/he/he -d '{"ports": [19000], "mem": 16, "cmd": "sleep 60", "cpus": 0.1, "instances": 1}'
{"id":"/he/he","cmd":"sleep 60","args":null,"user":null,"env":{},"instances":1,"cpus":0.1,"mem":16.0,"disk":0.0,"executor":"","constraints":[],"uris":[],"storeUrls":[],"ports":[19000],"requirePorts":false,"backoffSeconds":1,"backoffFactor":1.15,"maxLaunchDelaySeconds":3600,"container":null,"healthChecks":[],"dependencies":[],"upgradeStrategy":{"minimumHealthCapacity":1.0,"maximumOverCapacity":1.0},"labels":{},"version":"2015-02-11T12:35:29.170Z"}
web489 ~ #
web489 ~ # curl -H "Content-type: application/json" -X PUT http://web488:8080/v2/apps/he/he -d '{"ports": [19000], "mem": 16, "cmd": "sleep 60", "cpus": 0.1, "instances": 1}'
{"version":"2015-02-11T12:35:31.837Z","deploymentId":"47179034-ecc3-48e0-84da-9ba28cdc0feb"}
```

**Comment by ConnorDoyle** [comment]
@bobrik how would you feel if we change the response when `PUT`ing an app for the first time to match the response when updating an existing app?  E.g. return the resulting deployment.

**Comment by bobrik** [comment]
@ConnorDoyle that would simplify my deployment playbook. Returning provided app + filled defaults doesn't really give much info anyway.

:+1: for changing reply for the first `PUT`.

**Comment by ConnorDoyle** [comment]
We would still want the HTTP status code to vary -- `201` on first PUT, `200` or `202` for valid updates thereafter.
