### ISSUE TITLE
Docs are not updated to 0.8.0

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#1181]
https://mesosphere.github.io/marathon/ features 0.7.5.

**Comment by drexin** [comment]
Thanks, changed. Should be visible shortly.

**Comment by bobrik** [comment]
@drexin rest api docs seems to be outdated too. I don't see `maxLaunchDelaySeconds`, for example.

**Comment by drexin** [comment]
updated

**Comment by bobrik** [comment]
:+1:
