### ISSUE TITLE
MESOS-2161 bug killing Marathon every few hours

### ISSUE THREAD

**Issue by alberts** [mesosphere/marathon#1187]
Hi

We're having an issue that looks exactly like MESOS-2161 killing our Marathon nodes every couple of hours, which seems to have caused the cluster to end up leaderless today.

Is MESOS-2161 a Marathon bug or a Mesos bug?

Regards

Albert

**Comment by drexin** [comment]
It's a Mesos bug. Unfortunately it is quite hard to reproduce, but we have a fix that we are currently testing.
