### ISSUE TITLE
args from app definition are ignored when scaling app from web ui

### ISSUE THREAD

**Issue by chaudum** [mesosphere/marathon#1194]
hi,
I've got an app definition `CrateUnicast.json` that looks like that:

```json
{
  "id": "crate-mesos-unicast",
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "crate/crate:0.46.5-2",
      "privileged": true,
      "network": "HOST",
      "parameters": []
    },
    "volumes": [
        {
          "containerPath": "/tmp",
          "hostPath": "/tmp",
          "mode": "RO"
        },
        {
          "containerPath": "/data",
          "hostPath": "/data/crate",
          "mode": "RW"
        }
    ]
  },
  "instances": 3,
  "cpus": 1,
  "mem": 2014,
  "uris": [],
  "cmd": "crate",
  "args": [
    "-Des.cluster.name=mesos-unicast",
    "-Des.zen.discovery.minimum_master_nodes=2"
  ],
  "env": {
    "CRATE_HOSTS": "mesos-slave-1:4300,mesos-slave-2:4300,mesos-slave-3:4300",
    "CRATE_HEAP_SIZE": "1024m"
  },
  "constraints": [
    [
      "hostname",
      "UNIQUE"
    ]
  ],
  "ports": []
}
```

When starting the app using marathon using curl the app 

```sh
curl -L -H "Content-Type: application/json" -X POST localhost:8080/v2/apps -d@CrateUnicast.json | jq .
```
stdout:

```json
{
  "id": "/crate-mesos-unicast",
  "cmd": "crate",
  "args": [
    "-Des.cluster.name=mesos-unicast",
    "-Des.zen.discovery.minimum_master_nodes=2"
  ],
  "user": null,
  "env": {
    "CRATE_HOSTS": "mesos-slave-1:4300,mesos-slave-2:4300,mesos-slave-3:4300",
    "CRATE_HEAP_SIZE": "1024m"
  },
  "instances": 3,
  "cpus": 1,
  "mem": 2014,
  "disk": 0,
  "executor": "",
  "constraints": [
    [
      "hostname",
      "UNIQUE"
    ]
  ],
  "uris": [],
  "storeUrls": [],
  "ports": [],
  "requirePorts": false,
  "backoffSeconds": 1,
  "backoffFactor": 1.15,
  "maxLaunchDelaySeconds": 3600,
  "container": {
    "type": "DOCKER",
    "volumes": [
      {
        "containerPath": "/tmp",
        "hostPath": "/tmp",
        "mode": "RO"
      },
      {
        "containerPath": "/data",
        "hostPath": "/data/crate",
        "mode": "RW"
      }
    ],
    "docker": {
      "image": "crate/crate:0.46.5-2",
      "network": "HOST",
      "portMappings": null,
      "privileged": true,
      "parameters": []
    }
  },
  "healthChecks": [],
  "dependencies": [],
  "upgradeStrategy": {
    "minimumHealthCapacity": 1,
    "maximumOverCapacity": 1
  },
  "labels": {},
  "version": "2015-02-12T12:51:21.831Z"
}
```

3 Crate instances startsup correctly using the arguments `-Des.cluster.name=mesos-unicast` and `-Des.zen.discovery.minimum_master_nodes=2` and therefore forming a cluster named `mesos-unicast`.

When killing a docker container manually on one of the slaves, the container is restarted correctly and the node is joining the cluster `mesos-unicast` again.

**However**, when using the web UI and scale the cluster by adding another node, the run command of the docker container does not obtain the arguments specified in the `CrateUnicast.json` file, meaning the the default Crate cluster name `crate` is used and the new node does not join the cluster `mesos-unicast`.

Seems like a bug, or am I doing something wrong?

Thanks!

```
[christian@mesos-master ~]$ sudo yum info mesos
Installed Packages
Name        : mesos
Arch        : x86_64
Version     : 0.21.1
Release     : 1.1.centos701406

[christian@mesos-master ~]$ sudo yum info marathon
Installed Packages
Name        : marathon
Arch        : x86_64
Version     : 0.8.0
Release     : 1.1.97.el7
```

inspection of the initial docker container: https://gist.github.com/chaudum/0d6fd7e12ee2b90b87d4
inspection of the scaled docker container: https://gist.github.com/chaudum/d2b4b3d6e5dcbbf78f46

**Comment by drexin** [comment]
This seems like an error in the validation logic. It is disallowed to supply `cmd` and `args`. I wonder why it seems to work the first time, though. I would suggest to include the args in the `cmd`. You could also set the entry point in your container to the command and pass in the cluster name and master nodes as env variables.

**Comment by chaudum** [comment]
thanks for pointing that out! I've overseen that in the docs.
putting the arguments into the `cmd` solved the problem :) however, I'll also think about updating the Dockerfile.

**Comment by drexin** [comment]
Actually it was a happy accident, because you discovered an actual bug. I created a new issue to track this here: https://github.com/mesosphere/marathon/issues/1195
