### ISSUE TITLE
Marathon crashes after getting restarted

### ISSUE THREAD

**Issue by more-free** [mesosphere/marathon#1196]
Hi, 

We are currently running Marathon 0.8.0 on Mesos 0.21 (with zookeeper).  At the beginning everything works well,  but sometimes Marathon crashes, and once it crashes and get restarted (we use systemd service to automatically restart Marathon),  it looks problematic and we could not access the UI anymore.  I paste the log below ( after restarting Marathon ).

Any clue about this issue ?  thanks very much ! 

18:13:17,393 INFO  [MarathonSchedulerService] Defeated (Leader Interface)
18:13:17,393 INFO  [MarathonSchedulerService] Defeat leadership
18:13:17,393 INFO  [MarathonSchedulerService] Stopping driver
18:13:17,396 INFO  [MarathonSchedulerService] Setting framework ID to 20141216-070346-1912885258-5050-32095-0000
18:13:17,400 ERROR [CandidateImpl] Current member ID member_0000116201 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,401 ERROR [CandidateImpl] Current member ID member_0000116959 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,402 ERROR [CandidateImpl] Current member ID member_0000115792 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,403 ERROR [CandidateImpl] Current member ID member_0000113574 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,404 ERROR [CandidateImpl] Current member ID member_0000116170 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,404 ERROR [CandidateImpl] Current member ID member_0000112561 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,405 ERROR [CandidateImpl] Current member ID member_0000114454 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,406 ERROR [CandidateImpl] Current member ID member_0000114284 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,407 ERROR [CandidateImpl] Current member ID member_0000114498 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,407 ERROR [CandidateImpl] Current member ID member_0000117153 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,408 ERROR [CandidateImpl] Current member ID member_0000114963 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,409 ERROR [CandidateImpl] Current member ID member_0000117400 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,410 ERROR [CandidateImpl] Current member ID member_0000115583 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,411 ERROR [CandidateImpl] Current member ID member_0000115197 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,411 ERROR [CandidateImpl] Current member ID member_0000116787 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,412 ERROR [CandidateImpl] Current member ID member_0000113660 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,413 ERROR [CandidateImpl] Current member ID member_0000113321 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,413 ERROR [CandidateImpl] Current member ID member_0000115560 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,414 ERROR [CandidateImpl] Current member ID member_0000117729 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,415 ERROR [CandidateImpl] Current member ID member_0000112526 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,416 ERROR [CandidateImpl] Current member ID member_0000117530 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,416 ERROR [CandidateImpl] Current member ID member_0000117129 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,417 ERROR [CandidateImpl] Current member ID member_0000113744 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,418 ERROR [CandidateImpl] Current member ID member_0000115832 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,419 ERROR [CandidateImpl] Current member ID member_0000114725 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,420 ERROR [CandidateImpl] Current member ID member_0000117750 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,420 ERROR [CandidateImpl] Current member ID member_0000112941 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,421 ERROR [CandidateImpl] Current member ID member_0000116102 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,422 ERROR [CandidateImpl] Current member ID member_0000116888 is not a candidate for leader, current voting: [member_0000117751]
18:13:17,423 INFO  [LeaderProxyFilter] Proxying request to leader at dev1-cm1.corp.att.com:8080
18:13:17,464 INFO  [LeaderProxyFilter] Proxying request to leader at dev1-cm1.corp.att.com:8080

**Comment by more-free** [comment]
any clue about this issue ?   It blocks us from deploying marathon into production...   thanks !

**Comment by drexin** [comment]
I haven't seen this before. What is your setup? Does this always happen, or just sonetimes?

**Comment by ConnorDoyle** [comment]
I think I've seen this symptom when there is trouble talking to ZK.  One thing that has helped in the past is to specify the zookeeper hosts in the connection string by IP instead of hostname.

**Comment by kamilchm** [comment]
We have this same problem with Marathon 0.10.1 and Mesos 0.22.1.

**Comment by aquamatthias** [comment]
This problem still exists. We track this ticket here: #2751 since a lot of functionality has changed and the logs are outdated.
Duplicate: #2751
