### ISSUE TITLE
Random IP publishing - Marathon Scheduler

### ISSUE THREAD

**Issue by michiroth** [mesosphere/marathon#1198]
Hi all,

running Mesos 0.21.1 (Master, Slave) with

/bin/mesos-master.sh --zk=zk://localhost:2181/mesos --quorum=1 --ip=127.0.0.1 --work_dir=./replicatedLog

./bin/mesos-slave.sh --master=zk://localhost:2181/mesos --ip=127.0.0.1

and Marathon 0.8.0

./bin/start --master zk://localhost:2181/mesos --zk zk://localhost:2181/marathon

on the same machine leads to the following master log entries:

Framework 20150213-152740-16777343-5050-57107-0000 (marathon) at scheduler-76ca63ca-0b41-4f5c-836e-137304488467@80.156.86.78:61854 already registered, resending acknowledgement

The Marathon framework registration to the master works but the response does not seem to work cause of wrong remote address "at scheduler-76ca63ca-0b41-4f5c-836e-137304488467@80.156.86.78:61854"

Setting LIBPROCESS_IP=127.0.0.1 fixes this issue an the remote scheduler address gets correctly bound.

See https://github.com/mesos/chronos/issues/193

Is this the intended behaviour for the marathon scheduler driver to modify the IP address?

Wouldn't it be more conform with Mesos and intuitive to introduce an IP flag?

Many greets
Michael

**Comment by drexin** [comment]
Unfortunately it is not possible to pass this setting into the creation of the `MesosSchedulerDriver`, so we can't add a flag for this.

**Comment by drexin** [comment]
I will add an issue to the Mesos issue tracker to add a parameter for this.

**Comment by drexin** [comment]
Mesos issue created here: https://issues.apache.org/jira/browse/MESOS-2376

**Comment by michiroth** [comment]
many thanks dario!

**Comment by samek** [comment]
michiroth, where exactly did you put the libprocessip ? 
I have exactly the same problem

**Comment by michiroth** [comment]
hi samek, set LIBPROCESS_IP as an environment variable.

**Comment by samek** [comment]
I've edited the marathon file and in the function run_jar   added 

 **export LIBPROCESS_IP=10.0.0.136**
 exec java "${vm_opts[@]}" -cp "$marathon_jar" mesosphere.marathon.Main "$@"

**Comment by stuart-warren** [comment]
I got around this (after wasting half a day...) by adding ``export LIBPROCESS_IP=10.blah.blah.blah`` to /etc/default/marathon rather than hacking the start script

**Comment by samek** [comment]
@stuart-warren thanks for "wasting" your day. I'll move it there then.

**Comment by kolloch** [comment]
@michiroth @aquamatthias @samek : Is that resolved with https://github.com/mesosphere/marathon/issues/1671? Otherwise please reopen. Thanks!

**Comment by michiroth** [comment]
@kolloch following short tests done on macbook locally using marathon 0.10.0, mesos 0.24.0:

machine hostname resolvable -> marathon binding to resolved address
machine hostname resolvable, LIBPROCESS_IP set in env -> marathon binding to resolved address
machine hostname not resolvable, LIBPROCESS_IP set in env -> marathon binding to LIBPROCESS_IP
machine hostname not resolvable, LIBPROCESS_IP not set in env -> marathon binding to nothing :)

What do you think about a sensible default (localhost/127.0.0.1) which should be used by marathon in the last case?

**Comment by kolloch** [comment]
Hi @michiroth, thank you for testing this! 

The fix I referenced went into the 0.11 RC. I can't decide what I like best for the last case. `localhost` would not work in any production environment but it would maybe make local testing easier in case your host name is not resolvable. I guess it makes sense. So if you want to create an issue for this, feel very free to do so.

**Comment by michiroth** [comment]
@kolloch opened #2273

**Comment by manlge** [comment]
You can use that command on CentOS7 with yum install -y marathon

**Comment by manlge** [comment]
You can use following command on CentOS 7 with yum -y install marathon

echo "LIBPROCESS_IP=<marathon_ip>" >> /etc/sysconfig/marathon
systemctl restart marathon

On other linux

env LIBPROCESS_IP=192.168.56.101 java -Djava.library.path=/usr/local/lib:/usr/lib:/usr/lib64 -Djava.util.logging.SimpleFormatter.format=%2$s%5$s%6$s%n -Xmx512m -cp /usr/bin/marathon mesosphere.marathon.Main --master zk://192.168.56.101:2181/mesos --zk zk://192.168.56.101:2181/marathon --hostname 192.168.56.101
