### ISSUE TITLE
Please add a search bar to the applications overview to filter the list of applications

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#1204]
It would be great to be able to filter the list of running applications.

The filter should look in available information in the app, but also tasks within the app for results. However, only display apps in the list (no tasks).

**Comment by drexin** [comment]
:+1:

**Comment by bobrik** [comment]
:+1: for this, it's easy to get lost when scrolling appears.

**Comment by ashenden** [comment]
Hey @mlunoe @aquamatthias -- I saw the design request come in for this, but I don't think we're going to have time to get to this quick enough for your needs.  If possible, could we talk through this at your computer and sketch a solution that would allow you to simply reuse some existing components without warranting a full design sprint?

cc/ @aatumanova

**Comment by aquamatthias** [comment]
1) There is no time pressure on that. It is more a thing that bugs me and should be improved.
2) Sure. I bet we can find a solution, that does not take a full design sprint.

**Comment by aatumanova** [comment]
Chatted with @mlunoe about a simple design solution for this, will follow up with visual!

**Comment by ashenden** [comment]
Cool.  Let's please not spend to much design energy on it.  A sketch or 5 min mockup should work.

**Comment by aatumanova** [comment]
@mlunoe @aquamatthias @ashenden 

Here's a stab at the visual design for this filter. I thought it would be a nice touch to "light up" the search icon to signal that the filter is active when the user types something in.

![image](https://cloud.githubusercontent.com/assets/1326416/6240088/177b7bb8-b6bf-11e4-8684-0704938bd860.png)

If there are no matches for their query, we can display a message and an option to clear the search:

![image](https://cloud.githubusercontent.com/assets/1326416/6240183/31c57a7c-b6c0-11e4-9e3d-3ee7a4c2991a.png)

Thoughts?

**Comment by aquamatthias** [comment]
Like it :+1: 
One thing: can we change "New App" and Search?
-you search for id which is on the same "column"
-the "New App" Button is used rarely

**Comment by mlunoe** [comment]
@aatumanova Could you add a link to the icon?
It looks great! I think you are right @aquamatthias, let's maybe have it on the left :)

**Comment by MikeMichel** [comment]
How about https://github.com/michaelbromley/angularUtils/tree/master/src/directives/pagination which i used in https://github.com/mmbash/mops.io . Works like a charm. 
Demo http://plnkr.co/edit/Wtkv71LIqUR4OhzhgpqL?p=preview

**Comment by sttts** [comment]
@aatumanova :+1:  for the design. I like it.

**Comment by mlunoe** [comment]
@MikeMichel We're not using angular in this project. However, it's not too big of a task to implement this in React.

**Comment by aatumanova** [comment]
@aquamatthias @mlunoe the filter on the left is a great idea, I like that it aligns with the ID names! 

For the icons, let's use ion-search and ion-close-circled from the http://ionicons.com iconfont set. Let's also use ion-plus for the plus icon inside of the "new app" button.

Here is an updated design incorporating feedback from @ashenden. Changes include...
- Removing the bar between the icon and the query
- Adding some text to the right of the filter that communicates number of apps that match the search query.

![image](https://cloud.githubusercontent.com/assets/1326416/6254481/cbcf87d2-b75d-11e4-99e7-64b724a7af3a.png)

**Comment by aquamatthias** [comment]
Get in touch with Anastasia to see the latest state of this topic.

**Comment by philipnrmn** [comment]
I got in touch with Anastasia, her feedback was as follows:

* search icon is a tad too small
* a subtle hover effect on the “x” would be nice
* if there are no results for the keyword filter, some written feedback in the apps list area would help for communication

I'd like to merge #90 and address these three issues in a separate PR, then close this issue.
