### ISSUE TITLE
Killing multiple tasks in the UI doesn't work

### ISSUE THREAD

**Issue by drexin** [mesosphere/marathon#1207]
It sends 1 request per task it wants to kill, but the first command locks the app and all subsequent request until the first is done will fail because the app is locked. This requires a new endpoint that takes a list of task ids and kills them all. An issue for such an endpoint is here: https://github.com/mesosphere/marathon/issues/1206

**Comment by pierlo-upitup** [comment]
See https://github.com/mesosphere/marathon/commit/4d692cf987d36d2abfc44943a5cf4f53bbcc1678

**Comment by pierlo-upitup** [comment]
Actually, it seems like the DELETE to /tasks has been replaced by a POST to /tasks/delete : https://github.com/mesosphere/marathon/blob/4d692cf987d36d2abfc44943a5cf4f53bbcc1678/changelogs/changelog_0.8.0-0.8.1.md#new-endpoint-delete-v2tasks
