### ISSUE TITLE
Constraint: Slave that can only run one kind of app

### ISSUE THREAD

**Issue by nemothekid** [mesosphere/marathon#1209]
Apologies if this is spelled out in the doc, I'm having trouble understanding how to get what I need done. I have 3 slaves with the attributes `group:dns`.  What I would like is for **only** apps with the specified `[group, CLUSTER, dns]` constraint to run on slaves with the `group:dns` and for other apps to be prevented from launching tasks on those slaves.

It seems mesos exposed this through roles in resources, but I can't seem to see how to set cpu/mem/disk resource as anything other than a scalar value.

**Comment by drexin** [comment]
You can only achieve this by adding an `UNLIKE` constraint to all other apps. So in your case it would be

```json
...
"constraints": ["group", "UNLIKE", "dns"]
...
```

**Comment by bobrik** [comment]
You probably could create separate mesos cluster with own marathon for dns nodes.

**Comment by drexin** [comment]
A separate cluster shouldn't even be necessary. Having a Marathon and Mesos slaves with a different role should be sufficient.

**Comment by drexin** [comment]
Also there is a Mesos ticket to allow a framework to register with multiple roles. Once that has been resolved, we will also add support for that to Marathon.

https://issues.apache.org/jira/browse/MESOS-1763
