### ISSUE TITLE
TabPanes should be pages

### ISSUE THREAD

**Issue by aldipower** [mesosphere/marathon#1214]
For clearness and better handling, especially in context of routing, TabPanes should be pages, that could be triggered by the route directly.

Convert the apps- and deployments-tabpane in Marathon to pages. 
https://github.com/mesosphere/marathon/blob/master/src/main/resources/assets/js/components/Marathon.jsx#L464

Also the tabpanes for the tasks and configuration in the AppPageComponent should sort of a subpage.
https://github.com/mesosphere/marathon/blob/master/src/main/resources/assets/js/components/AppPageComponent.jsx#L154

**Comment by aquamatthias** [comment]
@aldipower is that still open?

**Comment by aldipower** [comment]
Due to a lot of refactorings, especially by implementing the react router, this task is kind of obsolete and only would produce more code overhead instead of simplicity.
