### ISSUE TITLE
Changing args to cmd triggers validation error

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#1222]
I'm running master.

1. Create app with `container` and `args` set.
2. Decide that you want to pass `$PORT`, therefore you need to use `cmd`.
3. Remove `args`, add `cmd`. Deploy.

```
AppDefinition must either contain one of 'cmd' or 'args', and/or a 'container'.
```

It is possible to remove app and deploy with `cmd` and `container`.

cc @drexin, possibly happened in #1201.

**Comment by drexin** [comment]
I think before https://github.com/mesosphere/marathon/pull/1201 it worked by accident. We have to provide a way to unset fields. `PUT` should override the whole app, which it currently doesn't and the behaviour it currently has needs to be exposed by a new `PATCH` endpoint.

**Comment by aquamatthias** [comment]
The problem is, that you can not express unsetting values the way we provide the API.
See #1418
