### ISSUE TITLE
Change `TaskIdUtil.appId` to return `Option[PathId]` instead of throwing `MatchError`

### ISSUE THREAD

**Issue by drexin** [mesosphere/marathon#1225]

**Comment by hekaldama** [comment]
@drexin, I am guessing this is for the .appId with signature of String only right? Not the TaskId one?

**Comment by drexin** [comment]
@hekaldama The one calls the other, so it has to be both.

**Comment by hekaldama** [comment]
@drexin I wonder if this should just actually do what https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/api/v2/TasksResource.scala#L94-L99 is doing so that all callers get the benefit of BadRequestException upon calling with bad task / app id?

**Comment by aquamatthias** [comment]
No TaskIdUtil any longer.
