### ISSUE TITLE
GET Tasks API should return protocol of ports

### ISSUE THREAD

**Issue by vishramachandran** [mesosphere/marathon#1229]
GET tasks API returns the service port, host and host port. However, it does not return the protocol.

haproxy-marathon-bridge incorrectly assumes that all exposed ports are TCP ports.
There may be UDP exposed ports too. The tasks api should expose the protocol and the marathon bridge should consume this information to configure the UDP load balancer.

**Comment by vishramachandran** [comment]
It would also help if the tasks API also returned the tags (key/value pairs) of the associated app. This is a recent feature delivered by https://github.com/mesosphere/marathon/issues/599

**Comment by aquamatthias** [comment]
@vishramachandran do you think it is a problem, that haproxy ports are configured as TCP ports and not HTTP ports?

**Comment by bobrik** [comment]
> This is what happens when you switch from load balancing on HTTP level to keep-alive tcp connections to backends [link](https://twitter.com/ibobrik/status/599187243354427392)
> ![yes](https://pbs.twimg.com/media/CFC9n1eWgAARZ0N.png)

Roughly 5krps.

**Comment by vishramachandran** [comment]
@aquamatthias my problem was more that the bridge configurer script would not be able to set up UDP based balancers. I am not the expert at HTTP vs TCP load balancing yet, so I'd rather not comment.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4675. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
