### ISSUE TITLE
Improved Error Messaging Around Incorrect JSON

### ISSUE THREAD

**Issue by kensipe** [mesosphere/marathon#1235]
An error with JSON submitted to Marathon should result in a clear indication of the failure.  In particular there should be no indication of the underlying technology like Scala or the JSON parser.

The latest example of this was a change made for Marathon 0.8 which introduced a JSON change for parameters to Docker.   The result of a request from a JSON using the previous format is:  
`{"message":"Can not deserialize instance of scala.collection.immutable.Seq out of START_OBJECT token\n at [Source: org.eclipse.jetty.server.HttpInput@62f8115e; line: 1, column: 2291]"}`

This issue may be related to [#1185](https://github.com/mesosphere/marathon/issues/1185)

any additional thoughts @air?

**Comment by air** [comment]
@kensipe can you add in the specific JSON and REST endpoint that caused the error so we can reproduce.

A good response would be `JSON is invalid against schema http://mesosphere.com/schema/marathon-0.8.0.json: expected 'list' but received 'value'.`

The user's action would be to self-check their JSON using a validation tool.

#1185 is important as it shows one way to implement using a schema.

**Comment by aquamatthias** [comment]
+ consider json schema check
+ add rendered message and args from JsResultException

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2732. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
