### ISSUE TITLE
Restart an app on non marathon leader not work 

### ISSUE THREAD

**Issue by koboltmarky** [mesosphere/marathon#1239]
Hi,

restart an app through the  /v2/apps/{appId}/restart endpoint only works on the marathon leader. If you restart an app on a non marathon leader
you get an {"message":"Unsupported Media Type"} error.

Greets
Marc

**Comment by drexin** [comment]
This should of course be fixed, but as a temporary solution you could try setting "Content-Type: application/json" on your request.

**Comment by koboltmarky** [comment]
The solution works, thx.
