### ISSUE TITLE
Update sbt build to export env variables when ran from teamcity

### ISSUE THREAD

**Issue by BenWhitehead** [mesosphere/marathon#1244]
- SBT_PROJECT_VERSION

**Comment by kolloch** [comment]
I do not understand this issue. What means exporting these environment variables and why do we want to do that?

**Comment by BenWhitehead** [comment]
To allow project version in sbt projects to be exposed to other tools (s3 scripts, packaging etc) vi an environment variable rather than having to parse files message can be sent to TeamCity that will then create environment variables for these other tools.

A code snippet of how we've accomplished this in other projects is:
```scala
  sys.env.get("TEAMCITY_VERSION") match {
    case None => // no-op
    case Some(teamcityVersion) =>
      // add some info into the teamcity build context so that they can be used
      // by later steps
      reportParameter("SCALA_VERSION", projectScalaVersion)
      reportParameter("PROJECT_VERSION", projectVersion)
  }

  def reportParameter(key: String, value: String): Unit = {
    println(s"##teamcity[setParameter name='env.SBT_$key' value='$value']")
    println(s"##teamcity[setParameter name='system.sbt.$key' value='$value']")
  }
```

However the Marathon build doesn't have a variable `projectVersion` or `projectScalaVersion`, so this code needs to be adapted to read the version information in the way marathon has expressed it.

**Comment by jasongilanfarr** [comment]
Only using velocity now. We should probably delete the team city stuff from the build.sbt file.
