### ISSUE TITLE
Add --no-logger functionality so logging can be optional

### ISSUE THREAD

**Issue by sielaq** [mesosphere/marathon#1246]
Hello,

I would like to add this feature,
https://github.com/mesosphere/marathon/pull/1245

so logger can be optionally disabled with ```--no-logger``` 
it is needed when you use supervisord and stdout/sterr for logging.

**Comment by drexin** [comment]
Closed by https://github.com/mesosphere/marathon/commit/493f3ef054898adcf144eaca88b7b4875d232546
