### ISSUE TITLE
NPE during group update when file is empty

### ISSUE THREAD

**Issue by sttts** [mesosphere/marathon#1247]
```
curl -v -D /dev/stderr -s -f -o response -H 'Content-Type: application/json' -X PUT srv001:5080/v2/groups/teamwire-prod -d@backend.json
```

```
Feb 26 13:17:48 srv003 marathon[23355]: java.lang.NullPointerException
Feb 26 13:17:48 srv003 marathon[23355]: #011at mesosphere.marathon.api.ModelValidation$class.checkGroupUpdate(ModelValidation.scala:38)
Feb 26 13:17:48 srv003 marathon[23355]: #011at mesosphere.marathon.api.v2.GroupsResource.checkGroupUpdate(GroupsResource.scala:18)
Feb 26 13:17:48 srv003 marathon[23355]: #011at mesosphere.marathon.api.v2.GroupsResource.update(GroupsResource.scala:115)
```

Group definition is available on request.

**Comment by sttts** [comment]
Of course with a 500 http status.

**Comment by drexin** [comment]
This is very surprising as both values are `Option`s. I have not been able to reproduce this. Could you try to create a minimum example that fails?

**Comment by sttts** [comment]
saw it the first time in production. but right now it's reproducible. Let me see what I can do.

**Comment by sttts** [comment]
I didn't mention, it's the rc1 plus my http100 patch.

**Comment by sttts** [comment]
Analysed the error. In fact in the `update` handler the `update` parameter was `null` because an empty file was given by the caller. An appropriate 4xx http code should be returned in such a case, not a 500.

**Comment by drexin** [comment]
There seem to be more endpoints affected by this. I created a new ticket to track this: https://github.com/mesosphere/marathon/issues/1259
