### ISSUE TITLE
Total resource usage in UI

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#1251]
Apps with 128mb RAM and 1000 instances consume more resources than apps with 2048mb RAM and 1 instance. However, in UI when sorting by ram 2048mb app is on top of the list. Showing total resource usage in UI could help with finding apps that require resource usage optimizations most.

Not sure how to do that, though. Maybe "show total resource usage" switch or something.

**Comment by pierlo-upitup** [comment]
Could you take a look at this @ashenden @aatumanova @air

**Comment by ashenden** [comment]
Agree.  I'd imagine that on the Apps Collection View we adjust to reflect total as opposed to instance usage.

**Comment by air** [comment]
There are a number of possible aggregate numbers that the user might be interested in: total RAM allocated, total CPU shares allocated, total disk MB allocated. If we're solving for one we should solve for them all (they're equally useful).

**Comment by bobrik** [comment]
@air I agree. Currently only RAM and CPU are displayed, though.
