### ISSUE TITLE
Reject null bodies in REST API

### ISSUE THREAD

**Issue by drexin** [mesosphere/marathon#1259]
When sending an empty body to an endpoint, instead of throwing a parse exception, Jackson returns `null` which breaks some of our endpoints.

**Comment by hekaldama** [comment]
@drexin, do you think a part of this solution would be that Jackson (or some other selected JSON library) should raise on parsing empty body? Wondering if there is another library to use that would handle this better, or if we can contribute to Jackson.

**Comment by drexin** [comment]
@hekaldama We started moving over to play-json wich will error on null bodies.

**Comment by hekaldama** [comment]
@drexin cool. I was trying to grab this cause it is labeled "good first bug". Is someone already working on it then?
