### ISSUE TITLE
Gui off by 1 error in paging container instances

### ISSUE THREAD

**Issue by stuart-warren** [mesosphere/marathon#1265]
Marathon 0.8.0 (Didn't see a closed issue)
If you scale to 8 instances, 7 are displayed in the list on 1 page
If you scale to 9 instances, 7 are displayed on first page, 2 more are on page 2

![marathonpaging](https://cloud.githubusercontent.com/assets/3208285/6470400/62ff5150-c1db-11e4-9dc2-76700f417189.png)

**Comment by adamtulinius** [comment]
This has been fixed in 0.8.2
![screen shot 2015-05-08 at 23 27 47](https://cloud.githubusercontent.com/assets/749381/7545975/f9b0aab8-f5d9-11e4-8a09-fd48ab8af972.png)
