### ISSUE TITLE
Start health checks when app has been started

### ISSUE THREAD

**Issue by drexin** [mesosphere/marathon#1276]
Currently it seems like Marathon only starts health checks when it does the periodic reconciliation. It should start the health checks right after receiving the `TASK_RUNNING` update from Mesos to make deployments faster.

**Comment by kolloch** [comment]
Is that a potential duplicate of #901 or is that another code path.

mesosphere.marathon.upgrade.DeploymentActor#performStep calls mesosphere.marathon.health.HealthCheckManager#addAllFor for every step

**Comment by kolloch** [comment]
Your proposal (starting the health check) on receiving the `TASK_RUNNING` update might or might not be better if I understand it correctly. I assume that we get the `TASK_RUNNING` update after process startup. That doesn't necessarily mean that the application is ready to reply to health check requests just yet.

**Comment by sttts** [comment]
I doubt the bug report is valid. As @kolloch writes, heath checks are created when the upgrade step starts. The health check actor though only triggers the actual health check workers for those tasks which are in status TASK_RUNNING. 

@drexin: can you give some details about what you are seeing? This was worked for sure in 0.8.1 and there should even be a number of tests I think.

**Comment by drexin** [comment]
Okay, I got bitten by the high default interval. Thanks!
