### ISSUE TITLE
Listing all tasks of an app is very slow with large numbers of tasks

### ISSUE THREAD

**Issue by drexin** [mesosphere/marathon#1278]
While fixing this issue, we should add a `limit` and an `offset` parameter to only load the tasks we want to show.

**Comment by quamilek** [comment]
Hey, if that resolves the problem of the raised ``TimeoutException`` in:
https://github.com/mesosphere/marathon/blob/v0.8.0/src/main/scala/mesosphere/marathon/MarathonSchedulerService.scala#L120
Currently i have a 1k children in `/marathon/state` on `Zookeeper`, an this exception has raised when i refresh marathon web gui and server HTTP status was `504`.
```
WARN  (mesosphere.marathon.api.MarathonExceptionMapper:28)
Mar 19 09:51:51 mesos-master1.local marathon[28186]: java.util.concurrent.TimeoutException: 
Can not retrieve the list of running deployments in time
```
```
INFO 10.74.226.170 - marathon [19/Mar/2015:08:51:46 +0000] "GET /v2/apps HTTP/1.1" 504 70
```

**Comment by drexin** [comment]
1. Hard to tell, from the message it seems unrelated, but it could be just a wrong message. In general we are trying to make all the calls faster with large numbers of tasks.

2. It will never be fully removed, but whenever an app, task or group is deleted, all its state will also be removed.
