### ISSUE TITLE
Killing not possible after Master Failure

### ISSUE THREAD

**Issue by marcelalburg** [mesosphere/marathon#1279]
Hey,

i running an Mesos 0.21.1 (3 Servers) / Marathon 0.8.0 (3 Servers) Cluster (the 3 Servers are the same and the slave nodes too).

Marathon ist started with: zk = zk://.../marathon and master = zk://../mesos and everything works fine.

If i reboot the mesos masternode, a new master is choosen and current jobs are working (but of yourse not this one from the rebooted node). In my case, marathon don't recognize the outage so fast (maybe, because i don't have an health check) and the old mesos master is comming up again. 

So, the error is, marathon thinks everything is fine, but one of my tasks isn't running. and when i try to kill this task, the new mesos master is loggging:

```
I0310 01:03:32.719782  3385 master.cpp:2716] Asked to kill task elasticsearch.5a2b3eca-c6ae-11e4-8408-56847afe9799 of framework 20150309-234322-1694542016-5050-2254-0000
W0310 01:03:32.719844  3385 master.cpp:2794] Cannot kill task elasticsearch.5a2b3eca-c6ae-11e4-8408-56847afe9799 of framework 20150309-234322-1694542016-5050-2254-0000 (marathon) at scheduler-8937dc48-fda2-4e55-9d39-e5c791ee2a00@192.168.0.103:55646 because it cannot be found; cannot send TASK_LOST since a non-strict registry is in use
```

in my case i started a docker with following configuration:

```
{
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "elasticsearch:1.4.4"
    },
    "portMappings": [
        {
            "containerPort": 9200,
            "hostPort": 0,
            "servicePort": 9200,
            "protocol": "tcp"
        },
        {
            "containerPort": 9300,
            "hostPort": 0,
            "servicePort": 9300,
            "protocol": "tcp"
        }
    ]
  },
  "id": "elasticsearch",
  "instances": 1,
  "cpus": 0.5,
  "mem": 412,
  "uris": []
}
```

after that, it's not possible to kill or restart this service, because i can't stop it and after a redeploy, marathon thinks the old job is currently running.

how can i kill this task correctly and how can i make it possible, that marathon detects short network outages ?

maybe a health check is a solution, but i've some docker container, wich one are not possible to check via an health check.

I found the same question at: http://stackoverflow.com/questions/28291116/unable-to-remove-task-from-marathon

Thanks
Marcel

**Comment by drexin** [comment]
Hi Marcel,

usually you don't want the Mesos master and slave to run on the same machine. Anyway, I think that the problem here is, that the slave could not cleanly unregister with the master, because it was running on the same machine and may have been killed before the slave could unregister and then the slave has been killed before a new master has been elected. If that's true, the newly elected master will wait for the slave to re-register for 10 minutes by default before sending out a TASK_LOST. Could you try the same with manually shutting down the slave first?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3345. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
