### ISSUE TITLE
ACL / Role Based Access Control support?

### ISSUE THREAD

**Issue by SEJeff** [mesosphere/marathon#128]
I know marathon supports HTTP Basic auth support, but it would be nice if there was a flexible RBAC / ACL system.

I'd like to use Marathon in a multi-tenant environment where each "tenant" (team at our company) is capable of managing jobs specific to their team. There are a few superuser groups who can see/manage everything, and a few "sub-admin" teams that can manage all jobs for a certain other group type, but in general, each team owns their own jobs.

Currently the group mapping is all stored in LDAP and cleanly maps from user --> group. This would be a fantastic addition to an already quite fantastic tool.

**Comment by bsideup** [comment]
:+1:

**Comment by h0tbird** [comment]
+1

**Comment by cfz** [comment]
+1

**Comment by jlrigau** [comment]
:+1:

**Comment by ankurpshah** [comment]
:+1:

**Comment by mlowicki** [comment]
Seems that discussion died at some point. Very long time ago it was mentioned that LDAP is on the roadmap but no official movements since then.

@guenter @gkleiman any news? I guess many people (including me) would be willing to help but would be good how the situation looks now.

**Comment by markrey** [comment]
+1

**Comment by gkleiman** [comment]
@mlowicki Marathon now supports plugins for authorization and authentication. You can write one that provdes LDAP integration.

Enterprise DC/OS comes with LDAP integration out of the box.

**Comment by SEJeff** [comment]
@gkleiman Thanks! Is that LDAP plugin on the roadmap to ever make it into the OSS DC/OS?

**Comment by janisz** [comment]
@mlowicki @SEJeff when plugin interface comes out I wrote simple plugin using shiro https://github.com/janisz/marathon-shiro-authentication-plugin It authenticate users and authorize if their groups matches the application path. 

> Shiro provides out-of-the-box realms for popular data sources like LDAP, Active Directory, Kerboros, and JDBC. If needed, you can also create your own realms to support specific functionality not included in the basic realms.

It's probably easiest way to set up LDAP with Marathon. Code is stale and needs update but core concept is pretty simple.

**Comment by jasongilanfarr** [comment]
As there are plugins available to do this, closing out.
