### ISSUE TITLE
Use API to only fetch displayed tasks on each page in the task list

### ISSUE THREAD

**Issue by drexin** [mesosphere/marathon#1286]

**Comment by drexin** [comment]
Moved to 0.9.0. Need to add stable paging in the backend first.

**Comment by aldipower** [comment]
Update: No update. This still needs paging, which we don't have for now. :)

**Comment by kolloch** [comment]
@aquamatthias made a different suggestion: For a certain number of tasks, do not display the list by default but provide a button "show tasks".

Providing (consistent) paging is difficult in the current code but that will hopefully change soon.

But we can also question if it is important that the user can page through a list of many tasks...

**Comment by aquamatthias** [comment]
@kolloch the /v2/apps/<appId> endpoint is used for that. It gives always __all__ tasks/health status etc.
Think we need some flags to be able to filter the needed data.

**Comment by kolloch** [comment]
you mean `/v2/apps/<app id>`, correct? `/v2/apps` does not include tasks by default, does it?

Yes, we need to provide additional functionality here.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3249. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
