### ISSUE TITLE
Health check failed when using docker HOST network mode

### ISSUE THREAD

**Issue by CptJason** [mesosphere/marathon#1297]
Hi, all

My application definition json files is like bellow:

{
  "container": {
    "type": "DOCKER",
    "docker": {
      "network": "HOST",
      "image": "nginx"
    }
  },
  "id": "nginx",
  "instances": 1,
  "ports": [80],
  "cpus": 0.25,
  "mem": 64,
  "uris": [],
  "healthChecks": [
        {
            "protocol": "HTTP",
            "path": "/",
            "gracePeriodSeconds": 3,
            "intervalSeconds": 10,
            "portIndex": 0,
            "timeoutSeconds": 10,
            "maxConsecutiveFailures": 3
        }
    ]
}

When I launched the application, the app failed because of health check fail: 

curl http://localhost:8080/v2/tasks |python -m json.tool

{
    "tasks": [
        {
            "appId": "/nginx",
            "healthCheckResults": [
                {
                    "alive": false,
                    "consecutiveFailures": 1,
                    "firstSuccess": null,
                    "lastFailure": "2015-03-13T10:47:17.888Z",
                    "lastFailureCause": "ConnectionAttemptFailedException: Connection attempt to 172.16.12.22:31314 failed",
                    "lastSuccess": null,
                    "taskId": "nginx.4bfdfe92-c96e-11e4-ba33-fa163ec34ff5"
                }
            ],
            "host": "172.16.12.22",
            "id": "nginx.4bfdfe92-c96e-11e4-ba33-fa163ec34ff5",
            "ports": [
                31314
            ],
            "servicePorts": [
                80
            ],
            "stagedAt": "2015-03-13T10:47:08.649Z",
            "startedAt": "2015-03-13T10:47:09.019Z",
            "version": "2015-03-13T10:47:07.792Z"
        }
    ]
}

The port 31314 does not exist on slave, the right host port should be 80, how to deal with this problem?

Many thanks!

**Comment by drexin** [comment]
If your app needs a specific port, please use BRIDGE mode. The `ports` array in the app definition is to define service ports. The port your application gets will be picked from the Mesos offer. We know that ports currently can be confusing and we are planning to improve that in a future release.

**Comment by aquamatthias** [comment]
Please reopen, if this problem can not be solved with the advise from drexin.

**Comment by SevenCheung** [comment]
I really also need to know how to make health check of HOST network mode successful?Who can solve this problem?
Thanks

**Comment by tdna** [comment]
@SevenCheung 
One way to start your application on the port mesos gives you. You can achieve that with the $PORT0 environmental variable. In this way your healtheck config could be:
`{
    "cmd": "yourservice -p $PORT0",
    "healthChecks": [
      {
        "protocol": "TCP"
      }
    ]
}`

The other way you need to specify mesos role with specific resources in which you set the wanted port.
