### ISSUE TITLE
Marathon Crashes continuously

### ISSUE THREAD

**Issue by mv012004** [mesosphere/marathon#1299]
Marathon v0.7.6

My marathon talks to mesos through zookeeper, and it keeps on crashing continuously, all i see is the following dump. Can someone help.

Mar 13 13:33:19 test03260 marathon[24032]: [2015-03-13 13:33:19,306] INFO Registering in Zookeeper with hostname:test03260.kdc.test.com (mesosphere.marathon.MarathonModule:125)
Mar 13 13:33:19 test03260 marathon[24032]: [2015-03-13 13:33:19,768] INFO Setting framework ID to 20141209-170811-3259247114-5050-12517-0000 (mesosphere.marathon.MarathonSchedulerService:69)
Mar 13 13:33:19 test03260 marathon[24032]: WARNING: Logging before InitGoogleLogging() is written to STDERR
Mar 13 13:33:19 test03260 marathon[24032]: F0313 13:33:19.770697 24093 org_apache_mesos_state_AbstractState.cpp:696] CHECK_READY(*future): is PENDING 
Mar 13 13:33:19 test03260 marathon[24032]: *** Check failure stack trace: ***
Mar 13 13:33:19 test03260 marathon[24032]: JVMDUMP039I Processing dump event "abort", detail "" at 2015/03/13 13:33:19 - please wait.
Mar 13 13:33:19 test03260 IBM Java[24032]: JVMDUMP039I Processing dump event "abort", detail "" at 2015/03/13 13:33:19 - please wait.
Mar 13 13:33:19 test03260 marathon[24032]: JVMDUMP032I JVM requested System dump using '//core.20150313.133319.24032.0001.dmp' in response to an event
Mar 13 13:33:19 test03260 IBM Java[24032]: JVMDUMP032I JVM requested System dump using '//core.20150313.133319.24032.0001.dmp' in response to an event
Mar 13 13:33:19 test03260 marathon[24032]: [2015-03-13 13:33:19,897] WARN No SSL support configured. (mesosphere.marathon.Main$$anon$1:62)
Mar 13 13:33:19 test03260 marathon[24032]: [2015-03-13 13:33:19,905] INFO Starting up (mesosphere.marathon.MarathonSchedulerService:135)
Mar 13 13:33:19 test03260 marathon[24032]: [2015-03-13 13:33:19,906] INFO Beginning run (mesosphere.marathon.MarathonSchedulerService:140)
Mar 13 13:33:19 test03260 marathon[24032]: [2015-03-13 13:33:19,907] INFO Offering leadership (mesosphere.marathon.MarathonSchedulerService:288)
Mar 13 13:33:19 test03260 marathon[24032]: [2015-03-13 13:33:19,907] INFO Using HA and therefore offering leadership (mesosphere.marathon.MarathonSchedulerService:295)
Mar 13 13:33:19 test03260 marathon[24032]: [2015-03-13 13:33:19,907] INFO jetty-8.y.z-SNAPSHOT (org.eclipse.jetty.server.Server:272)
Mar 13 13:33:19 test03260 marathon[24032]: [2015-03-13 13:33:19,938] INFO Set group member ID to member_0000001069 (com.twitter.common.zookeeper.Group:426)
Mar 13 13:33:19 test03260 marathon[24032]: [2015-03-13 13:33:19,988] INFO Candidate /marathon/leader/member_0000001069 waiting for the next leader election, current voting: [member_0000001069, member_0000001068, member_0000001065] (com.twitter.common.zookeeper.CandidateImpl:165)
Mar 13 13:33:20 test03260 marathon[24032]: [2015-03-13 13:33:20,168] INFO Registering com.codahale.metrics.jersey.InstrumentedResourceMethodDispatchAdapter as a provider class (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:113)
Mar 13 13:33:20 test03260 marathon[24032]: [2015-03-13 13:33:20,173] INFO Registering com.fasterxml.jackson.jaxrs.json.JacksonJsonProvider as a provider class (com.sun

**Comment by drexin** [comment]
Could you please upgrade to 0.8.1 and see if the error persists?

**Comment by deric** [comment]
I've noticed that Marathon (`v0.8.0rc1`) was frequently crashing while running on Java 8 (Oracle 1.8.0_40-b25) while instance running on Java 7 (openjdk 7u75-2.5.4-1~deb7u1) was "fine" (JVM not crashing). Does anyone has similar experience? 

Anyway, @drexin is Java 8 supported? I've just updated quorum to  `v0.8.1` I'll let you know if the problem persists.

**Comment by drexin** [comment]
There's a bug in the Mesos JNI bindings that make it not play nice with Java 8, but that will be fixed in 0.22 final. There's another bug in the state abstraction that we are currently investigating and hope to fix soon.

**Comment by mv012004** [comment]
I dont understand why it dumps these files under "/" and these are huge files. I hope there is a fix for the crashes, has anyone else faced this issue ?

**Comment by kolloch** [comment]
This has been hopefully solved by running Marathon 0.8.2-RC3 with Mesos 0.22.1 (Master+Libraries). Please reopen if the problem persists.
