### ISSUE TITLE
marathon 0.8.1 event_subscriber not working

### ISSUE THREAD

**Issue by stuart-warren** [mesosphere/marathon#1302]
Hi,
I've created a config file ``/etc/marathon/conf/event_subscriber``, and the param appears to be appended to the running service after a restart, theres even logs written, yet the endpoint does not seem to work for me

```
vagrant@master1:~$ cat /etc/marathon/conf/event_subscriber
http_callback
vagrant@master1:~$ ps -ef | grep event_subscriber
root      6499     1  3 02:41 ?        00:00:10 java -Djava.library.path=/usr/local/lib:/usr/lib:/usr/lib64 -Djava.util.logging.SimpleFormatter.format=%2$s%5$s%6$s%n -Xmx512m -cp /usr/bin/marathon mesosphere.marathon.Main --event_subscriber http_callback --zk zk://172.31.1.11:2181/marathon --master zk://172.31.1.11:2181/mesos
vagrant   6589  6470  0 02:46 pts/4    00:00:00 grep --color=auto event_subscriber
vagrant@master1:~$ sudo grep HttpCallbackEventSubscriber /var/log/syslog
Mar 16 02:26:47 master1 marathon[6120]: [2015-03-16 02:26:47,805] INFO Using HttpCallbackEventSubscriber for eventnotification (mesosphere.marathon.Main$:67)
Mar 16 02:28:26 master1 marathon[6208]: [2015-03-16 02:28:26,858] INFO Using HttpCallbackEventSubscriber for eventnotification (mesosphere.marathon.Main$:67)
Mar 16 02:39:42 master1 marathon[6377]: [2015-03-16 02:39:42,682] INFO Using HttpCallbackEventSubscriber for eventnotification (mesosphere.marathon.Main$:67)
Mar 16 02:41:26 master1 marathon[6499]: [2015-03-16 02:41:26,588] INFO Using HttpCallbackEventSubscriber for eventnotification (mesosphere.marathon.Main$:67)
vagrant@master1:~$ curl http://localhost:8080/v2/eventSubscriptions
{"message":"http event callback system is not running on this Marathon instance. Please re-start this instance with \"--event_subscriber http_callback\"."}
vagrant@master1:~$ curl http://localhost:8080/v2/info
{"name":"marathon","http_config":{"assets_path":null,"http_port":8080,"https_port":8443},"frameworkId":"20150314-095705-184623020-5050-9511-0000","leader":"slave1:8080","event_subscriber":null,"marathon_config":{"local_port_max":20000,"local_port_min":10000,"hostname":"slave1","master":"zk://172.31.1.11:2181/mesos","reconciliation_interval":300000,"mesos_role":null,"task_launch_timeout":300000,"reconciliation_initial_delay":15000,"ha":true,"failover_timeout":604800,"checkpoint":true,"webui_url":null,"executor":"//cmd","marathon_store_timeout":2000,"mesos_user":"root"},"version":"0.8.1","zookeeper_config":{"zk_path":"/marathon","zk":"zk://172.31.1.11:2181/marathon","zk_timeout":10,"zk_hosts":"172.31.1.11:2181","zk_future_timeout":{"duration":10}},"elected":true}
```

I'm also confused by ``"leader":"slave1:8080"``
It's clearly running on a server called master1
slave1 is at 172.31.2.11

**Comment by felixb** [comment]
I updated marathon to 0.8.1 yesterday. EventSubscriptions is working for me.

**Comment by stuart-warren** [comment]
@felixb thanks for checking.
Are you able to post you http://localhost:8080/v2/info info so I can see what settings you are using?

**Comment by felixb** [comment]
Here is the info from our dev marathon instance:

    {
      "name": "marathon",
      "http_config": {
        "assets_path": null,
        "http_port": 8080,
        "https_port": 8443
      },
      "frameworkId": "20150319-150359-2018883594-17100-27355-0001",
      "leader": "mesos-dev-269510:8080",
      "event_subscriber": {
        "type": "http_callback",
        "http_endpoints": [
          "http://127.0.0.1:8083/marathon/event"
        ]
      },
      "marathon_config": {
        "local_port_max": 20000,
        "local_port_min": 10000,
        "hostname": "mesos-dev-269510",
        "master": "zk://zoo-dev-269475.....:2181/infrastructure-test/mesos",
        "reconciliation_interval": 75000,
        "mesos_role": null,
        "task_launch_timeout": 300000,
        "reconciliation_initial_delay": 15000,
        "ha": true,
        "failover_timeout": 75,
        "checkpoint": true,
        "webui_url": null,
        "executor": "//cmd",
        "marathon_store_timeout": 2000,
        "mesos_user": "root"
      },
      "version": "0.8.1",
      "zookeeper_config": {
      "zk_path": "/infrastructure-test/marathon",
      "zk": "zk://zoo-dev-269475.....:2181/infrastructure-test/marathon",
      "zk_timeout": 10,
      "zk_hosts": "zoo-dev-269475.....:2181",
      "zk_future_timeout": {
          "duration": 10
        }
      },
      "elected": true
    }

**Comment by hyper-carrot** [comment]
+1, My marathon's info is 

```
{  
   "name":"marathon",
   "http_config":{  
      "assets_path":null,
      "http_port":8080,
      "https_port":8443
   },
   "frameworkId":"20150319-231746-33794240-5050-968-0000",
   "leader":"192.168.4.5:8080",
   "event_subscriber":{  
      "type":"http_callback",
      "http_endpoints":null
   },
   "marathon_config":{  
      "local_port_max":20000,
      "local_port_min":10000,
      "hostname":"192.168.4.5",
      "master":"zk://192.168.4.6:2181/my-marathon",
      "reconciliation_interval":300000,
      "mesos_role":null,
      "task_launch_timeout":300000,
      "reconciliation_initial_delay":15000,
      "ha":true,
      "failover_timeout":604800,
      "checkpoint":true,
      "webui_url":null,
      "executor":"//cmd",
      "marathon_store_timeout":2000,
      "mesos_user":"root"
   },
   "version":"0.8.1",
   "zookeeper_config":{  
      "zk_path":"/my-marathon",
      "zk":"zk://192.168.4.6:2181/my-marathon",
      "zk_timeout":10,
      "zk_hosts":"192.168.4.6:2181",
      "zk_future_timeout":{  
         "duration":10
      }
   },
   "elected":true
}
```

Why is this content?

```
 "event_subscriber":{  
      "type":"http_callback",
      "http_endpoints":null
   },
```

Is that right?

I send a GET request `http://192.168.4.5:8080/v2/eventSubscriptions`, and obtain a response: 

```
{"callbackUrls":["http://192.168.4.7:8000/api/marathon/event_callback"]}
```

**Comment by softwaremisconduct** [comment]
I have made sure that the file event_subscriber has http_callback in /etc/marathon/conf, restart marathon and then restart the host even still event subscription is does not working . 

```
curl -X GET http://IP_ADDRESS:8080/v2/eventSubscriptions
```

```
{"message":"http event callback system is not running on this Marathon instance. Please re-start this instance with \"--event_subscriber http_callback\"."}
```

**Comment by gkleiman** [comment]
I haven't been able to reproduce this with Marathon v0.8.1. I used the following parameters: --event_subscriber http_callback --http_endpoints http://192.168.99.1:8001 http://192.168.99.1:8002

@stuart-warren did you start Marathon with "--event_subscriber http_callback"? According to the documentation (https://mesosphere.github.io/marathon/docs/rest-api.html#event-subscriptions) the parameter is required in order to activate the endpoint.

**Comment by stuart-warren** [comment]
Yes I did, the full ps output is mentioned in the OP
```
java -Djava.library.path=/usr/local/lib:/usr/lib:/usr/lib64 -Djava.util.logging.SimpleFormatter.format=%2$s%5$s%6$s%n -Xmx512m -cp /usr/bin/marathon mesosphere.marathon.Main --event_subscriber http_callback --zk zk://172.31.1.11:2181/marathon --master zk://172.31.1.11:2181/mesos
```
I will close this anyway, it's not a feature I'm currently using and clearly noone else is having a problem.
Thanks :)

**Comment by hammi85** [comment]
Hi,

I have the same problem described above. I'm running on a ubuntu 14.04 with marathon 0.8.1 and I activated on all my nodes ``` --event_subscriber http_callback``` (it is shown in the process list). 
But a requests against the api always answers with ```{"message":"http event callback system is not running on this Marathon instance. Please re-start this instance with \"--event_subscriber http_callback\"."}```

What did I configure wrong?

```
$ cat /etc/marathon/conf/event_subscriber
http_callback
```

```
$ ps -ef | grep event_subscriber
java -Djava.library.path=/usr/local/lib:/usr/lib:/usr/lib64 -Djava.util.logging.SimpleFormatter.format=%2$s%5$s%6$s%n -Xmx512m -cp /usr/bin/marathon mesosphere.marathon.Main --zk zk://ip's:2181/marathon --http_endpoints http://bamboo-ip:8000 --event_subscriber http_callback --master zk://zk-ip's:2181/mesos
```

```
$ curl marathon-ip:8080/v2/eventSubscriptions
{"message":"http event callback system is not running on this Marathon instance. Please re-start this instance with \"--event_subscriber http_callback\"."}
```

I take any help I can get :-)

**Comment by stuart-warren** [comment]
@hammi85 where is your issue report?

**Comment by hammi85** [comment]
@stuart-warren 
I deleted it because at the moment I posted my report I figured out that a not right configured marathon was running on a slave node, where it was not suppose to run. So it was totally my fold an not a bug at all... I'm sorry! But thanks for the response.

**Comment by memelet** [comment]
Too bad this was not resolved, I am having this exact problem. 

/v2/info:

"event_subscriber": {
    "type": "http_callback",
    "http_endpoints": null
  },

**Comment by kolloch** [comment]
Hi @memelet, 

what is your Marathon command line? Which version of Marathon are you using?

**Comment by memelet** [comment]
@kolloch Oh, so very sorry for not reporting back. My problem was user error. Events are working great with 0.11.1.
