### ISSUE TITLE
marathon creates lots of zero byte /tmp/MIMEXXXX.tmp files

### ISSUE THREAD

**Issue by rboyer** [mesosphere/marathon#1303]
I suspect this is just the manifestation of https://java.net/jira/browse/JERSEY-2515.

**Comment by naelyn** [comment]
Marathon reproducibly drops one of these files every time it is restarted.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3338. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
