### ISSUE TITLE
Unable to upload artifacts

### ISSUE THREAD

**Issue by jaytaylor** [mesosphere/marathon#1305]
I'm trying to upload an artifact using the information from https://mesosphere.github.io/marathon/docs/artifact-store.html, but it always returns:

    {"message":"Unsupported Media Type"}

Here are some of the curl calls I've tried that seem like they should work, but don't:

    curl -v -include -XPOST http://marathon-host:8080/v2/artifacts --form file=@test.txt

    curl -v -include -XPOST http://marathon-host:8080/v2/artifacts/test.txt --form file=@test.txt

Can anyone show me how this works?  Can we work together to get some working examples into the documentation?

**Comment by jaytaylor** [comment]
Bump.

It's awfully quiet here.  Is this a real feature?  Any advice would be appreciated!

**Comment by aquamatthias** [comment]
@jaytaylor I have tried to reproduce the problem. I used the exact same curl commands you have provided (with a different file).

- Start marathon with the option `--artifact_store file:///tmp/artifacts`
- Upload a file `curl -include -XPOST http://localhost:8080/v2/artifacts --form file=@changelog.md`. 
- There is a file uploaded: `ls -la /tmp/artifacts/changelog.md`

See the log here:
```
➔ curl -include -XPOST http://localhost:8080/v2/artifacts --form file=@changelog.md 
HTTP/1.1 100 Continue

HTTP/1.1 200 OK
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
Content-Length: 0
Server: Jetty(8.1.15.v20140411)
```

If the artifact store is not defined on the command line, I get this response:
```
HTTP/1.1 422 
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
Content-Type: application/json
Transfer-Encoding: chunked
Server: Jetty(8.1.15.v20140411)

{"message":"No storage provider available to load/persist artifacts. Configuration problem?"}
```

Can you attach some more details, so we can reproduce this problem?

**Comment by aquamatthias** [comment]
Please reopen, if the problem still exists.

**Comment by jaytaylor** [comment]
I haven't had time to get back to this yet.  Will reopen if there is still an issue.

Thanks!

**Comment by tayzlor** [comment]
I just hit this - 

```
I just hit this, using marathon 0.8.2 - 

curl -s -v -include -XPOST http://MARATHON_IP:8080/v2/artifacts --form file=@.dockercfg
* Couldn't find host MARATHON_IP in the .netrc file; using defaults
* Hostname was NOT found in DNS cache
*   Trying MARATHON_IP...
* Connected to MARATHON_IP (MARATHON_IP) port 8080 (#0)
> POST /v2/artifacts HTTP/1.1
> User-Agent: curl/7.37.1
> Host: MARATHON_IP:8080
> Accept: */*
> Content-Length: 312
> Expect: 100-continue
> Content-Type: multipart/form-data; boundary=------------------------33ea6ebe2de75e44
>
* Done waiting for 100-continue
< HTTP/1.1 100 Continue
HTTP/1.1 100 Continue

< HTTP/1.1 415 Unsupported Media Type
HTTP/1.1 415 Unsupported Media Type
< Expires: 0
Expires: 0
< Content-Type: application/json
Content-Type: application/json
* Server Jetty(8.y.z-SNAPSHOT) is not blacklisted
< Server: Jetty(8.y.z-SNAPSHOT)
Server: Jetty(8.y.z-SNAPSHOT)
< Pragma: no-cache
Pragma: no-cache
< Cache-Control: no-cache, no-store, must-revalidate
Cache-Control: no-cache, no-store, must-revalidate
< Content-Length: 36
Content-Length: 36

* HTTP error before end of send, stop sending
<
* Closing connection 0
{"message":"Unsupported Media Type"}%```

**Comment by tayzlor** [comment]
This seems related to leader proxying issues here #726 and #1239 . I just picked a random master IP to do the CURL above (which didn't happen to be the leader one). If I choose the actual leader of the cluster, it works fine.

**Comment by aquamatthias** [comment]
Hey @tayzlor can you test this with our current release candidate (0.9.0 RC1). A lot of changes were made to the leader proxy (See #1598). If this problem remains, please open a separate issue.
