### ISSUE TITLE
AS user I WANT to know when my app was killed due to exceeding memory limit

### ISSUE THREAD

**Issue by air** [mesosphere/marathon#1306]
Currently if a task exceeds its memory bound, it's killed and restarted. This cause of failure is not visible to the user - it just appears to be flapping.

**Comment by janisz** [comment]
Is it still valid? Fixed by #2130

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3606. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
