### ISSUE TITLE
AS user I WANT to know that my deployment is blocked in 'docker pull'

### ISSUE THREAD

**Issue by air** [mesosphere/marathon#1307]
Docker pull takes a long time. If you don't know the pull is happening, it looks broken. Even if you do know, it's still somewhat nerve-wracking.

Explicitly state in the GUI that the deployment is in the 'docker pull' phase.

**Comment by felixb** [comment]
Isn't this kind of fixed in 0.8.1? The new GUI shows a yellow slot in the health bar for staging instances.

**Comment by air** [comment]
I'm suggesting we explicitly call out the 'docker pull' activity, not just 'staging'.

**Comment by drexin** [comment]
Why would we differentiate between a docker task and a normal one? Either way we will not get any information from Mesos what step it is in. We only know when a task has been staged and when it either failed or is running.

**Comment by air** [comment]
We would be justified in recognizing Docker because it has first-class support in Marathon. We would be improving the Docker experience.

Presumably though we would generalize to a 'fetching resources' step.

Is there any mechanism by which we can tell that a `docker pull` (or other container-related fetch) is happening?

**Comment by drexin** [comment]
No, Marathon knows this:

Staging task -> running|error -> failed|killed|finished

Mesos foes not give us any information about the actions it executes to start the task.

**Comment by Raffo** [comment]
Any update on this? Does this help you? https://issues.apache.org/jira/browse/MESOS-2020

**Comment by aquamatthias** [comment]
@Raffo if a task of an app fails, you can see this in App.lastTaskFailure (REST) or App > Debug > Last Task Failure (UI). There is currently no (questionable if there will be ever a) way to say, what the docker stage is.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3533. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
