### ISSUE TITLE
AS user I WANT to know when my deployment is blocked because no offers are matched

### ISSUE THREAD

**Issue by air** [mesosphere/marathon#1308]
Explicitly show the user when a deployment is blocked waiting for appropriate offer(s).

**Comment by ConnorDoyle** [comment]
@air, please search the issues list before creating new ones.

Possible duplicate or extension of these issues:

- #126
- #652
- #951
- #968
- #1077
- #1090

**Comment by air** [comment]
I think Cody's #1090 covers it - I missed it - I'll close this as dupe.
