### ISSUE TITLE
AS user I WANT to access my logs easily

### ISSUE THREAD

**Issue by air** [mesosphere/marathon#1309]
Couple of distinct use cases:
1. I WANT to see the current log of my running app.
2. My app is flapping and I want to see the log of my last failed run.

**Comment by ConnorDoyle** [comment]
Possible duplicate or extension of the following issues:

- #152
- #878

**Comment by ConnorDoyle** [comment]
@air it would be better to tag existing issues with the new `usability` label than to create duplicates.

**Comment by air** [comment]
@ConnorDoyle Totally agree. I promise I searched for good candidates first : )

#152 is closed as wontfix, didn't see this.
#878 is a specific implementation (link to Sandbox in Mesos UI). I think we could generate some design thought on how else to do it.

**Comment by mwasn** [comment]
Will be offered with #2721 and #2645

Closed as duplicated.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2720. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
