### ISSUE TITLE
Remove deprecated ZooKeeper leader election library

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#1310]
This twitter library is deprecated and should be removed: https://github.com/twitter-archive/scala-zookeeper-client

**Comment by kolloch** [comment]
+1

Most build failures currently are because of resolve failures involving the twitter maven repository.

**Comment by air** [comment]
Are there other impacts caused by this? Trying to understand for prioritization. Thanks.

**Comment by janisz** [comment]
Closed by https://github.com/mesosphere/marathon/pull/3777

**Comment by jeschkies** [comment]
Old Twitter leader election has been removed with https://github.com/mesosphere/marathon/commit/b476f32a9dae14674bd758ff650c7fd2fe6f778e.
