### ISSUE TITLE
Invalidate framework ID if registration triggers an error

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#1316]
Currently when the scheduler receives the `error` callback, we bail out of the program.  One cause for this callback to be called is to attempt to re-register after being marked completed by the master (e.g. for exceeding the configured framework failover timeout.)

A symptom is that once Marathon is marked completed, it can _never_ re-register until the leading Mesos master process is kicked over, or the persisted FrameworkID is manually deleted from ZooKeeper!

Currently, it's pretty hard to disambiguate this error from other causes of framework errors.  I've filed [MESOS-2522](https://issues.apache.org/jira/browse/MESOS-2522) to add a reason field for framework errors to help with this.

**Comment by aquamatthias** [comment]
@ConnorDoyle How can I force an error to reproduce this?

**Comment by ConnorDoyle** [comment]
To repro (note, not tested):

- set a low framework failover timeout (a few seconds)
- let Marathon register with Mesos
- kill the Marathon scheduler process
- watch the Mesos master logs for framework completion 
- restart the Marathon scheduler process with the same ZK config

**Comment by ConnorDoyle** [comment]
For the test case, we could fake a framework error by invoking the callback ourselves.  The message to look for (there's still no unambiguous reason field) is set here in the Mesos master code: https://github.com/apache/mesos/blob/0.22.1/src/master/master.cpp#L1705.
