### ISSUE TITLE
marathon 0.8.0 [Status Update] RUNNING event not working anymore.

### ISSUE THREAD

**Issue by nashasha1** [mesosphere/marathon#1321]
I can't get TASK_RUNNING event per 30s at 0.8.0 version, It is a bug or it was intentional?

**Comment by drexin** [comment]
Can you please give a little more context? What are you trying to do? What do you expect to happen? What happens instead?

Thanks.

**Comment by drexin** [comment]
In 0.8.0 we increased the reconciliation timeout to 5 minutes because it is very costly if you have a large number of tasks running. If you want to set it to a lower value, try passing `--reconciliation_interval=$TIME_IN_MILLISECONDS` to the startup script.

**Comment by nashasha1** [comment]
But I did not get the events per 5minutes.Now I have never got the event since the app is running.

Thanks.

**Comment by jsargiot** [comment]
Apparently the change that breaks this is this one: https://github.com/mesosphere/marathon/commit/e5f0bfa810b2c5f7d60ecaf6d9af3c5cbd34b7a0.

I'm also experiencing this problem on 0.8.1, TASK_RUNNING status updates are not forwarded to eventSubscriptors...

**Comment by drexin** [comment]
I remember, this change has been made to prevent event flooding. But if you ate getting the first TASK_RUNNING, what is the problem? As long as you don't receive a terminal state, you can expect the task to be alive.

**Comment by nashasha1** [comment]
Yes,that may work too. I need change some code.
Thanks a lot.

**Comment by kolloch** [comment]
@nashasha1: I assume that we can close this issue. Feel free to correct me.
