### ISSUE TITLE
Specify environment variables in the config to be used on each host through REST API

### ISSUE THREAD

**Issue by jdowns** [mesosphere/marathon#1328]
Right now, when I deploy a docker container to a host with the rest API, I can specify the hostname using a request body like this:

```
{
    ...,
    "container": {
        "docker": {
            ...
            "parameters": [
                { "key": "hostname", "value": "a.corp.org" },
               ...,
            ]
        },
        "type": "DOCKER",
        "volumes": []
    },
    ...
}
```

I would like to be able to specify a environment variable on the host for a parameter. Specifically, Mesos provides a $HOST variable that I'd like to use. I'd like to do something like this:

```
"parameters": [
                { "key": "hostname", "value": "$HOST" },
               ...,
            ]
```

But now this results in the hostname being set to the literal string "$HOST".  I can imagine there are other use cases for having host specific environment variables used on each configuration.

**Comment by nickpoorman** [comment]
+1

**Comment by aquamatthias** [comment]
Hey @jdowns you can use the env parameter in app.json for specifying environment variables.
This env Variables will be expanded in the cmd and are available in the docker.
However all other places in the json this expansion does not take place and would (probably) break compatibility.

**Comment by memelet** [comment]
This is too bad. I'm trying to pass the $HOST to docker as the --dns argument:

            parameters:
              - {key: dns, value: "$HOST"}

I have consul running on each slave and need for the container to get access to it. As it is I have no way for my container apps to run in mesos/marathon.

**Comment by kriss9** [comment]
+1

**Comment by fpgeek** [comment]
+1

**Comment by memelet** [comment]
@aquamatthias said:
Hey @jdowns you can use the env parameter in app.json for specifying environment variables.
This env Variables will be expanded in the cmd and are available in the docker.

But this seems not to be the case. For example if I specify an env  XYZ_PORT = $PORT at runtime the value for XYZ_PORT is the string $PORT.

**Comment by bradleyreeves** [comment]
+1

**Comment by krestjaninoff** [comment]
+1
Is there any architectural reason to not implement this? Do you think that information about current host brakes isolation of an application/container?

**Comment by bradleyreeves** [comment]
Maybe a separate issue should be opened that isolates functionality of hostname resolution in env variables.

**Comment by moricard** [comment]
+1

**Comment by JianTangAxa** [comment]
+1

**Comment by RavAngell** [comment]
+1

**Comment by mohamedhaleem** [comment]
+1

**Comment by aquamatthias** [comment]
@nfnt Is there a way for the Mesos containerizer to set the hostname for docker containers?

**Comment by nfnt** [comment]
No, the Mesos containerizer doesn't have such a feature.
