### ISSUE TITLE
Support disk resource

### ISSUE THREAD

**Issue by mindscratch** [mesosphere/marathon#1333]
Mesos 0.22.0 added support for [disk isolation](https://issues.apache.org/jira/browse/MESOS-1589) and naturally to [enforce](https://reviews.apache.org/r/29688/) it. Marathon currently allows cpu/mem to be provided, it would be nice to allow disk to also be set. 

Perhaps #375 already allows for this, if so should that issue be closed? it also seems the API docs don't indicate arbitrary resources are allowed.

**Comment by drexin** [comment]
It seems to be missing from the documentation, but disk has always been a resource in both, Mesos and Marathon, Mesos just couldn't isolate it before 0.22. If disk is set in the AppDefinition, Mesos should pick it up and isolate it, so changing Marathon shouldn't be necessary.

**Comment by mindscratch** [comment]
Ok, perhaps then the API docs for Marathon just need to be updated to show `disk` as an option when creating an app. The docs for the `POST /v2/apps` endpoint show `disk` in the response but not as part of the request.

**Comment by drexin** [comment]
Created a new ticket to track the doc changes: https://github.com/mesosphere/marathon/issues/1341

Closing this.
