### ISSUE TITLE
Support zookeeper authentication

### ISSUE THREAD

**Issue by stevendborrelli** [mesosphere/marathon#1336]
Looking at the zookeeper client code in Main.scala, it does not look like zookeeper authentication is used, even if a zk://user:pass@zk:2181/marathon URL is used. This means we are unable to apply any ACLs on the `/marathon` znode.

```
  val client = new ZooKeeperClient(
      Amount.of(conf.zooKeeperTimeout().toInt, Time.MILLISECONDS),
      conf.zooKeeperHostAddresses.asJavaCollection
    )
```

The library supports passing in credentials: http://twitter.github.io/commons/apidocs/com/twitter/common/zookeeper/ZooKeeperClient.html

**Comment by TalonOne** [comment]
Any ETA on this ? This would really help secure the cluster better.
