### ISSUE TITLE
Support queuing pending deployment requests affecting multiple apps

### ISSUE THREAD

**Issue by timoreimann** [mesosphere/marathon#1346]
Running two consecutive deployments against Marathon quickly enough can lead to a 409 error response containing the message

> App is locked by one or more deployments. Override with the option '?force=true'. View details at '/v2/deployments/<DEPLOYMENT_ID>'.

As the `force` option is only meant to be used for failed deployments [according to the official docs](https://github.com/mesosphere/marathon/blob/master/docs/docs/deployments.md) (see the _Force a Deployment_ section), I would argue that a more reasonable way to deal with this is to queue up all pending deployments and apply them successively. This also offers the possibility to "skip" waiting deployment requests as newer ones are overtaking.

**Comment by kolloch** [comment]
Conflicts (409) should only happen if the apps in the deployments overlap. Does it really make sense to queue them up? I have trouble coming up with a suitable use case. 

The idea of Marathon (as I understand it) is that the user specifies the desired state and Marathon calculates the steps necessary to reach that state.

If you have a quick succession of updates which affect the same application, it is probably either

1) an error
2) or you only want the last one (which force should do)

Do you disagree?

**Comment by timoreimann** [comment]
Indeed, we only want the last update as per your second case. Reading the official documentation I linked on my original posting, however, I am concerned that `force` may not be the right option. Quoting (**emphasis** by me):

> If a force flag is set, then all deployments that are affected by this deployment are cancelled. **This leaves the system in a possible inconsistent state**.

I am not exactly sure how the inconsistent state could look like, but my worst-case expectation is that the service would become unavailable. This is certainly not what we want and the reason for this issue request.

(However, if Marathon was capable of cancelling the ongoing deployment in terms of rolling back to the previous (i.e., about-to-be-replaced) version **safely**, followed up by the deployment of the waiting update, it would be equally fine with us.)

Does that make sense?

**Comment by drexin** [comment]
An inconsistent state can be reached, when the to be canceled deployment affects more apps than the one you are forcing, because the whole deployment will be canceled. When an app is in the middle of a rolling upgrade and the deployment is canceled, it will stay in a state where some old and some new tasks are running. If the newer deployment does not update that app, it will stay in that state until a new deployment is being made for that app.

**Comment by timoreimann** [comment]
@drexin: How can an app affect other apps? Is this just about groups, or possibly something else, such as dependencies specified in an app's Marathon configuration file?

**Comment by drexin** [comment]
Every app runs in a group, on the top level there's the `/` group. So if you have a deployment running that affects more then one app and then force update one of those apps, the whole deployment will be canceled.

**Comment by timoreimann** [comment]
After reading up again on the [topic of application groups](https://mesosphere.github.io/marathon/docs/application-groups.html), let me make sure I got this right: Could you say that force-updating can _only_ lead to an inconsistent state if (and only if) you are either using non-trivial groups (i.e., groups containing more than one app) or specify non-empty dependencies (either on the application or application group level)?

(Paraphrased: Apps which are not part of a (non-root) group that also do not specify any dependencies can be force-updated without any risk of becoming inconsistent.)

Would that be correct?

**Comment by drexin** [comment]
Lets say it that way. Every deployment that only affects a single app (this can also be true for apps with dependencies) can safely be force updated upon.

**Comment by timoreimann** [comment]
Gotcha, thanks. Do you mind if I submit a PR that clarifies in the docs what constitutes an inconsistent state and the circumstances under which it can be reached?

As we are (currently) deploying single apps only, the potential dangers surrounding force-updating shouldn't affect us. The bigger question may then be whether Marathon should still implement queuing (or something different) to avoid 409 errors for deployments that cannot be force-updated safely (assuming that other Marathon users actually care about this scenario.) If you deem so, you may want to keep this issue open.

**Comment by drexin** [comment]
Pull requests are highly welcome. I'm not sure we want to implement something like this in the near future, but we can keep this open for now.

**Comment by c089** [comment]
Quick idea: Could marathon distinguish these "single apps" and not require you to set the force option in that case?

**Comment by kolloch** [comment]
If we are absolutely sure, that it is safe, I support that idea.

Ideally, I think, you should always be able to update any app definition and the system should converge to that configuration. That means changing the way deployments are done, though, and the steps that Marathon executes might be harder to understand :(

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3381. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
