### ISSUE TITLE
Integrate information from deployment-design.md into other documentation

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#1350]
The deployment design document explores possible extensions to Marathon -- most of which have already happened.

Important concepts which are not already explained in other documentation should be extracted and moved to the appropriate place. After that, the document should be deleted.

/cc @BenWhitehead: do you agree?

**Comment by BenWhitehead** [comment]
I'm not sure. I don't know what the goal in terms of marathon docs is. I've been a bit out of touch with marathon docs for several months.

I think it definitely makes sense that the docs get updated so that "planned" things are explained now that they're implemented.

**Comment by aquamatthias** [comment]
@kolloch What other documentation do you have in mind?

**Comment by air** [comment]
I don't think design docs should be part of the published doc site, because they show up in google results and it takes effort to understand that it's not implemented.

For design docs I suggest we stick to e.g. github to solicit feedback.

**Comment by kolloch** [comment]
@air I agree, we should make a better job of designating design docs as not implemented, maybe separating them out into another location. Note that the published docs _are_ on github. We should create a different issue for that.

This issue is about merging _implemented_ parts of the deployment-design description (I should have made that more clear) into the rest of our documentation. @aquamatthias With "other documentation" I mean somewhere in our published docs where we describe implemented functionality. E.g. https://github.com/mesosphere/marathon/blob/master/docs/docs/deployments.md

**Comment by kolloch** [comment]
BTW @air if we make the design docs public at all, they will show up in google.

**Comment by air** [comment]
An immediate problem is https://mesosphere.github.io/marathon/docs/deployment-design-doc.html which I've reached via google, and it takes time to figure out it's not part of documentation. I'm not sure what we gain by having it there.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3481. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
