### ISSUE TITLE
POST /v2/apps behaves like PUT to update existing app 

### ISSUE THREAD

**Issue by activars** [mesosphere/marathon#1351]
Hi, 

I noticed that `POST` to `/v2/apps` to an existing app will update the deployment. This feature seems to be undocumented. I would like to know what's the plan for the API support. Is it going to be supported? or you are planning to deprecate it. If this is officially supported API, do you need help on improving the documentation?

Thanks

**Comment by drexin** [comment]
This is not true for the latest version (0.8.1). When posting an app with an existing id it will be rejected.

**Comment by activars** [comment]
Thanks for clarification. Do you think it's worth supporting this feature? (even though it doesn't feel like restful).

The use case is for CI deployment. It's much easier to have one API call  for both initiating and updating the deployment.

**Comment by drexin** [comment]
You can just use the PUT version in that case. If the app doesn't exist, it will be created.

**Comment by activars** [comment]
Thanks!  This helps. Can I help to add this to the API doc?
