### ISSUE TITLE
can't scale application

### ISSUE THREAD

**Issue by alexandarp** [mesosphere/marathon#1353]
Hi everyone, 

I am currently running ``mesos 0.22.0`` and ```marathon 0.80.1``` on Ubuntu. Whenever I try to scale my application, it gets stuck. I am successfully running two instances of my node application in Docker containers. Whenever I try to scale my application to 3 instances, nothing happens. Is it possible that this is an issue with Docker?

Here is a picture: 

![screen shot 2015-03-31 at 12 52 37 pm](https://cloud.githubusercontent.com/assets/6274471/6927874/233615ec-d7a5-11e4-8958-78c3ff38fa96.png)
 
Any help would be appreciated, thanks!

**Comment by drexin** [comment]
Could you please give some information on your setup? How many Mesos slaves are you running, how many resources do you have in total? What does your app definition look like and are you running any other frameworks besides Marathon? Please also check the Frameworks page in Mesos and see what it says for the percentage of your fair share.

**Comment by alexandarp** [comment]
Sorry about that, I should have been more specific. I looked a little closer at the problem, there is definitely a resource shortage since my servers are tiny. Thanks for responding, it helped me figure out the problem.

**Comment by drexin** [comment]
Happy to help ;-). Please let us know if you encounter any other issues.
