### ISSUE TITLE
why the task keep running?

### ISSUE THREAD

**Issue by kaybinwong** [mesosphere/marathon#1354]
hey there,
i create a simple task(using version 0.8),why the task keep running again and again?
![qq 20150401110637](https://cloud.githubusercontent.com/assets/5570216/6933923/5739c022-d85f-11e4-8b20-fb7d4a8afaee.png)
![qq 20150401110659](https://cloud.githubusercontent.com/assets/5570216/6933924/585f912a-d85f-11e4-80c7-30e5fa2f83c7.png)

**Comment by drexin** [comment]
Marathon is for long running tasks only. It will always try to keep the configured number of instances running. So if your task finishes, Marathon sees that there should be 1 instance running, but there is none and will start a new one.
