### ISSUE TITLE
Add option to disable HTTP access if HTTPS is enabled.

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#1360]
We could either redirect to the HTTPS port or just turn it off.  Either way, allowing HTTP when HTTPS is enabled seems like a bad situation.  This will require some changes to Chaos.

**Comment by ConnorDoyle** [comment]
CC @kolloch @guenter this ticket is "high priority".  Let's try to get this done before the end of the week.

**Comment by guenter** [comment]
It's more secure and easier to implement to just turn http off. Let's introduce a new option `--disable-http` so we don't break backwards compat.

**Comment by kolloch** [comment]
I agree with Tobi's (@guenter) suggestion. I will try to do that latest by tomorrow so that we still have one review cycle over night left.

**Comment by kolloch** [comment]
This is actually a duplicate of #474, do you agree? @guenter @ConnorDoyle 

And it is actually a chaos issue, correct? 

https://github.com/mesosphere/chaos/issues/14

**Comment by guenter** [comment]
Yes, this is a dupe
