### ISSUE TITLE
make resource paths relative

### ISSUE THREAD

**Issue by mildmike** [mesosphere/marathon#1369]
My goal is to use haproxy routing to host the marathon UI: https://host.domain.com/marathon/ -> http://localhost:8080/

I can then add end user authentication but not require authentication between other services in the mesos grid (using firewall rules).

The paths returned by the UI are root relative and break this setup.  I moved the assets to a shared directory and modified the paths to get around this (main.js:  /v2/apps-> v2/apps) but it would nice to have it integrated into the code.

**Comment by aquamatthias** [comment]
This is resolved in master. Please try out.
