### ISSUE TITLE
Add REST API documentation for labels

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#1372]
#1051 added labels but as far as I can see, we do not have documentation for them yet.

**Comment by ConnorDoyle** [comment]
They're [here](https://github.com/mesosphere/marathon/blob/master/docs/docs/rest-api.md#labels) and more examples are [here](https://github.com/mesosphere/marathon/blob/master/examples/labels.json) but it looks like the docs site needs to be updated with the current content.

**Comment by ConnorDoyle** [comment]
Created issue #1373 to update the docs site.

**Comment by kolloch** [comment]
ah! Didn't know that you had to update that page manually. Thanks for the info, @ConnorDoyle
