### ISSUE TITLE
Update the documentation site

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#1373]
The docs are out of date with new API features in the current release.  The docs are in the repo, but need to be moved into the `gh-pages` branch.

**Comment by ConnorDoyle** [comment]
Synced with latest release (currently `v0.8.1`), but encountered a page build error from GitHub.  Looks like there's an issue with rendering the rest doc due to a missing `{% endhighlight %}` tag.

**Comment by kolloch** [comment]
This can be closed, correct? @ConnorDoyle @drexin

**Comment by drexin** [comment]
Yep, thanks.
