### ISSUE TITLE
marathon is not listenning on TCP port

### ISSUE THREAD

**Issue by Damien-traxair** [mesosphere/marathon#1375]
Hello,

I'm new with mesos and marathon.
I finish to install mesos, and it run correctly. Now I try to run marathon, with the command "service marathon start", the service is running but is not listening on a TCP port.
I install marathon from the debian package provide by mesosphere on an Ubuntu 14.04.

the command in the ```ps aux``` output :
```
java -Xmx512m -Djava.library.path=/usr/local/lib -Djava.util.logging.SimpleFormatter.format=%2$s %5$s%6$s%n -cp /usr/local/bin/marathon mesosphere.marathon.Main --zk_hosts 192.168.0.4:2181,192.168.0.5:2181 --master zk://192.168.0.4:2181,192.168.0.5:2181/mesos --zk zk://192.168.0.4:2181,192.168.0.5:2181/marathon --hostname mesos-master-hostname.net --master zk://192.168.0.4:2181,192.168.0.5:2181/mesos
```

Best regards,
Damien

**Comment by Damien-traxair** [comment]
Hello,

Finally, I found where is my mistake.
With the debian package, the marathon service was running but not listenning on the tcp port 8080.

After I try to run marathon from the tgz archive with the script start in the bin directory and I have an exception : 
```
Exception in thread "main" java.net.UnknownHostException: traxit-mesos-m0: traxit-mesos-m0: Name or service not known
```

So, I patch this error about the hostname on my machine (the error was : ``` unable to resolve host ```) and after marathon was listenning on the port 8080 from the tgz archive and the debian package.

Best regards,
Damien

**Comment by rubenqba** [comment]
I have same problem. What is your exactly solution??
