### ISSUE TITLE
Fix the API for URIs

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#1377]
In Mesos, command URIs can have some additional data, like whether to attempt to extract the downloaded file, and whether the downloaded file should have the executable permission bit set.  The Marathon API doesn't adequately model these options, leading to awkward workarounds.  (e.g. `chmod ug+x myfile.sh && ./myfile.sh`)

**Comment by abhay-agarwal** [comment]
Could we also check any downloaded URI against a SHA1 or MD5 that gets included in the json config?

**Comment by kolloch** [comment]
I like your suggestions, @abhay-agarwal and @ConnorDoyle. 

If I understood @bernd-mesos correctly, the meson-fetcher supports setting permissions. It does not support checksums. So for the check sums we would need further support in mesos-fetcher.

**Comment by tarnfeld** [comment]
I'd love to see this! There's also fetcher configuration to avoid extracting tar.gz files if you don't want it extracted automatically. Perhaps something like;

```json
{
  "urls": {
    "hdfs:///utils/my-thing": {
      "extract": true,
      "executable": true
    }
  }
}
```

**Comment by bernd-mesos** [comment]
Once the Fetcher Cache MVP is committed (hopefully next week), checksums are on my plate in the next sprint.

**Comment by tarnfeld** [comment]
That's awesome to hear @bernd-mesos! I think the structure I posted above would work well with this as it'd be as simple as adding `checksum` field.

**Comment by ConnorDoyle** [comment]
Blocked by #1505, as we'd probably want to experiment with this for the v3 REST API.

**Comment by jasongilanfarr** [comment]
Don't we have fetch for this now?
