### ISSUE TITLE
Command Health Check Failing

### ISSUE THREAD

**Issue by sekhar4233** [mesosphere/marathon#1380]
I am getting below error while running Docker containers using Command Health Checks.

"Warning: Health check 'COMMAND /' failed."

Marathon continuously restarting my Docker container.

**Comment by drexin** [comment]
Could you please post your app definition?

**Comment by sekhar4233** [comment]
{
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "sekhar/apache2:v3",
      "network": "BRIDGE",
      "portMappings": [
        { "containerPort": 22, "hostPort": 0, "servicePort": 0, "protocol":
"tcp" },
        { "containerPort": 80, "hostPort": 0, "servicePort": 0, "protocol":
"tcp" }
      ]
    }
  },
  "id": "apache2",
  "instances": 1,
  "cpus": 0.5,
  "mem": 512,
  "ports": [ 0 ],
  "healthChecks": [
   {
          "protocol": "COMMAND",
          "command": { "value": "curl -f -X GET http://$HOST:$PORT0/index.html"
},
          "gracePeriodSeconds": 40,
          "intervalSeconds": 5,
          "timeoutSeconds": 5
   }
  ],
  "uris": [],
  "cmd": "/usr/bin/supervisord"
}


I am running apache server inside docker container using supervisord.

**Comment by drexin** [comment]
Have you tried to just start apache instead of using supervisord? Marathon takes care of restarting failed tasks for you, so it shouldn't be necessary.

**Comment by sekhar4233** [comment]
I have log stash forwarder along with apache server which forwards the application logs to elasticsearch. I don't think marathon allows me to start both processes.

**Comment by kolloch** [comment]
Hi @sekhar4233,

did you find a solution? Please reopen if you didn't.

I just tested the following app definition succesfully. It outputs the URL it checks to a /tmp file. Maybe you can add that as well to debug if it actually queries the correct URL and if yes, if that URL responds to the curl command.

```json
{
  "cmd": "python -m SimpleHTTPServer 8080",
  "cpus": 0.0001,
  "disk": 0,
  "instances": 1,
  "mem": 32,
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "ubuntu",
      "network": "BRIDGE",
      "portMappings": [
        { "containerPort": 8080, "hostPort": 0, "servicePort": 0, "protocol": "tcp" }
      ]
    }
  },
  "healthChecks": [
    {
      "protocol": "COMMAND",
      "command": { "value": "echo http://$HOST:$PORT0 >/tmp/test.log && curl -f -X GET http://$HOST:$PORT0/" },
      "gracePeriodSeconds": 10,
      "intervalSeconds": 10,
      "timeoutSeconds": 5,
      "maxConsecutiveFailures": 2
    }
  ]
}
```
