### ISSUE TITLE
How do you provide the docker --dns=1.2.3.4 via the api?

### ISSUE THREAD

**Issue by simonvc** [mesosphere/marathon#1382]
Have tried: 
```
"docker": {
          "parameters": [
                { "key": "dns", "value": "172.31.19.107" }
            ],
```
and 
```
"docker": {
  "dns": "172.31.19.107" 
```

and neither seem to do it.

**Comment by simonvc** [comment]
I now understand that you have to pass the DNS to the docker daemon, and not to the task. Its a shame you can't do per-task DNS as changing the DNS for the daemon requires restarting all containers on a host.

**Comment by EslamElHusseiny** [comment]
Is this feature still not possible?
