### ISSUE TITLE
Don't set ulimit in marathon-framework

### ISSUE THREAD

**Issue by doctapp** [mesosphere/marathon#1389]
Hi,

problem is ulimit is hardcoded in marathon-framework (ulimit -n 8192). This should not be there when it's configured on the host (/etc/security/limits.conf or other). Or at least provide a means similar to mesos to customize it (/etc/default/mesos configure file using env var ULIMIT="-n 8192").

Workaround for now is to modify the line in marathon-framework and restart the marathon service.

Thanks

**Comment by lloesche** [comment]
What if we change it to be
```
[ $(ulimit -n) -lt 8192 ] && ulimit -n 8192
```

would that solve the problem?

**Comment by doctapp** [comment]
Seems ok, but would prefer a mesos-style configuration parameter in /etc/marathon.
Thanks,
Martin
