### ISSUE TITLE
Marathon can not scale more instances then the number of slaves

### ISSUE THREAD

**Issue by gijsvo** [mesosphere/marathon#1392]
Hi,

i'm running a cluster with 3 mesos-master and 4 mesos-slave machines. I deployed the json scripts like simple-docker, that dockerizes an ubuntu14 and nginx-bridge provided by mesosphere to test the cluster. First I was able to scale more instances of the dockerized apps then I had slaves in my cluster.
But then I started to experiment with HAproxy and HAproxy-marathon-bridge and now the maximum number of instances is the number of slave machines that are connected to the cluster.
Actualy I started with 3 slave nodes and created the fourth from scrash, this one never had HAproxy of HAproxy-Marathon-Bridge installed, But also on this one only one instance possible.

When I scale to 5 instances, 4 deploy and run without a problem, the fifth instance is hanging in deployments in Marathon. I deleted HAproxy and HAproxy-Marathon-Bridge from all machines, slaves and masters, only Keepalived service is still running on the master nodes.

I checked the logs in var/log/mesos and see that only 4 and not 5 offers are made to Marathon.

I dont know where to change this setting, if it's a setting of a flag to pass to the master, slave or marathon.

I'm running Marathon 0.8.1 and Mesos version 0.22.0.

Hope anyone can help me with this one.

Gijs

**Comment by drexin** [comment]
Hi Gijs,

could you please check in the Frameworks tab in the Mesos UI what the Max Share is for Marathon.

Cheers,
Dario

**Comment by gijsvo** [comment]
Currently i'm running 4 libmesos/ubuntu docker containers and the max share in the Mesos UI is 51.927% at this moment.

**Comment by drexin** [comment]
That’s strange. Do you see any messages about declined offers in the Marathon log? Or any failed tasks?

**Comment by gijsvo** [comment]
I cant see any declined offers in the slaves in the /var/log/mesos logs. 

I0414 11:03:47.663175  1203 slave.cpp:1121] Got assigned task ubuntu.2918b437-e285-11e4-8382-001dd8b71c33 for framework 20150408-094445-1767506698-5050-2598-0000
I0414 11:03:47.663970  1203 gc.cpp:84] Unscheduling '/tmp/mesos/slaves/20150414-100155-1784283914-5050-972-S3/frameworks/20150408-094445-1767506698-5050-2598-0000' from gc
I0414 11:03:47.664046  1203 gc.cpp:84] Unscheduling '/tmp/mesos/meta/slaves/20150414-100155-1784283914-5050-972-S3/frameworks/20150408-094445-1767506698-5050-2598-0000' from gc
I0414 11:03:47.664126  1203 slave.cpp:1231] Launching task ubuntu.2918b437-e285-11e4-8382-001dd8b71c33 for framework 20150408-094445-1767506698-5050-2598-0000
I0414 11:03:47.665561  1203 slave.cpp:4160] Launching executor ubuntu.2918b437-e285-11e4-8382-001dd8b71c33 of framework 20150408-094445-1767506698-5050-2598-0000 in work directory '/tmp/mesos/slaves/20150414-100155-1784283914-5050-972-S3/frameworks/20150408-094445-1767506698-5050-2598-0000/executors/ubuntu.2918b437-e285-11e4-8382-001dd8b71c33/runs/bcd0a13f-53aa-494a-852f-fb87b322e5a6'
I0414 11:03:47.665887  1203 slave.cpp:1378] Queuing task 'ubuntu.2918b437-e285-11e4-8382-001dd8b71c33' for executor ubuntu.2918b437-e285-11e4-8382-001dd8b71c33 of framework '20150408-094445-1767506698-5050-2598-0000
I0414 11:03:47.673055  1203 docker.cpp:581] Starting container 'bcd0a13f-53aa-494a-852f-fb87b322e5a6' for task 'ubuntu.2918b437-e285-11e4-8382-001dd8b71c33' (and executor 'ubuntu.2918b437-e285-11e4-8382-001dd8b71c33') of framework '20150408-094445-1767506698-5050-2598-0000'


Are there maby other logs that povide more info?

Gijs

**Comment by gijsvo** [comment]
I found this error message in the var/log/mesos/mesos-slave.ERROR file.

E0414 08:40:51.040037 15857 slave.cpp:3089] Container 'ee88fb86-c8ee-48ad-9119-de3f5b33c525' for executor 'ubuntu.30673792-e271-11e4-bfc9-001dd8b71c32' of framework '20150408-094445-1767506698-5050-2598-0000' failed to start: None of the enabled containerizers (mesos) could create a container for the provided TaskInfo/ExecutorInfo message.
E0414 08:40:51.040105 15857 slave.cpp:3177] Termination of executor 'ubuntu.30673792-e271-11e4-bfc9-001dd8b71c32' of framework '20150408-094445-1767506698-5050-2598-0000' failed: Unknown container: ee88fb86-c8ee-48ad-9119-de3f5b33c525
E0414 08:40:51.041036 15857 slave.cpp:3431] Failed to unmonitor container for executor ubuntu.30673792-e271-11e4-bfc9-001dd8b71c32 of framework 20150408-094445-1767506698-5050-2598-0000: Not monitored

Hope this helps.

Gijs

**Comment by drexin** [comment]
That error means, that the docker containerizer is not enabled on that slave. You can enable it by starting the slave with —containerizers=docker,mesos

Cheers,
Dario

**Comment by gijsvo** [comment]
That's weird because I created a file in every /etc/mesos-slave/ folder named containerizers.
The exact content of this file is:
docker,mesos

I read somewhere these files are the equivalent of starting the slaves with the flag parameters.

Gijs

**Comment by drexin** [comment]
Yes, that should work. Could you try to restart the slave processes? Also please check if it really starts with those parameters with `ps` or `top`.

Cheers,
Dario

**Comment by gijsvo** [comment]
I restarted the slave service on all slaves and to be sure i started them with not with systemctl but commandline:

mesos-slave --master=zk://my3masters:2181/mesos --log_dir=/var/log/mesos --containerizers=docker,mesos --work_dir=/var/run/work

Now i started them manualy and they use the terminal for output, I still cant see any errors comming up, just disk usage notifications.

Gijs

**Comment by drexin** [comment]
And it still doesn’t start all the tasks? Could you check /var/log/syslog for the Marathon logs on the machine Marathon is running on?

**Comment by gijsvo** [comment]
There is still one task qeued in deployment. This is the var/log/messages output form the offers.
I'm using centos 7.
Apr 14 12:02:59 CEN_G_M2001 mesos-master[972]: I0414 12:02:59.646193  1084 master.cpp:2268] Processing ACCEPT call for offers: [ 20150414-100155-1784283914-5050-972-O4873 ] on slave 20150414-100155-1784283914-5050-972-S4 at slave(1)@10.3.90.116:5051 (CEN_G_S4001) for framework 20150408-094445-1767506698-5050-2598-0000 (marathon) at scheduler-22138743-fe2a-493d-a762-02ae345de0c0@10.3.90.106:45919
Apr 14 12:02:59 CEN_G_M2001 mesos-master[972]: I0414 12:02:59.646338  1084 master.cpp:2268] Processing ACCEPT call for offers: [ 20150414-100155-1784283914-5050-972-O4874 ] on slave 20150414-100155-1784283914-5050-972-S5 at slave(1)@10.3.90.111:5051 (CEN_G_S3001) for framework 20150408-094445-1767506698-5050-2598-0000 (marathon) at scheduler-22138743-fe2a-493d-a762-02ae345de0c0@10.3.90.106:45919
Apr 14 12:02:59 CEN_G_M2001 mesos-master[972]: I0414 12:02:59.646450  1084 master.cpp:2268] Processing ACCEPT call for offers: [ 20150414-100155-1784283914-5050-972-O4875 ] on slave 20150414-100155-1784283914-5050-972-S6 at slave(1)@10.3.90.110:5051 (CEN_G_S2001) for framework 20150408-094445-1767506698-5050-2598-0000 (marathon) at scheduler-22138743-fe2a-493d-a762-02ae345de0c0@10.3.90.106:45919
Apr 14 12:02:59 CEN_G_M2001 mesos-master[972]: I0414 12:02:59.646559  1084 master.cpp:2268] Processing ACCEPT call for offers: [ 20150414-100155-1784283914-5050-972-O4876 ] on slave 20150414-100155-1784283914-5050-972-S7 at slave(1)@10.3.90.109:5051 (CEN_G_S1001) for framework 20150408-094445-1767506698-5050-2598-0000 (marathon) at scheduler-22138743-fe2a-493d-a762-02ae345de0c0@10.3.90.106:45919
Apr 14 12:02:59 CEN_G_M2001 mesos-master[972]: I0414 12:02:59.646718  1084 hierarchical.hpp:648] Recovered cpus(*):0.75; mem(*):237; disk(*):246; ports(*):[31001-32000] (total allocatable: cpus(*):0.75; mem(*):237; disk(*):246; ports(*):[31001-32000]) on slave 20150414-100155-1784283914-5050-972-S4 from framework 20150408-094445-1767506698-5050-2598-0000
Apr 14 12:02:59 CEN_G_M2001 mesos-master[972]: I0414 12:02:59.646809  1084 hierarchical.hpp:648] Recovered cpus(*):0.75; mem(*):237; disk(*):246; ports(*):[31001-32000] (total allocatable: cpus(*):0.75; mem(*):237; disk(*):246; ports(*):[31001-32000]) on slave 20150414-100155-1784283914-5050-972-S5 from framework 20150408-094445-1767506698-5050-2598-0000
Apr 14 12:02:59 CEN_G_M2001 mesos-master[972]: I0414 12:02:59.646956  1084 hierarchical.hpp:648] Recovered cpus(*):0.75; mem(*):237; disk(*):246; ports(*):[31001-32000] (total allocatable: cpus(*):0.75; mem(*):237; disk(*):246; ports(*):[31001-32000]) on slave 20150414-100155-1784283914-5050-972-S6 from framework 20150408-094445-1767506698-5050-2598-0000
Apr 14 12:02:59 CEN_G_M2001 mesos-master[972]: I0414 12:02:59.647047  1084 hierarchical.hpp:648] Recovered cpus(*):0.75; mem(*):237; disk(*):246; ports(*):[31001-32000] (total allocatable: cpus(*):0.75; mem(*):237; disk(*):246; ports(*):[31001-32000]) on slave 20150414-100155-1784283914-5050-972-S7 from framework 20150408-094445-1767506698-5050-2598-0000
Apr 14 12:03:00 CEN_G_M2001 marathon[971]: [2015-04-14 12:03:00,063] INFO 10.2.249.88 -  -  [14/Apr/2015:10:03:00 +0000] "GET /v2/apps HTTP/1.1" 200 774 "http://10.3.90.106:8080/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36" (mesosphere.chaos.http.ChaosRequestLog:15)
Apr 14 12:03:00 CEN_G_M2001 marathon[971]: [2015-04-14 12:03:00,144] INFO 10.2.249.88 -  -  [14/Apr/2015:10:03:00 +0000] "GET /v2/deployments HTTP/1.1" 200 262 "http://10.3.90.106:8080/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.118 Safari/537.36" (mesosphere.chaos.http.ChaosRequestLog:15)
Apr 14 12:03:02 CEN_G_M2001 mesos-master[972]: I0414 12:03:02.013411  1084 http.cpp:516] HTTP request for '/master/state.json'

As you can see, there are 4 offers accepted. But there is nothing about the 5th offer that's qeued.

Gijs

**Comment by drexin** [comment]
What does your app definition look like and how many CPUs does each of the slaves have?

**Comment by gijsvo** [comment]
This is the json script to start the docker containers.

{
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "libmesos/ubuntu"
    }
  },
  "id": "ubuntu",
  "instances": 1,
  "cpus": 0.25,
  "mem": 256,
  "uris": [],
  "cmd": "while sleep 10; do date -u +%T; done"
}

Each slave has 500MB ram, 1 cpu and 13GB of resources. (the masters have the same setup)
The weird thing is it worked before, with the same resources allocated to the machines.

Gijs

**Comment by drexin** [comment]
Try using less mem. You currently request 256MB for each task. If your slave only has 512, you could theoretically start 2 tasks, but the executor also needs some memory itself.

> Recovered cpus():0.75; mem():237; disk():246; 

Here you see that after starting the first task, the slave only has 237MB left, so if every slave has one task running, none of the subsequent offers match the requested amount of 256MB. If you set the mem to 128MB, you should be able to start more tasks.

Cheers,
Dario

**Comment by gijsvo** [comment]
That did it!
Never thought it was a memory problem because right after the installation it worked. But because of the testing in the last days and no reboot my memory was probably still full of junk.

Thank you!

Gijs
