### ISSUE TITLE
Replace references to elastic mesos from the tutorial

### ISSUE THREAD

**Issue by joerg84** [mesosphere/marathon#1394]
As Elastic Mesos (i.e. google.mesosphere.com, digitalocean.mesosphere.com) will be removed shortly (see internal Jira https://mesosphere.atlassian.net/browse/MSPHERE-116) we should replace/remove references in the tutorial.

**Comment by ssk2** [comment]
:+1:

**Comment by ssk2** [comment]
Closed by #1395.
