### ISSUE TITLE
Deployments "steps" json

### ISSUE THREAD

**Issue by DustinChaloupka** [mesosphere/marathon#1400]
Was checking out the deployments endpoint and noticed that the `steps` field is coming back as an array of array of objects.  I may not have had enough exposure to all different types of deployments yet, but I have never seen the nested array holding more than just the one object defining the app and action.  Is it possible to have more than one or is this a bug in how the json is being formatted?

**Comment by kolloch** [comment]
Hi @DustinChaloupka ,

the currently released code does not make use of the possibility to have multiple actions per step. The current master version does schedule multiple actions in one step and thus employs more parallelism during deployments.

Does that answer your question?

**Comment by drexin** [comment]
If you deploy a group containing several apps it can have more than one.

**Comment by DustinChaloupka** [comment]
That does, thanks!
