### ISSUE TITLE
Variable substitution in AppDefinition.env variables

### ISSUE THREAD

**Issue by hyper0x** [mesosphere/marathon#1401]
I define mine environment variable while I create and start a new app via curl & the rest api, for example:

``` bash
"BAMBOO_WEBSOCKET_PORT": "$PORT1"
```

It is treated as plain text. But I want to get the second port I defined via `$PORT[1]` 

```
{
  "app": {
    ......
    "env": {
      "BAMBOO_WEBSOCKET_PORT": "$PORT1"
    },
    ......
    "ports": [
      10083,    
      10084    <---- I WANT TO GET IT
    ],
    ......
}
```

Have any suggestion or plan for this?

**Comment by drexin** [comment]
We don't expand variables in any part of the app definition right now. You could achieve what you want by setting the variable in the `cmd`, i.e. `"cmd": "BAMBOO_WEBSOCKET_PORT=$PORT1 mycmd"`

**Comment by hyper-carrot** [comment]
But it can not make Bamboo get the correct value. Because they are located in different machines.

**Comment by drexin** [comment]
Could you please explain your use case in a bit more detail?

**Comment by kolloch** [comment]
Hi @hyper-carrot, if we introduce the variable substitution now, it might break some users setup.

Can you elaborate why @drexin 's suggestion doesn't work for you?

**Comment by jeacott1** [comment]
as a vague workaround, if your app is using spring boot or something that can do the substitution, then passing the to-be-resolved variable directly as an env var will work.  ie env: "my.spring.config.property.BAMBOO_WEBSOCKET_PORT":""${PORT1}"    or whatever.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4611. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
