### ISSUE TITLE
Docker container name not being used

### ISSUE THREAD

**Issue by rithumlabs** [mesosphere/marathon#1403]
Can't seem to get Marathon to accept the --name option with Docker run, which assigns the desired name to the container being lauched. What gives? Example Marathon app-json below:

redis = {
  "id": "redis-0",
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "dockerfile/redis",
	  "network": "BRIDGE",
      "portMappings": [
        { "containerPort": 6379, "hostPort": 6379, "protocol": "tcp" }
      ],
      "parameters": [
        {"key": "hostname", "value": "node-0"},
        {"key": "name", "value": "redis"},
	{"key": "env", "value": "SERVICE_NAME=redis-0"},
	{"key": "env", "value": "SERVICE_TAGS=redis, db"}
      ]
    },
    "volumes": []
  },
  "cpus": .25,
  "mem": 500.0,
  "ports": [6379],
  "requirePorts": True,
  "env": { "container_name": "redis-0", "deployment_group": "dg-1" },
  "labels": {"environment": "single-node test"}
}

Marathon is assigning for the name something like this:
 "Name": "/mesos-edb5619c-92d5-4df1-abb5-f0c29b4fd807"

The docs says Marathon does a pass-thru with Docker options for the parameters.

**Comment by drexin** [comment]
We actually pass through all parameters, but Mesos assigns a name to the container. I'm closing this, because there's nothing we can do on the Marathon side. Please post this to the Mesos ML or issue tracker. Thanks!
