### ISSUE TITLE
The DNS name is the internal dns of  EC2

### ISSUE THREAD

**Issue by tianxiaoliang** [mesosphere/marathon#1404]
I use marathon api to launch a docker app which has webapp in it,
But in marathon UI the instance's hosname is "XXX.ec2.internal:31031",
So I can not redirect to target web service by click the port link in UI,also I don't even know the external IP of this web app,how could I get  this external IP of mesos slave

**Comment by drexin** [comment]
Marathon uses the hostname that it gets with the offer from Mesos. You can configure the slave to use a different hostname by setting the `--hostname` flag. I'll close this, as it is not a Marathon issue.

**Comment by tianxiaoliang** [comment]
could you write down the full command? thank you

**Comment by drexin** [comment]
`mesos-slave --hostname=your-hostname`

**Comment by tianxiaoliang** [comment]
Thank you
