### ISSUE TITLE
Healthcheck for non web apps

### ISSUE THREAD

**Issue by aseppala** [mesosphere/marathon#1412]
If I've understood correctly the healthcheck expects a http response from the monitored app. However not all apps are webapps. It would be good to be able to monitor other types of apps as well.

Suggestions: 

Use exit code of COMMAND to determine healthiness.

To monitor apps running in docker container, expose container ID to COMMAND healthcheck same way as $HOST and $PORT1. This would enable to build custom healthchecks like "docker exec $CONTAINERID health.sh".

**Comment by drexin** [comment]
That is exactly what the COMMAND healthcheck does. Ungortunately Marathon diesn't execute the COMMAND healthchecks (and doesn't know the container id) and Mesos doesn't seem to pass the container id to the healthcheck env either. Please file a ticket in the Mesos bug tracker.
