### ISSUE TITLE
Marathon restart deployment stuck for service launched with constraints: [[hostname:UNIQUE]]

### ISSUE THREAD

**Issue by srikanth-viswanathan** [mesosphere/marathon#1425]
I have a virtual machine cluster with a single mesos slave. When I try to make a v2/apps/<app>/restart request on an app that was previously launched with the hostname:UNIQUE constraint, the deployment is stuck in the "RestartApplication" state. After a lot of investigation, I discovered that the task was failing to start because of the hostname uniqueness constraint. I was able to fix it by setting "minimumHealthCapacity:0, maximumOverCapacity:1". Could Marathon detect this better and return a failure instead of being stuck? Is this the right forum to request such a bug fix/new feature?

**Comment by kolloch** [comment]
Hi @srikanth-viswanathan, yes, you have come to the right place :) So, thanks for your feedback.

You are not the first one to suggest better feedback if the required resources are not available. Unfortunately, it is pretty hard to solve in general. In a cluster, slaves may come and go, resources might be released at any time, so it is hard to detect when you are "stuck". In your case, Marathon cannot now that you will not add an additional slave soon.

What do you think of #1090? Would that help? If not, please feel free to elaborate and reopen the issue.

**Comment by srikanth-viswanathan** [comment]
@kolloch, thanks.  I think #1090 will suit my needs nicely. I sub'd myself to that issue.
