### ISSUE TITLE
Marathon cluster all apps restored to old point in time snapshot by delete deployment

### ISSUE THREAD

**Issue by npateriya** [mesosphere/marathon#1434]
May be related to https://github.com/mesosphere/marathon/pull/1399 & https://github.com/mesosphere/marathon/issues/660

We had couple of deployment task in hanged in state for 2-3 weeks
```
curl  marathon.shipped-cisco.com/v2/deployments | python -m json.tool
[
  {
        "affectedApps": [
            "/sleep-cluster"
        ], 
        "currentActions": [
            {
                "action": "ScaleApplication", 
....            }
        ], 
        "currentStep": 2, 
        "id": "4f918018-113e-4c06-ac3d-9294f55690c6", 
        "steps": 
            [
                {
                    "action": "ScaleApplication", 
                    "app": "/sleep-cluster"
                }
            ]
        ], 
        "totalSteps": 2, 
        "version": "2015-04-06T14:21:06.685Z"
    }
]
```
To cleanup hanged deployment jobs , I executed delete deployment, (without force=true)
```
curl  -X DELETE marathon.xyz/v2/deployments/4f918018-113e-4c06-ac3d-9294f55690c6 
{"version":"2015-04-26T18:34:32.517Z","deploymentId":"f54ad93a-76a6-4f38-b059-cc93f335ccf9"}
```

As force is false, expected only single app to be reverted. This resulted in all apps of cluster to be reverted to 3 week back point in time snapshot. Apps created after that point got deleted and already deleted apps are restored.

**Comment by drexin** [comment]
Thanks for reporting this, we already fixed this in master. We plan to release 0.8.2-RC1 tomorrow.

**Comment by phildougherty** [comment]
It's a bug when putting everything in the root group /

When they get stuck just scale them forcibly to the number of containers already running then re-deploy. It was fixed in the latest release.

Also your marathon UI is open to the world..
