### ISSUE TITLE
marathon docker deploy only one instance can access

### ISSUE THREAD

**Issue by wiselyman** [mesosphere/marathon#1441]
I deploy an tomcat docker image through marathon with instances of 3

Docker.json:
```
{
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "192.168.1.103:5000/tomcat",
      "network": "BRIDGE",     
      "portMappings": [
         { "containerPort": 8080, "hostPort": 0, "protocol": "tcp" }
      ]
    }
  },
  "id": "tomcat",
  "instances": 3,
  "cpus": 0.5,
  "mem": 512,
  "uris": [],
  "cmd":"/opt/tomcat/bin/deploy-and-run.sh"
}
```

Everything is ok in marathon ui and mesos ui

the url of the three instances
```
192.168.1.113:31000
192.168.1.114:31000
192.168.1.115:31000
```
only 192.168.1.113:31000 can show right page,and the others showed 

title :`Proxy error:502 Server dropped connection`

content:
```
502 Server dropped connection

The following error occurred while trying to access http://192.168.1.114:31000/:

502 Server dropped connection

```

and I check docker container status in mesos-slave shows 

`
4d40e45dce5d        192.168.1.103:5000/tomcat:latest   "/bin/sh -c /opt/tom   2 minutes ago       Up 2 minutes        8778/tcp, 0.0.0.0:31000->8080/tcp   mesos-66197b0a-406e-4beb-9b64-9bd0bbff169c
`

`
986cdce11dda        192.168.1.103:5000/tomcat:latest   "/bin/sh -c /opt/tom   2 minutes ago       Up 2 minutes        8778/tcp, 0.0.0.0:31000->8080/tcp   mesos-7e6f8665-7dad-45e8-9bf3-e5b558171b7b
`

`
83bf64e31d46        192.168.1.103:5000/tomcat:latest   "/bin/sh -c /opt/tom   2 minutes ago       Up 2 minutes        8778/tcp, 0.0.0.0:31000->8080/tcp   mesos-afa97aaf-2ad4-48a6-ad2b-5be00ff3afec 
`
Thanks

**Comment by drexin** [comment]
From a Mesos/Marathon perspective everything looks okay. The tasks are running with the correct config. Could this be a problem with the machine or Tomcat config?

**Comment by wiselyman** [comment]
@drexin 
I also try the official tomcat docker image(`docker pull tomcat`),and shows the same result.

**Comment by wiselyman** [comment]
@drexin 

After 4 days,and everything is ok,I don't know why,thanks !
