### ISSUE TITLE
Validation for app creation & update should not differ

### ISSUE THREAD

**Issue by MikeMichel** [mesosphere/marathon#1446]
starting an app with 

```
{
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "sloppy/apache-php",
      "network": "BRIDGE",
      "portMappings": [
                {
                    "containerPort": 80,
                    "hostPort": 0,
                    "protocol": "tcp"
                }
            ]
    }
  },
  "id": "apache",
  "instances": 1,
  "cpus": 0.1,
  "mem": 128,
  "cmd": ""
}

```
then changing memory  with PUT

```
{
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "sloppy/apache-php",
      "network": "BRIDGE",
      "portMappings": [
                {
                    "containerPort": 80,
                    "hostPort": 0,
                    "protocol": "tcp"
                }
            ]
    }
  },
  "id": "apache",
  "instances": 1,
  "cpus": 0.1,
  "mem": 512,
  "cmd": ""
}
```

fails with 

```
"error": "AppDefinition must either contain one of 'cmd' or 'args', and/or a 'container'."
```

**Comment by kolloch** [comment]
That's a bug but there is a work around. You can omit the `cmd: ""` in the second request and actually also in the first.

```json
{
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "sloppy/apache-php",
      "network": "BRIDGE",
      "portMappings": [
                {
                    "containerPort": 80,
                    "hostPort": 0,
                    "protocol": "tcp"
                }
            ]
    }
  },
  "id": "apache",
  "instances": 1,
  "cpus": 0.1,
  "mem": 512
}
```

Also notice that `PUT` in Marathon only updates the fields that you specify, leaving everything else unchanged. Therefore, you can also just specify the changed `mem`-field in the second request.

(See #1418 if you think that should be changed.)

**Comment by kolloch** [comment]
Note: Creating an app should have the same validation rule as updating an app.

**Comment by kolloch** [comment]
The problem was actually not the validation itself but the serialization of cmd: "".

An app without args and cmd: "" is automatically translated into an app with cmd: null and args: []. When you try to add a cmd to that, you see the validation error message above.

I will solve it in two ways:

* Make empty cmds invalid. You should not specify them.
* If the args array is empty, translate that into no args at all. (We cannot distinguish between empty and not specified in our serialization.)
