### ISSUE TITLE
PUT to `/v2/apps` gives an unhelpful error.

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#1447]
We should detect this problem and tell the user that they probably want to put the resource to `/v2/apps/{appId}` instead.

**Comment by shoenig** [comment]
While you're at it, the error message format is different depending on what type of error happened. For example, trying to create an app with a duplicate name returns `{"message":"An app with id [/hoenig/ping.indeed] already exists."}` whereas trying to create an app with an invalid name returns `{"errors":[{"attribute":"id","error":"path contains invalid characters (allowed: lowercase letters, digits, hyphens, \".\", \"..\")"}]}`

**Comment by kolloch** [comment]
Hi @shoenig , I have to think about it. If that is important to you, please create a separate issue.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3425. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
