### ISSUE TITLE
Disable post-creation dynamic rescaling for some apps

### ISSUE THREAD

**Issue by Kabhal** [mesosphere/marathon#1448]
Some apps does not support dynamic rescaling. It could be interesting to add a flag in JSON for these apps, so that you can launch an arbitrary number of instances at creation, but any later rescaling is denied.
And UI rescale button will be disabled in this case.

**Comment by aquamatthias** [comment]
Perhaps we will add constraints on application parameters.
Currently there are no plans in this direction.

**Comment by Kabhal** [comment]
Introducing 2 new parameters : minInstances and maxInstances would do the trick too.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2887. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
