### ISSUE TITLE
Provide applications.json file for apps to be auto-launched at startup

### ISSUE THREAD

**Issue by matt-deboer** [mesosphere/marathon#1449]
The (enhancement) idea is to have a "applications.json" file that is read by Marathon on startup for the purpose of deploying the apps defined within. The structure could be like so:

    {
      "applications": [
         { /* standard application definition here */ },
         { /* standard application definition here */ },
         ...
      ]
    }

The applications in the array would be deployed in order.
The file's path could be listed as an arg to the marathon executable.

This could be very useful for spinning up demo or dev instances of mesos+marathon with a pre-loaded set of apps, as well as (one half of) a mechanism to export/import a cluster definition between environments.
Thoughts?

**Comment by kolloch** [comment]
Hi @matt-deboer,

the part of making a REST call as part of the initial provisioning should be manageable with most provisioning tools.

Basically, if you want to spawn interrelated applications with one API-call, you can use a [PUT group](https://mesosphere.github.io/marathon/docs/rest-api.html#put-/v2/groups/%7Bgroupid%7D) call with all your application definitions inside. If an app should only be started after another app, you can specify dependencies.

If you want to export your group definition, you can use a GET call for that group. 

Does that solve your problem?

**Comment by kolloch** [comment]
I will close that issue for now if you want to pursue this further, please elaborate and reopen.

**Comment by matt-deboer** [comment]
that covers it just fine; thanks.
