### ISSUE TITLE
Remove ulimit changes from shell script

### ISSUE THREAD

**Issue by mindscratch** [mesosphere/marathon#1452]
The [shell script](https://github.com/mesosphere/marathon/blob/master/bin/marathon-framework#L88) attempts to modify ulimits when running Marathon. This can be problematic when trying to start Marathon as a non-root user.

In a systemd environment, the unit file could set `LimitNOFILE` to accomplish similar goals.

For reference, this ticket came from a discussion on the [google group](https://groups.google.com/d/msg/marathon-framework/204-gRO1o7Q/Ifz9hwAooKYJ).

**Comment by kolloch** [comment]
This seems to be related to #1389.

@lloesche Can we quickly change that?

**Comment by mindscratch** [comment]
Yup, this appears to be a duplicate, sorry about that.

**Comment by lloesche** [comment]
This is actually not a duplicate as it points out two problems:
1. changing ulimit to some hard coded number
2. calling ulimit as non-root user

#1389 only reports 1.

I added a suggestion in #1389 that might solve both.
