### ISSUE TITLE
Rolling Restart Alternative Stopping Mechanism

### ISSUE THREAD

**Issue by kensipe** [mesosphere/marathon#1463]
The current implementation of rolling restart or rolling deploys auto stops previous version (v1) of the app based on the good health of the new version's readiness (v2).     There is interest in doing an application version update however we want all of v2 up prior to v1 destroy AND there is a REST invocation to signal the v1 destruction.    The scenario would look like this:

1. app v1 running
2. marathon update v1 to v2
3. v2 fully update and running
4. external check of v2
5. successful external check leads to a message to marathon to remove v1
6. only v2 running

**Comment by kolloch** [comment]
Hi @kensipe,

what about scripting the REST API for that?

1. (unchanged)
2. add an additional app with v2 (PUT app or POST app)
3. wait for deployment to finish
4. (unchanged)
5. DELETE app v2
6. (profit)

I think that @guenter just told me about a customer doing just that.

**Comment by kolloch** [comment]
Just to keep our opened issues relevant, I will close this for now. If your requirements are different, you are more than welcome to reopen the issue.

**Comment by kensipe** [comment]
it was @guenter that wanted this issue recorded for otto.

**Comment by kolloch** [comment]
Hi @kensipe, I talked to @guenter and he elaborated that there approach was not to create a second app. Without creating a second app on upgrade you would need a different approach and additional features in Marathon.

But since they are doing blue/green deployment anyway it seems fairly natural to me.
