### ISSUE TITLE
Master IP should be passed down somehow to the containers 

### ISSUE THREAD

**Issue by opaugam** [mesosphere/marathon#1473]
At this point there does not seem to be a way for containers to get a hold of where the marathon masters are (e.g IP passed as a env. variable for instance, DNS-like system). This would be greatly appreciated in order to build a PaaS for instance where a task has the ability to spawn applications on its own.

Note one could in theory go monkey in the mesos ZK ensemble and grep the /marathon/leader/\* node, but this is quite ugly & error prone (plus it breaks encapsulation).

**Comment by knuckolls** [comment]
I think this is a pretty good idea. Backplane services that interact with marathon for scaling up / scaling down has always been one of the allures that marathon could possibly provide. It shouldn't require digging around in zk or making marathon participate in some bolt on service discovery framework when it could just be an environment variable.

**Comment by opaugam** [comment]
Yea and cheap to accomplish too as it's pretty much stateless without side-effects. K8S relies on their service concept to provide the same.

Our clustering overlay @ https://github.com/autodesk-cloud/ochopod is right now explicitly passing the master IPs which is fine as a workaround. Having this provided the same way you guys pass the MARATHON_APP_ID would make at least one poor developer very happy :)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3007. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
