### ISSUE TITLE
Use healthy status in dependencies between applications

### ISSUE THREAD

**Issue by Kabhal** [mesosphere/marathon#1474]
When dependencies are set between applications/groups, dependencies are satisfied since the container is started, but do not care about contained application status.
It could be interesting to take the "healthy" status into account (when health-checks are defined) so that we can set dependencies on a "completely functional" application.

It should be a new json key so that we can choose the dependency type we need, and we can mix them for a single application.

**Comment by drexin** [comment]
It should already take the health into account. Do you have a group definition where this is not working?

**Comment by Kabhal** [comment]
Great !
And are health-checks used in case of scaling ? I mean, if I start 2 instances of an application which have some HCs defined, does the second one wait for the first one to be healthy ?

**Comment by drexin** [comment]
No, it doesn't wait. Imagine you want to start 100 instances of your app and it takes 1 minute to fully start.  In this case the full deployment would take 100 minutes. It may make sense to in the future add something like "deploy 1 instance to see if everything works as expected and scale to N instances afterwards", but it's currently not planned.

**Comment by Kabhal** [comment]
I see.
In fact the "deploy first task, then start remaining tasks in parallel" is my current use case and would be helpful ...

**Comment by drexin** [comment]
I will close this ticket, could you please create a new one for that?
