### ISSUE TITLE
Introduce application-relative constraints

### ISSUE THREAD

**Issue by Kabhal** [mesosphere/marathon#1475]
Currently, Marathon manage constraints definition against Mesos slaves (given slave hostname or arbitrary attributes).
It could be interesting to introduce new operators to add constraints between applications themselves.
Use cases :
- Denying 2 different applications to be started on the same node

**Comment by kolloch** [comment]
Hi @Kabhal , can you elaborate on the use case for this please? What problem does that solve? And also how common is the problem?

**Comment by knuckolls** [comment]
One thing I can think of is compliance. Even though it's probably fine if two different client's containers run atop the same slave, it may be that a compromise must be made wherein we set constraints so that containers that handle sensitive things are not co-located with containers from other clients of a PaaS or something like that.

It's not necessarily required, because it could be that you could just put them outside the mesos cluster. But it would be preferable to continue to have all the goodies that marathon provides even if the client / compliance insists on anti-affinity of two containers.

**Comment by Kabhal** [comment]
Example 1 :
Basic example I seen on Kubernetes or Singularity I don't remember : To be sure a database and his backup application are never located on the same slave.

Example 2 :
For example, not all applications can be scaled using just instance count, because some configuration is specific for each node (example : try to create a Zookeeper cluster on Marathon, or create a Kafka cluster, etc ..)
Instead, I create a /zk group with multiple applications (e.g.: /zk/zookeeper-1, /zk/zookeeper-2, /zk/zookeeper-3).
However, I can't use the "hostname UNIQUE" constraint to be sure any zk node will be alone on a given slave, because I have not 3 tasks of a single application, but 3 different applications.
In this case, I would like to use something like 'id APP-UNLIKE /zk/zookeeper-*'

**Comment by kolloch** [comment]
Ok, makes sense. Its currently outside of our short term scope. We would welcome a PR, though.

**Comment by hellertime** [comment]
:+1: on this, as I was just looking for simmilar functionality. A smaller scoped solution might be to be able to setup constraints in an application group (say no two apps in the group can run on the same host)... this way you don't have to do a full constraint search across all applications, just a localized search. Still the full-blown multi-app constraint system would be a huge feature.

Another thought would be just to setup mesos roles and ensure that apps have affinity for those roles, and keep the roles on separate hosts... not the most elegant solution, but functional.

**Comment by jeacott** [comment]
+1 usecase - run multiple different application clusters across mesos managed resources. in this way its much more flexible than just the current 'cluster' and 'rack' solutions.

a simple group attribute for a given application would work well.

**Comment by ottoyiu** [comment]
:+1: we want to prevent more than one database container running on each host. It would be great to have application based constraints.

**Comment by venyz** [comment]
+1 usecase
Say a particular application produces a large volume of logs that are then processed by scribe. Scribe is managing things fine if we only have one instance of the app per host, but whenever we get two instances running on the same host, it cannot cope with the volume of logs produced and starts to fall massively behind. In this case, we’d like to make sure we only get one instance per host.

**Comment by janisz** [comment]
@venyz this looks like perfect application of unique hostname constrain.

**Comment by venyz** [comment]
@janisz The situation in which ‘unique hostname’ doesn’t work is when you want to have a canary instance for your app. Marathon sees that as a separate app and you easily end up with the canary sharing a host with a regular instance.

**Comment by jasongilanfarr** [comment]
I concur that this would be a very useful feature; however, I expect we will not internally have any time to implement it in the near/short/medium term. Please feel free to offer a design then we can discuss an implementation plan.

**Comment by jdef** [comment]
"anti-affinity" for apps/pods; something to consider for the v3 API?

**Comment by jasongilanfarr** [comment]
I would actually argue its Affinity and AntiAffinity (I had a usecase for both myself in the past), v3 for sure, not opposed to v2, but I don't think the team has the staff to do it right now.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2784. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
