### ISSUE TITLE
Introduce multiple scaling strategies

### ISSUE THREAD

**Issue by Kabhal** [mesosphere/marathon#1477]
Currently when scaling applications, tasks are started in parallel.
Multiple strategies should be available :
- start all tasks in parallel
- start all tasks serially, waiting for previous task to be healthy
- start first task, wait first task to be healthy, then start remaining tasks in parallel

The same chosen strategy should be applied for initial application launch, or for any application rescaling

**Comment by kolloch** [comment]
Can you elaborate on the use case?

Basically, I would recommend scripting the API in this case since everyone requires slightly different behaviors.

In addition, `upgradeStrategy` in the app definition provides some control over how to replace tasks when a new app definition has been supplied.

**Comment by Kabhal** [comment]
Ok I forget upgradeStrategy takes health into account.
My other use cases are probably too weak to worth this dev.

**Comment by kolloch** [comment]
Thanks for your feedback!
