### ISSUE TITLE
specifying a post action in input json file for docker container

### ISSUE THREAD

**Issue by sridharlreddy** [mesosphere/marathon#1479]
I need to specify the post actions in input json file for marathon so that they are executed after creating the application (more on docker container). I have not seen anywhere where I can specify some hooks kind of thing. Mesos seems to support the same already. Is this available in marathon?

**Comment by xiaods** [comment]
i have seen marathon have a pre-action for URI download. you can have a look the code.

**Comment by aquamatthias** [comment]
If you use docker containers, you should have all the control you need. 
If you use simple command line apps, you can define shell scripts, that get executed.
Hope this helps.

**Comment by junneyang** [comment]
If you use docker containers, you should have all the control you need. 
——if i use docker containers, how do i execute scripts on the target host before the container start or after the container stop?
i think it may be very useful!
