### ISSUE TITLE
Question: Health-Check Lifecycle Diagramm

### ISSUE THREAD

**Issue by tomuench** [mesosphere/marathon#1480]
Hello,

i have a question about the Health-Check Life cycle Diagram mentioned here [1]. What meaning does the operator **^** has? I have tested a bit around, and it can't be power or the bit-by-bit XOR-Operator. The equitation can be solved by a bit-by-bit AND-Operator.

I catch up the edge from scaling-state to healthy-state with equitation **r= i ^ h = i** at the diagram [1]. My parameters when i get into the state scaling are defined as the following:
- r = 1
- i = 2
- h = 1

Now a new instance get's up healthy and my parameters are changed to **r = 2** and **h = 2**. Then my App should be in a healthy state. So the equitation should on the edge should be true.
- **^** as XOR -> 2 = 0 = 2 -> false
- **^** as Power -> 2 = 4 = 2 -> false
- **^** as AND -> 2 = 2 = 2 -> true

Is my assumption right that the **^**-Operator stands for a bit-by-bit AND-Operator or did i get something wrong?

Thanks for your reply.

Best Wishes,

Tobias

[1] https://mesosphere.github.io/marathon/docs/health-checks.html

**Comment by kolloch** [comment]
Hi @tomuench ,

you are right, it is the AND operator ;)

I guess the author thought that ^ looked fairly close to the mathematical conjunction ∧ even though ^ is used for XOR in C-derived languages.
