### ISSUE TITLE
App stays in locked state

### ISSUE THREAD

**Issue by drexin** [mesosphere/marathon#1481]
Sometimes an app is reported as being locked without a running deployment and only gets unlocked when Marathon is being restarted. The problem seems to b a missing timeout in a call to the state abstraction in `MarathonStore.names()`, which is being called when an app needs to scale because tasks died. If that call never returns / times out, the app will never be unlocked.

**Comment by kolloch** [comment]
#1507 seems to be caused by this fix.

**Comment by solarkennedy** [comment]
This isn't fixed for me, and I'm running 0.8.2.

The same symptoms are occurring:
* app is locked, any changes (put/delete) in the UI return immediately
* Logs indicate the same kind of timeout and "Exceeded timeout for canceling conflicting deployments." (http://pastebin.com/XvVDTE5x)
* individual tasks cannot be killed in the UI either (same kind of locked deployment)

Does force=true make any difference in this? Is there any manual way to unlock an app to work around this bug?
