### ISSUE TITLE
Expose More Metrics

### ISSUE THREAD

**Issue by kensipe** [mesosphere/marathon#1489]
we need to expose more metrics from marathon... in particular:

- the time to store in zk (we have a store_timeout, but no way to monitor it)
- zk timeout

**Comment by kolloch** [comment]
Hi @kensipe ,

can you please elaborate? What are the metrics that you would like to see (count, duration, percantiles. histogram, gauge, timer)? On which granularity (over all write requests, for specific write requests)?

Thanks.

**Comment by kolloch** [comment]
@kensipe, you did not reply and the metrics you asked for have been provided before you asked.

If you want something added, it would be great to choose a more specific issue title so that we have a clearly scoped unit of work.
