### ISSUE TITLE
Decouple API (un)marshaling types from internal models

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#1505]
Right now, we have multiple classes that are used both as the (versioned) API representation and as the canonical internal representation of the resource.

The best example of this is `mesosphere.marathon.state.AppDefinition`.

This is a problem because it limits our ability to update the API while minimizing impact on parts of the codebase that _should_ be unaffected by such changes.  It also hinders our ability to maintain concurrent versions of the API during a period of transition.  Ideally we'd be able to introduce a `/v3` API, gradually move it from experimental to stable, and then eventually deprecate the current `/v2` API.

**Comment by kolloch** [comment]
+1 we already talked about that. Probably, we will not be able to do it soon, though.
