### ISSUE TITLE
Add useHostAsHostname to config

### ISSUE THREAD

**Issue by nickpoorman** [mesosphere/marathon#1511]
The hostname of a container in `BRIDGE` networking is being set to the `CONTAINER ID` when I really want it to be the hostname of the slave hosting the container.

Without the container knowing what host it's on, we can't have the akka workers talking to each other without some static setting of --hostname on the docker container.

As simple fix would be to add a param to the config that set's the hostname of the docker container to the host IP.

Docker exposes this as $HOST, however the config doesn't evaluate $HOST when passed to --hostname. See: #1328

This seems like it would be simple enough:

```
{
  "id": "echo-hostname",
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "nickpoorman/docker-echo-hostname",
      "network": "BRIDGE",
      "portMappings": [
        { "containerPort": 8090, "hostPort": 0, "protocol": "tcp" }
      ],
      "useHostAsHostname": true
    }
  },
  "instances": 1,
  "cpus": 1,
  "mem": 128
}
```

Without it this is what we get from `docker-echo-hostname`:

```
HOST = 10.0.203.192
HOSTNAME = 738302d53b9a
hostname = 738302d53b9a
hostname -i = 172.17.0.10
```

Then akka workers try to connect back to `738302d53b9a:<some port>` which clearly won't work.

**Comment by fpgeek** [comment]
+1

**Comment by sepiroth887** [comment]
If you run docker privileged this would automagically set the hostname correctly. Also iirc and u set the slaves hostname to an fqdn it will show as that instead of the ip.

**Comment by sepiroth887** [comment]
Minor clarification: the HOST env is determined by the hostname arg passed to mesos-slave

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4590. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
