### ISSUE TITLE
Health and Metrics doc fixes and improvements

### ISSUE THREAD

**Issue by mhausenblas** [mesosphere/marathon#1517]
In https://mesosphere.github.io/marathon/docs/health-checks.html
- define what is healthy and general guidance
- options 'protocol' doesn't list COMMAND
- change COMMAND to xxx.sh

In addition, change https://mesosphere.github.io/marathon/docs/rest-api.html#get-/metrics to JSON only

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2908. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
