### ISSUE TITLE
App groups and dependencies doc fixes and improvements

### ISSUE THREAD

**Issue by mhausenblas** [mesosphere/marathon#1518]
In https://mesosphere.github.io/marathon/docs/application-groups.html
- fix paths in example, such as `/product/mongo` -> `/product/database/mongo`
- explain paths semantics + best practice: relative rather than absolute
- different example (not MySQL)
- add concrete example (such as Redis + Python)

Also: where are the original (OmniGraffle?) docs?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2897. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
