### ISSUE TITLE
when stop marathon process mesos no delete marathon framework

### ISSUE THREAD

**Issue by 468894985** [mesosphere/marathon#1525]
When I stop marathon process,i found mesos Active Frameworks no delete marathon framework.
why is that?
Thanks!

**Comment by aquamatthias** [comment]
That is by intention. If marathon stops (e.g. reboot the machine) all started processes should still run.
You can shutdown a mesos framework via mesos if you really want to destroy it.
See  #1579 for graceful shutdowns
