### ISSUE TITLE
app_terminated_event is not documented

### ISSUE THREAD

**Issue by BrianHicks** [mesosphere/marathon#1530]
I _really_ needed `app_terminated_event` in the event bus for a project I'm on, and only discovered it after logging all event JSON to the console. It's not in the docs, could someone please add it on the next docs pass?

**Comment by janisz** [comment]
xref https://github.com/mesosphere/marathon/issues/4672

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2872. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
