### ISSUE TITLE
--zk_max_versions doesn't apply to group versions?

### ISSUE THREAD

**Issue by apuckey** [mesosphere/marathon#1533]
I have this option set to 20 on the command line ( 0.8.2-SNAPSHOT 0302c7698e061925dd26017464be74744b616bdb )

The apps in ZK are limited to 20 however i seem to have over 1000+ group:root:timestamp in /marathon/state in ZK

I'm not sure if this is the cause of /v2/apps going slow but /v2/apps takes 2 seconds to return the data and i only have about 30 apps and 40 tasks. 

So a few people loading the WebUI starts to become an issue and the CPU use skyrockets ( compounded by the fact that the WebUI doesn't wait for each /v2/apps call to finish. it just blindly requests one every 4 seconds )

In the commit level above it has the speed fix for the tasks.

Can i manually delete old group versions from ZK? or does this break marathon?

**Comment by bobrik** [comment]
@apuckey can you check with 0.8.1-RC1 if it works better for you? See #1497.

**Comment by apuckey** [comment]
this one: https://github.com/mesosphere/marathon/releases/tag/v0.8.1-RC1 ?

I can try it after tommorrow, I will let you know how it goes

**Comment by apuckey** [comment]
Ok i did it just now and /v2/apps loads in sub 500ms now however i still have 1000+ group versions in zookeeper :-)

**Comment by bobrik** [comment]
@drexin, @kolloch told you :confused:

**Comment by apuckey** [comment]
I had 3 or 4 people on the WebUI with the commitid in the first post and the cpu use on the master went to 100% and the leader kept changing. 

I then firewalled the 3-4 people viewing it and the cpu use came back down. however the /v2/apps was still 2000ms+

**Comment by kolloch** [comment]
@bobrik What did you tell us?

**Comment by bobrik** [comment]
@kolloch that newer versions are much more greedy in terms of CPU (#1497)

**Comment by aquamatthias** [comment]
Hey @apuckey 
I tested this with the current Maraton 0.9.0-RC1.
- Started marathon with --zk_max_versions 1000
- Update one application a 1000 times -> will create 1000 versions of group and app
- Restart marathon with --zk_max_versions 10
  This will not change the state until you change something. 
- Update the application
- Now there are 10 versions of app and group

Just as a side note: you can delete version in zk directly. You recognize a version by the pattern app:name:timestamp or group:name:timestamp.

I will close this ticket. Please reopen if this problem remains.
