### ISSUE TITLE
Seeing an intermittent issue where events stop publishing?

### ISSUE THREAD

**Issue by nugend** [mesosphere/marathon#1535]
I'm seeing an issue where my event subscribers stop receiving events after Marathon has been up for a while. I have a daemon managing alphabetical ranges that processes need to be assigned to and it manages the configurations that need to be handed out by registering task ids and deregistering them when a task is ended for some reason (Killed, Failed, whatever).

Normally, this works fine, but I've been noticing that sometimes, after Marathon has been up for a bit, the tasks stop going out. I bounce the Marathon process and it looks honky dory and the events come in.

Version I'm using is: 0.8.1

If it matters, I noticed that this issue seems to only show up when I have some inactive endpoints in the eventSubscriptions set (I'll leave the subscription in, but turn the listener off for a few days).

**Comment by aquamatthias** [comment]
Can you please provide logs for that? Marathon tries to deliver all events to all subscribers constantly - there is even a retry, if one subscription could not be delivered.

**Comment by nugend** [comment]
I don't have logs specifically associated with this version of the issue (I moved on to focus on ensuring the endpoints are only the active ones). I do have logs showing Marathon go pear shaped when there are too many dead-end eventSubscriptions. Would that be helpful?

**Comment by aquamatthias** [comment]
Hey @nugend if there is a problem with too many dead-end subscriptions, please open a new issue for that. Regarding this problem, it would be helpful, if you can  provide logs showing this problem.

**Comment by nugend** [comment]
Guess I'll close this one then. I don't have the ability to try and reproduce the issue.
