### ISSUE TITLE
JVM-only library for storing state (in Zookeeper)

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#1539]
### Proposal

We should implement storing the state in Zookeeper without relying on any native libraries and without relying on the Mesos release cycle to fix issues. 

We can either just provide another implementation for the existing [State](https://github.com/apache/mesos/blob/master/src/java/src/org/apache/mesos/state/State.java)  interface or provide an improved interface with a similar purpose. Whatever we choose as an interface in our code, we must keep the current data format or provide a migration.

### Problem

Currently, Marathon uses the [org.apache.mesos.state.State](https://github.com/apache/mesos/blob/master/src/java/src/org/apache/mesos/state/State.java) abstraction to persist data. It uses the provided ZookeeperState implementation which uses native code.

This implementation used to cause crashes (#834) repeatedly. These crashes have been solved for Mesos 0.22.1 but at the same time made more likely for older versions. 

It also leads to comments like these https://github.com/mesosphere/marathon/blob/e94d68503ab728b7e92e72ee6484aea364b0b327/src/main/scala/mesosphere/marathon/state/MarathonStore.scala#L124-L130 because the native code doesn't correctly create `ExecutionExceptions` with proper causes.

We also think that the timeout of the ZookeeperState-abstraction doesn't always work. We have seen hanging Zookeeper requests in production.

Mesos is a nice resource scheduler but it is not good framework for holding state.

### Affected/Related Issues

#834 should be solved for older Mesos-Library-Versions as well because they are not used anymore.

When implementing this, we should probably also allow authentication (see #1336).

This issue potentially obsoletes "#706 Add a config flag for selecting the Mesos state implementation" if we use another interface for state abstraction.

### Outlook

In the future, we potentially want to move away from Zookeeper to a more scalable solution for state keeping. In the mean time we have to provide something that works reliably across Mesos versions.

**Comment by ConnorDoyle** [comment]
For reference, here's a previous attempt at this by @swartzrock: https://github.com/mesosphere/mesos-utils/pull/17
