### ISSUE TITLE
Switching to a supported Java version

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#1544]
We are currently still supporting Oracle Java 1.6 which is not supported by Oracle anymore. Even Java 1.7 is not supported anymore. See http://www.oracle.com/technetwork/java/eol-135779.html

We should switch to Java 8 rather soon. For this we need to know if any/how many of our customers still depend on older Java versions.

**Comment by rasputnik** [comment]
We're still on 7, but not really a java shop - just a few scala apps, elasticsearch and zookeeper

**Comment by tangicolin** [comment]
we're also on java 1.7 but switch is possible if all stack is java 8 compliant (zookeeper...)

**Comment by kolloch** [comment]
@rasputnik thanks for your feedback! Would it be possible to switch to 8 or is that a show stopper for you?

**Comment by rasputnik** [comment]
@kolloch we'll have to eventually, so long as the infrastructure pieces support it I can't see it being a dealbreaker. Any ideas of timescales?

**Comment by kolloch** [comment]
We'll wait at least until July to collect feedback.

**Comment by memelet** [comment]
BTW, I have deployed 3 masters (zookeeper, mesos, marathon, chronos) and 2 slaves using oracle-java-8 and have not seen any problems. But its a very new deploy...

**Comment by kolloch** [comment]
Hi @memelet , any Java version related problems so far? Now, that you have more experience with that?

**Comment by kolloch** [comment]
The default JDK for Ubuntu LTS and maybe other distributions is still Java 7.

**Comment by rasputnik** [comment]
CentOS 6 openjdk is still java7 too

**Comment by kolloch** [comment]
We will recommend Java 8 (and not support anything else) starting with Marathon 0.11.

**Comment by kolloch** [comment]
Oh, we still need to document that in our changelog.

**Comment by aquamatthias** [comment]
@lloesche: can you update the native package definitions to depend on java 8?

**Comment by gkleiman** [comment]
The following distros supported by Mesosphere don't include official Java 8 packages:

- Ubuntu 12.04 (LTS)
- Ubuntu 14.04 (LTS)
- Debian 8 (Jessie)

We have to add instructions for installing Java 8  to our documentation.

**Comment by adam-mesos** [comment]
Heard 2 partners complain this week about Marathon dropping Java7 support. Seems they have customers still relying on Java7.
@kolloch @gkleiman @aquamatthias : Are there any technical reasons why Marathon 0.11 wouldn't work with Java7? Are we using new compiler/language features only available in Java8?

**Comment by aquamatthias** [comment]
@adam-mesos we use some libraries that specifically require java 8 (e.g. the latest jetty) as well as our own code base. scala 2.12. will be entirely on java 8 so we need to make that move. Last but not least: Java 6 and 7 have reached EOL so everybody has  to switch anyways...
This version will not run on java7 - I am sorry.
