### ISSUE TITLE
Disable inactive app ID URLs

### ISSUE THREAD

**Issue by joel-hamill** [mesosphere/marathon#1551]
In the Marathon web interface, depending on whether services have a web interface, clicking the URL below the ID name takes you to a  broken link. For example, if you click the URL underneath an instance of HDFS or Kafka you are sent to a 404 page with this text:

```

HTTP ERROR: 404

Problem accessing /. Reason:

    Not Found

Powered by Jetty://
```

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3099. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
