### ISSUE TITLE
Marathon leaders that lose leadership kill tasks upon regaining leadership

### ISSUE THREAD

**Issue by dkesler** [mesosphere/marathon#1553]
If a marathon leader loses leadership but doesn't shutdown (e.g. because of a temporary connection interruption with zookeeper), it is left with stale state.  If it later becomes leader, it will begin running with that stale state, which may result in it killing tasks that have been created since it last became leader.

From what I can tell, my guess is that the problem is that MarathonSchedulerActor.reconcileTasks fetches the list of known tasks via TaskTracker.get.  TaskTracker.get retrieves the tasks from an internal data structure, only falling back to zookeeper state if the internal data structure doesn't contain an entry for the app.  This works fine when an instance becomes leader for the first time since the data structure isn't populated, but if the instance was ever formerly a leader it will have stale data in it.  This means that it may be unaware of the actually running tasks when it performs reconciliation and thus kills them and fires off new tasks (since the old tasks that it was previously aware of also don't exist anymore).  It appears that the actual app definition is fine, although I haven't confirmed that.  (This explanation is a bit speculative  as i'm not super familiar with the code, but MarathonSchedulerActor.reconcileTasks' use of TaskTracker.get put me on the track that eventually led me to be able to reproduce it).

Steps to reproduce:
The scenario that I tested with:  3 marathon instances on version 0.8.0.  3 mesos masters running 0.22.1 and 4 mesos slaves.  We'll call the three marathon masters A, B, and C.  A starts out as the leader, B is next in line, and C is last.  (This should also work with two marathon masters)

1) Start an app with 3 instances.
2) Remove A as leader but leave it running still.  I did this by manually removing the node for A in /marathon/leader.
3) Allow B to take over leadership.  A should attempt to rejoin the leadership but be last in line.
4) Remove B as leader.
5) Allow C to take over leadership.
6) Scale your app down to 0 instances.
7) After the app has scaled down to 0 instances, scale it back up to 3 instances.
6) Remove C as leader.
7) At this point, A will regain leadership.  While reconciling tasks, A will receive a status update for the three tasks for the running app.  Since it does not know about those tasks, A will kill them.  (Sample log output follows)

Sample log output:
May 20 12:54:08 mesos-masterA marathon[4692]: [2015-05-20 12:54:08,843] INFO Received status update for task <app>.227f11d0-ff10-11e4-9246-00505688e7cd: TASK_RUNNING (Reconciliation: Latest task state) (mesosphere.marathon.MarathonScheduler:148)
May 20 12:54:08 mesos-masterA marathon[4692]: [2015-05-20 12:54:08,849] WARN No task for ID <app>.227f11d0-ff10-11e4-9246-00505688e7cd (mesosphere.marathon.tasks.TaskTracker:149)
May 20 12:54:08 mesos-masterA marathon[4692]: [2015-05-20 12:54:08,849] WARN Killing task value: "<app>.227f11d0-ff10-11e4-9246-00505688e7cd"

**Comment by aquamatthias** [comment]
Duplicates #1652

**Comment by xiaods** [comment]
I came across same issue based on marathon Version 0.8.2-SNAPSHOT and mesos 0.22.1.  I have let mesos slave offline, then visit on marathon ui, drop task. but the task can't delete by myself.

in mesos-master.INFO
```
I0708 02:29:43.757499 29367 master.cpp:3461] Performing implicit task state reconciliation for framework 20150630-161535-5105
3322-5050-2957-0001 (marathon) at scheduler-bd8a6b79-d55f-4227-b2d1-3fb830f2e999@10.3.11.2:43380
```

**Comment by dsiegel** [comment]
Why is this bug getting put off to 0.11.0, it seems like it would cause an outage for a service running on Marathon any time it happened. It's also pretty easy to trigger in the normal use of the system.

**Comment by felixb** [comment]
Good  question. Current HA mode is less HA than a single instance.

**Comment by kolloch** [comment]
@dsiegel , @felixb : I feel your pain. The problems in the current implementation are not easy to fix completely. We are working on reimplementing these parts but it is a lot of work.

One can probably bandage some of the problems but we rather prioritize the complete solution.

If you find a way to fix the problems on 0.8.2, 0.9.0 or 0.10.0 you can create a PR against the appropriate release branch.

**Comment by jaytaylor** [comment]
@kolloch Is there a way we can track progress on this reimplementation (e.g. some branch we can watch or reference)?  I am very keen to see what is happening on this front.

**Comment by KirstensAmazing** [comment]
I'm trying to understand here, because I too ran into this problem.  Is it possible this is due to not fully synchronizing state before electing itself as master? 

If true, is this not the same reconciliation solution that hadoop uses to handle the same problem ?  I.e. Would quorum based journaling make a fix easier in this case?


Example here: 

1. 1 Quorum-based Storage
“Quorum-based Storage refers to the HA implementation that uses Quorum Journal Manager (QJM).
In order for the Standby node to keep its state synchronized with the Active node in this implementation, both nodes communicate with a group of separate daemons called JournalNodes…In the event of a failover, the Standby will ensure that it has read all of the edits from the JournalNodes before promoting itself to the Active state. This ensures that the namespace state is fully synchronized before a failover occurs.”

http://blog.cloudera.com/blog/2012/10/quorum-based-journaling-in-cdh4-1/

**Comment by kolloch** [comment]
We want to move all (or 99%) of our in-memory state into actors. The `pk/shiny` branch contains a `WhenLeaderActor` abstraction to only start certain actors when leader and stop them completely if we are not the leader.

The branch contains much more but it does not touch the TaskTracker just yet. That's the next step. We try to move forward iteratively so we will have some soon to be discarded glue code in between. I described it here: https://github.com/mesosphere/marathon/blob/pk/shiny/docs/docs/core-architecture.md

(unfortunately the image link is broken until published)

Actors which have state which needs to be persisted have to load that state before accepting requests, then. There will be some interesting work making reconciliation (synching task state with Mesos) work correctly in all cases.

**Comment by jaytaylor** [comment]
(thumbsup)

Thanks for following up @kolloch

**Comment by geoffroyjabouley** [comment]
Could the fix referenced in the issue be backported to 0.9.3 version?
It seems the code is almost identical, but i don't know enough Marathon sw to be sure of that...

**Comment by sledigabel** [comment]
Hi,

I ran into this problem twice last week and most my containers restart when marathon triggers a reelection.
Interestingly, all running tasks that were submitted as a group don't seem to be impacted, whereas all other tasks submitted as apps were.
Does it make any sense or is it just a coincidence?
Could that be a valid workaround until the bug is fixed?

Thanks

Sebastien

**Comment by aquamatthias** [comment]
Hey @geoffroyjabouley @sledigabel Can you try out 0.11.0-RC2 or master and make sure that the problem is solved?

**Comment by kolloch** [comment]
And @sledigabel: Deploying as a group vs as an app shouldn't make a difference, so I guess it is a coincidence. (The code paths are very similar)

**Comment by EvanKrall** [comment]
I believe I've just been hit by this same bug, but I'm running Marathon 0.11.1, which should include the fix  [2bbdd6b](https://github.com/mesosphere/marathon/commit/2bbdd6b127b81daf1d37149028ad0ff35f66bb93).

Was any further work done on this issue after 0.11.1?

I've isolated the lines mentioning a specific task (`addelivery.main.gitb966eba3.config8c98c8a8.9a6f90f1-e7c3-11e5-b619-a6eb592d7175`) and filtered out noise like health check results and periodic task reconciliation:

```
$ grep 9a6f90f1-e7c3-11e5-b619-a6eb592d7175 stream_marathon_norcal-prod.2016-03-1* | grep -v -e 'Received health result:' -e 'Received status update for task.*TASK_RUNNING'
stream_marathon_norcal-prod.2016-03-11:2016-03-11T19:58:20+00:00 paasta4-r6-sfo2 marathon[4186]: [INFO] [03/11/2016 11:58:20.031] [marathon-akka.actor.default-dispatcher-150] [akka://marathon/user/launchQueue/3/2028-addelivery.main.gitb966eba3.config8c98c8a8] Request to launch task with id 'addelivery.main.gitb966eba3.config8c98c8a8.9a6f90f1-e7c3-11e5-b619-a6eb592d7175', version '2016-03-11T01:23:42.603Z'. 16 tasksToLaunch, 2 in flight. not backing off
stream_marathon_norcal-prod.2016-03-11:2016-03-11T19:58:20+00:00 paasta4-r6-sfo2 marathon[4186]: [INFO] [03/11/2016 11:58:20.166] [marathon-akka.actor.default-dispatcher-177] [akka://marathon/user/launchQueue/3/2028-addelivery.main.gitb966eba3.config8c98c8a8] Task launch for 'addelivery.main.gitb966eba3.config8c98c8a8.9a6f90f1-e7c3-11e5-b619-a6eb592d7175' was accepted. 0 tasksToLaunch, 16 in flight. not backing off
stream_marathon_norcal-prod.2016-03-11:2016-03-11T19:58:21+00:00 paasta4-r6-sfo2 marathon[4186]: [2016-03-11 11:58:21,938] INFO Sending event notification for task [addelivery.main.gitb966eba3.config8c98c8a8.9a6f90f1-e7c3-11e5-b619-a6eb592d7175]: TASK_RUNNING (mesosphere.marathon.core.task.tracker.impl.steps.PostToEventStreamStepImpl$$EnhancerByGuice$$a4177d10:56)
stream_marathon_norcal-prod.2016-03-15:2016-03-15T21:23:56+00:00 paasta7-r11-sfo2 marathon[38305]: [2016-03-15 14:23:56,980] INFO Task addelivery.main.gitb966eba3.config8c98c8a8.9a6f90f1-e7c3-11e5-b619-a6eb592d7175 expunged and removed from TaskTracker (mesosphere.marathon.tasks.TaskTracker$$EnhancerByGuice$$c2edeeb6:111)
stream_marathon_norcal-prod.2016-03-15:2016-03-15T21:23:56+00:00 paasta7-r11-sfo2 marathon[38305]: [2016-03-15 14:23:56,981] INFO Sending event notification for task [addelivery.main.gitb966eba3.config8c98c8a8.9a6f90f1-e7c3-11e5-b619-a6eb592d7175]: TASK_FAILED (mesosphere.marathon.core.task.tracker.impl.steps.PostToEventStreamStepImpl$$EnhancerByGuice$$8b0f1745:56)
stream_marathon_norcal-prod.2016-03-15:2016-03-15T21:23:56+00:00 paasta7-r11-sfo2 marathon[38305]: [2016-03-15 14:23:56,981] INFO initiating a scale check for app [/addelivery.main.gitb966eba3.config8c98c8a8] after task [addelivery.main.gitb966eba3.config8c98c8a8.9a6f90f1-e7c3-11e5-b619-a6eb592d7175}] terminated (mesosphere.marathon.core.task.tracker.impl.steps.ScaleAppUpdateStepImpl$$EnhancerByGuice$$1be7e7ec:34)
stream_marathon_norcal-prod.2016-03-15:2016-03-15T21:23:56+00:00 paasta7-r11-sfo2 marathon[38305]: [2016-03-15 14:23:56,960] INFO Received status update for task addelivery.main.gitb966eba3.config8c98c8a8.9a6f90f1-e7c3-11e5-b619-a6eb592d7175: TASK_FAILED (Docker container run error: Container exited on error: exited with status 1) (mesosphere.marathon.MarathonScheduler$$EnhancerByGuice$$9214efa8:76)
stream_marathon_norcal-prod.2016-03-15:2016-03-15T23:10:51+00:00 paasta4-r6-sfo2 marathon[4186]: [2016-03-15 16:10:51,780] INFO Received status update for task addelivery.main.gitb966eba3.config8c98c8a8.9a6f90f1-e7c3-11e5-b619-a6eb592d7175: TASK_LOST (Reconciliation: Task is unknown to the slave) (mesosphere.marathon.MarathonScheduler$$EnhancerByGuice$$9214efa8:76)
stream_marathon_norcal-prod.2016-03-15:2016-03-15T23:10:51+00:00 paasta4-r6-sfo2 marathon[4186]: [2016-03-15 16:10:51,781] INFO Task addelivery.main.gitb966eba3.config8c98c8a8.9a6f90f1-e7c3-11e5-b619-a6eb592d7175 expunged and removed from TaskTracker (mesosphere.marathon.tasks.TaskTracker$$EnhancerByGuice$$c2edeeb6:111)
stream_marathon_norcal-prod.2016-03-15:2016-03-15T23:10:51+00:00 paasta4-r6-sfo2 marathon[4186]: [2016-03-15 16:10:51,781] WARN Task not found. Do not post event for 'addelivery.main.gitb966eba3.config8c98c8a8.9a6f90f1-e7c3-11e5-b619-a6eb592d7175' (mesosphere.marathon.core.task.tracker.impl.steps.PostToEventStreamStepImpl$$EnhancerByGuice$$a4177d10:42)
stream_marathon_norcal-prod.2016-03-15:2016-03-15T23:10:51+00:00 paasta4-r6-sfo2 marathon[4186]: [2016-03-15 16:10:51,781] INFO initiating a scale check for app [/addelivery.main.gitb966eba3.config8c98c8a8] after task [addelivery.main.gitb966eba3.config8c98c8a8.9a6f90f1-e7c3-11e5-b619-a6eb592d7175}] terminated (mesosphere.marathon.core.task.tracker.impl.steps.ScaleAppUpdateStepImpl$$EnhancerByGuice$$458e0829:34)
$
```

You can see that marathon on paasta4-r6-sfo2 started this task on 2016-03-11, then at some point lost its leadership; paasta7-r11-sfo2 handled this task failing and started up some new tasks; later, paasta4-r6-sfo2 tries to reconcile tasks and can't find this one. It also killed a bunch of tasks it wasn't aware of:

```
2016-03-15T23:10:52+00:00 paasta4-r6-sfo2 marathon[4186]: [2016-03-15 16:10:52,126] WARN Killing task value: "addelivery.main.gitb966eba3.config8c98c8a8.5037b258-e99e-11e5-b4fd-3674531f91a3"
2016-03-15T23:10:52+00:00 paasta4-r6-sfo2 marathon[4186]: [2016-03-15 16:10:52,127] WARN Killing task value: "addelivery.main.gitb966eba3.config8c98c8a8.3cb01341-eaf4-11e5-b4fd-3674531f91a3"
...
```

`taskTracker.clear()` should have been called, since `defeatLeadership` logged only a few minutes after that task was started.

```
stream_marathon_norcal-prod.2016-03-11:2016-03-11T20:02:16+00:00 paasta4-r6-sfo2 marathon[4186]: [2016-03-11 12:02:16,017] INFO Defeat leadership (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$58a92378:280)
stream_marathon_norcal-prod.2016-03-11:2016-03-11T20:02:16+00:00 paasta4-r6-sfo2 marathon[4186]: [2016-03-11 12:02:16,214] INFO Defeat leadership (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$58a92378:280)
```

marathon[4186] on paasta4-r6-sfo2 ends up seeing 31 TASK_LOST tasks, and then killing 31 tasks during reconciliation with `WARN Killing task value: "addelivery.main`... messages. This completely matches my understanding of the bug in this issue.

Why is this still happening if the issue is closed?

**Comment by EvanKrall** [comment]
@kolloch @aquamatthias Sorry for the ping, but I want to make sure my update gets seen. Has this issue been worked on past the commit that closed it? Can I expect versions of Marathon newer than 0.11.1 to not have this bug anymore?

**Comment by liquid-sky** [comment]
I have a three-node marathon cluster (v0.15.3). Restarted Marathon master and when another one took over, the whole world of tasks got re-instantiated. That's really painful.

**Comment by xiaods** [comment]
anyone test it,what now the status for the issue?

**Comment by liquid-sky** [comment]
Looks like after upgrading to 1.1.1 this is no longer happening. I've found [another reference to this issue](https://github.com/mesosphere/marathon/issues/3783).

**Comment by EvanKrall** [comment]
@liquid-sky I'm pretty sure this issue and 3783 are different - 3783 isn't only happening when marathon leadership fails over, and the logs show very different things happening.

**Comment by xiaods** [comment]
hi,  you need consider sync zookeeper and mesos's timezone, it's very important reason for the failover feature.

**Comment by liquid-sky** [comment]
@xiaods, Mesos+Marathon+Exhibitor managed Zookeeper are running on the same host. All three machines are NTP synchronised.
