### ISSUE TITLE
Unexpected update and rollback behavior

### ISSUE THREAD

**Issue by pgkelley4** [mesosphere/marathon#1554]
Updates and rollbacks in marathon don't perform as we were expecting and I am wondering if it is intentional. There are two points in a deploy followed by a rollback that don't perform as expected. 

The deploy and rollback steps:
1) 2 instances are initially running
2) Deploy with a new version and instances == 1
3) Immediately one of the old instances is killed

With minimumHealthCapacity == 1 and maximumOverCapacity == 1 I would have expected the old instances to remain up until the new instances were healthy. But it seems that marathon is using the new value for instances with the minimumHealthCapacity. We would like both of the old instances to remain until the deployment of the new version is complete.

4) Issue a rollback
5) 2 new instances are launched

Ideally, the rollback deploy should see that the version is already deployed and running in this case (with minimumHealthCapacity == 1 and maximumOverCapacity == 1) and just remove the new version instances.

6) The initial instance is then killed once the 2 new rollback instances are healthy.

Are both of these behaviors intentional? 

Or maybe they are a side effect of the minimumHealthCapacity and maximumOverCapacity functionality and make sense for other use cases?

**Comment by kolloch** [comment]
Hi @pgkelley4, I guess what you describe makes sense but it is difficult to change the current behavior. We want to change some of these internals in the next months which might make that easier.

Other customers who need more control over deployments manage their deployments explicitly by creating different apps/groups for new and old versions. You can script the appropriate scaling/rollback yourself.

**Comment by pgkelley4** [comment]
Thanks for the response @kolloch and please keep this behavior in mind as things change.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2834. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
