### ISSUE TITLE
Proxying doesn't work for HTTPS

### ISSUE THREAD

**Issue by TalonOne** [mesosphere/marathon#1556]
I have a cluster of three Marathon instances running HTTPS only (Port 8443) using key store and --disable_http.

In this mode, the Marathon UI & API across the entire cluster seems to be broken. I see the following errors in logs every time an API call is done or the UI makes /apps or /deployments AJAX calls to the backend:

[2015-05-20 20:02:12,654] INFO Proxying request to leader at __marathon3.abc.com:8080__ (mesosphere.marathon.api.LeaderProxyFilter:62)
[2015-05-20 20:02:12,655] WARN Exception while proxying (mesosphere.marathon.api.LeaderProxyFilter:128)
java.net.ConnectException: Connection refused
	at java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:339)
	at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:200)

The reason for this is because the proxy is happening to marathon-leader i.e, marathon3.abc.com:__8080__ and NOT __8443__ which would clearly break as none of our nodes are listening on 8080 after using the --disable_http flag.

Looking into the code, the LeaderProxyFilter.scala is using the latest data from zookeeper. On doing some digging into data in my zookeeper cluster I found the leader stored in there points to 8080, NOT 8443:

----
root@zookeeper2:/a-zookeeper/bin# ./zkCli.sh -server localhost:2181
Connecting to localhost:2181
Welcome to ZooKeeper!
JLine support is enabled

WATCHER::
WatchedEvent state:SyncConnected type:None path:null
[zk: localhost:2181(CONNECTED) 0] ls /marathon/leader 
[member_0000000010, member_0000000009, member_0000000008]
[zk: localhost:2181(CONNECTED) 1] get /marathon/leader/member_0000000010
__marathon3.abc.com:8080__

----

This seems to be a serious bug and breaks the entire system in SSL/TLS only mode. I can't think of any work around to get this working without compromising security.

When done right, Marathon should be proxying to 8443 or whatever port the current leader is serving https traffic on. I hope we can get this fix in as a part of #828. Adding @kolloch for context.

Thanks!

**Comment by TalonOne** [comment]
Now that RC1 is out, I will install this on my cluster to test the behavior. Will write back my findings.

**Comment by kolloch** [comment]
Thanks a lot, @TalonOne!

**Comment by TalonOne** [comment]
@kolloch I had a chance to install my 3 machine cluster and I hit a couple of problems:

- The UI at https://mesos-ip:8444 throws a 403

>HTTP ERROR: 403
>Problem accessing /. Reason:
 >   Forbidden

- The https://$mesosip:8444/v2/apps throws a 502 saying Connection to leader refused.

>HTTP ERROR: 502
>Problem accessing /v2/leader. Reason:
 >   Connection to leader refused

Debug logs from one of the nodes in the cluster when I access /v2/leader: http://pastebin.com/iiTRVcnC

I still see proxying happening to nodes on 8080 while all three of my nodes are https only on https_port 8444

`[2015-06-24 19:30:58,471] INFO Proxying request to GET https://mesos-master3.abc.com:8080/v2/leader from mesos-slave1.abc.com:8080 (mesosphere.marathon.api.JavaUrlConnectionRequestForwarder$:271)`

Also when I browsed into zookeeper I found the following:

>[zk: localhost:2181(CONNECTED) 11] get /marathon/leader/member_0000000053
>**mesos-slave1.abc.com:8080**
>cZxid = 0xe00000102
>ctime = Wed Jun 24 19:44:30 UTC 2015
>mZxid = 0xe00000102
>mtime = Wed Jun 24 19:44:30 UTC 2015
>pZxid = 0xe00000102
>cversion = 0
>dataVersion = 0
>aclVersion = 0
>ephemeralOwner = 0x14e26914bc80021
>dataLength = 38
>numChildren = 0

FWIW, this is how I launch Marathon:

>$JAVA \
>    -Djava.library.path=/opt/mesos/lib:/opt/jdk1.7.0/jre/lib/amd64/server \
>     -jar $MARATHON_JAR \
>     --ssl_keystore_path $MARATHON_HOME/conf/marathonsslstore.jks\
>     --ssl_keystore_password $marathonjkspass \
>     --https_port 8444 \
>    --mesos_authentication_principal abc \
>     --mesos_authentication_secret_file "/opt/marathon/secrets/credentials" \
>     --disable_http \
>     --master zk://192.168.1.1:2181,192.168.1.2:2181,192.168.1.3:2181/mesos \
>     --zk zk://192.168.1.1:2181,192.168.1.2:2181,192.168.1.3:2181/marathon \
>    $@


Please help/clarify..

Thanks!

**Comment by kolloch** [comment]
Hi @TalonOne,

unfortunately, you are right. It is not working. We have an integration test set up which unfortunately sets parameters in a way that is not possible with the complete Marathon process.

I apologize because it was my mistake and I am going to fix that.

Thanks a lot for checking this out before the release!

**Comment by kolloch** [comment]
Hi @TalonOne, BTW since we switched to a separate repository for the UI, you have to do a `git submodule init` and a `git submodule update` if you are running from source.

**Comment by tnn1t1s** [comment]
IMO the leader proxy design should be lifted out. It is especially
problematic if you introduce an authentication mechanism that needs to act
as the originating user. One idea is to have all non-leaders return 500 and
front Marathon with an instance of HAProxy that manages leader detection
and only routes requests to the leader.

**Comment by aquamatthias** [comment]
I see at least those 3 options to this subject:

1. Enable automatic proxying to the leader (as proposed in 0.9.0)
1. Disable proxying, but use redirects (GET, HEAD, OPTIONS)
1. Disable proxying and return an http error code (500?)

We probably should make this behavior configurable?

**Comment by TalonOne** [comment]
@kolloch I tested RC3 and the proxying works with HTTPS as expected. Thanks!

There is one thing that didnt seem right though: My marathon peers were not trusting each others certs as I missed importing my local CA cert into the keystore. But when I do a curl to $MarathonIP:8443/v2/leader...I still get a 200 OK with an SSL exception being thrown on the marathon node. A 200 on an exception doesnt seem right.

About the proxying logic, all three methods mentioned above sound good. But I lean towards having a HAProxy infront of all these nodes as it keeps out SSL complexity out of Marathon and simplifies the design. Also, in the event of a SSL vulnerability like heartbleed, it is likely that proxies would be patched much earlier than individual components.

**Comment by kolloch** [comment]
Hey @TalonOne, the simple thing first: I am all for NOT using the HTTPS support in Marathon and instead doing that in an HAProxy but it seems to be used by some customers. Nothing should prevent you from using HAProxy, though.

In the proxy logic, the keystore you configure for serving HTTPS is also used for verifying the HTTPS certificate of the leader. That's why I am surprised that there are certificate errors.

That said, there shouldn't be a `500` if there is an exception. Can you attach a log excerpt with the full stack trace? thanks a lot.
