### ISSUE TITLE
Configurable refuseTimeout for offers

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#1558]
I have 120 slaves and want to run app with 90 tasks on unique hosts. Currently it takes about a minute and a half to finish deployment (health checks are involved too), I'd like to deploy much faster. Here's how I see deployment process for a single host now:

1. Marathon gets an offer, tries to match with pending tasks.
2. Previous version of the same app is still running on the host, offer declined.
3. Marathon launches one task on another host, kills task on the host with declined offer.
4. Marathon gets an offer from the host with killed previous version of the app, launches task.

Host is unused for at least 5 seconds between 2 and 4, that makes deployment slower.

Looks like Mesos has `Filters` for `driver.launchTasks` and `driver.declineOffer` where you can specify the timeout for an offer, but Marathon does not take advantage of this.

I propose to add cli flag `--offer_refuse_seconds` to Marathon to configure the timeout. I can probably do it myself.

Any thoughts?

**Comment by kolloch** [comment]
I am not quite sure that this should use Filters. Filters actually reduce the offers that we receive from Mesos.

What is required is basically hoarding offers because we expect to be able to use them not now but very soon. Offers that are not declined by frameworks count towards the total resource usage of the framework. Thus a framework is penalized for keeping hold of all resources thus we need to do this smartly.

This is quite a complicated code change, unfortunately.

**Comment by bobrik** [comment]
> Filters actually reduce the offers that we receive from Mesos.

```
message Filters {
  // Time to consider unused resources refused. Note that all unused
  // resources will be considered refused and use the default value
  // (below) regardless of whether Filters was passed to
  // SchedulerDriver::launchTasks. You MUST pass Filters with this
  // field set to change this behavior (i.e., get another offer which
  // includes unused resources sooner or later than the default).
  optional double refuse_seconds = 1 [default = 5.0];
}
```

Setting this to 1.0 instead of 5.0 should give back refused resource offers sooner. Am I wrong here?

**Comment by kolloch** [comment]
Ok, so basically we are not adding filters but reducing the timeout of existing ones.

I am not sure if Mesos communicates all unused resources whenever they become available or just periodically in a fixed interval. I just asked @tillt  (one of the Mesos core guys) to research that for us.

**Comment by bobrik** [comment]
#1931

**Comment by kolloch** [comment]
Yep, that's implemented. Sorry for not following up on this, @bobrik. Didn't get a response for that and I forgot it.
