### ISSUE TITLE
Versioning for recent additions in docs

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#1560]
Currently, we are documenting new features without mentioning at which release we introduce the feature.

Then, after a Marathon release we are updating our information.

This is problematic for (at least) two reasons:

* If we improve the existing documentation, the improvements get only published to the gh-pages branch after the next release and thus the public web page.

* Users who do not use the most recent release, do not see clearly if a feature is supported or not.

Looking through all recent documentation changes and add versioning information. Then we can publish the updated documentation immediately.

In future, we version all additions when adding them and update our documentation more frequently.

**Comment by bobrik** [comment]
Very much :+1:

**Comment by mhausenblas** [comment]
Great! How exactly will this work? ASF style? For example `docs/latest/` points to the most recent version, `docs/0.8.2/` to v0.8.2, etc.?

**Comment by kolloch** [comment]
I did it in a way easier fashion. We just mark sections with the first version to which they apply. This way we only have one documentation which encompasses all versions.

Otherwise, we have to cherry pick all documentation improvements to older versions.

**Comment by bobrik** [comment]
> I did it in a way easier fashion. We just mark sections with the first version to which they apply. This way we only have one documentation which encompasses all versions.

How are you going to deprecate and remove things? One giant doc with all api versions probably doesn't look good.

**Comment by kolloch** [comment]
We will not deprecate things for now.

So let's think about it when we do.
