### ISSUE TITLE
Restart marathon, the task missed but it shows only in mesos

### ISSUE THREAD

**Issue by BrickXu** [mesosphere/marathon#1566]
Hi all,

I met a problem when I restart the marathon. 

There was only one task in the marathon which status is in "STAGING", and after restart, I can not find the task in marathon, but it shows in mesos "active tasks", how could I synchronize the task from mesos to marathon?

ENV:
marathon 0.7.5
mesos 0.22.1

**Comment by kolloch** [comment]
Any chance you could try that with a recent Marathon release, e.g. 0.8.2-RC3?

**Comment by kolloch** [comment]
Please reopen if you experienced the same error with a recent version.

**Comment by BrickXu** [comment]
@kolloch thank you, I've upgraded marathon from 0.7.5 to 0.8.1.
