### ISSUE TITLE
http_endpoints not being split on ","

### ISSUE THREAD

**Issue by jaytaylor** [mesosphere/marathon#1569]
Corresponding with the [configuration shown in the documentation](https://mesosphere.github.io/marathon/docs/event-bus.html), I expected all 3 of my endpoints to be hit.  Instead marathon is failing to split on the commas and just sends only 1 request.

$ cat /etc/marathon/conf/http_endpoints:

    http://mesos-primary3a:8000/v1/eventBus,http://mesos-primary1a:8000/v1/eventBus,http://mesos-primary2a:8000/v1/eventBus

Resulting HTTP log:

    method=POST
    url=/v1/eventBus,http://mesos-primary1a:8000/v1/eventBus,http://mesos-primary2a:8000/v1/eventBus
    remoteAddr=172.1.2.180:33178
    referer=

src/main/scala/mesosphere/marathon/event/http/HttpEventModule.scala:

```scala
trait HttpEventConfiguration extends ScallopConf {

  lazy val httpEventEndpoints = opt[List[String]]("http_endpoints",
    descr = "The URLs of the event endpoints master",
    required = false,
    noshort = true)
}
```

It doesn't look like the value is being split appropriately here.

**Comment by jaytaylor** [comment]
Thanks for resolving this @kolloch and friends!

**Comment by kolloch** [comment]
Thank @gkleiman ! (And thanks for the thanks ;) )
