### ISSUE TITLE
Release 0.8.2-RC4

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#1574]

**Comment by brockoffdev** [comment]
@kolloch any idea when 0.8.2 will be made official? Used documentation today to setup "forcePullImage", and was pulling out my hair trying to figure out why it wasn't working until I realized 0.8.1 was the version that is currently installed by default :). 

I think this has been discussed elsewhere, but can we make sure that mesosphere docs are up-to-date based on the current version passed through on apt and yum?

**Comment by kolloch** [comment]
Hi @brockoffdev ,

0.8.2 will be released tomorrow (one week after the release of RC4) if no regressions get reported today.

Basically, getting our API documentation "right" has proven to be not really easy.

Challenges:
* We want to accept and publish PRs with documentation improvements quickly and not only with the next release.
* We want to use the fewest possible developer cycles on the documentation process. Documenting itself is important but the process should be very lean.
* We still want to make clear what version an option is available in.

Our current solution is to indicate the Marathon version that introduced a feature in the docs and publish them as fast as possible. So you might see features in the docs that aren't available for you.

It would be nice to select your version and only see features relating to that but it would require a lot of effort by us.

If you have suggestions on how to improve this without spending more effort on this, we are happy to hear them.
