### ISSUE TITLE
Marathon should have an endpoint, that signals if the instance is healthy

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#1577]
Marathon should report via an endpoint whether it is healthy or not.
This is also needed for the Marathon on Marathon use case.

**Comment by felixb** [comment]
This endpoint should work even when http basic auth is enabled.

**Comment by ddoc** [comment]
It would be nice to enable/disable basic auth for this endpoint separately from others.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3414. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
