### ISSUE TITLE
Implement shutdown endpoint, that removes all state created and stops the service

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#1579]
We need a REST endpoint that will destroy marathon and also remove all the state that was created.
- [ ] Add /shutdown endpoint.
- [ ] Kill all tasks started via marathon
- [ ] Remove zookeeper state 
- [ ] End process

**Comment by bobrik** [comment]
I'd be nice to have some sanity check, maybe enabling this endpoint with cli flag makes sense.

**Comment by aquamatthias** [comment]
See #712

**Comment by air** [comment]
To be clear this is to shutdown Marathon itself right? Nothing to do with stopping apps.

**Comment by kolloch** [comment]
Yes, I think the reference to #712 is confusing.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3611. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
