### ISSUE TITLE
Docker containers doc improvement

### ISSUE THREAD

**Issue by mhausenblas** [mesosphere/marathon#1584]
The [Running Docker Containers on Marathon](https://mesosphere.github.io/marathon/docs/native-docker.html) documentation is, concerning volumes usage, too generic and misleading. We should make clear that volumes should only be used for non-sandbox cases such as cluster-wide NFS mounts or cases where through configuration management a certain path exists in a predictable way on the Docker host (==Mesos worker node).

**Comment by kolloch** [comment]
Well, the auto-mounting of the sandbox directory inside of the container is useful.

**Comment by mhausenblas** [comment]
If it's useful, can you give one concrete example *how* you would use it?

**Comment by kolloch** [comment]
Create a docker container which serves static from $HTTP_ROOT.

```json
{
  "instances": 1,
  "cpus": 0.1,
  "mem": 64,
  "disk": 200,
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "peters-nginx",
      "network": "BRIDGE",
      "portMappings": [
        { "hostPort": 0, "containerPort": 80 }
      ]
    }
  },
  "env": {
    "HTTP_ROOT": "/mnt/mesos/sandbox/m-shop-static"
  },
  "uris": [
    "https://dl.dropboxusercontent.com/.../m-shop-static.zip"
  ]
}
```

**Comment by mhausenblas** [comment]
This is a useful example, indeed. However, in order to make it self-explaining, one would need the full story: how is `HTTP_ROOT` used/passed over and what's the content of the `peters-nginx` Dockerfile.

**Comment by jstabenow** [comment]
A small example for logs:

**Dockerfile:**
```sh
FROM ubuntu:14.04

RUN apt-get install -y nginx

RUN sed -i 's/worker_processes 4;/worker_processes 1;/g' /etc/nginx/nginx.conf; \
    sed -i 's/access_log.*/access_log \/mnt\/mesos\/sandbox\/access.log;/g' /etc/nginx/nginx.conf; \
    sed -i 's/error_log.*/error_log \/mnt\/mesos\/sandbox\/error.log;/g' /etc/nginx/nginx.conf; \
    sed -i 's/^pid/daemon off;\npid/g' /etc/nginx/nginx.conf

CMD ["/usr/sbin/nginx"]
```
Sed comes from [MarvAmBass](https://github.com/MarvAmBass/docker-nginx-ssl-secure)

**Marathon:**
```json
{
    "instances": 1,
    "cpus": 1.0,
    "mem": 512,
    "container": {
        "type": "DOCKER",
        "docker": {
            "image": "mydockerimage",
            "network": "BRIDGE",
            "portMappings": [
                {
                    "hostPort": 0,
                    "containerPort": 80
                }
            ]
        }
    }
}
```

**Comment by jstabenow** [comment]
@kolloch example (peters-nginx):

**run.sh:**
```sh
#/bin/bash
HTTP_ROOT=${HTTP_ROOT}
echo "server {
        listen 80 default_server;
        listen [::]:80 default_server ipv6only=on;
        root $HTTP_ROOT;
        index index.html index.htm;
        server_name localhost;
        location / {
                try_files $uri $uri/ =404;
        }
}" > /etc/nginx/sites-enabled/default
/usr/sbin/nginx
```
**Dockerfile:**
```sh
FROM ubuntu:14.04

RUN apt-get install -y nginx
RUN sed -i 's/^pid/daemon off;\npid/g' /etc/nginx/nginx.conf

ADD run.sh /run.sh
RUN chmod +x /run.sh

CMD ["/run.sh", "-n"]
```

**Comment by mhausenblas** [comment]
Thanks a lot, @jstabenow — I'll use this one!

**Comment by kolloch** [comment]
BTW, here is an issue about relative volume mounts in the Mesos JIRA:

"Support relative host paths for container volumes"
https://issues.apache.org/jira/browse/MESOS-2374

This would allow @mhausenblas use case without new docker containers. It should also solve using docker containers needing volume mounts for configuration.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3056. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
