### ISSUE TITLE
dryRun option is not described for PUT /v2/groups/{group}

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#1595]
It exists in example and in docs, but there's no explanation (even if it is obvious).

**Comment by kolloch** [comment]
Thanks for reporting this. We would be happy about contributions to the documentation as well.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3317. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
