### ISSUE TITLE
Move away from using instances in favour of tasks

### ISSUE THREAD

**Issue by ssk2** [mesosphere/marathon#1599]
Marathon uses "instances" to describe the number of desired tasks for an application. The API uses instances within application definitions and when describe applications. However, we also list individual tasks for each application, as well as the number of tasks by state (e.g. `tasksRunning`, `tasksHealthy` and so on).

In the user interface we show the equally confusing "Tasks / Instances" column which also mixes up what are apparently the same thing:
![image](https://cloud.githubusercontent.com/assets/355705/7971011/a96f825a-09f6-11e5-8d80-b4fdfd4cef44.png)

Tasks are a native Mesos concept, instances are not. The instances terminology can confuse users who are new to Mesos and Marathon until they figure out that 1 instance = 1 task. 

I propose changing instances to something like `tasksRequested` or `tasksDesired` (or any variant that is consistent with API naming). This will reduce confusion and make the API and user interface more consistent.

**Comment by kolloch** [comment]
I like it.

Unfortunately, for backwards compatibility we would have to allow both `instances` and `tasksRequested` and also include both in our JSON responses. I like that less.

**Comment by ssk2** [comment]
As a breaking change, perhaps we might want to consider this for the 1.0?

**Comment by kolloch** [comment]
@ConnorDoyle currently tries to decouple our API from our internal models. This would allow API v2/v3 in parallel and we could rename this there.

**Comment by ConnorDoyle** [comment]
@kolloch +1
Repurposed the `API` label and renamed it to `API v3` to group these.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3001. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
