### ISSUE TITLE
docker: hostPath in volumes seems to be ignored

### ISSUE THREAD

**Issue by memelet** [mesosphere/marathon#1600]
mesos: 0.22.1
marathon: 0.8.1
docker: 1.6.2

I define:

```
"volumes": [{
  "containerPath": "/var/log/vimana",
  "hostPath": "/var/log/vimana"
}]    
```

But the mounts I get are:

```
"Volumes": {
        "/mnt/mesos/sandbox": "/tmp/mesos/slaves/20150522-122903-2693333002-5050-7694-S9/frameworks/20150522-085224-378208266-5050-5138-0000/executors
        "/var/log/vimana": "/var/lib/docker/vfs/dir/38cf9ddf3c342baec70ade21a9cce2c267f909986f06cc101f5ecb672ae99f40"
    },
```

The volume is declared in the docker file, so this behavior seems to as if the containerizer just dropped my mount.

**Comment by kolloch** [comment]
Thanks for reporting this.

**Comment by memelet** [comment]
Is there any way to work around this? We pretty much can't use marathon for most of our containers because they need to get some config from the host file system. It also screws out out logstash log collection.

**Comment by gkleiman** [comment]
@memelet Can you share the app definition with us? I couldn't reproduce this.

I tried the following:

I executed the following in my only mesos slave (if you use OS X then you have to do this on your VM):

```bash
mkdir -p /tmp/foobar
echo "HELLO WORLD!" >/tmp/foobar/test
```

Then I used the following app definition:

```json
{
  "id": "/volumes",
  "cmd": "cat /var/data/test ; sleep 200; true",
  "container": {
    "type": "DOCKER",
    "docker": {
      "network": "HOST",
      "image": "ubuntu:15.04"
    },
    "volumes": [
      {
        "containerPath": "/var/data",
        "hostPath": "/tmp/foobar",
        "mode": "RO"
      }
    ]
  },
  "cpus": 1.5,
  "mem": 256.0,
  "executor": "",
  "constraints": [],
  "instances": 1,
  "ports": []
}
```

Then I went to the Mesos console, inspected the STDOUT of the running task and it contained the contents of the testing file.

**Comment by memelet** [comment]
Wow, that would be great if it's my fault. Let me take a closer look and get back. Thanks!

**Comment by memelet** [comment]
No, doesn't seem to work for me.

via marathon:
```
         {
            "constraints": [],
            "container": {
                "docker": {
                    "image": "systeminsights/svc-auth:1.2.0-136",
                    "network": "BRIDGE",
                    "portMappings": [
                        {
                            "containerPort": 3000,
                            "hostPort": 0,
                            "protocol": "tcp"
                        }
                    ],
                    "volumes": [
                        {
                            "containerPath": "/var/log/vimana",
                            "hostPath": "/var/log/vimana"
                        }
                    ]
                },
                "type": "DOCKER"
            },
            "cpus": 0.25,
            "env": {
                "VI_LOG_DIR": "/var/log/vimana"
            },
            "healthChecks": [
                {
                    "gracePeriodSeconds": 5,
                    "intervalSeconds": 60,
                    "path": "/api/v1/auth/health"
                }
            ],
            "id": "/svc/auth",
            "instances": 2,
            "mem": 64,
            "ports": [],
            "upgradeStrategy": {
                "minimumHealthCapacity": 0.5
            },
            "uris": [
                "http://10.0.137.160:5080/v2/artifacts/.dockercfg"
            ]
        }
```

Docker inspect shows the volume mounted at /mnt/docker/volumes:
```
"Volumes": {
        "/mnt/mesos/sandbox": "/mnt/mesos/slaves/20150522-122903-2693333002-5050
        "/var/log/vimana": "/mnt/docker/volumes/450cbd9b7bede7a2afeefbdb54d52bca
    },
```
And indeed that is where the log file is created and written to.

Via docker daemon:
```
docker run --name svc-auth -v /var/log/vimana:/var/log/vimana -e "VI_LOG_DIR=/var/log/vimana" systeminsights/svc-auth:1.2.0-136
```

Docker inspect shows the volume mounted where indicated:
```
    "Volumes": {
        "/var/log/vimana": "/var/log/vimana"
    },
```
In this case the log file is created at /var/log/vimana and written to.

**Comment by memelet** [comment]
Another tidbit. I changed the mode to RO just see how that was reflected, yet the volume (at the wrong location) is still mounted RW.

marathon:
```
            "volumes": [
                        {
                            "containerPath": "/var/log/vimana",
                            "hostPath": "/var/log/vimana",
                            "mode": "RO"
                        }
                    ]
```
docker inspect:
```
    "Volumes": {
        "/mnt/mesos/sandbox": "/mnt/mesos/slaves/20150522-122903-2693333002-5050-7694-S22/frameworks/2015052
        "/var/log/vimana": "/mnt/docker/volumes/6d6190d5bd793101aa034fec0d6e1aba31094c56ac1e331b3c9204b1a076
    },
    "VolumesRW": {
        "/mnt/mesos/sandbox": true,
        "/var/log/vimana": true
    },
```

**Comment by gkleiman** [comment]
I suspected that somehow the volumes defined in the app definition were not overriding the ones in the Dockerfile, but that doesn't seem to be the case (with Docker version 1.7.0, build 0baf609).

Can you try again with the following test case?

Create a Dockerfile with a volume in the mesos slaves:

```Dockerfile
FROM busybox
VOLUME /vol
```

Build the image:

```bash
docker build -t gk-volumes-test .
```

Create something in the volume:

```bash
echo "HELLO WORLD!" >/tmp/foobar/test
```

And finally use the app definition:

```json
{
  "id": "/volumes",
  "cmd": "cat /vol/test ; sleep 200; true",
  "container": {
    "type": "DOCKER",
    "docker": {
      "network": "HOST",
      "image": "gk-volumes-test:latest"
    },
    "volumes": [
      {
        "containerPath": "/vol",
        "hostPath": "/tmp/foobar",
        "mode": "RO"
      }
    ]
  },
  "cpus": 1.5,
  "mem": 256.0,
  "executor": "",
  "constraints": [],
  "instances": 1,
  "ports": []
}
```

**Comment by memelet** [comment]
When mounting the volume RO it works as you are seeing. But when mounting for write it does not.

```
{
  "id": "/volumes",
  "cmd": "cat /vol/test ; echo 'OUTPUT...' >> /vol/out.txt; sleep 200; true",
  "container": {
    "type": "DOCKER",
    "docker": {
      "network": "HOST",
      "image": "gk-volumes-test:latest"
    },
    "volumes": [
      {
        "containerPath": "/vol",
        "hostPath": "/tmp/volume-test",
        "mode": "RW"
      }
    ]
  },
  "cpus": 1.5,
  "mem": 256.0,
  "executor": "",
  "constraints": [],
  "instances": 1,
  "ports": []
}
```

docker inspect:

```
    "Volumes": {
        "/mnt/mesos/sandbox": "/mnt/mesos/slaves/20150522-122903-2693333002-5050-7694-S23/frameworks/20150522-085224-378208266-5050-5138-0000/executors/volumes.4012d770-29ee-11
        "/vol": "/mnt/docker/volumes/e0eed8355e211f927b14cfc020a5de50603c86cda7ae023e87a6eff267ef96a3/_data"
    },
```

```
$ sudo cat /mnt/docker/volumes/e0eed8355e211f927b14cfc020a5de50603c86cda7ae023e87a6eff267ef96a3/_data/out.txt
OUTPUT...

$ ls -l /tmp/volume-test
total 0
```

**Comment by gkleiman** [comment]
I just tried using the RW mode and it also worked fine.

It would be useful if you could start the mesos-slave with increased verbosity:

```SHELL
GLOG_v=1 /usr/local/sbin/mesos-slave --master=127.0.0.1:5050 --ip=127.0.0.1 --containerizers=docker,mesos --executor_registration_timeout=5mins -v
```

Then we can know exactly what parameters are being passed to docker by the mesos executor. In my case the command line is:

```
I0714 14:34:14.850263 149852160 docker.cpp:462] Running docker run -d -c 1638 -m 301989888 -e MESOS_TASK_ID=volumes.a302ffef-2a24-11e5-96a2-3aa1569139cd -e MARATHON_APP_ID=/volumes -e MARATHON_APP_VERSION=2015-07-14T12:34:10.191Z -e HOST=localhost -e MESOS_SANDBOX=/mnt/mesos/sandbox -v /tmp/foobar:/vol:rw -v /tmp/mesos/slaves/20150713-094332-16777343-5050-93196-S0/frameworks/20150601-122425-16777343-5050-2841-0001/executors/volumes.a302ffef-2a24-11e5-96a2-3aa1569139cd/runs/e2f2f860-fc5c-40f9-b6bc-2a95ef9ecd3e:/mnt/mesos/sandbox --net host --entrypoint /bin/sh --name mesos-e2f2f860-fc5c-40f9-b6bc-2a95ef9ecd3e gk-volumes-test:latest -c echo 'hello world!!!' >/vol/test_file ; sleep 200; true
```

**Comment by ajaybhatnagar** [comment]
I am encountering same issue too. Do not see the contents of the volume  loaded in the container.

Environment:
docker-engine                       1.7.1-0~trusty
marathon                                0.9.0-1.0.381.ubuntu1404
mesos                                     0.22.1-1.0.ubuntu1404

1. docker inspect shows on the container launched by marathon:
  Note the location of volume /es below for comparing with directly launched container later . Why it is pointing to /var/lib/docker/volumes when alternate location /es/esm is specified ?

    "Volumes": {
        "/es": "/var/lib/docker/volumes/369808aae5640f5743cd3fa4e48944024e3132968583fafd223ffbf95e6985c4/_data",
        "/hostproc": "/proc",
        "/mnt/mesos/sandbox": "/tmp/mesos/slaves/20150723-173753-2777017354-5050-1304-S0/frameworks/20150527-184449-2777017354-5050-1397-0000/executors/es-3.39af21be-3163-11e5-9f90-02000aec85a5/runs/4058b6c1-4cbf-414d-b6e8-41a0d1b818de",
        "/var/run/docker.sock": "/var/run/docker.sock",
        "/w": "/var/lib/docker/volumes/d8d0a3d0dcb8ae41118f17b87f65fdacc0105c77728393d6bc3bd9206d4443ed/_data"
    },
    "VolumesRW": {
        "/es": true,
        "/hostproc": true,
        "/mnt/mesos/sandbox": true,
        "/var/run/docker.sock": true,
        "/w": true
    },

2. Check with in the launched container does not show the volume mounted nor the files of the volume. (expected volume mounted as /es shown  as shown in next item no. 3 of this message)

root@estest:/es# df -m
Filesystem                                             1M-blocks  Used Available Use% Mounted on
rootfs                                                      3779  2559      1009  72% /
none                                                        3779  2559      1009  72% /
tmpfs                                                       8023     0      8023   0% /dev
shm                                                           64     0        64   0% /dev/shm
/dev/disk/by-uuid/a81694cb-75de-490b-9b06-8c677fa112c9      3779  2559      1009  72% /w
tmpfs                                                       1605     1      1605   1% /run/docker.sock
tmpfs                                                       8023     0      8023   0% /proc/kcore
tmpfs                                                       8023     0      8023   0% /proc/timer_stats

3. Container launched with docker command line on the node shows the same external volume mounted. It is using correct path to the volume to be mounted.
docker run -d --name esm01 -p 9200-9300:9200-9300  -v /es/esm:/es esimage

from docker inspect esm01:

    "Volumes": {
        "/es": "/es/esm",
        "/hostproc": "/proc",
        "/var/run/docker.sock": "/var/run/docker.sock",
        "/w": "/var/lib/docker/volumes/d8d0a3d0dcb8ae41118f17b87f65fdacc0105c77728393d6bc3bd9206d4443ed/_data"
    },
    "VolumesRW": {
        "/es": true,
        "/hostproc": true,
        "/var/run/docker.sock": true,
        "/w": true
    },


root@dmslave-01:/var/log/mesos# docker exec -it esm01 bash
root@esm01:/es# df -m
Filesystem                                             1M-blocks  Used Available Use% Mounted on
....
/dev/disk/by-uuid/a81694cb-75de-490b-9b06-8c677fa112c9      3779  2559      1009  72% /w
/dev/vdb1                                                  50268    52     47640   1% /es
tmpfs                                                       1605     1      1605   1% /run/docker.sock
...
4. Script used:

#!/bin/sh -x
curl http://10.236.133.167:8080/v2/apps  \
  -X POST \
  -H 'Content-type: application/json' \
  -d '{
    "id": "es-3",
    "cmd": "tail -f /etc/resolv.conf",
    "cpus": 0.5,
    "mem": 512.0,
    "instances": 3,
    "constraints": [["hostname", "UNIQUE"]],
    "container": {
      "type": "DOCKER",
      "docker": {
        "image": "esimage",
        "network": "BRIDGE",
        "portMappings": [
          { "containerPort": 9200, "hostPort": 0 },
          { "containerPort": 9300, "hostPort": 0 }
        ],
        "parameters": [
          { "key": "hostname", "value": "estest.weave.local" }
        ]
      }
    },
    "volumes": [
      {
        "containerPath": "/es",
        "hostPath": "/es/esm",
        "mode": "RW"
      }
    ]
  }'

Thanks
Ajay

**Comment by gkleiman** [comment]
@ajaybhatnagar thanks for reporting this.

Knowing the exact parameters being passed to docker by the mesos executor would be really useful.

You can get them from the mesos-slave logs if you start it with increased verbosity:

GLOG_v=1 /usr/local/sbin/mesos-slave --master=127.0.0.1:5050 --ip=127.0.0.1 --containerizers=docker,mesos --executor_registration_timeout=5mins -v

**Comment by ajaybhatnagar** [comment]
Thanks for quick response.
My mesos-masters are on another set of nodes  so I am afraid it  suggested startup may not work but I have added  the config for detailed logging in default setup or is there some other way to define debug logging from configuration. Is this sufficient for your logs info you need ?

root@dmslave-01:/var/log/mesos# cat /etc/default/mesos-slave
MASTER=`cat /etc/mesos/zk`
export DOCKER_HOST=tcp://127.0.0.1:12375
export MESOS_LOGGING_LEVEL=ERROR

**Comment by gkleiman** [comment]
You might have to replace:

export MESOS_LOGGING_LEVEL=ERROR

with

export GLOG_v=1

In order to docker cmd run by the executor.

**Comment by ajaybhatnagar** [comment]
Here is the relevant part in my opinion. It did not  show the volume mounts options on command . If you want full  logs, I will upload them.

I0724 14:20:25.402575  5691 docker.cpp:626] Starting container '0d779b94-f415-434e-ab0d-cf3af3f343cd' for task 'es-3.1f9ae105-320f-11e5-9f90-02000aec85a5' (and executor 'es-3.1f9ae105-320f-11e5-9f90-02000aec85a5') of framework '20150527-184449-2777017354-5050-1397-0000'
I0724 14:20:25.402813  5691 docker.cpp:808] Running docker inspect esimage:latest
I0724 14:20:25.493381  5695 docker.cpp:253] Docker pull esimage completed
I0724 14:20:25.493710  5695 docker.cpp:462] Running docker run -d -c 614 -m 570425344 -e MARATHON_APP_VERSION=2015-07-24T14:20:19.585Z -e HOST=10.236.133.171 -e MESOS_TASK_ID=es-3.1f9ae105-320f-11e5-9f90-02000aec85a5 -e PORT=31503 -e PORT_9200=31503 -e PORTS=31503,31504 -e PORT1=31504 -e PORT_9300=31504 -e MARATHON_APP_ID=/es-3 -e PORT0=31503 -e MESOS_SANDBOX=/mnt/mesos/sandbox -v /tmp/mesos/slaves/20150723-173753-2777017354-5050-1304-S3/frameworks/20150527-184449-2777017354-5050-1397-0000/executors/es-3.1f9ae105-320f-11e5-9f90-02000aec85a5/runs/0d779b94-f415-434e-ab0d-cf3af3f343cd:/mnt/mesos/sandbox --net bridge --hostname=estest.weave.local -p 31503:9200/tcp -p 31504:9300/tcp --entrypoint /bin/sh --name mesos-0d779b94-f415-434e-ab0d-cf3af3f343cd esimage -c tail -f /etc/resolv.conf
I0724 14:20:25.996450  5691 docker.cpp:277] Checkpointing pid 5926 to '/tmp/mesos/meta/slaves/20150723-173753-2777017354-5050-1304-S3/frameworks/20150527-184449-2777017354-5050-1397-0000/executors/es-3.1f9ae105-320f-11e5-9f90-02000aec85a5/runs/0d779b94-f415-434e-ab0d-cf3af3f343cd/pids/forked.pid'
I0724 14:20:25.997263  5691 docker.cpp:674] Running logs() {
  docker logs --follow $1 &
  pid=$!
  docker wait $1 >/dev/null 2>&1
  sleep 10
  kill -TERM $pid >/dev/null 2>&1 &
}
logs mesos-0d779b94-f415-434e-ab0d-cf3af3f343cd

**Comment by gkleiman** [comment]
@ajaybhatnagar thanks for getting back to me so quickly.

I think I know what the problem is. The docker volumes definition must go inside the "container" section of the app definition, and not on the root level.

Please try again with the following app definition:

```json
{
  "id": "es-3",
  "cmd": "tail -f /etc/resolv.conf",
  "cpus": 0.5,
  "mem": 512.0,
  "instances": 3,
  "constraints": [["hostname", "UNIQUE"]],
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "esimage",
      "network": "BRIDGE",
      "portMappings": [
        { "containerPort": 9200, "hostPort": 0 },
        { "containerPort": 9300, "hostPort": 0 }
      ],
      "parameters": [
        { "key": "hostname", "value": "estest.weave.local" }
      ]
    },
    "volumes": [
      {
        "containerPath": "/es",
        "hostPath": "/es/esm",
        "mode": "RW"
      }
    ]
  }
}
```

**Comment by gkleiman** [comment]
@memelet what I just told @ajaybhatnagar might also help you.

You define your volumes in .container.docker.volumes and they should be defined in .container.volumes

**Comment by ajaybhatnagar** [comment]
Perfect.  It worked.Thanks Gaston.

**Comment by memelet** [comment]
Gaston, you are my hero! And thanks much @ajaybhatnagar helping to chase this down.
