### ISSUE TITLE
Build should check for formatting changes

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#1605]
We automatically format the code in our build. This doesn't prevent pushing source code without formatting it first. Our build should check that.

**Comment by jeschkies** [comment]
I'd say this is a no-fix for now.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2988. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
