### ISSUE TITLE
Aggregate scalar resources across roles

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#1606]
Currently, all scalar resources have to be satisfied by one role. So, for example, if you specify that you need two CPUs and one is offered with role "*" and one is offered with role "public", you task will not launch.

For port resources already all resources disrespecting their roles are considered.

**Comment by ConnorDoyle** [comment]
More generally, Marathon could combine offers from the same slave (collected over a short hoarding period) to fight offer fragmentation.

**Comment by kolloch** [comment]
We hand back all offers we don't use immediately back to Mesos. Shouldn't then mesos defragment them for us? Even Aurora with resource hording simply returns the offers directly to Mesos if it detects multiple offers of the same host. Do I miss something?
