### ISSUE TITLE
Marathon URL in task environment

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#1607]
Marathon can be used for simple service discovery via its REST API. Thus it we should make it easy for tasks to reach Marathon on startup.

We can do this by introducing new automatic environment variables, e.g.
- `MARATHON_URL="https://marathon.atyourcompany.com"`

This should use the value of `--webui_url` if that's supplied and otherwise use the autodetected leader URL.

**Comment by kolloch** [comment]
This is very close to #1473, just URLs instead of IPs. We can easy have both.

**Comment by nugend** [comment]
Problem being that that will only list the currently active instance at task startup time when running in HA. To the best of my knowledge there is no way of updating an environment variable in a running process.

If this was going to happen and it was going to be reliable, it'd need to be a proxy the mesos executor exposed.

**Comment by kolloch** [comment]
You should set up load balancing for your Marathon instances and then specify the load balanced endpoint with `--webui_url`.

If you don't do that, you can still use this for service discovery while starting up your task. If you cannot redetermine where your dependencies are running at and fail to reach them, make your task fail. It will be restarted and the new task will get the current information.

**Comment by nugend** [comment]
Good idea for most people. *Probably* not workable inside my company :/

But now that you mention it, I can't consider my situation a reasonable objection to providing this capability for everyone else who works in a reasonable environment.

**Comment by rasputnik** [comment]
Really nice feature - as the Marathon API already codes dependencies etc. it seems odd not to provide a way for apps to query it.

Agree the master URL may cause issues, but I think @kolloch points out a potential fix. If such variables are only used at deploy time I don't see a need for anything more complicated than 'retry until the URL is reachable'.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3297. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
