### ISSUE TITLE
Add GET v2/tasks/{taskId}

### ISSUE THREAD

**Issue by nugend** [mesosphere/marathon#1609]
Should return single task associated with appropriate taskId. This relieves the API user of having to retrieve the whole set and process the entire JSON payload to get information associated with a single task.

Sample return for `GET v2/tasks/bridged-webapp.eb76c51f-4b4a-11e4-ae49-56847afe9799`:

```
{
    "appId": "/bridged-webapp",
    "healthCheckResults": [
        {
            "alive": true,
            "consecutiveFailures": 0,
            "firstSuccess": "2014-10-03T22:57:02.246Z",
            "lastFailure": null,
            "lastSuccess": "2014-10-03T22:57:41.643Z",
            "taskId": "bridged-webapp.eb76c51f-4b4a-11e4-ae49-56847afe9799"
        }
    ],
    "host": "10.141.141.10",
    "id": "bridged-webapp.eb76c51f-4b4a-11e4-ae49-56847afe9799",
    "ports": [
        31000
    ],
    "servicePorts": [
        9000
    ],
    "stagedAt": "2014-10-03T22:16:27.811Z",
    "startedAt": "2014-10-03T22:57:41.587Z",
    "version": "2014-10-03T22:16:23.634Z"
}
```

This would also add consistency in that GET v2/apps/{appId}, GET v2/deployments/{deploymentId} and GET v2/groups/{groupId} are all available

**Comment by kolloch** [comment]
Thanks for the suggestion. Maybe we should add it already just for consistency. But do you have a specific use case in mind? When do you already now the task ID and want to requery information about the task?

**Comment by shoenig** [comment]
I've been considering writing some deploy glue that manually checks the health of each Task using endpoints not associated with healthchecks registered to the App in Marathon. Having this per Task endpoint is not strictly necessary but it would be convenient.

**Comment by nugend** [comment]
So what I'm doing is running a config management daemon that waits for tasks to contact it and then hand out part of an alphabetical range. The tasks register with their taskIDs and then the daemon stores information about which config is tied to which task ID. I wanted to enrich that by having the port and host stored. I *thought* about having the task send the port and host to the daemon, but I figured it was better to treat Marathon as the canonical source.
