### ISSUE TITLE
Marathon 0.80 upgrade deployment stuck with no tasks in the queue

### ISSUE THREAD

**Issue by mingqi** [mesosphere/marathon#1610]
I have similar issue with #731 .  My marathon is 0.80 and mesos is 0.21.0. This issue occasionally happen only for app upgrade.  I saw a deployment was create and stuck on 0 / 1 progress. The step is "RestartApplication". Detail deployments information from /v2/deployments in below.

```json
[  
   {  
      "currentStep":1,
      "currentActions":[  
         {  
            "action":"RestartApplication",
            "app":"/ef3f50a8-beca-4548-ae3a-16b4ebfd600f"
         }
      ],
      "affectedApps":[  
         "/ef3f50a8-beca-4548-ae3a-16b4ebfd600f"
      ],
      "version":"2015-06-05T03:47:56.958Z",
      "id":"2e5c04f4-a6e6-475f-ad68-f3a3a264fddc",
      "totalSteps":1,
      "steps":[  
         [  
            {  
               "action":"RestartApplication",
               "app":"/ef3f50a8-beca-4548-ae3a-16b4ebfd600f"
            }
         ]
      ]
   }
]
```

There are only two line logs related to the deployments:
```
Jun  5 04:28:37 ip-172-31-8-66 marathon[8933]: [INFO] [06/05/2015 04:28:37.532] [marathon-akka.actor.default-dispatcher-842] [akka://marathon/user/MarathonScheduler/$a/UpgradeManager/c36468c7-414d-4e2a-a8b0-6f804eb4ad7e/$a] For minimumHealthCapacity 1.0 of /fa8d8f9c-0989-405c-9473-2b70f3eafda8 leave 1 tasks running, maximum capacity 2, killing 0 tasks immediately
Jun  5 04:28:37 ip-172-31-8-66 marathon[8933]: [INFO] [06/05/2015 04:28:37.532] [marathon-akka.actor.default-dispatcher-842] [akka://marathon/user/MarathonScheduler/$a/UpgradeManager/c36468c7-414d-4e2a-a8b0-6f804eb4ad7e/$a] Reconciliating tasks during app /fa8d8f9c-0989-405c-9473-2b70f3eafda8 restart: queuing 1 new tasks
``` 

I observed another confuse things:  Some task will left in task queue (GET /v2/queue ) even though application has been successfully deployed.  In my understanding the app will remove from queue after deployment done.  Back to my case, I found upgrade will success if last app deployment left task in queue, otherwise upgrade will failed. That's weird.

**Comment by kolloch** [comment]
Hi @mingqi, did you try with `0.8.2` (equal to `0.8.2-RC4`) or the master?

Can you come up with a minimal example on how to reproduce this? Including app.json?

Or if that's not possible put the complete Marathon logs, and that of the relevant Mesos slaves/master in a gist?

Thanks.

**Comment by mingqi** [comment]
We have two environments: stage and production.  The issue only happen on production occasionally.  It's improbable put Mesos slave logs because we have 20+ slave and not centralized. I will try to reproduce it put Marathon and Mesos master logs.  By my observation task didn't send to Mesos maste. I didn't see "Adding task ..." in log file.

As for upgrade to 0.8.2. Is that a stable enough for production?

**Comment by mingqi** [comment]
@kolloch 

I reproduce this issue and put log in s3:

marathon log: https://s3-us-west-2.amazonaws.com/mathilde-share/marathon.log
mesos info log: https://s3-us-west-2.amazonaws.com/mathilde-share/mesos-INFO.log
mesos error log: https://s3-us-west-2.amazonaws.com/mathilde-share/mesos-ERROR.log

Please let me know if you need more information, thanks.

**Comment by kolloch** [comment]
`0.8.2` is a stable release. You should use it with Mesos 0.22.1, though.

**Comment by kolloch** [comment]
State is compatible between 0.8.0 and 0.8.2 so you can also try if it solves your problem and roll back if unexpected problems occur.

**Comment by mingqi** [comment]
Issue look like be fixed after upgrade to 0.8.1. Closing this issue.

**Comment by mingqi** [comment]
closing issue

**Comment by machbio** [comment]
Mesos - 0.22.1 and Marathon - 0.8.2; Issue still exists.
Running a Single Master and Single Slave Node, the app is stuck in the deployment stage

**Comment by eliquious** [comment]
+1 

Marathon: Version 0.8.2-SNAPSHOT
Mesos: Version:0.22.1

Running 1 master, 6 public slaves. AWS tutorial with python-3 Docker example.

**Comment by lsiudut** [comment]
+1

Marathon: 0.8.2
Mesos: 0.22.1

Test environment with 1 master and 1 slave.

**Comment by gkleiman** [comment]
@machbio, @eliquious, @lsiudut repeating what Peter has said, it would be great if you can come up with a minimal example on how to reproduce this (including the app.json).

The complete Marathon logs (of the leader before the upgrade and of the leader with the new version), and those of the relevant Mesos slaves/master would also help.

By the way, Marathon v0.9.0 was released a little over a week ago. We'd to hear from you if this happens when upgrading to it.

**Comment by eliquious** [comment]
@gkleiman I believe my issue was related to not having any private slaves. I was going through the AWS  tutorial and only setup a few public slaves. After applying the `acceptedResourceRoles` of `slave_public` to my JSON, all my deployments worked from then on. So my guess is that it was trying to deploy to the private slaves by default, of which I had none. I do not know if this is the same setup as @machbio and @lsiudut but it seems likely as each of them only had one slave (and likely public as well).

**Comment by lsiudut** [comment]
In my case it was bad resource management in example I used. @gkleiman , sorry for taking your time here, I should have spend more time on it earlier.

**Comment by machbio** [comment]
@gkleiman I have destroyed the cluster - so I will not be able to reproduce the error... but I am willing to test out the new version of Marathon v0.9.0 and update the ticket of any issues..thank you for taking note of this ticket

**Comment by aquamatthias** [comment]
We can not do a bugfix Release for Marathon 0.8.0. Please try out a recent version of Marathon (0.13.0 at the moment) and reopen, if this problem still exists.
