### ISSUE TITLE
When will 0.8.2 be available in the mesosphere apt repository?

### ISSUE THREAD

**Issue by jaytaylor** [mesosphere/marathon#1617]
Just curious since I see the release here on github, but cannot find it in aptitude.

When will 0.8.2 be available in the mesosphere apt repository?

**Comment by kolloch** [comment]
Hi @lloesche, can you answer that, please?

**Comment by lloesche** [comment]
It is available in the public repositories since last week Friday, June 5th.

**Comment by kolloch** [comment]
Thanks for checking!
