### ISSUE TITLE
Run docker with portMapping in HOST network mode

### ISSUE THREAD

**Issue by hermansc** [mesosphere/marathon#1618]
Hi.

I'm running chronos using Marathon, and since it's communicating with Mesos it needs to run in HOST network mode. I'm also using consul with [registrator](https://github.com/gliderlabs/registrator) for service discovery and per [their docs](https://github.com/gliderlabs/registrator#host-mode-services) I can have the host running my container discovered, even with `--net=host`, by also specifying `-p port:port` when running the container.

Using Marathon 0.8.2 with `network: HOST` it for some reason "assigns" a port for my service:
![screen shot 2015-06-05 at 20 24 56](https://cloud.githubusercontent.com/assets/116978/8013430/0557b3d2-0bc1-11e5-986c-f4ba433a2caa.png)

Now, I've tried to run it with `"portMappings": [{ "conainerPort": 3000, "hostPort": 3000, "protocol: "tcp" }]`, but per #836 it doesn't seem like this is supported.

Ideas?

**EDIT**: Looks like it worked with:

```
"container": {
  "docker": {
    "parameters": [{ "key": "publish", "value": "3000:3000" }],
  }
}
```

Still weird with the misleading port in the UI though.

**Comment by nemothekid** [comment]
Heres an example json setup that advertises/exposes port 4400

```
{
  "ports": [
    4400
  ],
  "instances": 1,
  "shell": false,
  "container": {
    "docker": {
      "image": "mesosphere/chronos:chronos-2.3.4-1.0.81.ubuntu1404-mesos-0.22.1-1.0.ubuntu1404",
      "network": "HOST"
    },
    "type": "DOCKER"
  },
  "id": "chronos",
  "args": ["/usr/bin/chronos", "--master", "zk://zoo1:2181,zoo2:2181,zoo3:2181/mesos", "--zk_hosts", "zoo1:2181,zoo2:2181,zoo3:2181"],
  "mem": 128,
  "cpus": 0.2,
  "constraints": [
    [
      "group", "CLUSTER", "ops"
    ]
  ]
}
```

**Comment by hermansc** [comment]
Thanks. I thought `"ports": [4400]"` was meant for service discovery/mesos-dns and didn't affect the `docker run` command.

**Comment by nemothekid** [comment]
I don't think marathon cares or knows about what ports the docker container uses. And docker in HOST mode doesn't care about the `publish` flags at all. You could also use `portMappings` to remap ports, under BRIDGE mode.

```json
{
  "ports": [
    80
  ],
  "instances": 1,
  "shell": false,
  "container": {
    "docker": {
      "image": "some/webapp",
      "network": "BRIDGE",
      "portMappings": [{"containerPort": 3000, "hostPort": 80, "protocol": "tcp"}]
    },
    "type": "DOCKER"
  },
  "id": "chronos",
  "args": ["/usr/bin/chronos", "--master", "zk://zoo1:2181,zoo2:2181,zoo3:2181/mesos", "--zk_hosts", "zoo1:2181,zoo2:2181,zoo3:2181"],
  "mem": 128,
  "cpus": 0.2,
  "constraints": [
    [
      "group", "CLUSTER", "ops"
    ]
  ]
}
```

**Comment by hermansc** [comment]
Yeah, I know docker care doesn't _care_ about the `publish` flag per se - as it won't affect the container when run in host mode. However, you can see that it is indeed reflected in the config of the container (`docker inspect <hash>`) and it's further used by [registrator](https://github.com/gliderlabs/registrator#host-mode-services) to do service discovery for the host.

**Comment by kolloch** [comment]
Hi @hermansc ,

PortMappings are the way to go if you do not use HOST networking.

If you do not specify ports/portMappings, the default is that you get one dynamically assigned port. That is what you saw in the Marathon UI.

Is your problem now resolved? If not, please reopen the issue.

**Comment by flyinprogrammer** [comment]
> the default is that you get one dynamically assigned port. That is what you saw in the Marathon UI.
@kolloch Do you know where the code is for this lives? 

In my opinion a more sane defaults would be:
1. Never assign ports to containers using HOST networking (since they will never get used) 
2. Use the first servicePort declared for the element in the UI (to also encourage the intended use of service ports)?

Idk maybe I'm nuts, would love feedback and to help!

**Comment by xianlubird** [comment]
If I didn't assign port and portMappings in HOST mode, marathon will offer me a random port, but in this case, marathon will know what port does container really use?  how marathon schedule this container?

**Comment by hekaldama** [comment]
I am still having this issue even with using top level ports defined, and docker param set as noted above. The UI still reports a random port association and the event bus advertises that port. I need to run HOST networking and define what port my app is running on so the event bus relays the correct information for LB updates.

Thanks.

**Comment by xianlubird** [comment]
@hekaldama you can test the ports attribute outside the container label.
