### ISSUE TITLE
Be able to specify one or more 'required' constraints for successful application launch

### ISSUE THREAD

**Issue by bacoboy** [mesosphere/marathon#1619]
Since the default placement when NO constraints are provided is to place it anywhere, sometimes we want to make sure somebody doesn't do just that because they forgot to provide constraints.

In my case, I have all Mesos slaves tagged with an attribute called `service_cluster` (but the name doesn't matter -- this is just to explain the use case).  I'd like to be able to reject applications if I've configured by cluster to require at least a `service_cluster` constraint.

The default behavior of today (no constraint => place anywhere) should remain, but if I set one or more 'required' constraints in my marathon configuration, then I can reject any applications from starting if it was accidentally left off.

This can be used to stop accidental placement when your mesos cluster is running more than one logical environment w/o resorting to OS level isolation.

Thoughts?

**Comment by kolloch** [comment]
Hi @bacoboy,

in the upcoming `0.9.0` release we will include code that will allow you to do something similar with Mesos roles.

You can assign a role to some of your Mesos resources (e.g. service_cluster) and make sure that these resources are not used by default.

Look at `--default_accepted_resource_roles` in the command line config and "acceptedResourceRoles" in the REST API.

I still think that we might want something like you are suggesting for constraints. We have discussed something like this but haven't come up with a intuitive approach yet.

**Comment by bacoboy** [comment]
My idea doesn't require any mesos integration.  You just reject the application POST/PUT if missing one or all of the constraints specified in the marathon configuration that are deemed 'required'.  Since the default would skip this, the change would be backward compatible with existing functionality.

If you give me a pointer into the code where the requests are processed, I can attempt to make a PR.

**Comment by kolloch** [comment]
Hi @bacoboy, 

can you outline the exact syntax of the configuration in mind with examples of app definitions which are rejected/accepted? I guess most of the work is actually in that. Thanks!

**Comment by bacoboy** [comment]
Is this what you mean?

* Add an optional command line argument ``--required-constraints=key[,key]*``.  

If BOTH ``service_cluster`` AND ``environment`` were required the command line argument would be:

	--required-constraints=service_cluster,environment
    
If only ``environment`` was required the command line argument would be:

	--required-constraints=environment

For packages, I could have a file ``/etc/marathon/required-constraints`` which contains these values:

	% cat /etc/marathon/required-constraints
	service_cluster,environment

* Reject API POST/PUT if required constraint is missing with a 400 (bad request) and a json payload saying like ``Missing constraint: service_cluster``

By example, let's say I used the command line argument ``--required-constraint=service_cluster`` then this request would return success:

		{
		    "constraints": [
		        [
		            "service_cluster",
		            "CLUSTER",
		            "test-cluster"
		        ],
		        ["hostname", "GROUP_BY"]
		    ],
		    "container": {
		        "docker": {
		            "image": "nginx:latest",
		            "network": "BRIDGE",
		            "portMappings": [
		                {
		                    "containerPort": 80,
		                    "protocol": "tcp"
		                }
		            ]
		        },
		        "type": "DOCKER"
		    },
		    "cpus": 0.5,
		    "id": "/nginx",
		    "instances": 1,
		    "mem": 512
		}

This request would fail:

		{
		    "constraints": [
		        ["hostname", "GROUP_BY"]
		    ],
		    "container": {
		        "docker": {
		            "image": "nginx:latest",
		            "network": "BRIDGE",
		            "portMappings": [
		                {
		                    "containerPort": 80,
		                    "protocol": "tcp"
		                }
		            ]
		        },
		        "type": "DOCKER"
		    },
		    "cpus": 0.5,
		    "id": "/nginx",
		    "instances": 1,
		    "mem": 512
		}


If ``--required-constraints`` is not passed, then normal placement occurs.

**Comment by kolloch** [comment]
Thanks for your clarification! I thought about doing something similar with "policies". I would love to hear your feedback about this.

That is the basic idea (read this first): https://gist.github.com/kolloch/0d435af5e68a4febcb42

And this is an expanded/improved version: https://gist.github.com/kolloch/7705593539ae8a675fae

**Comment by bacoboy** [comment]
Are these policies meant to replace or sit along side constraints?

**Comment by kolloch** [comment]
They would sit along constraints. So basically, they in effect only add constraints.

**Comment by bacoboy** [comment]
You are absolutely correct in that all slave nodes are not created equal and having something to manage those differences is important.

I like the ability in mesos to apply arbitrary tags to servers and use constraints in marathon (positive or negative) to decide where things should or shouldn't run.  But your policy approach shifts the decision making from the user/launcher to a server-side decision engine.  In effect, you apply constraints when none are given via the policies.  I for one don't like this approach, but I'm sure there are many people who would.

For me, my launcher already has to decide what to launch, where (multiple mesos clusters), how big (ram/cpu), etc so adding the constraints to further specify additional constraints is a no brainer.  For simpler environments, I can see the lure of using policy to apply constraints where none are give, I'm not debating that.

Case in point, while people are testing, they often launch manually and forget to add constraints.  It could wind up everywhere and mess things up.  Your policy system would pick a default location and that might be fine for your environment.

However, my request is to say the opposite.  I'm saying there is no default.  If you forget to add it, your launch should fail.  This idea can co-exist with policies.  You can have a policy to make sure your app lands on a non-ssd box by default, but you MUST tell me the `environment` (production, staging, etc).

Ideally, I wouldn't have to seed this information into the policy API but could a pass command line option as outlined above.  If somebody didn't pass the required constraints for this cluster, marathon would reject the deployment attempt.

**Comment by bacoboy** [comment]
Been some time...  Any thoughts?

**Comment by bhack** [comment]
Is there a way to define optional constrains?
I.e. I want to consume some local datacenters hosts resources (if available) before placing on third party clouds.

**Comment by bhack** [comment]
Probably my use case could be covered by this long term issue https://github.com/mesosphere/marathon/issues/1174

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3248. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
