### ISSUE TITLE
portMappings is setted  but not working

### ISSUE THREAD

**Issue by istrike** [mesosphere/marathon#1622]
mesos:0.22.1
marathon:0.8.2
slave setting:mesos-slave --containerizers=mesos,docker --work_dir=/tmp/mesos/slave --log_dir=/tmp/mesos/slave_log --master=zk://192.168.1.147:2181/mesos --ip=192.168.1.147 --hostname=mesos.slave147.local --resources="ports(*):[5000-60000,5000-60000,5000-60000]"

i had started mesos and i want to use marathon create some docker containers than i get some err.
i post the json: 
{
    "id": "redis-aaaaaa",
    "container": {
        "docker": {
        "portMappings": 
        [{"containerPort": 6379, "hostPort": 56379, "protocol": "tcp" }],
        "image": "docker.unimatic.local:5000/library/redis:2.8.9"
    },
  "type": "DOCKER",
  "instances": 1,
  "cpus": 0.5,
  "mem": 128,
  "constraints": [
        ["mesos.slave147.local", "UNIQUE"]
    ]
  }
} to /v2/apps

it not works  when i check mesos log ,there is no stdout and stderr and still FAILED,and marathon still deploying 

when i del the portMappings it can create a contaner but no port mapping ....

**Comment by kolloch** [comment]
Hi @istrike,

the JSON is a bit hard to read because it's not indented or formatted:

```json
{
"id": "redis-aaaaaa",
"container": {
  "docker": {
    "portMappings": [
      {"containerPort": 6379, "hostPort": 56379, "protocol": "tcp" }
    ],
   "image": "docker.unimatic.local:5000/library/redis:2.8.9"
  },
  "type": "DOCKER",
  "instances": 1,
  "cpus": 0.5,
  "mem": 128,
  "constraints": [
    ["mesos.slave147.local", "UNIQUE"]
   ]
  }
}
```

The resources/instances configuration should not be part of the "container" JSON object.

I am also not sure what you try to achieve with the constraints setting.

Also, if you get some error, please include it in the bug description. Check the "lastTaskFailure" of your app.
