### ISSUE TITLE
Improper report of deployment

### ISSUE THREAD

**Issue by kensipe** [mesosphere/marathon#1631]
Assume I have an app deployed to marathon with an app id of /nginx

based on a **user error** I submitted the following using httpie
`http -v PUT http://demo-bliss.mesosphere.com:8080/v2/apps/nginx Instances=2`

this results in the 2 being a string "instances" : "2"
the proper httpie is this:  `http -v PUT http://demo-bliss.mesosphere.com:8080/v2/apps/nginx Instances:=2`

Using the improper version above (repeated here), marathon inappropriately provided a deployment ID but then did nothing:

here is the result of a bad request:

```
http -v PUT http://demo-bliss.mesosphere.com:8080/v2/apps/nginx Instances=2
PUT /v2/apps/nginx HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Content-Length: 18
Content-Type: application/json; charset=utf-8
Host: demo-bliss.mesosphere.com:8080
User-Agent: HTTPie/0.8.0

{
    "Instances": "2"
}

HTTP/1.1 200 OK
Content-Type: application/json
Server: Jetty(8.y.z-SNAPSHOT)
Transfer-Encoding: chunked

{
    "deploymentId": "f286436c-7976-4abb-8940-7dcba835f5fd", 
    "version": "2015-06-09T18:42:21.580Z"
}
```

**Comment by rasputnik** [comment]
The issue may be that you have a capital I at the start of 'instances'. Marathon ignores invalid keys in the json payload (and it needs to for forward compatibility).

**Comment by kolloch** [comment]
Since an PUT is actually an update in Marathon, empty is valid. The misspelled Instances parameter is ignored. We cannot change that without potentially causing incompatibility.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2990. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
