### ISSUE TITLE
Poor JSON response 

### ISSUE THREAD

**Issue by kensipe** [mesosphere/marathon#1632]
a recent incorrect http request ` http -v PUT http://demo-bliss.mesosphere.com:8080/v2/apps/nginx instances=2` resulted in the following:

```
http -v PUT http://demo-bliss.mesosphere.com:8080/v2/apps/nginx instances=2
PUT /v2/apps/nginx HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Content-Length: 18
Content-Type: application/json; charset=utf-8
Host: demo-bliss.mesosphere.com:8080
User-Agent: HTTPie/0.8.0

{
    "instances": "2"
}

HTTP/1.1 400 Bad Request
Content-Type: application/json
Server: Jetty(8.y.z-SNAPSHOT)
Transfer-Encoding: chunked

{
    "message": "Invalid JSON: JsResultException(errors:List((/instances,List(ValidationError(error.expected.jsnumber,WrappedArray())))))"
}
```

The value `"message": "Invalid JSON: JsResultException(errors:List((/instances,List(ValidationError(error.expected.jsnumber,WrappedArray())))))"` isn't a friend response.

**Comment by kolloch** [comment]
I think you are right and I can think of better ones. Can you tell us about what you would like here as a suggestion?

**Comment by kolloch** [comment]
This is actually a duplicated of your own issue #1235 if I am not mistaken.
