### ISSUE TITLE
Marathon not respecting GROUP_BY contraints

### ISSUE THREAD

**Issue by aameek** [mesosphere/marathon#1633]
This has been a bit unpredictable and seemed to be working earlier, but after a few days of inactivity on my mesos/marathon cluster, GROUP_BY is not spreading the load across 3 "pods" ...

Marathon: v0.8.1
Mesos: 0.22.1

Configuration of the deployed app:

![image](https://cloud.githubusercontent.com/assets/4740164/8070213/a571085a-0eb4-11e5-92bd-e7a30f0d4046.png)

Task placement:

![image](https://cloud.githubusercontent.com/assets/4740164/8070225/b7262e0e-0eb4-11e5-8a7c-1a1fc5d87d6a.png)

$ ssh sas@10.90.38.121 'ps -ef | grep pod | grep -v grep'
root      1673     1  0 Jun02 ?        00:48:17 /usr/sbin/mesos-slave --master=zk://10.54.128.106:2181,10.122.62.166:2181,10.88.164.26:2181,10.54.128.105:2181,10.88.164.25:2181/sastm5 --log_dir=/var/log/mesos <b>--attributes=pod:pod2</b> --containerizers=docker,mesos --executor_registration_timeout=5mins --hostname=10.90.38.121 --ip=10.90.38.121

$ ssh sas@10.122.149.72 'ps -ef | grep pod | grep -v grep'
root      1677     1  0 Jun02 ?        00:27:06 /usr/sbin/mesos-slave --master=zk://10.54.128.106:2181,10.122.62.166:2181,10.88.164.26:2181,10.54.128.105:2181,10.88.164.25:2181/sastm5 --log_dir=/var/log/mesos <b>--attributes=pod:pod3</b> --containerizers=docker,mesos --executor_registration_timeout=5mins --hostname=10.122.149.72 --ip=10.122.149.72

$ ssh sas@10.122.149.118 'ps -ef | grep pod | grep -v grep'
root      1675     1  0 Jun02 ?        00:49:32 /usr/sbin/mesos-slave --master=zk://10.54.128.106:2181,10.122.62.166:2181,10.88.164.26:2181,10.54.128.105:2181,10.88.164.25:2181/sastm5 --log_dir=/var/log/mesos <b>--attributes=pod:pod3</b> --containerizers=docker,mesos --executor_registration_timeout=5mins --hostname=10.122.149.118 --ip=10.122.149.118

There is a pod1 slave available in the cluster.

$ ssh sas@10.53.45.254 'ps -ef | grep pod | grep -v grep'
root      1724     1  0 Jun02 ?        01:07:34 /usr/sbin/mesos-slave --master=zk://10.54.128.106:2181,10.122.62.166:2181,10.88.164.26:2181,10.54.128.105:2181,10.88.164.25:2181/sastm5 --log_dir=/var/log/mesos <b>--attributes=pod:pod1</b> --containerizers=docker,mesos --executor_registration_timeout=5mins --hostname=10.53.45.254 --ip=10.53.45.254

**Comment by aameek** [comment]
Any update ?

**Comment by kolloch** [comment]
Hi @aameek, Marathon cannot now in advance how many different values of this attribute your slaves have. Therefore, it will only analyze the already running tasks to make a decision in whether it is ok to run additional tasks on this slave. It will never start a new task if it already has more tasks running on slaves of this attribute value than on other slaves.

If you know how many values there are in advance, you should specify that. E.g. "pod:GROUP_BY:3"

We gladly accept PRs that improve the documentation :)

**Comment by rhoml** [comment]
This is actually not working properly. I am setting the following constraints:

```Constraints
host:UNLIKE:none
host:GROUP_BY:5```

and I see that my tasks get spreaded across all the available hosts of my fleet it doesn't for the task to be spreaded across 5 of them.

Unless I am getting this constraint wrong?

I think this issue should be reopened.
