### ISSUE TITLE
dependencies should be set into app's env by default

### ISSUE THREAD

**Issue by BrickXu** [mesosphere/marathon#1636]
Our service discovery service depends on the `dependencies` value, but it does not set into app's env by default, so we need to add the same value with key `env` like this:

```
{
    "id": "/product/service/my-app",
    "container": {
        "type": "DOCKER",
        "docker": {
            "image": "group/image"
        },
    "env": {
        "dependencies": "/product/db/mongo:/product/db"
    },
    "dependencies": ["/product/db/mongo", "/product/db"] # the same as env
}
```

I think it would be better if marathon could set them automatically.

**Comment by aquamatthias** [comment]
Hey @BrickXu.
Can you describe your intention a little bit more detailed?
What does your process do, if it knows the dependency names?
Since it is possible to depend on groups and applications, how do you know?
Do they make sense outside of marathon?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2744. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
