### ISSUE TITLE
More responsive/faster Marathon scale up and scale down

### ISSUE THREAD

**Issue by Ferdiism** [mesosphere/marathon#1641]
MARATHON-152

**Comment by Ferdiism** [comment]
@air, can you please help us quantify the target?

**Comment by air** [comment]
Absolutely. Can we describe the current state - what's the current scaling rate (assuming best conditions)?

**Comment by aquamatthias** [comment]
@air: as far as I understood our discussion yesterday with David, this ticket does not reflect the requirement. I created a separate issue for the bug discovered:  #1709.
