### ISSUE TITLE
Let external tool kill old tasks after deployment

### ISSUE THREAD

**Issue by felixb** [mesosphere/marathon#1653]
In my setup it would be very useful not killing any task during/after deployment but let an external tool handle that.

This enables the following key features:
- The load balancer switches to the new version in one atomic action. There is are no flickering UI changes or similar things.
- Teams can decide when the switch happens. This is key in my orgs setup.
- Even faster roll back. You just need to switch back the LB.
- Killing the old tasks _after_ they are removed from LB, thus not loosing any requests.

The deployment plan would look like this:
1. n instances running
2. marathon deploys n new instances, there are now 2n instances running, still only the old instances are getting any requests from the LB
3. update the LB to point to new instances only
4. an external tool kills the n old instances to get back to a total of n instances

**Comment by bobrik** [comment]
Take a look at [zoidberg](https://github.com/bobrik/zoidberg), it enables exactly what you want. You can atomically switch versions in LB, do quick rollbacks the same way, send small portions of live traffic to new versions, etc.

The only problem is that you have to deploy versions as separate apps, like:

* `/myapp/v1`
* `/myapp/v2`

You can also have regular deployments in a single app if you don't want fancy version switching.

Currently only nginx is supported as a LB ([zoidberg-nginx](https://github.com/bobrik/zoidberg-nginx)), but it's trivial to add your own.

#1006 is probably related.

**Comment by felixb** [comment]
Thanks! I kind of have the same thing running already with haproxy and varnish deploying `/app/blu` and `/app/grn`. But it would be nice to get rid of that.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2774. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
