### ISSUE TITLE
Q: Constraints not working

### ISSUE THREAD

**Issue by jtktam** [mesosphere/marathon#1661]
# Slave started with:

/usr/sbin/mesos-slave --master=zk://x.x.x.x:2181/mesos --log_dir=/var/log/mes
os --hostname=y.y.y.y --ip=y.y.y.y.y --attributes=dns:true

# in my app_dns.json

app_dns.json
{
"cmd": "/root/mesos-dns -config=/root/config.json -logtostderr=true",
"cpus": 0.75,
"mem": 128,
"id": "mesos-dns",
"instances": 2,
"constraints": [["true", "CLUSTER", "dns"]]
}

# posted with

curl -X POST -H "Content-type: application/json" x.x.x.x:8080/v2/apps -d @app_dns.json

----

it shows up in the marathon gui and sits there as "deploying" without any action taken.

if I changed tried with a json wihout constraints:

# in my app_sleep.json

{
"cmd": "sleep 15",
"cpus": 0.25,
"mem": 16,
"id": "sleep-15",
"instances": 8
}

# posted with

curl -X POST -H "Content-type: application/json" x.x.x.x:8080/v2/apps -d @app_sleep.json

it deploys and runs fine.. 

---

slaves offering cpus(*):1; mem(*):245; disk(*):14910 to master, so there is enough CPU/RAM to deploy but it doesnt :(

any insight on what I am missing?

**Comment by kolloch** [comment]
I think you wrote your constraint in the wrong order. Try `["true", "CLUSTER", "dns"]` instead of `["dns", "CLUSTER", "true"]`
