### ISSUE TITLE
Datase, memory & swap space

### ISSUE THREAD

**Issue by trompx** [mesosphere/marathon#1662]
Hello,

I searched in the documentation but I could not find information about memory and swap space.
Say I start a mysql container with marathon with 512mo mem, what would happen when the mysql container use more than that ? Marathon would just kill the container ?
Is there an option to set a dynamic amount of memory, like use all the remaining memory of the host ? That would be really helpful.

Thank you

**Comment by kolloch** [comment]
It depends on the mesos isolator used.

See for example: http://stackoverflow.com/questions/27560116/how-does-marathon-limit-resources-for-directly-called-apps

**Comment by trompx** [comment]
Thanks for the fast answer ! I was looking for a way to easily handle vertical scaling when the traffic increases, without having to restart a task (say I want to move one container to another node to be able to allocate more memory to another / or just add more ram to the node without restart) but it looks like it is not possible out of the box.
