### ISSUE TITLE
Package the UI as webjar 

### ISSUE THREAD

**Issue by aldipower** [mesosphere/marathon#1673]
Create a script that creates a versioned release of the UI packaged in a .war-file, that can be served by the Marathon backend.

AC

1.    'npm run release'
2.   Version number should be retrieved from the package.json version key
3.    dist/ files should be created from the related Git Tag (version)
4.    Creates a ~~.war~~.jar-file with the contents of the dist-folder (main., img/, index.html)
5.    Released ~~.war~~.jar should be in the repository in an own release-folder

**Comment by pierlo-upitup** [comment]
Update: there was a misunderstanding, this needs to be a WebJar file .

**Comment by aldipower** [comment]
I am sorry, my fault.

**Comment by philipnrmn** [comment]
No worries! There's a lot of similarity between the two, so we can still use some of this work.

**Comment by aquamatthias** [comment]
Basic Steps provided. 
If finished, we need to integrate that into TC.
I create a ticket for the Backend part.

**Comment by aldipower** [comment]
PR created https://github.com/mesosphere/marathon-ui/pull/108, but TC integration is more difficult than expected because I need a Dockerimage with both Node.js and Maven integration.
