### ISSUE TITLE
Create Git Tags for releases

### ISSUE THREAD

**Issue by aldipower** [mesosphere/marathon#1674]
Release points or special versions should be tagged in the Git repository of the UI.

ACs
1. Version number should be set in package.json
2. We are using SemVer
3. Major and Minor version of the UI should be align to Marathon
4. Release point must have the versioned Git tag in the UI repository
5. Git tag must have a CHANGELOG

**Comment by aldipower** [comment]
Should we create a tag called 0.9.0 based on the current master to freeze a point that is shipped with the next release of Marathon?
What do think? @aquamatthias @philipnrmn @pierlo-upitup

**Comment by aquamatthias** [comment]
Please do so. If I understood correctly this tag should be used in the [releasing-0.9](https://github.com/mesosphere/marathon/tree/releasing-0.9) branch?

**Comment by aldipower** [comment]
OK, cool, yes you understood correctly.

**Comment by aldipower** [comment]
https://github.com/mesosphere/marathon-ui/releases/tag/v0.9.0

**Comment by aquamatthias** [comment]
Hey @aldipower can you set that in the release branch?

**Comment by aldipower** [comment]
Oh yes, I see.
