### ISSUE TITLE
Introduce a more dynamic approach for repetitive view declarations

### ISSUE THREAD

**Issue by mlunoe** [mesosphere/marathon#1680]
A good example is the app list, where we are actually repeating ourselves throughout the view declaration:
https://github.com/mesosphere/marathon-ui/blob/master/src/js/components/AppListComponent.jsx#L85

This could be done with a list of configurations and then fetching the view to match for each configuration.

This is one example, but there are multiple examples of this throughout the code.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3653. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
