### ISSUE TITLE
failed to start up Marathon after add --zk_max_versions

### ISSUE THREAD

**Issue by mingqi** [mesosphere/marathon#1685]
This is following up with #1683. Open this since I haven't right reopen it. 

Yesterday I tried to add --zk_max_versions flag and restart Marathon, but Marathon failed to start up. Finally I removed --zk_max_versions flags and restart again. I'm not sure whether is related to --zk_max_versions. Another wired things was we found some application (not application versions) was deleted from Marathon. The child nodes number of /marathon/state decrease to 19626 today.

**Comment by aquamatthias** [comment]
@mingqi It would be very helpful if you could provide logs for the failed start (if you use a quorum, it would help to have the logs of all nodes). Which version did you use to try this out? 
If you see some items deleted from the repo (which would be normal, if you use `zk_max_versions`), do you miss an application?

**Comment by jasongilanfarr** [comment]
Marathon 1.4 doesn't have this kind of behavior. Pretty sure this is a single znode limit
