### ISSUE TITLE
Gulp improvements

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#1688]
- [x] Add support for LiveReload in gulp ( https://github.com/mesosphere/marathon-ui/pull/45 )
- [ ] Allow ES6 in `node_modules`
- [x] Optimize Webpack loading times 
- [x] ~~Take a look at .changed() to only compile changed files~~ (using Webpack caching)
- [x] ~~Integrate mocha testing and figure a strategy for running tests only on changed files~~ (out of scope)
- [x] Produce JS source maps
- [ ] LESS source maps
- [x] Reduce the amount of Webpack logs
- [x] Restore ESLINT output during build
- [x] Switch to `eslint-loader` for Webpack
- [x] Move to Babel 6 and Node 5
- [ ] Prevent LESS from dying upon compilation exceptions

Phase 2
- [ ] Reduce number of Gulp tasks in favor of Webpack loaders (where appropriate)
- [ ] Move to Webpack's Dev Server + proxy settings

**Comment by aldipower** [comment]
@pierlo-upitup Can you give a status update on this and mark some checkboxes? Thx.

**Comment by aldipower** [comment]
@pierlo-upitup Can we close this?

**Comment by pierlo-upitup** [comment]
No, actually let's schedule a chat with @kennyt and @jfurrow as I know they have done good progress on build-system optimisations.

**Comment by jfurrow** [comment]
I'd be happy to chat about this! @kennyt recently reduced the DCOS UI JavaScript build time down to milliseconds.

**Comment by kennyt** [comment]
Lets do it!

**Comment by kennyt** [comment]
Just quickly thew together a doc of the general things you needa do.

https://docs.google.com/a/mesosphere.io/document/d/1NYJrS6I3YQXA4vUb8TLkP00HvGw4zWS-hicxe4SOGoA/edit?usp=sharing

**Comment by philipnrmn** [comment]
Bumping to 0.14.0 as it's not a blocker for 0.13.0

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2969. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
