### ISSUE TITLE
Support relative paths for host docker volumes

### ISSUE THREAD

**Issue by doctapp** [mesosphere/marathon#1694]
Hi,

Docker volumes require absolute paths. The path to uploaded files on the host using uris is not known a priori which prevents mounting them using docker volumes.

It would be great to support relative paths for hostPath which get expanded to the local mesos sandbox folder (under /tmp/mesos...). This would prevent using the MESOS_SANDBOX inside the container to locate host resources and remove MESOS knowledge from the container.

For instance, consider the following Marathon json volume using relative host paths:
...
    "volumes": [
      {
        "containerPath": "/some/path",
        "hostPath": "./local-file-from-uris",
        "mode": "RO"
      }
    ],
    "uris" : [ "http://some-host.com/local-file-from-uris" ]
...
hostPath would be expanded to the full mesos sandbox path. That way, uris can be local to the sandbox and be mounted directly from there.

Thanks

**Comment by kolloch** [comment]
Yes, that is a great suggestion.

This has to be implemented in Mesos, though. See https://issues.apache.org/jira/browse/MESOS-2374

**Comment by kolloch** [comment]
It would be great if you voted for that issue.

**Comment by doctapp** [comment]
Excellent, voted for it!

**Comment by garyelephant** [comment]
+1

**Comment by kolloch** [comment]
@garyelephant, you saw that it is resolved in Mesos 0.23, right?

**Comment by garyelephant** [comment]
@kolloch Yes, Thanks for your help.
