### ISSUE TITLE
Marathon fails to kill task, looping infinitely

### ISSUE THREAD

**Issue by jaytaylor** [mesosphere/marathon#1695]
When a mesos-worker host dies (e.g. gets rebooted), Marathon is not tolerating it well.  Even after the host comes back online it still just cycles endlessly (see output below).

I tried "manually" deleting the app and app-group in question via `curl -v -XDELETE http://mesos-primary1a:8080/v2/apps/app-81-1-hello-app/web-v5`, and the cmd reports success.  HOWEVER, the messed up app still shows up in the UI and the logs are still spamming the endless cycle of "Killing app...".

![screenshot #1](https://i.imgur.com/uzwOaUM.png)

![screenshot #2](https://i.imgur.com/T8f0JeN.png)

Additional info:

This is with mesos v0.22.1 and marathon v0.8.2.

    [INFO] [06/22/2015 19:58:38.766] [marathon-akka.actor.default-dispatcher-35] [akka://marathon/user/$e] Killing task app-81-1-hello-app_web-v5.62e995b3-190e-11e5-9737-0228107d4515 on host mesos-worker2a
    [INFO] [06/22/2015 19:58:38.767] [marathon-akka.actor.default-dispatcher-31] [akka://marathon/user/$b] POSTing to all endpoints.
    [INFO] [06/22/2015 19:58:38.769] [pool-1-thread-13] [akka://marathon/user/$b] Sending POST to:http://mesos-primary3a:8000/event
    [2015-06-22 19:58:38,772] WARN Task [app-81-1-hello-app_web-v5.62e995b3-190e-11e5-9737-0228107d4515] for app [/app-81-1-hello-app/web-v5] was killed for failing too many health checks (mesosphere.marathon.MarathonScheduler:167)
    [2015-06-22 19:58:38,777] INFO Task launch delay for [/app-81-1-hello-app/web-v5] is now [2 minutes 12 seconds 806 milliseconds] (mesosphere.util.RateLimiter:33)
    [2015-06-22 19:58:41,887] INFO Scaling /app-81-1-hello-app/web-v5 from 1 down to 0 instances (mesosphere.marathon.SchedulerActions:535)
    [2015-06-22 19:58:41,887] INFO Killing tasks: Set(app-81-1-hello-app_web-v5.62e995b3-190e-11e5-9737-0228107d4515) (mesosphere.marathon.SchedulerActions:539)
    [2015-06-22 19:58:41,889] INFO Already running 1 instances of /ds-81-1-tpdb/datastore-v0. Not scaling. (mesosphere.marathon.SchedulerActions:545)
    [2015-06-22 19:58:41,897] INFO Syncing tasks for all apps (mesosphere.marathon.SchedulerActions:457)
    [2015-06-22 19:58:41,902] INFO Requesting task reconciliation with the Mesos master (mesosphere.marathon.SchedulerActions:482)
    [WARN] [06/22/2015 19:58:48.760] [marathon-akka.actor.default-dispatcher-7] [akka://marathon/user/IO-HTTP/host-connector-1/1] Connection attempt to mesos-worker2a:31000 failed in response to GET request to / with 5 retries left, retrying...
    [WARN] [06/22/2015 19:58:48.762] [marathon-akka.actor.default-dispatcher-35] [akka://marathon/user/IO-HTTP/host-connector-1/2] Connection attempt to mesos-worker2a:31000 failed in response to GET request to / with 4 retries left, retrying...
    [WARN] [06/22/2015 19:58:48.764] [marathon-akka.actor.default-dispatcher-36] [akka://marathon/user/IO-HTTP/host-connector-1/1] Connection attempt to mesos-worker2a:31000 failed in response to GET request to / with 3 retries left, retrying...
    [WARN] [06/22/2015 19:58:48.766] [marathon-akka.actor.default-dispatcher-7] [akka://marathon/user/IO-HTTP/host-connector-1/2] Connection attempt to mesos-worker2a:31000 failed in response to GET request to / with 2 retries left, retrying...
    [WARN] [06/22/2015 19:58:48.768] [marathon-akka.actor.default-dispatcher-33] [akka://marathon/user/IO-HTTP/host-connector-1/1] Connection attempt to mesos-worker2a:31000 failed in response to GET request to / with 1 retries left, retrying...
    [WARN] [06/22/2015 19:58:48.770] [marathon-akka.actor.default-dispatcher-13] [akka://marathon/user/IO-HTTP/host-connector-1/2] Connection attempt to mesos-worker2a:31000 failed in response to GET request to / with no retries left, dispatching error...
    [INFO] [06/22/2015 19:58:48.770] [marathon-akka.actor.default-dispatcher-13] [akka://marathon/user/$e] Received health result: [Unhealthy(app-81-1-hello-app_web-v5.62e995b3-190e-11e5-9737-0228107d4515,2015-06-22T18:42:07.294Z,ConnectionAttemptFailedException: Connection attempt to mesos-worker2a:31000 failed,2015-06-22T19:58:48.770Z)]
    [INFO] [06/22/2015 19:58:48.771] [marathon-akka.actor.default-dispatcher-13] [akka://marathon/user/$e] Killing task app-81-1-hello-app_web-v5.62e995b3-190e-11e5-9737-0228107d4515 on host mesos-worker2a
    [INFO] [06/22/2015 19:58:48.771] [marathon-akka.actor.default-dispatcher-9] [akka://marathon/user/$b] POSTing to all endpoints.
    [2015-06-22 19:58:48,773] WARN Task [app-81-1-hello-app_web-v5.62e995b3-190e-11e5-9737-0228107d4515] for app [/app-81-1-hello-app/web-v5] was killed for failing too many health checks (mesosphere.marathon.MarathonScheduler:167)
    [INFO] [06/22/2015 19:58:48.774] [pool-1-thread-14] [akka://marathon/user/$b] Sending POST to:http://mesos-primary3a:8000/event
    [2015-06-22 19:58:48,783] INFO Task launch delay for [/app-81-1-hello-app/web-v5] is now [2 minutes 32 seconds 727 milliseconds] (mesosphere.util.RateLimiter:33)
    [WARN] [06/22/2015 19:58:58.773] [marathon-akka.actor.default-dispatcher-25] [akka://marathon/user/IO-HTTP/host-connector-1/2] Connection attempt to mesos-worker2a:31000 failed in response to GET request to / with 5 retries left, retrying...
    [WARN] [06/22/2015 19:58:58.779] [marathon-akka.actor.default-dispatcher-7] [akka://marathon/user/IO-HTTP/host-connector-1/1] Connection attempt to mesos-worker2a:31000 failed in response to GET request to / with 4 retries left, retrying...
    [WARN] [06/22/2015 19:58:58.781] [marathon-akka.actor.default-dispatcher-9] [akka://marathon/user/IO-HTTP/host-connector-1/2] Connection attempt to mesos-worker2a:31000 failed in response to GET request to / with 3 retries left, retrying...
    [WARN] [06/22/2015 19:58:58.783] [marathon-akka.actor.default-dispatcher-25] [akka://marathon/user/IO-HTTP/host-connector-1/1] Connection attempt to mesos-worker2a:31000 failed in response to GET request to / with 2 retries left, retrying...
    [WARN] [06/22/2015 19:58:58.785] [marathon-akka.actor.default-dispatcher-9] [akka://marathon/user/IO-HTTP/host-connector-1/2] Connection attempt to mesos-worker2a:31000 failed in response to GET request to / with 1 retries left, retrying...
    [WARN] [06/22/2015 19:58:58.787] [marathon-akka.actor.default-dispatcher-7] [akka://marathon/user/IO-HTTP/host-connector-1/1] Connection attempt to mesos-worker2a:31000 failed in response to GET request to / with no retries left, dispatching error...
    [INFO] [06/22/2015 19:58:58.788] [marathon-akka.actor.default-dispatcher-7] [akka://marathon/user/$e] Received health result: [Unhealthy(app-81-1-hello-app_web-v5.62e995b3-190e-11e5-9737-0228107d4515,2015-06-22T18:42:07.294Z,ConnectionAttemptFailedException: Connection attempt to mesos-worker2a:31000 failed,2015-06-22T19:58:58.787Z)]
    [INFO] [06/22/2015 19:58:58.788] [marathon-akka.actor.default-dispatcher-13] [akka://marathon/user/$b] POSTing to all endpoints.
    [INFO] [06/22/2015 19:58:58.789] [marathon-akka.actor.default-dispatcher-7] [akka://marathon/user/$e] Killing task app-81-1-hello-app_web-v5.62e995b3-190e-11e5-9737-0228107d4515 on host mesos-worker2a
    [INFO] [06/22/2015 19:58:58.790] [pool-1-thread-13] [akka://marathon/user/$b] Sending POST to:http://mesos-primary3a:8000/event
    [2015-06-22 19:58:58,796] WARN Task [app-81-1-hello-app_web-v5.62e995b3-190e-11e5-9737-0228107d4515] for app [/app-81-1-hello-app/web-v5] was killed for failing too many health checks (mesosphere.marathon.MarathonScheduler:167)
    [2015-06-22 19:58:58,799] INFO Task launch delay for [/app-81-1-hello-app/web-v5] is now [2 minutes 55 seconds 636 milliseconds] (mesosphere.util.RateLimiter:33)
    [WARN] [06/22/2015 19:59:08.810] [marathon-akka.actor.default-dispatcher-7] [akka://marathon/user/IO-HTTP/host-connector-1/1] Connection attempt to mesos-worker2a:31000 failed in response to GET request to / with 5 retries left, retrying...
    [WARN] [06/22/2015 19:59:08.813] [marathon-akka.actor.default-dispatcher-13] [akka://marathon/user/IO-HTTP/host-connector-1/2] Connection attempt to mesos-worker2a:31000 failed in response to GET request to / with 4 retries left, retrying...
    [WARN] [06/22/2015 19:59:08.815] [marathon-akka.actor.default-dispatcher-31] [akka://marathon/user/IO-HTTP/host-connector-1/1] Connection attempt to mesos-worker2a:31000 failed in response to GET request to / with 3 retries left, retrying...
    [WARN] [06/22/2015 19:59:08.819] [marathon-akka.actor.default-dispatcher-9] [akka://marathon/user/IO-HTTP/host-connector-1/2] Connection attempt to mesos-worker2a:31000 failed in response to GET request to / with 2 retries left, retrying...
    [WARN] [06/22/2015 19:59:08.820] [marathon-akka.actor.default-dispatcher-7] [akka://marathon/user/IO-HTTP/host-connector-1/1] Connection attempt to mesos-worker2a:31000 failed in response to GET request to / with 1 retries left, retrying...
    [WARN] [06/22/2015 19:59:08.823] [marathon-akka.actor.default-dispatcher-35] [akka://marathon/user/IO-HTTP/host-connector-1/2] Connection attempt to mesos-worker2a:31000 failed in response to GET request to / with no retries left, dispatching error...
    [INFO] [06/22/2015 19:59:08.824] [marathon-akka.actor.default-dispatcher-35] [akka://marathon/user/$e] Received health result: [Unhealthy(app-81-1-hello-app_web-v5.62e995b3-190e-11e5-9737-0228107d4515,2015-06-22T18:42:07.294Z,ConnectionAttemptFailedException: Connection attempt to mesos-worker2a:31000 failed,2015-06-22T19:59:08.823Z)]
    [INFO] [06/22/2015 19:59:08.824] [marathon-akka.actor.default-dispatcher-36] [akka://marathon/user/$b] POSTing to all endpoints.
    [INFO] [06/22/2015 19:59:08.826] [pool-1-thread-14] [akka://marathon/user/$b] Sending POST to:http://mesos-primary3a:8000/event
    [INFO] [06/22/2015 19:59:08.827] [marathon-akka.actor.default-dispatcher-35] [akka://marathon/user/$e] Killing task app-81-1-hello-app_web-v5.62e995b3-190e-11e5-9737-0228107d4515 on host mesos-worker2a
    [2015-06-22 19:59:08,828] WARN Task [app-81-1-hello-app_web-v5.62e995b3-190e-11e5-9737-0228107d4515] for app [/app-81-1-hello-app/web-v5] was killed for failing too many health checks (mesosphere.marathon.MarathonScheduler:167)
    [2015-06-22 19:59:08,830] INFO Task launch delay for [/app-81-1-hello-app/web-v5] is now [3 minutes 21 seconds 981 milliseconds] (mesosphere.util.RateLimiter:33)

**Comment by kolloch** [comment]
Hi @jaytaylor, are you sure that the mesos slave process deregistered from the Master before going down (orderly shutdown)? Otherwise it goes through the slave recovery process of Mesos. See:

http://mesos.apache.org/documentation/latest/slave-recovery/

That basically means that we do not get ANY task update from Mesos in Marathon until the recovery_timeout is up. I think that the default value for that is ten minutes. That means that Marathon will just continue trying to kill the tasks it considers unhealthy.

Does that sound plausible or is this something else?

**Comment by jaytaylor** [comment]
Hey there @kolloch,

I am pretty sure it did not shutdown in an orderly fashion.

It's been more than an hour yet I am still unable to delete the app from Marathon.  The app now seems like it is in a  stuck state in Marathon.

How can I recover from this without `rmr`ing all of ZooKeeper? :)

**Comment by kolloch** [comment]
Hi @jaytaylor, what is the task status in Mesos? Do find the tasks in Mesos? Can you kill them manually?

If Marathon is restarted, it should ask Mesos about the status of all tasks it knows about.

**Comment by jaytaylor** [comment]
In mesos, the task is nowhere to be found anymore.

![screen shot 2015-06-22 at 2 41 45 pm](https://cloud.githubusercontent.com/assets/435652/8293826/fdafbcf4-18ec-11e5-9fc3-55c2f64a55ce.png)

I'll try bouncing the Marathon service.

**Comment by jaytaylor** [comment]
Restarting Marathon seems to have done the trick!

    ID 	Memory (MB)	CPUs	Tasks / Instances	Health	Status
    /app-81-1-hello-app/web-v5	512	1	0 / 0	
	Suspended

Thank you for your assistance @kolloch!  Is there possibly a bug we can file about this? ..or why does the service need a restart to recover the app (the status was `running` before the service restart)?

**Comment by kolloch** [comment]
Restarting Marathon triggers "reconciliation" and throws away some internal state. Reconciliation is also initiated periodically. See `--reconciliation_initial_delay/--reconciliation_interval`: https://github.com/mesosphere/marathon/blob/master/docs/docs/command-line-flags.md

There is probably also some bug involved. We will rewrite the related code soon, so we will probably only investigate if that blocks some of our users regularly.

I will close the issue for now. If you hit the problem again, please reopen the issue.
