### ISSUE TITLE
Tag v0.9.0-RC2 contains v0.9.0-RC1 in version.sbt file.

### ISSUE THREAD

**Issue by quamilek** [mesosphere/marathon#1700]
When build marathon from tag `v0.9.0-RC2` result package has `v0.9.0-RC1` version.
`version.sbt` file contains `v0.9.0-RC1` https://github.com/mesosphere/marathon/blob/v0.9.0-RC2/version.sbt#L1

**Comment by aquamatthias** [comment]
Hey @quamilek thanks for reporting this. I moved the tag to the correct commit.
