### ISSUE TITLE
change the balance mode in haproxy-marathon-bridge

### ISSUE THREAD

**Issue by ee1200231** [mesosphere/marathon#1706]
I am using mesos/marathon to manage my apps. To balance the multiple instances of tomcat dockers, i am using the haproxy-marathon-bridge along with a cronjob that reloads the haproxy.cfg file every minute to add/remove apps. However, the default balance mode is "least conn". What is this protocol? and how do i enable round-robin instead of this?

**Comment by aquamatthias** [comment]
Hi @ee1200231 least conn is basically round robin. See this [doc](https://docs.joyent.com/top25/load-balancing-with-haproxy). What is not working with this mode?

**Comment by ee1200231** [comment]
One instance of the tomcat server was never being called. However, i figured out the reason and it was related to mesos/marathon and not the balance mode. 

Thanks for the reply, though. :)

**Comment by aquamatthias** [comment]
Would like to hear the reason - at least for reference. Close this ticket.

**Comment by ee1200231** [comment]
This is what I could analyse:
If a mesos-slave is offering , say 2 GB of Memory and 2 CPU units, then the instance of the tomcat docker utilising the last bit of the offering from that slave gets added to the haproxy configuration file (as it should be in general) but doesnt get called ever. Dont know the reason why!

For automating load balancing, I am using haproxy-marathon-bridge.
