### ISSUE TITLE
$PORT out of sync or not updated correctly

### ISSUE THREAD

**Issue by tnolet** [mesosphere/marathon#1707]
Hi,

I'm getting very strange behaviour running a simple executable Jar file on Marathon. I start the Jar using the $PORT variable. This works great. The app starts listening on that port, in the example port 41301.
```
INFO  [2015-06-25 13:34:45,252] org.eclipse.jetty.setuid.SetUIDListener: Opened application@3ba74ff0{HTTP/1.1}{0.0.0.0:41301}
```

However, Marathon then somehow decides it is running on port 31775 or another port and reports this back in the JSON blob. This also shows up in the Haproxy config, i.e:
```
listen bd7ed836-0275-47c1-af6c-75e4c6bf2d75_test-app
  bind 0.0.0.0:32768
  mode tcp
  option tcplog
  balance leastconn
  server bd7ed836-0275-47c1-af6c-75e4c6bf2d75_test-app-1 10.176.154.239:31775 check
```

notice the local port 31775. The service port is randomly assigned which is fine. I expect 41301 to be in the location of 31775 however. 

Note: when running Docker containers, this always works fine. This is just when running non-Dockerized Jars.

**Comment by kolloch** [comment]
Hi @tnolet ,

thanks for the report. We need more context. Are you using Marathon 0.8.2? What is the "JSON blob" you are talking about? Do you mean the JSON for the app (which should include the service port) or the JSON for the tasks? Can you provide the JSON as part of your report?

What is creating your haproxy config?

**Comment by tnolet** [comment]
@kolloch 

Hi there, 

some details:

```
marathon version: 0.8.1
mesos: 0.22.1
```

the JSON blob is the output from the `/v2/app/<app_id>` endpoint. I don't have the original output, as it seems to happen intermittently...I know, that doesn't help much.

**Comment by aquamatthias** [comment]
@tnolet A lot has changed here in the past versions. Can you try a more recent version, if that problem still exists? Please reopen if this is the case.
