### ISSUE TITLE
Mesos not working with private Docker registry

### ISSUE THREAD

**Issue by allanliu** [mesosphere/marathon#1708]
I have a private Docker registry that is accessible at https://docker.somedomain.com (over standard port 443 not 5000).  My infrastructure includes a set up of Mesosphere, which have docker containerizer enabled.  I'm am trying to deploy a specific container to a Mesos slave via Marathon; however, this always fails with Mesos failing the task almost immediately with no data in stderr and stdout of that sandbox.  

I tried deploying from an image from the standard Docker Registry and it appears to work fine.  I'm having trouble figuring out what is wrong.  My private Docker registry does not require password authentication (turned off for debugging this), AND if I shell into the Meso's slave instance, and sudo su as root, I can run a 'docker pull docker.somedomain.com/services/myapp' successfully every time.

Here is my Marathon post data for starting the task:
```
    {
      "id": "myapp",
      "cpus": 0.5,
      "mem": 64.0,
      "instances": 1,
      "container": {
        "type": "DOCKER",
        "docker": {
          "image": "docker.somedomain.com/services/myapp:2",
          "network": "BRIDGE",
          "portMappings": [
            { "containerPort": 7000, "hostPort": 0, "servicePort": 0, "protocol": "tcp" }
          ]
        },
        "volumes": [
          {
            "containerPath": "application.yml",
            "hostPath": "/var/myapp/application.yml",
            "mode": "RO"
          }
        ]
      },
      "healthChecks": [
        {
          "protocol": "HTTP",
          "portIndex": 0,
          "path": "/",
          "gracePeriodSeconds": 5,
          "intervalSeconds": 20,
          "maxConsecutiveFailures": 3
        }
      ]
    }   
```
I've been stuck on this for almost a day now, everything I've tried seems to be yielding the same result.  Any insights on this would be much appreciated.

My versions: 
Mesos: 0.22.1
Marathon: 0.8.2
Docker: 1.6.2

**Comment by allanliu** [comment]
Figured it out.

**Comment by anners** [comment]
What was the fix? I am having similar issues with a private repo that does not require password authentication.

**Comment by allanliu** [comment]
Yeah, was just a user error on me ;) .  My registry does have password auth; I just stuck this in my marathon app json, where the downloaded file includes you needed auth tokens/credentials to your registry.  
```
"uris": [
    "http://some.web.server.com/auth/.dockercfg"
  ],
```

**Comment by kmoughon** [comment]
are there options if there isn't a username and pw on the private registry?
