### ISSUE TITLE
Concurrent changes to the same AppDefinition will lead to inconsistent state

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#1709]
One customer makes changes to the same AppDefinition concurrently (simultaneous requests every 10-100 millisecs). This will result in completely broken AppDefinitions.

**Comment by andrewortman** [comment]
Can you elaborate? We want to make sure we don't run into the same issue right now in 0.8.2 

Do we just need to serialize any app definition changes?

**Comment by aquamatthias** [comment]
@andrewortman if you concurrently changes the same application definition at the same time, this can lead to an inconsistent state. I guess/hope this problem is very specific, since most of the time you don't want to change the same app definition at the same time.

**Comment by air** [comment]
Internal tracker MARATHON-200
