### ISSUE TITLE
Too many simultaneous requests will kill Marathon

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#1710]
There are customers, that hit the Marathon API very often (DDOS). This will effectively kill Marathon.

**Comment by air** [comment]
Might be a good case for http://httpstatusdogs.com/429-too-many-requests

**Comment by aquamatthias** [comment]
429 is more related to user rate limits. So I would opt more for a http://httpstatusdogs.com/503-service-unavailable
