### ISSUE TITLE
When proxied, the UI does not go to the correct endpoint

### ISSUE THREAD

**Issue by pyronicide** [mesosphere/marathon#1715]
When I proxy marathon - `http://my-cluster/services/my-marathon`, AJAX requests are sent to `http://my-cluster/v2/apps` instead of the correct URL which would be `http://my-cluster/services/my-marathon/v2/apps`.

**Comment by aldipower** [comment]
On which version this happens?
Should be solved by https://github.com/mesosphere/marathon/pull/1500

**Comment by pyronicide** [comment]
0.9.0-RC2

**Comment by philipnrmn** [comment]
This was fixed by @rcorral's commit [Building assets, getting ready for release](https://github.com/mesosphere/marathon-ui/commit/67bc3499f2a3bcf58008f1ca71747dcf72e44941).

The issue was that although this issue had been fixed, the `dist/main.js` file was out of date.
