### ISSUE TITLE
Not able to scale apps or deploy apps have plenty of resourses

### ISSUE THREAD

**Issue by svennela** [mesosphere/marathon#1719]
Hi ,

I am not able to scale apps, I am deploying simple app and not able to scale more than number of instances and i have plenty of resources. Please see below links of my marathon and mesos installations.

{
    "id": "serverspecs-app6", 
    "cmd": "while [ true ] ; do echo 'Hello Marathon' ; sleep 5 ; done",
    "cpus": 0.1,
    "mem": 10.0,
    "instances": 1
}

![screen shot 2015-06-26 at 6 55 11 pm](https://cloud.githubusercontent.com/assets/1060246/8389992/09e5547a-1c35-11e5-9e1b-8d7655da054e.png)
![screen shot 2015-06-26 at 6 54 33 pm](https://cloud.githubusercontent.com/assets/1060246/8389993/0c08c444-1c35-11e5-8c90-65f3bf3739d4.png)
![screen shot 2015-06-26 at 6 54 19 pm](https://cloud.githubusercontent.com/assets/1060246/8389995/0eaee5ac-1c35-11e5-8327-c523baa9cd89.png)

**Comment by svennela** [comment]
It is not able to scale beyond 38 instance(20+17+1). thats really weird.

**Comment by EvanKrall** [comment]
Looks like you're nearly out of CPUs.

Mesos has had floating point rounding issues in the past; I wonder if you actually have two 0.09999 CPU blocks free, neither of which is big enough for the 0.1 CPUs you need for your task.

**Comment by svennela** [comment]
Ok. I removed all the instance. Uploaded below tomcat app to marathon. Even though it still has 2 CPU's and 976 MB free memory it is stuck in deployment state. Where do i see errors and status of deployment? Please help?



{
  "id": "tomcat",
  "cmd": "mv *.war apache-tomcat-*/webapps && cd apache-tomcat-* && sed \"s/8080/$PORT/g\" < ./conf/server.xml > ./conf/server-mesos.xml && ./bin/catalina.sh run -config ./conf/server-mesos.xml",
  "mem": 512,
  "cpus": 0.5,
  "instances": 1,
  "uris": [
    "http://mirrors.gigenet.com/apache/tomcat/tomcat-8/v8.0.23/bin/apache-tomcat-8.0.23.tar.gz",
    "https://gwt-examples.googlecode.com/files/Calendar.war"
  ]
}

![screen shot 2015-06-29 at 5 41 50 pm](https://cloud.githubusercontent.com/assets/1060246/8421648/bac02c5e-1e86-11e5-9247-6c68cb01759b.png)
![screen shot 2015-06-29 at 5 41 37 pm](https://cloud.githubusercontent.com/assets/1060246/8421650/be49ec98-1e86-11e5-8a32-de845db645e1.png)

**Comment by rasputnik** [comment]
You can usually see failed sandboxes further down the main mesos UI window; that should give you a hint if your launch command is incorrect (I can see a typo here : "mv .war apache-tomcat-/webapps").

**Comment by aquamatthias** [comment]
Hey @svennela 
if you paste the cmd you provided on the command line - will it launch the application correctly?

**Comment by svennela** [comment]
Hi @aquamatthias 
Its not about application launching. If you deploy same command in your marathon environment, it will be deployed. I did same json deploy for tomcat instance if you see above. All i am testing is when will mesos will stop loading new applications, hopefully once capacity is out. In this case even though i have enough memory and CPU to process, deployment is stuck.
You can try to deploy same json it will be deployed.

**Comment by aquamatthias** [comment]
@svennela 
You can look at the Marathon log (syslog) to see if there are incoming offers from slaves.
If there are offers, the capacity is not the problem.
Look inside the mesos sandbox to see log files of the launched application.
In case of a misconfigured application the task will exit immediately and marathon will retry to deploy.
The application then hangs in Deploying state as in your example.

**Comment by svennela** [comment]
@aquamatthias ,

Sure.

**Comment by mconigliaro** [comment]
I'm having a similar issue right now, but with a brand new app. It just sits there in the "Deploying" state. @svennela how can I look at the sandbox if the task never appears in Mesos? Anything else I should look at?

**Comment by mconigliaro** [comment]
Here's the relevant messages from my Marathon log when I try to create a new app via the API:

```
{
  "id": "test",
  "cmd": "cd /tmp; python -m SimpleHTTPServer $PORT",
  "cpus": 0.1,
  "mem": 10.0,
  "instances": 1
}
```

```
curl -X POST http://192.168.33.100:8080/v2/apps -d @test.json -H 'Content-type: application/json'
```

```
Jul  8 00:18:14 vagrant marathon[6416]: [2015-07-08 00:18:14,297] INFO Upgrade id:/ version:2015-07-08T00:18:14.294Z with force:false (mesosphere.marathon.state.GroupManager:124)
Jul  8 00:18:14 vagrant marathon[6416]: [2015-07-08 00:18:14,300] INFO Take next configured free port: 10000 (mesosphere.marathon.state.GroupManager:186)
Jul  8 00:18:14 vagrant marathon[6416]: [2015-07-08 00:18:14,302] INFO Compute DeploymentPlan from Group(/,Set(),Set(),Set(),2015-07-08T00:18:04.548Z) to Group(/,Set(AppDefinition(/test,Some(cd /tmp; python -m SimpleHTTPServer $PORT),None,None,Map(),1,0.1,10.0,0.0,,Set(),List(),List(),List(10000),false,1 second,1.15,3600 seconds,None,Set(),Set(),UpgradeStrategy(1.0,1.0),Map(),2015-07-08T00:18:14.294Z)),Set(),Set(),2015-07-08T00:18:14.294Z) (mesosphere.marathon.upgrade.DeploymentPlan$:211)
Jul  8 00:18:14 vagrant marathon[6416]: [2015-07-08 00:18:14,304] INFO Computed new deployment plan: DeploymentPlan(2015-07-08T00:18:14.294Z, (Step(Vector(Start(App(/test, Some(cd /tmp; python -m SimpleHTTPServer $PORT))), 0))), Step(Vector(Scale(App(/test, Some(cd /tmp; python -m SimpleHTTPServer $PORT))), 1))))) (mesosphere.marathon.upgrade.DeploymentPlan$:265)
Jul  8 00:18:14 vagrant marathon[6416]: [2015-07-08 00:18:14,304] INFO Deploy plan:DeploymentPlan(2015-07-08T00:18:14.294Z, (Step(Vector(Start(App(/test, Some(cd /tmp; python -m SimpleHTTPServer $PORT))), 0))), Step(Vector(Scale(App(/test, Some(cd /tmp; python -m SimpleHTTPServer $PORT))), 1))))) with force:false (mesosphere.marathon.MarathonSchedulerService:102)
Jul  8 00:18:14 vagrant marathon[6416]: [2015-07-08 00:18:14,321] INFO Compute DeploymentPlan from Group(/,Set(),Set(),Set(),2015-07-08T00:18:04.548Z) to Group(/,Set(AppDefinition(/test,Some(cd /tmp; python -m SimpleHTTPServer $PORT),None,None,Map(),1,0.1,10.0,0.0,,Set(),Vector(),Vector(),Vector(10000),false,1000 milliseconds,1.15,3600000 milliseconds,None,Set(),Set(),UpgradeStrategy(1.0,1.0),Map(),2015-07-08T00:18:14.294Z)),Set(),Set(),2015-07-08T00:18:14.294Z) (mesosphere.marathon.upgrade.DeploymentPlan$:211)
Jul  8 00:18:14 vagrant marathon[6416]: [2015-07-08 00:18:14,325] INFO Computed new deployment plan: DeploymentPlan(2015-07-08T00:18:14.294Z, (Step(Vector(Start(App(/test, Some(cd /tmp; python -m SimpleHTTPServer $PORT))), 0))), Step(Vector(Scale(App(/test, Some(cd /tmp; python -m SimpleHTTPServer $PORT))), 1))))) (mesosphere.marathon.upgrade.DeploymentPlan$:265)
Jul  8 00:18:14 vagrant marathon[6416]: [2015-07-08 00:18:14,332] INFO 192.168.33.1 -  -  [08/Jul/2015:00:18:14 +0000] "POST /v2/apps HTTP/1.1" 201 620 "-" "curl/7.37.1" (mesosphere.chaos.http.ChaosRequestLog:15)
Jul  8 00:18:14 vagrant marathon[6416]: [2015-07-08 00:18:14,333] INFO Deployment acknowledged. Waiting to get processed: DeploymentPlan(2015-07-08T00:18:14.294Z, (Step(Vector(Start(App(/test, Some(cd /tmp; python -m SimpleHTTPServer $PORT))), 0))), Step(Vector(Scale(App(/test, Some(cd /tmp; python -m SimpleHTTPServer $PORT))), 1))))) (mesosphere.marathon.state.GroupManager:143)
Jul  8 00:18:14 vagrant marathon[6416]: [2015-07-08 00:18:14,344] INFO Compute DeploymentPlan from Group(/,Set(),Set(),Set(),2015-07-08T00:18:04.548Z) to Group(/,Set(AppDefinition(/test,Some(cd /tmp; python -m SimpleHTTPServer $PORT),None,None,Map(),1,0.1,10.0,0.0,,Set(),Vector(),Vector(),Vector(10000),false,1000 milliseconds,1.15,3600000 milliseconds,None,Set(),Set(),UpgradeStrategy(1.0,1.0),Map(),2015-07-08T00:18:14.294Z)),Set(),Set(),2015-07-08T00:18:14.294Z) (mesosphere.marathon.upgrade.DeploymentPlan$:211)
Jul  8 00:18:14 vagrant marathon[6416]: [2015-07-08 00:18:14,345] INFO Computed new deployment plan: DeploymentPlan(2015-07-08T00:18:14.294Z, (Step(Vector(Start(App(/test, Some(cd /tmp; python -m SimpleHTTPServer $PORT))), 0))), Step(Vector(Scale(App(/test, Some(cd /tmp; python -m SimpleHTTPServer $PORT))), 1))))) (mesosphere.marathon.upgrade.DeploymentPlan$:265)
Jul  8 00:18:14 vagrant marathon[6416]: [INFO] [07/08/2015 00:18:14.373] [marathon-akka.actor.default-dispatcher-2] [akka://marathon/user/MarathonScheduler/$a/UpgradeManager/2d22cf7b-4a59-4d86-9c88-60012c08ba79/$a] Successfully started 0 instances of /test
Jul  8 00:18:14 vagrant marathon[6416]: [2015-07-08 00:18:14,676] INFO 192.168.33.1 -  -  [08/Jul/2015:00:18:14 +0000] "GET /v2/apps HTTP/1.1" 200 624 "http://192.168.33.100:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36" (mesosphere.chaos.http.ChaosRequestLog:15)
Jul  8 00:18:14 vagrant marathon[6416]: [2015-07-08 00:18:14,705] INFO 192.168.33.1 -  -  [08/Jul/2015:00:18:14 +0000] "GET /v2/deployments HTTP/1.1" 200 305 "http://192.168.33.100:8080/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/43.0.2357.130 Safari/537.36" (mesosphere.chaos.http.ChaosRequestLog:15)
Jul  8 00:18:19 vagrant marathon[6416]: [INFO] [07/08/2015 00:18:19.385] [marathon-akka.actor.default-dispatcher-2] [akka://marathon/user/MarathonScheduler/$a/UpgradeManager/2d22cf7b-4a59-4d86-9c88-60012c08ba79/$a] Message [mesosphere.marathon.upgrade.StartingBehavior$Sync$] from Actor[akka://marathon/user/MarathonScheduler/$a/UpgradeManager/2d22cf7b-4a59-4d86-9c88-60012c08ba79/$a#1984028037] to Actor[akka://marathon/user/MarathonScheduler/$a/UpgradeManager/2d22cf7b-4a59-4d86-9c88-60012c08ba79/$a#1984028037] was not delivered. [8] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
```

I'm very new to Mesos/Marathon, but the messages that stand out to me are "Successfully started 0 instances of /test" and the one about akka not being able to deliver a message (dead letters?).

**Comment by mconigliaro** [comment]
FWIW, I just restarted my entire cluster and got things working again. One thing I noticed is that when it wasn't working, I had two active Marathon frameworks listed in Mesos (I have Marathon running on all three of my masters). It's not totally clear to me whether I should have an active framework listed for every running Marathon instance, or if I should only see one.

**Comment by kolloch** [comment]
@mconigliaro If you use the same zookeeper path to store state, Marathon should only register once with Mesos. You can run multiple Marathon instances on the same Mesos cluster, though, they should use different framework names and different zookeeper paths to store their state.
