### ISSUE TITLE
Github release archives don't contain the UI files

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#1720]
The archivers offered on the [marathon github release page](https://github.com/mesosphere/marathon/releases) do not contain the UI files. Inside the archive, the `assets` directory is empty.

**Comment by aldipower** [comment]
The archives built by TeamCity and offered on the official download location does. So this files could be attached/uploaded to the GitHub release, instead of package them with GitHub.
We have _two_ ways of packaging here and should eliminate one.

**Comment by aldipower** [comment]
There is no assets directory anymore at all. The UI is intergrated as a Webjar sind 0.12.0 .

**Comment by philipnrmn** [comment]
:+1:
