### ISSUE TITLE
Define workflow for maintaining (or not) /dist folder

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#1721]
If we want to keep the `/dist` folder in the marathon-ui repo, we currently would need to 

1. make sure it's up-to-date with master
2. require the developers to keep track of this manually
3. have an extra commit for each PR ("Update dist folder with latest versions")

I think this is clumsy and that we should find a better solution.
To me the very necessity of maintaining the `/dist` folder is up for debate. I personally can't think of any specific good reason why we should keep distributing it inside this repository (especially since we will be bundling a .war file within marathon soon), but I can definitely say that it's currently not very clear what the contents of this folder should be reflecting: current master? latest release/tag? 

Let's first agree wether or not we should maintain the compiled assets, and if so let's find a workflow that makes sense!

cc @mlunoe @rcorral @aldipower @philipnrmn @aquamatthias

**Comment by pierlo-upitup** [comment]
Related https://github.com/mesosphere/marathon/issues/1720

**Comment by aquamatthias** [comment]
I think it is generally a very bad idea to checkin generated code.

Suggested working mode:
-marathon-ui holds only src code
-marathon-ui has a build tool, that can create a versioned dist package (webjar)
-every merge on master triggers a TeamCity job, that uses the build tool, creates a versioned dist, uploads the dist to our s3 repo 
-marathon adds a dependency to the marathon-ui

**Comment by aldipower** [comment]
The 'dist'-files shouldn't be added at every PR.

@aquamatthias already have good ideas that I want to extend.
I think if we increase the version number in package.json they should be build and added. That is the point where the CHANGELOG also gets modified.
Also they are already built in TC on release.
And we have this ticket created to build a .war-file that can be included into the main Marathon package.
https://github.com/mesosphere/marathon/issues/1673

**Comment by philipnrmn** [comment]
I'd really like to remove dist from VC, at least in the UI project. 

I like @aquamatthias' and @aldipower's suggestions.

**Comment by pierlo-upitup** [comment]
https://github.com/mesosphere/marathon-ui/pull/66
