### ISSUE TITLE
Add doc about response message

### ISSUE THREAD

**Issue by tamarrow** [mesosphere/marathon#1722]
It's mentioned `https://mesosphere.github.io/marathon/docs/rest-api.html` but not specified.

**Comment by aquamatthias** [comment]
@tamarrow Can you please be more specific - in this document are a lot of response messages. Which one is missing?

**Comment by tamarrow** [comment]
It might be useful to explicitly state that the responses return info in a `message` field. This came up when a bad marathon request returned a [non-standard response](https://github.com/mesosphere/dcos-cli/pull/233)

**Comment by aquamatthias** [comment]
I see. But which request produces this (non-standard) response?

**Comment by tamarrow** [comment]
For example:  
http://tamar2-elasticload-af0qr2iejzjg-849044751.us-west-2.elb.amazonaws.com/marathon/v2/apps/%7B
returns a response that can't be json parsed and has no `message`.

**Comment by mgummelt** [comment]
@aquamatthias: We had a CLI error where due to parsing weirdness, a user species an app ID of "{instances:"

This gets translated to a request for /v2/apps/%7Binstances%3A

Despite this technically adhering to the API (apps/... is valid ASCII), marathon returns a 400 Bad Request

I would expect:

```
 {
"message": "App '{instances:' does not exist"
}
```

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3031. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
