### ISSUE TITLE
HOST networking mode with portMappings set should fail validation

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#1729]
This combination is never valid, and always will cause an error that is hard to track down (task launch fails in the Docker containerizer).  Marthon could detect the problem early and emit a warning to the user.

**Comment by kolloch** [comment]
+1

**Comment by akerekes** [comment]
+1

We just have spent a couple of man-hours to track this down.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3659. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
