### ISSUE TITLE
cannot create a working cluster

### ISSUE THREAD

**Issue by ee1200231** [mesosphere/marathon#1731]
A working multi node cluster setup has been given here: http://open.mesosphere.com/getting-started/datacenter/install/

I use 2 host, both running CentOS 7. One is used as both master and slave and works fine. The other is used as a slave only and it doesnt work. The slave process remains as "activating" but never gets activated and hence the master never detects it. Please help.

**Comment by kolloch** [comment]
Hi @ee1200231 , that does not seem to be a Marathon problem. Please ask on Mesos mailing list/IRC...
