### ISSUE TITLE
Refactor components: introduce EventBinder mixin

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#1737]
A lot of components need "boilerplate" code to bind to store events on mount, unmount and so on, as initially noted by @rcorral [here](https://github.com/mesosphere/marathon-ui/pull/59#discussion_r33611170). I suggest to introduce a mixin that would perform the binding/unbinding in the various lifecycle methods, and let the components expose a property or a function that return the event/callback mappings. 

~~TODO post merge https://github.com/mesosphere/marathon-ui/pull/59~~

**Comment by aldipower** [comment]
@rcorral @pierlo-upitup
Could I have an example for the mixin, if I want to access more than one stores like this?
```
  componentWillMount: function () {
    AppsStore.on(AppsEvents.DELETE_APP, 
     this.onDeleteAppSuccess);
    QueueStore.on(QueueEvents.RESET_DELAY, 
     this.onResetDelaySuccess);
  },

  componentWillUnmount: function () {
    AppsStore.removeListener(AppsEvents.DELETE_APP,
      this.onDeleteAppSuccess);
    QueueStore.removeListener(QueueEvents.RESET_DELAY,
      this.onResetDelaySuccess);
  },
```
It could be look like this?
```
this.events = [
  [AppsStore, AppsEvents.DELETE_APP, this.onDeleteAppSuccess],
  [QueueStore, QueueEvents.RESET_DELAY, this.onResetDelaySuccess]
]
```
Not sure if I like that..

**Comment by pierlo-upitup** [comment]
I think @mlunoe did some work on a similar thing, let's pull him in.

**Comment by mlunoe** [comment]
Hmm... not sure what you are referring to @pierlo-upitup?
But wouldn't something like this work:
```
var StoreMountMixin = {

  storeMountMixin_events: [],

  componentWillMount: function () {
    this.storeMountMixin_events.forEach(function (event) {
      if (_.isFunction(event.store.addChangeListener),
        _.isString(event.name),
        _.isFunction(event.callback)) {
        event.store.addChangeListener(event.name, event.callback);
      } else {
        throw new Error("storeMountMixin_events needs to be an array of objects with a store that extends EventEmitter, name (string) and a callback (function)");
      }
    });
  },

  componentWillUnmount: function () {
    this.storeMountMixin_events.forEach(function (event) {
      if (_.isFunction(event.store.addChangeListener),
        _.isString(event.name),
        _.isFunction(event.callback)) {
        event.store.removeChangeListener(event.name, event.callback);
      } else {
        throw new Error("storeMountMixin_events needs to be an array of objects with a store that extends EventEmitter, name (string) and a callback (function)");
      }
    });
  }
};
```

And then use it like this:
```
var ComponentName = React.createClass({
  mixins: [StoreMountMixin],
  storeMountMixin_events: [
    {
      store: AppsStore,
      name: AppsEvents.DELETE_APP,
      callback: this.onDeleteAppSuccess
    },
    {
      store: QueueStore,
      name: QueueEvents.RESET_DELAY,
      callback: this.onResetDelaySuccess
    }
  ]
});
```

Not sure if this makes things nicer though, and I didn't use the new way of creating mixins: https://medium.com/@dan_abramov/mixins-are-dead-long-live-higher-order-components-94a0d2f9e750

*NB: Didn't test this out at all*

**Comment by pierlo-upitup** [comment]
Reviewing this issue some time later, I have to say I prefer the more explicit approach of binding/unbinding events, and see no real advantage in doing so with a mixin. Closing!
