### ISSUE TITLE
Merge CHANGELOG files upon release?

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#1746]
I would like to know your opinion about possibly merging the CHANGELOG files automatically upon release. So that the UI changelog becomes a chapter of the main Marathon's own.

Do you think this is a sensible thing to do? If so, let's discuss technicalities here.

@aquamatthias @kolloch @gkleiman 

Reference https://github.com/mesosphere/marathon-ui/pull/67

**Comment by aquamatthias** [comment]
We try hard to document all changes in the changelog.md file.
When doing a release, this information is used to fill the release notes.

I think it makes sense to make the UI changelog part of the general changelog when creating a release.
You speak about an automatism - how can that work?

**Comment by kolloch** [comment]
Hi Perluigi,

I think it would suffice if you created your own changelog.md which we then
merge into our release notes upon release.

You could also directly append to our changelog.md but if I understood it
correctly, you want to choose freely which UI release you bundle with a
backend release. Then the manual approach is the best, I guess.

The changelog has to be copied manually into the github release text and
into the release emails anyway, so we cannot fully automate it, I guess. I
wouldn't mind automation, though, if we ensure manual review before the
release.

Best regards,
Peter

**Comment by pierlo-upitup** [comment]
Thanks for the input @kolloch – as we are in the process of creating our CHANGELOG.md file I wanted to make sure we are not adding additional workload on your shoulders, but if you have to assemble the release notes manually anyway maybe we can just [KISS](https://en.wikipedia.org/wiki/KISS_principle) for now ;-)
