### ISSUE TITLE
UI: Allow administratively zeroing / resetting the taskLaunchDelay

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#1754]
See #1681

- [x] See the task launch delay in the UI if there is one.
- [x] Reset the task launch delay for one application, if there is one.

**Comment by aldipower** [comment]
App with task execution delay on mouse hover:
![task-delay](https://cloud.githubusercontent.com/assets/859154/8596958/b952cdee-2652-11e5-8e38-7f9b347b5395.png)
If it has a delay there is a "Reset delay" button on the app page:
![task-delay-button](https://cloud.githubusercontent.com/assets/859154/8596959/bae5227e-2652-11e5-853c-c483d8f5d8f2.png)
Waiting on offers:
![tasks-waiting](https://cloud.githubusercontent.com/assets/859154/8596962/bc6e101a-2652-11e5-9f58-7b20ee730e7b.png)
