### ISSUE TITLE
Create a "Not found page"

### ISSUE THREAD

**Issue by aldipower** [mesosphere/marathon#1756]
The UI should display a "Not found page" on an incorrect route.

F.ex.:
http://marathon-ui:8080/#this-is-not-here
should display a not found page.

**Comment by xiaods** [comment]
indeed. +1

**Comment by pierlo-upitup** [comment]
There are currently two cases: 

1. An non-existing endpoint (e.g. "/foobar")
2. A not found route (e.g. "/#/foobar")

Should both cases produce the same error page? @aquamatthias @philipnrmn

**Comment by pierlo-upitup** [comment]
Let's concentrate on the [NotFoundRoute](http://rackt.github.io/react-router/#NotFoundRoute) for the moment. Redirecting all 404s outside of the frontend does not seem like a good idea.
