### ISSUE TITLE
enhancement: add a `name` property to `health checks`

### ISSUE THREAD

**Issue by Kosta-Github** [mesosphere/marathon#1764]
IMHO, it would make sense, to be able to add a `name` and/or `description` to the `health check` [definition](https://mesosphere.github.io/marathon/docs/health-checks.html).

**Comment by pierlo-upitup** [comment]
Hi @Kosta-Github,

thanks for the suggestion. Could you elaborate what would be the use case for this?

**Comment by Kosta-Github** [comment]
If you define several health checks for an app/task, you can name them accordingly and use it for displaying the failing tests in the UI.

E.g., if you are using docker containers hosting several services (https://github.com/scullxbones/docker_grafana_statsd_elk), you can define individual health checks for each service and then distinguish them in the UI.

**Comment by pierlo-upitup** [comment]
Thanks for the suggestion, we added this suggestion to our backlog.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2836. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
