### ISSUE TITLE
Add container image name to environment

### ISSUE THREAD

**Issue by marcust** [mesosphere/marathon#1766]
Currently marathon exports three variables into the environment of a dockerized application:
MARATHON_APP_VERSION, MARATHON_APP_ID and MESOS_TASK_ID.

For my current use case it would come in quite handy if more information would be available, namely the actual image that is used, something like MARATHON_APP_DOCKER_IMAGE.

Any chance to get this added?

**Comment by kolloch** [comment]
Hi @marcust, it would be an easy change. Can you elaborate on your use case to make us understand that better?

We also accept PRs. The code is in mesosphere.mesos.TaskBuilder#taskContextEnv.

https://mesosphere.github.io/marathon/docs/contributing.html

**Comment by marcust** [comment]
My use case is basically logging from inside the container, we want to add some meta information about what is actually running and the current image (including version tag) would come in handy.

My Scala foo is actually not good enough to have a really idiomatic way to find out if have a Container of type DOCKER or whatever else there is, so I figured the feature request would be easier ;)

**Comment by kolloch** [comment]
I will do this for a beer :)

**Comment by marcust** [comment]
I will buy you one next time I'm in Hamburg

**Comment by xiaods** [comment]
it is DefaultContainer?

**Comment by kolloch** [comment]
Hi @xiaods, I do not understand your question.

@marcust, can you test my PR? Thanks.

**Comment by xiaods** [comment]
@kolloch ignore my comments.
