### ISSUE TITLE
Implement marathon components for mesos persistent data stores

### ISSUE THREAD

**Issue by cmluciano** [mesosphere/marathon#1769]
https://issues.apache.org/jira/browse/MESOS-2205 Add user documentation for reservations
https://issues.apache.org/jira/browse/MESOS-2018 Dynamic Reservation (target 0.24.0)
https://issues.apache.org/jira/browse/MESOS-1554 Persistent resources support for storage-like services (target 0.24.0)

All three issues should be landing or have landed in mesos. It would be nice to create volumes like these from marathon, and then one could reference the volume from application.json.

**Comment by cmluciano** [comment]
More info for frameworks here https://github.com/apache/mesos/blob/master/docs/persistent-volume.md

**Comment by kolloch** [comment]
Definitely. They are targeted for Mesos 0.24.0, though.

**Comment by kolloch** [comment]
(I hope you didn't mind my updating your description with titles and target versions)

**Comment by cmluciano** [comment]
Nope that works for me :)

**Comment by xiaods** [comment]
what proposal to Implement the marathon component?

**Comment by mindscratch** [comment]
Is this related to #2493?

**Comment by cmluciano** [comment]
Yes

**Comment by cmluciano** [comment]
Since that ticket has more traction, I will just close this one
