### ISSUE TITLE
Secure event_subscriber callbacks

### ISSUE THREAD

**Issue by jstabenow** [mesosphere/marathon#1772]
Hey,
I want to secure an application based upon the Marathon-Event-Bus and couldn’t find a good solution.
Can anyone tell me if https_callbacks (https://...) and/or „Basic Auth“ (admin:password@...) are also planned for the event_subscriber in the future? Or are there already better approaches?

**Comment by xiaods** [comment]
@jstabenow you can read here doc:
https://github.com/mesosphere/marathon/blob/master/docs/docs/ssl-basic-access-authentication.md

**Comment by gkleiman** [comment]
@jstabenow as @xiaods hints, you can probably achieve what you need using SSL + Basic Access Authentication + the events stream endpoint (GET /v2/events).

Please reopen the issue if that doesn't fit your use case.

**Comment by jstabenow** [comment]
@gkleiman thanks for your hint. the stream endpoint seems the better way to be.
