### ISSUE TITLE
Support yaml as input format in the API

### ISSUE THREAD

**Issue by sttts** [mesosphere/marathon#1775]
YAML is much easier to write manually than JSON. JSON files get harder to read and maintain the bigger they get. YAML has support for multiline strings, JSON doesn't. App CMD strings with >500 characters are no fun in JSON.

**Comment by bobrik** [comment]
Also comments, YAML supports comments.

**Comment by aquamatthias** [comment]
Thought of that as well so often. Really like the idea.
:+1:

**Comment by bsideup** [comment]
:+1:

**Comment by MikeMichel** [comment]
+1

**Comment by kolloch** [comment]
Do you think one could simply put a YAML to JSON converter in front of the logic that we have now? All validation errors (beyond YAML syntax errors) would then of course relate to the JSON...

**Comment by bsideup** [comment]
@kolloch YAML is just an extension to JSON btw :) So Marathon could replace JSON parser with YML and it MUST be backward compatible

**Comment by MikeMichel** [comment]
sry, could not resist 
![image](https://cloud.githubusercontent.com/assets/8025931/8958169/701ef100-3603-11e5-9ad9-8809ee36a8ab.png)

**Comment by pierlo-upitup** [comment]
:laughing:

**Comment by shtratos** [comment]
+1

**Comment by aronica** [comment]
It's much easy use docker compose to express the relationship of two containers than using group in marathon.

**Comment by j3k0** [comment]
:+1:

**Comment by tsaridas** [comment]
+1

**Comment by charlesmims** [comment]
+1

**Comment by EMChamp** [comment]
+1, JSON gets horribly complicated to maintain and readability suffers.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2710. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
