### ISSUE TITLE
If user attempts to POST over an existing app, suggest they use PUT

### ISSUE THREAD

**Issue by ssk2** [mesosphere/marathon#1779]
I'm trying to update an application and thought that I could simply POST over it. Marathon doesn't like this.

```
Q-M:marathon-test sunil$ http -v POST http://<snipped>:8080/v2/apps < demo.json
POST /v2/apps HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 239
Content-Type: application/json
Host: <snipped>:8080
User-Agent: HTTPie/0.9.2

{
    "cmd": "python -m SimpleHTTPServer $PORT",
    "container": {
        "docker": {
            "image": "superguenter/demo-app"
        },
        "type": "DOCKER"
    },
    "cpus": 0.01,
    "id": "demo",
    "instances": 300,
    "mem": 256,
    "ports": [
        3000
    ]
}

HTTP/1.1 409 Conflict
Access-Control-Allow-Headers:
Access-Control-Allow-Methods: GET, HEAD, OPTIONS
Access-Control-Allow-Origin: *
Access-Control-Max-Age: 86400
Cache-Control: no-cache, no-store, must-revalidate
Content-Type: application/json
Expires: 0
Pragma: no-cache
Server: Jetty(8.y.z-SNAPSHOT)
Transfer-Encoding: chunked
X-Marathon-Leader: http://<snipped>:8080

{
    "message": "An app with id [demo] already exists."
}
```

It'd be helpful if the error message could suggest using `PUT /v2/apps/<appid>` if I had intended to update it.

**Comment by dotcomputercraft** [comment]
Is there a solution to this issue (1779).  I'm looking for a resolution to this same problem.  Thank you in advance

**Comment by ssk2** [comment]
@dotcomputercraft - are you able to deploy your application? I think just using PUT and changing the URL to include your application ID will work.

**Comment by dotcomputercraft** [comment]
@ssk2 -  Thank you. yes, I used PUT verb to solve the issue.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2871. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
