### ISSUE TITLE
When app is locked by deployment, deleting tasks via the UI does nothing

### ISSUE THREAD

**Issue by ssk2** [mesosphere/marathon#1780]
If I have an application that is locked by a deployment (due to an update to the application definition or similar), I'm able to go into that application via the UI and select and kill tasks. They then disappear from the UI but actually never stop running. They will re-appear when you refresh.

![image](https://cloud.githubusercontent.com/assets/355705/8606620/a8629804-2641-11e5-8530-043005857935.png)

The correct response should be an error message, similar to when you try to scale an app that is locked by a deployment.

![image](https://cloud.githubusercontent.com/assets/355705/8606626/b5a85a94-2641-11e5-834c-ce0e54e022a6.png)

**Comment by pierlo-upitup** [comment]
Depends on https://github.com/mesosphere/marathon/issues/1835

**Comment by aquamatthias** [comment]
This has been fixed in the service layer and should be fixed in the UI as well.

**Comment by pierlo-upitup** [comment]
@aquamatthias thanks for the heads up.
