### ISSUE TITLE
Authenticated private registry seems to fail with Docker 1.7 auth format?

### ISSUE THREAD

**Issue by pdzilla** [mesosphere/marathon#1781]
Marathon 0.8.2, Mesos 0.22.1, Docker 1.7.0

I've got a herd of boxes in a mesos + marathon cluster which run Docker 1.7.0 and pull their images from a private registry that uses authentication. I've not had issues with public registries executing the same tasks.

On each mesos slave, I've actually got login credentials for the private registry in the .docker/config.json file, so I added that file as a URI in the marathon app spec.  To wit, if I run `docker pull` from the CLI of the mesos slave, it pulls just fine.

When trying to make magic with Marathon, though, I get the errors further below in `mesos-slave.ERROR`

```json
{
	"container": {
    "type": "DOCKER",
    "docker": {
      "image": "docker-registry.domain:443/image:latest",
      "forcePullImage": true,
      "network": "BRIDGE",
      "privileged": false,
      "portMappings": [
        {
          "containerPort": 8080,
          "hostPort": 0,
          "servicePort": 8080,
          "protocol": "tcp"
        }
      ],
      "parameters": [
        { "key": "env", "value": "ENV=dev" }
      ]
    }
  },
  "id": "tomcat",
	"cpus": 0.5,
	"mem": 512.0,
	"instances": 2,
  "uris": [
    "file://localhost/root/.docker/config.json"
  ],
  "cmd": "$CATALINA_HOME/bin/catalina.sh run",
  "constraints": [
    ["hostname", "UNIQUE"]
  ],
  "labels": {
    "environment": "dev",
    "network": "Red"
  },
  "healthChecks": [
    {
      "protocol": "TCP",
      "gracePeriodSeconds": 3,
      "intervalSeconds": 10,
      "timeoutSeconds": 10,
      "maxConsecutiveFailures": 3
    }
  ],
  "upgradeStrategy": {
    "minimumHealthCapacity": 0.5,
    "maximumOverCapacity": 0.25
  }
}
```

mesos-slave.ERROR errors
```
E0710 05:08:34.904747  6066 slave.cpp:3112] Container 'adc2312f-7072-4f25-bfb1-91f022354713' for executor 'tomcat.b706d5c5-26c1-11e5-bd2e-b6087a30df50' of framework '20150626-194757-3682254739-5050-27187-0000' failed to start: Failed to 'docker pull docker-registry.domain:443/image:latest': exit status = exited with status 1 stderr =
E0710 05:08:34.906522  6066 slave.cpp:3207] Termination of executor 'tomcat.b706d5c5-26c1-11e5-bd2e-b6087a30df50' of framework '20150626-194757-3682254739-5050-27187-0000' failed: Unknown container: adc2312f-7072-4f25-bfb1-91f022354713
E0710 05:08:34.907197  6069 slave.cpp:3461] Failed to unmonitor container for executor tomcat.b706d5c5-26c1-11e5-bd2e-b6087a30df50 of framework 20150626-194757-3682254739-5050-27187-0000: Not monitored
```

Looking at Mesos' Sandbox stderr for this host and task, this is all that's there (info level stuff):

```
I0710 05:19:39.338995 27104 fetcher.cpp:214] Fetching URI 'file://localhost/root/.docker/config.json'
I0710 05:19:39.339140 27104 fetcher.cpp:194] Copying resource from '/root/.docker/config.json' to '/tmp/mesos/slaves/20150626-194757-3682254739-5050-27187-S11/frameworks/20150626-194757-3682254739-5050-27187-0000/executors/tomcat.43362beb-26c3-11e5-bd2e-b6087a30df50/runs/fc2a6e08-a13e-4c8b-9409-11f380f4830f'
I0710 05:19:39.343672 27104 fetcher.cpp:329] Skipped extracting path '/tmp/mesos/slaves/20150626-194757-3682254739-5050-27187-S11/frameworks/20150626-194757-3682254739-5050-27187-0000/executors/tomcat.43362beb-26c3-11e5-bd2e-b6087a30df50/runs/fc2a6e08-a13e-4c8b-9409-11f380f4830f/config.json'
```

I tried re-formatting config.json into .dockercfg, but the underlying Docker barfed on that saying it's the wrong auth format.

I admit to being a new user of Marathon; am I missing the painfully obvious or is there legitimately something wrong here? Happy to grab other info if it would help.

**Comment by mcoffin** [comment]
I'm not 100% sure here, but I'd imagine it's becuase it's copying config.json effectively in to `$HOME/config.json` instead of `$HOME/.docker/config.json`, so the docker executable is having a hard time finding it. I could be wrong though.

**Comment by xiaods** [comment]
you need tar the config.json with URI link, then the marathon will uncompress the tar file first.

**Comment by xiaods** [comment]
In order to solve this, you can create a tar.gz file containing the directory structure as:
```
# tar -tvf docker.tar.gz
drwxr-xr-x root/root         0 2015-07-10 09:56 .docker/
-rw------- root/root       136 2015-07-09 13:46 .docker/config.json
```

**Comment by xiaods** [comment]
Currently Mesos still only support registry 1.0, it should be better if it support registry 2.0.

**Comment by aquamatthias** [comment]
@pdzilla Did that solve your problems? If so please close this ticket.

**Comment by albertsj1** [comment]
I'm having the same issue.  I can't seem to get Marathon/Mesos to use the creds I supply in the docker.tar.gz to login to the registry and then pull the image.  Marathon 0.10.0, Mesos 0.22.1-1.0 from mesossphere rpm repo.
I can see using the mesos UI looking at the sandbox, the docker.tar.gz is downloaded and unzipped and the contents of .docker/config.json look fine; however, a docker pull is failing because it's not logged into the registry.

The registry server is a 2.0.0 server.  Is Mesos not compatible with registry 2.0 as @xiaods mentioned?

**Comment by albertsj1** [comment]
Found my problem.  Even though I'm using docker 1.6.0, the creds were stored in ~/.dockercfg and not ~/.docker/config.json.  Adding the .dockercfg that was generated to the uri section fixed the problem for me.

**Comment by kolloch** [comment]
Hi @pdzilla, does this work for you now? If not, please reopen the ticket.

**Comment by asheshambasta** [comment]
I faced a similar issue while trying to deploy a private docker repo, my marathon task looked like:

```json
{  
  "id": "some_id",
  "cpus": 0.1,
  "mem": 512,
  "instances": 3,
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "organisation_name/docker_repo_name:1.0"
    }
  },
  "uris":  [
      "https://<auth_user>:<auth_password>@private.server.com/config_files/docker.tar.gz"
  ],
  "cmd": "",
  "ports": [
    9000,
    1111
  ]
}
```

And when I checked my slave logs, I always saw:
`
E0903 09:16:18.538339  1330 slave.cpp:3112] Container '30fdd2f5-0333-4d06-9808-b9ec2780534a' for executor ’some_id.6efdd9f4-521c-11e5-b5e8-56847afe9799' of framework '20150901-132055-2231697418-5050-1246-0000' failed to start: Failed to 'docker pull organisation_name/docker_repo_name:1.0': exit status = exited with status 1 stderr = time="2015-09-03T09:16:18Z" level="fatal" msg="Error: image organisation_name/docker_repo_name:1.0 not found"
`

I then temporarily changed the repository settings to public and the deployment went through.
I haven't yet tried with .dockercfg yet, but I'll do that soon.

I then changed the repository back to private, destroyed the application in marathon, but it still seems to work for me. I'm very sure that its a cache issue and I'm going to see similar problems with other private repositories. 

I'll post issues/workarounds here.

**Comment by yangtao309** [comment]
good job @xiaods

**Comment by testzlx** [comment]
I have the same problem,I felt very upset about it.I do it follow  [marathon guide](https://mesosphere.github.io/marathon/docs/native-docker-private-registry.html),but it does not work

**Comment by testzlx** [comment]
I fix the problem,please see[solve](https://docs.quay.io/issues/quay-mesos.html)
