### ISSUE TITLE
Make the events from /v2/event API available in the UI

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#1784]
It could be very helpful to see the events happening on the server side.
This could also be the first step of using this API to refresh the state of the UI, instead of frequently calling other endpoints for realizing changes.

**Comment by aldipower** [comment]
https://mesosphere.github.io/marathon/docs/rest-api.html#event-stream

**Comment by aatumanova** [comment]
Would you like to see an event stream for a collection of apps, a single app, or a task?

**Comment by aquamatthias** [comment]
I see two cases: 
- the marathon wide (global) event stream
- the application specific event stream

The first one really is a debug thing, the latter one is more interesting for the user.
We should focus on the application specific events.
The Application Detail View should have a pane/tab that displays all application relevant events.

**Comment by janisz** [comment]
I started working on it [here](https://github.com/mesosphere/marathon-ui/compare/master...janisz:Fixes_%231784_Make_the_events_available_in_the_UI?diff=split&expand=1&name=Fixes_%231784_Make_the_events_available_in_the_UI)

**Comment by aldipower** [comment]
@janisz Just had a quick look on your branch. This looks fantastic. How is the status with this. You going to open a PR for that on some point?

**Comment by janisz** [comment]
Hi @aldipower 
I don't have time to work on :(
I get stuck with some perfomance issues (or probably did something really bad) sometimes I got white page. I'm not sure how to solve it. Probably for minimal version I'll store latest 100 entries, then I could think about loading older entries while user is scrolling page.
I also not sure how to present entries. JSON in pre is ugly, I thought about [console like](http://www.michalkowalkowski.com/cssConsole/) layout but maybe there is something that fit better with current design (and React)

**Comment by junneyang** [comment]
+1

**Comment by janisz** [comment]
I continue my works on this feature ([code](https://github.com/mesosphere/marathon-ui/compare/master...janisz:Fixes_%231784_Make_the_events_available_in_the_UI?expand=1). It works good but I still have some questions

1. How to present events to user. Becouse some events could be big (#3154), I decide to strip them to contain timestamp, event type and id (where id could be one of [possible ids](https://github.com/mesosphere/marathon-ui/compare/master...janisz:Fixes_%231784_Make_the_events_available_in_the_UI?expand=1#diff-05731da3761eeb32b23993250e69747dR40)
2. How many events shoul be shown. Now I hardcode [100](https://github.com/mesosphere/marathon-ui/compare/master...janisz:Fixes_%231784_Make_the_events_available_in_the_UI?expand=1#diff-05731da3761eeb32b23993250e69747dR60) as hard limit for events and show them all but maybe this should be more/less
3. Is current way of displaying data good (I mean table layout)
4. Which events should be displayed

Also I need to work on tests.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3061. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
