### ISSUE TITLE
Design an alternative way to store and access state

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#1785]
Ever read and every write hits the data store directly.
For write requests this is perfectly ok, but read requests can be optimized.

The current architecture of Marathon is leader based.
We can do some optimizations here on the state handling site.
Idea: Command Query Responsibility Segregation.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3194. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
