### ISSUE TITLE
Introduce jsDom or similar in our tests

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#1796]
Some components (e.g. `TooltipMixin`) require a DOM to be present. Let's come up with a plan of action for integrating a DOM in our tests. 

cc @philipnrmn @aldipower @mlunoe @rcorral @neatstreet

**Comment by mlunoe** [comment]
I found cheerio to be a good companion of mocha. See here: https://github.com/mesosphere/marathon-ui/blob/71915f52ab4eef2939b8d19d870d5ef021e8ab31/test/components/AppList.test.jsx#L53

**Comment by pierlo-upitup** [comment]
Thanks for the input mike! I'll take a look.

**Comment by rcorral** [comment]
Seems like jsDom is a good solution. Anyone against it?

**Comment by mlunoe** [comment]
I'm not against, I just had an easier time with mocha. That is just my experience

**Comment by rcorral** [comment]
Cheerio seems to be jQuery specific, or at least that's how they market themselves.
How was the experience easier with mocha?

**Comment by mlunoe** [comment]
It says: "Cheerio implements a subset of core jQuery...", meaning that Cheerio includes some parts of the core of jQuery to make selections easier. You can see a use case of it in the link I posted above.

To me it was easier to setup and understand how it worked, where jsDom took a lot more effort. I can't remember the exact use case, I just remember I started with jsDom and got frustrated enough to try out a different solution.

Here they are adding jQuery themselves to do selections only for testing: http://robballou.com/2014/using-jsdom-and-mocha-for-testing/

I would urge you to pick a small sample test and try out both solutions, and then take your pick based on that.

**Comment by aldipower** [comment]
I already tried to integrate jsDom some weeks ago and that's why we go without any DOM for now, before we have find a better solution (maybe Cheerio).. :)

The problem with jsDom is that it needs some specific versions of io.js for the current versions. On the other side an older version of jsDom isn't working out with the new versions of Mocha and React. So it's unusable for our setup in the moment.

**Comment by mlunoe** [comment]
Thanks for your input!

**Comment by pierlo-upitup** [comment]
Closing this as it's a partial duplicate of https://github.com/mesosphere/marathon/issues/2099
