### ISSUE TITLE
Final polishing on #90

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#1798]
ACs

- Update CHANGELOG to reflect UI additions
- CSS cleanup to fit in with our guidelines
- Dicrease padding-left in filterbox
- Search icon is a tad too small
- A subtle hover effect on the “x” would be nice
- If there are no results for the keyword filter, some written feedback in the apps list area would help for communication
- ESC key should reset the filter

After merging: https://github.com/mesosphere/marathon-ui/pull/90

**Comment by pierlo-upitup** [comment]
I am a bit concerned about performance. Shouldn't we [throttle](http://underscorejs.org/#throttle) the user keystrokes? 

I can see a huge performance hit when the list grows to larger numbers (we are triggering a re-render on each keypress here).

**Comment by philipnrmn** [comment]
Yeah, this is a good point. As long as we keep the debounce rate low enough to make it feel snappy, I'm in favour.
