### ISSUE TITLE
/v2/events behaviour

### ISSUE THREAD

**Issue by air** [mesosphere/marathon#1801]
Did some basic playing with the event stream and found some rough edges.
1. `http --verbose GET https://marathon.mesosphere.com/v2/events`
   1. This returns a `405 Method Not Allowed`. This appears incorrect: a GET is an allowed method. Surely what we really mean is `406 Not Acceptable`, "The resource identified by the request is only capable of generating response entities which have content characteristics not acceptable according to the accept headers sent in the request."
      - i.e. We want the client to specify `Accept:text/event-stream`.
      - Note, "the response SHOULD include an entity containing a list of available entity characteristics" - if we can give the user a hint on the correct `Accept` header inline (without going to docs), this is even better.
   2. The response has many blank lines for some reason [1].
2. `http --verbose GET https://marathon.mesosphere.com/v2/events/` (note trailing slash) returns a 404. This should work consistently with 1 above. Compare to `/v2/info` which works identically with and without trailing slash.

[1]

```
GET /v2/events HTTP/1.1
Connection: keep-alive
Host: marathon.mesosphere.com
Accept-Encoding: gzip, deflate
Accept: */*
User-Agent: HTTPie/0.8.0



HTTP/1.1 405 HTTP method GET is not supported by this URL
X-Marathon-Leader: http://srv4.hw.ca1.mesosphere.com:8080
Access-Control-Allow-Origin: *
Access-Control-Allow-Headers:
Access-Control-Allow-Methods: GET, HEAD, OPTIONS
Access-Control-Max-Age: 86400
Pragma: no-cache
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html;charset=ISO-8859-1
Content-Length: 1346
Server: Jetty(8.y.z-SNAPSHOT)
Set-Cookie: mesosphere_server_id=srv4_hw_ca1_mesosphere_com_8080; path=/

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 405 HTTP method GET is not supported by this URL</title>
</head>
<body>
<h2>HTTP ERROR: 405</h2>
<p>Problem accessing /v2/events. Reason:
<pre>    HTTP method GET is not supported by this URL</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>




















</body>
</html>
```

**Comment by air** [comment]
Did our Jetty and JSON upgrades in 0.11 make any of this better?

**Comment by kolloch** [comment]
@air: no. Thanks to the command that you supplied that was very easy to check ;)

**Comment by marenzo** [comment]
+1
also, because of the bug, the api doc is incorrect and the http helper there fails to send get request.

**Comment by anrs** [comment]
@air I consider that isn't a bug, maybe you just should specify the Accept header to "text/event-stream", just like:

curl -H"Accept: text/event-stream" https://127.0.0.1:8080/v2/events

If you typed like above, you'll receive the events stream.

**Comment by benpillet** [comment]
@anrs it is a bug because "Accept: */*" includes text/event-stream as an acceptable response.  I just ran into this myself.  If I tell someone I'll accept anything, they should tell me their response in any format they like, including text/event-stream.  They shouldn't say "you need to ask me more specifically"

**Comment by anrs** [comment]
@benpillet got it, thank for your explanation.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2691. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
