### ISSUE TITLE
performance issues with docker images

### ISSUE THREAD

**Issue by Kosta-Github** [mesosphere/marathon#1806]
I noticed this strange behavior for a docker image which performs some cpu intensive tasks:

If I start the docker container via `marathon` with a `cpus`-setting of `0.1` this seems to clamp the cpu utilization for that container to roughly 10% max even if no other stuff is running on that node. Setting `cpus` to `0.1` results in setting `cpu-shares` to `204` for the `docker run` command (verified with `docker inspect`).

However, if I start the exact same docker container manually with `docker run --cpu-shares=204 ...` on the same node the container can utilize the cpu by ~100% (as expected).

I don't understand why both containers (spawn from the exact same image) are behaving differently with respect to cpu utilization. I couldn't find any significant differences in the `docker inspect` outputs.

According to the various docs the behavior of the pure `docker run` meets my expectations and understanding: the `cpus`/`cpu-shares` settings are just hints about the ratio for distributing cpu cycles in case of cpu-overutilization; if there is only one running task asking for cpu cycles it should get the full cpu power without clamping/throttling, right?

**Comment by rasputnik** [comment]
Are you running the slaves with or without CFS enabled?

**Comment by Kosta-Github** [comment]
Is it enabled by default? I haven't enabled it actively; at least not that I am aware of...

**Comment by Kosta-Github** [comment]
I have verified that all files `cpu.cfs_quota_us` under `/sys/fs/cgroups/cpu/` are using the value `-1`. Something else I can look into?

BTW, I am using mesos/marathon from within a docker container via [PanteraS](https://github.com/eBayClassifiedsGroup/PanteraS).

**Comment by Kosta-Github** [comment]
Any advice where to look next would be appreciated.

**Comment by philipnrmn** [comment]
Would you be able to advise here please, @kolloch ?

**Comment by kolloch** [comment]
Hey @tnachen, does that meet your expectations? I couldn't find documentation about that.

Anything besides http://mesos.apache.org/documentation/latest/docker-containerizer/ one can look at?

(yes, I know, the code :) )

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3528. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
