### ISSUE TITLE
Application locked by deployment after deployment is complete

### ISSUE THREAD

**Issue by nugend** [mesosphere/marathon#1811]
Logs here: https://gist.github.com/nugend/f10c9cf61666208510ea

Marathon 0.8.2
Mesos 0.22.1

Cluster setup: Three Marathon in HA, Three Mesos in HA, Three ZK in HA. Three slaves with attribute "node-type:RT", one slave with attribute "node-type:DB"

Three applicationg groups of feedhandler and config-daemon tasks. feedhandler tasks are sharded across letter ranges, config-daemon tasks distribute letter range assignments and consume eventSubscription to determine if range assignment should be reclaimed and when deployments start and stop.

config-daemon also runs a restart process where it scales feedhandlers down to zero, reloads config to determine if number of needed nodes has changed and re-balance ranges and then scale up to new number of needed nodes (so restart API cannot be used by itself).

Process for config-daemon is as follows: Scale to zero, store deployment id, go back to listening to events, wait for deployment_id complete or fail, on complete, attempt to scale up. At this point, the application lock exception is happening reliably.

Only thing I can think of is that by blocking TASK_LOST events, somehow the application lock is being kept? I am strongly of the feeling that when the deployment complete (success or fail) message is sent, the application lock should have been released.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2692. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
