### ISSUE TITLE
Jar permissions a bit too restrictive

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#1812]
I don't think there is a reason to make it `0640`. Same applies to `run-tests-config-template.sh` and probably all other files that have strange permissions.

**Comment by aquamatthias** [comment]
@bobrik do you mean the assembly jar? What permission do you suggest?

**Comment by bobrik** [comment]
Yes, assembly jar. 0644 looks like a better choice for me.

**Comment by aquamatthias** [comment]
The jar is created by the sbt assembly plugin. Have to check, if we can adjust file permissions here. We definitively can do that for files under bin/*

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3198. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
