### ISSUE TITLE
Environment before execution

### ISSUE THREAD

**Issue by samek** [mesosphere/marathon#1813]
Hi, 

Is there a way to set-up some environment vars before the docker is started. 

I'm not talking about the env vars  which are passed to the container (-e). 

shell equivalent of   export MY_VAR=XXX && docker run -t image

Why ? We've setup weave and would need to set DOCKER_HOST to a local docker proxy in order to use it. 
We could put it as default on system level  but I would like some flexibility when to use weave and when not. 

Thanks.

**Comment by nathanleiby** [comment]
I'd also be interested in the answer to this question. My use case is:

I'd like to run an external process for service discovery that tracks available services. When I start a docker container via Marathon, I want to (dynamically) inject env vars corresponding to available services, in a Kube-like way.

https://github.com/GoogleCloudPlatform/kubernetes/blob/master/docs/user-guide/services.md#discovering-services

**Comment by gkleiman** [comment]
@samek I'm afraid that the Mesos' Docker executor doesn't support setting custom env variables before running the Docker CLI.

You could work around this by using the command executor and including the docker command in the app definition, but then you lose the benefits of the Docker executor.

@nathanleiby the following page describes a few approaches to service discovery usually used with Marathon: https://mesosphere.github.io/marathon/docs/service-discovery-load-balancing.html
