### ISSUE TITLE
Proposal: Add Hyper feature

### ISSUE THREAD

**Issue by xiaods** [mesosphere/marathon#1815]
Hyper is Hypervisor-agnostic Docker Engine, I hope marathon can support it.

https://hyper.sh/

**Comment by philipnrmn** [comment]
Interesting!

**Comment by gkleiman** [comment]
Thanks for the proposal. I think this is actually something that should be supported by Mesos first, as it would for example require a custom executor.

**Comment by xiaods** [comment]
@gkleiman you mean we should be implement a hyper executor in mesos, then let marathon support it?

**Comment by gkleiman** [comment]
@xiaods exactly

**Comment by xiaods** [comment]
Update:
Add a Mesos issue
https://issues.apache.org/jira/browse/MESOS-3435

**Comment by jasongilanfarr** [comment]
Closing in favor of mesos issue
