### ISSUE TITLE
Additional properties are not allowed ('key', 'value' were unexpected)

### ISSUE THREAD

**Issue by bradleyreeves** [mesosphere/marathon#1836]
Any insight into what might be causing this?

Error: Additional properties are not allowed ('key', 'value' were unexpected)
Path: container.docker.parameters.0
Value: {"value": "9990:9990", "key": "publish"}

Error while using DCOS cli from terminal, "dcos marathon app add wildfly.json"

wildfly.json as follows:

{
"container": {
"type": "DOCKER",
"docker": {
"image": "bradleyreeves/wildfly:latest",
"parameters":[{"key":"publish","value":"9990:9990"}]
}
},
"id": "wildfly-docker",
"acceptedResourceRoles": ["slave_public"],
"cpus": 1,
"instances": 1,
"mem": 2048,
"ports":[9990]
}

**Comment by philipnrmn** [comment]
Hi @bradleyreeves, I tried posting your configuration directly to the [Marathon app creation endpoint](https://mesosphere.github.io/marathon/docs/application-basics.html) and it worked, so I think it's not specifically those parameters that are causing the issue. There may be a problem in the CLI. 

<img width="1083" alt="marathon-1836" src="https://cloud.githubusercontent.com/assets/2989362/8780794/97a52e1e-2f0b-11e5-8845-87b9dca6aeec.png">

**Comment by bradleyreeves** [comment]
That's it @philipnrmn, I can confirm using the endpoint worked for me as well. Thanks for the help!

**Comment by philipnrmn** [comment]
OK, glad to hear it. I'll close this issue here, and raise it on the appropriate CLI project. Thanks for the report!
