### ISSUE TITLE
Don't show "no apps/deployments" message during page load

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#1846]
During page load empty messages are shown in the UI:

`No running apps` in the apps tab and `No deployments in progress` in the deployments tab. 

These should not be shown until the load has completed and the apps/deployments list is known to be empty. 

![20150721-empty-state-deployments](https://cloud.githubusercontent.com/assets/2989362/8802723/9b258940-2fc3-11e5-8caa-8a1c363abfe0.png)

**Comment by pierlo-upitup** [comment]
Will be closed when https://github.com/mesosphere/marathon-ui/pull/98 is merged

**Comment by philipnrmn** [comment]
Not sure why this was closed, I suspect I slipped in Waffle. Sorry!

**Comment by pierlo-upitup** [comment]
Yeah thought so! np
