### ISSUE TITLE
servicerouter: Allow disabling SSL frontend?

### ISSUE THREAD

**Issue by mconigliaro** [mesosphere/marathon#1848]
`servicerouter.py` automatically writes an SSL frontend to `haproxy.cfg`. It would be nice if this could be disabled via the command line.

**Comment by gkleiman** [comment]
Thanks for the suggestion, I moved it to our backlog.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3358. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3358. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
