### ISSUE TITLE
Update Docs: list all possible API error responses

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#1849]
ACs

- [ ] for each endpoint, find the list of possible HTTP error codes and a description of the response body (where applicable) 
- [ ] update the marathon docs

**Comment by air** [comment]
Hi, this looks like a dupe of #1054, can you review and merge if needed.

**Comment by pierlo-upitup** [comment]
@air You're right. I've added the ACs to #1054. Closing this now
