### ISSUE TITLE
Versioned command line flag documentation

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#1854]
Our version markers are not so well liked thus we want to migrate to separate docs per version.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2904. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2904. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
