### ISSUE TITLE
Versioned rest-api documentation

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#1855]
Our version labels are not so popular, so we move to separate documents per version.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3213. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3213. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
