### ISSUE TITLE
PUT /v2/groups overwrites "instances" even when not provided

### ISSUE THREAD

**Issue by davent** [mesosphere/marathon#1856]
If you provide JSON to PUT /v2/groups with no "instances" set the default of '1' is used. This means that if you have increased the instance count since the last deploy your application reverts to 1 instance during the next deploy.

This behaviour does not happen if you are not using groups (i.e. PUT /v2/apps/{appId}) . In this case if the PUT JSON does not contain an "instance" then the existing one is used.

**Comment by aquamatthias** [comment]
@davent which version of Marathon did you use?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3554. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3554. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
