### ISSUE TITLE
PUT /v2/groups/{appId} does not deploy

### ISSUE THREAD

**Issue by davent** [mesosphere/marathon#1858]
PUTing an updated Groups JSON put to Marathon returns:

Response: 200
{"version":"2015-07-22T16:49:09.690Z","deploymentId":"4dc035bc-2265-4012-ba3c-357d7e4d4ad6"}

However, no deploy is triggered. The only change I made to the JSON is to the Container section (I updated the "container": {"docker": {"image"}} atttributes). 

Edit.
The config is not actually getting updated despite a 200 response to the PUT API call

**Comment by aquamatthias** [comment]
Hey @davent If you are posting to the groups endpoint you update the group. I could imagine, that you send an AppDefinition? Can you share the update you send?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3231. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3231. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
