### ISSUE TITLE
Links in REST API docs don't work

### ISSUE THREAD

**Issue by ssk2** [mesosphere/marathon#1859]
These anchors don't work: 
https://mesosphere.github.io/marathon/docs/rest-api.html#post-/v2/groups

I'm not sure if this is fixable but if not, they should just be removed, so that it's not confusing.

**Comment by pierlo-upitup** [comment]
There is a discrepancy between the expected anchor tag ID value and the actual IDs. 

Example: 

The first link expects the target ID to be `#post-/v2/apps` but the id of the section is actually `id="post-v2-apps"`. 

I

**Comment by kolloch** [comment]
@pierlo-upitup I am currently updating this docs. If possible look (and potentially merge) https://github.com/mesosphere/marathon/pull/1857 first.

**Comment by pierlo-upitup** [comment]
@kolloch As far as I can see you didn't touch the first 50 lines or so – we should be good.

**Comment by ssk2** [comment]
Great, thanks!
