### ISSUE TITLE
Usability of the Marathon binary

### ISSUE THREAD

**Issue by errordeveloper** [mesosphere/marathon#1862]
I have just installed Marathon 0.9.0 on CentOS 7 and I can see there is a systemd unit that simply launches `/usr/bin/marathon` without any arguments, however I would like to find out what are customisation options for logging and how do I point it at a Zookeeper which is not on localhosts etc. The systemd unit loads the environment from `/etc/sysconfig/marathon`, which is not installed from the package. So here is my initial user experience with trying to figure this out in a CLI way.

```
[vagrant@mesos-00 ~]$ man marathon
No manual entry for marathon
[vagrant@mesos-00 ~]$ marathon --help
-bash: /usr/bin/marathon: Permission denied
[vagrant@mesos-00 ~]$ sudo marathon --help
 USAGE: marathon-framework (--jar <marathon.jar>)? <option>*

  Run the Marathon scheduler, collecting options from the configuration
  directory /etc/marathon/conf and configuration file /etc/default/marathon,
  and appending the options supplied on the command line.

  If you would like to pass the Jar to be run, do so with --jar. If the Jar is
  not supplied, the script assumes the Jar has been concatenated to it and
  will supply its own path to Java.

/bin/marathon: line 117:?T?FMETA-INF/MANIFEST.MF??u?1: No such file or directory
[vagrant@mesos-00 ~]$ sudo marathon -h
 USAGE: marathon-framework (--jar <marathon.jar>)? <option>*

  Run the Marathon scheduler, collecting options from the configuration
  directory /etc/marathon/conf and configuration file /etc/default/marathon,
  and appending the options supplied on the command line.

  If you would like to pass the Jar to be run, do so with --jar. If the Jar is
  not supplied, the script assumes the Jar has been concatenated to it and
  will supply its own path to Java.

/bin/marathon: line 117:?T?FMETA-INF/MANIFEST.MF??u?1: No such file or directory
```

I then figured out that the binary container of shell script with a jar appended to it... Which is actually hard to read.

Now, I thought I'll double check the version before reporting:

```
[vagrant@mesos-00 ~]$ sudo marathon --version
run_jar --zk zk://localhost:2181/marathon --master zk://localhost:2181/mesos
[vagrant@mesos-00 ~]$ sudo marathon -v
run_jar --zk zk://localhost:2181/marathon --master zk://localhost:2181/mesos
```

I understand there are docs online somewhere (which found later, of course), but I though this could be just a bit more intuitive on the CLI, as all I really wanted to know if it even takes any flags at all...

**Comment by errordeveloper** [comment]
I have also discovered that running `sudo java -cp /usr/bin/marathon mesosphere.marathon.Main --help` is a thing, but that's not something I have the capacity to memorise.

**Comment by aquamatthias** [comment]
Hey @errordeveloper thanks for sharing your experience.
I agree, Marathon is currently not a good *nix citizen.
We should improve that.

**Comment by kolloch** [comment]
I can reproduce this with docker:

```bash
docker run -i -t centos
rpm -Uvh http://repos.mesosphere.com/el/7/noarch/RPMS/mesosphere-el-repo-7-1.noarch.rpm
yum install -y marathon
marathon --help
```

If you how to fix that @errordeveloper, we would appreciate your help. We accept pull requests for https://github.com/mesosphere/marathon-pkg/. Thanks!

**Comment by errordeveloper** [comment]
Thanks for looking into this @kolloch! It would be good to know why is the binary packaged in just a way that it has to have a wrapper script with as much logic as it does and contain the jar at the tail, why don't it simply call `java -jar ...` with some kind of usual wrapping to handle `$JAVA_HOME` and some JVM flags, [like Elasticsearch has](https://github.com/elastic/elasticsearch/blob/master/distribution/src/main/resources/bin/elasticsearch), for example?

**Comment by kolloch** [comment]
BTW, you can use `marathon run_jar --help` to get to the command line help.

(I agree that this should be made much more obvious)

**Comment by duffqiu** [comment]
How to set other marathon parameters in /etc/default/marathon?
It seems it doesn't support some parameters like https...

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3432. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3432. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
