### ISSUE TITLE
Group environment

### ISSUE THREAD

**Issue by bsideup** [mesosphere/marathon#1863]
Hi!

For projects like Spring Cloud it would be great if Marathon will allow to specify environment variables for group. 

For instance, a group of apps could share environment variable `CONFIG_SERVER_URL`.

Thanks!

**Comment by gkleiman** [comment]
Thanks for the request, I'll add it to our backlog.

**Comment by kolloch** [comment]
Some things to consider:

* It probably should form a hierarchy. Inner groups inherit variables from outer groups. Environment variables on inner groups should override environment variables on outer groups.
* Environment variables defined in an app definition should override all environment variables that are inherited.
* We should expose the "effective" environment variables when `GET`ing an app. Maybe we should also indicate the source of the environment definition.
* Updating the environment variables of a group, must result in restarting all apps for which the effective environment variables change.

**Comment by bsideup** [comment]
@kolloch :+1: great addition

**Comment by sepiroth887** [comment]
+1

**Comment by fenicks** [comment]
:+1:

**Comment by avthart** [comment]
+1

**Comment by jaimelive** [comment]
+1

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3275. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3275. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
