### ISSUE TITLE
Set DiscoveryInfo for created TaskInfo messages

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#1866]
See https://github.com/apache/mesos/blob/0.23.0/include/mesos/mesos.proto#L1254

**Comment by keis** [comment]
I can see something about DiscoveryInfo was recently added is that support still only partial?

**Comment by gkleiman** [comment]
@keis partial support for DiscoveryInfo will be shipped in Marathon v0.14.0 

Marathon v0.14.0 will fill the DiscoveryInfo only if an app definition requests an IP-per-Task and includes service discovery information.

**Comment by crucidal** [comment]
@gkleiman I'm having trouble finding information on how to provide service discovery information to a marathon task. More specifically, how to provide this information when not directly spawning a docker container. Could you point me in the right direction?

**Comment by gkleiman** [comment]
@crucidal https://github.com/mesosphere/marathon/pull/3302 added a new field called "portDefinitions", which you can use to request ports, specify their names and also add labels.

Marathon will then use all this information to build the DiscoveryInfo.

Please note that this is only available on the current master and will be part of Marathon v0.16.0.
