### ISSUE TITLE
User Interface becomes unresponsive when running many tasks

### ISSUE THREAD

**Issue by mindscratch** [mesosphere/marathon#1867]
I'm running Mesos 0.22.1 and Marathon 0.9.0. I have ~15 applications deployed, most with 1 - 5 tasks. However, one application has 750 tasks. When trying to click on that app, to see the list of tasks the UI becomes unresponsive. Running Firefox, I'll eventually get a dialog asking if I want to Stop the script or continue.

I will eventually need to run thousands of tasks but I'm concerned based on what I'm seeing so far.

**Comment by kolloch** [comment]
Hi @mindscratch, we are aware of this issue and want to fix it in the next months.

The API call that is used in the GUI returns all tasks of the app at once. That overwhelms the UI at the moment. Marathon itself should be fine with this number of tasks.

We want to create a new API call which allows paging through the tasks and update the GUI accordingly.

**Comment by pierlo-upitup** [comment]
Also note: this PR which will be shipped in the upcoming Marathon v0.11.0 will already help a lot https://github.com/mesosphere/marathon-ui/pull/105

**Comment by mindscratch** [comment]
@kolloch @pierlo-upitup thanks, looking forward to the improvements.

**Comment by aldipower** [comment]
Hey @mindscratch, your problem should be solved with the newest version of the UI by mesosphere/marathon-ui#105 . Before all existing tasks were rendered, even if there weren't displayed.. Now only the displayed ones are rendered. I just scaled up easily to 3000 tasks and I think it can be much more. Only problem can be a slow network connection.

**Comment by mindscratch** [comment]
@aldipower sounds good, thanks for your work on it.
