### ISSUE TITLE
Resources from URIs with Docker containers

### ISSUE THREAD

**Issue by bsideup** [mesosphere/marathon#1869]
Hi!

Would be cool if resources will be available (as volumes) for Docker containers. It will allow following scenario:

Run Docker container with JVM and mount volume with JAR file inside it to run. 

In pure-Docker commands it will look like:

docker run -v `pwd`/app.jar:/app/app.jar -p 8080:8080 java:8-jre java -jar /app/app.jar

Why? I will explain usecase:

We have our Java application, it's built on Jenkins CI server and final artifact (JAR file) is pushed to Artifactory (Maven repository). We don't want to change this part and we found Marathon a very good fit for such scenario, currently we're deploying Mesos containers with artifactory links in URIs. Everything is great, but now we want to change containers to Docker, but keep this scheme (I will call it "docker repository-less"), so we don't want to pack our jars into Docker container. 

Thanks

**Comment by felixb** [comment]
Isn't the jar already available in the sandbox. 
The sandbox ist mounted to /mnt/sandbox by default.

**Comment by bsideup** [comment]
@felixb really? Cool, thanks :) Will check

**Comment by kolloch** [comment]
That should have fixed your problem. If not, please reopen.

@bsideup: Maybe you can add that as an example to our native-docker.md documentation? We would really appreciate that.

https://github.com/mesosphere/marathon/blob/pk/contributing-docs/docs/docs/contributing.md

**Comment by bsideup** [comment]
@kolloch Now I see it in native-docker.md:
```
For convenience, the mount point of the Mesos sandbox is available in the environment as $MESOS_SANDBOX.
```

So looks like it's more like my inattention :)
