### ISSUE TITLE
Provide events long-polling endpoint

### ISSUE THREAD

**Issue by bsideup** [mesosphere/marathon#1870]
Current implementation is sending http requests on events. It means that you have to hard-configure each address of receiver, it's not scalable. For instance http://github.com/QubitProducts/bamboo is waiting for such notifications.

What will be better is API for events long-polling ( http://www.pubnub.com/blog/http-long-polling/ ), where consumers of events could open a channel and listen for events instead of receiving them from http callbacks. 

It will allow scaling of bamboo (for example) for infinite number of nodes (currently every change in topology requires adding this bamboo nodes to the list of receivers)

**Comment by kolloch** [comment]
Good news! It is already implemented. Look at the events endpoint.

https://mesosphere.github.io/marathon/docs/rest-api.html#event-stream

**Comment by bsideup** [comment]
@kolloch great, thanks :)

But it didn't work for me :( 

```
curl -v http://192.168.33.10.xip.io:8080/v2/events
* Hostname was NOT found in DNS cache
*   Trying 192.168.33.10...
* Connected to 192.168.33.10.xip.io (192.168.33.10) port 8080 (#0)
> GET /v2/events HTTP/1.1
> User-Agent: curl/7.37.1
> Host: 192.168.33.10.xip.io:8080
> Accept: */*
>
< HTTP/1.1 405 HTTP method GET is not supported by this URL
< X-Marathon-Leader: http://192.168.33.10.xip.io:8080
< Pragma: no-cache
< Cache-Control: must-revalidate,no-cache,no-store
< Content-Type: text/html;charset=ISO-8859-1
< Content-Length: 1346
* Server Jetty(8.y.z-SNAPSHOT) is not blacklisted
< Server: Jetty(8.y.z-SNAPSHOT)
<
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 405 HTTP method GET is not supported by this URL</title>
</head>
<body>
<h2>HTTP ERROR: 405</h2>
<p>Problem accessing /v2/events. Reason:
<pre>    HTTP method GET is not supported by this URL</pre></p>
<hr /><i><small>Powered by Jetty://</small></i>
</body>
</html>
* Connection #0 to host 192.168.33.10.xip.io left intact
```

**Comment by bsideup** [comment]
@kolloch ah, ok, working fine if I force "Accept: text/event-stream".
