### ISSUE TITLE
Allow access to Mesos sandbox logs from Marathon UI

### ISSUE THREAD

**Issue by bsideup** [mesosphere/marathon#1871]
Currently logs are missing in Marathon UI, and you have to open Mesos UI and search for sandbox to find logs

**Comment by pierlo-upitup** [comment]
Duplicate of https://github.com/mesosphere/marathon/issues/878

**Comment by bsideup** [comment]
@pierlo-upitup not duplicate. I don't want to open mesos to see logs, I expect this functionality from Marathon OOTB like Singularity did :)

**Comment by pierlo-upitup** [comment]
@bsideup You are right – I misinterpreted your description. I think this issue is more representative of your idea https://github.com/mesosphere/marathon/issues/1309 ?

**Comment by bsideup** [comment]
@pierlo-upitup yes, sorry, didn't saw #1309 before. Mine is duplicate of #1309  :) Thanks!

**Comment by pierlo-upitup** [comment]
Perfect, thank you!
