### ISSUE TITLE
Kill & Scale should be available for more than one task

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#1872]
At the moment, you can only `Kill & Scale` a single task from the API. It should be possible to kill and scale multiple ~~apps~~ tasks. 

![20150724-multiple-kill-scale](https://cloud.githubusercontent.com/assets/2989362/8872928/e3403ee2-3201-11e5-88c4-5cc193e4ad68.png)

**Comment by pierlo-upitup** [comment]
Note to assignee: this also needs an additional test in `tasks.test.js` for 

> on multiple task deletion and scale

**Comment by pierlo-upitup** [comment]
As well as an entry in our changelog ;)
