### ISSUE TITLE
Consider rewording Kill & Scale

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#1873]
The wording of `Kill & Scale` button reflects its associated API call, but its utility is not obvious to a first-time user. 

Let's consider rewording it to something like `Kill Permanently` or `Kill (don't redeploy)`

**Comment by pierlo-upitup** [comment]
Note to assignee: this needs an entry in our changelog ;)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2873. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2873. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
