### ISSUE TITLE
Select all tasks checkbox should only select visible tasks

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#1875]
When you select all tasks using the shortcut checkbox in the title, any subsequent action is performed on all tasks belonging to the current application rather than the tasks on the current page. 

This is not normal behaviour - in gmail, for example, a similar checkbox selects all emails on the current page, not all emails in the inbox.

The behaviour of the checkbox should either be updated only to select the current page of tasks, or its utility should be clarified for the user. 

![20150724-select-all-tasks](https://cloud.githubusercontent.com/assets/2989362/8873054/22d6ccc8-3203-11e5-99e4-81652fff3f09.png)
(Any action applied to these tasks will apply to all nine, not to the eight currently displayed)

**Comment by pierlo-upitup** [comment]
Definitely agree +1

**Comment by pierlo-upitup** [comment]
Maybe we could have a dropdown similar to Gmail's one, with clearer instructions:

```
Select 
  \____ All (32 tasks)
  \____ Current page
```

**Comment by pierlo-upitup** [comment]
Note to assignee: this needs an entry in our changelog ;)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3263. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3263. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
