### ISSUE TITLE
Running a container on all hosts

### ISSUE THREAD

**Issue by tiagoboldt** [mesosphere/marathon#1876]
I would like to have a specific container running on all my Marathon hosts. 

I could set the number of instances to a ridiculously high number and then set the `hostname: unique` constraint, but it would probably impose an unnecessary load on the cluster with continuous attempts to allocate the service while also being prone to failure if at some point the number of machines goes above the number set for instances. 

Is there an optimal solution for this? Shouldn't this case be natively supported by Marathon?

**Comment by xiaods** [comment]
interest for this request. but I don't think marathon should provide the function.

**Comment by philipnrmn** [comment]
There's some related discussion here: #846

**Comment by kolloch** [comment]
Since this is a duplicate, I will close it. Reopen&explain if you disagree.
