### ISSUE TITLE
Hash Sum mismatch when adding apt repo

### ISSUE THREAD

**Issue by lwoydziak** [mesosphere/marathon#1879]
Running:

# Add the repository
sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
DISTRO=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
CODENAME=$(lsb_release -cs)
echo "deb http://repos.mesosphere.io/${DISTRO} ${CODENAME} main" | \
  sudo tee /etc/apt/sources.list.d/mesosphere.list
sudo apt-get -y update

Failed to fetch bzip2:/var/lib/apt/lists/partial/repos.mesosphere.io_ubuntu_dists_trusty_main_binary-amd64_Packages  Hash Sum mismatch

From two different machines, one in DigitalOcean and one from a local network.

**Comment by mconigliaro** [comment]
A lot of people reported this problem this morning, but it seems to be working again now.

**Comment by lwoydziak** [comment]
Verified, thank you for your help.
