### ISSUE TITLE
servicerouter: name-based application routing

### ISSUE THREAD

**Issue by mconigliaro** [mesosphere/marathon#1880]
This script currently creates a new frontend and binds to a unique port for each service. This is not ideal for service discovery because you still have to keep track of which port marathon assigned to which application:

    http://<load balancer address>:<mesosphere app port><path>

A better solution would be to run every application on the **same** frontend and route requests based on a path prefix. This routing can be done in HAProxy with ACLs. For example, here's how you'd route requests beginning with `/foo/` to the backend named `foo`:

    acl acl_foo path_beg -i /foo/
    use_backend foo if acl_foo

Now your applications don't need to be aware of ports at all. They just have to know each other's names:

     http://<load balancer address>/<mesosphere app name>/

The next problem is that the full request path including the prefix (e.g. `/foo/`) will get passed down to the backend, but that can be easily fixed with a rewrite rule in the backend: 

    reqrep ^([^\ ]*)\ /foo/(.*) \1\ /\2

Ideally `servicerouter.py` could enable port-based or name-based routing (or both) via command line switches.

**Comment by kolloch** [comment]
@lloesche: what do you think?

**Comment by mconigliaro** [comment]
Obviously, this really only works for HTTP services. I'm not sure if that complicates the implementation.

**Comment by lloesche** [comment]
That's what the HAPROXY_HTTP_FRONTEND_HEAD and HAPROXY_HTTPS_FRONTEND_HEAD are for. By default they bind to tcp/80 and tcp/443 respectively. Any application that has HAPROXY_{n}_VHOST (where {n} is the port index, so e.g. 0 for the first port) set will be included automatically.

So e.g. if your app exports HAPROXY_0_VHOST=www.myapp.com then haproxy will do vhost/sni based hostname matching and balance to the appropriate backend.

**Comment by kolloch** [comment]
So, is that already support and can we close that issue?

**Comment by lloesche** [comment]
It is. And using the templates you could also change the default vhost behaviour to use the proposed http://<load balancer address>/<mesosphere app name>/ syntax.

**Comment by mconigliaro** [comment]
OK, makes sense. Thanks guys.
