### ISSUE TITLE
Include Marathon 0.9.0 in Ubuntu Vivid repository

### ISSUE THREAD

**Issue by F21** [mesosphere/marathon#1883]
`http://repos.mesosphere.io/ubuntu vivid main` seems to be missing the Marathon package. However, `http://repos.mesosphere.io/ubuntu trusty main` contains a Marathon package that works correctly on `vivid` (contains the systemd startup scripts).

Currently, I need to work around by adding both the vivid and trusty repositories to install Mesos 0.23 and Marathon 0.9.0 on Ubuntu 15.04 (vivid).

**Comment by kolloch** [comment]
Hi @lloesche, is that hard to do?

**Comment by lloesche** [comment]
@kolloch not really, should be a simple patch since we already have systemd units for CentOS 7. Though I'm surprised that that trusty repo should include the systemd units. Trusty is upstart based. Maybe Ubuntu 15.04 contains some backwards compatible shim that makes upstart files work?

**Comment by lloesche** [comment]
https://github.com/mesosphere/marathon-pkg/pull/14 just got merged. The next stable release will automatically push packages for Debian 8 and Ubuntu 15.04. At the moment you can find them in the testing repositories. For vivid that would be:
```
deb http://repos.mesosphere.com/ubuntu vivid-testing main
```
