### ISSUE TITLE
Collect functionality/criteria for deployment status

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#1885]
feedback
errors
time (launch, stage, etc)
reason for rejection

**Comment by pierlo-upitup** [comment]
Relevant issues

https://github.com/mesosphere/marathon/issues/1881

https://github.com/mesosphere/marathon/issues/1842

https://github.com/mesosphere/marathon/issues/1784

https://github.com/mesosphere/marathon/issues/1780


https://github.com/mesosphere/marathon/issues/1309

https://github.com/mesosphere/marathon/issues/1179


https://github.com/mesosphere/marathon/issues/1090

https://github.com/mesosphere/marathon/issues/968

https://github.com/mesosphere/marathon/issues/878

https://github.com/mesosphere/marathon/issues/380

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3245. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3245. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
