### ISSUE TITLE
Marathon coredump on leader election (Running inside docker on coreOS)

### ISSUE THREAD

**Issue by sepiroth887** [mesosphere/marathon#1889]
Hey, 

Just stumbled upon this: 

Setup: 

3 CoreOS hosts (docker 1.7.1)
All run Mesos-Master container bundled with Marathon & Chronos
Remote 5 node zookeeper cluster. 

Mesos is healthy. 

Marathon attempts to start and then dies on leader election (verbose logs below):

Jul 28 00:56:13 stgmesos-1 marathon[1471]: [2015-07-28 00:56:13,471] INFO Binding mesosphere.marathon.api.v2.SchemaResource to GuiceManagedComponentProvider with the scope "Singleton" (com.sun.jersey.guice.spi.container.GuiceComponentProviderFactory:168)
Jul 28 00:56:13 stgmesos-1 marathon[1471]: [2015-07-28 00:56:13,522] INFO Started SelectChannelConnector@0.0.0.0:8080 (org.eclipse.jetty.server.AbstractConnector:338)
Jul 28 00:56:20 stgmesos-1 marathon[1471]: [2015-07-28 00:56:20,013] INFO Candidate /marathon/leader/member_0000000020 waiting for the next leader election, current voting: [member_0000000019, member_0000000020] (com.twitter.common.zookeeper.CandidateImpl:165)
Jul 28 00:56:32 stgmesos-1 marathon[1471]: [2015-07-28 00:56:32,009] INFO Candidate /marathon/leader/member_0000000020 is now leader of group: [member_0000000020] (com.twitter.common.zookeeper.CandidateImpl:152)
Jul 28 00:56:32 stgmesos-1 marathon[1471]: [2015-07-28 00:56:32,010] INFO Elected (Leader Interface) (mesosphere.marathon.MarathonSchedulerService:246)
Jul 28 00:56:32 stgmesos-1 marathon[1471]: WARNING: Logging before InitGoogleLogging() is written to STDERR
Jul 28 00:56:32 stgmesos-1 marathon[1471]: F0728 00:56:32.080438  1571 process.cpp:889] Name or service not known
Jul 28 00:56:32 stgmesos-1 marathon[1471]: *** Check failure stack trace: ***

Any ideas what this is?

**Comment by sepiroth887** [comment]
I should note that this setup works fine when running the container locally with ZK inside the container and no HA mode.

**Comment by sepiroth887** [comment]
Also given that the error is around name lookup it seems: 

/etc/marathon/ip and /etc/marathon/hostname are both set to the ip of the coreos eth0 interface with docker --net=host set

**Comment by sepiroth887** [comment]
Ok ... figured it out. On CoreOS and esp. on Azure the /etc/hosts file is not populated, so there is no entry with 127.0.0.1   <hostname> 

after adding this in it works apparently. Closing this again.

**Comment by kolloch** [comment]
Hi @sepiroth887,

I would love it if you could improve our documentation to help avoiding this and other pitfalls. Maybe we could extend the Getting Started page or create a "common pitfalls" page. What do you think?

We gladly accept documentation PRs.

**Comment by sepiroth887** [comment]
I will do so soon. Not sure of the best fix for it yet but ill write something up and send a PR

**Comment by sepiroth887** [comment]
It's not been forgotten, just swamped with work. Looking into this now.

**Comment by sepiroth887** [comment]
done. PR ready. Please review: https://github.com/mesosphere/marathon/pull/1919
