### ISSUE TITLE
PUTs on groups with incorrect IDs are partially ignored

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#1890]
The following request does not result in an error but does not create any app:

``` json
PUT /v2/groups/group HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 102
Content-Type: application/json
Host: localhost:8080
User-Agent: HTTPie/0.9.2

{
    "apps": [
        {
            "cmd": "python -m SimpleHTTPServer $PORT",
            "id": "app"
        }
    ],
    "id": "group"
}

HTTP/1.1 200 OK
Cache-Control: no-cache, no-store, must-revalidate
Content-Type: application/json
Expires: 0
Pragma: no-cache
Server: Jetty(8.1.15.v20140411)
Transfer-Encoding: chunked
X-Marathon-Leader: http://localhost:8080

{
    "deploymentId": "9119fb60-bd47-4f7e-ad7c-1caa7eceab0f",
    "version": "2015-07-28T12:18:25.287Z"
}
```

If you use no group ID or `"id": "/group"` as group ID, it works as expected.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2682. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2682. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
