### ISSUE TITLE
[Feature Request] HTTPS healthchecks

### ISSUE THREAD

**Issue by sepiroth887** [mesosphere/marathon#1894]
Lets start off stating that this may be relatively tricky.

So I have a few applications running that only expose https endpoints. The TCP healthcheck works fine and I use it as well. However this may or may not indicate a healthy state. 
I wonder how feasible it would be to allow protocol HTTPS for healthchecks. 

Potential Issues: 

1) HTTPS is ususally tried to a hostname which Marathon/Mesos isn't necessarily aware of.
2) The rootCA is not know and may fail verification.

I can probably do something like curl -k https://{mylocalIP|}/{healthPath} but it is pretty ugly. 

Maybe its possible to use a healthcheck that skips verification?

**Comment by kolloch** [comment]
Hi @sepiroth887, you can use COMMAND health checks for this right now. Even though, it includes the command start overhead, the advantage is, that it is executed by the slave and on the slave. So it scales with your cluster.

This is the reason why we eventually want to move all health check functionality from the Marathon code base to the Mesos code base. If mesos supports a HTTPS health check, it will be easy to support that from Marathon as well.

Here is the issue for HTTP health checks in Mesos: https://issues.apache.org/jira/browse/MESOS-2533
There is a patch as well: https://reviews.apache.org/r/36816/

Maybe, you could create a new ticket in the Mesos Tracker to request HTTPS support?

**Comment by sepiroth887** [comment]
IC. Wasnt aware that the checks for http/tcp were executed by marathon instead of the slaves. 

I use cmd for now then and file a ticket :) 

Thanks!!
