### ISSUE TITLE
Add section about our sprint board (waffle) in README

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#1895]
Both the `marathon` and `marathon-ui` repos should have a section in the README that explains how the users can track progress by looking at our Waffle board. 

We currently offer the Waffle "badge", but that is pretty cryptic way of communicating this.

**Comment by mlunoe** [comment]
My suggestion to just have a link with a descriptive text would be enough. The badge doesn't really provide any value for me.

**Comment by aquamatthias** [comment]
We will not use waffle in the future - close the ticket.
