### ISSUE TITLE
Docker Containers Names in Marathon.

### ISSUE THREAD

**Issue by ajaybhatnagar** [mesosphere/marathon#1899]
Enhancement Request.

When Marathon is launching Docker containers, it's hostname can be be specified in script like 
      "parameters": [
        { "key": "hostname", "value": "esm01.test.local" }]
However this gives the same hostname to all the instances started by marathon. Example when instance is set like below 
  "instances": 3
all containers will have the same hostname.

This approach has limitation if Docker containers need to form an inter container communicating  cluster when they need to be configured with individual "hostnames" . Dynamic container id is known only after container is launched where as the container cluster application expects to know the members hostnames beforehand to start handshake process with the members before admitting them as a cluster member.

It would be better if an option is provided for hostnames to be be associated with container id (or some other way) . For example, If I want the cluster to have 50 such containers and be able to scale on demand say min 5 to max   50, then I should be able to name them with say "host-NN" where NN could be in range from 01 to 50. When Marathon launches these containers , these could be incremented or decremented from 01 to 50. 

Another use case arises of such need arises when these containers need to use persistent storage which is exclusive to the container to record it's state/metadata about the cluster and some user/application data.

This will also be useful when debugging is need for application to track the incident logs and associate it with originating container.

**Comment by kolloch** [comment]
That seems to be related to https://github.com/mesosphere/marathon/issues/717.

Why do you use hostnames for inter-container communication? Does that work only on the same host or also cluster wide?

**Comment by ajaybhatnagar** [comment]
When setting up containers as "cluster nodes", cluster configuration needs to know it's members and establish peer to peer communication between "cluster nodes". It has to be cluster wide. From operating perspectives, these containers should be distributed among multiple slaves so that one slave node failure does not affect cluster service availability.

**Comment by kolloch** [comment]
Hi @ajaybhatnagar, what concrete technology are you talking about when you mention "cluster nodes"?

I think again that this issue includes very many (though maybe related ideas). I do not think that it is Marathons job to solve them all.

You can use `mesos-dns`, `servicerouter` or one of the many other solutions for service discovery. Or you query the Marathon API for running tasks.

**Comment by ajaybhatnagar** [comment]
One such cluster is elasticsearch cluster with master data and client and tribe nodes. Agree it may not be part of the scope for Marathon, but ability to handle most of them with in Marathon, will make it a great single point solution.

There are need for info to be given to framework for startup or before startup vs querying APIs after tasks are running. Querying afterwards defeats the purpose of preplanned setup launch in one go with minimal components for a service.

**Comment by sepiroth887** [comment]
I would also like to see counters but for different reasons. 

I think the naming scheme is good as is as i found most use cases have better workarounds without the inherent limitation that scheduling containers will fail on a name clash. In effect it would work like a constraint but not in the expected scope of the executor. 

However for things like zookeeper i found that counters for the node id are really handy and forced me so far to run zk outside of mesos/marathon ( i tried to grt around this with clever startup scripts but i dont like doing that) 

You could use the "ambassador pattern" to delegate cluster memebership management.

**Comment by Raffo** [comment]
+1. We would love to be able to read the container id to get filenames generated by fluentd.

**Comment by Raffo** [comment]
I would love to start working on this feature, but I'm not familiar with scala. Would someone provide some support on how to do it (here, on IRC, anywhere else is also OK) to speedup the process?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2797. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2797. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
