### ISSUE TITLE
Constraint terms are not validated, invalid input is silently ignored

### ISSUE THREAD

**Issue by jaytaylor** [mesosphere/marathon#1903]
I had an invalid constraint of the following form:

``` json
{
    ...
    "constraints": [
        ["my_attribute", "UN]LIKE", "yes"]
    ]
}
```

Notice the `]` in the middle of "UN]LIKE".

Marathon doesn't complain at all and appears to simply ignore the clause.

This is not helpful.

API inputs should be validated against the documented acceptable values, and an error response should be emitted when invalid input is submitted.

Marathon version: 0.8.1

**Comment by kolloch** [comment]
I agree, it would nice if they would be validated.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3132. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3132. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
