### ISSUE TITLE
Marathon cannot deal with SCALAR values in mesos slave attributes.

### ISSUE THREAD

**Issue by rncry** [mesosphere/marathon#1906]
If a mesos slave has an attribute set to a SCALAR value (eg `cpu:4`) this will not be matched by any filters in Marathon (eg `["cpu", "CLUSTER", "4"]`) when submitting a job, and consequently the job will never run.

**Comment by kolloch** [comment]
Thanks a lot for creating the issue!

**Comment by bobrik** [comment]
I think #1711 is the main issue here.

**Comment by kolloch** [comment]
Thanks, @bobrik. Closing duplicate.
