### ISSUE TITLE
Marathon should optionally log all configuration values.

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#1908]
Perhaps this could be implemented as an additional `--log_config` flag.

**Comment by guenter** [comment]
Seems generally useful, how about making it the default in Chaos?

**Comment by ConnorDoyle** [comment]
+1

**Comment by air** [comment]
Motivation: if we ask a customer to use flags `--foo` and `--bar`, we need a way to confirm those flags were correctly specified and accepted.

**Comment by kolloch** [comment]
@air  Since it is difficult to implement this completely, is logging command line arguments acceptable for now? Shall we close this?

**Comment by air** [comment]
> logging command line arguments 

If that captures all the user-specified config, yep good to go.

**Comment by air** [comment]
...and I assume that if any of the flags are incorrectly specified or wrong, the log will show their rejection right?

**Comment by ConnorDoyle** [comment]
@air Marathon will not start if it can't recognize all of the flags.

**Comment by kolloch** [comment]
Cool, that seems to resolve that. Thanks @air and @ConnorDoyle !
