### ISSUE TITLE
Useful configuration values missing from `/v2/info` output

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#1909]
Including `--max_tasks_per_offer`.

**Comment by air** [comment]
Motivation: if we ask a customer to use flags `--foo` and `--bar`, we need a way to confirm those flags were correctly specified and accepted.

**Comment by kolloch** [comment]
Yes! We should do that for every configuration option.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3651. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3651. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
