### ISSUE TITLE
Marathon becomes unresponsive under load

### ISSUE THREAD

**Issue by air** [mesosphere/marathon#1910]
Couldn't find an existing issue for this, LMK. This issue needs more definition and validation.

Report from @pyronicide:
> once the app hit about 3k tasks, we were able to view the UI at this point but could not destroy the app. Once we hit 4k tasks, Marathon became completely unresponsive to HTTP requests via. the browser and had 30s response times. We tried to roll back a deployment but the tasks continued to slowly climb to 5k (which it eventually hit 30min later). We then tried to delete the app. The API request came back successfully, no tasks were killed.

Goals
- As number of tasks increases, the API should not become unresponsive.
- Requests to interrupt runaway deployments should work.

**Comment by jaytaylor** [comment]
Since switching to a single node (hoping for better consistency/less state corruption) I've also experienced and noticed this behavior.

**Comment by lloesche** [comment]
Without knowing details about the installation, how much memory is Marathon running with? The default is 512MB if I'm not mistaken which is only sufficient for small installations. On a medium size cluster we're using `-Xmx2G` as a JVM arg and `--max_tasks_per_offer 100 --task_launch_timeout 86400000` as Marathon args for Marathon 0.9.1 on Mesos 0.23.0. Don't use the Marathon args on older versions though as they rely on a new feature in Marathon and a bugfix in Mesos 0.23.0. The `-Xmx2G` can and should be used on older versions and maybe even increased depending on the size of your cluster.

**Comment by jaytaylor** [comment]
It's a tiny cluster with less than 3 apps running.  The memory settings are
left at the default.

Are you saying that out-of-the-box Marathon does not come configured with
enough memory to run 3 tasks and still respond to API requests?

**Comment by lloesche** [comment]
The original ticket is talking about 4.000 tasks not 3. The defaults are set in `bin/marathon-framework` and can be overwritten by exporting `JAVA_OPTS`. Marathon as such comes as a jar file and if you're not using one of the startup wrappers the defaults of your JVM are used. You can print them with `java -XX:+PrintFlagsFinal 2>&1 | grep MaxHeapSize`. E.g. on a server with 256GB ram the default in OpenJDK 1.7 would be 32GB max heap size.

**Comment by aquamatthias** [comment]
The problem described here does not relate to Marathon, but to the configuration of the mesos slave nodes. The ulimit was not set properly, so that the slave processes died, when trying to launch tasks. That leads to mesos master problems, so that Marathon became unresponsive (since all messages send to mesos were ignored or timed out). 

I will close this ticket, since it directly reflects a specific problem which is solved.
