### ISSUE TITLE
Network reliability issues lead to Marathon state corruption

### ISSUE THREAD

**Issue by jaytaylor** [mesosphere/marathon#1912]
I believe I've tracked down the source of many of my issues and believe it is likely the same for many others which get filed and then dismissed as _cannot reproduce_.

I've been running and experiment for about a month.

I've got two Mesos/Marathon clusters;
- 3 Mesos/Marathon nodes running on AWS us-west-2
- 3 physical server nodes wired directly into a gigabit switch at my house, all backed by a UPS.

A week ago I deployed some apps to the AWS cluster on a Friday.  Left it alone all weekend and came back Monday morning to a broken cluster.  Marathon had become out of sync w/ Mesos, and some apps were offline completely (containers no longer running).  Other apps had empty (non-green) status bars in Marathon but were still alive in Mesos.  Restarting the cluster did not help Marathon identify the broken states, and ultimately I resorted to `rmr`'ing all of `/marathon` in zookeeper to get it back to a working state.

Now to contrast this with yesterday's discovery:

I'd deployed a few apps to the home LAN cluster almost exactly 30 days ago and have left it alone (forgot about it until yesterday :).  When I inspected the apps and cluster yesterday, things looked pretty good!  Marathon successfully delivered on the promise of keeping things up.
### What is the difference?

These 2 clusters were actually built with the exact same set of Ansible scripts and all the same versions of Marathon and Mesos.

The glaring difference I see is network reliability.  I would not have realized the inability to reproduce the issue if I had not left it running on an "ideal scenario" network (my home).

Has the marathon team looked into how marathon performs in various network reliability scenarios?

**Comment by kolloch** [comment]
There are some mechanisms in place to deal with communication outages:

* Marathon reconnects to the Mesos leader after connection failures
* Marathon periodically performs a reconciliation of task state (it basically requests all task status from Mesos for that)

Nevertheless, depending how bad your network connectivity is, you get problems in Marathon.

It would be interesting to see the logs of your Marathon. Sounds like it could not really reconnect to the Mesos master and reconcile the task states.

Marathon depends on Zookeeper working reliably both for its own leadership election as well as for storing state and connecting to the mesos master.

**Comment by aquamatthias** [comment]
@jaytaylor Thanks for reporting this! Do you think you could provide us with the logs of the problematic case? 
- Marathon log
- Mesos master log
That would help us a lot!

**Comment by jaytaylor** [comment]
Not sure if the logs are still there.  I'll check it out and see how far back my logs go.

**Comment by jaytaylor** [comment]
@aquamatthias Just checked and unfortunately those logs are long gone.

The conditions are quite straightforward: Setup a 3-node mesos+marathon cluster (ZK, Mesos, and Marathon run on each node) with 2+ mesos slaves on an unreliable network (e.g. AWS) and leave a few apps running for a few days.  Things will most likely go sideways.

For reference, I was running this on `m1.medium` instances.

**Comment by aquamatthias** [comment]
@jaytaylor Thanks for the update. If you see that happen again - please report. We will try to reproduce that as well.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2681. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2681. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
