### ISSUE TITLE
CPU thrashing with multiple tasks on multicore machines

### ISSUE THREAD

**Issue by sheldonkwok** [mesosphere/marathon#1913]
I'm running one task for every core on our forty core machine and encountering cpu thrashing where none of the tasks actually get very much cpu time because of the context switching. There doesn't seem to be an option to use the cpuset flag feature that Docker has.

**Comment by kolloch** [comment]
You can use the "parameters" parameter:

https://mesosphere.github.io/marathon/docs/native-docker.html#privileged-mode-and-arbitrary-docker-options

**Comment by sheldonkwok** [comment]
I already looked at this and it doesn't seem like you can set it dynamically unless I missed something. So this does not solve my issue. I ended up setting the cpus in the tasks but it seems like more of a hack that could be better solved higher up.

**Comment by kolloch** [comment]
You are right about not being able to set that dynamically.

So what did you have in mind exact? Can you elaborate? How could an API for this look like? What would it do?

Thanks!

**Comment by sheldonkwok** [comment]
Rather then setting the relative cpu shares that a process gets, I was thinking there could be an option to actually set the number of cpus the process gets. However, I solved the issue with CFS tuning and limiting the number of threads that each task uses and its working well now.

**Comment by kolloch** [comment]
Hi @sheldonkwok,

thanks for sharing that!

If you think that your insights could be generally useful to other docker users, we would like to encourage you to contribute to our documentation:

https://mesosphere.github.io/marathon/docs/contributing.html

**Comment by sybrandy** [comment]
Has this been documented?  I'd love to know more as I think we're running into a similar situation.

**Comment by xiaods** [comment]
cpuset can add by parameter. refer:https://mesosphere.github.io/marathon/docs/native-docker.html#privileged-mode-and-arbitrary-docker-options

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3599. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3599. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
