### ISSUE TITLE
Allow setting a max number of instances in the app definition

### ISSUE THREAD

**Issue by lloesche** [mesosphere/marathon#1914]
I have an application InfluxDB which has a requirement:

```
all clusters must contain three and only three nodes
```

It would be very handy if when creating my application I could set a lower and upper boundary for the number of instances this app is ever allowed to have during it's lifecycle. Just to prevent unknowing colleagues from accidentally scaling an app that e.g. mustn't have more than 3 instances to 4 and potentially causing data corruption.
It should be possible to update those boundaries but if I just scale the number of instances it shouldn't be possible to scale outside the pre-defined boundaries.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3130. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3130. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
