### ISSUE TITLE
Allow setting the number of instances to the number of slaves + expressions

### ISSUE THREAD

**Issue by lloesche** [mesosphere/marathon#1915]
I'd like to run a monitoring agent on every slave. Given enough resources I could currently set a constraint UNIQUE hostname and the number of instances to the number of slaves.
Instead of having to manually specify the number of slaves (which might fluctuate) Marathon should be able to figure it out itself. I'd like to use a variable name like '$num_slaves' instead of entering a specific number. Marathon should scale those apps as slaves come and go.

Likewise I'd like to be able to enter mathematical expressions (maybe this should be a second ticket?). So that I can run a service on e.g. 1/3 of my available slaves. For that I'd like to enter '$num_slaves/3'

There is currently an open ticket (would have to ask Cody for the number) in Mesos that will allow running system services on slaves irregardless of available resources/in system reserved resources.

This feature would already be universally useful for all kinds of monitoring, metrics collection agents and distributed filesystem clients and will be even more useful once Mesos supports system services.

This will also enable a new kind of DCOS application. At the moment to ensure that a service like e.g. the prometheus node exporter is running on every DCOS node we have to ship it embedded with the DCOS system image. This function will allow us and partners to ship services like the monitoring agents or a distributed filesystem client and run it on every slave in the cluster, without it having to be hard embedded into the system image.

**Comment by TalonOne** [comment]
+1 Would love to see this feature in Marathon!

**Comment by sepiroth887** [comment]
+1 similar things have been asked for multiple times. The use-cases are mostly around monitoring/metrics and helper images I guess. 

I still like the "instances" : "*" idea best ^^

**Comment by kolloch** [comment]
This is related to https://github.com/mesosphere/marathon/issues/846 and https://github.com/mesosphere/marathon/issues/1264

**Comment by lloesche** [comment]
I mean right now as a workaround for the first part I can just set hostname UNIQUE and instances to 10000000 and let Marathon figure it out. Probably not the neatest way to solve this though and doesn't allow me to specify 1/3 of all slaves. Also leaves a permanent deployment in the system.

**Comment by JohnOmernik** [comment]
I would like this feature as well. +1

**Comment by fksimon** [comment]
+1

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3173. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3173. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
