### ISSUE TITLE
Creating an App Using a Non-Leader Instance

### ISSUE THREAD

**Issue by coderlol** [mesosphere/marathon#1916]
Is it supposed to be possible to create an app, POSTING to the the /v2/apps end-point of a node that is the leader?  I have found that with Marathon 0.9.1 I have to POST to the leader node.

/v2/tasks, /v2/leader end points work fine against non-leader.

**Comment by kolloch** [comment]
This sounds like it is related to 

https://github.com/mesosphere/marathon/issues/1763

Are you using curl or some other tool which uses 100-continue for POSTs? Are you using Java 6 or 7?

If this is not related, please reopen with more details.

**Comment by coderlol** [comment]
Jupp, I'm using curl via ansible:

- name: Post Request to Marathon to Create App
  command: "curl -u marathonUser:marathonPassword -X POST -H \"Content-Type: application/json\" {{marathonUrl}} -d@{{appJson}}"

I think this is what Marathon picks up.  I don't have another java on the machine.

/usr/bin/java -version
java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-0ubuntu1.14.04.1)

OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

**Comment by kolloch** [comment]
So, either upgrade the Java version or use a curl option that prevents 100-continue.

That should be similar to `-H Expect:`
