### ISSUE TITLE
Declining Offers Infinute Loop

### ISSUE THREAD

**Issue by coderlol** [mesosphere/marathon#1917]
Mesos 0.23.0
Marathon 0.91.0
Ubuntu 14.04.02
Chronos 2.3.4

I have 3 nodes with each node running mesos master, slave, chronos, Zookeeper.  The Leader marathon node (myhost-3) logs the below continuously.  There is some seemingly infinite loop with mesos offering resources and chronos and marathon rejecting the offers.

Is this correct behavior?  That's quite a bit of /var/log/syslog that will build up over time.

Anything that can be done to control the never ending offering and rejection?

Aug  3 03:42:03 myhost-3 mesos-master[6088]: I0803 03:42:03.401494  6107 master.cpp:4290] Sending 4 offers to framework 20150802-195311-1646718986-5050-6183-0002 (chronos-2.3.4) at scheduler-e7256acf-9ee8-44a4-8ee6-571412b1fbc2@10.240.191.227:52921
Aug  3 03:42:03 myhost-3 chronos[12510]: [2015-08-03 03:42:03,402] INFO Received resource offers
Aug  3 03:42:03 myhost-3 chronos[12510]:  (org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework:79)
Aug  3 03:42:03 myhost-3 chronos[12510]: [2015-08-03 03:42:03,402] INFO No tasks scheduled or next task has been disabled.
Aug  3 03:42:03 myhost-3 chronos[12510]:  (org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework:115)
Aug  3 03:42:03 myhost-3 chronos[12510]: [2015-08-03 03:42:03,402] INFO Declining unused offers.
Aug  3 03:42:03 myhost-3 chronos[12510]:  (org.apache.mesos.chronos.scheduler.mesos.MesosJobFramework:86)
Aug  3 03:42:03 myhost-3 mesos-master[6088]: I0803 03:42:03.403924  6110 master.cpp:2884] Processing DECLINE call for offers: [ 20150802-195316-3821006858-5050-6088-O56348 ] for framework 20150802-195311-1646718986-5050-6183-0002 (chronos-2.3.4) at scheduler-e7256acf-9ee8-44a4-8ee6-571412b1fbc2@10.240.191.227:52921
Aug  3 03:42:03 myhost-3 mesos-master[6088]: I0803 03:42:03.404011  6110 hierarchical.hpp:761] Recovered cpus(*):1; mem(*):2676; disk(*):5023; ports(*):[31000-32000] (total: cpus(*):1; mem(*):2676; disk(*):5023; ports(*):[31000-32000], allocated: ) on slave 20150802-195311-1646718986-5050-6183-S2 from framework 20150802-195311-1646718986-5050-6183-0002
Aug  3 03:42:03 myhost-3 mesos-master[6088]: I0803 03:42:03.404467  6111 master.cpp:2884] Processing DECLINE call for offers: [ 20150802-195316-3821006858-5050-6088-O56349 ] for framework 20150802-195311-1646718986-5050-6183-0002 (chronos-2.3.4) at scheduler-e7256acf-9ee8-44a4-8ee6-571412b1fbc2@10.240.191.227:52921
Aug  3 03:42:03 myhost-3 mesos-master[6088]: I0803 03:42:03.404561  6111 hierarchical.hpp:761] Recovered cpus(*):1; mem(*):2676; disk(*):5023; ports(*):[31000-32000] (total: cpus(*):1; mem(*):2676; disk(*):5023; ports(*):[31000-32000], allocated: ) on slave 20150802-195311-1646718986-5050-6183-S0 from framework 20150802-195311-1646718986-5050-6183-0002
Aug  3 03:42:03 myhost-3 mesos-master[6088]: I0803 03:42:03.404908  6108 master.cpp:2884] Processing DECLINE call for offers: [ 20150802-195316-3821006858-5050-6088-O56350 ] for framework 20150802-195311-1646718986-5050-6183-0002 (chronos-2.3.4) at scheduler-e7256acf-9ee8-44a4-8ee6-571412b1fbc2@10.240.191.227:52921
Aug  3 03:42:03 myhost-3 mesos-master[6088]: I0803 03:42:03.405006  6108 hierarchical.hpp:761] Recovered cpus(*):1; mem(*):2676; disk(*):5023; ports(*):[31000-32000] (total: cpus(*):1; mem(*):2676; disk(*):5023; ports(*):[31000-32000], allocated: ) on slave 20150802-195311-1646718986-5050-6183-S1 from framework 20150802-195311-1646718986-5050-6183-0002
Aug  3 03:42:03 myhost-3 mesos-master[6088]: I0803 03:42:03.405375  6106 master.cpp:2884] Processing DECLINE call for offers: [ 20150802-195316-3821006858-5050-6088-O56351 ] for framework 20150802-195311-1646718986-5050-6183-0002 (chronos-2.3.4) at scheduler-e7256acf-9ee8-44a4-8ee6-571412b1fbc2@10.240.191.227:52921
Aug  3 03:42:03 myhost-3 mesos-master[6088]: I0803 03:42:03.405448  6106 hierarchical.hpp:761] Recovered cpus(*):4; mem(*):25104; disk(*):5023; ports(*):[31000-32000] (total: cpus(*):4; mem(*):25104; disk(*):5023; ports(*):[31000-32000], allocated: ) on slave 20150802-195316-3821006858-5050-6088-S3 from framework 20150802-195311-1646718986-5050-6183-0002

**Comment by kolloch** [comment]
Yes, this is the expected behavior. This is how Mesos works: It regularly sends available resources to the interested parties.

**Comment by coderlol** [comment]
Can the interval be controlled?

**Comment by adam-mesos** [comment]
@coderlol The interval with which Mesos sends offers to any/all frameworks can be set with `--allocation_interval` (default 1sec).
Each framework can also specify a non-default filter timeout (default 5sec), and Marathon added configurability for its decline timeouts in issue #1931
