### ISSUE TITLE
Proposal: Pre/Post Deployment Hook and Dynamic Attributes / Constraints

### ISSUE THREAD

**Issue by coderlol** [mesosphere/marathon#1923]
With mesos and docker, I need to deploy either A or B.  If A is running on the node, don't deploy B.  If B is deployed on the node, don't deploy A.

I figure a way to accomplish this is to update the mesos slave attributes.  I think it would be useful to have pre and post deployment hooks that can be executed in the host context.  I could use the hooks to dynamically update mesos attributes.

Comments?

**Comment by aquamatthias** [comment]
@coderlol If I understand correctly you want to schedule a task, depending on what is running on that node already? What is the reasoning for Pre/Post hooks? What are dynamic attributes / constraints? 
Can you elaborate a bit more, what you try to solve?

**Comment by Niyakiy** [comment]
Hi. Nearly equal to described in task functional requirements I'd like to have too.
It would be good to have some kind of post-task-start hook (which executes command, starts other marathon task or so). 
It can be useful, for example, for registering newly created task in Services Discovery service, or filling newly spawned docker container with data, or cascading marathon tasks execution, etc

**Comment by ensonik** [comment]
+1. I could use this to submit (through a bash script/command) an event to Datadog every time an application is deployed.

**Comment by dgromov** [comment]
+1. This would be super helpful.

**Comment by mjdev** [comment]
+1 I would like to use it to register services in Kong after deployment

**Comment by xiaods** [comment]
+1

**Comment by junneyang** [comment]
+1

**Comment by scheerer** [comment]
+1

**Comment by brat002** [comment]
+1

**Comment by ericf89** [comment]
Anyone found any decent workarounds this in the meantime?   I'd like to make a `curl` to kick off some integration tests once an app deploy is finished, but don't really see any simple way to do that.

**Comment by xiaods** [comment]
close it as favor.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3560. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3560. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
