### ISSUE TITLE
App stuck in deployment because of missing (unneeded) disk resource in the offer

### ISSUE THREAD

**Issue by benh** [mesosphere/marathon#1924]
It looks like we return a `None` if the offer doesn't include all of 'cpu', 'mem', and 'disk' resources as seen here: https://github.com/mesosphere/marathon/blob/v0.8.1/src/main/scala/mesosphere/mesos/TaskBuilder.scala#L174.

Mesos will not pass a 'disk' resource if there is 0 available disk on that machine (e.g., if all of the disk is used up by other tasks). Thus, even if there is ample 'cpu' and 'mem' resources Marathon will reject an offer because it does not contain a 'disk' resource even though the disk requirement for a task might be 0.

We've reproduced this behavior with Marathon by launching a one machine cluster and running one task which takes all the 'disk' followed by another task which required 'disk: 0' and confirmed that the second task would not launch.

**Comment by kolloch** [comment]
This should also be backported. @ConnorDoyle already provided a fix for 0.8.1 in #1925 .

**Comment by kolloch** [comment]
Patches for the 0.8, 0.9 and 0.10 already landed.

We keep this issue open until we have something on master which will eventually land in 0.11.
