### ISSUE TITLE
Marathon should log why an offer didn't match

### ISSUE THREAD

**Issue by lloesche** [mesosphere/marathon#1927]
At the moment Marathon will log what it needs
```
(need cpus=2.0, mem=51200.0, disk=0.0, ports=List(20020))
```
followed by several pages of resources and attributes in the offer. It's up to a human to scan through the log and find the reason why the offer didn't match. Instead if would be nice if Marathon could just log a single line stating the reason(s) why the offer was no match.

**Comment by aquamatthias** [comment]
@kolloch I see a lot of commits here. Can we close this ticket?
