### ISSUE TITLE
Marathon should deal with offer fragmentation.

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#1929]
A short hoarding period could give Marathon a chance to merge offers from the same slave in order to mitigate this.  Marathon could furthermore auto-tune the hoarding period by computing running statistics about offer inter-arrival time per-slave.

**Comment by kolloch** [comment]
@ConnorDoyle Shouldn't Mesos defragment offers if we reject unused offers quickly? I had a discussion with some core guys yesterday about a related topic and my impression was that this should not be an issue.

Is there a specific customer issue here that you observed or is it speculation? What obvious case am I missing? ;)

@rukletsov I would appreciate your thoughts on this. Thanks!

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2771. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2771. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
