### ISSUE TITLE
Can we convert version string to local time?

### ISSUE THREAD

**Issue by fengyehong** [mesosphere/marathon#1937]
In GUI app configuration page, I want to see app version with local time.
It is convenient especially when checking the timestamp of  current version.  
And I noticed that headers of older versions have been converted to local time.  
![2015-08-05 17 40 29](https://cloud.githubusercontent.com/assets/12654661/9082831/1d5523e0-3b99-11e5-8023-aac59bde7417.png)

So, is this OK?

**Comment by aldipower** [comment]
Hi,
good point, yes we could additionally display the local time behind the version string or on mouse hover. We will take care of this.
