### ISSUE TITLE
User-provided version

### ISSUE THREAD

**Issue by bsideup** [mesosphere/marathon#1947]
Hi!

Is it possible to specify custom version id for deployment? 

Thanks!

**Comment by aldipower** [comment]
At the best of my knowledge and in the case I understand you correctly, a deployment results in a new version _timestamp_, if the deployment is triggered, so this should not be possible. Can you give me some more information, maybe what you want to achieve? Thank you.

**Comment by bsideup** [comment]
@aldipower I used Elastic Beanstalk a lot before Marathon and what I want from Marathon is:

1) API for creating version of application (without deployment). Very useful for CI: build server is creating version and notifying ops about new available version. Then ops guy can review this version and if everything is fine (instance amount, memory, env vars) - it will press "deploy" (see 2) ).
2) API for deploying existing version from "catalog" (already implemented as "configuration history") 

I do understand that 1) could be implemented by storing manifests somewhere, but it will cause duplication (somewhere + config. history)


This is why "custom version" is important - CI can create this version with id like "foo-service-v1.3.4-ab83a7ef1", and release request will looks like "please release foo-service v1.3.4"

**Comment by aldipower** [comment]
Hey @bsideup !
Thank you for your explanation, now I understand and see the use case for this.
For now this isn't possible and planed, but we will have this in mind.
You could store app definitions in JSON-format of course by yourself and then apply them to Marathon. And maintain a custom catalog. This would be a solution for the meantime.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3048. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3048. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
