### ISSUE TITLE
Support checksumming of URIs

### ISSUE THREAD

**Issue by lloesche** [mesosphere/marathon#1950]
The URIs are downloaded and executed in my datacenter. I'd like the ability to also define a checksum for each URI, like e.g.:

```
   "uris": [
      "https://downloads.mesosphere.io/jenkins/0.7.0/jenkins-on-mesos.tgz",
      "https://downloads.mesosphere.io/some-other-file.tgz",
      "https://downloads.mesosphere.io/file-without-checksum.zip"
   ],
   "checksums": [
      "sha256=8f7c9b188344312ab12b0c9845d08ea7978f54ebd8a38740d8db30d8a920df62",
      "md5=8c26545f2b88b8a3b09b31cfb9d73b39",
      ""
   ]
```

Esp. considering DCOS universe and multiverse packages which some day will contain URIs hosted outside mesosphere servers this is going to be a valuable function. But also in case our systems ever get compromised this would add an extra layer of protection for our users since attackers would have to modify the files on the file storage as well as the metadata in Github.

Edit: I just realised URIs are probably just passed through to mesos-fetcher. So I guess this is something Mesos has to support first and then Marathon can implement it?

Edit 2: Turns out the Mesos team is already working on this: https://issues.apache.org/jira/browse/MESOS-2073

**Comment by aquamatthias** [comment]
Hey @lloesche this has to be supported from mesos as well. Can you create a JIRA for mesos and cross reference that here? Thanks!

**Comment by lloesche** [comment]
@aquamatthias it's already there, see Edit 2

**Comment by aquamatthias** [comment]
@lloesche Cool. We will start working on this when it is available in mesos.
Looking at the format of the suggestion, I think we should improve the format (I guess your suggestion is based on ordering, which could lead to problems easily).

I could think of something like:
```json
"uris": [
   { "uri": "http://foo.bla/asset1.tgz", "sha256": "xxx"},
   { "uri": "http://foo.bla/asset2.tgz", "md5": "xxx"},
   { "uri": "http://foo.bla/asset3.tgz"}
]
```

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3394. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3394. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
