### ISSUE TITLE
Surface resource offers in the UI

### ISSUE THREAD

**Issue by aatumanova** [mesosphere/marathon#1952]
Surface the offers that marathon is receiving from Mesos, and why they do or do not match.

**Comment by air** [comment]
Looks related to #1090

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2759. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2759. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
