### ISSUE TITLE
Add support for the new fetcher cache in Mesos 0.23

### ISSUE THREAD

**Issue by ssk2** [mesosphere/marathon#1953]
It looks like this requires additional configuration and for the fetcher cache boolean to set to be true when tasks are executed (as per https://github.com/apache/mesos/blob/master/docs/fetcher.md).  It would be nifty if Marathon supported this feature!

This is related to #1377.

**Comment by pdiorio** [comment]
+1 This would be a very useful addition!

**Comment by mindscratch** [comment]
:+1:

**Comment by sybrandy** [comment]
idea++ :+1:

**Comment by mindscratch** [comment]
Any chance this will make it in the 0.13.0 release?

**Comment by mindscratch** [comment]
I guess not. Perhaps 0.14?

**Comment by wendigo** [comment]
I can work on this but I need a tip from core-devs how to expose it via API :)

Looking at source in V2AppDefinition: ```uris: Seq[String] = AppDefinition.DefaultUris,``` this cannot be extended to be backwards compatible. We can add another field that will be combined with uris though.

**Comment by wendigo** [comment]
@aquamatthias looking forward for your opinion on that :)

**Comment by aquamatthias** [comment]
The URI's in mesos look like this:
```
 message URI {
    required string value = 1;
    optional bool executable = 2;
    optional bool extract = 3 [default = true];
    optional bool cache = 4;
  }
```
In order to support this data structure, we have to move away from simple strings.
The new field should allow expressing those properties, where all properties than the URI are optional. Example:
```
[
  { "uri": "http://example.com/bla" },
  { "uri": "http://example.com/foo", "executable": true, "extract": false, "cache": false }
]
```
To make this backward compatible, the `uris` property should stay as is with defaults applied.

Since `uris` is a pretty good name, we need another one. 
What would be a good name?

**Comment by wendigo** [comment]
Maybe something like "artifacts" since we are downloading them in order to launch our application.

**Comment by wendigo** [comment]
Or "fetchUris" or "downloadUris".

**Comment by mindscratch** [comment]
I'd prefer `uris` change to new format. As you mentioned, today there are default values being used for the other properties, why not expose them? There have been backward incompatible changes made before.

**Comment by wendigo** [comment]
@mindscratch I do not like breaking compatibility if it can be avoided.

**Comment by aquamatthias** [comment]
We already also have `storeUrls` - which makes it even more confusing...
At least in the format we should be backward compatible.

**Comment by mindscratch** [comment]
So what would be the difference between `uris` and say, `fetchUris`? It seems confusing to have two different properties that might do the same thing.

**Comment by wendigo** [comment]
I think that best solution is to provide V3 API in which every primitve type (i.e. string) is replaced with class enclosing this type (so "uris": ["uri1"] becomes "uris": [{"uri": "uri1"}]). Since we can't do that I would introduce new field and mark old one as deprecated to be dropped in next versions.

**Comment by wendigo** [comment]
Any thoughts @aquamatthias ?

**Comment by aquamatthias** [comment]
Hey @wendigo had the same idea in mind (see comment above) - introduce a new parameter with new format which supersedes 'uris'.

**Comment by wendigo** [comment]
So let's settle on naming and I can implement this feature :)

**Comment by mindscratch** [comment]
I'll vote for fetchUris ...can't wait to see this land.

**Comment by aquamatthias** [comment]
Naming is hard ...
What about the simple version?
fetch:[{uri:xxx}]

**Comment by wendigo** [comment]
Ok, I'm on it :)

**Comment by mindscratch** [comment]
Sounds good

**Comment by wendigo** [comment]
Almost there :smile: 

```Tests: succeeded 849, failed 0, canceled 0, ignored 2, pending 0```

**Comment by mindscratch** [comment]
Awesome!

**Comment by wendigo** [comment]
Done!
