### ISSUE TITLE
Create artifact storage directory if not exists

### ISSUE THREAD

**Issue by bsideup** [mesosphere/marathon#1955]
Hi!

If artifact storage is filesystem-based and directory not exists then Marathon will fail to start. Probably auto-creation of directory would be better option.

Thanks

**Comment by aquamatthias** [comment]
This indeed is currently a prerequisite for that storage provider: https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/io/storage/FileStorageProvider.scala#L53

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3526. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3526. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
