### ISSUE TITLE
Spurious Restarting App?

### ISSUE THREAD

**Issue by coderlol** [mesosphere/marathon#1965]
Has anyone noticed that at times Marathon spuriously restarting a docker container (docker v1.7.1, mesos 0.23, marathon 0.91) .

Most deployments go well, but from time to time, I would get see multiple containers on the same docker instance  for the same image.  The failed container does not have an "Exit" code.  The app definition specified only 1 instance.

Not sure what logs to collect that may help.

**Comment by aldipower** [comment]
Hi @coderlol , could you tell a little bit more about the docker container configuration?
And how many nodes are you running?

**Comment by coderlol** [comment]
docker containers all use bridge networking.  Number of containers about 3-4.  All containers share common layers "from".  The containers have different images, but the images share based images via "from"

I think the issue may occur when posting the apps to Marathon in quick succession and Marathon decides to push the containers to the same slave.  The same slave would use docker to pull the images.  If there is a problem pulling images (perhaps race condition), it is not recoverable.  Destroying the apps, via Marathon and/or at Docker, won't help.  A redeployment would see the same error.

Deleting all images from docker and re-deploying have helped.

I will see if I can get better observations

**Comment by coderlol** [comment]
I have marathon, chronos, mesos master on a 3 nodes cluster.  There are 2 different types (attributes) of slaves.  Each type has 2 slave nodes.

**Comment by aquamatthias** [comment]
Hey @coderlol It is hard to find the problem just by this description. Could you please 
- send the app definition you send
- the logs from Marathon 
- the logs from Mesos master and slave
So we are able to reproduce the problem. Thanks!

**Comment by coderlol** [comment]
Sure.  I have not seen it again, but will do if it comes back.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3597. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3597. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
