### ISSUE TITLE
Marathon Dockerfile insecure download

### ISSUE THREAD

**Issue by amouat** [mesosphere/marathon#1968]
Hi, I was just looking at the Marathon Dockerfile.

I'm not sure which Dockerfile is actually used to build the image, whether it's this one: 

https://hub.docker.com/r/mesosphere/marathon/~/dockerfile/

Or this one:

https://github.com/mesosphere/marathon/blob/master/Dockerfile

(or why the two are different), but in both cases they seem to install sbt by downloading from an http URL and without checking signatures or checksums.

This means that no guarantees can be given about what is in this image; sbt may have been tampered with either in transit or on the download site, and there is no way of telling.

It would be great if you started validating checksums or at least used an https URL. For examples of how to do this see the official images e.g. https://github.com/docker-library/redis/blob/37efc31242c8415d4f2e6d84255af0c7b97567c5/3.0/32bit/Dockerfile

**Comment by kolloch** [comment]
Hi @amouat, thanks, good point!

Could you provide a patch for that? We are accepting pull requests.

https://mesosphere.github.io/marathon/docs/contributing.html

**Comment by amouat** [comment]
Could do, but is this really the correct Dockerfile: https://github.com/mesosphere/marathon/blob/master/Dockerfile ?

It doesn't actually build.

**Comment by amouat** [comment]
If you can get someone to fix the build issue, I'm happy to help fix the insecure download.

Looks like I'll be at mesoscon next week if that helps.

**Comment by amouat** [comment]
Apologies for my previous comment, I've now figured out what's going on with the Hub builds (I'm not having a good day). You can click on the build ids to get the details.

I'll come up with some suggestions next week if I can. I'd also suggest cleaning up the builds if possible. For instance, what is the difference between 0.9.1 and v0.9.1? A latest tag that points to the newest stable version would be very useful for newcomers.

**Comment by amouat** [comment]
As a quick fix that makes things a lot better (but still not great) - just change the URL from http to https. It would still be much better to use checksums, but I'll need sometime to sit down with this. It's probably worth re-working things into two separate Dockerfiles, one of which is minimal image based on the JRE and only includes the jar file rather than all the sources and build tools.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3093. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3093. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
