### ISSUE TITLE
Should marathon do scaling automatically when an app deployed with constraints "HOST UNIQUE"?

### ISSUE THREAD

**Issue by BrickXu** [mesosphere/marathon#1974]
Hi all,

I've use marathon to manage deploy containers over 100+ nodes of cluster, and the cluster is still growing. Maybe 10+ or 20+ nodes joined the cluster at the same time and I need to scale some applications number up as many as the cluster nodes (via constraints `["HOST", "UNIQUE"]`) by the scripts.

Could marathon do something if an application was deployed by `["HOST", "UNIQUE"]`? I mean that when the new nodes join the cluster, marathon could find out which server is new, then deploy the application by itself. 

Thanks.

**Comment by aquamatthias** [comment]
Hey @BrickXu 
See #1915, #846 and #1264 for reference.
Currently there is no way of doing that inside marathon.
A simple way of doing that: Schedule a job that get's the current number of slaves from the mesos master and PUT a scale update to the related apps in Marathon with host unique constraint.
