### ISSUE TITLE
Discussion: component testing

### ISSUE THREAD

**Issue by aldipower** [mesosphere/marathon#1975]
This continues this, if wanted:
https://github.com/mesosphere/marathon-ui/pull/54

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2735. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2735. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
