### ISSUE TITLE
Bug with request to /v2/apps/.

### ISSUE THREAD

**Issue by mgummelt** [mesosphere/marathon#1977]
For whatever reason, we've seen a user run `dcos marathon app update . <properties>`, where the `.` is understood to be an app ID.  So we call `http://localhost:5080/marathon/v2/apps/.`

Rather than interpreting this as a request for an app with ID `.`, marathon seems to rewrite this to /v2/apps, which serves a different JSON format, therefore crashing the CLI.

**Comment by kolloch** [comment]
This is probably done by the HTTP framework that Marathon uses and not under our direct control. Wouldn't it make sense to validate that in the dcos CLI?

**Comment by mgummelt** [comment]
If "." is an invalid app ID, marathon should reply with an appropriate error message so that all clients can see that.  A CLI check would only fix the CLI, and in general result in duplicated effort across several clients.

**Comment by jasongilanfarr** [comment]
Reopen if this is still relevant.
