### ISSUE TITLE
Creation of state path in Zookeeper fails when performed concurrently

### ISSUE THREAD

**Issue by howardzhang** [mesosphere/marathon#1984]
Environment:
Marathon: 0.9.1
Mesos: 0.23.0
Zookeeper: 3.5.0-alpha
3 AWS EC2 instances(OS: centos 7.0)

I deploy this environment on AWS using Chef. After the deployment completes, the Marathon service on at least one EC2 instance(not limited to the EC2 instance has the leader of Mesos Master) is not available. I cannot access the RESTful API of Marathon. 

From the log("/var/log/message") 
```
Aug 12 06:32:32 vos-node-03 marathon[2559]: [2015-08-12 06:32:32,282] INFO Session establishment complete on server localhost/0:0:0:0:0:0:0:1:2181, sessionid = 0x34f209c213e0007, negotiated timeout = 40000 (org.apache.zookeeper.ClientCnxn:1235)
Aug 12 06:32:32 vos-node-03 marathon[2559]: [2015-08-12 06:32:32,428] INFO Registering in Zookeeper with hostPort:vos-node-03:8080 (mesosphere.marathon.MarathonModule:207)
Aug 12 06:32:32 vos-node-03 marathon[2559]: [2015-08-12 06:32:32,582] INFO Now standing by. Closing existing handles and rejecting new. (mesosphere.marathon.event.http.HttpEventStreamActor:100)
Aug 12 06:32:32 vos-node-03 marathon[2559]: [2015-08-12 06:32:32,584] INFO http_endpoints(List(http://127.0.0.1:8088/api/v1/marathon_event/)) are specified at startup. Those will be added to subscribers list. (mesosphere.marathon.event.http.HttpEventModule:61)
Aug 12 06:32:32 vos-node-03 marathon[2559]: Exception in thread "main" com.google.inject.CreationException: Guice creation errors:
Aug 12 06:32:32 vos-node-03 marathon[2559]:
Aug 12 06:32:32 vos-node-03 marathon[2559]: 1) Tried proxying mesosphere.marathon.MarathonScheduler to support a circular dependency, but it is not an interface.
... ... 
```

More detail log please refer to https://gist.github.com/howardzhang/02c8184f803d3effefa9

Does anyone get any information on this?

**Comment by kolloch** [comment]
Hi @howardzhang, thanks for reporting this.

Can you tell us the command line parameters that Marathon is started with?

**Comment by howardzhang** [comment]
Hi @kolloch, thanks for your attention.
Below is the command line parameters.
```
/usr/bin/marathon mesosphere.marathon.Main --event_subscriber http_callback --http_endpoints http://127.0.0.1:8088/api/v1/marathon_event/ --zk zk://localhost:2181/marathon --master zk://localhost:2181/mesos
```

**Comment by kolloch** [comment]
Hi @howardzhang, we have released two release candidates that should fix your problem:

* v0.10.1-RC1
* v0.9.3-RC1 

It would be great if you could confirm if these fix your issue.

Thanks a lot!

**Comment by aquamatthias** [comment]
Danke Peter!  Wollte ich am Montag machen - die Message in Slack war nur eine Info, falls einer fragt. Wir müssen nochmal diskutieren, ob so ein fix einen RC Cycle durchlaufen muss. 

Schönes Wochenende!
Matthias

**Comment by kolloch** [comment]
Wollte keine "offizielle" Release vor dem WE machen.

**Comment by howardzhang** [comment]
Hi @kolloch, Great. I will let you know if this issue occurs again.
And thanks for the quick fix.
