### ISSUE TITLE
enhancement: env var interpolation at deploy time

### ISSUE THREAD

**Issue by Kosta-Github** [mesosphere/marathon#1987]
I would like to use the docker `--hostname` option to set a hostname for the docker container, but would like to add the name of the node the container gets deployed to by env vars substitution/interpolation at deployment time, e.g.: `--hostname=my-service-${MESOS_NODE_HOSTNAME}` would result in `my-service-minion-001` on a mesos node `minion-001` and `my-service-minion-002` on a mesos node `minion-002`.

See also: https://github.com/mesosphere/marathon/issues/1791

**Comment by pchinmay** [comment]
marathon [doc](https://mesosphere.github.io/marathon/docs/native-docker.html) suggest passing hostname using parameters and priviledge flag sets to true.
But that does not work on latest version of mesos/marathon.

Any update when this should be available?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3328. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3328. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
