### ISSUE TITLE
Consolidate logging

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#1988]
Currently, we do not use logging consistently.

Some of our code uses log4j, other parts slf4j, other parts Akka logging.

We should probably

* use `slf4j` with the logback backend
* Configure akka to log via slf4j
* use appropriate adapters (log4j, ...) so that legacy libraries also ultimately log via logback

Furthermore, logging configuration should be appropriately documented.

**Comment by bobrik** [comment]
What I'd love to see is ability to grep for distinct offer processing lines. Right now lines look like this:

```
Sep 11 16:49:38 pewpew docker[25833]: [2015-09-11 16:49:38,358] INFO Offer [20150908-164039-319497226-5050-29034-O6855483]. Insufficient resources for [/pss/hhh/zedsg/shhr/bzz] (need cpus=2.0, mem=49152.0, disk=0.0, ports=(1 dynamic), available in offer:
```

Here offer is on the next line and it's not really convenient it tools like kibana.

**Comment by kolloch** [comment]
Related #1127

**Comment by kolloch** [comment]
Hi @bobrik, 

I am not sure what you are saying exactly and what solution you are suggesting. So feel free to clarify if I misunderstood that.

Generally, since our current logging isn't consistent, aggregating log statements across multiple lines for Kibana is hard. It should be reasonably easy to do once we consolidated the log format. You can do it, e.g. with logstash: http://logstash.net/docs/1.4.1/filters/multiline

I would rather not log all information for one offer on one line because that becomes rather unreadable.

**Comment by gkleiman** [comment]
Hi @kolloch,

I am not sure we can easily migrate to the `logback` backend, because some of our dependencies depend on the sl4j to log4j bridge (slf4j-log4j12):

```
> whatDependsOn org.slf4j slf4j-log4j12 1.7.5
[info] org.slf4j:slf4j-log4j12:1.7.5
[info]   +-org.apache.hadoop:hadoop-auth:2.4.1
[info]   | +-org.apache.hadoop:hadoop-common:2.4.1
[info]   |   +-mesosphere:marathon_2.11:0.12.0-SNAPSHOT [S]
[info]   |
[info]   +-org.apache.hadoop:hadoop-common:2.4.1
[info]   | +-mesosphere:marathon_2.11:0.12.0-SNAPSHOT [S]
[info]   |
[info]   +-org.apache.zookeeper:zookeeper:3.4.6
[info]     +-com.twitter.common.zookeeper:candidate:0.0.76
[info]     | +-mesosphere:marathon_2.11:0.12.0-SNAPSHOT [S]
[info]     |
[info]     +-com.twitter.common.zookeeper:client:0.0.70
[info]     | +-com.twitter.common.zookeeper:candidate:0.0.76
[info]     | | +-mesosphere:marathon_2.11:0.12.0-SNAPSHOT [S]
[info]     | |
[info]     | +-com.twitter.common.zookeeper:group:0.0.82
[info]     |   +-com.twitter.common.zookeeper:candidate:0.0.76
[info]     |     +-mesosphere:marathon_2.11:0.12.0-SNAPSHOT [S]
[info]     |
[info]     +-com.twitter.common.zookeeper:group:0.0.82
[info]     | +-com.twitter.common.zookeeper:candidate:0.0.76
[info]     |   +-mesosphere:marathon_2.11:0.12.0-SNAPSHOT [S]
[info]     |
[info]     +-com.twitter:util-zk_2.11:6.24.0 [S]
[info]       +-mesosphere:marathon_2.11:0.12.0-SNAPSHOT [S]
```

**Comment by kolloch** [comment]
You can usually [exclude dependencies](http://www.scala-sbt.org/0.13/docs/Library-Management.html#Exclude+Transitive+Dependencies) like this. 

It is strange that they depend on a concrete implementations. If I understood that correctly, all libraries should only depend on the slf4j interfaces and not on concrete implementations.

**Comment by gkleiman** [comment]
There's a ZK Jira for removing the dependency: https://issues.apache.org/jira/browse/ZOOKEEPER-1371, but it has been open since 2012 =(.

I will first create a PR consolidating on slf4j, then I'll try to change the backend replacing slf4j-log4j12.jar with log4j-over-slf4j.jar.

**Comment by gkleiman** [comment]
All logging is now done through slf4j with the log4j backend.

We'd like to switch the backend to logback, but ZooKeeper (started by our integration tests) depends directly on log4j classes not implemented by slf4j's log4j bridge.
