### ISSUE TITLE
Show Marathon UI version in about modal

### ISSUE THREAD

**Issue by aldipower** [mesosphere/marathon#1993]
The UI version should be visible in the about modal.

ACs
1. There should be a placeholder in the config. It schould be be replaceable by TeamCity, like %UI_VERSION%.
2. If %UI_VERSION% wasn't replaced by TeamCity, the version should come from the package.json with an added '-SNAPSHOT'.
Similiar like this:
```
version: %UI_VERSION% || "0.10.0" + "-SNAPSHOT"
```

**Comment by philipnrmn** [comment]
I can see this being really handy for bug reports.
