### ISSUE TITLE
marathon rpm does not allow running as non-root

### ISSUE THREAD

**Issue by InformatiQ** [mesosphere/marathon#1995]
for centos6 the script at /usr/bin/marathon is packaged with 750 permissions not allowing non-root users to execute it and the init script needs some modifications too to make marathon run as non-root user

**Comment by kolloch** [comment]
Thanks for reporting this.

We except contributions: https://mesosphere.github.io/marathon/docs/contributing.html

**Comment by InformatiQ** [comment]
where can i find the packaging scripts?

**Comment by kolloch** [comment]
Here: https://github.com/mesosphere/marathon-pkg/

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3254. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3254. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
