### ISSUE TITLE
Duplicable fields in app creation modal can send null values

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#1996]
- create an app from the UI
- add the parameters `1:2` and `3:4`
- delete the first row (`1:2`)
- hit submit

This will generate the following value for `container.parameters`:
`{parameters: [null, {key: "3", value: "4"}]}`

Note the extraneous `null` above. The correct JSON would be:
`{parameters: [{key: "3", value: "4"}]}`

The same case affects `container.docker.portMappings` and may affect `env` when PR #124 is merged.

**Comment by aldipower** [comment]
This is fixed in https://github.com/mesosphere/marathon-ui/pull/130 on-the-fly.
