### ISSUE TITLE
Marathon doesn't remove tasks which do not exist in Mesos

### ISSUE THREAD

**Issue by rukletsov** [mesosphere/marathon#1997]
I'm running a single Marathon instance in a docker container ("mesosphere/marathon:demo-0.9.2") on Mesos (via another Marathon). The current state is the following:
* Marathon UI reports a `sleep2` app with 300 / 0 (Tasks / Instances) and "Deploying" status
* These tasks have been previously killed and do not exist in Mesos any more.

I suppose Marathon sends Mesos kill requests and, as expected, receives `TASK_LOST` updates, which it doesn't process correctly. Here is the excerpt from the Marathon log:
```
[2015-08-13 13:49:52,687] INFO Received status update for task sleep.94b7cb71-41b4-11e5-9129-06c509a187f7: TASK_LOST (Reconciliation: Task is unknown) (mesosphere.marathon.MarathonScheduler$$EnhancerByGuice$$b9f91348:98)
[2015-08-13 13:49:52,688] INFO Finished processing status update for task sleep.94b7cb71-41b4-11e5-9129-06c509a187f7. Took 1 ms (mesosphere.marathon.MarathonScheduler$$EnhancerByGuice$$b9f91348:168)
[2015-08-13 13:49:52,688] WARN Couldn't post event for value: "sleep.94b7cb71-41b4-11e5-9129-06c509a187f7"
 (mesosphere.marathon.MarathonScheduler$$EnhancerByGuice$$b9f91348:134)
```
Note that task `sleep.94b7cb71-41b4-11e5-9129-06c509a187f7` is shown in MarathonUI is started.

P.S. I'm not 100% sure how I entered in the described above state, but I'll try to reconstruct the chain of events here, maybe it will provide some background. I had an app in marathon with some healthy tasks and some stuck in staging, then I killed the marathon scheduler, and killed the tasks on Mesos agent, restarted the Marathon, saw the app hanging around and asked Marathon to destroy it.

**Comment by kolloch** [comment]
Hi @rukletsov, this might be related to the demo code. It would be interesting if you experience similar problems with the regular 0.9.2 release (which might very well be). The effected code is very high on our "rewrite soon list".

https://github.com/mesosphere/marathon/issues/462

**Comment by aquamatthias** [comment]
This problem appears in the demo branch and is fixed there (see related PR)
