### ISSUE TITLE
Allow to specify custom Java binary location

### ISSUE THREAD

**Issue by zbzoch** [mesosphere/marathon#2018]
Marathon simply executes the default Java registered in system. There should be a possibility to specify custom JAVA_HOME, so you're able to choose a non-default JRE.

**Comment by gkleiman** [comment]
Thanks for creating the issue, we'll add it to our backlog.

**Comment by gkleiman** [comment]
This was fixed in 0d47bc1024ef8ab62f56ab586f1e09949deae128.
