### ISSUE TITLE
Replace util.serializedArrayToDictionary with object-path.set/insert()

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2027]
We are problably duplicating functionality [here](https://github.com/mesosphere/marathon-ui/blob/master/src/js/components/NewAppModalComponent.jsx#L125) as it can probably be rewritten using [objectPath.insert()](https://github.com/mariocasciaro/object-path#usage).

**Comment by pierlo-upitup** [comment]
ps sorry, @aldipower :(

**Comment by aldipower** [comment]
@pierlo-upitup Good idea! No need to say sorry.. ?

**Comment by pierlo-upitup** [comment]
Oops I meant Sorry @philipnrmn eheh! That's because we spent a couple hours of sound work on that function ;)

**Comment by aldipower** [comment]
This ticket is obsolete due to the refactoring of the application modal and could be closed.
