### ISSUE TITLE
Killing task not possible

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2029]
A message body writer for Java class scala.collection.immutable.Map$Map1, and Java type class scala.collection.immutable.Map$Map1, and MIME media type application/octet-stream was not found.

Steps to reproduce:
1) Start Marathon
2) Create 10 instances "Sleep 100"
3) Go to task list and select one task
4) Click "Kill"

Expected result: Task is killed without errors
Current result: Task is not killled (see stack trace)

[2015-08-18 14:14:23,924] ERROR A message body writer for Java class scala.collection.immutable.Map$Map1, and Java type class scala.collection.immutable.Map$Map1, and MIME media type application/octet-stream was not found.
The registered message body writers compatible with the MIME media type are:
*/* ->
  com.sun.jersey.core.impl.provider.entity.FormProvider
  com.sun.jersey.core.impl.provider.entity.MimeMultipartProvider
  com.sun.jersey.core.impl.provider.entity.StringProvider
  com.sun.jersey.core.impl.provider.entity.ByteArrayProvider
  com.sun.jersey.core.impl.provider.entity.FileProvider
  com.sun.jersey.core.impl.provider.entity.InputStreamProvider
  com.sun.jersey.core.impl.provider.entity.DataSourceProvider
  com.sun.jersey.core.impl.provider.entity.XMLJAXBElementProvider$General
  com.sun.jersey.core.impl.provider.entity.ReaderProvider
  com.sun.jersey.core.impl.provider.entity.DocumentProvider
  com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider
  com.sun.jersey.core.impl.provider.entity.SourceProvider$SourceWriter
  com.sun.jersey.server.impl.template.ViewableMessageBodyWriter
  com.sun.jersey.json.impl.provider.entity.JSONJAXBElementProvider$General
  com.sun.jersey.json.impl.provider.entity.JSONArrayProvider$General
  com.sun.jersey.json.impl.provider.entity.JSONObjectProvider$General
  com.sun.jersey.json.impl.provider.entity.JSONWithPaddingProvider
  com.sun.jersey.core.impl.provider.entity.XMLRootElementProvider$General
  com.sun.jersey.core.impl.provider.entity.XMLListElementProvider$General
  mesosphere.chaos.validation.JacksonMessageBodyProvider
  com.sun.jersey.json.impl.provider.entity.JSONRootElementProvider$General
  com.sun.jersey.json.impl.provider.entity.JSONListElementProvider$General
  com.sun.jersey.json.impl.provider.entity.JacksonProviderProxy
application/octet-stream ->
  com.sun.jersey.core.impl.provider.entity.ByteArrayProvider
  com.sun.jersey.core.impl.provider.entity.FileProvider
  com.sun.jersey.core.impl.provider.entity.InputStreamProvider
  com.sun.jersey.core.impl.provider.entity.DataSourceProvider
  com.sun.jersey.core.impl.provider.entity.StreamingOutputProvider
 (com.sun.jersey.spi.container.ContainerResponse:278)
[INFO] [08/18/2015 14:14:23.925] [marathon-akka.actor.default-dispatcher-5] [akka://marathon/user/MarathonScheduler/$a/$b] Killing 1 instances

Marathon version 0.10.0
Mesos version: 0.23.0

**Comment by gkleiman** [comment]
Thanks for reporting this.

We should also add an integration test in order to avoid regressions.

**Comment by meichstedt** [comment]
As for integration tests: I think it would make more sense to write generic tests; otherwise, we would have to test each method in order to make sure the correct annotations are added.

**Comment by gkleiman** [comment]
LGTM, but I'd like to have some tests.

Having a generic one that goes over all the endpoints and makes sure they return JSON and not crash would be very useful.

But I also think we need one that tries to delete/kill a task and checks that it is gone. The goal of #1644 was to have at least one integration test for every endpoint. I clearly missed this one, but it is never too late to add new tests =)

**Comment by meichstedt** [comment]
@gkleiman Let's create a generic solution in another scope – this one should quickly go into 0.10 for the next DCOS release. But in general, yes, this should be tested as well.
