### ISSUE TITLE
Make keyboard shortcuts discoverable

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2031]
There is currently no way of discovering the keyboard shortcuts. 

It would be good to have a simple help modal which lists all keyboard shortcuts. It should itself be available via the `?` shortcut.

**Comment by air** [comment]
:+1: Good examples:
- Github
- Gmail
- Trello

**Comment by philipnrmn** [comment]
Current shortcuts (originally posted in discussion over on #2033):

`esc` closes any open modal
` c ` opens the create modal
`g a` navigates to the Apps page
`g d` navigates to the Deployments page
`g v` shows the current UI version number
`⇧+,` shows the about modal

**Comment by pierlo-upitup** [comment]
@philipnrmn very cool idea – though hiding the keyboard shortcut legend behind another keyboard shortcut probably won't help noobs. How about adding an `info` section to our About modal?
