### ISSUE TITLE
Move edit configuration button to top of config pane

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2039]
The edit configuration button is at the bottom of the config pane. This feels hard to discover, especially when the configuration is complex and it can drop off the bottom of the screen:
![20150819-current-edit-button](https://cloud.githubusercontent.com/assets/2989362/9358204/13d2fa3e-468b-11e5-9c5e-c16da6641d1d.png)

I propose moving it to the top of the configuration pane, eg:
![20150819-suggested-edit-button](https://cloud.githubusercontent.com/assets/2989362/9358169/f39e0f92-468a-11e5-8fc3-e11e0764b323.png)

@aatumanova @air what do you think?

**Comment by aatumanova** [comment]
@philipnrmn nice idea, I like the placement. What do you think about rewording the button to "Edit Settings"?

**Comment by philipnrmn** [comment]
@aatumanova that sounds a lot better.

**Comment by air** [comment]
Absolutely move to the top.
I have three other thoughts:

1. Use of nouns. Maybe we can converge on a single noun for app config. Today we have AppDefinition, Configuration and Settings.
2. Do we need to make it clear that an Edit operation will create a new version, and redeploy the app? In the Edit modal the 'accept' button does a pretty good job, with the text 'Change and deploy configuration'. This is probably good enough. Is 'Redeploy app with these settings' clearer?
3. Are we using the button styles consistently? Some are outline and some are solid.

**Comment by aatumanova** [comment]
1. Agree! I move towards "Edit Configuration", since we use that word quite frequently.
2. An alert during the editing process would be helpful.
3. No they are not being used correctly. Solid button style is dominant, outline button style is secondary. In this case, I think the refresh and edit buttons should be in the outlined style.
