### ISSUE TITLE
Empty post body on event subscription callback

### ISSUE THREAD

**Issue by zsimpson** [mesosphere/marathon#2044]
I have requested a callback for marathon events using the /v2/eventSubscriptions?callbackUrl= endpoint.

It is correctly calling me back at the callback endpoint but the body of that POST callback is always empty.

It's totally possible that something is configured wrong but I've followed the docs and can't get a POST body.

Version installed from 0.9.0-1.0.381.ubuntu1404

**Comment by gkleiman** [comment]
Did you start Marathon with `--event_subscriber http_callback`?

It would help if you include the complete HTTP (including headers) that Marathon is doing and any relevant Marathon logs.

**Comment by zsimpson** [comment]
Thanks for asking for the headers.  Once I looked at those I saw that the content length was non-zero and I kept investigating and found that my express middleware was borking the json block.

So, no problem.  Sorry. Closing.
