### ISSUE TITLE
Tasks/Instances column rewording

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2047]
This is a spin-off issue from the discussion started [here](https://github.com/mesosphere/marathon-ui/pull/128#issuecomment-132838966)

Let's agree on what the Tasks/Instances column should be called and if we want to change the `1 / 2` value rows to be `1 of 2`.

<img width="1038" alt="screen shot 2015-08-20 at 10 41 00" src="https://cloud.githubusercontent.com/assets/1078545/9379445/8add1184-4729-11e5-9dfd-5ce1eb04f23c.png">

cc @aatumanova

**Comment by philipnrmn** [comment]
:+1: for  the 'Instances Running' solution proposed by @aatumanova

**Comment by pierlo-upitup** [comment]
and :+1: for the `of` instead of `/` !

**Comment by aatumanova** [comment]
To @air's point from the previous PR, we use the term "tasks" more frequently than instances. What do you all say to the wording "Tasks Running"?

**Comment by air** [comment]
Consistency would be good.

- The Marathon AppDefinition JSON uses `instances` - to mean, how many instances of this app do you want?
- A `Task` is a specific Mesos term - a thing run by an Executor.

Strawman: Alice wants to work with her `App`, deploying a certain number of `Instances`. As an implementation detail, the Mesos stack will create `Tasks` (each with a `Task ID`) to track those Instances. So in *most* cases, Alice wants to talk about Instances. When drilling into detail, we can introduce the Task concept (e.g. when looking at Task IDs).

Advantages: Our Alice workflow depends less on Mesos knowledge/specifics.

Thoughts?

**Comment by pierlo-upitup** [comment]
Just to add a little extra context, @aldipower told me this:

> A task is a running instance.

I really like his concise definition as it makes things a lot clearer to me: an `Instance` is, essentially, the app definition. A `Task` is when that definition gets staged and then is running.

**Comment by air** [comment]
Thanks PG. Let's prefer `Instances` wherever possible. Advantages:
- It expresses that all of 'these things' - e.g. sleepr instances above - **are the same**. They are all **instances** of a single AppDefinition.
- It matches the AppDefinition JSON. You send JSON talking about `instances`, and then you see `Instances Running` on the UI. That makes sense.

We should use `Task` only when talking about `Task ID` and so forth.

**Comment by leemunroe** [comment]
Following up on this to help clarify things. Are we good with using "instances" except where we talk specifically about mesos tasks?

<img width="903" alt="instances" src="https://cloud.githubusercontent.com/assets/15963/11380625/1d041170-92ac-11e5-87e4-bdb67d8ae16c.png">

**Comment by pierlo-upitup** [comment]
cc @aquamatthias

**Comment by aquamatthias** [comment]
@pierlo-upitup  I agree: from Marathon's point of view is an instance of the application definition. The Mesos term is Task. A detail view of the Task should use that term. Every user that also use the MesosUI will then understand the relationship.
