### ISSUE TITLE
Advanced JSON editing mode in app modal

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2049]
As a user, I want to create an app using [all fields](http://mesosphere.github.io/marathon/docs/rest-api.html#post-v2-apps) in its definition from the GUI. 

Currently the app modal does not expose all the fields available in the API. This means that a user cannot, for example, specify `forcePullImage=true` on a docker application. 

The modal would become very unwieldy if all fields were available to be edited. We should therefore provide an advanced mode which allows the user to deal directly with the JSON app definition. 

ACs
 - a tab allows the user to switch between the form and the JSON editor
 - switching between the two tabs preserves the latest edits in either mode
 - the editor need only check for JSON validity

**Comment by philipnrmn** [comment]
Consider adding 'copy to clipboard', possibly upload and download buttons.

**Comment by mwasn** [comment]
@leemunroe What do you think about this issue?

**Comment by kolloch** [comment]
I can say that I would really appreciate that feature.

**Comment by mindscratch** [comment]
I'd like to note, if I submit an app via JSON (which includes `"forcePullImage": true`) and then edit it via the UI, the `forcePullImage` reverts to false. So adding all options to the UI would be great.

**Comment by leemunroe** [comment]
Sounds great. We have redesigning the create view in the backlog `MARATHON-187` - wondering if it's worth exploring this hand in hand so we don't duplicate work.

**Comment by philipnrmn** [comment]
@gkleiman pointed out to me that offering `requirePorts` in the UI would significantly improve the utility of the `ports` field, thought I'd tack that on to this story instead of creating a story for a new field in the modal.

**Comment by pierlo-upitup** [comment]
Related for possible implications https://github.com/mesosphere/marathon/issues/3087

**Comment by mgummelt** [comment]
Glad that this is happening.  I updated a docker image, so I need to set forcePullImage on the app.
