### ISSUE TITLE
Add events tab in app detail view

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2050]
As a user, I want to see what's happening to my application tasks right now. 

We should add a tab in the app detail view which displays events relating to the current app as they occur.  We should filter the [events stream](https://mesosphere.github.io/marathon/docs/rest-api.html#get-v2-events) by `appId` to get the stream data. 

We should investigate how to display these messages in a human-friendly format which is still useful for debugging. 

We should derive ACs by answering the following questions:
- What fields in the JSON response are relevant to the user?
- How big should the buffer be? 1000 lines? Two minutes?
- Should these lines be filterable, and if so how?

**Comment by philipnrmn** [comment]
Ideally we would have server-side filter per #654; for the moment we will filter in the browser.

**Comment by aatumanova** [comment]
@cleverroffey, check this out!

**Comment by pierlo-upitup** [comment]
Also see mesosphere/marathon#1784

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3226. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3226. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
