### ISSUE TITLE
Marathon archived resources

### ISSUE THREAD

**Issue by johscheuer** [mesosphere/marathon#2051]
Hey,

I'm using Marathon 0.10 on Mesos 0.23.0 which runs on CentOS 7.1. I try to run a very simple app like this:

```json
{
  "id": "hello-repacked", 
  "cmd": "chmod u+x app/hello.sh && app/hello.sh",
  "cpus": 0.1,
  "mem": 10.0,
  "instances": 1,
  "uris": [
        "http://192.168.32.63:9000/app.zip"
    ]
}
```

The task never start because of this strange error:
```
I0820 13:25:12.635138 17396 fetcher.cpp:441] Fetched 'http://192.168.32.63:9000/app.zip' to '/tmp/mesos/slaves/20150807-114948-1059104960-5050-714-S7/frameworks/20150807-095424-1059104960-5050-2095-0000/executors/hello-repacked.e2e522c4-473e-11e5-bffd-0242f7fc7e39/runs/d0d165b0-2bd4-41a4-a271-fa7c2b19a3f5/app.zip'
I0820 13:25:12.767943 17393 exec.cpp:132] Version: 0.23.0
I0820 13:25:12.776345 17400 exec.cpp:206] Executor registered on slave 20150807-114948-1059104960-5050-714-S7
chmod: cannot access âapp/hello.shâ: No such file or directory
```

Why are there an â at the beginning and at the end? I also tried this with tar.gz which results in the same error message.

**Comment by gkleiman** [comment]
Could you please get the app definition from /v2/apps/hello-repacked and check whether there are any strange chars in the cmd attribute?

**Comment by johscheuer** [comment]
http://pastebin.com/hQJu1zER I couldn't find any strange chars

**Comment by gkleiman** [comment]
I tried to reproduce this using a tar.gz on OS X, but everything works as expected.

**Comment by johscheuer** [comment]
You are right the problem was that the unpacked file was in ./ and not in a subdir "app". Sorry for the false alarm but I was irritated by the "â".

Thanks for your help! :+1: :)
