### ISSUE TITLE
Consider splitting app modal into two: dockerised and non-dockerised

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2052]
As a user, I want the simplest modal possible so that I am not confused by extraneous fields. 

Unfortunately the app creation API is quite complex. There are several docker-specific fields, and there are also several fields whose meaning changes when a docker image is specified, eg `command`. 

There are also conflicts between fields such as `ports` and `container.docker.portMappings`, where one overrides the other. 

A simple solution to this would be to split the app creation route depending on whether the user intends to create a dockerised app or not. 

Question: 
- is it worth patching the app creation modal in this way, or should we look for a longer-term solution?
- if we want to proceed, should we have two distinct modals, or offer a 'wizard' guided selection?

**Comment by philipnrmn** [comment]
Would be interested to hear from @air and @aatumanova on this. Might also be of interest to @gkleiman and @kolloch

**Comment by philipnrmn** [comment]
I was reminded of this issue whilst implementing the suggestions in https://github.com/mesosphere/marathon/issues/950#issuecomment-127789678. Adding a `Docker command` field as suggested there confused the process, as the original `command` field would become redundant as soon as the docker-specific command field is filled.

**Comment by air** [comment]
I think dedicated modals would help a lot in reducing cognitive load.
e.g.
1. Click Create
1. Click Docker
1. Fill in fields specifically designed to capture Docker config.

We likely need a good term for 'non-Docker' apps. Mesos native app? Shell app? Bash app?

**Comment by junneyang** [comment]
native app
docker app
-^^-

**Comment by kolloch** [comment]
I think that one (unfortunately) also has to distinguish between docker apps with host networking and bridge networking since different fields are used in this case. 

Other than that I would like different fields based on the "type" of an app. I do not like the idea of a multi-step wizard, though, I would rather have one create dialog which has a drop down field for the "type" as top-most thing. It should remember the last "type" I have chosen, optimally. You should be able to switch types and data should be preserved if possible.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3064. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3064. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
