### ISSUE TITLE
Expose API calls to user

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2053]
As a user, I want to see each API call the GUI makes so that I can discover new features and automate my tasks easily. 

In Chrome developer tools, it's possible to track each API call and copy it as a `curl` command. It would be really cool to expose the outcome of user actions such as app creation, editing and scaling to the user in a similar manner. 

This is very much a power-user feature and should not be visible by default. 

Prior art: http://i.ytimg.com/vi/VaHdDNDx_iA/maxresdefault.jpg

**Comment by philipnrmn** [comment]
Possibly of interest to @lloesche :)

**Comment by philipnrmn** [comment]
Suggested keyboard shortcut: ``` ` ```

**Comment by pierlo-upitup** [comment]
Backtick is a bit tricky in certain keyboard layouts (i.e. Italian). Maybe "/"?

**Comment by philipnrmn** [comment]
Time to think about i18n?

**Comment by philipnrmn** [comment]
Ref: Google Compute Engine 'REST Version' @air

**Comment by air** [comment]
@philipnrmn's reference: Look at the ghosted modal in the background, at the very bottom. In the screenshot I've just clicked `Equivalent REST` to see my filled-out fields represented as a REST call.

![pasted image at 2015_08_14 09_41](https://cloud.githubusercontent.com/assets/18724/9841848/5a67c2f8-5a5a-11e5-90c7-7ee41a5c5552.png)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2738. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2738. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
