### ISSUE TITLE
Docker indicator in app list

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2054]
As a user, I want to see which of my apps are dockerised at a glance. 

It should be possible to differentiate between dockerised and non-dockerised applications from the app list.

**Comment by philipnrmn** [comment]
cc @aatumanova @air

**Comment by aatumanova** [comment]
@philipnrmn would adding a "container type" column be a good solution to this problem 

http://cl.ly/image/1O0l0L23062v

The three types currently possible are: docker, cgroup, and rocket.

cc: @ashenden

**Comment by ashenden** [comment]
I like the idea of distinguishing visually which apps are containers, though I'm not sure a dedicated column is the best solution, as it will result in empty cells for things that are not docker containers.  Consider, columns should by and large be common across all the objects in the list.  Instead, thing about how you could label an app to communicate it's a container.

**Comment by air** [comment]
I think we talked about using the 'app' icon (hexagon?) to represent one of the three container types.

**Comment by aatumanova** [comment]
@air that is right! check out the latest designs on invision.

**Comment by philipnrmn** [comment]
This is fixed in a branch, but not yet merged to master: mesosphere/marathon-ui#329

**Comment by orlandohohmeier** [comment]
As discussed in #2525, it seems that users don't see any value in distinguishing/filtering applications by type. We will therefore remove the filter and icons introduced in mesosphere/marathon-ui#286 and  mesosphere/marathon-ui#329.
