### ISSUE TITLE
Edit App causes reset of ports assigned on save

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2058]
@air reports:

> I edited the settings of `/frontend/marathon-ui` to add a single env var. After redeploy the app has no port assigned (so it's unaccessible).

**Comment by air** [comment]
I rolled back to the previous config using 'Apply these settings' in the history. This got me the port back, but the app returns 404.

**Comment by aldipower** [comment]
I can reproduce this. If the collapsible panel is closed the value from that won't be applied..
