### ISSUE TITLE
Urgent: Firefox bug #547718 and Marathon 204 responses

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2062]
Today @aldipower, @philipnrmn and me investigated the following scenario:

sending `DELETE` requests to the `/v2/queue/:appId/delay` (which trigger a `204` response) causes [a known bug in Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=547718) which prevent any further ajax requests from working.  

As [described here](https://groups.google.com/forum/#!topic/mithriljs/1unmja9hfmE), the workaround for this bug (unfortunately yet to be solved) is to set the response type header to "text" on the server.

@meichstedt : are there other 204 responses worth checking? This might obviously affect other endpoints too.

This is a very urgent issue, as it blocks Firefox users after the first failure.

**Comment by pierlo-upitup** [comment]
We have tried the following with @gkleiman and @meichstedt: 

in `src/main/scala/mesosphere/marathon/api/v2/QueueResource.scala` :+1: 
- change the `resetDelay` response from `noContent` (204) to `ok` (200)
- add a `Json.obj("ok" -> 1)` response to the `ok()` method
- add an `@Produces(Array(MarathonMediaType.PREFERRED_APPLICATION_JSON))` annotation
- add an `@Produces(Array(MediaType.TEXT_PLAIN))` annotation

we tried all combinations of the above, and while the `no element found` error is gone, we now are getting another js error: `TypeError: currentQueue is null`. 

We should:
- @gkleiman: fix the `no element found` error on the service layer by picking the most appropriate response for this case 
- @aldipower @philipnrmn me: investigate and fix the TypeError

**Comment by pierlo-upitup** [comment]
PS `resetDelay` is the only response using a 204

**Comment by aldipower** [comment]
@pierlo-upitup @philipnrmn 
Thank you for investigating into this.
I think the ```TypeError: currentQueue is null. ``` is directly related to this issue and will be solved together with ```no element found```. They always appear together.

**Comment by pierlo-upitup** [comment]
Nope, unfortunately that's not the case! We managed to get rid of `no element found` but not the `TypeError`.

**Comment by aldipower** [comment]
OK, having a hint for the ```TypeError: currentQueue is null. ```.
It appears sometimes after a alert box opened, which is here the case..
```javascript
Util.alert("Delay reset succesfully");
```
..native alert boxes are interrupting the JavaScript execution!
http://stackoverflow.com/questions/12201290/why-does-javascript-dialog-boxes-alert-confirm-stop-page-redrawing
It seems that things from React or the Ajax requests got confused by this interruption.

If I remove the alert message the error goes away..

This _doesn't_ do the trick, it still interrupts:
```javascript
setTimeout(function () {
  global.alert.apply(null, args);
}, 1);
```

Under this aspect a replacement of the native dialog boxes with our own ones looks much more necessary.
@pierlo-upitup  What was the issue number for this? Can not find it..

**Comment by philipnrmn** [comment]
@aldipower we didn't create an issue for custom dialogs; I just did so - see #2071

**Comment by philipnrmn** [comment]
NB: I was unable to reproduce this issue in the latest Developer Firefox, so I suspect a bugfix on the Firefox side is imminent.

**Comment by philipnrmn** [comment]
Tested and working since the resolution of #2071. There is still a `no element found` warning in the console, but subsequent network requests are resolved. 

Marathon 0.10 above, Marathon 0.11-snapshot (latest) below:
![2062-working](https://cloud.githubusercontent.com/assets/2989362/9494364/d3216590-4c05-11e5-9821-2f384f12d0a3.png)

**Comment by pierlo-upitup** [comment]
Awesome work @philipnrmn @aldipower :+1: 

Regarding the service part and the `no element found` issue: what do you think about "fixing" the response on the service layer, @gkleiman @meichstedt ? (see top of the post for info)
