### ISSUE TITLE
Add integration with Netflix Fenzo

### ISSUE THREAD

**Issue by mindscratch** [mesosphere/marathon#2063]
Netflix open sourced [Fenzo](http://techblog.netflix.com/2015/08/fenzo-oss-scheduler-for-apache-mesos.html) which has some promising features. It looks like schedulers can integrate with it or perhaps create a plugin to work with it.

It would be nice if Marathon added integration with Fenzo.

**Comment by ashwanthkumar** [comment]
+1

**Comment by xiaods** [comment]
+1

**Comment by worstadmin** [comment]
+1

**Comment by airwulf** [comment]
+1

**Comment by xiaods** [comment]
we need analysis the implement details on how implement this feature? if it not feasible, we don't waste the time to add + to this issue.

**Comment by phunghv** [comment]
+1

**Comment by raghu999** [comment]
+1

**Comment by bowlofstew** [comment]
+1

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2703. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
