### ISSUE TITLE
In Marathon 0.8.2 POST /v2/apps returns 201 when the app doesn't necessarily exist

### ISSUE THREAD

**Issue by ikinsey** [mesosphere/marathon#2070]
In Marathon 0.8.2 POST /v2/apps returns the following and seems to create and start the app correctly after a very short delay:

&{Code:201 Apps:[] App:<nil> Versions:[] Tasks:[] DeploymentId:a2deb836-cf20-4217-a527-37a86c4ed208}

**However**, if a GET /v2/apps/<id> is sent immediately after receiving that 201, *sometimes* the GET will return 404: {"message":"App '/666exp1env--666exp1--666exp1--93757a' does not exist"} implying that resources aren't always ready to be accessed when a 201 is served.

Somewhat related: https://github.com/mesosphere/marathon/issues/2069

**Comment by meichstedt** [comment]
Thanks for reporting this! In fact, we're aware of that problem, and there have been recent changes to the master that should prevent this. This will not be solved for 0.8.2, but it would be nice if you could check out the 0.11.x series as soon as they're out.

**Comment by mwasn** [comment]
Won´t fix in this version.
