### ISSUE TITLE
Replace native alert, prompt and confirm with custom modals

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2071]
Per @aldipower's comment [here](https://github.com/mesosphere/marathon/issues/2062#issuecomment-133461731), we should no longer use native `alert`, `prompt`, and `confirm` calls. 

- [x] custom `alert`
- [x] custom `prompt`
- [x] custom `confirm`

**Comment by aldipower** [comment]
Perhaps @pierlo-upitup likes this.. ;)
