### ISSUE TITLE
Doc bug - with portMappings, ports is unnecessary

### ISSUE THREAD

**Issue by swartzrock** [mesosphere/marathon#2074]
1) go to https://mesosphere.github.io/marathon/docs/rest-api.html#post-v2-apps
2) the "ports" section appears to use the ports from the container. However, this is confusing, as these will actually be used on the host.

Would it be better to just remove the "ports" entry from this example?

**Comment by kolloch** [comment]
The example shows most possible fields in the request. That doesn't mean that it makes sense to specify them all at once.

The API is especially confusing regarding ports, so additional (focussed) examples would make sense.

Maybe in a different page though with a link "look here for some examples".

Feel free to make a concrete suggestion with a pull request:

https://mesosphere.github.io/marathon/docs/contributing.html

**Comment by kolloch** [comment]
Just some meta-info:

* portMappings are only used with docker BRIDGE networking
* for all other cases use ports

**Comment by sascala** [comment]
http://mesosphere.github.io/marathon/docs/ports.html
