### ISSUE TITLE
document HOWTO execute a blue/green deployment

### ISSUE THREAD

**Issue by air** [mesosphere/marathon#2075]
Part of the Marathon API was explicitly added to make blue/green deployment easier: https://mesosphere.github.io/marathon/docs/rest-api.html#post-v2-tasks-delete

The process was documented internally by @brndnmtthws recently - translate that process into a page in the Marathon docs.

**Comment by kamilchm** [comment]
looks promising :+1:

**Comment by mwasn** [comment]
Currently in review for Marathon docs and Mesosphere blog
