### ISSUE TITLE
Health Check Timeout Never Resolves to Healthy or Unhealthy Service

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2078]
The HDFS service (and suspect any other service) does not reliably reach either a Healthy state or an Unhealthy state despite staying up beyond it's health check grace period. Sometimes this occurs on initial startup of the scheduler and sometimes after restarting the node on which the scheduler is running.
In order to reproduce reliably, simply reduce the health check timeout to 1s. It looks like any time the health check times out the service will remain in the "Idle" state. Marathon logs indicate that a health check actor is "added" and "started". However no health events are received as in other services.
Any time the healthcheck exceeds it's timeout it never reaches either a Healthy state or an Unhealthy state. It also looks like after this initial timeout failure, it never retries the health check. I often see cases where the HealthCheck nearly simultaneously times out and succeeds in its health check, and yet is never listed as Healthy.
This fails HDFS tests all the time. Even though HDFS is up and functioning and its health test passes when attempted, Marathon never lists the Service as healthy.

See #MARATHON-280

**Comment by jolexa** [comment]
"Any time the healthcheck exceeds it's timeout it never reaches either a Healthy state or an Unhealthy state. It also looks like after this initial timeout failure, it never retries the health check "

I think this is what I was facing in #2179

**Comment by gkleiman** [comment]
Closing this, since it is a Mesos bug and there is nothing for us to do: https://issues.apache.org/jira/browse/MESOS-3479
