### ISSUE TITLE
App constraints handling in create/edit dialog broken

### ISSUE THREAD

**Issue by meichstedt** [mesosphere/marathon#2079]
Affects: latest build

Steps to reproduce:
- open the create dialog and fill in a simple app definition
- add an invalid constraint, e.g. `foo`

_Result: no request is posted, but no ui-error is shown either_

- change the constraint to `hostname:unique` (considered invalid)

_Result: Error: App creation unsuccessful. Check your app settings and try again._

- change the constraint to `hostname:UNIQUE` (which actually is valid)

_Result: the app is created (I sometimes had to press `create` twice, though)_

- now, open the app configuration and inspect the constraints section.

_Result: the constraint is rendered as `hostname,UNIQUE`. This cannot be saved and does not show errors when hitting `create`_

**Comment by philipnrmn** [comment]
Entering a space in the `URIs` field causes the value `uris=[""]` to be sent, which delays the app forever.
