### ISSUE TITLE
Document the Waiting/Delayed status values

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2084]
Document the new Waiting/Delayed status values in Marathon doc explaining what that means and how to configure it.

**Comment by alon-argus** [comment]
Can someone please comment here in the meanwhile and say in a few words what they mean?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2750. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
