### ISSUE TITLE
Use icons to communicate nature of alerts

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2088]
I suggest using icons that communicate the nature of the alert, rather than the marathon logo.

I would divide these alerts into the following categories: success, warning, informational, or error.

For example, here is what a "Not Scaling" alert, which I consider an error alert, might look like: http://cl.ly/image/3M0h3A2i2o0c

The word "error", icon and red color clearly communicates to the user that something has gone wrong.

For "Delay reset succesfully" we will want a different icon — something green and with a checkmark for — to communicate to the user that everything went as planned. And so on.

For background, see https://github.com/mesosphere/marathon-ui/pull/154#issuecomment-134668257

**Comment by leemunroe** [comment]
@philipnrmn Could you upload your example alert again? Looks like it has disappeared.

**Comment by pierlo-upitup** [comment]
Closing this as it's superseded by the new redesigned modal dialogs.
