### ISSUE TITLE
Remove refresh button

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2097]
In several places in the app detail page there is a refresh button. It should not be necessary to provide one, since the UI polls regularly. 

Some error messages reference it, eg
`Error fetching deployments. Refresh to try again`. 

It would be cleaner to add a refresh link to the error messages and remove the refresh button completely.

**Comment by aldipower** [comment]
:+1:

**Comment by leemunroe** [comment]
Bump.

Is it safe to remove these yet?

![image](https://cloud.githubusercontent.com/assets/15963/12151038/e631ae3c-b461-11e5-8995-d1ce8e33bad8.png)

![image](https://cloud.githubusercontent.com/assets/15963/12151043/efc2fe74-b461-11e5-91c1-d9db0cb3f5e3.png)

![image](https://cloud.githubusercontent.com/assets/15963/12151050/f782c1c6-b461-11e5-9cc4-1323db2d741c.png)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3180. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
