### ISSUE TITLE
Error message breaks modal layout in Firefox

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2100]
- Create an application
- Start a large deployment
- Attempt to edit application whilst deployment is ongoing
- Buttons overflow modal

![20150826-broken-modal](https://cloud.githubusercontent.com/assets/2989362/9497650/48ca72fe-4c16-11e5-9542-cad8201cdf01.png)

**Comment by aldipower** [comment]
Only for interests, I _can't_ reproduce this with my Firefox 38 under Xubuntu.
