### ISSUE TITLE
/logging endpoint undocumented

### ISSUE THREAD

**Issue by mgummelt** [mesosphere/marathon#2103]
My deploy is stuck.  I see in the marathon log that marathon is getting an offer (1) from the master, but declining it.  The master log shows the offer details, and the numbers all look sufficient to deploy the task.  So now I don't know why marathon is rejecting.  It would be helpful if the marathon logs included the rejection reason.

**Comment by mgummelt** [comment]
Ah, I was just told that the `/logging` endpoint should let me up the logging level.

Would be nice if this were documented.  Changing the issue title...

**Comment by jolexa** [comment]
Or, is it better to document it in chaos (https://github.com/mesosphere/chaos/blob/master/README.md#built-in-endpoints) and then link from the marathon docs there?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3522. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
