### ISSUE TITLE
Refactor the application create/edit modal data handling

### ISSUE THREAD

**Issue by aldipower** [mesosphere/marathon#2105]
The data handling structures of the application modal for creating and editing the application configuration are in a bad and incomprehensible condition.

We need the following on a central and meaningful place:
- [ ] Function to transform the mod_e_l in the direction of the mod_a_l form input attributes
- [ ] Function to transform the mod_a_l form input attributes to the application mod_e_l structure
- [ ] Central and reusable application modal validation that is relational to the form attributes, but validating the mod_e_l itself
- [ ] Collapsible panels that are treated correctly even if they are closed
- [ ] Let the code be expressive

**Comment by aldipower** [comment]
https://github.com/mesosphere/marathon-ui/pull/158

**Comment by pierlo-upitup** [comment]
https://github.com/mesosphere/marathon/issues/2148

**Comment by pierlo-upitup** [comment]
Also see https://github.com/mesosphere/marathon/issues/2038

**Comment by mwasn** [comment]
Please check whether behaviour as described in  https://mesosphere.atlassian.net/browse/MARATHON-300 is fixed with refactoring. Otherwise create a new bug and update Jira issue.

**Comment by aldipower** [comment]
@mwasn This is fixed with this refactoring in 0.12.0. The constraints field isn't empty, after an error on the cmd-field.
Please don't refer to links that are not opened to everybody, thank you.
