### ISSUE TITLE
ES6 classes for React components

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2106]
With Babel in our toolchain, we have the option of moving towards ES6 classes for our React components. 

This could either be done as an one-off refactor, or incrementally starting with new components and reworking others as the need arises. 

@aldipower and @pierlo-upitup, what's your opinion on the value of proceeding with this?

**Comment by aldipower** [comment]
:+1: 
I would like to start with a one-off refactoring to have a clean base and don't mix the things up.

Only thing that scares me a bit is the changed context binding of ```this``` which isn't done automatically anymore in the react classes. This can lead to a lot of unrecognized errors while refactoring.
http://babeljs.io/blog/2015/06/07/react-on-es6-plus/

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3267. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
