### ISSUE TITLE
App detail view refresh button is inconsistent

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2116]
Since the introduction of the `Edit` button on the app config page, the Refresh button appears on the left in the overview pane and on the right in the Config and Debug panes. Additionally, it uses a different button type in each place. 

- [x] Make button style consistent
- [ ] Make button placement consistent

**Comment by philipnrmn** [comment]
Unfortunately, moving the refresh button to the right interferes with pagination and leaves a gap on the left. We should just update the style for the moment and find a more complete solution in 0.12.

**Comment by pierlo-upitup** [comment]
Note to ourselves: it's always a good idea to post screenshots to illustrate things like these – makes understanding the issue a lot quicker ;)
