### ISSUE TITLE
Clearing the last item in a duplicable list

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2120]
Background: https://github.com/mesosphere/marathon/issues/950#issuecomment-127789678
>  decrease opacity to 50% on the "(–)" icon when editing the last remaining row of a duplicable set of values (disabled state)

This request was implemented in mesosphere/marathon-ui#162 but is now slated for reversion because it disabled useful functionality, *viz*. removing the last environment variable in the list without manually clearing the text fields. 

We should find a solution that makes it clear to the user that the last field cannot be removed from the list but retains the ability to clear the last field when it is populated. 

@aatumanova @air what is your opinion here?

**Comment by aldipower** [comment]
We could dimm the button, if both row fields are completely empty.
If there are values in the row, don't dimm, because I probably want to remove this values.

**Comment by aatumanova** [comment]
@philipnrmn can you provide a screenshot please? I don't see any dimming on marathon-latest.

**Comment by philipnrmn** [comment]
Hey @aatumanova, you won't see it because although it was implemented, it was then [reverted](https://github.com/mesosphere/marathon-ui/pull/165), hence this issue. 

Here's a video of how it looked:
http://cl.ly/2h1A2z2M2X0X

**Comment by aatumanova** [comment]
Thanks for the video @philipnrmn!

Here's an idea for how to make it obvious that when there is a single row, it cannot be removed — but the contents of the row can be cleared. Thoughts?

Single row: http://cl.ly/image/1Z142b0R211W
Two rows: http://cl.ly/image/2h3V3d1K2d3A
Quadruple rows: http://cl.ly/image/0E0f1s0D222a

cc @aldipower @ashenden

**Comment by pierlo-upitup** [comment]
@aatumanova i really like the (x) for the last remaining row case, but why break the line for the (+) button?

**Comment by aatumanova** [comment]
@pierlo-upitup thought was:(+) after the list feels like a more natural placement, because this is where the new row will appear.

**Comment by air** [comment]
The `X` is good.

I was confused by two different button colours: white for the `X` but green for the `+`.

**Comment by aatumanova** [comment]
@air reasoning for the green was that it's an adding action, so more "positive". Green is visually used for positive actions — success, healthy, good.

That said, we're changing colors as I speak in the new designs for the epics Chad and I are working through, so I would suggest using white for the (+).

**Comment by philipnrmn** [comment]
Fixed in mesosphere/marathon-ui#95
