### ISSUE TITLE
Uniqueness blocks deployment even with minimumHealthCapacity=0

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#2124]
Marathon 0.10.0, Mesos 0.23.0, single slave `172.16.91.128"`. The following application is able to start, but you cannot restart it, even though `minimumHealthCapacity` set to `0` permits Marathon to kill existing task. If you drop `["hostname", "UNIQUE"]`, restarts work as expected.

```json
{
  "id": "/test",
  "cmd": "sleep 1800",
  "instances": 1,
  "mem": 16,
  "cpus": 0.1,
  "env": {
    "v": "3"
  },
  "minimumHealthCapacity": 0,
  "constraints": [
    ["hostname", "UNIQUE"],
    ["hostname", "CLUSTER", "172.16.91.128"]
  ]
}

```

I also don't understand why #689 states that with 3 nodes you have to set `minimumHealthCapacity` to  `0.3` to update anything. With anything above 2/3 (0.66) Marathon should be able to kill one instance and start new one at the same host.

**Comment by pierlo-upitup** [comment]
@bobrik shouldn't the `minimumHealthCapacity` field be under `upgradeStrategy` in your app definition? 

See https://mesosphere.github.io/marathon/docs/rest-api.html#upgradestrategy

**Comment by bobrik** [comment]
Yep, my mistake. Is there an issue to warn users about unknown fields in app definitions? I'd love to use "strict" mode for deployment when apps with extra fields are rejected.

**Comment by pierlo-upitup** [comment]
We are thinking about something along those lines – thanks for your input!

**Comment by gkleiman** [comment]
@bobrik I've also been thinking about a strict mode for a while.

So I just created the following issue: #2164 - Add a "strict" mode.

**Comment by bobrik** [comment]
:+1:
