### ISSUE TITLE
cgroup question regarding number of cpu's and hard/soft limit

### ISSUE THREAD

**Issue by apuckey** [mesosphere/marathon#2125]
I'm not sure this is the correct place for this but its a fairly simple question,

If i supply an app with 0.1 cpu and its the only container running on a mesos-slave does it get "hard" limited to 0.1 by default or is this a "soft" limit and it will burst to available cpu.

If its the later then if there are more containers running but not using cpu will it still burst and if every container is using cpu will it then grant shares based on the number of cpu's specified in the config?

Having trouble finding concrete documentation on this anywhere so some help would be appreciated :)

**Comment by meichstedt** [comment]
Hey Antony,
Marathon is only forwarding the information on limits for a process. cgroups isolation is implemented in the mesos slave.

AFAIK, there is no hard limit if there is plenty CPU available, meaning that your process can go crazy if there's nothing else going on. Please head for the [mesos community](http://mesos.apache.org/community/) to ask for implementation details about what exactly happens to processes with arbitrary cgroups limitations when a need for throttling arises. An educated guess would be that the configured CPU limit will be enforced, as this configuration is the basis for ressource scheduling.

Best regards
Matthias
