### ISSUE TITLE
UI: Add optional field for "user" in app definition

### ISSUE THREAD

**Issue by jolexa** [mesosphere/marathon#2127]
Since #395 was fixed, marathon accepts an optional user entry in the app definition to run as. It is possible to pass this in via the API, but not the UI. This is a request to add the field to the UI as well.

**Comment by pierlo-upitup** [comment]
Hi @jolexa, thanks for the feedback. 

We are going to evaluate the possibility of adding the user field to the app creation form. 

cc @air @aatumanova
