### ISSUE TITLE
Do not reexpose EntityRepository API in *Repository interfaces

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#2129]
The `EntityRepository` interface exposes methods that help to create different repositories by shouldn't be reexported. For example, the `AppRepository` extends `EntityRepository` and thus exposes methods like `def currentVersion(id: String)` which relate to the string variant of the `PathId`. This method is helpful to implement the AppRepository but all interactions with the AppRepository should specify the `PathId` instead.

Therefore, instead of extending an `EntityRepository` an `AppRepository` should use an appropriate `EntityRepository` internally.

**Comment by jasongilanfarr** [comment]
Persistence API doesn't do this and entity store is going away.
