### ISSUE TITLE
Create a health checks panel in the application creation/edit modal dialog

### ISSUE THREAD

**Issue by aldipower** [mesosphere/marathon#2131]
In the application modal dialog I should be able to add and edit multiple health checks.

We could do this in a collapsible panel like the DockerContainerSettings.

There are 3 types of health checks with different settings (corrected, see below).

```javascript
"healthChecks":
[
// HTTP
  {
    "path": "/api/health",
    "portIndex": 0,
    "protocol": "HTTP",
    "gracePeriodSeconds": 300,
    "intervalSeconds": 60,
    "timeoutSeconds": 20,
    "maxConsecutiveFailures": 3,
    "ignoreHttp1xx": false,
  },
// TCP
  {
    "portIndex": 0,
    "protocol": "TCP",
    "gracePeriodSeconds": 300,
    "intervalSeconds": 60,
    "timeoutSeconds": 20,
    "maxConsecutiveFailures": 0
  },
// COMMAND
  {
    "protocol": "COMMAND",
    "command": { "value": "curl -f -X GET http://$HOST:$PORT0/health" },
    "gracePeriodSeconds": 300,
    "intervalSeconds": 60,
    "timeoutSeconds": 20,
    "maxConsecutiveFailures": 3
  }
]
```

**Comment by aldipower** [comment]
@aquamatthias Could you approve that the JSON structure reflects the form fields we will display? So that we expose the correct form fields.

**Comment by aquamatthias** [comment]
@aldipower the json you posted is not complete. Please see https://mesosphere.github.io/marathon/docs/health-checks.html

**Comment by aldipower** [comment]
@aquamatthias Thanx, and does it make sense to expose all the fields? I guess, yes.

**Comment by aquamatthias** [comment]
Sure.

**Comment by Raffo** [comment]
@aquamatthias  Isn't this the wrong place to post such a thing? If so, can you duplicate it here https://github.com/mesosphere/marathon-ui ? I was thinking to add such a feature and I was wondering about the current status of this.

**Comment by aquamatthias** [comment]
Hey @Raffo No it is not the wrong place. All marathon related tickets (either service or ui) are handled in that project. github issues are turned off in marathon-ui.

**Comment by Raffo** [comment]
@aquamatthias thanks for letting me know! Having health checks in the marathon UI config dialog would be really great, I'll let you know in case I start working on this.
