### ISSUE TITLE
UI webjar SNAPSHOT is cached too long

### ISSUE THREAD

**Issue by aldipower** [mesosphere/marathon#2145]
The snapshot of the UI webjar included in Marathon seems to be cached for about 3 days on the servers. For testing purposes it would be good to be able to test the current snapshot build immediately with Marathon.
Clearing the .ivy2 directory, where the jars are stored locally, doesn't do the trick and we have the same behavior on different machines.

**Comment by aquamatthias** [comment]
I guess the s3 cache is guilty?

**Comment by philipnrmn** [comment]
Currently we're working around this by tagging releases which we need available immediately. It would be good to solve it though.

**Comment by aldipower** [comment]
I think this is fixed by @lloesche now?

**Comment by aldipower** [comment]
Somehow fixed.

**Comment by philipnrmn** [comment]
Yep this was fixed by zeroing the TTL of cached items in the relevant s3 bucket.
