### ISSUE TITLE
"task launch delay" undocumented

### ISSUE THREAD

**Issue by mgummelt** [mesosphere/marathon#2152]
site:mesosphere.github.io/marathon "task launch delay"

only 1 cursory result

**Comment by pierlo-upitup** [comment]
Thanks @mgummelt ,

I believe the corresponding docs section is https://mesosphere.github.io/marathon/docs/rest-api.html#backoffseconds-backofffactor-and-maxlaunchdelayseconds 

But yes, those three words don't ever show up in the docs in that same order. 

Do you feel like suggesting some edits?

**Comment by mgummelt** [comment]
I suggest we use consistent terms.  Calling it both "task launch delay" and "backoff" make it hard for a n00b (me) to understand the concept.  It also makes it hard to search the docs (which is what I did when I read the 0.10 changelog)

**Comment by pierlo-upitup** [comment]
@mgummelt that makes sense.

### ACs

- [ ] Make sure the docs use a consistent naming for `backoff`, `task launch delay` and the likes.

Pinging @kolloch

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3408. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
