### ISSUE TITLE
Row is off-centre if upper row is empty in lists

### ISSUE THREAD

**Issue by aldipower** [mesosphere/marathon#2157]
Here the ~~version~~ message information isn't available and the message row is emtpty.
All rows below move accidentally one up.

![emptyrow](https://cloud.githubusercontent.com/assets/859154/9627274/364cc08a-5163-11e5-8ca1-0a0400ce66e5.png)

**Comment by pierlo-upitup** [comment]
hah!

**Comment by pierlo-upitup** [comment]
@aldipower thank you very much for taking care of those unspecified_nodes as well – well done
