### ISSUE TITLE
Breaking line indentation: pick a style

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2163]
Let's agree on a consistent indentation style for line breaking statements including ternary operators, logical operators and string concatenators.

Discussion started in https://github.com/mesosphere/marathon-ui/pull/184/files#diff-ee58f29f51a4e5443773b0fed24eb749R86

For function arguments we seem to agree on 

```
var extraLongFunc = function(superLongFirstArgument,
  secondArgument,
  thirdArgument) {
```

For ternaries, we agreed to 

```
return doWeLikeTernaries
  ? <h1>YES</h1>
  : null;
```

But we haven't decided on a similar style for 

```
var extraLongString = "dadadadadadadadadada" + 
  "dedede!";
// OR
var extraLongString = "dadadadadadadadadada"
  +  "dedede!";
// ?
```

and 

```
if (whateverAndEver &&
  alsoThisAndThat && 
  whyNotThose) {
// OR
if (whateverAndEver
  && alsoThisAndThat
  && whyNotThose) {
```

Should we always go for the leading operator on the new lines for consistency with the ternary syntax?

**Comment by pierlo-upitup** [comment]
Pulling in @rcorral @mlunoe @kennyt @jfurrow

**Comment by mlunoe** [comment]
- For function calls (you are representing declarations here, and I think we should avoid the variable declarations and prefer function declarations) I would like to go with this, as it follows what we do in jsx:
```
SomeEntity.extraLongFunc(superLongFirstArgument,
  secondArgument,
  thirdArgument,
  fourthArgument
);
```
I think it makes it more readable and
- Did we decide to go with ternary operators?
- For string concatenation and boolean operators I'd like us to just be consistent. Some prefer the leading style as it is more apparent what is going on, and I tend to agree.

**Comment by pierlo-upitup** [comment]
Re function calls: yep, that was my idea too, first argument inline and following arguments one per line, just like we do in JSX.

About ternaries: we definitely agreed to not agree on anything until the Airbnb styleguide covers them :) But as a matter of fact some of us are writing them, and it makes sense to at least keep a consistent style. We (the HH team) decided for now to only ever use them for short, simple expressions and to indent them as above.

I also tend to like the leading `&&` and `||` .
