### ISSUE TITLE
Add a "strict" mode

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#2164]
Marathon currently accepts unknown fields in app definitions, which are then silently ignored. This leads to problems that are very hard to debug, e.g., typos in attribute names, attributes defined at the wrong level (for instance specifying the volumes at the root level instead of inside the container info).

A "strict mode" should be added, which would include extra validations such as:
- Not allowing unknown fields.
- Extra sanity checks, such as rejecting an app definition including port mappings if the `network` field is set to `HOST`. 

This mode could be enabled through a URL parameter (`POST /v2/apps?strict=true`) and should be disabled by default in order to maintain backwards compatibility. At some point it might be meaningful to enable it by default.

**Comment by meichstedt** [comment]
+1

**Comment by kolloch** [comment]
+1

**Comment by kolloch** [comment]
Extra sanity checks should be on by default (if the config doesn't make sense): https://github.com/mesosphere/marathon/issues/1729

Extra fields should only be disallowed in the strict mode that you suggest.

**Comment by M0dM** [comment]
+1

**Comment by bobrik** [comment]
Another thing that should appear in strict mode: `requirePorts` with one of the ports set to `0` should trigger an error. Currently marathon allocates port in it's own range that might not intersect with port range advertised by mesos slaves. This leads to inability to schedule app anywhere.

**Comment by M0dM** [comment]
@bobrik 

Maybe you should create another issue for this ;)

**Comment by jsancio** [comment]
+1. The CLI used to have logic to check against this. Now that we are delegating all checks to Marathon the user doesn't get warn when there are extra fields.

``` 
> dcos marathon app update test-app blah=234
Created deployment 9420a972-d02d-41b6-bcd6-3feef173c983

# This is better...
> dcos marathon app update test-app instances=helloworld
Error on request [PUT http://***.elb.amazonaws.com/marathon/v2/apps/test-app]: HTTP 400: Bad Request:
{
  "details": [
    {
      "errors": [
        "error.expected.jsnumber"
      ],
      "path": "/instances"
    }
  ],
  "message": "Invalid JSON"
}
```

**Comment by jsancio** [comment]
Another example. This could be really confusing to the user:

```
> dcos marathon group list
> dcos marathon group add bad_group.json
> dcos marathon group list
ID                  APPS
/bad-group           0
/bad-group/notgood   0
> dcos marathon app list
> cat bad_group.json
{
  "groups": [
    {
      "fakeapp": [
        {
          "cmds": "sleep 0",
          "id": "hi",
          "instances": 0
        }
      ],
      "id": "notgood"
    }
  ],
  "id": "bad-group"
}
```

**Comment by jrx** [comment]
+1

**Comment by adyatlov** [comment]
+1
Please see this customer issue: https://groups.google.com/a/dcos.io/forum/?utm_medium=email&utm_source=footer#!msg/users/sS0nqyXUZm4/3STrG6r3AAAJ

**Comment by ernestas-poskus** [comment]
+1

**Comment by pradeepchhetri** [comment]
+1

**Comment by reachbach** [comment]
+1

**Comment by greggomann** [comment]
+1
I think the fact that Marathon will silently alter submitted JSON is a pretty significant usability issue and it would be great to see it resolved.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3000. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
