### ISSUE TITLE
Marathon returns bad error when framework auth secret is too short

### ISSUE THREAD

**Issue by jgarcia-mesosphere** [mesosphere/marathon#2169]
When using a framework auth secret that's shorter than an unknown length, the error `java.io.IOException: Error reading authentication secret from file` is generated. We'd like this error to more clearly reflect the failure mode.

PR https://github.com/mesosphere/marathon/pull/2168 is submitted to add this to the docs.

**Comment by aquamatthias** [comment]
@jgarcia-mesosphere I can not reproduce this. I tried with one letter secret and also an empty file. The code looks like this:
```scala
try { 
    val secretBytes = ByteString.readFrom(new FileInputStream(secretFile))
    credentialBuilder.setSecret(secretBytes)
} catch {
    case cause: Throwable =>  throw new IOException(s"Error reading authentication secret from file [$secretFile]", cause)
}
```
The only reason this can fail with the exception you mention, is that there is an IOException. You can see that in the logs. Are you sure you specified the correct file and the file was readable to Marathon?

**Comment by aquamatthias** [comment]
Sorry: your log statement already says, that this is an IOException. 
Then the problem is clear: the file was not readable to Marathon - it does not have anything to do with the secret length.
