### ISSUE TITLE
Verify: Restarting Tasks during Deployment with Deps should use correct App Version

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#2170]
#1898 causes AppRepository writes to happen earlier. We have to verify that replacing tasks while upgrading does not start tasks with a new app definition if dependencies are still not restarted.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3151. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
