### ISSUE TITLE
Add installation guide for native packages (especially java8 related)

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#2173]
The installation guide in https://mesosphere.com/downloads/ should be updated.

**Comment by gkleiman** [comment]
CentOS will work out of the box once mesosphere/marathon-pkg#19 is merged.

For Ubuntu 12.04 and Ubuntu 14.04 we have to add the following steps to our guide:

sudo add-apt-repository ppa:webupd8team/java
sudo apt-get install oracle-java8-installer
sudo apt-get install oracle-java8-set-default

**Comment by mwasn** [comment]
Handed over to TW (see internal DOCS-236)
