### ISSUE TITLE
Application and Task Limit Guidance

### ISSUE THREAD

**Issue by AlexClineBB** [mesosphere/marathon#2183]
We're running a Mesos (0.22.1) and Marathon (0.8.2) cluster with 3 masters and 68 (272 CPUs and ~900GB RAM) slaves. Currently, we have 180 applications and 933 running tasks. Our tasks are CPU intensive and use little RAM. We have very infrequent scaling events which are always fewer than 50 tasks. We've found this configuration to be very stable and responsive.

In the next few months, we're estimating we'll increase to 200 applications with up to 2000 tasks running.

Are there any limits we should be adhering to? In the past I've heard of a 1000 running task limit, but I'm not sure if this still applies to the versions we're running.

We'd like to be able to plan for splitting the cluster now if we need to, rather than scramble later hitting a ceiling we didn't know about.

Any input on capacity planning will be helpful.

Thanks.

**Comment by philipnrmn** [comment]
Hi Alex,

It's great to hear that Marathon is working so well for you. 

200 apps and 2000 tasks will not cause any issues. Marathon will comfortably run tens of thousands of tasks - check out the [demo from this year's MesosCon keynote](https://www.youtube.com/watch?v=_tfneEN0uPs&feature=youtu.be&t=390), in which they deploy 50,000 in one go. 

I'll leave this issue open and add a documentation label as I believe we should have a 'Marathon at Scale' page in the docs where we define capabilities and list caveats.

**Comment by mwasn** [comment]
We cover this topic with #2429
