### ISSUE TITLE
Generalize task address discovery e.g. for health checks, UI.

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#2184]
In the [future](https://docs.google.com/document/d/17mXtAmdAXcNBwp_JfrxmZcQrs7EO6ancSbejrqjLQ0g), it will not be safe to assume that tasks will be reachable by the Mesos agent hostname or address (as read from the resource offer).  In case of custom network isolation modules, the task executor could be assigned an arbitrary IP address.  Per the design, linked above, a correct way to learn the task's assigned IP is to read it from status update metadata.  Marathon might want to provide a flag to control how task addresses are resolved.

For example:
- `--task_address_mode host_address`  
  Current mode of operation.
- `--task_address_mode status_update`  
  Read assigned address from status update metadata.
- `--task_address_mode mesos_dns`  
  Infer a DNS name that _mesos-dns_ can resolve to an address.

cc @spikecurtis @djosborne @karya0 @nqn

**Comment by cheuschober** [comment]
For interested parties like ours already doing parallel development of these features, could you clarify if the googledoc or this issue is the correct place to track and/or discuss the issue?

**Comment by ConnorDoyle** [comment]
For discussion of the changes in Mesos and recommendations for network isolation module and/or framework authors please use the linked Google doc or comment on MESOS-2044 in the ASF Jira (https://issues.apache.org/jira/plugins/servlet/mobile#issue/MESOS-2044).

Use this issue to discuss the proposed changes in Marathon specifically.

**Comment by cheuschober** [comment]
Thanks for the clarification. One of the questions I have is, given the above, how would service ports be tracked for the purposes of health checks? I think capturing the IP address is an important first-step but, currently, we can't abuse the existing ports metadata because we're not looking for offers.

**Comment by ConnorDoyle** [comment]
The health check subsystem does not use service ports at all.  This is primarily because service ports do not affect how containers are actually networked, unless that metadata is picked up by another system for example to configure a reverse proxy (as in the case of servicerouter or marathon-haproxy-bridge.)  Where they could apply is SRV record generation in a system like Mesos-DNS or Mesos-Consul. But SRV handling is problematic for many clients anyway and in that case Marathon should probably learn to send DiscoveryInfo instead.  Part of the takeaway is that ports matter much less with network isolators that implement IP-per-container.  In fact, decreasing reliance on scheduling ports on the Mesos agent host interface is one of the major benefits.

**Comment by cheuschober** [comment]
Perhaps I'm a little behind, but last I'd checked health checks still had support for the concept of `portIndex` which, as I understand it would be incompatible with an independent task address. Service ports may not need to be exposed directly but, short of a `COMMAND` protocol, I don't see how it would be possible to, say, specify HTTP checks on a web service with a task address. Is there something I'm missing?

**Comment by ConnorDoyle** [comment]
No, you're right; it's something that needs to be handled. Marathon will have to avoid conflating the host ports and the application (or service) ports.  Here's a related issue for work on the networking API: https://github.com/mesosphere/marathon/issues/1112

**Comment by cheuschober** [comment]
Awesome -- glad I've got a little handle on it. While the linked issue seems like a reasonable one, is the shorter path to just expose a `port` parameter in the health check for a static port check? If the goal is to avoid getting into the service discovery business (a case I totally understand) maybe that's an easier win?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2707. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
