### ISSUE TITLE
Docker private registry instructions don't appear to work on DCOS clusters deployed on AWS

### ISSUE THREAD

**Issue by ssk2** [mesosphere/marathon#2193]
I haven't replicated this myself but we've received a report that a user is unable to get the `.docker` folder instructions on the Marathon docs: https://mesosphere.github.io/marathon/docs/native-docker-private-registry.html working on DCOS. 

The old instructions seem to work fine.

Is this a known issue? Alternatively, any idea why this might not be working? The stable CoreOS version that is used for DCOS on AWS includes Docker 1.6.

**Comment by Lykathia** [comment]
One thought, would a mismatch of uid/gid cause any issues? (As in, if the .docker folder was tar'd up using a non-root user on another machine and transferred)

**Comment by ssk2** [comment]
Ah, that might be worth trying - the Mesos task fetcher (which is what pulls the URIs down) doesn't change the permissions. If the permissions are restrictive by default, the Docker daemon might not be able to read the file.

**Comment by Lykathia** [comment]
After a failed run, the sandbox looks like this:
![screenshot](https://i.imgur.com/H2AopWl.png)

Unfortunately there is no real output to debug off of. Here is the contents of stderr

```
/opt/mesosphere/packages/mesos--535e40344a2820e6fe8866b7f477cf5c75f6c86e/libexec/mesos/mesos-fetcher: /lib64/libcurl.so.4: no version information available (required by /opt/mesosphere/packages/mesos--535e40344a2820e6fe8866b7f477cf5c75f6c86e/libexec/mesos/mesos-fetcher)
I0906 00:57:06.055162 29287 logging.cpp:172] INFO level logging started!
I0906 00:57:06.056555 29287 fetcher.cpp:214] Fetching URI 'file:///etc/docker.tar.gz'
I0906 00:57:06.056591 29287 fetcher.cpp:194] Copying resource from '/etc/docker.tar.gz' to '/var/lib/mesos/slave/slaves/20150904-160242-2852388874-5050-1225-S1/frameworks/20150904-160242-2852388874-5050-1225-0000/executors/taskname.31800723-5432-11e5-a120-be0a694d6f92/runs/c1be1c29-694a-40af-8d74-24502f1b7b0f'
I0906 00:57:06.061437 29287 fetcher.cpp:78] Extracted resource '/var/lib/mesos/slave/slaves/20150904-160242-2852388874-5050-1225-S1/frameworks/20150904-160242-2852388874-5050-1225-0000/executors/taskname.31800723-5432-11e5-a120-be0a694d6f92/runs/c1be1c29-694a-40af-8d74-24502f1b7b0f/docker.tar.gz' into '/var/lib/mesos/slave/slaves/20150904-160242-2852388874-5050-1225-S1/frameworks/20150904-160242-2852388874-5050-1225-0000/executors/taskname.31800723-5432-11e5-a120-be0a694d6f92/runs/c1be1c29-694a-40af-8d74-24502f1b7b0f'
```

**Comment by ssk2** [comment]
Do you have access to the mesos-slave logs? The Docker containerizer may have written something useful out there.

**Comment by Lykathia** [comment]
Not seeing anything besides what you'd expect to see when pulling a private image w/o credentials.

```
E0906 01:20:57.597219  1132 slave.cpp:3112] Container '6142b5d1-3d35-4af6-8505-8c72092ea9a7' for executor 'TASKNAME.868aef32-5435-11e5-a120-be0a694d6f92' of framework '20150904-160242-2852388874-5050-1225-0000' failed to start: Failed to 'docker pull THE/IMAGE': exit status = exited with status 1 stderr = time="2015-09-06T01:20:57Z" level=fatal msg="Error: image THE/IMAGE not found"
```

**Comment by aquamatthias** [comment]
@sascala this ticket is rather old - can you please retest, if this is still a problem?

**Comment by sascala** [comment]
Sure.

**Comment by distributorofpain** [comment]
Not sure if this is related to my issue, but if i pull a file for a private registry ( .docker dir with the config.json file in it ), then i need to update that file, mesos pulls the file again, but doesnt update/overwrite the .docker folder or the config.json file.  because this file holds credentials that are wrong, i cannot get my images downloaded as i need the credentials updated.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2695. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
