### ISSUE TITLE
Merge 0.9.x asset commits into master

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2204]
Background: we accidentally deleted two branches containing commits upon which three Marathon releases depended (#2198)

In order to keep this from happening in the future, let's find a way to merge these two commits into `master`. 

NB this is not a future concern as we [no longer use](https://github.com/mesosphere/marathon/pull/1973) the submodule mechanism.

**Comment by okuryu** [comment]
:+1:
