### ISSUE TITLE
Please take a look at #2101

### ISSUE THREAD

**Issue by nashasha1** [mesosphere/marathon#2208]
Will you guys take a look at #2101 ! We met this terrible problem a few day ago, and it is still there. We don't think marathon can only just support 1000 apps. So ,do we do sth wrong? What can we do about this?

**Comment by nashasha1** [comment]
We met this problem in version 0.8.2 and 0.9.2

**Comment by philipnrmn** [comment]
Hi @nashasha1, I'm trying to reproduce this now. I'm going to close this issue as a duplicate and continue with the original.
