### ISSUE TITLE
Reimplement ignored Groups dependency integration test

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#2211]
The `Groups with dependant Applications get upgraded in the correct order with maintained upgrade strategy` test in `src/test/scala/mesosphere/marathon/integration/GroupDeployIntegrationTest.scala` is being  ignored, because it was flaky.

We need to reimplement it, so that it isn't flaky anymore.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2927. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
