### ISSUE TITLE
portMapping not working correctly for static ports (v 0.10.0)

### ISSUE THREAD

**Issue by jfindley** [mesosphere/marathon#2215]
If I statically assign ports (as some applications require this), the json is parsed correctly, but the actual resource assignment is wrong.  This means that adjacent ports can overlap, when they should not.

Example below.

Input:
```json
"portMappings":[{"containerPort":8300,"hostPort":8300,"servicePort":10000,"protocol":"tcp"},{"containerPort":8301,"hostPort":8301,"servicePort":10001,"protocol":"tcp"},{"containerPort":8301,"hostPort":8301,"servicePort":10002,"protocol":"udp"},{"containerPort":8302,"hostPort":8302,"servicePort":10003,"protocol":"tcp"},{"containerPort":8302,"hostPort":8302,"servicePort":10004,"protocol":"udp"},{"containerPort":8400,"hostPort":8400,"servicePort":10005,"protocol":"tcp"},{"containerPort":8500,"hostPort":8500,"servicePort":10006,"protocol":"tcp"},{"containerPort":53,"hostPort":53,"servicePort":10007,"protocol":"udp"}
```

Result (from /v2/apps):
```json
"message":"Task uses invalid resources: Invalid resources: Resource 'ports(*):[8300-8301, 8301-8302, 8302-8302, 8400-8400, 8500-8500, 53-53]' is invalid: Invalid ranges resource: overlapping ranges","state":"TASK_ERROR"
```

As you can see, the first few ports are not correctly mapped - 8300-8300 gets transformed into 8300-8301.  Oddly after the first two, this stops happening, which means the 8200-8200 mapping then conflicts and the task does not start.

**Comment by kolloch** [comment]
You are using the same ports for UDP/TCP which is problematic right now.

I think, this is a duplicate of https://github.com/mesosphere/marathon/issues/751.

**Comment by jfindley** [comment]
Yeah - it is indeed a duplicate - I don't know why the original didn't turn up in my searches.  I'll close this one.  Sorry for the noise.

**Comment by kolloch** [comment]
No worries. It IS confusing and not optimal.
