### ISSUE TITLE
Display life time duration as other durations in UI

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#2223]
<img width="499" alt="screen shot 2015-09-09 at 20 27 45" src="https://cloud.githubusercontent.com/assets/339354/9770620/6c20de8e-5731-11e5-82f3-fe43aa5b9faf.png">

The last version change is displayed in more human readable time units. I would like the life times be displayed in the same way. Alternatively, let's round them (right now they have varying amounts of decimal places) and have separators for 1,000s.

**Comment by haosdent** [comment]
LoL Sorry for post the message in incorrect places. Because I could not found your emails. I am a volunteer mesos contributor. And could you help me review a mesos webui bug fix. [MESOS-3282](https://reviews.apache.org/r/38056/) Thank you in advance.

**Comment by kolloch** [comment]
Hi @haosdent, I asked @joerg84 about this. But please do not post comments in unrelated issues of other projects.

**Comment by joerg84** [comment]
@haosdent: It is being reviewed right now.
@kolloch: sorry for posting this here :-)

**Comment by haosdent** [comment]
sorry. It's my fault.
