### ISSUE TITLE
POST to /v2/apps on non-leader doesn't work

### ISSUE THREAD

**Issue by eguven** [mesosphere/marathon#2227]
This is the same issue as https://github.com/mesosphere/marathon/issues/1239 where you get

    415 {"message":"Unsupported Media Type"}

the suggestion there (setting `"Content-Type: application/json"`) works as a workaround.

**Comment by gomes** [comment]
But it's not the same, when you are posting something, you have to explicit say what is your data. So, your workaround is the right way to do.

The example in doc https://mesosphere.github.io/marathon/docs/rest-api.html#post-v2-apps

**Comment by eguven** [comment]
This was not happening on leader though.

**Comment by kolloch** [comment]
This should be fixed on 0.11. Generally, I would recommend a "Content-Type" header, though, to be standard compliant.
