### ISSUE TITLE
enhancement: service-discovery environment variables

### ISSUE THREAD

**Issue by tony-kerz** [mesosphere/marathon#2232]
hi,

i was just going through (what i assume is) a common pattern,
where i am deploying one docker-app on marathon (in my case a hubot instance),
and it is wanting to connect to an instance of redis which i am wanting to deploy as 
another docker-app on marathon.

hubot will be looking to the `REDIS_URL` environment variable to connect to it's redis instance.

the obvious challenge here is that only mesos(-dns) will know what REDIS_URL should be at any given point, so how do we set it for the hubot instance?

my current thinking is to have the docker image for the hubot instance have an entrypoint which is a bash script which uses the [mesos-dns rest api](https://mesosphere.github.io/mesos-dns/docs/http.html) to do something like this:

```
core@ip-10-0-0-94 ~ $ export REDIS_URL=$(curl -s master.mesos:8123/v1/services/_${toBeDiscovered}._tcp.marathon.mesos | python -c '
import json,sys
obj=json.load(sys.stdin)[0]
discovered="{}:{}".format(obj["host"],obj["port"])
print(discovered)
')
```

but this approach has the drawbacks:
1. it requires a mesos specific docker image
2. it is repetitive in that the lookup code would have to be in all such images with dependencies
3. it doesn't handle the scenario where the thing to be discovered isn't running (yet)
4. it doesn't handle retry-wait logic in case the launch of the dependency and the depender occur immediately one after the other

so i had this idea, that it sure would be awesome if i could write marathon json something like so:

**dependency**

```
{
  "id": "my-hubot-redis",
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "redis:3.0.3",
      "network": "BRIDGE",
      "portMappings": [
        {
          "containerPort": 6379
        }
      ]
    }
}
```

**depender**

```
{
  "id": "my-hubot",
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "my-hubot:1.0"
    },
  "env": {
    "REDIS_URL": {
      "function": "lookup",
      "args": {
        "id": "my-hubot-redis"
      }
    }
  }
}
```

and have marathon resolve the value of REDIS_URL dynamically.

appreciate any input as to whether this is a reasonable idea, 
or if there are more idiomatic ways to accomplish this requirement.

best,
tony.

**Comment by kolloch** [comment]
Thanks for this proposal, @tony-kerz!

That's related to https://github.com/mesosphere/marathon/issues/1608.

I think that I might like the spirit of your approach better than my approach since it is independent of the app dependency mechanism and more flexible.

Please note that the looked up host port might only be valid on startup. So either this only provides a seed node and your client will automatically discover instances of the service and fail over to them or it will have to fail over and wait to be restarted.

**Comment by tony-kerz** [comment]
thanks pete,

yep, understood that the environment variable would only be dependable at start-up of the 'depender' (i.e. if the dependency failed after start-up of the depender, then that environment variable would no longer be dependable, and the behavior you described would be in effect).

**Comment by cgbaker** [comment]
We experience a similar situation. Our solution is to use one of the Marathon-haproxy bridges (currently, the marathon-haproxy-bridge, but switching to the servicerouter.py bridge). This way, the dependent service can be directed at the proxy using the service port. This requires knowing what the service port is, which requires creating the dependency first, then the dependent service. (We're managing our own dependencies.) A benefit, however, is that the indirection is handled through the haproxy, which is updated continuously. Therefore, if the dependency moves to another host/port, the dependent service doesn't need to be updated.

**Comment by jasongilanfarr** [comment]
This is essentially service discovery which is out of scope of marathon. Please consider mesos-dns, marathon-lb or similar solutions.
