### ISSUE TITLE
Health checks stop when app is scaled

### ISSUE THREAD

**Issue by sdwr98** [mesosphere/marathon#2234]
Hi all,

I'm having a problem with health checks and scaling that I can reproduce on 0.8.2, 0.9.1, and 0.10.1.  The app is a docker-based app, with an HTTP health check configured to run every 30 seconds.  When we scale the app up or down, any new tasks have health checks, but the existing running tasks lose their health checks.  In the logs, I see that Marathon is repeatedly starting and stopping a health check actor:

    Sep 10 12:28:17 mesosmaster1 marathon[23218]: [INFO] [09/10/2015 12:28:17.247] [marathon-akka.actor.default-dispatcher-7] [akka://marathon/user/$F] Received health result: [Healthy(service_userservice.ba46a4bc-57e4-11e5-b96b-005056b9ce19,2015-09-10T16:57:51.314Z,2015-09-10T19:28:17.247Z)]
    Sep 10 12:28:17 mesosmaster1 marathon[23218]: [INFO] [09/10/2015 12:28:17.253] [marathon-akka.actor.default-dispatcher-12] [akka://marathon/user/$F] Received health result: [Healthy(service_userservice.b9aef89a-57e4-11e5-b96b-005056b9ce19,2015-09-10T16:57:51.314Z,2015-09-10T19:28:17.253Z)]
    Sep 10 12:28:17 mesosmaster1 marathon[23218]: [INFO] [09/10/2015 12:28:17.255] [marathon-akka.actor.default-dispatcher-14] [akka://marathon/user/$F] Received health result: [Healthy(service_userservice.5743b350-57e5-11e5-b96b-005056b9ce19,2015-09-10T16:57:51.314Z,2015-09-10T19:28:17.255Z)]
    Sep 10 12:28:23 mesosmaster1 marathon[23218]: [INFO] [09/10/2015 12:28:23.218] [marathon-akka.actor.default-dispatcher-14] [akka://marathon/user/$Ic] Starting health check actor for app [/service/userservice] and healthCheck [HealthCheck(Some(/userservice/admin/info),HTTP,0,None,60 seconds,60 seconds,20 seconds,3,false)]
    Sep 10 12:28:24 mesosmaster1 marathon[23218]: [INFO] [09/10/2015 12:28:24.395] [marathon-akka.actor.default-dispatcher-13] [akka://marathon/user/MarathonScheduler/$a/DeploymentManager/3b8f7451-df07-4a89-9389-da94fb3e58d9/$a] Task service_userservice.ba46a4bc-57e4-11e5-b96b-005056b9ce19 has been killed. Waiting for 0 more tasks to be killed.
    Sep 10 12:28:28 mesosmaster1 marathon[23218]: [INFO] [09/10/2015 12:28:28.891] [marathon-akka.actor.default-dispatcher-12] [akka://marathon/user/$F] Stopped health check actor for app [/service/userservice] and healthCheck [HealthCheck(Some(/userservice/admin/info),HTTP,0,None,60 seconds,60 seconds,20 seconds,3,false)]
    Sep 10 12:28:28 mesosmaster1 marathon[23218]: [INFO] [09/10/2015 12:28:28.950] [marathon-akka.actor.default-dispatcher-12] [akka://marathon/user/$Lc] Starting health check actor for app [/service/userservice] and healthCheck [HealthCheck(Some(/userservice/admin/info),HTTP,0,None,60 seconds,60 seconds,20 seconds,3,false)]
    Sep 10 12:28:58 mesosmaster1 marathon[23218]: [INFO] [09/10/2015 12:28:58.906] [marathon-akka.actor.default-dispatcher-7] [akka://marathon/user/$Lc] Stopped health check actor for app [/service/userservice] and healthCheck [HealthCheck(Some(/userservice/admin/info),HTTP,0,None,60 seconds,60 seconds,20 seconds,3,false)]
    Sep 10 12:28:58 mesosmaster1 marathon[23218]: [INFO] [09/10/2015 12:28:58.964] [marathon-akka.actor.default-dispatcher-14] [akka://marathon/user/$Pc] Starting health check actor for app [/service/userservice] and healthCheck [HealthCheck(Some(/userservice/admin/info),HTTP,0,None,60 seconds,60 seconds,20 seconds,3,false)]

In the log above, the app had 3 running instances (you can see the first 3 lines are successful health checks).  At 12:28, I scaled the app down to 2 instances.  At that point, the health checks are lost in the UI and from the REST API, and I see the last 2 log messages repeated over and over.  

This is causing some problems with our automated systems that rely on health checks.  Any assistance in debugging this would be much appreciated! 

*Edit*: forgot to mention, if I kill one of the existing tasks that has lost health checks, the one that Marathon starts up to replace it does have health checks.  

Scott

**Comment by kolloch** [comment]
Hi @sdwr98, thanks for reporting this. I try to reproduce that now.

**Comment by kolloch** [comment]
@sdwr98: I couldn't reproduce that with 0.11. I will try with 0.10.1. If something is wrong with the steps that I follow, please tell me.

That's what I did (I removed some headers):

```http
PUT /v2/apps/peter/issue2234 HTTP/1.1
Accept: application/json
Content-Type: application/json

{
    "cmd": "python -m SimpleHTTPServer $PORT",
    "container": {
        "docker": {
            "image": "python:2",
            "network": "HOST"
        },
        "type": "DOCKER"
    },
    "cpus": 1,
    "healthChecks": [
        {
            "gracePeriodSeconds": 30,
            "ignoreHttp1xx": false,
            "intervalSeconds": 5,
            "maxConsecutiveFailures": 3,
            "path": "/",
            "portIndex": 0,
            "protocol": "HTTP",
            "timeoutSeconds": 5
        }
    ],
    "instances": 1,
    "mem": 128,
    "ports": [
        0
    ]
}

HTTP/1.1 201 Created
Content-Type: application/json; qs=2

{
    "deploymentId": "b8b85c09-aea6-4c30-a0e4-70871664ceb7",
    "version": "2015-09-14T16:16:03.969Z"
}

GET /v2/apps/peter/issue2234 HTTP/1.1
Accept: application/json

HTTP/1.1 200 OK
Content-Type: application/json; qs=2

{
    "app": {
        // ...
        "tasks": [
            {
                "appId": "/peter/issue2234",
                "healthCheckResults": [
                    {
                        "alive": true,
                        "consecutiveFailures": 0,
                        "firstSuccess": "2015-09-14T16:16:09.145Z",
                        "lastFailure": null,
                        "lastSuccess": "2015-09-14T16:18:29.705Z",
                        "taskId": "peter_issue2234.e5da2d35-5afb-11e5-b44d-be5b2935a987"
                    }
                ],
                "host": "srv5.hw.ca1.mesosphere.com",
                "id": "peter_issue2234.e5da2d35-5afb-11e5-b44d-be5b2935a987",
                "ports": [
                    31639
                ],
                "slaveId": "20150707-153709-218108076-5050-25588-S2",
                "stagedAt": "2015-09-14T16:16:05.425Z",
                "startedAt": "2015-09-14T16:16:05.614Z",
                "version": "2015-09-14T16:16:03.969Z"
            }
        ],
        // ...
    }
}

PUT /v2/apps/peter/issue2234 HTTP/1.1
Accept: application/json

{
    "instances": 3
}

HTTP/1.1 200 OK
Content-Type: application/json; qs=2

{
    "deploymentId": "8ec66563-1f09-44c2-b013-b742b7ea62c9",
    "version": "2015-09-14T16:23:29.779Z"
}

GET /v2/apps/peter/issue2234/tasks HTTP/1.1
Accept: */*



HTTP/1.1 200 OK
Content-Type: application/json; qs=2

{
    "tasks": [
        {
            "appId": "/peter/issue2234",
            "healthCheckResults": [
                {
                    "alive": true,
                    "consecutiveFailures": 0,
                    "firstSuccess": "2015-09-14T16:16:09.145Z",
                    "lastFailure": null,
                    "lastSuccess": "2015-09-14T16:25:21.344Z",
                    "taskId": "peter_issue2234.e5da2d35-5afb-11e5-b44d-be5b2935a987"
                }
            ],
            "host": "srv5.hw.ca1.mesosphere.com",
            "id": "peter_issue2234.e5da2d35-5afb-11e5-b44d-be5b2935a987",
            "ports": [
                31639
            ],
            "slaveId": "20150707-153709-218108076-5050-25588-S2",
            "stagedAt": "2015-09-14T16:16:05.425Z",
            "startedAt": "2015-09-14T16:16:05.614Z",
            "version": "2015-09-14T16:16:03.969Z"
        },
        {
            "appId": "/peter/issue2234",
            "healthCheckResults": [
                {
                    "alive": true,
                    "consecutiveFailures": 0,
                    "firstSuccess": "2015-09-14T16:24:05.104Z",
                    "lastFailure": null,
                    "lastSuccess": "2015-09-14T16:25:20.404Z",
                    "taskId": "peter_issue2234.f06b995e-5afc-11e5-b44d-be5b2935a987"
                }
            ],
            "host": "srv3.hw.ca1.mesosphere.com",
            "id": "peter_issue2234.f06b995e-5afc-11e5-b44d-be5b2935a987",
            "ports": [
                31034
            ],
            "slaveId": "20150618-112946-201330860-5050-2210-S0",
            "stagedAt": "2015-09-14T16:23:32.651Z",
            "startedAt": "2015-09-14T16:24:04.093Z",
            "version": "2015-09-14T16:23:29.779Z"
        },
        {
            "appId": "/peter/issue2234",
            "healthCheckResults": [
                {
                    "alive": true,
                    "consecutiveFailures": 0,
                    "firstSuccess": "2015-09-14T16:24:05.104Z",
                    "lastFailure": null,
                    "lastSuccess": "2015-09-14T16:25:20.404Z",
                    "taskId": "peter_issue2234.f06b995d-5afc-11e5-b44d-be5b2935a987"
                }
            ],
            "host": "srv3.hw.ca1.mesosphere.com",
            "id": "peter_issue2234.f06b995d-5afc-11e5-b44d-be5b2935a987",
            "ports": [
                31700
            ],
            "slaveId": "20150618-112946-201330860-5050-2210-S0",
            "stagedAt": "2015-09-14T16:23:32.651Z",
            "startedAt": "2015-09-14T16:24:04.378Z",
            "version": "2015-09-14T16:23:29.779Z"
        }
    ]
}
```

**Comment by sdwr98** [comment]
@kolloch I was trying to do some additional debugging this morning, and what I found was that, in a clean environment (started from scratch), I cannot reproduce this.  I can only reproduce this on our existing running Marathon instances, which have been upgraded from 0.8.2 (and 0.7.6 before that).  

I took a running cluster that I could reproduce the issue on, shut down Marathon, wiped the Zookeeper state, started it back up, and deployed an app - I could no longer reproduce it. 

So I guess at this point it's not really a bug so much as a migration issue.  It just means that we'll need to take down our prod cluster and re-launch everything, unless you can think of a way we could clean it without shutting down Marathon. 

Thanks for looking into this!

**Comment by kolloch** [comment]
@air: What do you think? Investigate further or rather concentrate on other things?

**Comment by air** [comment]
> unless you can think of a way we could clean it without shutting down Marathon.

Can we think of something for this?

Otherwise, since we can't repro we should focus on more critical issues.

**Comment by kolloch** [comment]
@air: Since I do not know what is happening there without further analysis, I cannot suggest a workaround. Sorry.
