### ISSUE TITLE
Improve documentation for LIBPROCESS_IP

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2245]
There have been [several tickets](https://github.com/mesosphere/marathon/issues?q=is%3Aissue+LIBPROCESS_IP) which were resolved by setting LIBPROCESS_IP in /etc/default/marathon, and recently an [issue on the community mailing list](https://groups.google.com/forum/#!topic/marathon-framework/vo2SjHA--7g) related to upgrading between Marathon versions. 

We should offer better documentation around the behaviour of this configuration option, (or possibly a 'troubleshooting' page in the docs).

**Comment by kolloch** [comment]
Specifying `--hostname` correctly should resolve this issue since 0.11. See #1671.

**Comment by jeschkies** [comment]
Out of date.
