### ISSUE TITLE
Provide human-readable version of error placeholders

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2247]
We should provide a human readable version of the following API error placeholders:
- `error.path.missing`
- `error.expected.jsnumber`

This is useful in the short term in theNew App Modal form where we will soon show per-field validation errors as received from the server response.

Example response on a `400 POST /v2/apps`

```
{"message":"Invalid JSON”, 
  "details”:[
  {"path":"/container/docker/image","errors":["error.path.missing”]},
  {"path":"/container/volumes(0)/containerPath","errors":["error.path.missing"]},
  {"path":"/container/docker/parameters(0)/value","errors":["error.path.missing"]},
  {"path":"/container/volumes(0)/hostPath","errors":["error.path.missing"]},
  {"path":"/container/volumes(0)/mode","errors":["error.path.missing"]},
  {"path":"/container/docker/parameters(0)/key","errors":["error.path.missing”]
}]}
```

**Comment by kolloch** [comment]
So basically we should render the I18n message there. We will probably only support English for the foreseeable future.

So the question is: Do we translate these in the service layer or in the gui? The messages that you want to display might actually depend on where you display them. If you display them at the field, they should not contain a reference to the field or value they apply to. If you display them elsewhere, they should contain these things.

On the other hand, having them in the API response can also help people debugging API responses.

**Comment by pierlo-upitup** [comment]
What if we offered a `/i18n` endpoint that would return a JSON representing the field -> translation for the desired langCode? This way the UI could hit that once and be able to perform additional manglings. 

I like the idea of having the UI show the same error messages that would be shown via the CLI or by users dealing with the API manually, and I'd like those to be centralised.

**Comment by aldipower** [comment]
The easiest and most straight-forward way in the moment I can see is to include a human-readable version of the error message in the JSON response.
An endpoint would introduce an additional overhead and point of failure. I am not sure if we will ever have another language than English. Even if this will happen, I don't want to receive a whole list of unused messages only for looking up a single one.

**Comment by pierlo-upitup** [comment]
Fair enough, but I think in any case we should get to a point where there is ONE source of truth for all error messages (and I doubt this is in the UI).

Reasons:

1. Consistency. All Marathon "interfaces" (UI, CLI, API consumers) should display the exact same error to the user for server-side communication
2. Maintainability. We don't want to hunt down changing error responses or even error codes over time.
3. Extensibility. If we actually implement I18N (who knows) the effort isn't duplicated. 

All in all I don't see a huge point of failure in hitting an endpoint once per session. Pretty much like we do for the `/info` already. But for the moment I'd also suggest to keep it simple and go for inline responses with error code as well as "human readable" messages.

**Comment by aldipower** [comment]
Include a human-readable version of the error message in the JSON response is one source of truth.

**Comment by aldipower** [comment]
The ```/info```-endpoint is not a good example, because we request this endpoint only on demand and display all the data that was requested.
An ```/i18n```-endpoint you've have to request beforehand, even if you never going to display a message from that, also you need to request all the bunch of messages at once else you end up in an individual request per message what doesn't work, if you want to display a 'network connection'-error-message. ;)

**Comment by philipnrmn** [comment]
Related to the situation in #2845, where we found that a `409 Conflict` can have more than one meaning, it would be great to have numeric error codes so that the UI can determine which error message to show in which situation.

**Comment by pierlo-upitup** [comment]
+1 for the error codes!

**Comment by junneyang** [comment]
{"path":"/container/volumes(0)/mode","errors":["error.path.missing"]},

what does error.path.missing meaning?
why the hostPath field is required?

**Comment by philipnrmn** [comment]
Hi @junneyang, 

Please don't ask for technical support in unrelated tickets - it's better to open a new ticket. I've opened and responded to your query here: #3735

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3594. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
