### ISSUE TITLE
Resources For Roles Not Found

### ISSUE THREAD

**Issue by ryanorr** [mesosphere/marathon#2255]
I'm trying to get a clustered redis instance running on mesos/marathon using a role called 'redis'. My configuration for this is as follows:

I'm starting the mesos master with the following flag:
--roles=redis

The mesos slaves with:
--resources=ports(*):[some_ports];ports(redis):[6379-6379,16379-16379,9696-9696]

And marathon with the flag:
--mesos_role redis

The JSON I'm submitting includes the property:
"acceptedResourceRoles": [
  "redis"
]

In marathon 0.9.0, when I initially posted the request to Marathon to launch the redis app it would not launch and nothing would show up in the logs. However, if I suspended the app and then scaled up it would work just fine. We just upgraded to 0.10.0 and now it simply won't work (with the same configuration). The logs indicate the following:

role: "redis"
role: "redis"
role: "redis"
[2015-09-13 13:14:54,749] INFO Offer [20150914-202456-1694804160-5050-10639-093479]. Insufficient resources for [/redis] (need cpus=1.0, mem=1024.0, disk=0.0, ports=([6379,16379,9696] required), available in offer:
role: "redis"

The ports 6379, 16379 and 9696 are all open. I decided to try earmarking resources specifically for this role to see if that made a difference, launching the slave with the following resources:
--resources=cpu(redis):1;mem(redis):1024.0;ports(*):[some_ports];ports(redis):[6379-6379,16379-16379,9696-9696]

This produces the same 'insufficient resources' error as before. If I eliminate the concept of roles all together everything starts up fine, we're just trying to use a role for redis because their clustering automatically adds 10000 to the port for cluster communication and we were running into conditions where that port was being taken by other apps.

**Comment by kolloch** [comment]
Hey @ryanorr, thanks for reporting this.

Can you share more of the log with us? Including the full offer that is rejected? Only resources with a role in `"acceptedResourceRoles"` are considered and scalar resources of different roles are not merged yet. Mesos also subtracts some resources for book keeping sometimes, therefore just configuring the exact resources that you need for that role might not be sufficient.

**Comment by aquamatthias** [comment]
This ticket looks orphaned and will be closed. Please reopen, if this is a Marathon problem, that still exists.
