### ISSUE TITLE
Dynamic Volume Mounts?

### ISSUE THREAD

**Issue by jvaleo** [mesosphere/marathon#2259]
In my setup currently we have only 1 instance of a service running on each host so we're able to mount a volume using /var/log/{service}:/var/log/{service}. When we move to multiple instances of that service running we'll have multiple instances writing to the same log file if we stick with our current setup. Inside the container we're already using $MESOS_TASK_ID for the hostname we register with service discovery and it would be great to do something like /var/log/$MESOS_TASK_ID:/var/log/$MESOS_TASK_ID. It looks like those variables are only available within the container and not when the task is actually being launched. In lieu of that, is there any other solution for some sort of "dynamic" volume mounts?

**Comment by kolloch** [comment]
Hi @jvaleo,

so it would help you if we added a `MARATHON_TASK_ID` environment variable which is exactly equal to the task id as exposed in the Marathon user interface?

Please note, though, that this ID would change if you restarted/upgraded your tasks.

**Comment by jvaleo** [comment]
@kolloch Isn't MESOS_TASK_ID what is displayed as the task ID in the UI? We would basically need that variable to be evaluated to the same value both inside and outside of the containers context.

**Comment by kolloch** [comment]
Hi @jvaleo, the MESOS_TASK_ID has a prefix that encodes the app ID. So it is not exactly the task ID that is displayed in the UI or available in the API.

It is available in container and non-container contexts, though. Or what do you mean by that?

Just note that a new task ID is assigned to every newly started task. So if the task fails and is restarted or you upgrade the app, you get new task IDs. So it is probably not suitable for your needs.

As is, Marathon is a framework for _stateless_ long running jobs and does not have good support for stateful services. #1242 might be interesting to you and there is some upcoming work on dynamic reservations which will lead to better support of stateful services.

**Comment by kolloch** [comment]
Oh, I am sorry, the `MESOS_TASK_ID` should be the same id as exposed in the UI -- including the prefix indicating the app. Sorry for that.

**Comment by aquamatthias** [comment]
@jvaleo you are looking for MESOS_TASK_ID. That variable is available, when the task starts. A solution to the logging problem could be a logging aggregator (flume, logstash)?
I close this ticket, since I see no action item. Please reopen, if I missed something.

**Comment by jvaleo** [comment]
@aquamatthias The issue is that MESOS_TASK_ID is only exposed inside of the container and not to Marathon. I need to be able have an environment variable which is dynamic in my Marathon application definition which can be interpreted when the task in launched. So if MESOS_TASK_ID were exposed it would look something like this:
```
 "volumes": [
            {
                "containerPath": "/var/log/$MESOS_TASK_ID",
                "hostPath": "/var/log/$MESOS_TASK_ID",
                "mode": "RW"
            }
```

If MESOS_TASK_ID == service.1.2.765.9314b29a-65f8-11e5-b923-56847afe9799 then the mounts would end up being /var/log/service.1.2.765.9314b29a-65f8-11e5-b923-56847afe9799:/var/log/service.1.2.765.9314b29a-65f8-11e5-b923-56847afe9799

**Comment by jvaleo** [comment]
Never mind, I figured out a solution

**Comment by wzhx78** [comment]
Hi jvaleo, what's your solution? can you share with us?

**Comment by PHPCEO** [comment]
@jvaleo could you please add your solution to this thread?

**Comment by duffqiu** [comment]
Hi, how to use the dynamic volume for docker? and which release does contain it?
Thanks!

**Comment by AI-PaaS** [comment]
+1, how?

**Comment by AI-PaaS** [comment]
+1

**Comment by junneyang** [comment]
+1

**Comment by arunkabraham** [comment]
@jvaleo could you please share your solution?
