### ISSUE TITLE
Could not determine the current leader

### ISSUE THREAD

**Issue by Painyjames** [mesosphere/marathon#2260]
I'm in this situation in which I got two masters and four slaves in mesos. All of them are running fine. But when I'm trying to access marathon I'm getting the 'Could not determine the current leader' error. I got marathon in both masters (117 and 115). This is basically what I'm running to get marathon up:

```
java -jar ./bin/../target/marathon-assembly-0.11.0-SNAPSHOT.jar --master 172.16.50.117:5050 --zk zk://172.16.50.115:2181,172.16.50.117:2181/marathon
```
Could anyone shed some light over this?

**Comment by Painyjames** [comment]
Oh my... it was a wrong setup on zookeeper.

**Comment by simoneroselli** [comment]
Hi, I get this error trying to deploy Marathon as Docker container on a dedicated Mesos slave. It's using a remote Zookeeper, running on 3 Mesos master. 

If I run Marathon directly from the slave itself (package), everything is fine.

With the same configuration and same package but running inside a container, I get:

"Problem accessing /. Reason:

    Could not determine the current leader"

 * Tried with both "host" and "bridge" Docker network mode
 * Zookeeper and Mesos master are perfectly reachable from inside the container
 * Zookeeper storage path is present for the new marathon  

Thanks
