### ISSUE TITLE
Task Health no longer displayed on app page

### ISSUE THREAD

**Issue by mindscratch** [mesosphere/marathon#2261]
In the UI, when clicking on an app you get a list of tasks. In versions prior to 0.10, there was a "health" column that showed a circle indicating the status of the task.

In 0.10.x, this column is no longer displayed. What this intentional? If a task becomes unhealthy, it's useful to know which one to help with investigating what might be going on with that task.

**Comment by aldipower** [comment]
Hey! Yes, that was a bug in 0.10 and is already fixed in the upcoming 0.11 release.
