### ISSUE TITLE
Link "Mesos details" is broken

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2266]
Go the task details page of any task and click on the link "Mesos Details" which links to the Mesos Slave UI where the task is running on. The link contains a two slashes right behind the IP where it should be just one:

Current result:
http://172.18.6.178:5050//#/slaves....
Expected result:
http://172.18.6.178:5050/#/slaves....

Marathon 0.12.0
Mesos 0.25.0

Btw.: with Mesos version 0.23.0 the link worked even with the two slashes.

**Comment by janisz** [comment]
Fixed here https://github.com/mesosphere/marathon-ui/pull/216

**Comment by janisz** [comment]
This could be closed

**Comment by mwasn** [comment]
Thanks @janisz !
