### ISSUE TITLE
Marathon scheduler default binding

### ISSUE THREAD

**Issue by michiroth** [mesosphere/marathon#2273]
Marathon scheduler binding uses the following hierarchy:

machine hostname resolvable -> marathon binding to resolved address
machine hostname resolvable, LIBPROCESS_IP set in env -> marathon binding to resolved address
machine hostname not resolvable, LIBPROCESS_IP set in env -> marathon binding to LIBPROCESS_IP
machine hostname not resolvable, LIBPROCESS_IP not set in env -> marathon binding to nothing

A reasonable default (e.g. 127.0.0.1) would be helpful in the last case so that marathon starts in each case.

**Comment by aquamatthias** [comment]
Hey @michiroth  which version of marathon you are using?

**Comment by aquamatthias** [comment]
Hey @michiroth the LIBPROCESS_IP handling is completely handled inside libprocess outside of Marathon.
Please report that ticket here: https://issues.apache.org/jira/browse/MESOS

**Comment by michiroth** [comment]
Hi @aquamatthias I've opened https://issues.apache.org/jira/browse/MESOS-2376 a long time ago regarding this issue.

The same problem impacts Mesos Slaves but circumvents it using the --ip flag. This sets the LIBPROCESS_IP env var before libprocess initialization so it succeeds 
(see https://github.com/apache/mesos/blob/master/src/slave/main.cpp#L176).

Marathon always depends on local hostname resolution. As the above mentioned ticket states the FrameWorkInfo should be enhanced so that an ip parameter can be passed to MesosSchedulerDriver and LIBPROCESS_IP env var can be set the same way before libprocess initalization as for mesos slaves.

Maybe some upvote for the Mesos issue helps :)

**Comment by aquamatthias** [comment]
@michiroth Added a comment and voted for that issue. Other than that we are planning to switch to the mesos HTTP API anyways, so this problem will be solved then.

**Comment by michiroth** [comment]
:+1:
