### ISSUE TITLE
Standardise lowercase / uppercase and trailing full stop in server-side error messages.

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2277]
The error messages returned by the API are inconsistent in casing and in sentence termination.

![image](https://cloud.githubusercontent.com/assets/1078545/9956797/c8cfd876-5dfb-11e5-97f5-d5c26cc27b92.png)

vs 

![image](https://cloud.githubusercontent.com/assets/1078545/9956800/cd430356-5dfb-11e5-97d0-26050a1f3f86.png)

mesosphere/marathon-ui#209

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3324. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
