### ISSUE TITLE
#209 0 values in ports field are stripped

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2278]
A more serious issue: `0` values entered into the `ports` field are stripped.

Here's a table of field value against the value set in the app config:
```
| Field value   | Config value | Correct |
|---------------|--------------|---------|
|               | 0            | True    |
| 0             | undefined    | False   |
| 0, 0          | undefined    | False   |
| 8080          | 8080         | True    |
| 8080, 8081    | 8080, 8081   | True    |
| 8080, 0       | 8080         | False   |
| 8080, 0, 8081 | 8080, 8081   | False   |
```

Here's a video demonstrating the above:
http://cl.ly/2i3z2D193y3v

**Comment by philipnrmn** [comment]
I believe this to be fixed by https://github.com/mesosphere/marathon-ui/commit/f9fe10c7adece096dbc6225c7ee041b5c354ce9f

Can we review this please?

**Comment by aldipower** [comment]
Fixed by you!
