### ISSUE TITLE
Automate Universe and Multiverse Packaging

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2281]
Each Marathon RC should be automatically added to the Multiverse repo (https://github.com/mesosphere/multiverse/)

Each Marathon stable release should be automatically added to the Universe repo (https://github.com/mesosphere/universe/)

related to #2251

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3629. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
