### ISSUE TITLE
Refactor UI messages into constants as introduced in #299

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2288]
This PR introduced a Messages constant. We should extract all messages to follow the same pattern.

https://github.com/mesosphere/marathon-ui/pull/229

**Comment by orlandohohmeier** [comment]
I've extracted all unauthorized and access forbidden messages. For every other UI message we need to introduce a new message component (with message templates) or unify/reduce the message content (eg. "Error fetching version details. Refresh the list to try again." => "Error fetching data. Refresh to try again."). What do you think?

**Comment by pierlo-upitup** [comment]
In general I wouldn't want to lose specificity – in your example, at least the first part of the message should stay as it is. `data` is too vague and I think users should get a more meaningful error message (if not just for better issue-reporting :wink: ).

What if we did similarly to the access error messages, and extracted the `Refresh to try again` part only?

```
`Error fetching version details. ${Messages.RETRY_REFRESH}`
```

?

**Comment by pierlo-upitup** [comment]
As I said, this is just a first pass. What we might end up doing later is a nicer module with a `sprintf` like syntax, so we can pass arguments and build more sophisticated messages. I guess we should return to that part later on, when our `i18n` strategy is clearer.

**Comment by orlandohohmeier** [comment]
Sounds good!

**Comment by pierlo-upitup** [comment]
Closed by https://github.com/mesosphere/marathon-ui/pull/281
