### ISSUE TITLE
/v2/events doesn't play well with JS EventSource

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#2289]
To reproduce:

* Open Marathon UI in a recent browser supporting `EventSource` (I used Chrome 45 for Mac OS)
* Enter the following code
```javascript
var es = new EventSource("http://<marathon_host>:8080/v2/events");
es.onmessage = function (event) {
  console.log(event.data);
};
```
* Even when events occur (like deployments or task restarts), the event handler is never called and nothing gets logged.

If you look in the "Network" tab for the "events" request, it does appear and if you look into the "EventStream" debugging tab, all events seem to be listed in the table.

I also experimented with used `es.addEventListener` instead of `es.onmessage`.

httpie also does work:
```bash
http --stream http://$MARATHON_HOST/v2/events Accept:text/event-stream
```

---

So is the JavaScript code incorrect or is the format of our events incorrect?

**Comment by aldipower** [comment]
All right, I've RTM and found out that you have to be explicit with the event-type.
The EventSource ```onmessage```-handler is only triggered, if the is _no_ ```event:```-field given in the stream. Marathon is fortunately explicit by this and defines all it's events.
So listening explicitly to this event-types works like this:
```
eventStream.addEventListener("my_great_event", (message) => console.log(message));
```

**Comment by kolloch** [comment]
Thx!
