### ISSUE TITLE
Using docker w/ application groups

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2292]
About this page:
https://mesosphere.github.io/marathon/docs/application-groups.html

Does this work with docker containers? @swartzrock would like to have a group of 2 docker containers which are scheduled at the same time. Can you do this now? Please add docs that show in detail how to do this!

https://mesosphere.atlassian.net/browse/MARATHON-318

**Comment by kolloch** [comment]
@swartzrock What do you mean by "scheduled at the same time?" Please elaborate. What did you try? What do you want to achieve? What is your objective? Marathon has no support for colocating containers on the same host.

**Comment by shiveshr** [comment]
@kolloch i think what swartzrock is referring to is a pod (ref: kubernetes) like semantic with docker containers to be supported in marathon. Groups obviously does not support this notion. But it would be great if such notion could be built.

**Comment by shiveshr** [comment]
also, i was trying to look at the jira ticket for more details on the issue but cant figure out how to log-in/sign up for it. could someone please help. 
thanks
shivesh

**Comment by mwasn** [comment]
Sorry, this is just a Mesosphere internal JIRA. All information have been copied to this ticket. It just for referencing.

**Comment by junneyang** [comment]
any update? thanks
