### ISSUE TITLE
Implement consistent behaviour on 409 (Conflict) to force deployments

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2298]
In https://github.com/mesosphere/marathon-ui/pull/202/files we implement the `force` action upon a `409` response from the REST API. We should do similarly whenever the UI is returning an error suggesting to use the `force=true`, as is the case when editing an app's definition which is currently being deployed:

![screen shot 2015-09-23 at 13 57 27](https://cloud.githubusercontent.com/assets/1078545/10044703/4e2c7f92-61fd-11e5-8c9d-9cbb481493fe.png)

**Comment by Raffo** [comment]
Definitely, now having a look at some marathon internals for fun and profit, but I could to the same I already did in https://github.com/mesosphere/marathon-ui/pull/202/files

**Comment by pierlo-upitup** [comment]
Hi @Raffo – thanks for jumping in! That would be amazing. 

In terms of UI, it might make sense to simply swap the `Change and deploy configuration` button text with `Force change and deploy configuration` to avoid stacking up modal dialogs – what do you think?

**Comment by Raffo** [comment]
@pierlo-upitup I would also avoid stacking up modal dialogs. Are you proposing of forcing changes by default? I would not like to do that as it would be inconsistent with the implementation in case of scaling. We could keep the message as it is, but add something like "press again to force change" or something similar. What do you think?

**Comment by pierlo-upitup** [comment]
Exactly – I suggest to replace the button text **after** the error is shown, to indicate the "press again" to force a new deployment.

**Comment by Raffo** [comment]
I would only change the text of the message message (the one in red in the picture above) and add "press again to force change" to it. I would not modify the text of the button between user interactions (I think it could be confusing for the users) though.

**Comment by pierlo-upitup** [comment]
Yeah, I see how that might end up being confusing. 

On the other hand that error message comes from the API as-is, so we will probably have to just use a custom message as you suggest.

**Comment by Raffo** [comment]
In the end it's not different from what we are already doing in https://github.com/mesosphere/marathon-ui/pull/202/files so I see no problems with that.

**Comment by pierlo-upitup** [comment]
Oh yes, I see what you mean. Sure thing!
