### ISSUE TITLE
Writes to EntityRepositories should be visible in following reads

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#2299]
Our code assumes that writes are visible for any read following a write.

But it turns out that Zookeeper writes are not immediately visible for subsequent reads. "Consistency Guarantees - ZooKeeper is a high performance, scalable service. Both reads and write operations are designed to be fast, though reads are faster than writes. The reason for this is that in the case of reads, ZooKeeper can serve older data, which in turn is due to ZooKeeper's consistency guarantees." (https://zookeeper.apache.org/doc/trunk/zookeeperProgrammers.html)

This should probably be handled:

* by serving read requests from memory (this is consistent because we only have one leader)
* using the sync request when a new leader starts up to make sure that it sees all prior writes

We will first implement this for tasks: https://github.com/mesosphere/marathon/issues/462

Symptoms:

* Deployments and Apps are not immediately visible after the PUT creating the deployment (see #1407)
* other races

**Comment by aquamatthias** [comment]
Fixed by #2411
