### ISSUE TITLE
Extend README.md by links to knowledge base and Marathon google group

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2303]
- [ ] Link to the Mesosphere Knowledge Base (https://support.mesosphere.com/hc/en-us)
- [ ] Please don´t use GitHub issues for discussing a specific problem, but open up a discussion on Google Groups (https://groups.google.com/forum/#!forum/marathon-framework)
- [ ] If you want to report a bug, please respect our checklist (logs, json app definition, labels etc.)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2984. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
