### ISSUE TITLE
Review and rewrite the "Getting Started" page 

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2304]
Ensure that first time user of Marathon do have a great user experience when the follow the documentation on http://mesosphere.github.io/marathon/docs/

Add common pitfalls and describe how to avoid them.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3635. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
