### ISSUE TITLE
Task counts are invalid

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#2311]
I'm not a math expert, but when app has 24 tasks and 3 of them are healthy, app still has 3 tasks, not 27.

![image](https://cloud.githubusercontent.com/assets/89186/10101605/91f86674-6391-11e5-9207-b4a60b15843f.png)

Before this there were 25 tasks, 25 healthy, 50 total. I did "Kill and scale" on one task.

Another issue here: why did 21 task suddenly lost health status? The do not seem to recover it.

Marathon 0.11.0-RC4.

**Comment by meichstedt** [comment]
Hi Bobrik,
this has been fixed in #2252. We will check if/why this has not been merged into 0.11.0-RC4
regards
Matthias

**Comment by bobrik** [comment]
:+1:

**Comment by bobrik** [comment]
What about lost health check statuses, were they fixed too?

**Comment by aldipower** [comment]
The wrong tasks count is fixed in 0.11.1 and the upcoming 0.12.
This ticket could be closed.
The health checks statuses aren't related to the tasks count.

**Comment by bobrik** [comment]
Should I make another ticket about health check statuses?

**Comment by aldipower** [comment]
Maybe it makes sense to hook into this?
https://github.com/mesosphere/marathon/issues/2314
Not sure, otherwise you could open another ticket for that.
Thank you very much.
