### ISSUE TITLE
Health state gets lost sporadically

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#2314]
Multiple users seem to report that the health state is not preserved in the context of upgrades.

See #2311 and #2234.

We assumed that happens if you migrate from really old versions but maybe the problem is more wide-spread.

I could imagine that reconciliation does not preserve health status or something like that.

We have verified the following and not found errors:

* Health state of an app with command health checks is preserved when Marathon restarts.
* Health state of an app with command health checks is preserved when migrating from 0.10.x to 0.11.x.

**Comment by bobrik** [comment]
I have issues when on 0.11.0-RC4 marathon restart does not fix the issue, HTTP health checks:

![image](https://cloud.githubusercontent.com/assets/89186/10169184/d309859c-66c7-11e5-9f63-86ffb9937f1f.png)

**Comment by kolloch** [comment]
Unfortunately, I cannot reproduce this easily. Any ideas what I could do differently, @bobrik ?

I tried to reproduce this with `COMMAND` health checks:

```javascript
{
    "cmd": "python -m SimpleHTTPServer $PORT",
    "cpus": 0.1,
    "disk": 0.0,
    "healthChecks": [
        {
            "command": {
                "value": "curl -f -X GET http://$HOST:$PORT0/"
            },
            "gracePeriodSeconds": 10,
            "ignoreHttp1xx": false,
            "intervalSeconds": 10,
            "maxConsecutiveFailures": 3,
            "path": "/",
            "portIndex": 0,
            "protocol": "COMMAND",
            "timeoutSeconds": 3
        }
    ],
    "id": "/test",
    "instances": 1,
    "mem": 16.0,
    "ports": [
        10000
    ]
}
```

and with `HTTP` health checks:

```javascript
{
    "cmd": "python -m SimpleHTTPServer $PORT",
    "cpus": 0.1,
    "disk": 0.0,
    "healthChecks": [
        {
            "gracePeriodSeconds": 10,
            "ignoreHttp1xx": false,
            "intervalSeconds": 10,
            "maxConsecutiveFailures": 3,
            "path": "/",
            "portIndex": 0,
            "protocol": "HTTP",
            "timeoutSeconds": 3
        }
    ],
    "id": "/test-http",
    "instances": 1,
    "mem": 16.0,
    "ports": [
        10000
    ]
}
```

- start marathon 0.10.x
- start app with `COMMAND` health checks (one instance)
- start app with `HTTP` health checks (one instance)
- start marathon 0.11.0
- scale up to 5
- all tasks become green after a while

**Comment by kolloch** [comment]
I also tried restarting Marathon.

Note, though, that Marathon took a while to start the health checks and show them as healthy after restarting.

**Comment by kolloch** [comment]
![screen shot 2015-10-05 at 15 01 20](https://cloud.githubusercontent.com/assets/339354/10281038/092846d2-6b72-11e5-99f6-b39ebbd48cc0.png)

**Comment by bobrik** [comment]
This is not easily reproduced, I've only seen that once and already restarted an app that had this issue. What should I save to help you debug it next time it happens?

**Comment by kolloch** [comment]
@bobrik: I would say 

* the Marathon log (at least from the restart on that exhibited the problem). You can grep for the task id prefix for the app id in question in the Marathon log before the restart and/or in the Mesos Master log. I would think that the Mesos log is not required in this case, though. 
* the app id in question
* Mesos `state.json` might come in handy

**Comment by gomes** [comment]
Hi guys, I think I can point the cause, I have the same problem and I saw this in the log:
```
[2015-10-28 21:43:16,764] INFO Removing health check for app [/proxy/v1] and version [2015-10-28T23:37:09.492Z]: [HealthCheck(Some(/health),HTTP,0,None,5 seconds,10 seconds,10 seconds,1,false)] (mesosphere.marathon.health.MarathonHealthCheckManager$$EnhancerByGuice$$4dd4f13e:85)
```
Looking at the code, a condition where after the reconciliation, if the task version != app.version, it removes the health check:

https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/health/MarathonHealthCheckManager.scala#L126 

So, if you scale your app and a new app version is generated, after the reconciliation, the health check will be disabled

**Comment by kolloch** [comment]
Hey @gomes, thanks for your analysis! That is a likely cause.

**Comment by kolloch** [comment]
Its easy to reproduce if you start Marathon with a low reconciliation inteval (e.g. `--reconciliation_interval 10000`) and then scale up an app. Thanks again, @gomes .

**Comment by gomes** [comment]
@kolloch I’m glad to help
