### ISSUE TITLE
Get app's hostname from Rest API

### ISSUE THREAD

**Issue by 208rishabh** [mesosphere/marathon#2331]
I want to use Marathon's Rest API to get the hostname of a particular application.

curl -XGET http://IP:8080/v2/apps/app_name/tasks gives a list of details including hostname. However I want the output to be only the hostname. Does something exist for this?

**Comment by meichstedt** [comment]
Have a look at [jq](https://stedolan.github.io/jq/). Basically, you want to parse the JSON output and filter for the values of interest. That'd be something like `<curl or httpie request> | jq '.tasks[].host'`

**Comment by 208rishabh** [comment]
Yes , i found it. Thanks.
The exact command is : curl -s "<marathon IP:port>/v2/apps/<appId>/tasks" | jq '.tasks[0] | "\(.host):\(.ports[0])"'
