### ISSUE TITLE
Switch logging backend to logback

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#2335]
We'd like to switch slf4j's logging backend from log4j to logback.

ZooKeeper (started by our integration tests) depends directly on log4j classes not implemented by slf4j's log4j bridge. So simply excluding the log4j dependencies and adding logback breaks our integration tests.

**Comment by gkleiman** [comment]
See mesosphere/chaos#42 and #2301.

**Comment by janisz** [comment]
Is this still valid?

**Comment by jasongilanfarr** [comment]
Already use logback
