### ISSUE TITLE
"No pseudo-deterministic assignment of host ports anymore" - Should be labeled as breaking change?

### ISSUE THREAD

**Issue by nemothekid** [mesosphere/marathon#2336]
Maybe my use case is a little unorthodox, but I have an app.json like so:

```json
{
  "args": ["-production", "-n=64", "-advertise=file:///var/lib/cm/ip"],
  "env":{
  },
  "constraints": [
    [
      "group",
      "CLUSTER",
      "worker"
    ],
    ["hostname", "UNIQUE"]
  ],
  "container": {
    "docker": {
      "image": "$DOCKER_IMAGE",
      "network": "BRIDGE",
      "parameters": [
        {"key":"publish", "value": "3333:3333"},
        {"key":"publish", "value": "7946:7946"},
        {"key":"publish", "value": "7946:7946/udp"}
      ]
    },
    "type": "DOCKER",
    "volumes": [{
      "containerPath":"/var/lib/cm/ip",
      "hostPath":"/etc/mesos-slave/ip",
      "mode":"RW"
    }]
  },
  "healthChecks":[
    {
      "protocol": "HTTP",
      "path": "/status/",
      "gracePeriodSeconds": 10,
      "intervalSeconds": 10,
      "portIndex": 0,
      "timeoutSeconds": 10,
      "maxConsecutiveFailures": 3
    }
  ],
  "cpus": 0.5,
  "mem": 128,
  "ports": [
    3333,
    7946
  ],
  "maxLaunchDelaySeconds": 30,
  "shell": false,
  "upgradeStrategy": {
    "minimumHealthCapacity":0.5,
    "maximumOverCapacity":0
  }
}
```

I don't use the `hostPort` setting because I need to bind both UDP and TCP - similarly I would suspect this bug would occur if I used `HOST` mode networking. 

In past versions of marathon, when setting `healthCheck`'s `portIndex` to 0, it would use `ports[0]` as the checking port. Now that host port assignments are random, this port index is now random meaning the health checks now fail. Them failing causes marathon to constantly kill and restart these tasks. 

What you need now is `"requirePorts":true`, but given that you didn't need this before it does break past setups that are valid. Even worse, the bug doesn't happen until you relaunch the tasks, we had upgraded a couple hours ago thought everything was fine, then suddenly some of our tasks couldn't start without failing. We chalked it up to bad app behavior before I had noticed the ports marathon was assigning to these tasks.

**Comment by gkleiman** [comment]
Release notes updated.
