### ISSUE TITLE
Image v0.11.0 with errors

### ISSUE THREAD

**Issue by rafaelcapucho** [mesosphere/marathon#2337]
Hello,

I'm deploying [1] with the following script:

docker run -d \
-e "MARATHON_HOSTNAME=${HOST_IP}" \
-e "MARATHON_HTTPS_ADDRESS=${HOST_IP}" \
-e "MARATHON_HTTP_ADDRESS=${HOST_IP}" \
-e "MARATHON_MASTER=zk://atlas001:2181,atlas002:2181,atlas003:2181/mesos" \
-e "MARATHON_ZK=zk://atlas001:2181,atlas002:2181,atlas003:2181/marathon" \
-p 8080:8080 \
-v /tmp:/tmp \
--name="marathon" \
--restart="always" \
mesosphere/marathon

The container are created properly, but it don't work and looking at the logs I see the messages in the attached image.

Thank you!

[1] - https://hub.docker.com/r/mesosphere/marathon/tags/

![logo15](https://cloud.githubusercontent.com/assets/163367/10240121/51fcdb46-68ae-11e5-91d9-43405ca94ffc.png)

**Comment by meichstedt** [comment]
Thanks for reporting this – we'll look into the issue asap.

**Comment by kolloch** [comment]
Hey @rafaelcapucho,

can you exec the connectivity test from your docker container? It might be a routing issue. alternatively, you can try with `--network=host` (or similar).

```
docker run -i -t --entrypoint /bin/bash mesosphere/marathon:v0.11.0 -l
root@3e008893da2a:/marathon# apt-get install netcat
...
root@3e008893da2a:/marathon# netcat atlas001 2181
```

**Comment by rafaelcapucho** [comment]
Hi @kolloch,

It returns:
```
root@c507d86ff9a2:/marathon# netcat atlas001 2181                                                                                                                          
atlas001: forward host lookup failed: Unknown host
```
Starting the container with ```--net="host"```works! or is better the map with ```-v``` my ```/etc/hosts``` ?

Thank you very much.

Also, not related with it but in the logs I can see that favicon isn't found yielding error every request:

![favicon](https://cloud.githubusercontent.com/assets/163367/10251141/514f177a-6905-11e5-86a0-e799d90c2a29.png)

**Comment by gkleiman** [comment]
@rafaelcapucho both approaches should work. If you use `--net="host"`, then you probably don't need to pass `-p 8080:8080`.

The favicon error you see is a result of Firefox requesting a non-existing URL.  Printing the whole stack trace for a 404 might be a little too dramatic, but it is logged at the INFO level, because it is not an unexpected/fatal error.
