### ISSUE TITLE
Application won't start on host (Insufficient resources) after task fails on host

### ISSUE THREAD

**Issue by nemothekid** [mesosphere/marathon#2346]
Marathon 0.11.0
Mesos 0.22.1

I have a task with 9 instances that operate with the `["hostname", "unique"] operator.  I noticed on a machine one of these tasks failed (there was a network hiccup and the application killed itself), and marathon refuses to relaunch the task on the same host.

```
Oct  2 19:43:55 master-01 marathon[3893]: The conflicting constraints are: [field: "hostname"
Oct  2 19:43:55 master-01 marathon[3893]: operator: UNIQUE
Oct  2 19:43:55 master-01 marathon[3893]: ] (mesosphere.mesos.ResourceMatcher$:86)
Oct  2 19:43:55 master-01 marathon[3893]: [2015-10-02 19:43:55,303] INFO Offer [20151002-093939-935624970-5050-12611-O73477]. Insufficient resources for [/geard] (need cpus=0.5, mem=128.0, disk=0.0, ports=([3333, 7946] required), available in offer:
Oct  2 19:43:55 master-01 marathon[3893]: id {
Oct  2 19:43:55 master-01 marathon[3893]:   value: "20151002-093939-935624970-5050-12611-O73477"
Oct  2 19:43:55 master-01 marathon[3893]: }
Oct  2 19:43:55 master-01 marathon[3893]: framework_id {
Oct  2 19:43:55 master-01 marathon[3893]:   value: "20150926-223547-935624970-5050-9387-0000"
Oct  2 19:43:55 master-01 marathon[3893]: }
Oct  2 19:43:55 master-01 marathon[3893]: slave_id {
Oct  2 19:43:55 master-01 marathon[3893]:   value: "20150927-191920-197427466-5050-1380-S10"
Oct  2 19:43:55 master-01 marathon[3893]: }
Oct  2 19:43:55 master-01 marathon[3893]: hostname: "10.129.196.35"
Oct  2 19:43:55 master-01 marathon[3893]: resources {
Oct  2 19:43:55 master-01 marathon[3893]:   name: "ports"
Oct  2 19:43:55 master-01 marathon[3893]:   type: RANGES
Oct  2 19:43:55 master-01 marathon[3893]:   ranges {
Oct  2 19:43:55 master-01 marathon[3893]:     range {
Oct  2 19:43:55 master-01 marathon[3893]:       begin: 1
Oct  2 19:43:55 master-01 marathon[3893]:       end: 65535
Oct  2 19:43:55 master-01 marathon[3893]:     }
Oct  2 19:43:55 master-01 marathon[3893]:   }
Oct  2 19:43:55 master-01 marathon[3893]:   role: "*"
Oct  2 19:43:55 master-01 marathon[3893]: }
Oct  2 19:43:55 master-01 marathon[3893]: resources {
Oct  2 19:43:55 master-01 marathon[3893]:   name: "cpus"
Oct  2 19:43:55 master-01 marathon[3893]:   type: SCALAR
Oct  2 19:43:55 master-01 marathon[3893]:   scalar {
Oct  2 19:43:55 master-01 marathon[3893]:     value: 1.0
Oct  2 19:43:55 master-01 marathon[3893]:   }
Oct  2 19:43:55 master-01 marathon[3893]:   role: "*"
Oct  2 19:43:55 master-01 marathon[3893]: }
Oct  2 19:43:55 master-01 marathon[3893]: resources {
Oct  2 19:43:55 master-01 marathon[3893]:   name: "mem"
Oct  2 19:43:55 master-01 marathon[3893]:   type: SCALAR
Oct  2 19:43:55 master-01 marathon[3893]:   scalar {
Oct  2 19:43:55 master-01 marathon[3893]:     value: 245.0
Oct  2 19:43:55 master-01 marathon[3893]:   }
Oct  2 19:43:55 master-01 marathon[3893]:   role: "*"
Oct  2 19:43:55 master-01 marathon[3893]: }
Oct  2 19:43:55 master-01 marathon[3893]: resources {
Oct  2 19:43:55 master-01 marathon[3893]:   name: "disk"
Oct  2 19:43:55 master-01 marathon[3893]:   type: SCALAR
Oct  2 19:43:55 master-01 marathon[3893]:   scalar {
Oct  2 19:43:55 master-01 marathon[3893]:     value: 17699.0
Oct  2 19:43:55 master-01 marathon[3893]:   }
Oct  2 19:43:55 master-01 marathon[3893]:   role: "*"
Oct  2 19:43:55 master-01 marathon[3893]: }
Oct  2 19:43:55 master-01 marathon[3893]: attributes {
Oct  2 19:43:55 master-01 marathon[3893]:   name: "group"
Oct  2 19:43:55 master-01 marathon[3893]:   type: TEXT
Oct  2 19:43:55 master-01 marathon[3893]:   text {
Oct  2 19:43:55 master-01 marathon[3893]:     value: "worker"
Oct  2 19:43:55 master-01 marathon[3893]:   }
Oct  2 19:43:55 master-01 marathon[3893]: }
Oct  2 19:43:55 master-01 marathon[3893]:  (mesosphere.mesos.TaskBuilder:69)
```

Note that there are no other tasks running on this machine, and the hostname, which is an IP, is unique to this task.  I've tried restarted the mesos-slave, rebooting the slave and deleting the /tmp/mesos.../latest folder which had no effect.

**Comment by nemothekid** [comment]
Now seeing it on a much more aggressive scale whereas marathon refuses to relaunch a large number of applications.

![screen shot 2015-10-02 at 9 26 15 pm](https://cloud.githubusercontent.com/assets/940094/10261435/4fc47fca-694c-11e5-846c-694c0c231922.png)

(I've suspended some non critical applications to reduce log spam and to try and get everything back up - but those suspended applications were stuck waiting as well).

AFAICT what happened was

1. Marathon's (and Mesos') Zookeeper connection timed out (So the ZK node went down)
2. There was a marathon leadership change
3. Nothing starts again.

Also all the Docker tasks are still running, however they are not registered in mesos, and killing the tasks does not resolve the "hostname" constraint issue.

**Comment by gkleiman** [comment]
Is it still possible to get the logs from Marathon Leaders and Mesos Masters shortly before/after the ZK failover? 

Marathon does a task reconciliation shortly after taking up leadership, so it should have detected that the tasks were LOST and tried to reschedule them.

**Comment by gkleiman** [comment]
This might be related to #2353.

**Comment by kolloch** [comment]
@nemothekid That looks bad.

It generally takes 10min until Mesos/Marathon decide that tasks are lost if the slave connection got lost. I am not sure if that is the reason.

Does Mesos still think that the tasks are running? For debugging this, we do need at least:

* The master state.json (http://leader.mesos:5050/state.json)
* The Marathon Logs
* The Mesos Master Logs

And just to make sure that we investigate the right thing, at least one concrete app id where things fail.

**Comment by nemothekid** [comment]
I'll get to work on producing some logs or I'lll upload the old logs. FWIW, after trying to mitigate this issue over the weekend I found that just running a single marathon instance prevented the issue. (I used to run 3, with 3 mesos master and 3 zookeeper nodes).

Now when ZK goes down/times out I don't lose all my tasks, so I'm guessing it might have an issue to do with marathon's ha.

**Comment by nemothekid** [comment]
The issue happened again with a single task on a single marathon instance.

1. The Zookeeper cluster couldn't be reached (so both marathon and mesos couldn't talk to zookeeper).
2. There was a mesos re-election 
3. Some tasks (all on the same app this time) were lost to mesos/marathon (atleast I can't see it in the interface)

Here is the marathon + mesos logs (Sorry I log both to syslog, the mesos re election occurs at `Oct  7 00:46:30 master-01 mesos-master[17250]: I1007 00:46:30.474894`)

Marathon Master logs (master-01): https://clbin.com/EFZ1a 
Mesos Master logs (master-02): https://s3-us-west-1.amazonaws.com/assets.channelmeter.com/mesos-master.txt
State: https://clbin.com/2h3h3

You can see that both `/web-prod` and `/geard` are stuck on resources issues, however the docker tasks are still running.

**Comment by nemothekid** [comment]
Looks like there might also be an issue where the `mesos-executor` hangs and keeps the resources allocated even though the container is dead

```
root@ms-worker-05:~# ps -AFwww | grep mesos
root     14164     1  0  1111   164   0 Oct03 ?        00:00:00 sh -c /usr/libexec/mesos/mesos-executor --override /bin/sh -c 'exit `docker wait mesos-da27592e-c5d4-414a-b8f8-130b73bd99f0`'
root     14168 14164  0 150789 2628   0 Oct03 ?        00:00:00 /usr/libexec/mesos mesos-executor --override /bin/sh -c exit `docker wait mesos-da27592e-c5d4-414a-b8f8-130b73bd99f0`
root     15932     1  2 174617 29216  0 18:47 ?        00:00:00 /usr/sbin/mesos-slave --master=zk://zoo1:2181/mesos --log_dir=/var/log/mesos --containerizers=docker,mesos --docker_stop_timeout=180secs --executor_registration_timeout=10mins --hostname=10.129.196.41 --ip=10.129.196.41 --attributes=group:worker --resources=ports:[1-65535]
root     15955 15932  0  1798   612   0 18:47 ?        00:00:00 logger -p user.info -t mesos-slave[15932]
root     15956 15932  0  1798   700   0 18:47 ?        00:00:00 logger -p user.err -t mesos-slave[15932]
```

```
root@ms-worker-05:~# docker ps -a | grep  mesos-da27592e-c5d4-414a-b8f8-130b73bd99f0
faea5cb4d74b        docker.channelmeter.com/geard:production-5e394dfaaad625f8cbcec23ffb6fb3f2a9027da2   "/go/bin/geard -prod   5 days ago          Exited (0) 5 days ago                       mesos-da27592e-c5d4-414a-b8f8-130b73bd99f0   
```

**Comment by nemothekid** [comment]
Actually think that last message is unrelated. I'm trying to run with `--disable_revive_offers_for_new_apps` if that fixes it.

Could it be possible

1. Marathon rejects the offer (described in my first post) because the executor hasn't quit yet.
2. There are no other offers for this particular task that matches
3. Because marathon wasn't able to get a suitable offer in `--revive_offers_repetitions` * `--min_revive_offers_interval` it gives up on launching the task?

**Comment by nemothekid** [comment]
`--disable_revive_offers_for_new_apps` didn't solve the problem.

The observed issue I'm seeing is twofold. 

1. Zookeeper is shutting down (not sure why - `2015-10-09 16:06:55,558 - INFO  [QuorumPeer[myid=1]/0:0:0:0:0:0:0:0:2181:Follower@166] - shutdown called` and doesn't restart for several seconds
1. Both mesos and marathon are partitioned from ZK for some time.
1. When ZK comes back, Marathon doesn't reclaim all the tasks.
1. Marathon tries to restart the tasks on slaves that already have the tasks running, but for some reason marathon doesn't register that the task is already running
1. Marathon has a conflict with itself on this task.
1. If I restart Marathon everything goes back to normal.

Here's a simpler log, over ~4 minutes on the logs for mesos-master and marathon.

https://gist.github.com/nemothekid/61ba7c994cc5a3d284bf

**Comment by gkleiman** [comment]
I just analyzed the logs in https://gist.github.com/nemothekid/61ba7c994cc5a3d284bf.

The mesos-master logs are not useful, because the process is always a follower during those ~4 minutes.

The Marathon logs show that after the Mesos Masters recover from the partition, the leader reports that all but one of the geard tasks have failed.

Marathon will then try to start more tasks, but it only gets one offer, which comes from the slave that is already running geard.

If you say that there are more than one geard processes running after the Mesos Master recover, then there might be a Mesos bug, that makes it wrongly send status updates saying that those tasks failed. I'd recommend looking into the logs of the Mesos Master leader.

**Comment by nemothekid** [comment]
My apologies for including the wrong master - I can't seem to figure out who was master during that time. The issue happened again and again two processes failed to come up, `geard` and `web-prod`. I can't figure out why its these two processes (I thought it may have been a networking issue, but the fact that `web-prod` goes down and no other apps on the same machine confuses me).

mesos 1 / marathon: https://gist.github.com/nemothekid/45e6707aa4449bda68d8
mesos 2: https://gist.github.com/nemothekid/65436b4a78f55121fdbc
mesos 3: https://gist.github.com/nemothekid/03869a9e60cb5df9b0f1 

Mesos was re-elected (mesos 01 became master) at Oct 13 18:08:36 and I think the previous master was mesos 3. From mesos 3:

```
Oct 13 18:08:22 master-03 mesos-master[30754]: W1013 18:08:22.406919 30771 group.cpp:456] Timed out waiting to reconnect to ZooKeeper. Forcing ZooKeeper session (sessionId=250621e7d7d0007) expiration
Oct 13 18:08:22 master-03 mesos-master[30754]: I1013 18:08:22.407146 30771 group.cpp:472] ZooKeeper session expired
Oct 13 18:08:22 master-03 mesos-master[30754]: I1013 18:08:22.407424 30773 contender.cpp:196] Membership cancelled: 1074
Oct 13 18:08:22 master-03 mesos-master[30754]: Lost leadership... committing suicide!
```

-----

Edit: I think I might be chasing a different issue than the one I saw on 2 weeks ago. In this case the application dies and as marathon tries to restart it, it takes a long time starting up. In any case the mesos-task was properly marked as `_failed`

**Comment by nemothekid** [comment]
I've confirmed that this should be #2353, so this issue is a duplicate of that.
