### ISSUE TITLE
Minimize task restarts on configuration changes

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#2348]
Summary:

If you only change the constraints of an app, only restart tasks that violate the new constraint.

Also be smarter about upgradeStrategy, backoff, health checks?

Original text:

Imagine you deployed stateful service on marathon across dozen of nodes and already pushed 20TB of data in it. You used mesos roles, `UNIQUE` constraint and `LIKE` constraint to restrict your service to the set of machines. So far so good.

Whenever you restart any instance, huge expensive rebalancing happens to ensure that data is safely replicated across the cluster.

Now bad things happen: one of the nodes went crazy and decided it's 2000 again and it runs Pentium 3 instead of Xeon from 2013. You decide to take this node out of production quickly by doing "Kill and scale" in Marathon UI. Cluster rebalances and looks good again and you now have time to investigate strange flashbacks of misbehaving node.

Before moving to investigation, you decide make marathon state safer by dropping bad node from `LIKE` constraint. You deploy new app definition and BOOM: all nodes restart in a rolling deployment.

Let's avoid this. I see no reason to restart dozen of nodes if I just removed 1 node from `LIKE` constraint. There is also no reason to redeploy everything if I change health checks, since tasks stay the same.

Mesos 0.24.1, Marathon 0.11.0, but it was like this forever. I tried to find an existing issue, but failed.

**Comment by gkleiman** [comment]
Thanks for reporting this, I added the issue to our backlog.

**Comment by kolloch** [comment]
@bobrik: I changed the title and added a summary to the ticket. If you dislike my changes, complain, please ;)

**Comment by bobrik** [comment]
Not just constraints, health checks as well. Also upgrade strategy. Basically anything that doesn't require restarting running tasks.

**Comment by kolloch** [comment]
For COMMAND health checks a restart is necessary. For the rest, you are right. I guess, it would be nice to create more focussed issues when we start to work on this, though.

**Comment by bobrik** [comment]
Maybe Mesos itself deserves an issue to prevent restarts on COMMAND health checks changes.

**Comment by janisz** [comment]
@bobrik have you opened an issue on Mesos Jira for this?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3417. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
