### ISSUE TITLE
Marathon trigger happy with killing overdue tasks

### ISSUE THREAD

**Issue by F21** [mesosphere/marathon#2349]
Recently switched from 0.10.1 to 0.11.0 and noticed that marathon is too trigger happy with killing overdue tasks which means that nothing gets launched, because marathon kills the tasks after they have been staging for just a few seconds.

Mesos is 0.24.1 and is launched with the `MESOS_EXECUTOR_REGISTRATION_TIMEOUT` environment variable set to `60mins`.

Mesos + Marathon is running on a cluster of VMs on my workstation, so it can take a few minutes to download docker containers/other binaries and launch them.

It used to work fine when I was using 0.10.1.

This problem occurs for all tasks I try to launch. For example, here's one I use for launching elasticsearch-mesos:

```json
{
  "id": "elasticsearch",
  "container": {
    "docker": {
      "image": "mesos/elasticsearch-scheduler:latest",
      "network": "HOST"
    }
  },
  "args": [
    "--zookeeperMesosUrl",
    "zk://master.mesos:2181/mesos",
    "--elasticsearchNodes",
    "1",
    "--elasticsearchDisk",
    "512"
  ],
  "cpus": 0.2,
  "mem": 350.0,
  "env": {
    "JAVA_OPTS": "-Xms128m -Xmx256m"
  },
  "instances": 1,
  "healthChecks": [
    {
      "gracePeriodSeconds": 120,
      "intervalSeconds": 30,
      "maxConsecutiveFailures": 0,
      "path": "/",
      "portIndex": 0,
      "protocol": "HTTP",
      "timeoutSeconds": 5
    }
  ]
}
```

This is what I see in the logs (when attempting to launch kafka-mesos):

```
 [2015-10-05 07:51:20,820] WARN Should kill: Task 'kafka.d7649570-6b35-11e5-8e16-080027600c64' was launched 11s ago and was not confirmed yet (mesosphere.marathon.tasks.TaskTracker$$EnhancerByGuice$$d71
Oct 05 07:51:20 core-01 start[584]: [WARN] [10/05/2015 07:51:20.820] [marathon-akka.actor.default-dispatcher-5] [akka://marathon/user/killOverdueStagedTasks/1] Killing overdue task 'kafka.d7649570-6b35-11e5-8e16-080027600c64'
Oct 05 07:51:24 core-01 start[584]: [2015-10-05 07:51:24,613] INFO Received status update for task kafka.d7649570-6b35-11e5-8e16-080027600c64: TASK_KILLED (Unregistered executor) (mesosphere.marathon.MarathonScheduler$$EnhancerByGuice$$3
Oct 05 07:51:24 core-01 start[584]: [2015-10-05 07:51:24,619] INFO Task kafka.d7649570-6b35-11e5-8e16-080027600c64 expunged and removed from TaskTracker (mesosphere.marathon.tasks.TaskTracker$$EnhancerByGuice$$d7144a84:111)
```

**Comment by gkleiman** [comment]
@F21: Thanks for opening this issue. You can tweak Marathon's timeouts through the `--task_launch_timeout` and `--task_launch_confirm_timeout` flags.

`---task_launch_confirm_timeout` was introduced in v0.11.0 and it might be too aggressive. We'll consider changing the default in the next release.

Please reopen the issue if this comment doesn't help you.
