### ISSUE TITLE
Latest Marathon package doesn't install on Ubuntu 14.04

### ISSUE THREAD

**Issue by ssk2** [mesosphere/marathon#2357]
This is because it depends on the `java8-runtime-headless` package which isn't available for releases older than 14.10. 

Instead, it should be relying on the `openjdk-8-jre` package.

**Comment by gkleiman** [comment]
`openjdk-8-jre` is also not available on Ubuntu 14.04:

```
$ docker run -it --net=bridge ubuntu:10.04 /bin/bash
root@9663e6db334b:/# apt-get update
Hit http://archive.ubuntu.com lucid Release.gpg
Get:1 http://archive.ubuntu.com lucid-updates Release.gpg [198B]
Get:2 http://archive.ubuntu.com lucid-security Release.gpg [198B]
Hit http://archive.ubuntu.com lucid Release
Get:3 http://archive.ubuntu.com lucid-updates Release [185kB]
Get:4 http://archive.ubuntu.com lucid-security Release [58.7kB]
Hit http://archive.ubuntu.com lucid/main Packages
Hit http://archive.ubuntu.com lucid/universe Packages
Get:5 http://archive.ubuntu.com lucid-updates/main Packages [811kB]
Get:6 http://archive.ubuntu.com lucid-updates/universe Packages [357kB]
Get:7 http://archive.ubuntu.com lucid-security/main Packages [627kB]
Get:8 http://archive.ubuntu.com lucid-security/universe Packages [221kB]
Fetched 2261kB in 1s (1537kB/s)
Reading package lists... Done
root@9663e6db334b:/# apt-get install openjdk-8-jre
Reading package lists... Done
Building dependency tree... Done
E: Couldn't find package openjdk-8-jre
root@9663e6db334b:/#
```

**Comment by ssk2** [comment]
Oops, I guess I was missing a backports repo. Anyway, thanks for fixing the
instructions!

**Comment by scalp42** [comment]
@ssk2 @gkleiman any way to not force the dependency on us ? This should be let to the user.

In my example, using Ubuntu 14.04 LTS:

```
The following packages have unmet dependencies:
marathon : Depends: java8-runtime-headless but it is not installable
```

I do **not** want to install the 3rd party PPA as you instruct. Our nodes are provisioned to pull from Oracle directly, yet `marathon` won't install:

```
root@mesos-1:/usr/lib/jvm# java -version
java version "1.8.0_65"
Java(TM) SE Runtime Environment (build 1.8.0_65-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.65-b01, mixed mode)
```

**Comment by ssk2** [comment]
@scalp42 -  can you point us to the installation method you use and I'll investigate further?

**Comment by gkleiman** [comment]
@ssk2, @scalp42: see also my comment on #2384:

>@scalp42 if you have already satisfied the dependency by installing Java 8 without using Ubuntu's pkg system, then you can use equivs-build to make an empty Debian package to register it.

>See http://shallowsky.com/blog/linux/install/blocking-deb-dependencies.html for an example.

**Comment by mlowicki** [comment]
@gkleiman I'm getting:
```
W: Failed to fetch http://ppa.launchpad.net/webupd8team/java/ubuntu/dists/jessie/main/binary-amd64/Packages  404  Not Found
```

**Comment by Poogles** [comment]
@mlowicki You appear to be trying to use a PPA on debian which won't work.

**Comment by selvik** [comment]
Hi @jkleiman 
You've mentioned:
"We have already updated Mesosphere's Download page with instructions on how to install Java 8 on old versions of Ubuntu."
Since that link doesn't contain the instructions any more, could you please add those instructions as part of this issue - so that any of us landing on this page will be able to use it.
Thank you!

**Comment by selvik** [comment]
Here is what worked for me: 

sudo add-apt-repository ppa:webupd8team/java
sudo apt-get update
sudo apt-get install oracle-java8-installer
sudo apt-get install oracle-java8-set-default

**Comment by scalp42** [comment]
@selvik unfortunately, some folks don't want to pull in this PPA.

**Comment by selvik** [comment]
@scalp42, Ah..I see. Thanks for letting me know. Since I'm only playing with this on test systems, I'll stick with it for now.

**Comment by seanjensengrey** [comment]
One can use `equivs` to generate a dummy `.deb` that satisfies `java8-runtime-headless`

```
apt-get install equivs
equivs-control dummy-jdk-8u91
equivs-build dummy-jdk-8u91
dpkg -i dummy-oracle-jdk_1.8.91_all.deb
```

In file `dummy-jdk-8u91`
```
### Commented entries have reasonable defaults.
### Uncomment to edit them.
Section: misc
Priority: optional
Standards-Version: 3.9.2

Package: dummy-oracle-jdk
Version: 1.8.91
Provides: java8-runtime-headless
Description: dummy package to satisfy java8-runtime-headless dep for manual install
 long description and info
 .
 second paragraph
```
