### ISSUE TITLE
PUT /v2/groups triggers restart while PUT /v2/apps does not

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#2360]
This always triggers app restart:

```
curl -s -X PUT -H "Content-type: application/json" http://172.16.91.128:8080/v2/groups -d @test.group.json | jq .
```

This triggers app restart only on app definition change:

```
curl -s -X PUT -H "Content-type: application/json" http://172.16.91.128:8080/v2/apps/whoa/huh -d @test.app.json | jq .
```

This started in 0.11.0, I checked 0.10.1 and it doesn't trigger restart on `PUT /v2/groups`. Moreover, `PUT /v2/groups` is not documented.

**Comment by naxhh** [comment]
We're having the same issue with 0.11

PUT to /v2/apps/<id> only triggers restart if the marathon config has changed.

**Comment by surdy** [comment]
Perhaps this could have been better documented, but Marathon is smart enough to only restart the apps if the app definition has changed. Infact it won't even restart the application if all that has changed in your definition is increase in instances  (scaling up the application). This is intended behaviour

On PUT /v2/groups I will defer to a marathon team member to answer that as I do not have enough experience with that.

**Comment by naxhh** [comment]
What is the intended way to deploy code changes only?
maybe `POST /v2/apps/{appId}/restart` ?

**Comment by kolloch** [comment]
This leaves me slightly confused, maybe you, too. So just to be clear: If you use `PUT` on apps or groups, only groups or apps which have changed config should be restarted. 

So according to @bobrik's description the apps end-point behaves correctly and the groups end-point does not behave correctly anymore in 0.11.

**Comment by kolloch** [comment]
@naxhh: Is your question related?

**Comment by naxhh** [comment]
I was thinking that PUT on apps performs a restar like groups... so that was the intended method to restart applications when code changes...

So yes. I think the question is related... but not sure :)

**Comment by aquamatthias** [comment]
Hey @bobrik we fixed that issue. There is an RC version 0.11.1-RC1 which includes the fix. Would be cool, if you could try that version. If everything goes well, we will do the 0.11.1 release tomorrow.

**Comment by bobrik** [comment]
Tried this on one cluster and it worked. Very nice! :)

Is it a backwards-compatible upgrade? I see zookeeper compression changes enabled by default. Will it still work if I downgrade to 0.11.0 for some reason.

**Comment by gkleiman** [comment]
@bobrik the upgrade is only backwards-compatible if you always start Marathon v0.11.1 with `--disable_zk_compression`. Otherwise ZK nodes larger than 64kb will be compressed, and older versions of Marathon won't be able to parse them.

**Comment by bobrik** [comment]
Not the best kind of change for a bugfix release, but okay.

**Comment by jgarcia-mesosphere** [comment]
I just ran into this, and I'd like to put my two cents in. We should be focussed on two distinct use cases:

1. Deploying production apps: In this case, we want every restart to be pinned to an explicit change to the json file, so we will be able to roll back immediately if needed. Marathon can only do this if the json file specifies an explicit docker tag (i.e., not `latest`). We should prevent other use of the endpoint for efficiency, and to prevent hapless users from deploying a broken `latest` to production and suffering a difficult roll back process.

2. Deploying for rapid development: In this case, it's easiest to just POST to `/v2/apps/{appId}/restart` because it explicitly calls the action we want.
