### ISSUE TITLE
Large file URIs cause "Failed to fetch all URIs for container" error when pulling from HDFS.

### ISSUE THREAD

**Issue by sybrandy** [mesosphere/marathon#2369]
Hello,

After upgrading to Marathon 0.11 today, a number of containers that we tried to start would fail.  Looking at the logs, we could see the "Failed to fetch all URIs for container" error.  Checking HDFS, everything looked fine.  We could even manually retrieve the files from HDFS.

After a good amount of debugging, it was discovered that it look like it's only the larger files (100MB and larger) that have issues.  It looks like something times out either during the download or during the extraction of the tar files.  Is there a new setting that we're missing or something else?

We tested this with a web server instead of HDFS with no issues.

FYI, we're still on Mesos 0.23.0.

**Comment by mindscratch** [comment]
FYI - Everything works fine after rolling back to marathon 0.10.0

**Comment by gkleiman** [comment]
@sybrandy: where do you see the "Failed to fetch all URIs for container" error? In the Mesos Slave log?

**Comment by mindscratch** [comment]
@gkleiman Yes, it was in the slave log but also in the Marathon log.

**Comment by mindscratch** [comment]
any thoughts?

**Comment by whamilton42** [comment]
I'm getting this error on 0.11 too.

Which file is this process actually trying to fetch?

**Comment by mindscratch** [comment]
@whamilton42 In our case we have tarball's in HDFS, we're using the "uris" field to fetch them.

**Comment by gkleiman** [comment]
@mindscratch  sorry for the delay. The `--task_launch_confirm_timeout` flag was introduced in v0.11.0 and the default is clearly to low.

We will change the default in the next release, but in the meantime you can workaround this by starting Marathon with a larger timeout. Marathon v0.10.1 used to wait 300000 ms (5 minutes), so that value should be fine for most cases.

**Comment by mindscratch** [comment]
@gkleiman that makes sense, I didn't realize the task had a state before "staging", so when I read the description for the `--task_launch_confirm_timeout` flag I didn't put it together. I'll give this a shot, thanks.

**Comment by mindscratch** [comment]
@gkleiman increasing the timeout did the trick.

**Comment by whamilton42** [comment]
My problem turned out to be unrelated - a file in the URIs section simply didn't exist.

**Comment by aquamatthias** [comment]
Hey @sybrandy we fixed that issue. There is an RC version 0.11.1-RC1 which includes the fix. Would be cool, if you could try that version. If everything goes well, we will do the 0.11.1 release tomorrow.

**Comment by mindscratch** [comment]
We redeployed marathon 0.11.0 but this time we set the config value to 5
minutes and it's working fine.

**Comment by sybrandy** [comment]
Yes, 5 minutes is working out well for us.  Thanks!

**Comment by mytechskill** [comment]
Hi @sybrandy ,

Please tell us where should I change the value.

Thanks in Advance...!!!

**Comment by mindscratch** [comment]
@mytechskill the marathon configuration setting is named `--task_launch_confirm_timeout`, see https://mesosphere.github.io/marathon/docs/command-line-flags.html
