### ISSUE TITLE
Correct way to enable event subscriptions

### ISSUE THREAD

**Issue by st15jap78** [mesosphere/marathon#2378]
Hello all,

I have been trying to enable event subscriptions. I found the Marathon REST API. I attempted to restart marathon with the "--event_subscriber http_callback" and created the "event_subscriber" and "http_endpoints". When i restart it shows " --http_endpoints http://localhost:1234/"  and I am running "nc -l -p 1234" to listen to the port. I am not getting anything when i create new apps. Maybe i am missing something? Thanks for any help. I'm using version 0.10.1 and don't have much experience with marathon yet.

**Comment by xiaods** [comment]
i have not came across this same bug. are u sure?

**Comment by aldipower** [comment]
Hi @st15jap78 !

Could you post the complete command line how you start Marathon ?
Also ensure you are opening the listening socket on the correct IP address.
And maybe there is some information in the logs.

**Comment by st15jap78** [comment]
Here is the command that i use to start marathon 

   ./sbin/start --master zk://my_ip/mesos --zk_hosts my_ip:2181 --event_subscriber http_callback --http_endpoints http://my_ip:1234

and i get the following 

-bash: ./sbin/start: No such file or directory

I used this tutorial to do the install if that helps. 
https://www.digitalocean.com/community/tutorials/how-to-configure-a-production-ready-mesosphere-cluster-on-ubuntu-14-04

Over the weekend i built it from the files here on git hub using a VM and can see the bin/start directory however with the way i installed it it must be somewhere else? When i did a grep it didn't turn anything up. Thanks for your help.

**Comment by st15jap78** [comment]
Obviously i am doing something wrong here. I installed via sudo apt-get install mesosphere. And i cannot find any of the directories needed. If someone knows where they are or what I am doing wrong it would be nice to know. I am sure its probably something simple I am missing.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3525. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
