### ISSUE TITLE
Debug page not showing failed tasks

### ISSUE THREAD

**Issue by mgummelt** [mesosphere/marathon#2379]
I've deployed HDFS in such a way that the tasks are coming up as staging, and immediately dying for some still unknown reason.  However, the "debug" page in marathon says "This app does not have failed tasks".  Is it not counting the killed staging tasks as "failed tasks"?  Regardless, it's incorrect.  `dcos task --json` shows many HDFS tasks that are in the TASK_KILLED state (which is a failure state).

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3457. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
