### ISSUE TITLE
Spritesheet generation

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#2392]
We need an automatic process to generate spritesheet from images, to incorporate the new icons. After a little research, I suggest to use [Glue](http://glue.readthedocs.org/en/latest/) or [sprity](https://github.com/sprity/sprity) for spritesheets generation.

**Open for discussion:**

* Should we push the resulting assets or regenerate the spritesheets during the release process. I prefer the latter. 

##  Glue vs. sprity

Both tools feature retina-ready sprites and are highly configurable. 

* Glue adds a bunch of new dependencies (python, ImageMagic, glue), but is pretty fast and the output quality is good.
* The resulting file size and quality from Sprity isn't that good, but it's *node* only and 
really fast.
* Glue uses images with a specific naming convention (foo@2x.png) for retina sprites, while sprity tries to scale images based on dimension settings.

## Action Items

* Integrate and document sprity or glue
* Create a better less/css output template, if necessary 

### Sprity 

Just a simple npm install:

	npm install sprity sprity-less --save-dev

### Glue

Please follow these installation instructions:

http://glue.readthedocs.org/en/latest/installation.html

### Sprity 

Use the following gulp task to generate the icon spritesheet:

	var gulp = require('gulp');
	var sprity = require('sprity');

	gulp.task('sprites', function () {
    	return sprity.src({
        	"src": "./src/img/**/*.{png,jpg}",
       		"style": "./icons.css",
        	"processor": "less",
        	"dimension": [{
            	"ratio": 1, "dpi": 72
        	}, {
            	"ratio": 2, "dpi": 72
       		}],
       		"orientation":"binary-tree"
    	}).pipe( gulp.dest("./sprites/"))
	});

### Glue

Use the following command to generate the icon spritesheets: 

	glue src/img sprites --retina

## Optimize

It's highly recommended to optimize the output using pngquant:

	pngquant img/icons* --ext=.png --force
	
### Sprity
![icons](https://cloud.githubusercontent.com/assets/647035/10397523/71c822b4-6ea8-11e5-9e7c-17bafbb1cdd1.png)
![icons 2x](https://cloud.githubusercontent.com/assets/647035/10397524/71cc64a0-6ea8-11e5-8e44-b10f95470c04.png)

### Glue
![icons](https://cloud.githubusercontent.com/assets/647035/10397497/4e76c16c-6ea8-11e5-9b31-781153430262.png)
![icons 2x](https://cloud.githubusercontent.com/assets/647035/10397496/4e720a0a-6ea8-11e5-9ec3-527ed0514414.png)

**Comment by pierlo-upitup** [comment]
Thanks for the excellent writeup, @orlandohohmeier. 

At first glance I'd say Sprity has the better edge as it integrates better with our `npm`/`gulp` stack. Image quality is a bit worrying in both cases, though. Maybe we need higher resolution source images to begin with?

In any case, I'd like to take a moment and question the whole spritesheet approach entirely. I think the idea here was to start with the sprites as a quick solution, but to move to SVG asap. With that said, we could just skip the whole spritesheet build system integration entirely, and spend our energies on getting a nice SVG / custom font setup. That would give us a lot more freedom and resolution independence anyway.

**Comment by orlandohohmeier** [comment]
As discussed, we will start with the plain images and replace them with SVGs and a custom made icon font in the very near future.
