### ISSUE TITLE
Improve error messages when concurrent modifications to an app time out.

### ISSUE THREAD

**Issue by guenter** [mesosphere/marathon#2395]
Currently, when too many clients try to modify the same app concurrently, and some clients time out, they get an obscure error message: `Futures timed out after [10000 milliseconds]`, and response code `504`.
The error message should be more descriptive, ex. `Too many concurrent modifications for APP_NAME. Please try again later.`, along with a client error code; `409 Conflict` seems most appropriate.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2956. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
