### ISSUE TITLE
What are the benefits of using group ?

### ISSUE THREAD

**Issue by xianlubird** [mesosphere/marathon#2396]
I have lots of containers to create,but I did not use group feature on marathon.In another word, I just use a single group to run lots of containers.But when the numbers of containers are above1000,marathon will response very slow even not create container.I do not know whether the reason is that I just use a single group.If I use more than one group, did it will react better?   Please help me .

**Comment by aldipower** [comment]
Hi @xianlubird !
Groups don't affect the performance.
Could you tell us a little bit more about your setup?
Available resources, Mesos version, Marathon version and so on.
What do the containers do? Simple workload or more complex?

**Comment by aldipower** [comment]
The benefits of using groups are that you could sort and categories your applications better in a folder like structure.
Also groups enables you to scale a bunch of applications at once by a factor of 1.5 .

**Comment by xianlubird** [comment]
Thanks a lot. My Mesos version is 0.23 and Marathon version is 0.10. I setup this cluster on aws. I have 5 vm and one master and 4 slave. The cpu num is 10 total and memory is 15GB. I just start simple docker container,it is a ubuntu image and command is top.That means I just start a ubuntu container that run top command front.When I use python client to call Marathon REST API,If the number of container managed by marathon above 1000, the python client will not response.Even if marathon receive my request, it will also react very slowly even can not deploy a container.  I want to know whether you have a performance data about marathon? How many instances can a marathon manage? Thank you !

**Comment by aldipower** [comment]
There is a differentiation between applications (apps) and the instances (tasks) each app is running.

We successfully and reasonable started 60.000 tasks (instances) with one single app.

The numbers look different if you want to start several apps, because an app is a node in Zookeeper. So currently Zookeeper becomes a bottleneck around 500 simultaneous applications. But we are working on this to improve this.

If you want to scale very large consider to work with less applications, but with more tasks.

**Comment by xianlubird** [comment]
Do you start 60.000 tasks are all the same task?  I read the REST API find that one single app can only run many instances (tasks) which are all the same function .I want to run different kinds of tasks in one single app, do you have some suggestions?

**Comment by jasongilanfarr** [comment]
Marathon 1.4 supports pods which can do this.
