### ISSUE TITLE
How to create app via rest-api with v0.11.0?

### ISSUE THREAD

**Issue by VFT** [mesosphere/marathon#2397]
By the rest api calling:
`curl -X POST http://192.168.2.91:8080/v2/apps -d ~/inky.json -H "Content-type: application/json"`

with v0.10.0  successed
with v0.11.0 failed

The error message:
`{"message":"Unexpected character ('/' (code 47)): maybe a (non-standard) comment? (not recognized as one since Feature 'ALLOW_COMMENTS' not enabled for parser)"}`

and the content of ~/inky.json
`{
       "id": "inky4",
    "container": {
        "docker": {
            "image": "192.168.2.98:5000/tomcat-jdk1.7",
            "network":"BRIDGE",
            "portMappings":[{"containerPort":8080,"hostPort":0,"protocol": "tcp"}]
        },
        "type": "DOCKER",
        "volumes": []
    },
    "args": [],
    "cpus": 0.5,
    "mem": 64.0,
    "instances": 1
}`

**Comment by aldipower** [comment]
Hi @VFT,
thank you for reporting this.

I just highlighted your example in JSON format and also validated it correctly with a JSON-validator.
```json
{
       "id": "inky4",
    "container": {
        "docker": {
            "image": "192.168.2.98:5000/tomcat-jdk1.7",
            "network":"BRIDGE",
            "portMappings":[{"containerPort":8080,"hostPort":0,"protocol": "tcp"}]
        },
        "type": "DOCKER",
        "volumes": []
    },
    "args": [],
    "cpus": 0.5,
    "mem": 64.0,
    "instances": 1
}
```
The JSON seems to be correct and valid.
Only anomaly I can see is the wrong indentation on line 2.
Could you test this again with correct identation?

We will have a deeper look into this.

**Comment by bobrik** [comment]
`~/inky.json` looks like incorrect json to me. I guess you wanted `@~/inky.json`.

**Comment by bobrik** [comment]
I wonder how that works on 0.10.0

**Comment by VFT** [comment]
Thanks for @aldipower  @bobrik 

The error was caused by my carelessness.

As @bobrik said,`~/inky.json` is incorrect json

this is correct：`curl -X POST http://192.168.2.71:8080/v2/apps -d@inky.json -H "Content-type: application/json"`
