### ISSUE TITLE
Allow embed fields in /v2/groups endpoint

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2404]
In the `/v2/apps` endpoint, it's possible to specify a `embed=...` parameter specifying `deployments` and `counts`. 

It would be useful to have this same functionality in the `/v2/groups` endpoint, as the application table in the UI needs this information in order to build the applications table. This can currently only be done by calling both `/v2/groups` and `/v2/apps` and interpolating the results.

**Comment by philipnrmn** [comment]
cc @pierlo-upitup

**Comment by pierlo-upitup** [comment]
Also worth noticing: `counts` and `deployments` are currently embedded by default. This should be the case for `groups` as well.

**Comment by philipnrmn** [comment]
Blocks #966, #2769, and #2770

**Comment by pierlo-upitup** [comment]
cc @air @mwasn please let's track this issue in our roadmap
