### ISSUE TITLE
Incorrect container name for docker experimental

### ISSUE THREAD

**Issue by Shtsh** [mesosphere/marathon#2408]
Seems new docker doesn't support dots in container name.

curl -X POST -H "Accept: application/json" -H "Content-Type: application/json" http://root:root@10.128.144.102:8080/v2/apps  -d@configurator.json

```
{
     "id": "configurator",
     "cpus": 0.1,
     "mem": 128,
     "instances": 1,
     "constraints": [["hostname", "UNIQUE"]],
     "env": {
        "SERVICE_ROLE": "configurator"
     },
     "container": {
         "type": "DOCKER",
         "docker": {
           "image": "docker.registry.iv/maintenance/configurator:1.4",
           "forcePullImage": true,
           "parameters": [
                { "key": "publish-service", "value": "config.mesos" }]
         }
       },
     "upgradeStrategy": {
        "minimumHealthCapacity": 0.5,
        "maximumOverCapacity": 0.2
     }
}
```

Container goes to KILLED state with next error:

```
Error response from daemon: Cannot start container d440b7d21715e370d370ab9dc9772a18de584c3d19c2314b9f32b17d7f825079: invalid name: mesos-20151012-105102-1720745994-5050-1-S1.7ff6b290-797f-4d9f-b886-f0f6e0b2cec2
```

When I'm trying to start manually

```
docker run  --name=mesos-20151012-105102-1720745994-5050-1-S1.7ff6b290-797f-4d9f-b886-f0f6e0b2cec2 -it docker.registry.iv/maintenance/configurator:1.4
```

I got the same error

If I remove dots from the name, it deploys as intended

```
docker run  --name=mesos-20151012-105102-1720745994-5050-1-S1 -it docker.registry.iv/maintenance/configurator:1.4
2015-10-12 16:16:49,559 INFO RPC interface 'supervisor' initialized
...
```

Here version of docker

```
# docker --version
Docker version 1.9.0-dev, build ed9434c, experimental
```

Mesos containers

```
mesoscloud/mesos-slave:0.24.1
mesoscloud/marathon:0.11.0
mesoscloud/mesos-master:0.24.1
```

Any ideas how to bypass or fix this issue?

**Comment by Shtsh** [comment]
It looks like network plugin become broken in this version of docker. And docker tries to use network which doesn't exist. 
Please close this issue.

**Comment by Shtsh** [comment]
My error.
I've dived into docker source code and found docker libnetwork incompatible with dots in entrypoint names.
https://github.com/docker/docker/blob/master/vendor/src/github.com/docker/libnetwork/config/config.go#L138
As result highly needed possibility to give names for containers without dots.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4800. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
