### ISSUE TITLE
marathon app update documentation misleading (requires file)

### ISSUE THREAD

**Issue by SL4YT1M3** [mesosphere/marathon#2409]
The cli documentation states:

dcos marathon app update [--force] <app-id> [<properties>...]

However, the update command cannot simply accept a json string as indicated but rather requires piping to it.

For example,

`dcos marathon app update basic-0 '{"instances":100}'` will fail.

These will succeed:

`echo '{"instances" : 100}' | dcos marathon app update basic-0`
`dcos marathon app update basic-0 < config.json`

**Comment by aldipower** [comment]
Hi @SL4YT1M3 !

This seems to be related to the [dcos-cli](https://github.com/mesosphere/dcos-cli) and not to Marathon itself.

Could you post your issue in this repository again?

Thank you very much.

**Comment by mwasn** [comment]
@SL4YT1M3 

This syntax works without piping:
`dcos marathon app update --force basic-0 instances=5`

See https://docs.mesosphere.com/using/cli/marathonsyntax/ for more examples.
