### ISSUE TITLE
Failed to connect error potentially due to double '/' when redirected to Mesos task page.

### ISSUE THREAD

**Issue by jordmoz** [mesosphere/marathon#2410]
In Marathon 0.11, when clicking on the Mesos details link, I am sent to 

http://daldevmesos01:5050//#/slaves/2015[......]

This results in a "Failed to connect to daldevmesos01:5050!" error on the Mesos page.

Removing the double // after the port 5050 and replacing it with a single / makes everything happy.

This is with Mesos 0.24.1.

**Comment by aldipower** [comment]
Hi @jordmoz ,

yes, this is a known issue and is fixed in the nearly upcoming Marathon 0.12, because this behavior changed in Mesos 0.24.

https://github.com/mesosphere/marathon/issues/2266

**Comment by jordmoz** [comment]
Thanks!  Sorry for the double entry.
