### ISSUE TITLE
What can the "uris" field in the .json definition be used for

### ISSUE THREAD

**Issue by tkrausjr** [mesosphere/marathon#2412]
Documentation on github repo is NOT clear and mentions dependencies but is not that specific as far as downloading a github archive file and using it to run an application.

**Comment by aldipower** [comment]
Hi @tkrausjr !

You're right the documentation on the github-page lacks a little bit of information there.

I've got this from the annotated source:
```
 * ... Any URIs specified
 * are fetched before executing the command. ...
 * Otherwise, if the downloaded file has a recognized archive extension
 * (currently [compressed] tar and zip) it is extracted into the executor's
 * working directory. ...
 */
```

That means you could inject and download external files/dependencies to your applications working directory before execution.

Hope this helps.

**Comment by aldipower** [comment]
- [ ] Documentation should be improved for the URIs field on the Github-page

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3617. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
