### ISSUE TITLE
Generic handler for 4XX and 5XX error codes

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2420]
Let's write a generic handler for unexpected errors. At present, error codes (eg `HTTP 422`) without specific handlers are not handled in the UI at all. We should have a fallback for such cases. 

To reproduce a `422`:
- Create an app in a new group `/test-group/test-app`
- Create an app with the same ID as the new group, eg `/test-group`

**Comment by aldipower** [comment]
The HTTP 422 is handled explicitly, but the attribute-name in the error response called "apps" isn't set yet in the UI.
If set it's looking like this:

![apps](https://cloud.githubusercontent.com/assets/859154/10458315/944d8c3c-71ca-11e5-8b93-6ce2ade7949f.png)

I'll prepare a fix.

**Comment by aldipower** [comment]
Closing this, general unspecific errors are handled. The given example was a specific one.
