### ISSUE TITLE
Support revocable offers

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#2424]
Mesos 0.23.0 added support for oversubscription via custom resource estimator and QoS controller policies.  Schedulers must opt-in to receive the special revocable offers that result from slack resource estimation.  Marathon could add support for this as a per-application setting.

**Comment by hamo** [comment]
+1 for this feature.

**Comment by WalterDalton** [comment]
This could be done at both the Marathon (default, applied to all apps level) and a per application level.   I see the default level (i.e. this instance of marathon will support revocable resources for all applications) being useful for running a dev Marathon instance under a master Marathon instance. I.e. you have the master Marathon running natively, then you have an instance of Marathon running in a docker container that is presented to say developers.  In the master Marathon app, you specify that the marathon app running in docker runs on revocable resources, and thus force the marathon in docker to have all applications running under it running under those revocable resources.  (Obviously authentication would determine who could submit applications to which Marathon.

**Comment by sergesyrota** [comment]
+1 for this too!

**Comment by qiujian16** [comment]
+1 for this feature, I would vote for per application level and let user decide the QoS of the application.

**Comment by ConnorDoyle** [comment]
Are any of you folks (@hamo, @WalterDalton, @sergesyrota, @qiujian16) running Mesos with oversubscription modules enabled?  I'm curious to know about your use cases.

**Comment by sergesyrota** [comment]
We're not running mesos in prod yet, but are actively looking into it. Use case for us would be managing workers where load can vary on a lot of external factors. External changes trigger a message addition into queue, and workers process them (doing some heavy calculations, etc). As such, we can have periods where everyone is idle, and the opposite where everyone's busy. To add to that, we have multiple queues like that, that vary when they get messages added. In the current model, we have to allocate for peak resource usage, and when messages are not there, we're just idling. With oversubscription enabled, we can specify that we want to have, say, up to 40 workers or as much as resources allow. This way we can run other things on the same resource (e.g. web servers or databases) that cannot be terminated. But when traffic is low, more workers can be started there to accommodate for that processing need.

**Comment by jolexa** [comment]
Our use-case for oversubscription would allow for easier scheduling in a mixed workload and responding to dynamic (external) events faster. So, an example,

Our workers may have a combined 1TB of ram during peak periods. There is a certain time when the peak workload is for an application that requires an excessive amount of ram, but most times, a nominal set of ram is required. IF there was oversubscription support, we could then allow the resource hungry application to be revokable for times when the peak workload requires the other app. We currently do this with restraints and pinning apps to a certain set of hosts but that is proving to be problematic at times.

I'm happy to expand on this further but consider it a +1 from our org as well.

**Comment by qiujian16** [comment]
Our use case is not quite related to oversubscription. We currently have a customised mesos allocator that can borrow resource as revocable resources between roles. If a role has a reservation, its unused resource can be borrowed to other roles as revocable resources.

**Comment by drewrobb** [comment]
+1, my org has a few use cases for this

**Comment by andyreidz** [comment]
+1, we also have need of this feature.

**Comment by leogamas** [comment]
+1 for this feature!

**Comment by jeacott1** [comment]
+1 please!  would be nice to be able to set min and/or max resource requirements too.

**Comment by nobusue** [comment]
+1

**Comment by hrdmtr** [comment]
+1

**Comment by WUMUXIAN** [comment]
+1

**Comment by yuriksan** [comment]
+1 Please !

**Comment by jeacott1** [comment]
+1

**Comment by supernovae** [comment]
+1

**Comment by kbroughton** [comment]
+1

**Comment by eastlondoner** [comment]
+1

**Comment by JamieCressey** [comment]
+1

**Comment by lesykm** [comment]
+1

**Comment by gyllen** [comment]
+1

**Comment by JetMuffin** [comment]
+1

**Comment by meetri** [comment]
+1

**Comment by supernovae** [comment]
+1

**Comment by tanbokan** [comment]
+1

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3038. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
