### ISSUE TITLE
Get rid of V2 model objects

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#2426]
Now that we use play json serialization, the structure of the model objects does not have to correspond to the JSON structure and we can get rid of one level of indirection.

(@connor, do you agree?)

**Comment by connor** [comment]
@kolloch I think you mis-tagged me :)

**Comment by gkleiman** [comment]
@connor: sorry for that, I believe he meant @ConnorDoyle

**Comment by ConnorDoyle** [comment]
@kolloch :+1:

Couple of related thoughts:

- What do you thnk about moving the `marathon.api.validation` logic into the play-json formatters and also get rid of hibernate validation?  If you need API-independent model validation, maybe a stackable Validation trait in the state package makes sense?
- You should also be able to drop the project dependency on the `jackson-case-class-module` artifact.  I wrote that thing as a shim for handling default values for Scala case classes.  Happy to see it go away :)  https://github.com/mesosphere/jackson-case-class-module .
- We shouldn't forget to allow HTTP event subscribers to choose the API version formatters to use for serializing events before introducing v3 formatters.
