### ISSUE TITLE
Documentation: add a "tuning for production" page

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#2429]

**Comment by mwasn** [comment]
Add limits of Marathon (2K apps, 50K Tasks)

**Comment by xiaods** [comment]
where is start?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3676. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
