### ISSUE TITLE
Support more advanced bin-packing with Fenzo

### ISSUE THREAD

**Issue by cmluciano** [mesosphere/marathon#2430]
#2063 mentions  Fenzo  integration and I believe a great use-case would be for more efficient bin-packing. Part of the allure of mesos is being able to eek out every bit of resources from a cluster.

Fenzo is able to make smarter decisions about where to place a new task based on a [Fitness level](https://github.com/Netflix/Fenzo/wiki/Fitness-Calculators). This allows it to more effectively choose which mesos-agent that it should run the task on. 

More efficient bin-packing would allow smaller tasks to stack up on machines that are already filling up. This provides more room for more resource hungry tasks that might otherwise not be able to find a machine.

**Comment by xiaods** [comment]
+1

**Comment by drewrobb** [comment]
+1

**Comment by mlerner** [comment]
+1

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2827. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
