### ISSUE TITLE
Implement optional "warm-up" health-check

### ISSUE THREAD

**Issue by cmluciano** [mesosphere/marathon#2431]
Some services require a "warm up" phase. Applications such as Solr or Memcache may come up and be "ready", but not "healthy." 

For example if I had a stateful service that requires some time to replicate some state between two tasks, my app would be up but I would not say that it is fully-healthy yet.

It would be great to have a second optional health-check that can be used to see if a task is both up and ready to receive new connections.

I would be happy to help out with an implementation of this :). Please let me know if you have any feedback.

**Comment by aldipower** [comment]
Hi @cmluciano, good idea, this sounds very useful to me for some use cases.
Could you go a little bit deeper in detail how this additional health check could work? What do you have in mind? How would you differ between "up" and "replicating" for example?

@gkleiman What do you think about this?

Every implementation is always welcome!

**Comment by cmluciano** [comment]
@aldipower I envisioned it as an optional health-check that would only be run at initial task creation time. So a service would have a REST endpoint that exposed something like "/replicated" that would be a boolean value perhaps. Once that health-check is satisfied, the normal health-check would take over for the lifetime of the task.

Job creation -> Optional health-check satisfied? -> normal health-check satisfied? -> mark job as healthy and continue normal health-check at specified interval.

**Comment by bobrik** [comment]
> `ignoreHttp1xx` (Optional. Default: false): Ignore HTTP informational status codes 100 to 199. If the HTTP health check returns one of these, the result is discarded and the health status of the task remains unchanged.

#1126

**Comment by hekaldama** [comment]
@cmluciano does #1126 satisfy what you need? Seems like it would from my standpoint.

**Comment by cmluciano** [comment]
@hekaldama I haven't had a chance to test that out, but I think it should satisfy our requirements.

**Comment by hekaldama** [comment]
@cmluciano cool. Do you know of any mechanism that would allow for before or after hooks in marathon? I am looking through issues / code now, but can't find anything yet. Idea would be to describe before saying TASK_STARTED, do something, if successful, say TASK_STARTED and healthy. Trying to inject smoke testing before putting newly deployed instance into LB rotation.

**Comment by cmluciano** [comment]
Nothing comes to mind at the moment. That part may still be a good enhancement. We will probably just keep reports that 100 code until our service is happy and then return a healthy status code.
