### ISSUE TITLE
Support per-container ip addresses

### ISSUE THREAD

**Issue by SEJeff** [mesosphere/marathon#2432]
This [new feature](http://mesos.apache.org/documentation/latest/networking-for-mesos-managed-containers/) in Mesos 0.25 would be great to use in marathon for launching tasks with user configurable ip addresses.

**Comment by duffqiu** [comment]
+1

**Comment by Poogles** [comment]
https://mesosphere.github.io/marathon/docs/ip-per-task.html

**Comment by gkleiman** [comment]
Experimental support for IP-per-Task was added in Marathon v0.14.0.

**Comment by duffqiu** [comment]
@gkleiman i am using marathon 0.15.3, does it work?
If yes, how to use it?
with the request with empty ipAddress as the doc said?
please give me direct guide
thanks a lot!

{
  "id": "/i-have-my-own-ip",
  "ipAddress": {}
}

**Comment by gkleiman** [comment]
@duffqiu ip-per-task doesn't work in Marathon v0.15.3. It does work in v0.14.x and 1.x.

**Comment by duffqiu** [comment]
thanks,

But if i use marathon 1.1.0, Do I need to do some special things for mesos?

**Comment by jaminlai** [comment]
+1

**Comment by gkleiman** [comment]
@duffqiu yes, you will need to install a network isolation module, such as the one developed by Calico: https://github.com/projectcalico/calico-mesos

**Comment by duffqiu** [comment]
It seems marathon still can't get the container's port if using this ip per container solution?

If that is true, it is not possible to use Bamboo -:(
