### ISSUE TITLE
AppRestart deployments don't wait for old tasks to be killed

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#2441]
AppRestart (TaskReplaceActor) deployments issue kills and then finish as soon as all new task are running, leaving outstanding kills.

As soon as the deployment is finished, the lock on the app is released and Marathon's normal scale code picks up. It usually notices that there are too many tasks running and, because it is not aware of the outstanding kills, it issues even more kills, making the running task count drop unnecessarily.

**Comment by bobrik** [comment]
This is pretty sad if you have apps with single task and minimumHealthCapacity = 0.

**Comment by gkleiman** [comment]
@bobrik I agree, it is a bit sad. But don't despair! PR #2445 should fix this =).

**Comment by bobrik** [comment]
Milestone makes me sad. Can we land it sooner?
