### ISSUE TITLE
Batch answers for service discovery end-points

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#2443]
`/v2/tasks` (Accept: plain/text) is frequently hit by service discovery software.

If we use a simple caching strategy, we might violate expectations. For example, if we have sent an event that advertised that a task A has just died, the task A should not be included in the list of tasks retrieved as a result of this event.

What we can do, though, is to batch requests. Rough outline of a potential algorithm:
- For every incoming request:
  - If we already have requests with the same parameters running, we save that request as `queued`.
  - If we have no request with the same parameters running, we start a new computation of the response and use it to answer the request.
- When a computation finishes:
  - We answer all requests that started before the computation with it.
  - If we have `queued` requests, we start a new computation.

**Comment by pyronicide** [comment]
This is a great improvement. It still has the potential to miss tasks (request A comes in and takes 3 seconds to complete, request B comes in 2 seconds after A and there have been a bunch of tasks that launched inbetween).

I'd also recommend something that most caching proxies use. They've got a header which, if included, circumvents the caching. That gives the tools to the end user. For most requests, there isn't a care factor about caching and for the ones that are mission critical, you can circumvent it easily.

**Comment by kolloch** [comment]
By the nature of distributed systems, you may always miss "future" events. Even without any caching.

I like the idea of giving control to the user. We could provide a separate set of endpoints for service discovery that is cached.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3273. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
