### ISSUE TITLE
'./haproxy-marathon-bridge install_haproxy_system' fails if 'redhat-lsb-core' package is not installed on RHEL, CentOS

### ISSUE THREAD

**Issue by dantrainor** [mesosphere/marathon#2446]
While running `haproxy-marathon-bridge` without the `install_haproxy_system` option works just swell, using the option to install haproxy fails (running with -x):

    [root@proxy ~]# ./haproxy-marathon-bridge install_haproxy_system mesos-master:8080
    + set -o errexit -o nounset -o pipefail
    + export LC_ALL=en_US.UTF-8
    + LC_ALL=en_US.UTF-8
    + name=haproxy-marathon-bridge
    + cronjob_conf_file=/etc/haproxy-marathon-bridge/marathons
    + cronjob=/etc/cron.d/haproxy-marathon-bridge
    + script_path=/usr/local/bin/haproxy-marathon-bridge
    + conf_file=haproxy.cfg
    + '[' 2 -lt 1 ']'
    + [[ -n install_haproxy_system ]]
    + declare -F
    + cut '-d ' -f3
    + fgrep -qx -- install_haproxy_system
    + install_haproxy_system mesos-master:8080
    + hash lsb_release
    + '[' -e /etc/system-release ']'
    + grep -q 'Amazon Linux AMI' /etc/system-release
    ./haproxy-marathon-bridge: line 67: os: unbound variable

Line 67 reads:

      if [[ $os == "CentOS" ]] || [[ $os == "RHEL" ]] || [[ $os == "AmazonAMI" ]]

Without the `lsb_release` application being installed, via the `redhat-lsb-core` package, $os never gets assigned when running on a Red Hat-based system, and thus running strict, the installation fails.

This was discovered using a minimal CentOS installation.  It runs pretty slim.

Without installing the `redhat-lsb-core` package ahead of time, maybe consider:

    if [[ $(grep CentOS /etc/redhat-release) ]] || ... ....

**Comment by aldipower** [comment]
Thank you for reporting this.

**Comment by lloesche** [comment]
@aldipower @aquamatthias can we just delete haproxy-marathon-bridge from the repo? It's not planned to maintain it any further. servicerouter does everything the bridge can and more.

**Comment by aquamatthias** [comment]
The scripts is deprecated and has moved to the examples folder for reference.
