### ISSUE TITLE
Event Subscriptions 

### ISSUE THREAD

**Issue by st15jap78** [mesosphere/marathon#2447]
Hello all, 

I have enabled event subscriptions and setup a port on localhost to listen.
I did this on all the masters and i made an event happen. It is working, I can see it.
My question is why is the event only being sent to one master? with it configured to localhost should marathon send the update to all localhost(masters)? It started only working on the elected leader, then randomly changed to only updating the other master. I would like to have bamboo and haproxy running on all the masters(3) for fail over reasons. 
Thanks,

**Comment by aquamatthias** [comment]
1) Please ask questions via the google group: https://groups.google.com/forum/#!forum/marathon-framework
2) Events are send only by the leader. The event is sent to the registered subscriber. If you want to have multiple subscriptions you can do so by providing all endpoints to post to.
