### ISSUE TITLE
Allow cluster-wider override of max launch delay

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#2450]
In 99% cases I don't want to wait for 1h (default) if suddenly 50/50 tasks failed because of brief network failure. Instead of specifying max launch delay for every app, I'd like to have CLI flag that changes this
default to something less conservative, like 60s.

Since I was the one who did #1096, I can do PR for this as well.

What do you think?

**Comment by aldipower** [comment]
Hey @bobrik !
Sounds very reasonable to me. :)
@aquamatthias @gkleiman ?

**Comment by gkleiman** [comment]
Sounds reasonable to me as well.

@bobrik : PRs are most welcome and encouraged!

**Comment by milosgajdos83** [comment]
I would love this to be done too. (sorry for non-constructive comment).

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3200. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
