### ISSUE TITLE
Allow BasicAuth for Health Checks

### ISSUE THREAD

**Issue by devinsba** [mesosphere/marathon#2461]
Hey all.

Where I work our healthcheck/metrics/etc servlets are behind basic authentication. It would be really nice to be able to define authentication on the health check config. And because we are using docker I cannot use the COMMAND type as that is currently broken.

I might have some time this weekend to submit a pull request unless someone beats me to it. I'm guessing this is a pretty trivial change but I haven't explored the code yet.

**Comment by aldipower** [comment]
Hi @devinsba !

That would be very useful.
A PR is appreciated at every time. :)

Could you explain why the command-type health check is broken, if using Docker?

**Comment by devinsba** [comment]
I haven't tested it but that's what the documentation says so I was going
off of that.
On Oct 16, 2015 5:33 AM, "Felix Gertz" <notifications@github.com> wrote:
>
> Hi @devinsba !
>
> That would be very useful.
> A PR is appreciated at every time. :)
>
> Could you explain why the command-type health check is broken, if using
Docker?

**Comment by aldipower** [comment]
Thank you, you're right, didn't noticed that.

**Comment by aldipower** [comment]
Ok, small correction, this is only the case if you are using Mesos 0.23.0 or 0.24.0 and is fixed in newer versions.
https://github.com/mesosphere/marathon/issues/2471

**Comment by fatz** [comment]
+1

**Comment by hampsterx** [comment]
+1

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3370. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
