### ISSUE TITLE
Update docs on COMMAND health checks for dockerized apps

### ISSUE THREAD

**Issue by aldipower** [mesosphere/marathon#2471]
The documentation on the health checks says that a health check of type command isn't possible on dockerized apps.

~~* [ ] If the application is of type docker, the possibility of adding command health checks shouldn't be selectable in the app creation modal.~~

* [ ] Be concise with the documentation (see @gkleiman 's  comment)

https://mesosphere.github.io/marathon/docs/health-checks.html

**Comment by gkleiman** [comment]
COMMAND Healthchecks on Dockerized apps wasn't possible on 0.23.0 and 0.24.0 because of a Mesos bug.

This has been fixed on Mesos 0.23.1 and 0.24.1: https://issues.apache.org/jira/browse/MESOS-3136

So I think we should close this issue.

**Comment by aldipower** [comment]
Ah ok! Thanx!

**Comment by gkleiman** [comment]
Closing this, since the docs on master are already up-to-date: https://github.com/mesosphere/marathon/blob/master/docs/docs/health-checks.md#L48
