### ISSUE TITLE
Changing mesos_user does not apply

### ISSUE THREAD

**Issue by janisz** [mesosphere/marathon#2472]
I have running Mesos/Marathon cluster. I added following file to  `/etc/mesos-master/acls`

``` json
{  "run_tasks": [{
      "principals":{ "type":"ANY" },
      "users":{ "values":[ "marathon" ] }
    }, { 
      "principals":{ "type":"NONE" },
      "users":{ "values":[ "root" ] }
    }]
}
```

and corresponding flag to Marathon `--mesos_user marathon`
Then I restarted both Mesos and Marathon, but Marathon tries to launch tasks as previous user.
It worked when I changed zk prefix. 
Do I need to set up new Marathon instance to change user?

**Comment by aldipower** [comment]
Not sure, only a wild guess, did you tried to restart ZooKeeper, too?

**Comment by janisz** [comment]
I've just tried that, but nothing has changed (I've got running cluster changed `mesos_user` and restart marathon, then restart zk). Is there any order in which I should do it?

**Comment by aldipower** [comment]
So, you restarted all Mesos-master/slaves, Marathon and ZK, right?

@gkleiman Any ideas?

**Comment by janisz** [comment]
Yep, one by one.

**Comment by aldipower** [comment]
The order I would do it is:
Stop: Marathon, mesos-slaves, mesos-master, ZK
Start: ZK, mesos-master, mesos-slaves, Marathon

**Comment by janisz** [comment]
@aldipower Thanks, It's working. Do you think it should appear somewhere in doc, list of options that require mesos/zk restart.

**Comment by janisz** [comment]
@aldipower @gkleiman I tested this solution I can't figure out why it is required. I mean every component needs to be stopped. I thought maybe slaves do not require restarts but then it was not working.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2860. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
