### ISSUE TITLE
Deploying Router.json (for Oinker App) times out for CM.3 EA. The app DOES get deployed.

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2476]
JIRA Key: MARATHON-403
Reporter: Tarak Parekh
Priority: Medium

Description:
Taraks-MacBook-Pro:dcos tarak$ dcos marathon app add router.json
Request to URL [http://tarak-611-elasticl-qvz1ky67bvd5-2116367870.us-west-2.elb.amazonaws.com/marathon/v2/apps] timed out.

The app gets deployed.

**Comment by pierlo-upitup** [comment]
Can we have more details on this one, please? @tparekh73

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2689. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
