### ISSUE TITLE
Document datadog and graphite reporters

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#2478]
- Document the new flags in the docs.
- Decide if it makes sense to create a new document for the metrics + reporters.

**Comment by SEJeff** [comment]
Also for said graphite reporter, please do send us a pull request to the [tools documentation](https://github.com/graphite-project/graphite-web/blob/master/docs/tools.rst) so we can merge it.

Source: I'm a graphite co-maintainer.

**Comment by gkleiman** [comment]
@SEJeff we haven't written our own reporter, we just use io.dropwizard.metrics.metrics-graphite, which is part of https://github.com/dropwizard/metrics.

**Comment by SEJeff** [comment]
Feel free to send a PR for marathon being able to send metrics to graphite, or ask that library to do the same. We love to have these types of things.
