### ISSUE TITLE
Wrong font size in "Health Checks" section

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2487]
Prompt "Health Check 1 - TCP" seems to have a wrong font size.

<img width="737" alt="screenshot at okt 20 15-55-55" src="https://cloud.githubusercontent.com/assets/12829900/10609246/15824a36-7743-11e5-8bb4-5433887e7015.png">

**Comment by aldipower** [comment]
@mwasn Which font size is assumed?
It's the same font-size like the breadcrumbs.

**Comment by aldipower** [comment]
This was discussed here, see more at the bottom:
https://github.com/mesosphere/marathon-ui/pull/241

**Comment by mwasn** [comment]
Not sure about the "right" font size. Looks a bit weird as I, as a user, would expect a smaller font-size than the label "Healt Checks" for the whole section. As it has already been discussed, I´ll close the issue.

**Comment by aldipower** [comment]
@mwasn Yeah, you're right, it's a little bit weird, if you have only one health check.
This headline acts as a separator between multiple checks, then it becomes more meaningful.

**Comment by aldipower** [comment]
@mwasn Also before 0.13 the label above was in green color, which differs more.
We should reconcile the layout of the modal at some point.
