### ISSUE TITLE
Misleading health check error: "ConnectionException: Premature connection close (the server doesn't appear to support request pipelining)"

### ISSUE THREAD

**Issue by discordianfish** [mesosphere/marathon#2489]
Hi,

I had issues with health checks that failed with this error:

```
Received health result: [Unhealthy(marathon-lb.5203a6bd-741e-11e5-b204-0cc47a6c0782,2015-10-12T14:30:24.163Z,ConnectionException: Premature connection close (the server doesn't appear to support request pipelining),2015-10-16T16:01:22.370Z)] 
```

which leads me to assume it's somehow related to (missing) pipelining support. I went reading RFCs, read spray documentation, even started writing a small client to reproduce it but couldn't. After all that I finally realized: The path in my health check was wrong, so it hit an endpoint returning 503.
The error is very misleading. After changing the path things are working now.

So I'm not sure why we get this error. It gets returned by spray but that shouldn't handle 5xx errors so maybe we close the connection when encountering 5xx which leads to this exception or something.

**Comment by gkleiman** [comment]
@discordianfish: do you always get that error message if you create a healthcheck for an endpoint that always returns 503? Or is it necessary to do anything else to reproduce it?

**Comment by discordianfish** [comment]
@gkleiman for haproxy in my case it happened everytime

**Comment by erSitzt** [comment]
I have the same problem with haproxy health checks.

**Comment by giuliano108** [comment]
We had a similar issue with a healthcheck endpoint that was returning HTTP 200 and an _empty_ response body. Making it return something fixed the problem for us.

**Comment by erSitzt** [comment]
If anyone experiences this with haproxy health checks, switch to `monitor-uri` instead of `mode health`
I switched from this :
```
listen health
  bind :8000
  mode health
  option httpchk
```
to this

```
listen health
  bind :8000
  acl site_dead nbsrv(web) lt 2
  monitor-uri   /frontend_alive
  monitor fail  if site_dead
```

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2696. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
