### ISSUE TITLE
Support  dynamic persistent volumes

### ISSUE THREAD

**Issue by wplatform** [mesosphere/marathon#2493]
use marathon to launch multiple docker container instance from the same images on a host, like this:
{
    "id": "/product/service/myApp",
    "cpus": 1.5,
    "mem": 256.0,
    "instances": 3,
    "container": {
        "type": "DOCKER",
        "docker": {
            "image": "group/image"
        },
        "volumes": [{
                "containerPath": "/etc/a",
                "hostPath": "/var/data/a",
                "mode": "RW"
            }]
}
if they containers runing on the same host, they apps  will use the same path "/var/data/a".  that file will conflict. I don't want to use the constraints:UNIQUE. I want to get the only directory of each container. How do I do?

**Comment by aquamatthias** [comment]
Hey @wplatform this is on our roadmap. The underlying  mechanism is described here: http://mesos.apache.org/documentation/latest/persistent-volume/

**Comment by tobilg** [comment]
@aquamatthias Can you please tell me what's the status on this? Is this already usable with Mesos 0.26/Marathon 0.14? If not, what's the roadmap/timeline?

I have a running Ceph cluster on CoreOS with a working Docker volume plugin, but it's very unclear to me how this can be used with Mesos/Marathon... I can find no article/blog post/whatever that deals with the automated creation of these volumes via Marathon (also: how to scale if each instance of a stateful service need to have it's own volume?).

Thanks in advance!

**Comment by aquamatthias** [comment]
@tobilg this feature is planned for Marathon 0.16 and is not available in prior versions.

**Comment by tobilg** [comment]
@aquamatthias Thanks for the feedback. Is there already a timeline when 0.16 is planned? From the past releases, I guess this means 3-5 months from the 0.14 release...

To be honest, I really think this is a very important feature. I'd be very curious how Mesos/Mesosphere clients normally run stateful services... Sounds quite impossible to me at the current state. For us this might me a show stopper for Mesos/Marathon in the middle term. Persistent volumes are in the works since 2014, and no end in sight (at least for me, concerning the "front to back"-usability)...

**Comment by AI-PaaS** [comment]
+1, need to dynamic create volume before docker run

**Comment by junneyang** [comment]
+1, need to dynamic create volume before docker run

**Comment by duffqiu** [comment]
the current workaround is to mount the parent volume to container, and then the app in container to create the sub-folder according to container's ip

**Comment by aquamatthias** [comment]
Persistent Volumes will be available in Marathon 0.16. We released RC1 today, so try this out!

**Comment by bobrik** [comment]
@aquamatthias I'm too lazy to open an issue, but link points to `about:blank`:

![image](https://cloud.githubusercontent.com/assets/89186/13757995/f336bf26-ea1e-11e5-8f6f-e08e25bdcee2.png)

**Comment by tobilg** [comment]
@aquamatthias Thanks a lot for adding this feature. If I understand the [Persistent Volume docs](https://github.com/mesosphere/marathon/blob/persistent-volumes-doc/docs/docs/persistent-volumes.md) correctly, then it's currently not possible to use [Docker volumes which use plugin drivers](https://docs.docker.com/engine/extend/plugins_volume/), such as [volplugin](https://github.com/contiv/volplugin) or [rbd](https://github.com/tobilg/docker-volume-rbd).

Is this assumption correct? If so, is it planned to add this in the future? If not, how can I use such volumes with Docker containers?

Thanks a lot in advance!

**Comment by aquamatthias** [comment]
@bobrik good catch. The docs are currently in review here: https://github.com/mesosphere/marathon/blob/persistent-volumes-doc/docs/docs/persistent-volumes.md
Once merged the link will work.

@tobilg we are currently waiting for mesos 0.28 which will support persistent volumes in docker. Docker volumes with plugin drivers is not available right now. Please make a feature request on the Mesos JIRA.

**Comment by timcharper** [comment]
I'm having a really tough time getting this to work.

http://stackoverflow.com/questions/36242383/mesos-slaves-reject-all-marathon-jobs-with-persistent-volumes-claims-no-space-a

**Comment by tobilg** [comment]
@aquamatthias I just created an [issue](https://issues.apache.org/jira/browse/MESOS-5102) in the Mesos JIRA. If I can improve the description please let me know. Thanks a lot in advance.

**Comment by LiginGeorge** [comment]
Hi,

We have installed mesos 0.28.2 version and marathon 1.1.1 version. I am looking to launch instance with persistent local volume option. In my slave server i have installed docker engine and i have installed local persistent plugin and created the volume. From marathon i am able to launch instance if persistent volume created in slave server. Is there any possibility to create new persistent volume from marathon itself with new instance launch  instead of creating volume from slave server.

**Comment by jdef** [comment]
There are two types of "persistent storage": agent-local, and external. If
you want persistent storage NOT located on the same agent (on which the
related task is running) then you'll need to use some kind of external
volume. Marathon ships with support for the Mesos DVDI isolator that lets
you use docker volume drivers for creating external volumes on-demand
(works with both mesos and docker containerizers).

**Comment by LiginGeorge** [comment]
Hi,
In my case we are using local-persist volume driver, Please find the volume which i have created
# docker volume ls
DRIVER              VOLUME NAME
local-persist       tomcat
After creating the volume in slaves server from marathon i can launch the instance via below json script.
But my requirement is without creating volume manually in slave servers from marathon console i need to  create local-persist volume in slave server and launch the instance. If you have the steps please let me know.

{
    "id": "tomcat",
    "container": {
        "docker": {
            "image": "tomcat:latest",
            "network": "BRIDGE",
            "portMappings": [{
                "containerPort": 80,
                "hostPort": 0,
                "protocol": "tcp"
            }],
            "parameters": [{
                "key": "volume-driver",
                "value": "local-persist"
            }, {
                "key": "volume",
                "value": "tomcat:/data/www"
            }]
        }
    },
    "cpus": 0.2,
    "mem": 32.0,
    "instances": 1
}

**Comment by LiginGeorge** [comment]
Hi Team,

Can you please help on this thread, for creating persistent local volume from marathon console via json

**Comment by arunkabraham** [comment]
Can anyone share the answer for the same?
