### ISSUE TITLE
Support SELinux volume modes for docker

### ISSUE THREAD

**Issue by jfindley** [mesosphere/marathon#2497]
Since docker 1.7, two additional volume modes are supported on top of 'ro' and 'rw': 'z' and 'Z'. These set the SELinux mode of the volume to be accessible from every container or just this container, respectively.

See http://www.projectatomic.io/blog/2015/06/using-volumes-with-docker-can-cause-problems-with-selinux/ for more info on this.

Currently if you launch a container as follows:

``` json
"volumes": [{
      "hostPath": "/var/data/test",
      "containerPath": "/var/data/test",
      "mode": "Z"
    }]
```

You get an error: 

``` json
{"message":"Invalid JSON","details":[{"path":"/container/volumes(0)/mode","errors":["Z is not a valid mode"]}]}
```

As mesos will also need to be changed for this to be possible, I've created MESOS-3776 to match this.

Thanks!

**Comment by siddharthist** [comment]
Has there been any progress on this feature? [Mantl](github.com/CiscoCloud/microservices-infrastructure) could use this feature, as we run Marathon on top of SELinux enabled hosts.

**Comment by justinclift** [comment]
Creating an SELinux rule to allow the access as this filesystem location should work shouldn't it?

From memory (a long time ago), it's not hard to create these rules on at least CentOS/RHEL based systems.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4515. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
