### ISSUE TITLE
cannot start nginx from the web interface

### ISSUE THREAD

**Issue by asdfsx** [mesosphere/marathon#2498]
I'm using mesos 0.24 and marathon 0.11.0. I want to use docker to start a nginx in a simple mesos cluster. I can start it by using a json file

``` json
{
    "id": "nginx",
    "container": {
        "type": "DOCKER",
        "docker": {
            "image": "mesos_36:5000/nginx",
            "network": "BRIDGE"
        }
    },
    "instances": 1,
    "cpus": 1,
    "mem": 64
}
```

But when I try to start nginx from marathon web interface, I failed. 
I create app like this
![image](https://cloud.githubusercontent.com/assets/2292716/10635923/b9fec24c-782e-11e5-9909-b75dc48a731f.png)
but after app create, it deployed and run as usual, but then it staged
![image](https://cloud.githubusercontent.com/assets/2292716/10635992/2a5077b6-782f-11e5-8c99-825accdf89e8.png) 
In mesos dashboard, I found it create lots of job but there status all finished FINISHED. 
![image](https://cloud.githubusercontent.com/assets/2292716/10636095/bf0339f2-782f-11e5-8f41-fddbe34e99e7.png)

Am I miss some thing?
Do I need to config something else to prevent from this?

**Comment by asdfsx** [comment]
I wonder why these job finished, so I check the marathon log, and mesos slave log.
In marathon's log I found 
![image](https://cloud.githubusercontent.com/assets/2292716/10636309/8df643fc-7831-11e5-8a22-99055fe5cd55.png)
It received TASK_FINISHED status.
Then I open docker's debug mode, then check docker's log, and find the following..
![image](https://cloud.githubusercontent.com/assets/2292716/10636503/c2546542-7832-11e5-8f73-385ac6f87d17.png)
why did the container stopped when it just started?
It really makes me confused

**Comment by rasputnik** [comment]
Have a look at the Sandbox folders of the FINISHED tasks - specially stderr and stdout.

**Comment by jstabenow** [comment]
Please check /v2/apps/nginx
Refs: #2147 and #2373

**Comment by asdfsx** [comment]
@jstabenow so this might be caused by a bug!!!!

**Comment by jasongilanfarr** [comment]
If this is still happening, please reopen.
