### ISSUE TITLE
Config change not updating docker volumes

### ISSUE THREAD

**Issue by SlyngDK** [mesosphere/marathon#2499]
Hi

I'm trying to update existing docker configuration with volumes, using this command:
echo '{
    "container": {
        "docker": {
        	"volumes": [
                {
                    "containerPath": "/sys/fs/cgroup",
                    "hostPath": "/sys/fs/cgroup",
                    "mode": "RO"
                }
            ],
            "forcePullImage": true,
            "image": "ubuntu:15.04",
            "network": "BRIDGE",
            "portMappings": [
                {
                    "containerPort": 9000,
                    "hostPort": 0,
                    "protocol": "tcp",
                    "servicePort": 0
                }
            ]            
        },
        "type": "DOCKER"
    }
}' | curl -X PUT -H "Content-Type:application/json;" -d @- http://<marathon-address>/v2/apps/<app>

It resulting in a empty volumes array in the app configuration.

Are I doing some thing wrong, or is it a bug?

Thanks!

**Comment by meichstedt** [comment]
As described in the [documentation](https://mesosphere.github.io/marathon/docs/native-docker.html), the `volumes` property belongs to the `container` node, not the`docker` node.

Hint: a post in the marathon-framework [google group](https://groups.google.com/forum/#!forum/marathon-framework) would be the better option when you're unsure whether it's a bug or not.
