### ISSUE TITLE
Add a link to API-Doc in the UI

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#2500]
In the top navbar we have About and Docs.
Please add a link to the API-Doc under /help so that it looks like:
- About
- API-Doc (--> /help)
- Docs ( --> gh-pages) 

BTW: is API-Doc the best name? Do you have a better one?

**Comment by surdy** [comment]
@aquamatthias not a great improvement over "API Doc", my suggestion "API Reference"

**Comment by pierlo-upitup** [comment]
Fixed by https://github.com/mesosphere/marathon-ui/pull/343

**Comment by aquamatthias** [comment]
@pierlo-upitup Thanks!
