### ISSUE TITLE
Event bus: no way to know deployed app when deployment_successful is received

### ISSUE THREAD

**Issue by pbnsilva** [mesosphere/marathon#2501]
On successful deployment the following event is fired (from docs):

```
{
  "eventType": "deployment_success",
  "timestamp": "2014-03-01T23:29:30.158Z",
  "id": "867ed450-f6a8-4d33-9b0e-e11c5513990b"
}
```

More deployment info should be shown here. Otherwise, how to know which app(s) were successfully deployed?

**Comment by pierlo-upitup** [comment]
You may want to look for the corresponding `id` in one of the `deployment_info` events. That one should hold all of the apps affected in the `plan.target` fields. Does that help?

**Comment by pbnsilva** [comment]
Yes, that is what I ended up doing. I would just rather track a single event, instead of multiple ones.

**Comment by pierlo-upitup** [comment]
I hear you. I guess the Event Bus is really meant to be used alongside the API endpoints, and not as an "after the fact" log-style tool. 
Essentially, if you were also polling the `/deployments` endpoint, you would get all the info about the affected apps for that specific deployment ID.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4086. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
