### ISSUE TITLE
Provide memory and cpu as environment variables in docker containers

### ISSUE THREAD

**Issue by mindscratch** [mesosphere/marathon#2505]
It would be useful if docker containers launched with marathon had the memory and cpu app settings set as environment variables, such as `MARATHON_APP_MEM` and `MARATHON_APP_CPU`.

These could be used to configure an application at runtime based on the memory/cpu given to the application.

**Comment by pierlo-upitup** [comment]
Hi @mindscratch,

thanks very much for your valuable feedback. I'd like to suggest you to join our [Google Group](https://groups.google.com/forum/#!forum/marathon-framework) if you haven't done so yet. 

We try to use GitHub issues for actual issue reporting, while for feature requests (which are more than welcome!) and, in general, for discussions around Marathon we prefer using the mailing list. Feel free to join and share your thoughts there!

Closing the issue for now.

**Comment by mindscratch** [comment]
@pierlo-upitup no problem, I've posted a message there, thanks.

**Comment by pierlo-upitup** [comment]
I apologise, the issue shouldn't have been closed. My bad!

**Comment by kolloch** [comment]
In #375 includes comments on how to name environment variables for arbitrary resources. The proposals I saw while skimming went along the pattern `MARATHON_RESOURCE_<....>`. We should probably name non-custom resources in the same way as custom resources.

**Comment by lloesche** [comment]
+1 I would love to automatically have any resource limits exported to the environment without having to set them explicitly / duplicating the information in my app definition.
Use case: setting limits for a Varnish in-memory caching proxy.

**Comment by geoffroyjabouley** [comment]
+1 for this feature, could be useful whenever dealing with docker java application and -Xmx option.

**Comment by fatz** [comment]
+1 I would also love to see `MARATHON_APP_DISK`

**Comment by schmandforke** [comment]
+1

**Comment by wendigo** [comment]
I did not see this issue but implemented this in #2787 :) Waiting for your comments.

**Comment by gkleiman** [comment]
Fixed by PR #2787.
