### ISSUE TITLE
Only the table body should scroll

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2507]
JIRA Key: MARATHON-442
Reporter: Chad Roffey
Priority: Medium

Description:
The header, the title bar (containing the search bar), the table header, and the filter panel should all be stationary. The table body content should consume the available space. When it runs out of room a scroll bar should appear.

**Comment by pierlo-upitup** [comment]
Not a bug ;)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2776. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
