### ISSUE TITLE
Can not connect to marathon after restart

### ISSUE THREAD

**Issue by BrickXu** [mesosphere/marathon#2508]
Hi,

I'm using Marathon 0.11.1 and Mesos 0.25.0 now. 

It works well for the first time, If I kill the Marathon process then start it again, I could not connect to the web ui via Chrome, but the Marathon process is running, no errors in the log file.

here is my command line flags:

```
export MARATHON_http_address=$BIND_IP
export MARATHON_http_port=$HTTP_PORT
export MARATHON_master=zk://XXXXXXX/mesos
export MARATHON_mesos_user=root
export MARATHON_mesos_role=logstash
export MARATHON_zk=zk://XXXXXXX/logstash
export MARATHON_mesos_authentication_principal=logstash
export MARATHON_mesos_authentication_secret_file=/home/marathon/etc/credential_logstash
export MARATHON_http_credentials=admin:91a5549748e76b41

nohup $PWD/bin/start  \
      --failover_timeout 3600 \
      --framework_name marathon-logstash \
      --ha \
      --hostname $HOSTNAME \
      --local_port_max 32000 \
      --local_port_min 8000 \
      --event_subscriber http_callback \
      --zk_timeout 30000 \
      2>&1 > /var/log/marathon.log &

```

I try to remove the path `/logstash` in ZK, even reinstall the marathon, but it does not work.

Now I must change the port if the Marathon restart.

**Comment by aquamatthias** [comment]
@BrickXu can you provide the log file? 
Have you tried to curl the port?

**Comment by BrickXu** [comment]
@aquamatthias  sorry, no logs left now. 
I've tried curl with -v and it return 401, then append authentication header, nothing returns.
Also, marathon return nothing via web broswer, and the log file shows no http request receive.

**Comment by aquamatthias** [comment]
There is a process that answered with a 401. Since your port is dynamically bound, are you sure you connect to correct one?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3574. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
