### ISSUE TITLE
Improve UI error messages

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2511]
At the moment Marathon UI's error messages are rendered in hidden `tr` elements and shown when relevant. This could be done better!

- [ ] Error messages should only be rendered when visible
- [ ] Error messages should not be within the app list table

**Update 11. Jan 2016 (pierlo)** Scope of this issue is to align the empty states with the first screens of https://mesosphere.invisionapp.com/share/6P56VR1XZ#/screens

- [ ] When no error but also no applications are shown, display a "Create your first app" button
- [ ] ~~When a scale operation is first scheduled, show the missing issues as "ghost rows" as shown [here](https://mesosphere.invisionapp.com/share/6P56VR1XZ#/screens/119296366)~~ (moved to https://github.com/mesosphere/marathon/issues/2945)

**Comment by aldipower** [comment]
We should think about a general/global notification overlay to display messages or something like that.
This overlay could be triggered by a flux-action from every place you can imagine.

@cleverroffey

**Comment by philipnrmn** [comment]
The current state of affairs is that the app list, the app instance instance list, and the deployment list all use the hidden `tr` technique. Error messages can stack up on top of each other. For brevity, the screenshots below show all possible error messages at once, which wouldn't ever happen, but hopefully are clear enough. 

#### Applications
![applications](https://cloud.githubusercontent.com/assets/2989362/11147891/8c613fc0-8a19-11e5-9b69-b3ecdeb5370f.png)
#### Instances
![instances](https://cloud.githubusercontent.com/assets/2989362/11147913/c21a6a24-8a19-11e5-9425-9d52c9ce6de6.png)
#### Deployments
![Deployments](https://cloud.githubusercontent.com/assets/2989362/11147929/d128a56c-8a19-11e5-9066-22e109110c48.png)

**Comment by aldipower** [comment]
Additionally we have errors in alert boxes, these alert boxes will be opened, if an asynchronous operation fails. Like fetching an app for editing, applying an old application configuration, scaling an application and so on.

#### Asynchronous errors
![alter-error](https://cloud.githubusercontent.com/assets/859154/11148120/08d468d8-8a1b-11e5-886a-7e45e807f51f.png)

... collecting error messages, please wait ...

**Comment by philipnrmn** [comment]
For completeness, there are other errors. 

#### Page not found (within webapp)
![not found](https://cloud.githubusercontent.com/assets/2989362/11148154/41111390-8a1b-11e5-9e7d-46f88c367264.png)

#### Page not found (outwith webapp)
![not found](https://cloud.githubusercontent.com/assets/2989362/11148160/4a936cce-8a1b-11e5-8b55-71f2aa5addc0.png)

#### Bad modal input
![bad input](https://cloud.githubusercontent.com/assets/2989362/11148170/5e3d317e-8a1b-11e5-96a6-4205289f8b9b.png)

**Comment by pierlo-upitup** [comment]
We should also prevent reaching non-existing apps:

![screen shot 2015-11-13 at 15 31 58](https://cloud.githubusercontent.com/assets/1078545/11148225/b8e27896-8a1b-11e5-9046-37a02c5a28c4.png)

**Comment by aldipower** [comment]
@pierlo-upitup Another topic.
Also you can't prevent this. Imagine you have an app opened on your computer and I will delete it on mine.. :)

**Comment by pierlo-upitup** [comment]
Sorry I just saw that @philipnrmn posted it already. My bad!
