### ISSUE TITLE
how to monitor a task restarts over a specific threshold times

### ISSUE THREAD

**Issue by gongaiguo** [mesosphere/marathon#2515]
I want to monitor a task restart times in a specific interval, through get events from the event_bus api.
But the task_id would changed each time it starts. 
How to implement the monitor policy?

ps. each app has many instances.

**Comment by gongaiguo** [comment]
+1

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4202. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
