### ISSUE TITLE
using `"requirePorts":true` and `"ports": [0]` causes deploy to hang forever.

### ISSUE THREAD

**Issue by abraithwaite** [mesosphere/marathon#2520]
Ran into this today accidentally.  On Marathon 0.23, haven't checked 0.24.

**Comment by bobrik** [comment]
@abraithwaite https://github.com/mesosphere/marathon/issues/2164#issuecomment-144490920

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4097. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
