### ISSUE TITLE
Service ports are assigned when servicePort is omitted

### ISSUE THREAD

**Issue by MacTynow** [mesosphere/marathon#2521]
Hi guys,

I ran into some unexpected behaviour (according to the docs : https://mesosphere.github.io/marathon/docs/native-docker.html). When you write a json with the following  : 

```"portMappings": [
        { "containerPort": 5000, "hostPort": 0, "protocol": "tcp" }
      ]```

it is equivalent to this : 

```"portMappings": [
        { "containerPort": 5000, "hostPort": 0, "servicePort": 0, "protocol": "tcp" }
      ]```

It automatically assigns a service port even though I omitted servicePort, because I don't want one to be assigned to this service that shouldn't be in service discovery.

The documentation says that servicePort is optional, I assumed it would mean it wouldn't assign one automatically if I didn't "ask" for one.

What are your thoughts?

**Comment by pierlo-upitup** [comment]
Hi @MacTynow,

from the docs:

> "servicePort" is a helper port intended for doing service discovery using a well-known port per service. The assigned servicePort value is not used/interpreted by Marathon itself but supposed to used by load balancer infrastructure. See Service Discovery Load Balancing doc page.** The servicePort parameter is optional and defaults to 0**. Like hostPort, If the value is 0, a random port will be assigned. If a servicePort value is assigned by Marathon then Marathon guarantees that its value is unique across the cluster. The values for random service ports are in the range [local_port_min, local_port_max] where local_port_min and local_port_max are command line options with default values of 10000 and 20000, respectively.

(bold mine)

**Comment by MacTynow** [comment]
Hi @pierlo-upitup, I don't see how this answers this issue. I read this part of the doc. If the parameter is optional, why does it default to 0 when I specifically omit it? In other terms, how do I do if I don't want a service port to be attributed to a service ?

**Comment by pierlo-upitup** [comment]
@MacTynow the docs clearly state this:

> The servicePort parameter is optional and defaults to 0

So if you don't supply the parameter, it will automatically default to 0. 

If you would like to continue the discussion on this topic or in general if you want to suggest changes may I suggest you to join our [Google Groups](https://groups.google.com/forum/#!forum/marathon-framework) if you haven't done so yet. 

As a rule of thumb we try to keep GitHub issues mostly for actual bug-reports. 
Thanks a lot for your understanding!

**Comment by MacTynow** [comment]
Alright, thanks for your answer, I'll post about this on Google Groups.
