### ISSUE TITLE
UI Filters are not applied to group (transitively)

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#2522]
When filtering (e.g. for type) the groups are not taken into account.
If there is an app in a group, that applies to that filter, than the group should be shown shown as well.

Example: 
/foo/app is currently deployed
/app is currently deployed

If I filter for deployments (top level), I would like to see:
Group foo (--> so that I know there are apps in deployment in foo)
App app

**Comment by mwasn** [comment]
@aldipower 
There is still an issue in the filtering function:

When I filter for _stephano_ I get three folder (which is not correct; should be one). Afterwards a add another character to the filter term and remove it again. --> Now I get the correct result set (one folder)

![filter](https://cloud.githubusercontent.com/assets/12829900/10694900/0a3d9b7a-79a1-11e5-9c62-b6ea8c8df7cb.gif)

**Comment by pierlo-upitup** [comment]
@mwasn this has been fixed by https://github.com/mesosphere/marathon-ui/pull/361
