### ISSUE TITLE
Status for group is not shown

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#2523]
Looking at the UI (e.g. top level) I need to see instantly:
- are there problems with any app (failing tasks, deployments, apps waiting for offer, delayed apps)
- is there any unhealthy app 

This information is currently only available if I click through every available group.

**Comment by mwasn** [comment]
Another solution could be to highlight the column "Running Instances" in red if not all instances are running. The user could go into that path and see on an app basis what´s happening...

**Comment by gkleiman** [comment]
Another solution: reflect the status in the group/app icon. I think that information is much more valuable than knowing whether an app is packaged with Docker or not.

**Comment by orlandohohmeier** [comment]
Just to bring up another solution... Add a new view (e.g. at the top) to highlight the current overall tasks health. The view could also provide quick links to failed/delayed apps. What do you think?

**Comment by leemunroe** [comment]
Another option we've been exploring.
* Remove status from folders completely to remove any confusion
* Add counts to the filters so users can see if there are apps that they need to look at
* When a user filters by status or anything else, the filtered results would only be applications, not folders (similar to how we want search results to work)

![status_counts](https://cloud.githubusercontent.com/assets/15963/10919816/b20259e4-8221-11e5-92d2-d824abf2006f.png)
*Note: This is a rough prototype, not a final visual representation*

Another option would be to keep the folder status as "worst case" status. What do others think about this, is folder status useful if the counts are in the sidebar?

**Comment by orlandohohmeier** [comment]
@leemunroe I like the folder "worst case" status as they're very easily recognisable and help users find groups with broken apps.

**Comment by orlandohohmeier** [comment]
@leemunroe What about adding a color to the filters ("delayed": red, ... ) to highlight if there is one or more app matching the app state filter?

**Comment by leemunroe** [comment]
@orlandohohmeier Good idea. Makes sense to tie the colors and icons with the filters some how.

**Comment by philipnrmn** [comment]
Bumped to 0.14.0 as it no longer blocks 0.14.0

**Comment by orlandohohmeier** [comment]
@leemunroe Could you please document the latest design decisions on this, considering the latest global search / filter design?

**Comment by leemunroe** [comment]
@orlandohohmeier Final design WIP but what we're thinking:

1. Continue to show worst case for groups (good visual indicator)
1. Show the counts in the filter sidebar using slightly modified design
1. Make the clickable area for filters the full width of the sidebar (including count)

Hypothesis being that by providing the filter counts users can easily get to the apps with problems.

![image](https://cloud.githubusercontent.com/assets/15963/11200276/9d97d714-8c89-11e5-9176-1f1a3dadf57b.png)

**Comment by aldipower** [comment]
@orlandohohmeier @leemunroe
The actual issue was fixed by this https://github.com/mesosphere/marathon-ui/pull/355 25 days ago.
Could we continue the result discussions in a new ticket?

**Comment by orlandohohmeier** [comment]
@aldipower We haven't addressed all issues yet and mesosphere/marathon-ui#355 was only a fix for part of the problem, thus I think we should use this ticket to discuss/find solutions.

**Comment by orlandohohmeier** [comment]
@aldipower We should definitely split such issue into smaller ones in the feature.

**Comment by aldipower** [comment]
Which issue isn't addressed?

**Comment by orlandohohmeier** [comment]
@aldipower  We still have no way to to see instantly if there is any unhealthy app.

**Comment by orlandohohmeier** [comment]
@aldipower Ok, as discussed we do have a solution but need to improve on that. I'll move that discussion to a new issue.

**Comment by aldipower** [comment]
Great, thanx! :)
