### ISSUE TITLE
Wording Basic: there might be Basic apps, but not every command line app is a basic app

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#2525]
We really should not upset people by saying - every non docker app is a basic app.

Suggestion: Command Line App

**Comment by philipnrmn** [comment]
Other suggestions that were kicked around:
cgroups, mesos native, shell app, bash app, native app, non-dockerized-but-still-containerized app...

I recall seeing a clearly stated decision on native app, but of course I can't find it now. I'll post the link when I next see it.

**Comment by pierlo-upitup** [comment]
@philipnrmn probably in an archived inVision board...

**Comment by gkleiman** [comment]
I'd go further and question whether distinguishing between Docker and non-Docker apps brings any value to the users. 

My opinion is that it doesn't.

**Comment by mwasn** [comment]
@philipnrmn : final decision can be found in the team sync meeting minutes. 

@aquamatthias I think "Command Line App" is too long for the side bar:
![image](https://cloud.githubusercontent.com/assets/12829900/10692523/6d7cb59a-7992-11e5-8c68-59181c94df07.png)

**Comment by orlandohohmeier** [comment]
It seems that users don't see any value in filtering applications by “basic” or “docker”. Let's remove the app type filter from the tab pan unless we have validation it will be useful.

**Comment by leemunroe** [comment]
+1 until further validation

**Comment by philipnrmn** [comment]
Fixed by mesosphere/marathon-ui#364
