### ISSUE TITLE
App id input looks a bit strange

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2527]
![](https://cloud.githubusercontent.com/assets/647035/10692587/e14e5172-7992-11e5-9554-3f077a3bdee9.gif)
The first input in the New Application Modal looks a bit strange before entering an app id. 
Environment: Win7 IE11

**Comment by pierlo-upitup** [comment]
I can reproduce this rendering quirk in IE11, but if anything this seems like an IE11 bug to me:

![ie11](https://cloud.githubusercontent.com/assets/1078545/11397927/7099a864-937d-11e5-8e68-1667567e64eb.gif)


basically as soon as the mouse is moved, the blinking cursor restores its actual position. Maybe we could hack some IE-specific solution together (trigger a repaint when the transition is completed, disable the transition, etc.) but I'm not too keen on doing that.

**Comment by orlandohohmeier** [comment]
I get the very same quirk rendering in Microsoft Edge. It seems to be an issue with transitions.

**Comment by pierlo-upitup** [comment]
My hunch is we should wait for the transition before focusing the input field.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2686. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
