### ISSUE TITLE
The New Application / Health checks close button (x) does not work

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2529]
JIRA Key: MARATHON-448
Reporter: Orlando Hohmeier
Priority: Medium

Description:
The New Application / Health checks close button (x) does not work and should be removed.

**Comment by aldipower** [comment]
Try to add an additional health check. Then you can remove the health checks with this button otherwise it clears the last standing health check.

**Comment by aldipower** [comment]
Not a bug to me, but a question of UX.

**Comment by pierlo-upitup** [comment]
Not a bug.

**Comment by orlandohohmeier** [comment]
Okay... It's a clear/remove button and it does work. We should use a different icon as it looks like the close button.

**Comment by leemunroe** [comment]
What I recommend

* Change the "x" icon for health checks to a minus style icon "–" so it's not confused with the modal close action
* Change the button copy to "Add Another Health Check"
* If the user clicks the minus icon on the first health check, remove the health check fields but keep a button with "Add A Health Check"

![image](https://cloud.githubusercontent.com/assets/15963/11010366/15e8d0e6-8493-11e5-91bc-b6e692a1af97.png)

![image](https://cloud.githubusercontent.com/assets/15963/11010423/887ab87c-8493-11e5-8cf4-ecc19335b9d2.png)

p.s. a whole new "Create" experience is on the roadmap

**Comment by aldipower** [comment]
@leemunroe: Perfect intermediate suggestions! Thanx!
