### ISSUE TITLE
LeadershipCallback.onElected: the default zk_timeout is too low with real world data

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#2532]
The whole zk state has to be read during startup time:
-groups
-apps
-tasks
In my example setup I had 500 apps with each one task. 
I got a timeout exception during leader election.

**Comment by gomes** [comment]
This worries me, I have 264 apps with 770 tasks currently. I had to decrease the number of versions in Zookeeper to 3.

**Comment by gkleiman** [comment]
@gomes: this doesn't affect any of the released versions and is a blocker, which means that it will be fixed before we ship the next release candidate (v0.13.0-RC1).

**Comment by kolloch** [comment]
Fixed by #2533
