### ISSUE TITLE
Marathon failed to deploy in loop with docker image pull, no errors

### ISSUE THREAD

**Issue by kopax** [mesosphere/marathon#2535]
Docker version 1.8.2, build 0a8c2e3
    DOCKER_APP_VERSION            1.8.2-0~trusty
    MESOS_APP_VERSION             0.23.0-1.0.ubuntu1404
    MARATHON_APP_VERSION          0.11.0-1.0.425.ubuntu1404

I cannot deploy a simple image.
The image I want to install was tested in local and in server

    docker pull secretrepo/registry
    docker run -p 5000:5000 -v srv/docker/registry:/var/lib/registry secretrepo/registry
    "listening on [::]:5000"

Marathon return no logs about the error
Mesos UI display a lots of application started and finished

_Mesos task stderr_

    I1023 18:10:21.162006  8509 exec.cpp:134] Version: 0.25.0
    I1023 18:10:21.164427  8512 exec.cpp:208] Executor registered on slave 7c948886-744c-4a21-a2f5-27ba3ded7fd4-S0
    WARNING: Your kernel does not support memory limit capabilities. Limitation discarded.
    WARNING: Your kernel does not support memory swappiness capabilities, memory swappiness discarded.

_Mesos task stdout_

    --container="mesos-7c948886-744c-4a21-a2f5-27ba3ded7fd4-S0.054cdabd-3419-4ed3-8e58-aa432873ac38" --docker="/usr/local/sbin/docker" --docker_socket="/var/run/docker.sock" --help="false" --initialize_driver_logging="true" --logbufsecs="0" --logging_level="INFO" --mapped_directory="/mnt/mesos/sandbox" --quiet="false" --sandbox_directory="/tmp/mesos/slaves/7c948886-744c-4a21-a2f5-27ba3ded7fd4-S0/frameworks/f1d1c38f-b267-4a59-bb97-688b1f15f8c3-0000/executors/registry.52d85650-79b1-11e5-a5a5-eebffa311d4a/runs/054cdabd-3419-4ed3-8e58-aa432873ac38" --stop_timeout="5secs"
    --container="mesos-7c948886-744c-4a21-a2f5-27ba3ded7fd4-S0.054cdabd-3419-4ed3-8e58-aa432873ac38" --docker="/usr/local/sbin/docker" --docker_socket="/var/run/docker.sock" --help="false" --initialize_driver_logging="true" --logbufsecs="0" --logging_level="INFO" --mapped_directory="/mnt/mesos/sandbox" --quiet="false" --sandbox_directory="/tmp/mesos/slaves/7c948886-744c-4a21-a2f5-27ba3ded7fd4-S0/frameworks/f1d1c38f-b267-4a59-bb97-688b1f15f8c3-0000/executors/registry.52d85650-79b1-11e5-a5a5-eebffa311d4a/runs/054cdabd-3419-4ed3-8e58-aa432873ac38" --stop_timeout="5secs"
    Registered docker executor on prod-02
    Starting task registry.52d85650-79b1-11e5-a5a5-eebffa311d4a

_Marathon image configuration_

    {
      "type": "DOCKER",
      "volumes": [
        {
          "containerPath": "/var/lib/registry",
          "hostPath": "/srv/docker/registry",
          "mode": "RW"
        }
      ],
      "docker": {
        "image": "secretrepo/registry",
        "network": "BRIDGE",
        "portMappings": [
          {
            "containerPort": 5000,
            "hostPort": 0,
            "servicePort": 5000,
            "protocol": "tcp"
          }
        ],
        "privileged": false,
        "parameters": [],
        "forcePullImage": false
      }
    }

Not a single logs in marathon, don't know if this is a marathon issue.

**Comment by samek** [comment]
Do you have port 5000 opened in mesos slave configuration ?
eg.
        cat /etc/mesos-slave/resources 
        ports(*):[4000-4500, 7000-7001, 7199-7199, 8000-9500, 31000-32000] 

on Marathon 11.0/1 if docker info entered from the UI has to have cmd stated otherwise it starts the docker with /bin/sh -c " " - (I think there's a issue reported on that already) so try adding actual cmd to it. 

I would first try those two.

**Comment by kopax** [comment]
This was solved by upgrading my config to latest version of marathon
