### ISSUE TITLE
Cannot edit configuration through UI for apps using docker without command

### ISSUE THREAD

**Issue by johngian** [mesosphere/marathon#2538]
Version: 0.11.1
Steps to reproduce:
- Deploy an app using docker
  - Example definition: https://gist.github.com/johngian/8c843f25e9b74ef0cec7
- Edit a configuration field through web UI
  - Go to configuration > edit
  - eg. edit # of instances
- API response returns error: `Invalid JSON, path:/cmd, error:minlength`

Expected behaviour:
Since `command` field can be left blank, this form submission should be valid.

**Comment by Perdjesk** [comment]
Moreover when you create an app by using the UI and you left blank the command field the app will be created but the command field will be fed with a space character.

Thus the app will be never be able to run because every docker run command will be wrong.

Version 0.11.1 

```
sudo docker ps -a | grep ghost
ffd03041052a        ghost               "/bin/sh -c ' '"         Less than a second ago   Up Less than a second         2368/tcp 
```

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4429. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
