### ISSUE TITLE
Docker command url-encoded

### ISSUE THREAD

**Issue by jfindley** [mesosphere/marathon#2541]
In marathon 0.11.1, docker commands are sometimes erroneously url-encoded.

E.g.  an app with: `"cmd": "logstash -e 'foo => bar' "` is passed to docker as `logstash -e 'foo =\u003e bar'`

**Comment by pierlo-upitup** [comment]
Hi @jfindley,

does that happen when using the web UI or from the CLI as well?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2788. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
