### ISSUE TITLE
how to share common env in a group of apps

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#2542]
like this:
the apps can access GROUP_PARAM1,GROUP_PARAM2 or not ?
how to achieve this goal?
thanks !
{
    "id": "group-app-test",
    "apps": [
        {
            "id": "app-test01",
            ...
        },
        {
            "id": "app-test02",
            ...
        },
        {
            "id": "app-test03",
            ...
        },
        {
            "id": "app-test04",
            ...
        }
    ],
    "env": {
        "GROUP_PARAM1": "1234567890",
        "GROUP_PARAM2": "0987654321"
    }
}

**Comment by pierlo-upitup** [comment]
@junneyang the `env` field is per-app, and is ignored by `groups`. https://mesosphere.github.io/marathon/docs/task-environment-vars.html

**Comment by junneyang** [comment]
i know what you say

my goal is that is there any way to share common env/variables in different apps？

thanks
