### ISSUE TITLE
Resources Filter does not work

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#2554]
![screenshot_02](https://cloud.githubusercontent.com/assets/330485/10910685/144de77a-8241-11e5-9009-61ed8d339245.png)

- the default value is not recognizable as such (it even is lighter than a real value) See this example: ![screenshot_03](https://cloud.githubusercontent.com/assets/330485/10910758/7fdc52c4-8241-11e5-88fa-378d9dca10d8.png) where CPU is defined, but Memory not
- if values are defined, they don't have any effect

**Comment by mwasn** [comment]
Not implemented yet. OVH points not the branch to be released.
