### ISSUE TITLE
Provide a Docker setup for kickstarting UI development

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#2556]
It would be nice to have a mocked API Server to enable [mesosphere/marathon-ui](/mesosphere/marathon-ui) collaboration without the need to install the full meos/marathon stack. Such a server would also help with design testing. What do you think?

/cc @aldipower @pierlo-upitup 

**UPDATE**
We think that to lower the entrance barrier for aspiring contributors the best solution would be to get rid of the Mesos/Marathon manual installation and the need for a CORS proxy. In our eyes, the easiest solution would be to leverage the existing docker images and simply compose them together to provide a complete environment to develop against.

**Comment by aldipower** [comment]
Generally a good idea, let the Marathon UI run out-of-the-box, but I am very concerned about maintaining this mocked API alongside the real API. Who would be or would feel responsible for this? I've the fear that this mocked server behaves different then the real API.

**Comment by pierlo-upitup** [comment]
Yeah. I think a better approach would be some sort of provisioned VM (via Vagrant?) with a predefined set of running apps that kinda cover a lot of test cases. But again, that requires gardening.

**Comment by orlandohohmeier** [comment]
@aldipower @pierlo-upitup Good point... I think a Vagrant box should work. Maybe we can use the [playa-mesos](/mesosphere/playa-mesos) box. I'll have a look. Thanks for your input!

**Comment by philipnrmn** [comment]
I use an nginx configuration which allows me to use the browserify and live reload servers against local or remote marathon APIs. A nice compromise might be to package this up and add it to the repository along with documentation on how to use it.

**Comment by orlandohohmeier** [comment]
This is a minimum Vagrantfile to run Mesos and Marathon (using the [playa-mesos](/mesosphere/playa-mesos) box). The only missing part is a link/proxy to the current (local) UI version. I was wondering if we're somehow able to use synced folders to let Marathon deliver the current version. What do you think?

```ruby
Vagrant.configure(2) do |config|

  # Use the playa-mesos box
  config.vm.box = 'playa_mesos_ubuntu_14.04'
  config.vm.box_url = "http://downloads.mesosphere.io/playa-mesos/#{config.vm.box}-virtualbox.box"

  # Create a private network, which allows host-only access to the machine
  # using a specific IP.
  config.vm.network :private_network, ip: '10.141.141.10'

  # If true, then any SSH connections made will enable agent forwarding.
  # Default value: false
  config.ssh.forward_agent = true

  # Configure vm memory size and the number for cpus as suggest in
  # mesosphere/playa-mesos
  config.vm.provider :virtualbox do |vb|
    vb.customize ['modifyvm', :id, '--memory', 2048]
    vb.customize ['modifyvm', :id, '--cpus',   2]
  end

end
```

**Comment by pierlo-upitup** [comment]
Regarding the Marathon UI part, I think a low-hanging fruit is to make use of the Webpack DevServer which supports proxy settings out of the box. Regarding the Mesos/Marathon stack, I think it's a possibly larger story that we might want to postpone for the time being.

**Comment by pierlo-upitup** [comment]
For the webpack devServer issue please refer to https://github.com/mesosphere/marathon/issues/1688
