### ISSUE TITLE
Enabling SSL: Does MARATHON_JKS_PASSWORD need to be equal to MARATHON_PKCS_PASSWORD?

### ISSUE THREAD

**Issue by caussourd** [mesosphere/marathon#2563]
I followed this procedure to enable SSL: 
https://github.com/mesosphere/marathon/blob/master/docs/docs/ssl-basic-access-authentication.md

Actually for me it was slightly different as I already have a certificate, so I created the pkcs12 file this way: 
`openssl pkcs12 -export -out mydomain.p12 -inkey private.key -in certificate.crt -certfile CACert.crt -name marathon`
and provided the MARATHON_PKCS_PASSWORD password. 

and then I imported the entry as mentioned in the documentation: 
`keytool -importkeystore  -srckeystore mydomain.p12 -srcstoretype PKCS12 -srcstorepass $MARATHON_PKCS_PASSWORD -alias marathon -deststorepass $MARATHON_JKS_PASSWORD -destkeystore marathon.jks`

Then I started marathon providing the path to marathon.jks and the MARATHON_JKS_PASSWORD password as mentioned in the documentation. 
But Marathon was starting with the error `java.security.UnrecoverableKeyException: Cannot recover key` and I couldn't access `https://localhost:8443/v2/apps`

After some research, I recreated the keystore with this time MARATHON_JKS_PASSWORD = MARATHON_PKCS_PASSWORD. Basically, using the same password. And this time it worked. Also it makes sense to me as we are providing MARATHON_JKS_PASSWORD to Marathon but not MARATHON_PKCS_PASSWORD... so, how does it know about it? So I'm wondering if it can actually work with the keystore password different for the pkcs12 password as the documentation is suggesting.

**Comment by pierlo-upitup** [comment]
Hi @caussourd and thanks for reporting this. 
We will take a closer look and get back to you as soon as we can.

**Comment by pierlo-upitup** [comment]
Just one question: could you please provide which Marathon, Mesos and ZooKeeper versions you are running?

**Comment by caussourd** [comment]
@pierlo-upitup 
Marathon  0.10.1
Mesos 0.23.0
Zookeeper 3.4.6

**Comment by kevincox** [comment]
Note that I was running into the same problem and making them the same fixed it.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3631. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
