### ISSUE TITLE
Reject application json with undefined/superfluous json

### ISSUE THREAD

**Issue by discordianfish** [mesosphere/marathon#2564]
It would be cool if the API would reject application json POSTs to the /v2/apps endpoint which contain superfluous elements. For instance I spend (too much) time debugging why my marathon application doesn't bind-mount it's volume until I realize that 'volumes' isn't child of 'docker' but directly on 'container'.
If marathon would fail when it reads elements not defined, this class of errors would be much simpler to debug.

**Comment by gkleiman** [comment]
Duplicated of #2164.
