### ISSUE TITLE
Port mappings do make sense when container is in net=host mode

### ISSUE THREAD

**Issue by gtmtech** [mesosphere/marathon#2566]
I was just reading through recent changelog notes and came across this in marathon-ui - which Im unable to add an issue to:

https://github.com/mesosphere/marathon-ui/blob/master/CHANGELOG.md

#2248 - port mappings dont make sense when container in net=host mode.

Unfortunately this is incorrect. Lots of people use registrator, which via the inspect API tracks ports of net=host containers via this exact mechanism.

So port mappings do alter the metadata for docker which some tools use. 

Unfortunately issues in marathon-ui are private, so I'll add this here instead.

**Comment by pierlo-upitup** [comment]
Hi there @gtmtech,

thanks for reporting this. 

As you noticed, `marathon-ui` is a separate repo, but we use the `marathon` repo to track all issues. As [mentioned in our Contributing.md](https://github.com/mesosphere/marathon-ui/blob/master/CONTRIBUTING.md) if you want to create a UI related issue simply add the `gui` label when opening an issue here. I just did that for you ;)

Thanks a lot for your report – we will take a closer look and get back to you.

**Comment by aquamatthias** [comment]
@gtmtech Thanks for highlighting this. The functionality is available from the REST endpoint. We will re-enable this in the UI.

**Comment by pierlo-upitup** [comment]
Let's restore portMappings in the modal dialog even if they're usually not needed/required in Host mode, then.
