### ISSUE TITLE
/v2/tasks returns tasks in random order

### ISSUE THREAD

**Issue by rasputnik** [mesosphere/marathon#2567]
(this is an old release - 0.7.5 - but I haven't seen any commits that would fix it in later releases).

Despite being fine for months, yesterday our 3-node marathon cluster started returning tasks in a different
order every other time it was polled. This caused havoc on the service discovery layer, as the different order caused constant haproxy reloads on all slaves and gateways.

is there a 'contract' that this order should be maintained, or should discovery solutions that use this information assume it will be random and sort accordingly?

**Comment by kolloch** [comment]
Yes, it should be considered random. The service discovery solution should sort it to make sure it doesn't update configuration unnecessarily.

**Comment by rasputnik** [comment]
thanks, that's what i'd assumed. looks like a recent commit to bamboo has broken things, i'll work on fixing it at that layer. thanks.
