### ISSUE TITLE
services refuses to start with requirePorts = true 

### ISSUE THREAD

**Issue by rodrickbrown** [mesosphere/marathon#2575]
Mesos-dns uses a fixed port and using the following definition I'm unable to start this application on port 8053. Only after setting requirePorts: false does the process come up 

{
    "id": "/mesos/dns-service",
    "cmd": "env && /bin/mesos-dns -config /etc/mesos/mesos-dns.config -alsologtostderr",
    "cpus": 0.5,
    "mem": 1024,
    "disk": 20,
    "user": "mesos",
    "instances": 3,
    "requirePorts": true,
    "ports": [ 8053 ],
    "constraints": [
      [
        "rack",
        "UNLIKE",
        "2"
      ]
    ],
    "maxLaunchDelaySeconds": 3,
    "backoffFactor": 1.20,
    "ports": [
      0
    ],
		"upgradeStrategy": {
        "minimumHealthCapacity": 0.5,
        "maximumOverCapacity": 0.5
    }
}

I'm using the following versions 

$ rpm -qf /bin/mesos
mesos-0.25.0-0.2.70.centos701406.x86_64
$ rpm -qf /usr/bin/marathon
marathon-0.11.1-1.0.432.el7.x86_64

**Comment by junneyang** [comment]
port must between 31000-32000

**Comment by rodrickbrown** [comment]
Even when setting the port to 31853 and using requirePorts: True the service just hangs deploying.

**Comment by junneyang** [comment]
![image](https://cloud.githubusercontent.com/assets/6802322/10988472/70d0ca5c-8477-11e5-81db-e5d627825e56.png)

your configuration is correct?

**Comment by InformatiQ** [comment]
I have the same problem

`
{
  "id": "/test",
  "cmd": "python -m SimpleHTTPServer $PORT0",
  "instances": 1,
  "cpus": 1,
  "mem": 32,
  "disk": 0,
  "ports": [32180],
  "requirePorts": true
}
`
no other app on my slaves is using that same port
