### ISSUE TITLE
Can use etcd instead of zookeeper for marathon to store apps info

### ISSUE THREAD

**Issue by xianlubird** [mesosphere/marathon#2577]
When run above 1000 container as apps on marathon,marathon will beacome very slow.

The bottleneck is zookeeper , every app is a node in zookeeper. 

If we use etcd to store app, whether it will perform better?   

I see that mesos have a issue to use etcd instead of zookeeper, does marathon have the same plan?

**Comment by xiaods** [comment]
give some measure data to prove your words.

**Comment by aquamatthias** [comment]
@xianlubird 
1) Would be great if you could share some performance data to understand, what slow means. (Use /metrics for example to retrieve metrics data)
2) Please try out Marathon 0.13.0-RC1 which has a store cache enabled by default. 
3) We do have a pluggable persistent store interface (https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/util/state/PersistentStore.scala) There is currently no plan of adding etcd, but it should be fairly easy.

**Comment by mcortinas** [comment]
Why @xianlubird has closed this ticket? 
Maybe if mesos is working on use etcd instead of zk (https://issues.apache.org/jira/browse/MESOS-1806) , it should be a good idea avoid have got the zookeeper just for marathon.

**Comment by janisz** [comment]
I think Mesos will drop all external dependencies  (ZK and docker)  and will finally implement its own leader election system (source @benh [answer on MesosCon EU 2015](https://youtu.be/K-x7yOy8Ymk?t=34m)

**Comment by jasongilanfarr** [comment]
We significantly redid the storage layout in ZK - which is very different from leader election (which is what the mesos ticket is about). The backend storage shouldn't be a significant issues after 1.4.

There are currently no plans to add new storage backends or leaderelection backends at this time.

**Comment by janisz** [comment]
According to the [Roadmap] (https://cwiki.apache.org/confluence/display/MESOS/Roadmap) Mesos will add support for etcd this year.
