### ISSUE TITLE
marathon is not killing unhealthy tasks

### ISSUE THREAD

**Issue by felixb** [mesosphere/marathon#2583]
I've configured HTTP health checks for a task:

    [{
      "path": "/internal/healthcheck",
      "protocol": "HTTP",
      "portIndex": 0,
      "gracePeriodSeconds": 5,
      "intervalSeconds": 2,
      "timeoutSeconds": 1,
      "maxConsecutiveFailures": 0,
      "ignoreHttp1xx": false
    }]

For some reasons, the task comes up not responding to health checks in a way, that the health check times out on L4.
I've seen, that marathon is trying to do the health check multiple times:

    [WARN] [11/06/2015 15:08:05.663] [marathon-akka.actor.default-dispatcher-45] [akka://marathon/user/IO-HTTP/host-connector-7754/2] Connection attempt to mesos-slave-*******:31268 failed in response to GET request to /internal/healthcheck with 5 retries left, retrying...
    [WARN] [11/06/2015 15:08:05.664] [marathon-akka.actor.default-dispatcher-39] [akka://marathon/user/IO-HTTP/host-connector-7754/0] Connection attempt to mesos-slave-*******.lhotse.ov.otto.de:31268 failed in response to GET request to /internal/healthcheck with 5 retries left, retrying...
    [WARN] [11/06/2015 15:08:05.664] [marathon-akka.actor.default-dispatcher-46] [akka://marathon/user/IO-HTTP/host-connector-7754/1] Connection attempt to mesos-slave-*******.lhotse.ov.otto.de:31268 failed in response to GET request to /internal/healthcheck with 1 retries left, retrying...

    [..]

    [WARN] [11/06/2015 15:08:08.664] [marathon-akka.actor.default-dispatcher-49] [akka://marathon/user/IO-HTTP/host-connector-7754/1] Connection attempt to mesos-slave-*******.lhotse.ov.otto.de:31268 failed in response to GET request to /internal/healthcheck with 4 retries left, retrying...
    [WARN] [11/06/2015 15:08:08.665] [marathon-akka.actor.default-dispatcher-48] [akka://marathon/user/IO-HTTP/host-connector-7754/2] Connection attempt to mesos-slave-*******.lhotse.ov.otto.de:31268 failed in response to GET request to /internal/healthcheck with 2 retries left, retrying...
    [WARN] [11/06/2015 15:08:08.665] [marathon-akka.actor.default-dispatcher-45] [akka://marathon/user/IO-HTTP/host-connector-7754/0] Connection attempt to mesos-slave-*******.lhotse.ov.otto.de:31268 failed in response to GET request to /internal/healthcheck with no retries left, dispatching error...

But there is no log message stating `Received health result: [Unhealthy(...`.
Marathon does not kill the task. It stays there until someone kills the task by hand.

Running `mesos-0.25` with `marathon-0.11.1`.

**Comment by pierlo-upitup** [comment]
Hi @felixb,

from [the docs](https://mesosphere.github.io/marathon/docs/health-checks.html):

> A health check is considered passing if (1) its HTTP response code is between 200 and 399, inclusive, and (2) its response is received within the timeoutSeconds period. **If a task fails more than maxConsecutiveFailures health checks consecutively, that task is killed**.

(my bold)

Have you tried raising the `maxConsecutiveFailures` to a meaningful value?

**Comment by felixb** [comment]
I don't want to raise it. I want marathon to recognize the task as failed and kill it.
`gracePeriod` and stuff is quite short.

**Comment by pierlo-upitup** [comment]
@felixb [from the docs](https://mesosphere.github.io/marathon/docs/health-checks.html):

> maxConsecutiveFailures(Optional. Default: 3) : Number of consecutive health check failures after which the unhealthy task should be killed. If this value is 0, then tasks will not be killed due to failing this check.

**Comment by felixb** [comment]
alright. then it's my fault I guess. thanks for the hint.
