### ISSUE TITLE
Sorting by CPU causes row column to expand

### ISSUE THREAD

**Issue by daiyiwhale** [mesosphere/marathon#2585]
The sort caret gets pushed up, causing the row to expand. Just a minor visual bug, thought I might bring it up (:

![](http://cl.ly/image/0j3U1D0Z1Q0a/Screen%20Recording%202015-11-06%20at%2011.05%20AM.gif)

**Comment by orlandohohmeier** [comment]
This is probably the same table header issue as in #2586

**Comment by daiyiwhale** [comment]
Maybe a spacing issue with column width?

**Comment by orlandohohmeier** [comment]
Yeah, probably.
