### ISSUE TITLE
Port mapping

### ISSUE THREAD

**Issue by kopax** [mesosphere/marathon#2587]
I am experience some trouble assigning port.

I know there is a range that marathon can assign.

If i do 

    { "containerPort": 1194, "hostPort": 0, "servicePort": 1194, "protocol": "tcp" }

I want to have the 1194 port.

There are some service like : email, gitlab, https, you don't wan't to get another port assigned and still wan't to have a virtual interface, is there a way to tell mesos to allow some ports, and if possible is it possible to customize it by port ?

Otherwise, is it possible to force marathon in a way ?

**Comment by junneyang** [comment]
you could ref:
https://mesosphere.github.io/marathon/docs/native-docker.html#bridged-networking-mode

![qq 20151109111230](https://cloud.githubusercontent.com/assets/6802322/11025159/ca799932-86d2-11e5-8858-07f66bf8acd5.png)

**Comment by kopax** [comment]
The problem is that with marathon 0.11.1 and mesos 0.25, the bridged fixed port mapping doesn't work for me.
Even if I set "servicePort", "containerPort" to a mesos available port, marathon/mesos keep starting the service on a randgom port.

**Comment by kolloch** [comment]
Hi @kopax,

you are using BRIDGED networking, right?

What do you want to achieve?

In this case, the containerPort is what you should bind to inside of your container. The hostPort is what is allocated by mesos and what other services connect to. You have to make sure that the mesos slaves are configured to actually offer the port that you require.

Docker makes sure that the hostPort on the host IP is forwarded to the containerPort on the container IP. 

The servicePort is something quite different. Marathon itself does not interpret it but it is used by some service discovery solutions.

Note that the `$PORT*` environment variables point to the assigned host ports and not the container port. In your case (as is usual) the container port is fixed and can be hard-coded into your configuration.

Generally, it is problematic to require a fixed host port in a dynamic environment like Mesos. Even if you configure the mesos slaves to offer the ports and require them in your app definition, you have to make sure that no task of any framework in your cluster uses those ports by accident.

**Comment by kolloch** [comment]
I hope that my comment helped you. If not, please reopen and tell us a bit more about what you want to achieve and what exactly doesn't work as expected.

**Comment by kopax** [comment]
Thanks for all the explaination @kolloch.

What I am trying to achieve is get a fixed port for my vpn so I don't have to change the client config all the time :)

I am not sure if I understand perfectly, and yes, I do use network BRIDGE.

I was thinking that servicePort was the "outside port", from what I read, I understand that I should use hostPort.

A small resume of what you say : 

- containerPort is the port used inside the container
- hostPort is the port used outside the container
- servicePort is the port used outside the container and only for some discovery service.

env  `PORT` can help to have a configurable port inside the container

To get a working config, i should replace this : 

    { "containerPort": 1194, "hostPort": 0, "servicePort": 1194, "protocol": "tcp" }

by this 

    { "containerPort": 1194, "hostPort": 31800, "servicePort": 31800, "protocol": "tcp" }

**Comment by kolloch** [comment]
If you do not use a load balancer that uses the servicePort to configure itself, you should not set the servicePort at all.

With the proposed configuration, your app should be accessible via the hostPort = 31800 from other hosts.

**Comment by kopax** [comment]
Sorry I forgot to say I was using haproxy, my configuration is not working through ha proxy.

    # TCP forwarding service: vpn: 31840
    listen tcp_vpn : 31840 <- hostPort
        mode    tcp
        option  tcplog
        balance roundrobin
        server  master-02_31705 10.0.0.1:31705 check <- servicePort ?

**Comment by kopax** [comment]
Coming back to @junneyang comment, what is the best approach for starting a container with special port like SMTP server. Is it better to let the container scale until it find a slave with the available port 25 + start some slave with 25 available or just using `network: "HOST"` and scale until it find a host ?

**Comment by kolloch** [comment]
There is not one best way to do these things.

One good approach is 
* To separate hosts that are publicly reachable by using a special mesos role (as done in DCOS). 
* To export all ports to mesos except the mesos ports itself.
* Bind the service or a forwarder to the service to the roles of these "public slaves" (nodes) with "acceptedResourceRoles".

It is also possible to have special hosts that are used as entry points from outside of the cluster and just configure load balancers on them. For these, you could just bypass Mesos for PORT configuration.

If you find a nice way to configure these things, please contribute to our documentation and provide a tutorial.
