### ISSUE TITLE
docker portMappings protocol type ?

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#2592]
https://mesosphere.github.io/marathon/docs/native-docker.html

this ref says:
![qq 20151109174544](https://cloud.githubusercontent.com/assets/6802322/11030543/ba05aa82-8709-11e5-8e3b-f5f7a71eb0a2.png)

just include tcp, what are the others type ?

thanks

**Comment by pierlo-upitup** [comment]
Thanks for the heads up @junneyang – I opened a PR to explicitly name the 2 possible `portMappings` values in the docs page: `tcp` and `udp`.
