### ISSUE TITLE
Very long labels expand horizontal scrollbar in app list

### ISSUE THREAD

**Issue by aldipower** [mesosphere/marathon#2593]
In the application list view, if I have an application with a very long label, the horizontal scrollbar expands by this label. This is unintentional because the contents of the label are hidden or cut.

This app has a label with over 1000 characters, look at the horizontal scrollbar:
![long-label](https://cloud.githubusercontent.com/assets/859154/11030658/b72872ac-86cf-11e5-8dc2-cd96377fa152.png)

**Comment by mwasn** [comment]
@mgummelt has reported a related issue which we should fix along with this. User tend to use labels not only for metadata but also injecting code. Have seen an example at a customer where they added autoscaling code to the labels. 

![screenshot from 2015-11-09 14-47-13](https://cloud.githubusercontent.com/assets/12829900/11051056/8a20d98a-8700-11e5-994c-74122af44d0d.png)

So we might think of shortening the actual value we show. A tooltip is implemented already to show the value key value pair.

cc/ @leemunroe

**Comment by leemunroe** [comment]
Was able to reproduce the horizontal scrollbar but not the long label. When I add a long label it seems to collapse to an ellipsis for me.

![image](https://cloud.githubusercontent.com/assets/15963/11054880/dc7e9ff8-8725-11e5-8020-5d12ee111739.png)

**Comment by philipnrmn** [comment]
Hi @leemunroe, labels do collapse to ellipsis if there's no room for them on the screen (from your screenshot it looks like your browser window is quite narrow).

The issue that @mgummelt raised is that very long labels which do fit on the screen don't look very good.

**Comment by aldipower** [comment]
Both issues described here are now solved.
