### ISSUE TITLE
HealthCheck reconciliation requires exact AppVersion for every task

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#2594]
When the `MarathonHealthCheckManager` reconciles running tasks with running HealthCheckActors, it needs to be able to retrieve the health check configuration for every AppDefinition version for which there still exist tasks. See https://github.com/mesosphere/marathon/blob/3d2955f0f316c5ec19489ee23f7cd3eaa022bba8/src/main/scala/mesosphere/marathon/health/MarathonHealthCheckManager.scala#L139-L152

This is problematic because:
- We recommend to restrict the number of versions to keep of every configuration item. (Otherwise we would have unbounded growth of the zookeeper storage.)
- And every scaling operation creates a new version of the AppDefinition.

So imagine the following scenario:
- Assume we restrict the configuration versions we keep to 2.
- Create app with 1 instance:
  - creates AppDefinition version 1
  - starts task1
- Scale it to 2 instances
  - creates AppDefinition version 2
  - starts task2
- Scale it to 3 instances
  - creates AppDefinition version 3 and drops version 1
  - starts task3

When the above code runs, it will not create HealthCheckActors for task1. Health information for that task will not be available.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2687. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
