### ISSUE TITLE
Document how to set up "Network isolation support"

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2601]
Create a document (must not be pushed to the official documentation as long as nothing is merged to Master) which provides guidance on
- How to set up Marathon (if any preparation must be done)
- Example JSONs 
- General walk through from set up to launch an app

**Comment by aquamatthias** [comment]
Moved to 0.15. - because it is unclear in the moment how to setup Network Isolation in the cluster.
We have documentation how to use that feature from Marathon, given it is enabled in the cluster.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2749. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
