### ISSUE TITLE
Can't pull docker image

### ISSUE THREAD

**Issue by kopax** [mesosphere/marathon#2602]
Failed to launch container: Failed to 'docker -H unix:///tmp/docker.sock pull registry.mydomain.com/work/app-web-test:7': exit status = exited with status 1 stderr = Error: image work/app-web-test:7 not found

Everytime I have to connect myself and pull the image with ssh.

Am I missing something ?

Marathon 0.11.1
Mesos 0.25
Docker version 1.8.2, build 0a8c2e3

**Comment by meichstedt** [comment]
@kopax Have you seen the documentation about using [private docker registries](https://mesosphere.github.io/marathon/docs/native-docker-private-registry.html)?

**Comment by kopax** [comment]
Yes I did, I was using that on all my docker images.

    "uris":  [
      "file:///etc/docker.tar.gz"
     ]

Then I noticed that it wasn't working at all. Where should be stored the docker.tar.gz ?

**Comment by hotstepper13** [comment]
As you configured, put the file in the /etc/ directory.

This might be an authentication issue as most registries sending a not found if any authentication attempt does not succeed. (seen by docker-registry and artifactory).

You have to be sure the follwing things:
1. You to create a valid login configuration by using "docker login <your_registry_url>"
2. Now follow the documention to archive the configuration files
3. Put the archive / Tarball to a location that is readable by the marathon user
4. Repeat on all mesos slave nodes (if there are any)

**Comment by kopax** [comment]
Ok well it was me. Following the documentation made it work.
