### ISSUE TITLE
Handle unrecognized api error attributes

### ISSUE THREAD

**Issue by aldipower** [mesosphere/marathon#2609]
The API has many inconsistent approaches of returning error attributes on app creation or editing.
In general it has this property `errors.[index].attribute`, but the identifier in `attribute` is inconsistent in it's structure.
We try to map the attributes in the AppFormStore, however we cannot trust the structure of the error attribute and don't handle them completely unfortunately, because we cannot be aware of all of them.

So we should find a way to show unhanded attributes as a general error.

A good example is, if something is going wrong with groups, the attribute can look differently:

```
apps
```

or

```
groups[0].apps
```

or

```
groups[0].groups[0].apps
```

Currently `groups[0].groups[0].apps` would be mapped untouched to an fieldId and it's not treated as an general error, but this fieldId doesn't exist, so the error is not shown at all.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3117. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
