### ISSUE TITLE
Option to disable Docker volumes from preventing migration

### ISSUE THREAD

**Issue by ghost** [mesosphere/marathon#2614]
It's possible this is a mesos issue, if so I will refile. Give that I have a docker container with a volume attached (in my case it's a single instance of mariadb), and that volume is pointed at shared storage (in our case an NFS mount) if the host that it's running goes down Marathon will never migrate the container to another host (I'm assuming because it wants to reattach the volume which it assumes is local).

It would be helpful to have an option in the volume specification to tell Marathon that this is the case so that it will migrate the instance anyway and remount the same path. Something like this:

```
  {
    "containerPath": "/var/lib/mysql",
    "hostPath": "/mnt/nfs/database/db1",
    "sharedStorage": "true", # false by default to keep the status quo
    "mode": "RW"
  }
```

Currently it's actually possible to get an application that is completely stuck in marathon unable to be removed until the original host becomes available again ( I tried scaling to zero which put a deployment into place which I was unable to stop, though this was only tested from the UI, I was then unable to destroy the application even with the deployment cancelled).

This would also be useful in the case where you're using a volume-driver that already uses shared storage directly (nfs/gluster/whatever) though I haven't tested what Marathon will do in that case.

**Comment by junneyang** [comment]
the same problem i stuck

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4195. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
