### ISSUE TITLE
get Futures timed out message, but the operation success

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#2617]
sometimes, when new app or delete app

curl -X POST http://10.5.24.21:8080/v2/groups -d @build.json -H "Content-Type: application/json"
curl -X DELETE http://10.5.24.21:8080/v2/groups/test?force=true -H "Content-Type: application/json"

it may return:
![image](https://cloud.githubusercontent.com/assets/6802322/11089326/d41f496e-88a3-11e5-87e4-22a1bc1d0d3d.png)

but, in fact, the new or the delete operation success!

thanks!

**Comment by aquamatthias** [comment]
@junneyang the request is put into a working queue. If there is no result in the configured timeout (default 10 secs) the request is answered with a timeout exception. But since the item is placed in the queue it will be processed. You can configure the timeout.

The question is: what happens in your system, so that you don't get an answer in time?

**Comment by junneyang** [comment]
it seems that the leader selection is in progress, i'm not sure. 
I didn't save the log

how to configure the timeout ?
thanks !

**Comment by aquamatthias** [comment]
The relevant timeout here is `--zk_timeout`

**Comment by junneyang** [comment]
is this the marathon's startup params or zookeepr's ?
thanks!

**Comment by aquamatthias** [comment]
This the timeout for all zk operations and is used in the REST layer as well.

**Comment by kolloch** [comment]
You can check what the command line flags do and what command line flags are available by looking at the documentation: https://mesosphere.github.io/marathon/docs/command-line-flags.html

It is a Marathon startup flag.

Please consider contributing the symptom and the solution to our documentation, e.g. the https://mesosphere.github.io/marathon/docs/common-problems.html sections.

https://mesosphere.github.io/marathon/docs/contributing.html

**Comment by junneyang** [comment]
OK, very thanks !
