### ISSUE TITLE
Remove dubious functionality to remove orphaned tasks from TaskTracker storage

### ISSUE THREAD

**Issue by meichstedt** [mesosphere/marathon#2620]
`TaskTracker.expungeOrphanedTasks` removes tasks from (ZK-) storage if they are not present in memory. It is called once after startup – hopefully after reconciliation has finished, but this is only controlled via a delay.

If `TaskTracker.expungeOrphanedTasks` id called before all apps are loaded/reconciled (e.g. when reconciliation takes longer than expected), non-orphaned tasks will be removed from storage by mistake.

@kolloch and I cannot think of a use case where this method makes things better, so we propose to remove it.

**Comment by kolloch** [comment]
@aquamatthias We would love to get your opinion on this.

See https://github.com/mesosphere/marathon/blob/7faf5af2697dbb1a43951e377b905617f22f3094/src/main/scala/mesosphere/marathon/tasks/TaskTracker.scala#L176-L188 and https://github.com/mesosphere/marathon/blob/7faf5af2697dbb1a43951e377b905617f22f3094/src/main/scala/mesosphere/marathon/MarathonSchedulerService.scala#L396-L422

**Comment by aquamatthias** [comment]
The expunge orphaned task logic should be the last part of the reconciliation attempt.

**Comment by kolloch** [comment]
Note that currently it is not executed for every reconciliation but only after the first one.

But even so, why? Why is that code necessary? In which cases does it help? I can definitely think of cases where it causes trouble.
