### ISSUE TITLE
v0.13.0-RC3 docker hub build has failed

### ISSUE THREAD

**Issue by clehene** [mesosphere/marathon#2622]
https://hub.docker.com/r/mesosphere/marathon/builds/bscozmieto4kbscbxh9ruwt/

**Comment by kolloch** [comment]
Thanks for reporting this!

I retriggered the build, hopefully it is available soon.

**Comment by aquamatthias** [comment]
Looks like a problem of docker hub: the tag is not listed here:
https://hub.docker.com/r/mesosphere/marathon/tags/
but it is available. I can pull and run  mesosphere/marathon:v0.13.0-RC3.

**Comment by clehene** [comment]
@kolloch thank you! 
@aquamatthias it only became available after the last build(s). 

The last build still shows a failure, however it seems that it got past the actual docker build.

The hub build infrastructure seems rather flaky. I'll check if there's any way to raise an issue.

**Comment by clehene** [comment]
https://github.com/docker/hub-feedback/issues/459
