### ISSUE TITLE
Add Retina Resolution (2x) Support for Deploying Icon

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2628]
JIRA Key: MARATHON-467
Reporter: John Ashenden
Priority: Medium

Description:
[~marcus] wasn't sure who to file this against.

See screenshot: http://cl.ly/image/1n1E1t2j1i1D

[~chad] [~lee] we'll likely need to supply an additional asset at 2x resolution for the team.

**Comment by orlandohohmeier** [comment]
It would be nice, if we somehow could use an SVG instead of two PNGs for this.

**Comment by leemunroe** [comment]
+1

Will provide SVGs. @orlandohohmeier Worth changing all the status icons in the same effort?

**Comment by orlandohohmeier** [comment]
@leemunroe I thinks, we already have SVGs for most of the icons... Some of them, just need some minor adjustments (e.g. color) and we need to integrate them.

**Comment by kpacha** [comment]
-1

I'd rather focus on important features, like #2430 & #2063

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2690. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
