### ISSUE TITLE
UI does not update/show the status correctly

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#2634]
I created one application with 1000 tasks.
After a couple of minutes I wondered why this app is still in Deployment.
After browser refresh the app shows as running.
I go to the application  and klick suspend.
All tasks are killed.
I klick on applications -> there is my application with 1000 tasks running, which is not true.
![screenshot_01](https://cloud.githubusercontent.com/assets/330485/11150538/c770c2ac-8a28-11e5-88a3-f138e2d33384.png)

After browser refresh the status is displayed correctly.

**Comment by orlandohohmeier** [comment]
Duplicate of mesosphere/marathon#2568

**Comment by aquamatthias** [comment]
Retested on OVH. This bug is still existent.
