### ISSUE TITLE
New constraint type: unique-best-effort

### ISSUE THREAD

**Issue by SEJeff** [mesosphere/marathon#2637]
The use case was something a user recently brought to me:

Given a cluster of 25 mesos agents, the user wants to run 30 instances of the given application. This new constraint would start the first 25 tasks 1 on each slave, and then put the remaining 5 on whatever agents send offers.

Some applications work best when on different hardware, but don't necessarily require it. This is one of those case.

This issue is really just to discuss if adding something akin to this would make sense for marathon.

**Comment by meichstedt** [comment]
@SEJeff thanks for bringing this up. Can you please flesh out the benefit of this approach in contrast to distributing tasks evenly via the `GROUP_BY` constraint?

Distributing evenly would mean that all agents are running either 1 or 2 instances of that app. Your described approach could lead to one agent running 6 of those instances, while all others are running 1. In another scenario with 10 agents and 100 instances, you might end up with 91 instances on one agent – whoah. So what is best effort?

From my point of view, it looks like I'd either have a `unique` constraint or an even distribution. Does that make sense?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4480. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
