### ISSUE TITLE
how to make app to monopolize one slave node ?

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#2638]
other apps cannot starts on it
thanks !

**Comment by junneyang** [comment]
how to achieve this goal?
thanks !

**Comment by hotstepper13** [comment]
Maybe you would like to have a look a look at "roles" or "labels". 

From the Marathon API:
    "acceptedResourceRoles": [ /* since 0.9.0 */
        "role1", "*"
    ],
    "labels": {
        "environment": "staging"
    },

Just define labels to "normal" nodes and another one to the "special" node. Now you can choose in your marathin files what schould be executed where.

**Comment by kolloch** [comment]
Hi @junneyang, you can look at the referenced PR for more info. Feel free to make constructive comments in the PR.

**Comment by kolloch** [comment]
@hotstepper13, thanks for chiming in! Of course, I would really value your comments on the PR as well.
