### ISSUE TITLE
could one marathon instance management multiple mesos frameworks ?

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#2639]
very thanks !

**Comment by wendigo** [comment]
I think it's not possible but multiple instances of marathon can be run on top of single mesos cluster

**Comment by rasputnik** [comment]
Yes, that should work. run each on its own port and give it its own zookeeper path. and you can optionally tag some slaves with a role if you need them to place their tasks in a more specific place.

**Comment by kolloch** [comment]
@wendigo and @rasputnik are right. Thanks!
