### ISSUE TITLE
Docs: Enhance artifact store documentation

### ISSUE THREAD

**Issue by jolexa** [mesosphere/marathon#2640]
Hello,

This is a suggestion. Personally, I find the artifact_store documentation very unclear.

When reading about the artifact store, I see that "marathon supports many backends" and that I should reference the command line options to specify a store backend.
https://mesosphere.github.io/marathon/docs/artifact-store.html 

Then, on the command line options, when trying to see what backends are available, I am given two examples, hdfs & file and then told to reference the above page for more information. https://mesosphere.github.io/marathon/docs/command-line-flags.html

This is recursive and not really providing me any material value into the usage of the artifact store, as a non-artifact store. Because the documentation is not clear, I quickly scrap the idea and invent my own artifact store.

My open questions include but not limited to:
- What backends does marathon support?
- How does the implementation look? diagram?
- Must all the mesos-slave nodes have access to the backend as well?
- Which process needs write access vs only read?

**Comment by kolloch** [comment]
Thanks for your suggestion @jolexa! You are right, we should document that better.

If you happen to experiment with the artifact store, we would be very happy if you reported your findings. We do gladly [accept pull requests for our documentation](https://mesosphere.github.io/marathon/docs/contributing.html).

**Comment by jolexa** [comment]
Happy to submit a PR, there are so many open questions for me that I don't
know where to start experimenting.

**Comment by andygrunwald** [comment]
It seems that at the moment only `file` and `hdfs` backends supported. See https://github.com/mesosphere/marathon/tree/master/src/main/scala/mesosphere/marathon/io/storage
As you can read at https://groups.google.com/forum/#!topic/marathon-framework/7E03WZwtIYg there seems to be work at a S3 Storage backend.

**Comment by blbradley** [comment]
I believe #3270 has mostly solved this issue. Do I have some agreement?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3371. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
