### ISSUE TITLE
Consolidate Actions Menu in App Details View

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2646]
**Scenario 1: Show buttons in a new structure**
Given a created app
When the user opens the app details view
Then three buttons are shown:
* Scale Application
* Restart
* **Reset Delay [only shown if app is in state Delayed]**
* Options (icon-mini-gear.svg)

**Scenario 2: Show drop down of options button**
Given a user opened the app details view
When the user clicks on the options button
Then a drop down is shown, offering 
* Suspend Application
* Destroy Application
* ~~Reset Delay [only shown if app is in state Delayed]~~

*NOTE:* Behavior and functionality of the buttons stays the same

**UPDATE**: updated ACs to reflect design input 

---
https://projects.invisionapp.com/share/9U3ZMXKD5#/screens/101208599

**Comment by mwasn** [comment]
@leemunroe We have another functionality if an app is delayed. If we hide this button under the gear symbol, the user doesn´t know that this option is available. What do you think?

**Comment by aldipower** [comment]
![resetdelay](https://cloud.githubusercontent.com/assets/859154/11213253/3e20a4c0-8d3b-11e5-8586-ed9edc0abbc0.png)

**Comment by leemunroe** [comment]
Good catch. Makes sense to keep this button outside of the gear dropdown so it's obvious.
