### ISSUE TITLE
Improve sidebar app status count and UX

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#2650]
As described by @aquamatthias in #2523, a user should instantly see if there are any problems with any app (unhealthy, failing tasks, deployments, apps waiting for offer, delayed apps). 
Currently this information is surfaced with a "worst case" status for groups (implemented in 
mesosphere/marathon-ui#355). This issue is meant to discuss ways to improve on this solution.

**Latest WIP design by @leemunroe**

![image](https://cloud.githubusercontent.com/assets/15963/11200276/9d97d714-8c89-11e5-9176-1f1a3dadf57b.png)

- [x] Continue to show worst case for groups (good visual indicator)
- [ ] Show the counts in the filter sidebar using slightly modified design
- [ ] Make the clickable area for filters the full width of the sidebar (including count)
- [x] Hypothesis being that by providing the filter counts users can easily get to the apps with problems.

**Comment by orlandohohmeier** [comment]
Related to #2663 and #2664

**Comment by leemunroe** [comment]
Working prototype available [here](https://mesosphere.invisionapp.com/share/ZH4YIA6G6#/screens/115985570).

Notice the clickable area is full width of sidebar and has a hover effect.

![count](https://cloud.githubusercontent.com/assets/15963/11220098/fe186854-8d12-11e5-8e21-cce8835eed79.gif)

**Comment by pierlo-upitup** [comment]
I love the counter "pills", makes 100000% sense.

**Comment by aldipower** [comment]
Looks great.
