### ISSUE TITLE
Improve ui scale error messages

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#2651]
![scale-error-message](https://cloud.githubusercontent.com/assets/647035/11209509/bb86a686-8d21-11e5-98a2-b07920571d46.png)

We should improve the error message writing, as it is not clear what exactly is the issue. This error is displayed when an app is locked by a deployment.

**Error message:**
*Failed to scale ${appId}. If you want to stop any current deployment of the app and force a new one to scale it, press the OK button.*

**Comment by kolloch** [comment]
Maybe: There is a deployment in progress that changes ${appId}. If you want to stop this deployment...
