### ISSUE TITLE
Improve ui kill and scale error messages

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#2652]
![screen shot 2015-11-17 at 12 02 02](https://cloud.githubusercontent.com/assets/647035/11209694/14e927d4-8d23-11e5-9634-683f02dbec2a.png)

We should improve the error message writing, as it is not clear what exactly is the issue. This error message (introduced in mesosphere/marathon-ui#396) is displayed when one tries to kill a task and scale an app which is locked by a deployment.

**Error message:**
*Failed to kill task and scale ${appId}. If you want to stop any current deployment of the app and force a new one to kill the task and scale it, press the OK button*

**Comment by leemunroe** [comment]
@orlandohohmeier Great, looking at improving Marathon alerts and feedback overall in general.

For this particular example, what copy would you recommend?

**Comment by leemunroe** [comment]
@orlandohohmeier I could do with your help on the wording. We're looking at introducing a "title" to dialogs. With that in mind, it might read something like this:


Title: "Warning: ${appId} Is Currently Deploying"

Description: "To scale to ${requestedInstances} instances, the current deployment will have to be stopped, and a new task started."

Actions: "Stop Current Deployment And Scale", "Cancel"

**Comment by orlandohohmeier** [comment]
@leemunroe Sorry, I've missed your earlier comment. I really like the introduction of a title. It is a huge improvement! Regarding the message, I think we should make crystal clear that forcefully stopping a deployment is dangerous and could screw things up. Besides this, I'm not sure if we know the number of requested instances within the modal component... What do you think about the following: 

Title: "Warning: ${appId} Is Currently Deploying"

Description: "In order to kill the tasks and scale to  ${requestedInstances || "a new number of"} instances, the current deployment will have to be **forcefully** stopped, and a new one started. Please be cautious, as this could result in unwanted states."

Actions: "Stop Current Deployment And Scale", "Cancel" (preselected)

/cc @aquamatthias

**Comment by orlandohohmeier** [comment]
Please see https://github.com/mesosphere/marathon/issues/2831#issuecomment-169384707 for a full list of dialog messages.
