### ISSUE TITLE
Never preselect dangerous actions in modal dialogs

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#2655]
![screen shot 2015-11-17 at 11 52 28](https://cloud.githubusercontent.com/assets/647035/11209856/380a66d2-8d24-11e5-8a82-8ea1cb5f6979.png)

Using the force option could produce very weird and unwanted results. Therefor the option to forcefully stop a running deployment should never be easy reachable and preselected in the ui. We may should also adjust the button labels, making really clear what will happen (e.g. "Stop running deployment and apply X"). What do you thinks?

/cc @aquamatthias @leemunroe

**Comment by aldipower** [comment]
Good points! :)
FYI:
In the Edit application dialog we change the button title to ```Change and deploy configuration forcefully```, if this is the case.

**Comment by leemunroe** [comment]
+1 for button labels. 

Related #2511

**Comment by pierlo-upitup** [comment]
Let's generalise this issue to take care of ALL possible dialogs whose default actions might cause dangerous side effects. 

Clearer button labels have been introduced in https://github.com/mesosphere/marathon/issues/2832, this issue is about making the more "risky" actions not selected by default.

**Comment by orlandohohmeier** [comment]
We could use the dialog state introduced in #2831 to adjust the default selection for all dangerous actions.

**Comment by pierlo-upitup** [comment]
Yeah I guess we could assume that if state == Danger, always preselect Cancel – right?

**Comment by orlandohohmeier** [comment]
Yep.

**Comment by pierlo-upitup** [comment]
This depends on https://github.com/mesosphere/marathon-ui/pull/521
