### ISSUE TITLE
Animate deploying icon UI

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2656]
Animate deploying icon in
- App Collection View
- App Details View

The deploying icon looks like it should be animated, but is currently static. This makes the user question if anything is actually happening, or if the deployment has stalled.
Issue was raised during a usability test.

```
// Suggested animation/speed
animation: spin 1s linear infinite;
```

**Comment by orlandohohmeier** [comment]
Please consider the objections in mesosphere/marathon-ui#389

**Comment by kolloch** [comment]
An alternative would be to use symbols that do not suggest that they should be animated.

**Comment by orlandohohmeier** [comment]
@leemunroe Could you please revisit this, as there might be a little too much going with all the animations...

**Comment by leemunroe** [comment]
I'm wondering if the health bar is useful in this view. As far as I can tell we have two different "components" visualizing the same information here.

1. The health bar
2. The explicit "Healthy" "Unhealthy" "Unknown" stats

![image](https://cloud.githubusercontent.com/assets/15963/11250836/4e37cf0c-8de3-11e5-9f53-53f48bd61c83.png)

If we removed the bar does that make it any less useful? Examples:

![image](https://cloud.githubusercontent.com/assets/15963/11250880/88cb67d2-8de3-11e5-9c1a-bd89a01b5d4b.png)

![image](https://cloud.githubusercontent.com/assets/15963/11250960/d842aea6-8de3-11e5-98d4-358dc2e7d3de.png)

**Comment by orlandohohmeier** [comment]
@aquamatthias @kolloch @aldipower What do you guys think?

**Comment by kolloch** [comment]
I think that the individual statistics (* 2 Healthy (100%)...) act as some kind of legend. In a way they do explain the health bar only view that people encounter on the index page.

So subjectively I like it as is but I am not strongly opposed to remove it.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3195. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
