### ISSUE TITLE
Global Search Result Set in App Collection View

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2661]
* Search is always a new global search
* Show applications only (no groups)

---
https://mesosphere.invisionapp.com/share/BF4VSTXA5#/screens/114542459

**Comment by orlandohohmeier** [comment]
Remove from ready as we need a final call on this. 
https://github.com/mesosphere/marathon-ui/pull/403#issuecomment-157778534

/cc @mwasn @leemunroe
