### ISSUE TITLE
Change Header When Applying Filter in App Collection View 

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2662]
* Title changes to 'Search results for "$query" (Clear search)'
* "Clear search" resets the view to all applications at root level and clears all filters
* BUT title should remain as breadcrumbs to reflect current group if only filters were applied

![image](https://cloud.githubusercontent.com/assets/12829900/11214202/31dd20da-8d40-11e5-8676-27b40e59b1f4.png)

---
https://mesosphere.invisionapp.com/share/BF4VSTXA5#/screens/114542459

**Comment by pierlo-upitup** [comment]
@leemunroe are we sure about the "Clear search" link style being dark grey with underline? We usually have only white and no underline. Could you take a look at the gif here and let me know if you're OK with the default link style: https://github.com/mesosphere/marathon-ui/pull/407 ?

**Comment by leemunroe** [comment]
@pierlo-upitup Good call. Definitely lets strive for consistency when we can. I think your stretched gif looks fine :stuck_out_tongue:
