### ISSUE TITLE
how to monitor app's(including shell and docker) cpu,mem,network,disk info ?

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#2667]
thanks !

**Comment by kolloch** [comment]
Hi @junneyang, there are very many ways but it's outside the scope of our work and the Marathon issue tracker right now. That also depends on your current monitoring setup. Prometheus has some custom Marathon integration.

If you have done your research and have some Marathon-specific pointers for this topic, we would appreciate your contribution to our docs.

https://mesosphere.github.io/marathon/docs/contributing.html
