### ISSUE TITLE
Data on what features Marathon customers actually use

### ISSUE THREAD

**Issue by air** [mesosphere/marathon#2672]
Problem: We don't have data on which Marathon features are popular and which are underused. This data would help us focus time on what's actually valuable to customers.

Is there a way we can add data collection to Marathon in a way that meets everyone's needs, first and foremost being the user and their right to not participate?

Initial thoughts
- No data collected by default. Must be opt-in.
- Can we encapsulate the data gathering functionality in a plugin that's not shipped by default?
- What data should we capture? e.g. All API calls.
- How should data be anonymized? e.g. Stripping out all values from JSON.
- How can we be completely transparent about what's being done? e.g. Publishing data.
- How would data be submitted back to us?

I'd love to hear from users on how we can get this right.

**Comment by kolloch** [comment]
We should never really capture any API payload, only features used or similar.

**Comment by air** [comment]
> API payload

Example problem: On app create, how do we capture how *constraints* are used? It's only expressed in the payload.

Ideas:
- Just capture the fact that `constraints` was used in the request. Minimal data. e.g `constraints_were_used=yes`
- Just extract the operators that were used in `constraints`. e.g. `constraint_operators_used=UNIQUE`

**Comment by jsancio** [comment]
From Marathon's point of view we should implement metrics to expose this information anonymously. You can leave it to DCOS, private deployment, etc to figure out what they want to do with this data. For example:
- Some users may want to summarize this data internally for themselves
- Some users may want to share that data with the support provider
- Some users may want to share that data in the public domain.

**Comment by leemunroe** [comment]
+1

Some things I'd like to know to help us improve design and UX:

* How many applications do users have? 
* How many apps have health checks, labels, are docker etc.?
* What percentage of users use feature X? 
* How are they using feature X?
* What are common errors, alerts, validation messages surfaced?

Related:

* Ability to communicate with users (e.g. via Intercom)
* Some way to gather feature requests / feedback from the UI (e.g. via Uservoice)

I'm a fan of Segment and how we have it set up with DCOS.

**Comment by kolloch** [comment]
hey @leemunroe, thanks for your suggestions but I think it is better to separate the "related" things into different issues.

**Comment by leemunroe** [comment]
Some ideas that were mentioned in the product workshop recently:

* Use the mailing list to get some data via surveys (not perfect, but better than nothing)
* Ensure the data collected is anonymous and show the data that is captured
* Provide a good incentive e.g. for those that opt-in enable them to benchmark against others
* Have a SaaS component that adds some sort of data capture e.g. Support

**Comment by air** [comment]
Fun fact: Open source Jenkins will phone home **by default**, sending anonymized data. You can turn it off in settings.

**Comment by air** [comment]
What are existing statistics: Is there anything we want to report from the `/metrics` endpoint?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4200. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
