### ISSUE TITLE
Look at default link styling

### ISSUE THREAD

**Issue by leemunroe** [mesosphere/marathon#2675]
Currently links are not obvious.

e.g. which of these is clickable?
![image](https://cloud.githubusercontent.com/assets/15963/11259864/5ec97a50-8e1a-11e5-9e8f-767d4723c859.png)

Related #2662

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2705. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
