### ISSUE TITLE
Create button doesn´t work with IE

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2676]
> Anthony Howeanhowe
> Hi Everyone, under Internet Explorer, in Marathon UI, when you go to create a new , it looks like the  "+Create" button doesn't click

**Comment by philipnrmn** [comment]
I've just done some testing and it doesn't look like it's a 0.13 problem in any recent IE version. I would guess 0.11 or earlier.

**Comment by philipnrmn** [comment]
Confirmed, Marathon UI version is 0.11.2. It occurs in IE11 on Windows Server 2012.

**Comment by philipnrmn** [comment]
To reproduce:

* open developer tools in Internet Explorer
* click the `+ New App` button
* enter a valid ID and cmd in the app modal
* click the `+ Create` button

Note that the app is not created, and an error appears in the console.
