### ISSUE TITLE
Ability to specify the value of the hostname an app task is running on.

### ISSUE THREAD

**Issue by bradleyreeves** [mesosphere/marathon#2679]
Perhaps I am mistaken, but it seems there is currently no way to dynamically reference the hostname of a task and use it as an env variable value. I'm sure the use cases for this are obvious and many.

Edit:
To be specific: currently, the json usage 
"env": {
    "CASSANDRA_BROADCAST_ADDRESS":"$HOSTNAME"
  }
will set CASSANDRA_BROADCAST_ADDRESS to the value "$HOSTNAME", instead of trying to resolve it to a valid hostname based on the machine the task is then run on.
/Edit

This is exceptionally useful when working with docker apps that will use the conatiner's hostname as a default for some env variable, and it needs to be overridden to the actual machine's hostname.

A good example: https://hub.docker.com/_/cassandra/
Edit:
Using the value "CASSANDRA_BROADCAST_ADDRESS":"auto" would set the value to the container hostname, instead of the machine hostname.

**Comment by jeromegn** [comment]
+1

We also need a similar feature for logging purposes, we would need to be able to set parameters on our docker containers like: `{ "key": "log-opt", "value": "tag=$MESOS_TASK_ID" }`. That's for syslog, it's much easier to find logs for specific containers that way.

**Comment by kolloch** [comment]
Have a look at the wild discussions here: https://github.com/mesosphere/marathon/issues/1828

@jeromegn: It probably makes sense to use separate issues for substituting variables (which have to be known to Marathon BEFORE the task launch) in the env variables and in other places.

I can completely understand the usefulness of this. It is hard to do right and might not be worked on soon by us. In the meantime, you can work around most of these issues by creating your own docker images which set the desired environment variables before starting the main process.

**Comment by jeromegn** [comment]
Thanks @kolloch.

It so happens that you can specify *some* variables to be interpolated in the parameters (like the short container ID via "your-app/{{.ID}}".) For now that satisfies our needs.

**Comment by cookandy** [comment]
+1 

A valid use case would be setting the hostname of a container to the hostname of the machine it is started on.  For example:

```json
 "parameters": [
                { "key": "hostname", "value": "$HOSTNAME" }
            ]
```

**Comment by adkhare** [comment]
Do we have any plans on this issue?

**Comment by alaa** [comment]
+1

**Comment by MattFriedman** [comment]
+1

**Comment by erSitzt** [comment]
+1

**Comment by nicbet** [comment]
+1

Having the docker host, that a container was placed on by Marathon, available in an ENV variable to the container would significantly simplify some of our routing and service discovery mechanisms, without the need to build custom base images with customized logic for discovering that very information before the main application in the container executes.

**Comment by jrrickard** [comment]
+1

**Comment by endzyme** [comment]
+1

**Comment by elan100cs** [comment]
+1

**Comment by sdouglasnelson** [comment]
+1

**Comment by JianTangAxa** [comment]
+1

**Comment by raghu999** [comment]
If you are using Docker, This should be very easy if you do a `docker inspect` on any running container you will see that docker  docker dynamically assigns  ENV `HOST`. So for example if you add an in your json that should work 
```
"env": {
"CASSANDRA_BROADCAST_ADDRESS":"HOST"
}
```

**Comment by raghu999** [comment]
+1

**Comment by arnoldcano** [comment]
+1

**Comment by RavAngell** [comment]
+1

**Comment by mpenate** [comment]
+1

**Comment by willyhoang** [comment]
+1

**Comment by jdef** [comment]
@jasongilanfarr indirectly related to template discussion

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4203. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
