### ISSUE TITLE
Mesos details link broken due to extra /

### ISSUE THREAD

**Issue by schneidexe** [mesosphere/marathon#2682]
In the task details in marathon UI there is a link to the mesos details which takes you to the executor details in the mesos UI in a new tab/window (see https://github.com/mesosphere/marathon-ui/pull/114). This link contains one extra leading ```/``` in the context path of the URL which opens an "empty" executor page (actually no task information) in mesos UI and also triggers mesos UI's reconnect popup. Once you remove the extra ```/``` in the browser's address it shows the information just fine.

The extra ```/``` should be removed.

It actually an issue for [marathon-ui](https://github.com/mesosphere/marathon-ui) but seems issues cannot be reported there.

**Comment by tobilg** [comment]
When trying Marathon 0.13.0-RC4, Mesos Detail Links are not even showing in my case (Mesos 0.25.0):

Marathon [screenshot](http://imgur.com/k6yhsBN)

**Comment by pierlo-upitup** [comment]
@schneidexe thanks for reporting this. Which version of Marathon are you running? This should was fixed by https://github.com/mesosphere/marathon-ui/pull/216. 

@tobilg that seems like a separate issue. Could you provide more info?

**PS** Isses for https://github.com/mesosphere/marathon-ui rightfully belong here, with a `gui` label. I guess we need to make it more clear in our README ;-)

**Comment by tobilg** [comment]
@pierlo-upitup I will gladly provide more info. Can you specify what you need? You can have a look at my other issue I reported https://github.com/mesosphere/marathon/issues/2683 which contains more screenshots.

**Comment by aldipower** [comment]
This was fixed in 0.12.0 .

https://github.com/mesosphere/marathon/issues/2266

Mesos changed the link behavior in 0.23.0, so older Marathon UI versions (< 0.12.0) are broken with newer Mesos versions ( > 0.22.0 ).

**Comment by pierlo-upitup** [comment]
@tobilg thanks for the heads up. 

I'd like to know under which circumstances the "No link available" shows up. Can you post a screenshot of the "About" modal dialog (link is at the top-right of Marathon UI)? Can you reach mesos' web UI normally?

**Comment by schneidexe** [comment]
@pierlo-upitup still using 0.11.x, was searching for older issues but not in PRs. Thanks!

**Comment by tobilg** [comment]
@aldipower As I wrote, I use Mesos 0.25.0 with Marathon 0.13.0-RC4. In 0.13.0-RC1 this works for me without issue. So I guess this might be another issue of 0.13.0-RC4.

@pierlo-upitup I uploaded another [screenshot](http://imgur.com/EYPXH7I)

**Comment by aldipower** [comment]
@tobilg Yes, sorry, I actually meant the actual issue described by @scheidexe . Yours is another issue actually, but maybe related.

**Comment by pierlo-upitup** [comment]
@tobilg I see a "Mesos Leader UI url" unspecified in the screenshot. Seems like your Mesos configuration is not exposing that value to Marathon?

**Comment by pierlo-upitup** [comment]
I think this might be related: https://mesosphere.github.io/marathon/docs/command-line-flags.html#optional-flags

**Comment by tobilg** [comment]
@pierlo-upitup I never configured the WebUI URL manually before, even in 0.13.0-RC1. I'd rather guess that Marathon should be able to extract this from the Zookeeper connection string (respectively by retrieving the Master info from Zookeeper by the URL specified). 

The Mesos Master `state.json` URIs should be clear if Marathon knows which is the leading Master IMHO, or do I have a misunderstanding?

**Comment by pierlo-upitup** [comment]
Closing this issue and moved your request to https://github.com/mesosphere/marathon/issues/2694 @tobilg.
