### ISSUE TITLE
Running instances are confusing

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#2684]
Marathon 0.13.0-RC4. When zooming into group, some sub-groups have weird running instance bars. They recover back to normal after a few seconds, looks like it is correlated with UI state update

![image](https://cloud.githubusercontent.com/assets/89186/11298344/1f8ee46c-8f76-11e5-859b-6192541b6fd8.png)

Can't see how with 1/1 tasks you can have healthy, running and unscheduled on the same bar :)

This is how our root group looks like:

![image](https://cloud.githubusercontent.com/assets/89186/11298389/80804b62-8f76-11e5-9e05-00947ba41854.png)

This is how it looks one level in:

![image](https://cloud.githubusercontent.com/assets/89186/11298397/90ffc954-8f76-11e5-97c4-0140ad3c7361.png)

There should be no "unscheduled" on the root level.

**Comment by pierlo-upitup** [comment]
cc @leemunroe

**Comment by orlandohohmeier** [comment]
@bobrik Thanks for your input. I also feel that the running instances / health bar display is kinda confusing on the group level, as the health bar includes suspended apps but the running instance count did not (ok, it does but it's 0 of 0 added to the accumulated values). 

![confusing-instance-count](https://cloud.githubusercontent.com/assets/647035/11339158/774d3a76-91f8-11e5-9b15-daea535942db.gif)

@leemunroe Could you please have a look into this, and work on a less confusion display? Maybe a separate column, like in 0.11, could help?   

![health-bar-0.11](https://cloud.githubusercontent.com/assets/647035/11338824/a8bf9d62-91f6-11e5-8b1d-deacfdb6c4d3.png)

I've opened another issue  ( #2699 ) regarding the update/render issue you mentioned.

**Comment by leemunroe** [comment]
Is it useful to show unscheduled in the group level? @bobrik's suggestion to remove it makes sense to me.

**Comment by lloesche** [comment]
As a user I don't see why suspended apps should be visualised in the health bar.

**Comment by meichstedt** [comment]
Also makes sense to me. Apps with instances == 0 should not be taken into account.

**Comment by gkleiman** [comment]
+1 for removing unscheduled apps from the health bar.

**Comment by orlandohohmeier** [comment]
Ok, let's remove them from the health bar.
