### ISSUE TITLE
Authorisation of kill and scale endpoint

### ISSUE THREAD

**Issue by janisz** [mesosphere/marathon#2685]
When user perform kill and scale request it require only `KillTask` permission while scaling require `UpdateAppOrGroup`. It should check if user has ppermission to `KillTask` and `UpdateAppOrGroup` to perform kill and scale.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3540. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
