### ISSUE TITLE
Failover during update scales below minimum health capacity

### ISSUE THREAD

**Issue by pgkelley4** [mesosphere/marathon#2688]
While working on https://github.com/mesosphere/marathon/issues/2249 I noticed that TaskReplaceActor may not be setup to handle Marathon failovers.

I put together a quick test to verify this. I started an update on a 2 instance app, then restarted the master. The new master picked up the deployment plan just fine, but it would kill too many tasks and fall below the minimum health capacity (Not every time).

I believe this is because the TaskReplaceActor.preStart method assumes it will be run once at the beginning of an update and then:
- tasksToKill doesn't take into account that some may be the new version and might not be healthy (often the case in an update). Because of this nrToKillImmediately is wrong and will kill tasks right away.
- reconcileNewTasks doesn't know that tasks were previously started.
- the backoff delay is reset every time.

This can be fixed by changing the preStart method to assume things could have already been started. I will put up a PR soon with some unit tests to illustrate the problem and propose a solution.

**Comment by kolloch** [comment]
@pgkelley4 Thanks for the excellent research!

**Comment by pgkelley4** [comment]
Just wanted to add here that when this does become a priority, my PR https://github.com/mesosphere/marathon/pull/2689 has unit tests demonstrating the issue.

**Comment by aquamatthias** [comment]
@pgkelley4 Marathon 1.4.0 will pickup and reconcile running deployments, the same way as you suggested.
