### ISSUE TITLE
Filters don't updated correctly on reload

### ISSUE THREAD

**Issue by aldipower** [mesosphere/marathon#2691]
The application list filters don't update correctly on reload or URL change as mentioned here https://github.com/mesosphere/marathon-ui/pull/411#issuecomment-158522289 by @leemunroe  .

"
2. Back button loses state

Expected behavior: Clicking the browsers back button should take me back to the results I was just looking at.

To reproduce: Conduct a new search, then apply a status filter, click through to app details, then click browser back button.
"

![back](https://cloud.githubusercontent.com/assets/15963/11311712/56b72e62-8f86-11e5-9560-0f5e1f60c0ff.gif)

**Comment by pierlo-upitup** [comment]
Fixed by https://github.com/mesosphere/marathon-ui/pull/424
