### ISSUE TITLE
Document the most important metrics

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#2692]
Recently, someone ask on the mailing list whether we have documentation on which metrics we do expose.

Documenting all metrics in a generally understandable way is probably a lot of work. But we should identify a subset of metrics that is important to most of our customers. I guess our guideline should be which metrics can quantify "Marathon health" and be used to make operations aware of likely problems, e.g. very slow responses.

We appreciate community feedback on what kind of metrics are most important.

**Comment by ruivapps** [comment]
That would be great! Thanks you!
