### ISSUE TITLE
Preserve unknown config options when editing app

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#2693]
In #2674 a user raised concerns that a particular configuration option was rest when he used the UI to edit the application config. The UI didn't provide support for the particular option and thus didn't seem to preserve the previous value.

In general, the UI should preserve all configuration that the user did not explicitly change.

**Comment by aldipower** [comment]
In general the UI preserves unknown config parameters.
This problem described with ```forcePullImage``` is related to the nested container object and is definitely a specific bug.

**Comment by mwasn** [comment]
@aldipower Do we have tests in place ensuring that we don´t have regressions like #2674? If not I would suppose to add some with this issue.

**Comment by aldipower** [comment]
@mwasn No, we haven't for this specific case. I also think that we should add tests for that.

**Comment by aldipower** [comment]
I have tested this again and cannot reproduce anymore.
I think it is fixed alongside with https://github.com/mesosphere/marathon/issues/2812
