### ISSUE TITLE
Marathon does not expose Mesos leader webui URL

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2694]
As originally reported by @tobilg in https://github.com/mesosphere/marathon/issues/2682#issuecomment-158356167 
and in particular in https://github.com/mesosphere/marathon/issues/2682#issuecomment-158905946 :

> I never configured the WebUI URL manually before, even in 0.13.0-RC1. I'd rather guess that Marathon should be able to extract this from the Zookeeper connection string (respectively by retrieving the Master info from Zookeeper by the URL specified). The only thing I changed when going from RC1 to RC4 was changing the Docker image tag for the systemd service definition.

> The Mesos Master state.json URIs should be clear if Marathon knows which is the leading Master IMHO, or do I have a misunderstanding?

cc @gkleiman

**Comment by aquamatthias** [comment]
@pierlo-upitup @tobilg The web UI URL is extracted from the Mesos Master information.
It _can_ be configured from the command line, if Marathon and Mesos is not in the same network and there is a network rule to reach the mesos master.
