### ISSUE TITLE
Document scale test findings / Marathon limits

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2697]

**Comment by aquamatthias** [comment]
@mwasn I think the scale test results document hopefully pretty well the limits of Marathon. Is there anything else left, that has not been addressed?

**Comment by mwasn** [comment]
No, I think we´re done for now.

**Comment by aquamatthias** [comment]
See: https://docs.google.com/spreadsheets/d/1Ln23csJxVgor7JIrY3cozftEsy6-Q1_qqKOg3NZkhmY

**Comment by sunshinezeng** [comment]
Hi, I'm wondering whether you have similar test conducted for 0.15 release?
