### ISSUE TITLE
App list / health bar update/render issue

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#2699]
![health-bar-update-issue](https://cloud.githubusercontent.com/assets/647035/11338163/bf8c139e-91f2-11e5-88d6-c23d22e6de6c.gif)
The app list health bar isn't update/render properly. It displays the group health information until the next apps data update. May be a health bar `shouldComponentUpdate` or app lit `key` issue.

**Comment by pierlo-upitup** [comment]
I think it might be we only check the `health` but not the `state` of the app in the `shouldComponentUpdate` call.

**Comment by orlandohohmeier** [comment]
@pierlo-upitup It's neither a `shouldComponentUpdate` nor a app list `key` issue. The data was corrupted due to some object reference issues within the `getGroupHealth` method.
