### ISSUE TITLE
Change format of groupId under app name

### ISSUE THREAD

**Issue by leemunroe** [mesosphere/marathon#2704]
Following on from this discussion https://github.com/mesosphere/marathon-ui/pull/405

After showing new global search to a couple of people, they were slightly confused about the format, and exactly what group the app was in.

<img width="593" alt="screen shot 2015-11-23 at 8 53 39 am" src="https://cloud.githubusercontent.com/assets/15963/11345439/be1f9e26-91cb-11e5-987b-f4b3c4d30f24.png">

As mentioned before just having the slash "/" wasn't that obvious either.

What do you think of this idea? This reflects the format of the title when user browses groups and the title on the application view.

<img width="619" alt="screen shot 2015-11-23 at 10 36 32 am" src="https://cloud.githubusercontent.com/assets/15963/11345780/1a19be80-91ce-11e5-92c4-9ccfeb8ea21b.png">

cc @aldipower @pierlo-upitup @mwasn @orlandohohmeier

**Comment by aldipower** [comment]
This makes perfect sense to me.
It is much more straight forward for the user and eliminates the confusion the appId introduces.

**Comment by pierlo-upitup** [comment]
I like it, but I have to say I'd like to have the full appId at least *somewhere* for the CLI users to copy/paste or general usability. We use the title attribute, but I think that's not enough. Maybe in the detail page?

**Comment by aldipower** [comment]
@pierlo-upitup This is a good point. We should reintroduce it at another place. Detail page could makes sense.

**Comment by orlandohohmeier** [comment]
@pierlo-upitup @aldipower We could implement it in a way (https://jsbin.com/qutoraduxo) that users can actualy copy and paste it.

**Comment by aldipower** [comment]
@orlandohohmeier This is a really nice trick! I am curious, if the user will recognize this?

**Comment by orlandohohmeier** [comment]
@leemunroe Looks really good and I like that it reflects the format of the breadcrumb/title! :+1:  The only thing I personally don't like that much is the "In" part. For me it's harder to read it as there is no clear separation between the redundant proposition and the path. What about using a different color, or starting with a lowercase "i' like Dropbox does?

**Comment by orlandohohmeier** [comment]
@aldipower We should add the path to detail page anyway.

**Comment by leemunroe** [comment]
I like the suggestion of lower case "in" and including the full appId somewhere on the detail page.

**Comment by philipnrmn** [comment]
We could even show the breadcrumb inline with the app name, as in the app detail page:
![inline](https://cloud.githubusercontent.com/assets/2989362/11369453/49133d5a-92bf-11e5-8a54-6e7520335488.png)
