### ISSUE TITLE
Link groupId in search results to individual groups

### ISSUE THREAD

**Issue by leemunroe** [mesosphere/marathon#2705]
As a user if I search for a specific group name there is no convenient way to get to that group from the search results.

Link the individual groups in groupId so I can conveniently get to the group I am looking for.

![frontend](https://cloud.githubusercontent.com/assets/15963/11345927/e2fa4e28-91ce-11e5-8c68-03530c75b41e.gif)

Related #2704

**Comment by pierlo-upitup** [comment]
Blocked by https://github.com/mesosphere/marathon/issues/2704
