### ISSUE TITLE
Need the option not to dynamically create host port for docker port mapping 

### ISSUE THREAD

**Issue by dudi123456** [mesosphere/marathon#2706]
In our cluster, we use flannel+etcd, which enables docker containers on multi host can communicate directly without port mapping. 
In the docker, we can gain this target by not giving the host port when docker run. but  in the marathon, there is no option to do this. Marathon will assign dynamically host port to docker container even we do not give the hostport parameter.

**Comment by philipnrmn** [comment]
Hi @dudi123456, 

It is possible to create an application without a host port. 

Marathon will use the default `ports: [0]` if the `ports` field is unspecified in an application definition. However if you send an empty ports array, as in the definition below, Marathon will not create assign any host port to the docker container. 

```
{
  "id": "no-ports-app",
  "cmd": "sleep 100",
  "ports": []
}
```

I'll submit a PR to improve the documentation on this point.

**Comment by dudi123456** [comment]
Thanks for reply.  But it isn't successfully whenever i add the   "ports": [] to the container part or outside it. I use marathon 0.11.1 and mesos 0.25. Below is the config file:

{
  "container": {
    "type": "DOCKER",
     "volumes": [
      {
        "containerPath": "/dev/random",
        "hostPath": "/dev/urandom",
        "mode": "RO"
      }
    ],
    "docker": {
      "image": "tomcat:8.0",
      "network": "BRIDGE",
      "portMappings": [
         { "containerPort": 8080, "servicePort": 9090,"protocol": "tcp" }
     ]
     }
  },
  "ports": [],
  "id": "tomcat16",
  "instances": 2,
  "cpus": 0.5,
  "mem": 512,
  "uris": []
}

**Comment by philipnrmn** [comment]
Thanks for the clarification. 

Your application definition uses bridged networking and specifies a container port to map, therefore a host port will be mapped to the specified container. You would need to remove the `portMappings` member in order not to map a port. I don't believe it's possible with Docker to open a port on the container without having it mapped to a port on the host. 

The recently announced upcoming [IP per task](https://groups.google.com/forum/#!topic/marathon-framework/rke0Jo2Tkp0) functionality may be of interest to you.

**Comment by philipnrmn** [comment]
After some discussion with @gkleiman I made some clarifications to my response above.
