### ISSUE TITLE
Migrate to React 0.14

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2710]
Let's migrate to the latest React version and keep our codebase maintainable.

**Comment by aldipower** [comment]
In the moment we have a well working UI in terms of the architecture.

Some questions:

Where do you see non-maintainability arising?
Where are the advantages/enablers of the new React version?
Where are the pitfalls?

**Comment by pierlo-upitup** [comment]
Yes, let's approach this pragmatically. Moving to React 0.14 would give us:

- being able to leverage all the latest React Router goodness: dynamic routes, much nicer Route syntax, embedded router properties in components,  and [more](https://github.com/rackt/react-router/blob/master/CHANGES.md#v100) 
- removing `React.findDOMNode()` calls (refs now return the DOM node)
- a really yummy `shallowCompare` addon: https://github.com/facebook/react/pull/3355
- allow us to use the latest `onClickOutsideMixin` [with my PR](https://github.com/Pomax/react-onclickoutside/pull/48) that fixes server-side rendering for components that make use of it 

All in all not that much goodness within React 0.14 per se, and I agree these things shouldn't have the highest priority.

**Comment by pierlo-upitup** [comment]
@aldipower @philipnrmn @orlandohohmeier backlogging this issue for the moment. Correct me as you see fit!

**Comment by orlandohohmeier** [comment]
Ok, but we shouldn't put this on the shelf. I agree that updating to a new react version doesn't have the highest priority and comes with some risk, but it becomes more risky/painful the longer we wait...  
Let's schedule the update for the next few months.

**Comment by pierlo-upitup** [comment]
@orlandohohmeier that's what Backlog is for :wink:

**Comment by orlandohohmeier** [comment]
@pierlo-upitup Yeah, but it feels like some of the issue were sitting in the backlog for quite a while and I think we should revisit this one soon (maybe within the next two release).

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3047. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
