### ISSUE TITLE
Extract LESS into modules

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2711]
The current `main.less` file is quite the mess.

We should refactor, enforcing a more modular approach so that our CSS is easy to maintain and expand.

**Comment by orlandohohmeier** [comment]
A few questions before we start refactoring the `main.less` mess: Do we have a plan for structuring/naming the modules? Do we follow the twitter bootstrap module structure? Should modules reflect rect components?

**Comment by pierlo-upitup** [comment]
Yeah, I guess @aldipower was going to present his approach so we can discuss it together.

**Comment by aldipower** [comment]
@orlandohohmeier 
```We``` or ```me```? ;)

1st question:
I need to understand the complete less-mess. After tah I will develop a structure and present it in a PR as a proposal for review, where you can punch my proposal against the wall.. ;)
2nd question:
Maybe not.
3th question:
No, makes no sense currently.

**Comment by orlandohohmeier** [comment]
@aldipower Don't you think it may makes sense to discuss the general approach before investing time to  refactor the `main.less`? Looking forward to your proposal anyway... :)

**Comment by aldipower** [comment]
Maybe I am as quick in writing code then in writing discussion text. :)

**Comment by pierlo-upitup** [comment]
Let's discuss against a concrete proposal, I like that ;-)

**Comment by orlandohohmeier** [comment]
:smile:

**Comment by aldipower** [comment]
Oh yes. Me too! :smile:

**Comment by leemunroe** [comment]
Nice work! Maybe I'll even start to commit some code now :wink:

**Comment by orlandohohmeier** [comment]
@leemunroe Go ahead...
