### ISSUE TITLE
does the group or app version support self-defined labels?

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#2713]
eg: V1.0.0.0
V1R2C01
...

i think the default version format:
"version": "2015-09-29T15:59:51.164Z"
is not human readable

thanks !

**Comment by philipnrmn** [comment]
You can define any label you like on an app (see below for an example). Groups do not currently support labels. Labels are prominently shown in the latest UI (check out our 0.13 release candidate!). You can define your own label and name it `version` if you like. 

The `version` field is the way Marathon tracks revisions to the app definition, it's not designed to give information on the code running within the application. 

Example labelled app definition:
```
{
  "id": "labelled-app",
  "cmd": "sleep 100",
  "labels": {
    "version": "V1R2C01"
  }
}
```
