### ISSUE TITLE
Global ellipsis on breadcrumbs

### ISSUE THREAD

**Issue by aldipower** [mesosphere/marathon#2714]
![label2](https://cloud.githubusercontent.com/assets/859154/11394495/a9ed2838-9365-11e5-8cea-948bff7732ca.png)

The BreadcrumbsComponent doesn't evolve a global ellipsis.
It's just cut by the next column or field.

It should have an ellipsis ```...``` in the case that the breadcrumbs-width is larger then the available space.

**Comment by mwasn** [comment]
How can the user navigate to the deepest level in this case? 
Could we show the full path (incl. link) as a drop-down similar to the label dropdown? Would appreciate a solution for this as the is the common use case I think.

**Comment by aldipower** [comment]
The user should still able to navigate to the deepest level.

I was not precise in my explanation, sorry.

I thought about a clickable ellipsis like this:
```in Applications > ... > longrou...|```

**Comment by mwasn** [comment]
Sounds good. Let´s test this out.
