### ISSUE TITLE
Deployment loading bar should have new style

### ISSUE THREAD

**Issue by aldipower** [mesosphere/marathon#2715]
If I _rollback_ or _stop_ a deployment in the deployment list the old loading bar appears.
It should have the same style as the new barbershop loading bar.

https://github.com/mesosphere/marathon-ui/blob/master/src/js/components/DeploymentComponent.jsx#L57

**Comment by mwasn** [comment]
Should be fixed with 0.14.0 to achieve consistency.

**Comment by philipnrmn** [comment]
Is this a good interaction? Isn't it kind of weird to show a deployment deploying? Metadeployment? @leemunroe, would be interested in your thoughts.
