### ISSUE TITLE
Rename the "basic" app type

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#2717]
Rename the "basic" app type and all similar references as there is no such thing.

**Comment by mwasn** [comment]
Is "basic" visible in the ui anywhere? Then let´s fix that in 0.14.0 otherwise in 0.15.0

**Comment by orlandohohmeier** [comment]
@mwasn It's not visible, just a few constants and string references.

**Comment by mwasn** [comment]
@orlandohohmeier OK, then let´s fix it right away in 0.15.0 so that we don´t carry this technical debt with us.
