### ISSUE TITLE
Show Logs (Error Logs and and Output Logs) in Task Detail View

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#2721]
Show logs within the marathon ui, to streamline the task debugging: As Administrator I want to access the Error and Output Logs of a single task so that I stay in Marathon UI for while debugging issues.

Please use the prototype (#2645) as reference and foundation. Besides the missing features the prototype needs a structural rewrite for better reusability.

**Scenario 1: show download link for stdout**
GIVEN a deployed app with one or more tasks
WHEN a user opens the app detail view
THEN a download link stdout is shown for every task

**Scenario 2: show content of stdout file**
GIVEN a download link for stdout file
WHEN a user clicks on the link
THEN the content of the file is shown in a separate window

**Scenario 3: show download link for stderr**
GIVEN a deployed app with one or more tasks
WHEN a user opens the app detail view
THEN a download link stderr is shown for every task

**Scenario 4: show content of stderr file**
GIVEN a download link for stderr file
WHEN a user clicks on the link
THEN the content of the file is shown in a separate window

---
https://projects.invisionapp.com/share/9U3ZMXKD5#/screens/97718387

**Comment by mwasn** [comment]
@orlando: is this issue ready to be refactored in 0.14.0 or is it just a reminder for a later step? If it´s just a reminder we should assign it to milestone _Next_

**Comment by orlandohohmeier** [comment]
@mwasn I would like to get the feature ready for 0.14.0.  *BTW: That's the wrong Orlando... :smile:*

**Comment by mwasn** [comment]
Ups...
