### ISSUE TITLE
Clean up model validation

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#2723]
Currently, validations in Marathon are done using different methods. Some validations are applied in "Formats" (JSON->Case Class conversion). Some validations are applied via Annotations and some validations are applied by methods in BeanValidation.

It would be nice to unify the approach and ensuring the following properties:

* Constructing case classes with invalid attributes throws an exception
* User-friendly validation errors
* Errors are mapped to JSON-API-fields wherever possible
* Checks are not duplicated

We prototyped some concepts that we want to leave here for future reference:

```scala
case class ModelValidation(validation: () => Boolean, error: String)
object ModelValidation {
  def apply(validation: => Boolean, error: String) = new ModelValidation(() => validation, error)
}

case class HealthCheck(...) {
  def validations: Seq[ModelValidation] = Seq(
    ModelValidation(validCommandHealthCheck, "A command health check may not specify a port."),
    ModelValidation(validHealthCheckWithPort, "portIndex and port may not be used at the same time.")
  )

  def validCommandHealthCheck: Boolean =
    if (protocol == Protocol.COMMAND) port.isEmpty // we cannot exclude portIndex because of backwards compatibility
    else true

  def validHealthCheckWithPort: Boolean =
    if (protocol != Protocol.COMMAND) portIndex.isDefined ^ port.isDefined
    else true
  }
  // ...
}
```

And inside the formats we could use something like:

```scala
    val reads = new Reads[HealthCheck] {
      override def reads(json: JsValue): JsResult[HealthCheck] = {
        try format.reads(json)
        catch {
          case MyValidationException => 
            JsError
        }
      }
    }

    Format(reads, format)
```

**Comment by aquamatthias** [comment]
@gkleiman: @alexanderweber currently works on improving ModelValidation. The idea is to use https://wix.github.io/accord/ 
The validation mechanism you outline here should be achieved by this.

**Comment by kolloch** [comment]
Cool! @aquamatthias 

One of the differences seems to be that you can still construct instances of the case classes that have invalid fields. If I think about it, I actually think that's good because it leaves validation out of tests etc but @gkleiman was concerned about that.
