### ISSUE TITLE
feature request: User controllable app upgrade policy

### ISSUE THREAD

**Issue by chengweiv5** [mesosphere/marathon#2724]
As discussed in marathon groups [here](https://groups.google.com/forum/#!msg/marathon-framework/34d9kS1pFbY/MAGfmcK_BQAJ), I open this issue to track this feature request.

> Hi all,
>
> We're running marathon 0.9.2 + mesos 0.21.0 in product environment with great experience.
>
> As marathon targets to hosting log-running service and we run some web apps on marathon and experienced upgrade apps by upgrading it's docker image.
>
> However, after go though marathon docs(https://mesosphere.github.io/marathon/docs/) we found that seems marathon doesn't support user controllable upgrade policy but documented some hints to do BLUE-GREEN deployment.
>
> What we mean "user controllable app upgrade policy" like below:
>
> 1. user controlled what percentage of running containers will be upgraded
> 2. after configured percentage of running containers upgraded, stop for a period user specified, like, 1day, 1week or forever until receive next instruction.
>
> Though we can do that based on BLUE-GREEN deployment, but it's much complicated since you have two apps, and we'll merge both them into load balancer or proxy, that means some hacks by hand or in code.
>
> Is there any plan to implement "user controllable app upgrade policy" or such a feature deserved a PR?
>
> --
> Thanks,
> Chengwei

**Comment by aquamatthias** [comment]
Hi @chengweiv5 please see: https://mesosphere.github.io/marathon/docs/deployments.html Rolling Restarts. 
to point 1 in you list: can be controlled by minimumHealthCapacity 
to point 2 in your list: the upgrade process waits until the first set of deployed apps becomes healthy. 

- Can you explain why a user defined waiting period is helpful?
- If you could define this period, is there anything else, that is missing?

**Comment by wendigo** [comment]
Hi,

I have very similiar use cases:

1. Healthy does not mean that instance is running at full capacity - i.e. JVM applications need some time for JIT to optimize code,
2. Spawned new instance(s) will receive fraction of production traffic and if and only if everything seems ok after defined time new version will be scaled up and old instances will be destroyed (you can call it canary testing in production)

**Comment by aquamatthias** [comment]
@wendigo 
1. is the responsibility of the application, that signals the health status. There will probably never a mechanism in Marathon, that knows about JIT status of a started Java application. 
2. You are right. There are several issues missing here: 
  - how does service discovery work?
  - how is load balancing set up?
  - graceful shutdown: how can we drain traffic, before shutting down
  - ...
I think we have to break this epic down into smaller pieces...

**Comment by wendigo** [comment]
Okay. Maybe we could introduce something like "stages". Each deployment consists of multiple stages like:

1) deploy new version
2) scale to 4 new instances
3) kill old version
4) end deployment

Transition to the next stage could be triggered manually (API call) or by some sort of internal signal (i.e. health check, timer, any other condition)

**Comment by aquamatthias** [comment]
Hey @wendigo we have the concept of Deployments. Every deployment can contain a list of DeploymentSteps, each step executing several DeploymentActions. A rolling update basically is able to work the way you describe it. Depending on the minimumHealthCapacity you can control how many instances should get started/stopped.

Did you try this out?

**Comment by wendigo** [comment]
But there is way to manually trigger transitions between DeploymentSteps? I would like to halt deployment between Steps.

**Comment by aquamatthias** [comment]
@wendigo No. Can you create a separate ticket for that?

**Comment by wendigo** [comment]
Yes I can :)

**Comment by wendigo** [comment]
https://github.com/mesosphere/marathon/issues/2766

**Comment by chengweiv5** [comment]
hi @aquamatthias 

>Can you explain why a user defined waiting period is helpful?

This is quiet helpful if we can stop after rolling upgrade several instances, so it works like a A/B test.

>If you could define this period, is there anything else, that is missing?

define this period is fine or I can ask to stop after upgrade some of instances, like @wendigo ask for #2766

**Comment by aquamatthias** [comment]
@chengweiv5 thanks for the answer. Since #2766 is more clear in scope, I will close this ticket.
