### ISSUE TITLE
Using container of type MESOS does not start task

### ISSUE THREAD

**Issue by philwinder** [mesosphere/marathon#2725]
Using the following marathon command:
```
{
  "id": "mesos-containerizer",
  "cpus": 0.2,
  "mem": 256,
  "instances": 3,
  "args": ["sleep", "100"],
  "container": {
    "type": "MESOS",
    "volumes": [
      {
        "containerPath": "/test",
        "hostPath": "/some/test",
        "mode": "RW"
      }
    ]
  }
}
```
I am unable to launch a task. What I expect, is that a task is launched with the standard Mesos containerizer, with this volume. Marathon accepts this as valid JSON. However, Mesos reports the error:
```
Container 'xxx' for executor 'xxx' of framework 'xxx' failed to start: None of the enabled containerizers (mesos) could create a container for the provided TaskInfo/ExecutorInfo message.
```
If you remove the container item from the json, everything works as expected.

Because Marathon does not log the TaskInfo packet it is sending to mesos, I can't be sure why this is failing.

**Comment by philipnrmn** [comment]
Hi @philwinder,

That's not a valid 

`MESOS` is not a valid value for `type`. At present, Marathon only supports the value `DOCKER` as a `type`. The `type` field is for forward-compatibility in case Marathon is extended in the future to support alternative container formats, eg runC. 

Any app started without a `container` field will be containerised by Mesos using cgroups. You can therefore start your application in a 'mesos' container like so:

```
{
  "id": "mesos-containerizer",
  "cpus": 0.2,
  "mem": 256,
  "instances": 3,
  "cmd": "sleep 100"
  }
}
```

**Comment by philwinder** [comment]
Sure, but how do you add volumes? :-)

**Comment by philipnrmn** [comment]
There's no need to add volumes to the Mesos sandbox - if I've understood your question correctly, and you simply want read/write access to the hard disk of the node on which your task is running, then you have it already. 

As an example, try deploying a task:
```
{
  "id": "write-to-disk",
  "cmd": "echo working > /tmp/write-to-disk && sleep 100"
}
```

Then from your shell
```
$ cat /tmp/write-to-disk
working
```

**Comment by philwinder** [comment]
Actually, what I'm worried about is applications having access read/write anywhere on the host. For example, I could easily run: `"cmd": "sudo rm -rf /"`.

Mesos containerizer volumes allow an application to have it's own pseudo filesystem. E.g. I can all the container to "think" it is writing to /var/tmp, but infact it is only writing to a local copy. See http://mesos.apache.org/documentation/latest/containerizer/

So, there are use cases that require applying Mesos volumes, so I was wondering how to do that via marathon?

However, I have recently found out that the mesos containerizer doesn't allow you to mount bind /, which is what I really want. So even if there was a way in marathon, it still wouldn't work.
