### ISSUE TITLE
Health Checks events should contain hostname

### ISSUE THREAD

**Issue by gongaiguo** [mesosphere/marathon#2726]
I try use event bus to generate alarm. But I can't get hostname from the health checks events.
And it's so tedious  to get the hostname from mesos by failed taskId. 
Could the events' json content contain the hostname of the failed task?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3452. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
