### ISSUE TITLE
Integrate IP-Per-Container ipAddresses into task detail view

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2727]
The task detail view needs to support the IP per container feature, which will expose a new set of fields on each individual task:

```

{
  "host": "slave1.local",
  "id": "my-app_0-1396592784349",
  "ipAddresses": [
    {
      "protocol": "IPv4",
      "ipAddress": "192.168.0.2"
    }
  ]
  ...
}
```
If a task exposes the `ipAddresses` array, it needs to be used to generate the task's URL, which will be populated by combining the `ipAddress` and the `port`, which comes from the app definition as provided by the user:

Example:
```
{
  "id": "oinker",
  "instances": 3,
  "ipAddress": {
    "labels": {
      "pool": "10.1.2.0/24"
    },
    "discovery": {
      "ports": [
        { "number": 80, "name": "http", "protocol": "tcp" }
      ]
    }
  }
```

So the URL for the task above should be:

`{task.ipAddresses[0].ipAddress}:{app.ipAddress.discovery.ports[0].number}`

cc @aquamatthias @mwasn

**Comment by aldipower** [comment]
@aquamatthias Are the JSON definitions set in stone?

This needs also an issue in the application creation modal dialog.

**Comment by pierlo-upitup** [comment]
@aldipower we suggested to postpone the modal dialog part for Phase 2 as it might create confusion.

**Comment by aquamatthias** [comment]
@pierlo-upitup Correct. In Phase 1 there will be most likely only one IP address.
