### ISSUE TITLE
Expose IP-per-container app definition in App Details page

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2729]
The App Details page needs to expose the new `ipAddress` object in the `Configuration` tab.

A `ipAddress` attribute will be added to the application definition. This attribute will hold the specification of a network interface with following attributes:
```
{
  "id": "oinker",
  "instances": 3,
  "ipAddress": {
    "groups": ["dev"],
    "labels": {
      "pool": "10.1.2.0/24"
    },
    "discovery": {
      "ports": [
        { "number": 80, "name": "http", "protocol": "tcp" }
      ]
    }
  }
```

**groups** (optional): array of network groups. One network interface can belong to zero or more network groups. The idea is that containers can only reach containers with which they share at least one network group.
**labels** (optional): arbitrary key/value pairs as meta data to the network definition. This data can be used in the IPAM service to further specify requirements for the network interface.
discovery (optional): array of discovery information objects with the following attributes:
ports (required): an array of objects describing the ports used by the app. Each object contains the following attributes:
**number** (required): integer field with the port number the app is bound to.
protocol (required): enumeration of ["tcp", "udp"] defining the protocol.
name (optional): name of the port.

**Comment by pierlo-upitup** [comment]
@leemunroe would it be enough to expose this object as a "code" block like we do for the healthChecks or can you suggest a better approach?
Keep in mind that:
- `labels` are not the same as the top-level labels, they are specific to the `network` object and have likely different meaning / use cases
- `groups` is an array
- there can be multiple `ports`

**Comment by leemunroe** [comment]
@pierlo-upitup I think that makes perfect sense.

**Comment by gkleiman** [comment]
There's something not covered by mesosphere/marathon-ui#447.

Tasks with their own IP address still have a `host` field, with the hostname of the slave they're running on.

That field should be shown in the task details page.
