### ISSUE TITLE
Health Checks is shown but not added

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#2732]
If you create/edit an app and open the "Health checks" section of the form, you see one pre-existing health-check:

![screen shot 2015-11-26 at 16 51 14](https://cloud.githubusercontent.com/assets/339354/11426668/f3437e12-945d-11e5-96ee-c923c3e3cc11.png)

If you now click on "create", an app without a health check is created. The health check is only added if you fill in something into the path field. If you remove it again, the health check apparently remains and is validated:

![screen shot 2015-11-26 at 16 54 14](https://cloud.githubusercontent.com/assets/339354/11426729/5a5b6b3c-945e-11e5-8154-405bfea626a1.png)

You can "remove" the health check if you click on the "-" sign. Then you get back to the state shown in the first screenshot.

I think that it would be easier to understand if we didn't show any health check form at all if you don't have a health check. Once you click on "Add Health Check", the health check form appears and is validated.

**Comment by mwasn** [comment]
Thanks @kolloch ! 
@leemunroe Can you please double-check the Healthcheck section from design point of view?

**Comment by kolloch** [comment]
Right, I think this a duplicate but actually I would like to keep something open to track this.

**Comment by pierlo-upitup** [comment]
@kolloch https://github.com/mesosphere/marathon/issues/2529 was closed by https://github.com/mesosphere/marathon-ui/pull/446 – can we close this now?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3326. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
