### ISSUE TITLE
Invalid validation for multiple ports

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#2734]
![screen shot 2015-11-26 at 17 53 19](https://cloud.githubusercontent.com/assets/339354/11427875/b5506116-9466-11e5-88d4-d3f4b0c5ac90.png)

**Comment by aldipower** [comment]
I can't reproduce this.
Which UI version do you use?
Could you show me how to reproduce this?

**Comment by kolloch** [comment]
Create an app with ports "0". Than afterwards edit the app and change it to something like "1xxxx,0".

**Comment by kolloch** [comment]
I think that it is a service level bug.The API call returns

```json
{"message":"Bean is not valid","errors":[{"attribute":"ports","error":"Elements must be unique"}]}
```
