### ISSUE TITLE
Marathon keeps waiting if uri is not available

### ISSUE THREAD

**Issue by jglobant** [mesosphere/marathon#2736]
I added a uri which does not exist to the json and launched the task in Marathon 0.11 on Mesos 0.23. The task did not start neither changed its status, it kept on "waiting".
Of course uris should exist and it is kind of an admin's fault.

Nonetheless Marathon should give some warning in this case.

**Comment by kolloch** [comment]
This is handled by the fetcher in Mesos. The errors are not propagated back to Marathon so that we cannot display them to the user.

**Comment by jglobant** [comment]
Where can I find a log about this?

**Comment by kolloch** [comment]
@bernd-mesos Can you help him?

I would guess that it is the Mesos agent logs or the sandbox logs (stdout/stderr).

**Comment by jglobant** [comment]
nothing to find there
