### ISSUE TITLE
can't get host ip in docker container managed by marathon and mesos

### ISSUE THREAD

**Issue by zjyzju** [mesosphere/marathon#2737]
We need get host ip in docker container for service discovery. And with docker cmd, we can use docker cmd like 'docker run -d -e HOST_IP=`ip -4 addr | grep eth | grep -Po 'inet \K[\d.]+' | sed -n '1p'`'. But with marathon, how to get host ip in docker container?

**Comment by philipnrmn** [comment]
This depends to an extent on your environment. It may be as simple as inspecting the `DOCKER_HOST` EV. 

Alternatively, if you have stable IP addresses for your machines, you can create a configuration file with the IP address in it, and mount that as a shared volume into the container. 

If your requirements are more complex, I'd suggest tracking and contributing to #1800 and the corresponding Mesos issue [MESOS-2902](https://issues.apache.org/jira/browse/MESOS-2902).

**Comment by zjyzju** [comment]
Thanks, now I have got the host ip in container through env which set by marathon cmd command in json file: "cmd":"export HOST_IP=$HOST && /usr/bin/supervisord -c /etc/supervisord.conf".

**Comment by philipnrmn** [comment]
Thanks for updating the ticket! Glad you got it working.

**Comment by deedubs** [comment]
I know this is a long dead issue but I wanted to give an option for those of us on AWS.

You can hit the metadata service from inside your container to get the hosts information.  Retrieving the private IP of the HOST can be accomplished using

> curl http://169.254.169.254/latest/meta-data/local-ipv4

Public IP is at

> curl http://169.254.169.254/latest/meta-data/public-ipv4
