### ISSUE TITLE
Introduce ES6 import-statement

### ISSUE THREAD

**Issue by aldipower** [mesosphere/marathon#2738]
Refactor all usages of ```require``` to the new ```import```-statement.

So this
```javascript
var myModule = require("../js/myModule");
```
becomes this
```javascript
import myModule from "../js/myModule";
```

**Comment by pierlo-upitup** [comment]
As I see this as a tech-debt issue, I'd suggest to provide a pragmatic explanation to why this is needed with benefits, pitfalls, etc.

**Comment by aldipower** [comment]
@pierlo-upitup Good point. Until this is done, this issue is not implementable.
