### ISSUE TITLE
Run Unit Tests on Jenkins

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#2739]

**Comment by kolloch** [comment]
Just had a meeting with @ssk2. He will either run the unit tests on jenkins or ./bin/run-tests.sh (including integration/scale simulation tests as well).

**Comment by pierlo-upitup** [comment]
Removing `gui` label as it does not apply.

**Comment by mwasn** [comment]
Tests successfully added to internal Jenkins instance (jenkins.mesosphere.com).
