### ISSUE TITLE
Override cmd field with null, not " "

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2749]
#2147 is resolved, and we can therefore update our handling of the `cmd` field. 

Before this fix was in place, we were unable to override an existing `cmd` value. We opted to send a single space `" "` instead. Unfortunately, this had the serious side-effect of preventing the application running its own `cmd` or `entrypoint` directive, and instead caused it to restart repeatedly. 

We should ensure that a `null` value is sent to the API in this circumstance, and the single space is never sent.

**Comment by pierlo-upitup** [comment]
Thanks a ton for following up on this!

**Comment by aldipower** [comment]
Great, thank youe!

**Comment by drdocker** [comment]
Woohoo! Thanks a bunch.
