### ISSUE TITLE
idea: define app template that could be loaded from Marathon UI when creating a new app

### ISSUE THREAD

**Issue by geoffroyjabouley** [mesosphere/marathon#2750]
These json templates could be stored in a local folder, or in a git
Whenever creating a new app using Marathon UI, you can load an existing template and then tune it for your need (ex: change an environment variable value).

**Comment by orlandohohmeier** [comment]
Thanks for your input. I like the idea of app templates to streamline the app creation. Predefined or community templates could also help lowering entry barriers to newcomers.
Thinking about this ideas I even suggest to have an extra dialog/endpoint where you only need to define a very limited set of variables to actually create an app.

@aquamatthias @pierlo-upitup @leemunroe What do you guys think?

**Comment by aquamatthias** [comment]
Reminds me a little bit, of what we are trying to achieve here: https://github.com/mesosphere/multiverse/

**Comment by junneyang** [comment]
+1
this cloud be very useful!

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3607. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
