### ISSUE TITLE
use log-driver optin while deploying application inorder to redirect logs to journald

### ISSUE THREAD

**Issue by chaithrar** [mesosphere/marathon#2754]
Hi,

We have requirement where we need to redirect logs from marathon deployed applications to go to journald.

docker 1.6 higher support "log-driver" option which pushes logs to journald/json-file
Can this option be used in the json files. If its possible can you please share the sample json file

**Comment by orlandohohmeier** [comment]
As far as I know it's not possible due to the way mesos handles docker. Please see the following thread for details:  https://groups.google.com/d/msg/marathon-framework/kaQ6m35AYjQ/wjj9OHn1_9wJ

**Comment by chaithrar** [comment]
I got it worked for latest version of docker 1.6 . But seem slike systed_unit in journald is coming as docker.service.  and container name is messos-<long numer> so there is no way I am able to map the application. Is there any way we can override  container name mesos creates?

**Comment by orlandohohmeier** [comment]
Thanks for sharing your findings. I'll reach out to the team and get back to you as soon I have an answer.

**Comment by tspecht** [comment]
Any news on this? Would be great to have the log output to debug containers that fail to start!

**Comment by ensonik** [comment]
+1

**Comment by aaaler** [comment]
:+1:

**Comment by rahimre** [comment]
+1

**Comment by iannickb** [comment]
+1

**Comment by xissy** [comment]
+1

**Comment by jdef** [comment]
AFAIK there is no way to rename the container that mesos creates (aside from influencing the cgroup root that mesos uses (cgroups_root flag)).

**Comment by Matt-Dee** [comment]
I'd like to bump this.  I'm tasked with a similar issue and am really interested as to what the solution was.

**Comment by thiagoit** [comment]
+1

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3143. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3143. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
