### ISSUE TITLE
Allow executor reuse

### ISSUE THREAD

**Issue by burke** [mesosphere/marathon#276]
I'm not really sure how to go about implementing this exactly, but it would be nice to be able to tell marathon to reuse an executor for multiple task invocations:

We're not migrating to the containerizer API just yet, and we're writing our own Docker executor. Since docker containers aren't spawned inside the cgroup created by mesos, we'd like to use one shared executor per host to spawn all the docker containers mesos asks for.

Due to https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/mesos/TaskBuilder.scala#L78, we can't currently accomplish this. 

I guess in our case it would make sense for the executorID to be `marathon-<executor path>`. I'm assuming that executorID reuse between frameworkIDs is acceptable. Maybe a boolean option in the App "reuse_executor"?

Is this out-of-scope, or does it sound reasonable?

/cc @Sirupsen

**Comment by kolloch** [comment]
Hi @burke, we just rediscovered this ticket. Is that still a priority for you? Then please reopen the ticket.
