### ISSUE TITLE
Can't seem to get Marathon COMMAND health checks to suceed

### ISSUE THREAD

**Issue by achalupa74** [mesosphere/marathon#2760]
Marathon Version: 0.13.0
Meso Version: 0.25.0

I've never been able to get COMMAND health checks to succeed.  I've specified my health check as follows:

"healthChecks": [
    {
      "protocol": "COMMAND",
      "command": { "value": "curl -i --cacert /var/chef/cache/cookbooks/man/files/default/auto4.labs.aspect.com-chain --tlsv1.2 https://$HOST:$PORT0/api/version" },
      "gracePeriodSeconds": 180,
      "intervalSeconds": 30,
      "timeoutSeconds": 20,
      "maxConsecutiveFailures": 3
    } 
  ],

When i start my application i never see the health check go GREEN.  Though if i run the curl command manually (replace $HOST and $PORT0 appropriately) from one of the master machines i'm able to get a successful HTTP response to the above command.

Can you provide any tips on how to debug COMMAND health checks?

NOTE: I've also tried simpler curl commands w/o https and I also can't get those health checks to succeed.

Thanks!

**Comment by aldipower** [comment]
Hi @achalupa74 !

Which health state you get with the command? 
Unhealthy or unknown?
Is there a task failure message if you click on the task details?

**Comment by achalupa74** [comment]
Sorry for the delay.  I'm just now getting back to this.  The other piece of data that i missed in the original question is that the application in question is a docker container.  All signs seem to indicate that the helath check isn't firing at all.  My application configuration looks like this:

Current Version - 12/17/2015, 12:51:16 PM↻ Refresh

✎ Edit
ID
/alexa/manhattanux
Command
Unspecified
Constraints
hostname:UNIQUE
layer:CLUSTER:worker
Dependencies
Unspecified
Labels
HAPROXY_URL_ACL=/manux
HAPROXY_BACKEND_SSL=true
HAPROXY_BIND_ADDR=10.240.6.196
environment=alexa
HAPROXY_MODE=http
HAPROXY_SSL_CERT=/etc/ssl/private/aws.aspect.com.pem
Resource Roles
Unspecified
Container
{
  "type": "DOCKER",
  "volumes": [
    {
      "containerPath": "/var/log/aspect",
      "hostPath": "/var/log/aspect",
      "mode": "RW"
    },
    {
      "containerPath": "/opt/aspect/certs",
      "hostPath": "/opt/aspect/certs",
      "mode": "RO"
    }
  ],
  "docker": {
    "image": "dockerreg.aws.aspect.com:5000/manhattanux:latest",
    "network": "HOST",
    "privileged": false,
    "parameters": [
      {
        "key": "env",
        "value": "MANHATTAN_PORTAL_HOST=alexa.aws.aspect.com"
      },
      {
        "key": "env",
        "value": "NODE_ENV=production"
      },
      {
        "key": "env",
        "value": "MANHATTAN_PORTAL_PROTOCOL=https"
      }
    ],
    "forcePullImage": true
  }
}
CPUs
0.1
Environment
Unspecified
Executor
Unspecified
Health Checks
[
  {
    "protocol": "COMMAND",
    "portIndex": 0,
    "command": {
      "value": "echo https://$HOST:$PORT0/api/version >/tmp/manux.log && curl -k https://$HOST:$PORT0/manux/#/login"
    },
    "gracePeriodSeconds": 180,
    "intervalSeconds": 30,
    "timeoutSeconds": 20,
    "maxConsecutiveFailures": 3,
    "ignoreHttp1xx": false
  }
]
Instances
1
Memory
128 MiB
Disk Space
0 MiB
Ports
443
Backoff Factor
1.15
Backoff
1 seconds
Max Launch Delay
3600 seconds
URIs
Unspecified
User
Unspecified
Version
2015-12-17T17:51:16.587Z


You'll notice in the above I altered the health check to also do a simple 'echo' of some text into the a log file.  I'm not seeing this log file getting created.  And in the marathon UI the health status stays 'gray' which i assume means unknown?


I'm attaching a couple of screenshots from the Marathon UI.


![debugtab](https://cloud.githubusercontent.com/assets/13783548/11877567/1937c982-a4be-11e5-8be7-fb46b5a4595a.JPG)
![health](https://cloud.githubusercontent.com/assets/13783548/11877590/3f0f3884-a4be-11e5-8e98-4eb49dd1bc84.jpg)


Any help is much appreciated.

**Comment by achalupa74** [comment]
We found a work around for this problem.  by adding these environment variable to the application json we now see the command health checks firing

"env": {    
    "MESOS_LAUNCHER_DIR": "/usr/libexec/mesos"
  },

taken from here: https://issues.apache.org/jira/browse/MESOS-3738

**Comment by achalupa74** [comment]
Don't understand why but adding the MESOS_LAUNCHER_DIR environment variable solved our problem.  closing this cases.
