### ISSUE TITLE
Reason code should be propagated for TASK_FAILED status_update_event messages

### ISSUE THREAD

**Issue by andrewortman** [mesosphere/marathon#2762]
In the event stream, it would be nice to distinguish between different failure modes whenever you receive a TASK_FAILED event. For example, knowing when the task failed due to memory constraints or disk constraints.

Right now the message looks like this: 

``` json
{
  "slaveId": "20151103-152147-1444348170-5050-25743-S22",
  "taskId": "test.536e8db4-99e6-11e5-8a3e-00163e011756",
  "taskStatus": "TASK_FAILED",
  "message": "",
  "appId": "/test",
  "host": "foobar3",
  "ports": [
    31595,
    31596
  ],
  "version": "2015-12-03T17:47:53.585Z",
  "eventType": "status_update_event",
  "timestamp": "2015-12-03T17:51:08.753Z"
}
```

but ideally we would have an additional "reason" field with the reasons code in mesos.proto - 

``` json
{
  "slaveId": "20151103-152147-1444348170-5050-25743-S22",
  "taskId": "test.536e8db4-99e6-11e5-8a3e-00163e011756",
  "taskStatus": "TASK_FAILED",
  "message": "",
  "reason": "REASON_CONTAINER_LIMITATION_MEMORY",
  "appId": "/test",
  "host": "foobar3",
  "ports": [
    31595,
    31596
  ],
  "version": "2015-12-03T17:47:53.585Z",
  "eventType": "status_update_event",
  "timestamp": "2015-12-03T17:51:08.753Z"
}
```

**Comment by andrewortman** [comment]
Related: #1306

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2913. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2913. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
