### ISSUE TITLE
Can we customize the contaier name created by mesos?

### ISSUE THREAD

**Issue by chaithrar** [mesosphere/marathon#2763]
By default mesos creates container name staring with mesos-<long number 
can we overiride this? can we specify what could be the container name for an app?

**Comment by janisz** [comment]
Duplicated by https://github.com/mesosphere/marathon/issues/4805

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4196. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4196. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
