### ISSUE TITLE
Make health status bar wider

### ISSUE THREAD

**Issue by leemunroe** [mesosphere/marathon#2764]
Would it make sense to give the health status bar more room on the application list view?

Right now it feels very cramped @ 50px. User tests have indicated these bars are useful. And there is typically a lot of extra real estate dedicated to app and group names to take advantage of.

![image](https://cloud.githubusercontent.com/assets/15963/11578984/dc52220e-99de-11e5-8e84-3dad13c28c8d.png)

**Comment by pierlo-upitup** [comment]
I think the most sensible approach would be to have a few preset values based on screen width. I wouldn't just make it larger by default for all viewport sizes.

**Comment by drdocker** [comment]
:+1: Good discussion, guys.  @pierlo-upitup I like that idea and I love the 0.13 UI, but the health bars are looking a little small, especially on large monitors. Decreasing the colspan on the "x of x" column, and doubling the colspan on the health bar seems to make it look a bit better.


![health2](https://cloud.githubusercontent.com/assets/14265086/11645421/04bcec40-9d1a-11e5-9693-6d429e124196.png)

Cheers!
