### ISSUE TITLE
feature request: manually trigger transition between deployment steps

### ISSUE THREAD

**Issue by wendigo** [mesosphere/marathon#2766]
Related to discussion in https://github.com/mesosphere/marathon/issues/2724

I would like to define deployment with multiple deployment steps in such way that transition between consecutive deployment steps will be either automatic or manual.

i.e. when rolling new version I would like to model this kind of deployment:
- fetch, deploy new version, scale it to 4 instances
- <- waiting for trigger
- scale new version to 8 instances
- <- waiting for trigger
- destroy old version

Having this kind of manual control over transitions will allow to model more complex deployment models when there is non-zero, non-deterministic interval between each deployment steps: canary tests in production where new version will receive fraction of production traffic, it's scaled up after N hours and full deployed after another M hours. 

It would be also great to be able to see deployment steps (progress) in UI and trigger transitions from UI/API

**Comment by chengweiv5** [comment]
+1, this is a feature request from real world, user may like to do this to do:

- manually health check, more comprehensively, rather than marathon health check, to ensure everything goes fine with the new version
- A/B test, yes, I known green blue deployment, but it's too complicated to operate, user have to handle **2 apps** and update these 2 apps in their load balancer, whenever he change the upgrade percentage, it's nightmare.

**Comment by drcrallen** [comment]
I have 3 apps setup in marathon called "???-canary, ???-perf, ???-rollout" which function in a similar fashion. (they also sort lexicographically correct)

Since "when" to transition from one to the other, aka, when a canary is considered qualified, or a perf test is considered qualified, can greatly vary... I don't see a good way to hook this into marathon directly.

**Comment by brndnmtthws** [comment]
It's worth mentioning that this can be done with [marathon-lb](https://github.com/mesosphere/marathon-lb#zero-downtime-deployments).

**Comment by r4um** [comment]
Since everyone has their own requirements and use cases, how about making upgrade strategies pluggable and selectable during application creation and/or deployment ?

Additionally it would be awesome, if one can interact with these plugins via the API, `/plugins/PLUGIN` endpoint or something.

**Comment by karlkfi** [comment]
One alternative to manual transition triggers would be **blocking lifecycle event hooks**.

Deployment Example:

1. Load Balancer registers blocking deployment hook for all services (maybe in a group)
1. User creates new app
1. Marathon deploys new app
  1. Marathon creates new app instance
  1. Marathon calls Load Balancer and blocks
  1. Load Balancer creates/updates LB table and tells Marathon to continue
1. Marathon shows app as deployed

Graceful Update Example:

1. Load Balancer registers blocking deployment hook for all services (maybe in a group)
1. User updates existing app config
1. Marathon performs rollign deployment
  1. Marathon creates new app instance
  1. Marathon calls Load Balancer and blocks
  1. Load Balancer creates/updates LB table and tells Marathon to continue
  1. Repeat i-iii until configured quorum is reached
    1. Marathon calls Load Balancer and blocks
    1. Load Balancer switches incoming traffic from old table to new table
  1. Repeat i-iii until all instances are replaced
1. Marathon shows app as updated/deployed

This pattern should also work for internal or external drains.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4396. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4396. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
