### ISSUE TITLE
Current group should be prefilled in the app creation modal

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2768]
If a user is looking at a particular group when they hit the create button, we can infer that they intend to create an application in the same group. We should prefill the current group in the ID field. 

*via @gkleiman*

**Comment by pierlo-upitup** [comment]
This is already the case in 0.14 
![create](https://cloud.githubusercontent.com/assets/1078545/11591143/d7c05618-9a95-11e5-9911-7d7fe583edc1.gif)

**Comment by philipnrmn** [comment]
Oops, missed that PR - thanks.
