### ISSUE TITLE
Show empty groups

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2769]
At present we don't show empty groups in the UI. If we intend to give users the ability to add groups (relevant issue: #966) and delete groups (relevant issue: #2770), we should also show empty groups. 

We should probably make it clear to the user that a group is empty - possibly with a different icon from a populated group?

**Comment by pierlo-upitup** [comment]
Interesting insights : https://github.com/mesosphere/marathon/issues/966#issuecomment-169729521

**Comment by pierlo-upitup** [comment]
cc @leemunroe do empty groups call for a different icon to signal their emptyness?

**Comment by leemunroe** [comment]
Good thinking. We'll come up with an icon.

**Comment by leemunroe** [comment]
On second thoughts, after looking at other tools (e.g. Finder, Drive, Dropbox) we feel it doesn't require a different icon. Please use the same folder icon.

**Comment by pierlo-upitup** [comment]
Closed by https://github.com/mesosphere/marathon-ui/pull/670
