### ISSUE TITLE
URI fields should be links

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2772]
Where the URI field is linkable - ie is of a suitable protocol to be opened in a browser - we should make it a link to allow the user to check it quickly. This link should open in a new tab. 

*via @gkleiman*

**Comment by pierlo-upitup** [comment]
@gkleiman could you provide examples of where this is not already the case?

**Comment by gkleiman** [comment]
@pierlo-upitup we were looking at the app configuration view.

**URL:** http://localhost:8080/ui/#/apps/%2Fprod%2Fapp1/configuration

**Screenshot:**

<img width="855" alt="screen shot 2015-12-08 at 21 34 50" src="https://cloud.githubusercontent.com/assets/146374/11667724/b16c82d2-9df3-11e5-8779-b10e0095b4f8.png">
