### ISSUE TITLE
Don't display "unspecified" fields in the UI

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2773]
Many fields are shown in the UI when they are "unspecified". This creates unnecessary noise. We should consider which fields we want to display when they are not specified in the configuration (eg `cmd`), and hide all others unless they are specified. 

Posted configuration

```
{
  "id": "minimal-app",
  "cmd": "sleep 100"
}
```

Displayed configuration:
![screen shot 2015-12-04 at 15 13 27](https://cloud.githubusercontent.com/assets/2989362/11591642/ac81019c-9a99-11e5-959e-0697a418676d.png)

_via @gkleiman_

**Comment by pierlo-upitup** [comment]
cc @leemunroe what do you think about this? I kinda see the initial idea of showing a complete app description with visible "gaps" as I can imagine it might convey some useful information in specific scenarios...

**Comment by leemunroe** [comment]
Agreed this is ugly and noisy. But also a good nudge to what can be done. Some options:

* Switch "Unspecified" for something else like "-" or just blank to lessen the pixel density
* Remove the field row entirely if unspecified
* As @philipnrmn mentioned, only display important unspecified fields and hide others
* Add more hierarchy to this view e.g. accordion groups that replicate the create/edit modal

I'm unfamiliar with the importance of most of these fields but we could explore some options and see what people think. Any other ideas other than already mentioned?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2848. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2848. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
