### ISSUE TITLE
Sidebar mobile view and add container storage informations.

### ISSUE THREAD

**Issue by kopax** [mesosphere/marathon#2774]
- The sidebar doesn't fit well using my smartphone, Why didn't you pick the sidebar example from twitter bootstrap website ?
- Is there a chance that in later release you display the storage (used/available) of each container ? 
- Is there a chance that in a later release you display also the hostname ?

**Comment by philipnrmn** [comment]
Hi @kopax,

We don't currently target mobile browsers as a priority. Maybe you could tell us a bit about how you use Marathon from your mobile phone? I'd be fascinated to hear more. We also welcome PRs against the [UI](https://github.com/mesosphere/marathon-ui) if you'd like to have a stab yourself. 

On the matter of storage, it's not something Marathon monitors at present, I'd suggest raising an issue with the `enhancement` flag to stimulate some discussion on the matter. It should be possible to script a health check for disk usage using `cadvisor` or similar though.

**Comment by kopax** [comment]
I have no usage on mobile view but It was just a remark, I understand it is not a priority.
I have added a third question about the hostname.

**Comment by philipnrmn** [comment]
`host` is shown in the UI in the task detail view since v0.13.0.

**Comment by kopax** [comment]
I meant on the list view.
It is in the UI since way before 0.13.0

**Comment by philipnrmn** [comment]
A specific feature request is a good way to get a discussion going on this, as other members of the community will wish to offer their opinions on new functionality. 

Of course, a PR which implements this functionality is even better!

**Comment by kopax** [comment]
Could you create it for me ? 
I can't see how to create a special feature request :/

**Comment by samek** [comment]
Here you can see how it looks portrait and in landscape mode on iphone. 

It would work if the name would be printed instead of icon beside the name. 

How do I use marathon with my phone ? 
Sometimes I do scale and app over the phone, but since version 0.13 I have to use search to find the right one. 



![img_2147](https://cloud.githubusercontent.com/assets/125693/11983957/ee53e2a6-a9b7-11e5-9bfc-66811342f9ab.PNG)
![img_2148](https://cloud.githubusercontent.com/assets/125693/11983956/ee4e26d6-a9b7-11e5-86f8-fb60f2025800.PNG)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2896. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2896. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
