### ISSUE TITLE
Syntax highlighting for JSON fragments in configuration

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2775]
We display some fragments of JSON in the application configuration view (containers and healthchecks, in particular).

It would be helpful to display them with syntax highlighting. 

![screen shot 2015-12-04 at 15 17 51](https://cloud.githubusercontent.com/assets/2989362/11591730/5ae0d74e-9a9a-11e5-8897-652f9db932af.png)

*via @gkleiman*

**Comment by orlandohohmeier** [comment]
+1
