### ISSUE TITLE
Show error alert for failing Mesos logs downloads

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2777]
As discussed in https://github.com/mesosphere/marathon-ui/pull/449#issuecomment-161319707 and as planned in https://github.com/mesosphere/marathon/issues/2721 if a download fails we need to inform the user with an alert.

TODO after merging https://github.com/mesosphere/marathon-ui/pull/449

**Comment by pierlo-upitup** [comment]
@leemunroe do we have a design for this? We need to be able to show :
- a "loading" state (files are being requested but not yet available)
- an "error" state (something went wrong with the request. Possible offer the user to try again?)

**Comment by leemunroe** [comment]
@pierlo-upitup There's a loading state [here](https://mesosphere.atlassian.net/browse/MARATHON-552) and I can get you error state. Can you confirm the flow?

1. Error log and output log icons displayed
1. User clicks icon
1. Browser attempts to request and download file ("loading" state)
1. Error occurs, something wrong with request, tell user (what are the possible errors here?)
1. [Optional] User can try again

![image](https://cloud.githubusercontent.com/assets/15963/11661547/54d1f550-9d87-11e5-8e3e-fdb53cbc1236.png)

**Comment by pierlo-upitup** [comment]
Thanks for the pointer, couldn't find it on inVision. Regarding the above, it makes sense to me with an additional (optional) step 0 which would be: 

0. Show a n/a state for tasks with no files 

as covered by @aldipower in https://github.com/mesosphere/marathon-ui/pull/475 .

cc @orlandohohmeier @aldipower for additional feedback on your points

**Comment by leemunroe** [comment]
Cool. What circumstances are there no files? Would it be expected or is it a possible error? Wondering how best to communicate this.
