### ISSUE TITLE
Enable JMX

### ISSUE THREAD

**Issue by bcarpio** [mesosphere/marathon#2780]
We have added the following to our /etc/default/marathon file but it doesn't seem to correctly enable JMX, I can connect to the port via jconsole but I don't get anything back from the marathon process:

export JAVA_OPTS="-Xms512m -Xmx512m -Dcom.sun.management.jmxremote -Dcom.sun.management.jmxremote.port=9191 -Dcom.sun.management.jmxremote.authenticate=false"

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2778. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2778. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
