### ISSUE TITLE
Provision to start service group in a priority node

### ISSUE THREAD

**Issue by suyash1983** [mesosphere/marathon#2791]
When using a service group having dependent service(s), how can start those interdependent services in a specific node with highest priority. For e.g. Let say there are three node cluster running ``Mesos slave``, where each slave has it's own priority (between 1 to 3 where 1 is the highest priority) so:

- How to start a service group in highest priority node among the nodes.
- If it fails to start on that node due to some resource failure then automatically start the service group (failover condition) to node having second highest priority.
- Again failback to highest priority node if resource is available or dependency will meet.

**Comment by aquamatthias** [comment]
Hey @suyash1983. You can stick tasks to nodes via constraints: https://mesosphere.github.io/marathon/docs/constraints.html

There is currently no logic for scaling an application in a way you describe it.
It should be pretty easy to achieve that goal from outside Marathon using the REST API: https://mesosphere.github.io/marathon/docs/rest-api.html
