### ISSUE TITLE
haproxy-marathon-bridge   error

### ISSUE THREAD

**Issue by xuedihualu** [mesosphere/marathon#2793]
[root@docker-128 haproxy]# sh -x /usr/local/haproxy/haproxy-marathon-bridge 
+ set -o errexit -o nounset -o pipefail
/usr/local/haproxy/haproxy-marathon-bridge:行170: 未预期的符号 `>' 附近有语法错误

**Comment by aldipower** [comment]
Hi @xuedihualu !

Could you please post which version of Marathon, Linux distribution and Docker image you are using?
Thank you.

@lloesche

**Comment by lloesche** [comment]
@aldipower haproxy-marathon-bridge should not be used anymore. https://github.com/mesosphere/marathon-lb is doing the same thing just in a more robust way.

**Comment by aldipower** [comment]
Thank you @lloesche !

@xuedihualu Does it help you, if you upgrade to the marathon-lb ?

**Comment by xuedihualu** [comment]
@aldipower  
marathon 0.13 docker 1.9
Thank you , I will tell you , if i try it successfully.

**Comment by xuedihualu** [comment]
@lloesche
I use the images based centos. Do you have any practical examples, I would like to refer to it,thank you.
