### ISSUE TITLE
API listing of finished tasks

### ISSUE THREAD

**Issue by bydga** [mesosphere/marathon#2794]
Hi, im just wondering if you plan to add details about the ended (killed/lost/finished/failed) tasks. Currently  there's only support for the "last" fail - in both - GUI and in API. 

It would be nice to have such list with the done tasks. Or is it potentially too much storage-consuming?

**Comment by gkleiman** [comment]
Hi @bydga,

Thanks for the feature request. This has been discussed a few times, so I'll add the issue to our backlog.

The only datastore supported by Marathon right now is ZK. It's been mentioned that ZK might not be the right place to store tasks history, and a new datastore will be needed.

- Also related to #2799

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2856. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2856. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
