### ISSUE TITLE
Error: Unknown option 'zk_host'

### ISSUE THREAD

**Issue by Fei-Guang** [mesosphere/marathon#2802]
ubuntu@mesos:~/marathon-0.13.0$ export MARATHON_MASTER=zk://localhost:2181/mesos
ubuntu@mesos:~/marathon-0.13.0$ export MARATHON_ZK_HOST=zk://localhost:2181/mesos
ubuntu@mesos:~/marathon-0.13.0$ export MARATHON_HTTP_PORT=8070
ubuntu@mesos:~/marathon-0.13.0$ export MARATHON_WEBUI_URL=http://localhost:8070/index.html

[2015-12-09 15:25:43,661] INFO Starting Marathon 0.13.0 with --http_port 8070 --webui_url http://localhost:8070/index.html --zk_host zk://localhost:2181/mesos --master zk://localhost:2181/mesos (mesosphere.marathon.Main$:main)
[scallop] Error: Unknown option 'zk_host'

**Comment by aldipower** [comment]
Hi @Fei-Guang !

As the error says, there is no such option ``zk_host``.
You can see all option for 0.13.0 here:
https://github.com/mesosphere/marathon/blob/v0.13.0/docs/docs/command-line-flags.md

Define the ZooKeeper host like this
```
--zk zk://localhost:2181/marathon
```

Also your master setting seems to be incorrect, you try to connect to ZK, but you need to connect to the Mesos master.
Guessing you need this:
```
--master localhost:5050
```

Does this work?

If not, how do you start Marathon?
