### ISSUE TITLE
Refactor ajaxWrapper and throw fetch-jsonp in the mix

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2803]
After https://github.com/mesosphere/marathon-ui/pull/476 is merged
-  refactor the ajaxWrapper to be inline with the [fetch specs](https://fetch.spec.whatwg.org/) (ie: `response.body` vs `response.data`, etc.)

After https://github.com/mesosphere/marathon-ui/pull/473 is merged
- introduce [fetch-jsonp](https://www.npmjs.com/package/fetch-jsonp) to replace our custom `JSONPUtil.js`

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3663. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3663. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
