### ISSUE TITLE
Use shutdown call to kill tasks

### ISSUE THREAD

**Issue by sargun** [mesosphere/marathon#2811]
When doing a deployment or shutting down an app, ideally Marathon should use shutdown, and not kill. This gives the tasks a grace period to SIGTERM. 

In addition, once https://issues.apache.org/jira/browse/MESOS-4139 is implemented, we should be able to configure the escalationTimeout, so individual apps can have longer periods to shutdown their tasks.

**Comment by aquamatthias** [comment]
Duplicates #712
