### ISSUE TITLE
Add contextual dropdown menu to Application List items

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2814]
Mockup: https://mesosphere.invisionapp.com/share/Q255TQOTK#/screens/119875789

When the user clicks on the contextual menu toggle (e.g the three dots: "...") a dropdown offering the possible commands is shown:

- Scale
- Restart
- Suspend
- Reset Delay (optional; only if the app is delayed)

Please note the Destroy command is deliberately left out.

When one of the actions is clicked, the associated modal with confirmation/prompt is shown just like in the Application Detail view.

@leemunroe could you please attach the three dots icon to this issue?

**Comment by aldipower** [comment]
Hey @leemunroe !
Happy new year. :)
Could I find the three-dots-icon somewhere or could you add it?
Thank you.

**Comment by aldipower** [comment]
Got the icon. @orlandohohmeier gave me a hint.
