### ISSUE TITLE
Investigate alternative to ref hack for AboutModalComponent

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#2815]
TestUtils ShallowRenderer can't unmount component with refs (see: https://github.com/mesosphere/marathon-ui/blob/master/src/js/components/modals/AboutModalComponent.jsx#L63 ) on the top level component element. As introduced by mesosphere/marathon-ui#473.

**Error**
```Error: Invariant Violation: removeComponentAsRefFrom(...): Only a ReactOwner can have refs. This usually means that you're trying to remove a ref to a component that doesn't have an owner (that is, was not created inside of another component's `render` method). Try rendering this component inside of a new top-level component which will hold the ref.```

**Comment by aldipower** [comment]
The alternative is to remove the unnecessary and unneeded ref.
This ref is a leftover from the old times and could be easily removed.

**Comment by orlandohohmeier** [comment]
Ok then. Let's remove the `ref` and do the `destroy` callback handling within the `AboutModalComponent`. We might consider refactoring the underlying `ModelComponent` and get rid of the `destroy` thing... 

Nonetheless I'm wondering if there is a solution for top level component refs despite using a real DOM thing for testing.

/cc @pierlo-upitup @philipnrmn

**Comment by pierlo-upitup** [comment]
Oh yeah. I totally didn't think about that. Thanks for the heads up @aldipower 

@orlandohohmeier the solution is to stop using the shallow renderer if what we actually want is an actual mount in the DOM, which is part of our test refactoring efforts.
