### ISSUE TITLE
Document UI application states

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#2816]
Application states such as "Running", "Waiting", "Deploying", "Delayed" are not directly present in the Marathon API but deduced by querying multiple end-points. How this is done is not transparent.

Since this is such an important concept, a first step would be to document what these states mean exactly.

**Comment by pierlo-upitup** [comment]
Thanks @kolloch, that's a very good point. 
What would be the best place to hold this documentation, though? Inside the marathon-ui README.md? Or would this be the right time to add a UI section to the official Marathon docs?

**Comment by pierlo-upitup** [comment]
cc @mwasn

**Comment by mwasn** [comment]
I would prefer a UI chapter within official Marathon docs.

**Comment by pierlo-upitup** [comment]
+1 on the UI chapter in the official DOCS, and let's also add an  :information_source: icon in the table header that when clicked opens the DOCS page in a new tab (as suggested by @leemunroe )
