### ISSUE TITLE
Expose EventSubscriptions in UI

### ISSUE THREAD

**Issue by ssorallen** [mesosphere/marathon#282]
### [Event Subscriptions](https://github.com/mesosphere/marathon/blob/master/REST.md#event-subscriptions)
- List all event subscriptions
- Add a new event subscription
- Remove an event subscription
- Test an event subscription

**Comment by aldipower** [comment]
After two years of letting the API mature we should consider to implement this in the next 2 years.
ping @pierlo-upitup

**Comment by jasongilanfarr** [comment]
EventSubscribers no longer exists in Marathon 1.5 and we no longer directly support marathon-ui. Someone could provide a PR to marathon-ui to expose EventStream into the UI though...
