### ISSUE TITLE
Improve --ha description (was: typo in marathon document)

### ISSUE THREAD

**Issue by chengweiv5** [mesosphere/marathon#2820]
https://mesosphere.github.io/marathon/docs/command-line-flags.html

```
v0.13.0 --[disable_]ha (Optional. Default: enabled): Run Marathon in HA mode with leader election. 
Allows starting an arbitrary number of other Marathons but all need to be started in HA mode. This mode 
requires a running ZooKeeper. See --master.
```

should be `See --zk`?

**Comment by philipnrmn** [comment]
Hi @chengweiv5,

I think `See --master` is correct here, because it explains the previous clause and the `--master` documentation is where we explain that ZooKeeper is optional. I'm not sure the reference adds all that much value though so maybe we should just remove it. What do you think?

**Comment by chengweiv5** [comment]
sure, good to me.
