### ISSUE TITLE
Tooltip isn't removed on content change

### ISSUE THREAD

**Issue by aldipower** [mesosphere/marathon#2821]
If I stay on the health bar and the content of the tooltip changes heavily then this happens:
![tooltip](https://cloud.githubusercontent.com/assets/859154/11784279/c1057190-a27b-11e5-81d2-220f0cccd735.png)

If only the numbers are changing and not the amount of the states itself everything seems to be ok.

**Comment by orlandohohmeier** [comment]
I can't reproduce that behavior on my machine (OSX 10.11.1, Chome  47.0.2526.80), but there is an update issue... The tooltip seems to only update on mouse movement.

![health-tooltip-update-issue](https://cloud.githubusercontent.com/assets/647035/11818232/72564928-a359-11e5-92be-4c56bf9192a5.gif)
