### ISSUE TITLE
Unclear how to apply new instance count to deployed group

### ISSUE THREAD

**Issue by dontrebootme** [mesosphere/marathon#2823]
I'm defining groups and sending the json to the group endpoint to create the group, that part works. If I go back and modify the instances to a new value (1->2) and then do a group update I get back a new deploymentID and version but I dont see it actually applying and new deployments/changes.

Is there documentation about group updates and is this expected to function?

aside: I'm using [marathonctl](https://github.com/shoenig/marathonctl)

**Comment by gkleiman** [comment]
You can check the REST API docs for the [PUT /v2/groups/{groupId}](https://mesosphere.github.io/marathon/docs/rest-api.html#post-v2-groups) endpoint.

If you PUT a group and only change the instance count of an app, then it will be scaled, but the currently running tasks will not be restarted. If you modify any other app definition field, then all tasks will be restarted.

You can also scale up/down all the apps in a group by the same factor using the `scaleBy` attribute.

Examples:

POST /v2/groups:

```
{
  "id": "/prod",
  "apps": [
    {
      "id": "/prod/app1",
      "cmd": "echo `date`; sleep 5000",
      "instances": 4
    },
    {
      "id": "/prod/app2",
      "cmd": "echo `date`; sleep 5000",
      "instances": 4
    }
  ]
}
```

To scale `/prod/app1` down to 2 instances and `/prod/app2' down to 3:

PUT /v2/groups/prod:

```
{
  "apps": [
    {
      "id": "/prod/app1",
      "instances": 2
    },
    {
      "id": "/prod/app2",
      "instances": 3
    }
  ]
}
```

Or to scale up both apps to 8:

PUT /v2/groups/prod:

```
{
  "scaleBy": 2
}
```
