### ISSUE TITLE
Perhaps add simple UI for viewing collected logs

### ISSUE THREAD

**Issue by magcius** [mesosphere/marathon#2825]
The Mesos Docker slave redirects and collects logs in each slave's sandbox, but it would be nice if Marathon could have a better view of these.

This could be helpful if the slaves are in a private network and aren't publicly accessible.

**Comment by philipnrmn** [comment]
Hi @magcius, 

We've got a PR on the way which gives direct access to the `stdout` and `stderr` of each task - mesosphere/marathon-ui#473 - which should make life a bit easier. It doesn't address the case were the slave nodes aren't accessible though, this would have to be done via the API.

**Comment by magcius** [comment]
Out of curiosity, since we're building a Marathon cluster from scratch, what's the recommended setup? When we looked at DCOS, it seemed the slaves were behind a private NAT. Should the slaves be publicly accessible?

**Comment by philipnrmn** [comment]
There isn't really a single perfect setup, since requirements are so variable. 

I'm not a security expert, but it seems logical to avoid exposing nodes if you can avoid it. My preferred setup for a web application on cloud infrastructure, for example, would be to use a few public nodes as reverse proxies and run the actual app services on nodes behind private NAT or some similar mechanism.

**Comment by jolexa** [comment]
Great work on this feature in latest releases. Everything was working well until I switch to https on my URLs (behind ELB/proxy layer) - then I've found that the marathon ui redirects the request to https://<slave ip>:5051/pathtofile, naturally I don't have ssl on ever slave endpoint directly. I wonder if this is a bug or limitation of Mesos?

**Comment by philipnrmn** [comment]
Hi @jolexa, thanks for the compliment!

Running marathon behind https should not cause a problem, just ensure that the `mesos-leader-ui-url` flag is correctly set when you start marathon.

**Comment by jolexa** [comment]
Hi @philipnrmn,

My mesos_leader_ui_url is set to https://FQDN/, but then it gets redirected to the slave ip (which obviously does not have https enabled), not the FQDN. I can provide the javescript console screenshots if it helps.

**Comment by philipnrmn** [comment]
Ah, I think I understand the issue. Thanks for the report, I'll see what we can do to resolve this.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3140. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3140. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
