### ISSUE TITLE
pass credentials with ajax requests

### ISSUE THREAD

**Issue by vixns** [mesosphere/marathon#2826]
The  latest UI's ajax wrapper miss `xhr.withCredentials = true`

**Comment by philipnrmn** [comment]
Hi @vixns,

Can you confirm the version you are using (hit `g v` in the UI to see an alert with the UI version) please?

Also, does this prevent HTTP Basic Auth from working or is there some other effect?

**Comment by philipnrmn** [comment]
I just tested the latest UI (0.15.0-SNAPSHOT) with http basic auth turned on and it worked as expected, so I'm not sure what functionality is breaking here.

**Comment by vixns** [comment]
I am using marathon Version 0.14.0-SNAPSHOT with latest UI (0.15.0-SNAPSHOT), the auth/authorization plugins from https://github.com/mesosphere/marathon-example-plugins updated with latest plugin interface (0.14.0-SNAPSHOT) and https.

The Authorization header is present in the main request, but not the ajax ones.
All ajax requests return 401 http codes, because Authorization header is missing

`xhr.withCredentials = true` should fix this

**Comment by philipnrmn** [comment]
Ah, I understand then. Thanks for the PR!
