### ISSUE TITLE
Provide a UI plugin mechanism

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#2827]
There are some UI features that could be configuration/environment specific or related to a Marathon plugin (e.g. an authentication dialog). We should provide UI plugin mechanism to integrate those features.

**Example Plugins (UPDATE  5 January 2016)**

Authentication
* Display a dialog or add a login page
* Add methods to verify permissions before performing any action
* Add a method to invalidate login
 
Banner
* Add some additional static content

Tracking (Audit Log)
* Listen to all user action

Third Party Integration (e.g. Mesos Logs)
* Integrate some additional content by "replacing" components
* Add some additional content 

/cc @philipnrmn @pierlo-upitup @aldipower @aquamatthias

**Comment by orlandohohmeier** [comment]
I suggest to fix the namings, and data structure of our key components and introduce some kind of a dependency manager to replace those components if needed using separate loaded plugins with the respective js, css and html.

**Comment by orlandohohmeier** [comment]
Besides finding an elegant way to register plugins, inject code or replace components we probably need to find a way to postpone the application bootstrapping until the plugins are configured.

**Comment by rcorral** [comment]
This is my proposal for how the Plugin API should work.
This doesn't explain how it is implemented in Marathon UI nor does it explain which parts of the system should or shouldn't be pluggable.

I propose for there to be two ways in which plugins can "hook" into the system.
1. Actions
2. Filters

### Actions
These are "events" that occur in the system. For example 'applicationLoaded' or 'userLoggedIn'.
These are events that should trigger subsequent actions on plugins. For examle, after a user logs in, a tracking plugin could identify the user with the tracking system.

The API could look something like this:
* `Plugins#addAction(hookName, callback)`
* `Plugins#doAction(hookName, [argument1[, argumentN]])`

For the example above it would be used like this:

The plugin would first register for the given hook:
`Plugins.addAction('userLoggedIn', myCallback);`

Later on the application would fire the action:
`Plugins.doAction('userLoggedIn', 'joe@example.com');`


### Filters
These are hooks that allow for a value to be filtered by plugins. For example 'applicationRoutes', could be a hook that allows for a set of routes to be filtered and a plugin could in turn, add/remove routes.

The API could look something like this:
* `Plugins#addFilter(hookName, callback)`
* `Plugins#applyFilter(hookName, value, [argument1[, argumentN]])`

For the example above it would be used like this:

The plugin would first register for the given hook:
`Plugins.addFilter('applicationRoutes', myCallback);`

Later on the application would filter the routes:
`routes = Plugins.applyFilter('applicationRoutes', routes);`

**Comment by orlandohohmeier** [comment]
@rcorral Thanks for your input! Kinda sounds like the Wordpress Plugin System :wink:, which isn't bad. 
I like the idea of having a way to listen to application events and a mechanism to filter/adjust data (content and configuration). This enables a variety of different plugins (tracking, authentication, ... ) and probably covers all of our needs.

*BTW: We should perhaps use different terms, as the Wordpress documentation had sometimes confused the API terms, back in the days (thinking about the times, when I hacked Wordpress Themes and Plugins).*

@philipnrmn @pierlo-upitup @aldipower @Poltergeist What do you guys think?

**Comment by rcorral** [comment]
It is exactly the Wordpress Plugin System. Out of the many plugins systems I've used in the past, I've really liked the design of the Wordpress Plugin System the most.
In terms of naming, it doesn't matter to me ;) I like the naming they've chosen but it does take some getting used to.

**Comment by pierlo-upitup** [comment]
@rcorral thanks for the input. I like the idea of defining a "generic" API, though I'd say the challenging aspects of how a Plugin architecture should work of course lie in the details. 

I see a number of finer-grained issues that need to be addressed, for example: 

- how do you actually inject a component dynamically in the renderer? (e.g. a `loginDialog`) 
- how do we allow a plugin to inject its own actions without breaking other parts of the system? how do we manage possible dependencies between plugins?
- how is a plugin distributed?

That may be a bit too much to reason about in abstract terms, I know... 
I guess the best we can do is really just sit down and come up with an example plugin and understand the limitations/challenges.

I've found [a very nice article](https://nylas.com/blog/react-plugins) that while not easily applicable to our situation gives a few hints at how one might solve some of these things. Spoiler: the authors stress the importance of having an OmniStore (a-la Redux) to simplify things - but we can steal a couple of good ideas.

I'd love to gather some more reading material, so please share whatever you find! :+1:

**Comment by aldipower** [comment]
WIP

Hi everybody.

I want to complement this difficult topic with some ideas/thoughts, too.
It could be, that this will have a huge refactoring impact on the already existing codebase. 
We should do this in a correct way from the beginning on. We can't change our minds to a different strategy, after we implemented the plugin-system.

So I want to start to define the overall _architectural_ requirements/objectives to the plugin system.
That should be our first step to make these requirements very clear and settled.
After this, we have a base, we can work with and we can start to think about the technical implementation.

_Please feel free to add something or correct me on the requirements._

## Plugin architectural requirements

### Plugins should be _extensions_
Plugins should __not__ __modify or override__ existing code/functionality, __but__ __extend__ them.
Overriding is a maintenance mess and dangerous in terms of security and integrity of the application.

Particular example how it could work:
I am not able to replace the caption of a hard-coded table column.
But it is possible to _add_ a _complete_ new table!
In this particular example, we could bring the hard-coded table also into a plugin.
This enables us to replace the old table itself - now a plugin too - with another plugin.

I am able to extend Marathon UI.

Most plugins won't replace anything, just add things, which makes it easier to deal with those.

### Plugins should be able to _communicate_
Communication is always bi-directional (not technically), means receive and send.
The plugin should be able to __listen__ on application wide dispatched events.
The plugin should be able to __emit__ application wide dispatched events.

It should __never__ be able to see or __call__ a __function__ from __outside__ of it's own living.
Not the actions, not the stores, not the components.

Particular example how it _could_ work with __receiving__:
Plugin wants a fresh app list from the API.
1. It registers at the global AppDispatcher and listens for AppEvents.CHANGE .
2. It receive the new app-list-object with the AppEvents.CHANGE given as function argument.
3. It stores the new app-list-object into it's _own_ store.

Note: The plugin has _not_ access to the AppsStore, it receives the data through the dispatched event and stores it in it's own store. A plugin hasn't access to any function outside it's scope. It would be an anti-pattern to require the AppsStore in the plugin.

Particular example how it _could_ work with __emitting__:
Plugin wants to delete an app.
1. It dispatches a global event GlobalActions.DELETE_APP (naming has to be discussed), app parameters as payload.
2. This event will be handled in the main marathon ui and the according action is triggered then.

Note: The plugin has _not_ access to the AppsActions, it just dispatches the related event with the needed payload.

That means we need to expose our flux actions to global events that can be used by the plugins.
You can call it like this: The actions needs to be exported and switched to the plugin explicitly.

The __only__ way a plugin can __communicate__ is the __dispatcher__.

It's free to the plugin to implement it's own internal actions and stores.

This ensures integrity and maintenance.

### Plugin should be able to _inject components_
Based on the two rules above the plugin should be able to __inject__ its __component__(s) into other components application wide by emitting the component __through__ the global __dispatcher__.

Particular example how it _could_ work:
1. Plugin has a component
2. It dispatches this component maybe like this
[code]
```javascript
// PluginEvents.INJECT - componentToEmit, renderTargetsArray
emit(PluginEvents.INJECT, myComponentClass, [RenderPlaces.APP_PAGE_COMPONENT, RenderPlaces.TASK_LIST_COMPONENT])
```
[/code]
3. Render-targets could listen on a PluginStore for these events.
4. Then the render-targets, e.g. the AppPageComponent, injects this component dynamically into it's render-function.

With the same method we are able to change the state of a component with events.

### Plugin should live in it's _own namespace_

The plugin should have it's __own namespace__/scope and should __not__ be able to __access__ the __main marathon__ namespace.
The global dispatcher is passed as a parameter.

This ensures the first and second rule.

## _[Flowchart placholder]_

## Summary
Only 4 simple rules to follow.  Cool, heh?!

This would enable us to have a plugin interface that _we_ control. 
It's about integrity, maintainability, understandability and flexibility.

With the simple interface of having only a dispatcher, we can ensure integrity, maybe understandable documentation.
Plugins live on there own. Developer can decide how to implement the plugin, we don't care.
This means also that the plugins can be very maintainable. The Plugin-Events-API won't change that often I guess. This is very very important on the long run.
We can rename our actions, but the according events for the plugin api stay as they are! Yeah! :)

## Non-architectural thoughts
### Plugin helper
We could define a plugin helper class to simplify things, every plugin needs to derive from.
E.g. 
```javascript
emit(PluginEvents.INJECT, myComponentClass, [RenderPlaces.APP_PAGE_COMPONENT, RenderPlaces.TASK_LIST_COMPONENT])
```
becomes
```javascript
this.injectMe([RenderPlaces.APP_PAGE_COMPONENT, RenderPlaces.TASK_LIST_COMPONENT]);
```
and so on.

_[Real life example to follow]_

**Comment by orlandohohmeier** [comment]
@aldipower Thanks a ton! This is full of good ideas! I have a few questions, additions and comments:

## Simple (limited) Plugin Interface

I really like your approach to limit the plugin access as much as possible, as it improves maintainability and ensures that we can change stuff without breaking plugins. I'm not sure about the events for everything approach, yet... I like the simplicity but it also has some drawbacks. We should, for example, allow a few operation (replacing components, register routs) only at specific points in time (e.g. bootstrap) as the application state would otherwise become unpredictable but limiting events to a specific time kinda feels strange.

In any case our plugin interface (events or methods) should be simple (limited), stable (at least for the next 1/2 year), tested like crazy and documented. 

## Data Integrity 

Whatever we choose as our plugin interface (wordpress like methods, events or something else), we need to find ways to protect the application data, to ensure data integrity. Therefor every store needs to validate the data it receives (from the application dispatcher), should not provide any setter (as defined by Flux architecture pattern) and any data should be immutable. Same (kinda) is true for every component which potentially passes data to a plugin.

## Implementation 

I agree, that any plugin system we introduce will have a huge impact on our code base and we should really carefully evaluate possible designs. 
As it is nearly impossible to do everything right from the beginning, I would like to introduce such a system in very small iterations by limiting the plugin abilities to the absolute bare minimum for a very particular use case (e.g. an authentication dialog, or even only a simple banner).

## Isolation/namespacing

As long as the plugins live in the same frame as our application there is no complete/real isolation... Thinking about your event only system, I was wondering if it is possible to load plugins as workers to achieve real isolation (it even takes of data ownership). What do you think?

**Comment by orlandohohmeier** [comment]
In the pursuit of creating a safe, maintainable and robust plugin mechanism we considered all the great ideas and came up with the following plan:

## 4 simples rules 

As proposed plugins should follow these simples rules:

* Plugins should be extensions
* Plugins should be able to communicate
* Plugin should be able to inject components
* Plugin should live in it's own namespace

## Implementation 

We will focus on components (React) at the moment, as it is possible to implement most of the given use cases with them even though that could mean that a plugin is replicating functionality.

## PluginDispatcher

We will add an additional dispatcher (`PluginDispatcher`) which is used for plugin events and the only(!) way for plugins to communicate. 

## Events

Dedicated plugin events to registe/inject/mount (*we're still working on the wording*) components as well as getting notified about application state changes.

## Data Integrity 

Every store (subscribed to the `PluginDispatcher`) needs to validate all the data it receives, should not provide any setter (mesosphere/marathon#3011) and any data exposed should be immutable. The same rules apply for every component which potentially passes data to a plugin.

## Store all the plugins

We will add a store which stores all plugin components as well as their mount point (and order/priority) 

## Mount Point (*we're not happy with the wording and looking for better alternatives*)

Add a component to integrate/mount components provided by plugins. This component renders it's children at least every time the `PluginStore` sends a change event. It will also handle any exceptions throw by its children to ensure that the whole application break due to some buggy plugin.

## Marathon Plugins

We will extend the current Marathon Plugin mechanism to also provide Marathon UI Plugins. Marathon also needs to provide some additional metadata like the plugin order/priority as we need something to decide which plugin to use in case of an conflict (e.g. to plugins replacing the app list).

## Documentation/Example

We need to provide a really good documentation as well as an example

*/written in collaboration with @aldipower*
