### ISSUE TITLE
Show error icon for failing Mesos logs

### ISSUE THREAD

**Issue by leemunroe** [mesosphere/marathon#2844]
Related #2777 

![image](https://cloud.githubusercontent.com/assets/15963/11866013/7796b42c-a4a8-11e5-9172-419c6f93d5ad.png)

Icon available in `Marathon > Production > Components > Icons > icon-warning.svg`

**Comment by orlandohohmeier** [comment]
![](https://cloud.githubusercontent.com/assets/647035/11902518/bca77dc0-a5b2-11e5-8f7a-a1e504286a00.png)
@leemunroe There seem to be a view box/position issue with that icon.

**Comment by leemunroe** [comment]
@orlandohohmeier Sorry about that, forgot to vectorize the stroke. Updated.
