### ISSUE TITLE
Provision to start group of applications on same Mesos slave

### ISSUE THREAD

**Issue by suyash1983** [mesosphere/marathon#2846]
I have cluster of 3 Mesos slaves, where I have two applications: “A” and “B”. Where A depends on B and the requirement is both of the applications/services should start on same node instead of different slave nodes.

So I have created the application group and added the dependency properly in the JSON file. After launching the JSON file via “v2/groups” REST API, I observe that sometime both application group will start on same node but sometimes it will start on different slaves which breaks our requirement.

So intent/requirement is; if any application fails to start on a slave both the application should failover to other slave node. Also can I configure the JSON file to tell Marathon to start the application group on slave-1 (specific slave first) if it is available else start it on other slave in a cluster. Due to some reason if this application group will start on other slave can Marathon relaunch the application group to slave-1 if it is available to serve the request.

Thanks in advance for help.

**Comment by suyash1983** [comment]
Some where I found:

```
Marathon application groups don't have any semantics concerning co-location on the same node and the same is the case for dependencies.

You seem to be looking for a Kubernetes like Pod abstraction in marathon, which is on the roadmap but not yet available.
```

**Comment by veerals123** [comment]
I am facing similar situation. In a multi process application, all the individual processes need to be monitored and should fail over together as a group (in case a slave node where the app is running goes down). Its the most basic requirement. How does one achieve this with Mesos-marathon? Are there any known tricks?

**Comment by aquamatthias** [comment]
Duplicate #894

**Comment by junneyang** [comment]
any update on how this could be achieved as of current versions ?
Thanks
