### ISSUE TITLE
Marathon 0.13 compatible with Mesos 0.26.0?

### ISSUE THREAD

**Issue by mindscratch** [mesosphere/marathon#2848]
Mesos 0.26.0 was recently released, any idea if it is compatible with Marathon 0.13.0?

Based on the [upgrade](http://mesos.apache.org/documentation/latest/upgrades/) instructions it seems like it probably should, though it mentions some "compile time adjustments" might be required.

**Comment by mindscratch** [comment]
I've tested mesos 0.26.0 with marathon 0.13.0, everything seems to be fine.

**Comment by shafay2000** [comment]
I can also validate that mesos-0.26.0-0.2.145.centos701406.x86_64 & marathon-0.13.0-1.0.440.el7.x86_64 work wonderfully together. Make sure you have upto date patches, else you will see SASL auth issues.

**Comment by scalp42** [comment]
@mindscratch unfortunately, we're not seeing that, see: https://github.com/mesosphere/marathon/issues/2870

They changed something related to tasks IPs with Docker containers.

**Comment by gkleiman** [comment]
@scalp42 Marathon v0.13.0 doesn't use the IP address in NetworkInfo for health checks, so it should still be compatible with Mesos 0.26.0.
