### ISSUE TITLE
Update docs to use marathon-lb

### ISSUE THREAD

**Issue by ssk2** [mesosphere/marathon#2854]
These docs (https://mesosphere.github.io/marathon/docs/service-discovery-load-balancing.html) don't mention the new marathon-lb project.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3045. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3045. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
