### ISSUE TITLE
Make filters work like label / status selectors

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#2861]
Selecting some filters on the left triggers fancy listing where apps are shown in a flat list:

![image](https://cloud.githubusercontent.com/assets/89186/11900887/4efd93e8-a5a0-11e5-8aa8-4cbfcf9241a3.png)

On the other side, filters don't do that:

![image](https://cloud.githubusercontent.com/assets/89186/11900900/61cd60d4-a5a0-11e5-9b08-65bc91902dd9.png)

I think we should be consistent here and make flat lists everywhere where some filtering is involved.

Another issue: filters do not work when you select something on the left panel.

**Comment by pierlo-upitup** [comment]
Hi @bobrik, just to clarify: searching is now a Global search, which means you are not filtering your apps from within the current group, but always searching across **all** groups.
Sidebar facets, on the other hands, filter down the current list of apps (ie within the current group or the current set of results). 

Regarding the last line: can you explain the situation in detail?

**Comment by bobrik** [comment]
@pierlo-upitup 

1. Select some filter with apps on the left (`Running` / `Suspended`)
2. Enter garbage in filter box: `dfg;s eb;gbejf bglejkfbh;eosrg` works for me
3. Observe apps that in the list:

![image](https://cloud.githubusercontent.com/assets/89186/11901042/51e728ac-a5a1-11e5-892a-0d8b68c278c4.png)

I believe filter should still apply here.

**Comment by pierlo-upitup** [comment]
To understand: did you Submit the search? Please note, since we switched to Global Search, the input field does not behave like a real-time filter anymore and you need to hit enter / click the submit icon.

**Comment by bobrik** [comment]
I didn't submit. Looks like the whole issue is "filter requires submit". It was counter-intuitive for me.

**Comment by pierlo-upitup** [comment]
Thanks for the feedback! We'll think of ways to communicate the interaction more clearly
cc @leemunroe 

Closing the issue.

**Comment by bobrik** [comment]
@pierlo-upitup I'll be happy to subscribe to the issue about search without submitting, if you have one :)
