### ISSUE TITLE
Listing Docker Containers and Networking on Mesos/Marathon

### ISSUE THREAD

**Issue by imesh** [mesosphere/marathon#2864]
I understand the basic concepts of running a Docker container on Mesos with [this](http://mesos.apache.org/documentation/latest/docker-containerizer/) and [this](https://open.mesosphere.com/advanced-course/deploying-a-web-app-using-docker/) as an Marathon application. I have two questions:

1. Does Mesos/Marathon has a REST API to list Docker containers started by a Marathon application? I went through [REST API reference](https://mesosphere.github.io/marathon/docs/rest-api.html) but could not find a way to do this. What I'm looking for is the IP addresses of the Docker containers within the Mesos cluster/network.

2. Does Mesos provide a [Flannel](https://github.com/coreos/flannel) like SDN for Docker or is it just local IP addresses containers would get for each Mesos slave? I checked [this](https://mesosphere.github.io/marathon/docs/native-docker.html) but could not figure this out.

Many Thanks!

**Comment by gkleiman** [comment]
> 1. Does Mesos/Marathon has a REST API to list Docker containers started by a Marathon application? I went through REST API reference but could not find a way to do this. What I'm looking for is the IP addresses of the Docker containers within the Mesos cluster/network.

Check the [/v2/apps/{appId}/tasks](https://mesosphere.github.io/marathon/docs/rest-api.html#get-v2-apps-appid-tasks) endpoint, it returns exactly what you need.

> 2. Does Mesos provide a Flannel like SDN for Docker or is it just local IP addresses containers would get for each Mesos slave? I checked this but could not figure this out.

Marathon v0.14.0-RC1 introduces [experimental ip-per-task support](https://github.com/mesosphere/marathon/blob/c73062837db886e74f84f03f18aefe1f3419e519/docs/docs/ip-per-task.md), but not for Docker containers.

I don't know about Flannel, but it seems like it is possible to get Weave to work with Mesos + Marathon: http://weave.works/guides/platform/mesos-marathon/os/centos/cloud/vagrant/

As a side-note, the [marathon-framework Google Group](https://groups.google.com/forum/#!forum/marathon-framework) is a better place to post this kind of questions. We prefer to use GitHub for bug reports and feature requests.

**Comment by imesh** [comment]
Thanks @gkleiman for your quick response!
