### ISSUE TITLE
[Question] Marathon resources role behavior

### ISSUE THREAD

**Issue by fengyuleidian0615** [mesosphere/marathon#2871]
I'm trying to understand marathon resource role behavior by experimenting with following config.
slave1: set with default_role as "busybox"
slave2: set with default_role as "ubuntu"
master: marathon-0.13.0-1.0.440.el7.x86_64

Test1: 
- Start marathon with default config(no explicitly set /etc/marathon/conf/mesos_role)
- Add acceptedResourcesRoles to "busybox" for busybox.json to launch as app1
- At the same time, run a "ubuntu" version as app2.
by my understanding, app1 will go to slave1 and app2 will go to slave2, but both app1 and app2 will not run actually.

Test2: 
- Start marathon with default config(set /etc/marathon/conf/mesos_role to busybox)
- Add acceptedResourcesRoles to "busybox" for busybox.json to launch as app1
- At the same time, run a "ubuntu" version as app2.
app1 goes to slave1 eventually as expected, while app2 still not running;
swtich mesos_role to "ubuntu" and restart marathon, app2 will go to slave2, whileas app1 will not running.

Is above behavior by design or I'm mis-configured somewhere?
My understanding is: marathon will not bound with any particular role, it will schedule application with defined role to the corresponding resources, but from the test it's opposite.

thanks!

**Comment by gkleiman** [comment]
Until [MESOS-1763](https://issues.apache.org/jira/browse/MESOS-1763) is fixed, Marathon can register to Mesos using just one role.

You might be able to achieve what you're trying to do using Mesos Agent Attributes and Marathon Constraints.

**Comment by fengyuleidian0615** [comment]
@gkleiman dunk!
