### ISSUE TITLE
Allow scaling an application automatically based on scaling policy

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#2875]
Instead of defining an instance count, define some criteria to scale an application automatically.
Different policies should be implemented, so that users can define the appropriate set needed for their application. 

The first policy to implement should be based on the mesos slave count.
This policy select all slaves in the cluster, that match the defined constraints of an application and takes that as instance count. Whenever the slaves change, the instance count is changed accordingly.

**Comment by wendigo** [comment]
Hi @aquamatthias! Can you make it pluggable from the beggining? :) Auto-scaling can be based on multiple signal sources: current utilization, history of utilization, quick changes in traffic, predictions etc. Making it pluggable will allow for more generic implementations.

**Comment by aquamatthias** [comment]
@wendigo definitively. The plan is to create this as a pluggable interface.

**Comment by xiaods** [comment]
pluggable interface， how to archive it? where is found the design doc?

**Comment by aquamatthias** [comment]
Hey @xiaods look here: https://mesosphere.github.io/marathon/docs/plugin.html.
There is currently no plugin interface for auto scaling - it is part of that story.

**Comment by jdef** [comment]
is the API for this going to be pluggable as well? for example (assuming this is baked into the app API):

```json
/*app*/ {
  "id": "log-shipper",
  "cmd": "run-fluentd.sh"
  ...
  "plugins": [
    {
      "kind": "policy/scale",
      "id": "log-shipper-scaling",
      "provider": "daemonScaler"
    }
  ]
}
```

```json
/*app*/ {
  "id": "my-webapp",
  "cmd": "run-app.sh"
  ...
  "plugins": [
    {
      "kind": "policy/scale",
      "id": "webapp-scaling",
      "provider": "horizontalScaler",
      "spec": { /* spec parsed by horizontalScaler plugin */
        "targetUtilization": {
          "cpu": 80.0 /* percentage */
        }
      }
    }
  ]
}
```

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3108. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3108. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
