### ISSUE TITLE
Marathon v0.14.0 events buggy

### ISSUE THREAD

**Issue by scalp42** [mesosphere/marathon#2878]
I noticed that Marathon is not sending some the events.

Pretty much attach 3 clients to the events endpoint, some won't get anything.

Sorry for the capture but it's the best I could do to describe:

![](https://i.imgur.com/PqkMJY8.png)

- top left corner is straight up sseclient in python
- top right corner is using httpie to connect to it (and you can see is getting more events than the others)
- bottom is marathon-lb

**Comment by scalp42** [comment]
Even if I interrupt and try again to connect to the events endpoints with httpie, the other listeners are not getting anything (they should be getting at the very minimum an `event_stream_attached` when doing this:

![](https://i.imgur.com/TuHVla5.png)

**Comment by scalp42** [comment]
You can see all 3 clients getting differents answers now (I think some are completely lagging behind):

![](https://i.imgur.com/HULdvd7.png)

**Comment by scalp42** [comment]
Marathon v0.13.0 appears to have the same issue.

We downgraded to 0.11.0 and all are getting the events correctly and all synced.

**Comment by scalp42** [comment]
To follow up, we upgraded back to Marathon 0.14.0 RC1 and we switched to using callbacks instead.

but I can confirm sse events are not working correctly.

**Comment by scalp42** [comment]
Clicked the wrong button.

**Comment by aquamatthias** [comment]
Hey @scalp42 I tested this on Marathon 0.14.0-RC1.
- 3 Marathon Masters with 7 mesos slaves
- 8 Listener started via <br/> `httpie (http --stream http://marathon.leader:8080/v2/events "Accept: text/event-stream"`
- 1 python simple SSEClient 
- started listeners in a loop which will create 10 Accept/Remove Handler events every 5 seconds <br/>
  `while true; do ab -c 10 -n 10 -t 5 -s 1 -H "Accept: text/event-stream" http://marathon.leader:8080/v2/events ; sleep 5; done`
- started some apps with failing health checks which will create some standard Marathon Events

Let that setup run for more than 2 hours, which generated ca 16000 events.
I see the same events on all listeners.
I see every event almost simultaneously on every listener. 

There are some points that come to mind:
- do you connect directly to Marathon or do you use a proxy? 
- it looks like you connect not directly to the leading master. Can you try to connect to the leading master?
- events are dropped, if the client is slow (slow consumer or slow network). Please look into the Marathon logs for `Ignore event {} for handle {} (slow consumer)`
- how many resources are assigned to Marathon (CPU, Memory)? Is there a high load on that machine?

I can not reproduce the problem. 
Please try to narrow down the problem space. 
Please provide logs.

**Comment by scalp42** [comment]
The only difference I can see is that I was not connecting to the Marathon leader directly (just picking whatever Marathon node in RR DNS).

There was no load issues (master were idle with 0-1 tasks on slaves).

Do we actually have to connect to the leader ?

Unfortunately, I'm using callbacks right now and would need to spin up a new cluster, which would take some time, so can't give ETA right now.

**Comment by aquamatthias** [comment]
The leader proxy will always connect to the the leading master. To not have another hop and to rule out the leader proxy (or any other proxy in between), I would recommend to always connect to the leading master (GET /v2/leader).

**Comment by aquamatthias** [comment]
Can not reproduce. Please reopen if you can reproduce the problem.

**Comment by scalp42** [comment]
@aquamatthias I'd like to reopen the issue.

We're not using latest Marathon `0.14.0` and Mesos `0.26.0` and SSE events are not working for us.

**Comment by aquamatthias** [comment]
@scalp42 reopened. Please see my last comment - how can I reproduce the problem?

**Comment by scalp42** [comment]
I'm trying to figure if its related to https://github.com/mesosphere/marathon-lb/issues/35. I do see events but they're "lagging" behind.

I'll try again today with your same setup.

**Comment by scalp42** [comment]
So I tested using your loop and it appears to work I'll admit besides:

```
Jan 21 19:22:20 mesos-master-i-227cb2e5 marathon[11548]: [2016-01-21 19:22:20,422] INFO Received EOF from stream handle HttpEventSSEHandle(b86ddfc6-1495-4fc0-87b5-2744b8aa2335 on 10.52.42.244). Ignore subsequent events. (mesosphere.marathon.event.http.HttpEventStreamHandleActor:marathon-akka.actor.default-dispatcher-49)
Jan 21 19:22:20 mesos-master-i-227cb2e5 marathon[11548]: [2016-01-21 19:22:20,422] INFO Received EOF from stream handle HttpEventSSEHandle(576f0135-a748-4bd3-b8ec-7103b75eb4c5 on 10.52.42.244). Ignore subsequent events. (mesosphere.marathon.event.http.HttpEventStreamHandleActor:marathon-akka.actor.default-dispatcher-49)
Jan 21 19:22:20 mesos-master-i-227cb2e5 marathon[11548]: [2016-01-21 19:22:20,422] INFO Received EOF from stream handle HttpEventSSEHandle(81a4b559-8034-42bd-a1d7-b15b7726ce5a on 10.52.42.244). Ignore subsequent events. (mesosphere.marathon.event.http.HttpEventStreamHandleActor:marathon-akka.actor.default-dispatcher-49)
Jan 21 19:22:20 mesos-master-i-227cb2e5 marathon[11548]: [2016-01-21 19:22:20,422] INFO Received EOF from stream handle HttpEventSSEHandle(f94a7169-a2c0-4a3e-a9d5-3e9b4cfa1f47 on 10.52.42.244). Ignore subsequent events. (mesosphere.marathon.event.http.HttpEventStreamHandleActor:marathon-akka.actor.default-dispatcher-49)
Jan 21 19:22:20 mesos-master-i-227cb2e5 marathon[11548]: [2016-01-21 19:22:20,422] INFO Received EOF from stream handle HttpEventSSEHandle(953218eb-e380-46e1-b620-2cdac8944d7a on 10.52.42.244). Ignore subsequent events. (mesosphere.marathon.event.http.HttpEventStreamHandleActor:marathon-akka.actor.default-dispatcher-49)
Jan 21 19:22:20 mesos-master-i-227cb2e5 marathon[11548]: [2016-01-21 19:22:20,422] INFO Received EOF from stream handle HttpEventSSEHandle(38537935-d142-4aef-90c9-9268997be464 on 10.52.42.244). Ignore subsequent events. (mesosphere.marathon.event.http.HttpEventStreamHandleActor:marathon-akka.actor.default-dispatcher-49)
Jan 21 19:22:20 mesos-master-i-227cb2e5 marathon[11548]: [2016-01-21 19:22:20,422] INFO Received EOF from stream handle HttpEventSSEHandle(c17a18d0-f25b-4088-ba43-88d386770fa2 on 10.52.42.244). Ignore subsequent events. (mesosphere.marathon.event.http.HttpEventStreamHandleActor:marathon-akka.actor.default-dispatcher-49)
Jan 21 19:22:20 mesos-master-i-227cb2e5 marathon[11548]: [2016-01-21 19:22:20,422] INFO Received EOF from stream handle HttpEventSSEHandle(4383c208-9b00-46f2-8709-4ab2cf661837 on 10.52.42.244). Ignore subsequent events. (mesosphere.marathon.event.http.HttpEventStreamHandleActor:marathon-akka.actor.default-dispatcher-49)
Jan 21 19:22:20 mesos-master-i-227cb2e5 marathon[11548]: [2016-01-21 19:22:20,423] INFO Received EOF from stream handle HttpEventSSEHandle(726d6246-773a-4707-bcfe-cd36ce19136b on 10.52.42.244). Ignore subsequent events. (mesosphere.marathon.event.http.HttpEventStreamHandleActor:marathon-akka.actor.default-dispatcher-57)
Jan 21 19:22:20 mesos-master-i-227cb2e5 marathon[11548]: [2016-01-21 19:22:20,425] INFO Received EOF from stream handle HttpEventSSEHandle(576f0135-a748-4bd3-b8ec-7103b75eb4c5 on 10.52.42.244). Ignore subsequent events. (mesosphere.marathon.event.http.HttpEventStreamHandleActor:marathon-akka.actor.default-dispatcher-57)
```

I'm going to assume it's on the marathon-lb side then.
