### ISSUE TITLE
what does the "cpus" mean ?

### ISSUE THREAD

**Issue by gudeyang1** [mesosphere/marathon#2881]
hello,i'm confused by    "cpus": 0.2,  in the json file ,  what does that mean ? is it means the container can only use 0.2 cpu ,if i have 1 cpu, that means 20% ?    but according to the test,marathon can't limit the use percent  of a container,  the test is like that , i have 32 cpus ,"docker stats" shows the container use 200-300% cpu,but i only give 0.2 cpu ,what's the matter? 

and sorry for my bad english!

**Comment by kamilchm** [comment]
http://theza.ch/2014/09/17/cpu-resources-in-docker-mesos-and-marathon/

**Comment by gudeyang1** [comment]
@kamilchm thanks a lot ,this is whta i'm looking for
