### ISSUE TITLE
Possible licensing / redistribution issue with marathon

### ISSUE THREAD

**Issue by SEJeff** [mesosphere/marathon#2883]
Mararhon is Apache 2 licensed and logback is LGPL 2 licensed. Per [Apache](http://www.apache.org/licenses/GPL-compatibility.html) they mention that it is GPLv3 compatible and GPLv2 incompatible. The FSF also agrees with this statement. Does this mean that there is technically a licensing violation in Marathon?

**Comment by gkleiman** [comment]
@SEJeff thanks for opening the issue. logback is dual-licensed under the EPL v1.0 and the LGPL 2.

Marathon is using logback under the EPL v1.0, which should be compatible with the Apache License v2.0.

**Comment by SEJeff** [comment]
Perfect and thanks
