### ISSUE TITLE
How to remove existed container ?

### ISSUE THREAD

**Issue by VFT** [mesosphere/marathon#2884]
Containers will be removed after existing with state of mesos task is `FINISHED` if i add `Parameters key=rm value=true`,but if i destroy the app and the state of mesos task is `KILLED`,it can't be removed,how to do?

**Comment by gkleiman** [comment]
@VFT container creation/removal is handled by the Mesos Agents, not by Marathon.

You can configure the amount of time to wait before removing Docker containers through the Mesos Agent's `--docker_remove_delay` flag. See http://mesos.apache.org/documentation/latest/configuration/ for a list of all the available flags. If you are not using Docker, then you can configure the maximum amount of time to wait before cleaning up executor directories through the `--gc_delay` flag.

If your Mesos Agents already have too many stopped Docker containers, you can remove them manually using the Docker command. See the following page for a cheat sheet with useful Docker cleanup commands: https://www.calazan.com/docker-cleanup-commands/

**Comment by mkgong** [comment]
Does GC process suppose cleanup old docker images as well?  
In my case,  GC process deleted exited containers file under /var/mesos/meta/slaves and /var/mesos/slaves.  But it didn't remove docker images that under /ephemeral/docker/devicemapper/devicemapper/data and /ephemeral/docker/devicemapper/devicemapper/metadata.

**Comment by timrichd** [comment]
I'd also like to know how to remove the docker images from my mesos cluster

**Comment by janisz** [comment]
Duplicates: https://github.com/mesosphere/marathon/issues/4967
