### ISSUE TITLE
Unable to change marathon port

### ISSUE THREAD

**Issue by CMTHM** [mesosphere/marathon#2885]
sudo ./bin/start --master local --zk zk://10.20.8.106:2181/marathon --http_port=7070 to change the port .
But it's not working 
[scallop] Error: Unknown option 'http_port=7070'
I am accessing ubuntu through putty 
Is it necessary to  give IP address of ubuntu machine instead of "local"?

**Comment by gkleiman** [comment]
The flag name and the value have to be separated by a space, not by an equals sign.

Please try with `--http_port 7070` instead of `--http_port=7070` and re-open the issue if it doesn't work.

Happy New Year!
