### ISSUE TITLE
Unable to create new Apps

### ISSUE THREAD

**Issue by JoachimAndersson** [mesosphere/marathon#2886]
Version 0.13.0
Mesos version 0.25 same with 0.26
When doing v2/apps

with the example 

{
  "id": "/tools/docker/registry",
  "instances": 1,
  "cpus": 0.5,
  "mem": 4096,
  "disk": 0,
  "executor": "",
  "constraints": [],
  "uris": [],
  "storeUrls": [],
  "ports": [
    5000
  ],
  "requirePorts": false,
  "backoffSeconds": 1,
  "backoffFactor": 1.15,
  "maxLaunchDelaySeconds": 3600,
  "container": {
    "type": "DOCKER",
    "volumes": [
      {
        "containerPath": "/docker_storage",
        "hostPath": "/hdd/tools/docker/registry",
        "mode": "RW"
      }
    ],
    "docker": {
      "image": "registry",
      "network": "BRIDGE",
      "portMappings": [
        {
          "containerPort": 5000,
          "hostPort": 0,
          "servicePort": 5000,
          "protocol": "tcp"
        }
      ],
      "privileged": false,
      "parameters": [],
      "forcePullImage": false
    }
  },
  "healthChecks": [],
  "dependencies": [],
  "upgradeStrategy": {
    "minimumHealthCapacity": 1,
    "maximumOverCapacity": 1
  },
  "version": "2015-08-19T21:26:47.616Z"
}

i Get the following Error

<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
        <title>Error 500 </title>
    </head>
    <body>
        <h2>HTTP ERROR: 500</h2>
        <p>Problem accessing /v2/apps. Reason:

            <pre>    javax.servlet.ServletException: java.lang.NoClassDefFoundError: Could not initialize class mesosphere.marathon.api.v2.BeanValidation$</pre>
        </p>
        <hr />
        <a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.z-SNAPSHOT</a>
        <hr/>
    </body>
</html>

**Comment by JoachimAndersson** [comment]
Latest Version of the Java 9-EA was the problem, downgraded to java 8 latest.

**Comment by aquamatthias** [comment]
@JoachimAndersson which distribution do you use?
@sascala This looks like a documentation problem. Can you compare with mesosphere.io/downloads?

**Comment by JoachimAndersson** [comment]
Linux slave5-mesos 3.19.0-42-generic #48~14.04.1-Ubuntu SMP

**Comment by crazyadventures** [comment]
Can echo same observation.

Mesos 0.26 and Marathon 0.13 running on Ubuntu trusty 14.04.3 LTS.

Java alternative set to /usr/lib/jvm/java-9-oracle/bin/java

Have also tried setting Java alternative to /usr/lib/jvm-7-openjdk-amd64/jre/bin/java   OR /usr/lib/java-7-oracle/jre/bin/java and rebooting.

Both marathon and mesos were working previously (issues occurred after upgrading from Marathon 0.8 and Mesos 0.21 (I think they were version numbers previously installed and working)

**Comment by aquamatthias** [comment]
I retested this very example and could create the application.
Please use java 8 (__not__ java7 __not__ java9).

**Comment by crazyadventures** [comment]
"Downgraded" to Java8 - confirmed working now - thanks :+1:

**Comment by aquamatthias** [comment]
Thanks for reporting this!
