### ISSUE TITLE
Marathon SSL documentation inaccurate

### ISSUE THREAD

**Issue by ghilios** [mesosphere/marathon#2889]
If MARATHON_JKS_PASSWORD and MARATHON_KEY_PASSWORD are not identical (and equal to that provided by --ssl_keystore_password), then Marathon fails to load the key from the keystore provided by --ssl_keystore_path

**Comment by kevincox** [comment]
:+1:

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3159. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3159. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
