### ISSUE TITLE
Marathon failed to deploy a Docker image on 1.91 with v1.21 API

### ISSUE THREAD

**Issue by alfredcs** [mesosphere/marathon#2897]
The Cassandra docker image had been successfully deployed  using Docker (1.9.1 with v1.21 API ) CLI. However using Marathon ( 0.13.0-1.0.440.ubuntu1504 ) with Mesos (0.25.0-0.2.70.ubuntu1504) to deploy the same image failed with following json file.

{
              "id": "/cass31/seed",
              "ports": [7199, 7000, 7001, 9160, 9042],
              "container": {
                  "type": "DOCKER",
                  "docker": {
                      "image": "cass31",
                      "network": "BRIDGE",
                      "portMappings": [
                        { "containerPort": 9160, "hostPort": 0, "servicePort": 9160, "protocol": "tcp" },
                        { "containerPort": 7199, "hostPort": 0, "servicePort": 7199, "protocol": "tcp" },
                        { "containerPort": 7000, "hostPort": 0, "servicePort": 7000, "protocol": "tcp" },
                        { "containerPort": 7001, "hostPort": 0, "servicePort": 7001, "protocol": "tcp" },
                        { "containerPort": 9042, "hostPort": 0, "servicePort": 9042, "protocol": "tcp" }
                      ]
                  },
                  "volumes": [
                        {  "containerPath": "/var/log/cassandra", "hostPath": "/var/mesos-slaves/cass3/mesos-s5u/log", "mode": "RW" },
                        {  "containerPath": "/var/lib/cassandra", "hostPath": "/var/mesos-slaves/cass3/mesos-s5u/data", "mode": "RW" }
                  ]
              },
              "env": {
                  "CASSANDRA_SEEDS": "cass3.seed.marathon.mesos"
              },
              "constraints": [["os", "LIKE", "ubuntu"],["rack_id", "LIKE", "rack-1"],  ["hostname", "UNIQUE"]],
              "instances": 1
}
 

The mesos-slave show following logs:

Jan  4 22:39:29 ip-10-0-10-178 mesos-slave[749]: I0104 22:39:29.657234  1020 slave.cpp:1270] Got assigned task cass31_seed.044db17a-b334-11e5-be35-ee075baf725b for framework 5a807714-6b43-4e14-9dfb-5bb83e33f691-0000
Jan  4 22:39:29 ip-10-0-10-178 mesos-slave[749]: I0104 22:39:29.657582  1020 slave.cpp:1386] Launching task cass31_seed.044db17a-b334-11e5-be35-ee075baf725b for framework 5a807714-6b43-4e14-9dfb-5bb83e33f691-0000
Jan  4 22:39:29 ip-10-0-10-178 mesos-slave[749]: I0104 22:39:29.663460  1020 slave.cpp:4852] Launching executor cass31_seed.044db17a-b334-11e5-be35-ee075baf725b of framework 5a807714-6b43-4e14-9dfb-5bb83e33f691-0000 with resources cpus(*):0.1; mem(*):32 in work directory '/tmp/mesos/slaves/91bc5e66-c065-47d9-a218-28e7a66acd96-S8/frameworks/5a807714-6b43-4e14-9dfb-5bb83e33f691-0000/executors/cass31_seed.044db17a-b334-11e5-be35-ee075baf725b/runs/1ccce7d8-8d7c-4edb-8afd-122c9ebb8867'
Jan  4 22:39:29 ip-10-0-10-178 mesos-slave[749]: I0104 22:39:29.663936  1020 slave.cpp:1604] Queuing task 'cass31_seed.044db17a-b334-11e5-be35-ee075baf725b' for executor cass31_seed.044db17a-b334-11e5-be35-ee075baf725b of framework '5a807714-6b43-4e14-9dfb-5bb83e33f691-0000
Jan  4 22:39:29 ip-10-0-10-178 mesos-slave[749]: I0104 22:39:29.669472  1005 docker.cpp:761] Starting container '1ccce7d8-8d7c-4edb-8afd-122c9ebb8867' for task 'cass31_seed.044db17a-b334-11e5-be35-ee075baf725b' (and executor 'cass31_seed.044db17a-b334-11e5-be35-ee075baf725b') of framework '5a807714-6b43-4e14-9dfb-5bb83e33f691-0000'

Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.708575625Z" level=debug msg="Calling GET /v1.21/containers/cass31:latest/json"
Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.708610142Z" level=info msg="GET /v1.21/containers/cass31:latest/json"
Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.708752882Z" level=error msg="Handler for GET /v1.21/containers/cass31:latest/json returned error: no such id: cass31:latest"
Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.708779900Z" level=error msg="HTTP Error" err="no such id: cass31:latest" statusCode=404
Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.709059246Z" level=debug msg="Calling GET /v1.21/images/cass31:latest/json"
Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.709083615Z" level=info msg="GET /v1.21/images/cass31:latest/json"
Jan  4 22:39:29 ip-10-0-10-178 mesos-slave[749]: I0104 22:39:29.782827  1012 docker.cpp:385] Checkpointing pid 2500 to '/tmp/mesos/meta/slaves/91bc5e66-c065-47d9-a218-28e7a66acd96-S8/frameworks/5a807714-6b43-4e14-9dfb-5bb83e33f691-0000/executors/cass31_seed.044db17a-b334-11e5-be35-ee075baf725b/runs/1ccce7d8-8d7c-4edb-8afd-122c9ebb8867/pids/forked.pid'

Jan  4 22:39:29 ip-10-0-10-178 mesos-slave[749]: I0104 22:39:29.803808  1008 slave.cpp:2379] Got registration for executor 'cass31_seed.044db17a-b334-11e5-be35-ee075baf725b' of framework 5a807714-6b43-4e14-9dfb-5bb83e33f691-0000 from executor(1)@10.0.10.178:42902
Jan  4 22:39:29 ip-10-0-10-178 mesos-slave[749]: I0104 22:39:29.804414  1008 docker.cpp:1016] Ignoring updating container '1ccce7d8-8d7c-4edb-8afd-122c9ebb8867' with resources passed to update is identical to existing resources
Jan  4 22:39:29 ip-10-0-10-178 mesos-slave[749]: I0104 22:39:29.804574  1008 slave.cpp:1760] Sending queued task 'cass31_seed.044db17a-b334-11e5-be35-ee075baf725b' to executor 'cass31_seed.044db17a-b334-11e5-be35-ee075baf725b' of framework 5a807714-6b43-4e14-9dfb-5bb83e33f691-0000
Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.846109988Z" level=debug msg="Calling POST /v1.21/containers/create"
Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.846160958Z" level=info msg="POST /v1.21/containers/create?name=mesos-91bc5e66-c065-47d9-a218-28e7a66acd96-S8.1ccce7d8-8d7c-4edb-8afd-122c9ebb8867"
Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.848934454Z" level=debug msg="Calling GET /v1.21/containers/mesos-91bc5e66-c065-47d9-a218-28e7a66acd96-S8.1ccce7d8-8d7c-4edb-8afd-122c9ebb8867/json"
Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.848964166Z" level=info msg="GET /v1.21/containers/mesos-91bc5e66-c065-47d9-a218-28e7a66acd96-S8.1ccce7d8-8d7c-4edb-8afd-122c9ebb8867/json"
Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.860255882Z" level=error msg="Handler for GET /v1.21/containers/mesos-91bc5e66-c065-47d9-a218-28e7a66acd96-S8.1ccce7d8-8d7c-4edb-8afd-122c9ebb8867/json returned error: no such id: mesos-91bc5e66-c065-47d9-a218-28e7a66acd96-S8.1ccce7d8-8d7c-4edb-8afd-122c9ebb8867"
Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.860301505Z" level=error msg="HTTP Error" err="no such id: mesos-91bc5e66-c065-47d9-a218-28e7a66acd96-S8.1ccce7d8-8d7c-4edb-8afd-122c9ebb8867" statusCode=404
Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.861447990Z" level=debug msg="Calling GET /v1.21/images/mesos-91bc5e66-c065-47d9-a218-28e7a66acd96-S8.1ccce7d8-8d7c-4edb-8afd-122c9ebb8867/json"
Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.861476317Z" level=info msg="GET /v1.21/images/mesos-91bc5e66-c065-47d9-a218-28e7a66acd96-S8.1ccce7d8-8d7c-4edb-8afd-122c9ebb8867/json"
Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.861659397Z" level=error msg="Handler for GET /v1.21/images/mesos-91bc5e66-c065-47d9-a218-28e7a66acd96-S8.1ccce7d8-8d7c-4edb-8afd-122c9ebb8867/json returned error: No such image: mesos-91bc5e66-c065-47d9-a218-28e7a66acd96-S8.1ccce7d8-8d7c-4edb-8afd-122c9ebb8867"
Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.861697871Z" level=error msg="HTTP Error" err="No such image: mesos-91bc5e66-c065-47d9-a218-28e7a66acd96-S8.1ccce7d8-8d7c-4edb-8afd-122c9ebb8867" statusCode=404
Jan  4 22:39:29 ip-10-0-10-178 kernel: [1478744.276437] aufs au_opts_verify:1597:docker[24924]: dirperm1 breaks the protection by the permission bits on the lower branch

Jan  4 22:39:29 ip-10-0-10-178 kernel: [1478744.298842] aufs au_opts_verify:1597:docker[25563]: dirperm1 breaks the protection by the permission bits on the lower branch
Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.911734427Z" level=debug msg="Calling POST /v1.21/containers/e7fb2f0e3b90733b2947f4b446c42135faa242f31138c436ade2b5970f533f39/attach"
Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.911767618Z" level=info msg="POST /v1.21/containers/e7fb2f0e3b90733b2947f4b446c42135faa242f31138c436ade2b5970f533f39/attach?stderr=1&stdout=1&stream=1"
Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.911840299Z" level=debug msg="attach: stdout: begin"
Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.911871919Z" level=debug msg="attach: stderr: begin"
Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.912368002Z" level=debug msg="Calling POST /v1.21/containers/e7fb2f0e3b90733b2947f4b446c42135faa242f31138c436ade2b5970f533f39/start"
Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.912405086Z" level=info msg="POST /v1.21/containers/e7fb2f0e3b90733b2947f4b446c42135faa242f31138c436ade2b5970f533f39/start"
Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.913829004Z" level=debug msg="Assigning addresses for endpoint mesos-91bc5e66-c065-47d9-a218-28e7a66acd96-S8.1ccce7d8-8d7c-4edb-8afd-122c9ebb8867's interface on network bridge"
Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.913860471Z" level=debug msg="RequestAddress(LocalDefault/172.17.0.0/16, <nil>, map[])"
Jan  4 22:39:29 ip-10-0-10-178 docker[24766]: time="2016-01-04T22:39:29.916263813Z" level=debug msg="/sbin/iptables, [--wait -t nat -A DOCKER -p tcp -d 0/0 --dport 31667 -j DNAT --to-destination 172.17.0.2:9042 ! -i docker0]"
Jan  4 22:39:29 ip-10-0-10-178 systemd-udevd[2523]: Could not generate persistent MAC address for vethf4e6629: No such file or directory
Jan  4 22:39:29 ip-10-0-10-178 kernel: [1478744.328753] aufs au_opts_verify:1597:docker[24924]: dirperm1 breaks the protection by the permission bits on the lower branch
Jan  4 22:39:29 ip-10-0-10-178 kernel: [1478744.331062] device vethf4e6629 entered promiscuous mode
Jan  4 22:39:29 ip-10-0-10-178 kernel: [1478744.331330] IPv6: ADDRCONF(NETDEV_UP): vethf4e6629: link is not ready

The logs seem to contain a few notable issues:

1) Why did Mesos try to query Docker API for images but using incorrect container URI and to query container info but using image URI?

2) Should there be a delay after POST and before next GET for the newly created container to avoid 404 error?

3) Should Mesos query the same container ID after delay, rather than spawning off a new container?

4) Is Mesos 0.25.0-0.2.70.ubuntu1504 compatible with Docker 1.91 with v1.21 API? 

Any assistance will be greatly appreciated!

**Comment by jgarcia-mesosphere** [comment]
Hi there!

1. Looks like the correct container URI to me. It's specified as `cass31`, which is interpreted as "the official cass31 repo at hub.docker.com". I don't see an official cass31 repo there, so I think we'll need to define the container name and owner more explicitly.
2. That's docker's behavior, not ours.
3. We leave that up to Docker and just request the same tag.
4. As far as we know, it is compatible. Please correct the container name and [set up a private repo if necessary](https://mesosphere.github.io/marathon/docs/native-docker-private-registry.html) then try again.

**Comment by gkleiman** [comment]
@alfredcs please re-open this issue if you have further questions related to Marathon.

The Mesos JIRA and mailing lists are a better channel for questions related to Mesos (but not  to Marathon).
