### ISSUE TITLE
Enhance metrics to include incoming resources?

### ISSUE THREAD

**Issue by fengyehong** [mesosphere/marathon#2898]
There is now a metric named `service.mesosphere.marathon.core.launcher.impl.OfferProcessorImpl.incomingOffers`

I wonder if we can also include offer resources incoming speed? like `incomingOfferCpus`, `incomingOfferMemory`, `incomingOfferDisk`

If these metrics become low or even zero, it *may* indicate that the framework is suffering a resource starvation. And it can also tell us what kind of resource needs supplement.

Mesos by now can only report overall resource usage, which can not expose states of frameworks, or roles.

Thanks.

**Comment by aquamatthias** [comment]
Hey @fengyehong thanks for submitting this idea.
We have plans to make this information available as part of the deployment/launch queue, not as part of metrics.
