### ISSUE TITLE
inline script in docker command

### ISSUE THREAD

**Issue by joelstewart** [mesosphere/marathon#2901]
I am trying to use a different interface than default for a docker container.  Host networking allows me to locate this other nic (enp0s8), which would be the same name for all boxes in the cluster.

I can run with docker fine:

docker run --net='host' -p 9200:9200 -p 9300
;9300 el2 -Des.transport.publish_host=$(/sbin/ifconfig enp0s8|awk '/netmask/ {print $2}')

This correctly sets the slave's ip for this alternate nic and allows it to join a cluster.  So the 9200 should bind to one interface (default gateway) while the transport should bind to the other (enp0s8).

In marathon, it won't run with the script in the cmd, but runs fine putting in a specific ip..  

I tried via the GUI to specify the command as shown below as well as the alternate encoding the string for json ("-Des.transport.publish_host=$(\/sbin\/ifconfig enp0s8|awk '\/netmask\/ {print $2}')")

Is this something that is expected to work? 

Here is /v2/apps for the failing to deploy app.  
{
    "apps": [{
        "id": "/elsapp",
        "cmd": "-Des.transport.publish_host=$(/sbin/ifconfig enp0s8|awk '/netmask/ {print $2}')",
        "args": null,
        "user": null,
        "env": {

```
    },
    "instances": 1,
    "cpus": 1,
    "mem": 256,
    "disk": 0,
    "executor": "",
    "constraints": [],
    "uris": [],
    "storeUrls": [],
    "ports": [9200,
    9300],
    "requirePorts": false,
    "backoffSeconds": 1,
    "backoffFactor": 1.15,
    "maxLaunchDelaySeconds": 3600,
    "container": {
        "type": "DOCKER",
        "volumes": [],
        "docker": {
            "image": "els",
            "network": "HOST",
            "privileged": false,
            "parameters": [],
            "forcePullImage": false
        }
    },
    "healthChecks": [],
    "dependencies": [],
    "upgradeStrategy": {
        "minimumHealthCapacity": 1,
        "maximumOverCapacity": 1
    },
    "labels": {

    },
    "acceptedResourceRoles": null,
    "version": "2016-01-06T02:06:40.655Z",
    "versionInfo": {
        "lastScalingAt": "2016-01-06T02:06:40.655Z",
        "lastConfigChangeAt": "2016-01-06T02:06:40.655Z"
    },
    "tasksStaged": 1,
    "tasksRunning": 0,
    "tasksHealthy": 0,
    "tasksUnhealthy": 0,
    "deployments": [{
        "id": "adbd6242-9725-4f12-8ad1-018c477db88b"
    }]
}]
```

}

**Comment by aquamatthias** [comment]
@tnachen is there a way to specify this?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3411. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3411. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
