### ISSUE TITLE
Show health status bar breakdown on application detail view

### ISSUE THREAD

**Issue by leemunroe** [mesosphere/marathon#2906]
Currently on the application list a tooltip with an explanation for each of the colors in the health status bar is provided.

On the detail view only information on healthy, unhealthy and unknown is provided.

Does it make sense to also show (if great than 0)
* Staged
* Over Capacity
* Unscheduled

This expectation was highlighted in recent usability testing.

![image](https://cloud.githubusercontent.com/assets/15963/12156478/ebdeb35c-b47f-11e5-862e-82e2f30fdf28.png)

**Comment by Poltergeist** [comment]
+1 @aldipower and me are currently discussing the topic and we do think that it would be a good idea to see the other states as well. Maybe we should thinking about only showing these types only if they are > 0 like in the dropdown on the app list.

**Comment by pierlo-upitup** [comment]
On the other hand we don't have a problem with spacing in this page, so I'd vote for *always* showing these labels even when = 0. This is a good way to "self document" these states. 

Related: https://github.com/mesosphere/marathon/issues/2907

I'd love to see the `(?)` in this section too, somehow.

**Comment by leemunroe** [comment]
I would lean more towards only show if > 0. In my (limited) experience, staged, over capacity and unscheduled are not as common.

+1 for a help icon and associated doc. Thinking the icon could go on far right, or the health bar on this view could trigger the tooltip with the info and more detail link.

**Comment by aldipower** [comment]
Cool, then let's do it with > 0. I think it is not necessary to self-document them. The awareness of these states isn't that mandatory in my opinion.
