### ISSUE TITLE
Add help icons linking to docs for status and health

### ISSUE THREAD

**Issue by leemunroe** [mesosphere/marathon#2907]
Follow up to #2873 

Usability tests highlighted that often users aren't clear what different statuses mean or what the health column means.

Introducing these icons is a non-obtrusive but effective way of providing more information to customers on what they mean.

The linked content would be
* Marathon UI https://mesosphere.github.io/marathon/docs/marathon-ui.html
* Health Checks https://mesosphere.github.io/marathon/docs/health-checks.html

![image](https://cloud.githubusercontent.com/assets/15963/12157022/81857e88-b483-11e5-908a-856a05836313.png)

/cc @pierlo-upitup

**Comment by pierlo-upitup** [comment]
Thanks a lot for this, @leemunroe . How does the `(?)` interaction work, though? We have to keep in mind these table headers are clickable (for sorting) so the small icon might be a tough link target for some users.

I wonder if this could be solved with a popover : 

- hover mouse on the `(?)` icon
- a popover is revealed (similar to the progress bars)
- inside the popover a textual link to the docs is shown

What do you think?

**Comment by leemunroe** [comment]
@pierlo-upitup I dig it. This what you had in mind?

![image](https://cloud.githubusercontent.com/assets/15963/12206346/38af67aa-b5f5-11e5-8122-aba048d4d59d.png)

**Comment by pierlo-upitup** [comment]
Exactly!!!

**Comment by leemunroe** [comment]
@pierlo-upitup Added `icon-help.svg` to `design/products/marathon/production/components/icons`. 

I would suggest a 60% opacity then 100% on hover for icon.

For tooltip keep consistency with the existing tooltips/popovers.
