### ISSUE TITLE
Show Docker ID for a task in UI

### ISSUE THREAD

**Issue by magcius** [mesosphere/marathon#2908]
For debugging purposes, sometimes it can be helpful to have the Docker ID for `docker logs` or similar. `docker ps` isn't enough, since it doesn't show envvars or other kinds of task configuration that might differ between applications. Having the Docker ID in the list of tasks per application would be a huge help.

**Comment by aldipower** [comment]
Good idea!

Displaying the Docker Container ID in the tasks details has to be implemented both in the API and GUI.

**Comment by Poogles** [comment]
+1 for this, I normally end up hopping into the container and poking around to check.

**Comment by pierlo-upitup** [comment]
cc @aquamatthias

**Comment by aquamatthias** [comment]
And has to be provided by Mesos - is there a ticket for this?

**Comment by AI-PaaS** [comment]
+1 for this

**Comment by AI-PaaS** [comment]
https://issues.apache.org/jira/browse/MESOS-2191 this ticket talk about this. In the comment:"So now I am confused, which container Id do you need? the mesos container id or the docker container id? You can get the docker one by using ExecutorDriver::sendFrameworkMessage."
I think this fix the issue

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2737. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2737. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
