### ISSUE TITLE
Update and improve dialog messages

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#2909]
The new dialog design introduced in #2831 includes a dialog title as well as a state. We don't have that content yet... You find a list of all dialogs including a title, state and message proposal in the following. Any feedback is highly appreciated.

#### confirm (current message: "There is a deployment in progress that changes ${appId}. If you want to stop this deployment and force a new one to scale it, press the 'Scale forcefully' button.")

**Title:** Danger: ${appId} Is Currently Deploying
**Message:** In order to scale to a new number of instances, the current deployment will have to be forcefully stopped, and a new one started. Please be cautious, as this could result in unwanted states.
**Button:** Stop Current Deployment and Scale
**State:** Danger
          
#### alert (current message: "Not scaling: ${Messages.UNAUTHORIZED}")

**Title:** Error: Unauthorized Access
**Message:** Could not scale application.
**State:** Danger

#### alert (current message: "Not scaling: ${Messages.FORBIDDEN}")

**Title:** Error: Access Forbidden
**Message:** Could not scale application.
**State:** Danger

#### alert (current message: "Not scaling: ${errorMessage.message || errorMessage}")

**Title:** Error: Could Not Scale ${appId || "Application"}
**Message:** ${errorMessage.message || errorMessage} 
**State:** Danger

#### alert (current message: "Error restarting app: ${Messages.UNAUTHORIZED}")

**Title:** Error: Unauthorized Access
**Message:** Could not restart application.
**State:** Danger

#### alert (current message: "Error restarting app: ${Messages.FORBIDDEN}")

**Title:** Error: Access Forbidden
**Message:** Could not restart application.
**State:** Danger

#### alert (current message: "Error restarting app: ${errorMessage.message || errorMessage}")

**Title:** Error: Could Not Restart ${appId || "Application"}
**Message:** ${errorMessage.message || errorMessage} 
**State:** Danger

#### alert (current message:  "Error destroying app: ${Messages.UNAUTHORIZED}")

**Title:** Error: Unauthorized Access
**Message:** Could not delete application.
**State:** Danger

#### alert (current message: "Error destroying app: ${Messages.FORBIDDEN}")

**Title:** Error: Access Forbidden
**Message:** Could not delete application.
**State:** Danger

#### alert (current message: "Error destroying app: ${errorMessage.message || errorMessage}")

**Title:** Error: Could Not Destroy ${appId || "Application"}
**Message:** ${errorMessage.message || errorMessage}
**State:** Danger

#### alert (current message: "Error killing task: ${Messages.UNAUTHORIZED}")

**Title:** Error: Unauthorized Access
**Message:** Could not kill task.
**State:** Danger

#### alert (current message:  "Error killing task: ${Messages.FORBIDDEN}")

**Title:** Error: Access Forbidden
**Message:** Could not kill task.
**State:** Danger

#### alert (current message: "Error killing task: ${errorMessage.message || errorMessage}")

**Title:** Error: Could Not Kill Task
**Message:** ${errorMessage.message || errorMessage}
**State:** Danger

#### confirm (current message: "Failed to kill task and scale ${appId}. If you want to stop any current deployment of the app and force a new one to kill the task and scale it, press the 'Kill and scale forcefully' button.")

**Title:** Danger: ${appId} Is Currently Deploying
**Message:** In order to kill the tasks and scale to a new number of instances, the current deployment will have to be forcefully stopped, and a new one started. Please be cautious, as this could result in unwanted states.
**Button:** Stop Current Deployment and Scale
**State:** Danger
        
#### alert (current message: "Not scaling: ${Messages.UNAUTHORIZED}")

**Title:** Error: Unauthorized Access
**Message:** Could not scale application.
**State:** Danger

#### alert (current message: "Not scaling: ${Messages.FORBIDDEN}")

**Title:** Error: Access Forbidden
**Message:** Could not scale application.
**State:** Danger

#### alert (current message: "Not scaling: ${errorMessage.message || errorMessage")

**Title:** Error: Could Not Scale  ${appId || "Application"}
**Message:** ${errorMessage.message || errorMessage}
**State:** Danger

#### alert (current message: "Delay reset successfully")

**Title:** Application Delay
**Message:** Reset successful.
**State:** Info    

#### alert (current message: "Error resetting delay on app: ${Messages.UNAUTHORIZED}")

**Title:** Error: Unauthorized Access
**Message:** Could not reset application delay.
**State:** Danger

#### alert (current message: "Error resetting delay on app: ${Messages.FORBIDDEN}")

**Title:** Error: Access Forbidden
**Message:** Could not reset application delay.
**State:** Danger

#### alert (current message: "Error resetting delay on app: ${errorMessage.message || errorMessage}")

**Title:** Error: Could Not Reset  ${appId || "Application"} Delay
**Message:** ${errorMessage.message || errorMessage}
**State:** Danger

#### promt (current message: "Scale to how many instances?")

**Title:** Scale Application
**Message:** How many instances would you like to scale to?
**Button:** Scale Application
**State:** Info

#### confirm (current message: "Suspend app by scaling to 0 instances?")

**Title:** Suspend Application
**Message:** Do you want to suspend ${appId} by scaling to 0 instances?
**Button:** Suspend Application
**State:** Info
  
#### confirm (current message: "Restart app '${appId}'?")

**Title:** Restart Application
**Message:** Do you want to restart ${appId}?
**Button:** Restart Application
**State:** Info
		 
#### confirm (current message: "Destroy app '${appId}'? This is irreversible."

**Title:** Danger: You're About To Destroy ${appId}
**Message:** Do you really want to destroy ${appId}? This is irreversible.
**Button:** Destroy Application
**State:** Danger		
		 
#### alert (current message: "Could not update to chosen version: ${errorMessage.message || errorMessage}")

**Title:** Error: Could Not Update Application Configuration
**Message:** Could not update to chosen version: ${errorMessage.message || errorMessage}
**State:** Danger

#### confirm (current message: "Rollback deployment of applications: '${model.affectedAppsString}'? Destroying this deployment will create and start a new deployment to revert the affected app to its previous version.")

**Title:** Warning: You're About To Rollback The Deployment
**Message:** This will stop the current deployment of ${model.affectedAppsString} and start a new deployment to revert the affected applications to its previous version.
**Button:** Rollback Deployment
**State:** Warning

#### confirm (current message: "Stop deployment of applications: '${model.affectedAppsString}'? This will stop the deployment immediately and leave it in the current state.")

**Title:** Warning: You're About To Stop The Deployment
**Message:** This will stop the deployment of ${model.affectedAppsString} immediately and leave the applications in their current state.
**Button:** Stop Deployment
**State:** Warning

#### alert (current message: "The UI version is ${config.version}")

**Title:** Marathon UI
**Message:** You're running version ${config.version}.
**State:** Info

#### alert (current message: "Could not fetch app '${props.appId}' version for editing: ${props.appVersion}")

**Title:** Error: Could Not Fetch Requested ${props.appId} Configuration
**Message:** Could not fetch version ${props.appVersion}.
**State:** Danger

/cc @leemunroe @cleverroffey @philipnrmn @aldipower @Poltergeist @pierlo-upitup

**Comment by pierlo-upitup** [comment]
Thanks for gathering all of these! 

I think we're on the right track with this, however I'd like to keep the specificity of each error message. For example:

> alert (current message: "Not scaling: ${errorMessage.message || errorMessage}")

> Title: Error
> Message: ${errorMessage.message || errorMessage} 
> State: Danger

This should be:

> Title: **Not scaling**
> Message: `${appId}. ${errrorMessage}`
> State: Danger

What do you think?

**Comment by orlandohohmeier** [comment]
Yeah, good point... I'm not sure if we know the ${appId} within the error handler. What about the following:

Title: Error: Unable To Scale ${appId || "Application"}
Message: ${errorMessage.message || errorMessage} 
State: Danger

**Comment by pierlo-upitup** [comment]
Yeah that sounds very reasonable. I guess we can figure out the best solution for each case individually. Also – it might make sense to split this work amongst us as it's probably very tedious :stuck_out_tongue:

**Comment by pierlo-upitup** [comment]
This depends on https://github.com/mesosphere/marathon-ui/pull/521

**Comment by orlandohohmeier** [comment]
@pierlo-upitup: I've adjusted the title/message proposals as discussed

**Comment by pierlo-upitup** [comment]
@orlandohohmeier regarding your proposal, I believe that titles need be generic and most importantly predictable in length. As `appId` fields can vary in length, they make for poor tittles. I'd rather have the detailed info in the `message`. 

I will go through the messages and add suggestions as I see fit.

**Comment by leemunroe** [comment]
Added some notes to the Drive doc
