### ISSUE TITLE
Document all UI coding guidelines

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#2910]
Document all coding guidelines (using eslint rules or within the respective contributing section), otherwise any comment on coding styles kinda feels arbitrary as it is not always clear what the desired style is.

**Comment by pierlo-upitup** [comment]
I'd say the `.eslint` should speak for itself, unless it can't solve a specific situation (ie our way of indenting multiline functions, etc.).

Let's have a guidelines page in our repo that covers these exceptions only.

**Comment by orlandohohmeier** [comment]
I like the eslint only approach. What about writing eslint plugins to enforce those specific rules?

**Comment by pierlo-upitup** [comment]
Reminder: let's document how line-breaking JSX should look like. 

Good Examples:
```
<PromptDialogComponent data={dialogData}
  onAccept={this.handleAcceptDialog}
  onDismiss={this.handleDismissDialog}  />
```

```
<PromptDialogComponent data={dialogData}
    onAccept={this.handleAcceptDialog}
    onDismiss={this.handleDismissDialog}>
  <ChildNode />
</PromptDialogComponent>
```

Is there a way to enforce our guideline with an eslint rule?
