### ISSUE TITLE
Improve Tests pt. 2

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2911]
Let's use this issue as an ongoing story for improving our UI Test Strategy.
Related: https://github.com/mesosphere/marathon-ui/pull/511

Integration Tests Strategy
- [ ] Define Integration Testing strategy and scope (what is the desired outcome? is testing within a browser against the Marathon API enough? which tools are suitable in an OSS project?) cc @air  
- [ ] get a working DCOS integration test runner set up
- [ ] define and write some Integration Tests 

ACs
- [x] Audit the existing tests, organise them by scenario (ie: BDD (with DOM), Unit Tests, Integration Tests (?)) (https://github.com/mesosphere/marathon/issues/2929)
- [x] separate unit tests from behavioural tests such that unit tests are clearly associated with the files they test (https://github.com/mesosphere/marathon/issues/2928)
- [x] ensure that behavioural tests run with a DOM context to avoid the shallow renderer and children[0].props.children[0].props.children[0] type chains [https://github.com/mesosphere/marathon-ui/pull/547]
- [x] add coverage numbers - [https://github.com/mesosphere/marathon-ui/pull/554] 
- [x] write and document some example tests
- [ ] create jobs for areas where tests are missing
- [ ] add Sinon for spies and other benefits

Thanks to @philipnrmn for the ideas.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3086. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3086. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
