### ISSUE TITLE
Ensure Up-to-date State

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#2917]
Originally part of #468.

[Zookeeper does not guarantee visibility](https://zookeeper.apache.org/doc/r3.1.2/zookeeperProgrammers.html#ch_zkGuarantees) of updates immediately after confirmation (at least not for different clients).

That probably means that, in addition to serving reads from memory, we need to issue a ZooKeeper sync command on startup.

Acceptance Criteria
- [ ] think about [Zookeeper consistence guarantees](https://zookeeper.apache.org/doc/r3.1.2/zookeeperProgrammers.html#ch_zkGuarantees) and ensure our reads always read the latest data

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3128. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3128. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
