### ISSUE TITLE
Docker container hanging when scale app

### ISSUE THREAD

**Issue by tranhuucuong91** [mesosphere/marathon#2924]
# Situation
I have docker image. I use [dumb-init](https://github.com/Yelp/dumb-init) for reap orphaned zombie processes.

Dockerfile
```
COPY docker-entrypoint.sh /
ENTRYPOINT ["dumb-init", "/docker-entrypoint.sh"]
```

docker-entrypoint.sh
```
# start filebeat for transfer logging
/data/filebeat -c /data/filebeat.yml &

# start apache ofbiz
XMS=${XMS:-256M}
XMX=${XMX:-512M}
MAX_PERM_SIZE=${MAX_PERM_SIZE:-512M}

java -Xms${XMS} -Xmx${XMX} -XX:MaxPermSize=${MAX_PERM_SIZE} -jar ${PATH_OFBIZ}/ofbiz.jar
```

- When I use `docker stop`, container gracefully stopped.
- I want to test autoscaling so I scale app on marathon, scale up -> down -> up -> down quickly. Then, process in container is hanging. **No other way, I must restart server.**
I think the cause may be due mesos use `docker kill` to stop container.

## Process status
docker ps
```
CONTAINER ID        IMAGE                                                    COMMAND                  CREATED             STATUS              PORTS                               NAMES
74d8edceb5dd        registry.olbius.lan:5001/tranhuucuong91/olbius-pos:t10   "dumb-init /docker-en"   16 hours ago        Up 16 hours         8080/tcp, 0.0.0.0:31876->8443/tcp   mesos-1c4d361a-9565-493a-a6ab-111e190dbdae-S0.e0b3c028-5439-4e31-a80e-6b654c2cce50
```

top
```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                       
10856 root      20   0       0      0      0 Z  97.8  0.0   1018:33 filebeat  
```

pstree -p | grep 10856
```
        |-docker(796)-+-dumb-init(10771)---filebeat(10856)---{filebeat}(10864)
```

pstree -ap
```
init,1
  ├─acpid,1028 -c /etc/acpi/events -s /var/run/acpid.socket
  ├─atd,1001
  ├─cron,1000
  ├─dbus-daemon,838 --system --fork
  ├─dhclient,664 -1 -v -pf /run/dhclient.eth0.pid -lf /var/lib/dhcp/dhclient.eth0.leases eth0
  ├─docker,796 daemon --dns 8.8.8.8 --dns 8.8.4.4 --registry-mirror=https://registry.olbius.lan:5000
  │   ├─(dumb-init,10771)
  │   │   └─(filebeat,10856)
  │   │       └─{filebeat},10864
```

## System info
OS: ubuntu 14.04
Linux kernel: 4.2.0-19-generic
mesos: 0.26.0
marathon: 0.13.0
docker-engine: 1.9.1

**Comment by aquamatthias** [comment]
Hey @tranhuucuong91 Thanks for reporting this. Mesos uses docker kill to stop the task. If you have a problem with this, please report that in the Mesos Jira: https://issues.apache.org/jira

**Comment by tranhuucuong91** [comment]
I resolved problem with mesos. Mesos use `docker kill` by default. If you want mesos use `docker stop`, you need config `docker_stop_timeout` with value greater than `0s`.
Like that: `echo 10secs > /etc/mesos-slave/docker_stop_timeout`
Thank for your help.

**Comment by aquamatthias** [comment]
Hey @tranhuucuong91 thanks for reporting this
