### ISSUE TITLE
Unclear description of GROUP BY constraint

### ISSUE THREAD

**Issue by medzin** [mesosphere/marathon#2925]
The current documentation of GROUP_BY constraints states that:

> It is important to note that Marathon only knows about different values of the attribute (e.g. "rack_id") by analyzing current running tasks.

What is not very precise, because AppTaskLauncherActor and later ResourceMatcher have only a list of application tasks for which they match constraints:

https://github.com/mesosphere/marathon/blob/v0.13.0/src/main/scala/mesosphere/marathon/core/launchqueue/impl/AppTaskLauncherActor.scala#L108-L109

It raises the question of whether it makes sense to run applications with GROUP_BY constraint without providing the number of values in constraints, because new applications never know this number and it all depends on what kind of offers they receive from Mesos, which eventually results in quite random behavior.

**Comment by aquamatthias** [comment]
@medzin Thanks for pointing this out. And you are right: the cluster state is observed by means of incoming offers from Mesos. We should make this more clear in the documentation.
@sascala: can you add a section about this? Thanks.

**Comment by sascala** [comment]
Would this text change capture your meaning?

Marathon only knows about different values of the attribute (e.g. "rack_id") by analyzing incoming offers from Mesos. If tasks are not already spread across all possible values, specify the number of values in constraints. For example, if you are spreading across 3 racks, use:

**Comment by medzin** [comment]
@sascala You could give some warning to the user that there is a possibility that in spite of the grouping by rack_id tasks will be distributed in one rack_id (if constraint is without the number of values).

**Comment by sascala** [comment]
@medzin @aquamatthias How does this look?

Marathon only knows about different values of the attribute (e.g. "rack_id") by analyzing incoming offers from Mesos. If tasks are not already spread across all possible values, specify the number of values in constraints. If you don't specify the number of values, you might find that the tasks are only distributed in one value, even though you are using the GROUP_BY constraint. For example, if you are spreading across 3 racks, use:

**Comment by medzin** [comment]
@sascala perfect!

**Comment by sascala** [comment]
https://github.com/mesosphere/marathon/commit/2838e6b4edafad8f003587664f6eb51cdcc656d3

**Comment by timoreimann** [comment]
As the doc update has made it to the github.io page, this issue can be considered done and be closed.

**Comment by medzin** [comment]
Documentation available on https://mesosphere.github.io/marathon/docs/constraints.html
