### ISSUE TITLE
Create a UI Plugin Example

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2926]
We should create at least one Marathon UI plugin that will serve as an example for writing UI plugins. 

Related: https://github.com/mesosphere/marathon/issues/2827

A good candidate could be adding a simple auth integration in the UI for the already existing `auth` Marathon plugin: https://github.com/mesosphere/marathon-example-plugins/tree/master/auth

The (rough) AC for this would be:

- [ ] Define how a plugin can distribute JS(X)/CSS 
- [ ] How these can be sourced by the UI at build time
- [ ] Provide a list of available hooks/filters/actions that allow the plugin to interact with the data

The UI for the `auth` plugin could add the following:

~~- A login dialog that is shown by the `/login` route~~
~~- "Login denied" validation error~~
~~- A "Welcome, user - Logout" entry in the nav bar~~
~~- optionally the ability to filter apps based on the `user` name~~

Let's keep this issue updated as we get closer to understanding the problem better. 

Please look at https://mesosphere.github.io/marathon/docs/plugin.html

**Comment by aldipower** [comment]
@pierlo-upitup The first three AC's are covered here:
https://github.com/mesosphere/marathon-ui/pull/596

The four AC's for the auth-plugin makes that much sense, that I would propose to implement a real auth-plugin with it.
Should I rename this issue or create a new one?
