### ISSUE TITLE
Deployments should be restarted after TaskTracker (and others) are prepared

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#2932]
Otherwise task loading might run into timeouts (observed during tests)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3276. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3276. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
