### ISSUE TITLE
task_launch_timeout vs task_launch_confirm timeout in docs

### ISSUE THREAD

**Issue by abraithwaite** [mesosphere/marathon#2939]
These should probably reference each other.  I was using task_launch_timeout and was caught off-guard when things were still getting killed at 5 minutes.

Maybe consider setting task_launch_timeout default to 6 minutes as well since it doesn't make sense for them to have the same value, especially when they're checked a few lines from one another in the code.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3603. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3603. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
