### ISSUE TITLE
Update AppDefinition PATCH to match RFC 6902

### ISSUE THREAD

**Issue by ssorallen** [mesosphere/marathon#294]
Currently, PATCHing an AppDefinition takes a JSON blob that looks like a partial AppDefinition:

```
PATCH /v2/apps/appOfMyEye '{"instances": 5}'
```

However, that is not the correct way to implement PATCH as described in [RFC 6902](http://tools.ietf.org/html/rfc6902). PATCH bodies should be lists of modifications to a resource:

```
PATCH /v2/apps/appOfMyEye '[{"op": "replace", "path": "/instances", "value": 5}]'
```

**Comment by aquamatthias** [comment]
We will not change the behavior of the /v2/apps API. We will address PUTting and PATCHing in the `/v3/` API.
