### ISSUE TITLE
different definitions of 'cpu' parameter for mesos and docker

### ISSUE THREAD

**Issue by uniwolf** [mesosphere/marathon#2940]
The definitions of 'cpu' parameter for mesos and docker are different.
+ The mesos treat 'cpu' as number. 
+ But marathon translate the 'cpu' parameter to 'cpu-shares' parameter of docker container, which is a relative value.

Am i right?

for such a scenario:
+ server_1 has 1 cpu 
+ server_2 has 2 cpus
+ the application's parameter cpu=0.1 and instances=20.
+ there are 10 tasks run on server_1 and server_2 Respectively.

So, each task run on server_1 can get max 10% cpu usage, and 20% for each task on server_2.
In another words, the processing ability of tasks on server_1 is **only half** of that on server_2.

The problems:
 1. mesos would limit the task number for servers with small cpu number. 
 As the example above, I can't set instance number more than 30 ((1+2)/0.1), even if the two servers are still idle. 
 2. uncertainly actual max cpu usage as the tasks number is uncertainly on different server.

So, the question is:
 how to set the 'cpu' parameter is much appropriately, or how to limit CPU usage for marathon docker application?

**Comment by aquamatthias** [comment]
The `cpu` parameter in Marathon is passed as is to Mesos. The value and meaning is exactly the same.

**Comment by uniwolf** [comment]
It is my fault. I checked mesos source code. Mesos translate the cpu to cpu-shares for docker app.

```cpp
   if (cpus.isSome()) {
      uint64_t cpuShare =
        std::max((uint64_t) (CPU_SHARES_PER_CPU * cpus.get()), MIN_CPU_SHARES);
      argv.push_back("-c");
      argv.push_back(stringify(cpuShare));
    }
```

But I still can not think clearly for the question of the scenario above. 
Can u help me?
