### ISSUE TITLE
Select interface to bind app port

### ISSUE THREAD

**Issue by diegooliveira** [mesosphere/marathon#2943]
I was looking for a way to define that PORT binds to a specific network interface but found nothing. Something like bind the app1 port to the eth0 interface and app2 to the eth1 interface. Is there a way to achieve that?

**Comment by wendigo** [comment]
Unfortunately it's not possible within mesos itself. However in mesos 0.26.0 you can workaround this with IPAM/Network Isolator and NetworkInfo.IpAddress to hint IPAM that provided IP address should be used for container. IPAM then can decide which network interface to use.

More at: http://mesos.apache.org/documentation/latest/networking-for-mesos-managed-containers/

**Comment by aquamatthias** [comment]
@diegooliveira You can define the network interface to use in the mesos slave. This interface is used for all tasks/ports that run on this slave. There is currently no option to select the NIC for the port. 

We recently have added IP/Container which allows for security groups: https://github.com/mesosphere/marathon/blob/master/docs/docs/ip-per-task.md 
But also here you can define the group only on app/task level, not port level.

Please request such a feature in the Mesos Jira: https://issues.apache.org/jira

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2955. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2955. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
