### ISSUE TITLE
Show better feedback in Task List upon scale action

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2945]
~~As illustrated here~~

https://mesosphere.invisionapp.com/share/6P56VR1XZ#/screens/119296366

~~upon a successful Scale operation is detected, the Task List should display "ghost" entries to provide better feedback to the user.~~

@leemunroe let's solve this problem with a global notification system, for the issues discussed in https://github.com/mesosphere/marathon-ui/pull/545#issuecomment-171402292.

**Comment by aldipower** [comment]
Imagine I scale from 5 to 500.

I really don't like the idea to pollute the task list with meaningless task entries that don't exists in the API response. We should try to reflect the API 1:1 .

That is not the idea of a clear feedback to the user I have in mind.

**Comment by pierlo-upitup** [comment]
@aldipower of course we only fill the rows within the current page – what bothers you about that?

**Comment by pierlo-upitup** [comment]
cc @leemunroe

**Comment by leemunroe** [comment]
The goal here is to immediately give the user feedback that their input was received and something is happening. This idea is similar to Facebook's or Slack's [placeholders](http://cloudcannon.com/deconstructions/2014/11/15/facebook-content-placeholder-deconstruction.html). 

Is the concern that we're implying there are tasks when there are not? Open to other suggestions, as long as we can provide some sort of feedback.

**Comment by pierlo-upitup** [comment]
I really like this, it makes the interaction friendlier. @aldipower do you have a better suggestion?

**Comment by aldipower** [comment]
@leemunroe @pierlo-upitup 
Yes, exactly, one concern is to implying tasks that are not there and the UX is also not complete here.
But I absolutely, I see the need for some sort of feedback.

Let me give an example:
I scale from 5 tasks to 50 tasks,
I assume that I get 45 placeholder tasks,
but I see only 3 additional placeholder tasks, because one page only display 8 tasks.
To be consistent, I should be able to click through the pages with all these placeholders,
but that feels somehow strange to.

Why not just displaying a general and non-page-blocking loading indicator?
That would be really useful on other places too!

**Comment by aldipower** [comment]
In short, this is a specific solution to a generic problem.
Let's think about a generic solution.

Could we use also a notification banner on top of the page for this?

**Comment by leemunroe** [comment]
Good points. Agreed. Let's review this.

/cc @cleverroffey

**Comment by orlandohohmeier** [comment]
I don't agree that we need a more generic solution in the kinds of a generic "something is happening" indicator (even though it could be a good addition), as this was about communicating the scale action but we do need a solution which also communicates scale down operations. What about using the health bar or instance count (something indicating the number of instances) to communicate this operations? I'm thinking of animation illustrating the scale operations. What do you think?

**Comment by pierlo-upitup** [comment]
@orlandohohmeier scale operations in my experience happen in bursts, rather than linearly. That means progress animations might not be the best at illustrating idle periods between bursts.

The way I see this, we could do away with a notification system that shows the user a banner whenever an change to an app has been requested (including scaling) *directly* in the app details page. I'm sure @leemunroe has some great ideas there.

**Comment by aldipower** [comment]
@pierlo-upitup I like the idea with the banner.

**Comment by orlandohohmeier** [comment]
@pierlo-upitup Don't get me wrong, I like to have a notification system to communicate changes. But would also like a specific solution which is proably better in copmunicate this paricular update. What about an arrow up/down animation (kinda like those you see on stock trading websites) right next to the instance count?

**Comment by leemunroe** [comment]
@orlandohohmeier Interesting idea. Can you paste in a screenshot example to explain what you mean?

**Comment by orlandohohmeier** [comment]
@leemunroe I had something like the following in mind: 

<img width="372" src="https://cloud.githubusercontent.com/assets/647035/12391911/6857733c-bdeb-11e5-9aa6-ce48dd872a76.png">

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3142. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3142. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
