### ISSUE TITLE
Revisit variables.less to minimize variable creep

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2946]
We have 6 different declarations of the color `#FFFFFF`. Let's review the contents of our variables file to keep some sort of control over this mess :wink:

**Comment by leemunroe** [comment]
Some related reading
* https://davidwalsh.name/sass-color-variables-dont-suck
* http://thesassway.com/beginner/variable-naming

**Comment by Poltergeist** [comment]
https://github.com/mesosphere/marathon-ui/blob/master/src/css/components/panel.less#L11 has the same color value as `@navbar-border-color` to keep this in mind.
