### ISSUE TITLE
Group Deployments look strange

### ISSUE THREAD

**Issue by Poltergeist** [mesosphere/marathon#2947]
Group deployments look strange in the table if there are more then one application in a group. They are vertical aligned in the middle. Imagine 10 applications in one group. This will happen often when you scale groups. 
![image](https://cloud.githubusercontent.com/assets/156010/12235495/8b7c467a-b874-11e5-93c1-dd380929a87d.png)
cc @leemunroe

**Comment by leemunroe** [comment]
@Poltergeist I'm not that familiar with group deployments. What's the best way to reproduce this using the UI?

**Comment by aldipower** [comment]
@leemunroe We merged yesterday the ability to scale complete groups. In the app list open the contextual actions menu on a group. Ensure to have some applications in the group and maybe docker apps that take a while to deploy, otherwise it's maybe to quickly.

**Comment by aldipower** [comment]
@Poltergeist @leemunroe
I would suggest to top align the content in the cells. That would fix the strangeness.

But of course we could think about a Dropdown-Popover for the "Affected Applications", if there are too many apps. Similiar to the "labels popover".

**Comment by leemunroe** [comment]
Definitely want to rethink the design of this screen in the future. 

Vertically aligning the cells in this particular table seems like a good solution for now.
