### ISSUE TITLE
Unable  to run marathon without zookeeper

### ISSUE THREAD

**Issue by digitalrinaldo** [mesosphere/marathon#2950]
Is zookeeper now required for this version of marathon?

chronos.x86_64                                                                                                                  2.4.0-0.1.20151007110204.el7                                                                                                                   @mesosphere

I am unable to get the following configuration to be used.

[root@some-system-name ~]# cat /etc/default/marathon
MARATHON_MASTER=nnn.nnn.nnn.nnn:5050
MARATHON_HTTP_PORT=8090

**Comment by aquamatthias** [comment]
ZooKeeper is mandatory for Marathon. There is currently no way to run it without.

**Comment by kevincox** [comment]
The docs should be updated then. Because it sounds like running with `--disable_ha` allows running without zookeeper.

**Comment by yanivr78** [comment]
Yes its says on the docs that there is a way to do it,
But no matter what i tried nothing works and since the documents doesnt show an example i guess that no one knows how to do it as well.

**Comment by aquamatthias** [comment]
@yanivr78 Marathon uses zk for:
- leader election
- storage backend
- find mesos master

If you disable ha mode, it will not use zk for leader election. 
For the other points zk is needed.
There is currently no way to run Marathon without zk.

**Comment by yanivr78** [comment]
And i have my mesos working without zk because i have only 1 machine.
Should i install marathon with zk and it will still work with mesos?

**Comment by kevincox** [comment]
On 17/10/16 16:04, yanivr78 wrote:
> And i have my mesos working without zk because i have only 1 machine.
> Should i install marathon with zk and it will still work with mesos?
Yes, this is what I do. I have a single zookeeper node listening on 
localhost just for marathon.

**Comment by jasongilanfarr** [comment]
You can use "--internal_store_backend mem" and marathon storage will be in memory only. If marathon dies does any reason, you'll lose all marathon state. You can disable leadership with zk using "--disable_ha". Warning: You _will loose all state if marathon is ever stopped for any reason_.

**Comment by yanivr78** [comment]
Thanks this sounds cool,
I have installed mesos-sphere marathon - my biggest question is how do I
define this switch ?
or how do I define switches at all ?

currently I run it as a service with systemctl start marathon and there is
no possible way that I can see to add this --internal_store_backend mem
switch ?
