### ISSUE TITLE
Create stylish component for number input

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#2956]
After this PR is merged:
https://github.com/mesosphere/marathon-ui/pull/521

we should get back to the design of the `number` input to match the mockups as mentioned in https://github.com/mesosphere/marathon-ui/pull/521#issuecomment-170485233

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3026. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3026. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
