### ISSUE TITLE
Implement a dialog queue 

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#2958]
Even though it's probably an edge case, there are moments we need to queue dialogs as user would otherwise miss important dialogs (e.g. alert informing about an issue).

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3478. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3478. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
