### ISSUE TITLE
provide validation plugin extension

### ISSUE THREAD

**Issue by metskem** [mesosphere/marathon#2960]
As a follow up on mesosphere/marathon#2905 we would like to have a plugin that can be used for validating an app.
The plugin should get the complete app (including all attributes) passed, so it can inspect it, validate it, and accept or decline.

The plugin could be called from the same plugpoints as the authorization plugin does (create app, delete app, update app and so on).

A few examples of validation:
- check for insane upgrade strategies
- check for healthcheck frequencies
- check for the use of certain constraints
- check for the use of certain labels

kind regards,
Harry

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3168. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3168. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
