### ISSUE TITLE
provide a way of having ownership of an app

### ISSUE THREAD

**Issue by metskem** [mesosphere/marathon#2961]
As a follow up on mesosphere/marathon#2905 we would like to have a way of providing ownership of an app.
This ownership should be explicit and not be based on the name of the app, but preferably a separate new attribute, or maybe a reserved label.

Having ownership of an app only makes sense (to us) if we could base authorization decisions on it.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2806. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2806. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
