### ISSUE TITLE
DCOS tests for Marathon are failing

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#2970]
JIRA Key: MARATHON-697
Reporter: Sunil Shah
Priority: Medium

Description:
The tests that are posted to the #dev-agility channel are part of the DCOS tests repo and test installation of the Marathon package onto master branch of DCOS image. 

TeamCity output here: https://teamcity.mesosphere.io/viewLog.html?buildId=103274

Currently they're failing - perhaps due to the changes in the Marathon package in the Universe.

We should fix these!

**Comment by aquamatthias** [comment]
@gkleiman can you look into those tests. Thanks.
