### ISSUE TITLE
Mesos uses UI's protocol for task URLs

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#2974]
I access marathon over HTTPS, but most of my tasks only speak HTTP. They do HTTPS with the help of LB, just like Marathon. Since 0.14.0-RC1 marathon uses `//host:port/path` links instead of `http://host:port/path`.

I think we could do better here. Some options:
- CLI arg to specify protocol globally
- Per-app setting
- Just revert to http

**Comment by philipnrmn** [comment]
I agree that this is annoying! It was also annoying before we made links relative though. 

My preference would be for a per-app setting, at least until we've got proper service discovery available.

**Comment by bobrik** [comment]
I don't think that service discovery is related to the issue. When I go to Marathon UI I want to go directly to the task, bypassing any service discovery.

Per-port setting like `ui_url_template` would be nice, though. Example values:

* `http://$HOST:$PORT/`
* `https://$HOST:$PORT/`
* `http://$HOST:$PORT/spanish/inquisition`

Not sure how to implement that given that ports are just an array of numbers currently.

**Comment by philipnrmn** [comment]
My suggestion would be to extend the ports to be something like 
```
ports: [
  { number: 8080, protocol: "http" }
  { number: 21, protocol: "ftp" }
]
```

Unfortunately the `ports` field is already very overloaded and this just makes it more complex.

**Comment by aldipower** [comment]
:+1: to @philipnrmn proposal to add an optional protocol field to the ports.

**Comment by pierlo-upitup** [comment]
cc @gkleiman for extra :eyes:

**Comment by triggity** [comment]
concur, it's pretty annoying that just clicking on the host:port in the UI now leads to a broken page that i have to manually edit the url for or copy manually into the url. given that https is usually done outside of marathon itself, can we just revert this to http ?

**Comment by bobrik** [comment]
Any chance to address this with new `portDefinitions` thing?

**Comment by bobrik** [comment]
Looks like you [don't even use https internally](https://mesosphere.com/blog/2016/04/06/lets-encrypt-dcos/), why keep it https in marathon ui then?

![why](https://mesosphere.com/wp-content/uploads/2016/04/image_7-800x642@2x.png)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3632. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3632. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
