### ISSUE TITLE
Restart all applications in group

### ISSUE THREAD

**Issue by logankp** [mesosphere/marathon#2980]
We would like the ability to restart all applications in a group from the Web UI. I know this can be done using the API, but it would be much more convenient to be able to do this through the existing UI.

**Comment by aldipower** [comment]
Hi @logankp, this is a good request. 
We need to add a more efficient and simpler call to the API, that doesn't affect the apps beforehand and saves at least one HTTP-request, like we have with `/apps/{appId}/restart`.

**Comment by logankp** [comment]
Cool! I'd be willing to help with this once everything's ready.

**Comment by nizedk** [comment]
I am all for this, I am currently facing this challenge as well. I'd much prefer if the gui presented that option. How can I contribute, when not having code skills myself?

**Comment by vincentnexonm** [comment]
@logankp A little bit off topic but I'm looking at the Marathon REST API documentation and your comment suggests there's an API already that allows me to restart a group in Marathon? I don't see anything of the sort except for individual apps, /v2/apps/{appId}

Could you point me to where you're able restart an application group through the REST API?

**Comment by logankp** [comment]
@vincentnexonm I don't think there currently is an API call for this. I believe what I was saying a year ago was that this could be done through the API by looping through all apps in a group and restarting them individually.

Obviously there needs to be a better API as @aldipower was suggesting.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2785. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2785. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
