### ISSUE TITLE
Allow updating container fields without sending the whole JSON

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#2981]
Users want to update parts of the `container` specification, without having to resend the whole `container` JSON. For example in order to update the Docker image tag, without having to include all the portMappings, etc.

Quotes from the DCOS Community Slack:

> If I send the JSON for container with only the image property then it drops everything unless it has a default.

And:

> hello - let’s say I have an application deployed with marathon referencing a docker image with the v1.0 tag. Is it possible with a simple http call update the docker image tag(and therefore deploying the new version of the application) without modifying the rest of the application? Of do I need to update the whole json manifest? Thanks

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3199. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3199. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
