### ISSUE TITLE
how can I see the marathon deploy log

### ISSUE THREAD

**Issue by loveai88** [mesosphere/marathon#2986]
I deploy a app in marathon.it show waiting about 10 mins,but I have enough resources in my mesos clusters.

Is there any log I can see the process detail?
Thanks

<img width="267" alt="2016-01-14 10 40 52" src="https://cloud.githubusercontent.com/assets/1001227/12314357/5807f2d8-baab-11e5-9b4b-e2b8b3ed6e16.png">

<img width="253" alt="2016-01-14 10 40 59" src="https://cloud.githubusercontent.com/assets/1001227/12314359/5ace1eb6-baab-11e5-9cb9-6b3afdb961d1.png">

**Comment by hotstepper13** [comment]
First of all open your task in marathon, there might be a page "debug" which schould give you a hint what is happening. To see the details, you have to go to the mesos UI and look for the sandbox output.

**Comment by kolloch** [comment]
This usually requires inspecting logs/state.json manually. Check out https://mesosphere.github.io/marathon/docs/troubleshooting.html#an-app-stays-in-quot-waiting-quot-forever
