### ISSUE TITLE
mean* metrics should only cover reporting interval

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#2988]
We collect all kinds of mean metrics in Marathon using the codahale metrics library. Unfortunately, when used in combination with datadog or statsd+graphite, you end up with meanRates or mean request times that incorporate the whole life time of Marathon instead of only the reporting interval. That makes the interpretation of these metrics difficult.

This is a known problem, look at e.g. http://stackoverflow.com/questions/24603561/how-to-clear-historical-stats-from-java-codahale-metrics-timers

Maybe we are better served by switching to http://kamon.io or other alternatives.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2876. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2876. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
