### ISSUE TITLE
Report task status updates by type

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#2993]
It can really help debugging if the metrics reflect the type of the Mesos task updates, e.g.:
- TASK_STAGED
- TASK_RUNNING
- TASK_LOST
- ...

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2888. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
