### ISSUE TITLE
docker pull a remote image conflict

### ISSUE THREAD

**Issue by loveai88** [mesosphere/marathon#2998]
I run a docker app with 3 tasks,and the docker image not exist in the slave ,it must to pull from docker.io.
Marathon assign 2 app run  in a slave,and the last in another.

I see the log by journalctl,it show me like this :`level=error msg="HTTP Error" err="No such image: solr:latest" statusCode=404`.

There is two threads to pull the image 
```
[root@** ~]# ps -ef|grep solr
root     30113 10735  0 12:17 ?        00:00:00 docker -H unix:///var/run/docker.sock pull solr:latest
root     30114 10735  0 12:17 ?        00:00:00 docker -H unix:///var/run/docker.sock pull solr:latest
```

How can I resolve it ?Is it a bug?

**Comment by aquamatthias** [comment]
Looks like a bug. Please report in the Apache Mesos Jira: https://issues.apache.org/jira
