### ISSUE TITLE
Filter event type  when callback post message

### ISSUE THREAD

**Issue by nashasha1** [mesosphere/marathon#3001]
Hi guys.
Can marathon filter some event type when it post event to callback server? For instance，I don't want to receive `deployment_info` or some other events.

Thanks

**Comment by meichstedt** [comment]
Can you please be more specific on your use case @nashasha1? What's the downside of filtering events on the receiving end?

**Comment by nashasha1** [comment]
Thanks @meichstedt . I use internet to transmit these events，but that cost too much.

**Comment by meichstedt** [comment]
From that perspective, it might make sense to allow filtering event for each susbcriber – we'll look into that.

**Comment by nashasha1** [comment]
@meichstedt  Thank you!~

**Comment by janisz** [comment]
Releated to: https://github.com/mesosphere/marathon/issues/3154
Fixed by: https://github.com/mesosphere/marathon/pull/4669
Discarded by: https://github.com/mesosphere/marathon/issues/4675
