### ISSUE TITLE
Marathon shouldn't start up if the the ZK state is not compatible

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#3004]
Marathon shouldn't start if the major number of the `storage version` persisted in ZooKeeper is greater than the major number of the current version.

The goal of this change is to avoid running with an incompatible state.

**Comment by unterstein** [comment]
Instead of using a ```storage version``` you could introduce an indicator like described in https://github.com/mesosphere/marathon/issues/3005 showing that an migration is in progress. If this indicator is present, you could deny startup of marathon.

**Comment by jasongilanfarr** [comment]
It doesn't start up anymore. Migration will fail if the storage version is too new.
