### ISSUE TITLE
Update ZK storage version at the beginning of a migration

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#3005]
Before starting a ZK storage migration, Marathon should update the `storage version`, to prevent older versions from running with an incompatible state (see #3004).

It also has to set (and persist) a `migrationInProgress` boolean flag, so that on case of errors the migration is resumed.

**Comment by unterstein** [comment]
Like we discussed should the indicator ```migrationInProgress``` is enough to decide if the marathon instance if operating on a possibly incompatible state.

**Comment by jasongilanfarr** [comment]
I feel like this one is dead. Only the leader can migrate and that blocks all other operations (more or less)
