### ISSUE TITLE
Leadership Metric

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3010]
Frequent leadership changes point to stability issues. It would be very good to have a metric that provides visibility into leadership changes. 

Possibilities:

* Model a metric similar to "uptime" -- "durationOfLeadership".
* Count leadership changes.

Technical implementation:

* "durationOfLeadership" Provide a `WhenLeaderActor` that resets the duration when started.

**Comment by prsekar** [comment]
@aquamatthias I have opened a pull request. Can you review this and let me know if this can be merged ?
