### ISSUE TITLE
Refactor all stores that expose setters

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#3011]
Refactor all stores that expose setters or writable data properties as they shouldn't expose anything writable to ensure data integrity and proper separation of concerns. For more details please refer the related Flux documentation:

> Nothing outside the store has any insight into how it manages the data for its domain, helping to keep a clear separation of concerns. Stores have no direct setter methods like setAsRead(), but instead have only a single way of getting new data into their self-contained world — the callback they register with the dispatcher...

/source https://facebook.github.io/flux/docs/overview.html

**Comment by aldipower** [comment]
Which store is exposing setters? Could you give an example?
Shouldn't be the case already actually...

**Comment by orlandohohmeier** [comment]
@aldipower I'll rephrase the issues as they're not explicitly defining setters like set prop(val) or setProp(val) but exposing their data but storing data in a public property, which should be avoided due to the given reasons.
