### ISSUE TITLE
Show reason for health check failure in the UI

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#3016]
You can't tell what's wrong by looking at this:

![image](https://cloud.githubusercontent.com/assets/89186/12397981/a255b8ce-be08-11e5-9fc7-112731ba04ca.png)

Is it a timeout? Is it a connection refused error? Is it a 503 http error?

Logs are not really helpful either:

```
[2016-01-18 17:20:03,738] WARN Connection attempt to somehost:9893 failed in response to GET request to /rs-status with 3 retries left, retrying... (spray.can.client.HttpHostConnectionSlot:marathon-akka.actor.default-dispatcher-15)
```

Both could be improved.

**Comment by meichstedt** [comment]
AFAICT we have the http status available – frontend guys: can you please see whether you'd need any more information on this?

Logs could be improved, but if the gui can display the problems I'd go with that as it's more convenient for the user imho.

**Comment by aldipower** [comment]
@meichstedt Yeah, should be easy to display the health check http-status in the gui too.
But how could we extend the information with TCP and COMMAND health checks?
Is this even necessary or are the messages verbose enough at these checks?

**Comment by aldipower** [comment]
@meichstedt Just noticed, there is no http status available in the lastTaskFailure. But there is a really very verbose `message`. Let's use that! :)

![healthc](https://cloud.githubusercontent.com/assets/859154/12546983/abceda9e-c34d-11e5-834b-1818a008bf29.png)

**Comment by bobrik** [comment]
@meichstedt this is a [message from Mesos](https://github.com/apache/mesos/blob/f99ae0e7618b8a6508ff7d97c290572592508737/src/master/master.cpp#L246-L249), it has nothing to do with marathon health checks.

I'd add exception and message to the current UI, ex:

* Warning: Health check for `/why` failed (ConnectionRefusedException): connection refused while trying to connect to host:port

This also encourages you to have meaningful exceptions for logs.

**Comment by aldipower** [comment]
OK, not that easy. :) The message is only the lastTaskFailure from Mesos as said.

As you can see in the health checks data, I don't have any http-status code and no message on the healthChecksResults:
![ltf](https://cloud.githubusercontent.com/assets/859154/12547197/2ca3daba-c34f-11e5-98ed-ced61ae2f507.png)

So it would be nice to add one of this, both or like @bobrik suggested.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3340. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
