### ISSUE TITLE
Specifying application dependencies in Marathon UI

### ISSUE THREAD

**Issue by akunaatrium** [mesosphere/marathon#3019]
I can't seem to find a way to specify application dependencies in the Marathon UI. I can see that under Configuration tab marathon lists Dependencies as Undefined. Is it currently possible only through the REST API?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4147. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
