### ISSUE TITLE
Marathon-docker labels

### ISSUE THREAD

**Issue by eugenetaranov** [mesosphere/marathon#3020]
Hi,

not sure whether it is a bug or intended behaviour:

when docker container is launched via marathon (0.13) no label specified at creation time gets pushed to docker:

label lang=php56 is visible at marathon dashboard
<img width="706" alt="screenshot 2016-01-19 02 18 29" src="https://cloud.githubusercontent.com/assets/1123643/12406128/fe019e46-be52-11e5-839e-24b5a5ba64a7.png">

but missing when requested via docker api:

```
{
  "Status": "Up 3 minutes",
  "Created": 1453162544,
  "Image": "apache-php",
  "Labels": {},
  "HostConfig": {
    "NetworkMode": "bridge"
  },
  "Ports": [
    {
      "IP": "0.0.0.0",
      "Type": "tcp",
      "PublicPort": 31920,
      "PrivatePort": 80
    }
  ],
  "Command": "/usr/sbin/httpd -D FOREGROUND",
  "Names": [
    "/mesos-85389712-cdd7-47c0-bd50-6b546f8d9ea2-S0.bbbff4f3-d7d4-4385-9e93-e50e9dfbcc03"
  ],
  "Id": "c1dc9965ef4a9480c7538f5232f579c758d50d5fd2825ae2638f6a4a096ea4c7"
}
```

Thanks

**Comment by apognu** [comment]
I do believe those labels are actually Mesos labels, unrelated to Docker.

**Comment by jeacott** [comment]
It would be super helpful if they were pushed to do ker labels. Perhaps with automatic marathon id added as docker label so that identity from syslog is made a whole lot easier.

**Comment by r1ckr** [comment]
If you want to put a docker label, in the parameter section of docker container settings in marathon(Right below "Port Mapping" section), put "label" as key and "com.something.something=something" as value. Then you create the app and do a docker inspect, you will see the label there.

Source:
https://issues.apache.org/jira/browse/MESOS-4446

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4738. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
