### ISSUE TITLE
Memory Limit Recommendations for Marathon

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3022]
When customers run Marathon on Marathon what are the recommended

A) JVM -Xmx and other memory related settings (but let's not dive into fine-grained GC tuning in this issue)
B) the memory limit for the AppDefinition

?
## Consequences of incorrect limits

If we set A) too low, we get OutOfMemory errors. If we set B) too low, the Marathon process gets killed by the kernel if we are on a cluster with enforced memory limits (which is the case in DCOS).
## Parameters

The memory consumption and therefore the recommended limits certainly depend on the number of apps/tasks and maybe other factors. We need to qualify our answer with these numbers.
## Technical Background

In pure Java processes, memory consumption is typically dominated by the heap but we also have a stack for each thread. Before Marathon 0.15 the number of threads in Marathon was historically completely unbounded. In 0.15 we are more conservative with creating new threads (initial pools + new threads if we need them to prevent deadlocks) but we still cannot guarantee a thread limit due to technical debt.

Furthermore, Marathon is not a pure JVM process but includes native code as well to interface with Mesos. For an analytical approach to determining a memory limit, we would need a guarantee that the memory used by the MesosSchedulerDriver is bounded under the specified circumstances.
## Possible solution

One approach to reach the goal of this issue is to employ/extend the scale tests to monitor memory consumption and find and then verify the recommended limits.

**Comment by kolloch** [comment]
We have an unbounded number of threads in Marathon because of blocking code:

https://github.com/mesosphere/marathon/pull/3028
Convert some sync TaskTracker calls to async (epic)

https://github.com/mesosphere/marathon/issues/3029 Remove RWLock from MarathonHealthCheckManager

https://github.com/mesosphere/marathon/issues/3030 Remove LockManager from MarathonStore

https://github.com/mesosphere/marathon/issues/3031 Convert all synchronous TaskTracker calls to asynchronous calls

https://github.com/mesosphere/marathon/issues/3032 Non-blocking HTTP layer

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3516. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
