### ISSUE TITLE
Remove RWLock from MarathonHealthCheckManager

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3029]
The `MarathonHealthCheckManager` uses `RWLock`s to synchronize its state. There is some incorrect synchronization but, in addition, locking doesn't compose well in our code base.

One problem is that all potentially blocking constructs are marked with `scala.concurrent.blocking` to prevent deadlocks. `scala.concurrent.blocking` just results in spawning more threads when needed. That means that as long as we use blocking code constructs, the number of threads that Marathon uses is, in effect, unbounded.

We should probably manage the state in this class by using an Actor.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3572. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
