### ISSUE TITLE
Remove LockManager from MarathonStore

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3030]
The `MarathonStore` uses `LockManager`s to synchronize its state. There is probably some incorrect synchronization for the failure cases but, in addition, locking doesn't compose well in our code base.

One problem is that all potentially blocking constructs are marked with `scala.concurrent.blocking` to prevent deadlocks. `scala.concurrent.blocking` just results in spawning more threads when needed. That means that as long as we use blocking code constructs, the number of threads that Marathon uses is, in effect, unbounded.

We should probably manage the state in this class by using an Actor.

**Comment by jasongilanfarr** [comment]
LockManager doesn't exist anymore.
