### ISSUE TITLE
Convert all synchronous TaskTracker calls to asynchronous calls

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3031]
Historically, the `TaskTracker` used concurrent data structures to handle state access. That allowed synchronous access to the state. Since we have now an actor based `TaskTracker` implementation, there is a compatibility layer that still allows synchronous calls but really performs an `ask` and an `Await.result` call.

The problem is that all potentially blocking constructs (like Await.result) are marked with `scala.concurrent.blocking` to prevent deadlocks. `scala.concurrent.blocking` just results in spawning more threads when needed (which is good). That means that as long as we use blocking code constructs, the number of threads that Marathon uses is, in effect, unbounded.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3219. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
