### ISSUE TITLE
Non-blocking HTTP layer

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3032]
We currently need to use `Await.result` to use our async core code with the HTTP layer. We should switch to something supporting asynchronous requests for optimal performance.

At a bare minimum, we should ensure that the thread for accepting http requests is bounded. We must then avoid spawning tasks with dependencies to other task on this pool in this case to avoid deadlocks.

**Comment by jasongilanfarr** [comment]
This is covered by the move to akka http instead of chaos.
