### ISSUE TITLE
Unknown server error, could not create or apply app.

### ISSUE THREAD

**Issue by dalekurt** [mesosphere/marathon#3033]
I get this error message `Unknown server error, could not create or apply app.` when attempting to deploy a docker container from the marathon web interface,
![screenshot 2016-01-19 11 46 23](https://cloud.githubusercontent.com/assets/93077/12425337/5d4e08ea-bea2-11e5-9a9e-dbb176a95e92.png)

How can I troubleshoot and is this a known issue?

**Comment by meichstedt** [comment]
@dalekurt specifying both a `CMD` and a docker image to deploy doesn't make much sense – you should specify either one of these. If you still run into problems, can you please add information on your docker configuration?

**Comment by dalekurt** [comment]
At the moment I'm only providing a CMD `echo hello; sleep 10` to test the cluster. This is the second cluster I've do over the past 7 days and the last one and I get this error. 

There in no docker image entered for this.

**Comment by meichstedt** [comment]
So does this actually have to do with docker?

Sorry, but you have to be more specific here. How and where did you setup your cluster? Can you please try to create the app via the REST api and provide the AppDefinition?

**Comment by dalekurt** [comment]
@meichstedt The issue that I'm having is that I'm unable to deploy anything via Marathon, including docker images. I create a JSON file with the following:

```{
  "id": "hello2",
  "cmd": "echo hello; sleep 10"
}
```

Then I attempted to deploy it via the REST API and got the following results. I have a cluster of 6 server instances (3x master and 3x slaves) on a provider called racknation.cr. Using the instructions found on (http://open.mesosphere.com/getting-started/install/)[http://open.mesosphere.com/getting-started/install/].  
```
curl -i -H 'Content-Type: application/json' -d@hello.json 138.59.17.10:8080/v2/apps
HTTP/1.1 500 Server Error
Date: Fri, 22 Jan 2016 10:45:22 GMT
X-Marathon-Leader: http://138.59.17.10:8080
Pragma: no-cache
Cache-Control: must-revalidate,no-cache,no-store
Content-Type: text/html;charset=iso-8859-1
Content-Length: 446
Connection: close
Server: Jetty(9.3.z-SNAPSHOT)

<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /v2/apps. Reason:
<pre>    javax.servlet.ServletException: java.lang.NoClassDefFoundError: Could not initialize class mesosphere.marathon.api.v2.BeanValidation$</pre></p>
<hr /><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.z-SNAPSHOT</a><hr/>
</body>
</html>
```

**Comment by jgarcia-mesosphere** [comment]
Dale and I tracked this down to using Marathon with JDK 9 instead of JDK 8.

**Comment by air** [comment]
Java 9 is at least a year out (!) http://www.java9countdown.xyz/

**Comment by deric** [comment]
I run into the same issue with `java 1.8.0_72` and Marathon 0.14, it doesn't seem to be related to JDK9. I couldn't find any message in logs. Is there a way how to debug this?

**Comment by gkleiman** [comment]
@deric you can try raising the log level through the `/logging` endpoint and see if something useful appears in the logs.

**Comment by jgarcia-mesosphere** [comment]
If you aren't using Java 9, you're seeing a different issue. Please report that separately.
