### ISSUE TITLE
[Enhancement] allow data container usage

### ISSUE THREAD

**Issue by kopax** [mesosphere/marathon#3036]
Is it possible to add the potability to deploy a data container attached to the docker app I am deploying ?

something like : 

```
"container": {
  "type": "DOCKER",
  "docker": {
    "image": "company/app:latest",
    "network": "BRIDGE",
    "dataContainer: "company/app-data:latest"
  }
},
```

This would add a post hook that automatically run 

```
docker pull company/app-data:latest
docker run -d --name mesos-8476acff-5f94-44b9-8a0c-4bcdc60e30c2-S0.f2836b6a-6d56-4f57-be86-8e21e24eb58f company/app-data /bin/true
```

Then attach the application to this data container using `--volumes-from`

**Comment by wendigo** [comment]
I think it's not possible in Mesos itself. I've checked in the Mesos source code and currently you can only mount a volume as in: https://github.com/apache/mesos/blob/684b551b02da55b62f401dc05936e3f067f55a70/src/docker/docker.cpp#L473

**Comment by kopax** [comment]
The downside of the current volume mount option : 

 - You have to care where you store your data if you use "path_origin:path_dest"
 - You have to care when using this volume from another container & add them all otherwise you corrupt your data.

The goodside of data container : 

 - Data is stored dynamically in temporary space, while reference to this data container existe, data remain on HD.
 - You can reuse the data container with any instance of your application running on this host.
 - You never corrupt your database, if you need to add a volume for all instances, juste add it into your image once and every.
 - You don't have to bother with uuid/guid, just create the user you need in your data container and it will copy and save the file permissions


I am pretty convinced data container is the way to go, and volume should be used for overriding the conf.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4160. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
