### ISSUE TITLE
Resident Tasks: Adjust App handling workflow

### ISSUE THREAD

**Issue by meichstedt** [mesosphere/marathon#3043]
subtasks
- [x] Scale up
- [x] Scale Down (leaves suspended Tasks lying around)
- [x] Restart
- [x] Change config
- [x] Deployment Logic works overall – **enforcing upgradeStrategy minHealthy <= 0.5, maxOverCapacity == 0** is part of #3231

Task Lost handling is tracked in #3368

**Comment by kolloch** [comment]
The essence of this is that the deployment logic has been designed with "Task = Launched Task" in mind. After our changes, a Task might only represent a reservation. Therefore you have to filter unlaunched tasks from the logic.

**Comment by meichstedt** [comment]
Task Lost handling is tracked in #3368
