### ISSUE TITLE
Allow creating Resident Tasks from the UI

### ISSUE THREAD

**Issue by meichstedt** [mesosphere/marathon#3044]
This is a placeholder issue, for the moment.

ACs
- TBD

**Comment by Poltergeist** [comment]
This does work as a work around, as soon as a persistent local volume is added to an app configuration the residency setting is added to the configuration right before the data is posted to the service. If there is a better way to expose the residency setting in the ui in a sense-full way then lets due that. Currently I do think the work around does work but it should be a setting which is done by the service layer. 

@meichstedt maybe we should close this issue for now.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3670. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
