### ISSUE TITLE
Setting env variables can break mesos docker deployment

### ISSUE THREAD

**Issue by jeroenwijdemans** [mesosphere/marathon#3050]
### Decription

When sending a REST call to marathon the env variable is declared on apps level. These environment variables are passed into the mesos task as 'os' variables. For normal mesos task this is sufficient / desired. 
But there can be docker variables that you only want to pass into mesos docker run command and not onto the mesos os. 
For example the 'http_proxy': we run into an issue where the image cannot be pulled from a private repository because we want to set the http_proxy on a docker container (the registry can only be contacted internally).

It would be nice if we can define env variables on a container level which are only passed to mesos docker run command (with the '-e' flag).

marathon version: 0.13.0
mesos version: 0.25.0

### To reproduce: 

POST http://marathon.mayfly.bol.com/v2/groups

```
{
  "id": "/test",
  "apps": [
    {
      "id": "ubuntu-without-path",
      "instances": 1,
      "cpus": 0.15,
      "mem": 512.0,
      "container": {
        "docker": {
          "image": "ubuntu:15.04",
          "network": "BRIDGE"
        },
        "type": "DOCKER"
      },
      "env": {
        "PATH": ""
      }
    }
  ],
  "groups": []
}
```

Mesos will not be able to execute its command because its PATH variable is gone. And give this result:

```
I0121 08:39:00.021203 11446 exec.cpp:134] Version: 0.25.0
I0121 08:39:00.023387 11481 exec.cpp:208] Executor registered on slave f78200b5-2bfa-4d2d-b425-871e55729ec5-S0
ABORT: (/tmp/mesos-build/mesos-repo/3rdparty/libprocess/src/subprocess.cpp:177): Failed to os::execvpe in childMain: No such file or directory*** Aborted at 1453365540 (unix time) try "date -d @1453365540" if you are using GNU date ***
PC: @     0x7f650931ecc9 (unknown)
*** SIGABRT (@0x2ce8) received by PID 11496 (TID 0x7f64fee07700) from PID 11496; stack trace: ***
    @     0x7f65096bd340 (unknown)
    @     0x7f650931ecc9 (unknown)
    @     0x7f65093220d8 (unknown)
    @           0x419b12 _Abort()
    @           0x419b4c _Abort()
    @     0x7f650b138c3b process::childMain()
    @     0x7f650b13ac6d std::_Function_handler<>::_M_invoke()
    @     0x7f650b138adc process::defaultClone()
    @     0x7f650b139972 process::subprocess()
    @     0x7f650a9907f1 Docker::run()
    @           0x4397f2 mesos::internal::docker::DockerExecutorProcess::launchTask()
    @     0x7f650b10cb61 process::ProcessManager::resume()
    @     0x7f650b10ce5f process::internal::schedule()
    @     0x7f6509e98a40 (unknown)
    @     0x7f65096b5182 start_thread
    @     0x7f65093e247d (unknown)
W0121 08:39:00.023387 11448 logging.cpp:81] RAW: Received signal SIGTERM from process 1470 of user 0; exiting
```

**Comment by luhkevin** [comment]
I'm also seeing this issue, although my PATH var is not empty in the marathon spec.

**Comment by gkleiman** [comment]
@jeroenwijdemans this is a Mesos bug. The Mesos fetcher should use it's own environment, without the variables from `TaskInfo`.

Can you please file an issue in Mesos' bug tracker?
