### ISSUE TITLE
AppDefinition config edit dialog broken

### ISSUE THREAD

**Issue by meichstedt** [mesosphere/marathon#3055]
Tested with Version 0.15.0-SNAPSHOT

1. Create an app via the UI (e.g. shell app `id: sleep`, `cmd: sleep 1000`)
2. Go on the app's configuration tab and click edit
3. Change any of the values (CPU, Memory, Disk Space, Instances)
4. Click _Change and deploy configuration_

results in error `You cannot specify both uris and fetch fields`

**Comment by aldipower** [comment]
Duplicate of #3064
Serious bug recently introduced.

**Comment by meichstedt** [comment]
Ok, I'll close this one then.
