### ISSUE TITLE
Improvements to the Marathon UI state descriptions

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3056]
Thanks for your great work on #2873. I published it now: https://mesosphere.github.io/marathon/docs/marathon-ui.html

Some suggestions for improvements:
- Running: "The application is reported as being successfully running." there can be failing tasks and it will still show as running. So I would be a bit more careful in the wording.
- Deploying: I would clarify that if you do a group deployment all affected apps are marked as deploying until the deployment finishes. So the deployment for that app might already have been finished but other apps in the same deployment have not.
- Delayed: Refer to the backoff configuration options for more explanations.

**Comment by pierlo-upitup** [comment]
Feel free to open a PR ;) Thanks for the feedback, btw.

**Comment by kolloch** [comment]
Oh, I feel very free. Feel free as well :)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3494. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
