### ISSUE TITLE
The app context menu in the app list is hard to find

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#3058]
Feel free to disregard this issue, as it might be just me being stupid.

But knowing that you can now delete groups from the GUI, I was looking for a delete button or something similar and I didn't even notice there is a new context menu, until a frontend developer pointed it out to me. 

cc/ @leemunroe

**Comment by leemunroe** [comment]
Something related came up in user tests. "How do I destroy all applications but keep the group?"

Couple ideas come to mind here.

Adding clarity to the group options (and a delete group option)
![image](https://cloud.githubusercontent.com/assets/15963/12518641/98803106-c0ee-11e5-9805-195e1d9c051e.png)

Adding actions once user is in a group
![image](https://cloud.githubusercontent.com/assets/15963/12518772/5d6ca1f2-c0ef-11e5-87da-3c18eb23d7e5.png)

That being said, we should validate first if people are actually using group actions.

**Comment by pierlo-upitup** [comment]
possible alternative : using a different icon for the context menu. Instead of the three dots, a gear icon that looks more like a button.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2736. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
