### ISSUE TITLE
Improve error message if a version timestamp is included in new app definition

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#3060]
Please a improve the error message if a version timestamp is included in new app definition, as it states that `version` may only be combined with the 'id' field but isn't allowed at all if it's a new app.

**App Definition**

``` json
{
"id": "test",
"cmd": "sleep 999",
"cpus": 0.3,
"instances": 1,
"mem": 9,
"version": "2016-01-21T14:37:29.892Z"
}
```

**Error Message**
`requirement failed: The 'version' field may only be combined with the 'id' field.`

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3565. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
