### ISSUE TITLE
"Unknown" task state is confusing

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3061]
While reviewing #2906 I noticed the "unknown" task state. It confused me.

What is meant is that the health status of these tasks is unknown. The tasks themselves are of course known.

Maybe use "health unknown" or "health?" as status text? @leemunroe ideas?

**Comment by leemunroe** [comment]
Very true. This has come up in user tests.

@kolloch Do you think an icon with tooltip added to the right would help explain what these mean? Like #2907

**Comment by kolloch** [comment]
Yes, that would help :+1: 

In addition, I would still like to come up with a better name.

**Comment by leemunroe** [comment]
"Health Unknown" seems like a good option to me.

![image](https://cloud.githubusercontent.com/assets/15963/12628164/b38989d2-c4f6-11e5-9b9b-20cefb293a77.png)

Would also need changed in the popover.

**Comment by meichstedt** [comment]
What about `Untracked`? Would be just 1 word and might be clear in this context.

**Comment by kolloch** [comment]
@leemunroe I like your proposal but for the sake of the discussion, it is important to include more than just "Healthy, Unhealthy, Health Unknown" in your screen shot (e.g. unscheduled, overcapacity). even unknown would be kind of clear if you assume the "health context".

"Untracked" doesn't have any strong relationship to health in my brain. So I would just be confused again.

"Unmonitored" is a bit better or "Not monitored" because I relate monitoring to health.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3589. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
