### ISSUE TITLE
can't ⌘+C or Ctrl+C on the Marathon page as it launches "create" dialog

### ISSUE THREAD

**Issue by ghostsquad** [mesosphere/marathon#3065]
can't ⌘+C or Ctrl+C on the Marathon page as it launches "create" dialog

**Comment by philipnrmn** [comment]
See also #2033, where we decided it was not reproducible. Unfortunately I have since reproduced it.

**Comment by scalp42** [comment]
Having the same issue here.

**Comment by pierlo-upitup** [comment]
Fixed in https://github.com/mesosphere/marathon-ui/pull/579
