### ISSUE TITLE
The feature of IP-Per-Task could not be seen in UI in Marathon 0.14 release

### ISSUE THREAD

**Issue by yingfeng** [mesosphere/marathon#3068]
Although IP-Per-Task is an experiment feature, but we could not see the corresponding UI to config such features, it's inconvenient for us to use. Could such feature be added to UI immediatedly?

**Comment by Poltergeist** [comment]
Hello @yingfeng,
As you mentioned this feature is as of now a experimental feature, there is a way to see the ip per container in the UI which was introduced in [mesosphere/marathon-ui#450](https://github.com/mesosphere/marathon-ui/pull/450). However such a feature could indeed be developed fairly quickly. If you can make some time to add this feature to the application creation/edit-modal, we would also be very happy to receive a contribution for this.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2924. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
