### ISSUE TITLE
Create Docker integration tests that use bridge networking

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#3070]
The Docker Integration tests added in #1604 don't use bridge networking nor port mappings.

We should implement tests that do the following:
- [ ] Start a very simple Docker app using bridge mode and no port mappings nor health checks.
- [ ] Start a very simple Docker app using bridge mode, port mappings and health checks.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3470. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
