### ISSUE TITLE
Make Docker integration tests work with Docker Machine

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#3071]
The Docker Integration tests are skipped under OS X, because they can't run with Docker Machine.

At least the following changes have to be done so that they work:
- [ ] Update process keeper, so that it forwards the following environment variables from the host OS to the Mesos Slave process run inside the Docker container: 'DOCKER_TLS_VERIFY', 'DOCKER_HOST', 'DOCKER_CERT_PATH',  'DOCKER_MACHINE_NAME'.
- [ ] Set the `--docker_socket` flag of the Mesos Slave to the value of `DOCKER_HOST` environment variable. The format used by Docker Machine is: `tcp://192.168.99.100:2376`. Mesos currently doesn't accept that format, so we have to open a JIRA issue or create a patch.

**Comment by jasongilanfarr** [comment]
Don't think this is still relevant anymore.
