### ISSUE TITLE
Future timestamps

### ISSUE THREAD

**Issue by leemunroe** [mesosphere/marathon#3077]
During usability test noticed that a timestamp was "in the future" and displayed as "in a few seconds".

![image](https://cloud.githubusercontent.com/assets/15963/12521550/0b4437c6-c100-11e5-8565-6ec10963da9d.png)

Does this seem odd? Is it due to misalignment of times? If this happens should we display it as "Just now"?

**Comment by Poltergeist** [comment]
@leemunroe Do you mean it should display {timestamp} (Just now) instead of {timestamp} (in a few seconds) or (Just now)?

**Comment by leemunroe** [comment]
I was thinking {timestamp} (just now)

**Comment by leemunroe** [comment]
Is it possible to change this across the board for timestamps?

Looks great now for the last task failure timestamp, but there are other occurrences:
* Last task failure version
* Last changes config
* Version column on the instances tab

Also can we make it lower case "j" to be consistent.

![image](https://cloud.githubusercontent.com/assets/15963/12750925/6c7613c6-c9ba-11e5-8ee3-5429ed40552c.png)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2958. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
