### ISSUE TITLE
Containers with args []  cannot start on Marathon v.0.13.0

### ISSUE THREAD

**Issue by zoza1982** [mesosphere/marathon#3079]
Trying to start this does not work anymore unless you remove "args" section. Used to work in older version. I am trying to run elasticsearch-mesos and it fails on new version of marathon. I tried inky example from marathon docs ...same thing.

Marathon: v0.13.0
Mesos: 0.25.0
Docker:1.8.2
OS: Centos7

This fails:
```
{
    "id": "inky", 
    "container": {
        "docker": {
            "image": "mesosphere/inky"
        },
        "type": "DOCKER",
        "volumes": []
    },
    "args": ["hello"],
    "cpus": 0.2,
    "mem": 32.0,
    "instances": 1
}
```

This works:

```
{
    "id": "inky", 
    "container": {
        "docker": {
            "image": "mesosphere/inky"
        },
        "type": "DOCKER",
        "volumes": []
    },
    "cpus": 0.2,
    "mem": 32.0,
    "instances": 1
}
```

**Comment by miry** [comment]
I use args with official elasticsearch docker image and it works for me. Do you have some logs?

**Comment by miry** [comment]
```
{
    "id": "inky", 
    "container": {
        "docker": {
            "image": "mesosphere/inky"
        },
        "type": "DOCKER"
    },
    "args": ["hello"],
    "cpus": 0.2,
    "mem": 32.0
}
```

```
Registered docker executor on ec2-54-173-183-11.compute-1.amazonaws.com
Starting task inky.d4185650-c351-11e5-828a-0e0b4bc88447
hello
```

**Comment by Poltergeist** [comment]
@zoza1982 I am currently trying to reproduce this bug. Thanks for providing these JSON's so far. Did you create the application with the ui or with the api? If you've created it with the ui could you provide the version of the ui, it gets shown after pressing `g v`. How exactly does it fail? Could you please provide us with an error-log, if that is available? I'll let you now when I reproduced this problem.

**Comment by zoza1982** [comment]
@Poltergeist  thanks. I did it via api .  Classical curl command.

**Comment by zoza1982** [comment]
I found the issue. Seems related to docker overlay issue. 
```
[root@mi-worker-001 ~]# docker run ubuntu:14.04 /bin/echo 'Hello world'
Error response from daemon: mkdir /var/lib/docker/overlay/75e154f4702378cef256aa5eaad99604fbf7f5efda0f658e01211a865c05e920-init/merged/dev/shm: invalid argument
```

**Comment by Poltergeist** [comment]
Okay so this issue is resolved and can be closed, or not?

**Comment by miry** [comment]
@zoza1982 did you run your docker daemon with `--selinux`?

**Comment by zoza1982** [comment]
@miry  Yes I tried. NO luck.
@Poltergeist  yes this issues can be closed. Not related to Marathon. Sorry for false alarm.
