### ISSUE TITLE
Provide a "View/Tail" option for Error Logs and Output Logs

### ISSUE THREAD

**Issue by ddragosd** [mesosphere/marathon#3081]
With the feature in #2721 users are now able to download the `stderr` and `stdout` straight from Marathon UI which is fantastic.

After using this feature for a while I came to realise that some logs may be a few hundreds of MB. Do we want to force the user to download the whole file just to see the most recent logs ? Or can we/should we provide a "view" option, similar to the one in Mesos, where logs are displayed in a new window that refreshes automatically ?

**Comment by pierlo-upitup** [comment]
Thanks for the feedback @ddragosd! This feature is already on our Roadmap ;)

**Comment by luismfonseca** [comment]
I'd also like this to happen. For me, it's much more useful having a "pailer" like Mesos than a download.

How is this planed to be implemented, could this simply use the mesos "pailer" directly? I can work on this feature if you guys want.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2986. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
