### ISSUE TITLE
Auto-link URLs in validation error messages

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#3082]
The URLs in the error message strings received from the API should be automatically rendered as clickable URLs that open the link in a new window.

**Comment by aldipower** [comment]
Could you give an example? Which error messages do you mean? Thank you.

**Comment by pierlo-upitup** [comment]
It shouldn't really matter as the idea is that any URL should be clickable, if shown within a validation error by the API.

Here's one, though:

<img width="713" alt="screen shot 2016-01-25 at 10 39 14" src="https://cloud.githubusercontent.com/assets/1078545/12547317/f650b1d0-c34f-11e5-87c5-ca8c1de5a9ba.png">

**Comment by aldipower** [comment]
OK, got it. 
Nitpicking: This error message is from the UI, not from the API.

**Comment by pierlo-upitup** [comment]
Yeah bad example :) - of course we want the same behaviour also for those in the UI codebase.
