### ISSUE TITLE
HA Proxy Marathon Bridge  could not be found

### ISSUE THREAD

**Issue by miry** [mesosphere/marathon#3086]
In the old/new documentation there is old link to master branch. According new changes it was moved to the examples folder.

```
$ curl https://raw.githubusercontent.com/mesosphere/marathon/master/bin/haproxy-marathon-bridge
Not Found
```

I think first should be changed docs than move the script to correct folder.

**Comment by meichstedt** [comment]
@miry is referencing the open docs: https://open.mesosphere.com/tutorials/service-discovery/

There are also several locations in the Marathon-internal docs that reference `./bin/haproxy-marathon-bridge` and should be fixed as well.

**Comment by meichstedt** [comment]
Thanks for pointing that out @miry!

**Comment by tobilg** [comment]
I thought the perferred way of service discovery would now be Mesos DNS? Has this changed?

**Comment by aquamatthias** [comment]
@sascala the haproxy-marathon-bridge script has been deprecated. We suggest https://github.com/mesosphere/marathon-lb instead of this simple script. The script is still accessible and has been moved from the `bin` folder to the `examples` folder. Our documentation should reflect that. Can you please change our documentation accordingly? Thanks!

**Comment by tobilg** [comment]
@aquamatthias Thanks for the fast feedback. I'd be interested what the "official" position is on Mesos DNS, as we're currently using it for service discovery. Is it correct to say that Mesos DNS should be used if Marathon is not the only framework which launches apps, and `marathon-lb` for Marathon-only architectures?

I'd really appreciate if the docs at https://mesosphere.github.io/marathon/docs/service-discovery-load-balancing could also say something about `marathon-lb` deployment. If I understand it correctly, one could launch the Docker image on each Mesos Slave? If so, what would be the configurations for the other apps launched through Marathon which should use the service discovery? Examples would be great! @sascala Thanks a lot in advance.

**Comment by aquamatthias** [comment]
There is no mesosDNS xor marathon-lb from my point of view. A lot of users use both.
Interesting articles using marathon-lb are here: https://mesosphere.com/?s=marathon-lb

**Comment by sascala** [comment]
I'll put this in next week's sprint.

**Comment by sascala** [comment]
https://github.com/mesosphere/open-docs/commit/d67b8a12f24ee22373e8d25f426b93d7a7bb219b
