### ISSUE TITLE
Replace obsoleted uris field with newly introduced (>= 0.15) fetch field

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#3087]
As discussed in https://github.com/mesosphere/marathon-ui/pull/574#commitcomment-15606806

FTM, marking this issue as `blocked by` as this change isn't reflected in the docs.

**Comment by aldipower** [comment]
FTR
There is a junction implemented for backwards compatibility with the uris-attribute at the application model.
https://github.com/mesosphere/marathon-ui/blob/master/src/js/stores/transforms/AppFormModelPostProcess.js#L50

The comments should be remove, the junction itself not.

**Comment by pierlo-upitup** [comment]
The docs are now updated to reflect the deprecation https://github.com/mesosphere/marathon/pull/3097

**Comment by pierlo-upitup** [comment]
#### Update
The change introduced in https://github.com/mesosphere/marathon/pull/2953 essentially means that 
Marathon (>= 0.15) considers `fetch` and `uris` essentially as two different "views" on the same field behind the scenes. Apps are guaranteed to have these 2 fields in sync. 

I propose to ignore the `fetch` field completely in the UI, at least for 0.15.x. 
Moving forward, we should consider the idea of adopting the `fetch` field and ignore `uris`.

**Comment by gkleiman** [comment]
Looks like this was fixed by mesosphere/marathon-ui#594
