### ISSUE TITLE
Delayed applications can appear to be running

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#3092]
Originally discovered in this environment:
10-node cluster, Mesos 0.25, Marathon 0.14.0, Marathon UI 0.14.2

~~To reproduce:~~
- Create two app configurations which are greedy of resources (eg require a large number of CPUS). -
- Scale both to zero, then scale both to thousands of instances. 
- Repeatedly refresh the app list. The task count will be correct (0/3000), but the application will sometimes appear to be delayed (correct behaviour) and sometimes running (incorrect behaviour). 

Alternative way to reproduce:
- Create one app configuration which needs more resources than are available
- Stop its deployment
- It will appear to be in 'Running' state.

**Comment by philipnrmn** [comment]
CC @jgehrcke who discovered this bug

**Comment by gkleiman** [comment]
I observed an app in status `Running` which had only one task, which was `Staging` and not `Unknown` or `Healthy`.

**Comment by philipnrmn** [comment]
I'm struggling to reproduce this bug using the current marathon and marathon-ui master. @glkeiman can you provide any more information on how to force that bad state?

**Comment by philipnrmn** [comment]
Appears to be behaving itself:
![LGTM](https://s3.amazonaws.com/f.cl.ly/items/2N2G451s0y311T1v1R0i/Screen%20Recording%202016-04-06%20at%2006.18%20PM.gif?v=acbaffd7)

**Comment by philipnrmn** [comment]
H/T @orlandohohmeier for helping me out with reproducing this one, I've edited the original post to reflect this. 

The actual bug seems to be that after a deployment is stopped, even if an instance was never created, the groups endpoint returns `instances: 1`, which is incorrect.

**Comment by pierlo-upitup** [comment]
This was fixed by https://github.com/mesosphere/marathon-ui/issues/733
