### ISSUE TITLE
TooltipComponent is too tightly coupled with its usage

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#3094]
This component either needs to be renamed or it needs to get rid of its references to the Mesos log download usage. 

https://github.com/mesosphere/marathon-ui/blob/master/src/js/components/TooltipComponent.jsx#L47

**Comment by pierlo-upitup** [comment]
cc @orlandohohmeier

**Comment by orlandohohmeier** [comment]
Hihi. :smile:  I could have sworn that I already introduced an extra message prop to define the tooltip message... But no, I must have forgotten. :innocent: Let's introduce a message prop and decouple this component form its usage.
