### ISSUE TITLE
Bind the host's IP address inside the container

### ISSUE THREAD

**Issue by magcius** [mesosphere/marathon#3111]
When using e.g. haproxy-marathon-bridge on slaves, containers can't actually directly connect to `localhost:servicePort`, because localhost refers to the `docker0` interface, not the host's interface. Containers can connect to the host with `172.17.42.1`, but this isn't guaranteed to be stable.

Docker has support for `--add-host`. It would be nice if Mesos / Marathon could bind the host inside the container for service discovery reasons.

Or have I missed any easier way to use haproxy-marathon-bridge for service discovery?

**Comment by ejether** [comment]
Inside the container the environment variable $HOST is set to the `hostname` of the host. If you have DNS setup, you can use that inside the container. You can add a dns server using `--dns` in in the parameters

**Comment by magcius** [comment]
$HOST requires app logic whereas having it in `/etc/hosts` would be nicer, but OK.

**Comment by ejether** [comment]
I agree that it would be a nice feature but also wanted to share how we are getting around it with our apps.

**Comment by Poltergeist** [comment]
There is also the [marathon-lb](https://github.com/mesosphere/marathon-lb) project which hast more advanced features in comparison to the haproxy-marathon-bridge. I hope this solves your question.

**Comment by magcius** [comment]
How do Docker containers running inside Mesos connect to the marathon-lb instance to access other services, though?

**Comment by ejether** [comment]
We are running the marathon-lb a docker container on all our slaves in host networking mode. 
Without any extra configuration it will function just like haproxy-marathon-bridge but will allow you to extend the functionality quite a bit with some extra configuration.

We use a variety of methods to inform the container of the hosts address. 
* configure the service in the container to use the host ip address with and environment variable (The majority of our services use this and we consider it a bit hacky but it works reliably)
* use the --add-host flag on the docker run command
* we are looking into mesos-dns and the --dns flag in the docker command

**Comment by magcius** [comment]
Mesos doesn't allow you to add `--add-host` / `--dns` in its slave, does it? I don't see anything in https://github.com/apache/mesos/blob/master/src/docker/docker.cpp

We'll modify our applications to expand $HOST. Thank you.

**Comment by ejether** [comment]
You can use the `parameters` block in your json post body.

In this example below (borrowed from https://mesosphere.github.io/marathon/docs/native-docker.html
and edited) you can see how the `parameters` could be used to `--add-host` or `--dns`

```
{
    "id": "privileged-job",
    "container": {
        "docker": {
            "image": "mesosphere/inky",
            "privileged": true,
            "parameters": [
                { "key": "hostname", "value": "a.corp.org" },
                { "key": "volumes-from", "value": "another-container" },
                { "key": "dns","value":"8.8.8.8"},
                { "key": "add-host","value":"mesos-slave:ip-of-slave"},
            ]
        },
        "type": "DOCKER",
        "volumes": []
    },
    "args": ["hello"],
    "cpus": 0.2,
    "mem": 32.0,
    "instances": 1
}
```

**Comment by xiaods** [comment]
if the app is scaling to 2, the add-host can't dynamically with shell.

```
# docker run -it --add-host localhost:$(ifconfig eth0 | grep "inet addr" | cut -d ':' -f 2 | cut -d ' ' -f 1) ubuntu:15.10 cat /etc/hosts
172.17.0.4      9cc54e76d647
127.0.0.1       localhost
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters
10.3.10.32      localhost
```

**Comment by ejether** [comment]
I don't know if I understand what you are saying but the add host is only being used to add the ip of the docker host. If the app is scaling, then the add-host flag will get run on both containers.

You may run into a lot of problems if you have localhost declared twice in your /etc/hosts file.

**Comment by xiaods** [comment]
@ejether thanks for your reminder.

**Comment by ejether** [comment]
In my experience, it does work to add it as a parameter in marathon.

**Comment by xiaods** [comment]
@ejether how can we support it?

**Comment by ejether** [comment]
That is really up to you and affected by what you're automation infrastructure consists of.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3131. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
