### ISSUE TITLE
How could I get all machine ports usage info ?

### ISSUE THREAD

**Issue by xianlubird** [mesosphere/marathon#3114]
Marathon can assign **hostPort** in container field. But if the cluster which is managed by marathon has no more port that I assign, then marathon can not deploy this app.  So I want to know, which port in this cluster is free and I can assign them directly and do some other thing. I know marathon get port info from mesos-slave offer , so how should I get cluster ports usage info? mesos or marathon ? Could someone give me some idea? Thank you.

**Comment by scalp42** [comment]
I could be totally wrong but it's easy to get Mesos slave configured range of ports as it's an attribute on the slave, and parsing all tasks in Marathon using the tasks endpoint.

**Comment by xianlubird** [comment]
@scalp42 But the task can only get this app's port status, I want to know all the port status in the cluster which include many machines and maybe some machine even has not a app or task.

**Comment by Poltergeist** [comment]
As stated in the [API](https://mesosphere.github.io/marathon/docs/generated/api.html#v2_tasks_get) the tasks endpoint is getting all the tasks in the marathon cluster. This data can easily be handled and parsed to build a list of all the ports which are in use.

**Comment by xianlubird** [comment]
Yes, Thank you
