### ISSUE TITLE
Improve the usability of the label dropdown feature

### ISSUE THREAD

**Issue by leemunroe** [mesosphere/marathon#3124]
The label dropdown is not usable for labels longer than 10 characters, which tends to be most labels. This has been identified in usability tests and emails from users pointing this out.

Here is what I would suggest, using the existing UI and styling:

1. Increase the width of the dropdown - make it auto and give it a max-width of ~ 400px
1. When a label is selected, move it to the top
1. Change the dropdown text to "x Labels Selected" when at least one is selected
1. If there are no labels then don't show the dropdown

Thoughts?

Before
![image](https://cloud.githubusercontent.com/assets/15963/12662870/1f92b8c4-c5d8-11e5-9d47-0a269c12f578.png)

After
![image](https://cloud.githubusercontent.com/assets/15963/12662863/13e0be22-c5d8-11e5-85c5-1cb460b74ada.png)

**Comment by pierlo-upitup** [comment]
Yeah, that could work.
