### ISSUE TITLE
Some question about hostport and serviceport ...

### ISSUE THREAD

**Issue by xianlubird** [mesosphere/marathon#3125]
I know that serviceport is unique in the cluster and a machine can run many hostport . But if I create a app which assign a hostport and the same serviceport, Does marathon will make sure other machine also will free this port for waiting my this app's task scale ?   In a word, does marathon will make sure hostport is unique in the cluster like serviceport.

**Comment by Poltergeist** [comment]
Ports are defined per cluster [ports in the docs](https://mesosphere.github.io/marathon/docs/rest-api.html#ports-array-of-integers). So if you set a port to 0 this port is reserved for the application on a cluster level.

**Comment by xianlubird** [comment]
Yes, Thank you
