### ISSUE TITLE
Show groups as part of search results

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#3127]
We should also display groups as part of the search results, not just applications.

![image](https://cloud.githubusercontent.com/assets/1078545/12744164/fcc4ba5e-c992-11e5-81cb-42fbd5f8ab2b.png)

**Comment by Poltergeist** [comment]
This sounds interesting, should only match the direct match or all descending groups as well.
Example:
```
git
  \_applications
        \_assigner
             \_marathon-ui
             \_marathon
```
If know the search is executed for `git` would the list be:
- git
- git/applications
- git/applications/assigner
- git/applications/assigner/marathon
- git/applications/assigner/marathon-ui

I think only groups should be shown where the last segment is matching the filtertext plus the applications in the descending group for the example:
- git
- git/applications/assigner/marathon
- git/applications/assigner/marathon-ui

**Comment by pierlo-upitup** [comment]
As we are already showing results for apps whose path matches the search term, the idea is to add to the results list (possibly to the top) *only* the exact match for any of the groups in the path. So in your example, the 2nd set of results is what I'd expect.

**Comment by orlandohohmeier** [comment]
Just to make sure, we're all on the same page... Consider the following apps, how should the match look like?

1. ⚙/foo/apps/bar/app
2. ⚙/apps/bar/app 
3. ⚙/apps/foo/app

Searching for "apps"  would result in:
* 📁/apps
* 📁/foo/apps
* ⚙/foo/apps/bar/app
* ⚙/apps/bar/app 
* ⚙/apps/foo/app

Searching for "foo" would result in:
* 📁/foo
* 📁/apps/foo
* ⚙/foo/apps/bar/app
* ⚙/apps/foo/app

Searching for "app" would result in:
* 📁/apps (fuzzy match)
* 📁/foo/apps  (fuzzy match)
* ⚙/foo/apps/bar/app
* ⚙/apps/foo/app
* ⚙/apps/bar/app 

Is this what you guys had in mind?
