### ISSUE TITLE
Loading state for task working directory

### ISSUE THREAD

**Issue by leemunroe** [mesosphere/marathon#3128]
When a task's working directory is loading we should show a loading state instead of an empty state.

Currently we show "Currently no files available". 

Instead show "Loading files..."

![dir](https://cloud.githubusercontent.com/assets/15963/12751518/ed225f86-c9bd-11e5-8628-d52387219863.gif)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3440. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
