### ISSUE TITLE
What's a better solution to logs not being retrieved?

### ISSUE THREAD

**Issue by leemunroe** [mesosphere/marathon#3129]
Sometimes we have trouble retrieving logs or directory info from mesos sandbox.

Currently we show the user an icon/download option and then tell the user to click to retry if it doesn't work. 

At this point do we know that it won't work? What would be a better experience here? Should we show the "Working directory" at all if there is nothing retrieved?

![log-fail](https://cloud.githubusercontent.com/assets/15963/12751834/aac7d75e-c9bf-11e5-926a-14f5f8078a76.gif)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3657. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
