### ISSUE TITLE
Proxy logs endpoints from mesos slaves

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#3138]
See backstory: https://github.com/mesosphere/marathon/issues/2972#issuecomment-171485134

**UPDATE** by pierlo-upitup : adding inline description from linked comment.

Sandbox is not just about logs, although they are the most important thing. I like the proposal, but this would require mesos (masters and slaves) and marathon to work over the same protocol (be that HTTP or HTTPS) for user. This is not always possible. Slaves usually live in the private trusted network that users don't have access to. Often slaves are HTTP, but Marathon is HTTPS.

The obvious solution is to make it work on the same protocol. Another solution would be to proxy logs through Marathon to avoid the need to expose mesos endpoints to users.

Another thing I just remembered: people often interested not in sandbox, but in the page one level up, where executor stats live and you can see actual resource usage. This link could be better than sanbox. Actual resource usage can be shown in Marathon UI to minimize the need to go to Mesos UI. That'd be great, but has the same drawbacks as logs from the sandbox.

Hope this helps.

**Comment by pierlo-upitup** [comment]
cc @air

**Comment by cah-ghernandez** [comment]
Do we have an ETA on this? Is it being considered in the near future?

**Comment by damomurf** [comment]
This limitation causes us huge issues also. Our slave endpoints aren't accessible directly to a user's browser, so currently we're running in an environment where developers are simply unable to access logs or other information.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3094. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
