### ISSUE TITLE
breaking API change on portIndex?

### ISSUE THREAD

**Issue by timoreimann** [mesosphere/marathon#3140]
We recently upgraded from Marathon 0.11 to 0.14.1 and noticed that all our deployments were failing. Looking at the logs, we found this:

```
[Unhealthy(service.1d56c262-c9ca-11e5-a454-0242c88d2ac8,2016-02-02T16:00:05.537Z,Missing/invalid port index and no explicit port specified,2016-02-02T16:30:29.359Z)] (mesosphere.marathon.health.HealthCheckActor:marathon-akka.actor.default-dispatcher-7)
```

We did not specify the port index. To my understanding, it used to default to 0. Once we passed it explicitly, deployments went through just fine.

I scanned through the release notes but couldn't find any mentioning of a breaking API change in this regards. The only thing I could find was [a section](https://github.com/mesosphere/marathon/blob/master/changelog.md#health-checks-allow-port-instead-of-portindex-1) describing the additional `port` field. I understand this as supposedly non-breaking, however. The description of [this commit](https://github.com/mesosphere/marathon/commit/38ce1b3f1be6ad99379fa9f859bb8df59451c1ac) from last November also indicates that backwards compatibility should be maintained.

Was this a deliberate API modification, and did I miss a note somehow? Or rather an inadvertent change?

Side note: The [deprecated REST API documentation](https://mesosphere.github.io/marathon/docs/rest-api.html) says that `portIndex` defaults to zero. I can't find any description of the field in the [new documentation](https://mesosphere.github.io/marathon/docs/generated/api.html) though. Where did this piece of specification go?

Thanks.

**Comment by drewrobb** [comment]
I also observed this same breaking change in moving from 0.13.1 to 0.14.1 or 0.15.0.

**Comment by gkleiman** [comment]
@timoreimann thanks for reporting this. We tried to maintain backwards compatibility when we introduced the `port` field, so this is a bug.

**Comment by timoreimann** [comment]
@gkleiman I see you did not set the 0.14.0 milestone. Do I understand correctly that a fix will be patched into 0.15 and future releases, but not 0.14? If so, why not?

**Comment by gkleiman** [comment]
@timoreimann can you please provide an app definition that works on v0.13.1, but fails when migrating to v0.14.1?

The following worked for me:

1. Start Marathon v0.13.1
2. Cleanup the state, by doing: `http DELETE :8080/v2/groups`
3. POST the following to /`v2/apps`:

```json
{
  "id": "/foo",
  "instances": 1,
  "healthChecks": [
    {
      "path": "/",
      "protocol": "HTTP",
      "gracePeriodSeconds": 10,
      "intervalSeconds": 10,
      "timeoutSeconds": 5,
      "maxConsecutiveFailures": 3
    }
  ],
  "cmd": "python -m SimpleHTTPServer $PORT"
}
``
4. Wait for health checks to pass.
5. Upgrade to Marathon v0.14.1.
6.  `foo` is still healthy.
7. Trigger a deployment by doing `PUT /v2/groups` with the following:
```json
{
  "scaleBy": 2
}
```
8. `foo` is scaled up and the health check passes.

**Comment by timoreimann** [comment]
@gkleiman Our app definitions are fairly encapsulated by tooling. Will try to extract the actual Marathon request payload and get back to you.

FWIW, we upgraded from 0.11 to 0.14 (but @drewrobb mentioned he also observed the same behavior when updating from 0.13) and are solely using `/v2/apps` (no groups).

**Comment by gkleiman** [comment]
@timoreimann thanks for getting back to me so quickly.

I tried the following, but still didn't manage to reproduce this:

* Starting Marathon vv0.11.1in the first step, replacing step 7 with `PUT :8080/v2/apps/foo` with the following content:

```json
{
  "id": "/foo",
  "instances": 2
}
```

**Comment by moderation** [comment]
I'm having a similar issue. In 0.14 the following health check would work. This is for a Docker container with HOST networking exposing a number of ports including 9090.

```javascript
"healthChecks": [  
  {  
    "protocol": "HTTP",  
    "path": "/_haproxy_health_check",  
    "port": 9090  
  }  
```
After upgrading to 0.15, this now returns the error:

`Health check port indices must address an element of the ports array or container port mappings.`

**Comment by gkleiman** [comment]
I  managed to reproduce this issue, doing the following:

1) Start Marathon v0.15.1
2) POST /v2/apps

```json
{
  "id": "/foo",
  "instances": 1,
  "healthChecks": [
    {
      "path": "/",
      "protocol": "HTTP",
      "gracePeriodSeconds": 10,
      "intervalSeconds": 10,
      "timeoutSeconds": 5,
      "maxConsecutiveFailures": 3
    }
  ],
  "cmd": "python -m SimpleHTTPServer $PORT"
}
```

3) PUT /v2/apps

```json
[{
  "id": "/foo",
  "healthChecks": [
    {
      "path": "/",
      "protocol": "HTTP",
      "gracePeriodSeconds": 10,
      "intervalSeconds": 10,
      "timeoutSeconds": 5,
      "maxConsecutiveFailures": 3
    }
  ]
}]
```

Working on a fix right now.

**Comment by timoreimann** [comment]
Thanks for the fix. May I ask if it will be available in patch releases of 0.14 and 0.15?

**Comment by timoreimann** [comment]
Can someone respond to my question please? Possibly @gkleiman, @aquamatthias, or @meichstedt?

Thank you.

**Comment by gkleiman** [comment]
@timoreimann the release process for Marathon v0.15.1 started yesterday and it includes the fix for this problem.

The commit has also been cherrypicked in the `releases/0.14` branch, so I think that the intention is to do a Marathon v0.14.1 release including the fix. @aquamatthias  should be able to confirm this.

**Comment by timoreimann** [comment]
@aquamatthias I saw the 0.15.1 announcement but nothing in regards to a 0.14 bugfix release. Is it scheduled for some time already?

**Comment by meichstedt** [comment]
Hey @timoreimann I just hit the release button – the docker image and native packages for 0.14.2 should be available soon.

**Comment by timoreimann** [comment]
@meichstedt Thanks Matthias!

I just noticed something else: Commit 38ce1b3f1be6ad99379fa9f859bb8df59451c1ac also [changed the documentation](https://github.com/mesosphere/marathon/commit/38ce1b3f1be6ad99379fa9f859bb8df59451c1ac#diff-add0ffc408bf06c887232738b1ddb664L79) for `portIndex`'s default value from `0` to `None` and added a requirement that either `port` or `portIndex` must be specified. From my perspective, this isn't correct, and the documentation should be changed to say that `portIndex` with a value of 0 is (still) the default, but it may be overridden by providing a `port` value instead.

If you agree, then I'd be happy to provide a PR. Thanks!

**Comment by meichstedt** [comment]
Hey @timoreimann `portIndex` only defaults to `0` if no `port` is specified and the health check protocol is either `TCP` or `HTTP`. The validation is clear: you need to specify _either portIndex or port_, and the docs should reflect that. Technically, the default is `None`, but a fallback default of `0` will applied to ensure backwards compatibility. From that POV, I wouldn't say that `portIndex` in general defaults to `0` – that would imo be misleading, too. I know this is nit picking, and I agree, the docs should make that clear. So we'd be happy if you provide a PR :)

**Comment by timoreimann** [comment]
@meichstedt, thanks for the explanation. I'll put together a PR and try to clear things up. :-)
