### ISSUE TITLE
Don't restart tasks on HTTP/TCP health check updates

### ISSUE THREAD

**Issue by fengyehong** [mesosphere/marathon#3143]
Currently modification of health checks of an app will restart all its tasks.

In fact as HTTPS, HTTP, TCP health checks are done by marathon master, there is no need to restart tasks(if COMMAND health check not changed)

So is it possible Marathon can do this?  HTTPS/HTTP/TCP health check modifications don't lead to running tasks restart. 

This makes health check more flexible, so user can change health check strategy with no side effect.

Thanks.

**Comment by gkleiman** [comment]
@fengyehong thanks for the issue. I took the liberty to update the title.

Our longer-term goal is to delegate HTTP/TCP health checks to Mesos, once that's supported. In that case restarting the tasks will still be needed. But I will add this request to our backlog for future evaluation/prioritization.

**Comment by jasongilanfarr** [comment]
I don't believe this is really on the table. Future v3 may add support for "these json fields don't require a task restart", but this is out of scope for v2
