### ISSUE TITLE
SBT fails to download api-console.jar when launching container from Dockerfile.development

### ISSUE THREAD

**Issue by natemurthy** [mesosphere/marathon#3151]
As of commit `255061e` on the master branch, executing `./bin/run-tests.sh` fails with
```
[warn]     ::::::::::::::::::::::::::::::::::::::::::::::
[warn]     ::              FAILED DOWNLOADS            ::
[warn]     :: ^ see resolution messages for details  ^ ::
[warn]     ::::::::::::::::::::::::::::::::::::::::::::::
[warn]     :: mesosphere.marathon#api-console;0.1.1!api-console.jar
[warn]     ::::::::::::::::::::::::::::::::::::::::::::::
sbt.ResolveException: download failed: mesosphere.marathon#api-console;0.1.1!api-console.jar
```
This happened 1 of 2 times for me. Second time download succeeded.

**Comment by gkleiman** [comment]
Hi @natemurthy, Mesosphere recently moved to another CDN provider, it looks like there was a temporary glitch during the migration.

Please re-open this if this happens to you again.

**Comment by natemurthy** [comment]
I attempted to build again and download succeeded again this third time around.
