### ISSUE TITLE
Create Integration Test Suite, that can test mesos nightly and RC Releases

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#3153]
Marathon depends on Mesos. 
There is a Mesos release almost every 4 weeks.
It should be very easy to test, if the new Mesos version works correctly with Marathon.

Sur plus feature: this test suite should be able to run on different mesos versions.
With this we also could test new Marathon releases against older mesos versions.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2892. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
