### ISSUE TITLE
Create/Edit modal: replace empty duplicable rows with "add" button by default

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#3156]
All of the duplicable row fields in the Create/Edit modal need to behave like the Persistent Local Volumes as portrayed in the mockup. This should reduce visual clutter for the default empty state.

The fields in question are:
- Docker > Port Mappings
- Docker >  Parameters
- Docker > Volumes
- Environment Variables
- Labels
- Health Checks
- Persistent Local Volumes (https://github.com/mesosphere/marathon/issues/3155)

Example behaviour (as introduced in the Volumes mockup):

![create](https://cloud.githubusercontent.com/assets/1078545/12810890/5052efb4-cb29-11e5-8962-8d0f72c0d214.gif)

cc @leemunroe

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3006. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
