### ISSUE TITLE
Show 400 error for Constraints field

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#3160]
There is a known bug in the service layer in 0.15 that prevents valid constraints from being accepted. 

We currently do not show errors for the `constraints` field. 

```
{"cpus":0.1,
"mem":16,
"disk":0,
"instances":1,
"id":"test",
"cmd":"sleep 1",
"constraints":[["constraint","unique"]]}
```
is valid, but not accepted, but in the UI we ignore the `400` error returned: 

```
{"message":"Invalid JSON","details":[{"path":"/constraints(0)","errors":["Constraint definition must be an array of strings in format: <key>, <operator>[, value]"]}]}
```

This server-side error should be shown in the modal.

**Comment by pierlo-upitup** [comment]
The related error in the service layer is https://github.com/mesosphere/marathon/issues/3161

**Comment by aldipower** [comment]
To be more precise, the 400 error isn't ignored in the UI, but the error-path returned isn't mapped correctly to the constraints field.

Adding this line to the `responseAttributePathToFieldIdMap` in the `AppsFormStore` should do the trick:
`
"/constraints({INDEX})": "constraints",
`

There is already a mapping with the path `/constraints`, but the index `(0)` returned is kind of unexpected.

**Comment by pierlo-upitup** [comment]
Yep, was about to add that. Thanks!

**Comment by gkleiman** [comment]
Just a clarification, the request is actually invalid, because Marathon is case-sensitive and the right operator would be `UNIQUE`.

**Comment by pierlo-upitup** [comment]
Thanks @gkleiman – i believe the right approach to solve the usability issue here would be to return a more meaningful message from the server.
