### ISSUE TITLE
Consider not reversing the task ID for the HostName

### ISSUE THREAD

**Issue by SEJeff** [mesosphere/marathon#3163]
The [task builder](https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/mesos/TaskBuilder.scala#L102) code calls [toHostname](https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/state/PathId.scala#L66) which takes the path like structure of a task id, reverses it, and joins it back into a string.

This turns a marathon task id such as:
`/linux/hastebin/redis`

Into a mesos task with a name such as `redis.hastebin.linux`, and a hostname such as `redis-hastebin-linux.marathon.mesos` from mesos-dns.

Since we're using the first bit as the team that is running the application (and enforcing this via external systems), it would be nicer if there was a way to make the hostname from mesos-dns something more like: `linux-hastebin-redis.marathon.mesos`.

I realize this is relatively deep in the marathon code, but it would be excellent if there was a way to make this configurable.

**Comment by gkleiman** [comment]
@SEJeff thanks for the suggestion!

**Comment by kamaradclimber** [comment]
I am also interested in this since it makes any service discovery system confused.

**Comment by kamaradclimber** [comment]
Changing the task name seems easy to do in the code but the migration will be probably quite painful. How could we solve that ?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3008. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
