### ISSUE TITLE
Marathon 0.15 error on bad application id is really bad

### ISSUE THREAD

**Issue by cmaloney** [mesosphere/marathon#3164]
![image](https://cloud.githubusercontent.com/assets/751088/12832245/a462a026-cb4d-11e5-86ac-7e391642b9c6.png)

In Marathon 0.14 this told me the ID was invalid with the validation rules.

**Comment by pierlo-upitup** [comment]
Tanks @cmaloney – I can only reproduce this if copy-pasting the value, instead of typing it. Is that what you mean?

**Comment by cmaloney** [comment]
I typed it in in that case, but had moved focus to another field before pressing create. Don't recall the exact order.

**Comment by pierlo-upitup** [comment]
I see what you mean now. `_` is not an allowed character in the `id` field, but we don't enforce this validation rule. Additionally, the UI fails to parse the error returned by the server as it does not conform with the rest of error messages (it returns a `attribute` key instead of `path`). Will dive deeper, thanks a lot for your help.

**Comment by pierlo-upitup** [comment]
Scrap that, I traced this down to a change in the service layer (https://github.com/mesosphere/marathon/pull/2975/files#diff-7bb478205fd47f472265c276e29b7cfaR227). The UI code responsible for parsing the error response needs to be updated to reflect the new schema (`errors` became `details`).

**Comment by cmaloney** [comment]
Is it possible to add some sort of integration test to ensure this is working at a basic level before release / people change both codebases as needed?

**Comment by pierlo-upitup** [comment]
@cmaloney absolutely. We are currently mocking API responses in our behavioural tests. As shown here, that's not gonna protect us from unexpected/undocumented changes in the API, unfortunately. There is a story to capture that, we only need to adjust priorities for it. https://github.com/mesosphere/marathon/issues/2911
