### ISSUE TITLE
GET /v2/apps/{app_id}/tasks should return service ports too

### ISSUE THREAD

**Issue by ssk2** [mesosphere/marathon#3165]
From [the documentation](https://mesosphere.github.io/marathon/docs/generated/api.html#v2_apps__app_id__tasks_get), it looks like the only way to get the service port associated with a given task is to use the `text/plain` response when querying `/v2/apps/{app_id}/tasks`:
![image](https://cloud.githubusercontent.com/assets/355705/12834816/68583dae-cb5f-11e5-936b-1abe20f12b6c.png)

At the very least, full port information should be returned in the `application/json` response.

Similar to #1609 and related to #670.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3348. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
