### ISSUE TITLE
Surface "Edit Configuration" button in application detail page and add keyboard shortcut.

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#3170]
It would be really nice to have `e` as a shortcut for bringing up the configuration modal from an app detail page. At present it takes two clicks - once to configuration, once to edit. 

I would suggest `E` for advanced editing mode.

**Comment by pierlo-upitup** [comment]
+1 
Not just that, I really do believe that the Edit button is too buried. As discussed briefly with @leemunroe , we should probably surface the Edit button to be closer to the other action buttons (both in the detail page as well as inside the contextual dropdown menu in the app list).

**Comment by philipnrmn** [comment]
Strongly agreed ^^

**Comment by leemunroe** [comment]
+1

Where do you think it should go? 

![image](https://cloud.githubusercontent.com/assets/15963/12884511/109146d0-ce5f-11e5-9150-afa1b32e1e25.png)

![image](https://cloud.githubusercontent.com/assets/15963/12884521/261c051c-ce5f-11e5-8dde-05a86d4b3638.png)

![image](https://cloud.githubusercontent.com/assets/15963/12884533/3d71431c-ce5f-11e5-9461-b2fb0d390631.png)

/cc @cleverroffey

**Comment by pierlo-upitup** [comment]
1 and 3 works best for me. Regarding no. 2, in extra-wide screens the Edit Configuration button will be too far away from the rest.

**Comment by philipnrmn** [comment]
Personally I like 2 best because that's where I expect to find the button.

**Comment by gkleiman** [comment]
Option 1 + moving the "Restart" button into the Context menu would work good for me.

**Comment by leemunroe** [comment]
I like @gkleiman's idea of moving restart to dropdown and having an edit button with the other actions.

What do you think the button text should be?
* Edit Application
* Edit Configuration
* Edit

**Comment by aldipower** [comment]
Great issue/ideas!

For better understanding, the new surfaced edit button is additional?
Because every app version has an edit button. What will happen to those? Let them as they are?
![edit](https://cloud.githubusercontent.com/assets/859154/12912887/af1d3b26-cf1b-11e5-94c5-d7319ade22d8.png)

**Comment by leemunroe** [comment]
@aldipower Correct, this should be additional.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3510. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
