### ISSUE TITLE
"Apply" button is broken (sending both uris and fetch)

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#3172]
The `uris` and `fetch` fields can't be PUT to the API at the same time. This produces an uncaught `400` error when the user clicks on the `apply` button.

We need to make sure we are not sending both `fetch` and `uris` when applying an app's older version.

UPDATE: this refers to the Apply button in the Application Versions list.

Acceptance criteria for considering this fixed:
 - `uris` and `fetch` are never simultaneously sent from the UI
 - the app config JSON editor never shows fields which aren't part of the JSON schema (eg `tasks`)
 - a POST request resulting from creating an app only sends fields which are set
 - a PUT request resulting from editing an app configuration only sends fields which have changed

**Comment by philipnrmn** [comment]
I pontificated a little about this in a comment on a PR [here](https://github.com/mesosphere/marathon-ui/pull/598#issuecomment-180335416)

**Comment by pierlo-upitup** [comment]
Yep, thanks for linking the original discussion!

**Comment by aquamatthias** [comment]
@pierlo-upitup @philipnrmn  can we close this issue?

**Comment by pierlo-upitup** [comment]
@aquamatthias –  @philipnrmn is on it.

**Comment by philipnrmn** [comment]
Edited the original ticket to add clear acceptance criteria.

**Comment by aquamatthias** [comment]
The question is: is the fix version still 0.15?

**Comment by philipnrmn** [comment]
I would say that we should release a 0.15.n bugfix release after this is merged.

**Comment by pierlo-upitup** [comment]
**Note** – this bug has a quickfix in branch `release/0.15.5` ready to be released.

**Comment by rhruiz** [comment]
Hi folks,

it seems that this bug is back on marathon 1.3.3 / marathon-ui 1.1.5, by applying an old version of an app's configuration I get a `400 Bad request` in the web developer tools with the following response:

```{
    "message": "Invalid JSON",
    "details": [
        {
            "path": "",
            "errors": [
                "You cannot specify both uris and fetch fields"
            ]
        }
    ]
}```

**Comment by PotHix** [comment]
What do we need to do to reopen this issue?
