### ISSUE TITLE
Consider making servicePort optional

### ISSUE THREAD

**Issue by cmluciano** [mesosphere/marathon#3176]
Currently we don't use the servicePort for any of our applications since we use separate service discovery tooling. Since we don't specify this port and the code currently assigns one automatically, we started to hit the upper limits of the current port range for `--local_port_min and --local_port_max`. 

It would be great if this could be turned off or adjusted so that servicePort is not necessary to assign. This would allow us to keep the default values for `local_port` instead of changing them as we scale.

**Comment by pierlo-upitup** [comment]
cc @aquamatthias

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3463. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
