### ISSUE TITLE
Improve Create/Edit Form usability with keyboard

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#3182]
We should consider a few improvements to the Create/Edit modal

ACs
- [ ] When clicking on (+) in one of the duplicable rows, the focus should be set to the first input field added so I can start typing.
- [ ] When moving around with TAB, and focusing  on (+) or (-) , the buttons should show a distinct "focus" state, so I can hit Enter comfortably.
- [ ] It should be possible to TAB between the closed Sections of the form, for example : 
  to unfold the Docker Container Settings I would hit TAB from the `cmd` field and then Enter to unfold the form section.

Generally, I should be able to fill in everything without needing a mouse :)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3067. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
