### ISSUE TITLE
Improve modal dialogs usability with keyboard

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#3184]
I'll use the "Destroy Application" modal dialog as an example:
- [ ] There's no way of selecting the buttons `Destroy Application`/`Cancel` buttons using the keyboard.
- [ ] Pressing TAB moves around the links in the "background" page, that shouldn't happen.
- [ ] IMHO the `Cancel` button should have focus by default. Pressing TAB should change focus to the `Destroy Application` button.

Related to #3182

**Comment by pierlo-upitup** [comment]
Thanks!

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3075. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
