### ISSUE TITLE
Introduce immutable.js and get rid of Lazy.js

### ISSUE THREAD

**Issue by aldipower** [mesosphere/marathon#3185]
Immutable.js should be introduced, where it makes sense, e.g. in the store getters to prevent accidentally changing data by reference, getting rid of the `deepCopy()` in the store.

As immutable.js is also capable of lazy-evaluation and returning data-sequences for functional processing, it is a good idea to get rid of lazy.js and replace it either with immutable.js, where we have a sequence-chain or with the native ES6 functions, where e.g. a simple `.find()` is used.

https://facebook.github.io/immutable-js/docs/#/

**Comment by pierlo-upitup** [comment]
![giphy](https://cloud.githubusercontent.com/assets/1078545/12889931/92741944-ce81-11e5-83d3-501e957f1fb0.gif)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3237. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
