### ISSUE TITLE
Human readable metadata for apps

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#3189]
We discussed that with @leemunroe and @alberts before, @abraithwaite expressed the need too.

With large Marathon deployments when many applications are deployed on many Marathons it becomes hard to find out which app does what and where to find sources, documentation or metrics. While you can link to sources and marathon definitions from docs, building the whole graph (docs, sources, metrics, api links, etc.) is quite hard when the only thing you have in front of you is failing Marathon application.

It is reasonable to say that alerting should be used for such things, but it does not cover cluster exploration. Sometimes you just wonder what is this new shiny thing that consumes 5 terabytes of ram and has 500 instances.

I'd argue that having a text field with brief explanation and a few links could save a lot of time and help with this issue. If any new member of my team can go to marathon Web UI, open application called `/marathon/analytics/zoidberg` and see at least the following, many hours could be saved.

> Zoidberg is a service discovery for Mesos and Marathon: https://github.com/bobrik/zoidberg.

**Comment by abraithwaite** [comment]
This would be incredibly helpful, especially when under 🔥 from a production issue.  Being able to include links to metrics, source code, action plans, usage, etc. is a huge step up from practicing archeology. 🗿

**Comment by pierlo-upitup** [comment]
Thanks a lot for your input – that sounds indeed like a really useful feature.  
Adding this to our Backlog for future evaluation/prioritisation.

cc @air @leemunroe @aquamatthias

**Comment by air** [comment]
Hey @pierlo-upitup for your info see MARATHON-792

**Comment by abraithwaite** [comment]
Any updates on this?

**Comment by abraithwaite** [comment]
Bump.

**Comment by jasongilanfarr** [comment]
I can say that we're definitely going to do this in a future API revision. Seems like it'd be super easy for us to implement this, so i'll see if I can do it quickly.

I can tell you that we internally tend to use mesos labels for this, but that does require restarting a task to change the comments.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3191. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
