### ISSUE TITLE
How to reliably discover Marathon URL

### ISSUE THREAD

**Issue by aleks-f** [mesosphere/marathon#3191]
Since `webui_url` entry in Mesos state JSON is optional, one can try the luck with `hostname` (which is also optional).

However, if both of the above entries are missing from Mesos state, is there any other way to reliably discover where Marathon API server is listening?

UPDATE: this below seems not to be correct diagnosis.
~~Furthermore, if a Marathon instance is migrated to another location, Mesos `webui_url` seems to retain the old, stale value. This looks like a bug? Is there any workaround?~~

**Comment by pierlo-upitup** [comment]
Hi @aleks-f – have you tried inspecting the `frameworks` list returned by the Mesos `state.json`? 
Each entry in that array should have a `name` and `hostname` property. It should be trivial to search for `marathon` and then gathering the information needed from there.
Hope this helps!

**Comment by aleks-f** [comment]
@pierlo-upitup : yes, of course, but I'm looking for a reliable method that will work in any scenario. Both `webui_url` and `hostname` are optional, so they may not be there, correct? Furthermore, for some reason (Mesos or Marathon bug?), Mesos does not show the new `webui_url` entry after Marathon leader changes.

Thanks for your help so far.

**Comment by aleks-f** [comment]
@pierlo-upitup : I see now that `hostname` defaults to "hostname of the machine" if not specified on the command line. Does that mean it will always be there and accurately updated in Mesos state?

**Comment by aleks-f** [comment]
I have updated the original issue - the last problem was misdiagnosed. So, only the main question remains - a reliable way (meaning a value that will be present under any circumstances) to discover from the Mesos state JSON where the new marathon leader is listening after migration .

**Comment by aleks-f** [comment]
Got the answer - documentation is somewhat confusing - it says `webui_url` is optional, default :none, but later it states "If not set, the url to the leading instance will be sent to Mesos."

**Comment by rodrickbrown** [comment]
@aleks-f  Is Mesos-dns not an option? Mesos-dns will register running frameworks like marathon.mesos which will always point to the current leader.
