### ISSUE TITLE
Adapt default Mem/CPU settings

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#3192]
Should be the same as the default backend values:
Mem: 128 MB
CPU: 1 

Note: the min mem limit in mesos is 32MB and 0.01 CPU.
We should validate those in the UI.

**Comment by joerg84** [comment]
FYI: Mesos constants are defined here: https://github.com/apache/mesos/blob/f99ae0e7618b8a6508ff7d97c290572592508737/src/master/constants.cpp#L30

There are even some plans to enforce that in the distant future: https://issues.apache.org/jira/browse/MESOS-1807
