### ISSUE TITLE
Refactor: tidy up duplication of PathUtils

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#3197]
We manipulate the app path in several places, eg `BreadcrumbComponent` and `AppListComponent`. We have a single unit-tested utility method in `PathUtils` which we're not using in these cases. Let's use it!

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3529. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
