### ISSUE TITLE
REST API docs contains invalid JSON

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#3203]
The first example on [this page](https://mesosphere.github.io/marathon/docs/rest-api.html) contains two errors in JSON: the first is that JS-style comments after `acceptedResourceRole` is not valid, and the second is that there is no comma after the value of `args`. 

This is rather annoying when copy-pasting into `curl` or similar.

h/t @leemunroe for noticing!

**Comment by pierlo-upitup** [comment]
We should use `YAML`! :trollface:

**Comment by jasongilanfarr** [comment]
Pretty sure this is now validated.
