### ISSUE TITLE
Allow logging to a file via a cli flag

### ISSUE THREAD

**Issue by SEJeff** [mesosphere/marathon#3204]
Placeholder for [this issue in chaos](https://github.com/mesosphere/chaos/issues/53). From an ops standpoint, this is something that I see as lacking a bit on marathon. It would be really nice if there was a way to have it log to a file for those running it standalone and not inside a docker container.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2136. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
