### ISSUE TITLE
As an end-user, I would like to find a /latest endpoint on /v2/apps/<appId>/versions

### ISSUE THREAD

**Issue by jgarcia-mesosphere** [mesosphere/marathon#3205]
To be able to retrieve the most current app definition without task data (for efficiency when an app is scaled to a huge number of tasks), I would like to have a `/v2/apps/<appId>/versions/latest` endpoint that will show just the most recent version.

**Comment by pierlo-upitup** [comment]
Hi!

Please help me understand this. According to [the docs](https://mesosphere.github.io/marathon/docs/rest-api.html#get-v2-apps):

1) Doing a `GET` to `/v2/apps/{appId}` already returns the current configuration of the app 
2) If you want to exclude `tasks` from the returned info, simply don't pass the `embed=apps.tasks` query parameter

Or am I missing something?

**Comment by jasongilanfarr** [comment]
Lastest version is just at the app endpoint. Reopen if that's insufficient.
