### ISSUE TITLE
Add average time to failure for tasks to the UI

### ISSUE THREAD

**Issue by cmaloney** [mesosphere/marathon#3206]
Currently, if a task is failing rapidly (One task dies every 30 seconds) or slowly (one task dies every 3 days), I have no way of telling in Marathon's UI. In addition, because Marathon just restarts the tasks, no one might notice when their software has become less stable / started crashing more frequently than it used to. It would be really nice to give developers the insight of something like "time between failures" or "average task lifetime". Even better would be the statistics themselves presented in a chart so it's easy to spot "clusterings" around various lifetimes.

**Comment by pierlo-upitup** [comment]
cc @air @leemunroe @aquamatthias

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2512. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
