### ISSUE TITLE
Avoid `version.toString`

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3207]
Use Timestamp for versions and timestamps. There are a lot of occurrences in the code of passing `Timestamp`s around as `String`s. I guess that the historical reason was "time pressure" since it was easier to serialize such Strings to JSON at that time. We should get rid of them.

You can find many of these occurrences by searching for:
- `versionString`
- `version.toString`
- `version: String`
- `timestamp: String`

**Comment by jasongilanfarr** [comment]
Pretty sure this is no longer relevant.
