### ISSUE TITLE
POST /v2/tasks/delete doesn't works as should

### ISSUE THREAD

**Issue by marenzo** [mesosphere/marathon#3208]
The api doc says:
- **200** - "If scale=false, all tasks that were killed are returned. If scale=true, than a deployment is triggered and the deployment is returned." which means in other words, the delete went okay
- **400** - "There are unknown task ids, that can not be killed"

Now, sending a post to "/v2/tasks/delete" with unknown id, returns the following:

```
-> % curl -i -X POST http://marathon:8080/v2/tasks/delete -H "Content-Type: application/json" --data '{"ids": ["service-id.1d877890-cf57-11e5-80c2-FAKE"]}'
HTTP/1.1 200 OK
Date: Wed, 10 Feb 2016 12:03:05 GMT
X-Marathon-Leader: http://marathon:8080
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
Content-Type: application/json; qs=2
Transfer-Encoding: chunked
Server: Jetty(9.3.z-SNAPSHOT)

{"tasks":[]}
```

(note the "FAKE" in the id)

When trying to send ID which is not by the task ID convention, I actually do receiving 400:

```
-> % curl -i -X POST http://marathon:8080/v2/tasks/delete -H "Content-Type: application/json" --data '{"ids": ["FAKE"]}'                                                 
HTTP/1.1 400 Bad Request
Date: Wed, 10 Feb 2016 12:05:00 GMT
X-Marathon-Leader: http://marathon:8080
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
Content-Type: application/json
Transfer-Encoding: chunked
Server: Jetty(9.3.z-SNAPSHOT)

{"message":"Invalid task id 'FAKE'."}
```

In both cases I'm sending task ID which doesn't exists, but only in one case I'm actually receiving the right status code.

Also, when adding "**?scale=true**" the behavior is again different:

```
-> % curl -i -X POST http://marathon:8080/v2/tasks/delete\?scale\=true -H "Content-Type: application/json" --data '{"ids": ["service-id.1d877890-cf57-11e5-80c2-FAKE"]}'
HTTP/1.1 200 OK
Date: Wed, 10 Feb 2016 12:07:21 GMT
X-Marathon-Leader: http://marathon:8080
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
Content-Type: application/json; qs=2
Transfer-Encoding: chunked
Server: Jetty(9.3.z-SNAPSHOT)

{"version":"2016-02-10T12:07:21.666Z","deploymentId":"63eccf04-a0c8-44f3-865a-0f70daf68a0b"}
```

See that the response body of this request is different than the response body of the first request.

The lack of consistency is weird, and the fact that I'm not receiving 400 for unknown ids (as in the first case) is either bug or just wrong description of the api.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2444. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
