### ISSUE TITLE
Mesos fetcher not working on docker apps on CoreOS

### ISSUE THREAD

**Issue by Spritekin** [mesosphere/marathon#3213]
Reference in question https://github.com/mesosphere/marathon/issues/3179.

Please read the question. Essentially I'm starting a docker app and the specified URIs are not being downloaded to the container, however Marathon says it has.

This is the relevant section of the executor stdout

```
I0211 01:30:41.644635  3328 fetcher.cpp:422] Fetcher Info: {"cache_directory":"\/tmp\/mesos\/fetch\/slaves\/287019ff-a08e-4fec-a770-089ebb649af5-S247","items":[{"action":"BYPASS_CACHE","uri":{"cache":false,"executable":false,"extract":false,"value":"http:\/\/mesos-master.aws.cmcrc.com\/prometheus.yml"}}],"sandbox_directory":"\/var\/lib\/mesos\/slave\/slaves\/287019ff-a08e-4fec-a770-089ebb649af5-S247\/frameworks\/287019ff-a08e-4fec-a770-089ebb649af5-0000\/executors\/prometheus3.10246805-d05f-11e5-ad23-96dfddec601a\/runs\/2d804f41-323d-40f5-914b-9e7d46a948e0"}
I0211 01:30:41.646569  3328 fetcher.cpp:377] Fetching URI 'http://mesos-master.aws.cmcrc.com/prometheus.yml'
I0211 01:30:41.646590  3328 fetcher.cpp:248] Fetching directly into the sandbox directory
I0211 01:30:41.646610  3328 fetcher.cpp:185] Fetching URI 'http://mesos-master.aws.cmcrc.com/prometheus.yml'
I0211 01:30:41.646622  3328 fetcher.cpp:132] Downloading resource from 'http://mesos-master.aws.cmcrc.com/prometheus.yml' to '/var/lib/mesos/slave/slaves/287019ff-a08e-4fec-a770-089ebb649af5-S247/frameworks/287019ff-a08e-4fec-a770-089ebb649af5-0000/executors/prometheus3.10246805-d05f-11e5-ad23-96dfddec601a/runs/2d804f41-323d-40f5-914b-9e7d46a948e0/prometheus.yml'
I0211 01:30:41.654059  3328 fetcher.cpp:454] Fetched 'http://mesos-master.aws.cmcrc.com/prometheus.yml' to '/var/lib/mesos/slave/slaves/287019ff-a08e-4fec-a770-089ebb649af5-S247/frameworks/287019ff-a08e-4fec-a770-089ebb649af5-0000/executors/prometheus3.10246805-d05f-11e5-ad23-96dfddec601a/runs/2d804f41-323d-40f5-914b-9e7d46a948e0/prometheus.yml'
```

Look that the message is quite specific, the file has been downloaded to that path. So I go to that server and into that path:

```
core@ip-172-31-43-113 /var/lib/mesos/slave/slaves/287019ff-a08e-4fec-a770-089ebb649af5-S247/frameworks/287019ff-a08e-4fec-a770-089ebb649af5-0000/executors/prometheus3.10246805-d05f-11e5-ad23-96dfddec601a/runs/2d804f41-323d-40f5-914b-9e7d46a948e0 $ ls -la
total 16
drwxr-xr-x 2 root root 4096 Feb 11 12:30 .
drwxr-xr-x 3 root root 4096 Feb 11 12:30 ..
```

So the files are not there, however Mesos says they were downloaded. From the Mesos UI:
mode    nlink   uid gid size    mtime  
-rw-r--r--  1   root    root    1 KB    Feb 11 12:30     prometheus.yml  Download
-rw-r--r--  1   root    root    3 KB    Feb 11 12:40     stderr  Download
-rw-r--r--  1   root    root    1 KB    Feb 11 12:30     stdout  Download

My file prometheus.yml is there! I can even click and see the contents. But not in the specified path. Note the container is happilly running as I'm not using the file itself, this is just a download test.

So I go into the container:

```
docker exec -ti 6ba4aba98a33 /bin/sh 
cd /mnt/mesos/sandbox/
/mesos/sandbox/
/mnt/mesos/sandbox # ls -la
total 16
drwxr-xr-x    2 root     root          4096 Feb 11 01:30 .
drwxr-xr-x    3 root     root          4096 Feb 11 01:30 ..
```

So no, the file is definitely not there.

I must consider this a bug.

Software versions:
Marathon 0.15.0
Mesos 0.26
CoreOS 899.3.0

Luck!
Guimo

**Comment by philipnrmn** [comment]
Hi Guimo,

Looks like a permissions problem with your shell user to me, specifically because `ls -la` responds `total 16`, but lists no files - if there were none you should see `total 0`. 

Can you double-check this please?

**Comment by Spritekin** [comment]
My CoreOS user is the admin level user. I went sudo:
core@ip-172-31-45-238 /var/lib/mesos/slave/slaves/287019ff-a08e-4fec-a770-089ebb649af5-S300/frameworks/287019ff-a08e-4fec-a770-089ebb649af5-0000/executors/prometheus3.cf6937bc-
d3a2-11e5-ad23-96dfddec601a/runs/c013f1df-a485-4a03-bc2e-80893c600167 $ sudo ls -la
total 16
drwxr-xr-x 2 root root 4096 Feb 15 16:13 .
drwxr-xr-x 3 root root 4096 Feb 15 16:13 ..


Also:
$ sudo su -
$ cd /var/lib/mesos/slave/slaves/287019ff-a08e-4fec-a770-089ebb649af5-S300/frameworks/287019ff-a08e-4fec-a770-089ebb649af5-0000/executors/prometheus3.cf6937bc-d3a2-11e5-ad23-96dfddec601a/runs/c013f1df-a485-4a03-bc2e-80893c600167/
$ ls -la
total 16
drwxr-xr-x 2 root root 4096 Feb 15 16:13 .
drwxr-xr-x 3 root root 4096 Feb 15 16:13 ..

So the file is not there.
But, in any way, if I was unable to see the file, where is it?

I tried:
sudo cp /var/lib/mesos/slave/slaves/287019ff-a08e-4fec-a770-089ebb649af5-S300/frameworks/287019ff-a08e-4fec-a770-089ebb649af5-0000/executors/prometheus3.cf6937bc-d3a2-11e5-ad23-96dfddec601a/runs/c013f1df-a485-4a03-bc2e-80893c600167/prometheus.yml /home/core/
cp: cannot stat '/var/lib/mesos/slave/slaves/287019ff-a08e-4fec-a770-089ebb649af5-S300/frameworks/287019ff-a08e-4fec-a770-089ebb649af5-0000/executors/prometheus3.cf6937bc-d3a2-11e5-ad23-96dfddec601a/runs/c013f1df-a485-4a03-bc2e-80893c600167/prometheus.yml': No such file or directory

But the download link in Mesos is:
http://172.31.45.238:5051/files/download?path=%2Fvar%2Flib%2Fmesos%2Fslave%2Fslaves%2F287019ff-a08e-4fec-a770-089ebb649af5-S300%2Fframeworks%2F287019ff-a08e-4fec-a770-089ebb649af5-0000%2Fexecutors%2Fprometheus3.cf6937bc-d3a2-11e5-ad23-96dfddec601a%2Fruns%2Fc013f1df-a485-4a03-bc2e-80893c600167%2Fprometheus.yml

Look at the path, it is exactly the same path I use. And when I use that link I get the file!

I really have no answer for this... where is the file?

Luck!
Guimo

**Comment by Spritekin** [comment]
So I decided to go and do a full disk scan...
```
# find . | grep prometheus.yml
./var/lib/docker/overlay/0dc654a9be13c75c5e8ca4a47163a9120650b7b0ff5c8c2310300158f7a6ae3f/upper/var/lib/mesos/slave/slaves/287019ff-a08e-4fec-a770-089ebb649af5-S300/frameworks/287019ff-a08e-4fec-a770-089ebb649af5-0000/executors/prometheus3.cf6937bc-d3a2-11e5-ad23-96dfddec601a/runs/c013f1df-a485-4a03-bc2e-80893c600167/prometheus.yml
./var/lib/docker/overlay/3a6b0c1beac66a56889d7e179e9cabf555b342e75b7236e1ce9216e82c3749d5/root/etc/prometheus/prometheus.yml
./var/lib/docker/overlay/74e3b12aba2ae3febb79a1fcb8a08916f8d2b9a2ddba3d93d8a7150e0f0008c6/root/etc/prometheus/prometheus.yml
./var/lib/docker/overlay/8805f68c39bf54f8c53ee17714c09784a2e42a83e031e985418e6152bebf06c8/root/etc/prometheus/prometheus.yml
./var/lib/docker/overlay/c3c8460f399a2c74281933717142f2fc1294597dca9a5d8383c3ea3e04725ebf/root/etc/prometheus/prometheus.yml
./var/lib/docker/overlay/d9e964262ab62044d019e39ea64252a924a99d96e1b6ee86ac90926298f17dbd/root/gopath/src/github.com/prometheus/prometheus/documentation/examples/prometheus.yml
./var/lib/docker/overlay/90a5122247ff9b12a10e4e69d665ca255e9bd3f372d2cbbc419a591c9fef4a31/root/etc/prometheus/prometheus.yml
./var/lib/docker/overlay/48cdadf05bb7e51d87b0100ab5e577dd28fe977945ca0f4b3c1d9dba168637a6/root/etc/prometheus/prometheus.yml
```

So looks like the file exists in this "overlay" folder, not in the path specified by mesos. So I went into this folder:
# cd /var/lib/docker/overlay/0dc654a9be13c75c5e8ca4a47163a9120650b7b0ff5c8c2310300158f7a6ae3f/upper/var/lib/mesos/slave/slaves/287019ff-a08e-4fec-a770-089ebb649af5-S300/frameworks/287019ff-a08e-4fec-a770-089ebb649af5-0000/
executors/prometheus3.cf6937bc-d3a2-11e5-ad23-96dfddec601a/runs/c013f1df-a485-4a03-bc2e-80893c600167/
ip-172-31-45-238 c013f1df-a485-4a03-bc2e-80893c600167 # ls -la
total 40
drwxr-xr-x 2 root root 4096 Feb 15 16:13 .
drwxr-xr-x 3 root root 4096 Feb 15 16:13 ..
-rw-r--r-- 1 root root 1193 Feb 15 16:13 prometheus.yml
-rw-r--r-- 1 root root 3121 Feb 15 16:28 stderr
-rw-r--r-- 1 root root 1476 Feb 15 16:13 stdout

And look at that... the file is there!

So now the question becomes... what is this overlay folder? Why are files there and why is it not mounted to the container.

**Comment by gkleiman** [comment]
@Spritekin: Mesos should mount the volume automatically. If it is not working, then there might be a bug in Mesos. Could you please open a ticket on their [issue tracker](http://issues.apache.org/jira/browse/MESOS)?

**Comment by Spritekin** [comment]
I will... thanks!

**Comment by micahhausler** [comment]
@Spritekin Are you by chance running Mesos itself in a container? If that is the case, you need to mount the agent's `work_dir` to the host.

**Comment by Spritekin** [comment]
@micahhausler 

Hi, yes indeed I am. I run in CoreOS so everything is docker. 

So, you suggestion to mount the agent's work dir to the host... what do you mean exactly? Where in the host?
This is my mesos-slave command:
```
        ExecStart=/usr/bin/docker run --privileged --net=host \
            -e MESOS_IP=${COREOS_PRIVATE_IPV4} \
            -e MESOS_HOSTNAME=${COREOS_PRIVATE_IPV4} \
            -v /sys:/sys -v /usr/bin/docker:/usr/bin/docker:ro \
            -v /var/run/docker.sock:/var/run/docker.sock \
            -v /lib64/libsystemd.so.0:/lib/libsystemd.so.0 \
            -v /lib64/libpthread.so.0:/lib/libpthread.so.0:ro \
            -v /lib64/libdevmapper.so.1.02:/lib/libdevmapper.so.1.02:ro \
            -v /lib64/libudev.so.1:/lib/libudev.so.1:ro \
            -v /lib64/libdl.so.2:/lib/libdl.so.2 \
            -v /lib64/libc.so.6:/lib/libc.so.6 \
            -v /lib64/libselinux.so.1:/lib/libselinux.so.1 \
            -v /lib64/librt.so.1:/lib/librt.so.1 \
            -v /lib64/libm.so.6:/lib/libm.so.6 \
            -v /lib64/libresolv.so.2:/lib/libresolv.so.2 \
            -v /lib64/liblzma.so.5:/lib/liblzma.so.5 \
            -v /lib64/libgcrypt.so.20:/lib/libgcrypt.so.20 \
            -v /lib64/libgpg-error.so.0:/lib/libgpg-error.so.0 \
            -v /lib64/libcap.so.2:/lib/libcap.so.2 \
            -v /lib64/libpcre.so.1:/lib/libpcre.so.1 \
            -v /lib64/libattr.so.1:/lib/libattr.so.1 \
            mesosphere/mesos-slave:0.28.0-2.0.16.ubuntu1404 \
              --containerizers=docker,mesos \
              --master=zk://mesos-zk1.aws.cmcrc.com:2181,mesos-zk2.aws.cmcrc.com:2181,mesos-zk3.aws.cmcrc.com:2181/mesos \
              --work_dir=/var/lib/mesos/slave \
              --log_dir=/var/log/mesos/slave \
              --executor_registration_timeout=3mins \
              --resources="ports(*):[80-32000]"
```

I have /var/lib/mesos/slave as my work dir inside the container but I need to mount it to /var/lib/mesos/slave in the host... as in:
-v /var/lib/mesos/slave:/var/lib/mesos/slave

Is that correct?

**Comment by micahhausler** [comment]
Yes, that solved it for me.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4113. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
