### ISSUE TITLE
[DEFER] Resident Tasks: Conservatively remove spurious volumes/reservations

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3223]
We need a conservative housekeeping mechanism that prevents unwanted destroy/unreserve operations. State of discussion is
- Nothing is removed implicitly to prevent faulty removal and resulting data loss
- When a task terminates (due to whatever reason), reservations and volumes are retained
- When an app is deleted, reservations and volumes are removed.
- The deployment action for stopping the app terminates only after all reservations and volumes and tasks have been removed.
- Whenever an offer is received for a task that's marked, Marathon will schedule unreserve/destroy operations **and remove the task state**
- Whenever **unknown** reservations/volumes are received, Marathon will either
  - record these and provide info about them, **or**
  - log a warning that unknown reservations have been received

We might need either an extra endpoint to wipe tasks by ID.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2417. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
