### ISSUE TITLE
Cannot remove a constraint

### ISSUE THREAD

**Issue by eLvErDe** [mesosphere/marathon#3233]
Hello guys,

After adding a constraint from the web interface there's no way to remove it. Looks like a trivial form validation bug, see the screenshot: http://www.hostingpics.net/viewer.php?id=581825Selection008.png

Regards, Adam.

**Comment by philipnrmn** [comment]
Hi Adam,

Thanks for the bug report. I reproduced this and we'll get it fixed. 

Philip

**Comment by philipnrmn** [comment]
Context: form value-getter interprets a blank field as the following:
```
[
  [ "" ]
]
```
