### ISSUE TITLE
hostPort to containerPort mapping

### ISSUE THREAD

**Issue by akamalov** [mesosphere/marathon#3234]
Greetings,

A small question: can I do 1:1 port mapping of hostPort to containerPort ? Using Docker and Bridge and I am failing to deploy a container if I specify 1:1 portMapping
```
"hostPort": 9090,
"containerPort": 9090
```

Marathon stays indefinitely in "waiting" state...

Any ideas?

Thanks,

Alex

**Comment by giammy2290** [comment]
same problem for me

**Comment by akamalov** [comment]
Answering my own question: my error was that I didn't provide resources under Mesos-Slave nodes: /etc/mesos-slave resources. Once I provided available ports and restarted Mesos-Slave, I was able to successfully use hostPort to containerPort.
