### ISSUE TITLE
JSON field documentation missing in new, generated REST API

### ISSUE THREAD

**Issue by timoreimann** [mesosphere/marathon#3235]
The [deprecated REST API documentation](https://mesosphere.github.io/marathon/docs/rest-api.html) comes with extra information on the semantics and valid value ranges for the individual JSON fields, such as `id`, `cmd`, and `mem`. The [new, generated REST API documentation](https://mesosphere.github.io/marathon/docs/generated/api.html) seems to miss this part entirely.

Adding these pieces becomes more important the further the deprecated REST API page turn out-dated.

**Comment by philipnrmn** [comment]
We should definitely improve this. PRs are always welcome!

**Comment by alenkacz** [comment]
Where does the https://mesosphere.github.io/marathon/docs/generated/api.html live within this repository?

**Comment by philipnrmn** [comment]
Hi @alenkacz 

It's generated from these RAML sources:
https://github.com/mesosphere/marathon/blob/master/docs/docs/rest-api/public/api/api.raml

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1777. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
