### ISSUE TITLE
Serverside validation messages are inconsistent

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#3241]
There seem to be two kinds of error response objects when validation errors occur in the API:

Case 1) Generic errors
Case 2) Field-specific errors

**Case 1** errors trigger a `422` response with this structure:
```
{
  "message": "Object is not valid",
  "details": [
    {
      "attribute": "value",
      "error": "Groups and Applications may not have the same identifier: /hello"
    }
  ]
}
```
(side-note: `value` seems to be a placeholder for non-specific attribute paths)

**Case 2** errors trigger a `400` response with this structure:
```
{
  "message": "Invalid JSON",
  "details": [
    {
      "path": "/cpus",
      "errors": [
        "error.expected.jsnumber"
      ]
    }
  ]
}
```

I suggest the following result for consistency:

**Case 1)** `422`
```
{
  "message": "Object is not valid",
  "details": [
    {
      "path": "general",
      "errors": [
        "Groups and Applications may not have the same identifier: /hello"
      ]
    }
  ]
}
```

**Case 2)** `400`
Unchanged.

Please correct if I'm wrong and looking forward to hearing your thoughts on this.

**Comment by gkleiman** [comment]
cc/ @alexanderweber

**Comment by alexanderweber** [comment]
@pierlo-upitup I understand the confusion behind these two. I would say that we should still differentiate here, so I will try to make my point here.

Regarding **Case 1** we have a valid JSON which led to instantiation of an object having certain attributes. Whose attributes have errors though, hence the `422` response. In this specific case the `group` is having `group.apps` and `group.groups` which have the same id. The validation is done on the `group` object itself. I had to decide whether to link to `group.apps` or `group.groups` as the point of failure, both seemed inconvenient though. The most reasonable choice would be to point at the object itself. So `value` is actually indicating, that the error is on the top level of object validation, the object itself so to say. It is the unchanged notation of `Accord` package we  are using in our validation. We could still discuss on alternatives in naming here though. Please keep in mind, that `group` in this case is object's name we are working on. The actual object name could also be something arbitrary like `g` or `foobar`.

In **Case 2** though, the message produced by Jackson indicates an error in the JSON, so there is no instance of an object at this point, so it can be viewed as a plain text. Hence the `path` notation which is common for JSON files is appropriate.

**Comment by alexanderweber** [comment]
@aquamatthias Can you also give your opinion on this one? I talked f2f to Pierluigi just a minute ago. We agreed on following points:

1. renaming `attribute` to `path` for **Case 1**
2. replacing the `error` property in **Case 1** to an `errors` array of strings like in **Case 2**
3. having `value` as the top level `path` of a point of failure. So basically keep it as in **Case 1**

I have an additional suggestion, which came up after realising the lack of expression behind the meaning of `value`. In `422` errors we could provide a type of class the error appeared in, e.g. `"type": "Group"` in this case. But I also agree on that this background information might be confusing for the end user as well.

**Comment by aquamatthias** [comment]
@alexanderweber 

I agree with your proposal for 1. and 2. 
Regarding  3 I see at least 3 different types to validation involved:
- JSON validation - the json is invalid and we have the path to the invalid one (e.g. /cpus) 
- Object attribute validation - the parsed object is checked on attribute level (e.g. foo.arr[23].bla)
- Object validation - the compound object is checked for validity (e.g.Groups and Applications may not have the same identifier), we could take (`/`,  `.`, `self`, `this` as root?) 

So I see two options: either translate general validation errors as problems in path root or introduce 2 types of errors: path level errors and general errors (basically add a `type` to every error).

**Comment by alexanderweber** [comment]
@aquamatthias I think Pierluigi had some concerns introducing a new field, like `type`, which might be a rather misleading information for the customer. So if I got you right, this would be ok for the **Case 1** scenario:

```JSON
{
  "message": "Object is not valid",
  "details": [
    {
      "path": "self",
      "errors": [
          "Groups and Applications may not have the same identifier: /hello"
      ]
    }
  ]
}
```
Just to be sure on the `self` reference, there also might be cases like:
```
...
   "path": "groups[0].self"
...
```
which I do not really see as a problem, but want to make sure being an acceptable output.

**Comment by aquamatthias** [comment]
I disagree: I think self only make sense to point to root, never as part of the path.

**Comment by alexanderweber** [comment]
I see your point, I'll implement the self reference on the root only behaviour then. Thanks a lot for the feedback!
