### ISSUE TITLE
Show stdout and stderr logs in the browser

### ISSUE THREAD

**Issue by alenkacz** [mesosphere/marathon#3244]
Currently, the logs are downloaded. I would prefer for them to be opened in my browser window.

Does that make sense? (at least for smaller logs)

If it does, I am happy to contribute.

**Comment by philipnrmn** [comment]
Hi @alenkacz 

That makes perfect sense and it's how we envisage it working eventually - the download was a first-pass implementation. There's already a ticket for it in our backlog: #3081. Thanks for volunteering to contribute, that would be great. 

@leemunroe or @cleverroffey may be able to provide our current design thinking on this feature.

**Comment by leemunroe** [comment]
@alenkacz Absolutely. [Here's a design solution](https://invis.io/4561PSY6B) we're exploring. We would love your feedback on how this looks so far and if it matches your expectations.

![image](https://cloud.githubusercontent.com/assets/15963/13076429/13cbc934-d467-11e5-82f2-71890c1c60bf.png)

**Comment by alenkacz** [comment]
@leemunroe looks awesome! :)

**Comment by xiongtx** [comment]
Any progress on this?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2467. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
