### ISSUE TITLE
Refactor DuplicableRowsMixin field key/index generation

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#3245]
The `DuplicableRowsMixin` uses `Util.getUniqueId` to generate keys/indices at the moment. These keys are used as array indices and are needed to obtain correct from field order. 
Problem with the current approach is that items in an array with very high keys (basically every number above 2^32-1) are excluded when creating a `deepCopy` clone.  
The fix introduced in mesosphere/marathon-ui#633 works around this issue by truncating the `Util.getUniqueId` number to a smaller number with a higher risk of collisions. 
The key needs to only be _locally_ unique, thus a simple consecutive number should do the trick. As this a less complicated and error prone we should refactor the `DuplicableRowsMixin` accordingly.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2634. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
