### ISSUE TITLE
Handle errors for not present fields as a general error

### ISSUE THREAD

**Issue by Poltergeist** [mesosphere/marathon#3248]
If a field is not given and an error corresponding to the not present field is thrown it should be resolved in a general error. 

Example: With the introduction of local volumes we have a mixed structure in the `container.volumes` array some objects do have a hostpath some don't. This resolved in the following error from an older api which was not handled correctly:

![image](https://cloud.githubusercontent.com/assets/156010/13074673/60dc813e-d4a6-11e5-944d-ccfbc6f8e3f0.png)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1810. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
