### ISSUE TITLE
Add router, make resources linkable

### ISSUE THREAD

**Issue by ssorallen** [mesosphere/marathon#325]
There is only one route in the UI right now: the root ("`/`"). Linking to specific applications would be useful.

The router will have to use hashes rather than push state so the app is still served from the root.

**Comment by aldipower** [comment]
I've experimented a little bit with react-router to integrate with Marathon. It's not that easy, it causes a lot of refactoring of the TabPanes, clickhandler and states.
https://github.com/mesosphere/marathon/tree/325-make-resources-linkable

**Comment by aldipower** [comment]
Ok, maybe we should rely on the Backbone.Router it's a more flexible approach.

**Comment by mlunoe** [comment]
I used Backbone Router here: https://github.com/mesosphere/mm-frontend/blob/master/src/models/Router.js

https://github.com/mesosphere/mm-frontend/blob/master/src/components/MesosphereManager.jsx#L98

**Comment by ssorallen** [comment]
@mlunoe, the repo you linked to is private. Did you mean to link to that?

**Comment by ConnorDoyle** [comment]
Edited to remove some private links.  @mlunoe can you provide a public gist as an example instead?

**Comment by mlunoe** [comment]
Thanks, sorry. My bad. I've updated the comment with a link to a gist

**Comment by aldipower** [comment]
@mlunoe Yes, entirely my opinion, workarounds should be only done, if there's absolutly no other way out. 'react-router' relies to much on jsx and react, so you can't work flexible with routes, what causes a lot of workarounds trying to integrate this in Marathon. Let's use Backbone.Router with the approach you have proposed in the gist.

**Comment by ssorallen** [comment]
@mlunoe, the `render` function in your Gist re-implements much of what `Backbone.Router` offers you. The Gist comes close to rewriting some of the [`route` code](http://backbonejs.org/docs/backbone.html#section-161) line-for-line. You could let Backbone's router do more work for you by moving that logic into your extended Backbone router or simply remove Backbone's router all together.

**Comment by mlunoe** [comment]
That is true, so in stead we could just register/map the functions in this component onto the router, like this maybe?
```
var noop = function () {};

var Marathon = React.createClass({
  propTypes: {
    router: React.PropTypes.instanceOf(Router).isRequired
  },
  getInitialState: function () {
    return {
      component: <HomePage model={this.state.user} />
    };
  },
  componentDidMount: function () {
    var router = this.props.router;
    _.reduce(router.routes, function(obj, route) {
        obj[route] = this[route] || noop;
        return obj;
    }, router, this);
  },
  home: function () {
    this.setState({
      component: <HomePage model={this.state.user} />
    });
  },
  render: function () {
    var component = this.state.component;
  }
});
```

P.S. There's probably a better way of doing the mapping of functions. Not sure if it is a good idea to use reduce to extend the router with certain functions of this component.

@ssorallen @aldipower Any suggestions?

**Comment by aldipower** [comment]
Yeah. 
Also I would suggest to name the route functions in the component with a 'route'-prefix.
```
routeHome: function() {
```
Then you can easily see in the code, that it's a route function.
Instead of reduce I would use map to do a mapping. :)
```
    componentDidMount: function () {
      var router = this.props.router;

      _.map(router.routes, function (routeFunctionName) {
        var routeName = routeFunctionName.name.charAt(0).toUpperCase() +
        routeFunctionName.name.slice(1);

        router[routeFunctionName] = this["route" + routeName] || noop;
      });
    }
```

**Comment by ssorallen** [comment]
Why does the logic in `componentDidMount` need to be there at all? Given the `Marathon` object in @mlunoe's last comment, the Router can handle the rest of the work. I don't think the `Marathon` object needs knowledge of the router.

The already-rendered check could be moved to a function to prevent duplicate code across route methods, but that ensures the router finds the current page's route before trying to render.

```js
var marathon;

Backbone.Router.extend({
  routes: {
    'home': 'home'
  },
  home: function() {
    if (marathon == null) {
      React.render(
        React.createElement(Marathon, {initialPage: 'home'}),
        ...
      );
    } else {
      marathon.home();
    }
  }
});
Backbone.History.start();
```

**Comment by mlunoe** [comment]
Of course! That is so much cleaner! Thanks!

**Comment by aldipower** [comment]
Good approach, thanx.

**Comment by ssorallen** [comment]
Actually, the React docs for [`setProps`](https://facebook.github.io/react/docs/component-api.html#setprops) recommend always calling `render` instead of special casing because React will just pass new props if the element is already rendered. I'd modify my example to this:

```js
Backbone.Router.extend({
  routes: {
    'home': 'home'
  },
  home: function() {
    React.render(
      <Marathon page="home">,
      ...
    );
  }
});
Backbone.History.start();
```

**Comment by mlunoe** [comment]
:+1:
