### ISSUE TITLE
Improve documentation for event bus messages

### ISSUE THREAD

**Issue by tpolekhin** [mesosphere/marathon#3257]
Hello, i'm collecting callbacks from marathon to track applications fails and deployments on our cluster.
I have couple of questions regarding all this stuff. For example i took easy grafana docker container and deployed it to marathon and record all events i received. Here is the timeline:
1. `api_post_event` - from this event i can get `appDefinition.id` with name of the application, information about docker container and its configuration, clientIp is also useful.
2. `group_change_success` - this event contains no information useful in any way, and i cannot correlate this event to any application on marathon
3. `add_health_check_event` - what does this mean? i already defined a health check in the POST JSON for grafana, or this is ENABLING health checks for application? (with `appId` i can correlate this to my app)
4. `deployment_info` - this huge beast required me to set `maxKafkaMessageSize` to 32k chars(!!!), but i found very little of this message useful: `plan.id` - to correlate later with `deployment_success` or `deployment_failed` events, i can get my app name `grafana` from `currentStep.actions.app` but this really needs to be top-level field. All this `plan` section - how can i benefit from it anyway?
5. `deployment_step_success` - with `currentStep.actions` i can get that my application has started
6. `deployment_info` - another info beast
7. `status_update_event` - cool, i can see `appId` and status, no correlation to `deploymentId` thou
8. `deployment_success` - no `appName` just `deploymentId`
9. `deployment_step_success` - received after `deployment_success` - weird, eh?

can someone shed some light on this event bus mess? thank you

**Comment by philipnrmn** [comment]
Sounds like we should shore the documentation up here. Adding the relevant labels.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2428. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
