### ISSUE TITLE
http_event_callback_slow_consumer_timeout does not influence the HTTP timeout

### ISSUE THREAD

**Issue by flosell** [mesosphere/marathon#3261]
In recent releases, `http_event_callback_slow_consumer_timeout` was added to configure a timeout when marathon should treat event callbacks as responding too slow (#3047). 

It seems like this doesn't affect the actual HTTP timeout but instead uses the hardcoded 10sec timeout from `HTTPEventModule`: https://github.com/mesosphere/marathon/blob/000a1cc66ab9ad96fb686e7a1350e652f205c85c/src/main/scala/mesosphere/marathon/event/http/HttpEventActor.scala#L63

We are currently dealing with an event callback that can take more than 10sec to respond but increasing the `http_event_callback_slow_consumer_timeout` doesn't have any effect, leading to lost events. 

Shouldn't marathon just use the configured timeout for event callbacks?

**Comment by philipnrmn** [comment]
I wonder whether we missed this TODO:
https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/event/http/HttpEventModule.scala#L94-L95

**Comment by tmmi** [comment]
Maybe https://github.com/mesosphere/marathon/pull/3805 ?

**Comment by meichstedt** [comment]
@flosell I'd vote for a different timeout because I'd actually expect the consumerTimeout to be lower than the requestTimeout (which is currently not configurable), otherwise the logic makes not much sense.

**Comment by tmmi** [comment]
Ok, requestTimeout included in the new PR https://github.com/mesosphere/marathon/pull/3827

**Comment by meichstedt** [comment]
Resolved in #3827
