### ISSUE TITLE
initdb: directory "/var/lib/postgresql/data" exists but is not empty

### ISSUE THREAD

**Issue by satya-thota** [mesosphere/marathon#3271]
I've been trying to persist postgress but keeps on giving me the error. It is similar to https://github.com/mesosphere/marathon/issues/2790 

Any idea where I am going wrong with volumes

**Comment by philipnrmn** [comment]
Hi @satya-thota 

Without more information about your environment and configuration, it's hard to know what to suggest. 

I would say that persisting PostgreSQL via Marathon is probably not something we could support at this time. Something so complicated should probably be a Mesos framework. You may find the [Apache Cotton](https://github.com/apache/incubator-cotton) project interesting.
