### ISSUE TITLE
Inaccurate Statistics

### ISSUE THREAD

**Issue by parker20121** [mesosphere/marathon#3275]
The running statistics, etc, aren't summing properly. The attached diagram shows that 10 instances are running on the left, but the services running in the right panel number in the hundreds. I'm running  0.15.0-RC3.

![marathon-statistics](https://cloud.githubusercontent.com/assets/351878/13179973/99fc7aaa-d6f4-11e5-8863-de29f971714e.png)

**Comment by orlandohohmeier** [comment]
@parker20121 thanks a bunch for reporting this! We will look into it.

**Comment by orlandohohmeier** [comment]
@parker20121 I looked into it, and I must acknowledge that's definitely a little confusing, but the numbers within the sidebar (left) represent the number of apps, not the number instances running. We probably should add a tooltip-something to clarify this difference.

/cc @leemunroe

**Comment by parker20121** [comment]
To me it's very misleading since you can have individual tasks failing, but
the numbers on the left would say everything's ok.

**Comment by parker20121** [comment]
If one app task fails, where does it get counted?

**Comment by parker20121** [comment]
Should there also be a failed category? if an app reaches the maximum number of retries and has failed, does that get counted anywhere?

**Comment by orlandohohmeier** [comment]
@parker20121 Yeah, it's confusing and as proposed I would add a simple tooltip-something to clarify this. Do you think that would solve this particular issue? 

As Marathon never stops trying to launch your apps, I don't see need for a "failed" state.  Marathon applies a backoff and increases that backoff for further failures until it reaches a given maximum *delay*  but will relentless retry to launch your apps. Such "failing" apps are marked as `delayed`.

**Comment by parker20121** [comment]
Either that or changing the label from "Status" to "App Status" or "Application Status".

I guess I read too much into the "maxConsecutiveFailures" healthcheck parameter, where the task is killed if it exceeds that setting. 

Thanks for looking at it.

**Comment by leemunroe** [comment]
I think "App Status" is a great suggestion. Esp. for newer users.
