### ISSUE TITLE
Avoid adding empty fields to JSON editor

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#3293]
- Open app create modal
- Verify that JSON looks like the following:

```
{
  "id": null,
  "cmd": null,
  "cpus": 1,
  "mem": 128,
  "disk": 0,
  "instances": 1,
  "ports": [
    0
  ]
}
```
- Return to form
- Open the collapsible `Labels` section but do not enter a new label
- Return to JSON editor and note that the `labels` field has been added to the JSON

AC:
- Non-default empty fields should not be added to the JSON editor.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1873. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
