### ISSUE TITLE
Remember collapsible panel state in app modal after toggle to JSON editor

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#3294]
- Open app modal
- Open a collapsible section, eg `Labels`
- Switch to JSON mode, then back to form mode
- Observe that the collapsible section has closed

ACs
- Collapsible sections should maintain their state on mode toggle
- Collapsible sections with errors should always be opened

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2317. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
