### ISSUE TITLE
Validate app config settings in JSON editor

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#3295]
Current the JSON editor only flags invalid JSON to the user. It would be good to highlight bad application configuration values. 

ACs
- Useful inline feedback is provided when the user enters a bad key in the JSON editor (eg "label" instead of "labels")
- Useful inline feedback is provided when the user enters a bad value in the JSON editor (eg `"cpus": "1"` instead of `"cpus": 1`)

**Comment by pierlo-upitup** [comment]
Adding to this: as an MVP we should surface server-side validation errors.

Currently
1. Switch to JSON editor
2. Enter bad CPU value, e.g. "foo"
3. click Create
4. No error is shown

ACs
- if using the JSON editor, show individual errors at the bottom of the editor like we do for generic server-side errors


Made up example:

![screen shot 2016-02-29 at 12 45 10](https://cloud.githubusercontent.com/assets/1078545/13393530/4e3a9f3e-dee2-11e5-9024-fc865edede06.png)

Alternatively, we could provide a generic error saying that the JSON is not correct if it's simpler. Either way I think this should be part of the MVP for the JSON editor, as we are hiding vital feedback from the user. 

cc @philipnrmn @leemunroe

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2288. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
