### ISSUE TITLE
Remove JSON editor padding

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#3297]
At present the JSON editor has the same padding the as app form.

ACs
- the JSON editor entirely fills the modal body without padding. Only the title

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2159. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
