### ISSUE TITLE
Download/export app configuration as JSON

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#3298]
It would be very useful to allow users to export their app configurations as JSON; there are a host of use cases for this from templates to moving app configurations to automated deployment to users who prefer to edit app configurations locally. 

Note that this is obstructed by the lack of an app configuration retrieval endpoint. As we can only retrieve the detail of the whole app, it's currently impossible in the UI to tell a manually assigned port, either in `ports` or in the various `container` ports fields, from a randomly assigned port. However, the ticket could reasonably be delivered with this as a known issue. 

ACs
- a button exists which allows users to download their app configuration

**Comment by leemunroe** [comment]
Some ideas:
* "Download JSON Config" button in the config tab
* "Copy JSON" button in the JSON editor
* "View Raw JSON" in the config tab
* "View JSON" button which opens the edit modal in JSON mode

**Comment by pgraemer** [comment]
would love to see that!

**Comment by leemunroe** [comment]
![image](https://cloud.githubusercontent.com/assets/15963/13521636/f020198c-e19e-11e5-89ec-2109210d7cd6.png)

1. Button with "Download JSON"
1. Do we still need the "Refresh" button or can we remove it?

**Comment by philipnrmn** [comment]
Looks great! +1 on removing the refresh button.

**Comment by philipnrmn** [comment]
Slightly related: https://github.com/mesosphere/marathon/issues/3170

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1746. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
