### ISSUE TITLE
Code folding in JSON editor

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#3299]
It would be nice to have code folding which allowed the larger sections of a JSON configuration, eg `container` and `healthChecks`, to be folded. It would be even nicer if they folded with respect to the state of the collapsible sections in the form.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2284. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
