### ISSUE TITLE
Form validation after making changes in JSON editor

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#3300]
- Open app modal, switch to JSON view
- Make a 'bad' change like `"labels": { "": "12345" }`
- Switch back to form view
- Labels field should be open and the error highlighted

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2550. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
