### ISSUE TITLE
Marathon UI hangs after being open for a while

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#3304]
Whenever I start hearing my macbook trying to take off I know I forgot to close one of marathon tabs.

![whoa](http://i.imgur.com/ZXR2DAQ.png)

Usually happens on task list view, but I cannot be sure.

**Comment by philipnrmn** [comment]
That's not good! We fixed a serious memory leak [back in 0.14.1](https://github.com/mesosphere/marathon-ui/pull/476), can you let us know what version of the UI you're running? Typing `g v` should bring up an alert with the relevant detail.

**Comment by bobrik** [comment]
0.15.4, 0.15.5

**Comment by philipnrmn** [comment]
OK, thanks for the report. We'll look into it. Anything in particular triggering it? Anything unusual about your workload?
