### ISSUE TITLE
Specify integer value of tasks to update at a time during rolling update, rather than percentage.

### ISSUE THREAD

**Issue by dchesterman** [mesosphere/marathon#3315]
Note sure if this is covered somewhere but we have a use case to only update one node at a time of a deployed application.  It would be great if we could specify a new attribute that allowed you to define how many nodes to update at a time.  I see its called out in the original design docs here https://mesosphere.github.io/marathon/docs/deployment-design-doc.html#rolling-upgrade

**Comment by orlandohohmeier** [comment]
Hi @dchesterman thanks for the request! Could you please provide a little more insight on why you need to update a specific number of instances/nodes at the time? Why is the `minimumHealthCapacity` not working for you? This will help validating different solutions.

**Comment by dchesterman** [comment]
Sure.  I'm interested in being able to run a more stateful application through marathon that could be sensitive to losing more than one node at a time.  It may be able to handle more failures but for safety, I'd rather just explicitly define it to roll one at a time.

I haven't had a chance to dig in at all to see what sort of precision can be reached with the existing percentage based allocation across an application with potentially hundreds of instances, but it would be great if it was just that explicit integer definition and no guess work was required.

**Comment by drcrallen** [comment]
I have a service that is also very stateful, and has HA achieved by replication in "lower SLA" tiers of the service.

As such the upgrade of a particular SLA-tier app in marathon is bound, not by the HA achieved in that app, but of the failover application tier's ability to handle the failover, regardless of the quantity of nodes in the strict-SLA tier.

If I wanted to I could kill the entire strict-SLA tier and have all requests failover to the lower tier, but then the customer would definitely notice the upgrade. By upgrading only a few nodes a a time, the lower-SLA tier is still able to service the requests without noteably impacting customer experience.

As such, being able to specify "one instance at a time" or "5 instances at a time" is WAY more desired than x% at a time.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2539. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2539. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
