### ISSUE TITLE
Marathon can kill lots of services at once if its host gets overloaded

### ISSUE THREAD

**Issue by EvanKrall** [mesosphere/marathon#3317]
If the box running Marathon gets overloaded / its NIC gets saturated, healthchecks for many different tasks may fail at once.

This, combined with the fact that Marathon kills unhealthy tasks before starting new ones and waiting for them to come up, means that a minute or so of high load on your Marathon master can cause all instances of your apps to die, depending on your health check parameters.

Some changes that might solve this issue:
1. When tasks are unhealthy, start new tasks (and wait for their healthchecks to pass) before killing old ones. (my preferred solution, as this would be helpful in other situations. #3318)
2. Globally rate-limiting task kills. This would limit the damage of a short-lived master overload.
3. A circuit-breaker on the health check kills when enough health checks fail in a short period of time. This would limit the damage of a longer period of overload.

cc @solarkennedy @nhandler @rob-johnson

**Comment by orlandohohmeier** [comment]
Hi @EvanKrall thanks a bunch for reporting this and your proposals! We definitely need to look into this and evaluate the different solutions to make Marathon even more reliable.

/cc @aquamatthias

**Comment by orlandohohmeier** [comment]
In the meantime I suggest to use the `command` health checks to work around the network limitations as they are executed localy by Mesos on the agent running the corresponding tasks. 
For details please refer to https://mesosphere.github.io/marathon/docs/health-checks.html

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2492. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2492. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
