### ISSUE TITLE
Start new tasks and wait for their health checks to pass before killing unhealthy tasks

### ISSUE THREAD

**Issue by EvanKrall** [mesosphere/marathon#3318]
Similar to #2104, but this ticket goes further.

Marathon's task killing can happen faster than new instances can start up. The following conditions can aggravate this:
- Your application only has 1 or a few instances configured
- Something happens (e.g. #3317) that causes many healthchecks to die at once.
- Your application takes a long time to start up
- The Mesos cluster does not have enough resources free for replacement tasks (i.e. some other framework is taking those resources before Marathon can use them to start replacements)

When Marathon detects an unhealthy instance, it should start a new instance and wait for its health checks to pass before killing the old ones.

I'm not sure what the correct behavior should be when the unhealthy instance becomes healthy again. I think it's valid to stop starting a new instance, or go ahead and start the new instance anyway, then kill the old one.

Ideally, this would all be controlled by the `minimumHealthCapacity` and `maximumOverCapacity` parameters.

**Comment by EvanKrall** [comment]
cc @solarkennedy @nhandler @rob-johnson

**Comment by orlandohohmeier** [comment]
@EvanKrall Thanks alot for reporting this! We will look into it along with mesosphere/marathon#3317 
In the meantime I suggest to use `command` health checks as proposed in mesosphere/marathon#3317 as well as sufficient `upgradeStrategy` and `acceptedResourceRoles` settings to mitigate the issues. 

For details please refert to https://mesosphere.github.io/marathon/docs/rest-api.html and https://mesosphere.github.io/marathon/docs/health-checks.html

**Comment by jasongilanfarr** [comment]
I feel like this is the current behavior (if appropriately configured) but feel free to reopen if it isn't.
