### ISSUE TITLE
how to pass parameters from dependent apps to the target app?

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#3321]
how to passing parameters from dependent apps to the target app?

thanks for your help!

**Comment by orlandohohmeier** [comment]
@junneyang There is no way to pass parameters from dependent apps, as far as I know. Could you please provide a little more context? Maybe there is another (better) way to solve your problem.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2622. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2622. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
