### ISSUE TITLE
Expose a direct link to Mesos

### ISSUE THREAD

**Issue by luismfonseca** [mesosphere/marathon#3322]
It would be helpful for me if Marathon UI had a direct link to Mesos master.

For example:
<img width="825" alt="screen shot 2016-02-24 at 15 03 17" src="https://cloud.githubusercontent.com/assets/2430467/13289407/dbffb856-db07-11e5-9565-ba6fac3f926c.png">

Not sure if Marathon could receive the public link to Mesos or if it could just redirect to a random machine at the Mesos port...

**Comment by janisz** [comment]
It already has link to Mesos in About section.

**Comment by orlandohohmeier** [comment]
![](https://cloud.githubusercontent.com/assets/647035/13296387/a24a9a42-db2d-11e5-8abb-5bf33d76ce49.png)

Hi @luismfonseca as @janisz said, there is already a "link"/url pointing to the Mesos leader UI in the about section, but we should actually link it.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2190. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2190. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
