### ISSUE TITLE
Change sidebar application status title

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#3324]
The sidebar status count (sidebar status filter component) quite confusing, at least for newcomers, as it's not clear that it is about application and not instances/tasks. Thus we should change the sidebar application status title as proposed in mesosphere/marathon#3275

**Comment by orlandohohmeier** [comment]
![](https://cloud.githubusercontent.com/assets/647035/13291900/e7914d4e-db19-11e5-8811-36bbd1626404.png)

Looks a little squeezed with the new title. What do you think @leemunroe?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1863. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1863. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
