### ISSUE TITLE
Environmental variables for Marathon Authentication

### ISSUE THREAD

**Issue by akamalov** [mesosphere/marathon#3329]
Greetings,

Wondering if anyone can point to a right direction where I can find Marathon 0.14 environmental variables for:

```
--mesos_authentication_secret_file
--mesos_authentication_principal 
```
I tried both **MESOS_AUTHENTICATION_PRINCIPAL** and **MESOSPHERE_AUTHENTICATION_PRINCIPAL** and none of them worked :(

Thanks so much in advance!!

Alex

**Comment by orlandohohmeier** [comment]
Hi @akamalov all `MARATHON_XXX=yyy` variables are interpreted as application parameters, thus 
`MARATHON_MESOS_AUTHENTICATION_SECRET_FILE` and `MARATHON_MESOS_AUTHENTICATION_PRINCIPAL`  should do the trick.

**Comment by akamalov** [comment]
Orlando, 

Thank you so much for the prompt reply.
