### ISSUE TITLE
Remember create modal state OR provide warning on close

### ISSUE THREAD

**Issue by leemunroe** [mesosphere/marathon#3332]
Something that has came up in user tests, particularly testing out the new JSON editor.

User entered a bunch of JSON, then closed the modal to check something, then clicked create button and the create modal and JSON editor had reset. Frustrating if using the form. Even more frustrating if using JSON editor. And I imagine a lot of users may close the form to look at another app to copy JSON.

Ideal behavior would be to remember what the user had already entered in the create modal.

If not possible, a yellow warning dialog to warn the user that unsaved changes will be lost, would help.

cc @philipnrmn

**Comment by philipnrmn** [comment]
I fall victim to this all the time for slightly different reason - as a heavy `vim` user I tend to hit the `Esc` key reflexively when I went to correct something, which closes the modal, sometimes losing a lot of changes. 

Good to know it's not just me.

**Comment by philipnrmn** [comment]
Incidentally, this is IMO another reason to consider moving to a multi-stage app creation process. Retaining unsaved state on the client side would be practical enough here.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2152. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2152. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
