### ISSUE TITLE
Deprecate healthchecks with are not pushed the Mesos Agent

### ISSUE THREAD

**Issue by mwasn** [mesosphere/marathon#3334]
JIRA Key: MARATHON-839
Reporter: Sargun Dhillon
Priority: High

Description:
We should deprecate healtchecks that are not done by Mesos on the slave. Currently, this includes the HTTP, and TCP healthcheck. The current pattern of healthchecking from the framework is counter-productive in that it's Marathon specific, and it's hard to extract information from. In addition, as the network team is implementing filtering, we have to take into account remote healthchecking from a framework instance which may change.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1714. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1714. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
