### ISSUE TITLE
id validation question

### ISSUE THREAD

**Issue by fengyehong** [mesosphere/marathon#3336]
Marathon id can now only contain digits (`0-9`), dashes (`-`), dots (`.`), and lowercase letters (`a-z`), and use a regular expression `^(([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])\\.)*([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])$` to validate it. 

As underline `_` is widely accepted in many system's namespace, is it possible Marathon can accept `_` too? 
1. Naming is more flexible and gives user more choices when naming their apps
2. Makes it easier to integrate with 3rd party systems(eg. account management system), because resuing part of its namespace is possible (simply replacing `_` with `-` is not good as we may have both `a-b` and `a_b`)

Thanks.

**Comment by orlandohohmeier** [comment]
Hi @fengyehong, I can't think of reason why underscores `_` shouldn't be allowed in app ids,  maybe some Mesos, Zookeeper constraints I'm not aware of...
It shouldn't be too difficult to adjust the regular expression. So if you want to give it a try, pull request welcome! 

/cc @gkleiman

**Comment by orlandohohmeier** [comment]
@fengyehong I asked the team, just to be sure, and they just told me that Marathon restricts app ids to the set of allowed characters in DNS hostnames ([RFC 1123](https://tools.ietf.org/html/rfc1123)), where `/` is replaced with `.` and then the name is reversed – `/org/example/app` turns into `app.example.org`. 

I hope you're ok closing this issue, as I feel we should stick to that restriction.

/cc @BenWhitehead

**Comment by fengyehong** [comment]
Thank you @orlandohohmeier for your clarification. It's really elegant transforming from `/org/example/app` to `app.example.org`.

But before seeing your comment, I was not aware of it and have no idea where the restriction comes from. So I am curious how many users know and rely on this feature?

*By the way, I checked Mesos and Zookeeper, didn't found any kind of naming restriction.*

**Comment by orlandohohmeier** [comment]
Yeah, you're right! We should include this in our documentation. As always PRs welcome.

**Comment by jasongilanfarr** [comment]
Closing out. If it would really be helpful to understand why we don't allow _, please open a PR to update the docs. I don't see a compelling reason to keep this open as we choose to restrict app ids to suffice other needs. If we take this to the extreme, we would need to document why we don't support arbitrary characters.
