### ISSUE TITLE
Expose container port in the healthcheck environment

### ISSUE THREAD

**Issue by lloesche** [mesosphere/marathon#3340]
Command healthchecks are being executed inside the container now. Therefor it would make sense to not only have $HOST and $PORT0... but also sth. like $CONTAINER_PORT0 when bridge networking is used.

Right now when I run a command healthcheck

```
bash -c "$ </dev/tcp/$HOST/$PORT0"
```

the traffic will leave the container using the docker0 interface and come back in on e.g. eth0.
This means I need a firewall rule that allows this traffic on the host even though I'm just trying to check a local service.

What would be much neater is a check like this:

```
bash -c "$ </dev/tcp/localhost/$CONTAINER_PORT0"
```

That way the traffic never leaves the container.

Of course I could hard code the well known container port for every application that I run but a more generic way that universally works for all apps would be much nicer.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2406. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2406. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
