### ISSUE TITLE
Allow fine-grained capability management of docker containers

### ISSUE THREAD

**Issue by crucidal** [mesosphere/marathon#3341]
Currently a docker container can be launched either privileged or not.
As a work-around to this issue we're currently manually starting our containers via CMD actions and adding fine-grained capabilties to the docker containers.

However, it would be nice if marathon could do this natively.
Ideally the privileged flag should stay but in addition, if it is false  you should be able to provide 0 to * amount of fine-grained flags.ie. privli--cap-add=sys_admin.
list of flags I'm talking about can be found almost at the bottom of this page: https://docs.docker.com/engine/reference/run/#runtime-privilege-and-linux-capabilities

(tip: search 'Capability Key' to quickly get to the list)

**Comment by orlandohohmeier** [comment]
Hi @crucidal, there is a docker `parameters` object which allows you to supply arbitrary command-line options for the docker run command. You should be able to use this object to supply these fine-grained capability keys and configure docker as you desire.

For details please refer to https://mesosphere.github.io/marathon/docs/native-docker.html

**Comment by xiaods** [comment]
use parameters can support your request

**Comment by crucidal** [comment]
Thanks guys. This is a feature I completely missed.
