### ISSUE TITLE
Passing SRV records (Service DiscoveryInfo) for non-docker tasks

### ISSUE THREAD

**Issue by crucidal** [mesosphere/marathon#3342]
Marathon automatically provides DiscoveryInfo to Mesos when a docker container is launched.
However, the SRV records are incomplete (port information is missing) when the task is a normal CMD action.

It would be nice if we could either post this information manually or have marathon automatically pass this information properly.

**Comment by gkleiman** [comment]
@crucidal thanks for creating an issue. Until now Marathon only adds DiscoveryInfo if the app uses IP-per-Task and specifies discovery information.

We merged https://github.com/mesosphere/marathon/pull/3302 yesterday, which makes Marathon always add the DiscoveryInfo and will be included in the next release.

Please re-open this issue if the functionality added in the PR isn't enough.
