### ISSUE TITLE
Directly open the mesos console for a task instance

### ISSUE THREAD

**Issue by crucidal** [mesosphere/marathon#3343]
To start: The direct links to download the logs files are a really nice addition! :-)
![console](https://cloud.githubusercontent.com/assets/14801878/13322318/38b181ca-dbd4-11e5-86fe-4f634754d647.PNG)

I'd like to suggest a little tweak though: Visually, keep it exactly like this! :-)
Functionally: Point the file icon to the download url of the output and the name of the output (stdout or stderr) to the url which directly opens the mesos console.

When an app is unhealthy the first thing you want to do is to check the console output. to see what's going on at that moment.

**Comment by orlandohohmeier** [comment]
@crucidal there is already an issue ( #3244 ) requesting direct (in the browser) log access and we even have a first design. I'd like to close this issue as it kinda duplicates #3244, hope you don't mind.
