### ISSUE TITLE
what does the disk parameter use for?

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#3349]
the API Doc(Version 0.15.3):
{
  "id": "/foo",
  "instances": 2,
  "cmd": "sleep 1000",
  "cpus": 0.1,
  "disk": 0,
  "mem": 16,

could it limit the disk usage on the target nodes?

thanks very much!

**Comment by meichstedt** [comment]
Hey @junneyang that's indeed what it does. Additionally, Marathon won't launch a task on an agent if the required disk size is not offered.

Sadly enough there's a rather old ticket to update the docs for that: #1341
@sascala can you please help in documenting this integral part of the api, if you haven't already? thanks!

**Comment by junneyang** [comment]
does this support nfs?
if my hosts mount to nfs server:
root@native-yangjun-5-5-24-31:~# df -h
Filesystem            Size  Used Avail Use% Mounted on
/dev/vda1              25G   18G  5.7G  77% /
none                  4.0K     0  4.0K   0% /sys/fs/cgroup
udev                  2.0G   12K  2.0G   1% /dev
tmpfs                 396M  340K  395M   1% /run
none                  5.0M     0  5.0M   0% /run/lock
none                  2.0G   88K  2.0G   1% /run/shm
none                  100M     0  100M   0% /run/user
**10.5.24.3:fileserver  493G  6.7G  461G   2% /opt/fileserver**

**Comment by junneyang** [comment]
![qq 20160301133335](https://cloud.githubusercontent.com/assets/6802322/13418633/3c8f4746-dfb2-11e5-8e0c-46fd45d62b9a.png)
