### ISSUE TITLE
Allow sending notifications of crashed tasks

### ISSUE THREAD

**Issue by logankp** [mesosphere/marathon#3351]
If a task/container crashes in Marathon, we would like to be able to get a notification (email) of the crash. Being able to configure limits so we don't get an email for tasks constantly going up and down would be great as well.

**Comment by jolexa** [comment]
You can already do this with the marathon event stream. Of course, it will require some plumbing to AWS SNS, a logging aggregator, or similar service to meet your needs.

**Comment by logankp** [comment]
That would work, but I was hoping for something a little more integrated. If you'd be willing to accept this in the core product, I'd be more than happy to help with it.

**Comment by jolexa** [comment]
Just to note, I'm not a contributor, just a community member.

**Comment by aldipower** [comment]
Hi @logankp !

As this is a slightly specific use-case in my opinion I would follow @jolexa suggestion of using the event stream.
Marathon shouldn't be responsible for sending emails, this has a lot of implications.

**Comment by logankp** [comment]
@aldipower Makes sense. I'll start poking around the event stream.

Thanks!
