### ISSUE TITLE
Unable to view stdout/stderr of tasks externally with a proxied cluster setup

### ISSUE THREAD

**Issue by sgnn7** [mesosphere/marathon#3352]
Current stdout/stderr buttons use slave addresses that are sent to the client's browser to fetch the logs which only works if the user can resolve the address and access those slaves but this doesn't work in a proxied environment like we (and I'm guessing other people too) use since the slave addresses look something like `http://ip-172-30-xx-xx.region-name.compute.internal:5050/version?jsonp=jsonp_somehash` that resolve to private ranges. 

It would be nice if Marathon could proxy the log content rather than do the direct download or alternatively have a way to prefix this generated URL with the proxy address.

**Comment by aldipower** [comment]
Hi @sgnn7 !

This sounds very reasonable to me, we will think about this.

**Comment by sds** [comment]
In our case, the problem is simply that if you serve Marathon behind a proxy over HTTPS, the link fails to load because it attempts to fetch from the Mesos master over HTTP.

```
main.js:36 Mixed Content: The page at 'https://marathon/ui/#/apps/%2Fmyapp' was loaded over HTTPS, but requested an insecure script 'http://mesos-master:5050/master/state.json?jsonp=jsonp_154e13dd1f8'. This request has been blocked; the content must be served over HTTPS.
```

This is related to the following open issue in the Mesos project: https://issues.apache.org/jira/browse/MESOS-2856

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2183. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2183. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
