### ISSUE TITLE
when apps migrate to other host, how to guarantee the volume migrate as well?

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#3355]
thanks very much!

**Comment by meichstedt** [comment]
Can you please be more specific with your question? What is `the volume` here?

**Comment by junneyang** [comment]
docker example:
"volumes": [
                    {
                        "containerPath": "aaa",
                        "hostPath": "aaa",
                        "mode": "RW"
                    },
                    {
                        "containerPath": "bbb",
                        "hostPath": "bbb",
                        "mode": "RW"
                    }
                ]
if container app migrates to other host,  how to guarantee the volume migrate as well?

**Comment by xiaods** [comment]
you need a plugin to migrate the external volume

**Comment by junneyang** [comment]
@xiaods 
would you please give me some suggest and reference?
tahnks very much!

**Comment by xiaods** [comment]
yes, please see here: https://github.com/ClusterHQ/mesos-module-flocker

**Comment by junneyang** [comment]
@xiaods 
I'll learn about it, thanks !
