### ISSUE TITLE
Support acceptedResourceRoles at granularity of each entry in portMappings

### ISSUE THREAD

**Issue by drewrobb** [mesosphere/marathon#3356]
We have an app using two ports. We have `acceptedResourceRoles = ["special-role", "*"]` configured for this app. On the slave for purposes of example we have `resources=ports(*):[31000-32000];ports(special-role):[8000-9000]` and marathon configured to use both roles. We would like the app's first port to use a port from 8000-9000 but the second port to use a port from 31000-32000 and specifically never from 8000-9000. The purpose of this configuration is to allow different host level firewall settings between the two port ranges. The current marathon API does not allow this.

I propose a per port portMappings field `container.docker.portMappings.[].acceptedResourceRoles` configuration field that if present would override the top level `acceptedResourceRoles` for that application. Then our portMappings for this example app would look something like this:

```
portMappings = [
{hostPort: 0, acceptedResourceRoles: 'special-role'}, 
{hostPort: 0, acceptedResourceRoles: '*'}
]
```

I'm aware of the `requirePorts` setting, however it is not very desirable to have to pick a specific host port for each application.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2388. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2388. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
