### ISSUE TITLE
Health Checks not running on some instances after many scaling operations

### ISSUE THREAD

**Issue by drewrobb** [mesosphere/marathon#3357]
@kolloch you left a FIXME [here](https://github.com/mesosphere/marathon/blob/a35f1c9f4f0dec7501de55efa72742510afe6d1c/src/main/scala/mesosphere/marathon/health/MarathonHealthCheckManager.scala#L149), but I didn't see any corresponding issue so I'm opening one.

We are encountering this problem quite frequently in production due to having applications that are automatically scaled against daily load changes. Is the fix you had in mind of falling back to use the most recent version of the app for the health check definition still valid? I could help out if that is all that is needed.

**Comment by drewrobb** [comment]
I took a stab at fixing this, but it didn't seem to be the simple fix that I thought it might have been. Any guidance would be appreciated.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1683. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1683. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
