### ISSUE TITLE
Expose server-side validation errors in JSON editor

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#3360]
We should surface server-side validation errors.

Currently
1. Switch to JSON editor
2. Enter bad CPU value, e.g. "foo"
3. click Create
4. No error is shown

ACs
- if using the JSON editor, show individual errors at the bottom of the editor like we do for generic server-side errors

Made up example:

![screen shot 2016-02-29 at 12 45 10](https://cloud.githubusercontent.com/assets/1078545/13393530/4e3a9f3e-dee2-11e5-9024-fc865edede06.png)

Alternatively, we could provide a generic error saying that the JSON is not correct if it's simpler. Either way I think this should be part of the MVP for the JSON editor, as we are hiding vital feedback from the user. 

cc @philipnrmn @leemunroe

**Comment by leemunroe** [comment]
It would be great to be as specific as possible so users know how to fix it without guessing. So I like your idea @pierlo-upitup 

Here's an example of how it *could* look in the restyle.

https://invis.io/CX697AAN9

**Comment by pierlo-upitup** [comment]
cc @orlandohohmeier @Poltergeist  check the link above for general validation error updates
