### ISSUE TITLE
Show multiple general errors in app modal

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#3361]
Since #3255 was merged, it's possible to have multiple errors in errors relating to `self`. 

We should consider showing multiple errors in these circumstances. It would be good to understand what these error messages might look like - cc @alexanderweber to shed some light on this.

**Comment by alexanderweber** [comment]
Thank you for getting back to me on this. Please also have a quick look into #3387 as a PR for #3339.

We decided to make our validation output look exactly like the output produced by the external play-json validation library. This way we would not distinguish between JSON syntax or object related errors. The JSON output structure is as follows:

```
{
  "message": "'Invalid JSON', meaning the error is of JSON nature",
  "details": [
    {
      "path": "path to the occurrence of the error",
      "errors": [
        "property has an error, e.g. it does not begin with a '/'",
        "property also has a second error, e.g. it is being empty"
      ]
    }
  ]
}
```  
To make it concrete, there is validation going on app level, which might throw following:

```
{
  "message": "Object is not valid",
  "details": [
    {
      "path": "/",
      "errors": [
        "AppDefinition must either contain one of 'cmd' or 'args', and/or a 'container'.",
        "Health check port indices must address an element of the ports array or container port mappings."
    }
  ]
}
```
That one should be generated if:
- `cmd`, `args` nor `container` is defined
- **AND** HealthCheck ports are not of a command protocol type and are not in the list of host ports
Both of this errors do not have a specific property of error. These are errors of general nature on this object.

Now imagine the `id` also being not valid. That would produce:
 ```
{
  "message": "Object is not valid",
  "details": [
    {
      "path": "/",
      "errors": [
        "AppDefinition must either contain one of 'cmd' or 'args', and/or a 'container'.",
        "Health check port indices must address an element of the ports array or container port mappings."
    },
    {
      "path": "/id",
      "errors": [
         "must match regular expression '^(([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])\\.)*([a-z0-9]|[a-z0-9][a-z0-9\\-]*[a-z0-9])|(\\.|\\.\\.)$'"
      ]
    }
  ]
}
```
I hope these examples elaborate the reason behind generating an `errors` array of messages.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2397. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2397. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
