### ISSUE TITLE
API Request: Scale application id by arbitrary number

### ISSUE THREAD

**Issue by jolexa** [mesosphere/marathon#3366]
Right now, to increase the number of application instances by any amount, I have to first parse the currently number of running instances, do math, then issue a PUT to the `/v2/apps/{appID}` endpoint. Is there an easier way to do this?

This is a request to add a PUT endpoint to the appid to change the number of instances relative to the current number running. Something like, "scale +2" would be nice.

**Comment by aldipower** [comment]
Hi @jolexa !

Currently you could scale complete groups by a factor with the `scaleBy` key. Maybe this already helps you?

An example PUT request on the groups endpoint could look like this:
```
curl -X PUT http://localhost:8080/v2/groups/myGroupId  -H "Content-Type: application/json" -d '{"scaleBy":"1.5"}'
```

This scales the complete group by a factor of 1.5 .

**Comment by jolexa** [comment]
That might work for us. Not all of our applications are grouped though (most aren't)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1870. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1870. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
