### ISSUE TITLE
Be able to change syslog facility

### ISSUE THREAD

**Issue by jimonreal** [mesosphere/marathon#3372]
It would be helpful if marathon would let change the syslog facilty from user to another one, like localX.
This way I could send marathon logs, mesos logs and any other to different facilities and make different things on each facility.

**Comment by aldipower** [comment]
Good idea, we are already thinking about some solutions.
https://github.com/mesosphere/chaos/issues/53

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2523. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2523. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
