### ISSUE TITLE
Don't rely on the presence of fields in task definitions

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#3376]
In various places across the UI, where we render tasks as returned by the `/v2/apps/{appID}` endpoint in views, we reference properties in `task` like `version` and `startedAt`. 

Since resident tasks became available in the service, we can no longer rely on these fields. We need to check every reference and make it safe to avoid potentially serious UI bugs. 

Example `task` with all fields present:
```
{
    "id": "resident1.992cc5af-dfb9-11e5-9c48-227ab8d0dd36",
    "slaveId": "4b0c56ca-2b53-4c34-9c86-34e82b60effa-S0",
    "host": "master",
    "startedAt": "2016-03-01T15:17:50.666Z",
    "stagedAt": "2016-03-01T15:17:50.599Z",
    "ports": [],
    "ipAddresses": [],
    "version": "2016-03-01T14:44:23.148Z",
    "localVolumes": [
        {
            "containerPath": "var2",
            "persistenceId": "resident1#var2#992cc5ae-dfb9-11e5-9c48-227ab8d0dd36"
        }
    ],
    "appId": "/resident1"
}
```

Example resident `task`, missing some fields:
```
{
    "id": "resident1.c2ba3e3c-dfb8-11e5-9c48-227ab8d0dd36",
    "slaveId": "4b0c56ca-2b53-4c34-9c86-34e82b60effa-S0",
    "host": "master",
    "localVolumes": [
        {
            "containerPath": "var",
            "persistenceId": "resident1#var#c2ba172b-dfb8-11e5-9c48-227ab8d0dd36"
        }
    ],
    "appId": "/resident1"
}
```

**Comment by aldipower** [comment]
I've had a second look and it seems this is completely covered now with e.g. null-checks.
So I will close this.

**Comment by philipnrmn** [comment]
Thanks for picking this up @aldipower !
