### ISSUE TITLE
RAML API doc javascript takes 30s to load

### ISSUE THREAD

**Issue by air** [mesosphere/marathon#3378]
The resource `api-console/scripts/api-console-vendor.js` is 2.9MB and takes 31s to load from our internal cluster. The impression is that our API docs are slow. Can we compress this?

I see some prior work at e.g. https://github.com/mulesoft/api-console/pull/170

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4399. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4399. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
