### ISSUE TITLE
Named Arguments for docker (--env-file)

### ISSUE THREAD

**Issue by mv012004** [mesosphere/marathon#3380]
Is there a way we can pass the --env-file argument to the docker run command through marathon/mesos, I played around with a lot of configurations based on the documentation, but it appends the --env-file argument after the image name, i looked at the issue #1740 which was closed, correcting the documentation. Which is fine, what I want is basically similar to the env field should have an option for env-file which will take that as an input for docker to process all the fields in the file as env variables.

`docker run --privileged -c 1024 -m 2726297600 -e MARATHON_APP_VERSION=2016-03-01T22:55:58.336Z -e HOST=testhost -e PORT_5001=9000 -e MESOS_TASK_ID=test.c3e8be83-e000-11e5-9899-1232639cf0af -e PORT=11524 -e PORTS=11524 -e MARATHON_APP_ID=/test -e PORT0=11524 -e MESOS_SANDBOX=/mnt/mesos/sandbox  -v /usr/local/abc/test/config:/app/test/config:rw -v /tmp/test/tmp/slaves/20160222-111307-1085656586-8085-6433-S0/frameworks/20160222-111307-1085656586-8085-6433-0000/executors/test.c3e8be83-e000-11e5-9899-1232639cf0af/runs/696dcc62-548a-4654-9439-74c58cd56e6d:/mnt/mesos/sandbox --net bridge -p 11524:5001/tcp --name mesos-20160222-111307-1085656586-8085-6433-S0.696dcc62-548a-4654-9439-74c58cd56e6d test.com:443/testsuite/test:testtag --env-file /usr/local/abc/test/config/test.list`

I have put the following under the containers section in the Marathon JSON
`
"args": [
        "--env-file", "/usr/local/abc/test/config/test.list"
       ]
`
however when I manually run the command and put --env-file before the image name it works as expected. Is there something I am missing.! :|

Thanks,
Mihir

**Comment by mv012004** [comment]
Any one know about this ?

**Comment by mv012004** [comment]
Can someone help with this ?? Or point me in some direction.!

**Comment by mv012004** [comment]
Any ideas ???

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1937. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1937. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
