### ISSUE TITLE
Marathon build failed, Tests unsuccessful

### ISSUE THREAD

**Issue by RecursionTaoist** [mesosphere/marathon#3381]
cd /path/to/marathon-0.15.2/
sbt assembly
![image](https://cloud.githubusercontent.com/assets/10989916/13449082/fb598316-e062-11e5-988f-5a1c02a316b6.png)

java version "1.8.0_73"
Scala code runner version 2.11.7

**Comment by RecursionTaoist** [comment]
Failed everytime

**Comment by RecursionTaoist** [comment]
Linux <host> 3.10.0-229.el7.x86_64 #1 SMP Fri Mar 6 11:36:42 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jasongilanfarr** [comment]
Closing out as we are no longer having these issues on master.
