### ISSUE TITLE
Removing a constraint fails in Marathon web UI

### ISSUE THREAD

**Issue by akunaatrium** [mesosphere/marathon#3386]
Removing a constraint fails. Currently I have a constraint "hostname:UNIQUE" and when clear the text box and click on "Change and deploy configuration", it says:

```
Comma-separated list of valid constraints. Valid constraint format is "field:operator[:value]".
Constraint definition must be an array of strings in format: <key>, <operator>[, value]
```

Version of Marathon is 0.15.2.

**Comment by aldipower** [comment]
Hi @akunaatrium !

I can reproduce this in 0.15.*, thanx for reporting this.
Anyway I can't reproduce this in the current master, seems there are some changes at the service layer side, so is fixed for the upcoming 0.16 .

**Comment by jordmoz** [comment]
We ran into a similar issue with a GROUPBY constraint.  Removing it from the UI fails.  To work around it we just set the constraint to ```hostname:LIKE:.*``` so that it doesn't really constrain the tasks, but marathon is happy that it has a constraint.

**Comment by evanbattaglia** [comment]
I'm not 100% positive, but think I see this happenning with removing `cmd`, too.

**Comment by astawiarski** [comment]
This issue seem to be also blocking terraform marathon provider from removing constraints. It's possible to change, but removal fails.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1722. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1722. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
