### ISSUE TITLE
Validation on enumerations

### ISSUE THREAD

**Issue by zunder** [mesosphere/marathon#3388]
Validation dependent on values of enumeration unnecessarily bloat validation code. E.g.:

``` Scala
  implicit val containerValidator: Validator[Container] = {
    val volumeValidator: Validator[Volume] = new Validator[Volume] {
      override def apply(volume: Volume): Result = volume match {
        case pv: PersistentVolume => valid[PersistentVolume](PersistentVolume.persistentVolumeValidator).apply(pv)
        case dv: DockerVolume     => valid[DockerVolume](DockerVolume.dockerVolumeValidator).apply(dv)
      }
    }

    val dockerContainerValidator: Validator[Container] = validator[Container] { container =>
      container.docker is notEmpty
      container.docker.each is valid
      container.volumes is every(valid(volumeValidator))
    }

    val mesosContainerValidator: Validator[Container] = validator[Container] { container =>
      container.docker is empty
      container.volumes is every(valid(volumeValidator))
    }

    new Validator[Container] {
      override def apply(c: Container): Result = c.`type` match {
        case Mesos.ContainerInfo.Type.MESOS  => validate(c)(mesosContainerValidator)
        case Mesos.ContainerInfo.Type.DOCKER => validate(c)(dockerContainerValidator)
        case _                               => Failure(Set(RuleViolation(c.`type`, "unknown", None)))
      }
    }
```

According to [accord/issues/58](https://github.com/wix/accord/issues/58) this might be compressed like in this example:

``` Scala
  val vt = validator[Test] { t =>
    ((t.p should be == 0) and (t.n is empty)) or
    ((t.p should be == 1) and (t.n should startWith("test")))
  }
```

It is still a workaround though. A better implementation might apply with the next accord milestone.

@meichstedt regarding container validation. There is an alternative to pattern matching described in [accord/issues/58](https://github.com/wix/accord/issues/58). I tried it out and this does compile:

``` Scala
  private val volumeValidator: Validator[Volume] = new Validator[Volume] {
    override def apply(volume: Volume): Result = volume match {
      case pv: PersistentVolume => valid[PersistentVolume](PersistentVolume.persistentVolumeValidator).apply(pv)
      case dv: DockerVolume     => valid[DockerVolume](DockerVolume.dockerVolumeValidator).apply(dv)
    }
  }

  implicit val containerValidator = validator[Container] { container =>
    (((container.`type` should be == Mesos.ContainerInfo.Type.MESOS) and (container.docker is empty)) or
      ((container.`type` should be == Mesos.ContainerInfo.Type.DOCKER) and
        (container.docker is notEmpty) and (container.docker.each is valid))) and
      (container.volumes is every(valid(volumeValidator)))
  }
```

Nevertheless I find it not being a real gain towards readability. Hopefully there will be a better way, as the previous mentioned accord issue was already been labeled as an improvement for the next milestone. Let me know what your thoughts are on that matter.

**Comment by holograph** [comment]
Would appreciate your input on wix/accord#58 in terms of the ideal DSL and result model. It's good to have actual users to help prioritize enhancements :-)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2299. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2299. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
