### ISSUE TITLE
[DEFER] Ensure that `NetworkInfoList` networking still works

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3390]
In the launch task case, we always create tasks with `networking = Task.HostPorts(ports)`. See `TaskOpFactoryImpl`.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2210. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2210. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
