### ISSUE TITLE
Docker example in Marathon Application Basics page fails to run

### ISSUE THREAD

**Issue by natemurthy** [mesosphere/marathon#3399]
I have a 4 node (1 master + 3 workers) Mesos/Marathon cluster running in EC2 behind a VPC. I'm following the instructions on this page:

https://mesosphere.github.io/marathon/docs/application-basics.html

and could successfully deploy, launch, and run the first two examples on the page with no problem. But I'm having issues running the `basic-3.json` example using Docker containers. Below are some screenshots from my web dashboards:

![marathon-docker-1](https://cloud.githubusercontent.com/assets/1788878/13502915/d527533e-e121-11e5-9494-32347f62fb98.png)

![marathon-docker-2](https://cloud.githubusercontent.com/assets/1788878/13502926/dc853a60-e121-11e5-840f-945c0e9aae57.png)

![marathon-docker-3](https://cloud.githubusercontent.com/assets/1788878/13502932/e0abe742-e121-11e5-8d65-8a1b89005a89.png)

In my Marathon dashboard I am observing the `basic-3` app looping into `Waiting` -> `Deploying` ->  `Delayed` states and repeating this over and over again.

![marathon-docker-4](https://cloud.githubusercontent.com/assets/1788878/13502946/eadba248-e121-11e5-9bed-b6c98f1b52b5.png)

And in Mesos I'm just seeing everything complete with `FAILED` state over and over for the same task. I manually installed Docker on all my worker nodes. Are there some additional configurations I need to make that were omitted in the instructions above?

**Comment by junneyang** [comment]
you should provide the task parameters for analysing.
or check if your docker container could run locally without the deployment of marathon.

**Comment by aldipower** [comment]
Hey @natemurthy .
Could you also post a screenshot with the Last Task Failure in the Debug Tab.
That would be helpful to see what is going on.
Thank you.

**Comment by natemurthy** [comment]
@junneyanng yes, i can run docker container locally on my worker nodes:

```
$ sudo docker run hello-world

Hello from Docker.
This message shows that your installation appears to be working correctly.

To generate this message, Docker took the following steps:
 1. The Docker client contacted the Docker daemon.
 2. The Docker daemon pulled the "hello-world" image from the Docker Hub.
 3. The Docker daemon created a new container from that image which runs the
    executable that produces the output you are currently reading.
 4. The Docker daemon streamed that output to the Docker client, which sent it
    to your terminal.

To try something more ambitious, you can run an Ubuntu container with:
 $ docker run -it ubuntu bash

Share images, automate workflows, and more with a free Docker Hub account:
 https://hub.docker.com

For more examples and ideas, visit:
 https://docs.docker.com/userguide/
```

**Comment by natemurthy** [comment]
![Uploading docker-marathon-5.png…]()

**Comment by natemurthy** [comment]
@aldipower Screenshot of Last Task Failure from Debug Tab

![docker-marathon-5](https://cloud.githubusercontent.com/assets/1788878/13545862/8d42ecda-e24e-11e5-9e3e-7006073ab410.png)

**Comment by natemurthy** [comment]
@kolloch can you re-open this issue, we haven't resolved it yet.

**Comment by natemurthy** [comment]
Since this issue was accidentally closed, I created a new ticket: https://github.com/mesosphere/marathon/issues/3407
