### ISSUE TITLE
v0.11.0 Version Update

### ISSUE THREAD

**Issue by irmakcakmak** [mesosphere/marathon#3409]
We are running v0.11.0 and plan to update it, but as of v0.11.1, backwards compatibility is broken with the addition of zk_compression flag and the way data is stored in zk. What is the correct way of upgrading without losing Marathon state?

**Comment by bergerx** [comment]
I'm concerned about "#2984 Failed migration 0.11.1 -> 0.14.0-RC3".
Could it be safer to jump directly to 0.15.3-1 without migrating to 0.11.1 initially?

**Comment by aquamatthias** [comment]
Hey @irmakcakmak we suggest to always update zk state before updating to a newer version.
See https://mesosphere.github.io/marathon/docs/upgrade/index.html
If you are concerned, you can disable zk_compression.
@bergerx The migration logic in Marathon will handle this. You can jump directly to the latest stable version.

**Comment by irmakcakmak** [comment]
@aquamatthias thanks!
