### ISSUE TITLE
args in marathon file does not resolve env variables

### ISSUE THREAD

**Issue by triggity** [mesosphere/marathon#3416]
```cmd``` field in a marathon app config would resolve environment variables before passing them in. this is documented here: https://mesosphere.github.io/marathon/docs/ports.html

however, the ```args``` field does not have it's environment variables resolved before passing in. 
Is this a bug or deliberate and missing from the documentation?

a canonical example:

using a basic image with 
```
ENTRYPOINT ["echo"]
```
and ```args: [ "$PORT0"]```

the container logs show it echoing
```$PORT0``` instead of the expected resolved env variable for $PORT0

**Comment by aquamatthias** [comment]
Hey @triggity the args are passed directly to the exec syscall without running a shell. This is intended behavior. If you need env expansion please use `cmd` instead of `args`

**Comment by micahhausler** [comment]
@aquamatthias So is it impossible to pass a command to a docker container and have an environment variable be interpreted in that command? `cmd` is incompatible with a `container` in an app definition.

**Comment by aquamatthias** [comment]
@micahhausler Don't know what you mean by incompatible. Please see https://mesosphere.github.io/marathon/docs/native-docker.html, especially the Command vs Args section.

**Comment by micahhausler** [comment]
I see what you mean now. I got confused because the `cmd` doesn't respect the docker container's entrypoint.
