### ISSUE TITLE
Restyle About modal

### ISSUE THREAD

**Issue by leemunroe** [mesosphere/marathon#3417]
In #3305 the About Modal could do with some restyling. Here are some suggestions.

Before
![image](https://cloud.githubusercontent.com/assets/15963/13592858/e111abea-e4aa-11e5-9712-7f5e7d02a5f5.png)
- [ ] Increase the height of the modal
- [ ] Remove the logo, replace with "About Marathon" (logo is already in the header of the main UI)
- [ ] Add "x" icon top right to close modal
- [ ] Remove version from header and place at the top of the definition list
- [ ] Increase the width of the definition list `<dt>` so all words can fit
- [ ] Add 20px padding to the modal body
- [ ] Give the `<h5>` some visual hierarchy with a 1px bottom border and 10px bottom padding

After
![image](https://cloud.githubusercontent.com/assets/15963/13593043/af6ba508-e4ac-11e5-97b9-ff5242e77878.png)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2292. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2292. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
