### ISSUE TITLE
Orphaned containers with docker 1.10.2

### ISSUE THREAD

**Issue by olesku** [mesosphere/marathon#3418]
We recently had problems with hundreds of orphaned containers that Mesos had marked as TASK_FAILED and Marathon were no longer tracking even though they were still active processes running in Docker.

After going through what changes had we had done to our environment before this started to happen I tried to downgrade docker. This solved the problem.

Our environment when this happened was docker-engine-selinux-1.10.2-1, mesos 0.27 and marathon-0.15.3-1.0.463 on CentOS 7.

**Comment by aquamatthias** [comment]
Thanks @olesku for the report. Please create a mesos ticket here: https://issues.apache.org/jira since this i a mesos containerizer problem.
