### ISSUE TITLE
tasks health check result will be Unknown when mesos leader re-elect

### ISSUE THREAD

**Issue by heww** [mesosphere/marathon#3419]
tasks health check (HTTP/TCP protocol ) result will be Unknown when mesos leader re-elect (eg, mesos leader restarted) and then marathon-lb generate wrong haproxy.cfg which make web app 503.

**Comment by aquamatthias** [comment]
Hey @heww this description is very short - I think I do not understand all details. Can you provide a more detailed explanation of the problem? Steps to reproduce or logs would be helpful. Thanks!

**Comment by heww** [comment]
eg, i have three marathon nodes named control-01 control-02 and control-03, and now leader is control-01. 

i have some web apps run in marathon with http health check. then i use marathon-lb for proxy these apps, it works very well.

for some reason marathon service on control-01 restarted (marathon which i run using docker offen restarted ), then marathon cluster re-elect, for example new leader is control-02, but now the apps' health check all become to Unknown. and at this moment marathon-lb get health status change event in sse, it will regenerate its haproxy conf using marathon api, because the health checks of tasks in apps are Unknown,marathon-lb generate "empty" conf file, then the web apps will not accessible through marathon-lb.

**Comment by aquamatthias** [comment]
Hey @heww thanks for explaining the problem more clearly. 
The health state is currently held in memory (it does not make too much sense to persist this information).
So when a new leader got elected, this information has to be gathered from all tasks. 
During this time the health status is unknown.

I see 2 points here:
- why do you have that much restarts / leader elections? Perhaps you should try to find the root cause of this.
- marathon-lb chooses to not route traffic to a task with unknown health state (which is a safe default). Perhaps you can do a feature request to tweak the behavior in that situation?

**Comment by heww** [comment]
for point 1, I don't find the reason, and I think it maybe relate to https://github.com/mesosphere/marathon/issues/3022 ,here is my docker command to run marathon 
```bash
docker run -d --name marathon \
    -e JAVA_OPTS=" -verbose:gc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps -XX:+PrintHeapAtGC -XX:+PrintGCApplicationConcurrentTime -XX:+PrintGCApplicationStoppedTime  -XX:+UseConcMarkSweepGC -XX:+UseParNewGC -XX:+CMSParallelRemarkEnabled  -XX:+UseCMSCompactAtFullCollection -XX:+HeapDumpOnOutOfMemoryError" \
    -e MARATHON_ARTIFACT_STORE="file:///store" \
    -e MARATHON_EVENT_SUBSCRIBER=http_callback \
    -e MARATHON_HOSTNAME="control-03" \
    -e MARATHON_HTTP_CREDENTIALS="user:password" \
    -e MARATHON_MASTER="zk://10.10.8.139:2181,10.10.8.141:2181,10.10.8.140:2181/mesos" \
    -e MARATHON_ZK="zk://10.10.8.139:2181,10.10.8.141:2181,10.10.8.140:2181/marathon" \
    --net=host \
    -v /etc/marathon/store:/store \
    mesosphere/marathon:v0.14.2
```
where JAVA_OPTS is used to debug, at the beginning it was set to be default value which is mentioned in doc. In fact that I am not be familiar with Java/JVM.

En, I think marathon restart is a normal operation for when upgrade marathon to new version, old version will be stopped and new version started.

for point 2, now I run marathon-lb without health chech and then it solved the problem (I need more test for this)

**Comment by aquamatthias** [comment]
If you have memory problems you should see it in the logs.
You can adjust memory settings with `-Xmx` and `-Xms` 
See: http://stackoverflow.com/questions/14763079/what-are-the-xms-and-xmx-parameters-when-starting-jvms

**Comment by heww** [comment]
close it for marathon-lb will add basic LRU cache for health status https://github.com/mesosphere/marathon-lb/pull/148
