### ISSUE TITLE
Label dropdown should not have a scrollbar by default

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#3421]
<img width="988" src="https://cloud.githubusercontent.com/assets/647035/13600395/cb970746-e528-11e5-9fd5-817c0a89a74c.png">
The label dropdown should not have a scrollbar by default. `overflow-y: auto;` should do the trick.

/environment W7-IE11

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1698. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1698. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
