### ISSUE TITLE
Report kills due to failed health check in "Last Task Failure"

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#3423]
Currently (v0.15.3) Marathon can kill task due to failed health check, but it doesn't show up in "Last Task Failure" in debug tab. I propose reporting kills as task failures and showing them in debug tab.

**Comment by aquamatthias** [comment]
The current health check logic is pretty isolated and initiates a task kill, if a task becomes unhealthy. 
Since from that side it is not a task failure (as reported by mesos) we do not add this information.
I agree we should add this information.
