### ISSUE TITLE
Maintain "assign random port" settings after JSON mode switch

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#3424]
![assign-random-port-reset-issue](https://cloud.githubusercontent.com/assets/647035/13609981/c18803b2-e55b-11e5-9227-b3308a4458fe.gif)
The assign random port settings should always be maintained and should not change after using the JSON mode unless one actually changes the port setting.

**Comment by pierlo-upitup** [comment]
This depends on the API. Once an app is deployed, the `apps` endpoint will return the actual port assigned to that task. The "blueprint" knowledge about the dynamic port request is lost.

**Comment by orlandohohmeier** [comment]
Yeah, I know, but thats a different story.  We should not lose the setting after switching to the JSON edit mode.

**Comment by pierlo-upitup** [comment]
Oh I'm sorry. I misread the issue!
