### ISSUE TITLE
Modal Dialog UX enhancement: signal changes in section

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#3434]
@leemunroe I'm of the opinion there should be a way for the user to know if a section contains settings or if it's in an empty state. This is really helpful especially when editing.

For an app with env, labels and optional settings defined, I propose the following

Before:

![screen shot 2016-03-09 at 13 16 55 1](https://cloud.githubusercontent.com/assets/1078545/13635003/7f300f16-e5f9-11e5-8185-67d3515a49c8.png)

After:

![screen shot 2016-03-09 at 13 18 48](https://cloud.githubusercontent.com/assets/1078545/13635023/95ea0734-e5f9-11e5-9780-e96e27c8615f.png)

The visual hints should make it clear to the user that those sections have some settings specified.
Feel free to suggest alternative solutions!

**Comment by leemunroe** [comment]
I like your style @pierlo-upitup 

How about also making the text same color as the border for extra clarity?

**Comment by pierlo-upitup** [comment]
Yeah, good point!

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1862. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1862. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
