### ISSUE TITLE
marathon set envionment variables is  invalid!        help me!  thanks

### ISSUE THREAD

**Issue by ninyjun** [mesosphere/marathon#3435]
docker run -d --env='HOST_IP='ifconfig eth0 | grep &quot;inet addr&quot; | awk '{print $2}' | awk -F: '{print $2}''' 10.1.245.140:5000/svcdemo 
docker container is ok.      HOST_IP  is valid  in container

Bug  in marathon set envionment variables  
HOST_IP='ifconfig eth0 | grep &quot;inet addr&quot; | awk '{print $2}' | awk -F: '{print $2}''
HOST_IP  is invalid (  get original character)  in container
help me!  thanks

**Comment by Gidipp** [comment]
What you are trying to do is not really ideal. 

When you start the container through Marathon Mesos will set up few environment variables for you (you can check this running docker inspect on the docker container started in the mesos slave).

One of this environment variable is called HOST which is the hostname of the host where the container is running. You could use this variable instead.

**Comment by ninyjun** [comment]
I need to get host ip ( a service framework in container need it)

**Comment by Gidipp** [comment]
HOST is the hostname of the host.  if you have a DNS working you should't have any problem to resolve the hostname to an IP address.

**Comment by jasongilanfarr** [comment]
@ninyjun is this still a problem for you? If so, please reopen.
