### ISSUE TITLE
Inline validation messaging

### ISSUE THREAD

**Issue by leemunroe** [mesosphere/marathon#3445]
This came up in usability testing and I'm interested in your thoughts.

Validation occurs as the user is typing. This can be a good thing and a bad thing.

In the examples here it is quite a jarring experience as before I'm finished typing what I want to type I get some harsh validation which can be a jarring experience.

I would expect to not get the validation messages and red UI until I have tabbed off these inputs.

Thoughts?

![validation](https://cloud.githubusercontent.com/assets/15963/13643035/c9510f94-e5d3-11e5-984a-ccecb3624803.gif)

**Comment by jasongilanfarr** [comment]
@leemunroe is this still relevant? If so, please reopen.
