### ISSUE TITLE
Mesos details link is broken for exited tasks

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#3447]
Mesos 0.27, Marathon 0.15.3.

Working link for running task:

![image](https://cloud.githubusercontent.com/assets/89186/13646138/ff3c0db4-e625-11e5-8630-b9e320a46b74.png)

```
http://dev:5050/#/slaves/4d4fe7f9-3018-43d5-a98a-056984265a69-S0/frameworks/4d4fe7f9-3018-43d5-a98a-056984265a69-0000/executors/exit.e0582755-e625-11e5-8729-024204d08742
```

Broken link for failed task from Debug tab:

![image](https://cloud.githubusercontent.com/assets/89186/13646095/dafc8fa0-e625-11e5-9b35-087405e0062b.png)

```
http://dev:5050/#/slaves/4d4fe7f9-3018-43d5-a98a-056984265a69-S0/frameworks/4d4fe7f9-3018-43d5-a98a-056984265a69-0000/executors/
```

It redirects to main page of mesos ui with the following error in the console:

![image](https://cloud.githubusercontent.com/assets/89186/13646189/332a3fce-e626-11e5-81a9-46e36b69fa1a.png)

```
angular-1.2.3.min.js:84 TypeError: Cannot read property 'originalPath' of undefined
    at controllers.js:292
    at f.$broadcast (angular-1.2.3.min.js:103)
    at angular-route-1.2.3.min.js:11
    at D (angular-1.2.3.min.js:91)
    at D (angular-1.2.3.min.js:91)
    at angular-1.2.3.min.js:93
    at f.$eval (angular-1.2.3.min.js:101)
    at f.$digest (angular-1.2.3.min.js:98)
    at angular-1.2.3.min.js:83
    at angular-1.2.3.min.js:34
```

**Comment by abraithwaite** [comment]
:+1: ran into this multiple times.

**Comment by tmmi** [comment]
Fix is waiting for CR: https://github.com/mesosphere/marathon-ui/pull/765
