### ISSUE TITLE
Scaling delay period

### ISSUE THREAD

**Issue by ejether** [mesosphere/marathon#3449]
I'd like to see a setting that would amount to a delay period between starting healthy instances of a service so that each instance might have time to settle before another instance is started. 

Is this a feature request or is there something that I missed in the docs.  
It doesn't look like `backoffSeconds` does this, but perhaps I misread the docs?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4714. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4714. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
