### ISSUE TITLE
docker net=bridge of marathon container result in publishing non-routable address to mesos

### ISSUE THREAD

**Issue by krdi** [mesosphere/marathon#3451]
I have "dockerized" marathon.  All is ok when I use net=host, but when setting net=bridge the marathon startup can contact the mesos master, but the mesos master cannot contact marathon, as marathon seems to publish the 172 address of the container rather than the host's IP address.  The marathon configuration flag "--hostname (Optional. Default: hostname of machine): The advertised hostname that is used for the communication with the mesos master"  This flag seems to indicate (to me anyway) that the hostname (or I would "assume" an IP address as well could be substituted) and that's what would sent to mesos.  However, only the bind address (the 172 docker container IP) is sent.  Many applications (elasticsearch, zookeeper, et. al) can set a bind address and port and an advertised address and port.

So my questions is this:
Is --hostname supposed to the published address and LIBPROCESS_IP the bind address and if so this is a bug
or
Is there a way to set the publish address of the marathon server application?

Mesos, et. al. is an amazing product.  Awesome.

Thanks,
KR

**Comment by krdi** [comment]
Just to be clear, I am not speaking of marathon running a container job, but the running of marathin itself inside a docker container (on the same host as I run a containerized zookeeper and a containerized mesos master).

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4557. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4557. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
