### ISSUE TITLE
Documentation for event subscribers

### ISSUE THREAD

**Issue by hekaldama** [mesosphere/marathon#3452]
My event subscriber used to respond with a HTTP status code of 400 when it didn't know about the appId it was being told about in the event message. It appears that since the change a7a0b474bb (may be other places) my event subscriber cannot respond with non 200 because it will be marked as 'unresponsive'.

Is there documentation for how an event subscriber should respond and with what? If not, can we get some written? If this is not the desired behavior, can we get it remedied? I feel like an 'unresponsive' host should be one that a successful connection cannot be made to, not one that responds non 200, but I could be persuaded otherwise.

Thank you in advance.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4089. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4089. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
