### ISSUE TITLE
[DEFER] Resident Tasks: Reconcile reservations/volumes

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3455]
If a new task is launched and we still have some reservations/volumes available, no new reservations/volumes created because we assume that we can launch tasks on the existing reservations/volumes. This becomes problematic if a Mesos agent becomes permanently unavailable. Similar to tasks we need to reconcile the state, e.g. request offers and mark when we have seen reservations for the last time. If the last time we saw a reservation is long ago (configurable), we assume that it does not exist anymore.

This is related to #3455.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2342. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2342. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
