### ISSUE TITLE
Removing an empty group with name "map" results in a 405 error

### ISSUE THREAD

**Issue by Poltergeist** [mesosphere/marathon#3459]
Setting up an empty group with the name `map` makes this group unremovable. If the user tries to remove it the API does return a `405 Method not allowed` status without a message body.

Scenario:
- Creating an empty group called `map`.
- Destroying it.
- API returns 405.

**Comment by lexwbr** [comment]
@Poltergeist I am trying to reconstruct the issue by doing following steps through API:

1. POST on /v2/groups with JSON: `{ "id": "/map" }`
2. DELETE on /v2/groups/map

Last step yields a 200 status. Is there anything that you do differently?

**Comment by aquamatthias** [comment]
Tested on Marathon master.
Could not reproduce.
