### ISSUE TITLE
Creating an app with the name of an empty group overrides the group

### ISSUE THREAD

**Issue by Poltergeist** [mesosphere/marathon#3461]
If a app is created with the same name as and empty group the empty group is removed. 
This also applies if the empty group does contain another empty group.

Scenario:
- Create an empty group named `test`
- Create an app with the id `test`.
  App definition:

``` JSON

{
  "cmd": "sleep 100;",
  "cpus": 1,
  "mem": 128,
  "disk": 0,
  "instances": 1,
  "id": "test"
}
```

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1700. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1700. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
