### ISSUE TITLE
Validation errors should only be shown if the user had the chance to enter the valid values.

### ISSUE THREAD

**Issue by Poltergeist** [mesosphere/marathon#3462]
Currently if the User starts to enter the size the validation error `Container Path and Size must be set` is shown. This error message should only be shown if the user had the chance to enter the path.

![image](https://cloud.githubusercontent.com/assets/156010/13674805/3f6faa3a-e6df-11e5-9dfd-692aba893ed0.png)

**Comment by pierlo-upitup** [comment]
Duplicate of https://github.com/mesosphere/marathon/issues/3445
