### ISSUE TITLE
JSON Editor validation UX

### ISSUE THREAD

**Issue by Poltergeist** [mesosphere/marathon#3464]
The JSON editor does validate the JSON on change which makes it quite annoying to use it to type the JSON, as the error message starts to jump in every now and then. 

The JSON validation should be debounced and only validate if the user hasn't changed something after a  reasonable timeframe.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2112. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2112. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
