### ISSUE TITLE
JSON Editor error title box displaced

### ISSUE THREAD

**Issue by Poltergeist** [mesosphere/marathon#3465]
![screen shot 2016-03-10 at 16 06 58](https://cloud.githubusercontent.com/assets/156010/13675184/c6c2514e-e6e0-11e5-89fb-87109ac5626d.png)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1708. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1708. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
