### ISSUE TITLE
Create / edit modal remember section

### ISSUE THREAD

**Issue by Poltergeist** [mesosphere/marathon#3466]
If the user is switching to the JSON editor he should see the same section after switching back.

Scenario:
- Switch to container section
- Switch to JSON editor
- Switch to config editor
- user should see the container section

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2660. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2660. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
