### ISSUE TITLE
Ports: name should be optional

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#3468]
The optional `portDefinition[index].name` is an optional field, but its value must be unique. 

When creating non-dynamic portDefinitions via the new UI, we are currently sending empty values as `""`, but we should either send `null` or nothing at all, if the user does not specify a value.

This way, we prevent getting back validation errors from the server complaining about non-unique port names. 

Please note that for dynamic ports we are currently sending a `null` by default. Let's pick one consistent solution.

![screen shot 2016-03-11 at 09 16 24](https://cloud.githubusercontent.com/assets/1078545/13696914/051d0b80-e76a-11e5-8173-9bca58cb8b50.png)

**Comment by Poltergeist** [comment]
This was also solved by mesosphere/marathon-ui/pull/715 so this issue might be closed @pierlo-upitup
