### ISSUE TITLE
Resident tasks: Cleanup from MarathonTask state changes

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3472]
Cleanup from MarathonTask state changes:
- [ ] `TaskSerializer` is package private
- [ ] check remaining `MarathonTask` occurrences (persistence related only)
- [ ] Nice-to-have: `TaskFailures` (`Task.Id` instead of Mesos `TaskID`)
- [ ] Nice-to-have: Check for other usages of Mesos `TaskID`, should only be used for communication with Mesos
- [ ] Nice-to-have: `MarathonTestHelper.*taskProto` methods are gone

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2567. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2567. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
