### ISSUE TITLE
[DEFER] Resident Tasks: Optimizing volume matching

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3473]
Remove linear scan over all tasks from offer matching. E.g. in `PersistentVolumeMatcher`, `TaskOpFactoryImpl.inferForResidents`.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1992. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
