### ISSUE TITLE
Marathon destroys docker containers when suspended

### ISSUE THREAD

**Issue by srshanmugam** [mesosphere/marathon#3478]
I am using docker containers as apps to be deployed in mesos. The docker containers run apace storm components. From marathon UI, when one of the app is suspended, first issue the restart link does not work. So i tried scaling the application instead of restarting. Scaling actually creates a new container. So the data within the old container is lost. I can do a workaround using docker volumes to host, but then I would need to pin the apps to host.

Is this an expected behavior of restarting an app using marathon?

**Comment by gkleiman** [comment]
Clicking on `Suspend` is actually a shortcut for scaling an app down to 0 instances.

I agree that this might not be very intuitive.

cc/ @leemunroe

**Comment by srshanmugam** [comment]
Thanks for the response. Does scaling down to 0 means, the docker container will be destroyed? If yes, what's the best way to stop and restart an app that's based on docker?

**Comment by leemunroe** [comment]
It is confusing. We should at least update our warning. 

@srshanmugam So I understand correctly, your expectation was that the current state would be saved on suspend, and restarting would have brought it back to that state?

**Comment by srshanmugam** [comment]
Thanks again, yes, at very minimum, not destroy the containers. Destroying the container deletes the state of the container, especially when volumes are not used.

**Comment by srshanmugam** [comment]
Any updates or suggestions on handling docker container apps restart with Marathon?

**Comment by roddyofchina** [comment]
@srshanmugam @Ieemunroe  I also appeared this problem,  when one of the app is suspended, 
Restart the app does not work,If use Scale my app can  run, But  the App data is new.

**Comment by roddyofchina** [comment]
My marathon logs , Marathon's version  1.1.3

Sep 21 17:05:54 localhost marathon[11650]: [2016-09-21 17:05:54,417] INFO 192.168.4.109 - - [21/Sep/2016:09:05:54 +0000] "GET //192.168.2.147:8080/v2/queue HTTP/1.1" 200 12 "http://192.168.2.147:8080/ui/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36"  (mesosphere.chaos.http.ChaosRequestLog$$EnhancerByGuice$$dc32d379:qtp713707020-38)
Sep 21 17:05:54 localhost marathon[11650]: [2016-09-21 17:05:54,417] INFO 192.168.4.109 - - [21/Sep/2016:09:05:54 +0000] "GET //192.168.2.147:8080/v2/apps//web-01?embed=app.taskStats&embed=app.readiness HTTP/1.1" 200 1090 "http://192.168.2.147:8080/ui/" "Mozilla/5.0 (Windows NT 6.3; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/49.0.2623.108 Safari/537.36"  (mesosphere.chaos.http.ChaosRequestLog$$EnhancerByGuice$$dc32d379:qtp713707020-33)
Sep 21 17:05:55 localhost marathon[11650]: [2016-09-21 17:05:55,146] INFO Upgrade group id:/ version:2016-09-21T09:05:55.146Z with force:false (mesosphere.marathon.state.GroupManager:marathon-akka.actor.default-dispatcher-6074)
Sep 21 17:05:55 localhost marathon[11650]: [2016-09-21 17:05:55,147] INFO [/web-01]: restart detected for app (oldVersion FullVersionInfo(2016-09-21T09:04:34.315Z,2016-09-21T09:04:34.315Z,2016-09-21T07:45:13.750Z)) (mesosphere.marathon.upgrade.GroupVersioningUtil$:ForkJoinPool-2-worker-11)
Sep 21 17:05:55 localhost marathon[11650]: [2016-09-21 17:05:55,155] INFO Computed new deployment plan:
Sep 21 17:05:55 localhost marathon[11650]: DeploymentPlan 2016-09-21T09:05:55.146Z
Sep 21 17:05:55 localhost marathon[11650]: step 1:
Sep 21 17:05:55 localhost marathon[11650]:  * Restart(App(/web-01, image="docker.io/nginx")))
Sep 21 17:05:55 localhost marathon[11650]: (mesosphere.marathon.state.GroupManager:ForkJoinPool-2-worker-11)
Sep 21 17:05:55 localhost marathon[11650]: [2016-09-21 17:05:55,155] INFO Deploy plan with force=false:
Sep 21 17:05:55 localhost marathon[11650]: DeploymentPlan 2016-09-21T09:05:55.146Z
Sep 21 17:05:55 localhost marathon[11650]: step 1:
Sep 21 17:05:55 localhost marathon[11650]:  * Restart(App(/web-01, image="docker.io/nginx")))
Sep 21 17:05:55 localhost marathon[11650]:  (mesosphere.marathon.MarathonSchedulerService$$EnhancerByGuice$$cefd15e2:ForkJoinPool-2-worker-11)
Sep 21 17:05:55 localhost marathon[11650]: [2016-09-21 17:05:55,156] INFO [/web-01] storing new app version 2016-09-21T09:05:55.146Z (mesosphere.marathon.state.GroupManager:ForkJoinPool-2-worker-11)
Sep 21 17:05:55 localhost marathon[11650]: [2016-09-21 17:05:55,473] INFO Deployment of / successful (mesosphere.marathon.MarathonSchedulerActor:marathon-akka.actor.default-dispatcher-6067)
Sep 21 17:05:55 localhost marathon[11650]: [2016-09-21 17:05:55,474] INFO Removing a82f054a-9497-497e-9698-f85b46f1b25a from list of running deployments (mesosphere.marathon.upgrade.DeploymentManager:marathon-akka.actor.default-dispatcher-6067)
Sep 21 17:05:55 localhost marathon[11650]: [2016-09-21 17:05:55,729] INFO Updated groups/apps according to deployment plan a82f054a-9497-497e-9698-f85b46f1b25a (mesosphere.marathon.state.GroupManager:ForkJoinPool-2-worker-5)
Sep 21 17:05:55 localhost marathon[11650]: [2016-09-21 17:05:55,729] INFO Deployment acknowledged. Waiting to get processed:
Sep 21 17:05:55 localhost marathon[11650]: DeploymentPlan 2016-09-21T09:05:55.146Z
Sep 21 17:05:55 localhost marathon[11650]: step 1:
Sep 21 17:05:55 localhost marathon[11650]:  * Restart(App(/web-01, image="docker.io/nginx")))
Sep 21 17:05:55 localhost marathon[11650]: (mesosphere.marathon.state.GroupManager:ForkJoinPool-2-worker-11)

**Comment by jdef** [comment]
There is no way to stop and resume the same docker container instance using Marathon. Suspending an app destroys the related containers.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2212. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
