### ISSUE TITLE
Bug: Only leader should report metrics

### ISSUE THREAD

**Issue by fengyehong** [mesosphere/marathon#3480]
I noticed that by now every marathon node will report metrics if reporter is configured. Take graphite as example, we usually configure a prefix with framework name, just like in [metrics docs](https://mesosphere.github.io/marathon/docs/command-line-flags.html#metrics-flags).

So if my graphite has retention set to 60s:7d(each datapoint represents 60s), and marathon graphite reporter interval set to 60s,

On time 1s, leader node report metrics
On time 3s, a non-leader node report metrics to the same path (data reported by leader is over written!)
On time 61s, leader node report metrics
On time 63s, a non-leader node report metrics to the same path (over written again!)

This will result all the metrics stored in graphite has value zero. Whether this happens depends on the start time of each node.

So I think only leader should report metrics.

**Comment by fengyehong** [comment]
any one agree on this? i guess not many people use metrics reporter by now...

**Comment by zzl0** [comment]
+1

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2668. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
