### ISSUE TITLE
Does marathon support docker command cpu-quota and cpu-period

### ISSUE THREAD

**Issue by nashasha1** [mesosphere/marathon#3481]
I use marathon and mesos to run docker container. I know marathon have arguments `cpus` to limit cpu usage, it will turn to be docker's `-c` argument. But I don't know how to set `cpu-quota` and `cpu-period`.

Does marathon support this? If does, what's the version and argument should I use.

**Comment by nashasha1** [comment]
Any ideas?

**Comment by gkleiman** [comment]
You can pass arbitrary docker parameters through the `parameter` field. Would that be enough?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2493. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
