### ISSUE TITLE
Move documentation from redcarpet to kramdown.

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#3489]
GitHub will not support redcarpet after May 1st - we need to make sure, that cramdown gives us the same result as redcarpet. This is the mail I received from GitHub:

> You are currently using the 'redcarpet' Markdown engine, which will not be supported on GitHub Pages after May 1st. At that time, your site will use 'kramdown' for markdown rendering instead. To suppress this warning, remove the 'markdown' setting in your site's '_config.yml' file and confirm your site renders as expected. For more information, see https://help.github.com/articles/updating-your-markdown-processor-to-kramdown.
> 
> GitHub Pages was recently upgraded to Jekyll 3.0. It may help to confirm you're using the correct dependencies:
> 
>  https://github.com/blog/2100-github-pages-now-faster-and-simpler-with-jekyll-3-0
> 
> For information on troubleshooting Jekyll see:
> 
>  https://help.github.com/articles/troubleshooting-jekyll-builds
> 
> If you have any questions you can contact us by replying to this email.

**Comment by aquamatthias** [comment]
@sascala can you apply the changes needed for this change? (see the links for instructions).
Obviously we have to switch before May 1st.

**Comment by sascala** [comment]
Our site renders, so I'm going to mark this closed. http://mesosphere.github.io/marathon/docs/
