### ISSUE TITLE
Missing validation for multiple slashes when creating Groups

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#3496]
Marathon does strip out multiple `/` when receiving them,  but we should disallow that in the UI.

<img width="636" alt="screen shot 2016-03-15 at 16 34 53" src="https://cloud.githubusercontent.com/assets/1078545/13783516/1242141c-eacc-11e5-9491-2f0b1e1972a1.png">

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2401. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
