### ISSUE TITLE
Scheduler Migrations: AppDefinition validation

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3501]
For now, we want to restrict the configuration possibilities to simplify the implementation:

* We only allow one readinessCheck.
* A scheduler application has always an instance count of 1 _or 0_ (dependent on some label)
* A resident application has always the upgrade strategy with a maximumOverCapacity of 0

[we can also think of more restrictions if it makes implementing an MVP easier and supports the Scheduler Migrations use case of one instance]

Depends on #3500.

Context: We want to be able to drive scheduler upgrades manually. See [MARATHON-856](https://mesosphere.atlassian.net/browse/MARATHON-856) (private, sorry).

**Comment by aquamatthias** [comment]
A scheduler application can not be scaled
A scheduler application has always an instance count of 1
A scheduler application has always the upgrade strategy (0, 0)

**Comment by kolloch** [comment]
@aquamatthias I changed your comment and integrated it into the description of the issue
