### ISSUE TITLE
Questions about port names

### ISSUE THREAD

**Issue by googoid** [mesosphere/marathon#3506]
Hey everybody,

Recently I decided to setup MariaDB Galera cluster on marathon.
Long story short, every node advertises it's own address and some ports (3306, 4567, 4568, 4444).
I want to run every node in a docker container with bridge networking.
Service discovery (Galera node discovery) is done via consul which uses CiscoCloud's `mesos-consul` thingy.

The first problem I met was random port assignment. It's not possible to configure Galera node to listen for a port, but advertise other port. This is crucial.
But it is solved by just passing `containerPort: 0`, `hostPort: 0`, `servicePort: 0`. Marathon (mesos?) generates 4 random ports and properly passes to the container via `$PORTS`, then i parse them in the container entrypoint, prepare Galera configs, it works like a charm.
Then the entrypoint tries to discover other ports to join the cluster via querying consul. Unfortunately I can't get specific port because there are no port names.

Recently I saw the `0.16.0-RC1` branch, built it, replaced my staging server's binaries, restarted marathon and whoa la I have new UI with port names. I was very happy until I really started to use them. I know it's pre-release but anyway I need that feature really badly!

So, I put port names there, left all ports `0` and looked into mesos state. And what i saw was very disappointing:
1. There were advertised wrong port numbers (random `servicePort`)
2. There were no port names.
But I got correct random ports inside the container (actual ports that were bridged by docker).

After looking at the source code I discovered that for port names `portDefinition` are used (why?). I put port names in port definitions and it advertised port names to mesos. But again with wrong port numbers.

My next thought was to put `0` for port number in `portDefinition`. Surprisingly it mapped `portDefinition` to the correct container `portMapping` element. But again advertised the `servicePort` (which I still don't understand why is needed).

So my question: Is advertising `servicePort` intentional, or is that a bug?

And when will be 0.16.0 released (approx.)?

Thanks in advance, you're great!

P. S. Currently I'm trying to achieve my goal using HOST networking with fixed ports, but this is not preferable because I will need unique hosts for every node.

**Comment by googoid** [comment]
One more thing I found:

`{"message":"Object is not valid","details":[{"path":"/portDefinitions","errors":["Ports must be unique."]}]}`

`{
    "port": 3306,
    "protocol": "tcp",
    "name": "MYSQL",
    "labels": {}
  }, {
    "port": 4567,
    "protocol": "tcp",
    "name": "TRAFFIC",
    "labels": {}
  }, {
    "port": 4567,
    "protocol": "udp",
    "name": "TRAFFIC_UDP",
    "labels": {}
  }, {
    "port": 4568,
    "protocol": "tcp",
    "name": "IST",
    "labels": {}
  }, {
    "port": 4444,
    "protocol": "tcp",
    "name": "SST",
    "labels": {}
  }`

It doesn't consider `protocol` for uniqueness.

**Comment by gkleiman** [comment]
Thanks for reporting this!

Advertising the `servicePort` was a bug, we fixed that today and included the fix in v0.16.0-RC3.

The second issue is related to #751. By default Mesos only offers one range of ports and Marathon doesn't support custom resource ranges. So it uses the same range for both tcp and udp ports.

**Comment by googoid** [comment]
Thanks a lot for the reply. I'm glad that the issue is fixed now :+1:
