### ISSUE TITLE
app group deploy error

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#3508]
1. group defination:
{
    "id": "develop/envname",
    "apps": [
        {
            "id": "mun",
            "cpus": 0.1,
            "mem": 512,
            "ports": [
                0
            ],
            "requirePorts": false,
            "instances": 1,
            "executor": "",
            "container": {
                "type": "DOCKER",
                "docker": {
                    "image": "10.5.24.46:80/nscloud/mun:1.0.0.1",
                    "forcePullImage": true,
                    "network": "BRIDGE",
                    "portMappings": [
                        {
                            "containerPort": 80,
                            "hostPort": 0,
                            "servicePort": 0,
                            "protocol": "tcp"
                        },
                        {
                            "containerPort": 443,
                            "hostPort": 0,
                            "servicePort": 0,
                            "protocol": "tcp"
                        }
                    ],
                    "privileged": true,
                    "parameters": [
                    ]
                },
                "volumes": [
                    {
                        "containerPath": "/usr/local/nginx/logs/",
                        "hostPath": "/tmp/logs",
                        "mode": "RW"
                    }
                ]
            },
            "env": {
                "API_domain": "nscloud.api.nsfocus.com",
                "Portal_domain": "www.nscloud.com",
                "API_Proxy_IP": "10.5.24.33",
                "pub_Redis": "10.5.24.60",
                "pub_Redis_PWD": "123456",
                "Atsani_Redis": "10.5.24.60",
                "Atsani_Redis_PWD": "123456"
            },
            "constraints": [
            ],
            "labels": {
                "version": "1.0.0.1"
            },
            "uris": [
            ],
            "dependencies": [],
            "healthChecks": [
                {
                    "protocol": "HTTP",
                    "path": "/",
                    "gracePeriodSeconds": 3,
                    "intervalSeconds": 10,
                    "portIndex": 0,
                    "timeoutSeconds": 10,
                    "maxConsecutiveFailures": 3
                }
            ],
            "backoffSeconds": 1,
            "backoffFactor": 1.15,
            "maxLaunchDelaySeconds": 3600,
            "upgradeStrategy": {
                "minimumHealthCapacity": 0.5,
                "maximumOverCapacity": 0.2
            }
        }
    ]
}

2. if i use the api /v2/groups to POST,
error msg:
Exception: {u'message': u'Invalid JSON', u'details': u"Unrecognized token 'apps': was expecting ('true', 'false' or 'null')"}

3. but if i use curl to POST
curl -X POST http://10.5.24.21:8080/v2/groups -d @build.json -H "Content-Type: application/json"
it is right!

marathon: Version 0.15.3
mesos: 0.27.1
thanks for your help!

**Comment by junneyang** [comment]
sorry, a low mistake...

**Comment by osmansarood** [comment]
How did you fix the above issue?

**Comment by junneyang** [comment]
@osmansarood 

when i change the id from 

{
**"id": "develop/envname",**
"apps": [
{

to 

{
"id": "/develop/envname",
"apps": [
{

it works!
