### ISSUE TITLE
why does the app or group label not support i18n, such as chinese?

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#3510]
eg:
"labels": {
  "desc": "**mun测试**",
 "version": "1.0.0.1"
},

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4424. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
