### ISSUE TITLE
is there any framework which supports jenkins running on marathon?

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#3516]
like the Kubernetes Plugin:
https://wiki.jenkins-ci.org/display/JENKINS/Kubernetes+Plugin

**Comment by gkleiman** [comment]
cc/ @ssk2

**Comment by ssk2** [comment]
Hi @junneyang, there is a Mesos plugin which allows the Jenkins scheduler to run builds on Mesos itself. You can run the Jenkins master on Marathon. (This is how the DC/OS package for Jenkins does it.)

These links may help:
+ http://www.ebaytechblog.com/2014/04/04/delivering-ebays-ci-solution-with-apache-mesos-part-i/
+ http://www.ebaytechblog.com/2014/05/12/delivering-ebays-ci-solution-with-apache-mesos-part-ii/
+ https://github.com/jenkinsci/mesos-plugin
+ https://github.com/mesosphere/jenkins-mesos

There is also a Marathon plugin for Jenkins now, which allows you to deploy Marathon applications as a post build step:
+ https://github.com/jenkinsci/marathon-plugin

Both plugins are available on the Jenkins Update Centre.

Hope this helps!
