### ISSUE TITLE
residency added even if no volumes are requested

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#3518]
Two bugs here:

- `residency` is added even if no volumes are requested, leading to a validation error.
- The validation error is `general: AppDefinition must contain persistent volumes and define residency`. I think that the `general: ` prefix should be removed.

![Reproduction steps](https://s3.amazonaws.com/f.cl.ly/items/3M2w0G0m1H1p0o2m0e47/Screen%20Recording%202016-03-17%20at%2010.47%20am.gif)

**Comment by Poltergeist** [comment]
There is a work around present currently after creating a app but before sendig it to the server. The application is tested if it does contain a container and a volume in the object if it does the residenccy setting is added. We shoudl test the volumes and only add the residency setting only if there is a persistent local volume present. unique to the persistent local volumes is the `persistent` attribute. https://github.com/mesosphere/marathon-ui/blob/master/src/js/actions/AppsActions.js#L53-L59

**Comment by gabrielhartmann** [comment]
ETA for fix?

**Comment by timcharper** [comment]
It appears that with marathon v1.0.0-RC1 (and ui v1.0.0) residency is not being automatically added when editing an instance and adding a persistent volume, resulting in this same error message.

**Comment by meichstedt** [comment]
@Poltergeist Can you have a look please?

**Comment by Poltergeist** [comment]
Currently the residency setting is added in the frontend right before the request is send to create an app. We decided to copy that behaviour to the PUT request based on one more factor.

Add the residency setting on put if a local persistent volume is associated to the application and the residency setting is not set.

**Comment by Poltergeist** [comment]
@timcharper So right now it is not possible to add a persistent local volume to an existing application. I added the work around mentioned in my last comment. This will get you further but then finally throw 
```json
{
  "message": "Object is not valid",
  "details": [
    {
      "path": "/app(0)",
      "errors": [
        "Persistent volumes can not be changed!"
      ]
    }
  ]
}
```
So I fear if you want to use persistent local volumes you have to create a new application. So adding the work around to marathon-ui does not make sense currently, and the original issue can still considered to be closed. If there are any questions on persistent local volumes feel free to mention me in a question in this issue, I cant try to do my best with answering those.

**Comment by timcharper** [comment]
Great; thank you, @Poltergeist . This error message will be much more helpful.

**Comment by spencersmith** [comment]
Is there an update/workaround to this bug?
