### ISSUE TITLE
The default Docker network should be `host`.

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#3519]
Marathon will use `host` networking by default, it doesn't make any sense to show the `select` option in the dropdown.

**Comment by pierlo-upitup** [comment]
Not sure it's a bug, as I believe we use the 'undetermined' state to detect if the user actually made a selection. I'd say the network mode should be disabled if no image name is supplied. cc @leemunroe

**Comment by gkleiman** [comment]
I believe this is a bug. If you provide an image and don’t select a network mode, you won’t know which one you get unless you know the backend defaults by heart.

**Comment by leemunroe** [comment]
@pierlo-upitup are we using this to decide whether to update the JSON or not?

What's the downside of making this "Host" by default in the UI?

**Comment by pierlo-upitup** [comment]
I think we should probably fix this bug by simply making the Network Mode field required as soon as an image name is entered. As @leemunroe suggests, I believe the no-field selected by default is helpful to the JSON editor to determine what to show.

**Comment by pierlo-upitup** [comment]
This was fixed by https://github.com/mesosphere/marathon-ui/pull/723
