### ISSUE TITLE
Odd Mesos UI behavior

### ISSUE THREAD

**Issue by dlyub** [mesosphere/marathon#3524]
I have deployed a system in my AWS account and noticed a behavior I don't quite understand. My other systems are fine, but there's something about this environment that forces incorrect machine listed as a slave. 

In the first image I have a screenshot of the slaves tab. You'll see that Slave host name is "ip-10-184-241-84.ec2.internal". 

![slave](https://cloud.githubusercontent.com/assets/13035968/13862657/fe4a80f2-ec6a-11e5-8237-509df9da8b7e.PNG)

When I click on the ID I see "Slave:ip-10-184-241-166.ec2.internal" which in fact is the address of the master. No resources are showing either. 

![slave2](https://cloud.githubusercontent.com/assets/13035968/13862656/fe4900b0-ec6a-11e5-809c-433effb5970e.PNG)

Any ideas on what might be causing this behavior?

Thank you!

See this problem in this environment with both Mesos 0.25 and 0.28.

**Comment by janisz** [comment]
It's Mesos issue not Marathon. Please report it on user@mesos.apache.org mailing list
