### ISSUE TITLE
Marathon callback lost message

### ISSUE THREAD

**Issue by xianlubird** [mesosphere/marathon#3532]
I used marathon version 0.9.2 and mesos 0.24.0, registry a url to get the callback event. But I found that marathon will lost some APP KILLED callback message , That means I can not get the message that one app was killed.  When I test version 0.15.2  , I did not found this problem,  Is someone else also found this problem?

**Comment by gkleiman** [comment]
Please re-open if you can reproduce this with a recent version of Marathon.
