### ISSUE TITLE
Add a more capable storage layer for Marathon (replace ZK)

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#3535]
With the current usage of ZK we have limitations in the number of apps and tasks that can be launched.
Marathon should support a more capable data store to maintain state.

**Comment by cmluciano** [comment]
Hi! I have mentioned this around the Slack channel in mailing list. Moving this configuration would be huge for running large amounts of application with a decent set of environment variables. We have already exceeded 1k marathon applications in our stack and in our tests a Marathon failover can choke the mesas-master from also reconciling tasks. This sometimes causes the mesas-master process to fail and become stopped. For now I assume we may need a separate ZK cluster for Marathon data.

**Comment by jasongilanfarr** [comment]
Fixed in #4178
