### ISSUE TITLE
The application is locked by deployment error is missing in the app edit modal

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#3537]
![app-is-locked-issue](https://cloud.githubusercontent.com/assets/647035/13924749/c1cb889c-ef85-11e5-8175-93c71a5d858c.gif)
There is no application is locked by deployment error in the app edit modal.

**Comment by pierlo-upitup** [comment]
And if using the JSON editor, the error is completely messed up:

![image](https://cloud.githubusercontent.com/assets/1078545/13952077/adcc02fe-f034-11e5-8101-b053b66cadee.png)

**Comment by pierlo-upitup** [comment]
Wrong button.
