### ISSUE TITLE
Cleanup JSON editor portDefinitions

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#3539]
![clean-up-json-editor-port-definitions mov](https://cloud.githubusercontent.com/assets/647035/13928195/0968b602-ef95-11e5-8052-20f4ca646cb9.gif)
Please cleanup JSON editor `portDefinitions` as the empty null values are kinda confusing.

**Comment by pierlo-upitup** [comment]
Also, this is related https://github.com/mesosphere/marathon/issues/3595

**Comment by pierlo-upitup** [comment]
Please clarify: is this about removing the extra `vip` field?

**Comment by orlandohohmeier** [comment]
@pierlo-upitup: Yeah, I would remove all the empty `null` values, especially the `vip` field as it is just a placeholder.

**Comment by pierlo-upitup** [comment]
The `vip` was removed in https://github.com/mesosphere/marathon-ui/pull/721 – regarding `name` and `labels` it's OK, we need to do that so that the user can "remove" the name in case of editing. Closing the issue, if I missed something feel free to re-open.
