### ISSUE TITLE
Browsing the app create/edit options should not add any data

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#3540]
![app-edit-config-data-handling](https://cloud.githubusercontent.com/assets/647035/13929120/df938c7c-ef98-11e5-872c-fbb76f587981.gif)

Browsing the app create/edit options should not add any data to the app definition nor trigger `handleAppConfigChange`.

**Comment by pierlo-upitup** [comment]
This goes hand in hand with https://github.com/mesosphere/marathon/issues/3156

**Comment by pierlo-upitup** [comment]
Also this is related https://github.com/mesosphere/marathon/issues/3595

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2643. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
