### ISSUE TITLE
Extra slash appears in ID field when creating new app

### ISSUE THREAD

**Issue by leemunroe** [mesosphere/marathon#3551]
To reproduce, open edit modal, cancel, go back to collection view, create app.

![slash](https://cloud.githubusercontent.com/assets/15963/13963048/07df87ca-f021-11e5-98c4-4281bff9dd2e.gif)

**Comment by leemunroe** [comment]
Getting the same for new group. Possibly URL related.

![image](https://cloud.githubusercontent.com/assets/15963/13963114/586107be-f021-11e5-8c7f-294b2ec7de86.png)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2613. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
