### ISSUE TITLE
Editing an App: Switching between JSON and normal Editor produces a broken UX

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#3552]
When editing an application:

1. It should be possible to submit again when switching back from JSON to Editor (the submit button stays disabled)
2. field-validation should be re-run at least on the "general" section to ensure we surface per-field validation messages
3. this issue https://github.com/mesosphere/marathon/issues/3470 probably goes hand in hand (in the gif we finally show a General Error because we receive a `{path: "", errors: ["You cannot specify both ports and port definitions"]}` from the server, apparently.

![switch](https://cloud.githubusercontent.com/assets/1078545/13963779/038378c6-f067-11e5-8fa7-edacea93ba3f.gif)

**Comment by orlandohohmeier** [comment]
I agree with all of them but don't see why one should be able to submit again after switching mode, if there is still an error.

**Comment by pierlo-upitup** [comment]
In the example above, because the validation is not shown and the CPU / Mem numbers appear valid from the user's point of view.

**Comment by orlandohohmeier** [comment]
But that is issue 2, isn't it?
