### ISSUE TITLE
allow to configure requirePort in marathon webUI

### ISSUE THREAD

**Issue by garyelephant** [mesosphere/marathon#3555]
Allow to configure requirePort in marathon webUI.

In my case I use marathon + mesos-dns, I need to assign specific port for specific application to avoid using SRV request to get application port.I think others may also need this feature.

**Comment by pierlo-upitup** [comment]
cc @air @leemunroe

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2104. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
