### ISSUE TITLE
Create Modal: always show Port Index for host ports

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#3559]
@gkleiman reports that the Ports section should not let the user specify a Port value unless we are in Docker/BRIDGE mode. 

In a nutshell, this is because – unless the user explicitly sets `requirePorts: true` , what we are in fact specifying here is a `servicePort` – which does not meet the current expectations.

In fact, from [the docs](https://mesosphere.github.io/marathon/docs/ports.html#specifying-ports):

> In this example, we specify three randomly assigned host ports which would then be available to our command via the environment variables $PORT0, $PORT1 and $PORT2. Marathon will also randomly assign three service posts in addition to these three host ports.

So in the Host Networking case it would be a lot less confusing to the users if we simply disabled editing the port value altogether, and simply asked the user "how many ports do you need". 

The proposed solution then should look like this for anything but Docker/BRIDGE mode:

![screen shot 2016-03-23 at 14 22 04](https://cloud.githubusercontent.com/assets/1078545/13986423/aa050412-f102-11e5-8053-272bc456f717.png)

cc @leemunroe @aquamatthias

**Comment by gkleiman** [comment]
:+1:

**Comment by gkleiman** [comment]
@pierlo-upitup nit: I think the text should be "Configure your application to listen **on** $PORT0..."

**Comment by pierlo-upitup** [comment]
cc @air

**Comment by gkleiman** [comment]
The current modal (which shows the port number, not the env variable index) is still very useful if `requirePorts` is set to `true`.

**Comment by leemunroe** [comment]
From a UX pov I think it would be worth adding a paragraph below `For more advanced port configuration options, including service ports, use JSON Mode.` with "use JSON Mode" toggling to JSON.

![image](https://cloud.githubusercontent.com/assets/15963/14001077/81eecd24-f101-11e5-8bbb-0ef6754cae9a.png)


cc'ing @sargun as he had some good feedback on this UI
