### ISSUE TITLE
Stop health checks when no longer leader

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#356]
When a Marathon instance abdicates leadership, it should stop any currently running task health checks.

**Comment by sttts** [comment]
I completely miss "Defeat leadership" messages in my logs although leader changes take place. Somehow onDefeated is not called anymore. This would also explain why health checks are not stopped anymore and tasks are killed by non-leaders (#896).

**Comment by ConnorDoyle** [comment]
@sttts, would you mind making a new issue to track the missing call to `onDefeated` (link to this one and #896)?
