### ISSUE TITLE
AppsStore: Refactor generateList to behave more consistently

### ISSUE THREAD

**Issue by Poltergeist** [mesosphere/marathon#3565]
Currently the `generateFlatList` function introduced in https://github.com/mesosphere/marathon-ui/pull/710/files#diff-183e0e82aee2602b551871df771bd11aR167 returns an object, or an array depending on how it's called. 

Let's have a cleaner API, that returns consistently the same type.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1822. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
