### ISSUE TITLE
Fix "commit suicide if the zk connection is dropped" test

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#3566]
#3528 introduces a new test in `LeaderIntegrationTest` called "commit suicide if the zk connection is dropped".

It succeeds only when running in isolation. We have to investigate why it's failing and fix the test or Marathon.

**Comment by jeschkies** [comment]
Note: Marathon does not suicide anymore on connection loss.

**Comment by aquamatthias** [comment]
@jeschkies: Marathon suicides on abdication loss. Retested on master.

**Comment by aquamatthias** [comment]
I don't see the test marked as Unstable - close this ticket.

**Comment by jeschkies** [comment]
Okay, Marathon does not suicide in `NetworkPartitionIntegrationTest` I will investigate that.
