### ISSUE TITLE
Container IP not correctly display in 0.15.0 and above

### ISSUE THREAD

**Issue by robbrockbank** [mesosphere/marathon#3575]
I'm using a Docker network plugin that assigns a routable IP address per container on a Docker container.

In Marathon 0.14.2 release the IP address of the container was correctly displayed

```
Host 172.24.197.102
IP Addresses 192.168.0.0
Ports [31830]
Endpoints 172.24.197.102:31830
Service Discovery n/a
Status Started
```

From Marathon 0.15.0 and above, the IP address of the container is no longer displayed:

```
Host 172.24.197.103
Ports [31781]
Endpoints 172.24.197.103:31781
Service Discovery n/a
Status Started
```

Why is the actual container IP no longer available in Marathon?

I'm running Mesos 0.28 on CentOS 7.

**Comment by robbrockbank** [comment]
@gkleiman Could this be from this check-in to MarathonTasks.scala?:

https://github.com/mesosphere/marathon/commit/e44c923fb29dd299653f146339f49f29a86deb2b

If so then I assume the problem is that the App definition has an IP address assigned in it ... but to be honest I'm not entirely sure what that means.

Any light on this issue would be hugely appreciated.

Rob

**Comment by djosborne** [comment]
This seems to go beyond just the UI neglecting to show it, and seems to be the marathon engine/http server failing to calculate it.

I used an app definition which requested an IP in v0.14.0. When I then GET that app's information from marathon, I see the task's IP:
```
"tasks":[  
         {  
            "id":"star_probe-b.67428c31-f2a8-11e5-b537-0242ac110005",
            "host":"172.17.0.6",
            "ipAddresses":[  
               {  
                  "ipAddress":"192.168.0.2",
                  "protocol":"IPv4"
               }
            ],
            "ports":[],
```

Same app definition launched with Marathon v0.15.3:
```
      "tasks":[  
         {  
            "id":"star_probe-b.0cf0a396-f2a9-11e5-aec7-0242ac110005",
            "host":"172.17.0.6",
            "ipAddresses":[],
            "ports":[],
```

This is using net-modules. For a quick repro, you can clone the net-modules project, and run `make cluster`. Then `bin/launch-probes.sh`. Then tear down the demo, change marathon's version in docker-compose.yml, and repeat.

**Comment by air** [comment]
hi @aquamatthias can we triage this as a possible regression and shoot to include in next RC?

**Comment by michaelmonroe** [comment]
I'm also seeing this same behavior in all versions of 15.0,15.1.15.2, 15.3 as well as 16.0-SNAPSHOT. This effectively stops the API from reporting the IP address of container based tasks. This has now broken load balancing and container IP based architecture approaches for HA.

**Comment by gkleiman** [comment]
IP-per-Task support was introduced with the commit 8f770ce7b95f73902bb4d1e80cd200abd805ec9b and broken by commit 32b2407a8a7d5266b309e0e9aed7699e9684349e:

```
$ git log -S 'if (status.hasContainerStatus) builder.addAllNetworks(status.getContainerStatus.getNetworkInfosList)'
commit 32b2407a8a7d5266b309e0e9aed7699e9684349e
Author: Peter Kolloch <peter@mesosphere.io>
Date:   Mon Dec 14 18:43:20 2015 +0100

    Toward #462 - create interface traits for TaskTracker

    ..to ease later replacement of the implementation.

    Also move `determineOverdueTasks` to `KillOverdueTasksActor` to
    shrink the TaskTracker interface since this method is only called
    there.

commit 8f770ce7b95f73902bb4d1e80cd200abd805ec9b
Author: Gastón Kleiman <gaston@mesosphere.io>
Date:   Fri Nov 20 10:11:31 2015 +0100

    Towards #2709 - Add IP-per-task support
```
