### ISSUE TITLE
Duplicable row client-side validation hangs the UI (Safari Browser)

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#3577]
I can reproduce this problem only in Safari - Chrome works fine.
Steps to reproduce: 
- Create Application Form 
- Switch to persistent volume tab
- Enter a number in the Size field

This spinning ball is shown - the UI is dead.

**Comment by Poltergeist** [comment]
This is connected to the duplicable rows mixin every time a invalid value is added the ui will get stuck. So this is also breaking the env vars and the labels.
