### ISSUE TITLE
Marathon UI doesn't let to edit application with double hypthen in the group name

### ISSUE THREAD

**Issue by oleksiys** [mesosphere/marathon#3583]
I have an application, that is deployed within a group, that has double hyphen "--" in its name.
To be specific, let's assume the application path looks like:
/group1/group2/helloworld--suffix/helloworld

When I try to edit this application descriptor (click edit) it immediately shows the error panel that states:
"Error Loading Configuration", "Error fetching version suffix/mu-hello-world for /group1/group2/helloworld."
Which implies that double hyphen has some special meaning for Marathon UI, because I'm still able to edit the application using REST API.

**Comment by oleksiys** [comment]
Forgot to mention, it's Marathon version 0.15.3

**Comment by rlubke** [comment]
+1 on getting a resolution on this.

**Comment by cookandy** [comment]
also +1 please

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1689. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
