### ISSUE TITLE
Object is not valid on app scaling

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#3585]
Marathon 1.0.0-RC1. `PUT /v2/apps//group/subgroup/app?force=true {"instances": 0}`:

```json
{
  "message": "Object is not valid",
  "details": [
    {
      "path": "/groups(0)/apps(0)/id",
      "errors": [
        "Identifier is not child of /jsanford. Hint: use relative paths."
      ]
    }
  ]
}
```

**Comment by bobrik** [comment]
Same on app deployment:

```yaml
id: /group/subgroup
apps:
  - id: svc
    cpus: 0.1
    mem: 128
    # ...
```

```
# cat marathon.json | curl -s -X PUT -H "Content-type: application/json" -d @- https://marathon/v2/groups | jq .
```

```json
{
  "message": "Object is not valid",
  "details": [
    {
      "path": "/groups(0)/apps(0)/id",
      "errors": [
        "Identifier is not child of /jsanford. Hint: use relative paths."
      ]
    }
  ]
}
```

**Comment by bobrik** [comment]
You might notice that it's even complaining about different group and app.

**Comment by bobrik** [comment]
It gets better, group jsanford:

![image](https://cloud.githubusercontent.com/assets/89186/14028921/235e71d2-f1f7-11e5-8655-02be203dfb82.png)

Now I enter it:

![image](https://cloud.githubusercontent.com/assets/89186/14028931/2ce67ca4-f1f7-11e5-97cb-6710b5757089.png)

I think the following happened:

1. James deployed his app `/jsanford/jsanfordsigh` on the previous version of marathon where relative app paths were broken. He somehow managed to deploy his thing, though.
2. I upgraded marathon to 1.0.0-RC1.
3. Now I have group `/jsanford` with 1 task but 0 apps and app `/jsanfordsigh`.

Killing both resolved the issue, but I thing you might want to have an upgrade path for it. Feel free to close it, though, since bug appeared and disappeared in RC releases.

**Comment by gkleiman** [comment]
Closing this as it was fixed in previous RCs.
