### ISSUE TITLE
Question:  Is it possible to get container IP as $-parameter in the health checks?

### ISSUE THREAD

**Issue by robbrockbank** [mesosphere/marathon#3586]
I'm running Docker-containerizer tasks with a Docker network that assigns a routable IP per container.

I'd like to run health checks for the tasks, but really need to be able to access the container IP address.  Is this possible?  There are `$HOST` and `$PORT0` parameters, but is there something like `$IP` to access the container IP?

I have used the DNS entry for accessing the container IP, but this doesn't work if you scale a task so there are multiple identically names tasks.  I think being able to access the IP would be better (and wouldn't rely on DNS).

**Comment by ricardoareis** [comment]
it would be awesome, currently, I use Calico IPAM and health check with a script inside a container.

**Comment by gkleiman** [comment]
It is not possible right now, adding this as a feature request.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2122. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
