### ISSUE TITLE
Not specifying "network" config causes mesos to thrash

### ISSUE THREAD

**Issue by peterklipfel** [mesosphere/marathon#3587]
In the UI, if I leave the `network` option as `Select`, the container spins up, but I end up with a thrashing container and the following error messages

    Failed to shutdown socket with fd 16: Transport endpoint is not connected

and

    Error: No such image or container: mesos-ff039e4b-f47a-4192-9724-0386d4145445-S0.8a7edf98-f202-44e7-abbf-627734534ef4

If I unselect and reselect the `Select` option, the UI will not let me submit the container until I specify either `bridged` or `host`

**Comment by gkleiman** [comment]
Mesos' default network mode is `HOST` ( see https://github.com/apache/mesos/blob/master/include/mesos/mesos.proto#L1693). So it is using the host mode.

The socket error means that the Mesos Agent tried to connect to something and failed. So it might have problems fetching the container image.

The GUI issue you mention at the end is related to #3519. (cc/ @pierlo-upitup)
