### ISSUE TITLE
memory size can not set less than 32m

### ISSUE THREAD

**Issue by berockguo** [mesosphere/marathon#3588]
we have some apps use only 1m memory. please remove this limit by js.

**Comment by janisz** [comment]
It's not Marathon limit. It's required by Mesos.
https://github.com/apache/mesos/blob/65c1450f2e948234d4dd2670244bc0e792b86f03/src/master/constants.hpp#L45
https://github.com/apache/mesos/blob/65c1450f2e948234d4dd2670244bc0e792b86f03/src/master/constants.hpp#L45
