### ISSUE TITLE
Task json generated with the GUI fails with error message when using API [Version 1.0.0-RC1]

### ISSUE THREAD

**Issue by jaimelive** [mesosphere/marathon#3590]
Task json generated (using json slider on top right corner) with the Version 1.0.0-RC1 GUI will generate an error when submitted through the API even though when submitted thorough the GUI it runs without a problem.

Error:

``` json
{"message":"Object is not valid","details":[{"path":"/upgradeStrategy","errors":["got 1.0, expected 0.5 or less","got 1.0, expected 0.0"]},{"path":"/isResident","errors":["must be false"]}]}

```

Task:

``` json
{
  "id": "tree",
  "cmd": "touch stuff; touch kite; touch /mesosData/YHEAAAA; tree /",
  "cpus": 1,
  "mem": 128,
  "disk": 0,
  "instances": 1,
  "ports": [
    0
  ],
  "container": {
    "docker": {
      "image": "jaimelive/tree",
      "network": "BRIDGE",
      "portMappings": [
        {
          "protocol": "tcp",
          "name": null,
          "labels": null,
          "containerPort": 0,
          "hostPort": 0
        }
      ],
      "parameters": []
    },
    "type": "DOCKER",
    "volumes": [
      {
        "hostPath": "mesosVol",
        "containerPath": "/mesosData",
        "mode": "RW"
      },
      {
        "containerPath": "mesosVol",
        "persistent": {
          "size": 10
        },
        "mode": "RW"
      }
    ]
  },
  "env": {},
  "healthChecks": []
}
```

Submited with: 
`
curl  -X POST http://master.mesos:8080/v2/apps -d @sample.json -H "Content-type: application/json"
`

**Comment by gkleiman** [comment]
AFAIK Marathon 1.0.0-RC1 uses a different `upgradeStrategy` for apps with persistent volumes and it shouldn't trigger that validation error.

cc/ @aquamatthias

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1955. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
