### ISSUE TITLE
HTTP health check uses host IP/port rather than container IP for performing checks

### ISSUE THREAD

**Issue by robbrockbank** [mesosphere/marathon#3591]
Mess 0.28 w/ Marathon 0.14.2

I'm using the Docker Containerizer to spin up Docker tasks.  I'm also using Calico Docker networking to create containers with routable IP addresses.

I can see the IP address of the container correctly displayed in Marathon [although see issue #3575 -- this does not work in later versions of Marathon], and the DNS entry resolves to this IP address. 

When I use HTTP health checks, the request is fired at the host IP and marathon assigned port so it isn't hitting the container.  It should be fired at the container IP (which is routable).  End result:  health check fails.
.

**Comment by timcharper** [comment]
@robbrockbank I also have this issue. I've read elsewhere that this is a current limitation of Marathon. A workaround is to just go ahead and do a forward.

**Comment by gkleiman** [comment]
Marathon v0.14.2 should use the ip address of the first NetworkInfo message if an ip address was requested in the app definition.

If no ip was requested in the app definition, then the NetworkInfo messages are ignored and the agent's IP address is used to perform the health check.

Is that the behaviour your experiencing?

**Comment by timcharper** [comment]
@gkleiman I'm using weave networking (parameter `net` `weave` specified in the docker parameter list), and it is using the host IP instead of the provisioned weave IP for health check.

**Comment by robbrockbank** [comment]
Aha!  Apologies, but I believe I have this working now.

I was launching the tasks through the UI - which doesn't set the ipAddress field - there is currently no way to include this in the UI ( #3690 ).

If I launch using the API, and include the ipAddress section, the health checks do use the task IP [at least for 0.14.2]

I'm fine with this issue being closed, but it looks as though @timcharper is hitting something similar.  Tim - can you comment?

**Comment by timcharper** [comment]
Sorry for slow response.

I'm not using Mesos to assign unique IPs, but doing it through the docker plugin, Weave. When I look at the mesos task details, from within the Marathon UI, I see the Weave IP address assigned to the docker container. However, I am compelled to use port forwards for all health checks.

**Comment by timcharper** [comment]
I looked in to the `ipAddress` setting. It's ignored / dropped for docker containers; I can't even set it.

If I could set it, then I believe it would do have the effect I wanted, although it'd be a hack. Better to create a docker network mode which causes it to be respected... `managed` ?

**Comment by timcharper** [comment]
Oh, it looks like I can bypass the UI and set this directly (I thought it'd be sufficient to edit the JSON params)

**Comment by timcharper** [comment]
The API does not seem to allow me to specify a health check, still:

Running:
```
$ cat <<-'EOF' > /tmp/definition.json
{
  "container": {
    "type": "DOCKER",
    "volumes": [],
    "docker": {
      "image": "registry.marathon.mesos:5000/le-python",
      "network": "HOST",
      "privileged": false,
      "parameters": [
        {
          "key": "net",
          "value": "weave"
        }
      ],
      "forcePullImage": false
    }
  },
  "portDefinitions": [],
  "ipAddress": {},
  "healthChecks": [
    {
      "protocol": "HTTP",
      "path": "/",
      "gracePeriodSeconds": 3,
      "intervalSeconds": 10,
      "port": 8000,
      "timeoutSeconds": 10,
      "maxConsecutiveFailures": 3
    }
  ]
}
EOF
$ curl  'http://10.141.141.10:8080/v2/apps//le-python?force=true' -X PUT -H 'Content-Type: application/json'   --data @/tmp/definition.json | jq .
```

output:

```
{
  "message": "Object is not valid",
  "details": [
    {
      "path": "/healthChecks(0)",
      "errors": [
        "Health check port indices must address an element of the ports array or container port mappings."
      ]
    }
  ]
}
```
