### ISSUE TITLE
Accessing Marathon Plugin Conf in Java Implementation

### ISSUE THREAD

**Issue by ameyanerurkar** [mesosphere/marathon#3592]
How do we access the Plugin Configuration when we implement the Marathon auth Plugin interface in Java.

For e.g in the Scala example plugin code: https://github.com/mesosphere/marathon-example-plugins/blob/8d8a933666231d09c13dd157d59e0d30f530ee69/auth/src/main/scala/mesosphere/marathon/example/plugin/auth/ExampleAuthenticator.scala#L46

How do we access this "configuration" JSON object in the Java implementation of the plugin interface?

**Comment by aquamatthias** [comment]
@ameyanerurkar the same logic as in the scala example can be applied to the java example: just implement this interface https://github.com/mesosphere/marathon/blob/master/plugin-interface/src/main/scala/mesosphere/marathon/plugin/plugin/PluginConfiguration.scala in your java class.
