### ISSUE TITLE
Docker volume ":z" option

### ISSUE THREAD

**Issue by googoid** [mesosphere/marathon#3593]
Good day, ladies and gents

I'm curious if it's really not possible to pass docker volume ":z" option or I'm just stupid?

Thanks

**Comment by gkleiman** [comment]
Mesos doesn't support SELinux Docker volume modes yet, see: https://issues.apache.org/jira/browse/MESOS-3776

**Comment by googoid** [comment]
Ok, thanks for the answer. Looking forward :)
