### ISSUE TITLE
marathons  not  able  to  pull image  from docker  registry  or  docker  hub

### ISSUE THREAD

**Issue by vikashsingh005** [mesosphere/marathon#3599]
Hi,  

Currently  i  am  using  docker  version 1.10  and  mesos  and  marathons  both  latest version

i  also  added .docker  file  to  etc,here  is  my   json  post  resuqest

{  
      "id": "10/101",
      "cpus": 1,
      "mem": 1024,
      "instances": 1,
      "container": {
        "type": "DOCKER",
        "docker": {
          "image": "mydomain.com:5000/test:ubuntu",
          "network": "HOST"
        }
      },
      "uris": [
             "file:///etc/docker.tar.gz"  
      ]
    }

But  Mesos  Slave  always  complain Failed,  cant  find  any  logs  on  Either  ui  on  console

**Comment by gkleiman** [comment]
This looks like a Mesos issues. Did you take a look at the Mesos Agent logs and at the files in the task sandbox?

**Comment by jasongilanfarr** [comment]
Please reopen if this is still an issue for you. We commonly pull successfully from dockerhub and private registries.
