### ISSUE TITLE
Empty response body when update existing application

### ISSUE THREAD

**Issue by sielaq** [mesosphere/marathon#3601]
Affected: Marathon 0.15.3

Not always, but repeatable, during update application (sending PUT with JSON)
I'm getting response body empty, but response code 200.
And mostly deployment is started and we cannot track the deployment
since there is no deployment_id given :(

Is there any race condition that response body is empty ?
It is similar to closed issue #1407

**Comment by gkleiman** [comment]
Could you please provide some logs? That should help us reproduce the issue.

**Comment by sielaq** [comment]
I will try to write a script and scenario that reproduce it.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1680. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
