### ISSUE TITLE
how to create mutiple marathon on mesos

### ISSUE THREAD

**Issue by Ace-Tang** [mesosphere/marathon#3602]
can someone help me how to create multiple marathon on mesos, thanks

**Comment by gkleiman** [comment]
Here's the app definition that DCOS uses to run Marathon on Marathon: https://gist.github.com/gkleiman/670909bc2aa6bd824285

**Comment by Ace-Tang** [comment]
thanks, gkleiman
I got the answer, marathon flag --zk zk://host1:port1,host2:port2,.../path ,this flag will help
