### ISSUE TITLE
Launching marathon with `--disable_ha` results in infinite election cycle

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#3606]
I tried to launch a development build of marathon against a local 3-node meso cluster while investigating why I couldn't create persistent volumes in Marathon against non-root mesos disk resources.

I'm running against the code in 4fe20cb, using the following sbt command:

`run --zk zk://mesos-1:2181,mesos-2:2181,mesos-3:2181/marathon-local --master zk://mesos-1:2181,mesos-2:2181,mesos-3:2181/mesos --mesos_authentication_principal marathon --mesos_role mlocal  --mesos_authentication_secret_file /Users/timcharper/src/oss/marathon/scratch/secret --logging_level debug --disable_ha --hostname tim-scimmia --http_address tim-scimmia --https_address tim-scimmia`

Full log output: https://gist.github.com/timcharper/b594218a15c18a634283da77dc440ebf

What's happening, I believe, is the code starts [here](https://github.com/mesosphere/marathon/blob/4fe20cb5dc2e8c945faf8709c557181157a4d7af/src/main/scala/mesosphere/marathon/MarathonSchedulerService.scala#L374-L375) and, knowing we aren't using high availability, elects itself as the master. But then it passes `None` as the `abdicateOption`, which threads through to the `runDriver` call [here](https://github.com/mesosphere/marathon/blob/4fe20cb5dc2e8c945faf8709c557181157a4d7af/src/main/scala/mesosphere/marathon/MarathonSchedulerService.scala#L325). Then, when the driver is attempted to be run, it completes immediately, because the value of `driver` is still `None`. So, [executeAbdicationCommand runs](https://github.com/mesosphere/marathon/blob/4fe20cb5dc2e8c945faf8709c557181157a4d7af/src/main/scala/mesosphere/marathon/MarathonSchedulerService.scala#L228) and that function, detecting that `abdicateOption` is `None`, simply sets leadership back to `false`. Later, we get back to [here since we're stillRunning](https://github.com/mesosphere/marathon/blob/4fe20cb5dc2e8c945faf8709c557181157a4d7af/src/main/scala/mesosphere/marathon/MarathonSchedulerService.scala#L234), call [offerLeadership](https://github.com/mesosphere/marathon/blob/4fe20cb5dc2e8c945faf8709c557181157a4d7af/src/main/scala/mesosphere/marathon/MarathonSchedulerService.scala#L361) again and then get back to the [start](https://github.com/mesosphere/marathon/blob/4fe20cb5dc2e8c945faf8709c557181157a4d7af/src/main/scala/mesosphere/marathon/MarathonSchedulerService.scala#L374), setting ourselves as a leader. Ad infinitum.

I can work around it by applying the following patch:

``` diff
diff --git a/src/main/scala/mesosphere/marathon/MarathonSchedulerService.scala b/src/main/scala/mesosphere/marathon/MarathonSchedulerService.scala
index 90eb315..b2a8376 100644
--- a/src/main/scala/mesosphere/marathon/MarathonSchedulerService.scala
+++ b/src/main/scala/mesosphere/marathon/MarathonSchedulerService.scala
@@ -372,7 +372,20 @@ class MarathonSchedulerService @Inject() (
             // In this case we aren't using ZooKeeper for leadership election.
             // Thus, we simply elect ourselves as leader.
             log.info("Not using HA and therefore electing as leader by default")
-            electLeadership(None)
+            val self = this
+            val noop = new ExceptionalCommand[JoinException] {
+              override def execute(): Unit = {
+                log.info("Doing nothing! You're the leader. You win. Go away")
+              }
+            }
+            val doElect = new ExceptionalCommand[JoinException] {
+              override def execute(): Unit = {
+                log.info("We win")
+                self.onElected(noop)
+              }
+            }
+
+            electLeadership(Some(doElect))
         }
       }
     })
```

**Comment by jasongilanfarr** [comment]
@timcharper pretty sure this is fixed now too.
