### ISSUE TITLE
how to configure container name in marathon?

### ISSUE THREAD

**Issue by gudeyang1** [mesosphere/marathon#3610]
i run docker on marathon via json file,but found that the containers's name was random ,like" mesos-b56b519f-4f0a-423b-bfdc-f964ba682549-S0.17d51e2d-8c9a-45fb-875b-ce3e389f1632"   , i want to specify the containers's name like the command docker run -d -name , anyone can help ? thanks

**Comment by gkleiman** [comment]
This is not supported by Mesos, see https://www.mail-archive.com/user@mesos.apache.org/msg05869.html

**Comment by gohonsen** [comment]
@gkleiman how to get container name or container id in marathon ?

**Comment by robsonpeixoto** [comment]
@gohonsen https://mesosphere.github.io/marathon/docs/task-environment-vars.html

**Comment by gohonsen** [comment]
@robsonpeixoto thanks. But I want to get it by rest api with appid, how ?
