### ISSUE TITLE
Question: is Mesos unified containerizer supported through the API?

### ISSUE THREAD

**Issue by martonsereg** [mesosphere/marathon#3638]
I tried out the unified containerizer support of Mesos with some `mesos-executor` commands as described [here](https://github.com/apache/mesos/blob/master/docs/container-image.md#test-it-out), but I couldn't find any documentations about it on the Marathon side.
Is it supported (or will be supported) from the Marathon API, so I can specify the mesos containerizer but still provide a docker image?

**Comment by aquamatthias** [comment]
Hey @martonsereg the unified containerizer feature is not finished in Mesos and is currently not supported in Marathon.

**Comment by martonsereg** [comment]
Thanks for the info, do you have any ETA about it? Is it a very long-term thing or can we expect it in the near future?

**Comment by aquamatthias** [comment]
@martonsereg  I can not promise anything, but it is high on our roadmap.
