### ISSUE TITLE
Error paths are mapped incorrectly

### ISSUE THREAD

**Issue by aldipower** [mesosphere/marathon#3652]
The UI maps indexed error paths for rows incorrectly.

The API wraps the index of a row with parentheses `()` like this:
`/portDefinitions(0)/name`
As you can see here:
https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/api/v2/Validation.scala#L32

But the UI tries to map this with brackets `[]` like this:
`/portDefinitions[0]/name`

This doesn't match.

Every brackets in the mapping must be converted to parentheses.

Serious bug!

**Comment by pierlo-upitup** [comment]
Damn, that shouldn't have slipped. Thanks! Will test this asap.
