### ISSUE TITLE
JSON editor help button obscured by line highlight

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#3656]
- Open Create modal
- Switch mode
- place cursor in first or second row of editor
- help icon is obscured

![screen shot 2016-04-05 at 15 54 43](https://cloud.githubusercontent.com/assets/2989362/14284236/ec7ec58c-fb46-11e5-8caa-147c045deac7.png)

**Comment by pierlo-upitup** [comment]
Fixed by https://github.com/mesosphere/marathon-ui/pull/732
