### ISSUE TITLE
Don't provide a kill button for "suspended" resident tasks

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#3658]
![resident-tasks](https://cloud.githubusercontent.com/assets/647035/14284491/15d5ea04-fb48-11e5-8fba-30ed834d7876.gif)
There shouldn't be a kill and kill & scale button for "suspended" resident tasks, as there is no way to kill them until you have removed/wiped the volume.

**Comment by pierlo-upitup** [comment]
Also suggested by @gkleiman 
>  and I also think it would be good if the UI would show non-running tasks with a reservation as “suspended” or something like that instead of as “waiting"

**Comment by pierlo-upitup** [comment]
Flagging as bug

**Comment by pierlo-upitup** [comment]
I believe we should also expose a way to send `POST /v2/tasks/delete?wipe=true` to "wipe" the volumes.

**Comment by pierlo-upitup** [comment]
After talking with @gkleiman and @aquamatthias we agreed that the correct solution here is to add a "Kill & Wipe" button for stateful tasks.
