### ISSUE TITLE
Improve genral error reporting

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#3661]
![](https://cloud.githubusercontent.com/assets/647035/14285086/780bda06-fb4a-11e5-8377-6465319115a9.png)
If I create an app with an existing app id, I get a pretty useless general error message. Let's include the api message/details. 

**API response**
```
{"message":"An app with id [/postgres] already exists."} 
```

**Comment by pierlo-upitup** [comment]
This was fixed in https://github.com/mesosphere/marathon-ui/pull/721 and https://github.com/mesosphere/marathon-ui/pull/725
