### ISSUE TITLE
Create group of docker containers

### ISSUE THREAD

**Issue by ghost** [mesosphere/marathon#3665]
Is it possible to create a group containing two application of type docker? 

I would like to have a simple group containing a web server and a database. 

I have tried to create a json file but I got the following error:

`{"message":"Object is not valid","details":[{"attribute":"value","error":"AppDefinition must either contain one of 'cmd' or 'args', and/or a 'container'."}]}`

the json configuration I have used is the following:
`
{
  "id": "/product",
  "groups": [
    {
      "id": "/product/database",
      "apps": [
         {
         "id": "/product/redis",
         "container":
         {
           "type": "DOCKER",
           "volumes": [],
           "docker": {
             "image": "redis",
             "network": "BRIDGE",
             "portMappings": [
               {
                 "containerPort": 80,
                 "hostPort": 0,
                 "protocol": "tcp"
               }
             ],
             "privileged": false,
             "forcePullImage": false
           }
       },
       "instances": 1,
       "cpus": 0.1,
       "mem": 64
        }
      ]
    },{
      "id": "/product/service",
      "dependencies": ["/product/database"],
      "apps": [
         {
         "id": "/product/php",
         "container": {
           "type": "DOCKER",
           "volumes": [],
           "docker": {
             "image": "php",
             "network": "BRIDGE",
             "portMappings": [
               {
                 "containerPort": 80,
                 "hostPort": 0,
                 "protocol": "tcp"
               }
             ],
             "privileged": false,
             "forcePullImage": true
           }
       },
       "instances": 1,
       "cpus": 0.1,
       "mem": 64
        }
      ]
    }
  ]
}
`

Marathon 0.15.3
Mesos 0.27.2

**Comment by Poltergeist** [comment]
Hi @Gidipp , 
I do think that you posted your configuration against the `/apps` endpoint, which will not work with a group structure, instead you might want to `POST` the configuration to the /groups endpoint. In that case your configuration will work and produce the following structure
```
/product
  - /database/
  - /service/ 
  - /redis
  - /php
```
If you want the following structure:
```
/product
  - /database/
      - /redis
  - /service/ 
      - /php
```
You have to change the JSON to this structure:
```JSON
{
  "id": "/product",
  "groups": [
    {
      "id": "/product/database",
      "apps": [
        {
          "id": "/product/database/redis",
          "container": {
            "type": "DOCKER",
            "volumes": [],
            "docker": {
              "image": "redis",
              "network": "BRIDGE",
              "portMappings": [
                {
                  "containerPort": 80,
                  "hostPort": 0,
                  "protocol": "tcp"
                }
              ],
              "privileged": false,
              "forcePullImage": false
            }
          },
          "instances": 1,
          "cpus": 0.1,
          "mem": 64
        }
      ]
    },
    {
      "id": "/product/service",
      "dependencies": [
        "/product/database"
      ],
      "apps": [
        {
          "id": "/product/service/php",
          "container": {
            "type": "DOCKER",
            "volumes": [],
            "docker": {
              "image": "php",
              "network": "BRIDGE",
              "portMappings": [
                {
                  "containerPort": 80,
                  "hostPort": 0,
                  "protocol": "tcp"
                }
              ],
              "privileged": false,
              "forcePullImage": true
            }
          },
          "instances": 1,
          "cpus": 0.1,
          "mem": 64
        }
      ]
    }
  ]
}
```

Please let me know if that fixes your issue.

**Comment by Gidipp** [comment]
Thank you very match for your help. 

I have changed the API endpoint to `/groups` and effectively it works fine. 

However I don't understand what would be the best way to access the database from the application.

I can't use an HTTP proxy since the connection is pure TCP and I won't like to use the HOST network because I would lose the possibility to run multiple Redis container in the same host. 

Ideally I would like to have two variables ( e.g. REDIS_HOST and REDIS_PORT) in the application that are updated when the redis container is started (and every time is restarted). 

Is it something somehow possible?

Thanks

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2244. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
