### ISSUE TITLE
Scrolling issue with create modal

### ISSUE THREAD

**Issue by leemunroe** [mesosphere/marathon#3671]
When using create modal on a smaller screen I'm having scrolling issues in Chrome on Mac OS X.

Typically if the content area of the modal is longer than the viewable area, I can scroll that area. In this screen recording you can see that instead of scrolling the content area the whole page behind the modal scrolls instead, making the modal unusable.

Using Chrome Version 49.0.2623.110 (64-bit)

![](https://s3.amazonaws.com/f.cl.ly/items/3E1d461P2o2S00143j0O/Screen%20Recording%202016-04-05%20at%2009.29%20AM.gif?v=df6a1fd9)

**Comment by philipnrmn** [comment]
Hey @leemunroe, I can't reproduce this. Do you have any nonstandard accessibility features enabled?

![](https://s3.amazonaws.com/f.cl.ly/items/1s3M0d3o1U2d2G032U2R/Screen%20Recording%202016-04-06%20at%2011.05%20AM.gif?v=d4f93bb7)

**Comment by orlandohohmeier** [comment]
@leemunroe I'm also unable to reproduce this, and I tired a lot...

**Comment by leemunroe** [comment]
Weird. I was able to get it working as expected by removing `overflow` and `overflow-y` from `.modal`.

Note in this screen recording I also turned the scrollbars on in Mac settings.

![](https://s3.amazonaws.com/f.cl.ly/items/442K0y1T3W0w3h0p0c2F/Screen%20Recording%202016-04-06%20at%2001.22%20PM.gif?v=9ee5aeeb)

**Comment by orlandohohmeier** [comment]
![scrolling-works-as-expected](https://cloud.githubusercontent.com/assets/647035/14345810/60ff32fc-fcaf-11e5-8f35-fda7d0768f4d.gif)

I still don't know why you're unable to scroll the modal, as I don't have such a problem, as you can see. Nonetheless, I've created and pushed a "fix" mesosphere/marathon-ui@857428fcf47d98fcb64819005d730f689158bbb1. I would love, if you could try.

**Comment by pierlo-upitup** [comment]
We cannot reproduce this issue. Removing the `bug` label and putting it back to Backlog.

**Comment by pierlo-upitup** [comment]
Upon further investigation, @Poltergeist was able to reproduce, and it seems to affect retina screens only.
