### ISSUE TITLE
Resident tasks: Disallow "acceptedResourceRoles" != ["*"]

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3673]
Mesos treats resources which already have a role assignment != "*" as "reserved". Therefore, they cannot be reserved again. To change that, the reserve op would need to specify the resources to relabel as well as the goal reservation state. Since we cannot change that short term, we should disallow resident apps which target roles != "*".

/cc @aquamatthias @meichstedt

**Comment by meichstedt** [comment]
disallowing defining `acceptedResourceRoles` alone is not enough imo. The Marathon doc says _If you do not specify this, Marathon considers all resource offers with roles that have been configured by the --default_accepted_resource_roles command line flag. If no --default_accepted_resource_roles was given on startup, Marathon considers all resource offers._

So in general, we should only consider unreserved resources for reservations.
