### ISSUE TITLE
`Validation` should not be in API layer

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3676]
`Validation` is currently in the `mesosphere.marathon.api.v2` package. It is used all over the place.

In my opinion, the api package can use code from core/state etc but not the other way around to prevent cyclic dependencies.

/cc @gkleiman @lxwbr @aquamatthias

**Comment by lxwbr** [comment]
@kolloch I do agree. Bugged me from day one.

**Comment by jasongilanfarr** [comment]
We've kind of addressed this as a start and there's soon to be more incoming. Closing out as it's just a "which package is this in"
