### ISSUE TITLE
The UI doesn't let you create an app with BRIDGED networking and no port mappings

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#3688]
There's no way of removing the default port mapping without using the JSON editor.

**Comment by pierlo-upitup** [comment]
@gkleiman can you please suggest a use case for creating an app in BRIDGE mode without assigning a portMapping?

**Comment by pierlo-upitup** [comment]
Backlogging this as we need to define if this is an actual use-case for those using the UI.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2228. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
