### ISSUE TITLE
Readiness Checks Should be Independent of Service Health

### ISSUE THREAD

**Issue by gabrielhartmann** [mesosphere/marathon#3689]
The Health of a Scheduler is a signal to an end-user.  The user may choose to ignore it or, if Unhealthy, may choose to take actions to improve it.

Regardless of the health of a Scheduler or any Task, an end-user may wish to perform a configuration or software update.  These actions may or may not be what are necessary to return a Scheduler to a healthy state.

The concepts of health and update status (readiness) are not related.  They are independent signals to end-users of two separate aspects of a service.

The current requirement that one aspect of a service be in a particular state (Healthy) before operations like configuration or software updates may proceed is inappropriate.

**Comment by aquamatthias** [comment]
Health Checks are meant for showing if a task is alive - they are not meant as monitoring solution showing the status of a complete service. So it should _not_ show if a cassandra cluster is healthy, but if the cassandra scheduler is healthy. If we want to show the health of the cassandra cluster, Marathon health checks are not the right tool.

Readiness checks are performed during the start period, so tasks can signal if they are ready to serve traffic.

It was a design decision in Marathon to start the readiness checks after a task becomes healthy. We removed this dependency, so they are independent now.
