### ISSUE TITLE
Marathon UI task creation doesn't include fields for IP Address

### ISSUE THREAD

**Issue by djosborne** [mesosphere/marathon#3690]
**Background:**
Marathon v0.14.0 introduced the ability to specify the ipAddress field, to indicate that a task should request an IP-per-container. The user can also fill that field with "groups", and "service discovery info". 

**Request:**
These parameters should be available in the UI. This would look something like the following:
- Some sort of checkbox to "activate" this field (since the presence of this field triggers ip address assignment).
- a field to specify one or more groups
- a field to specify multiple discovery ports, where each port has a name, number, and protocol

This would primarily target the Mesos containerizer, but would also be useful for the docker containerizer. For example, if using the Docker Containerizer with a user-defined docker network, then the task will be using IP-per-container. The user should indicate this in Marathon by using the ipAddress fields to specify discovery ports.

**Comment by pierlo-upitup** [comment]
cc @air @leemunroe

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2426. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
