### ISSUE TITLE
Marathon uses incorrect URI for continue operation on a interrupted plan

### ISSUE THREAD

**Issue by mohitsoni** [mesosphere/marathon#3691]
Marathon currently uses following URI to `continue` an interrupted plan:
`/services/cassandra/v1/plan/continue`

This URL should be:
`/service/cassandra/v1/plan/continue`

The change to the URI should be: `services` -> `service`

**Comment by pierlo-upitup** [comment]
@aquamatthias is this only related to the `POST` -> `/continue` or is there a similar problem for the `GET` requests perfomred by the backend? If not, we can close this issue as the UI addressed this in the linked PR.

**Comment by aquamatthias** [comment]
Fixed in the UI.
