### ISSUE TITLE
UX improvements to scheduler upgrades

### ISSUE THREAD

**Issue by pierlo-upitup** [mesosphere/marathon#3693]
From @leemunroe 

> To help make this flow a bit more usable, I suggest a couple of minor UI tweaks and additions to the docs.
1. Marathon UI Docs documenting the new "Waiting for user action..." status
2. Deployments Docs documenting scheduler migrations and "Continue" button
3. A tooltip + link to deployment docs from the deployments tab so user can read about what the Continue button means e.g. next to the "Action" table heading
4. Link "Waiting for user action..." to the deployments tab so the user doesn't have to guess where to go

**Comment by leemunroe** [comment]
I would remove the sidebar status filter until it's clear that this will be helpful

**Comment by pierlo-upitup** [comment]
Re-opening as the linked PR only solves the last AC

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2486. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
