### ISSUE TITLE
Odd looking padding (right) in IE11

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#3696]
![screen shot 2016-04-07 at 12 02 00](https://cloud.githubusercontent.com/assets/647035/14347670/95cf2d08-fcb8-11e5-9572-6a741a5ae6ea.png)

Environment: IE11 on Windows 8.1

**Comment by pierlo-upitup** [comment]
So this seems to be because scrollbars in IE11 think they are "invisible" scrollbars (like in OSX) but they are not actually. Interesting.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2130. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
