### ISSUE TITLE
External Volumes: DVDI/rexray

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3698]
The API will be extended such that users may request different types of "external" volumes distinguished by provider. 

Initial testing will focus on the Docker Volume Driver Interface provider and the "rexray" driver. For this use case, we also provide specific validation. Other provider/driver combinations should work in principal but are not tested.

Sample application definition JSON fragment:

```
      {
        "id": "/foo",
        "container": {
	   ...
          "volumes": [
            {
              "containerPath": "/docker_storage",
              "mode": "RW",
              // also supported for non-docker containers!
              "external": {
		    // Uniquely identifies the volume inside of the cluster for some provider driver
                 // combinations which provide cluster-wide volumes.
                 // For other providers this may only be unique per node, e.g. secret providers.
                "name": "my-external-volume",
                “provider”: “dvdi”,
                “options”: { “dvdi/iops”: 1000, “dvdi/driver”: “rexray” },
                “size”: 1234
              }
            },
            ...
          ]
        },
        ...
      }
```

There still seems to be a rather big bug in combination with rexray:

* [#88 mesos-module-dvdi: hung on unmount operation](https://github.com/emccode/mesos-module-dvdi/issues/88): Workaround, use the filesystem isolator of Mesos

Related epic (sorry, internal): [MARATHON-749](https://mesosphere.atlassian.net/browse/MARATHON-749)

**Comment by jdef** [comment]
correction: the "bug in combination with rexray" is really not specific to rexray. more closely related to an implementation detail of the DVDI mesos module (it relies on something else to isolate the container mount namespace from the host mount namespace). rexray may have other bugs, but this isn't one :)
