### ISSUE TITLE
External Volumes: Choose a matching upgrade strategy by default

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3699]
External volumes require specific upgrade strategy settings. These should be chosen by default if the user does not specify anything explicitly similarly to what we do for "persistent" volumes.

Depends on #3698.

Related epic (sorry, internal): [MARATHON-749](https://mesosphere.atlassian.net/browse/MARATHON-749)

**Comment by kolloch** [comment]
@lexwbr Could you do that today? Probably not a big deal based on your other work.

**Comment by jdef** [comment]
looks like this needs to take external vols into account?https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/api/v2/json/Formats.scala#L661

**Comment by jdef** [comment]
related #3686
