### ISSUE TITLE
External Volumes: Clean up validation

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3700]
The current state of the validation logic is a bit overcomplicated. We also need to verify that the resulting error paths make sense.

Depends on #3698.

Related epic (sorry, internal): [MARATHON-749](https://mesosphere.atlassian.net/browse/MARATHON-749)

**Comment by jdef** [comment]
"does not seem to result in the correct validation paths" -- what does this mean?
@kolloch

**Comment by kolloch** [comment]
I thought that I remembered some discussion around that -- maybe you fixed that. Anyway, we'll deal with the topic.

**Comment by jdef** [comment]
I was asking for a more verbose and meaningful description of the problem.
The issue description is pretty terse
