### ISSUE TITLE
--assets_path command-line flag not working

### ISSUE THREAD

**Issue by ruippeixotog** [mesosphere/marathon#3706]
When our servers were running Marathon v0.10.1, we used to run it with some customizations to the official Marathon UI, deploying them by doing the following process:
- Clone https://github.com/mesosphere/marathon-ui and apply the modifications;
- Run the gulp build and deploy the resulting `dist` directory to our servers;
- Run Marathon with the `--assets_path <path_to_ui_dist_dir>` command-line flag.

Recently (well, at the end of February) we migrated our infrastructure to use the latest Marathon version at the time, v0.15.2. However, now the customized UI is not being recognized or loaded, the built-in one appearing instead. I checked that the command-line flag is still being passed correctly (`ps` shows it as before) and the UI is correctly built (by running an HTTP server to the resources and opening the page).

Did the behavior of the `--assets_path` flag change? Must the UI be built or packaged in a different way now?

**Comment by aquamatthias** [comment]
The UI is now a separate project https://github.com/mesosphere/marathon-ui and is integrated as webjar.
The `--asset_path` is deprecated - we need to make that clear in the documentation.
Also note: you now have the ability to write http plugins, if you want to have your own or custom UI.

**Comment by aquamatthias** [comment]
The other option is to replace the UI files in the jar by your own UI files.

**Comment by ruippeixotog** [comment]
Thank you for the quick response! Is there any documentation for writing a plugin with the capabilities to serve a custom UI? I found [this page](https://mesosphere.github.io/marathon/docs/plugin.html), but it seems to mention only `Authorizer` and `Authenticator` plugins. I can also unpackage the JAR file and replace the UI webjar as you said, but it would be a lot more inconvenient as I wouldn't be able to use directly the official Debian repository and install Marathon using `apt-get` (unless I'm missing something here).

**Comment by aquamatthias** [comment]
Hey @ruippeixotog you are right this is missing.
We re in the process of updating the docs here. 
The plugin interface you need to implement is this: https://github.com/mesosphere/marathon/blob/master/plugin-interface/src/main/scala/mesosphere/marathon/plugin/http/HttpRequestHandler.scala
An example plugin can be found here: https://github.com/mesosphere/marathon-example-plugins/tree/master/http

**Comment by ruippeixotog** [comment]
Thank you for the links! I think that the plugin approach won't work for me as it seems it can only provide new endpoints rooted at `/v2/plugins`, being unable to modify existing endpoints. I'll consider replacing the UI files in the assembly JAR instead - it's a bit cumbersome but it can be done. Thanks again!

**Comment by ruippeixotog** [comment]
Just to note that, although this issue was closed, [the official documentation page](https://mesosphere.github.io/marathon/docs/command-line-flags.html#optional-flags-1) still lists `--assets_path` as a valid option. It leads users to think there is a way to customize the web UI, a thing that is not easy to do anymore.

**Comment by aquamatthias** [comment]
@ruippeixotog thanks for reminding me here. I created a patch to solve this: https://phabricator.mesosphere.com/D169
