### ISSUE TITLE
external volumes: UI shows volume attached even though app is suspended and no tasks are active

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#3724]

**Comment by pierlo-upitup** [comment]
After a quick chat with @kolloch we came to the conclusion that in fact the UI should not make any assumption about the attached/detached state of an external volume.  The correct fix for this is to drop that column entirely from the UI at this point: to actually display such info the API must include some changes that depend on Mesos. We probably need a separate issue for that. 
cc @air

**Comment by jdef** [comment]
sounds good to me
