### ISSUE TITLE
is there any way to access other app's envs? thanks!

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#3726]

**Comment by xiaods** [comment]
what purpose on this report.

**Comment by Poltergeist** [comment]
Hi, each application is run in their own container (environment) so there is currently no way to access the environment of another container.

**Comment by junneyang** [comment]
@xiaods 
like the docker-compose's link feature

**Comment by xiaods** [comment]
@junneyang  marathon is not the scope on this feature, need u do that. alternative, we need expect compose support marathon

**Comment by junneyang** [comment]
@xiaods 
why marathon is not the scope on this feature?
multi-app's interactive is a  reasonable  feature, i think.

**Comment by jasongilanfarr** [comment]
This is something we defer to a service discovery mechanism, for example marathon-lb or mesos-dns
