### ISSUE TITLE
TCP/HTTP health checks not resistant to network partition

### ISSUE THREAD

**Issue by medzin** [mesosphere/marathon#3728]
Current implementation of health checks does not perform optimally during a network partition. It marks task to be killed and once the network partition heals it kills all of the tasks on the far side of the partition. Can Marathon use TASK_LOST status from Mesos to pause health checks?

**Comment by gkleiman** [comment]
Marathon treats a `TASK_LOST` update as a task failure and will launch a new the task, so it wouldn't make sense to pause health checks.

The proper fix would be to add support for Mesos HTTP/TCP health checks once  https://issues.apache.org/jira/browse/MESOS-2533 is merged.

**Comment by gkleiman** [comment]
Fixed in v0.15.x by e8ace92168573927326f64963b73bb6df88dbdd3, we still have to port this fix to 1.x

cc/ @aquamatthias

**Comment by SEJeff** [comment]
@gkleiman In a perfect world, it seems like [this](https://issues.apache.org/jira/browse/MESOS-2533) and [this](https://issues.apache.org/jira/browse/MESOS-3567) are actually better. Doing it this way, would allow not having to have these sort of hacks in marathon proper, and everyone is better off!

What do you think?

**Comment by jasongilanfarr** [comment]
Support for Mesos health checks is in marathon now.

**Comment by SEJeff** [comment]
What version will this be in?
