### ISSUE TITLE
Marathon health checks do not work with Docker host network

### ISSUE THREAD

**Issue by Nihn** [mesosphere/marathon#3729]
Hi,

when I try adding health check to app run by Marathon (`marathon-lb`) in Docker container in `host` network, app is permanently `Unhealthy`. When I do it manually everything works fine:
```
root@lb1:~# curl -XGET localhost:9090/_haproxy_health_check
<html><body><h1>200 OK</h1>
Service ready.
</body></html>
root@lb1:~# echo $?
0
```
same applies to TCP check.
If app is run in `bridge` network checks work ok too.

Another thing is that I need to specify `9090` port in `ports` config field to add check even it is not required by `host` network.

**Comment by pierlo-upitup** [comment]
Hi @Nihn 
could you provide the JSON of the app definition? Also, which Marathon and Mesos versions are you running this on?

**Comment by Nihn** [comment]
@pierlo-upitup 
Strange thing but I'm not able to reproduce it anymore. Closing ticket.

**Comment by bakstad** [comment]
I have a similar problem. I also want to add a health check for marathon-lb running in docker. 

My first problem was that I got the error message "curl not found" which I didn't understand, but it seems that health checks with protocol COMMAND are run _inside_ the container itself.

The second problem then became that the marathon-lb image does not have curl installed, so how would this even be possible then?

It seems like they are working on the issue here https://issues.apache.org/jira/browse/MESOS-3599 .

One solution to this would be to introduce variables in the marathon-gui so that we can write a HTTP health check with something like: http://$HOST:9090/_haproxy_health_check

**Comment by pierlo-upitup** [comment]
@bakstad I'm not sure I understand what you're trying to do.

Is your goal to add a health check to the `marathon-lb` application itself? If so, how about using HTTP health check against a portIndex? 

![image](https://cloud.githubusercontent.com/assets/1078545/14639230/b930b08c-063b-11e6-91f9-2379fc5f7875.png)


Or, from the JSON editor

```
"healthChecks": [
    {
      "protocol": "HTTP",
      "path": "/",
      "portIndex": 0,
      "gracePeriodSeconds": 300,
      "intervalSeconds": 60,
      "timeoutSeconds": 20,
      "maxConsecutiveFailures": 3
    }
  ]
```

**Comment by bakstad** [comment]
My goal is to run a healthcheck against marathon-lb's haproxy at port 9090 and ensure it is running, but I thought health checks only ran against the http://<host>:<allocated_port> and I completely overlooked the port settings. It solves my problem exactly, thanks!

 I'm sorry for the inconvenience.

**Comment by vivekjuneja** [comment]
@bakstad  - I was trying to do the same thing. I deployed the marathon-lb with the following JSON - 

```
{
	"healthChecks": [{
		"port": 9090,
		"path": "/_haproxy_health_check",
		"protocol": "HTTP"
	}],
	"container": {
		"docker": {
			"network": "HOST",
			"image": "mesosphere/marathon-lb:v1.1.1"
		},
		"type": "DOCKER"
	},
	"mem": 256,
	"cpus": 0.1,
	"instances": 1,
	"args": [
		"sse",
		"-m",
		"http://marathon:8080",
		"--group",
		"external"
	],
	"id": "marathon-lb"
}
```

However, the health checks fails, as Marathon is unable to use the Port 9090. It instead defaults to "portIndex" and uses Port Index 0. 

How did you solve this ?

Thanks!

**Comment by bakstad** [comment]
@vivekjuneja According to the marathon-lb docs you have to specify the environment variable PORTS which specifies the ports haproxy will bind to. In my config below you will see 9090 and a long list of 10000-10200 ports which are used to load balance services running on marathon.

Here is my configuration:
```
{
  "id": "marathon-lb",
  "cpus": 0.5,
  "mem": 64,
  "instances": 2,
  "constraints": [["hostname", "UNIQUE", ""]],
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "mesosphere/marathon-lb",
      "network": "HOST",
      "privileged" : true,
      "parameters": [],
      "forcePullImage": false
    }
  },
  "cmd": "/marathon-lb/run sse --marathon http://master.mesos:8080 --group external",
  "env": {
    "PORTS": "9090,10000,10001,10002,10003,10004,10005,10006,10007,10008,10009,10010,10011,10012,10013,10014,10015,10016,10017,10018,10019,10020,10021,10022,10023,10024,10025,10026,10027,10028,10029,10030,10031,10032,10033,10034,10035,10036,10037,10038,10039,10040,10041,10042,10043,10044,10045,10046,10047,10048,10049,10050,10051,10052,10053,10054,10055,10056,10057,10058,10059,10060,10061,10062,10063,10064,10065,10066,10067,10068,10069,10070,10071,10072,10073,10074,10075,10076,10077,10078,10079,10080,10081,10082,10083,10084,10085,10086,10087,10088,10089,10090,10091,10092,10093,10094,10095,10096,10097,10098,10099,10100,10101,10102,10103,10104,10105,10106,10107,10108,10109,10110,10111,10112,10113,10114,10115,10116,10117,10118,10119,10120,10121,10122,10123,10124,10125,10126,10127,10128,10129,10130,10131,10132,10133,10134,10135,10136,10137,10138,10139,10140,10141,10142,10143,10144,10145,10146,10147,10148,10149,10150,10151,10152,10153,10154,10155,10156,10157,10158,10159,10160,10161,10162,10163,10164,10165,10166,10167,10168,10169,10170,10171,10172,10173,10174,10175,10176,10177,10178,10179,10180,10181,10182,10183,10184,10185,10186,10187,10188,10189,10190,10191,10192,10193,10194,10195,10196,10197,10198,10199"
  },
  "healthChecks": [
    {
      "path": "/_haproxy_health_check",
      "protocol": "HTTP",
      "gracePeriodSeconds": 30,
      "intervalSeconds": 5,
      "timeoutSeconds": 5,
      "maxConsecutiveFailures": 5,
      "ignoreHttp1xx": false,
      "port": 9090
    }
  ]
}
```

**Comment by vivekjuneja** [comment]
Thanks @bakstad !

I do still have the same issue, even with PORTS environment variable definition. Marathon uses the ports assigned to the each Task instance, instead of the Port 9090. Here are the screen shots to help make my point -

![image](https://cloud.githubusercontent.com/assets/122003/14701525/d05b9c44-07e0-11e6-9edc-ceb79f6ada9e.png)


Here is the screen shot of my Configuration in Marathon -

![image](https://cloud.githubusercontent.com/assets/122003/14701605/2dea8136-07e1-11e6-8ca8-7e9ee6db26a5.png)

I think I might be doing something silly here. If you find something useful, do let me know to resolve this situation.

**Comment by vivekjuneja** [comment]
@bakstad - I was able to fix this issue, however I am not sure if this is a right way to run "marathon-lb" on Mesos.

Here is the JSON file I use now - 
```
  "id": "marathon-lb",
  "cpus": 0.5,
  "mem": 64,
  "instances": 2,
  "constraints": [["hostname", "UNIQUE", ""]],
  "ports": [9090],
  "requirePorts": true,
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "mesosphere/marathon-lb:v1.1.1",
      "network": "HOST",
      "privileged" : true,
      "parameters": [],
      "forcePullImage": false
    }
  },
  "cmd": "/marathon-lb/run sse --marathon http://marathon:8080 --group external",
  "env": {
    "PORTS": "9090,10000,10001,10002,10003,10004,10005,10006,10007,10008,10009,10010,10011,10012,10013,10014,10015,10016,10017,10018,10019,10020,10021,10022,10023,10024,10025,10026,10027,10028,10029,10030,10031,10032,10033,10034,10035,10036,10037,10038,10039,10040,10041,10042,10043,10044,10045,10046,10047,10048,10049,10050,10051,10052,10053,10054,10055,10056,10057,10058,10059,10060,10061,10062,10063,10064,10065,10066,10067,10068,10069,10070,10071,10072,10073,10074,10075,10076,10077,10078,10079,10080,10081,10082,10083,10084,10085,10086,10087,10088,10089,10090,10091,10092,10093,10094,10095,10096,10097,10098,10099,10100,10101,10102,10103,10104,10105,10106,10107,10108,10109,10110,10111,10112,10113,10114,10115,10116,10117,10118,10119,10120,10121,10122,10123,10124,10125,10126,10127,10128,10129,10130,10131,10132,10133,10134,10135,10136,10137,10138,10139,10140,10141,10142,10143,10144,10145,10146,10147,10148,10149,10150,10151,10152,10153,10154,10155,10156,10157,10158,10159,10160,10161,10162,10163,10164,10165,10166,10167,10168,10169,10170,10171,10172,10173,10174,10175,10176,10177,10178,10179,10180,10181,10182,10183,10184,10185,10186,10187,10188,10189,10190,10191,10192,10193,10194,10195,10196,10197,10198,10199"
  },
  "healthChecks": [
    {
      "path": "/_haproxy_health_check",
      "protocol": "HTTP",
      "gracePeriodSeconds": 30,
      "intervalSeconds": 5,
      "timeoutSeconds": 5,
      "maxConsecutiveFailures": 5,
      "ignoreHttp1xx": false,
      "port": 9090
    }
  ]
}
```

I had to use the "requirePorts" to force Marathon to use the provided Port instead of using the Mesos allocated port. I also had to change my Mesos slaves to use 9090 in the allocation by adding it in /etc/mesos-slave/resources file. 

Although this works for me, I am not sure if this is the right approach to it.

@pierlo-upitup  - If you have time, i would love to have your advise as well on this. If you can point me to a reference, I would appreciate that too. 

Thanks!

**Comment by bakstad** [comment]
You sort of have to ignore the ports that show up in the GUI. The marathon-lb container is running in HOST mode, meaning that it shares the network with the host OS. So as long as haproxy can bind to 9090 you should reach haproxy at http://{node_ip}:9090/haproxy?stats

I don't really understand why you needed to update your mesos slave configuration though.

**Comment by vivekjuneja** [comment]
@bakstad - Thanks! I am aware of the HOST mode. 

As I mentioned earlier, Marathon was not using the Host port 9090, instead was using the Mesos defined Ports. In the screenshot I attached earlier, you can see the ports 31145 and 31163 being used _(notice the red arrows)_. These ports are being allocated by Mesos Slave.

Let me know if you still have issues understand this behavior.

**Comment by bakstad** [comment]
Hm, I don't know if this helps, but have you tried upgrading to the newest version for marathon-lb (1.2.0)?
