### ISSUE TITLE
Improve format of events on the event bus

### ISSUE THREAD

**Issue by guenter** [mesosphere/marathon#373]
The format of the events on the event bus is inconsistent, and a consumer needs to maintain a significant amount of state to make it useful. Let's track suggestions for a redesigned event bus here.

**Comment by janisz** [comment]
Related to https://github.com/mesosphere/marathon/issues/4947

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3700. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
