### ISSUE TITLE
Event Bus - can't get status update json

### ISSUE THREAD

**Issue by wwjgit** [mesosphere/marathon#3730]
I enabled the flags -event_subscriber and –http_endpoints to try to receive events. And I started a webserver using netcat. However, while there were two redis instances status changing from TASK_LOST to TASK_RUNNING, only one TASK_RUNNING json was received on my netcat. I found that on marathon UI, those two redis instances were updated at the same time. Maybe that is reason? If the status of two tasks change at the same time, only one update json will be received?

Any ideas on this?

**Comment by Poltergeist** [comment]
Hi @wwjgit , 

I will look into that. 

Marathon Ui is polling the endpoints for tasks constantly every few seconds, so it might be that the status of the tasks are changed in one interval of requests and it only seems like the tasks changed their status at the same time.

What version of Marathon and Mesos are you using?

**Comment by wwjgit** [comment]
Thank you, Poltergeist.

Marathon 0.13.0
Mesos 0.26.0

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1771. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
