### ISSUE TITLE
volumes-from failed

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#3733]
i refer this doc, the last section
https://mesosphere.github.io/marathon/docs/native-docker.html
![qq 20160411193116](https://cloud.githubusercontent.com/assets/6802322/14425745/08040b12-001c-11e6-998f-8a4f8b2fd1ce.png)

app01:
{
    "id": "/develop/docker-demo",
    "apps": [
        {
            "id": "data-test",

app02 volumes-from app01:
        {
            "id": "django",
"parameters": [
                        { "key": "volumes-from", "value": "/develop/docker-demo/data-test" }
                    ]

mesos error:
Error response from daemon: no such id: /develop/docker-demo/data-test

thanks for your help!

**Comment by pierlo-upitup** [comment]
Hi @junneyang 
which Mesos and Marathon version are you trying to run this on?

**Comment by junneyang** [comment]
MesosVersion:0.27.1
MarathonVersion 0.15.3

**Comment by pierlo-upitup** [comment]
I believe you need to specify the docker ID for the `volumes-from`, not the marathon app ID. 
Does this help http://stackoverflow.com/questions/29065246/how-to-use-volumes-from-in-marathon?

**Comment by junneyang** [comment]
@pierlo-upitup 
thanks!

**Comment by pierlo-upitup** [comment]
You're very welcome @junneyang ! Closing the issue for now, feel free to re-open if needed.
