### ISSUE TITLE
"Labels" fields should allow multi-lines values

### ISSUE THREAD

**Issue by eLvErDe** [mesosphere/marathon#3734]
Hello,

These fields can be used to pass HAProxy configuration snippets trough Marathon-LB:
https://github.com/mesosphere/marathon-lb#overridable-templates

However, if I put "\n" in the field, the resulting file contains "\n" instead of a carriage return.
I think the field should allow multi-line input and should not strip anything (double space can be used for the configuration file to be indented correctly, and it does matter).

Best regards,

Adam.

**Comment by Poltergeist** [comment]
Hi @eLvErDe, this sounds to me like an issue with marathon-lb, could you please open an Issue at the www.github.com/mesosphere/marathon-lb repository.

**Comment by brndnmtthws** [comment]
This is certainly not a bug in marathon-lb. If you manually edit the JSON or POST it to Marathon, everything works great. The UI widget will eat any newlines you paste into the label value fields.

**Comment by brndnmtthws** [comment]
Actually, maybe this belongs in the marathon-ui project? Please advise.

**Comment by eLvErDe** [comment]
Thanks for reopening !

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4507. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
