### ISSUE TITLE
[split from #2247] question about error.path.missing

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#3735]
@junneyang asked the following question in #2247. 

```
{"path":"/container/volumes(0)/mode","errors":["error.path.missing"]},

what does error.path.missing meaning?
why the hostPath field is required?
```

**Comment by philipnrmn** [comment]
Hi @junneyang,

`error.path.missing` means that the item specified in the value of `path` is missing. In your case, that's `/container/volumes(0)/mode`. 

That means you need to specify a `hostPath`, `containerPath` and `mode` in each object in `volumes`, eg:

```
{
  "hostPath": "/local/path/to/store/packages",
  "containerPath": "/storage",
  "mode": "RW"
}
```

`hostPath` is required because a container volume without a mapping to the host would be ephemeral; if the instance was killed, all its data would be lost.

**Comment by junneyang** [comment]
@philipnrmn 
hostPath is not required, because docker daemon could auto select hostPath for container volume,
we can use docker inspect to find details.

1. if i define like this, error.path.missing exception throws:
"volumes": [
                    {
                        "containerPath": "/opt/data-test",
                        "mode": "RW"
                    }
                ]

2. fi i define like this, no errors:
"volumes": [
                    {
                        "containerPath": "/opt/data-test",
                        **"hostPath": "",**
                        "mode": "RW"
                    }
                ]

it's right
