### ISSUE TITLE
Isolated regions / Per Container IP - impact on marathon UI

### ISSUE THREAD

**Issue by robfrut135** [mesosphere/marathon#3744]
Hi, 
I was reading this doc. about "Per-Container IP" 

https://docs.google.com/document/d/17mXtAmdAXcNBwp_JfrxmZcQrs7EO6ancSbejrqjLQ0g/edit  

It'd be really useful and a great improvement re-think UI to allow operate with this functionality (different isolated regions where apps're running inside Marathon). In that sense, I've made prototype for that and modify the original doc. adding the features that I consider more vital. In the next days I'm gonna add a basic visual design for it to the doc.

**11 Impact on Marathon UI**
- General requirements
1. Login feature to replace current “Basic Authentication”.
2. User can authenticate as _application developer_ / _datacenter operator_.
- Application developer role
1. Will have only access to the applications that run. 
2. By default, the apps are gonna running in a default isolated region created by default for a specific application developer. For instance: _default-region_
3. Are able to create new isolated regions inside his _default-region_
4. Modify the application list view to group applications by regions in application developer profile.
5. Add a new option in the Application create view to allow select a region where the app are gonna running (allays available region by  _default-region_)
6. attached an approach 
   ![prueba3](https://cloud.githubusercontent.com/assets/11392338/14462256/75fb2696-00c6-11e6-96ea-cc2520cccbcb.png)
   ![prueba4](https://cloud.githubusercontent.com/assets/11392338/14462257/7616afb0-00c6-11e6-91f0-c7c33561fdf5.png)
   ![prueba copy](https://cloud.githubusercontent.com/assets/11392338/14462258/763ece5a-00c6-11e6-93b0-81fa3831034c.png)
- Datacenter operator role
1. Will have a full access
2. Are able to admin every region in Marathon
3. Are able to create new users
4. Will need a “Create user view” to signup new users
5. When a new user is created a new isolated region is created for this user

What do you mean about it? Is there similar feature described in other issue? 
I didn't find something like this....

related with #3745

**Comment by pierlo-upitup** [comment]
cc @air

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2048. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
