### ISSUE TITLE
Isolated regions / Per Container IP - impact on marathon API

### ISSUE THREAD

**Issue by robfrut135** [mesosphere/marathon#3745]
Hi, 
I was reading this doc. about "Per-Container IP" and related with #3744 

https://docs.google.com/document/d/17mXtAmdAXcNBwp_JfrxmZcQrs7EO6ancSbejrqjLQ0g/edit  

It'd be really useful add to the API something like this to manage the described feature

**10 Impact on Marathon API**

It will be needed new endpoints in the Marathon API  (an approach)

v3/users/                 [GET|PUT|POST]
v3/users/{userId}               [GET|PUT|DELETE]
v3/users/{userId}/regions/        [GET|DELETE]
v3/users/{userId}/regions/apps/     [GET|DELETE]
v3/users/{userId}/regions/groups/       [GET|DELETE]

v3/regions/                 [GET|PUT|POST]
v3/regions/{regionId}               [GET|PUT|DELETE]
v3/regions/{regionId}/apps/        [GET|DELETE]
v3/regions/{regionId}/groups/         [GET|DELETE]

What do you mean about it? Is there similar feature described in other issue? 
I didn't find something like this....

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2098. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
