### ISSUE TITLE
No way to delete persistent volumes for an application instance

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#3748]
I have a task for which I only want one persistent volume (I realized the high-availability issues with this statement). Marathon created two volumes on the same host, causing it so that each time this instance is restarted, the persistent volume attached is alternated, which is very undesirable.

http://screencast.com/t/ZP1kepqZ6k9k

Running Marathon `v1.1.0RC1`, Mesos `0.28.0`

**Comment by aquamatthias** [comment]
Hey @timcharper thanks for the report.

It looks like there are 2 tasks known to Marathon, but the current instance count is 1.
This is normal if you ever had an instance count of 2.
I guess you scaled your application to 2 instances in the past?
If you downscale your application, the task data and the volume will remain.
If the running task dies, Marathon picks one of the unlaunched tasks and launches that.
I guess this leads to the alternate behavior you describe.
We will try to fix this, by giving the unlaunched tasks an order.

You can kill a task and also wipe the reservation with the volume by using 
```
POST /v2/tasks/delete?wipe=true

{
    "ids": [
        "task.a21cb64a-b5eb-11e4-a4f4-685b35c8a22e"
    ]
}
```
Does this solve the problem?

**Comment by pierlo-upitup** [comment]
Related https://github.com/mesosphere/marathon/issues/3658

**Comment by pierlo-upitup** [comment]
Also related https://github.com/mesosphere/marathon/issues/3657

**Comment by timcharper** [comment]
@aquamatthias in this case, I always intended to have one, and never scaled it up to two. The app allocated an additional persistent volume when I restarted the container after adding a health check to the container. (I was about to report this issue, too, but I'm not able to reproduce it with the latest RC!)

I tried hitting that endpoint; this was the output:

```
$ curl -v -X POST http://leader.mesos:8080/v2/tasks/delete?wipe=true -d '{"ids":["docker-registry.551ece24-f68a-11e5-a061-ced3864efcb8"]}'; echo
* About to connect() to leader.mesos port 8080 (#0)
*   Trying 172.30.31.53...
* Connected to leader.mesos (172.30.31.53) port 8080 (#0)
> POST /v2/tasks/delete?wipe=true HTTP/1.1
> User-Agent: curl/7.29.0
> Host: leader.mesos:8080
> Accept: */*
> Content-Length: 64
> Content-Type: application/x-www-form-urlencoded
>
* upload completely sent off: 64 out of 64 bytes
< HTTP/1.1 415 Unsupported Media Type
< Date: Tue, 12 Apr 2016 21:27:19 GMT
< Server: Jetty(9.3.z-SNAPSHOT)
< Cache-Control: no-cache, no-store, must-revalidate
< X-Marathon-Leader: http://172.30.31.51:8080
< Expires: 0
< Pragma: no-cache
< Date: Tue, 12 Apr 2016 21:27:19 GMT
< Content-Type: application/json
< X-Marathon-Via: 1.1 172.30.31.53:8080
< Transfer-Encoding: chunked
<
* Connection #0 to host leader.mesos left intact
{"message":"Unsupported Media Type"}
```

**Comment by timcharper** [comment]
@aquamatthias in this case, I always intended to have one, and never scaled it up to two. The app allocated an additional persistent volume when I restarted the container after adding a health check to the container. (I was about to report this issue, too, but I'm not able to reproduce it with the latest RC!)

The api call you suggested worked!

```
$ curl -v -X POST http://leader.mesos:8080/v2/tasks/delete?wipe=true -d '{"ids":["docker-registry.551ece24-f68a-11e5-a061-ced3864efcb8"]}' -H "Content-Type: application/json"; echo
* About to connect() to leader.mesos port 8080 (#0)
*   Trying 172.30.31.53...
* Connected to leader.mesos (172.30.31.53) port 8080 (#0)
> POST /v2/tasks/delete?wipe=true HTTP/1.1
> User-Agent: curl/7.29.0
> Host: leader.mesos:8080
> Accept: */*
> Content-Type: application/json
> Content-Length: 64
>
* upload completely sent off: 64 out of 64 bytes
< HTTP/1.1 200 OK
< Date: Tue, 12 Apr 2016 21:28:47 GMT
< Server: Jetty(9.3.z-SNAPSHOT)
< Cache-Control: no-cache, no-store, must-revalidate
< X-Marathon-Leader: http://172.30.31.51:8080
< Expires: 0
< Pragma: no-cache
< Date: Tue, 12 Apr 2016 21:28:47 GMT
< Content-Type: application/json; qs=2
< X-Marathon-Via: 1.1 172.30.31.53:8080
< Transfer-Encoding: chunked
<
* Connection #0 to host leader.mesos left intact
{"tasks":[{"id":"docker-registry.551ece24-f68a-11e5-a061-ced3864efcb8","slaveId":"ec3fca08-b678-421a-80fb-665881f2a4d9-S1","host":"sw-analytics45.vivintsky.com","localVolumes":[{"containerPath":"storage","persistenceId":"docker-registry#storage#551ece23-f68a-11e5-a061-ced3864efcb8"}],"appId":"/docker-registry"}]}
```

**Comment by timcharper** [comment]
I'll close this out and open up a feature request instead.

**Comment by timcharper** [comment]
It seems it'd make sense to add the wipe parameter to the `/v2/apps/{app_id}/tasks` `DELETE` api call, and it would be nice to have a way to do this same thing via the Marathon UI.

**Comment by aquamatthias** [comment]
@timcharper 
1) cool that it worked
2) the launch of another task during an upgrade deployment was a bug, that was fixed with 1.1
3) we will add documentation for this flag

**Comment by timcharper** [comment]
I just used this feature today from Marathon UI 1.1.0-RC2 and it worked!

**Comment by aquamatthias** [comment]
Great.
