### ISSUE TITLE
App creation modal doesn't open on connection errors, silently

### ISSUE THREAD

**Issue by aldipower** [mesosphere/marathon#3757]
If I have a connection error on the info-endpoint, the app creation modal doesn't open silently without an warning.

At least an error alert should be faced, that the endpoint isn't reachable.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2150. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
