### ISSUE TITLE
Facing Privilege Issues Even Though When Set The Parameter To True

### ISSUE THREAD

**Issue by varkolli** [mesosphere/marathon#3766]
My deployments are failing with permissions denied issues even though when set Privilege to TRUE via Marathon API /v2/apps. I am trying to access the file which is inside the container.
When I tried this through CLI on one of the worker nodes without any privileges set, I was able to access. But I am seeing issues only while doing it from the Marathon API

Marathon Version : Version 0.13.0
Mesos Version : 0.25.0.

**Comment by pierlo-upitup** [comment]
Hi @varkolli 

could you please paste the JSON application definition for the the app that's causing the issue? Thanks.

**Comment by varkolli** [comment]
Hello There,

Very Good Morning,

Thanks for your reply. Please see the payload below ..

{
  "id": "/registration151",
  "cmd": "/Jars/common-service.jar",
  "instances": 1,
  "cpus": 0.5,
  "mem": 4096,
  "disk": 0,
  "executor": "",
  "constraints": [],
  "uris": [],
  "storeUrls": [],
  "ports": [
    5000
  ],
  "requirePorts": false,
  "backoffSeconds": 1,
  "backoffFactor": 1.15,
  "maxLaunchDelaySeconds": 3600,
  "container": {
    "type": "DOCKER",
    "volumes": [
      {
        "containerPath": "/docker_storage",
        "hostPath": "/hdd/tools/docker/registry",
        "mode": "RW"
      }
    ],
    "docker": {
      "image": "xyz.com/xyz/common-service:latest",
      "network": "BRIDGE",
      "portMappings": [
        {
          "containerPort": 1111,
          "hostPort": 0,
          "servicePort": 0,
          "protocol": "tcp"
        }
      ],
      "privileged": true,
      "parameters": [],
      "forcePullImage": false
    }
  },
  "healthChecks": [],
  "dependencies": [],
  "upgradeStrategy": {
    "minimumHealthCapacity": 1,
    "maximumOverCapacity": 1
  },
  "version": "2015-08-19T21:26:47.616Z"
}



Thanks
Varun
408 525 5943

" You can't just ask the customers what they want and then try to give that to them. By the time you get it built, they'll want something new" - Steve Jobs.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2582. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
