### ISSUE TITLE
Cannot delete "cmd" / Command property of Docker job once set

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#3767]
Recorded screencast showing the issue:

http://screencast.com/t/qOKPQHCmM

This bug seems to be in multiple places; if I delete the `cmd` key altogether from the JSON payload, and click post, then `PUT` is issued with `{}` (absolutely no changes). If I set the `cmd` key to `null` or wipe it out in the friendly UI, then `PUT` is issued with `{cmd: null}` but marathon ignores it.

Reproducible in Marathon 1.1.0-RC2. Here's the application description:

```
{
  "id": "/influxdb",
  "cmd": "start",
  "cpus": 0.25,
  "mem": 256,
  "disk": 0,
  "instances": 1,
  "container": {
    "type": "DOCKER",
    "volumes": [],
    "docker": {
      "image": "registry.weave.local:5000/influxdb",
      "network": "BRIDGE",
      "portMappings": [
        {
          "containerPort": 0,
          "hostPort": 0,
          "servicePort": 10001,
          "protocol": "tcp",
          "labels": {}
        }
      ],
      "privileged": false,
      "parameters": [
        {
          "key": "hostname",
          "value": "influxdb.weave.local"
        },
        {
          "key": "net",
          "value": "weave"
        }
      ],
      "forcePullImage": false
    }
  },
  "portDefinitions": [
    {
      "port": 10001,
      "protocol": "tcp",
      "labels": {}
    }
  ]
}
```

**Comment by pierlo-upitup** [comment]
Hi @timcharper,
first of all thanks for taking the time to record these screencasts – they help a lot!

Regarding the first issue (deleting the `cmd` property from the JSON editor entirely) I would argue that the correct way to "unset" the value is indeed to set that property to `null`. This tells Marathon that the previous value should be mutated to the newly sent one, in this case `null`. I'm not sure I agree that the UI should detected `undefined` properties and convert those to `null`. After all, `cmd` is actually an optional field.

When you switch back to the graphical editor, you saw that when erasing a previously entered `cmd` the UI actually sets it to `null`. That's correct.

However, it seems like the service layer silently ignores the change and fails to trigger a new deployment with the computed differences. 

Passing this to @aquamatthias for more insights.

**Comment by pierlo-upitup** [comment]
After talking to @aquamatthias it seems like the `PUT` operation is unable to process the un-setting of a previously specified value (as is the case in the reported issue). This is not exactly a bug, so I'm removing the label. 

A workaround to solve the problem would be to deploy a new application with the correct configuration and to destroy the previous one.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2329. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
