### ISSUE TITLE
Provide working example for VIP routing

### ISSUE THREAD

**Issue by meichstedt** [mesosphere/marathon#3779]
Please provide a working example (tutorial/deep dive) for [VIP routing](https://mesosphere.atlassian.net/browse/DOCS-742)

This may be integrated into the [DC/OS docs](https://github.com/dcos/dcos-docs), but it should at least be a part of the Marathon documentation.

An example of a deep dive can be found here: https://github.com/dcos/dcos-docs/pull/66

_Note: this should be done by eod 04/15_

**Comment by gkleiman** [comment]
Here's an app definition using port mappings:

```json
{
  "id": "/server",
  "cmd": "python -m SimpleHTTPServer 80",
  "cpus": 1,
  "mem": 128,
  "disk": 0,
  "instances": 1,
  "container": {
    "docker": {
      "image": "python:2.7-alpine",
      "network": "BRIDGE",
      "portMappings": [
        {
          "containerPort": 80,
          "protocol": "tcp",
          "name": "http",
          "labels": {
            "VIP_0": "192.168.0.100:80"
          }
        }
      ]
    },
    "type": "DOCKER"
  }
}
```

**Comment by air** [comment]
Also see https://github.com/dcos/dcos-vagrant/blob/master/examples/minuteman/README.md
