### ISSUE TITLE
Provide working example for External Volumes

### ISSUE THREAD

**Issue by meichstedt** [mesosphere/marathon#3780]
Please provide a working example (tutorial/deep dive) for [External Volumes](https://mesosphere.atlassian.net/browse/MARATHON-876)

This may be integrated into the [DC/OS docs](https://github.com/dcos/dcos-docs), but it should at least be a part of the Marathon documentation.

An example of a deep dive can be found here: https://github.com/dcos/dcos-docs/pull/66

_Note: this should be done by eod 04/15_

**Comment by aquamatthias** [comment]
Documentation is here: https://mesosphere.github.io/marathon/docs/external-volumes.html
