### ISSUE TITLE
Provide working example for Marathon Auth

### ISSUE THREAD

**Issue by meichstedt** [mesosphere/marathon#3781]
Please provide a working example (tutorial/deep dive) for [Marathon Auth](https://mesosphere.atlassian.net/browse/DOCS-760)

This may be integrated into the [DC/OS docs](https://github.com/dcos/dcos-docs), but it should at least be a part of the Marathon documentation.

An example of a deep dive can be found here: https://github.com/dcos/dcos-docs/pull/66

_Note: this should be done by eod 04/15_

**Comment by aquamatthias** [comment]
See PR here: https://github.com/mesosphere/wp-gh-test/pull/47

**Comment by four2five** [comment]
@aquamatthias that link 404s

**Comment by air** [comment]
Looks like we documented the format, but didn't give any working examples.
I think we should show
- How to set up a path for a single team, `/eng/webteam`
- How to set up a path for a individual user, `/home/alice`

**Comment by aquamatthias** [comment]
Example Plugin is here: https://github.com/mesosphere/marathon-example-plugins/tree/master/auth
