### ISSUE TITLE
Healthcheck in app groups

### ISSUE THREAD

**Issue by sjkyspa** [mesosphere/marathon#3784]
Hi all, When I define the marathon request blow, Did the marathon will start the```api``` after the ```db``` is health?
Thanks in advance 

```
{
  "id": "controller",
  "apps": [
    {
      "id": "db",
      "cpus": 0.2,
      "mem": 256,
      "instances": 1,
      "container": {
        "type": "DOCKER",
        "docker": {
          "image": "tutum/mysql",
          "network": "BRIDGE",
          "portMappings": [
            { "containerPort": 3306 }
          ]
          ]
        }
      },
      "healthChecks": [
        {
          "protocol": "TCP",
          "gracePeriodSeconds": 3,
          "intervalSeconds": 2,
          "portIndex": 0,
          "timeoutSeconds": 5,
          "maxConsecutiveFailures": 3
        }
      ]
    },
    {
      "id": "api",
      "cpus": {{ .cpus }},
      "mem": {{ .mem }},
      "instances": 1,
      "container": {
        "type": "DOCKER",
        "docker": {
          "image": "{{ .image }}",
          "network": "BRIDGE",
          "portMappings": [
            { "containerPort": 8088, "hostPort": 0 }
          ]
        }
        ]
      },
      "dependencies": ["/controller/db"],
      "healthChecks": [
         {
           "path": "/",
           "portIndex": 0,
           "protocol": "HTTP",
           "gracePeriodSeconds": 120,
           "intervalSeconds": 2,
           "timeoutSeconds": 3
         }
      ]
    }
  ]
}
```

**Comment by Poltergeist** [comment]
Hi @sjkyspa,

As written in the [docs](https://mesosphere.github.io/marathon/docs/rest-api.html#post-v2-apps) 
> dependencies (Array of Strings)

> A list of services upon which this application depends. An order is derived from the dependencies for performing start/stop and upgrade of the application. For example, an application /a relies on the services /b which itself relies on /c. To start all 3 applications, first /c is started than /b than /a.

Your application `api` will start after the `/controller/db` application is started. Following my knowledge the api should start after the healthchecks pass for the `db`

**Comment by aquamatthias** [comment]
Please reopen, if it does not work as expected
