### ISSUE TITLE
Marathon UI doesn't always automatically update the status of tasks

### ISSUE THREAD

**Issue by vishnu2kmohan** [mesosphere/marathon#3786]
A manual refresh is still required.

Reproducible on version 1.1.1 (Note: The keyboard shortcut `g v` states the version as 1.1.2)

Steps to reproduce:

dcos package install hdfs
dcos package install cassandra
dcos package install kafka
dcos package install jenkins

dcos package install _your favorite DCOS service with a complex health check_

**Comment by pierlo-upitup** [comment]
Can you please add more details regarding the expected task status and the actual results you're seeing? Many thanks.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2137. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
