### ISSUE TITLE
Provide support for Docker user-defined networks

### ISSUE THREAD

**Issue by BostonDriver** [mesosphere/marathon#3788]
Marathon doesn't allow docker user-defined networks to be used.  Mesos added this support via [https://issues.apache.org/jira/browse/MESOS-4369](url).  Example json showing how to specify the user-defined network will also help.

**Comment by andrewkrug** [comment]
I would second this as a feature I actually need today.  The ability to call docker on a marathon application build and create network overlays at the same time would be handy.  Use cases that come to mind would be launching all containers in an app into an on the fly created calico net.

**Comment by BostonDriver** [comment]
I looks like this is also needed for mesos unified containers as well as docker.

**Comment by andrewkrug** [comment]
Any one have anything to report on asking for this feature?  I've got to write an interface for this and I'd love to find a workaround.

**Comment by xiaods** [comment]
we can use marathon docker parameter to  --net=customernet

**Comment by jdef** [comment]
marathon now supports docker user networks. use docker network type USER and ipAddress.networkName=the-name-of-your-user-network

**Comment by vitan** [comment]
@jdef  , so the user story suggests:

1. create the user-defined network somewhere outside of the mesos/marathon
2. call the marathon interface with params: docker network type&ipAddress sth.

doesn't it?

**Comment by jdef** [comment]
yes that sounds about right

**Comment by LiginGeorge** [comment]
Hi,

Just posting this because i am new to mesos/marathon. I have created userdefined network in my slave server, i didn't understand the format which should keep in json
root@i:~# docker network ls
NETWORK ID          NAME                DRIVER              SCOPE
a295ac6220c1        dcmadm_default      bridge              local

root@i:~# docker network inspect dcmadm_default
[
    {
        "Name": "dcmadm_default",
        "Id": "a295ac6220c14d876fcf89aa92352fd5fc9c81720804d380f73620fd0d1b0e15",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.19.0.0/16",
                    "Gateway": "172.19.0.1"
                }
            ]
        },
        "Internal": false,
        "Containers": {},
        "Options": {},
        "Labels": {}
    }
]

What format should i use in network field below in json file.
"network": "BRIDGE", (by default)

**Comment by AlexShemeshWix** [comment]
+1
