### ISSUE TITLE
Marathon UI causes Chrome to lock up or really slow down when switching to JSON edit mode and back

### ISSUE THREAD

**Issue by vishnu2kmohan** [mesosphere/marathon#3789]
This is particularly noticeable when attempting to edit an application like `marathon-lb`

**Comment by pierlo-upitup** [comment]
Hi @vishnu2kmohan – could you provide more details please? 
1. Which version of Marathon UI are you experiencing this with? (type `g v` in the Applications page to find out)
2. It would be great if you could paste the JSON for the application config that's causing the issue.

With a vanilla `marathon-lb` app config I was not able to reproduce in 1.1.2

**Comment by JonnyBGod** [comment]
I am getting this behavior with marathon 1.1.1.
For some reason this happens from time to time.

ENV:
Vagrant on OSX macbook pro 16gb ram
Small dcos cluster
Marathon 1.1.1
vanilla marathon-lb

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1705. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
