### ISSUE TITLE
Marathon UI change tracking while in edit mode appears to be finicky

### ISSUE THREAD

**Issue by vishnu2kmohan** [mesosphere/marathon#3790]
Say I have an app configured to spawn `/usr/bin/python3 -m http.server $PORT0` and I attempt to edit it and type `python:3` in the value field for the docker image (or just make a plain old typo) that I back out of and reset the value and then proceed to make a change where I actually intended, the UI will still think that I wanted a Docker image which you can detect if you switch to JSON mode where you'll see that it filled out an empty skeleton that fails validation when I attempt to apply the change that I originally intended. In this state I won't be able to apply or save my changes and am forced to cancel and redo it from scratch.

**Comment by adyatlov** [comment]
This screen-cast shows another way to reproduce the issue. If you switch to JSON mode in the configuration dialog afterwards, you'll see that the container type was changed to DOCKER.
https://drive.google.com/a/mesosphere.io/file/d/0Bye3Wj7an4bDWEIwZ29makpCcG8/view
