### ISSUE TITLE
Wrong application status

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#3793]
![](https://cloud.githubusercontent.com/assets/647035/14603443/ebe94b8e-056d-11e6-8eeb-ef90daa58e87.png)
![](https://cloud.githubusercontent.com/assets/647035/14603521/7f45ee96-056e-11e6-810b-17024a57d129.png)
An application with 0 running instances but configured to run  at least one instance should never appear as suspended but as waiting.

**Comment by pierlo-upitup** [comment]
Having a hard time reproducing this. Can you think of what could have triggered the Suspened in the screenshot above?

**Comment by pierlo-upitup** [comment]
According [to the source code](https://github.com/mesosphere/marathon-ui/blob/master/src/js/stores/AppsStore.js#L159), we only ever set `SUSPENDED` if the app has no deployments and 0 instances and 0 tasks.
