### ISSUE TITLE
use explicit path in error messages

### ISSUE THREAD

**Issue by vixns** [mesosphere/marathon#3796]
`{"message":"Object is not valid","details":[{"path":"/groups(1)/groups(0)/apps(0)/container/docker/portMappingsvalue(0)/name","errors":["must fully match regular expression '^[a-z0-9-]+$'"]}]}`

makes really hard to guess which app raise the error. It should contains explicit groups/apps names instead of `groups(x)/apps(x)`

**Comment by pierlo-upitup** [comment]
I believe this PR will deliver a much more usable validation message https://github.com/mesosphere/marathon/pull/3741

Please re-open otherwise
