### ISSUE TITLE
Marathon should surface a message in the UI if it is unable to register with a master

### ISSUE THREAD

**Issue by ssk2** [mesosphere/marathon#380]
Not sure how exactly this works, but I failed to connect my local Marathon instance to a Mesos master running on AWS. Figured out that it was unable to receive the registration handshake by looking at the master's logs. We should make this visible in the UI.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3771. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
