### ISSUE TITLE
Host-to-container volume mapping in Marathon 1.1

### ISSUE THREAD

**Issue by liquid-sky** [mesosphere/marathon#3804]
Since upgrading to Marathon 1.1, I don't see an option in GUI to map host path to Docker container path (as usually submitted with docker `--volume` flag). 

Since my applications are still running, I assume that json way still works:

```
...
  "volumes": [
    {
      "containerPath": "/data/hadoop",
      "hostPath": "/opt/data/hadoop",
      "mode": "RW"
   }
 ]
...
```

Is there a plan to discontinue support for volume mappings? 

GUI volume config:
<img width="732" alt="screen shot 2016-04-19 at 13 07 20" src="https://cloud.githubusercontent.com/assets/3029571/14638590/d92fe346-062f-11e6-8a54-61afd2a95303.png">

If submitted via JSON:
<img width="730" alt="screen shot 2016-04-19 at 13 07 44" src="https://cloud.githubusercontent.com/assets/3029571/14638600/e0dbc722-062f-11e6-9387-f0abb987ff67.png">

Relevant? :-)
![workflow](https://cloud.githubusercontent.com/assets/3029571/14638186/0bdd8a84-062e-11e6-9770-3fb95eea0fe4.png)

**Comment by pierlo-upitup** [comment]
Hi @liquid-sky 

we didn't remove the spacebar heating 😉  simply make sure you specify a docker image first in the `Docker Container` settings to access the docker volume settings.

**Comment by pierlo-upitup** [comment]
@leemunroe we should consider adding a tooltip or some sort of information in the Volumes section mentioning that you need to specify a docker image first to have access to the docker volumes.

**Comment by sttts** [comment]
Show the volume widgets, but make them disabled with a tooltip "only available for Docker containers".

**Comment by liquid-sky** [comment]
Ahh, just noticed that the section appears when docker image name is entered. Thanks, folks!

**Comment by leemunroe** [comment]
@sttts solution sounds good. Something like "First configure your Docker container" and link to the section.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1884. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
