### ISSUE TITLE
[UI] escaped chars rewrite 

### ISSUE THREAD

**Issue by vixns** [mesosphere/marathon#3809]
When using the config editor and pasting labels values containing newlines (typical use: marathon-lb templates),

```
test\n test
 test
```

should become `test\n test\n test` in the JSON, but is `test\\n test  test`

(the \ is escaped and the newline is converted to space on paste ).

Workaround : always use the JSON editor when having escaped chars.

**Comment by pierlo-upitup** [comment]
Hmm if you're talking about labels, thats due to the HTML input field being of type `text`– which does not allow for newlines. In this case we might have to change to a textarea.

**Comment by vixns** [comment]
Yes, it's about labels, double escaping `\n` or `\t`should be avoided.

what about a parsed/raw format toggle option on each value field, that switch between `text` and `textarea` ?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1701. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
