### ISSUE TITLE
COMMAND health check on Docker seems to have problems with subshells

### ISSUE THREAD

**Issue by valentinomiazzo** [mesosphere/marathon#3810]
Mesos: 0.27.1
Marathon: 0.14.0
Docker: 1.7.1

I created a docker app based on bobrik/collectd-mesos and wanted to add and health check.
I though something like `[ $(netstat -ntp | grep collectd | wc -l) -eq 1 ]` could work.
In fact I tested it by attaching to the docker container with `docker exec -it <hash> sh` and it worked.

But... when I put the command in Marathon it didn't.
I tried to pin the problem and it seems there is something strange when using subshells.
For example this check `echo "$(ps aux)" ; true` prints just `USER` in the stderr log.

I tried different approaches like `cmd | while read x ; ... ` or `cmd | xargs test ...` but none of them worked.

**Comment by gkleiman** [comment]
@valentinomiazzo Marathon delegates the command health checks to Mesos, so you might be able to find more useful help in their Jira: https://issues.apache.org/jira/browse/mesos
