### ISSUE TITLE
Indeterminate progress bars during deployment make debugging difficult

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3811]
So alright, some tasks are stuck in staging. I see which groups are effected.

![screen shot 2016-04-20 at 13 38 31](https://cloud.githubusercontent.com/assets/339354/14673257/38ff2ea8-06fd-11e6-8fc5-328eb2180e29.png)

Now I entered the group. But I don't see the task states in the progress bar anymore:

![screen shot 2016-04-20 at 13 35 22](https://cloud.githubusercontent.com/assets/339354/14673205/ce734736-06fc-11e6-9805-1b137caba7c2.png)

I would simply like to have the same info on app level as I have on group level in the progress bar.

Funny enough, the information is shown in the tooltip but not in the bar:

![screen shot 2016-04-20 at 13 39 11](https://cloud.githubusercontent.com/assets/339354/14673277/5840f90e-06fd-11e6-98f5-e3eac78a03e3.png)

I remember that this was done on purpose but I really think that we made the wrong choice here.

/cc @leemunroe

**Comment by leemunroe** [comment]
Is it the color that is confusing? i.e. we're using stripes to indicate staged in one view, and yellow in another

Would you expect something more like this (quickly mocked up)?
![image](https://cloud.githubusercontent.com/assets/15963/14676309/c2b2e9b4-06c1-11e6-8d1d-95476678ac06.png)

**Comment by kolloch** [comment]
I am not quite sure that I get your point.

Yes, it is strange to use different colors in different views. And, as you can see in the screenshot, at the app list level there was no visual distinction between staged tasks and "unknown health" tasks in the bar at all.

**Comment by kolloch** [comment]
(and the yellow color looks much more distinct than gray stripes vs opaquely gray. That might be different for color blind people though, so you might want to distinguish by color and by pattern.)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1939. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
