### ISSUE TITLE
Dependencies Not working

### ISSUE THREAD

**Issue by ashishsoni** [mesosphere/marathon#3814]
I am trying below JSON where one of the dependencies doesn't exist but marathon still start all the three application , Is this a bug

for the service-a i added a dependencies which is not declared so it should fail the deployment or wait but it ends up starting all 3 application

```
{
  "id": "department-b",
  "apps": [
    {
      "id": "service-common",
      "cpus": 0.1,
      "mem": 32,
      "ports": [0],
      "cmd": "python -m SimpleHTTPServer $PORT0",
      "instances": 1
    }
  ],
  "groups": [
    {
      "id" : "product-a",
      "apps":[
        {
          "id": "service-a",
          "cpus": 0.1,
          "mem": 32,
          "ports": [0],
          "cmd": "python -m SimpleHTTPServer $PORT0",
          "instances": 1,
          "dependencies": [
            "missingdependencies"
          ]
        },
        {
          "id": "service-b",
          "cpus": 0.1,
          "mem": 32,
          "ports": [0],
          "cmd": "python -m SimpleHTTPServer $PORT0",
          "instances": 1,
          "dependencies": [
            "/department-b/product-a/service-a"
          ]
        }
      ]
    }
  ]
}
```

**Comment by pierlo-upitup** [comment]
cc @gkleiman

**Comment by pierlo-upitup** [comment]
Hi @ashishsoni can you provide which versions of Marathon and Mesos you're running this on?

**Comment by ashishsoni** [comment]
Hi , 
I am using marathon:v1.1.1 and mesos 0.27.1-2.0.226
Ashish

**Comment by aquamatthias** [comment]
The way dependencies work in Marathon:
- all applications that are available under the defined path are dependencies of this app
- A DAG is build from the dependencies, that are resolved during deployment time
- if you don't have any app under this path, then the list of dependent apps is empty.

See details here: https://mesosphere.github.io/marathon/docs/application-groups.html

**Comment by jzampieron** [comment]
Are there any plans to expand the behavior? There are certain complex deployment scenarios where its desirable to be able to refer to a dependency by path alone. 

One example is installing Cassandra from the CLI because you can't put it in a group due to a bug in the deployment scripts.

**Comment by jasongilanfarr** [comment]
Long term, we do intend on expanding the behavior, if you could enumerate the exact use case, it would be very helpful.

**Comment by jzampieron** [comment]
Here's the concept: We have a set of microservices that we run on DCOS. We use both custom dockerized microservices (our own) and some standard DCOS services/containers (i.e. Cassandra, Marathon-LB, Let's Encrypt). We'll be adding Spark, Concord, Zeppelin, Kafka and possibly others shortly. 

There are dependencies between the services and things need to come up in a particular order and be healthy. 

What caused me to find this was one of our services deploying itself while Cassandra was still deploying b/c it didn't honor the whole path to cassandra, even though it was listed in the dependencies list for that particular app. 

b/c of an issue with the Cassandra json options, it won't let you specify a proper group type path, i.e. /companyname/deploymentname/cassandra -> this fails. So we use /companyname-cassandra-deploymentname instead, which is outside the overall group, but still namespaced for uniqueness.

To add another level of complexity its also possible that there could be multiple instances of this service set within a single DCOS cluster. 

We use the following group structure to organize this:

/companyname/deploymentname/{common services, i.e. lb-private, lb-public, letsencrypt}
/companyname/deploymentname/backend/{backend services}
/companyname/deploymentname/frontend{frontend services}

The desire it to be able to capture the entire dependency structure and just one-shot roll out the whole thing from scratch. Right now, there's some shell script magic to deal with the Cassandra schema.

It would be good to allow the user to specify the entire DAG via the dependencies element and the typical / based paths anywhere within the cluster that they have permissions to view. 
You'll obviously need some kind of loop detection in case someone goofs up the json specs.

Some thought will be needed on how to handle shared instances of services, where a database has multiple keyspaces or databases used by totally disparate applications that have no knowledge of each other.

Was that a good explanation? I can expand if needed.
