### ISSUE TITLE
Logic for using quotes around variables

### ISSUE THREAD

**Issue by cookandy** [mesosphere/marathon#3815]
Hello,

I have a marathon deployment script which sets some `ENV` vars, as shown below:

```
"env": {
   "NEW_RELIC_APP_NAME" : "MyApp",
   "NEW_RELIC_HOST_DISPLAY_NAME" : "${HOST}"
   "NEW_RELIC_LICENSE_KEY" : "xxx",
   "NEW_RELIC_LOG" : "STDOUT",
}
```

You can see that each of the variables uses quotes around the value (to satisfy the json requirement).  

However, when the container starts, I notice that the `NEW_RELIC_APP_NAME` and `NEW_RELIC_HOST_DISPLAY_NAME` variables have single `'` marks around them, which causes the `$HOST` variable to not expand.  The other two variables don't have this:

```
NEW_RELIC_APP_NAME='MyApp'
NEW_RELIC_HOST_DISPLAY_NAME='${HOST}'
NEW_RELIC_LICENSE_KEY=xxx
NEW_RELIC_LOG=STDOUT
```

Can someone tell me how this happens?

**Comment by pierlo-upitup** [comment]
Hi @cookandy 

environment variables are simple key-value string pairs at the moment. 

There is already an issue to keep track of this feature request here https://github.com/mesosphere/marathon/issues/1828 and here https://github.com/mesosphere/marathon/issues/2679.

Thanks for your feedback!
