### ISSUE TITLE
could marathon UI support update app group?

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#3816]
like this :
![6897e0be-07cb-11e6-85b2-56d4c3dbf04f](https://cloud.githubusercontent.com/assets/6802322/14699593/a1cfd08a-07cb-11e6-85a8-09e1e9566858.png)

add edit/update interface
thanks！

**Comment by pierlo-upitup** [comment]
Hi @junneyang 

modifying a group id will trigger a re-deployment for each of the app within that group.  For that reason, we decided to not surface this action in the UI at the moment. 

We might re-assess this decision at some point.
Thanks for your feedback!

**Comment by junneyang** [comment]
@pierlo-upitup 
tnanks
i think we should popup warnings for that,
but we should not refuse to provide such valuable feature.

**Comment by pierlo-upitup** [comment]
cc @leemunroe

**Comment by leemunroe** [comment]
Thanks @junneyang - can you confirm what it is you wanted to edit/update in your use case? Wondering if it was the ID or if there is more to it.

**Comment by junneyang** [comment]
i suggest all configurations of the group could be updated, like the app's update:
![qq 20160510094753](https://cloud.githubusercontent.com/assets/6802322/15133326/530986ee-1694-11e6-81f8-6ae1272be5be.png)
 
i also suggest the UI could be simplify for group update.
just let user modify the group's JSON defination is OK.

thanks!

**Comment by linsheng9731** [comment]
+1 
sometimes , i need to modify the group's name. if marathon ui support simple function to update group info is better !

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2379. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
