### ISSUE TITLE
How to pass parameter to main.yml from marathon container?

### ISSUE THREAD

**Issue by dmilind** [mesosphere/marathon#3818]
I have marathon container on ubuntu 14.04. and I have ansible-marathon role in configuration file. In main.yml file of ansible-marathon role I need some parameters for
 command: and volume: modules.  So my question is how we can pass them to the container.? For the broader view. 

this is yml file what values should come in the highlighted place.

- name: pull latest version of marathon container
  shell: "docker pull  {{mesosphere}}//marathon:{{V0.15.3}}"
  tags : install
- name: starting marathon
    docker:
    image: {{mesosphere}}//marathon:{{V0.15.3}}
    name : marathon
    command: "                 "
    state : reloaded 
    restart_policy:always
    hostname: "{{ansible_eth0.ipv4.address}}"
    volumes: "{{     }}"

tags:
   - config
   - restart

**Comment by aquamatthias** [comment]
Several ways to do this:
- use the file /etc/default/marathon/marathon.defaults 
- use environment variables
- change the script that starts marathon.

For details see here: https://mesosphere.github.io/marathon/docs/command-line-flags.html
