### ISSUE TITLE
does marathon support using environment variables for service discovery?

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#3819]
mesos-dns just for the app's host discovery,
how about the app's hostPort?

thanks!

**Comment by aquamatthias** [comment]
No support for service discovery via env variables.

mesos-dns can give you the information about the port as well.
But keep in mind, this would be a DNS SRV record instead of an A record.

See https://mesosphere.github.io/marathon/docs/service-discovery-load-balancing.html
