### ISSUE TITLE
Use a real database instead of ZooKeeper as persistent storage

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#3826]
thanks

**Comment by shijinkui** [comment]
dependency on rdb is not good idea.  no-sql and file are easy. column type is not force to provide.

**Comment by aquamatthias** [comment]
@junneyang I changed the title to explain the enhancement.
To answer your original question: we have plans to support other data stores.
ZooKeeper is at the moment a minimal requirement.

**Comment by jasongilanfarr** [comment]
We may eventually address this; however, its not in the scope for the time being. We dramatically improved the storage layout within Zookeeper and there is a longer term task to replace it.
