### ISSUE TITLE
use sbt-native-package?

### ISSUE THREAD

**Issue by shijinkui** [mesosphere/marathon#3838]
using `bin/start` script to find the main function and then start application.
Why not use [sbt-native-package](http://www.scala-sbt.org/sbt-native-packager/index.html) to pacakge, and let the os to manage marathon application on runtime.

universal format mey be more clear to the project code.

thanks

**Comment by aquamatthias** [comment]
Hey @shijinkui the start script allows this:
- it translates env vars into command line flags
- it reads from /etc/default/marathon/marathon.defaults on linux systems
- this functionality is available on the system and also inside Docker containers

Do you think the native packager can do this as well?
What are the advantages?

**Comment by shijinkui** [comment]
os manage the service will be the right thing, such as building  rpm.
