### ISSUE TITLE
How marathon scale apps?

### ISSUE THREAD

**Issue by a93ushakov** [mesosphere/marathon#3839]
If task has incorrect setted  resource limits - does marathon automaticaly increase resource limits or launches new instances?

**Comment by denisbetsi** [comment]
No

**Comment by aquamatthias** [comment]
@a93ushakov Marathon is a scheduler. Mesos is running the tasks. Depending on the isolators configured in Mesos, a task is killed if too many resources are used (e.g. memory-> OOM). If a task is killed, Marathon will restart that task, but will not adjust resource limits.

**Comment by a93ushakov** [comment]
Does exist any ready software that allow in automatic way increase resources?

**Comment by denisbetsi** [comment]
Yes, I wrote something to scale things up and down based on current load. Currently it increases and decreases # of instances by issuing marathon API request commands. It can easily be modified to increase RAM or CPU on that instance config vs scaling up and down. Though for latency it's easier to scale up instances vs reconfiguring an instance
