### ISSUE TITLE
Inconsistency of interpretation of "residency" property in Marathon JSON descriptor 

### ISSUE THREAD

**Issue by adyatlov** [mesosphere/marathon#3843]
1) Deploy an app with the persistent volume **without**  specifying "residency" and **without** specifying "upgradeStrategy" properties ==> FAIL.
2) Deploy an app with the persistent volume **without**  specifying "residency" but **with** "upgradeStrategy" properties ==> SUCCESS.
3) Deploy an app with the persistent volume **with** specifying "residency" and **with** "upgradeStrategy" properties ==> SUCCESS.
Please use descriptors form the attachment in order to reproduce.

[marthon_descriptor_inconsistency.zip](https://github.com/mesosphere/marathon/files/240900/marthon_descriptor_inconsistency.zip)

**Comment by meichstedt** [comment]
Thanks for finding and reporting this, @jrx and @adyatlov!
