### ISSUE TITLE
Visualize current load / capacity

### ISSUE THREAD

**Issue by magcius** [mesosphere/marathon#3845]
We've often hit issues with Marathon because we don't have enough capacity in our cluster to be able to handle the provisioning we give it. It would be nice if there was a visual way of identifying the current load and capacity of the cluster, to know how much room left we have to scale. Otherwise, we're just blindly tweaking the numbers until they feel right.

**Comment by meichstedt** [comment]
@magcius have you considered using [DC/OS](https://dcos.io/)? The current UI offers at least some more infos about available nodes and their usage. Features addressing your request will likely be introduced into the DC/OS UI, but most probably not into the MarathonUI as is is now.

Some backgrounds: Marathon might be one out of multiple framework that run in a cluster. One can argue about whether one such framework should provide general information about cluster capacity (it might not be able to use all this capacity alone, and it might not be able to see all resources in the cluster).

BTW: If you say _because we don't have enough capacity in our cluster_, do you mean the capacity that _your_ Marathon instance may use?

**Comment by magcius** [comment]
Admittedly, I've been confused as to how Mesosphere views Marathon vs. other frameworks. Mesosphere seems to have a significant weight towards Marathon because a lot of products, like the entire [service discovery system](https://github.com/mesosphere/marathon-lb) are built on the Marathon APIs, and don't interact with other frameworks. So we have been reluctant to use other frameworks because they seem to be fairly second-class citizens compared to Marathon.

If we had a general system load inside Mesos's current Bootstrap-based UI, that would be fine. However, it's most convenient when figuring out why our Marathon offers are getting declined, so it would be super convenient to be had right in Marathon's UI for context so I don't need to cross-reference two UIs when scaling an application.

**Comment by magcius** [comment]
Perhaps another way of getting around the same thing would be a tooltip on the waiting state to say "Requested allocation requires 0.5 CPU / 1GB Mem, only have 0.1 CPU / 512MB Mem available" or similar when the offer is declined. Not as great, since it requires me to do more math than a visualization would allow, but it would at least me start figuring out what resource is at fault, and start adjusting parameters.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2544. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
