### ISSUE TITLE
Size check for deployments

### ISSUE THREAD

**Issue by jgarcia-mesosphere** [mesosphere/marathon#3848]
When a group deployment is initiated, the size of the znode created is `old group + deployment metadata + updated group`. This can become too large to transact with ZooKeeper if it exceeds approximately 500kb (the jute.maxbuffer defaults to 1mb). Can we put a line in the log in this case that can advise the user to adjust their app and group definition sizes?

**Comment by aquamatthias** [comment]
@jgarcia-mesosphere we don't know the zk configuration so we can not fail here. But to print a log warning is very good idea.

**Comment by gkleiman** [comment]
@aquamatthias we know the default limit and that it is highly discouraged to increase it.

I think we should add a validation and reject changes that would lead to the root group exceeding 400kb. A log message is not enough to prevent users from exceeding the limit and getting a broken Marathon.
