### ISSUE TITLE
Marathon metrics for max rps for an API

### ISSUE THREAD

**Issue by neeleshkorade** [mesosphere/marathon#3853]
Hi,
I am looking for max rps for our marathon instance (across all APIs). I am referring to /metrics API for the same. Based on my understanding so far, the metric to look for is **max** under **org.eclipse.jetty.servlet.ServletContextHandler.dispatches**. However, the number I see here doesn't look correct. I ran some tests and could see that the **count** metric reflects the number of requests that Marathon is receiving. However, the **max** looks totally off. In my case, when I sent 100rps to marathon, the **max** value showed was "0.266". 

I am thinking I am amiss somewhere. Could someone help me understand if I am referring to the right metric for what I am looking for (rps across all APIs)? If not, which is the right metric, if there is one? If yes, why's the number off? 

Thank you
Neelesh

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1799. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
