### ISSUE TITLE
GROUP_BY constraint - specifying number of values causes deployment to stall

### ISSUE THREAD

**Issue by kellyaa** [mesosphere/marathon#3857]
Deployed a new application with 5 instances.  Specified the following constraint:

 "constraints": [["rack", "GROUP_BY", 5]]

Where there are exactly 5 different values of the "rack" attribute amongst all of the mesos agents.

I would have expected that each of the 5 instances would be deployed on 5 different mesos agents that each have a unique "rack" value.  The result seen is that only one instance is deployed. The other 4 stay in a waiting state indefinitely. If I remove the number of values  and redeploy so that it looks like this:

 "constraints": [["rack", "GROUP_BY"]]

The all 5 instances are deployed, however not spread across all 5 racks - which is expected behavior.  I've tried this against a few different clusters for sanity sake, ensuring sufficient resources were there across all 5 racks - with the same exact result.  

Any ideas what may cause this?

**Comment by gkleiman** [comment]
@kellyaa according to https://mesosphere.github.io/marathon/docs/constraints.html, constraint values have to be specified as a string ("5") instead as an integer (5).

@brndnmtthws created a PR to change that behaviour, but changing your app definition might be a good workaround until the next Marathon release.

**Comment by brndnmtthws** [comment]
This should be resolved by #3865.

**Comment by kellyaa** [comment]
@gkleiman Thanks! Yeah, that was a typo on my part.  Putting quotes around "5" still displayed the same behavior but after help from @brndnmtthws we've realized that the root cause will most definitely be solved by the referenced PR.  Our constraints that we were grouping on were scalar values.  Thanks for your help!!
