### ISSUE TITLE
Is `--volumes-from` supported in marathon

### ISSUE THREAD

**Issue by rupamroy** [mesosphere/marathon#3863]
Hi 

Is `--volumes-from` supported in marathon , I want to mount a volume in the app container from another container ? This means that second container should be present in all the hosts which has the first container marathon should consider these two container as a group. Is that possible to do this ? If what version of marathon supports this and where is the documentation on that ?

**Comment by gkleiman** [comment]
This is not possible right now.

Mesos plans to add support for pods, which will behave similar to kubernetes pods and share volumes across containers.

Once Mesos supports pods, we'll also add support to Marathon.
