### ISSUE TITLE
Disable Leader Proxying

### ISSUE THREAD

**Issue by arodd** [mesosphere/marathon#3868]
I am using a service discovery/health check mechanism that detects if the local node is the leader and then updates service discovery records with the current leader.  The external records match the SSL certificate and work fine coming in externally, however if I health check on the SSL interface it tries to proxy via SSL to the other nodes even for a leader lookup query.  The certificate doesn't have the hostname of the marathon instance and so it complains that the subject alternative name is missing from the certificate.  This pollutes the logs with messages each time the health check runs.   Would it be possible to disable leader proxying altogether via a flag?  I don't actually need it to proxy because the incoming requests should always hit the leader based on the health check determining who the current leader is. I have also tried not disabling the http interface and binding it to localhost for the health check but then it still tries to proxy to the other node who is also only listening via localhost:http.  This method has been cleaner on the logs but still not perfect. Just disabling the proxying mechanism altogether would be beneficial in my specific scenario.   Is this something that is doable?

**Comment by gkleiman** [comment]
This is not possible right now, marking this issue as a feature request.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1892. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
