### ISSUE TITLE
Reporter cannot be consumed from an env var

### ISSUE THREAD

**Issue by jgarcia-mesosphere** [mesosphere/marathon#3870]
When using `MARATHON_REPORTER_GRAPHITE...` in the environment file, we could not get the reporter to start sending data. When we changed to a command-line flag, the reporting started working.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1719. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
