### ISSUE TITLE
Infinite looping on failed deployment

### ISSUE THREAD

**Issue by gondor** [mesosphere/marathon#3874]
I normally won't post an issue until I've spent time reading all the docs and looking through configuration options.  Maybe I've missed a setting but have seen this a couple times now and would like to know how to set it to fail after X attempts.

When our continuous delivery posts a new version of a Docker based applications there is the odd time it fails to startup/health check.  For example in a Spring/Hibernate based app that has schema changes that are failing to update due to a constraint.  What happens is it FAILS in Mesos, then is re-launched again.  I've seen this happen for 20 hours straight until I killed the deployment completely.   

What do I set to fail after N times or N time frame or is this the desired community behavior?

**Comment by gkleiman** [comment]
> If a task fails more than maxConsecutiveFailures health checks consecutively, that task is killed causing Marathon to start more instances. These restarts are modulated like any other failing app by backoffSeconds, backoffFactor and maxLaunchDelaySeconds. The kill of the unhealthy task is signalled via unhealthy_task_kill_event event.

Marathon will try to start the app forever. There's no way to tell Marathon to give app after a certain number of retries, but it supports an exponential back-off between retries. Please check https://mesosphere.github.io/marathon/docs/rest-api.html for more details.
