### ISSUE TITLE
Labels do not wrap nicely in the UI

### ISSUE THREAD

**Issue by ssk2** [mesosphere/marathon#3876]
We have a long label, it appears to get truncated after 3 lines:
![image](https://cloud.githubusercontent.com/assets/355705/15129657/dce4c966-15f7-11e6-8de8-fd79fb70b87b.png)

The limit appears to be 3 lines:
![image](https://cloud.githubusercontent.com/assets/355705/15129686/0f822e0e-15f8-11e6-92be-7e8f1448610f.png)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1706. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
