### ISSUE TITLE
is there any way to run batch scripts in multi containers?

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#3878]
like ansible, puppet, etc.
i think this feature is very useful on aspect point, like the AOP concept.

thanks!

**Comment by gkleiman** [comment]
I don't understand your question. Do you want to know if you can schedule multiple containers, like in kubernetes pods?

Or if you can start scripts inside of already-running containers?

Please send questions like this to the marathon-framework Google group. We use GitHub Issues to track bug reports/feature requests.

**Comment by junneyang** [comment]
i mean start scripts inside of already-running containers 
thanks

**Comment by gkleiman** [comment]
I am afraid that Mesos doesn't support this, so it is not possible right now.
