### ISSUE TITLE
List destroyed apps, and recover functionality

### ISSUE THREAD

**Issue by mlunoe** [mesosphere/marathon#388]
At some point there was expressed a concern about how easy it is to destroy an app.

Well I feel a safety net for this destroy functionality would handle this problem.

As a user I want to see a list of destroyed apps (like the app versions), so I can recover an accidentally destroyed app or recreate an app with a configuration used in an earlier destroyed app.

**Comment by jeschkies** [comment]
Closing for lack of response. Also, this feature I planed as far as I know.
