### ISSUE TITLE
Getting tasks for app with no tasks returns 404 "App does not exist"

### ISSUE THREAD

**Issue by JayH5** [mesosphere/marathon#3881]
If an app has been suspended or has no tasks currently, then requests to `/v2/apps/<app-id>/tasks` returns a 404 response code and the JSON `{"message":"App '<app-id>' does not exist"}`.

The app itself definitely exists and requests to `/v2/apps/<app-id>` succeed.

This seems to be the case for Marathon 0.15.3 and 1.1.1 but I am not sure exactly which versions are affected. Marathon 0.11.1 does not exhibit this behaviour and will instead return a 200 response code as well as an empty list: `{"tasks":[]}`.

**Comment by gkleiman** [comment]
I couldn't reproduce this neither on Marathon v1.1.1 nor on master.

**Comment by gkleiman** [comment]
Confirmed that this affects Marathon v0.15.3.

**Comment by gkleiman** [comment]
cc/ @aquamatthias do you think we should backport the fix?

**Comment by jasongilanfarr** [comment]
Please reopen if we should backport. @JayH5
