### ISSUE TITLE
Marathon Scaling application issue

### ISSUE THREAD

**Issue by s13k** [mesosphere/marathon#3883]
Marathon is able to scale maximum 5 instances on the first node but  when I tried scaling it further the host gets changed to the second slave node.And the task fails to start and error in the debug section of the Marathon UI shows "Abnormal executor termination".

I would like to know why is it not getting scheduled on the other slave node???

**Comment by gkleiman** [comment]
@s13k look at the Mesos Agent (Slave) logs to see why the executor failed.
