### ISSUE TITLE
How to build custom mesosphere.marathon/ui jar ?

### ISSUE THREAD

**Issue by tmmi** [mesosphere/marathon#3884]
from https://github.com/mesosphere/marathon-ui

**Comment by pierlo-upitup** [comment]
I'm guessing a simple way is to replace the contents of the UI webjar within the locally built marathon JAR with the contents of the Marathon UI `dist` folder once you've followed the instructions on how to build your UI locally. A webjar is essentially a `.zip` file, so just extract it to reveal its contents. Then pack it all up again and you should be good to go. Let me know if this helps, @tmmi .

**Comment by tmmi** [comment]
Thanks, for tip.
I build ui npm run dist and pack with zip -r ui-1.2.1-SNAPSHOT.zip dist
rename to jar and put into my local m2repo into proper directory 
 .m2/repository/mesosphere/marathon/ui/1.2.1-SNAPSHOT/
Next I change in marathon
  val MarathonUI = "1.2.1-SNAPSHOT"
and add to resolvers :+ Resolver.mavenLocal

But test failed:
*** 1 TEST FAILED ***
WebJarServletTest:

- Get /ui/ will return the index.html *** FAILED *** (8 milliseconds)
  "" did not include substring "<title>Marathon</title>" (WebJarServletTest.scala:61)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2066. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
