### ISSUE TITLE
Marathon won't start

### ISSUE THREAD

**Issue by robertd** [mesosphere/marathon#3891]
Hi all,

I am following [DO guide](https://www.digitalocean.com/community/tutorials/how-to-configure-a-production-ready-mesosphere-cluster-on-ubuntu-14-04) on how to install Mesos/Zookeeper/Marathon and configure it in 1 master and 2 slaves scenario, but I'm experiencing some issues.

Mesos is running just fine:

![capture2](https://cloud.githubusercontent.com/assets/31543/15198701/52667b9a-1796-11e6-8079-93d373da8bc5.JPG)

However Marathon is not starting at all:

Started marathon and checking status...
```bash
robertd@mesos-master:/etc/marathon/conf$ sudo start marathon
marathon start/running, process 10328
robertd@mesos-master:/etc/marathon/conf$ sudo status marathon
marathon stop/waiting
```

Starting marathon with `5 sec` delay
```bash
robertd@mesos-master:/etc/marathon/conf$ sudo start marathon
marathon start/running, process 10696
robertd@mesos-master:/etc/marathon/conf$ sudo start marathon
start: Job is already running: marathon
robertd@mesos-master:/etc/marathon/conf$ sudo start marathon
marathon start/running, process 11064
```

For some reason it keeps crashing but I have no idea why. 
Here are the contents of the `etc/marathon/conf` directory:

```bash
robertd@mesos-master:/etc/marathon/conf$ ll
total 24
drwxr-xr-x. 2 root root 4096 May 11 16:40 ./
drwxr-xr-x. 3 root root 4096 May 11 15:56 ../
-rw-r--r--. 1 root root   16 May 11 16:22 hostname       (xxx.xxx.xxx.xxx)
-rw-r--r--. 1 root root   32 May 11 16:22 master         (zk://xxx.xxx.xxx.xxx:2181/mesos)
-rw-r--r--. 1 root root   35 May 11 16:23 zk             (zk://xxx.xxx.xxx.xxx:2181/marathon)
```

Few additional marathon/mesos questions:

- How do you specify different port?
- How do you set cluster name?
- Can you set user-friendly name in the `hostname` and how? Every time I set it, mesos won't pickup the slave.

Thanks for your help in advance!

**Comment by robertd** [comment]
Checked the syslog:

```bash
May 12 10:09:18 mesos-master kernel: [2064323.693775] init: marathon main process (3579) terminated with status 1
May 12 10:09:18 mesos-master kernel: [2064323.693795] init: marathon main process ended, respawning
May 12 10:09:18 mesos-master marathon[3611]: Exception in thread "main" java.lang.UnsupportedClassVersionError: mesosphere/marathon/Main : Unsupported major.minor version 52.0
May 12 10:09:18 mesos-master marathon[3611]: #011at java.lang.ClassLoader.defineClass1(Native Method)
May 12 10:09:18 mesos-master marathon[3611]: #011at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
May 12 10:09:18 mesos-master marathon[3611]: #011at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
```

**Comment by robertd** [comment]
I'll do as these guys suggest here and I'll report back...
https://issues.apache.org/jira/browse/MESOS-5147

**Comment by robertd** [comment]
It worked. Forgot to mention that I'm on `Ubuntu 14.04`

```bash
sudo add-apt-repository ppa:openjdk-r/ppa
sudo apt-get update
sudo apt-get install openjdk-8-jdk
sudo update-alternatives --config java
sudo update-alternatives --config javac
```

**Comment by arslanqadeer** [comment]
Worked for me too. Thanks

**Comment by eromoe** [comment]
Great work! I install java8, but it is not the default java. The whole doc doen't mention that, just one line saying `install jdk 1.8`, who would know it need set java8 as default.
