### ISSUE TITLE
I can create a marathon app in JSON mode that will never start because cmd is null and there is no container image

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#3893]
```
{
  "id": "mesosvol",
  "cmd": null,
  "cpus": 1,
  "mem": 128,
  "disk": 0,
  "instances": 1,
  "container": {
    "type": "MESOS",
    "volumes": [
      {
        "containerPath": "data",
        "external": {
          "name": "jdef-test-124",
          "provider": "dvdi",
          "size": 1, 
          "options": {
            "dvdi/driver": "rexray"
          }
        },
        "mode": "RW"
      }
    ]
  }
}
```

**Comment by prsekar** [comment]
The marathon doc (https://mesosphere.github.io/marathon/docs/rest-api.html#post-v2-apps0 says either cmd or args are needed for an app to be deployed. We could add a check for either cmd or args present in the appDef to return an error. @aquamatthias is this sound reasonable, i could make the change

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1696. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
