### ISSUE TITLE
Marathon-LB stuck waiting for resource offer

### ISSUE THREAD

**Issue by MihaiAnei** [mesosphere/marathon#3895]
I cannot seem to be able to deploy marathon-lb, can you help me?

<img width="1686" alt="screen shot 2016-05-13 at 16 05 43" src="https://cloud.githubusercontent.com/assets/6485811/15248797/c7c5f908-1924-11e6-849e-5d694954c0fd.png">

[mesos-lb-state.zip](https://github.com/mesosphere/marathon/files/263298/mesos-lb-state.zip)

Using DC/OS v.1.7-open installed by CLI method.

**Comment by manei** [comment]
Also trying to deploy Datadog doesn't seem to work. I think it has something to do with the fact that those are DOCKER type containers. Docker is installed on all slaves, v1.11.1

**Comment by sahlex** [comment]
I'm experiencing the same issue. Any cure?

**Comment by sahlex** [comment]
In marathon logs I see a message about insufficient resources, but I cannot see why it's not matching the host...

Jun 29 14:27:22 mesos.brodosmit.de java[12954]: [2016-06-29 14:27:22,297] INFO Offer [81052672-ba9f-41fa-99c7-d201bea54455-O268]. Insufficient resources for [/marathon-lb] (need cpus=0.5, mem=256.0, disk=0.0, ports=([88, 8443, 9090, 9091] required), available in offer: [id { value: "81052672-ba9f-41fa-99c7-d201bea54455-O268" } framework_id { value: "81052672-ba9f-41fa-99c7-d201bea54455-0000" } slave_id { value: "81052672-ba9f-41fa-99c7-d201bea54455-S3" } hostname: "172.17.42.42" resources { name: "ports" type: RANGES ranges { range { begin: 1 end: 21 } range { begin: 23 end: 5050 } range { begin: 5052 end: 32000 } } role: "slave_public" } resources { name: "cpus" type: SCALAR scalar { value: 2.0 } role: "slave_public" } resources { name: "mem" type: SCALAR scalar { value: 496.0 } role: "slave_public" } resources { name: "disk" type: SCALAR scalar { value: 23702.0 } role: "*" } attributes { name: "public_ip" type: TEXT text { value: "true" } } url { scheme: "http" address { hostname: "172.17.42.42" ip: "172.17.42.42" port: 5051 } path: "/slave(1)" }] (mesosphere.mesos.TaskBuilder:marathon-akka.actor.default-dispatcher-546)

**Comment by BenHall** [comment]
I had the same issue and I believe I've resolved it. In the JSON for Marathon-LB it has an acceptedResourceRoles node. Once I removed that I could deploy the LB. 

```
  "acceptedResourceRoles": [
    "slave_public"
  ]
```

**Comment by sahlex** [comment]
It was not working for me when I had `slave_public` set, that's why I took it away so the marathon-lb matches offers from other hosts as well. I switched it back, and now it works!

I assume it was due to resource request that could not be satisfied by the public node. I set hosts to 0.5 and memory to 256MB and now it starts up.

Anyways - thanks!
