### ISSUE TITLE
Allow subscription of specific events from event stream

### ISSUE THREAD

**Issue by rlubke** [mesosphere/marathon#3896]
Would be nice to be able to subscribe to a specific set of events from Marathon vs all events from the fire hose.

For example, we have an integration with nginx for which we subscribe to Marathon's event stream.  However, given the number of services we have there's a lot of noise generated for this integration as we're only interested in three event types.  While this would put a little more load on Marathon, it would definitely by a saver on the wire.  Would also help reduce the chance of the event queue from getting backlogged causing events to be dropped.

**Comment by xiaods** [comment]
+1

**Comment by sathee005** [comment]
+1

**Comment by eduser25** [comment]
+1

**Comment by atamborrino** [comment]
+1

**Comment by elianka** [comment]
+1

**Comment by janisz** [comment]
Duplicates: #4637
Fixed: https://github.com/mesosphere/marathon/pull/4671

**Comment by janisz** [comment]
@jasongilanfarr Could be closed now
