### ISSUE TITLE
Private registry sandbox security problem

### ISSUE THREAD

**Issue by jeacott** [mesosphere/marathon#3898]
If I'm using a private registry, and follow the instructions to provide the tar.gz credentials,  then those credentials are made available not only to mesos in order to procure the docker, but also to anything inside that container that cares to look at the mounted sandbox.  It would be especially helpful if the fetcher had an option to NOT copy fetched files to the sandbox.

**Comment by xiaods** [comment]
any update?

**Comment by gkleiman** [comment]
@jeacott, @xiaods: this needs support from Mesos' fetcher. Please open a ticket in their JIRA.

**Comment by xiaods** [comment]
@jeacott do you have some proposal on fix it? if not , i think the issue can't be fix asap

**Comment by jeacott** [comment]
Like i suggested, an option to NOT copy artifacts to the moumted sandbox would suit very well.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4152. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
