### ISSUE TITLE
Require M-N healthy instances (count, rather than percentage)

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#3900]
I've deployed a Cassandra cluster (3.x) with Marathon. With a replication factor of 3, it's a problem to have 2 nodes unhealthy at a given time. I'm using persistent volumes to pin containers to consistently start on the same hosts (because Marathon support for full disk volumes is not actualized ATM).

Presently, the restart strategy only allows me to specify a minimum percentage of unhealthy hosts. With a Cassandra cluster, I cannot allow over-provisioning for obvious reasons.

Preferably, I care less about the % of instances out of health at a time than I do about # of instances. I'd like a way to specify a specific quantity of out-of-instances.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2147. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
