### ISSUE TITLE
Allow specification of >50% minimum healthy instances for persistent tasks

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#3901]
There doesn't seem to be a really good reason for this restriction. I'd prefer a scenario in which my rollout stalls because minimum healthy instances cannot be satisfied, than to have more unhealthy instances than can be tolerated by the cluster.

**Comment by hotstepper13** [comment]
If i remind correctly you could set minimumHealthCapacity to 0.5 which means that at least 50% of your tasks must remain active.

In conjunction with maximumOverCapacity you can define how your deployment should work.

For instance:
All tasks are stopped and redeployt
minimumHealthCapacity: 0
maximumOverCapacity: 0

Stop 50% of tasks, redeploy them, wait until they are healthy and then stop and redeploy the remaining
minimumHealthCapacity: 0.5
maximumOverCapacity: 0

Let all your taks live until the new ones become healthy
minimumHealthCapacity: 1
maximumOverCapacity: 1

**Comment by timcharper** [comment]
Hi @hotstepper13 thanks for the reply! This was all clear to me. Ultimately, https://github.com/mesosphere/marathon/issues/3900 is what I want, but I didn't want to conflate the features too much so I opened them separately.

My requirement is that at most 1 instance is unhealthy at a given time during deploy; I absolutely cannot over-provision. This requirement could be satisfied by allowing me to specify >50% healthy instances minimum, or by specifying `maximumUnhealthyQty`, or something.

**Comment by meichstedt** [comment]
@timcharper I can see your point. In general we try to prevent a deployment from becoming stalled, if possible, because there's no easy way to find out why it's not proceeding. However, the upgradeStrategy is already interpreted in context of the _type_ of application: for apps using persistent volumes, Marathon won't allow any overCapacity (which it **does** for normal apps even if `maximumOverCapacity = 0`).

I'd suggest allowing any `minimumHealthCapacity < 1` but killing at least 1 task to get an upgrade rolling. Or, would you rather prefer Marathon **not** killing 1 task if that'd keep less than the specified `minimumHealthCapacity`?

**Comment by timcharper** [comment]
@meichstedt that sounds like a reasonable compromise to me. It does seem to bend the meaning of the term, `minimumHealthCapacity`, by extending the meaning to be "`minimumHealthCapacity` except when this means no instances can be unhealthy, in which case `minimumHealthCapacity` = # of hosts - 1". I think it would be clearer to add a different strategy, and allow a numeric qty specification for # of unhealthy hosts, but can empathize with a concern that this would be too much complexity for the API / implementation.

**Comment by timcharper** [comment]
Scratch that; adding a `qty` input would be too much complexity, since `minimumHealthCapacity` indicates no unit. I'm becomming more won over to your suggestion, @meichstedt

**Comment by meichstedt** [comment]
@timcharper Totally agree. The fact that the restart behavior doesn't really adhere to the maximumOverCapacity bugs me for a while now. People tend to think that `maximumOverCapacity = 0` means _there'll never be more instances than specified_, which is unfortunately wrong.

I'd really like to make that clear and easy to use, and having an upgradeStrategy that _somehow_ allows specifying integer count for min/max/whatever sounds reasonable; we just have to make sure we stay backwards compatible if it was ever to become part of the v2 api.

In the meantime my suggested approach might be easier to implement, but I'd have no problem with changing the internal model while extending the api to accept a different upgradeStrategy – I only have time constraints on that ;)

**Comment by timcharper** [comment]
I have a commit for this, however it's not a pull request because I have another pull-request in flight for persistent volumes. Once that is merged, I can open it, or, if this looks harmless enough, we can just cherry pick it in.
