### ISSUE TITLE
Errors were encountered while processing: /var/cache/apt/archives/python2.7-minimal_2.7.9-2_amd64.deb

### ISSUE THREAD

**Issue by adolphlwq** [mesosphere/marathon#3902]
## env
- ubuntu 15.04 vivid 64bit
- java 8 
- mesos 0.26
- marathon=1.1.0-1.0.471.ubuntu1504
## problem

I use the repo provided by mesosphere (deb http://repos.mesosphere.io/ubuntu/ vivid main).I run into this error when  installing marathon:

```
Errors were encountered while processing:
/var/cache/apt/archives/python2.7-minimal_2.7.9-2_amd64.deb
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4542. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by adolphlwq** [comment]
@meichstedt  Thanks!
