### ISSUE TITLE
launch_tokens seems not to work in Version 1.1.1

### ISSUE THREAD

**Issue by hotstepper13** [mesosphere/marathon#3904]
I am using Marathon 1.1.1 on Ubuntu14.04 and set launch_tokens to 2. From the docs I assume that this means that only 2 tasks are started within 30 seconds (default interval).

However I can see that there seems no limit regarding the parallel starting of tasks. (have seen 5 parallel starts so far)

Healthchecks are defined and I can see that marathon has multiple apps/tasks in Deployment state.

The reason why i need this limit is that our applications causing a high cpu load while starting. Starting too much in parallel cause the health checks to fail and marathon will restart already running tasks which drives us deep into cpu problems.

In addition to the above setting I have also set max_tasks_per_offer to 2

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4442. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
