### ISSUE TITLE
is there any way to enter the app for debug ?

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#3917]
how to enter the app fro debug ?
i suggest marathon provide proxy & webUI for this.
or any one could give some suggestions? 
thanks!

**Comment by philipnrmn** [comment]
Hi @junneyang, a proxy and web UI for debugging tasks is a great feature idea! I think it's well beyond the scope of Marathon core so I'm going to close this issue, but please don't be discouraged by that -  we'd love to see a plugin if you were inclined to write one. 

Your first line of attack in debugging is the logs, which are provided for download in the task detail view. If they are not helpful, you can SSH to the node on which it's running and attach your debugging tools directly to the relevant process.

**Comment by kamilchm** [comment]
@philipnrmn debugging is needed mostly when app fails and you [can't jump or download logs of failed tasks](https://github.com/mesosphere/marathon/issues/3447) at the moment :( You need to go to Mesos Web UI and filter failed tasks list with name of your app to see links for its sandbox.
We created 2 PRs in Marathon UI to fix these issues:
* https://github.com/mesosphere/marathon-ui/pull/765
* https://github.com/mesosphere/marathon-ui/pull/768

Can you help us to push it into the next release?
