### ISSUE TITLE
marathon app json can't support dynamic values in double string

### ISSUE THREAD

**Issue by xiaods** [mesosphere/marathon#3919]
```
"parameters": [
      {
        "key": "add-host",
        "value": "localhost:$HOST"
      }
    ],
```
i need add a slave ip to docker daemon, but when i scaling the app instance, the ip is need dynamic ip. so how can i do that?anyone can do me a favor to answer the question?

**Comment by xiaods** [comment]
currently marathon only accept $HOST as a literal string.

**Comment by gkleiman** [comment]
You can use the `MARATHON_HOST` env variable to get the slave's host name.
