### ISSUE TITLE
How to implement linking between docker containers in Marathon applications?

### ISSUE THREAD

**Issue by alexraju** [mesosphere/marathon#3925]
I have created a sample application from a docker image which has a dependency towards docker container running database. 
After I the marathon deployment of database, the database container is having dynamic naming, not the one I passed as docker parameter. Because of this I'm not able to set the `link` parameter when deploying the sample application. What is the recommended way to do this?

Also, I tried to manually get the container name of the database and set this in `link` parameter for the sample application. This is not working either.

**Comment by xiaods** [comment]
you need orchestration with your engine

**Comment by gkleiman** [comment]
@alexraju Marathon can start the tasks in different nodes, so Docker links aren't very helpful.

You can find info about some ways of doing service discovery here: https://mesosphere.github.io/marathon/docs/service-discovery-load-balancing.html

**Comment by alexraju** [comment]
Since, its been a long time, I forgot about this ticket. Actually I found out the best way using VIPs in DC/OS.

**Comment by xiaods** [comment]
actually i think compose is killing feature for docker container. so don't worry, use alternative tools: swarm or k8s.

**Comment by alexraju** [comment]
You mean using these as the orchestration tools within dcos (as an alternative to marathon)?
But, I think the support for these are minimal currently.
