### ISSUE TITLE
Create PORT_NAME environment variable when we define portDefinitions with name

### ISSUE THREAD

**Issue by dqminh** [mesosphere/marathon#3926]
For example, given the following config:
```
portDefinitions:
  - name: grpc
  - name: http
```
it would be nice for documentation purposes to also have `PORT_GRPC` and `PORT_HTTP` environment variable defined together with `PORT0` and `PORT1`

**Comment by gkleiman** [comment]
@dqminh thanks for the feature request, I added it to our backlog.
