### ISSUE TITLE
Be able to set app must provide constraints?

### ISSUE THREAD

**Issue by xyalan** [mesosphere/marathon#3932]
I have tested Marathon constraints with Mesos attributes.Now app which no constraints are provided is to place it anywhere, but I do not want somebody do this.App that deploy to marathon must provide constraints, refuse if no.Be able do this Now? How to configure? 

Like #1619

**Comment by aquamatthias** [comment]
This is currently not possible.
I can think of a plugin interface for custom validation,  that could help here.
