### ISSUE TITLE
Inconsistent validation in Marathon and Marathon UI

### ISSUE THREAD

**Issue by medzin** [mesosphere/marathon#3933]
There is inconsistency between memory resource validation in Marathon (API) and Marathon UI (JavaScript). API requires that the memory should be greater than or equal to zero but in UI I need to enter value greater than or equal to 32.

**Comment by aquamatthias** [comment]
In the UI we try to guide the user as best as we can.
In the service layer we try to allow as much as we can.
Thats why there is this difference.
