### ISSUE TITLE
http_callback blacklisted with no way out

### ISSUE THREAD

**Issue by eLvErDe** [mesosphere/marathon#3935]
Hello,

After a network modification I broke the callback link between marathon and marathon-lb. Marathon detected the callback was unsuccessful and decided to blacklist it (well, honestly that doesn't look right to me at all but it's up to you).

> May 25 08:47:21 pssu-host01 marathon[6023]: [2016-05-25 08:47:21,810] INFO Will not send event deployment_step_success to unresponsive hosts: http://proxy.domain:8181 (mesosphere.marathon.event.http.HttpEventActor:marathon-akka.actor.default-dispatcher-14)

However, after fixing the issue I found no way to get the callback working again. Triggering marathon-lb restart make it subscribe again but Marathon keep refusing to run the callback, thanks to the blacklist.

I guess the only way out is to restart marathon....

Best regards, Adam.

**Comment by aquamatthias** [comment]
Failing callbacks back off. Marathon will retry this callback after the back off time automatically.
