### ISSUE TITLE
Please support move app between groups directly！

### ISSUE THREAD

**Issue by readthecodes** [mesosphere/marathon#3937]
I have a app run in group1, but now I want move it to group2, I can't move to group2 directly, the only way marathon provide is create another app in group2 and then destroy the old app in group1.

**Comment by hokiegeek2** [comment]
I think this is a great idea, don't know the level of difficulty to implement, but this would be a cool feature IMHO.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2063. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
