### ISSUE TITLE
Why is Marathon updating my application every ~5-15 minutes?

### ISSUE THREAD

**Issue by gwgundersen** [mesosphere/marathon#3939]
I have an application hosted on Docker Hub, deployed in a Docker container, and running via Marathon. I noticed this morning that my Docker Hub image had 7.7K pulls. Suspecting that my application had not suddenly become very popular, I began monitoring it on Marathon and noticed that the `Updated` column is changing. Here are the timestamps for the past hour:

```
5/26/2016, 4:03:37 PM
5/26/2016, 4:16:29 PM
5/26/2016, 4:25:15 PM
5/26/2016, 4:50:24 PM
5/26/2016, 4:55:32 PM
5/26/2016, 5:07:05 PM
```

[Here is a GIF of Marathon updating my application](http://imgur.com/ZXzNTuG)

It doesn't look like the application is being fully redeployed, but why is it staging and then updating? And would this be causing the dramatic increase in pulls from Docker Hub?

**Comment by Poogles** [comment]
Are you sure the containers not exiting and being restarted by Marathon?  Have you checked the Mesos logs?

**Comment by gwgundersen** [comment]
I've checked Mesos logs via the user interface, but that only lists the logs for current applications. My application's logs always have only a few lines, since it was always just restarted. Should I be looking somewhere else?

**Comment by gkleiman** [comment]
@gwgundersen what do you see in the Marathon leader logs?

**Comment by jeschkies** [comment]
@gwgundersen do you still observe this issue?

**Comment by gwgundersen** [comment]
@jeschkies, I'm no longer working at that job. I suppose we can close this since it's not possible for me to investigate further.
