### ISSUE TITLE
Can I get an definitive answer on where the COMMAND healthcheck runs?

### ISSUE THREAD

**Issue by erickmgriffin** [mesosphere/marathon#3946]
I see confusing git, forum and slack entries on where exactly the healthcheck for a DOCKER image runs.  Does it:
- run on the VM that runs the mesos-slave and service container?
- run in the service container itself?

Also, what exactly does marathon check for to consider a COMMAND to be healthy?  0?  Or, something else, assuming its a bash or sh command.

Can you update and elaborate a bit more in the documentation?...

**Comment by nicovillanueva** [comment]
As per [the docs](https://mesosphere.github.io/marathon/docs/health-checks.html), "health checks are locally executed on the agent running the corresponding task"

For example, I have one healthcheck configured like so: http://imgur.com/bfLByfR
Beyond the fact that such check is awful, that is ran inside the Docker container that makes up the Marathon application (a.k.a., the Mesos -long running- task)
And, yeah, if that thing exits with code 0, is considered healthy.

**Comment by erickmgriffin** [comment]
COMMAND health checks are locally executed by Mesos on the agent running the corresponding task.  To me, that should read, "COMMAND health checks are executed by Mesos in the container of the corresponding task."  Sounds like double-talk to me, or a translation.

**Comment by nicovillanueva** [comment]
Absolutely. Unless someone else corrects us, maybe later I'll send a PR to clarify this.

**Comment by gkleiman** [comment]
@erickmgriffin my understanding is that the health checks are executed by Mesos in the container of the corresponding task.

I have asked our team of Mesos developers to confirm this. If this is true, then both Marathon's and Mesos' documentation should be improved.

**Comment by gkleiman** [comment]
@nicovillanueva I just confirmed that your suggestion is correct. PRs are welcome and encouraged =).

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2459. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
