### ISSUE TITLE
High CPU utilization and non-responsiveness

### ISSUE THREAD

**Issue by nicovillanueva** [mesosphere/marathon#3947]
OS: Linux Mint 17
Browser: Google Chrome 49.0.2623.110

Very frequently, when having a Marathon tab open for a while, it ends up being almost unresponsive.
If I happen to leave it open, do something else for ~5 minutes, then go back to it, it usually will be completely unresponsive to clicks for a few seconds. I usually just open the same URL on another tab.

Inspecting the browser's task manager, the CPU utilization is averaging 101%: http://imgur.com/bx7KEVt

I wish I could give you guys more info, but there's not many reproduction steps for this. Let me know if I could help you out somehow.

EDIT: I cannot add labels, but it's a UI related thingy.

**Comment by pierlo-upitup** [comment]
Hi @nicovillanueva what UI version are you using? Type `g v` in your browser to reveal the UI version dialog. Thanks!

**Comment by nicovillanueva** [comment]
Hi! On such dialog, it says 1.1.2
On the "About" dialog, says 1.1.1

**Comment by pierlo-upitup** [comment]
OK so that's the latest. Thanks.

**Comment by bobrik** [comment]
I assume it's the same issue: #3304.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1702. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
