### ISSUE TITLE
How should I use HDFS as a volume in  Marathon?

### ISSUE THREAD

**Issue by yangdalong** [mesosphere/marathon#3948]
Hi.
When I use Marathon，I want to use HDFS as a volue,but I can't find the right way to solve it.Here is my configuration:
{
      "id":"ssh-test-hdfs",
      "container": {
      "type": "DOCKER",
      "volumes": [
      {
        "containerPath": "/opt/mesosphere",
        "hostPath": "hdfs://192.168.131.142:9000/",
         "mode": "RW"
       }
      ],
     "docker": {
     "image": "192.168.131.141:5000/cbtest/centos_ssh:v1",
          "network": "BRIDGE",
          "portMappings": [
            { "containerPort": 22, "hostPort": 0, "protocol": "tcp"}
          ]
     }
    },
      
     "constraints": [["hostname", "UNIQUE"]],
     "cpus": 0.1,
     "mem": 50.0,
     "instances": 1
}
But it's not working properly.
Is there a way to solve the problem of using HDFS as a volume?Thank you very much!^_^
Looking forward to your reply!

**Comment by gkleiman** [comment]
@yangdalong I'd ask this in one of Mesos' support channels.

Marathon will just pass the path to Mesos.

**Comment by holysilent** [comment]
@gkleiman   ok,   thanks a lot
