### ISSUE TITLE
Provide a Dockerfile to build marathon-ui project

### ISSUE THREAD

**Issue by pierrecdn** [mesosphere/marathon#3949]
Actually, it is really painful to build the marathon-ui project (nvm, npm, gulp, specific versions required, etc.).
It could be easier to maintain a Dockerfile image.

**Comment by sivaramsk** [comment]
Do you mean this -
https://hub.docker.com/r/mesosphere/marathon/~/dockerfile/

On Mon, May 30, 2016 at 10:47 AM, Pierre C. <notifications@github.com>
wrote:

> Actually, it is really painful to build the marathon-ui project (nvm, npm,
> gulp, specific versions required, etc.).
> It could be easier to maintain a Dockerfile image.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/mesosphere/marathon/issues/3949>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAS8fdjJRFMnoEyetmpdIcw1zikrBteVks5qGvh7gaJpZM4Ip2z2>
> .
>



-- 
ever tried. ever failed. no matter.
try again. fail again. fail better.
        -- Samuel Beckett

**Comment by pierrecdn** [comment]
@sivaramsk : no, this Dockerfile is to build marathon.
I wanted to patch **[marathon-ui](https://github.com/mesosphere/marathon-ui)**, then easily build the project and integrate it into a marathon fork.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2394. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
