### ISSUE TITLE
can marathon specify host_ip when setting portmapping?

### ISSUE THREAD

**Issue by elianka** [mesosphere/marathon#3951]
when i use marathon to create docker containers, i could use portMappings to set port in container and port in host. Meanwhile, i have two ethx on host, such as IP_A and IP_B, and i just want to set the port mapping on IP_A then IP_B. Can marathon do this?
like the function in `docker run  -p IP:host_port:container_port`

```
        "portMappings": [
          {
            "containerPort": 6666,
            "hostPort": 6666,
            "protocol": "tcp"
                }
```

**Comment by b0e** [comment]
I think this is not possible, yet. This would be very useful for me, too. What is needed to convert this into a feature request?

**Comment by gkleiman** [comment]
I don't think that Mesos supports this.

**Comment by gkleiman** [comment]
cc/ @sargun

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1911. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
