### ISSUE TITLE
Unable to remove an application if it is in a subgroup named "tasks"

### ISSUE THREAD

**Issue by Devatoria** [mesosphere/marathon#3952]
When using Marathon 1.1.1, if I create a group named `myfolder`, then a subgroup named `tasks`, and then launch an application in this subfolder, Marathon is unable to remove this app.

```
Are you sure you want to destroy /myfolder/tasks/nginx? This action is irreversible.

Error destroying /myfolder/tasks/nginx: App '/myfolder' does not exist
```

This error is probably caused by the Marathon API call `/v2/apps/{app_id}/tasks/{task_id}` which shadows the call `/v2/apps/{app_id}/tasks`. Indeed, the `{app_id}` parameter is `/myfolder/tasks/nginx` here.

A workaround is to remove the folder itself.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1690. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
