### ISSUE TITLE
dcos 1.7  - unable to access marathon 

### ISSUE THREAD

**Issue by jitendraky** [mesosphere/marathon#3953]
Getting error while accessing marathon, seems to be an issue with zookeeper

HTTP ERROR: 503
Problem accessing /. Reason:
Could not determine the current leader

**Comment by njappboy** [comment]
@jitendraky You might want to try using `mesos-resolve` to determine the leader via zookeeper:
```shell
$ mesos-resolve `cat /etc/mesos/zk` 2>/dev/null
```

**Comment by gkleiman** [comment]
Looks like a dupe of #4063
