### ISSUE TITLE
 Is there a way to manually update the image with tag:latest to the real latest one? 

### ISSUE THREAD

**Issue by yfc845** [mesosphere/marathon#3955]
As in my environment there will be new docker image pushed to our registry frequently, thus whenever there is a new version of image, we have to manually update it to the image config in Marathon.

But as you know, the tag:latest doesn't represent for the real latest image, thus I cannot config in marathon like: "image: xxx/xxx:latest"

I am thinking if there is a way, everytime when pushing a new version of image to registry, there can be a command I can run to manually update the tag:latest one to the one I just pushed?

Or is there a way Marathon can always run the real latest image?

ps: I already turned on the "forcepull", it has nothing to do with this issue anyway...

**Comment by gkleiman** [comment]
@yfc845 you can trigger a restart each time you update the tag, see https://mesosphere.github.io/marathon/docs/rest-api.html#post-v2-apps-appid-restart

Please re-open if that didn't help.
