### ISSUE TITLE
Marathon 1.1.1 and Mesos TaskStatus

### ISSUE THREAD

**Issue by tymofii-polekhin** [mesosphere/marathon#3956]
Hello, i've builded Mesos from release tar of 0.28.1 version and launched marathon on top. 
Then i created simple task in marathon to launch `grafana/grafana` docker container with `BRIDGE` network to port 3000 from random port. 
Configured a TCP health check for this port in marathon. 
Container went up well and health checks are green, but... 

Looking at mesos-slave logs i don't see any TASK_STATUS_UPDATE events. 
Mesos task goes from TASK_STARTING to to a single TASK_RUNNING and then nothing. 

Is this made by design? 
Is this a recent change?

**Comment by gkleiman** [comment]
TCP health checks are performed by Marathon, not Mesos, so the transitions you observed are the expected ones.

**Comment by tymofii-polekhin** [comment]
@gkleiman thats cool) a little over a month have passed)

so you're officially rejecting support for mesos-hook modules with marathon?)

**Comment by gkleiman** [comment]
@tymofii-polekhin you didn't mention mesos-hook modules in your original post.

Let me answer the two questions you asked explicitly:

1. Is this made by design? Yes, TCP health checks are performed by Marathon, not Mesos. If a TCP health check fails, Marathon will kill the unhealthy task. If it succeeds, Marathon will show the task as healthy, Mesos is not notified.
2. Is this a recent change? No, it is not a recent change.

**Comment by tymofii-polekhin** [comment]
@gkleiman okay then why don't you report a TASK_STATUS on every healthcheck? For example, service discovery solutions may use this information for their own task health updates. Right now TASK_STATUS event is dispatches only when STATE has changed. I don't see any benefit from this right now. Maybe you can explain further? Thanks

**Comment by gkleiman** [comment]
@tymofii-polekhin AFAIK the Mesos Scheduler Driver doesn't have a method to allow frameworks to send status updates.

If you're interested in getting event updates from Marathon, then you should look into: https://github.com/mesosphere/marathon/blob/master/docs/docs/event-bus.md

**Comment by tymofii-polekhin** [comment]
@gkleiman i've seen a bunch of frameworks doing that, and, honestly, i don't see a reason why anyone should create a separate process for Marathon events only
