### ISSUE TITLE
COMMAND HealthChecks removed on mesos-master restart/issue

### ISSUE THREAD

**Issue by davent** [mesosphere/marathon#3957]
COMMAND Health Checks are being removed (i.e. `INFO Removing health check for app`) and never re-created when something happens to the mesos-master. I have seen this with both a restart of the mesos-master and also under less controlled situations such as a leader re-election or network issues.

To reproduce:

1) Create an App with a COMMAND Health Check
2) Restart mesos-master
3) grep marathon log for `Removing health check`

Although `addAllFor` and subsequently `add` is called (which you can see int he logs: `INFO Adding health check for app`) No health check data is ever available either via the UI (the good old grey bar of doom) or via the JSON return via the API.

The HTTP and TCP Health Checks return successfully but the only way to re-establish the COMMAND Health Checks is to restart the Apps.

Using:
Mesos: 0.28.0
Marathon: 1.1.1

**Comment by brat002** [comment]
Have this problem too.

**Comment by andlaz** [comment]
Same issue.

**Comment by davent** [comment]
Some additional information:

When a Mesos Slave drops from the cluster (in the case just witnessed this was due to a faulty EC2 node having to be rebooted) and then rejoins this appears to also cause this issue.

**Comment by brat002** [comment]
Does any plans to fix it? Marathon is unusable in real production infrastructure without health checks.

**Comment by kensipe** [comment]
@davent @brat002 @andlaz  Thanks for the report.  After some review, It looks like it may be an issue with Apache Mesos.   Command health checks are reported differently than other health checks in Mesos.  They are received via a task status update.   If you look at the implementation in Mesos:  https://github.com/apache/mesos/blob/master/src/health-check/main.cpp#L135-L137
Updates are only sent:
1) for the first success
2) after a failure
In your example there is no failure so no update of status.  It doesn't make sense for Marathon to assume a success.  When need to get the health status from mesos after a network partition or master fail over.

I'm working with the core team to get an answer in place.

**Comment by brat002** [comment]
After some improvements in mesos https://github.com/apache/mesos/issues/118, looks like marathon also has a problem. 
Now Mesos shows health: true after leader re-election, but marathon still show "unknown" health.

Marathon task status:
`id: "lsau01-XXXXXXXXXXXXXX",
name: "lsau01-XXXXXXXXXXXXXX",
framework_id: "c5ad05ba-4a33-4d65-ab67-4d7c29928985-0001",
executor_id: "",
slave_id: "9c7ac89c-0410-4a12-be32-ff758a7997f2-S6",
state: "TASK_RUNNING",
resources: {
cpus: 0.1,
disk: 0,
mem: 256,
ports: "[30636-30636]"
},
statuses: [
{
state: "TASK_RUNNING",
timestamp: 1467805454.02181,
labels: [
{
key: "Docker.NetworkSettings.IPAddress",
value: "10.148.228.174"
}
],
container_status: {
network_infos: [
{
ip_address: "10.148.228.174",
ip_addresses: [
{
ip_address: "10.148.228.174"
}
]
}
]
},
healthy: true
}`

Could anybody look this?

**Comment by brat002** [comment]
Please, reopen bug.

**Comment by brat002** [comment]
Another problem - containers randomly losts own health status in Marathon, but Mesos still write health: true to their stdout/stderr's.

**Comment by tsydd** [comment]
#4094 should fix it

**Comment by davent** [comment]
As 1.2 is currently in RC6 will this fix make it in to the release?
