### ISSUE TITLE
version 1.1.1 returns different JSON response on /v2/deployments

### ISSUE THREAD

**Issue by kesselborn** [mesosphere/marathon#3965]
Sorry to create a new bug, but it's not possible to re-open mesosphere/marathon#3820 . Please see [this comment that describes why the bug is not fixed yet](https://github.com/mesosphere/marathon/issues/3820#issuecomment-222201282).
The problem is, that -- contrary to the documentation -- the response in version 1.1 changed in the following way:

```
    1 pre 1.1:                                   |    1 1.1:
    2 ----------------------------------------   |    2 ----------------------------------------
    3                                            |    3
    4 [                                          |    4 [
    5   {                                        |    5   {
    6    ...                                     |    6     ...
    7     "steps": [                             |    7     "steps": [
    8       [                                    |    8       {
    9                                            |    9         "actions": [
   10         {                                  |   10           {
   11           "action": "StartApplication",    |   11             "type": "StartApplication",
   12           "app": "/foo"                    |   12             "app": "/foo"
   13         }                                  |   13           }
   14                                            |   14         ]
   15       ],                                   |   15       },
   16       [                                    |   16       {
   17                                            |   17         "actions": [
   18         {                                  |   18           {
   19           "action": "ScaleApplication",    |   19             "type": "ScaleApplication",
   20           "app": "/foo"                    |   20             "app": "/foo"
   21         }                                  |   21           }
   22       ]                                    |   22         ]
   23                                            |   23       }
   24     ],                                     |   24     ],
   25     ...                                    |   25     ...
   26 ]                                          |   26 ]
 
 ```

I guess it's a bug in the implementation and not in the documentation, but not sure about  this. Note that projects already [build fixes around this behaviour](https://github.com/gambol99/go-marathon/pull/158) which is not really desirable I think.

**Comment by afraisse** [comment]
Stumbled upon this while using mesosphere/marathon-client to get deployments. Correct me if I'm wrong, but isn't the 1.1 version of the API more meaningful and fluent than the previous one ?

**Comment by kesselborn** [comment]
@afraisse the problem is not which response is more meaningful but which response is the correct one. Currently, the api change is not documented and it is not clear whether the change was intended or not.

**Comment by afraisse** [comment]
What I meant is I'm rooting for the change to be documented, instead of being reverted.

**Comment by kesselborn** [comment]
@afraisse ah, ok ... fair enough :)

**Comment by timoreimann** [comment]
@gkleiman could you provide some feedback on this one? You marked it as a bug and set the milestone to 1.2. Does this mean we are going to go back to the old implementation?

I understand that you guys have a lot of issues, but some indication on how this issue is going to be handled would be super helpful and appropriate.

**Comment by aquamatthias** [comment]
@kesselborn @afraisse @timoreimann This is an unintended change that has been introduced with Marathon 1.1 while implementing readiness checks. At that point in time I would also suggest to keep this change and document it. WDYT?

**Comment by timoreimann** [comment]
@aquamatthias Personally, I'm fine with sticking to the status quo. My organization primarily talks to Marathon through [go-marathon](https://github.com/gambol99/go-marathon) which has added support for the API change. Plus, the change occurred during the transition from 0.x to 1.x which is more tolerable to me.

If anyone expresses strong feelings towards the old format though, I'd be happy to follow the revert road as well.

**Comment by afraisse** [comment]
Same here. We use the Java marathon-client  and they already have accepted my PR introducing support for the change. 

We can also go back to the old version easily though.

**Comment by aquamatthias** [comment]
I will update the example json to meet this new structure.

**Comment by aquamatthias** [comment]
Examples are updated
