### ISSUE TITLE
Error restarting Application: [object Object]

### ISSUE THREAD

**Issue by magcius** [mesosphere/marathon#3966]
We have been seeing this bizarre issue when trying to restart certain services. There seems to be no rhyme or reason to which services give the error, but we have to scale to 0 and then back up to 1.

Screenshot:
![Screenshot](https://cloud.githubusercontent.com/assets/40890/15868509/038d45c8-2c9d-11e6-87d8-5e2d1fa88f49.png)

**Version**: 0.15.2

Additional information just in case:

![additional info](https://cloud.githubusercontent.com/assets/40890/15868498/f14ed8b8-2c9c-11e6-91c4-48699486c295.png)

**Comment by magcius** [comment]
I found some slight information on what's going on here.

We first PUT to `v2/apps//db-build-ingest-simple-image-worker/restart`. This causes a 301 Moved Permanently to `v2/apps/db-build-ingest-simple-image-worker/restart`. But the semantics of 301 is that the new request is made as a GET, not as a PUT. The server returns 405 Method Not Allowed for the new GET, and the client code doesn't know what's going on here.

Why the initial URL is bizarre, and why the server is returning a 301 instead of a 307, I'm not sure.

**Comment by magcius** [comment]
The issue seems to be that our application ID starts with `/`, e.g. `/db-build-ingest-simple-image-worker`. I think this is because we migrated from a Marathon without groups, and then moved to one that has it.

Are application IDs that start with `/` supposed to be supported? If so, how should they behave in the API?

**Comment by magcius** [comment]
Oh, actually, it's because we are putting Marathon behind OAuth2Proxy for security reasons, and OAuth2Proxy is broken if URLs have double slashes: https://github.com/bitly/oauth2_proxy/issues/179

Sorry for the noise, this isn't a Marathon bug at all! That said, double slashes are a bit unusual and it would be nice to urlencode the URL to `/%2F`, which I imagine might get past OAuth2Proxy.

**Comment by jdef** [comment]
this doesn't seem to be a marathon bug, closing out. please re-open if you think there's a marathon bug here
