### ISSUE TITLE
change build.scala to build.sbt

### ISSUE THREAD

**Issue by shijinkui** [mesosphere/marathon#3967]
move build.scala to root build.sbt

**Comment by jasongilanfarr** [comment]
As stated in the PR, we do prefer the .scala edition over the .sbt edition of the build. If there is a highly compelling reason to move over to the .sbt edition, please reopen.

**Comment by shijinkui** [comment]
hey @jasongilanfarr ,thank for review. At the newer sbt version, build.sbt is the recommended style, support multi-project.

http://www.scala-sbt.org/0.13/docs/Full-Def.html
>This page describes an old style of .scala build definition. In the previous versions of sbt, .scala was the only way to create multi-project build definition, but sbt 0.13 added multi-project .sbt build definition, which is the recommended style.
