### ISSUE TITLE
Only 1 Health Check pass required to be "healthy"

### ISSUE THREAD

**Issue by davent** [mesosphere/marathon#3969]
If you specify multiple COMMAND health checks for an app then the said app will be marked as 'healthy' even if one of the checks fails.

This can be replicated by creating a task with 2 or more COMMAND health checks. Edit one check to purposefully fail. The app should restart and will come back up as healthy. If you make all the checks purposefully fail then the app will restart as unhealthy.

**Comment by andrebeat** [comment]
This has already been reported before #1445.

**Comment by gkleiman** [comment]
Closing as a duplicated of #1445.

**Comment by scbunn** [comment]
Is this actually being working on? #1445 is marked closed?
