### ISSUE TITLE
Detailed docs on labels

### ISSUE THREAD

**Issue by mhausenblas** [mesosphere/marathon#3978]
We don't really explain what labels are and how to use them. ATM, they are only mentioned on an [outdated page](https://mesosphere.github.io/marathon/docs/rest-api.html). As a reference, see how [Docker](https://docs.docker.com/engine/userguide/labels-custom-metadata/) and [K8S](http://kubernetes.io/docs/user-guide/labels/) address this in detail.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1927. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
