### ISSUE TITLE
Marathon doesn't install on Debian 8.5

### ISSUE THREAD

**Issue by hdep** [mesosphere/marathon#3983]
Hello,

I am following the tutorial from : https://open.mesosphere.com/getting-started/install/

When I want to install marathon package it is looking for : 
marathon : DÃ©pend: java8-runtime-headless mais il n'est pas installable

There is no java8-runtime-headless package available on Debian.

Regards,

**Comment by jlferrer** [comment]
This is not related to marathon,

you have to add jessie-backports apt sources:

- https://backports.debian.org/Instructions/
- https://packages.debian.org/jessie-backports/java8-runtime-headless

**Comment by hdep** [comment]
I'm not sure that building a debian package with depends on package that doesn exist does on the system is good idea. Anyway this is not my concern.

The following documentation doesn't reflect this : 

https://open.mesosphere.com/getting-started/install/

Thank you for the tips.
