### ISSUE TITLE
Marathon 1.1.1 Health Checks are Failing intermittently

### ISSUE THREAD

**Issue by raghu999** [mesosphere/marathon#3990]
Hello,
    We have a issue where we see our app health checks are failing intermittently when the slaves are re-registered or the masters are restarted. Is there a Known issue in 1.1.1.

**Comment by gkleiman** [comment]
This is not a known issue, can you please add some relevant logs?

What kind of health checks are you using (`COMMAND` or `HTTP`)?

**Comment by raghu999** [comment]
Here is what we observed in TCP Health check if we add this line to TCP health check in JSON `ignoreHttp1xx: false` the health checks are failing . When we remove the same Health Checks are passing . One more observation is  even if we edit `ignoreHttp1xx:false` out from JSON Marathon will add it we can confirm by selecting Json Mode in UI. 
```
{
  "portIndex": 0,
  "protocol": "TCP",
  "gracePeriodSeconds": 300,
  "intervalSeconds": 60,
  "timeoutSeconds": 20,
  "maxConsecutiveFailures": 3,
 "ignoreHttp1xx": false
}
```
