### ISSUE TITLE
Can configure multiple apps to use the same service port

### ISSUE THREAD

**Issue by fiskl** [mesosphere/marathon#3999]
When using JSON mode to set the service port it is possible to use the same service port as an existing app.

No errors are shown, and there is indication in the UI that a problem exists.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2359. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
