### ISSUE TITLE
Also create 'PORT_<NAME>' env variables for ports defined in port mappings

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#4005]
Right now, `PORT_<NAME>` env variables are only added for ports defined in `portDefinitions`, but not for ports defined in `portMappings`.

cc/ @jdef @jasongilanfarr

**Comment by kensipe** [comment]
It looks like https://github.com/mesosphere/marathon/pull/4008 fixes this.  can we close this @gkleiman ?

**Comment by gkleiman** [comment]
There's still a TODO in the code, so we might not be generating the named env vars in all cases:

https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/mesos/TaskBuilder.scala#L420

**Comment by aquamatthias** [comment]
@jdef can you fix this TODO?

**Comment by jeschkies** [comment]
It seems the case @gkleiman mentions is related to #4183. Can you verify this @jdef?

**Comment by jdef** [comment]
I guess I wouldn't consider them closely related. But they should both be
addressed
