### ISSUE TITLE
Feature Request: Hook for Shutdown of Frameworks

### ISSUE THREAD

**Issue by fceller** [mesosphere/marathon#4007]
When a framework is shutdown, that has created persistent volumes or made dynamic reservation, it should be possible, that a hook of some sort is called, so that the framework can cleanup (ie. unreserve the dynamic reservations, free the persistent disks).

What can happen is, that the user sees the ArangoDB in Marathon and there is a "destroy" this will shut down the framework without giving it a chance to cleanup.

**Comment by toddleo** [comment]
any progress or plans on solving this? From a user stand point I reckon this is an essential feature.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1861. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
