### ISSUE TITLE
Feature request: Non-UI (API only) mode

### ISSUE THREAD

**Issue by okuryu** [mesosphere/marathon#4010]
I'm running Marathon with an own Marathon authentication plugin. The plugin requires HTTP header to authenticate from clients. In this situation, if I try to open Marathon UI in my browser, Marathon UI returns errors to failed fetch apps data because my guess that Marathon UI calls Marathon API to fetch data and Marathon API requires authentications by the plugin, right?

In this case, if Marathon API with plugins works as expected, but Marathon UI doesn't work well anymore. Depending on plugins to use, this means that Marathon UI doesn't work correctly. I think any alternative way are reasonable for these cases like non-UI mode, API only mode, or non-fetching data UI mode.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2092. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
