### ISSUE TITLE
`"acceptedResourceRoles": [""]` is not being caught

### ISSUE THREAD

**Issue by lloesche** [mesosphere/marathon#4011]
I can provide `"acceptedResourceRoles": [""]` and it's not caught in Marathon, while `"acceptedResourceRoles": []` is.

**Comment by kensipe** [comment]
@lloesche when you say "not caught" does that mean that marathon ignores it?

**Comment by lloesche** [comment]
Instead of throwing an error it accepts the invalid role name.
What I saw was a user trying to remove the default role of the marathon-lb Docker container slave_public by setting it to an empty string ''. However this didn't have the desired behaviour (what he needed was '*'). But instead of getting an error his invalid config was accepted and the task got stuck in waiting since Marathon never received a resource offer matching that role.

**Comment by kensipe** [comment]
thanks!  we are working on a solution!

**Comment by jasongilanfarr** [comment]
I believe we need to add a validation to ensure `for all resource roles, the value is non-empty`

**Comment by mpark** [comment]
#4067
