### ISSUE TITLE
Add log rotation to the Marathon Docker container

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#4013]
Marathon logs are currently not being rotated. We've already seen user switching the logging level to WARN in order to prevent Marathon from running out of space. This makes it very hard to debug issues.

Marathon's Docker container should ship with log rotation set up out-of-the-box.

**Comment by kensipe** [comment]
@gkleiman I'm new to the project so I could be missing something.  It looks like marathon's logging uses `logback`.    It would be easy to setup a rotation HOWEVER it also appears that marathon logs everything to `stdout`.     we would need to convert this to a file based model if this is the case.

**Comment by gkleiman** [comment]
@kensipe Marathon's current logs are too verbose, and given that it logs to stdout, some users have to change the logging level to WARN to avoid running out of space. This makes it very difficult to debug issues.

I think that the right solution would be to add a logback configuration to the container, that uses file logging + rotation.

This ticket only mentions the Docker container, but we should do something similar for DC/OS, which uses journald for the base Marathon. We've observed that journald easily gets overwhelmed, dropping logs when they're most needed.

**Comment by jasongilanfarr** [comment]
I personally don't agree with this issue and I don't think the correct
resolution is within our container. Instead, I believe that the logs should
defer to however docker is configured. So if you're deploying marathon in
production without DCOS we may want to give some recommendations for
production logging (maybe even writing a Kafka logback appender that can be
turned on via config to integrate into a relatively standard Kafka->ELK
stack).

I'd hope we do something in DCOS that is relatively standard (e.g.
Kakfa->ELK).

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2469. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
