### ISSUE TITLE
Marathon 1.2.0-rc Docker Images Broken

### ISSUE THREAD

**Issue by djosborne** [mesosphere/marathon#4024]
The docker images for both `mesosphere/marathon:v1.2.0-rc1` and `mesosphere/marathon:v1.2.0-rc2` are broken. `mesosphere/marathon:latest-dev` as well.

rc1 and latest-dev fail when launching an application with the message: `java.lang.UnsatisfiedLinkError: Mesos JAR version 1.0.0-rc1 is not backwards compatible with Mesos native library version 0.28.2`

rc2 fails on start with the message: `Failed to load native Mesos library from /usr/lib/libmesos.so
[2016-06-23 17:01:26,306] ERROR Fatal error while trying to take over leadership. Exit now. (mesosphere.marathon.core.election.impl.CuratorElectionService:ForkJoinPool-2-worker-13-EventThread)
java.lang.UnsatisfiedLinkError: /usr/lib/libmesos-1.0.0.so: libevent_openssl-2.0.so.5: cannot open shared object file: No such file or directory`

**Comment by djosborne** [comment]
Reason is likely that 0.28.0 is installed in the Dockerfile: https://github.com/mesosphere/marathon/blob/master/Dockerfile#L18

Are you folks waiting for an official cut of 1.0.0? Or should I open up a PR to make the Dockerfile match Dockerfile.development which uses `mesos=1.0.0-1.0.52.rc1.debian81`

**Comment by kensipe** [comment]
rc1 and rc2 were "soft" releases (unannounced) as we transition to Mesos 1.0.   It requires the latest version of mesos.  You can find details here: https://github.com/mesosphere/marathon/issues/4015

We are waiting on the Mesos release... which should be shortly.

**Comment by bobrik** [comment]
@kensipe does "soft" mean "definitely not working"? I don't see why not change base image to RC mesos for RC marathon.

**Comment by Morsicus** [comment]
mesosphere/marathon:v1.2.0-rc3 pushed on docker-hub yesterday. Looks like this version fix your issue.

**Comment by bobrik** [comment]
Yeah, I updated mesos-compose a few hours ago: https://github.com/bobrik/mesos-compose/pull/14
