### ISSUE TITLE
Delete (rollback) deployment is dangerous

### ISSUE THREAD

**Issue by janisz** [mesosphere/marathon#4046]
Let's consider situation when application is running and is healthy. Let the deployment be scheduled. New version of app cannot be started (for whatever) reason. Then user delete the deployments (by clicking rollback in UI or just sending DELETE on endpoint without force). Let assume that app cannot be redeployed (e.g. artifact is unavailable). After this procedure user end up with 0 running instances!

**Example:**
1. `resource we can control` is an URL of http server accesible from mesos agents that we can start/stop on demand (e.g. `python -m SimpleHTTPServer` on local machine)
2. Deploy application
   
   ``` json
   {
     "id": "/rollbacktest",
     "cmd": "sleep 30 && wget <resource we can control> && python -m SimpleHTTPServer $PORT0",
     "cpus": 0.1,
     "mem": 32,
     "disk": 0,
     "instances": 5,
     "healthChecks": [
       {
         "path": "/",
         "protocol": "HTTP",
         "portIndex": 0,
         "gracePeriodSeconds": 5,
         "intervalSeconds": 60,
         "timeoutSeconds": 20,
         "maxConsecutiveFailures": 3,
         "ignoreHttp1xx": false
       }
     ],
     "portDefinitions": [
       {
         "port": 10486,
         "protocol": "tcp",
         "labels": {}
       }
     ]
   }
   ```
3. Update this application
   
   ``` json
   {
     "id": "/rollbacktest",
     "cmd": "sleep 30 && wget <resource we can control> && fail",
     "cpus": 0.1,
     "mem": 32,
     "disk": 0,
     "instances": 5,
     "healthChecks": [
       {
         "path": "/",
         "protocol": "HTTP",
         "portIndex": 0,
         "gracePeriodSeconds": 5,
         "intervalSeconds": 60,
         "timeoutSeconds": 20,
         "maxConsecutiveFailures": 3,
         "ignoreHttp1xx": false
       }
     ],
     "portDefinitions": [
       {
         "port": 10486,
         "protocol": "tcp",
         "labels": {}
       }
     ]
   }
   ```
4. Application is failing.
5. Disable `resource we can control`.
6. Rollback to previous version.
7. We end up with 0 running tasks.

IMO when user want to rollback deployment, expected behavior will be to do not restart currently running application if has same version as version we want to rollback. Or behave as normal deployment and take in to account `upgradeStrategy` settings.

Releated to: #1554

**Comment by meichstedt** [comment]
Hi @janisz, thanks for reporting this.

I'd be interested in your thoughts (and the opinion of others as well, of course): which options exactly would you expect here? As described in #3954, I don't think that a rollback or even an automatic rollback are valid options in this scenario. So instead of defining what we would expect _when rolling back a deployment_, I'd rather tackle the question _what do we expect in case of a failing deployment_.

1. let the deployment fail after a timeout and keep all running tasks no matter their version
1. let the deployment fail after a timeout and kill all tasks that are of the _new_ version
1. let the deployment fail after a timeout and kill all tasks that are **not** of the new version

... other options? We'll try to improve the deployment logic in the near future, so every input is appreciated.

**Comment by kamilchm** [comment]
4. don't kill running task that was started from the same version that you try to rolllback?

**Comment by janisz** [comment]
Internally we implemented stop deployment in our CI when deployments takes more time than expected. Unfortunately it was possible to rollback deployment from API/UI so we decided to rewrite `DELETE  /v2/deployments/[0-8a-b-]` → `DELETE  /v2/deployments/[0-8a-b-]?force=true`.

I'm not a fan of making the deployment fail. The criteria could vary between applications e.g., different timeouts. I'd rather leave it up to users to manually decide when it's broken. In Continuous Delivery world breaking deployment is something unusual and should be treated with special care.

My only concern is rollback functionality. Deleting all apps without taking care of `minimumHealthCapacity` is not acceptable. Ideally when I wan't to redeploy a version that was deployed previously and it's tasks are still running then they should not be touched (could be killed if needed to meet instances count) only new task should be spawned. But I understand approach in which all task are wiped out and spawning again. Maybe marathon should allow user to chose desired strategy [like kubernetes](https://github.com/kubernetes/kubernetes/blob/master/docs/proposals/deployment.md#deployment-strategies). Actually Marathon do give a choice. User can do:
* Rolling update — stop the deployment with  `DELETE /deployments/<deployment id>?force=true` and redeploy application
* Recreate — just use  `DELETE /deployments/<deployment id>`

Finally, I think separated `Rollback` section could close this issue.

**Comment by janisz** [comment]
I did some research on how to fix this behavior [here](https://github.com/janisz/marathon/commit/90f67ac7254a6e220919dbc72e42b353404c200a) but unfortunately I failed and can't see easy way to do it :(

**Comment by kamilchm** [comment]
What are the problems?

**Comment by janisz** [comment]
I've tried to reproduce this issue using [latest](https://github.com/mesosphere/marathon/commit/668695f) Mesos and it looks like problem was solved

**Comment by wleese** [comment]
We've hit this bug too. Which version is recommended?

**Comment by aquamatthias** [comment]
Marathon 1.4 will filter the list of running tasks and only replace tasks that are not already replaced. 
@janisz can you try this version?

**Comment by janisz** [comment]
@aquamatthias I followed steps I described https://github.com/mesosphere/marathon/issues/4046#issue-163117891 and it's not working. Rollback creates new deployment but it's not working. Applications are replaced even if they are in proper version and should not be touched.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2340. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2340. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
