### ISSUE TITLE
Critical error with Marathon-UI causing surprising docker parameter loss

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#4051]
We have Marathon 1.1.1 deployed and are experiencing an issue with Marathon-UI in which Docker parameters are wiped out if the docker container name is momentarily deleted. Worse, it does it in a hidden way, such that is not visible unless if you switch to JSON mode.

http://screencast.com/t/VWiGvN8vR

**Comment by timcharper** [comment]
This was actually reproduced with a build which included Marathon UI 1.2.0-SNAPSHOT. I'm testing to confirm if it exists in Marathon-UI 1.1.3 right now

**Comment by timcharper** [comment]
I've confirmed that this bug exists with the latest build of Marathon (built from 668695f9)

**Comment by timcharper** [comment]
The cause is here:

https://github.com/mesosphere/marathon-ui/blob/701ca80041917bc4fec0ab3ccfa160f0826af544/src/js/stores/transforms/AppFormModelPostProcess.js#L36

I understand why this code exists, but there are two problems:

- The post process trigger updates a state tree that is not visible to the user (it seems unfortunate that there are two independent representations of the state here).
- Determining whether or not the container branch of config should exist solely on the non-blankness of the image parameter is a frustration indeed.

I think there might be two fixes:

a) Fire the `Image` value change event on field blur, instead of on field change. Update the code to propagate application state to the form state when this deletion occurs so the value deletion is visible to the user
b) Add a form checkbox for "use docker". Only delete this state when use docker is set to false. Assume "use docker" value is true if container exists.

**Comment by aquamatthias** [comment]
@orlandohohmeier can you look into this issue?

**Comment by aquamatthias** [comment]
@orlandohohmeier any update here?

**Comment by marcomonaco** [comment]
We need to move this to our next release due to priority decisions. I will label with 1.5.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1792. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1792. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
