### ISSUE TITLE
Marathon Version difficult to see in "About"

### ISSUE THREAD

**Issue by djosborne** [mesosphere/marathon#4053]
![screenshot from 2016-06-30 14-01-51](https://cloud.githubusercontent.com/assets/3444362/16504163/62a32b28-3ecb-11e6-8803-305c2b23ed18.png)

Very hard to see the grey on blue

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1729. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1729. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
