### ISSUE TITLE
Can't specify discovery info for Docker User Network

### ISSUE THREAD

**Issue by djosborne** [mesosphere/marathon#4054]
Trying to launch the following application JSON yields the error: `/ipAddress: ipAddress/discovery is not allowed for Docker containers using BRIDGE or USER networks`:

```
{
  "id": "test-1",
  "cpus": 0.1,
  "mem": 64,
  "instances": 1,
  "container": {
    "docker": {
      "image": "nginx",
      "network": "USER"
    },
    "type": "DOCKER"
  },
  "ipAddress": {
      "networkName": "test",
      "discovery": {
          "ports": [
            { "number": 80, "name": "http", "protocol": "tcp" }
          ]
      }
  },
  "healthChecks": [
    {
      "protocol": "HTTP",
      "path": "/",
      "port": 80,
      "gracePeriodSeconds": 300,
      "intervalSeconds": 60,
      "timeoutSeconds": 20,
      "maxConsecutiveFailures": 3
    }
  ]
}
```

Why is discovery info blocked for Docker User networks?

**Comment by jdef** [comment]
should be possible to specify discovery information via portMappings; can you try that instead?

**Comment by aquamatthias** [comment]
@jdef any update here?

**Comment by djosborne** [comment]
It seems like specifiying port information in PortMappings instead of DiscoveryInfo does allow the necessary information to be stored in Marathon.

However, now that the location has changed, Marathon-LB is failing to balance to these tasks, since it checks DiscoveryInfo for ip-per-container tasks.

I would have liked to get Marathon-LB working before closing this issue...

**Comment by djosborne** [comment]
@brndnmtthws adjusted Marathon-LB to expect the information in the new location. All is working!

**Comment by aquamatthias** [comment]
@djosborne great to hear!
