### ISSUE TITLE
Option to lift one instance limit for apps using DVDI external volumes

### ISSUE THREAD

**Issue by drewrobb** [mesosphere/marathon#4055]
We would like to use the [netshare](netshare.containx.io) volume driver with the nfs based AWS EFS service for marathon apps. In this case there is no good reason (that I am aware of) to have a [constraint of only one app instance](https://github.com/mesosphere/marathon/blob/d39289e3663eae0876541b0d748057b0625c753e/src/main/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProvider.scala#L147) because the nfs mount is designed to be mountable in multiple places at once. In our test environment we simply removed this validator in a patched marathon and didn't encounter any problems. However I think some kind of option in the volume configuration would be a better design for my feature request so that people using other volume drivers don't have issues.

Thanks!

**Comment by gkleiman** [comment]
cc/ @meichstedt

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1750. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1750. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
