### ISSUE TITLE
forceful operations effective on empty 'force' query parameter value

### ISSUE THREAD

**Issue by timoreimann** [mesosphere/marathon#4056]
Being a boolean type, The `force` query parameter available to PUT or DELETE requests should only become effective if its value is set to _true_. At least on Marathon 1.1.1, however, operations are also forced if the content of the query parameter is left empty. That is, a request of the kind

`http://my-mesos-master:8080/v2/apps/myapp?force=`

triggers a forceful deployment. My suggestion would be to fall back to the unforceful mode if the value is anything different to _true_. This would provide a safety net for those scenarios where the URL is constructed programmatically and the force parameter value is dropped inadvertently (as happened in my case and led me to this defect report).

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1688. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1688. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
