### ISSUE TITLE
Proposal: generate MARATHON_NETWORK_NAME envvar when networkInfo.name is not empty

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#4065]
Frameworks running as apps in Marathon may be configured to run on a particular virtual network. If that framework launches tasks then those tasks should _likely_ be configured to run on the same virtual network. In order to accomplish this the framework needs to discover the name of the virtual network upon which it is running.

Proposal:
- Marathon will generate a `MARATHON_NETWORK_NAME` environment variable that captures the name of the network (see mesos protobuf field `NetworkInfo.name`) only if it is non-empty
- update Docs to reflect the change
  - https://mesosphere.github.io/marathon/docs/task-environment-vars.html
- since this is an auto-generated envvar it should probably pick up any user-specified prefix (see command line flags)

/cc @gkleiman @sargun @mgummelt @adam-mesos

**Comment by adam-mesos** [comment]
But then if those apps/tasks register with Mesos as a scheduler themselves (e.g. Spark), how do they know to pass the network name on to the tasks they launch?

**Comment by mgummelt** [comment]
Rather than forcing the scheduler to tell its tasks what network they're in, can't we do this at the Mesos level?  Mesos could look at the network the scheduler is running in, and by default launch tasks in that network.

**Comment by mgummelt** [comment]
Yea, I figured, but I think that's the correct solution.  For example, your OS knows that your process is running as `adam`, so it knows to implicitly launch subprocesses under `adam`.

**Comment by jdef** [comment]
Marathon has also been asked to support apps belonging to multiple container networks. So we'd need a slightly different envvar naming scheme to accommodate.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2100. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2100. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
