### ISSUE TITLE
Keep deployments for a while after completion [was: How can I get the status or the result of a deployment by the deploymentId ?]

### ISSUE THREAD

**Issue by gohonsen** [mesosphere/marathon#4072]
When I send a post request to /v2/apps, I get a deploymentId from the response, I want to know the status of the deployment, and if it was sucessfully finished or if it was failed. 
GET /v2/deployments  only list the running deployments,  if the deployment is finished, GET /v2/deployments/{deploymentId}  is useless, there's no API to get it.  How can I get the status or the result of a deployment by the deployment id ? thanks!

**Comment by gkleiman** [comment]
@gohonsen deployments are sadly removed once they're completed, so it is not possible to get the status of a completed deployment.

**Comment by gohonsen** [comment]
Thanks.Actually, I do not know what the purpose of remove the completed deployment,
I would like to suggest that you can provide an api to get all the deployments' history, 
it's better than "Keep deployments for a while after completion" in my mind. What do you think ?

**Comment by jasongilanfarr** [comment]
This is something I also would like to see us do; however, I'm concerned
that the growth of "permanent deployment history" may be a bit out of the
scope of marathon. Instead, imagine the history is available for N minutes
after completion. One could then archive (with a second process) the
historical data to a longer term solution such as Kafka, Cassandra, HDFS,
elastic search, etc. it may be worth considering having the event stream
have a publisher plugin to do this (but if marathon published this data and
retained it for a small amount of time, another service could fulfill this
role).

Would something like this sufficiently satisfy what you're asking for? If
you could describe "your ideal solution", what would it do?

**Comment by gohonsen** [comment]
@jasongilanfarr  I think if the deployments were created by marathon, we should view the deployments' lifecycle(start, running, completed successfully, failed) by marathon, too.
Keep deployments for a while after completion could let me know the result (I can request every few seconds and save the result), that's also ok.  thanks.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2171. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2171. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
