### ISSUE TITLE
Fronting an application using HOST network mode with Marathon-LB does not work

### ISSUE THREAD

**Issue by isurulucky** [mesosphere/marathon#4074]
Hi, 

I have a application [1], which is using HOST network. I would like to expose some of the port via the marathon load balancer. Added the HAPROXY_GROUP, but seems the haproxy is not picking up the application. Any idea on what is happening here?

[1].
{
    "id": "xxxx",
    "cpus": 0.5,
    "mem": 1024.0,
    "instances": 1,
    "executor": "",
    "container": {
        "type": "DOCKER",
        "docker": {
            "image": "xxxx:1.0.0",
            "network": "HOST",
            "portMappings": [
                {
                    "protocol": "tcp",
                    "containerPort": 4000,
                    "servicePort": 10060,
                    "hostPort": 4000
                },
                {
                    "protocol": "tcp",
                    "containerPort": 11224,
                    "servicePort": 10176,
                    "hostPort": 11224
                }
            ]
        }
    },
    "portDefinitions": [
      {
        "port": 4000,
        "protocol": "tcp"
      },
      {
        "port": 11224,
        "protocol": "tcp"
      }
    ],
    "requirePorts": true,
    "healthChecks": [
      {
        "portIndex": 1
      }
    ],
    "labels": {
        "HAPROXY_GROUP": "marathon-lb"
    }
}

**Comment by gkleiman** [comment]
@isurulucky the best place to get help with marathon-lb is in its repo. Please create an issue in https://github.com/mesosphere/marathon-lb/issues
