### ISSUE TITLE
tasks turn into ipless ghosts after killing agent

### ISSUE THREAD

**Issue by vixns** [mesosphere/marathon#4076]
Using HEAD marathon + mesos containers and network/cni, when rebooting a mesos-agent node, all previous tasks still exists in marathon, but no longer exists on mesos and cannot be killed from the UI.

The only way i found to get rid of them was to delete entries in zookeeper and restart marathon.

a task's life in zookeeper :

`/marathon/state/task:mysql_node.6d20d829-4381-11e6-bb22-8a8e927fff55`

Creation:

`4task:mysql_node.6d20d829-4381-11e6-bb22-8a8e927fff55$1a4a7bd9-ba30-420a-814a-42b222dff0e0� /mysql_node.6d20d829-4381-11e6-bb22-8a8e927fff55 10.35.0.12" scope* internal" type* master(�����*B2016-07-06T13:42:17.410ZR) '419772c4-f0f0-458a-ba21-8c32840de358-S0` 

Green:

`4task:mysql_node.6d20d829-4381-11e6-bb22-8a8e927fff55$31613461-3762-6439-2d62-6133302d3432� /mysql_node.6d20d829-4381-11e6-bb22-8a8e927fff55 10.35.0.12" scope* internal" type* master(�����*0�����*B2016-07-06T13:42:17.410ZJ� 1 /mysql_node.6d20d829-4381-11e6-bb22-8a8e927fff55*) '419772c4-f0f0-458a-ba21-8c32840de358-S01�o�C��A:1 /mysql_node.6d20d829-4381-11e6-bb22-8a8e927fff55HZ��h:�Eі�n7���"j "*10.135.6.182vlanR) '419772c4-f0f0-458a-ba21-8c32840de358-S0`

After killing the agent:

`4task:mysql_node.6d20d829-4381-11e6-bb22-8a8e927fff55$33313631-3334-3631-2d33-3736322d3634� /mysql_node.6d20d829-4381-11e6-bb22-8a8e927fff55 10.35.0.12" scope* internal" type* master(�����*0�����*B2016-07-06T13:42:17.410ZJ� 1 /mysql_node.6d20d829-4381-11e6-bb22-8a8e927fff55"0Slave 10.35.0.12 removed: health check timed out*) '419772c4-f0f0-458a-ba21-8c32840de358-S01O������AHPR) '419772c4-f0f0-458a-ba21-8c32840de358-S0`

**Comment by meichstedt** [comment]
Most probably related to the root cause of #4039 (the tasks are lost but not expunged from state)

**Comment by meichstedt** [comment]
Hey @vixns has this been resolved for you?

**Comment by vixns** [comment]
yes, I still have some tasks in bad states on early clusters setup, when restarting masters / agents / marathon are frequent and dns not fully operational.
Anyway, killing these in marathon ui do the job, I no longer have this issue.
