### ISSUE TITLE
Consider encrypting records for safe-keeping in Zookeeper

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#4078]
Marathon has the keys to the kingdom, and Zookeeper is not secure. Even though there is authentication, it is not over SSL (yet), and when SSL arrives, inter-node chatter will not be secure.

I suggest that secrets are encrypted with a symmetric key to both prevent tampering and reading of marathon data.

**Comment by timcharper** [comment]
@gkleiman Is this tagging indication that such a feature would be welcomed? As in if I did the work to implement it would it have a chance of getting merged if the code quality were to par?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2107. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2107. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
