### ISSUE TITLE
Add integration tests for Docker External Volumes

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#4082]
There's no integration test for Docker External Volumes, making it very hard to be confident of code changes related to this functionality.

**Comment by jdef** [comment]
To be clear: there's a dc/os integration test that exercises the mesos containerizer (w/ docker vol isolator) and external volumes. What's missing is a dc/os integration test that leverages the docker containerizer + external vols.

**Comment by jdef** [comment]
xref https://github.com/dcos/dcos/pull/220/files#diff-e68bd6cbb63a4d94e426ca8692c4eae6R938

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1823. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1823. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
