### ISSUE TITLE
Add integration tests for IP-per-Task support

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#4083]
This wasn't done at the time that IP-per-Task support was added, because it wasn't clear how to start a Mesos cluster with IP-per-Task support.

Since DC/OS will ship with overlay networking out of the box, we should make sure that this functionality is covered by a Marathon or a DC/OS integration test.

**Comment by jdef** [comment]
Pretty sure that someone wrote a dc/os integration test for this. I've forwarded this to Avinash for feedback

**Comment by jdef** [comment]
https://github.com/dcos/dcos/commit/1ad4d55979c342a5da21bde57f3dba4176f500a6

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2043. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2043. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
