### ISSUE TITLE
Question: Command health checks results on dockerized apps

### ISSUE THREAD

**Issue by Spritekin** [mesosphere/marathon#4090]
Hi,
The health checks docs specify:
A health check is considered passing if (1) its HTTP response code is between 200 and 399, inclusive, and (2) its response is received within the timeoutSeconds period.

This is true for HTTP checks, but the docs say nothing for COMMAND checks. Does this mean only (2) is valid for a COMMAND health check. Is the command result ignored?

I ask this because I have a curl command working in the container as the health chech. It was working fine but someone in my company introduced an invalid character and the curl started failing. However even when curl was failing, the health check passed. 

So the COMMAND check only cares about having a response in the allocated time, it doesn't care if the response is a success or a failure.

Is that correct?

**Comment by unterstein** [comment]
Hi @Spritekin,

if you configure a health check based on a COMMAND check, the health check will analyze the exit code of the command. So, if your exit code is not equals 0, the health check will fail.

Hope this helps you and I will close this task now. If you have any further questions or this solution is not working for you, feel free comment on this task and/or e-open the task.

Kind regards
Johannes

**Comment by Spritekin** [comment]
Hi @unterstein 
I will elaborate my doubts on https://github.com/mesosphere/marathon/issues/4091 which is the reason I ask this.
