### ISSUE TITLE
Request: POST/DELETE method on http health checks

### ISSUE THREAD

**Issue by Spritekin** [mesosphere/marathon#4091]
As far as I see, the http health checks use the GET method to retrieve the url.
I would like to request adding a POST (and maybe delete) support so I can send more complex checks to my app. 

For example, I run Docker Swarm as an app. The /info health check responds ok, but the swarm is unable to run a hello-world task. By having a POST support (maybe having a payload attribute) I could write my payload and request to run the hello-world command. If the response is too slow then the health check will fail and service will restart.

Thanks!

**Comment by unterstein** [comment]
Hi @Spritekin,

a possible workaround could be a COMMAND health check using ```curl -XPOST```. I will add this task to our backlog and we will discuss to implement this enhancement.

Does the workaround fits your needs for now? If you have any further questions or this solution is not working for you, feel free to ask further questions.

Kind regards
Johannes

**Comment by Spritekin** [comment]
Hi @unterstein 
Yes, that's what I'm doing right now. I just wanted a cleaner way to do it. As it is now it looks really messy.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2259. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2259. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
