### ISSUE TITLE
error loading logback dependencies

### ISSUE THREAD

**Issue by schmidtjohannes** [mesosphere/marathon#4099]
Hi,
I changed my logback configuration as described here:
https://groups.google.com/forum/#!topic/marathon-framework/0p68uIfpBR4

Starting marathon throws an excepcion:
Caused by: java.lang.ClassNotFoundException: org.codehaus.janino.ScriptEvaluator
But still works fine.

My question is how can I avoid this? Add the jar in marathon-classpath in my server as a short-term solution?
I would be happy if you would add the lib to the build-process (never worked with scala neither with SBT)

Thanks in advance

**Comment by unterstein** [comment]
Hi @schmidtjohannes,

your suggested `short-term` solution ```adding the lib to marathon-classpath``` should work. By default marathon does not enable regular expressions in logback configurations and it is not planned currently to change this behavior.

If you have any further questions or your solution is not working for you, feel free to ask further questions.

Kind regards
Johannes

**Comment by schmidtjohannes** [comment]
Thanks @unterstein for your comments!

The solution was to use --jar the moment I start marathon, so it is
/usr/bin/marathon --jar /my/marathon/libs/commons-compiler-2.7.8.jar:/my/marathon/libs/janino-2.7.8.jar:/usr/bin/marathon
On centos7 the marathon script adds the --jar to the classpath and that is what solved my problem.
