### ISSUE TITLE
Fetch URI with query string

### ISSUE THREAD

**Issue by lmtjalves** [mesosphere/marathon#4100]
When I need to fetch a URI that contains a query string the downloaded file will contain the query string in the name. Is there a way to avoid this? Is it possible to specify the file name?

**Comment by unterstein** [comment]
Hi @lmtjalves,

currently this is not possible, but mesos would allow to specify the file name.  Therefore the marathon API should be enhanced to provide this functionality.

Kind regards
Johannes

**Comment by gkleiman** [comment]
Just leaving this here: https://github.com/apache/mesos/blob/master/include/mesos/mesos.proto#L442
