### ISSUE TITLE
Using marthon artifact store

### ISSUE THREAD

**Issue by nizarq** [mesosphere/marathon#4106]
Hi Folks, 

We have been using labels to save app specific metadata. Is the marathon artifact store a good place to keep cluster level metadata - that is, is there an artifact store per app or there's a single central artifact store?
I'm working on a cloud provisioned cluster running DCOS. How can I tell if an artifact store is configured? 
I did a curl **request**:  curl http://localhost:8080/v2/artifacts
which gave me the **response**: {"message":null}

Does this mean an artifact store is available? If so, I've tried and failed to add something to it using the following curl request. What am I doing wrong (it might be an issue with my curl statement - I haven't used curl too much)?

 curl -F "name=file" -F "filename=@artFile.txt" http://localhost:8080/v2/artifacts -v
-   Trying 127.0.0.1...
- Connected to localhost (127.0.0.1) port 8080 (#0)
  > POST /v2/artifacts HTTP/1.1
  > Host: localhost:8080
  > User-Agent: curl/7.48.0
  > Accept: _/_
  > Content-Length: 302
  > Expect: 100-continue
  > Content-Type: multipart/form-data; boundary=------------------------c4bd2ce547c77c6e
  >
  < HTTP/1.1 100 Continue
  < HTTP/1.1 500 Internal Server Error
  < Date: Sat, 16 Jul 2016 02:24:34 GMT
  < X-Marathon-Leader: http://172.16.0.5:8080
  < Cache-Control: no-cache, no-store, must-revalidate
  < Pragma: no-cache
  < Expires: 0
  < Content-Type: application/json
  < Transfer-Encoding: chunked
  < Server: Jetty(9.3.z-SNAPSHOT)
- HTTP error before end of send, stop sending
  <
- Closing connection 0

**Comment by unterstein** [comment]
Hi @nizarq,

in DC/OS the marathon artifact store is not enabled by default. If you want to use a marathon artifact store, you need to specify this during installation of dc/os.

According to your server responses it would be great if could you provide your marathon logs. There should be a more detailed error message, when no artifact store is enabled.

Thanks
Johannes

**Comment by cmeiklejohn** [comment]
@unterstein How can one enable the artifact store if they are using the Mesosphere provided CloudFormation templates?

**Comment by unterstein** [comment]
Hi @cmeiklejohn,

unfortunately it is not possible to enable the artifact store within CloudFormation templates.

Kind regards
Johannes

**Comment by cmeiklejohn** [comment]
Yes, that should be made clear in the documentation.  We ditched the artifact store and moved completely to S3 instead.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2229. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2229. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
