### ISSUE TITLE
Add integration tests for the http event stream endpoint

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#4108]

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1842. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1842. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
