### ISSUE TITLE
Unable to re-deploy when constraint is unfulfilled

### ISSUE THREAD

**Issue by philwinder** [mesosphere/marathon#4110]
Similar to #2810.

My use case is to provide an edge router on all nodes. To do this I use a UNIQUE hostname constraint and set the number of instances to the number of nodes.

In one of my tests I only use a single VM, but leave the constraint at 3 (for example). If one of the containers die during deployment, they will not be restarted until the constraint is satisfied. I.e. never.

To recreate, create a Meos/marathon (tested with 15.3), with fewer than three worker nodes. Use the following json below:

```
{
  "id": "/example",
  "groups": [
    {
      "id": "/example/constraint",
      "apps": [
        {
          "id": "/example/constraint/test",
          "cpus": 0.1,
          "mem": 128.0,
          "cmd": "sleep 9999999",
          "container": {
            "type": "DOCKER",
            "docker": {
              "image": "alpine",
              "network": "BRIDGE"
            }
          },
          "instances": 3,
          "constraints": [
            [
              "hostname",
              "UNIQUE"
            ]
          ]
        },
        {
          "id": "/example/constraint/fail",
          "cpus": 0.1,
          "mem": 128.0,
          "cmd": "sleep 1 ; exit 0",
          "container": {
            "type": "DOCKER",
            "docker": {
              "image": "alpine",
              "network": "BRIDGE"
            }
          }
        }
      ]
    }
  ]
}
```

Then create the app with `POST /v2/groups`.

Then drill down to view the application. You will see that the "fail" task is stuck waiting to be deployed, despite the fact that there is nothing stopping it from being redeployed. 
![screen shot 2016-07-18 at 14 46 29](https://cloud.githubusercontent.com/assets/8793723/16916784/b224ac1a-4cf6-11e6-8ffe-bb404bf1db8f.png)

**Comment by unterstein** [comment]
Hi @philwinder,

I was not able to reproduce this behavior with the current version. Can you please provide your marathon logs? Then we could have a closer look at your issue.

Kind regards
Johannes

**Comment by philwinder** [comment]
Sure thing. Here you go: http://pastebin.com/raw/qD1TpZ8k

Interestingly, there are no TASK_FAILED messages, despite returning 1. The message is TASK_FINISHED. This is with Mesos 0.25.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1988. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1988. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
