### ISSUE TITLE
Can I revert last or specify version app?

### ISSUE THREAD

**Issue by xyalan** [mesosphere/marathon#4111]
There are old version list on Marathon UI:
![Imgur](http://i.imgur.com/Pk4QUMb.png)
I can edit or apply each version.Reference [Marathon REST API](https://mesosphere.github.io/marathon/docs/rest-api.html), There are two API about version:

```
GET /v2/apps/{appId}/versions
GET /v2/apps/{appId}/versions/{version}
```
Is there a API which can apply last or specify version?

**Comment by unterstein** [comment]
Hi @xyalan,

in case you want to redeploy an older version or rollback to an older version of your app, you could do the following:

`PUT /v2/apps/{appId}` with request body `{ "version": "2016-07-22T10:19:55.809Z" }`

Hope this fixes your issue and I will close this task now. If you have any further questions or this solution is not working for you, feel free comment on this task and/or e-open the task.

// cc @sascala: Should we add this to our documentation?

Kind regards
Johannes
