### ISSUE TITLE
Validations leak app ids and service ports

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#4127]
When an app is created/updated, Marathon will check if the user specified a duplicated service port. If it did, it will respond with a validation error, including the id of the conflicting app, without checking if the user is authorized to see the id of the conflicting app.

cc/ @adam-mesos

**Comment by adam-mesos** [comment]
Not good, since ideally this user wouldn't even know that the other app exists, let alone its full app_id.
But since you're not showing configuration, logs, or agent location, it's not the end of the world.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1732. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1732. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
