### ISSUE TITLE
Marathon Docker args parsing doesn't accommodate spaces

### ISSUE THREAD

**Issue by Blackbaud-IanThomas** [mesosphere/marathon#4140]
When deploying an app in a Docker container, I have tried to pass an `argc/argv` tuple where one of the args contains a space, according to `marathon-lb` documentation, referenced here:

https://github.com/mesosphere/marathon-lb/blob/master/marathon_lb.py#L1392

When I do that, my argument that contains a space gets the space turned into `%20`, like: `http://master.mesos/service/marathon-saboten-test%20http://master.mesos/service/marathon-nautilus-test%20http://master.mesos/service/marathon-microedge-test/v2/apps?embed=apps.tasks`

This is happening at the marathon/mesos arg parsing level.

https://github.com/mesosphere/marathon/blob/eecedfbc0b8295b75a0951ab5232da06566e0ab9/src/main/scala/mesosphere/mesos/TaskBuilder.scala#L326

I think that the args parser should handle the spaces properly, or maybe this is an invalid syntax for command line args and `marathon-lb` needs to handle multiple marathon instances better.

**Comment by brndnmtthws** [comment]
That's correct, this is the expected behaviour. Just specify each Marathon URI as a separate arg, and it should work. Please reopen if not.

**Comment by Blackbaud-IanThomas** [comment]
@brndnmtthws I definitely understand if this is the expected behavior. Specifying each URI as a separate arg doesn't work because `marathon-lb` only listens to the last one that you give.  I've heard rumblings that `marathon-lb` will be superseded by another better form of load balancing, so if this isn't a marathon issue, I'm not worried about pressing the issue at the `marathon-lb` level.  Does that seem like the case?

**Comment by brndnmtthws** [comment]
Can you open an issue at https://github.com/mesosphere/marathon-lb instead?

**Comment by Blackbaud-IanThomas** [comment]
Will do. Thanks!
