### ISSUE TITLE
rewrite most/all of our test case assertions using scalatest matchers

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#4143]
for example: https://github.com/mesosphere/marathon/pull/4131#discussion_r72055447

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2628. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2628. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
