### ISSUE TITLE
remove deprecation:false from scalacOptions in Test once Mesos removes deprecated fields from API

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#4144]
https://github.com/mesosphere/marathon/pull/4131#discussion_r72054647

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2237. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2237. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
