### ISSUE TITLE
Containers in Bridged network mode does not copy the root namespace.

### ISSUE THREAD

**Issue by Amal-V** [mesosphere/marathon#4151]
While using Bridged network mode, the containers are not able to access the VIP or Marathon-internal or Mesos dns addresses.
It seems they only have the google name resolvers inside.

```
root@817e8f697f71:/opt/tyk# cat /etc/resolv.conf 
search ap-southeast-1.compute.internal
nameserver 8.8.8.8
root@817e8f697f71:/opt/tyk# ping leader.mesos
ping: unknown host leader.mesos
```

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4096. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4096. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
