### ISSUE TITLE
Remove mesosStatus from mesosphere.marathon.core.task.Task

### ISSUE THREAD

**Issue by unterstein** [mesosphere/marathon#4153]
After https://github.com/mesosphere/marathon/pull/4141 is merged, the mesosTaskStatus should be completely removed from Task.

This includes:
- Remove `Task.mesosStatus`
- Change `Task.Status#stagedAt`, `Task.Status#startedAt` to `Task.Status#since`, which is distinct in combination with `Task.Status#taskStatus`
- Add healthy information to `Task.Status`
- Maybe it is necessary to add a garbage flag to `Task.Status`
- Maybe remove `def launched: Option[Launched]` from `Task`

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1974. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1974. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
