### ISSUE TITLE
MARATHON_SINGLE_INSTANCE_APP should be a property, not a label

### ISSUE THREAD

**Issue by mgummelt** [mesosphere/marathon#4160]
See https://mesosphere.github.io/marathon/docs/recipes.html

Why is this a label?

**Comment by unterstein** [comment]
Hi Michael,

this is a good question! We are aware of this and will hopefully refactor this within v3. I`ll close this issue as duplicate of https://github.com/mesosphere/marathon/issues/4225 (your ticket was opened earlier, but @ssk2 has more details).

Kind regards
Johannes
