### ISSUE TITLE
external volumes should accept absolute containerPath

### ISSUE THREAD

**Issue by vixns** [mesosphere/marathon#4164]
according to http://mesos.apache.org/documentation/latest/docker-volume/, containerPath can be absolute or relative.

Marathon implementation does not accept absolute paths yet, please remove https://github.com/mesosphere/marathon/blob/releases/1.2/src/main/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProvider.scala#L162

**Comment by unterstein** [comment]
Maybe @jdef can add his opinion to this issue :)

Saw your TODO here https://github.com/mesosphere/marathon/blob/releases/1.2/src/main/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProvider.scala#L168

**Comment by jdef** [comment]
https://issues.apache.org/jira/browse/MESOS-5389

via @Gilbert88 
> we have it included in [mesos] 1.0
so in the future, only command task (mesos container without image specified) case has to use the relative `container_path`.
for docker container or mesos container with image specified, container_path can be either absolute or relative.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2000. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2000. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
