### ISSUE TITLE
Deployment locked by another completely independent deployment

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#4165]
1) `PUT /v2/groups` with:

```json
{
  "id": "/foo",
  "apps": [
    {
      "id": "initial",
      "cpu": 999,
      "container": {
        "type": "DOCKER",
        "docker": {
          "image": "foo",
          "network": "BRIDGE",
          "portMappings": []
        }
      }
    }
  ]
}
```

2)  `PUT /v2/groups` with:

```json
{
  "id": "/bar",
  "apps": [
    {
      "id": "/bar/initial",
      "cmd": "sleep 100"
    }
  ]
}
```

This app definition is completely unrelated to the first one, so it should be possible to create a deployment. However Marathon will return an error like the following one:

```json
 {"message":"App is locked by one or more deployments. Override with the option '?force=true'. View details at '/v2/deployments/<DEPLOYMENT_ID>'."
```

Note that this doesn't happen if the first `PUT` doesn't include an empty `portMappings` array.

**Comment by jasongilanfarr** [comment]
This does not happen on master and both apps are deployed correctly. I'm checking 1.2 and 1.3 now.

**Comment by jasongilanfarr** [comment]
The real reason for this is that the portDefinitions is initially unassigned then reassigned on the next deployment.
