### ISSUE TITLE
Usability problem with new service port checks after upgrade. 

### ISSUE THREAD

**Issue by joerg84** [mesosphere/marathon#4167]
After upgrading a cluster with many apps which might have the same service port allocated from before the update (bad configuration, but note that the ports might not be used),
I cannot restart any app as the check is checking all service for all apps -not just the one I upgraded...

I would expect that when upgrading a cluster with many apps, it forces me to only update the app I want to restart, but not all other apps which are running in the cluster.

**Comment by gkleiman** [comment]
cc/ @aquamatthias

**Comment by unterstein** [comment]
Fixed through #4172
