### ISSUE TITLE
Implement the possibility to have plugable Nav Tabs in Marathon-UI

### ISSUE THREAD

**Issue by daltonmatos** [mesosphere/marathon#4169]
Hello,

I would like to know if is of interest of the Marathon project to have implemented the possibility to support pluggable Nav Tabs on Marathon-UI. Currently there are 2 constant tabs ([js/constants/tabs.js](/mesosphere/marathon-ui/blob/master/src/js/constants/tabs.js)) and there's no way for a plugin to add new tabs.

If you have interest we can discuss the implementation details here and produce a Pull Request for this.

I see two ways to implement tthis:
- The plugin firing e new event, say `NavTabsEvents.ADD_NAVTAB`, and the listener of this event populates a tab array (maybe inside a `NavTabsStore`?)
- The plugin attaches itself to a `PluginMountPoints.NAVTAB_RIGHT` and this is added as a `<PluginMountPointComponent placeId={PluginMountPoints.NAVTAB_RIGHT} />` at the relevant place.

Let me now what do you think.

Thanks,

/cc @aquamatthias @meichstedt @gkleiman

**Comment by aquamatthias** [comment]
@orlandohohmeier any thoughts on that?

**Comment by daltonmatos** [comment]
Also, the plugin would probably need to be able to register new routes.

**Comment by xiaods** [comment]
i would like to get the feature, how about you any initial code to show the way.

**Comment by daltonmatos** [comment]
Here is a PR with a Work in Progress implementation: https://github.com/mesosphere/marathon-ui/pull/775

Thanks.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2538. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2538. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
