### ISSUE TITLE
Scaling an application with validation errors leads to error message "Object is not valid"

### ISSUE THREAD

**Issue by unterstein** [mesosphere/marathon#4173]
Hi,

@joerg84 and me tried to scale an application with had already validation errors and we received the error message "Object is not valid", see here:

![image](https://cloud.githubusercontent.com/assets/904420/17397460/7c994214-5a38-11e6-89e1-69700c316aaa.png)

In the network tab we see the actual error.

It would be super awesome, if the validation error would be displayed in the error modal :)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1897. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1897. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
