### ISSUE TITLE
Service ports seem to not be persistent in the UI. 

### ISSUE THREAD

**Issue by joerg84** [mesosphere/marathon#4174]
When setting the port to 0 (i.e., random port) in json mode, starting the app and the going back the json app definition the port is set to 1001. This is annoying when updating a running up app via the json mode as it will fix the port to 1001.

**Comment by joerg84** [comment]
@unterstein @aquamatthias

**Comment by jasongilanfarr** [comment]
A random port will be allocated on first use. Once its set, we keep the service port set to the randomly selected value.

**Comment by unterstein** [comment]
@joerg84 what was the conclusion at the discussion with @aquamatthias about this topic?

**Comment by jasongilanfarr** [comment]
Please reopen if you have more data to contribute.
