### ISSUE TITLE
Automatically added fetch section in the app definition leads to validation error.

### ISSUE THREAD

**Issue by joerg84** [mesosphere/marathon#4175]
Steps to reproduce:
1. create app with URI (when checking the json app definition while creating, there is only the uri section  as expected)
2. Start app and check json app definition of running app. Now there are both the uri and fetch sections specified (i.e., the uri section is duplicated)
3. When trying to save the json app definition it will lead to an error as both `uri` and  `fetch` are specified.

**Comment by joerg84** [comment]
@aquamatthias @unterstein

**Comment by unterstein** [comment]
@joerg84 what was the conclusion at the discussion with @aquamatthias about this topic?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4673. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4673. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
