### ISSUE TITLE
Application fails when specified a non-zero disk resource of mounted disk

### ISSUE THREAD

**Issue by Abhijeet-Jadhav** [mesosphere/marathon#4181]
I have tried running some apps on Marathon. Apps run only on root disk of Mesos. When a mounted disk is specified in resources file(/etc/mesos-slave/resources) of mesos agent, apps didn't run (are in waiting state forever). It seems mounted disk resource is not offered to Marathon framework. Is multiple disk feature supported in Marathon ?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4662. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4662. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
