### ISSUE TITLE
Issues installing marathon on Ubuntu 16.04 Xenial using apt

### ISSUE THREAD

**Issue by tazaki** [mesosphere/marathon#4182]
Following the instructions provided here: https://open.mesosphere.com/getting-started/install/

ubuntu@u161:~$ sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv E56151BF
Executing: /tmp/tmp.qhDRC1VCAM/gpg.1.sh --keyserver
hkp://keyserver.ubuntu.com:80
--recv
E56151BF
gpg: requesting key E56151BF from hkp server keyserver.ubuntu.com
gpg: key E56151BF: public key "Mesosphere Archive Automatic Signing Key <support@mesosphere.io>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)

ubuntu@u161:~$ DISTRO=$(lsb_release -is | tr '[:upper:]' '[:lower:]')
ubuntu@u161:~$ CODENAME=$(lsb_release -cs)
ubuntu@u161:~$ echo "deb http://repos.mesosphere.com/${DISTRO} ${CODENAME} main" |  sudo tee /etc/apt/sources.list.d/mesosphere.list
deb http://repos.mesosphere.com/ubuntu xenial main
ubuntu@u161:~$ sudo apt-get -y update
Hit:1 https://repo.saltstack.com/apt/ubuntu/16.04/amd64/latest xenial InRelease
Get:2 http://repos.mesosphere.com/ubuntu xenial InRelease [3,134 B]
Get:3 http://security.ubuntu.com/ubuntu xenial-security InRelease [94.5 kB]
Get:4 http://repos.mesosphere.com/ubuntu xenial/main amd64 Packages [673 B]
Hit:5 http://nova.clouds.archive.ubuntu.com/ubuntu xenial InRelease
Hit:6 http://nova.clouds.archive.ubuntu.com/ubuntu xenial-updates InRelease
Hit:7 http://nova.clouds.archive.ubuntu.com/ubuntu xenial-backports InRelease
Fetched 98.3 kB in 5s (17.3 kB/s)
Reading package lists... Done
W: http://repos.mesosphere.com/ubuntu/dists/xenial/InRelease: Signature by key 81026D0004C44CF7EF55ADF8DF7D54CBE56151BF uses weak digest algorithm (SHA1)

ubuntu@u161:~$ sudo apt-get -y install mesos marathon
Reading package lists... Done
Building dependency tree
Reading state information... Done
E: Unable to locate package marathon

ubuntu@u161:~$ lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04.1 LTS
Release:        16.04
Codename:       xenial

Am I doing something wrong? I can confirm this process works on Ubuntu 14.04.

Thanks!

**Comment by arthur-tacca** [comment]
I experienced this problem too. The Xenial (16.04) package archive does not have the marathon package while the Trusty (14.04) archive does. 

- Trusty package list: http://repos.mesosphere.com/ubuntu/dists/trusty/main/binary-amd64/Packages
- Xenial package list: http://repos.mesosphere.com/ubuntu/dists/xenial/main/binary-amd64/Packages

**Comment by flyinprogrammer** [comment]
```
Package: marathon
Priority: extra
Section: default
Installed-Size: 72742
Maintainer: Mesosphere Package Builder <support@mesosphere.io>
Architecture: amd64
Version: 1.1.3-1.0.503.ubuntu1604
Depends: java8-runtime-headless, lsb-release, unzip
Filename: pool/main/m/marathon/marathon_1.1.3-1.0.503.ubuntu1604_amd64.deb
Size: 66634420
MD5sum: 31671081bd364298dded13962bc08b27
SHA1: 97c22d8e7bb1a38b4ba2b66bd1528fc7c147ddc9
SHA256: 0333d5fe89aee3f71c8e5a72879d35845a429f3179f050226f30492fc210e06d
Description: Cluster-wide init and control system for services running on Apache Mesos
Homepage: https://github.com/mesosphere/marathon
License: Apache-2.0
Vendor: Mesosphere, Inc.

Package: marathon
Priority: extra
Section: default
Installed-Size: 70907
Maintainer: Mesosphere Package Builder <support@mesosphere.io>
Architecture: amd64
Version: 0.15.7-1.0.501.ubuntu1604
Depends: java8-runtime-headless, lsb-release, unzip
Filename: pool/main/m/marathon/marathon_0.15.7-1.0.501.ubuntu1604_amd64.deb
Size: 64971610
MD5sum: 35e0034bf885d6e938f127e14adbc741
SHA1: 9ff197003732c81a35b565d9381e9912761c74ba
SHA256: 0f76f750f9d30ce8910cf4aa0040b409512304d4617cc22efbb829d5880de792
Description: Cluster-wide init and control system for services running on Apache Mesos
License: Apache-2.0
Homepage: https://github.com/mesosphere/marathon
Vendor: Mesosphere, Inc.
```

looks like they've added the marathon package, a chronos package is still missing though

**Comment by flyinprogrammer** [comment]
https://github.com/mesosphere/docker-containers/pull/66

Also, Mesosphere should be adding curl as a package dependency because this code base shells out for curl all the time :sadpanda: .

**Comment by flyinprogrammer** [comment]
oh mesosphere, you're so awesome:

```
Unpacking marathon (1.3.0-1.0.506.ubuntu1604) ...
dpkg-deb (subprocess): cannot copy archive member from '/var/cache/apt/archives/marathon_1.3.0-1.0.506.ubuntu1604_amd64.deb' to decompressor pipe: unexpected end of file or stream
dpkg-deb: error: subprocess paste returned error exit status 2
dpkg: error processing archive /var/cache/apt/archives/marathon_1.3.0-1.0.506.ubuntu1604_amd64.deb (--unpack):
 cannot copy extracted data for './usr/bin/marathon' to '/usr/bin/marathon.dpkg-new': unexpected end of file or stream
```

**Comment by judithpatudith** [comment]
Hey all, we're looking into better structures for getting timely responses to issues, but for now I'll poke the Marathon team about getting this specific issue addressed. Sorry for the wait time, and thank you for continuing to follow up!

**Comment by jasongilanfarr** [comment]
Something broke in our packaging, I don't know enough about how we currently publish debs. By 1.4, I intend on it to be 100% in our sbt build and fully automated without a separate build project. I've done most of this for docker already and I'm working on deb and rpm support.

**Comment by davidmaes** [comment]
I'm experiencing the same as flyinprogrammer. Any ETA for when the marathon install issues will be fixed for Ubuntu 16.04?

**Comment by aquamatthias** [comment]
@lloesche Can you please look into this?
TC seems to build the package correctly: https://teamcity.mesosphere.io/viewType.html?buildTypeId=Oss_Marathon_Packages&branch_Oss_Marathon=v1.3.0&tab=buildTypeStatusDiv
The upload to the package server is also green:
https://teamcity.mesosphere.io/viewLog.html?buildId=405533&tab=buildResultsDiv&buildTypeId=Oss_Marathon_PublishTar

But the package is not installable:
```
dpkg-deb (subprocess): cannot copy archive member from '/var/cache/apt/archives/marathon_1.3.0-1.0.506.ubuntu1604_amd64.deb' to decompressor pipe: unexpected end of file or stream
dpkg-deb: error: subprocess paste returned error exit status 2
dpkg: error processing archive /var/cache/apt/archives/marathon_1.3.0-1.0.506.ubuntu1604_amd64.deb (--unpack):
 cannot copy extracted data for './usr/bin/marathon' to '/usr/bin/marathon.dpkg-new': unexpected end of file or stream
```

**Comment by aquamatthias** [comment]
@lloesche Can we close this one? I retested and got:
```
Get:6 http://repos.mesosphere.com/ubuntu xenial/main amd64 marathon amd64 1.3.0-1.0.506.ubuntu1604 [83.0 MB]
Selecting previously unselected package marathon.
Preparing to unpack .../marathon_1.3.0-1.0.506.ubuntu1604_amd64.deb ...
Unpacking marathon (1.3.0-1.0.506.ubuntu1604) ...
Setting up marathon (1.3.0-1.0.506.ubuntu1604) ...
```

**Comment by lloesche** [comment]
Yup

**Comment by catbadger** [comment]
And it's baaack...

**Comment by lloesche** [comment]
@catbadger the repo is called `xenial`, not `ubuntu-xenial`.

**Comment by catbadger** [comment]
derp on my part. thank you.
