### ISSUE TITLE
allow multiple networks

### ISSUE THREAD

**Issue by vixns** [mesosphere/marathon#4188]
Many apps needs a network and a loopback interface.
When using the `network/cni` isolator, you can add a loopback interface

``` json
{
    "name": "loopback",
    "type": "loopback"
}
```

Then you must add an extra networkInfo with name "loopback", or the interface will be created in the namespace, but will stay down.

For my needs, I've patched the Taskbuilder.
Adding `builder.addNetworkInfos(NetworkInfo.newBuilder().setName("loopback"))` is sufficient to make it work, but cannot be seriously merged.

You can't specify a second network in marathon, ipAddress and networkName are uniques.

We should be able to add multiple networks definitions, maybe by deprecating `ipAddress` in favor of a new `ipAdresses` or `networks` array.

**Comment by jdef** [comment]
sounds like there are multiple issues represented by this ticket:

1. mulitple networks are a desired feature
2. loopback isn't being created/init'd properly by the CNI isolator

**Comment by vixns** [comment]
1/ yes, more than desired, required for properly operating unified containers, this is the issue highlighted by this ticket.

2/ mesos make no assumptions about loopback, it's just a standard CNI network. When a proper networkinfo is provided, it works just fine.
But, when no networkinfo is provided and the corresponding cni configuration exists, the interface is created (but not activated) in the container network namespace. I only test loopback, not multiple bridges, so I don't know if it's a specific issue with the cni loopback plugin, cni or the mesos isolator.
Anyway, this is not related to marathon.

**Comment by vixns** [comment]
loopback issue fixed in mesos https://issues.apache.org/jira/browse/MESOS-6269
