### ISSUE TITLE
Task stuck in "Started" status after node fails

### ISSUE THREAD

**Issue by pavels** [mesosphere/marathon#4190]
I don' t know if this is actually duplicate of something else (there is couple of filed bugs, some are closed, which seems related to this)

I have 100% reproducible behavior, that when the node fails long enough so that mesos marks  tasks as  TASK_LOST, in marathon it is left stuck as running without any possibility to get rid of them (well, i can remove them from zookeeper and restart marathons, but i would rather avoid this in production). After some tries (like scaling or suspending ...) i am left with this in logs

> W0808 09:09:57.836412 15668 master.cpp:4117] Cannot kill task mongodb.3a996070-5b20-11e6-922b-4ccc6a28a170 of framework ddbddeec-b70d-42ba-8e13-f444de6241b9-0000 (marathon) at scheduler-68500f22-068a-46bc-a526-0088cb52fd81@192.168.41.3:17634 because it is unknown; performing reconciliation
W0808 09:10:02.346374 15664 master.cpp:4117] Cannot kill task postgresql.344a62ef-5b20-11e6-922b-4ccc6a28a170 of framework ddbddeec-b70d-42ba-8e13-f444de6241b9-0000 (marathon) at scheduler-68500f22-068a-46bc-a526-0088cb52fd81@192.168.41.3:17634 because it is unknown; performing reconciliation
W0808 09:10:02.346667 15664 master.cpp:4117] Cannot kill task postgresql.28e283da-5d02-11e6-9abe-4ccc6a28a3f5 of framework ddbddeec-b70d-42ba-8e13-f444de6241b9-0000 (marathon) at scheduler-68500f22-068a-46bc-a526-0088cb52fd81@192.168.41.3:17634 because it is unknown; performing reconciliation
W0808 09:10:07.836618 15670 master.cpp:4117] Cannot kill task mongodb.3a996070-5b20-11e6-922b-4ccc6a28a170 of framework ddbddeec-b70d-42ba-8e13-f444de6241b9-0000 (marathon) at scheduler-68500f22-068a-46bc-a526-0088cb52fd81@192.168.41.3:17634 because it is unknown; performing reconciliation

My versions are:

Marathon - 1.1.2
Mesos - 1.0.0

If you have scale of 1 and 

>   "upgradeStrategy": {
    "minimumHealthCapacity": 0,
    "maximumOverCapacity": 0
  },

This leads to complete loss of service - if this service is database server (which is connected to shared network storage, that's why it has scale 1 and maximumOverCapacity 0), that everything connected to it is lost. One single physical machine than brings down the whole cluster. After this is triggered, only way to bring things up is either set scale to 2 (after another failure it will need to be set to 3 as the stuck processes accumulate ...) or manually edit Zookeeper and do the needed restarts.

I don;t know what's happening, but it seems something is really terribly wrong - i seemed to me that the main and most important future of marathon and all the mesos/,arathon stack is to keep services running even if things go bad. This behavior shows, that it is simple to get marathon into state, when everything fails. It takes single node to fail and it can't recover. No restarts will help. Health check won't help either, because marathon has the service as "Unhelathy" but running, but because maximumOverCapacity is 0 it can't bring the running service down as it doesn't exists in mesos and can't start new up because it thinks one is still running but in fact it doesn't (and MESOS has the states right, it has the task as lost)

**Comment by unterstein** [comment]
Hi @pavels,

is it possible for you to re-test your behavior on a testing environment on 1.2.0-RC8 or 1.3.0-RC2?

Thanks
Johannes

**Comment by pavels** [comment]
Hi

i have upgraded to 1.3.0-RC2 and looks like the problem is solved

Thank you
