### ISSUE TITLE
Better visibility of unsufficient resource offers

### ISSUE THREAD

**Issue by nicovillanueva** [mesosphere/marathon#4192]
Currently, whenever a deployment is not successful due to unsufficient resource offers, there is no clear and easily available indication of what is actually unsufficient.
There is no indication of whether the CPU, memory, or ports are not enough/not available.

This information is logged into /var/log/messages, but it definitely should be available on the UI.

**Comment by kamilchm** [comment]
see https://github.com/mesosphere/marathon/issues/1090

**Comment by nicovillanueva** [comment]
Oh man. I swear I searched, and found nothing. Maybe my search skills are getting bad. Feel free to close this up.
Thanks!

**Comment by unterstein** [comment]
Hi @nicovillanueva, hi @kamilchm,

thank you for reporting and linking #1090 =)

Cheers
