### ISSUE TITLE
Confusion regarding versioning

### ISSUE THREAD

**Issue by bodymindarts** [mesosphere/marathon#4196]
What is the official latest version of this project? 
is it v0.14.3 as specified in the latest [github release](https://github.com/mesosphere/marathon/releases/tag/v0.14.3) or rather v1.1.1 as is featured [on the website](http://mesosphere.github.io/marathon/) or v1.1.2 or v1.3.0-RC2 as are visible via `git tags`?

Would highly appreciate clarification.

**Comment by jasongilanfarr** [comment]
0.14.3 is an old maintenance release.
1.1.2 is the latest stable release.
1.2.0-RCX is a release candidate for 1.2 which we may drop in favor of 1.3
1.3.0-RC2 is the current release candidate. It unfortunately has 2 major blockers which I'm fixing right now.

I want to try to make it more clear in Github and couldn't find how.
