### ISSUE TITLE
Much larger test coverage and cleanup of Service Ports

### ISSUE THREAD

**Issue by jasongilanfarr** [mesosphere/marathon#4198]

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2140. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2140. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
