### ISSUE TITLE
Dependencies is not working

### ISSUE THREAD

**Issue by xuanhai266** [mesosphere/marathon#4201]
In Marathon, I created a group "gr-http". In this group, I created 2 applications: http and http2. Application "http2" is depend on "http". I add dependencies in application "http2" but it's not working. 
The application "http2" is still running while "http" is not running.
This is my JSON config:

`
{
	"id":"/gr-http",
	"apps":[
		{
			"id":"/gr-http/http",
			"cmd":"python -m SimpleHTTPServer $PORT",
			"instances":0,
			"cpus":0.1,
			"mem":50,
			"disk":0,
			"portDefinitions":[
				{
					"port":10000,
					"protocol":"tcp",
					"labels":{
					}
				}
			]
		},
		{
			"id":"/gr-http/http2",
			"cmd":"python -m SimpleHTTPServer $PORT",
			"instances":0,
			"cpus":0.1,
			"mem":50,
			"disk":0,
			"portDefinitions":[
				{
					"port":10000,
					"protocol":"tcp",
					"labels":{
					}
				}
			],
			"dependencies":[
				"/gr-http/http"
			]
		}
	]
}
`

I don't know why it's not working.
Thank you

**Comment by xiaods** [comment]
do you have config health check?

**Comment by xuanhai266** [comment]
yes. I did. But I think it's not importance in this case.
