### ISSUE TITLE
Marathon UI displays task within state TASK_LOST as Started

### ISSUE THREAD

**Issue by unterstein** [mesosphere/marathon#4211]
Hi,

in the current marathon-ui, tasks in the state TASK_LOST are displayed as `Started`. 

Situtation:
I have an app with instance count 6. 6 tasks are RUNNING and i have 2 tasks in state `TASK_LOST`.

Expected behavior:
6 tasks are displayed.

Current behavior:
DC/OS: 6 `Running`
Marathon-ui: 8 `Started`
Network view: 6 `RUNNING`, 2 `TASK_LOST`

Kind regards
Johannes

![image](https://cloud.githubusercontent.com/assets/904420/17621514/103a0d58-6094-11e6-856e-a96c60bf14fc.png)

**Comment by orlandohohmeier** [comment]
This is probably related to https://github.com/mesosphere/marathon/issues/4321

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1728. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
