### ISSUE TITLE
GracefulTaskKillIntegrationTest is unstable

### ISSUE THREAD

**Issue by jasongilanfarr** [mesosphere/marathon#4214]

**Comment by unterstein** [comment]
@jasongilanfarr it this test still flaky?

**Comment by timcharper** [comment]
It is still flaky: https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-loop-tests/1951/testReport/

**Comment by timcharper** [comment]
https://github.com/mesosphere/marathon/blob/fedf081e3c53543765703c2635823ec979318ca3/src/test/scala/mesosphere/marathon/integration/GracefulTaskKillIntegrationTest.scala

**Comment by timcharper** [comment]
Merging into #4736
