### ISSUE TITLE
Support for env variable interpolation

### ISSUE THREAD

**Issue by rupamroy** [mesosphere/marathon#4216]
I should be able to substitute the values of the env variables being set by marathon and mesos in other env variables required in the container. 

So for appdynamics say i require a env variable TIER_NAME , in the marathon app definition i should be able to define an environment variable TIER_NAME = `$MARATHON_APP_ID` and this should result in value of MARATHON_APP_ID being substituted for $TIER_NAME

**Comment by Project0** [comment]
Absolutly usefull, this will allow something like this to handle the auto mapping of ports:
$LIBPROCESS_PORT = $PORT0

**Comment by janisz** [comment]
Duplicates https://github.com/mesosphere/marathon/issues/1828 https://github.com/mesosphere/marathon/issues/1401

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4385. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
