### ISSUE TITLE
failover of marathon to host not running mesos-master

### ISSUE THREAD

**Issue by joelstewart** [mesosphere/marathon#4217]
Configure one host1 running:
- marathon
- mesos-master
- zookeeper

Configure second host (192.168.56.11) running:
- marathon

I'm running these on centos 7 as services.

I configured host1 /etc/mesos-master and /etc/mesos-slave with hostname and ip set to host 1 ip.  And I set /etc/zk to point to host 1 zk.  Host1 marathon works, deploys apps, etc.

I configured host2 /etc/marathon/conf/hostname to host 2 ip, carefully set master and zk to the appropriate host1 addresses, and added file /etc/default/marathon/LIBPROCESS_IP with contents of the host2 ip.

Upon starting, host1 is leader.  Stopping marathon on host1 does not failover to host2. visiting host2 :8080 "about" says host2 is leader, but host1:5050 shows host2 as an "inactive framework".  journalctl on host 2 has message for marathon:

"Scheduler driver bound to loopback .....  you might want to set 'LIBPROCESS_IP' environment variable ..."

What am I missing?  I am trying to achieve/observe marathon failover.

**Comment by youxixin888** [comment]
marathon needs FQDN hostname. so   `vi /etc/hosts`.

**Comment by joelstewart** [comment]
thanks.

failover works with hostnames added to /etc/hosts

although apache mesos site does say setting up /etc/hosts or DNS is a system requirement, it might deserve repeating in marathon docs, especially in install or HA docs pgs.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4123. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
