### ISSUE TITLE
Can Marathon persistent health check result?

### ISSUE THREAD

**Issue by fengyehong** [mesosphere/marathon#4220]
Currently health check result are held in memory and got lost when leader re-elected or failed over, this cause some problems in load balancing.
### Expected Result

we want to route traffic to `healthy` instances
### Actual Result

As leader re-elected can happen at any time, and after that, all instances become `unknown`, and needs time to recollect, load balancing module have two choices now:
1. route traffic to all running instances, so part of the traffic may be routed to unhealthy instances
2. insist on healthy instances, so refuse all traffic as no `healthy` instances found, which is apparently a bad idea

This means we can only choose to route traffic to `running` instances

I notice there is a related issue #3419, which says marathon-lb caches health status, but I think Marathon is the best place to hold this result (I am not using marathon-lb)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2197. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
