### ISSUE TITLE
Marathon-UI: how to connect to the Marathon

### ISSUE THREAD

**Issue by helium12** [mesosphere/marathon#4222]
As https://github.com/mesosphere/marathon-ui ,
I ran marathon-ui with **no-docker** way, it could be visited at 127.0.0.1:4200, but could not "Create Application", while my marathon running normally.  So how to config my marathon-ui to connect to marathon?   Looking forward for your help. Thank you very much.

**Comment by Poltergeist** [comment]
Hi @helium12, I personally used a proxy (nginx) to have marathon and marathon-ui be served from the same url locally before we started to use the docker-compose. You could also add the apiUrl o your config file. Which you should have copied from https://github.com/mesosphere/marathon-ui/tree/master/src/js/config the template to `config.dev.js`. I hope this works for you. If you have any more questions please ask.

Also the marathon which you are running locally should have a ui bundled with it as well.

**Comment by ouyangxuanyun** [comment]
you could visit marathon by http://marathon.docker:8080(make sure you have configured your hosts already ), it works for me.

**Comment by orlandohohmeier** [comment]
Closing this issue; feel free to reopen if you need further information on how to "connect" to Marathon.
