### ISSUE TITLE
"MARATHON_SINGLE_INSTANCE_APP" should be built into the API properly 

### ISSUE THREAD

**Issue by ssk2** [mesosphere/marathon#4225]
The current implement of the MARATHON_SINGLE_INSTANCE_APP variable is hacky and is hard to use correctly:
- Currently it's implemented as a label. It should be a first class citizen of the top level API, e.g. `"singleInstanceApp" : true`.
- upgradeStrategy should be implicit if this field is enabled instead of having to define this manually.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2656. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
