### ISSUE TITLE
Argument passing for docker applications (Mesos+docker containerizer)

### ISSUE THREAD

**Issue by eduser25** [mesosphere/marathon#4226]
Facing issues passing arguments and the documentation doesn't seem to say anything much different from what I'm already doing. App is exiting reporting it didn't recieve any argument (I added a printf of all arguments just at the beggining of the application):

`{
  "id": "/pghelloworld",
  "cpus": 0.1,
  "mem": 64.0,
  "instances": 1,
  "container": {
    "type": "DOCKER", 
    "docker": {
      "image": "someImage/helloworld",
      "forcePullImage": true,
      "network": "HOST"
    },
    "volume" :[]
  },
  "args": [
      "--rest_ip=172.16.1.1",
      "--login=root",
      "--password=pwd",
      "--marathon_endpoint=172.16.1.100:8080",
      "--domain=service",
      "--dns=dns",
      "-watcher",
      "--app_name=/pghelloworld"
    ]
}`

The stdout of printing the `os.Args` in GoLang:
`[/go/bin/pghelloworld]` (no args at all?)

`ENTRYPOINT` of the application is defined as `/go/bin/pghelloworld`, and there is no `CMD` defined.

**Comment by xiaods** [comment]
args is CMD?

**Comment by unterstein** [comment]
Hi @eduser25,

which version of marathon are you using? Maybe this https://github.com/mesosphere/marathon/blob/master/docs/docs/native-docker.md#command-vs-args is helping you. Otherwise it would be really helpful if you could add the marathon logs around the task launch timestamp.

Thanks
Johannes

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1757. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
