### ISSUE TITLE
#GUI Redeployment of all apps make services in group 'stateful applications' that cannot be changed.

### ISSUE THREAD

**Issue by rabun788** [mesosphere/marathon#4233]
This is an effort to rebuild every app in case the mesos masters lose any configurations and we need to redeploy from scratch.

This script runs every five minutes and backs up the marathon json file to github.

```
#!/bin/bash
ts=$(date "+%T %D")
ENV="infra"
cd ./marathon-backup

while true; do 
    #git init - Occurs in Dockerfile
    git config --global user.email "docker@ems.com"
    git config --global user.name "Mesos Docker Bot"
    git config --global push.default simple
    git remote add origin git@github.enterterprise.com:ems/docker-marathon-backup.git
    git branch $ENV
    git checkout $ENV
    git pull origin $ENV
    curl -uadmin:password -k http://marathon-$ENV.mesos.enterprise.com:8080/v2/apps | jq . > marathon-backup.json
    git add --all
    git commit -m "$ts"
    git push origin $ENV
    echo "sleeping"
    sleep 300
done
```

Then when we restore the configurations we use this script.

```
#!/usr/bin/env bash

# script/deploy: deploys artifacts

set -e
set -o errexit
set -o errtrace
cd $(dirname $0)/..

source script/bootstrap

function marathon() {
    # Deploy to Marathon
    taskProgress "Deploying to Marathon"
    taskDebug "marathon ${MARATHON_URL}"

    MARATHON_ID="${MARATHON_APP}/${IMAGE_NAME}"

    taskDebug "deployment url ${MARATHON_ID}"

    #replace variables from Marathon template
    taskDebug "deploying ${REMOTE_IMAGE_NAME}..."

    JSON=$(ejson decrypt credentials.ejson)
    USER=$(echo $JSON | jq '.username' |  sed 's/"//g')
    PASS=$(echo $JSON | jq '.password' |  sed 's/"//g')
    CREDS=$USER:$PASS

    echo ""

    cat marathon-backup.json | \
    curl -s -u "${CREDS}" -XPUT -H"Content-Type: application/json" -d @- --url "http://marathon-infra.mesos.enterprise.com:8080/v2/groups"

    echo ""
}

case "$1" in
    *)
        marathon
        ;;
esac
```

After marathon gets the configurations back, everything is back up and running, but when we need to scale the application down, we get this message -->

> Scaling down $/maps/stores-data will cause any existing local volumes to be detached from destroyed instances. Read more about persistent local volumes.
> Are you sure you want to continue?

After we click the 'continue scaling' button, nothing happens.

If we wanted to scale the application to more instances, nothing happens.

Any ideas on how we can better this process or fix this bug?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4100. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
