### ISSUE TITLE
Zombie instances

### ISSUE THREAD

**Issue by janisz** [mesosphere/marathon#4236]
From time to time on our cluster appears zombie instances. By zombie instance I mean instance that is running but its application is unknown (deleted) in marathon.

`/v2/apps/<zombie-instace-id` returns instance info but it odes not appear in `/v2/apps`. Application could not be deleted because Marathon returns it does not known this app.

Workaround to kill all instances and application is to  create new application with `zombie-instace-id`. Zombies instances will be assigned to this application and will be manageable from marathon.

This occurs after problems with ZK. Marathon version from 0.13 to 1.1.1.

**Comment by jdef** [comment]
@gkleiman related to recent fixes you've been hacking on?

**Comment by solarkennedy** [comment]
I'm encountering this too. My internal name for this is "ghost marathon apps".
Sounds like a I have slightly different symptoms maybe. Here are some facts about what his happening in my situation:
* App shows up in the marathon API when queried directly.
* App does *not* show up in `/v2/apps`
* Tasks *do* show up in mesos
* Marathon *does* restart these tasks with the same configuration if I kill the tasks manually with "docker kill" (so marathon is doing its normal thing here)

@jdef this is still happening at Yelp now, but I can't let it go on for long. Besides marathon logs filtered for this app is there any other data you would like me to collect?

We are on marathon version 1.1.1-1.0.472 and mesos version 1.0.1

**Comment by aquamatthias** [comment]
If you delete an application e.g. `DELETE /v2/apps/{appId}` the application is deleted from the group.
Subsequent calls do not list the application.
This call also has created a deployment. Until the deployment is finished, the application is still stored in the repository and available via `/v2/apps/{appId}` by intention.

If you use `DELETE /v2/deployment/{id}?force=true` you can end up in such a situation easily. See #4581 for a more detailed explanation. 

Is the problem you describe covered by these 2 options?
In any other case I need more information + logs to analyse.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2438. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
