### ISSUE TITLE
How does marathon customize hostname such as 'docker run -h 'myhost'

### ISSUE THREAD

**Issue by jaminlai** [mesosphere/marathon#4237]
Hi：

We can customize the hostname for the container with command:

`"docker run -h 'myhost' xxx"`

However I couldn't found the solution with marathon deploy app for customizing hostname,  especially when I scale-out more than instances and the hostname inside each container must named by my regular such as 'mydomain-7af2dfe3a468' but now default hostname is '7af2dfe3a468' such as.

**Comment by jdef** [comment]
have you tried setting a custom docker/parameters value via the apps API?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4771. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
