### ISSUE TITLE
Unable to update Docker image name for an app in 1.3.0-RC4

### ISSUE THREAD

**Issue by alahiff** [mesosphere/marathon#4240]
In 1.3.0-RC4 if I edit an application to change the name of the Docker image, nothing at all happens. In the logs I see this:
```
2016-08-22T21:55:36.282427+01:00 vm50 marathon[26845]: [2016-08-22 21:55:36,282] INFO Computed new deployment plan:
2016-08-22T21:55:36.282740+01:00 vm50 marathon[26845]: DeploymentPlan 2016-08-22T20:55:36.273Z NO STEPS
```
This happens both using the UI and using the REST API. I hadn't experienced this problem with earlier versions of Marathon (e.g. 1.1.1 works as expected).

**Comment by alahiff** [comment]
Sorry, just realized #4228 probably fixes this.

**Comment by unterstein** [comment]
Hi @alahiff,

thanks for reporting! Actually @vixns fixed this in https://github.com/mesosphere/marathon/pull/4185 :)

But yes, this will be included in the next RC. I`ll close this ticket, but I will comment to this ticket when RC5 is released.

Cheers
Johannes

**Comment by bogdangi** [comment]
Hi,

I had issue with marathon v1.3.0-RC4, so I did manual update to version 1.3.0-RC5 and it is working now.

Thank you for update.
