### ISSUE TITLE
Is there a equivalent of POD definition in Marathon where multiple containers can be co-located and co-scheduled?

### ISSUE THREAD

**Issue by tekneeq** [mesosphere/marathon#4244]

**Comment by unterstein** [comment]
Hi @tekneeq,

currently not, but we are currently working on this feature and we are planning to ship this feature in the near future. You can get a sneak preview of the design document here: https://docs.google.com/document/d/1uPH58NWN_OuynptsqTOq8v5qlkivq2mUb2M9J5jZTMU/edit

I`ll close this issue now. If you have further questions feel free to post them or re-open the issue :)

Kind regards
Johannes
