### ISSUE TITLE
Allow "hidden labels"

### ISSUE THREAD

**Issue by kevincox** [mesosphere/marathon#4247]
It would be nice to have a convention for labels that are "generally not for user viewing". For example we could hide labels that start with an underscore from the UI by default. This is because while labels are a very general way to attach data to jobs the UI presents them all to users in a way that is fairly unsightly for things like attaching DNS names.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2154. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
