### ISSUE TITLE
Old deployments leaks in ZK

### ISSUE THREAD

**Issue by janisz** [mesosphere/marathon#4249]
I just spot that in my ZK there are about 76 deployments that are not known to Marathon. They do not appear in `/v2/deployments` and when I try to delete them I got 404 Not found.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1724. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
