### ISSUE TITLE
Add ability to coerce garbage collection of lost tasks.

### ISSUE THREAD

**Issue by drcrallen** [mesosphere/marathon#4251]
https://github.com/mesosphere/marathon/pull/4004 added more `TASK_LOST` handling and garbage collection, but sometimes a bad event occurs and a task really is lost during the process. An operator might not want to wait until `task_lost_expunge_gc` for the tasks to be reaped, and would like for select task ids to be expunged immediately.

This ask is that there be a way to immediately expunge lost tasks (by task id) that are waiting for garbage collection.

**Comment by drcrallen** [comment]
This is probably addressed by https://github.com/mesosphere/marathon/commit/25ce737e39a370a151c119022b8d16523f04e990

**Comment by unterstein** [comment]
Hi @drcrallen,

through #4117 it should be possible to expunge immediately after receiving TASK_LOST. Could you retest your issue in 1.3.0-RC5?

Thanks
Johannes

**Comment by drcrallen** [comment]
@unterstein unfortunately the only deployment workflow I have right now is what can be found in the mesosphere repository.

**Comment by drcrallen** [comment]
looks like `marathon_1.3.0-1.0.502` might be available, but I'm not sure what the mapping of `1.0.502` to `RC?` is.

**Comment by drcrallen** [comment]
Installed `marathon=1.3.0-1.0.502.ubuntu1404` from `deb http://repos.mesosphere.io/ubuntu trusty-testing main` and `[Kill]` button works as expected.
Upgrade process acted weird where marathon thought more application instances were running than really were, but killing the superfluous ones fixed the problem.

**Comment by drcrallen** [comment]
Thanks!

**Comment by unterstein** [comment]
Awesome :)
