### ISSUE TITLE
Why marathon restart container will rebuild

### ISSUE THREAD

**Issue by mgdsxhy** [mesosphere/marathon#4252]
Marathon restart button on the interface is not restart container, but delete all containers, create again. Why is this so?

**Comment by jdef** [comment]
Because this is how containers are managed via marathon/mesos. If this is breaking a use case for you, can you provide some additional details on that use case?

**Comment by mgdsxhy** [comment]
Thank you for your reply, jdef. 
The restart button is easy to cause misunderstanding. What should I do if I need to restart the selected container via marathon?
The second question, how to get ID of the selected container by Marathon API

**Comment by jdef** [comment]
Marathon has no equivalent of `docker restart CTID`. Neither does Mesos.
You'll need to ssh into the box, or else build companion tooling if you
need this exact feature.

Regarding "how to get ID of the selected container" -- I'm assuming that
you're asking about the Docker container ID (vs the Mesos container ID)?
Marathon doesn't provide an API to get either.

What is the broader use case you're attempting to implement?

**Comment by mgdsxhy** [comment]
Hi, jdef
We have a demand is can pass the marathon to restart the container, Now, we have changed the code with: 

vim ./src/slave/containerizer/docker.hpp 
  static std::string name(const SlaveID& slaveId, const std::string& id)
    {
      // return DOCKER_NAME_PREFIX + slaveId.value() + DOCKER_NAME_SEPERATOR +
      //  stringify(id);
      return DOCKER_NAME_PREFIX + DOCKER_NAME_SEPERATOR +
        stringify(id);
    }

vim ../src/slave/containerizer/docker.cpp
// Declared in header, see explanation there.
const string DOCKER_NAME_PREFIX = "docker";
// Declared in header, see explanation there.
const string DOCKER_NAME_SEPERATOR = ".";

vim ../src/slave/slave.cpp
  // containerId.set_value(UUID::random().toString());
  // containerId.set_value(stringify(taskInfo.task_id()));         //containerId==taskId
  containerId.set_value(stringify(taskInfo.task_id()).substr(int(stringify(taskInfo.task_id()).find("."))+1));   //containerId== taskId.UUID`

Now, **How to compile it?**

**Comment by jdef** [comment]
That change looks suspect to me. But I'm not a core expert. Your question
is one for the mesos-dev mailing list. Pretty sure there are docs for
compiling mesos here
http://mesos.apache.org/documentation/latest/getting-started/
