### ISSUE TITLE
Development container fails to start

### ISSUE THREAD

**Issue by isaacd9** [mesosphere/marathon#4263]
Following the documentation from readme under the "Running the development Docker" header causes the container to be built properly, but, running 

`docker run -p 8080:8080 marathon-head --master local --zk zk://localhost/marathon`

fails with error message:

`Failed to start a local cluster while loading agent flags from the environment: Flag 'work_dir' is required, but it was not providedI0828 22:33:41.809705    72 leveldb.cpp:304] Persisting metadata (8 bytes) to leveldb took 3.432628ms`

It seems like explicitly setting the Mesos work directory by adding  `ENV MESOS_WORK_DIR /var/lib/mesos` to the Dockerfile resolves the issue.

**Comment by aquamatthias** [comment]
@isaacd9 Thanks for this report.
This is (strange) behavior from the latest Mesos version.
We should add this to our documentation until this is fixed in Mesos.
@sascala can you add this to the readme? Thanks

**Comment by cglewis** [comment]
I'll add this, as I just ran into the same issue.

**Comment by isaacd9** [comment]
Thanks for this 👍  :)

**Comment by rukletsov** [comment]
This "strange behaviour" has a name and reasons. Please in the future talk to us if you find something "strange" in Mesos: it can be a bug, a feature, or a misunderstanding.
