### ISSUE TITLE
Marathon process is not starting

### ISSUE THREAD

**Issue by durgaswaroop** [mesosphere/marathon#4272]
I am trying to run marathon inside a docker container. I downloaded the binaries from the site and ran the following command.

 `$MARATHON_HOME/bin/start --master zk://172.17.0.2:2181/mesos --zk zk://172.17.0.2:2181/marathon`
And I get the error saying `

> [scallop] Error: Unknown option 'home'

Then I downloaded it directly from the yum repo and I tried running it with 

`/usr/bin/marathon --master zk://172.17.0.2:2181/mesos --zk zk://172.17.0.2:2181/marathon`

This time I don't get any errors, just a message on screen saying 

> run_jar --home /opt/marathon

But the marathon process is not starting and there is nothing showing up on the UI
I am using the latest version of Marathon and Mesos version 0.28.2

**Comment by jeschkies** [comment]
Which version did you download for the first case?

**Comment by durgaswaroop** [comment]
For the first case it was `V 1.1.1` which is the latest one. For the second case it was the recent version available on RHEL's recent version.

**Comment by aquamatthias** [comment]
@durgaswaroop You specified a command line option `--home /opt/marathon` or defined an environment variable `MARATHON_HOME=/opt/marathon` which translates to the command line option. That's why Marathon does not start up, since there is no such option.

**Comment by durgaswaroop** [comment]
It has been a while since I tried marathon now but I don't really remember setting any variables myself.  But I will try to see if this solves the issue.
