### ISSUE TITLE
Marathon Web UI not support mesos containerize 

### ISSUE THREAD

**Issue by HackToday** [mesosphere/marathon#4278]
From https://hub.docker.com/r/mesosphere/marathon/

The latest-dev marathon deployed, it seems it still use docker container, I did not find ways to use  `Mesos containerizer`

**Comment by HackToday** [comment]
From https://github.com/mesosphere/marathon/pull/4088  it seemed it had include such support, but web UI not expose that support

**Comment by HackToday** [comment]
@bernd-mesos  and @aquamatthias  From 
https://github.com/mesosphere/marathon/blob/master/changelog.md

I could find 
>Starting with version 1.3.0, Marathon supports docker container images without having the Docker Containerizer depend on a Docker Engine. Instead the Mesos containerizer with native AppC support added in Apache Mesos version 1.0 (released July 2016) directly uses native OS features to configure and start Docker containers and to provide isolation.

But when tried marathon 1.3.2 , the UI still not have it, it just have docker container.

Could you help confirm when it would be OK in UI part ?

**Comment by aquamatthias** [comment]
@HackToday The UI currently only support this via JSON mode. There is no specific UI for this.

**Comment by HackToday** [comment]
Thanks @aquamatthias , I referred here : https://github.com/apache/mesos/blob/master/docs/container-image.md

Could you tell me where  can find the proper json format for `Unified Containerizer` ? Any link would be helpful

The link here http://mesosphere.github.io/marathon/docs/rest-api.html  only contains docker container examples.  I did not know what's the format for `Unified Containerizer`

**Comment by aquamatthias** [comment]
@HackToday Please see 
https://mesosphere.github.io/marathon/docs/native-docker.html
See Section: Mesos Containerizer and Universal Container Runtime

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1923. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
