### ISSUE TITLE
Idea: support prioritization of tasks

### ISSUE THREAD

**Issue by andrewortman** [mesosphere/marathon#4285]
We have a fairly large cluster now and several hundred applications running. Some of these applications are business critical - ie, they go down and we start to loose money while some of the applications are simple intern toys or hackathon projects.

We would be interested in potentially setting a "priority" level on applications - a simple weight of which applications get offer priority in the case of partial cluster outage or if a slave goes down and tasks need to be rescheduled. 

We could do this with roles, but right now marathon only supports one additional role beyond the default '*' role

Another problem is preemption. If a subset of machines go down, we want to kill the super-low priority offers on other machines if room isn't available.

**Comment by aquamatthias** [comment]
@andrewortman I agree with this proposal. Multiple roles and preemption is on the roadmap.

To workaround the current limitation of one additional role: you could use multiple Marathon instances (e.g. one for high prio and one for everything else).

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2435. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
