### ISSUE TITLE
How to disable marathon auto-scale?

### ISSUE THREAD

**Issue by JerryDog** [mesosphere/marathon#4287]
I have a marathon with 5 tasks. 
node1 have 3 containers and node2 have 2 containers.

when node2 shutdown. marathon will start 2 new containers on node1. I don't want this happen.
I just want 3 containers live then. And then I can start node2 and resumed the 2 exited containers.

**Comment by jdef** [comment]
Sounds like you want residency, for example:

"""
"residency": { "taskLostBehavior": "WAIT_FOREVER" }
"""

Also, see the related documentation on UpgradeStrategy

**Comment by meichstedt** [comment]
@JerryDog Can you be more specific about the problem? Is the problem that you don't want 5 tasks on one agent? Marathon will always try to satisfy the wanted instance count as defined by the `instances` value. So it is perfectly reasonable to launch two tasks on agent 1 if agent2 is no longer available and there are no constraints to prevent this.

Seems to me like you'd want to use the new `MAX_PER` (see [here](https://github.com/mesosphere/marathon/blob/releases/1.3/docs/docs/constraints.md#max_per-operator)) constraint introduced with Marathon 1.2 RC's which will officially be available in the upcoming 1.3 release. That will allow to specify a maximum number of tasks e.g. per node.

**Comment by JerryDog** [comment]
@jdef thanks!   I used what you said,  and I create a marathon application. But the app keep "Deploy" state, here is my json.
`{

  "id": "myadd",

  "cpus": 1,

  "mem": 128,

  "disk": 0,

  "instances": 5,

  "container": {
	  "volumes": [{
            "containerPath": "nginx",
            "mode": "RW",
	    "persistent": {
	         "size": 100
	    }
           }],
    "docker": {
      "image": "nginx",
      "parameters": [
        {
          "key": "net",
          "value": "mac_net1"
        }
      ]
    },
    "type": "DOCKER"
  },
  "residency": {
    "taskLostBehavior": "WAIT_FOREVER"
  },
  "upgradeStrategy": {
    "maximumOverCapacity": 0,
    "minimumHealthCapacity": 0
  }
}`

And if I don't use "volumes" and "residency", the app can be created successfully.

**Comment by JerryDog** [comment]
@meichstedt thanks! I want to ensure the tasks on agent2 will not be lost  if agent2 is no longer available. 
Because I have some import files on those tasks. I want to keep tasks persistent. 
As you said, It seems to be no way to solve.

**Comment by meichstedt** [comment]
@JerryDog as I've mentioned above, you could use the `MAX_PER` constraint to restrict the maximum number of tasks per node. Feel free to reopen if you have a specific use case that is not covered.
