### ISSUE TITLE
Dcos marathon application does not auto restart when the slave ec2 instance is down

### ISSUE THREAD

**Issue by viveksatasiya** [mesosphere/marathon#4288]
hello,

I have started DC/OS cluster on AWS using cloudformation template. I have created on task on public slave instance using following marathon template.

> {
>   "id": "/haproxy-public-1",
>   "cmd": null,
>   "cpus": 0.5,
>   "mem": 128,
>   "disk": 0,
>   "instances": 1,
>   "constraints": [
>     [
>       "hostname",
>       "UNIQUE"
>     ]
>   ],
>   "acceptedResourceRoles": [
>     "slave_public"
>   ],
>   "container": {
>     "type": "DOCKER",
>     "volumes": [],
>     "docker": {
>       "image": "sargun/haproxy-demo:3",
>       "network": "HOST",
>       "privileged": false,
>       "parameters": [],
>       "forcePullImage": false
>     }
>   },
>   "env": {
>     "CONFIGURL": "https://gist.githubusercontent.com/viveksatasiya/0b793382d210de0d12d1b537aa5a5096/raw/56dcd1112b4a7ce09151b5040c82090d1612dfae/dcos-loadtest-haproxy-config.txt"
>   },
>   "healthChecks": [
>     {
>       "path": "/login/getLogin",
>       "protocol": "HTTP",
>       "portIndex": 0,
>       "gracePeriodSeconds": 300,
>       "intervalSeconds": 5,
>       "timeoutSeconds": 3,
>       "maxConsecutiveFailures": 1,
>       "ignoreHttp1xx": false
>     }
>   ],
>   "portDefinitions": [
>     {
>       "port": 80,
>       "protocol": "tcp",
>       "labels": {}
>     }
>   ],
>   "requirePorts": true,
>   "upgradeStrategy": {
>     "minimumHealthCapacity": 0.9,
>     "maximumOverCapacity": 0.2
>   }
> }

when I forcefully stop an ec2 instance from aws console, my task becomes unhelathy instantly but it does not auto restart on another public slave machine. It waits for mesos to remove node from the cluster and when node has been removed by cluster and new ec2 instance is up and joined the cluster at that time it starts a new task and kill old unhealthy task.

Why marathon does not start instantly new task when it finds that task unhealthy?

Am I making any mistakes??

Thanks in advance.

**Comment by viveksatasiya** [comment]
Hello,

I have debugged on master and get to know that mesos master in DC/OS has --agent_removal_rate_limit=1/20mins parameter set by default that's why it is taking time to remove that agent from the cluster.

Marathon is not starting task again on another node until mesos master removes that failed node from cluster.

Why marathon does not start instantly new task when it finds that task unhealthy?

and is there any way to change  --agent_removal_rate_limit=1/20mins parameter in DCOS??

Thanks.

**Comment by aquamatthias** [comment]
Hi @viveksatasiya 
Which version of Marathon do you run?
How many public nodes do you have?

Without logs it is hard to say what happened - please provide logs.

Generally:
If you restart a node, all tasks are defined as lost.
Marathon will try to start replacement tasks for the lost tasks.
In your case you need at least 2 public nodes to start a replacement task.
The original task will be expunged after the gc timeout (Marathon 1.1: 24 hours, Marathon 1.3 75 seconds in default configuration)

**Comment by viveksatasiya** [comment]
Hi @aquamatthias ,

Thanks for the reply. Actually I have other spare public nodes in the cluster on which Marathon can start another instance and it is also starting another instance on another node but after 75 seconds which also have been mentioned by you in your reply which is working fine, but the thing is that Marathon should start another instance on spare nodes immediately It should not wait for 75 seconds.I think that It should wait for 75 seconds to kill old instance not for starting another instance.

Please correct me if I am wrong??

**Comment by aquamatthias** [comment]
1) task lost
The task is declared lost after 75 seconds in Mesos (default settings).
You can change the defaults to see such problems earlier.

2) health checks
You can do more aggressive health checks in Marathon.
Health Checks as implemented today waits for the task to die, before a new task is started.

**Comment by viveksatasiya** [comment]
Ok thanks a lot. :)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2420. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
