### ISSUE TITLE
[scallop] Error: Unknown option 'home'

### ISSUE THREAD

**Issue by deepsignals** [mesosphere/marathon#4301]
Hi,

I deployed 3 Mesos masters and 4 agents (version 1.0.1) on 3 Zookeeper nodes. About Marathon, I tried both binary version 1.1.1 and another built from source version 1.3.0-RC6.

However, I was failed to start with following settings:
```
$ export MESOS_NATIVE_LIBRARY=$MESOS_BUILD_DIR/src/.lib/libmesos.so
$ export MESOS_NATIVE_JAVA_LIBRARY=$MESOS_NATIVE_LIBRARY
$ ./marathon/bin/start --master zk://$ZK_LIST/mesos --zk zk://$ZK_LIST/marathon
```

Here is detailed information of error:

Marathon v1.1.1
```
MESOS_NATIVE_LIBRARY, MESOS_NATIVE_JAVA_LIBRARY set to '/app/mesos/build/src/.lib/libmesos.so'
[2016-09-05 19:35:16,076] INFO Starting Marathon 1.1.1 with --home /app/marathon --h /app/marathon --master zk://172.28.50.5:2181,172.28.50.6:2181,172.28.50.7:2181/mesos --zk zk://172.28.50.5:2181,172.28.50.6:2181,172.28.50.7:2181/marathon (mesosphere.marathon.Main$:main)
[scallop] Error: Unknown option 'home'
```

Marathon v1.3.0-RC6, run in dev mode
```
MESOS_NATIVE_LIBRARY, MESOS_NATIVE_JAVA_LIBRARY set to '/app/mesos/build/src/.lib/libmesos.so'
[scallop] Error: Unknown option 'home'
```

I googled many times, but I still not figured out any solution. Could you please help me fix it?

Regards,

**Comment by aquamatthias** [comment]
Marathon will translate all env vars starting with `MARATHON_` as command line args: https://github.com/mesosphere/marathon/blob/master/bin/start#L43
```
MARATHON_HOME=/app/marathon
```
Will lead to the behavior you describe, so I guess you have set this env var?
I will close this ticket - please reopen, if this does not solve the problem.
