### ISSUE TITLE
Update TaskBuilder so we can launch Pods

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#4302]
- [ ] Add TaskGroupBuilder
- [ ] adapt TaskOpFactory
- [ ] AppDefinition should start a task --> TaskBuilder
- [ ] Pod should start a task group --> TaskGroupBuilder

**Comment by nfnt** [comment]
PR for `TaskGroupBuilder`: https://github.com/mesosphere/marathon/pull/4353
