### ISSUE TITLE
UI Displays two health tasks when only one is healthy and one is TASK_LOST

### ISSUE THREAD

**Issue by jamiethermo** [mesosphere/marathon#4321]
![image](https://cloud.githubusercontent.com/assets/9422866/18328000/daeca188-7501-11e6-83ce-9ce1f28c6ff5.png)

but

![image](https://cloud.githubusercontent.com/assets/9422866/18328014/ef390db6-7501-11e6-8a75-23caaa928a41.png)

**Comment by jamiethermo** [comment]
App config:

```
{
  "id": "/edt/crschr-reliable-task-framework",
  "cmd": null,
  "cpus": 0.5,
  "mem": 1000,
  "disk": 0,
  "instances": 1,
  "container": {
    "type": "DOCKER",
    "volumes": [],
    "docker": {
      "image": "<docker image using>",
      "network": "HOST",
      "privileged": false,
      "parameters": [
        {
          "key": "label",
          "value": "<iam role>"
        }
      ],
      "forcePullImage": true
    }
  },
  "healthChecks": [
    {
      "path": "/",
      "protocol": "HTTP",
      "gracePeriodSeconds": 30,
      "intervalSeconds": 60,
      "timeoutSeconds": 20,
      "maxConsecutiveFailures": 3,
      "ignoreHttp1xx": false,
      "port": 2179
    }
  ],
  "portDefinitions": [
    {
      "port": 2179,
      "protocol": "tcp",
      "labels": {}
    }
  ],
  "args": [
    "10.254.193.20"
  ]
}
```

**Comment by jamiethermo** [comment]
![image](https://cloud.githubusercontent.com/assets/9422866/18328514/ebe47cf2-7503-11e6-9975-18ef017f28af.png)

**Comment by jamiethermo** [comment]
Grepped out the GETs:

[marathon-useful.log.zip](https://github.com/mesosphere/marathon/files/460400/marathon-useful.log.zip)

**Comment by Daniel-ltw** [comment]
marathon command line flags is what you need. 

both task_lost_expunge_gc and task_lost_expunge_interval is what you are searching for.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1731. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
