### ISSUE TITLE
Document Task Kill behavior introduced with Mesos 1.0 kill policies

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#4323]
Marathon 1.3 has implemented 2 features for graceful shutdown:
- taskKillGracePeriod:  is the time between a task get a SIGTERM and waits for the task to die until a SIGKILL is send. The task is responsible for terminating in that time, until it is killed forcefully. 
- TASK_KILLING: a new task state has been introduced in Mesos, which signals, that a task got a kill request and is in the grace period. Other tools (e.g. load balancer, service discovery etc) should not route traffic to tasks in that state

This behavior should be documented in the Marathon gh pages.

**Comment by c3st7n** [comment]
Has this issue been addressed already? It looks like it might have: https://github.com/mesosphere/marathon/issues/4323

**Comment by aquamatthias** [comment]
@sascala Please update this ticket with a reference to the documentation and close this ticket.

**Comment by kangman** [comment]
Hi @sascala is this in the documentation yet?  I cannot see where to see examples of how to use these features when trying to drain a node for maintenance and the like.

**Comment by janisz** [comment]
`taskKillGracePeriod` has no effect with Mesos executor with shell task see [MESOS-6933](https://issues.apache.org/jira/browse/MESOS-6933)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2314. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
