### ISSUE TITLE
Document secrets handling in Marathon

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#4324]
Marathon 1.3 has added secrets to environment variables.
The AppDefinition supports defining secret env vars and secrets.
In order to make secrets work, you need to write a plugin to render secret values.

This is a plugin extension that needs to be documented as part of the plugin extension hooks.

**Comment by scottjpack** [comment]
Hey @aquamatthias , interested in getting these docs.  Is there a draft anywhere I could take a look at?

**Comment by aquamatthias** [comment]
@scottjpack busy times - sorry no doc yet.

The gist of it:
1) You can define an app definition like this
```json
{
  "id": "/foo",
  "user": "root",
  "secrets": {
    "secret1": { "source": "/path/in/secret/store/eg/db/password" }
  }
  "env": {
    "PASSWORD": { "secret": "secret1" }
  },
}
```

It defines secrets with a source and assigns a name (secret1 in this example)
You can reference this secret as environment variable.

2) You have to define a plugin, which can resolve secrets and sets those values as environment variables.
See: https://github.com/mesosphere/marathon/blob/master/plugin-interface/src/main/scala/mesosphere/marathon/plugin/task/RunSpecTaskProcessor.scala#L11

3) Whenever a task is started, this plugin is called to set the correct env vars.

Hope this helps as a quick start.

**Comment by petr-k** [comment]
Is the corresponding GUI shown at https://docs.mesosphere.com/1.8/administration/secrets/config-service/ (step 8) in a non-public Marathon fork, a non-public Marathon plugin or something else altogether?

**Comment by aquamatthias** [comment]
@petr-k this link points to DC/OS which has its own UI and secrets implementation. There is currently no GUI support in Marathon.

**Comment by koshelev** [comment]
@aquamatthias Should secrets handling be considered a beta functionality as it relies on plugins?

**Comment by aquamatthias** [comment]
@koshelev That is intended since there can be different secrets provider. Marathon provides an API for secrets, but no implementation. The whole functionality has a feature flag, so you can adjust if secrets are allowed or not.

**Comment by aquamatthias** [comment]
@sascala can you add a section to secrets handling to our gh-pages site?

**Comment by sascala** [comment]
@aquamatthias Of course

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2432. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
