### ISSUE TITLE
i suggest marathon support dependcy environment inject automatic

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#4325]
eg:
{
    "id": "develop/demo",
    "apps": [
        {
            "id": "app-test01",
            ...
            "env": {
                "APP01_PARAM1": "aaa",
                "APP01_PARAM2": "bbb"
            },
            "dependencies": [],
        },
        {
            "id": "app-test02",
            "env": {
                "APP02_PARAM1": "ccc",
                "APP02_PARAM2": "ddd"
            },
            "dependencies": ["../app-test01"],
            ...
        }
    ]  
}

app-test02 depend app-test01
so , we want marathon inject app-test01's ENV:
develop_demo_app-test01_APP01_PARAM1
develop_demo_app-test01_APP01_PARAM2
to app-test02's ENV

thanks!

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2390. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
