### ISSUE TITLE
does marathon support batch deployment on every one of given host list?

### ISSUE THREAD

**Issue by junneyang** [mesosphere/marathon#4327]
eg:  
APP: apptest
HOSTS: serverA, serverB,serverC

we want serverA, serverB,serverC all has one apptest instance.
 
thanks!

**Comment by aquamatthias** [comment]
Marathon supports rolling restarts: https://mesosphere.github.io/marathon/docs/deployments.html
You can use constraints to define the servers, the application can run on: https://mesosphere.github.io/marathon/docs/constraints.html

Not 100% sure what you want to achieve, but you could use GROUP_BY to spread the load.
During an upgrade you will have the old version and the new version side by side (default) until the new version is ready and healthy and then the old version is stopped.

**Comment by junneyang** [comment]
eg:
i want a app(say test01) deploy on three hosts(say server01, server02, server03)
how to achieve this goal?
thanks!

**Comment by aquamatthias** [comment]
You can say something like this:

```json
  "constraints": [
    [ "hostname", "LIKE", "server0[123]" ],
    [ "hostname", "UNIQUE" ]
  ]
```

The first constraint says: only deploy on server01, server02 or server03.
The seconds one says: only deploy once instance of the app per host.

Another approach:
you can define attributes on server01, server02 and server03 - e.g. `rack_id=rack1`
Then you can say:
```json
  "constraints": [
    [ "rack_id", "GROUP_BY" ]
  ]
```
