### ISSUE TITLE
App keeps showing `Waiting` 1.3.0-RC6

### ISSUE THREAD

**Issue by drcrallen** [mesosphere/marathon#4335]
<img width="1425" alt="screen shot 2016-09-08 at 9 40 22 am" src="https://cloud.githubusercontent.com/assets/8213081/18358182/c4006e9e-75a8-11e6-93d0-ae51778347cc.png">

I have an app which I had scaled up to more nodes than were available, but didn't end up allocating more resources, so I scaled it back down to 1, which it already had. The status is stuck as `Waiting`

**Comment by drcrallen** [comment]
Restarting marathon fixed this

**Comment by unterstein** [comment]
Hi @drcrallen,

I recently tried this with the current marathon ui with a `hostname:UNIQUE` constraint and through scaling this back to 1 instance i receive the following screen:
<img width="949" alt="screenshot 2016-09-09 12 51 50" src="https://cloud.githubusercontent.com/assets/904420/18384679/39ef498e-768c-11e6-9422-5b66c7aa4809.png">

Maybe something strange happens in your scenario. I am closing this issue now. If this happens again please open this ticket again and it would be super cool if you could add some logs, your app definition and the information from the debug tab.

Thanks,
Johannes

**Comment by drcrallen** [comment]
If it happens again I'll see if I can get it reproducible. Thanks!
