### ISSUE TITLE
Apps shown as 'Unhealthy' even within `gracePeriodSeconds` - 1.3.0

### ISSUE THREAD

**Issue by drcrallen** [mesosphere/marathon#4337]
I have an app which has a setting for health checks of `"gracePeriodSeconds": 21600` because it takes a long time to reach healthy state. But Marathon 1.3.0 is listing it as UNHEALTHY way before the grace period has elapsed.

**Comment by unterstein** [comment]
Hi @drcrallen,

I retested this a couple of seconds ago and I could configure an app with taskKillGracePeriodSeconds through the UI which is recognized and passed correctly. This app goes from Running -> Killing -> Killed. Could you please paste your app definition so that I can retest?

Thanks
Johannes

**Comment by drcrallen** [comment]
The grace period I'm talking about here is the grace period after startup (or first healthy) that an app is allowed before being considered unhealthy.

**Comment by drcrallen** [comment]
It doesn't seem to kill the application, but it does now report it as Unhealthy.

**Comment by unterstein** [comment]
Hi @drcrallen,

as far as I can see this here https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/core/health/impl/HealthCheckActor.scala#L133 all health check results are ignored until the grace period is reached OR at least one health check result was successful. Maybe your system returns at some a success to the health check?

Kind regards
Johannes

**Comment by drcrallen** [comment]
@unterstein I'll monitor this more once the 1.3.0 release is deployed on the same systems. It doesn't kill the instances, just labels them as unhealthy in the UI (I didn't check the raw status from an api call). This is a deviation from the 1.1 behavior where it was staying in the running state with unknown health until at least the elapsed time.

Will continue to monitor and update if it happens on the official release.

**Comment by drcrallen** [comment]
https://github.com/mesosphere/marathon/issues/4391 fixed the stable release packaging, I'll see if I can get a reliable test thing for this item.

**Comment by drcrallen** [comment]
Ok here's the app def that reliably reproduces what I'm seeing:



```json
{
  "id": "/fake",
  "cmd": "python -m SimpleHTTPServer $PORT0",
  "cpus": 0.01,
  "mem": 32,
  "disk": 0,
  "instances": 1,
  "healthChecks": [
    {
      "path": "/",
      "protocol": "HTTP",
      "portIndex": 0,
      "gracePeriodSeconds": 30,
      "intervalSeconds": 5,
      "timeoutSeconds": 1,
      "maxConsecutiveFailures": 3,
      "ignoreHttp1xx": false,
      "port": 0
    },
    {
      "protocol": "COMMAND",
      "command": {
        "value": "exit 1"
      },
      "gracePeriodSeconds": 300,
      "intervalSeconds": 60,
      "timeoutSeconds": 20,
      "maxConsecutiveFailures": 3,
      "ignoreHttp1xx": false
    }
  ],
  "portDefinitions": [
    {
      "port": 10000,
      "protocol": "tcp",
      "name": "rpc",
      "labels": {}
    }
  ]
}
```

You'll notice there are two health checks. The first succeeds very quickly, and the second will never succeed but has a 300 second grace period.

The app almost instantly becomes listed as "unhealthy" way before the 5 minute grace period of the second health check.

**Comment by drcrallen** [comment]
The application won't be terminated within the grace period, but it is confusing for any api consumer which is monitoring for unhealthy nodes.

**Comment by drcrallen** [comment]
also confusing for any UI operator who is trying to figure out if deployment is in a bad state or is still ongoing.

**Comment by drcrallen** [comment]
Also I think in 1.1.x it simply retained an Unknown status until the grace period elapsed

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2181. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
