### ISSUE TITLE
Deployments REST API documentation/example invalid

### ISSUE THREAD

**Issue by stepanv** [mesosphere/marathon#4351]
The deployments REST API documentation https://mesosphere.github.io/marathon/docs/rest-api.html#get-v2-deployments implies that `steps` are an array of array as follows

> ```
> "steps": [
>             [
>                 {
>                     "action": "RestartApplication", 
>                     "app": "/test/service/srv1"
>                 }
>             ], 
>             [
>                 {
>                     "action": "RestartApplication", 
>                     "app": "/test/db/mongo1"
>                 }
>             ],
>             ...
> ```

However, running `GET` to `/v2/deployments` against a real instance of Marathon (v1.1.1) I get a different class model (an array of *action objects* that contain an array):

```
  "steps": [
    {
      "actions": [
        {
          "type": "StopApplication",
          "app": "/service-foo/app"
        }
      ]
    },
    {
      "actions": [
        {
          "type": "StopApplication",
          "app": "/service-bar/app"
        }
      ]
    }
  ],
```

Is it possible that the doc needs an update?

**Comment by unterstein** [comment]
Hi @stepanv,

thanks for reporting this. In 1.2/1.3 we changed `type` to `action`. So this should be updated to:

```
  "steps": [
    {
      "actions": [
        {
          "action": "RestartApplication",
          "app": "/test/service/srv1"
        }
      ]
    },
    {
      "actions": [
        {
          "action": "RestartApplication",
          "app": "/test/db/mongo1"
        }
      ]
    }
  ],
```
