### ISSUE TITLE
Not able to create user defined network from marathon

### ISSUE THREAD

**Issue by LiginGeorge** [mesosphere/marathon#4359]
I am using marathon 1.1.2 , and mesos 1.0.0 version. I have created  user defined n/w in slave server in docker. I would like to launch container from marathon using user defined network. But if i specify Network type USER its not recognizing and throwing error. In the Networking type Bridge and Host mode only its taking by marathon. Let me know how to configure user defined n/w.

**Comment by unterstein** [comment]
Hi @LiginGeorge,

could you specify which error is thrown? It would be useful if you could provide the marathon logs showing this error.

Thanks
Johannes

**Comment by LiginGeorge** [comment]
Hi,

 I am getting Invalid Network type (  "network": "USER",) i have specified instead of brige. Here i am giving the json file which i have tried in my scenario. How can i enable USER network type in from marathon.
{
    "id": "nginx",
    "container": {
        "docker": {
            "image": "nginx",
            "network": "USER",
            "portMappings": [{
                "containerPort": 80,
                "hostPort": 0,
                "protocol": "tcp"
            }],
            "parameters": [{
                "key": "volume-driver",
                "value": "local-persist"
            }, {
                "key": "volume",
                "value": "dcmadm_data:/data/www"
            }]
"networkInfo": [
    {
      "name": "DCM"
    }
  ]
     }
          },
    "cpus": 0.2,
    "mem": 32.0,
    "instances": 1
}

**Comment by LiginGeorge** [comment]
Hi @unterstein  

 Did you get any chance to check this issue

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2541. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
