### ISSUE TITLE
Create InstanceRepository and migrate tasks

### ISSUE THREAD

**Issue by meichstedt** [mesosphere/marathon#4370]
Subtasks:
- [x] Create an `InstanceRepository`
- [x] Migrate tasks -> instances

Pods/TaskGroups have several containers that need to be created/updated/deleted. To prevent multi-step reads/writes to the persistence layer when updating instances, it makes sense to introduce a

```
trait InstanceRepository extends Repository[Instance.Id, Instance] {
  def instances(runSpecId: PathId): Source[Instance.Id, NotUsed] = {
    ids().filter(_.runSpecId == runSpecId)
  }
}
```

in `Repositories`. That also solves the problem of recreating instances in-mem after a failover.

We then need a migration that loads all existing tasks, converts them to instances (incl an executorId which can be inferred from the taskId), stores them in the `InstanceRepository` and deletes them from the `TaskRepository` afterwards.

**Comment by aquamatthias** [comment]
@jasongilanfarr can you take this item?

**Comment by jasongilanfarr** [comment]
Yep
