### ISSUE TITLE
Names of the apps and groups are not visible on mobile

### ISSUE THREAD

**Issue by alenkacz** [mesosphere/marathon#4377]
![marathon-mobile](https://cloud.githubusercontent.com/assets/264608/18503359/dd711e6a-7a5c-11e6-9df6-d8b11c208988.png)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1856. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
