### ISSUE TITLE
Failed write to group:root upon application launch 

### ISSUE THREAD

**Issue by cmluciano** [mesosphere/marathon#4384]
Marathon 1.1.1
Mesos 0.28.0

I found an interesting issue that I'm looking to gather feedback on. On Marathon 1.1.1 it seems that a proper write was made to an application's ZK path and the application was launched by Marathon. 

We found that that same update did not happen to the general group:root node that seemingly stores all of the information for the global set of applications. So when we made a request to the the /apps API to check if the application was launched, it said no and it could not be searched for in the UI. But we could visit the exact path in the UI to find the running applications and seemingly hit the API at that applications exact path.

Can anyone think of a reason that the group:root node would not be updated or would be unsuccessful?

We "fixed" this by making a minor change to the 6 affected applications to trigger a new deployment of them in Marathon.

**Comment by jasongilanfarr** [comment]
Did the root group happen to exceed 1mb and/or was there a "very strange ZK error in the logs"? While this is likely fixed in #4178 which comes in 1.4, if you can provide more data it'd be very helpful.

**Comment by cmluciano** [comment]
There are some around 400mb but not greater

**Comment by jasongilanfarr** [comment]
I meant the size of the ZK nodes, not the size of the apps.

**Comment by cmluciano** [comment]
Yep that's the size of some of the zknodes

**Comment by cmluciano** [comment]
I should mention that this is 2 marathons at roughly 3600 apps a piece

**Comment by aquamatthias** [comment]
ZK in default configuration fails to store nodes greater 1MB. 
Marathon <= 1.3 stores all apps and groups into the root node (compressed).
Marathon 1.1.3 implements a size check, so it will fail if the size exceeds this maximum.
Please upgrade to this version, to see if this is the problem you are running into.

**Comment by cmluciano** [comment]
By fail does that just mean that a clients request is rejected?

**Comment by jasongilanfarr** [comment]
That is correct yes.

**Comment by aquamatthias** [comment]
Marathon 1.4 has a greatly improved zk storage layout, so we don't have this kind of limitation any longer.
