### ISSUE TITLE
Response from new app is not 200 (1.3.0-RC6)

### ISSUE THREAD

**Issue by drcrallen** [mesosphere/marathon#4407]
A PUT to `/v2/apps/some_id` with a new app definition gave back a 201 instead of a 200 as indicated in the API explorer.

The API explorer doesn't even list a 201 as a valid return from `/v2/apps/{app_id}`.

**Comment by aquamatthias** [comment]
201 is the correct status code for creating the entity. This is missing in the documentation.

**Comment by aquamatthias** [comment]
The RAML docs now define 201 as response code.
