### ISSUE TITLE
Marathon quit immediately after service start. (Due to not set java 8 as default, docs need improve)

### ISSUE THREAD

**Issue by eromoe** [mesosphere/marathon#4413]
I fellow this doc https://open.mesosphere.com/getting-started/install/ .
I didn't create 3 mesos-master because I only had three vm,  just ran mesos-master and zookeeper on one vm , other two planed to install mesos-slave(not setup yet).
Atfer I finished first vm install, I could access mesos from `xxx.xxx.xxx.xxx:5050`,  but couldn't access marathon from `xxx.xxx.xxx.xxx:8080`. Then I found marathon quit immediately after  `service marathon start`.

None of `/etc/marathon/conf` and `/etc/default/marathon` existed, so all configurition was as default.

mesos log files in `/var/log/mesos`:

```
mesos-master.INFO                                                  
mesos-master.ubuntu12.invalid-user.log.WARNING.20160918-164449.32134
mesos-master.ubuntu12.invalid-user.log.INFO.20160918-164449.32134  
mesos-master.WARNING
```

invalid-user in log filename? but I can access   `xxx.xxx.xxx.xxx:5050`.

marathon log content:

```
$ tail /var/log/upstart/marathon.log
run_jar --zk zk://localhost:2181/marathon --master zk://localhost:2181/mesos
run_jar --zk zk://localhost:2181/marathon --master zk://localhost:2181/mesos
run_jar --zk zk://localhost:2181/marathon --master zk://localhost:2181/mesos
run_jar --zk zk://localhost:2181/marathon --master zk://localhost:2181/mesos
run_jar --zk zk://localhost:2181/marathon --master zk://localhost:2181/mesos
run_jar --zk zk://localhost:2181/marathon --master zk://localhost:2181/mesos
```

Any way to work around?

**Comment by eromoe** [comment]
solved by set java8 as default, thanks to https://github.com/mesosphere/marathon/issues/3891
Doc should add this! The whole doc doen't mention set java8 as default except one line 
```
Requirements
    ....
    JDK 1.8+
```
Who would know it has such extra requirement if he doesn't familiar with java stack? 
At least I don't.

**Comment by aquamatthias** [comment]
@eromoe Thanks for this hint
Java 8 is defined as requirement for Marathon: https://mesosphere.github.io/marathon/docs/
The native package enforce JDK 1.8.

I agree we should be more clear on saying, that the default jvm should be set to java8.
@sascala Please add this to our docs.

**Comment by sascala** [comment]
https://github.com/mesosphere/marathon/pull/4698
