### ISSUE TITLE
Support 1 down/1 up upgradeStrategy for apps with persistent volumes

### ISSUE THREAD

**Issue by marc-lebourdais** [mesosphere/marathon#4416]
Marathon already handles this special case for upgradeStrategy:

```
minimumHealthCapacity: 1
maximumOverCapacity: 0
```

If not, upgrades would be deadlocked. This is easy to see, since 100% of instances are required to be healthy at all times (i.e. none can be killed first), and no more than 100% of instances can exist (i.e. none can be started first).

Marathon chooses to handle this special case by starting one extra instance first and then taking down one existing instance. Lather, rinse and repeat. With applications using persistent volumes, it's also straightforward to see why this won't work. However, there is a requirement that `minimumHealthCapacity <= 0.5`, which results in at least 50% of instances being killed during an upgrade (or restart). Without having looked at the code, I imagine that this requirement is based off of a `ceil(N*minimumHealthCapacity)` calculation to determine the number of instances to take down. If `N = 1`, you can still upgrade a single-instance application with persistent volumes.

This strategy yields undesirable effects for a persistent-storage app running potentially hundreds of instances (arguably even one running just 3 instances), where half of the instances get killed immediately. I propose for persistent apps that `minimumHealthCapacity` not be constrained, and instead allowed a range of `[0, 1]` with the special case being handled such that for `N-floor(N*minimumHealthCapacity) < 1`, only a single instance will be killed/started at a time.

**Comment by christianparpart** [comment]
I am actually really missing that feature, too. It's not really promoting high availability (as it creates a downtime in between), but it does make sense and that's why we're currently manually suspend apps to scale them back up to 1 right after. ;)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2118. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
