### ISSUE TITLE
Add validation rule to fail if multiple Mesos healthchecks are defined.

### ISSUE THREAD

**Issue by danoprita** [mesosphere/marathon#4421]
Hi,

I have a Docker container and I want to add 2 COMMAND healthchecks for it:
1. curl -f -X GET http://$HOST:$PORT0
2. curl -f -X GET http://hostname-another-app:8095/status

First command passes. The second one fails. 

Expected result:
Marathon should display the application as Unhealthy. 

Actual Result:
Marathon displays the application as Healthy.

When I edit the configuration and leave only the second healthcheck (the one that fails), Marathon correctly displays the application as Unhealthy.

It seems that Marathon doesn't handle correctly multiple COMMAND healthchecks.

**Comment by aquamatthias** [comment]
@danoprita Mesos currently only supports one health check.
We need to add a validation rule to make sure you get an error, if you specify more than on command health check.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1922. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
