### ISSUE TITLE
how to get a task status(TASK_RUNNING and so on) through marathon REST API?

### ISSUE THREAD

**Issue by tanglianggithub** [mesosphere/marathon#4441]
task statuses include:
TASK_STAGING
TASK_STARTING
TASK_RUNNING
TASK_FINISHED
TASK_FAILED
TASK_KILLED
TASK_LOST

I saw them on https://mesosphere.github.io/marathon/docs/event-bus.html.
But don't know how to get task status through marathon REST API.

**Comment by jeschkies** [comment]
The [groups](https://mesosphere.github.io/marathon/docs/rest-api.html#groups) expose task stats. Could that help?

**Comment by aquamatthias** [comment]
The most natural endpoint is `/v2/tasks` which lists all the tasks.
You can also use the `/v2/apps` and `/v2/groups` endpoint with embedded task information.

The json looks like this:
```json
{
            "appId": "/sll",
            "host": "192.168.99.1",
            "id": "sll.137a704f-8ed8-11e6-a147-2a2bf4e4eca6",
            "ipAddresses": [
                {
                    "ipAddress": "192.168.99.1",
                    "protocol": "IPv4"
                }
            ],
            "ports": [
                31559
            ],
            "servicePorts": [
                10000
            ],
            "slaveId": "c3e35d6b-3a10-4baa-bdd4-7d7b360134e1-S0",
            "stagedAt": "2016-10-10T10:55:37.226Z",
            "startedAt": "2016-10-10T10:55:37.875Z",
            "state": "TASK_RUNNING",
            "version": "2016-10-10T10:55:37.215Z"
        }
```

See state.
