### ISSUE TITLE
[Pods] We need to validate the id of the pod during creation

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#4449]
Create pod with id `/myPod` should be rejected

**Comment by unterstein** [comment]
`instanceId="/myPod"` should be rejected, but instanceId for `runspecId="/myPod"` should be valid, right?

**Comment by aquamatthias** [comment]
The validation rule for PathId forbids uppercase characters.
This is not checked during creation.
If you want to query a pod, you get a validation error.
