### ISSUE TITLE
Marathon 1.3.0 frequent crashes

### ISSUE THREAD

**Issue by christianparpart** [mesosphere/marathon#4454]
Hey all,

since we've upgraded to Marathon 1.3.0 (up from 1.1.x) we noticed frequent leader changes (some times many times within a single hour) in our 3-node Marathon cluster. We then found out that this is due to the leading marathon docker instance crashing. However, I do not find anything _really_ useful in the `docker log` output to tell me what the actual root cause is. Since the marathon docker instances are configured with `--restart=always` they're quickly coming up again, but the leader changes, and thus, we also see tons of Health Check status updates in the Marathon event stream in `/v2/events` where our service discovery hooks into (so we noticed).

The question is, why is it crashing? The only leads I found are HTTP errors like:

```
[2016-09-22 13:37:22,914] WARN Illegal response header: Illegal 'Access-Control-Request-Method' header: Invalid input ',', expected TokenCha
POST, PUT, DELETE, GET, OPTIONS                                                                                                             
    ^                                                                                                                                       
```

and:

```
[2016-09-22 13:37:22,918] WARN Illegal response header: Illegal 'Set-Cookie' header: Invalid input 'l', expected OptWS, ';' or EOI (line 1, 
partner=xxxxxxxxxx; domain=.xxxxxxx.com; path=/; expires=Fri, 22-Sep-2017 13:37:22 GMTlang=de_DE; domain=.dawanda.com; path=/; expires=Mon, 
                                                                                      ^                                                     
```

However, I suspect that cannot be the cause of the docker instance crash (we're not limiting in HW resources either).

What can I provide you to understand our marathon instance crashes better?

**Comment by jeschkies** [comment]
Hi,

could you provide a few more details of the setup. Are you running Marathon within DC/OS or plain on Mesos with a Docker container?

**Comment by aquamatthias** [comment]
@christianparpart Can you attach the complete logs from mesos and marathon?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2362. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
