### ISSUE TITLE
Depend on default-jre-headless

### ISSUE THREAD

**Issue by nhandler** [mesosphere/marathon#4460]
The marathon deb packages in the mesosphere apt repository currently depend on `java8-runtime-headless`. Per the [Debian policy for Java](https://www.debian.org/doc/packaging-manuals/java-policy/x105.html):

> Programs must depend on the needed runtime environment (default-jre or default-jre-headless if need a GUI or not, and java<N>-runtime or java<N>-runtime-headless as provided by alternative Java environments).

The `default-jre-headless` package provides the `java8-runtime-headless` virtual package.

**Comment by aquamatthias** [comment]
@lloesche can you look into this?

**Comment by lloesche** [comment]
The quoting above removes the part where the Debian packaging policy actually says
```
...
default-jre or default-jre-headless if need a GUI or not, and java<N>-runtime or java<N>-runtime-headless as provided by alternative Java environments
...
```
where the `<N>` in `java<N>-runtime-headless` is the important part and also what we depend on: `java8-runtime-headless`.

We use the same dependency for old versions of Debian and Ubuntu where `default-jre-headless` doesn't point to Java 8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4328. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
