### ISSUE TITLE
Unable to get an application running with a docker container

### ISSUE THREAD

**Issue by jmat6** [mesosphere/marathon#4474]
Hi

I have setup the mesos and marathon on my local system. Also, I have docker engine running on my system, and when I do, `sudo docker images`, I get the following, 

```
REPOSITORY                                                 TAG                 IMAGE ID            CREATED             SIZE
myrepo/hello                                               latest              b7ce0084dbaf        4 weeks ago         330.3 MB
fluent/new                                                 latest              adc4b7b4b0eb        4 weeks ago         1.589 GB
<none>                                                     <none>              3a87799875ed        4 weeks ago         1.589 GB
<none>                                                     <none>              16a573cd3b85        4 weeks ago         330.3 MB
769348183957.dkr.ecr.us-east-1.amazonaws.com/ruby          2.1.10              77bf121d484e        8 weeks ago         1.535 GB
769348183957.dkr.ecr.us-east-1.amazonaws.com/centos-base   7                   9ab68a0dd16a        10 weeks ago        330.3 MB
hello-world                                                latest              c54a2cc56cbb        12 weeks ago        1.848 kB
docker/whalesay                                            latest              6b362a9f73eb        16 months ago       247 MB

```

Now, through the Marathon UI, I am trying to make an application, and after going doing all the steps in the documentation at `https://mesosphere.github.io/marathon/docs/native-docker-private-registry.html`, when I finally create the application, it's status varies between Deploying and Waiting intermittently and finally shows delayed. I never get it in the running stage. I try to figure out the logs on my machine but I am not able to make sense of them seeing their volume. 

My JSON config for the app was as follows: 

```
ID
/123
Command
Unspecified
Constraints
Unspecified
Dependencies
Unspecified
Labels
Unspecified
Resource Roles
Unspecified
Container
{
  "type": "DOCKER",
  "volumes": [],
  "docker": {
    "image": "769348183957.dkr.ecr.us-east-1.amazonaws.com/centos-base",
    "network": "BRIDGE",
    "privileged": false,
    "parameters": [],
    "forcePullImage": true
  }
}
CPUs
1
Environment
Unspecified
Executor
Unspecified
Health Checks
Unspecified
Instances
1
IP Address
Unspecified
Memory
128 MiB
Disk Space
50 MiB
Port Definitions
[
  {
    "port": 10000,
    "protocol": "tcp",
    "labels": {}
  }
]
Backoff Factor
1.15
Backoff
1 seconds
Max Launch Delay
3600 seconds
URIs
file:///etc/docker.tar.gz
User
Unspecified
Args
Unspecified
Version
2016-09-25T10:32:38.240Z
```

Am I missing anything? AFAIK, what should happen is the application should automatically pull this image from my local repo and finally get deployed on the machine. Should I also create a task for my application because I haven't made any task specifically? If yes, won't I have to first create an application and then add tasks to it?

**Comment by jeschkies** [comment]
Hi,

just so I'm understanding you correctly. You want to start an app in a docker image with Marathon and it's stuck in `Deploying` or `Waiting` state?

How big is the image you try to start? How fast is your connection?

**Comment by aquamatthias** [comment]
If your application is delayed, this means the task has been started multiple times, but failed.
This is an application specific problem.
Please look into the sandbox to see the log file of your application.
