### ISSUE TITLE
RAML docs on feature/pods branch inconsistent with HTML docs

### ISSUE THREAD

**Issue by cruhland** [mesosphere/marathon#4488]
Take a look at the response bodies in the HTML API docs for [`PUT /v2/apps/{appId}`](https://mesosphere.github.io/marathon/docs/rest-api.html#put-v2-apps-appid) and [`PUT /v2/groups/{groupId}`](https://mesosphere.github.io/marathon/docs/rest-api.html#put-v2-groups-groupid). Both responses look like the following JSON; I've confirmed this via the DC/OS CLI integration tests:

```json
{
    "deploymentId": "c0e7434c-df47-4d23-99f1-78bd78662231",
    "version": "2014-08-28T16:45:41.063Z"
}
```

Now compare that with the RAML docs on the `feature/pods` branch. For [apps](https://github.com/mesosphere/marathon/blob/6731f8a398951673a12a7b138a3d8cb7a2dc7a09/docs/docs/rest-api/public/api/v2/apps.raml#L262-L265), the response body is an [app.App](https://github.com/mesosphere/marathon/blob/6731f8a398951673a12a7b138a3d8cb7a2dc7a09/docs/docs/rest-api/public/api/v2/types/app.raml#L63). For [groups](https://github.com/mesosphere/marathon/blob/feature/pods/docs/docs/rest-api/public/api/v2/groups.raml#L94-L97), the response body is similarly a [group.Group](https://github.com/mesosphere/marathon/blob/91d03b0e23ad06b9cbd0dfe10cae094ed304f6a9/docs/docs/rest-api/public/api/v2/types/group.raml#L7) (note that the path for that endpoint seems to be incorrectly specified as `PUT /v2/groups` instead of `PUT /v2/groups/{groupId}`).

This inconsistency caused some confusion for me when running CLI integration tests. We should determine which set of documentation is correct and update the other to match.

Additionally, note that the structure of the [response for `PUT /v2/pods/{podId}`](https://github.com/mesosphere/marathon/blob/386effaf401ea560ef8868dfacba7c39c49d6dba/docs/docs/rest-api/public/api/v2/pods.raml#L90-L92) is consistent with the other `PUT` endpoints in the RAML docs, but inconsistent with their current implementation. This will require new CLI code to be written to handle the response for pods. I heard from @jasongilanfarr that the change was intentional, but given the above inconsistency I thought it should be mentioned.

**Comment by aquamatthias** [comment]
@cruhland 

The raml docs for `PUT /v2/apps/{appId}` look like this:
```raml
    put:
      is: [ secured, deployable ]
      body:
        application/json:
          example: !include examples/app.json
          type: app.App
```
The body statement refers to the request body, not the response body.
The response body is defined in the trait `deployable` which looks like this:
```raml
deployable:
  responses:
    200:
      description:
        A deployment is started which has a unique deployment identifier.
        The related deployment can be fetched from the /v2/deployments endpoint.
        If the deployement is gone from the list of deployments, it means that it is finished.
        As long as the deployment runs, the effect of that change operation is visible only partially.
      body:
        application/json:
          example: !include v2/examples/deployments_result.json
```

Translates to: you send an app.App and you get a deployment as result.
This reflects the implementation in Marathon.

The same is true for `PUT /v2/groups` as well as `PUT /v2/groups/{groupId}`
Note on the path: 
We include the group specification twice:
```raml
/v2/groups: !include v2/groups.raml
/v2/groups/{group_id}: !include v2/groups.raml
```
to reflect the actions based on the root path and on a specific groupId.

You are right regarding the `/v2/pods` endpoint. 
It will not return a deployment, but the original specification.
The deployment Identifier is available via the HTTP Response Header: `Marathon-Deployment-Id`
Changed here: https://github.com/mesosphere/marathon/compare/feature/pods...mv/raml_spec?expand=1

**Comment by cruhland** [comment]
Thanks for clearing up my misunderstanding, @aquamatthias!
