### ISSUE TITLE
apps reload

### ISSUE THREAD

**Issue by vixns** [mesosphere/marathon#4504]
I have a haproxy app running in marathon (proxying a galera cluster). When cluster topology changes, the haproxy config file is updated, and I need to send a HUP signal to all haproxy tasks to made them load the new configuration.

I didn't found a proper way to send signals to running tasks, so I have custom haproxy images using inotify to monitor the config file and reload on change, works but not smart.

What about adding an API endpoint to send arbitrary signals to tasks ?

**Comment by aquamatthias** [comment]
@vixns Please send this request to Mesos - this is not possible in Marathon.
