### ISSUE TITLE
marathon show as `Inactive Frameworks` in mesos, but actually running 

### ISSUE THREAD

**Issue by eromoe** [mesosphere/marathon#4512]
Today, I found I can't not access marathon webui, but marathon service is running, after I restart it, get this situation.

show as `Inactive Frameworks`
![1](https://cloud.githubusercontent.com/assets/3938751/18937688/2d9296de-8625-11e6-84e9-68b14d819ccb.png)

Running (marathon-lb state is TASK_LOST)
![2](https://cloud.githubusercontent.com/assets/3938751/18937689/2e72ed60-8625-11e6-85b3-a2338108e7e7.png)

marathon-lb is running too.
![3](https://cloud.githubusercontent.com/assets/3938751/18937692/39013df4-8625-11e6-9d3d-279febfca283.png)

PS: I start marathon on 10.142.55.190 and 10.142.55.196  (but not config high availability)

**Comment by aquamatthias** [comment]
What is the version of Marathon + Mesos?
Prior versions of Marathon did not have a heartbeat to Mesos, which could lead to this behavior.
Actual versions have heartbeat enabled by default.

**Comment by chris530** [comment]
This happens to be often too  marathon 1.1.1  mesos 1.0.1.  Restarting marathon fixes it

**Comment by chinaares** [comment]
This happens to me  mesos 1.1.0 and marathon 1.3.6. Restarting marathon fixes it ,and reappear offen.

**Comment by chinaares** [comment]
nobody help??

**Comment by aquamatthias** [comment]
@chinaares If Marathon gets partitioned from Mesos, the framework is listed as inactive. 
We introduced a heartbeat monitor, that should abdicate in this case. 
Apparently that did not happen in your case. Can you share your log file?
