### ISSUE TITLE
Dynamically Assign a Unique ENV variable for the tasks running more than 1 instance

### ISSUE THREAD

**Issue by raghu999** [mesosphere/marathon#4513]
This is a important feature for container/app metrics , If we have more than one instance of app running in mesos/marathon except for `MESOS_CONTAINER_NAME` all Environment variables are same, This becomes very tough identifying Apps/Containers running more than 1 instance. The Container Name is too big which cannot be used , In our case the container name is too long to add it as prefix.    It would be helpful if Mesos or Marathon can add Dynamically a Unique Identifier as an `ENV` for Docker containers.

**Comment by jdef** [comment]
sounds like a dup of #1242 ; if so, please close this
