### ISSUE TITLE
Bug: Now Environment variables can't be included in the docker run command

### ISSUE THREAD

**Issue by arehmandev** [mesosphere/marathon#4520]
Hi guys, Perkbox DevOps dude here - New DCOS 1.8 release seems to have brought an issue (wasn't around during 1.8 Early release):

To recreate the bug:
Specify an environment variable in marathon JSON e.g. Key: test Value: sampletext - inside the container an environment variable is now present as $test=sampletext (this has been checked via sshing to the node, docker exec -it containerid bash).

Now in the docker run command run something like "echo $test > /root/test.txt && tail -f /dev/null"

Now if you ssh into the node running the container and do a docker exec -it containerid bash and cat /root/test.txt ... nothings present. 

It seems the commands are not executed after the environment variables are applied.. rather strange. Hope its not too complex for you guys.

Kind regards.

**Comment by aquamatthias** [comment]
@jrx can you retest this please?

**Comment by jrx** [comment]
@arehmandev @aquamatthias 

Hi!

If you deploy with the DC/OS Service UI. You now have to use uppercase environment variables. So your test above will work if you use `$TEST` instead of `$test`:

```
"echo $TEST > /root/test.txt && tail -f /dev/null"
```

You can check what variables are available inside of the container with command `env`.

Best,
Jan

**Comment by aquamatthias** [comment]
@arehmandev If this does not solve your problem, please reopen.
