### ISSUE TITLE
Marathon REST API for stopping a app

### ISSUE THREAD

**Issue by neddogg** [mesosphere/marathon#4528]
Hi Everyone,

I'm seeking for the **marathon REST API** that stops a running app. I went through the [REST API of marathon](https://mesosphere.github.io/marathon/docs/rest-api.html) but I was only able to found api to create and start, restart, get and delete an app. 
So I'm wondering, may be I went through the stop api without knowing. 

Any clue please?
Thanks.

**Comment by jeschkies** [comment]
You can kill all tasks and set the desired task count to zero. This suspends the app. Could you try that and give feedback. Thanks a ton.

**Comment by neddogg** [comment]
Hi @jeschkies, Thanks for the quick reply. Sorry I had something urgent to handle. Yes I was about to stop the running app by killing all it tasks. I didn't have set the desired task count to zero.
Thanks @jeschkies. 
You know your thing.

**Comment by jeschkies** [comment]
No Problem. I'm just getting into Marathon myself ;).
