### ISSUE TITLE
can't provide --tmpfs parameter for docker run via marathon json

### ISSUE THREAD

**Issue by butterflyinfly** [mesosphere/marathon#4529]
Hi guys!

I need to configure the application json in marathon. This application is running inside the docker container in privileged mode. I'd like to change the mode to unprivileged, that's why I need to provide the --tmpfs parameter for docker run, something like this:
 docker run -d --tmpfs /run:rw,noexec,nosuid,size=65536k my_image

When I try to do something like this:
 "container": {
    "type": "DOCKER",
    "volumes": [
        "/dev/mem: !Tmpfs {size: *** Mi}"
        ],
I see the error "There was a problem with your configuration
containerVolumes/0/mode: Specify a path
containerVolumes/0/containerPath: Specify a path"

Could you please help me how to configure it in Marathon? 

Thanks in advance.

**Comment by aspring** [comment]
I use the following to configure tmpfs:

```json
  ...
  "container": {
    "docker": {
      ...
      "parameters": [
        {"key": "tmpfs", "value": "/run"},
        {"key": "tmpfs", "value": "/tmp:exec,mode=777"}
      ]
      ...
    },
    "type": "DOCKER"
  }
}
```

**Comment by aquamatthias** [comment]
@nfnt can you confirm?

**Comment by nfnt** [comment]
Injecting the `tmpfs` command line option using `parameters` will work.

**Comment by butterflyinfly** [comment]
Thanks a lot!
