### ISSUE TITLE
Marathon REST API for retrieving the status of an app.

### ISSUE THREAD

**Issue by neddogg** [mesosphere/marathon#4536]
Hi Everyone,

I'm seeking for the marathon REST API that get status of an app (whether it is running, suspend, waiting or destroying). I went through the [REST API of marathon](https://mesosphere.github.io/marathon/docs/rest-api.html) but I couldn't see something like that. 
So I'm wondering, may be I went through such api without knowing.

Any clue please?
Thanks.

**Comment by aquamatthias** [comment]
Hey @neddogg I would suggest `GET /v2/apps/{appId}` See documentation here: https://mesosphere.github.io/marathon/docs/generated/api.html#v2_apps__app_id__get

Especially see all embed options to get the state you are interested in.
