### ISSUE TITLE
Marathon Web UI Bundle version

### ISSUE THREAD

**Issue by vervas** [mesosphere/marathon#4544]
Hey there

Is there supposed to be a fixed relationship between the marathon version and the marathon UI version?

marathon UI has v1.1.4 released and so does marathon, however it still points to an older marathon UI version (https://github.com/mesosphere/marathon/blob/v1.1.4/project/build.scala#L303)

Is this normal? shall we expect version 1.1.4 of marathon UI in another marathon version?

**Comment by aquamatthias** [comment]
Hey @vervas Marathon UI is a self contained project https://github.com/mesosphere/marathon-ui with its own version scheme.
