### ISSUE TITLE
Failing app blocks other apps when deploying an app group

### ISSUE THREAD

**Issue by frankscholten** [mesosphere/marathon#4545]
# The Problem

When deploying a group of Marathon apps and one of them fails, it gets restarted over and over again, blocking other apps so they are stuck in `STAGING`.

# The Context

I am creating a Marathon file which demonstrates how to deploy the Socks Shop, the cloud native reference application, with Marathon's IP-per-task functionality.

The `catalogue-db` fails because of a blocker in Mesos:  https://issues.apache.org/jira/browse/MESOS-6002. The services that were deployed before the catalogue-db service are `RUNNING` but the ones after are stuck in `STAGING`

Is the blocking of services a matter of configuration or is this a bug?

# How to reproduce

See the `deploy/marathon-cni` branch at https://github.com/microservices-demo/microservices-demo/tree/deploy/marathon-cni/deploy/mesos-marathon-ip-per-task and deploy the `marathon.json` file

**Comment by aquamatthias** [comment]
@frankscholten Marathon supports dependencies: https://mesosphere.github.io/marathon/docs/application-groups.html

The marathon.json you have defined says: 
`weave-demo/ui` depends on `weave-demo/service` depends on `weave-demo/db` 

All apps in `service` and transitively all apps in `ui` depend on `catalogue-db`.
The deployment will not proceed until this dependency is started completely.

If you want to deploy `service` and `ui` without `db`, you have to remove the dependency to `db` (albeit it sounds like a sensible dependency).
