### ISSUE TITLE
Rexray Issue:-Automatic unlimitted volume created in AWS Instance during deploying Mongo 3.1 on mesosspher cluster

### ISSUE THREAD

**Issue by pratapnanda** [mesosphere/marathon#4555]
Hello Team,
I am wondering to see the result when i used to deploy MongoDB in Mesosphere cluster in AWS.
I have manually created a EBS volume in AWS("ec2-awsdata") and the deploy Application with External Volumes(using docker) in mesosphere(below Yml file). Rex-ray didn't find my existing volume "ec2-awsdata" and tried to create multiple volume in AWS in a loop.Then I forcefully destroy the deployment and manually delete those volume.
I dont understand where is my mistake or has some bugs in rexray for MongoDB

Below are my configuration:
core@ip-10-0-2-222 ~ $ rexray version
Binary: /opt/mesosphere/packages/rexray--5969104330e3381cadedff3daf6e94000283bf32/bin/rexray
SemVer: 0.3.3-dcos+7
OsArch: Linux-x86_64
Branch: (detached
Commit: 1816ee3
Formed: Wed, 31 Aug 2016 04:25:48 UTC
core@ip-10-0-2-222 ~ $ rexray volume get
- name: ec2-awsdata
volumeid: vol-7da82fc9
availabilityzone: us-west-2a
status: available
volumetype: gp2
iops: 100
size: "1"
networkname: ""
attachments: []
- name: ""
volumeid: vol-110d5498
availabilityzone: us-west-2b
status: in-use
volumetype: standard
iops: 0
size: "8"
networkname: ""
attachments:
- volumeid: vol-110d5498
instanceid: i-5463b4c1
devicename: /dev/sda1
status: attached
core@ip-10-0-2-222 ~ $ docker version
Client:
Version: 1.10.3
API version: 1.22
Go version: go1.5.4
Git commit: 3cd164c
Built:
OS/Arch: linux/amd64

Server:
 Version:      1.10.3
 API version:  1.22
 Go version:   go1.5.4
 Git commit:   3cd164c
 Built:
 OS/Arch:      linux/amd64

core@ip-10-0-7-183 /etc/rexray $ cat config.yml
rexray:
loglevel: info
modules:
default-admin:
host: tcp://127.0.0.1:61003
storageDrivers:
- ec2
volume:
unmount:
ignoreusedcount: true
aws:
accessKey: xxxxx
secretKey: xxxxx
region: us-west-2

YML files
{
"id": "/test-mongo",
"instances": 1,
"cpus": 0.1,
"mem": 256.0,
"container": {
"type": "DOCKER",
"docker": {
"image": "mongo:3.1",
"network": "BRIDGE",
"portMappings": [
{
"containerPort": 27017,
"hostPort": 0,
"servicePort": 53376,
"protocol": "tcp"
}
],
"forcePullImage": true
},
"volumes": [
{
"containerPath": "/data/test-mongo-volume",
"external": {
"name": "ec2-awsdata",
"provider": "dvdi",
"options": { "dvdi/driver": "rexray" }
},
"mode": "RW"
},
{
"hostPath": "var-log",
"containerPath": "/var/log/mongodb",
"mode": "RW"
}
]
},
"upgradeStrategy": {
"minimumHealthCapacity": 0,
"maximumOverCapacity": 0
}
}

error logs:
core@ip-10-0-2-224 /var/log/rexray $ ls
rexray.log
core@ip-10-0-2-224 /var/log/rexray $ tail -f rexray.log
time="2016-10-06T08:19:07Z" level=info msg="waiting for volume creation to complete" driverName=ec2 moduleName=default-docker resp.VolumeId=0xc8204ecfc8 runAsync=false snapshotID= volumeID=
time="2016-10-06T08:19:07Z" level=info msg=vdm.Path driverName=docker moduleName=default-docker volumeID= volumeName=ec2-awsdata
time="2016-10-06T08:19:08Z" level=info msg=vdm.Path driverName=docker moduleName=default-docker volumeID= volumeName=ec2-awsdata
time="2016-10-06T08:19:09Z" level=info msg=vdm.Path driverName=docker moduleName=default-docker volumeID= volumeName=ec2-awsdata
time="2016-10-06T08:19:09Z" level=info msg=vdm.Path driverName=docker moduleName=default-docker volumeID= volumeName=ec2-awsdata
time="2016-10-06T08:19:10Z" level=info msg=vdm.Path driverName=docker moduleName=default-docker volumeID= volumeName=ec2-awsdata
time="2016-10-06T08:19:10Z" level=info msg=vdm.Path driverName=docker moduleName=default-docker volumeID= volumeName=bbf22b930d5a44635a3c2bfa699f9f2f99b7bc48e64f20524c8c981985fb0126
time="2016-10-06T08:19:10Z" level=info msg="getting path to volume" driverName=docker moduleName=default-docker volumeID= volumeName=bbf22b930d5a44635a3c2bfa699f9f2f99b7bc48e64f20524c8c981985fb0126
time="2016-10-06T08:19:10Z" level=info msg=sdm.GetVolume driverName=ec2 moduleName=default-docker volumeID= volumeName=bbf22b930d5a44635a3c2bfa699f9f2f99b7bc48e64f20524c8c981985fb0126
time="2016-10-06T08:19:10Z" level=info msg=sdm.GetVolumeAttach driverName=ec2 instanceID=i-5773714f moduleName=default-docker volumeID=vol-22b13696

When I deploying different application ,it works perfect .Below YML file works perfect as per expectation and it attached to AWS EBS sucessfully

{
"id": "/test-docker",
"instances": 1,
"cpus": 0.1,
"mem": 32,
"cmd": "/usr/bin/tail -f /dev/null",
"container": {
"type": "DOCKER",
"docker": {
"image": "alpine:3.1",
"network": "HOST",
"forcePullImage": true
},
"volumes": [
{
"containerPath": "/data/test-rexray-volume",
"external": {
"name": "ec2-awsdata",
"provider": "dvdi",
"options": { "dvdi/driver": "rexray" }
},
"mode": "RW"
},
{
"hostPath": "var-log",
"containerPath": "/var/log/myapp",
"mode": "RW"
}
]
},
"upgradeStrategy": {
"minimumHealthCapacity": 0,
"maximumOverCapacity": 0
}
}

I dont understand where is my mistake or rexray has some issue in MongoDB

**Comment by pratapnanda** [comment]
I am using Dc/OS version :1.8.4

**Comment by jdef** [comment]
see the first item listed here:
https://github.com/mesosphere/marathon/blob/master/docs/docs/external-volumes.md#potential-pitfalls

the docker image you're using (mongo:3.1) declares two VOLUME entries:
```
        "Volumes": {
            "/data/configdb": {},
            "/data/db": {}
        },
```

When using external volumes, for each of the above you need volume a spec
in your marathon app that declares a matching containerPath. Docker 10.3 is
particularly annoying because volume creation crash-loops if you don't do
this. Upgrading to docker 11.x fixes the volume creation crash-looping.

**Comment by pratapnanda** [comment]
Many Thanks for answer.it is now working after declare volume a spec in your marathon app
