### ISSUE TITLE
Marathon on DC/OS 1.8 GA running on CoreOS stable becomes unavailable

### ISSUE THREAD

**Issue by tobilg** [mesosphere/marathon#4561]
I encountered the problem on CoreOS latest stable that the Services UI/the Marathon UI becomes unavailable. When doing a `sudo journalctl -u dcos-marathon -n 200` I see a lot of the following errors:

```
Oct 04 08:29:50 dcos-master-1.mydomain.local java[11941]: java.io.IOException: Too many open files
Oct 04 08:29:50 dcos-master-1.mydomain.local java[11941]:         at sun.nio.ch.ServerSocketChannelImpl.accept0(Native Method)
Oct 04 08:29:50 dcos-master-1.mydomain.local java[11941]:         at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:422)
Oct 04 08:29:50 dcos-master-1.mydomain.local java[11941]:         at sun.nio.ch.ServerSocketChannelImpl.accept(ServerSocketChannelImpl.java:250)
Oct 04 08:29:50 dcos-master-1.mydomain.local java[11941]:         at org.eclipse.jetty.server.ServerConnector.accept(ServerConnector.java:382)
```

My `ulimits` seem to be fine:

```
admin@dcos-master-1 ~ $ cat /proc/sys/fs/file-max
606342
admin@dcos-master-1 ~ $ ulimit -u
23763
```

After restarting the `dcos-marathon` service everything works again.

**Comment by aquamatthias** [comment]
@cmaloney any ideas?

**Comment by tobilg** [comment]
Another user also faced this problem: https://dcos-community.slack.com/archives/general/p1475830446008908

**Comment by cmaloney** [comment]
Systemd sets number of open files limit per systemd service, we could up the file number limit for marathon (https://github.com/dcos/dcos/blob/master/packages/marathon/build#L17) like we do for Mesos (https://github.com/dcos/dcos/blob/master/packages/mesos/extra/dcos-mesos-master.service#L7) from the default to something higher. Need to know what is a reasonable thing, and why we just started running into this recently.

**Comment by aquamatthias** [comment]
@cmaloney no change regarding file handles I am aware of. Is there a change in CoreOS?

**Comment by tobilg** [comment]
Then a change in CoreOS would be my suspicion as well. Maybe https://groups.google.com/forum/m/#!topic/coreos-user/Trek9GQh87I contains a hint?

**Comment by cmaloney** [comment]
@tobilg what all was running in the cluster? Anything making lots of connections to marathon?

**Comment by tobilg** [comment]
@cmaloney Sorry for the delayed answer. This is just our test cluster, which only runs a few dozen tasks, and, to my knowledge, nothing that will create a lot of connections to Marathon. 

Would there be a way to track the connection counts? Other than doing `netstat` or similar?

**Comment by kamoljan** [comment]
Hi guys!

We are facing the same issue with DCOS 1.8.5 and 1.8.6.
How can we fix it?
It is realated to CoreOS or Marathon?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1718. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
