### ISSUE TITLE
TASK_LOST not work in marathon 1.3.2

### ISSUE THREAD

**Issue by HackToday** [mesosphere/marathon#4571]
from https://github.com/mesosphere/marathon/blob/master/changelog.md

it have 
> If Mesos agents get detached from the Mesos master, all tasks are assumed LOST. The reaction of Marathon in the past was to kill LOST tasks. Under certain configurations, however, those agents were able to rejoin the cluster, so LOST was not a terminal state.

In this version, Marathon will wait until a LOST task is assumed dead. This amount of time is configurable. The default timeout is 24 hours. LOST tasks after that timeout get killed by Marathon.

This change was so important that we back ported this functionality to prior versions of Marathon.

I tried following cases:

```
1. start mesos master and agent and run marathon 1.3.2 (build from source)
2. create an application with docker container nginx, and check container with `docker ps`
3.stop mesos-agent
4. wait some seconds, and task become TASK_LOST
5. check `docker ps`, docker container id is changed, so it means marathon create a new container
```

I also run with marathon 1.1.1, it is same behavior. I am not sure `the new  TASK_LOST behavior difference` here.

**Comment by aquamatthias** [comment]
Hey @HackToday 
Whenever a task is declared LOST, Marathon will start a replacement task.
If the LOST task becomes RUNNING again, the replacement task is killed.

**Comment by HackToday** [comment]
@aquamatthias  The issue is that 

I start mesos-agent(which means mesos-agent join the master again),  the  LOST task would still be replaced by the new task. So the container id is different.


Then what's the new feature `TASK_LOST behavior` about ?  It seems marathon 1.1.1 and 1.3.2 is same. Not have any difference.  But the release note say it is different. I am confused

**Comment by aquamatthias** [comment]
@HackToday 
The handling of lost tasks is not easy to understand - especially on the Mesos side:
1) If an agent is lost, all tasks are declared lost.
2) If the agent does not rejoin the cluster in the specified timeout (default: 75 seconds (agent ping)), all tasks are killed by Mesos. There is no way Marathon can help here. I guess you are running into this case.
3) If the agent rejoins the cluster after the specified timeout, but there was a Mesos Master failover, the agent can rejoin the cluster together with all tasks. Now Marathon is in charge of handling those tasks. If it is in the GC timeout it will update the tasks and kill replacement tasks. Otherwise it will kill the now running lost task.

This behaviour has been implemented in 1.3 and was backported to 1.1.2. and 0.15.4

**Comment by anywhy** [comment]
I have the same problem. Start a stateful app,  task LOST. 
When mesos-agent rejoin the cluster  in the specified timeout.  Container id  and volumes id is different, that means local volume data will lose. 
need help!

**Comment by HackToday** [comment]
@aquamatthias  One question for the 
```
If Mesos agents get detached from the Mesos master, all tasks are assumed LOST. The reaction of Marathon in the past was to kill LOST tasks. Under certain configurations, however, those agents were able to rejoin the cluster, so LOST was not a terminal state.

In this version, Marathon will wait until a LOST task is assumed dead. This amount of time is configurable. The default timeout is 24 hours. LOST tasks after that timeout get killed by Marathon.
```

It also said  75 seconds, I am not sure which time length is correct. 24 hours or  75 seconds ?  Thanks

**Comment by aquamatthias** [comment]
@HackToday We changed the default from 24h to 75seconds in Marathon 1.3

**Comment by HackToday** [comment]
@aquamatthias  Something maybe wrong here .https://github.com/mesosphere/marathon/blob/master/changelog.md


in Changes from 1.1.0 to 1.3.0 Section:

```
TASK_LOST behavior

In this version, Marathon will wait until a LOST task is assumed dead. This amount of time is configurable. The default timeout is **24 hours**. LOST tasks after that timeout get killed by Marathon.
```

So is it wrong here?

**Comment by aquamatthias** [comment]
@HackToday Yes. You can see the truth here: https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/core/task/jobs/TaskJobsConfig.scala#L12

I will fix the changelog - sorry for confusion.

**Comment by aquamatthias** [comment]
See: https://github.com/mesosphere/marathon/compare/mv/fix_changelog?expand=1

**Comment by HackToday** [comment]
Thanks  @aquamatthias
