### ISSUE TITLE
Is Marathon able to report the IP of a container running in a task when task status changed ?

### ISSUE THREAD

**Issue by wu8685** [mesosphere/marathon#4580]
Recently, I start a app with one task which runs a container. This container is just under BRIDGE mode, so it will get a IP from docker daemon like `172.17.0.2`. Is there a way to get this container IP from marathon when task status changed ?

Or is there a way in higher version? I am using v1.1.1

**Comment by aquamatthias** [comment]
@wu8685 the container ip is not accessible outside of the agent. You can define portMappings inside your container definition. So the container port will be mapped to the agent port, which is accessible in the cluster. You can get the agent address via the task list (get via /v2/groups, /v2/apps or /v2/tasks)
