### ISSUE TITLE
Tasks managed by marathon still stick around, don't show up in the UI, but are reaped after a marathon restart

### ISSUE THREAD

**Issue by solarkennedy** [mesosphere/marathon#4581]
This is similar in spirit to #4236, but it happens at Yelp with individual tasks too.

The symptom is that Marathon still keeps old tasks running, even when the app that managed them no longer exists.

These tasks are _still_ in the ZK state! In fact this is how I've begun to get an early warning on this condition. Here is the psuedo-code:

```
#!/bin/bash
set -eu
CLUSTER=$1

cd /tmp/

zkdump -l /marathon/state/  | sed "s/', '/\n/g" |  sed "s/\['/\n/g" | sed "s/'\]/\n/g"  > state
grep 'app:' state | cut -f 2 -d : | sort -u> apps
grep 'task:' state  | cut -f 2 -d : | sort > tasks

rogue_task_count=0

for task in `cat tasks`; do
  app_name=$(echo $task | cut -f 1-4 -d '.')
  if ! grep -q $app_name apps; then
    echo Found a rogue task with no app associated with it: $task
    let rogue_task_count=$rogue_task_count+1
  fi
done

if [[ $rogue_task_count -eq 0 ]]; then
  echo "OK: All tasks accounted for"
  exit 0
else
  echo "CRIT: $rogue_task_count tasks have no associated marathon app!"
  echo "This means that marathon has gotten out of sync with mesos."
  echo "Try restarting all the marathons to force things to reconcile!"
  exit 2
fi
```

This happens about once per week at Yelp. Restarting Marathon (causing a re-election) _does_ cause them to get cleaned up, but we don't like to restart Marathon, because of the risk of hitting #3783!

We were not monitoring for this condition before the upgrade to 1.3, so I'm not confident if this is a regression or not.

Our tooling does use a lot of `force=true` to abort or change existing deployments, do you know if this could trigger this?

**Comment by aquamatthias** [comment]
@solarkennedy 

1) Forcing application/group updates
overriding updates with `force=true` is a "normal" operation. It says: the specification I have is not correct, please override with this specification. 

2) Forcing deployments to abort 
This is a dangerous operation and should be used if you exactly know what you are doing.
Marathon will cancel all action it performs, leaves the state as is and pretend to be successful.
This is almost _NEVER_ what you want.

If you use 2) than it is absolutely possible to end up in the situation you describe.
Can you verify?

**Comment by solarkennedy** [comment]
@aquamatthias thanks for the clarification. Can you confirm that 1) is via PUT/POST on `/v2/apps/{appId}` and related app endpoints?

And 2) is done via the `DELETE /v2/deployments/{deploymentId}` endpoint?


If correct. I've found a place where we were doing 2 in paasta.
If you want I can make a PR to close out this issue and try to clarify the warning in `deployments.md` ?

**Comment by aquamatthias** [comment]
@solarkennedy a simple answer: all force operations (`/v2/apps`, `/v2/groups`, `/v2/tasks`) are safe. 

The only unsafe operation is `/v2/deployments/{id}?force=true` 
It is totally safe to use `/v2/deployments/{id}?force=false` (false is the default, so omitting has the same result). The first translates to "Stop Deployment", the second is "Rollback Deployment".

The documentation we have is not exhaustive on this topic - an clarification is welcome!

**Comment by solarkennedy** [comment]
This is still happening to us :(

Even though I've confirmed we are no longer using force to delete deployments, we still get these ghost tasks that go away after a restart or re-election.

@mattmb found log lines that look suspicious:
```
arathon[107648]: [2016-10-14 02:40:53,626] WARN App /question--answer.main.git85822726.configd1928660 exists in TaskTracker, but not App store. The app was likely terminated. Will now expunge. (mesosphere.marathon.SchedulerActions:ForkJoinPool-2-worker-111)
```

Maybe this is the part of our code causing this behavior?
https://github.com/Yelp/paasta/blob/bcbf6399b212b08a67fe44af087e8283fe2e5dbe/paasta_tools/bounce_lib.py#L194-L200

@aquamatthias I know you said that those operations should be *safe*, but I'll try removing force from some of that and seeing if these ghost tasks stop lingering.

**Comment by solarkennedy** [comment]
If found an exact example of this in action. This is what seems to be the things that make these "ghost" apps":
* App is exist, has 5 tasks
* We scale down to 0, force=>true
* We delete the app, force=>true (before marathon has a chance to kill the tasks)
* Tasks no longer show up in the marathon UI, but still hang around
* The "Deployment" stays around forever

I'm not sure what else we can even *do* except delete the deployment with force=>true? Rollback doesn't help.

However, after I restart marathon (new leader election) the extra tasks are reaped and the app can be deleted as normal (because it has 0 tasks). 

I'll stop commenting on a closed issue for now and re-open if anything else changes, but for now I'm going to re-enable our workaround cron jobs to delete orphaned tasks, deployments, and apps.

**Comment by aquamatthias** [comment]
@solarkennedy: thanks for the repro steps. I will reopen the issue.

**Comment by Rob-Johnson** [comment]
I've been looking through logs today, and found a few things:

For a given 'ghost' task, Marathon is continually trying to kill the orphan task, recognising that the task is missing.
```
INFO Killing 1 tasks for reason: Orphaned (ids: task [apollo.batch.gitd3c7e39d.configd2c06e44.df26515c-95ad-11e6-9e37-32b491cbe179] ...) (mesosphere.marathon.core.task.termination.impl.TaskKillServiceDelegate$:ForkJoinPool-2-worker-37)
```

At the same time, Marathon is doing reconciliations and receiving  status updates showing ``TASK_RUNNING``

```
```

**Comment by Rob-Johnson** [comment]
I've had a hunt through the logs a bit today:

Here is Marathon recognising that the task is orphaned, trying to kill it
```
INFO Killing 1 tasks for reason: Orphaned (ids: task [apollo.batch.gitd3c7e39d.configd2c06e44.df26515c-95ad-11e6-9e37-32b491cbe179] ...) (mesosphere.marathon.core.task.termination.impl.TaskKillServiceDelegate$:ForkJoinPool-2-worker-505)
```

At the same time, Marathon is doing reconciliations, and getting TASK_RUNNING back.
```
INFO Received status update for task apollo.batch.gitd3c7e39d.configd2c06e44.df26515c-95ad-11e6-9e37-32b491cbe179: TASK_RUNNING (Reconciliation: Latest task state) (mesosphere.marathon.MarathonScheduler$$EnhancerByGuice$$f7ffa73b:Thread-104068)
```

We also see a lot of messages that look like:

```
WARN Expunging task [ad--landscape.main.gite06dc8dd.configc8497a10.1ddb2d35-964d-11e6-88ce-f2d3644d99df] from state: max retries reached (mesosphere.marathon.core.task.termination.impl.TaskKillServiceActor:marathon-akka.actor.default-dispatcher-45)
```
Though I've not found one for the same ghost task yet.


When we restart marathon, the logs look like this:

```
Received status update for task apollo.batch.gitd3c7e39d.configd2c06e44.df26515c-95ad-11e6-9e37-32b491cbe179: TASK_FINISHED (Container exited with status 0) (mesosphere.marathon.MarathonScheduler$$EnhancerByGuice$$f7ffa73b:Thread-29)
Killing 2 tasks for reason: DeletingApp (ids: task [apollo.batch.gitd3c7e39d.configd2c06e44.df26515c-95ad-11e6-9e37-32b491cbe179],task [apollo.batch.gitd3c7e39d.configd2c06e44.df26515d-95ad-11e6-9e37-32b491cbe179] ...) (mesosphere.marathon.core.task.termination.impl.TaskKillServiceDelegate$:marathon-akka.actor.default-dispatcher-28)
Killing known task [apollo.batch.gitd3c7e39d.configd2c06e44.df26515c-95ad-11e6-9e37-32b491cbe179] (mesosphere.marathon.core.task.termination.impl.TaskKillServiceActor:marathon-akka.actor.default-dispatcher-28)
Sending event notification for task [apollo.batch.gitd3c7e39d.configd2c06e44.df26515c-95ad-11e6-9e37-32b491cbe179] of app [/apollo.batch.gitd3c7e39d.configd2c06e44]: TASK_FINISHED (mesosphere.marathon.core.task.update.impl.steps.PostToEventStreamStepImpl$$EnhancerByGuice$$72b3659c:marathon-akka.actor.default-dispatcher-49)
initiating a scale check for app [/apollo.batch.gitd3c7e39d.configd2c06e44] due to [task [apollo.batch.gitd3c7e39d.configd2c06e44.df26515c-95ad-11e6-9e37-32b491cbe179]] TASK_RUNNING  (mesosphere.marathon.core.task.update.impl.steps.ScaleAppUpdateStepImpl$$EnhancerByGuice$$58f7bce7:marathon-akka.actor.default-dispatcher-44)
```

So Marathon receives TASK_FINISHED update here?

**Comment by solarkennedy** [comment]
Due to the instability, in the short term I've roll back our production clusters to the last known stable version for us, which is 1.1.

In the medium term I'm going to try to roll forward with a 1.4 snapshot to see if it fixes this.

**Comment by aquamatthias** [comment]
Retested this with Marathon 1.4.0-RC3 with exactly the same steps you provided.
I could not reproduce this problem any longer.
The deployment finishes correctly.
All tasks get killed and are removed correctly.
