### ISSUE TITLE
Allow size specification for external volume with Docker

### ISSUE THREAD

**Issue by bosschaert** [mesosphere/marathon#4583]
When I create an external volume for use with my Docker container, it does not allow me to specify the size of this volume, which means that all the volumes are created with the default size. 

I.e. the following definition gives me as error: "/container/volumes(0)/external/size must be undefined for Docker containers"

If I remove the `size` constraint from the `external` section things work, but I would like to be able to specify the size.

```
{
  "id": "testhttpd",
  "cmd": null,
  "cpus": 1,
  "mem": 128,
  "disk": 0,
  "instances": 1,
  "container": {
    "docker": {
      "network": "BRIDGE",
      "image": "httpd",
      "portMappings": [
        {
          "containerPort": 80,
          "protocol": "tcp",
          "name": null
        }
      ]
    },
    "type": "DOCKER",
    "volumes": [
      {
        "containerPath": "/root/www",
        "external": {
          "name": "persistent",
          "size": 200,
          "provider": "dvdi",
          "options": {
            "dvdi/driver": "rexray"
          }
        },
        "mode": "RW"
      }
    ]
  },
  "env": {},
  "labels": {}
}
```

**Comment by aquamatthias** [comment]
@jdef can you look into this one?

**Comment by jdef** [comment]
Using the mesos DVDI implementation (provided by mesos), this gets translated to a `docker run ...--volume-driver=... --volume=...` command. there's no `docker run` option for specifying size. so this is more of a mesos-impl restriction vs. a marathon restriction (for example, the mesos dvdi implementation could add a step to create a volume given some size parameter). 

in this case, given the mesos impl, it seemed better to add a validation rule in marathon to avoid user confusion: "I specified a size, marathon let me, but it's not being used!"

Please file a ticket against the Mesos project if you're interested in seeing support for `size` with create-on-demand volumes when using the docker containerizer: https://issues.apache.org/jira/browse/MESOS/?

**Comment by bosschaert** [comment]
Thanks for explaining @jdef - I have created https://issues.apache.org/jira/browse/MESOS-6384

**Comment by jdef** [comment]
... and if you don't need to use the docker containerizer, I'm pretty sure
that Marathon now supports running docker images w/ the mesos
containerizer. In which case we **should** allow you to specify the size of
the external volume. If we don't, then that's a bug.
