### ISSUE TITLE
can't get stderr or stdout error from ui console

### ISSUE THREAD

**Issue by sinlang** [mesosphere/marathon#4586]
client stdout link in ui, not data return

**Comment by aquamatthias** [comment]
If Mesos Leader and Marathon are in the same DMZ than this should work out of the box. If there is network translation involved, you have to specify the URL to reach the leading Mesos master via `--mesos_leader_ui_url`

**Comment by mnp** [comment]
I'm seeing the same behavior on dcos-docker.

`--mesos_leader_ui_url` defaults to `/mesos` in dcos-marathon.service, but I've also tried `http://172.17.0.2:/5050` as an experiment.

Not also that while the Marathon UI can't pull the stdout and stderr logs, the DCOS ui can do it, by going to the service workspace and looking at the files or logs tabs.
