### ISSUE TITLE
start marathon output mush errors(centos7 mesos1.0.1, marathon1.3.1)

### ISSUE THREAD

**Issue by sinlang** [mesosphere/marathon#4587]
10月 13 08:43:10 mesos-master marathon[21504]: [2016-10-13 08:43:10,061] INFO 192.168.122.1 - - [13/Oct/2016:12:43:10 +0000] "GET //mesos-master:8080/v2/apps//group-1/curl-5?embed=app.taskStats&embed=app.readiness HTTP/1.1" 200 827 "http://mesos-master:8080/ui/" "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0"  (mesosphere.chaos.http.ChaosRequestLog$$EnhancerByGuice$$43931f4:qtp1157624710-39)
10月 13 08:43:11 mesos-master marathon[21504]: [2016-10-13 08:43:11,876] INFO mapping exception to status code (mesosphere.marathon.api.MarathonExceptionMapper$$EnhancerByGuice$$6b5f0460:qtp1157624710-36)
10月 13 08:43:11 mesos-master marathon[21504]: com.sun.jersey.api.NotFoundException: null for uri: http://192.168.122.198:8080/api/v1/config
10月 13 08:43:11 mesos-master marathon[21504]:         at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1543)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)
10月 13 08:43:11 mesos-master marathon[21504]:         at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
10月 13 08:43:11 mesos-master marathon[21504]:         at mesosphere.marathon.api.CacheDisablingFilter.doFilter(CacheDisablingFilter.scala:18)
10月 13 08:43:11 mesos-master marathon[21504]:         at mesosphere.marathon.api.CacheDisablingFilter$$EnhancerByGuice$$6e58fe19.CGLIB$doFilter$0(<generated>)
10月 13 08:43:11 mesos-master marathon[21504]:         at mesosphere.marathon.api.CacheDisablingFilter$$EnhancerByGuice$$6e58fe19$$FastClassByGuice$$432b8a41.invoke(<generated>)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
10月 13 08:43:11 mesos-master marathon[21504]:         at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:87)
10月 13 08:43:11 mesos-master marathon[21504]:         at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:28)
10月 13 08:43:11 mesos-master marathon[21504]:         at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:86)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52)
10月 13 08:43:11 mesos-master marathon[21504]:         at mesosphere.marathon.api.CacheDisablingFilter$$EnhancerByGuice$$6e58fe19.doFilter(<generated>)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
10月 13 08:43:11 mesos-master marathon[21504]:         at mesosphere.marathon.api.CORSFilter.doFilter(CORSFilter.scala:46)
10月 13 08:43:11 mesos-master marathon[21504]:         at mesosphere.marathon.api.CORSFilter$$EnhancerByGuice$$1792800b.CGLIB$doFilter$0(<generated>)
10月 13 08:43:11 mesos-master marathon[21504]:         at mesosphere.marathon.api.CORSFilter$$EnhancerByGuice$$1792800b$$FastClassByGuice$$2c6f3ce7.invoke(<generated>)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.google.inject.internal.cglib.proxy.$MethodProxy.invokeSuper(MethodProxy.java:228)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
10月 13 08:43:11 mesos-master marathon[21504]:         at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:87)
10月 13 08:43:11 mesos-master marathon[21504]:         at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:28)
10月 13 08:43:11 mesos-master marathon[21504]:         at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:86)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.google.inject.internal.InterceptorStackCallback$InterceptedMethodInvocation.proceed(InterceptorStackCallback.java:72)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.google.inject.internal.InterceptorStackCallback.intercept(InterceptorStackCallback.java:52)
10月 13 08:43:11 mesos-master marathon[21504]:         at mesosphere.marathon.api.CORSFilter$$EnhancerByGuice$$1792800b.doFilter(<generated>)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
10月 13 08:43:11 mesos-master marathon[21504]:         at mesosphere.marathon.api.LimitConcurrentRequestsFilter.pass(LimitConcurrentRequestsFilter.scala:31)
10月 13 08:43:11 mesos-master marathon[21504]:         at mesosphere.marathon.api.LimitConcurrentRequestsFilter$$anonfun$3$$anonfun$apply$2.apply(LimitConcurrentRequestsFilter.scala:15)
10月 13 08:43:11 mesos-master marathon[21504]:         at mesosphere.marathon.api.LimitConcurrentRequestsFilter$$anonfun$3$$anonfun$apply$2.apply(LimitConcurrentRequestsFilter.scala:15)
10月 13 08:43:11 mesos-master marathon[21504]:         at mesosphere.marathon.api.LimitConcurrentRequestsFilter.doFilter(LimitConcurrentRequestsFilter.scala:35)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
10月 13 08:43:11 mesos-master marathon[21504]:         at mesosphere.marathon.api.LeaderProxyFilter.doFilter(LeaderProxyFilter.scala:101)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
10月 13 08:43:11 mesos-master marathon[21504]:         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
10月 13 08:43:11 mesos-master marathon[21504]:         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
10月 13 08:43:11 mesos-master marathon[21504]:         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1158)
10月 13 08:43:11 mesos-master marathon[21504]:         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
10月 13 08:43:11 mesos-master marathon[21504]:         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
10月 13 08:43:11 mesos-master marathon[21504]:         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
10月 13 08:43:11 mesos-master marathon[21504]:         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
10月 13 08:43:11 mesos-master marathon[21504]:         at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240)
10月 13 08:43:11 mesos-master marathon[21504]:         at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
10月 13 08:43:11 mesos-master marathon[21504]:         at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:437)
10月 13 08:43:11 mesos-master marathon[21504]:         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
10月 13 08:43:11 mesos-master marathon[21504]:         at org.eclipse.jetty.server.Server.handle(Server.java:517)
10月 13 08:43:11 mesos-master marathon[21504]:         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
10月 13 08:43:11 mesos-master marathon[21504]:         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
10月 13 08:43:11 mesos-master marathon[21504]:         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
10月 13 08:43:11 mesos-master marathon[21504]:         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
10月 13 08:43:11 mesos-master marathon[21504]:         at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
10月 13 08:43:11 mesos-master marathon[21504]:         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.java:213)
10月 13 08:43:11 mesos-master marathon[21504]:         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
10月 13 08:43:11 mesos-master marathon[21504]:         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
10月 13 08:43:11 mesos-master marathon[21504]:         at org.eclipse.jetty.util.thread.QueuedThre

**Comment by aquamatthias** [comment]
@sinlang You throw a request to `/api/v1/config` in Marathon. This path is not existent, so Marathon will answer:
```json
{
    "message": "URI not found: /api/v1/config"
}
```

It will also write the exception to the log file (this is what you pasted).
I changed the log setting to omit the logging of an error.
See: https://phabricator.mesosphere.com/D73
