### ISSUE TITLE
Allow use of externally setup persistent storage

### ISSUE THREAD

**Issue by wrouesnel** [mesosphere/marathon#4590]
If I setup my Mesos cluster with a set of persistent volumes manually created into a suitable role, then what I would like to be able to do is launch tasks able to take advantage of that storage without having Marathon actually manage it.

The use-case for doing this is being able to safely lose Marathon instances and ZK data without having a painful recovery process for volumes out of Mesos (i.e. Mesos volumes persist locally per node, but Marathon does not store it's metadata the same way).

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1762. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
