### ISSUE TITLE
FetchUri isExtract does not support support query strings

### ISSUE THREAD

**Issue by geoffpatehutch** [mesosphere/marathon#4592]
Line 40 of marathon/src/main/scala/mesosphere/marathon/state/FetchUri.scala checks if a file can be extracted by seeing if it endswith a series of extensions. However, it does not handle the case where a file has a query string (eg SAS token) attached.

Maybe it could split the uri on the '?' delimiter, and then check the extension on the path without the query?

**Comment by jasongilanfarr** [comment]
The proper thing to do would be to parse out as a URL and then check the end of the path.

**Comment by allquantor** [comment]
Hi, I did a fix, here the [PR](https://github.com/mesosphere/marathon/pull/5214).

**Comment by jdef** [comment]
I really dislike that we automatically set the "extract" bit based on
filename. For a couple of reasons:
(1) the need to keep in sync the supported archive file types that Mesos
knows how to extract
(2) there's no way for someone to opt-out of extracting an archive. said
another way, what if I want to upload an archive and NOT have it extracted?

**Comment by allquantor** [comment]
@jdef 
extract could be a function `File => R` e.g if there is no extraction needs it would be `identity`.
We would still have to keep in sync the extraction functions that can be used.

**Comment by jdef** [comment]
My point is that Marathon is trying to outsmart the user here. I think it's
a mistake. The fetch API has an `extract` attribute that a user can set to
`true` if they want Mesos to extract the archive at task launch time. That
Marathon applies additional "magic" (to automatically set the extract bit)
is misguided.

**Comment by allquantor** [comment]
@jdef Now I got you. Sounds reasonable to me. When removing the "magic" it still is worth to catch the error that can occur during the extraction for the sake of user-friendly log messages.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1692. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
