### ISSUE TITLE
[Feature Request] Expose instance number as ENV to running tasks

### ISSUE THREAD

**Issue by aseppala** [mesosphere/marathon#4593]
It would be useful is running tasks would know their instance number. I.e. when application is scaled to 2, instances would know if they are instance number *1* or *2*.

This would help for applications that run in a pull mode to get control on which pool of tasks each instance pulls. Think sharded processing.

**Comment by janisz** [comment]
Similar to https://github.com/mesosphere/marathon/issues/1242

**Comment by jdef** [comment]
closing this as a duplicate of #1242

**Comment by isavcic** [comment]
Since this one is closed as being the duplicate, is #1242 in the pipeline to get implemented at all?
