### ISSUE TITLE
set all node ip or hostname to app env in a group

### ISSUE THREAD

**Issue by Fangfenghua** [mesosphere/marathon#4594]
eg:
{
  "id": "/product",
  "groups": [
    {
      "id": "/product/database",
      "apps": [
         { "id": "/product/mongo", ... },
         { "id": "/product/mysql", ... }
       ]
    }
  ]
}

if /product/mongo at node1 
/product/mysql at node2

cat set mysql: MARATHON_MONGO_NODE=node1 env

**Comment by janisz** [comment]
Can you elaborate?

**Comment by jasongilanfarr** [comment]
We don't really have a way of doing "Set an environment variable with the task information from another application." This seems out of scope of what marathon does and something that a service discovery mechanism (for example, marathon-lb) can do for you.
