### ISSUE TITLE
marathon restarts

### ISSUE THREAD

**Issue by eashweragero101** [mesosphere/marathon#4595]
need some help here marathon tends to restart every 2 seconds . can someone help me on this 

I have posted the error below 

Failed to load native Mesos library from /usr/lib/libmesos-0.25.0.so
java.lang.UnsatisfiedLinkError: Mesos JAR version 1.0.0 is not backwards compatible with Mesos native library version 0.25.0

**Comment by jasongilanfarr** [comment]
Marathon needs mesos-1.0 and your system has 0.25. Have you tried upgrading mesos?

**Comment by jasongilanfarr** [comment]
Any update on this @eashweragero101? If so, please reopen.

**Comment by eashweragero101** [comment]
How To Configure a Production-Ready Mesosphere Cluster on Ubuntu
14.04 | DigitalOcean
<https://www.digitalocean.com/community/tutorials/how-to-configure-a-production-ready-mesosphere-cluster-on-ubuntu-14-04>


i used this to set up i can share the cook book if u need

**Comment by eashweragero101** [comment]
thanks for your help
