### ISSUE TITLE
persistent volumes gets deleted on task_lost in marathon 1.3

### ISSUE THREAD

**Issue by sasounda** [mesosphere/marathon#4603]
I recently upgraded to Marathon 1.3 and found that local persistent volumes were getting deleted when tasks get lost. Specifically, on system reboots or when an agent goes down and comes back up, the volumes are not persisted. Though local persistent volumes are still in an experimental stage, upgrading to Marathon 1.3 has broken something which was working in previous Marathon versions.

**Comment by jasongilanfarr** [comment]
@timcharper Any ideas on this one?

**Comment by timcharper** [comment]
I'll look in to this right now and see if I can reproduce, although I have upgraded marathon to 1.3.4 from a patched version of 1.2.x and did not see this behavior.

**Comment by timcharper** [comment]
@sasounda did you happen to check if the volumes are really deleted? I.E. check disk to see if data is still there? Check mesos slave to see if volumes are still allocated?

**Comment by sasounda** [comment]
While I didn't confirm it through Mesos, I checked through my stateful app that it indeed lost historical data. I think I also did confirm through the Volumes tab in the Marathon UI.

**Comment by timcharper** [comment]
I've replicated this issue on my end with Marathon `1.3.5`. Marathon inappropriately allocates a new volume when a task goes into LOST state, and then, once that task times out, it destroys the old volume along with the task itself.

**Comment by timcharper** [comment]
@aquamatthias this bug does not exist in Marathon 1.4; removing milestone

**Comment by timcharper** [comment]
Bug replicated in `1.3.6` and `1.4.0-rc1`

**Comment by timcharper** [comment]
The root cause of this problem is the introduction of `UnreachableStrategy`

#4810 describes a problem in which this value is currently not configurable. However, the defaults are also too low to be sensible.

Further, #4137 describes a problem in which reserved resources associated with an instance are not being reused. We can fix this issue in particular by changing the UnreachableStrategy defaults, clearly documenting the values, and then specifying safer defaults.

**Comment by timcharper** [comment]
https://phabricator.mesosphere.com/D301 is targeted to resolve this specific aspect. @sasounda Please track #4137 for a solution which will prevent Marathon from unnecessarily allocating more volumes

**Comment by sasounda** [comment]
thanks @timcharper

**Comment by meichstedt** [comment]
Considered fixed for 1.4

In 1.3, one could use `--task_lost_expunge_gc` to define a value that prevents lost tasks to get expunged too soon (defaults to 75 seconds). However, that will also affect non-resident tasks.

@aquamatthias do you think we need to address something more for 1.3?
