### ISSUE TITLE
Marathon does not allow for multiple attributes with the same name

### ISSUE THREAD

**Issue by drcrallen** [mesosphere/marathon#4604]
If a mesos agent is started with the following attribute property: `some_attr:a;some_attr:b`, since `mesosphere.mesos.Constraints.ConstraintsChecker`:53 uses `lazy val attr = offer.getAttributesList.find(_.getName == field)` any constraint checker will only validate against `a`... anything that attempts to use `b`, will be ignored, even though the offer as printed by the log contains both attributes: `attributes { name: "some_attr" type: TEXT text { value: "a" } } attributes { name: "some_attr" type: TEXT text { value: "b" } }`

**Comment by jdef** [comment]
interesting find. what's the broader use case (why do you need multiple
attrs with the same name)?

**Comment by drcrallen** [comment]
I have resources in a cluster statically partitioned per role, and a pool of general resources up for grabs. I use an attribute called `pork` to describe what things are allowed to run there. So like, two instances of the same service or role, but with different SLA expectations might have different hardware configurations, thus have some underlying earmarking that is needed to ensure they run on hardware configurations that are expected.

I managed to get a node configured such that one node could run either type appropriately, and tried plugging it in to marathon. I found that only the first attribute in the list would be accepted, thus the second `pork` attribute was never seen.

**Comment by jdef** [comment]
related mesos issues:
* https://issues.apache.org/jira/browse/MESOS-1215
* https://issues.apache.org/jira/browse/MESOS-1216

sounds like the path forward is to do this:

1. implement support for multiple attributes w/ the same name in marathon
2. once mesos supports sets, deprecate the above and declare sets as the canonical approach for this
3. eventually remove support for multiple attributes w/ the same name (once mesos removes this, which will probably be a long time from now)

**Comment by allquantor** [comment]
I'm not sure if this 
https://github.com/mesosphere/marathon/pull/5201
should be linked here. Sorry if not.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1704. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
