### ISSUE TITLE
App status is "Waiting" even though all tasks are running

### ISSUE THREAD

**Issue by redshirtrob** [mesosphere/marathon#4605]
The Marathon UI reports that all tasks are running, but the status is "Waiting". Both Marathon and Mesos agree that all the tasks are running.

Inspecting the Marathon UI code I found the following, which makes it seem like this could happen if there was an overdue entry in the launch queue for this task.

```
function applyAppDelayStatus(app, queue) {
  var hasChanges = false;

  var queueEntry = queue.find(function (entry) {
    return entry.app != null && app.id === entry.app.id && entry.delay != null;
  });

  if (queueEntry) {
    let status = queueEntry.delay.overdue
      ? AppStatus.WAITING
      : AppStatus.DELAYED;

    if (app.status !== status) {
      hasChanges = true;
    }
    app.status = status;
  }

  return hasChanges;
}

```

I inspected the launch queue and there is an overdue entry for this task. The entry requests N+1 instances (where N is the number of hosts, and I constrained to hostname unique). So, this launch task can't be satisfied (This is likely a weird race condition from when I removed an agent from the cluster).

So, how do I remove this entry from the launch queue? From what I can tell, there isn't a REST API for this, and it looks like this queue isn't persisted to ZK or anywhere else. I would prefer not to relaunch the task unless I have to.

**Comment by IvanTing** [comment]
I have encountered same issue and below is my step to change the status back from Waiting to Running.
1. Scale up the Marathon App to N+1 instances. The UI will show N of N+1 instances.
2. Scale down the Marathon App to N instances. The UI should show Running status again.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2669. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
