### ISSUE TITLE
Add event notification for KILLING

### ISSUE THREAD

**Issue by marcust** [mesosphere/marathon#4609]
I didn't want to hijack #712, though this is related. I want to make sure that I deregister my services from my service-registry when the shutdown process _begins_. We currently use [allegro/marathon-consul](https://github.com/allegro/marathon-consul), which depends on the event queue to see changes in Marathon. The problem is that no external tool can see when a shutdown is actually started. 

As far as I can see the events REST endpoint currently does not have an event for the start of a killing operation:

```
event: health_status_changed_event
data: {"appId":"/mesos-task","taskId":"mesos-task.4dba23eb-96aa-11e6-bf6f-062c477e5e33","version":"2016-10-20T09:48:07.232Z","alive":true,"eventType":"health_status_changed_event","timestamp":"2016-10-20T09:48:52.628Z"}

event: status_update_event
data: {"slaveId":"3dd09faa-5cb6-4c7f-9c75-7ebbc5726de0-S1","taskId":"mesos-task.ef8d8f04-96a9-11e6-bf6f-062c477e5e33","taskStatus":"TASK_KILLED","message":"Container exited with status 137","appId":"/mesos-task","host":"executor-1.eu-central-1.dev-core.hubrick.net","ipAddresses":[{"ipAddress":"10.65.57.77","protocol":"IPv4"}],"ports":[31830,31831],"version":"2016-10-20T09:45:27.349Z","eventType":"status_update_event","timestamp":"2016-10-20T09:48:57.945Z"}
```

From the log I see that Marathon actually start the killing process the second it emits the status update event:

```
October 20th 2016, 11:48:52.628 Killing 1 tasks for reason: Upgrading (ids: task [mesos-task.ef8d8f04-96a9-11e6-bf6f-062c477e5e33] ...) (mesosphere.marathon.core.task.termination.impl.TaskKillServiceDelegate$:marathon-akka.actor.default-dispatcher-3)
```

Even with `--enable_features task_killing` (as mentioned in #4033) I don't see any additional events.  

Is it possible to emit a notification event when the killing begins?

**Comment by timoreimann** [comment]
Using Marathon 1.3.3 with the feature flag set, I see a `TASK_KILLED` event getting emitted. From my log file:

`[2016-12-16 21:10:42,235] INFO Sending event notification for task [app.0b50b3b4-c3d4-11e6-9e55-0242583832e9] of app [/app]: TASK_KILLED (mesosphere.marathon.core.task.update.impl.ste
ps.PostToEventStreamStepImpl$$EnhancerByGuice$$799e0ce:marathon-akka.actor.default-dispatcher-2)`

I double-checked by hooking up to the event stream with a small listener and also received the event.

**Comment by timoreimann** [comment]
I was looking for `TASK_KILLED` while of course this issue pertains to `TASK_KILLING`.

I do see a `status_update_event` event with the corresponding state when I enable the feature flag:

```
received event 'status_update_event'
{
  "slaveId": "7c7ed257-e22a-4966-879d-c640862b06a8-S0",
  "taskId": "app.e407cdd6-c5e8-11e6-9367-024283ca1baa",
  "taskStatus": "TASK_KILLING",
  "message": "",
  "appId": "/app",
  "host": "192.168.99.100",
  "ipAddresses": [
    {
      "ipAddress": "192.168.99.100",
      "protocol": "IPv4"
    }
  ],
  "ports": [
    31096
  ],
  "version": "2016-12-19T12:44:29.992Z",
  "eventType": "status_update_event",
  "timestamp": "2016-12-19T12:44:42.391Z"
}
```

**Comment by marcust** [comment]
I just found #3813, maybe that is already fixed. We will upgrade our infrastructure and test again.

**Comment by marcust** [comment]
Apparently, the TASK_KILLING event is actually emitted, at least in 1.1.0. Don't know why I didn't see that before.
