### ISSUE TITLE
Issues with documentation for Marathon API REST

### ISSUE THREAD

**Issue by lerayj** [mesosphere/marathon#4612]
The documentation is kind of broken:

[Marathon REST API](http://mesosphere.github.io/marathon/docs/rest-api.html)

Anchors aren't working.
From **DELETE /v2/apps/{appId}/tasks/{taskId}** part, all the presentation is destroyed.

![image](https://cloud.githubusercontent.com/assets/5832419/19602284/ff8de1a0-97ac-11e6-8d48-1705b9516f3d.png)

Looks like the Markdown interpreter didn't do his job!

Pretty annoying...

**Comment by jasongilanfarr** [comment]
I fixed this
