### ISSUE TITLE
marathon nproc and ulimit not respected

### ISSUE THREAD

**Issue by elppc** [mesosphere/marathon#4616]
Hi,
Is there any reason Marathon would loose sysctl conf (nproc, limits...) when switching to another user ?
I have tested with a cassandra instance. After having configured /etc/sysctl.d/sysctl.conf, /etc/security/limits.conf and /etc/security/limits.d/20-nproc.conf,I can't get the cassandra process be launched with good pararmeters when I precise "user": "cassandra" in marathon json.
If I launch a task as root in marathon with "cmd": "su cassandra -c '..." everything is fine, I can get the right limits.

I start the app through the UI

```
{
  "id": "/cassandra",
  "cmd": "su cassandra -c '/opt/cassandra-3.0.8/bin/cassandra -f'",
  "cpus": 0.5,
  "mem": 2200,
  "disk": 0,
  "instances": 1,
  "constraints": [
    [
      "hostname",
      "UNIQUE"
    ]
  ],
  "portDefinitions": [
    {
      "port": 10000,
      "protocol": "tcp",
      "labels": {}
    }
  ]
}
```

It works good, the limits are fine.

```
{
  "id": "/cassandra",
  "cmd": "/opt/cassandra-3.0.8/bin/cassandra -f",
  "cpus": 0.5,
  "mem": 2200,
  "disk": 0,
  "instances": 1,
  "constraints": [
    [
      "hostname",
      "UNIQUE"
    ]
  ],
  "portDefinitions": [
    {
      "port": 10000,
      "protocol": "tcp",
      "labels": {}
    }
  ],
  "user": "cassandra"
}
```

Limits aren't set, only defaults are applying. The /etc/security/limits.conf isn't taken into account...

**Comment by jdef** [comment]
It looks like we have some band-aid code in our startup script. Sounds like
a more general solution is needed:

[jdefelice@ec101 marathon]$ cat bin/marathon-framework |grep -A3 -B3 -e
ulimit
  local log_format='%2$s%5$s%6$s%n' # Class name, message, exception

  # if running as root and open file limit less than 8192 raise the limit
  [ $EUID -eq 0 -a $(ulimit -n) -lt 8192 ] && ulimit -n 8192

  export PATH=/usr/local/bin:"$PATH"
  local vm_opts=( -Djava.library.path=/usr/local/lib:/usr/lib:/usr/lib64

**Comment by jdef** [comment]
Oh wait, I think I misread. In this case your cassandra task is launching
on a slave. So .. did you change the ulimits conf on the slave? The
Marathon startup script only affects the Marathon process itself.

**Comment by elppc** [comment]
Yes. Limits are set on all slaves. It's OK with "su Cassandra..."

**Comment by jasongilanfarr** [comment]
I believe it depends on which user the cassandra tasks are running as. This sounds more like a mesos issue than a Marathon one. You could set the user to run the tasks as from marathon (probably root, but that'll depend on how you've configured mesos).
