### ISSUE TITLE
Question: Can marathon assign tasks to multiple roles

### ISSUE THREAD

**Issue by jessecollier** [mesosphere/marathon#4619]
Here's what we want to do:

A single marathon with:
- A pool of slaves to run any tasks on any "unreserved" agents
- A pool of slaves to run only specific tasks assigned by `acceptedResourceRoles` tasks

It appears that marathon can only listen for slaves running one type of reserved role. By default this is the slave_public in dcos. It also appears that you cannot specify multiple mesos roles. So my question is: Can I do what I've described above?

**Comment by jmlvanre** [comment]
Hi @jessecollier, 
What you are trying to do requires multiple roles support in Mesos. That is a feature on the Mesos roadmap, but not yet implemented. Once it is implemented then Marathon will be able to take advantage of it and accomplish your goal.
In the interim the solution is to have a marathon per role.

**Comment by jdef** [comment]
xref #2237

**Comment by jessecollier** [comment]
@jmlvanre Thanks for answering.

The parameter `acceptedResourceRoles` leads me to believe this is an option to support multiple roles for a framework. Perhaps the documentation can be updated to include this note until mesos adds support?

**Comment by sascala** [comment]
https://github.com/mesosphere/marathon/pull/4697

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2652. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
