### ISSUE TITLE
Ability to cancel Delay

### ISSUE THREAD

**Issue by leventov** [mesosphere/marathon#4631]
Probably I haven't found this in docs or API,

After many tasks are failed to start, the app is moved to "Delayed" state with some timeout. When I believe I've resolved the cause of failures, I may want to force Marathon to start making attempts of   starting tasks again, without waiting for the rest of the delay period. I don't want to use "Restart" for this because I don't want to kill existing running tasks.

**Comment by fengyehong** [comment]
There is an API for this:

`DELETE /v2/queue/{app_id}/delay`

https://mesosphere.github.io/marathon/docs/generated/api.html#v2_queue__app_id__delay_delete

And marathon UI provides a reset dealy button if app in "Delayed" state.

**Comment by leventov** [comment]
@fengyehong so "Reset" button actually cancels the delay? I thought it was resetting the delay to the initial value (e. g. 10 minutes).

**Comment by fengyehong** [comment]
>so "Reset" button actually cancels the delay?

Yes, try it. The API description is much more clear.

`This delay can be removed by calling this endpoint. The effect is, that the tasks of this application will be launched immediately.`

**Comment by jasongilanfarr** [comment]
Closing out.
