### ISSUE TITLE
why marathon account instance number into Version?

### ISSUE THREAD

**Issue by chengweiv5** [mesosphere/marathon#4635]
Lets say I have an app which first has 5 instances running, and then, I'd like to scale it to 3, ok, marathon generates a new **Version** with only **instances** changed.

As a end user, ok, it's fine, because I see there are 3 instances and all of them has **the same Version**, that's make me happy, no surprise.

However, if I scale my app from 1 to 8, ok, **it does surprise me**, it says there are **2 Versions** instances, 1 in version 1 and 7 in version 2.

See instances list as below.

![marathon-version](https://cloud.githubusercontent.com/assets/689798/19991410/ffecf23a-a26f-11e6-9d9a-41f5823b98ad.png)

That's definitely not a good idea I think, from an end user point of view.

It just says my application going to sane, inconsistent state.

I think we should kick **instance** out of Version.

**Comment by jasongilanfarr** [comment]
I generally agree with you here. I'll put it in the v3 suggestions. I don't know if we can reasonably do this in the V2 api.

**Comment by chengweiv5** [comment]
@jasongilanfarr great to know that, thanks

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1851. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
