### ISSUE TITLE
Adding servcie for MongoDB in Mesos using marathon framework 

### ISSUE THREAD

**Issue by priyankaghadage** [mesosphere/marathon#4636]
**Rancher Version**: v.1.1.4
**Docker Version**: 1.11
OS and where are the hosts located? AWS Ubuntu 14.04

 three EC2 Instances with three mesos-master containers and three mesos-slaves containers created via Rancher

**Rancher Environment Type**: (Cattle/Kubernetes/Swarm/Mesos) Mesos

**Steps to Reproduce**:
 Created 3 hosts using RancherUI envorment type Mesos.
 Install Marathon on Mesos through Rancher UI and able to access marathon dashboard <node-IP>:8080
 Adding mongoDB using marathon UI with below json

{
 "id": "/todo-with-mongo-marathon",
 "instances": 1,
 "container": {
 "type": "DOCKER",
 "docker": {
 "image": "mongo:3.1",
 "network": "BRIDGE",
 "portMappings": [
 {
 "containerPort": 27017,
 "hostPort": 0,
 "servicePort": 53376,
 "protocol": "tcp"
 }
 ]
 }
 },
 "healthChecks": [{
 "protocol": "HTTP",
 "portIndex": 0
 }],
 "ports": [0],
 "cpus": 0.25,
 "mem": 256.0
 }

**Results**:
 Mongo Service stays in deploying sate forever, mongo conatiner logs says - "**waiting for connections on port 27017"**
 and automatically restarts service after few minuites.
 **No stdout and stderr files** are generated for todo-with-mongo-marathon service.

**Expected**:
 MongoDB should get created and should be accessible through other services

**Comment by Poogles** [comment]
You're using a TCP health check on the MongoDB port which (AFAIK) going to work.  Change this for a TCP health check and it should get marked as healthy.

**Comment by jasongilanfarr** [comment]
@Poogles is correct. You should try either a TCP or MESOS_TCP health check. You can also use a command check and check with mongodb's cli. @priyankaghadage Please try that and reopen if you're still running into issues.
