### ISSUE TITLE
Add filter option for event types on GET /v2/events endpoint

### ISSUE THREAD

**Issue by tobilg** [mesosphere/marathon#4637]
As far as I understand, when using server-sent events via the `/v2/events` endpoint, currently all events are sent from Marathon.

I think there are many use cases where applications registering on that endpoint are actually only interested in some specific event types, not all events. Also, in large clusters with lots of tasks, I guess there will be a lot of traffic over the connection, putting load on Marathon as well as the listening application itself.

I could imagine that something like the `embed` query string parameter of the [GET /v2/apps](http://mesosphere.github.io/marathon/docs/generated/api.html#v2_apps_get) would make sense, e.g.

`GET /v2/events?event_types=deployment_info,deployment_success,deployment_failure`

**Comment by tobilg** [comment]
I just saw that there's also https://github.com/mesosphere/marathon/issues/654, which is still open.

**Comment by janisz** [comment]
Related to #3154

**Comment by tobilg** [comment]
Thanks @janisz for linking the issues, and to @jasongilanfarr as well for labeling it as well.

I think a good example for this kind of filtering is actually the Facebook Graph API with it's [field expansion](https://developers.facebook.com/docs/graph-api/using-graph-api/#fields) functionality. With that, it's even possible to filter/define the result on nested sub-fields (objects).

For example, a basic query can look like this: https://graph.facebook.com/?id=http://www.google.com

which will result in 

```javascript
{
   "og_object": {
      "id": "381702034999",
      "description": "Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for.",
      "title": "Google",
      "type": "website",
      "updated_time": "2016-11-17T09:31:49+0000"
   },
   "share": {
      "comment_count": 2,
      "share_count": 39738503
   },
   "id": "http://www.google.com"
}
```

If one uses the field expansion like https://graph.facebook.com/?fields=og_object{description},share{share_count}&id=http://www.google.com

one receives this instead:

```javascript
{
   "og_object": {
      "description": "Search the world's information, including webpages, images, videos and more. Google has many special features to help you find exactly what you're looking for.",
      "id": "381702034999"
   },
   "share": {
      "share_count": 39738503
   },
   "id": "http://www.google.com"
}
```

**Comment by janisz** [comment]
I was tying to implement it few months ago. But I hit a problem with keeping it backward compatible with old implementation. Subscriptions are stored in ZK so we need to add migration step to handle it correctly. 

Now it become critical for me because some events are > 8 MB.

**Comment by tobilg** [comment]
@janisz I think this affects a lot of applications, for example `marathon-lb` should be affected of this, too. 

I created a [Marathon->Slack integration](https://github.com/tobilg/marathon-slack), and that's where I personally stumbled upon it first. I do the filtering on the application side, which is kind of ineffective concerning cpu and network resources IMO.

There might be use cases where it would make sense to filter on field values as well, so as if an application wants to only listen to a specific applications events, such as [status updates](https://mesosphere.github.io/marathon/docs/event-bus.html#status-update) of a certain `appId`.

**Comment by janisz** [comment]
Prepared pull request for this #4671 so far only filtering on event type is working. We can think if we need something more.

**Comment by tobilg** [comment]
I created a Marathon event proxy in Node which can be used to filter by event type, until this is native Marathon functionality:

https://github.com/tobilg/marathon-event-proxy

**Comment by tobilg** [comment]
Thanks @janisz for the PR, and @jasongilanfarr for merging it! That was fast :-)

May I ask in which Marathon version this will be included? Also, would it make sense to open another issue regarding the filtering/reformatting of the event objects (re https://github.com/mesosphere/marathon/issues/4637#issuecomment-261198914)?

**Comment by jasongilanfarr** [comment]
The current plan is to release this in 1.4 which should have an RC in the next couple weeks.
