### ISSUE TITLE
Allow a user to put a single task into "maintenance mode"

### ISSUE THREAD

**Issue by andrewortman** [mesosphere/marathon#4638]
We've run into several problem scenarios:
1) We want to run a Java heap dump on a specific instance of a task - doing so will cause the health check to become unhealthy. We want marathon to keep the task running even though it is unhealthy.
2) A single instance of an application has a problem and an operator wants to keep it alive for a developer to review

Both of these scenarios could benefit from a feature that allows an operator to put a single task or group of tasks into "maintenance" - here's how I imagine it would function:

1) When a task is put into maintenance, a new task is spawned to replace it. 
2) New healthchecks from this task are ignored
3) The task stays alive until the task is either killed by a user or the task dies.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1765. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
