### ISSUE TITLE
JSON schema for Groups missing

### ISSUE THREAD

**Issue by tobilg** [mesosphere/marathon#4643]
A while ago, a JSON schema for Groups existed at the following URL: 

https://raw.githubusercontent.com/mesosphere/marathon/master/docs/docs/rest-api/public/api/v2/schema/Group.json

This is now gone. I was using it for the https://github.com/dcos-labs/marathon-validate tool to validate application/group JSON files.

The docs at https://mesosphere.github.io/marathon/docs/generated/api.html#v2_groups_post also reference this file as well. Is this because the new pod features? Or just a mistake?

**Comment by jasongilanfarr** [comment]
This is just a mistake, I'll restore it shortly.

**Comment by tobilg** [comment]
Thanks a lot @jasongilanfarr!

**Comment by jasongilanfarr** [comment]
Fixed in https://github.com/mesosphere/marathon/commit/8fda479929e4a01a1557da35f4c909161ef5da26
