### ISSUE TITLE
healtheck on custom ports in host mode doesn't work

### ISSUE THREAD

**Issue by vavrusa** [mesosphere/marathon#4645]
The [doc](https://mesosphere.github.io/marathon/docs/health-checks.html) says:

> For MESOS_HTTP, MESOS_HTTPS, MESOS_TCP, TCP, HTTP and HTTPS health checks, either port or portIndex may be used. If none is provided, portIndex is assumed. If port is provided, it takes precedence overriding any portIndex option.

However it fails to deploy when only `port` is specified, and not `portIndex`:

```
"Health check port indices must address an element of the ports array or container port mappings."
```

It works if I set `portIndex: 0` and then override it with `port: X`, but that's likely not expected behaviour.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1717. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
