### ISSUE TITLE
Fix font color for the Marathon version in the UI's "About" modal

### ISSUE THREAD

**Issue by tobilg** [mesosphere/marathon#4648]
The version info text in the "About" modal of the Marathon UI uses light grey on a light blue background, which is kind of hard to read/recognize, see the following screenshot:

![Screenshot](http://i.imgur.com/5IYxpwf.png)

**Comment by unterstein** [comment]
// cc @orlandohohmeier

**Comment by tobilg** [comment]
Shall I close this based on https://groups.google.com/forum/#!msg/marathon-framework/c6qUW8c0_3A/05dh0FjJBgAJ @orlandohohmeier?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2413. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
