### ISSUE TITLE
Have "Search All Applications" match on hostname or ports acquired

### ISSUE THREAD

**Issue by drcrallen** [mesosphere/marathon#4650]
If I search for a hostname in the searchbox on the marathon landing page, I expect to be able to find application instances which have that hostname.  In 1.3.0 it returns nothing.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2005. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
