### ISSUE TITLE
Drop offers unavailable in next configurable time

### ISSUE THREAD

**Issue by janisz** [mesosphere/marathon#4653]
Change scheduler to ignore offers with Unavailability that occurs in next configurable time interval (`--offer_minimum_availibility`). For example we probably want to decline offer of a node that will be down in next quarter because we will need to reschedule that task.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2454. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
