### ISSUE TITLE
When a instance error occurs, it is created endlessly

### ISSUE THREAD

**Issue by houht** [mesosphere/marathon#4654]
When I create a docker instance, Instance An error occurred and creation was unsuccessful, marathon send create instance  task does not stop.

Is there a solution?

**Comment by unterstein** [comment]
Hi @houht,

I think I do not understand your problem correctly. Can you please explain what you are doing, maybe add an example app definition? Can you also post your marathon version and your marathon log.

Thanks
Johannes

**Comment by jasongilanfarr** [comment]
@houht This is by design. Marathon is designed to keep a service running so it will continuously restart the app if it fails.

**Comment by houht** [comment]
@jasongilanfarr Thank you very much, I will use the following solution:

"docker": {
      "parameters":[{"key":"rm","value":"true"}]
}

**Comment by houht** [comment]
@unterstein Thanks. I mean that  docker app  will always be created when it has a error with itself
