### ISSUE TITLE
Marathon app scale down strategy

### ISSUE THREAD

**Issue by leventov** [mesosphere/marathon#4661]
It would be nice to specify scale down policy, e. g. terminate instances one by one, with specified delay.

This is useful for "smooth rebalancing" of instances between two different apps.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2332. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
