### ISSUE TITLE
Ability to kill a specific instance from Marathon UI

### ISSUE THREAD

**Issue by leventov** [mesosphere/marathon#4662]
This seems to be possible to do with REST API: http://mesosphere.github.io/marathon/docs/rest-api.html#post-v2-tasks-delete

But I didn't find a way to kill a specific instance from the UI. It would be nice to add this

**Comment by mikekuriger** [comment]
When you click the checkbox next to the instance,  a kill box appears.

**Comment by leventov** [comment]
@mikekuriger thank you. Maybe make this button visible, but inactive when no instances are selected?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1915. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
