### ISSUE TITLE
PUT /v2/groups/myApp endpoint can kill everything depending on the content of the JSON

### ISSUE THREAD

**Issue by pierrecdn** [mesosphere/marathon#4663]
Hi,
It seems that by PUT-ing to `/v2/groups/<mygroup>` with using an id="/" inside the JSON document, you can basically overwrite the whole '/', meaning no more apps except your own if you've got sufficient rights...
It seems to me that it is not very REST compliant, and btw a bit dangerous :smile: ...

**Comment by jasongilanfarr** [comment]
While not ideal, this is by design and it's documented as such. You can always use the app endpoint to add an application anywhere in the group hierarchy.
