### ISSUE TITLE
Upgrade to wix 0.6

### ISSUE THREAD

**Issue by jasongilanfarr** [mesosphere/marathon#4664]
The model has improved a decent amount: http://wix.github.io/accord/migration-guide.html

**Comment by jasongilanfarr** [comment]
Started the work here https://phabricator.mesosphere.com/D197, blocked on upstream https://github.com/wix/accord/issues/84

**Comment by jasongilanfarr** [comment]
Upstream has a workaround: add `"org.scala-lang" % "scala-compiler" % scalaVersion.value % "provided"` to `libraryDependencies` and my PR should work.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1779. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
