### ISSUE TITLE
Speculation: https health checks don't work with poor-ssl settings

### ISSUE THREAD

**Issue by jasongilanfarr** [mesosphere/marathon#4665]
I turned on "-Ywarn-dead-code" and the Marathon HTTPS health checks had an implicit for the SSLContext that was not actually used. I assume based on this that HTTPS checks where the configuration of the deployed application doesn't match the default SSL configuration of the JVM will always fail.

This is mostly speculation, but it feels unlikely that I'm incorrect.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1712. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
