### ISSUE TITLE
Docs: Add missing event types to Event Bus docs

### ISSUE THREAD

**Issue by tobilg** [mesosphere/marathon#4672]
From having a look at [src/main/scala/mesosphere/marathon/core/event/Events.scala](https://github.com/mesosphere/marathon/blob/v1.3.6/src/main/scala/mesosphere/marathon/core/event/Events.scala) it seems that there are actually more event types available than documented in the docs at [https://mesosphere.github.io/marathon/docs/event-bus.html](https://mesosphere.github.io/marathon/docs/event-bus.html), such as

* `api_post_event`
* `scheduler_registered_event`
* etc.

**Comment by zen-dog** [comment]
You're right and we would love to accept a PR improving the documentation.

**Comment by tobilg** [comment]
I'd do that, but tbh it's kind of unclear to me when/how these events are triggered and what exactly is their use. 

I guess one could prepare sample events from looking at the code and the protos, but I'm not sure if it makes sense to do it this way. I'd prefer something "official" regarding the documentation.

**Comment by tobilg** [comment]
What's the current status on this? Thanks!

**Comment by sascala** [comment]
It's near the top of my "to do" queue: https://jira.mesosphere.com/secure/RapidBoard.jspa?rapidView=254&view=planning&selectedIssue=DOCS-1672&quickFilter=926

**Comment by janisz** [comment]
How about adding Scaladoc comments to [Events.scala](https://github.com/mesosphere/marathon/blob/v1.3.6/src/main/scala/mesosphere/marathon/core/event/Events.scala) and link to gerated docs?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2474. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
