### ISSUE TITLE
Replace spray with Akka HTTP

### ISSUE THREAD

**Issue by jasongilanfarr** [mesosphere/marathon#4678]

**Comment by gosubpl** [comment]
Hi, I am an `akka-http` contributor. Would you be willing to accept a PR from me for this issue? If yes, please let me know what sort of CLA do I need to sign to start contributing to this repo.

**Comment by janisz** [comment]
AFAIK There is no CLA. Before you start you should know that spray is currently used in Healthchecks, HTTP Callbacks and tests. First two usages are gonna be deprecated (see  https://github.com/mesosphere/marathon/issues/4675 and https://github.com/mesosphere/marathon/issues/3334) and removed in the future. IMO the best place to start are tests and [Marathon facade](https://github.com/mesosphere/marathon/blob/master/src/test/scala/mesosphere/marathon/integration/facades/MarathonFacade.scala).

**Comment by jasongilanfarr** [comment]
This is in scope for 1.5, the general plan is to generate a client from the raml and hopefully the stub layer for the server too.

**Comment by gosubpl** [comment]
@jasongilanfarr Sorry for not doing anything with that - getting around to it now - I was too busy with akka stuff. I see that you have a lot of http client code - spray had a nice adapter for that, akka-http doesn't have this (yet) - so I wold like to ask what is the timeline for 1.5 to sensibly structure the work.
Also, can you please give me some pointers for "generate a client from the raml" - what is raml and where do I find it? Where is the "stub layer for the server" used?

**Comment by jasongilanfarr** [comment]
No worries at all, happy to have the help, it's a pretty big task.

I'm planning on sharing the 1.5 plans once we've signed off internally
which should be in the next week or two.

The core idea is that we use a raml specification for the API. Starting in
1.4, particularly for pods, we actually generate a lot of the data types
(and use them), so I was hoping we'd do a lot of the same for the actual
http calls, client and server. The client should be relatively easy to
generate, however, the server is a bit trickier as we need routes that
express abstract functionality and may need to be overridden (for event
stream for example).

I'd love to enable you to take this on, maybe we could chat next week about
it?

**Comment by jasongilanfarr** [comment]
Ps: raml is under docs/docs/....

**Comment by gosubpl** [comment]
Thanks for the pointer. I've sent you an e-mail, so we can chat about that.

**Comment by janisz** [comment]
Does this ticket include replacing chaos with akka http or only spray?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2592. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
