### ISSUE TITLE
Updating "user" in configuration in web gui has no effect

### ISSUE THREAD

**Issue by cribalik** [mesosphere/marathon#4679]
Steps to reproduce:

* In the gui, click on an application
* Go to the "configurations" tab
* Click edit
* change the "user" field from empty value to whatever value OR directly insert it into the JSON in JSON mode
* Click "Change and deploy configuration"
* The following PUT call sent to the server has payload "{}" :(

Updating other values, like "command", works. I only experience thus problem with "user".

**Comment by zen-dog** [comment]
Thanks for reporting it. @Poltergeist @Poltergeist

**Comment by cribalik** [comment]
Fixed in PR #788 in marathon-ui repo
