### ISSUE TITLE
Cannot resolve `scalac-scapegoat-plugin` when building

### ISSUE THREAD

**Issue by natemurthy** [mesosphere/marathon#4680]
As of d924c36 on `master` I cannot run the full Marathon test suite:

```
$ ./bin/run-tests.sh
...
[info] Resolving com.sksamuel.scapegoat#scalac-scapegoat-plugin_2.10;1.0.0 ...
[warn] 	module not found: com.sksamuel.scapegoat#scalac-scapegoat-plugin_2.10;1.0.0
[warn] ==== local: tried
[warn]   /root/.ivy2/local/com.sksamuel.scapegoat/scalac-scapegoat-plugin_2.10/1.0.0/ivys/ivy.xml
[warn] ==== public: tried
[warn]   https://repo1.maven.org/maven2/com/sksamuel/scapegoat/scalac-scapegoat-plugin_2.10/1.0.0/scalac-scapegoat-plugin_2.10-1.0.0.pom
[info] Resolving org.fusesource.jansi#jansi;1.4 ...
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: com.sksamuel.scapegoat#scalac-scapegoat-plugin_2.10;1.0.0: not found
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 
[warn] 	Note: Unresolved dependencies path:
[warn] 		com.sksamuel.scapegoat:scalac-scapegoat-plugin_2.10:1.0.0 ((com.sksamuel.scapegoat.sbt.ScapegoatSbtPlugin) ScapegoatSbtPlugin.scala#L105)
[warn] 		  +- default:marathon_2.10:0.1-SNAPSHOT
sbt.ResolveException: unresolved dependency: com.sksamuel.scapegoat#scalac-scapegoat-plugin_2.10;1.0.0: not found
```

It appears Maven has artifacts for Scala 2.11 artifact but not for 2.10 (see https://repo1.maven.org/maven2/com/sksamuel/scapegoat/). Anyone else seeing the same thing?

**Comment by zen-dog** [comment]
You need scala 2.11 (see https://github.com/mesosphere/marathon/blob/master/build.sbt#L68)

**Comment by aquamatthias** [comment]
@zen-dog according to this ticket this is the `$ ./bin/run-tests.sh` command.
If this is not working, our setup is wrong here.

**Comment by jasongilanfarr** [comment]
@natemurthy Our CI jobs pull down all artifacts from the main maven repositories configured in our build on every commit (there isn't really a local cache for us). Could you include the output of:

`sbt test:compile`?

**Comment by natemurthy** [comment]
I added more detail to my original comment. I re-synced my Marathon fork so that `master` is at `bcc86da`. Interestingly, this resolves perfectly fine when compiling all `main` and `test` source files, as do all the dependencies. However, I do get some compiler errors:
```
$ sbt test:compile
...
[info] downloading https://repo1.maven.org/maven2/com/sksamuel/scapegoat/scalac-scapegoat-plugin_2.11/1.2.1/scalac-scapegoat-plugin_2.11-1.2.1.jar ...
[info] 	[SUCCESSFUL ] com.sksamuel.scapegoat#scalac-scapegoat-plugin_2.11;1.2.1!scalac-scapegoat-plugin_2.11.jar (257ms)
...
[error] 50 errors found
[error] (marathon/test:compileIncremental) Compilation failed
[error] Total time: 62 s, completed Nov 23, 2016 11:38:38 AM
```

**Comment by natemurthy** [comment]
I've re-synced my Marathon fork so that master is at bcc86da. Getting more compilation errors:

```
$ sbt test:compile
...
[error] 83 errors found
[error] (marathon/test:compileIncremental) Compilation failed
[error] Total time: 108 s, completed Dec 7, 2016 6:50:40 AM
```
@jasongilanfarr ☝️

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2559. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
