### ISSUE TITLE
How to get the 'containerName' from an app？

### ISSUE THREAD

**Issue by JerryDog** [mesosphere/marathon#4681]
API “/v2/apps/{app_id}/tasks”  returned  without the “containerName”.

I have found the “containerName” in “src/main/scala/mesosphere/marathon/core/task/Task.scala”.

I modified like this:

“src/main/scala/mesosphere/marathon/core/task/Task.scala”
line 83++++ **def taskName: Option[String] = launched.map { _ => taskId.containerName }**

"src/main/scala/mesosphere/marathon/api/v2/json/Formats.scala"
line 123++++ **"containerName" -> task.taskName,**

Am I right?

**Comment by aquamatthias** [comment]
Hey @JerryDog The containerName you are referring to is the container inside a pod definition: https://github.com/mesosphere/marathon/blob/master/docs/docs/rest-api/public/api/v2/types/podContainer.raml#L58

Not sure what you expect as containerName - the docker image name?

I suggest you use the `/v2/apps?embed=tasks` to see the app definition together with all tasks.
Does this give you the information needed?

**Comment by JerryDog** [comment]
@aquamatthias Thanks! containerName is the docker container name,  /v2/apps?embed=tasks returned without the containerName.  I will find anther way to get the containerName.  Thank you.
