### ISSUE TITLE
Enable AppDeployIntegrationTest

### ISSUE THREAD

**Issue by meichstedt** [mesosphere/marathon#4682]
AppDeployIntegrationTest, GroupDeployIntegrationTest (and TaskLostIntegrationTest, somehow) are three integral integration tests in Marathon – they must not be disabled. No change can be merged if they don't run green. If the problem ist mostly that they don't run in parallel mode, try to extract single suites rather than having multiple test cases in one suite, or only tag single unstable test cases rather than the whole suite.

**Comment by aquamatthias** [comment]
Created #4719 to track TaskLostIntegrationTest separately.
