### ISSUE TITLE
ubuntu xenial deb built with arguably not-required dependencies?

### ISSUE THREAD

**Issue by flyinprogrammer** [mesosphere/marathon#4683]
# What's wrong?

```
# apt-cache depends marathon=1.3.6-1.0.540.ubuntu1604
marathon
  Depends: <java8-runtime-headless>
    default-jre-headless
    openjdk-8-jre-headless
    openjdk-9-jre-headless
  Depends: lsb-release
  Depends: unzip
```
`lsb-release` seems to only be required if you use: haproxy-marathon-bridge
https://github.com/mesosphere/marathon/blob/31426bd1f7b091b78748ea7fd83c497db3dfea9e/examples/haproxy-marathon-bridge#L81-L83

And I can't find any reference to requiring `uzip`.

If these dependencies aren't required to run marathon, could we get them removed as package requirements?

### Why do I care?

I'm packaging marathon into an ubuntu xenial container, and lsb-release requires python3 and that seems silly.

**Comment by flyinprogrammer** [comment]
Apparently there's a closed-source package post-install script: `/var/lib/dpkg/info/marathon.postinst`

```
#!/bin/sh
set -e

codename () {
  out $(lsb_release -cs)
}

out () { printf '%s\n' "$*" ;}

case "$1" in

  configure)
    if [ "$(codename)" = "wheezy" ]; then
      # Enable the SYSV links (only used on select systems).
      update-rc.d marathon defaults
    fi
    ;;

  configure|abort-upgrade|abort-remove|abort-deconfigure)
    ;;

  *)
    echo "postinst called with unknown argument \`$1'" >&2
    exit 1
    ;;
esac

#DEBHELPER#

exit 0
```

That relies on lsb-release, I might be possible to use`/etc/debian_version` or `/etc/os-release` instead.

**Comment by gkleiman** [comment]
@flyinprogrammer the scripts aren't "closed-source", they come from https://github.com/mesosphere/marathon-pkg

**Comment by flyinprogrammer** [comment]
@gkleiman dope - i'll go write some tests and submit a PR 👍

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2606. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
