### ISSUE TITLE
Remove `transitiveAppsById` and `transitivePodsById` from `Group`.

### ISSUE THREAD

**Issue by mpark** [mesosphere/marathon#4687]
https://phabricator.mesosphere.com/D75 introduced `transitiveAppsById` and `transitivePodsById` into the `Group` class. By and large, the `transitive*` properties are only used from the `RootGroup` class. There are a couple of cases in which these properties are still used via `Group` (e.g. `applicationDependencies`), but it should be possible to remove their use entirely.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2570. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
