### ISSUE TITLE
Update only the delta for `RootGroup.dependencyGraph` rather than recomputing.

### ISSUE THREAD

**Issue by mpark** [mesosphere/marathon#4688]
https://phabricator.mesosphere.com/D75 introduced `RootGroup` in which we compute the `dependencyGraph` of all run specs in Marathon upon request. We also recompute this graph every time anything changes in the group. Since all modifying operations have been moved into `RootGroup`, and many are intentionally narrow-purposed (e.g., `removeApp`), we can simply update the previous `dependencyGraph` rather than rebuilding the entire graph.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2185. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
