### ISSUE TITLE
API timeout should not use ZK timeout

### ISSUE THREAD

**Issue by janisz** [mesosphere/marathon#4689]
There is a chance to get 503 Timeout response from API while action is successfully performed. This occurs because API timeout is the same as ZK timeout (and other internal timeouts) and could be reached first.

Need to introduce API timeout (e.g. 30s) to prevent occurring too fast but also reduce ZK timeout (e.g. 5s) to be smaler then internal timeouts (e.g., `group_manager_request_timeout` [etc](https://github.com/mesosphere/marathon/search?utf8=%E2%9C%93&q=INTERNAL+TUNING+PARAMETER%3A+timeout&type=Code))

**Comment by jasongilanfarr** [comment]
i agree - the API timeout should probably be a bit longer. I do think, especially with the new persistence store that we should keep the Zk timeout on the higher side. If you deploy a group with a ton of apps (1000s, it requires a _ton_ of writes to zk)

**Comment by janisz** [comment]
I think this is related to bug that occurs when Marathon is under heavy load. When I try to deploy ne application I've got 503 Service Unavailable but application is deployed.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2258. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
