### ISSUE TITLE
scheduler_registered_event  &  app_terminated_event are not documented

### ISSUE THREAD

**Issue by ArunMj** [mesosphere/marathon#4690]
scheduler_registered_event
------------------------------------
{ 
 "master": "local"
 "frameworkId':"f01b925a-d31e-42f3-a628-ee805e72e5fa-0000", 
 "timestamp" : "2016-11-23T08:47:10.918Z",
 "eventType":"scheduler_registered_event"
}

 app_terminated_event,
--------------------------------
 { 
    "eventType" : "app_terminated_event", 
   "timestamp" : "2016-11-23T08:47:11.071Z",
   "appId" : "/testapp"
}

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2641. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
