### ISSUE TITLE
How can marathon v1.1.2 “/v2/apps/{app_id}/tasks” return container name?

### ISSUE THREAD

**Issue by JerryDog** [mesosphere/marathon#4692]
Marathon Rest API "/v2/apps/{app_id}/tasks" return without docker container name.

I saw formats in src/main/scala/mesosphere/marathon/api/v2/json/Formats.scala.

Like:

val base = Json.obj(
      "id" -> task.taskId,
      "slaveId" -> task.agentInfo.agentId,
      "host" -> task.agentInfo.host,
      "state" -> task.mesosStatus.fold(mesos.TaskState.TASK_STAGING)(_.getState)
    )

I want to add an op like this:

val base = Json.obj(
      "id" -> task.taskId,
      "containerName": task.containerName.
      "slaveId" -> task.agentInfo.agentId,
      "host" -> task.agentInfo.host,
      "state" -> task.mesosStatus.fold(mesos.TaskState.TASK_STAGING)(_.getState)
    )

Or tell me where the code path marathon  get mesos returned data and parsing them.

**Comment by jasongilanfarr** [comment]
If I am not mistaken, the container name is not available from the mesos Task message.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2095. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
