### ISSUE TITLE
Upgrading from marathon 0.15.7 to 1.1.3 leads to unusable marathon if app groups were improperly structured before upgrade

### ISSUE THREAD

**Issue by zen-dog** [mesosphere/marathon#4694]
Customer reported a problem where they upgraded their service marathon to mon-marathon:dcos-ee-1.1.3-1.0.2 form mon-marathon:v0.15.7. Error looks smth. like:
```
{"path":"/groups(5)/apps(2)/id","errors":["Identifier is not child of /mariadb-b. Hint: use relative paths."]}
```

This happens due to improper structure app groups e.g.:
```
Group( id = /, apps = ["/foo/bla"] )
```

The targeted solution is to provide a migration for 1.1.x, 1.3.x and 1.4.x versions that will correct the app groups.

**Comment by philippfranke** [comment]
Perhaps related to #4745

**Comment by zen-dog** [comment]
Fixed in https://github.com/mesosphere/marathon/pull/4711
