### ISSUE TITLE
Consider keeping a single `version` at the `RootGroup` level.

### ISSUE THREAD

**Issue by mpark** [mesosphere/marathon#4695]
Currently, each `Group` in Marathon has its own `version` property. However, it seems that we assign a `version` to the entire tree of `Group`s. When we modify a `Group` in a tree for example, we update the `version` of every `Group` in the tree, rather than just the `Group` being modified. Unless per-`Group` versioning is a feature we're considering in the future, it may be worth considering keeping the `version` only at the `RootGroup` level.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4469. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
