### ISSUE TITLE
Revisit management of `version`, from various levels of APIs.

### ISSUE THREAD

**Issue by mpark** [mesosphere/marathon#4696]
We use at least 2 levels of APIs in which we set the `version` of a tree of `Group`s.

1 level is at the `RootGroup` class, in functions such as `updateApp`, `removeApp`, and another is
at the `GroupManager` level, in functions such as `updateRoot`. Since `GroupManager` __uses__ the functions from `RootGroup` to modify the `RootGroup`, also performs other operations such as writing the group to the `GroupRepository`, it seems that the version passed to the `GroupManager` API has overrides the one passed to `RootGroup`.

For example:
```
GroupManager.updateRoot(_.removeApp(appId, _ => newApp, version1), version2, /* ... */);
```
I believe `version2` in this case ends up being used rather than `version1`.

A little more subtle issue is that `removeApp` has a default argument for `version`.
```
def removeApp(/* ... */, version: Timestamp = Timestamp.now())
```
So, on an invocation like:
```
GroupManager.updateRoot(_.removeApp(appId, _ => newApp), version2, /* ... */);
```
We don't even see that in fact there's a `Timestamp.now()` that is being overridden by `version2`.

This contrary to the `updateApp` API which requires a `version` explicitly.

This ticket is to capture the investigation of:
  (1) which level should be responsible for versioning?
  (2) should the bumping of `version` be implicit or explicit? keeping in mind testability, since if `version` is __always__ implicit, we can't provide the expected value to test against.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4711. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
