### ISSUE TITLE
Developing Marathon in a Virtual Machine refers to deprecated playa-mesos

### ISSUE THREAD

**Issue by artemharutyunyan** [mesosphere/marathon#4699]
[playa-mesos](https://github.com/mesosphere/playa-mesos) has been deprecated in favor of [DC/OS Vagrant](https://github.com/dcos/dcos-vagrant). Instructions for developing Marathon in a VM need to be updated accordingly.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2509. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
