### ISSUE TITLE
API /events : health_status_changed_event results always with alive: false

### ISSUE THREAD

**Issue by mleneveut** [mesosphere/marathon#4710]
Hello,

I'm using Marathon 1.3.5 and when I suscribe to /v2/events, the failed_health_check_event sends always avlive: false.

Every time I get this event, I check the /tasks result for the same appId, and sometimes it sends true.

Why does failed_health_check_event always sends alive false ?

09:40:20.144 : failed_health_check_event : {"appId":"/datafiller/a04/datafiller-planner","taskId":"datafiller_a04_datafiller-planner.85b4fea6-b

09:40:20.149 : health_status_changed_event : /datafiller/a04/datafiller-planner : alive=false
09:40:20.388 : datafiller_a04_datafiller-planner.85b4fea6-b53e-11e6-9ed1-005056b30b80, alive from /tasks : false

09:40:37.975 : health_status_changed_event : /datafiller/a04/datafiller-planner : alive=false
09:40:39.020 : datafiller_a04_datafiller-planner.85b4fea6-b53e-11e6-9ed1-005056b30b80, alive from /tasks : true

**Comment by aquamatthias** [comment]
Retested on this version with an application where the tasks switch constantly healthy/unhealthy.
Output for one task added.
You see the health_status_changed_event changes to alive=false and to alive=true at the end.
The failed_health_check_event is send for every failing health check. 
```
event: failed_health_check_event
data: {"appId":"/foo","taskId":"foo.8b7bb01c-b57c-11e6-aa24-3277c043fc0e","healthCheck":{"path":"/health","protocol":"HTTP","portIndex":0,"gracePeriodSeconds":20,"intervalSeconds":1,"timeoutSeconds":1,"maxConsecutiveFailures":10,"ignoreHttp1xx":false},"eventType":"failed_health_check_event","timestamp":"2016-11-28T15:09:05.602Z"}

event: health_status_changed_event
data: {"appId":"/foo","taskId":"foo.8b7bb01c-b57c-11e6-aa24-3277c043fc0e","version":"2016-11-28T15:08:39.844Z","alive":false,"eventType":"health_status_changed_event","timestamp":"2016-11-28T15:09:05.603Z"}

event: failed_health_check_event
data: {"appId":"/foo","taskId":"foo.8b7bb01c-b57c-11e6-aa24-3277c043fc0e","healthCheck":{"path":"/health","protocol":"HTTP","portIndex":0,"gracePeriodSeconds":20,"intervalSeconds":1,"timeoutSeconds":1,"maxConsecutiveFailures":10,"ignoreHttp1xx":false},"eventType":"failed_health_check_event","timestamp":"2016-11-28T15:09:06.625Z"}

event: failed_health_check_event
data: {"appId":"/foo","taskId":"foo.8b7bb01c-b57c-11e6-aa24-3277c043fc0e","healthCheck":{"path":"/health","protocol":"HTTP","portIndex":0,"gracePeriodSeconds":20,"intervalSeconds":1,"timeoutSeconds":1,"maxConsecutiveFailures":10,"ignoreHttp1xx":false},"eventType":"failed_health_check_event","timestamp":"2016-11-28T15:09:11.725Z"}

event: health_status_changed_event
data: {"appId":"/foo","taskId":"foo.8b7bb01c-b57c-11e6-aa24-3277c043fc0e","version":"2016-11-28T15:08:39.844Z","alive":true,"eventType":"health_status_changed_event","timestamp":"2016-11-28T15:09:12.741Z"}
```
