### ISSUE TITLE
Marathon timeout of KillTasks

### ISSUE THREAD

**Issue by jolexa** [mesosphere/marathon#4712]
Hello,

We have seen this message when trying to issue a DELETE to the `/v2/apps` endpoint.

```{"message":"Ask timed out on [Actor[akka://marathon/user/MarathonScheduler#2035436870]] after [5000 ms]. Sender[null] sent message of type \"mesosphere.marathon.MarathonSchedulerActor$KillTasks\"."}```

To my knowledge this timeout is not configurable. I'm also not able to find specific info in the logs during this occurrence. Any suggestions/comments?

**Comment by aquamatthias** [comment]
@jolexa 
Which version of Marathon do you run?
Under which circumstances do you see this?
Can you add a more complete log?

**Comment by jolexa** [comment]
Version: 1.3.0 (non-DCOS)

Issuing a DELETE to the /v2/apps endpoint. `curl -X DELETE localhost:8080/v2/apps/<app id>/tasks/<task id>`

```
Nov 28 07:10:13 ip-10-224-118-91 marathon[13884]: akka.pattern.AskTimeoutException: Ask timed out on [Actor[akka://marathon/user/MarathonScheduler#-882593002]] after [5000 ms]. Sender[null] sent message of type "mesosphere.marathon.MarathonSchedulerActor$KillTasks".
Nov 28 07:10:13 ip-10-224-118-91 marathon[13884]: #011at akka.pattern.PromiseActorRef$$anonfun$1.apply$mcV$sp(AskSupport.scala:604)
Nov 28 07:10:13 ip-10-224-118-91 marathon[13884]: #011at akka.actor.Scheduler$$anon$4.run(Scheduler.scala:126)
Nov 28 07:10:13 ip-10-224-118-91 marathon[13884]: #011at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:601)
Nov 28 07:10:13 ip-10-224-118-91 marathon[13884]: #011at scala.concurrent.BatchingExecutor$class.execute(BatchingExecutor.scala:109)
Nov 28 07:10:13 ip-10-224-118-91 marathon[13884]: #011at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:599)
Nov 28 07:10:13 ip-10-224-118-91 marathon[13884]: #011at akka.actor.LightArrayRevolverScheduler$TaskHolder.executeTask(LightArrayRevolverScheduler.scala:331)
Nov 28 07:10:13 ip-10-224-118-91 marathon[13884]: #011at akka.actor.LightArrayRevolverScheduler$$anon$4.executeBucket$1(LightArrayRevolverScheduler.scala:282)
Nov 28 07:10:13 ip-10-224-118-91 marathon[13884]: #011at akka.actor.LightArrayRevolverScheduler$$anon$4.nextTick(LightArrayRevolverScheduler.scala:286)
Nov 28 07:10:13 ip-10-224-118-91 marathon[13884]: #011at akka.actor.LightArrayRevolverScheduler$$anon$4.run(LightArrayRevolverScheduler.scala:238)
Nov 28 07:10:13 ip-10-224-118-91 marathon[13884]: #011at java.lang.Thread.run(Thread.java:745)
```

**Comment by pierrecdn** [comment]
@jolexa : did you get some input about this ? We may encounter the same issue on one cluster.

**Comment by janisz** [comment]
We experienced this issue as well. I suggest following steps:
* Upgrade to 1.3.10 it contains performance optimizations. 
* Increases metrics timeout. Metrics collected every 10s consumems 10% of CPU.
* Disable events callbacks or switch to filtered SSE. Parsing events consumes CPU and deployment events could be pretty big.
* Avoid multiple deployments at once, better to squash them in one request. 
* If you are using HTTP health checks please consider moving to command because they are done on host by Mesos. 
* Increases timeouts.

**Comment by pierrecdn** [comment]
@janisz Many thanks for your feedbacks. Do you remember how did you solve the issue at first ?Before doing these short-terms

**Comment by janisz** [comment]
We still experience this issues. Maybe not exactly on kill action. Marathon still returns 500 with timeout error but we reduced this number. We started with increasing timeouts, not all are documented some of them are marked as [`INTERNAL TUNING PARAMETER`](https://github.com/mesosphere/marathon/search?utf8=%E2%9C%93&q=%22INTERNAL+TUNING+PARAMETER%22&type=Code).

**Comment by pierrecdn** [comment]
OK, in our case it was a side effect of activating features through an isolator which apparently blocked the TASK_FINISHED or TASK_KILLED events from being received by the master, triggering contentions and so on.
Rollbacking those features just resolved the issue, even with hundredth of apps, some of them failing every time etc.
I guess that your environment is heavily loaded :)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2106. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
