### ISSUE TITLE
RepositoryTest LazyVersionCachingPersistence test is flaky

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#4716]
https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/public-test-marathon-phabricator/276/testReport/junit/mesosphere.marathon.storage.repository/RepositoryTest/LazyVersionCachingPersistence_versioned_should_list_and_retrieve_the_current_and_all_previous_versions_up_to_the_cap/

**Comment by jasongilanfarr** [comment]
I've been experimenting with this one and I made some changes to the locking that dropped the failure rate from 1/100 to about 1/1000, but its totally unclear to me why its failing at all. I thought it _might_ be WorkQueue/KeyedLock, but the other persistence stores use those too and they pass the same test case.

**Comment by jasongilanfarr** [comment]
What gets even stranger: If i change to the ZkStore as the backend, it seems to pass reliably. Yet, in memory store and all the other stores around in memory pass reliably too, so this just makes it even stranger.
