### ISSUE TITLE
MesosAppIntegrationTest pod tests are flaky

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#4717]
Both of these are flaky:

https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/public-test-marathon-phabricator/277/testReport/junit/mesosphere.marathon.integration/MesosAppIntegrationTest/deploy_a_simple_pod_with_health_checks/

https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/public-test-marathon-phabricator/275/testReport/junit/mesosphere.marathon.integration/MesosAppIntegrationTest/deploy_a_simple_pod/

**Comment by nfnt** [comment]
Review: https://phabricator.mesosphere.com/D242
