### ISSUE TITLE
GroupDeployIntegrationTest "Groups with dependent applications get upgraded in the correct order with maintained upgrade strategy" is flaky

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#4718]
https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/public-test-marathon-phabricator/280/testReport/junit/mesosphere.marathon.integration/GroupDeployIntegrationTest/Groups_with_dependent_applications_get_upgraded_in_the_correct_order_with_maintained_upgrade_strategy/

**Comment by timcharper** [comment]
Serial execution did not help.

**Comment by jeschkies** [comment]
Still Unstable.

**Comment by jeschkies** [comment]
Closed by https://github.com/mesosphere/marathon/commit/9cbfb974411a98d70f634ec6149f2bb2f2ca7894
