### ISSUE TITLE
MarathonStartupIntegrationTest is broken

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#4726]
Reported by @nfnt 

"Marathon should fail during start, if the HTTP port is already bound" aborts, probably due to a changed shut down behavior of Marathon, introduced with [D155](https://phabricator.mesosphere.com/D155).

**Comment by nfnt** [comment]
This also doesn't properly cleanup. There will be a process running, trying to connect to Zookeeper and polluting the test logs with these warnings like:
```
INFO [09:49:43 ClientCnxn] Opening socket connection to server 127.0.0.1/127.0.0.1:22346. Will not attempt to authenticate using SASL (unknown error)
WARN [09:49:43 ClientCnxn] Session 0x158af7d429f0004 for server 127.0.0.1/127.0.0.1:22346, unexpected error, closing socket connection and attempting reconnect
java.net.ConnectException: Connection refused
	at sun.nio.ch.SocketChannelImpl.checkConnect(Native Method)
	at sun.nio.ch.SocketChannelImpl.finishConnect(SocketChannelImpl.java:717)
	at org.apache.zookeeper.ClientCnxnSocketNIO.doTransport(ClientCnxnSocketNIO.java:356)
	at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1192)
```

**Comment by timcharper** [comment]
@nfnt we were having some issues with deadlocks when stopping the test zookeeper instance; we gutted the launcher code and switched over to curator-test solution and it seems to be working more reliably. #4870 I believe it's possible the log clutter you are seeing is a manifestation of that.

This test was marked as serial in cc82191e0fffff21b1d6b1c3380089513473affb and seems to be passing now.
