### ISSUE TITLE
Deprecate relaunchEscalationTimeoutSeconds

### ISSUE THREAD

**Issue by meichstedt** [mesosphere/marathon#4727]
When initially adding support for resident tasks, we came up with
```
"residency": {
    "relaunchEscalationTimeoutSeconds": 10,
    "taskLostBehavior": "WAIT_FOREVER"
}
```
although both properties have not really been supported so far.

`relaunchEscalationTimeoutSeconds` and `taskLostBehavior`are superseded by `timeUntilInactiveSeconds` and `timeUntilExpungeSeconds`. The latter two, in combination with a selector that decides which instances to kill when scaling down, will be used to describe this behavior more fine grained. Therefore, the `residency` property should be marked deprecated and replaced (by a `resident: boolean` flag?).

//cc @jeschkies

**Comment by jeschkies** [comment]
Should it be marked as deprecated in the RAML? Where is the option used?

**Comment by jeschkies** [comment]
Hm, so the first step for 1.4 would be to introduce `resident: Boolean` flag and mark `residency` in `app.raml` as deprecated. I don't know if one can do the later in RAML, @meichstedt? Then for 1.5 or 2.0 it will be removed.

**Comment by jdef** [comment]
we introduced a "deprecated" pragma in the network overhaul branch. i can backport. it's small

**Comment by jdef** [comment]
https://phabricator.mesosphere.com/D290

**Comment by jdef** [comment]
what's the auto-normalization path to go from the old API to the new API? for example, if Alice provides a `residency` object, how should we translate that to the new properties?

**Comment by jeschkies** [comment]
Hm, this deprecation seems to be much more evolved. We do not use `relaunchEscalationTimeoutSeconds` but we check if the `App.residency` property is defined.

**Comment by jeschkies** [comment]
Okay, I've just read that it should be replaced by a boolean :see_no_evil:.

**Comment by jeschkies** [comment]
I actually would opt to not remove the field.

**Comment by jeschkies** [comment]
Please also see discussion here https://phabricator.mesosphere.com/D298

**Comment by jeschkies** [comment]
I've abandoned the diff.

**Comment by jeschkies** [comment]
https://phabricator.mesosphere.com/D306

**Comment by jeschkies** [comment]
postpone for 1.5

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2615. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
