### ISSUE TITLE
Future time out while waiting for event

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#4728]
Reported by @jeschkies 

In different uni tests
```
A timeout occurred waiting for a future to complete. Queried 11 times, sleeping 15 milliseconds between each query.
```
https://jenkins.mesosphere.com/service/jenkins/job/marathon-unit-integration-tests-pushes/2525/

**Comment by nfnt** [comment]
That's a very broad description. A future timing out in a test case means that an expected action (e.g. a `deployment_success` event) didn't occur. The reason for that very much depends on what is expected in the test case, hence specific to the test case. I'd recommend to close this ticket and concentrate on specific test failures only.

**Comment by jeschkies** [comment]
Let's close this ticket.
