### ISSUE TITLE
Assets still accessible with `http_credentials` enabled

### ISSUE THREAD

**Issue by ssorallen** [mesosphere/marathon#473]
The API endpoints are secured when the `--http_credentials` flag is enabled when starting Marathon, but other endpoints like the one that serves assets is not.

As seen in the screenshot, I have not yet given the name + password but my browser was able to download assets. Only when the JavaScript attempted to request `/v2/apps` did my browser ask me for credentials:

![screenshot 2014-08-22 10 11 39](https://cloud.githubusercontent.com/assets/29612/4014335/97b12b8e-2a1f-11e4-86de-eab83f2224f2.png)

**Comment by ssorallen** [comment]
Old issue. Closing.

**Comment by ConnorDoyle** [comment]
@ssorallen has earned the necromancer GitHub achievement

**Comment by ssorallen** [comment]
👻👻👻👻👻👻👻👻

**Comment by ssorallen** [comment]
@ConnorDoyle Something I appreciated at Facebook: an issue reaper that commented on issues after 6 months of inactivity and closed them automatically after another 6 months of inactivity. An issue that hasn't been touched in 1 year+ probably isn't useful.
