### ISSUE TITLE
Fix unstable test mesosphere.marathon.integration.DockerAppIntegrationTest

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#4735]
`create a simple docker app using http health checks with HOST networking` is marked unstable – this is a major use case for most people deploying docker containers via Marathon, so it **must** be tested and pass.

**Comment by nfnt** [comment]
Didn't fail when testing locally for 10 runs. I'm assuming that other test-related fixes already resolved this test failure. Will run a few times on the CI to see if it fails there.

**Comment by nfnt** [comment]
Review: https://phabricator.mesosphere.com/D282
