### ISSUE TITLE
SSL is not enforced if SSL settings are provided

### ISSUE THREAD

**Issue by ssorallen** [mesosphere/marathon#474]
If SSL is enabled via the `ssl_keystore_path` flag, SSL works via https://localhost:8443 but it is not enforced; it's still possible to visit the UI via the unencrypted http://localhost:8080. If gone unnoticed, you might submit your username/password via plain text over HTTP.

* Is it possible to enable HTTP -> HTTPS redirection if SSL is enabled?

**Comment by ConnorDoyle** [comment]
Re-opening -- the merged PR didn't actually resolve this issue.
