### ISSUE TITLE
Reconsider usage of instance.isLaunched

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#4746]
Reported by @meichstedt 

A pod can have 1 running and 1 finished task and is still considered running. The semantic of isLaunched differs from the potential status a pod instance can have, therefore this definition must either be revised to be correct, or replaced by something that's unambiguous.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2547. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2547. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
