### ISSUE TITLE
Reconsider VersionInfo for pods

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#4747]
Reported by @meichstedt 

A PodDefinition currently never has a FullVersionInfo, only ever an OnlyVersion. There are some specifics regarding scale changes and config changes, which are probably needed for pods as well and likely lead to bugs if we don't fully implement this.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2611. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2611. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
