### ISSUE TITLE
InstanceUpdateOperation.ReservationTimeout should pass a timestamp

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#4748]
Reported by @meichstedt 

In order to generate events for status changes, instance.update uses a Timestamp.now when handling a InstanceUpdateOperation.ReservationTimeout. The ReservationTimeout should transport a timestamp so that this dependency in Instance can be removed (and the code can be tested easier/is more deterministic).

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2189. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2189. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
