### ISSUE TITLE
Remove implementation dependency on tasks

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#4749]
Reported by @meichstedt 

There are several places where the implementation assumes that an instance has at least one task. This is not assured anywhere, so it must either be assured, or the implementations need to be safe in case of an empty list.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2580. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2580. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
