### ISSUE TITLE
Check Expiration Improvement

### ISSUE THREAD

**Issue by jeschkies** [mesosphere/marathon#4753]
> Matthias Eichstedt
I'm ok with this for now; however, in a final version, I wouldn't handle/evaluate UnreachableInactive on task level, but only on instance level. My suggestion would be to do the following:
receive Mesos TaskStatus(Unreachable, unreachableTime = X)
instance.state = Unreachable, since = X
receive Mesos TaskStatus(Unreachable, unreachableTime = X)
if (instance.state == Unreachable && since.expired) instance.state = Unreachable, since = now
receive Mesos TaskStatus(Unreachable, unreachableTime = X)
if (instance.state == UnreachableInactive && since.expired) UpdateEffect.Expunge(instance) // instance.state = UnreachableExpired, since = now (we don't have this yet)
As I said, I'm ok with fixing that in a later diff.

**Comment by jeschkies** [comment]
@meichstedt is this still a fix?

**Comment by jeschkies** [comment]
As discussed the `InstanceState.since` field should be set on each update. This should be used by e.g. `ExpungeOverdueLostTasksActor` instead of accessing `Instance.tasksMap`. In the long run we want to make `Instance.tasksMap` private.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4471. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4471. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
