### ISSUE TITLE
Use Internal Mesos Task Status Case Class Model Instead of Protobuf Model

### ISSUE THREAD

**Issue by jeschkies** [mesosphere/marathon#4759]
There is a lot of logic in the test code to craft Mesos task status because the Protobuf builder is a little cumbersome. We should introduce an internal case class model. This makes dealing with the status easier and is robust against changes to the proto buf model similar to internal models of AppDefinition and PodDefinition converted from their raml counter parts.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4143. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4143. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
