### ISSUE TITLE
Fix unit test fixtures and helpers

### ISSUE THREAD

**Issue by meichstedt** [mesosphere/marathon#4761]
Lots of tests rely on potentially invalid data that is created with test helper classes that create instances, tasks and task updates in dubious states, e.g.

```
    def runningInstance(app: AppDefinition): Instance = {
      TestInstanceBuilder.newBuilder(app.id, version = app.version)
        .addTaskWithBuilder().taskRunning()
        .withNetworkInfo(hostName = Some(hostName), hostPorts = hostPorts)
        .build()
        .instance
    }
```

This was basically the same before pods, but with introducing pods, the possibility of an instance and it's tasks not reflecting real data has become much bigger (lots of test helpers that create task status updates turned out to create updates referencing inexistent taskIds which broke some tests).

There should be a meaningful set of RunSpec fixtures (AppDefinitions and PodDefinitions in various real-life configurations) and an implementation that leverages the **actual production code** to build and update the models, in pseudo code something like

```
val clock = ???
val instance = buildInstanceFrom(appDefinition)
  .updateToRunning(timestamp = clock.tick())
  .updateToFailed(timestamp = clock.tick())
```

Note: a WIP approach for this can be found [here](https://github.com/mesosphere/marathon/commit/4d7cf84e1ece857416887b590148481574610050).

**Comment by jeschkies** [comment]
If the Mesos status class is just a case class it would also be enough to call

```
val clock = ???
val instance = buildInstanceFrom(appDefinition)
  .update(MesosStatus(Condition.Running))
```

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1855. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1855. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
