### ISSUE TITLE
Resolve Futures Timeouts with High Rates of Task Activity

### ISSUE THREAD

**Issue by kensipe** [mesosphere/marathon#4762]
Marathon currently has a challenge when there are a high rate of app changes which can cause a timeout on the REST call due to the queue to write to ZK.   A single create app writes to ZK 4 or 5 times.   All task updates write to ZK.   To test this, try deploying 1 group of 5000 apps.  You will get a futures timeout, however the application  will eventually be consistent with what was requested (5000 apps in this case).

There are a couple of strategies to consider.  A simple one is to increase the actor system timeout however the CLI timeout is set to 5 secs.

A better strategy is to provide a token back for the request and allow for a query to the system with the token to test for it's fidelity and status.   Then a request is not considered fault tolerant until a deployment plan has been created and stored.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1797. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1797. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
