### ISSUE TITLE
Make legacy code accessing the first task of an instance less painful

### ISSUE THREAD

**Issue by meichstedt** [mesosphere/marathon#4764]
Lots of places in the code fetch the first task in an instances tasksMap – in all places that are implemented under the assumption that there is exactly one task. That is error prone and ugly, but it should at least be less cluttered than `instance.tasksMap.headOption.map(_._2)` or similar.

**Comment by unterstein** [comment]
Maybe we could add an implicit functionality to Instance via a TestTraits extracting this code to instance.getFirstTask or something similar? This could throw an exception if no Task is present, but usually you know that there is a Task if you call it. What do you think?

**Comment by unterstein** [comment]
https://phabricator.mesosphere.com/D336
