### ISSUE TITLE
ipAddress RAML spec is wrongly stating that some fields are required

### ISSUE THREAD

**Issue by Poltergeist** [mesosphere/marathon#4766]
The RAML spec of the ipAddress field is stating that `groups`, `discovery` and `labels` are required. But they are optional. 

https://github.com/mesosphere/marathon/blob/master/docs/docs/rest-api/public/api/v2/types/network.raml#L85

I created this issue after talking offline to @jdef

**Comment by jdef** [comment]
https://phabricator.mesosphere.com/D264
