### ISSUE TITLE
HealthCheck RAML spec is wrongly stating it should contain command

### ISSUE THREAD

**Issue by Poltergeist** [mesosphere/marathon#4767]
`CommandHealthCheck` is stating that command health checks should be:
```JSON
{
  "command": {
    "command": "exit 0;"
  }
}
```
Right format would be:
```JSON
{
  "command": {
    "value": "exit 0;"
  }
}
```
 
https://github.com/mesosphere/marathon/blob/master/docs/docs/rest-api/public/api/v2/types/healthCheck.raml#L25

**Comment by timcharper** [comment]
Resolved by https://phabricator.mesosphere.com/D266

**Comment by jasongilanfarr** [comment]
@Poltergeist CommandHealthCheck is incorrect - its the API used for pods. CommandCheck is used for apps and indeed has the wrong definition.
