### ISSUE TITLE
Download is insecure

### ISSUE THREAD

**Issue by benmccann** [mesosphere/marathon#477]
The README says marathon can be installed via:

    curl -O http://downloads.mesosphere.io/marathon/marathon-0.6.1/marathon-0.6.1.tgz
    tar xzf marathon-0.6.1.tgz

Installing software on your computer via http is insecure because in can be attacked via MITM to get you to run malicious code. It'd be really nice if downloads happened over https

**Comment by drexin** [comment]
@lloesche @lingmann Can we close this, or will https download be added?
