### ISSUE TITLE
Access a mesos-master behind a domain name (not an IP)

### ISSUE THREAD

**Issue by mmelcot** [mesosphere/marathon#4776]
Hi everybody,

Is it possible to run and access a mesos master on a machine that is placed behind a proxy?

I have successfully succeeded to deployed a MesosMaster/Marathon/MesosSalve on my local infrastructure.

The problem arises when I want to put the MesosSlave somewhere in the internet, so that MesosSlave and MesosMaster shall communicate through public IPs

My conf is the following:

                  Internet                                                                          My Infra

          .----------------------.                   .-----------------.    .-----------------.              .-------------------------------------------------.
          |    Mesos Slave VM    |                   |  Front Machine  |    |      Proxy      |              |                     Tool-VM                     |
          |    178.22.17.248     |                   |  39.224.147.94  |    |    10.2.0.57    |              |                   10.1.10.176                   |
          |----------------------|                   |  my.domain.com  |    |-----------------|              |           192.168.5.1 (docker bridge)           |
          |                      |                   |-----------------|    |                 |              |-------------------------------------------------|
          |                      |                   |                 |    |                 |              |                                                 |
          |       __________     |                   | __________      |    | __________      |              |                 .-----------------------------. |
          |      [_...__..5051.°]|                   |[_..5050.__...°] |<---|[_..5050.__...°] |<------------^|                 |   Mesos-Master Container    | |
          |                      |                   |                 |    |                 |              \ __________      | 192.168.5.4 (docker bridge) | |
          |                      |                   | __________      |    | __________      |              |[_..5050.__...°]^|-----------------------------| |
          |                      |                   |[_..2181.__...°] |<---|[_..2181.__...°] |<------------^|                 \ __________                  | |
          |                      |                   |                 |    |                 |              \ __________      |[_..5050.__...°]             | |
          |                      |                   |                 |    |                 |              |[_..2181.__...°]^| __________                  | |
          |                      |                   |                 |    |                 |              |                 \[_..2181.__...°]             | |
          |                      |                   |                 |    |                 |              |                 '-----------------------------' |
          '----------------------'                   '-----------------'    '-----------------'              '-------------------------------------------------'

However:

> My domain infra redirect everthing that arrives from outside on ports 5050 (for Mesos) and port 2181 (zookeeper) **ONLY** for requests that are addressed to the domain 'my.domain.com' (which is a virtualhost of  39.224.147.94). But not for the other requests (that are arriving on 39.224.147.94).

So I try to execute the service through CLI for the moment:

1. Execute **Mesos Master**(in Mesos Master Container)

<code>/usr/sbin/mesos-master --ip=192.168.5.4 --work_dir=~/Mesos/mesos-0.23.0/workdir/ --zk=zk://192.168.5.4:2181/mesos --quorum=1 --log_dir=/var/log/mesos --external_log_file=/dev/stdout</code>

2. Execute **Marathon** (in Mesos Master Container)

<code>/usr/bin/marathon --zk zk://192.168.5.4:2181/marathon --master zk://my.domain.com:2181/mesos</code>

3. Execute **Mesos Slave** (in Mesos Slave VM)

<code>/usr/sbin/mesos-slave --master=my.domain.com:5050 --work_dir=/var/lib/mesos/agent --port=8009  --containerizers=docker  --executor_registration_timeout=3mins --log_dir=/var/log/mesos</code>

The Mesos Master can see the Slave resources.
However, when I send a Job through Marathon, this job stay in a **waiting** state.

It seems that the slave is not able to communicate on the hostname of the Master, but only using it's public IP:

I have this in the Slave logs:

> New master detected at master@39.224.147.94:5050

The thing is that the incoming traffic on **39.224.147.94:5050** is blocked by my infra (only **my.domain.com:5050** is accepted).

So, is it possible to create a connection between Master and Slaves, using domain names, but not IPs?

**Comment by nfnt** [comment]
Closing this as it isn't an issue or feature request. Please use other channels as described in https://mesosphere.github.io/marathon/support.html for questions like this.
