### ISSUE TITLE
fix unstable LeaderIntegrationTest.all

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#4778]
https://phabricator.mesosphere.com/D270

**Comment by timcharper** [comment]
James mentioned he had fixed this already so assigning to him to so he can close it.

**Comment by jdef** [comment]
already fixed, see https://github.com/mesosphere/marathon/blob/00346f7e1b98afb06b4525a1c9904d389e16b925/src/test/scala/mesosphere/marathon/integration/LeaderIntegrationTest.scala#L128
