### ISSUE TITLE
Unit Test fail with Connection Loss Exception

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#4782]
created by @jeschkies 

When I run Marathon's unit tests in parallel I receive
The future returned an exception of type: 

```
org.apache.zookeeper.KeeperException$ConnectionLossException, with message: KeeperErrorCode = ConnectionLoss. (ZookeeperServer.scala:100)
```

for mesosphere.marathon.core.storage.store.impl.cache.LoadTimeCachingPersistenceStoreTest and mesosphere.marathon.core.storage.store.impl.cache.LazyCachingPersistenceStoreTest

**Comment by aquamatthias** [comment]
This test case is not marked as Unstable and run green in jenkins.
