### ISSUE TITLE
Marathon SSL and Basic Access Authentication

### ISSUE THREAD

**Issue by alexisCata** [mesosphere/marathon#4783]
I'm following this doc:
https://github.com/mesosphere/marathon/blob/master/docs/docs/ssl-basic-access-authentication.md
I have researched on Internet but I can't find nothing related...

In the step 3. Combine the key and certificate files into a PKCS12 format file...

> $ openssl pkcs12 -inkey marathon.key \
>                 -passin "env:MARATHON_KEY_PASSWORD" \
>                   -name marathon \
>                     -in trusted.pem \
>               -password "env:MARATHON_PKCS_PASSWORD" \
>          -chain -CAfile "trustedCA.crt" \
>            -export -out marathon.pkcs12

Where "trustedCA.crt" come from? There is no clear info in the docs
Is a cert of my server? 
I have created a cert in my server and added but when I executed the command and get the error:

> Error self signed certificate getting chain.

Any help will be appreciated

**Comment by janisz** [comment]
I generate self signed certs as follow without chain.

```bash
mkdir -p /etc/marathon/ssl
cd /etc/marathon/ssl
export MARATHON_SSL_KEYSTORE_PASSWORD=jks_pass
keytool -keystore marathon.jks -deststorepass $MARATHON_SSL_KEYSTORE_PASSWORD -alias marathon -genkey -keyalg RSA
cat << EOF > /etc/default/marathon
MARATHON_SSL_KEYSTORE_PATH=/etc/marathon/ssl/marathon.jks
MARATHON_SSL_KEYSTORE_PASSWORD=$MARATHON_SSL_KEYSTORE_PASSWORD
EOF
```

**Comment by unterstein** [comment]
Thanks @janisz for the answer.
I`ll interpret in your thumbs up, that this solves your issue? I would like to use your ticket as marker that we should improve the documentation on this topic.

**Comment by alexisfloresortega** [comment]
Sorry for the delay answering.
Just tries but is not working, can start marathon in that way

2016-12-16 11:32 GMT+01:00 Johannes Unterstein <notifications@github.com>:

**Comment by alexisfloresortega** [comment]
Sorry, my bad. Its working! :D

2016-12-20 16:41 GMT+01:00 Ale Xis <alexisfloresortega@gmail.com>:

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1916. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1916. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
