### ISSUE TITLE
Fix LeaderElection code

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#4786]
copy of https://mesosphere.atlassian.net/browse/MARATHON-1102
created by @meichstedt 

There are open issues wrt the stability of Marathon's leader election mechanism. The scope of this ticket is to either fix it or come up with a plan to improve this and add tests to prevent regressions.

**Comment by aquamatthias** [comment]
We fixed the known deadlock issues. We need clearer descriptions to act on.
