### ISSUE TITLE
Implement Suspended condition

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#4789]
In [Condition.scala](https://github.com/mesosphere/marathon/blob/46a86b3ea63231fa4da9bfc55664ca4d6be666c5/src/main/scala/mesosphere/marathon/core/condition/Condition.scala) we describe the task life cycle for resident tasks that aren't described by a Mesos TaskState, such as `Created` or `Reserved`.

A consequence of this is it becomes difficult to describe termination statuses for resident tasks. Currently, when a resident task dies, we transition the task condition directly from `Running` to `Reserved`. This can be confusing because `Reserved` comes before `Running` in the normal life-cycle, and leads us to need to [interpret Reserved as a terminal status in certain conditions](https://github.com/mesosphere/marathon/blob/46a86b3ea63231fa4da9bfc55664ca4d6be666c5/src/main/scala/mesosphere/marathon/core/task/termination/InstanceChangedPredicates.scala#L10).

Also, when reporting the task status via the API, it could be confusing to pause a task and see the task status go directly to `staging`. It would be better to show `suspended`.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4801. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4801. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
