### ISSUE TITLE
Jenkins loop test is not green consistently

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#4793]
https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-loop-tests/

**Comment by jeschkies** [comment]
Related to https://github.com/mesosphere/marathon/issues/4779

**Comment by jeschkies** [comment]
It seems we managed that. Didn't we?

**Comment by jeschkies** [comment]
Close in favor of more [detailed issues](https://github.com/mesosphere/marathon/issues?q=is%3Aopen+is%3Aissue+label%3Aflaky-test).
