### ISSUE TITLE
Marathon scales significantly past target

### ISSUE THREAD

**Issue by kensipe** [mesosphere/marathon#4801]
When scaling marathon v1.4.0-snap30 to 20,000 instances of an app... the task count went to 20,229.  It stayed there for a significant amount of time... several minutes.

It eventually went back down to 20,000.

<img width="1649" alt="screen shot 2016-12-07 at 12 08 52 pm" src="https://cloud.githubusercontent.com/assets/27497/20982232/44509d56-bc7d-11e6-8740-a33f18a7c56b.png">

<img width="1649" alt="screen shot 2016-12-07 at 12 08 45 pm" src="https://cloud.githubusercontent.com/assets/27497/20982236/48ff3d1c-bc7d-11e6-980c-9b925fb0a15a.png">

**Comment by aquamatthias** [comment]
@kensipe Please retest this with v.1.4.0-RC3

**Comment by kensipe** [comment]
@aquamatthias on it

**Comment by aquamatthias** [comment]
@kensipe The numbers have been improved significantly with RC4. Can you share the numbers? Can we close this ticket?

**Comment by kensipe** [comment]
@aquamatthias I haven't seen this for any of the RC releases.. I'll post the numbers for scale tests.
