### ISSUE TITLE
Resident Task: Unique host constraint not enforced when launching multiple reservations on the same offer

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#4803]
Looks like if two instances for an app are launched against an offer, both instances evaluate their uniqueness constraints from the deployment state before either task is assigned to an agent.

(IE - if I scale up 1 at a time, constraints are honored. If I scale up 2 at a time, constraints are violated)

http://screencast.com/t/CEGXHBo2

**Comment by aquamatthias** [comment]
Duplicates #3867
