### ISSUE TITLE
how to make fixed name for docker container launching from mesos marathon

### ISSUE THREAD

**Issue by geolig** [mesosphere/marathon#4805]
In my set up i am creating application using docker container via mesos marathon.

I have used docker container link while launching the application from marathon using below syntax 
{
	        "key": "link",
		"value": "mesos-4897cc0d-3a81-4be3-8384-8a254678ff59-S25.9978c761-5550-4dab-835f-530ac2bbf86a:tomcatlatestnew"
            }]

Added to that, in my environment i am using 2 slave servers , while launching the application using docker linking its getting launched in one slave and i am able to access the application. But while failover the instance from one slave to other slave container name getting changed hence docker linking is not working and i am unable to access application. Please do let me know how can i make fixed container name even though fail over happened from one slave to other salve.

**Comment by janisz** [comment]
So far it's not possible. See mailing list threads:  [mesos](https://lists.apache.org/thread.html/4e929d0522f3ec07361b13da34aaf11d09c0624cf0335546a081023b@1455147266@%3Cuser.mesos.apache.org%3E), [marathon](https://groups.google.com/d/msg/marathon-framework/QdA485Afma8/o3S8JC7DBgAJ)

**Comment by geolig** [comment]
Hi Janisz,

  Thanks for your reply. I have a one more question, currently i am using docker IPAM for getting IP address for my application but that IP get changed if the application is fail over from one slave to another. How do i can make fixed IP for the application so that when application fail over time it will retain the same IP, please help

**Comment by janisz** [comment]
I have never used Mesos/Marathon in that way but it looks like you need [IP per container](https://mesos.apache.org/documentation/latest/networking-for-mesos-managed-containers/) and SDN that is capable of assigining IP form IP pool for every application. Take a look at [Project Romana](http://romana.io/how/romana_details/#ip-address-management) or [Calico](https://www.projectcalico.org/). Take a look at [CNI](https://mesos.apache.org/documentation/latest/cni/) becouse this is what is used undernnet to integrate with Mesos containers.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4197. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4197. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
