### ISSUE TITLE
Unkillable Apps in Marathon 1.1

### ISSUE THREAD

**Issue by Rob-Johnson** [mesosphere/marathon#4806]
I've come into a situation wherein I can't delete a Marathon app, or kill the tasks associated with it.

Symptoms:

- The app does *not* appear in the list of apps returned by  the ``/v2/apps`` endpoint.
- The app *does* appear when you go to the ``/v2/apps/{appId}`` endpoint.
- The app *is* in the list of apps in the zookeeper ``/marathon/state`` node.
- If I kill the only task associated with the app, then Marathon restarts it.
- If I try to delete the app via the API, Marathon returns a 404 with the Message ``"App '/apollo.canary.git54607924.configa53dc013' does not exist"``

This was picked up by our monitoring scripts that look for 'lost' tasks, as described in #4581 (which we've since updated to check for this failure mode).

I know that this is 1.1, and I can't be confident whether it affects newer versions, but I'm kind of reluctant to upgrade to a newer version:

- #4581 has meant that we've rolled back 1.3 deployments to 1.1 everywhere at Yelp.
- #4769 means it's scary to move forward to 1.4

I've also tried a rolling restart of the Marathon cluster to see if it helps, but to no avail.

I've got lots of logs for analysis, so let me know which specific parts can help.

Thanks!

**Comment by janisz** [comment]
@Rob-Johnson any description? I suspect it could be related to https://github.com/mesosphere/marathon/issues/4236 but it's hard to tell with title only issue.

**Comment by Rob-Johnson** [comment]
sorry @janisz I hit the enter key too quickly and github submitted the issue. I've updated the description now.

**Comment by meichstedt** [comment]
@Rob-Johnson sounds to me like this might be related with the issue that has been fixed with #4711 
@zen-dog can you have a look please?

**Comment by zen-dog** [comment]
Hm, I vaguely remember that broken apps from #4711 would appear in `/v2/apps/{appId}`. @Rob-Johnson do you see smth. like `"errors":["Identifier is not child of /app Hint: use relative paths."` in the log?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1829. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1829. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
