### ISSUE TITLE
Unable to update UnreachableStrategy

### ISSUE THREAD

**Issue by meichstedt** [mesosphere/marathon#4810]
`UnreachableStrategy` can currently not be updated since it's not covered in `AppUpdate` – probably applies for pods as well?

**Comment by jeschkies** [comment]
Is https://phabricator.mesosphere.com/D304 fixing this?

**Comment by timcharper** [comment]
Yes, @jeschkies

**Comment by timcharper** [comment]
Closing as D304 has landed
