### ISSUE TITLE
Convert docker image/tag names into content hash pull requests on job creation

### ISSUE THREAD

**Issue by wrouesnel** [mesosphere/marathon#4814]
Docker's content hash system allows the regular docker pull command to pull down a cryptographically guaranteed container image, but is frequently unused because people don't like looking at the hashes compared to the image and tag names.

It would be extremely helpful if Marathon could be launched with a parameter which forced all docker image names to be converted to their sha256 hash request format (storing the original image name somewhere in the job description would be useful, but not required).

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2366. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2366. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
