### ISSUE TITLE
Question: security code review

### ISSUE THREAD

**Issue by chiel1980** [mesosphere/marathon#4815]
Hi,

Did you guys ever did a security review on your code by an external party?
And if yes, are you willing to share these results or can we find it back in some specifc commits?
We are scheduling a code review by an external security company and if you want, we would like to share these results with you/the community as feedback to improve the product (if anything has been found) :)

Michiel

**Comment by aquamatthias** [comment]
Hey @chiel1980 - we internally reviewed Marathon with respect to security. 
One result was a MesosCon talk from @gkleiman. You can find the slide deck here: http://schd.ws/hosted_files/mesosconeu2016/a0/Securing%20a%20Marathon%20Installation.pdf

If you can share the results of your investigations - that would be great!

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4369. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4369. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
