### ISSUE TITLE
Document UnreachableStrategy

### ISSUE THREAD

**Issue by meichstedt** [mesosphere/marathon#4816]
After introduction of UnreachableStrategy and changing the defaults, we need to update the docs, also re Local Persistent Volumes (`persisttent_volumes.md`) and the related dcos-docs to explain how this works, which effects it has, and what meaningful values for a normal stateless service as well as a stateful service are.

See https://phabricator.mesosphere.com/D301

**Comment by sascala** [comment]
@meichstedt This sounds like an augmentation of this? https://github.com/mesosphere/marathon/pull/4642 (not merged yet because it's not yet released).

**Comment by meichstedt** [comment]
@sascala yes, it is. The default `UnreachableStrategy` for apps with persistent volumes will create new instances/new volumes and delete existing volumes (if possible), after an instance has been unreachable for longer than 7 days and is expunged by Marathon. It should be mentioned that data might be deleted at that point, either in the docs for the task handling/UnreachableStrategy, or in [persistent_volumes.md](https://github.com/mesosphere/marathon/blob/master/docs/docs/persistent-volumes.md), which aggregates arbitrary information around persistent volume usage and pitfalls.

I think either @jeschkies or I should add something.

**Comment by sascala** [comment]
@meichstedt Does this address the issue? https://github.com/mesosphere/marathon/pull/4642/commits/233f538da056e0ddcd6cb1b3fd5574ea5c40584b

**Comment by meichstedt** [comment]
@sascala Just saw this now – yes, it does!
