### ISSUE TITLE
Support `isUpgrade` for `killSelection`

### ISSUE THREAD

**Issue by jeschkies** [mesosphere/marathon#4818]
https://phabricator.mesosphere.com/D307

**Comment by jeschkies** [comment]
@jdef and @meichstedt why is `isUpgrade` required at all? As far as I see we are fine if the app version changes.

**Comment by jdef** [comment]
if we don't check for `killSelection` in `isUpgrade` then changes aren't persisted, right? fields should either be involved with an "upgrade" or "scale change" -- there is no other option at this point
