### ISSUE TITLE
Marathon should not re-use task ids for resident tasks

### ISSUE THREAD

**Issue by unterstein** [mesosphere/marathon#4819]
In the current implementation, marathon re-uses task ids in case of resident tasks, see:

<img width="1618" alt="screenshot 2016-12-09 13 47 28" src="https://cloud.githubusercontent.com/assets/904420/21049588/11f2b4d0-be16-11e6-89ef-1922e9fbc06a.png">

To avoid problems when running different tasks with the same task id, this behavior should be changed.

**Comment by timcharper** [comment]
I noticed this as well. When I was writing my ceph-on-mesos framework I was directed to this and shied away: https://issues.apache.org/jira/browse/MESOS-2198

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1772. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1772. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
