### ISSUE TITLE
Endpoint name must be marked as optional

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#4821]
The network endpoint name must be marked as optional, as it is only required if network type is `container` and the `default_network_name` wasn't specified. The current spec results in DC/OS UI validation issues.

**Comment by jdef** [comment]
endpoint names are not optional. it's the port name.

network names are optional. because host networks don't have names.

endpoints != networks

**Comment by jdef** [comment]
closing because there is not really a bug here
