### ISSUE TITLE
Using groupRepository as 1 source of truth about running apps

### ISSUE THREAD

**Issue by zen-dog** [mesosphere/marathon#4824]
We shouldn't depend on appRepository outside of group manager to access apps like we do here:

`mesosphere/marathon/MarathonSchedulerActor.scala:399`
```
  def scaleRunSpec(): Future[Unit] = {
    appRepository.ids().concat(podRepository.ids()).runWith(Sink.set).andThen {
      case Success(ids) => for (id <- ids) schedulerActor ! ScaleRunSpec(id)
      case Failure(t) => log.warn("Failed to get task names", t)
    }.map(_ => ())
  }
```
There should be 1 "source of truth" for currently running apps instead of 2.

**Comment by jasongilanfarr** [comment]
Not sure how this was never noticed, but `ids()` returns _all_ ids even if they are not current. So this is actually the real issue in #4791. Root is the only actual source of truth.

**Comment by jasongilanfarr** [comment]
E.g. If there is no current version, the id will still be listed!

**Comment by unterstein** [comment]
https://phabricator.mesosphere.com/D317

**Comment by zen-dog** [comment]
Same as https://phabricator.mesosphere.com/D310 so take one ;)

**Comment by jasongilanfarr** [comment]
I have more to contribute on this one.
