### ISSUE TITLE
pods quickstart guide error

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#4825]
as per https://github.com/mesosphere/marathon/pull/4602#pullrequestreview-12368516

step 1 says `-d@<mypod>.json http://<ip>:<port>/v2/pods <<EOF` ... and `<mypod>.json` should really be `/dev/stdin`

**Comment by sascala** [comment]
https://github.com/mesosphere/marathon/pull/4832

**Comment by sascala** [comment]
And, thank you for catching this, @jdef
