### ISSUE TITLE
Send Promise in PromiseActor instead of creating Actor 

### ISSUE THREAD

**Issue by jeschkies** [mesosphere/marathon#4827]
In many places we have to know if an action was completed by an actor. Currently we use the ask pattern from Akka or `mesosphere.Util.PromiseActor`.

The `PromiseActor` sends a message and completes the promise when it receives a reply. It would be easier to send the promise and not create a temporary actor.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4487. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4487. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
