### ISSUE TITLE
Marathon startup script does not handle spaces in arguments properly

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#4829]
https://github.com/mesosphere/marathon/commit/3b10a8e2e0e782880475b8ad46172e99f1a37a28#commitcomment-20153340

https://github.com/mesosphere/marathon/commit/3b10a8e2e0e782880475b8ad46172e99f1a37a28#commitcomment-20153342

**Comment by aquamatthias** [comment]
https://phabricator.mesosphere.com/D324
