### ISSUE TITLE
healthCheckResults does not contain information about Mesos healthcheck

### ISSUE THREAD

**Issue by janisz** [mesosphere/marathon#4834]
After switching to Mesos healthcecks, `healthCheckResults` is not correctly populated. Default executor marks Tasks as killed with optional field health as false and this is the only way to distinguish healtcheck kills from "normal" scheduler kills. 

Related: #4168 #3334

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4339. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4339. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
