### ISSUE TITLE
Pods totally ignored in dependency graph stuff

### ISSUE THREAD

**Issue by jasongilanfarr** [mesosphere/marathon#4843]
Not sure we should actually fix this - I'd rather have us fix dependencies itself, eg:

If an app has a dependency, we "wait" for the dependency to be healthy before we deploy. This could be as simple as "isAppHealthy? If not, wait for an event for that app - event stream to future..."

**Comment by jdef** [comment]
We promised that if a group had dependencies that they'd be transitive w/
respect to the pod. If that's not the case then we need to update the docs.

I don't see us making major changes to dependencies for 1.4 at this point

**Comment by jasongilanfarr** [comment]
We indeed made that promise and never actually did it. I think we should update the docs in favor of fixing dependencies later (1.5) to not be so insanely expensive and unintuitive, favoring a model that says "please don't start X unless Y is healthy" and use that at deployment time.

**Comment by aquamatthias** [comment]
That's actually not true: the dependency graph is computed via `transitiveRunSpecs` which take apps and pods into account.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4696. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4696. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
