### ISSUE TITLE
AppDeployIntegrationTest "backoff delays are reset on configuration changes" is unstable

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#4849]
Marked here: f03285b20817909a1c08169436b26af5520c0a1b

Seen here: ??? @unterstein where did you see this fail?

**Comment by unterstein** [comment]
https://jenkins.mesosphere.com/service/jenkins/job/public-test-marathon-phabricator/706/

**Comment by timcharper** [comment]
Marked as serial in cc82191e0fffff21b1d6b1c3380089513473affb and seems to be passing reliably now

**Comment by unterstein** [comment]
great
