### ISSUE TITLE
Embed Call Sequence Diagrams in Scaladoc

### ISSUE THREAD

**Issue by jeschkies** [mesosphere/marathon#4856]
We should embed our diagrams in the Scala doc. See discussion on https://phabricator.mesosphere.com/D334

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4362. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4362. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
