### ISSUE TITLE
pods docs: pods can not be changed via the /v2/groups endpoint

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#4859]
as per https://github.com/mesosphere/marathon/issues/4843#issuecomment-267086044

**Comment by aquamatthias** [comment]
Dependencies are evaluated for pod deployments as well. 
Dependencies will have an effect only, if your deployment affects more than one pod.

The limitation that needs to be documented clearly: pod changes get not reflected via the /v2/groups endpoint.

**Comment by sascala** [comment]
I mention this twice on the pods docs, in the Technical Overview and Limitations sections: https://github.com/mesosphere/marathon/blob/master/docs/docs/pods.md and also discuss the pods API.
