### ISSUE TITLE
notify-rate-limiter assumes apps, no pods

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#4863]
rate limiting should work for BOTH apps and pods

xref https://github.com/mesosphere/marathon/blob/0f132000a53e8a14713b28f4a86d515876b88ec6/src/main/scala/mesosphere/marathon/core/task/update/impl/steps/NotifyRateLimiterStepImpl.scala#L36

**Comment by jasongilanfarr** [comment]
I have a funny feeling we don't do this for scale checks, health checks, etc... definitely a blocker

**Comment by jasongilanfarr** [comment]
https://phabricator.mesosphere.com/D352
