### ISSUE TITLE
Add fact, that migration to 1.5 is only possible from 1.4, to change log as highlighted change

### ISSUE THREAD

**Issue by unterstein** [mesosphere/marathon#4864]
Add a big block of documentation within the 1.5 change log for the minimum requirement of 1.4 running before migrating to 1.5 and the fact that you can not directly upgrade from a version < 1.4

See https://phabricator.mesosphere.com/D338

**Comment by jasongilanfarr** [comment]
High on my todo list is writing an extensive changelog for persistence
including warnings about 1.4->1.5. This is already tracked in JIRA too.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2447. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2447. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
