### ISSUE TITLE
Upgrade may stuck if app new launched task FINISH before health check passing

### ISSUE THREAD

**Issue by fengyehong** [mesosphere/marathon#4866]
Marathon Version: 1.3.6
Step to reproduce:
1. start a simple web server app with health check, with 1 instance, wait unit running
```
{
  "id": "/test",
  "cmd": null,
  "cpus": 1,
  "mem": 128,
  "instances": 1,
  "container": {
    "type": "DOCKER",
    "volumes": [],
    "docker": {
      "image": "httpd:2.4",
      "network": "BRIDGE",
      "portMappings": [
        {
          "containerPort": 80,
          "protocol": "tcp"
        }
      ]
    }
  },
  "healthChecks": [
    {
      "path": "/",
      "protocol": "HTTP",
      "portIndex": 0,
      "gracePeriodSeconds": 60,
      "intervalSeconds": 20,
      "timeoutSeconds": 20,
      "maxConsecutiveFailures": 3,
      "ignoreHttp1xx": false
    }
  ]
}
```
2. modify app configuration, change app cmd to "sleep 20", and upgrade

Expected result:
1. Newly launched tasks fail health check
2. Newly launched task finish
3. Marathon launch another task after the task finish
4. repeat step 1

Actual result:
1. Newly launched tasks fail health check
2. Newly launched task finish
3. From now on, marathon deployment get stuck and do not try to launch new task

I think this affects marathon 1.3.x and 1.1.x

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4758. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4758. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
