### ISSUE TITLE
Refactor Jenkins jobs

### ISSUE THREAD

**Issue by jeschkies** [mesosphere/marathon#4867]
We have several Jenkins jobs running with different configurations at different places. Some have a shell command defined, some run in some cases a shell script that's checked in, other use Pipelines:

- ~https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-unit-integration-tests-pushes/~
- https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/public-test-marathon-phabricator/
- https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-loop-tests/
- https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/public-marathon-unstable/
- https://jenkins.mesosphere.com/service/jenkins/job/public-marathon-unit-integration-tests-pulls/
- ~https://jenkins.mesosphere.com/service/jenkins/job/test-marathon-integration/~

We should define what we want and track our changes here.

We should opt for Pipelines to execute multiple jobs in stages and some in parallel.

Since we are using Phabricator we probably need to define two or three pipelines:

1. Is triggered by every revision and builds the patch against base [and master](https://github.com/mesosphere/marathon/issues/4891).
2. Is triggered by pushes to master, builds that commit and annotates it.
3. Builds pull requests by the community.

**Comment by jasongilanfarr** [comment]
I deleted test-marathon-integration after I verified its a subset of the other GitHub or builder.

I'll add what I believe the layout should be, we actually have a lot more jobs than those.

**Comment by jeschkies** [comment]
I've disabled https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-unit-integration-tests-pushes/.

**Comment by jeschkies** [comment]
I've disabled https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/public-marathon-plugin-test-pulls/

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2021. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2021. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
