### ISSUE TITLE
Partial app definition update

### ISSUE THREAD

**Issue by apognu** [mesosphere/marathon#4868]
Hi,

Most of the time, you would like to update only some attributes from an app JSON definition. `PUT`ting a JSON with only root scalar attributes (`cpus`, `mem`, etc.) works perfectly for that, but as soon as you try to update a nested attribute, behavior is not what you'd want.

My use-case is updating an app Docker image (version bump) without getting hold of the original JSON. So I'd `PUT` the following JSON:

```
{
  "container": {
    "docker": {
      "image": "image:newversion"
    }
  }
}
```

It works, but it also reinitializes all other attributes around `image`. And I can see why, Marathon could not know if I want to remove them, or leave them untouched.

Since the current behavior is the standard behavior for `PUT`, is there any plan to introduce en endpoint for the `PATCH` HTTP method that would allow to atomically edit one or more attributes from the app?

Regards,
Antoine.

**Comment by jeschkies** [comment]
Thanks for you feedback @apognu. We are currently looking into a new approach to the API so this is valuable feedback.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4497. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4497. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
