### ISSUE TITLE
Create integration test to install marathon debian snapshot package and start marathon

### ISSUE THREAD

**Issue by unterstein** [mesosphere/marathon#4869]
This test should also include configuration of parameters through `/etc/marathon/conf/`

for example
`/etc/marathon/conf/default_accepted_resource_roles` with `*` content, like described here https://github.com/mesosphere/marathon/issues/4854

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2445. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2445. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
