### ISSUE TITLE
Avoid Zookeeper Deadlock in Integration Tests

### ISSUE THREAD

**Issue by jeschkies** [mesosphere/marathon#4870]
@timcharper and I found a deadlock in `NetworkPartitionIntegrationTest` when Zookeeper was stopped and the test fails, the Zookeeper thread won't join.

A solution might be the test server from [Curator](http://curator.apache.org/curator-test/).

**Comment by timcharper** [comment]
https://phabricator.mesosphere.com/D355

**Comment by timcharper** [comment]
I had the NetworkPartitionIntegrationTest test fail and things quit properly with the curator-powered zookeeper test server.

**Comment by timcharper** [comment]
Landed in d3376ad38848bd020bd254f121da8b66e64efda7
