### ISSUE TITLE
Tasks with configured Marathon HealthChecks fail HealthChecks after migration to 1.4

### ISSUE THREAD

**Issue by meichstedt** [mesosphere/marathon#4873]
The migration from tasks to instances introduced a bug where a task's effectiveIpAddress is unresolvable after migration (there is actually a TODO left in the code). The HealthCheckWorkerActor then can't fetch the tasks IP and fails stating `Health check failed: unable to get the task's effective IP address`.

Tasks that are launched afterwards are fine. Reproducible with any task that has Marathon http health checks configured.

**Comment by jdef** [comment]
https://phabricator.mesosphere.com/D354
