### ISSUE TITLE
How can i run a container on every mesos-agent server ?

### ISSUE THREAD

**Issue by zhangjingl02** [mesosphere/marathon#4878]
some container  used every server ,How can i run a container on every mesos-agent server

**Comment by janisz** [comment]
Duplicates https://github.com/mesosphere/marathon/issues/846

**Comment by jasongilanfarr** [comment]
One option is to set the number of instances higher than the number of agents and add a constraint so that only one can run on a given agent. We will be stuck permanently trying to deploy your container...

**Comment by jasongilanfarr** [comment]
Closing in favor of the duplicate.
