### ISSUE TITLE
delete redundant wix validation code

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#4881]
once #4879 lands we should remove redundant wix validation code (and refactor unit tests appropriately)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1758. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1758. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
