### ISSUE TITLE
Enable pod command checks when mesos supports them.

### ISSUE THREAD

**Issue by jasongilanfarr** [mesosphere/marathon#4895]
See also: 6c0149d0d1592bb0bc5509a1b5e4770605f87905

**Comment by aquamatthias** [comment]
Mesos JIRA: https://issues.apache.org/jira/browse/MESOS-6280

It is not clear, if it lands in Mesos 1.2

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2149. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
