### ISSUE TITLE
Groups endpoint is providing different information then apps endpoint

### ISSUE THREAD

**Issue by Poltergeist** [mesosphere/marathon#4899]
I did the same as in #4897 described in the animation. But I actually clicked on cancel. Now the Groups endpoint is delivering me with `instances: 2` for the app `/test` and the apps endpoint of the app is providing me with `instances: 0`. This is how the marathon UI handles this issue: 

![wttask mov](https://cloud.githubusercontent.com/assets/156010/21391523/59c1d1b8-c78c-11e6-9f08-92a2d9628dc4.gif)

**Comment by zen-dog** [comment]
Tested locally on current master and both endpoints (groups and apps) give back the right instance count.

**Comment by Poltergeist** [comment]
In `1.4.0-RC4` This issue seems to be fixed it occurred to me in `1.4.0-RC3`
