### ISSUE TITLE
how to create a task with gpu and docker

### ISSUE THREAD

**Issue by cjnewstar111** [mesosphere/marathon#4909]
I want to create a task whith gpu and docker. fist  I use the docker type like this，but it appears error like 'GPU resources only work with the Mesos container' 
![gpu](https://cloud.githubusercontent.com/assets/16218143/21448879/551551c0-c922-11e6-953c-664d2093a40f.jpg)
then I use the cmd type, like this, though this task can be craeted, but it always in the state of 'Waiting', and can not be 'running' status. So i really want to know how to use marathon with gpu and docker
![2](https://cloud.githubusercontent.com/assets/16218143/21448901/965972a6-c922-11e6-9573-847ec8077a1c.jpg)
![3](https://cloud.githubusercontent.com/assets/16218143/21448940/db7404c8-c922-11e6-929f-99f6c071ca43.jpg)

**Comment by c-yokoyama** [comment]
I'm trying to create a similar task. First, I faced the same problems.
I added the following option when launching the mesos agent, 
```
--containerizers=docker,mesos --isolation=cgroups/devices,gpu/nvidia,filesystem/linux,docker/runtime --image_providers=docker 
```
and used nvidia-docker cmd like this.(You need to install nvidia-docker in mesos agent node previously.)
```
{
    "id": "nvidia-docker-test",
    "cmd": "nvidia-docker run -it nvidia/cuda bash",
    "cpus": 1,
    "mem": 512.0,
    "gpus": 1
}
```
I was able to deploy gpu containers in this way, however when I destroyed the task on marathon GPU,  the gpu container process was not killed in the mesos agent node .

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1887. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
