### ISSUE TITLE
Git pull support in URI?

### ISSUE THREAD

**Issue by ror6ax** [mesosphere/marathon#4910]
Well, there's not much to talk about, really.

It looks like URI's are being used as provision hooks and that use would surely benefit from versionality, etc.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2657. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
