### ISSUE TITLE
Document limits and performance of Marathon

### ISSUE THREAD

**Issue by bergerx** [mesosphere/marathon#4913]
Can we have a doc about telling current known limits of the framework.

In the past we didn’t do our homework, didn’t run tests for marathon control plane and were hit hard by the max app limit (not container) in production. Marathon stopped responding at some point, that was in [an earlier version of Marathon](https://github.com/mesosphere/marathon/blob/master/changelog.md#performance-improvements-1). We were forced to deploy a couple of marathons because of this, then i left that company before being able to upgrade Marathon version.

I'm coming against the same question 3rd time in different companies before putting together a system to deploy multiple services, we first want to have some answers about it's scalability.

Here are some question I have in mind:
* what is the expected resources (cpu, mem) to be reserved to marathon for a fixed sized cluster (ideally a matrix with different key parameters)
* what is the max app/group counts
* what is the max agent count in a cluster
* what is the max task count to be managed by marathon
* how app/group/agent count impacts the performance of marathon
* what is the limit of apps to be created via [post to groups endpoint](https://mesosphere.github.io/marathon/docs/generated/api.html#v2_groups_post)
* how concurrent deployments impacts the performance of marathon (e.g. having 600 apps deployed at once)

**Comment by aquamatthias** [comment]
@bergerx I agree with most of your points.
I would add:
- command line settings for a fixed sized cluster (different sizes). Especially with respect to:
   - reconciliation
   - offer handling 
   - launch behaviour
   - kill behaviour

This is a topic we are actively working on. 
Once they are available, we will share the results.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4345. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
