### ISSUE TITLE
Propose, establish and adopt a consistent test fixture approach

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#4918]
This arises from a desire improve the clarity of lifecycle management for stateful fixtures such as actor systems and zookeeper instances. One attempt can be found in [D379](https://phabricator.mesosphere.com/D379), which introduced an `onTeardown` method for fixtures and enforces better separation of concerns, such that the entity responsible for creating an actorSystem is directly responsible for making sure it is cleaned up properly.

After a discussion in our internal developer slack channel, here are some shared agreements amongst the Marathon core team:

- `var thing: Type = _; before { thing = ??? }` pattern should be avoided and removed. None of us like it and there are several clearly better alternatives (`withFixture` / loan-fixture / trait style with `onTeardown`).
- Much of Akka testkit is built around the assumption that a single`ActorSystem` is used for a suite. Many of our tests instantiate the same actor with the same name and are dependent on a unique actor system per test. We should make it so that these actors don't collide with each other, by using a unique `ActorRefFactory` and supervisor per test, with appropriate levels of isolation (delayed crash from actor created in former test should not cascade and cause actors to crash in a later test).
- The setup code and teardown code should be in the same module. We should never instantiate something that needs to be closed as a default for some parameter. Either something provides the closable thing, and sees to it being closed, or the thing that instantiates handles the closing concern (could be by registering a termination hook / after hook). 
- For tests with unavoidable actor name collisions, it would probably be ideal to use an actorRefFactory, in which case, a `withRefActory` loan-fixture method is warranted.

When we solidify the direction we want to go, we should update `contributing.md` to include these guidelines. Also, we should update and land `D379` as appropriate.

**Comment by timcharper** [comment]
As an alternative to `onTeardown`, it appears that the recommended way to do fixtures in ScalaTest is to define a type, `FixtureParam`, and mix in one of `org.scalatest.fixture.{FunSpec,FlatSpec}`, and implement `withFixture`.

This probably works in most cases but it has other limitations. It may be desirable to provide different sets of values in fixtures from one test to the next; this mechanism doesn't provide an easy way to specify that. It may also be desirable to override a value in one test, which is used as an input to another fixture value (like `akkaConfig`). This is also difficult to do with the `org.scalatest.fixture.{FunSpec,FlatSpec}` approach.

**Comment by jeschkies** [comment]
The *loan-fixture methods* as described [here](http://www.scalatest.org/user_guide/sharing_fixtures#loanFixtureMethods) seem quite good to me. We could provide a common set of methods to mix in. We already use them in [KillServiceActorTest](https://github.com/mesosphere/marathon/blob/master/src/test/scala/mesosphere/marathon/core/task/termination/impl/KillServiceActorTest.scala).

**Comment by timcharper** [comment]
Here are some options:

## OneArgTest / org.scalatest.fixture.FunSpec

- `+` built in to Scala test; standard
- `+` concise
- `-` all tests must receive exactly the same fixture; not possible to override values
- `-` does not compose well

```scala
class ExampleSpec extends org.scalatest.fixture.FunSpec {
  class FixtureParam {
    implicit lazy val system = ActorSystem(uniqueId)
    implicit lazy val materializer = ActorMaterializer()
    lazy val dispatcher = system.dispatcher
  }

  def withFixture(test: OneArgTest) = {
    val theFixture = new FixtureParam()

    try {
      withFixture(theFixture)
    }
    finally theFixture.system.terminate().futureValue
  }

  test("should do the thing") { f =>
    import f._
    // ...
  }
}
```

## loan fixtures (implicit containers)

With loan fixtures, I would propose that, when yielding multiple values, we yield a container class implicitly, such that helper methods are able to to declare which fixtures sets they need, implicitly.

- `+` can customize the fixtures per test by passing parameters to the loan fixture method
- `+` helper methods can access the fixtures asking for the fixture container implicitly
- `+` container can describe implicit / non-implicit properties which can be imported as needed for the test
- `-` a bit verbose.
- `+` very clear from where values are coming

```scala
class AkkaFixtures(config: Config) {
  implicit lazy val system = ActorSystem(uniqueId, config)
  implicit lazy val materializer = ActorMaterializer()
  lazy val dispatcher = system.dispatcher
}

object AkkaFixtures {
  def apply(config: Config = ConfigFactory.load())(body: AkkaFixtures => Unit): Unit = {
    val f = new AkkaFixtures(config)

    try {
      body(f)
    }
    finally f.system.terminate().futureValue
  }
}

class ExampleSpec extends FunSpec {
  class OtherFixtures(implicit akkaFixture: AkkaFixtures) {
    val leActor = akkaFixture.system.actorOf(Props(...))
  }

  def otherFixtures(body: OtherFixtures => Unit)(implicit akkaFixture: AkkaFixtures) {
    val f = new OtherFixtures
    try {
      body(f)
    }
    finally f.leActor ! PoisonPill
  }

  val altConfig: Config = ???

  def helperMethod(param: Int)(implicit akkaFixture: AkkaFixtures, ) = {
    // ...
  }

  test("should do the thing") {
    AkkaFixtures(config = altConfig) { implicit akkaFixture =>
      otherFixtures() { implicit other =>
        import akkaFixture._
        import other._
        helperMethod(someParam)
        // ...
      }
    }
  }
}
```

## loan fixtures (not implicit containers)

We use containers only when we need to specify a mix or multiple implicit / not-implicit fixture values (such as akka fixtures set... implicit materialize, system, timeout, non-implicit dispatcher).

Helper methods which depend on fixture values only depend on the exact fixture values they need

- `+` can customize the fixtures per test by passing parameters to the loan fixture method
- `+` helper methods can access the fixtures asking for the fixture container implicitly
- `+` container can describe implicit / non-implicit properties which can be imported as needed for the test
- `-` more verbose.
- `-` very clear from where values are coming

```
class AkkaFixtures(config: Config) {
  implicit lazy val system = ActorSystem(uniqueId, config)
  implicit lazy val materializer = ActorMaterializer()
  lazy val dispatcher = system.dispatcher
}

object AkkaFixtures {
  def apply(config: Config = ConfigFactory.load())(body: AkkaFixtures => Unit): Unit = {
    val f = new AkkaFixtures(config)

    try {
      body(f)
    }
    finally f.system.terminate().futureValue
  }
}

class ExampleSpec extends FunSpec {
  class OtherFixtures(akkaFixture: AkkaFixtures) {
    val leActor = akkaFixture.system.actorOf(Props(...))
  }

  def otherFixtures(akkaFixture: AkkaFixtures)(body: OtherFixtures => Unit) {
    val f = new OtherFixtures(akkafixtures)
    try {
      body(f)
    }
    finally f.leActor ! PoisonPill
  }

  val altConfig: Config = ???

  def helperMethod(param: Int, actorSystem: ActorSystem, leActor: ActorRef) = {
    // ...
  }

  test("should do the thing") {
    akkaFixtures(config = altConfig) { akkaFixture =>
      otherFixtures(akkaFixture) { other =>
        import akkaFixture._
        import other._
        helperMethod(someParam)
        // ...
      }
    }
  }
}
```

# Composable traits with onTeardown support

This approach uses Scala's composable traits, and depends on a method which can be called inside of a test, `onTeardown`, to register some bit of code that should be executed when the test is complete.

It's documented [here](http://www.scalatest.org/user_guide/sharing_fixtures#fixtureContextObjects) (although onTeardown is not)

- `+` Minimal low boiler plate
- `+` Very composable
- `+` Easily customizable per test
- `+` Impossible to instantiate the fixture without registering the teardown hook
- `-` Possible to accidentially instantiate the fixture outside of a test, leading to a runtime exception instead of compiler error.
- `-` overrides can become unwieldy; everything must be declared lazily in order to allow for overrides. Failure to do so = runtime error.
- `-` Requires new `OnTeardownSupport`; `BeforeAndAfter` is insufficient because `after` can only be called once *PER SUITE*

```scala
trait AkkaFixtureSupport with OnTeardownSupport {
  trait AkkaFixtures {
    lazy val config = ConfigFactory.load
    implicit lazy val system = ActorSystem(uniqueId, config)
    implicit lazy val materializer = ActorMaterializer()
    lazy val dispatcher = system.dispatcher

    onTeardown { system.terminate().futureValue }
  }
}

class ExampleSpec extends AkkaFixtureSupport {
  trait Fixtures extends AkkaFixtures {
    val leActor = system.actorOf(Props(...))
    onTeardown { leActor ! PoisonPill }

    def helperMethod(param: Int) = {
      // ...
    }
  }


  test("should do the thing") {
    new Fixtures {
      override lazy val config = ConfigFactory.parse("???")
      helperMethod(someParam)
      // ...
    }
  }
}
```

**Comment by timcharper** [comment]
We also need to think about akka fixtures.

Options:

- Inject all actors with unique paths such that they don't collide nor see eachother (from test to test)
  - 👍 simple
  - 👍 do not need a teardown per test
  - 👎 we don't clean up on each test; potentially stochastic failure

- Create a parent actor per test, use testkit underlyingActor to get a unique `ActorRefFactory` per test.
  - 👍 easy
  - 👍 better isolation, clean up per test
  - 👎 requires teardown per test, which introduces complexity

**Comment by timcharper** [comment]
After our meeting it seems like we got consensus on the following points:

- Use patterns that are already suggested / encouraged
- Simplicity mostly trumps verbosity here
- Prefer to use actor-system-per-suite
- We don't want to make it easy to do stateful fixtures because they should only be used when absolutely necessary

With these consensus points, I'm going to suggest that we do the following:

- No more `var thing: Type = _` with before / after.
- We will create and tear down in the same module
- We will use an actor system for the entire suite. We will let generally let actors get killed when the suite finishes. While not ideal (we could have some confusing logs if previous actors are still logging messages, for example), it's probably fine. We will either have unique actor names or use the loan-fixtures technique to get a unique actor ref factory per test.
- If we want immediate teardown, we'll use the loan fixtures technique to provide fixtures to each suite. If we don't need immediate teardown, we will use traits or factory methods / case classes / whatever.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4438. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
