### ISSUE TITLE
Marathon silently drops command health checks

### ISSUE THREAD

**Issue by orlandohohmeier** [mesosphere/marathon#4919]
Marathon silently drops command (exec) health checks when creating pods even though the API doc says the pod spec is perfectly valid. 

**API Doc**
https://github.com/mesosphere/marathon/blob/master/docs/docs/rest-api/public/api/v2/types/healthCheck.raml#L33

**Pod Spec**
```
{
  "id": "/test/pod-with-command-health-check",
  "containers": [
    {
      "name": "container-1",
      "resources": {
        "cpus": 0.1,
        "mem": 10
      },
      "exec": {
        "command": {
          "shell": "while true ; do echo 'test' ; sleep 100 ; done"
        }
      },
      "healthCheck": {
        "exec": {
          "command": {
            "shell": "sleep 5 ; exit 0"
          }
        }
      }
    }
  ],
  "scaling": {
    "kind": "fixed",
    "instances": 1
  },
  "networks": [
    {
      "mode": "host"
    }
  ]
}
```

**Marathon Version**
```
1.4.0-RC3
```

_Side Note:  Marathon shouldn't silently drop any config, but that is a different topic and covered in #2164_

**Comment by aquamatthias** [comment]
Mesos currently does not support command based health checks with pods.
Marathon has a validation rule that prevents those health checks.
Pasting your definition yields this response:
```json
{
    "details": [
        {
            "errors": [
                "Mesos Master (1.1.0) does not support Command Health Checks"
            ],
            "path": "/containers(0)/healthCheck"
        }
    ],
    "message": "Object is not valid"
}
```
I removed the validation rule, and the health check was accepted and returned.
The value was not dropped.
