### ISSUE TITLE
AppStartActorTest is unhealthy

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#4921]
Observing a 10% failure rate in most of them. Stats in the loop build as of now:

```
   2 mesosphere.marathon.upgrade.AppStartActorTest:Without Health Checks
   6 mesosphere.marathon.upgrade.AppStartActorTest:With Health Checks
   7 mesosphere.marathon.upgrade.AppStartActorTest:Failed
   7 mesosphere.marathon.upgrade.AppStartActorTest:No tasks to start with health checks
   7 mesosphere.marathon.upgrade.AppStartActorTest:No tasks to start without health checks
Sample size: 71
```

**Comment by aquamatthias** [comment]
https://phabricator.mesosphere.com/D403

**Comment by HackToday** [comment]
Looking forward this fix, since now, build from source would fail to produce marathon jars.

**Comment by timcharper** [comment]
@janisz I made a silly little `Makefile` which downloads the reports from Jenkins, and then uses some unix tools + jq to make get the counts.

**Comment by timcharper** [comment]
https://gist.github.com/timcharper/633cbe755887c55aa620ee1d7da81e69

**Comment by janisz** [comment]
Thanks for sharing. I thought you used some sbt plugin. I run `sbt test` in a loop for a night and then parse an output with grep
```bash
while true; do sbt "integration:test" 2>> /tmp/integration_test_master.txt; done
cat /tmp/integration_test_master.txt | grep "All tests passed" | wc -l
cat /tmp/integration_test_master.txt | grep "\*\*\* FAILED \*\*\*" | less
```
to see what tests fails and how often.
