### ISSUE TITLE
pod.container.image API is missing labels, used by appc API

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#4931]
related mesos proto: https://github.com/apache/mesos/blob/be127e6eca1312bf8c2b039646f6909fa42cd342/include/mesos/mesos.proto#L1851

**Comment by aquamatthias** [comment]
@nfnt  Do we need a specific API to set appc labels -  can we just use the container labels?

**Comment by aquamatthias** [comment]
@nfnt:
I created a patch that sets appc labels from pod and container labels: https://phabricator.mesosphere.com/D407
Can you try to launch an appc container with custom labels?

**Comment by nfnt** [comment]
Custom labels are okay to use with appc images. Only the `version`, `os` and `arch` labels will be used by the appc provisioner, other labels will be ignored. The `os` and `arch` labels are required, `version` will be set to "latest" by default. So we can use the container labels to set appc labels.

**Comment by aquamatthias** [comment]
I see. Instead of using labels here, we probably should create properties for appc container:
```
os: String (default = linux)
arch: String (default = amd64)
version: String (default = latest)
```

**Comment by nfnt** [comment]
Yes, this seems like a better solution. The comment in `mesos.proto` for this label is misleading. It says that these labels are optional even though they are not.

**Comment by aquamatthias** [comment]
Looks like the appc integration in Mesos is experimental.
We probably should rethink to change the API, if the underlying Mesos API is stable.
Until then I recommend to use the labels approach from [D407](https://phabricator.mesosphere.com/D407)

**Comment by aquamatthias** [comment]
@jasongilanfarr any thoughts on this?

**Comment by jasongilanfarr** [comment]
Agree with your suggestion
