### ISSUE TITLE
Upgrading a RC might lead to an inconsistent state

### ISSUE THREAD

**Issue by gkleiman** [mesosphere/marathon#4943]
The format of the persisted objects sometimes changes between release candidates.

Right now migrations are only run between final releases, this might lead to an inconsistent state when upgrading from Marathon vx.x.x-RCN to vx.x.x-RCN+1. In some cases the only/easiest way of fixing this is to teardown the framework and wipe the ZK state, which is far from ideal.

I think that this makes testing harder for users, but if this is the expected behaviour, then we should document it somewhere - probably with a big warning in the RC release notes.

**Comment by aquamatthias** [comment]
The storage version needs to be adapted, so we can run migrations between RCs.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4713. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
