### ISSUE TITLE
Containerizer change from mesos to docker 

### ISSUE THREAD

**Issue by evilezh** [mesosphere/marathon#4944]
Running mesos 1.1.0 and marathon 1.3.5. 
so .. I've told that marathon should launch via MESOS containerizer ... after some failures to launch container, it is automatically changed to DOCKER. Maybe someone think it about as cool feature, but as DOCKER is not installed and it does not swtich back to MESOS .. task now is set to fail forever.

**Comment by unterstein** [comment]
Hi @evilezh,

thanks for reporting! Could you please add your app definition and the logs of marathon to reproduce and retrace your issue?

Thanks
Johannes

**Comment by aquamatthias** [comment]
@evilezh See https://mesosphere.github.io/marathon/docs/native-docker.html for setting up Mesos and examples for an application. Please reopen if there is anything missing.
