### ISSUE TITLE
Marathon container service orchestration

### ISSUE THREAD

**Issue by tangjiaxing669** [mesosphere/marathon#4945]
How to use marathon containers to achieve service orchestration, similar docker-compose?

Marathon deployment seems unable to achieve this function.

**Comment by janisz** [comment]
This can be done at executor level see https://github.com/mesos/docker-compose-executor or by manual translation of docker compose yaml to marathon group http://stackoverflow.com/a/40038361/1387612

**Comment by tangjiaxing669** [comment]
@janisz Thanks

**Comment by tangjiaxing669** [comment]
@janisz i used docker-compose-executor, but it can't running in marathon 1.3.6. Is there any other workaround?  This is my question [https://github.com/mesos/docker-compose-executor/issues/19](https://github.com/mesos/docker-compose-executor/issues/19)

**Comment by janisz** [comment]
It looks like threre is a problem with Marathon validation. Can you run same configuration without container filed?

```json
{
  "id": "docker-compose-demo",
  "cmd": "echo hello world",
  "cpus": 1,
  "mem": 128,
  "disk": 0,
  "instances": 1,
  "constraints": [["hostname", "CLUSTER", "slave3"]],
  "executor": "/usr/local/src/compose_executor.sh",
  "labels": {
      "fileName": "/root/docker-compose.yml"
  }
}
```
Created issue for this: https://github.com/mesosphere/marathon/issues/4978

**Comment by tangjiaxing669** [comment]
@janisz  If there is no container field, you will be prompted with the following information:

```
There was a problem with your configuration
general: AppDefinition must either contain one of 'cmd' or 'args', and/or a 'container'.
```

**Comment by aquamatthias** [comment]
@tangjiaxing669 The validation makes sure, your app defines an entry point, which is either `cmd`, `args` or `container`. It looks like custom executors are not part of this equation. Please file as a separate issue. 
If you define ```"cmd": "foo"``` does it start correctly?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1941. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
