### ISSUE TITLE
Constraints in Marathon UI: Unable to use regexes which contain commas

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#4950]
created by @nickbp 

In the UI, commas are used in the placement constraint syntax to separate multiple rules which are ANDed together. However they may also be used within regexes for those constraints.
At the moment there doesn't appear to be a way to escape the commas which are meant to be inside regex strings. For example, something like backslash escaping could be supported in the UI:

`rack_id:LIKE:{bar.*\,baz.*},hostname:UNLIKE:baz`
(at the moment this results in a syntax error)

Specific steps were:
Go to /marathon
Click new application button
Switch to Optional section
Enter one of the above in the Constraints box

other examples:
`rack_id:LIKE:{bar.*,baz.*}`
`rack_id:LIKE:"{bar.*,baz.*}`

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1720. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
