### ISSUE TITLE
How to run application with custom executor?

### ISSUE THREAD

**Issue by janisz** [mesosphere/marathon#4952]
Is it possible to run app with custom executor using Marathon?

Currently Marathon runs custom executors like this:
[`val shell = s"chmod ug+rx $executorPath && exec $executorPath $cmd"`](https://github.com/mesosphere/marathon/blob/v1.4.0-RC5/src/main/scala/mesosphere/mesos/TaskBuilder.scala#L72)

this make it really hard (or impossible) to use custom executor with Docker. The above code was added for Mesos 0.14. While there was change in 0.20.0 to support custom executor with container

> [With 0.20.0 we added a ContainerInfo field to TaskInfo and ExecutorInfo that allows a Containerizer such as Docker to be configured to run the task or executor.](https://mesos.apache.org/documentation/latest/docker-containerizer/)

**Comment by aquamatthias** [comment]
@janisz Good question. This feature is available for a long time. I have not heard a lot from people using custom executors with Marathon.
@nfnt Can you try to test this functionality?

**Comment by jdef** [comment]
Using a custom executor w/ Marathon is probably somewhat perilous. The expectation is that any custom executor should implement some minimum set of executor behavior in a manner consistent with Marathon's expectations (consider Mesos health checks). We should probably have some better documentation around this topic if it's something that we intend to continue support for.

**Comment by janisz** [comment]
The only problem that I spotted is this weird command. It was not touched from ages and probably tries to solve some issue with ancient Mesos version. Currently command should contain only information how to launch task.

**Comment by jdef** [comment]
Also, if we want robust, first-class support for custom executors then I'd argue that we should expose a richer API for specifying the executor command (for example, args vs. command line for executor invocation)

**Comment by janisz** [comment]
Releated code from Singularity: https://github.com/HubSpot/Singularity/blob/db9b5564c56bd7bfadec7edfe2c407d6782144c1/SingularityService/src/main/java/com/hubspot/singularity/mesos/SingularityMesosTaskBuilder.java#L341
Thread: https://lists.apache.org/thread.html/135a687756732274c66c03a89752746236e26d0296ab6f2b93bc1c19@1409872992@%3Cuser.mesos.apache.org%3E

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4210. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
