### ISSUE TITLE
Debug logging is not enabled properly by logging level flag

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#4960]
When running the following (in sbt):

```
set testOptions in Test := Nil
test-only mesosphere.marathon.integration.LeadershipAbdicationIntegrationTest -- -z "Abdicating a leader does not kill a running task which is currently involved in a deployment"
```

We should see the text, logged at debug level, "Start processing offer"; however, we do not.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4561. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
