### ISSUE TITLE
Clean up Marathon jobs in Jenkins

### ISSUE THREAD

**Issue by artemharutyunyan** [mesosphere/marathon#4961]

**Comment by jeschkies** [comment]
Seems to be a child of https://github.com/mesosphere/marathon/issues/4867

**Comment by jeschkies** [comment]
Should be done if we have online master, releases and Phabircator pipelines left.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2257. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
