### ISSUE TITLE
--disable_metrics has no effect

### ISSUE THREAD

**Issue by jasongilanfarr** [mesosphere/marathon#4966]
DebugConf maps the option value instead of actually checking if it was disabled.

Appears to have been the case since April 2015.

```
    val metricsBehavior = conf.metrics.get.map(_ => new MetricsBehavior(metricsProvider))
```
 should be something like
```
    val metricsBehavior = if (conf.metrics.get.getOrElse(true)) Some(new MetricsBehavior) else None
```

**Comment by aquamatthias** [comment]
Patch is here: https://phabricator.mesosphere.com/D451
