### ISSUE TITLE
Cluster nodes full from old images -- recommended cleanup action?

### ISSUE THREAD

**Issue by DrEsteban** [mesosphere/marathon#4967]
We are running into issues where the agent nodes have maxed out their disk space, due to the accumulation of old image versions.  The error message can usually be found in the container logs.  Something like "no space left on device".

**Does Marathon have a suggested/supported way to clean out old images/containers from the agents?**

**Comment by janisz** [comment]
Take a look at https://github.com/spotify/docker-gc

**Comment by meichstedt** [comment]
@DrEsteban Marathon can only tell Mesos to launch tasks on a given agent, it cannot offer means of gc'ing on those agents.

@janisz thanks for posting the link!

**Comment by DrEsteban** [comment]
@janisz As I understand it, the "docker-gc" image will only do gc on whatever node Marathon decides to start it on.  How would I ensure that _all_ nodes run the image to ensure the entire cluster is cleaned?

**Comment by jasongilanfarr** [comment]
@DrEsteban You can set `instances` to the number of nodes or higher and marathon will run it on every agent it can. The app will be stuck deploying forever though....

**Comment by DrEsteban** [comment]
@jasongilanfarr Won't that _only_ guarantee X number of instances?  For example, Marathon could potentially try to start all X containers on the same agent?

**Comment by jasongilanfarr** [comment]
You would need to add a constraint to ensure that only one can run on any given host.

**Comment by DrEsteban** [comment]
Excuse my ignorance, but do you have a link or quick summary on how to add that constraint?

**Comment by DrEsteban** [comment]
@jasongilanfarr Something like this?

```
$ curl -X POST -H "Content-type: application/json" localhost:8080/v2/apps -d '{
    "id": "sleep-unique",
    "cmd": "sleep 60",
    "instances": 3,
    "constraints": [["hostname", "UNIQUE"]]
  }'
```

[https://mesosphere.github.io/marathon/docs/constraints.html](https://mesosphere.github.io/marathon/docs/constraints.html)

**Comment by jasongilanfarr** [comment]
That could work, yes.

**Comment by janisz** [comment]
In 1.13 Docker adds this functionality [`docker system prune`](https://docs.docker.com/engine/reference/commandline/system_prune/)

**Comment by jdef** [comment]
https://issues.apache.org/jira/browse/MESOS-4945

**Comment by DrEsteban** [comment]
Updating this thread, I went ahead and created a Gist post which outlines our solution for this problem.  

https://gist.github.com/DrEsteban/b0fc800d5b524752558801437a0aed78

@jdef, that sounds exactly like the functionality I was originally asking about, thanks for linking that feature request!
