### ISSUE TITLE
Delete Event Subscriber Endpoint

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#4971]

**Comment by janisz** [comment]
I think this is blocked by https://github.com/mesosphere/marathon/issues/4686 We can't remove endpoint without providing events functionality for integration tests because some of them rely on events.

**Comment by jasongilanfarr** [comment]
My draft review takes care of this.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2456. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
