### ISSUE TITLE
How can assign fixed IP from mesos matahon while launching docker container

### ISSUE THREAD

**Issue by geolig** [mesosphere/marathon#4974]
Team,

 Please let us know how can i achieve fixed IP for each container while launching application from the mesos marathon console. Let me know if you have any steps/procedure if you have published anywhere.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1966. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
