### ISSUE TITLE
Scale Test of 1k hosts

### ISSUE THREAD

**Issue by kensipe** [mesosphere/marathon#4984]

**Comment by kensipe** [comment]
blocked on gce tooling from kevin.   should be available by the end fo the week.

**Comment by kensipe** [comment]
Test with 1k nodes on GCE was finally executed.  It shows issues with marathon 1.3.6 on scaling up.   It showed issues with scale app mem configuration in the tests.  It should a decrease in dcos responsiveness... commonly resulting in 503 errors for deployed services.

**Comment by kensipe** [comment]
It is now blocked waiting for 1.9 EA release

**Comment by marcomonaco** [comment]
This can be also closed, right?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2125. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
