### ISSUE TITLE
Don't start a new deployment when configurations like "minimumHealthCapacity" are changed only

### ISSUE THREAD

**Issue by leventov** [mesosphere/marathon#4987]
When I change an app config via web UI, and change only configurations like `updateStrategy.minimumHealthCapacity`, making a rolling update with all other configurations unchanged is pointless.

**Comment by janisz** [comment]
Probably only required change is in implementation of [mesosphere.marathon.state.RunSpec#needsRestart](https://github.com/mesosphere/marathon/blob/f2a052c8147f8120083f7c9d731e0f0bb5e958d7/src/main/scala/mesosphere/marathon/state/RunSpec.scala#L48). Deployment plan is ready to perform no action [if restart is not required](https://github.com/mesosphere/marathon/blob/9dc73ae7bf1833f8c5353c8d160f43a87dcab4c2/src/main/scala/mesosphere/marathon/upgrade/DeploymentPlan.scala#L238). 
I'm afraid that subset of configuration options that do not require task restart is really small and nobody will notice the difference.
Releated: https://github.com/mesosphere/marathon/issues/3945 https://github.com/mesosphere/marathon/issues/3143

**Comment by aquamatthias** [comment]
There are values in an app or pod definition, that have no consequences to the running tasks.
Marathon should not restart tasks if only such configuration is affected. 
This is a common request and on our roadmap.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4709. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
