### ISSUE TITLE
Rollback shouldn't update instances, which were not yet touched by the rolled back deployment 

### ISSUE THREAD

**Issue by leventov** [mesosphere/marathon#4988]
If I have 10 instances and minimumHealthCapacity = 0.9, and start a new deployment, instances are updated one-by-one. When I click "Rollback" deployment which has yet touched only one instance, Marathon starts to update all 10 instances with the old configuration, even those 9 which are already on that version.

**Comment by kamilchm** [comment]
Duplicate of https://github.com/mesosphere/marathon/issues/4046?

**Comment by aquamatthias** [comment]
Duplicate #4046
