### ISSUE TITLE
Generated Rest API Docs Broken

### ISSUE THREAD

**Issue by drewkerrigan** [mesosphere/marathon#4996]
https://mesosphere.github.io/marathon/docs/rest-api.html

If you scroll down to "DELETE /v2/apps/{appId}/tasks/{taskId}” - You’ll see where the html and markdown are shown instead of correctly generated html.

**Comment by branden** [comment]
Just ran into this and was about to report it. Looks like markdown -> HTML rendering stopped in the middle of the document. Screenshot of page source:

![screenshot 2017-01-19 15 27 29](https://cloud.githubusercontent.com/assets/42242/22129625/fe07ea10-de5b-11e6-9d0a-49b57e6674d0.png)

**Comment by drewkerrigan** [comment]
Yeah I can actually see the culprit right in your screenshot, `<code>wipe=false...` is an unclosed `code` tag which would result in the behavior we're seeing.

**Comment by aquamatthias** [comment]
Thanks for the fix. Republished the site.
