### ISSUE TITLE
Set the docker on the portmapping slave to fail to start

### ISSUE THREAD

**Issue by floodcool** [mesosphere/marathon#4998]
Using Mesos 1.0.1 version of the development of java-based Framework, in the scheduler to create a configuration docker configuration, when you set the portMapping, as shown below, slave can not start,The portMapping configuration code is as follows:

DockerInfo.PortMapping.Builder portMapping = DockerInfo.PortMapping.newBuilder();
portMapping.setContainerPort(10470);
portMapping.setHostPort(32768);
portMapping.setProtocol("tcp");
dockerInfoBuilder.addPortMappings(portMapping.build());

Exception information is as follows:
I0118 16:37:46.352216 29057 exec.cpp:237] Executor registered on agent ee14920b-7aab-49d0-a939-9281407038d6-S2
W0118 16:37:46.352216 29055 logging.cpp:91] RAW: Received signal SIGTERM from process 29313 of user 0; exiting

The same configuration, if you do not set portMapping can start normally, please advise!
 However, there is no port to display using the docker ps command

**Comment by janisz** [comment]
Did you set Network to BRIDGE? By default it's [HOST](https://github.com/apache/mesos/blob/1.0.1/include/mesos/mesos.proto#L1814). What contenerizer are you using? Mesos conenerizer does not support port mapping yet.

Is this question Marathon releated? I think you should ask on Apache Mesos mailing list.

**Comment by floodcool** [comment]
@janisz  Network has been set up to BRIDGE, I use the Mesos conenerizer. Why in the relevant api portmapping set.
Sorry, it is really asking the question of Apache Mesos.

**Comment by janisz** [comment]
In Mesos 1.0.2 only HOST network is supported with Mesos Containerizer with Docker runtime. 
From Mesos documentation:

> [Only host network is supported. We will add bridge network support soon using CNI support in Mesos](https://github.com/apache/mesos/blob/1.0.2/docs/container-image.md) [(MESOS-4641).](https://issues.apache.org/jira/browse/MESOS-4641)

**Comment by aquamatthias** [comment]
@floodcool Hope the answer helps. If not: Please ask in the Mesos forum.
