### ISSUE TITLE
`pod kill instance X` doesn't kill the instance

### ISSUE THREAD

**Issue by jasongilanfarr** [mesosphere/marathon#5002]
To repro:
Add pod: https://github.com/dcos/dcos-cli/blob/master/cli/tests/data/marathon/pods/pod_kill.json
`dcos marathon pod add /path/to/pod`
Get pod instance from: `dcos marathon pod list --json`
`dcos marathon pod kill kill-pod instance-id-here`
call to DELETE /service/marathon/v2/pods/pod-kill::instances succeeds, 10 seconds later, no change.
CLI test for this started failing with recent dcos-enterprise change. See test failure: https://teamcity.mesosphere.io/viewLog.html?buildId=537536&buildTypeId=DcosIo_DcosCli_Linux_Binary&guest=1
Options

**Comment by aquamatthias** [comment]
I tried to reproduce this on Marathon 1.4.0-RC5

```
$>  cat simple-pods.json  | http :8080/v2/pods
HTTP/1.1 201 Created
...
```
Wait for deployment to finish.
```
$>  http :8080/v2/pods/simple-pods::status
HTTP/1.1 200 OK
...
```
Grep instance id which was `simple-pods.instance-0f1a9296-e305-11e6-bbed-b224fe3de2fd` in my case.

```
$> http DELETE :8080/v2/pods/simple-pods::instances/simple-pods.instance-0f1a9296-e305-11e6-bbed-b224fe3de2fd
HTTP/1.1 200 OK
...
```

Delete the instance which returned the instance json.

Worked on the Marathon side. I guess the problem is in the CLI?



```
simple-pods.json
{
  "id": "/simple-pods",
  "scaling": { "kind": "fixed", "instances": 1 },
  "environment": { "PING": "PONG" },
  "containers": [
    {
      "name": "ct1",
      "resources": {
        "cpus": 0.1,
        "mem": 32
      },
      "exec": { "command": { "shell": "sleep 1000" } }
    }
  ],
  "networks": [
    { "mode": "host" }
  ]
}
```

**Comment by unterstein** [comment]
Hi,

can`t reproduce via CLI against current dcos testing/master:

```
Johanness-MacBook-Pro:cli junterstein$ dcos marathon pod add pod_kill.json 
Created deployment 079e047f-c4b5-4a5b-8b2e-0c60f0654600

Johanness-MacBook-Pro:cli junterstein$ dcos marathon pod list --json > tmp.json && cat tmp.json | grep "pod-kill.instance"
        "id": "pod-kill.instance-835462a6-e316-11e6-acc0-96d5adb80fda",
        "id": "pod-kill.instance-8353ed75-e316-11e6-acc0-96d5adb80fda",
        "id": "pod-kill.instance-83530314-e316-11e6-acc0-96d5adb80fda",

Johanness-MacBook-Pro:cli junterstein$ dcos marathon pod kill pod-kill pod-kill.instance-835462a6-e316-11e6-acc0-96d5adb80fda

Johanness-MacBook-Pro:cli junterstein$ dcos marathon pod list --json > tmp.json && cat tmp.json | grep "pod-kill.instance"
        "id": "pod-kill.instance-8353ed75-e316-11e6-acc0-96d5adb80fda",
        "id": "pod-kill.instance-83530314-e316-11e6-acc0-96d5adb80fda",
        "id": "pod-kill.instance-d6b99147-e316-11e6-acc0-96d5adb80fda",
```

When I do a `dcos marathon pod kill $podId $instanceId` the instance will be killed.
