### ISSUE TITLE
A button to stop the current deployment

### ISSUE THREAD

**Issue by leventov** [mesosphere/marathon#5003]
It would be nice if there is a way and a button on an application page to stop the current deployment.

Currently there is a hacky way to do this by scaling a deploying app and then click "Stop current deployment and scale".

**Comment by janisz** [comment]
There was this option in UI although it was removed by https://github.com/mesosphere/marathon/issues/3692 Stop deployment is dangerous as described in https://github.com/mesosphere/marathon/issues/4046 I think this functionality is now deprecated and will be replaced soon https://github.com/mesosphere/marathon/issues/3035#issuecomment-273335378

**Comment by aquamatthias** [comment]
@leventov We had a stop button in the past. This operation is dangerous and can result in loss of data and tasks. We decided to hide this functionality in the UI. We will remove it in API as well.
