### ISSUE TITLE
Marathon should serve requests to system endpoints (/ping, /metrics) without waiting for consistent leadership

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#5005]
Currently all requests have to pass the LeaderProxyFilter.
In situations without a leader, or a leader was elected but not started successfully, Marathon should still serve those requests on every instance.

Background:
Even when elected as leader, Marathon responds to requests with a 503 while processing migration. Since `/ping` is likely to be used for health checks, Marathon should serve those requests even when not leader, and while it's processing migration. Otherwise Marathon-onMarathon instances might be killed due to failing health checks.

**Comment by timcharper** [comment]
Set severe and milestone 1.4 per communication with @meichstedt ; this needs to be back ported to 1.1

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2405. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
