### ISSUE TITLE
Better insights in the log during a migration

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#5006]
When Marathon is performing a Migration, it logs to the log file:
- if the Migration starts
- if the Migration ends
More insights into that process would help a lot.

Especially in big/long migrations, Marathon appears to be "stuck", but is not.

**Comment by meln1k** [comment]
Hi @aquamatthias !

In this [PR](https://github.com/mesosphere/marathon/pull/5034) I implemented periodic logging if a migration step is a long-running operation.

Suggestions/feedback is highly appreciated.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2520. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
