### ISSUE TITLE
Marathon does not support container_path to be absolute path for external volumes for Mesos containers

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#5008]
DCOS-13418

Mesos does support that. If a container image is specified for Mesos container, container_path of an external volume can be absolute. If container image is not specified, the container_path can be absolute as well, but will fail if host filesystem does not have the mount point.

This is the test I performed in the soak cluster:

```
Jies-MacBook-Pro:soak jie$ dcos marathon app add < ~/workspace/tmp/app.json
Error while fetching [https://soak.mesosphere.com/service/marathon/v2/apps]: HTTP 422: {"message":"Object is not valid","details":[{"path":"/container/volumes(0)/containerPath","errors":["must fully match regular expression '^[^/]*$'"]}]}
Jies-MacBook-Pro:soak jie$ cat ~/workspace/tmp/app.json
{
  "id": "/unified-containerizer/evol",
  "cpus": 0.001,
  "instances": 1,
  "mem": 128,
  "container": {
    "type": "MESOS",
    "docker": {
      "image": "alpine"
    },
    "volumes": [
      {
        "containerPath": "/pv",
        "external": {
          "name": "jieucrvolume",
          "provider": "dvdi",
          "options": {
            "dvdi/driver": "rexray"
          }
        },
        "mode": "RW"
      }
    ]
  },
  "cmd": "echo \"`date`\" >> /pv/file",
  "volumes": [
    {
      "containerPath": "/pv",
      "external": {
        "name": "jieucrvolume",
        "provider": "dvdi",
        "options": {
          "dvdi/driver": "rexray"
        }
      },
      "mode": "RW"
    }
  ]
}
```

**Comment by marcomonaco** [comment]
Comment from @Gilbert88:

I believe the validation to prevent the absolute container path for the case of container without container image specified (no rootfs). But since the support of Unified Containerizer, we allow volumes with absolute container path for containers not sharing the host's root filesystem. Please see this table for absolute/relative container path semantic in Mesos:
https://github.com/apache/mesos/blob/master/docs/docker-volume.md#enabling-frameworks-to-use-docker-volumes

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1684. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
