### ISSUE TITLE
[Design Doc] Jobs in Marathon

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#5009]

**Comment by farra** [comment]
Will Marathon support Jobs as part of Groups such that with a single Marathon application definition could include a group of both jobs and apps that have dependencies between them? 

Would love to see the design doc when it's available!

**Comment by jasongilanfarr** [comment]
We are still doing a lot of internal planning right now and plan to send
something out with the general 1.5 plan relatively soon.

The TL;DR is that an application (and eventually) pod can have a schedule
associated with it, either "Continuous", "On a Cron Schedule", or "Run on
Demand". We likely won't support any form of dependencies/workflows in the
initial implementation.

**Comment by farra** [comment]
Even simple dependencies would allow this feature to effectively serve the role as Kubernetes' Init Containers: https://kubernetes.io/docs/concepts/abstractions/init-containers/

I'm looking for a similar feature in which I may want one or more jobs to run prior to launching a marathon app. These jobs should run once and should not be scaled with the marathon app.
