### ISSUE TITLE
[Design Doc] Managed Services

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#5011]

**Comment by timcharper** [comment]
work has been done but I am currently focusing on 1.4 tasks before resuming work on it per priority discussions

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2462. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
