### ISSUE TITLE
[Design Doc] CI and automation release process

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#5015]

**Comment by kensipe** [comment]
working doc:  https://docs.google.com/document/d/1ku79VcZssRzkFqjjrTdF_UsFZdwC1uvBvRB37eLsQTQ/edit#heading=h.x8xy9e31iky7

design doc:
https://docs.google.com/document/d/1sUv3KUHgLM2wB3QxLVE2Qv1qe7lBRXClgZJkpJAjSxE/edit#heading=h.td1p02in4kck
