### ISSUE TITLE
Weird error when starting an invalid pod

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#5016]
DCOS-13434

I see the following error

![image-2017-01-25-13-55-03-539](https://cloud.githubusercontent.com/assets/19775099/22296875/d19d0540-e31b-11e6-9b6e-602473cdcbb4.png)

when I try to submit this (obviously wrong) pod definition, marathon actually tries to start it. Is this expected behaviour or some checks needs to be added?

```
{
  "id": "/",
  "containers": [
    {
      "name": "container-1",
      "resources": {
        "cpus": 1,
        "mem": 128
      }
    }
  ],
  "scaling": {
    "kind": "fixed",
    "instances": 1
  },
  "networks": [
    {
      "mode": "host"
    }
  ]
}
```

**Comment by aquamatthias** [comment]
We need to check for an non empty id.
https://phabricator.mesosphere.com/D447

**Comment by unterstein** [comment]
But id `/` is quite cool ;-)
