### ISSUE TITLE
Consider batching offers as a `Source` to allow expressing preferences for offer matching

### ISSUE THREAD

**Issue by jmlvanre** [mesosphere/marathon#5017]
Today the offer processor streams each individual offer to the offer matchers. This does not allow us to express any preference between offer for matching. 

An example of a preference would be: "Offer A will be unavailable in 5 minutes, Offer B has no planned unavailability, prefer to launch on Offer B". Given today's offer processing system if Offer A arrives first, it will get matched first.

@jasongilanfarr pointed out that we can use the `Source` concept to batch the offers for some configurable amount of time (for example 500 ms) allowing us to then sort that batch before sending it through the offer matching process. An initial sort would be by the time delta between `now` and `unavailability.start` (If unavailability is set).

Aurora has a similar concept. It collects the offers and has an ordering of their maintenance concept (expressed as enums). The code can be found [here](https://github.com/apache/aurora/blob/06a221fda9d4153f8a1162e37ed1036c3291572b/src/main/java/org/apache/aurora/scheduler/offers/OfferManager.java#L277)

**Comment by janisz** [comment]
Related to : https://github.com/mesosphere/marathon/issues/4653

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4112. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
