### ISSUE TITLE
GroupsResourceTest might be unstable

### ISSUE THREAD

**Issue by jeschkies** [mesosphere/marathon#5022]
https://jenkins.mesosphere.com/service/jenkins/job/public-test-marathon-phabricator/1092/testReport/junit/mesosphere.marathon.api.v2/GroupsResourceTest/access_without_authorization_is_denied_if_the_resource_exists/

**Comment by aquamatthias** [comment]
Patch is here: https://phabricator.mesosphere.com/D483
