### ISSUE TITLE
Fix Known Failing Integration Tests in releases/1.3

### ISSUE THREAD

**Issue by jeschkies** [mesosphere/marathon#5028]
So far we ignore if the integration test stage fails in [releases/1.3](https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/marathon-pipelines/job/releases%252F1.3/). Let's fix or ignore the tests so that the pipeline can report on broken builds.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4191. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
