### ISSUE TITLE
Run unit and integration tests in parallel on two different nodes.

### ISSUE THREAD

**Issue by jeschkies** [mesosphere/marathon#5030]
We can speed up the CI by running the unit and integration tests in parallel on two different nodes.

**Comment by jasongilanfarr** [comment]
I suspect this will have almost no noticeable impact. unit tests (once you've compiled) take 36 seconds. Spinning up another node and compiling again to run the tests will likely enter a queuing delay > 2 min.

This is not worth the effort.

**Comment by jeschkies** [comment]
Unit test take > 4 Minutes on Jenkins. Provisioning and copying everything might eat up the gain.

**Comment by jasongilanfarr** [comment]
This isn't true: https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/public-test-marathon-phabricator/1107/consoleText

test (which in this particular job includes compile etc) has the tests completing in just 28 seconds.

`
Run completed in 27 seconds, 192 milliseconds.
Total number of tests run: 2767
Suites: completed 239, aborted 0
Tests: succeeded 2767, failed 0, canceled 0, ignored 1, pending 2
All tests passed.
[info] ScalaTest
[info] Run completed in 27 seconds, 192 milliseconds.
[info] Total number of tests run: 2767
[info] Suites: completed 239, aborted 0
[info] Tests: succeeded 2767, failed 0, canceled 0, ignored 1, pending 2
[info] All tests passed.
[info] Passed: Total 2767, Failed 0, Errors 0, Passed 2767, Ignored 1, Pending 2
[success] Total time: 269 s, completed Jan 27, 2017 3:59:49 PM
`

**Comment by jasongilanfarr** [comment]
I think a higher priority item would be adapting my original prototype of a phabricator jenkins pipeline and maybe adding support for things like "apply the review stack, apply vs master, apply vs named branch (e.g. for release cherry-picks) where the diff has some encoding of "this actually targets releases/1.4"

**Comment by jeschkies** [comment]
Sure. This is not on my priority list. I was hoping that it is a low hanging fruit but it's not. Hm, how come the unit test stage takes more than 4 minutes? I wonder what the overhead is.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4691. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
