### ISSUE TITLE
Create Marathon 1.3.9

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#5035]

**Comment by marcomonaco** [comment]
Please include https://github.com/mesosphere/marathon/issues/5024

**Comment by janisz** [comment]
Can we add https://github.com/mesosphere/marathon/pull/4986 I can backport it once it's get merged to master.

**Comment by unterstein** [comment]
Hey @janisz,

unfortunately #4986 didn`t came in 1.3.9 due time constraints. 1.3.9. was released a couple of hours ago. I created #5039 to track the 1.3.10 release, including this ticket.

- Johannes

**Comment by janisz** [comment]
@unterstain No problem, thanks for creating the ticket.
