### ISSUE TITLE
Integrate Marathon on the Soak Cluster

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#5037]
- Pump metrics data to data dog: _no dedicated subtask_
- Create dashboard for Marathon: https://github.com/mesosphere/marathon/issues/5130
- Define TestCases (documented) that we want to run: https://github.com/mesosphere/marathon/issues/5131
- Set up test cases according to test plan: https://github.com/mesosphere/marathon/issues/5132
- Set up data-dog grapsh and monitors: https://github.com/mesosphere/marathon/issues/5133

**Comment by zen-dog** [comment]
Since there are individual tickets for all the points, I'll move this ticket to "Done"
