### ISSUE TITLE
Solve Dependency conflicts of `akka-http` to pass `sbt assembly`

### ISSUE THREAD

**Issue by jeschkies** [mesosphere/marathon#5038]
Apparently we have two version of akk-http as dependencies:
* com.typesafe.akka:akka-http_2.11:10.0.1
* com.typesafe.akka:akka-http-experimental_2.11:2.4.11

The later is a transient dependency of `de.heikoseeberger:akka-http-play-json_2.11:1.10.1`. As far as I can tell `kka-http-play-json` has no 2.11 version for `akka-http` non-experimental. I'd just exclude the experimental version when packing. However, I'd also like to make sure that everything works. So I propose to run the integration tests against the assembly.

**Comment by jasongilanfarr** [comment]
We can safely use akka-http and exclude the experimental one as they have compatible ABIs.

**Comment by jeschkies** [comment]
Ok.

**Comment by jeschkies** [comment]
In review see https://phabricator.mesosphere.com/D467
