### ISSUE TITLE
Backup & Restore from zk state

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#5043]
[Subtasks](https://github.com/mesosphere/marathon/issues?utf8=✓&q=%235043%20in%3Atitle%20)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1739. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
