### ISSUE TITLE
Broken link to Marathon-LB documentation under mesosphere.github.io/marathon/

### ISSUE THREAD

**Issue by ppar** [mesosphere/marathon#5045]
There's a broken link in the Marathon documentation under mesosphere.github.io.

On this page:

https://mesosphere.github.io/marathon/docs/service-discovery-load-balancing.html

the end of the phrase:

> For more information, see the Marathon-lb repository or refer to the __marathon-lb documentation on the Mesosphere site.__

links to:

https://docs.mesosphere.com/administration/service-discovery-with-marathon-lb/service-discovery-and-load-balancing-with-marathon-lb/

which redirects (eventually) to:

https://docs.mesosphere.com/1.8/usage/service-discovery-with-marathon-lbhttps://test-mesosphere-documentation.pantheonsite.io/usage/service-discovery/marathon-lb/

which is a broken link (or actually two). Removing the first of the two catenated URLs, the address:

https://test-mesosphere-documentation.pantheonsite.io/usage/service-discovery/marathon-lb/

asks for basic authentication and doesn't look like it's meant to be public. Finally, combining those two addresses into:

https://docs.mesosphere.com/1.8/usage/service-discovery/marathon-lb/

gives something that looks like Marathon LB documentation, so maybe the page should link to that one instead.

**Comment by sascala** [comment]
Fixed: https://github.com/mesosphere/marathon/commit/5612a90451109a573d115c234cad98d227f37d45
