### ISSUE TITLE
fix gce launcher list issues for clean but not purged clusters

### ISSUE THREAD

**Issue by kensipe** [mesosphere/marathon#5055]

**Comment by kensipe** [comment]
clean doesn't remove gce templates and the templates are used for `cluster list`.  
We are looking to query the master with best effort.   None or value based on timeout.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1789. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
