### ISSUE TITLE
Clean Tech Debt Marathon SI tests

### ISSUE THREAD

**Issue by kensipe** [mesosphere/marathon#5058]

**Comment by kensipe** [comment]
hashmap of errors that are in loops,
add errors with counts at the end of loop

**Comment by kensipe** [comment]
parameterized py tests
refactor the creation of 'ScaleTest'
refactor the call for instance, vs group
use defaultmap from collection for stats.

**Comment by kensipe** [comment]
consolidate the SI tests and make green again

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1736. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
