### ISSUE TITLE
#5063 Create tar with sbt for snapshot packages

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#5065]

**Comment by jeschkies** [comment]
Duplicates https://github.com/mesosphere/marathon/issues/5068 since we create packages only once.

**Comment by jeschkies** [comment]
Also closed by https://github.com/mesosphere/marathon/commit/300bfe4e44dde170abc5363d5d1ca0ab9d2742d.

**Comment by jeschkies** [comment]
Also closed by https://github.com/mesosphere/marathon/commit/300bfe4e44dde170abc5363d5d1ca0ab9d2742d1.
