### ISSUE TITLE
#5063 Upload Snapshot Packages to S3

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#5066]
In TeamCity the step is

```bash
set -x
IMAGE=$(ls marathon-*-SNAPSHOT.tgz | tail -n 1)
shasum $IMAGE
aws s3 cp \
  --acl public-read \
  --region %S3_REGION% \
  $IMAGE \
  s3://%S3_BUCKET%/marathon/snaps/%BUILD_ID%/marathon.tgz
```

**Comment by jeschkies** [comment]
I wonder how this relates to https://github.com/mesosphere/marathon/issues/5069.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2323. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
