### ISSUE TITLE
Migrate sbt assembly to sbt native packager (for rpm and deb artifacts) for tagged packages

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#5067]

**Comment by jeschkies** [comment]
This would ease the creation of our tar, deb and rpm packages. However, it would also change our start scripts.

**Comment by jeschkies** [comment]
Looking at the make targets for the Marathon packages in [marathon-pkg](https://github.com/mesosphere/marathon-pkg/blob/master/Makefile) I don't think it's trivial to ensure the the packages built by sbt native packager do not brake the setup.

**Comment by jeschkies** [comment]
I'd like to setup a test environment to deb and rpm packages.

**Comment by jeschkies** [comment]
Having looked at the logic we have right now, migrating to sbt native package is out of scope for now. We don't have a reliable way to verify that the packages are equivalent.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2052. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
