### ISSUE TITLE
#5062 Create build docker image in pipeline

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#5070]
*Note*: This task does not include publishing the image.

**Comment by jeschkies** [comment]
The task is done when I push a commit to master which triggers the pipeline. After the `Test Integration` stage a `Assemble Jar` followed `Build Docker Image` and `Archive Binaries` stages.

**Comment by jeschkies** [comment]
The Docker image build should be adapted. It should just copied the assembled jar. We may want to use the [sbt native packager](http://www.scala-sbt.org/sbt-native-packager/).

**Comment by jeschkies** [comment]
Looking at the [introduction](http://www.scala-sbt.org/sbt-native-packager/introduction.html) of the native package I think migration may be out of scope for this task. We would change some behaviour. It might be ok for Docker images. For rpm and deb packages it will be different.
