### ISSUE TITLE
#5063 Upload Release Docker Image to Docker Hub

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#5071]
Is blocked by https://github.com/mesosphere/marathon/issues/5070.

As a Marathon developer, I want a Docker image for each commit in our Docker repository to master so that
* I can sent it to a customer if needed
* I can test it ad-hoc
* the release can just pick the image for the release commit

## Details
Each build is tagged with the commit hash. This way it is easy to pull an image for a specific commit. A release would not need to rebuild the image and can just retag the image:
```bash
docker tag marathon:<commit> marathon:1.x.x
```

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1972. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
