### ISSUE TITLE
UI: Applications/instances view needs 'sort by host' and 'show all'

### ISSUE THREAD

**Issue by lhoss** [mesosphere/marathon#5072]
Simple example use-case, which is a *big* pain to debug right now:
Deploy any app with 20+ instances (>3 'pages' currently) in marathon (for ex. accumulo-tserver in our case), and find out  on which hosts marathon could not deploy an instance due to some unfulfilled resources.
Marathon just giving me the infos:  `Waiting (20 of 22 instances)` / `2 Unscheduled`
( ps: *looking fwd* to have insights about those `Insufficient resources`logs in the UI!) )

There are 2 major usability issues here:
* There's no sort by host (as the main column attribute is the 'ID'  and thus clicking it  sorts by ID,  though I'm sure most people could better use a sort by ID.. we need both!)
* The page size is hardcoded to 8 (!) entries. 
 * I'ld suggest a simple 'show all' checkbox or button (alternatively a way to choose (much) larger page-sizes)

Alternatively (for this usecase) it would be very helpful to be able to filter/show a list of hosts that would be expected to host the * Unscheduled* instances  (but this would be too complex to solve in general ... here it's enough to actually show the `Insufficient resources` infos, in a structured way, on which host, what resources could not be fulfilled)

Related issue: https://github.com/mesosphere/marathon/issues/3000
( that also mentioned the 'sort by host' would be nice )

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2663. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
