### ISSUE TITLE
How is the event bus streaming data ?

### ISSUE THREAD

**Issue by Jbrownstone** [mesosphere/marathon#5073]
Hi,

i'm trying to monitor the Marathon Event Bus, in order to write a script which deploy my docker containers one by one, but while waiting for the previous one to finish before launching the next one.

I managed to connect to the event bus using PyCurl library, and am having some strange behaviours with how i receive datas from the bus.

Often while monitoring i end up with only a part of the data : {}, and not the totality of it, and i can only get the rest of the data by triggering a new event (which will also have event's data truncated until i trigger a new event).

I did everything on my end to try to figure out if i didn't missed something, like if my handler is only triggered when the buffer has a sufficient amount of data, but didn't manage to get anything out of configuration, so i was wondering if the bus really streams content or if it waits until it has enough information buffered before sending it to the client.

I sincerely hope i've been clear, and thank you in advance for your response, i'll add anything i forgot to include if you need any further information.

**Comment by tobilg** [comment]
Not a Python expert, but you're aware that the Event Bus is using SSE? There are some special client libraries for Python, like https://github.com/mpetazzoni/sseclient

Maybe you can try those clients?

**Comment by Jbrownstone** [comment]
Thanks for responding.

I did try this client, and it's the same deal, it does however help processing data tho, so thanks.
But still, i still have to trigger a new event in order to get the “deployment_success" i should get after deployment_step_success

**Comment by aquamatthias** [comment]
@Jbrownstone `/v2/events` uses SSE to stream events. The events are pushed, there is no need to "trigger an event". Please note: `deployment_success` is send if the deployment is finished, where `deployment_step_success` is send if one step is finished. If your deployment contains multiple steps, than you will not see `deployment_success` immediately after `deployment_step_success`.

An easy way to attach to the stream is curl:
```
curl :8080/v2/events -H "Accept:text/event-stream"
```
