### ISSUE TITLE
docker --cpus option in docker 1.13

### ISSUE THREAD

**Issue by yogeshnath** [mesosphere/marathon#5074]
current marathon "cpus" option relates to docker "cpu-shares" option.

When do we expect the new docker "--cpus" option to be available in Marathon.

**Comment by janisz** [comment]
This needs to be done by Mesos https://github.com/apache/mesos/blob/1.0.2/src/docker/docker.cpp#L523

**Comment by aquamatthias** [comment]
This has to be done on the mesos side. Will close this ticket here.
