### ISSUE TITLE
GCE launcher - test DIND

### ISSUE THREAD

**Issue by kensipe** [mesosphere/marathon#5075]

**Comment by kensipe** [comment]
Failed using alpine... closer with ubuntu.    able to launcher vms but unable to connect to the docker process (blocking the extraction of the dcos installer)

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1844. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
