### ISSUE TITLE
UNLIKE constraint seems to be required

### ISSUE THREAD

**Issue by mlunoe** [mesosphere/marathon#5077]
Marathon version: 1.4.0-RC5

When I submit this app config:
```js
{
  "id": "/mlunoe/constraints",
  "cmd": "sleep 9999",
  "instances": 1,
  "cpus": 0.1,
  "constraints": [
    [
      "five",
      "UNLIKE"
    ]
  ]
}
```

I receive this API response:
```js
{
  "message": "Object is not valid",
  "details": [
    {
      "path": "/constraints",
      "errors": ["A regular expression value must be provided"]
    }
  ]
}
```

**Comment by janisz** [comment]
Regexp for like and unlike are required see docs https://github.com/mesosphere/marathon/blob/v1.4.0-RC5/docs/docs/constraints.md#unlike-operator

**Comment by mlunoe** [comment]
It doesn't say that for UNLIKE though, and the raml files do not specify regexes for these: https://github.com/mesosphere/marathon/blob/master/docs/docs/rest-api/public/api/v2/types/constraint.raml#L20

**Comment by janisz** [comment]
OK, now it's clear where is the problem. I thought it was API related not docs. Probably it's missing from the beginning since docs for constrains weren't updated recently.

**Comment by mlunoe** [comment]
Well, the docs doesn't specify it `UNLIKE` to be required either. Only `LIKE` and `MAX_PER`: ![](https://cl.ly/0P3V1k3x1u3v/Image%202017-02-01%20at%2016.20.01.png)

**Comment by jasongilanfarr** [comment]
We don't really have a way to express that outside of a comment in the RAML. I agree there should be a comment though.

**Comment by mlunoe** [comment]
It seems that `CLUSTER` is required too. If I submit this:
```js
{
  "id": "/mlunoe/constraints",
  "instances": 1,
  "cpus": 0.1,
  "cmd": "sleep 9999",
  "constraints": [
    [
      "three",
      "CLUSTER"
    ]
  ]
}
```

I get this response:
```js
{
  "message": "Object is not valid",
  "details": [
    {
      "path": "/constraints",
      "errors":["Missing value"]
    }
  ]
}
```

**Comment by aquamatthias** [comment]
@sascala 
Our documentation does not say explicitly if a value is optional or mandatory for constraints.
See: https://mesosphere.github.io/marathon/docs/constraints.html

Can you add a sentence to each?

Value is mandatory for:
- LIKE
- UNLIKE
- CLUSTER
- MAX_PER

Value is optional for
- UNIQUE
- GROUP_BY

**Comment by sascala** [comment]
@aquamatthias https://github.com/mesosphere/marathon/pull/5199

**Comment by mlunoe** [comment]
Are we sure about the optional value for `UNIQUE`? 

In Marathon version: 1.4.0-RC9, when I submitted this app config:
```js
{
  "id": "/mlunoe/constraints",
  "cmd": "sleep 9999",
  "instances": 1,
  "cpus": 0.1,
  "constraints": [
    [
      "five",
      "UNIQUE"
      "foo"
    ]
  ]
}
```
I received this API response:
```js
{
  "message": "Object is not valid",
  "details": [
    {
      "path": "/constraints",
      "errors": [
        "Value specified but not used"
      ]
    }
  ]
}
```

**Comment by sascala** [comment]
https://github.com/mesosphere/marathon/pull/5199

**Comment by mlunoe** [comment]
@sascala: See my comment here: https://github.com/mesosphere/marathon/pull/5199/files#r103363064

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1699. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
