### ISSUE TITLE
On Demand Scale Tests MVP

### ISSUE THREAD

**Issue by jeschkies** [mesosphere/marathon#5085]
As a Marathon developer I would like to run a scale test against a custom cluster **on demand** so that I can generate test results and compare them over time.

## Jenkins Job

* Takes parameters:
  * Marathon URL
  * Meta data
  * Credentials
* Runs all scale test against Marathon URL
* Archives results from CSV on Jenkins
  * Includes meta data
  * Includes error messages

## Limitations

* Does not create a Marathon cluster for user.
* Does not provide any visualization or analytics of results.
* The tests do not install Marathon or make any assumptions of the cluster and the version.

**Comment by kensipe** [comment]
FYI: this test configuration will be limited to scaling up to 2400 tasks

**Comment by kensipe** [comment]
https://phabricator.mesosphere.com/D494

**Comment by kensipe** [comment]
https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/scale/job/marathon-root-scale-pipeline/
