### ISSUE TITLE
ValidationError should be more expressive than "error.pattern"

### ISSUE THREAD

**Issue by jeschkies** [mesosphere/marathon#5093]
We should fill the JSON constraints with more context. E.g. the min length constraint just gives `error.minLenght` but not the actual value.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4173. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
