### ISSUE TITLE
HTTP to HTTPS redirection for marathon service

### ISSUE THREAD

**Issue by butterflyinfly** [mesosphere/marathon#5095]
Hello to All,

I've got a question about redirection of marathon traffic from http to https. 

I've enabled ssl in marathon by providing --ssl_keystore_path and --ssl_keystore_password flags, but didn't provide --disable_http, because currently there are a lot of places in code that talk to marathon via http url and we can't change it now. So I would like to leave http and https working at the same time, but enable auto-redirect all requests which were made via http to https, so the clients will be automatically redirect to use the HTTPS and get connected using encrypted channel.

Could you please suggest how this can be configured or just point me to documentation where it's described? 

Thanks.

**Comment by janisz** [comment]
Marathon does not support redirect HTTP o HTTPS. You can achieve it by setting up small server that will listen on HTTP and redirect all request to HTTPS.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4640. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
