### ISSUE TITLE
Create an AMI with all Dependencies for Jenkins Nodes

### ISSUE THREAD

**Issue by jeschkies** [mesosphere/marathon#5096]
The sbt builds on Jenkins have to download all dependencies each time. We could cache them in the AMI and update the AMI once in a while.

Change the packer script so that it adds missing steps from https://wiki.mesosphere.com/display/MARATHON/Provision+New+AMI+for+Jenkins+Node.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2451. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
