### ISSUE TITLE
Plot Scale Test Results

### ISSUE THREAD

**Issue by kensipe** [mesosphere/marathon#5103]

**Comment by kensipe** [comment]
need to look at: https://wiki.jenkins-ci.org/display/JENKINS/Plot+Plugin

**Comment by kensipe** [comment]
to add plugin into jenkins we need it 
1) tested on our own jenkins cluster
2) file a jira for velocity

https://mesosphere.slack.com/archives/velocity/p1486426538004862

**Comment by jdef** [comment]
alternative graphing package:
http://www.statmethods.net/advgraphs/ggplot2.html

**Comment by kensipe** [comment]
Gnuplot
