### ISSUE TITLE
extract dcos label knowledge from AppDefinition into a validation plugin

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#5106]
* https://github.com/mesosphere/marathon/blob/0d1d9514c12fec37c9072ed0ba41233afa93c39f/src/main/scala/mesosphere/marathon/state/AppDefinition.scala#L508-L523

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2496. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
