### ISSUE TITLE
Release Marathon v1.3.10

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#5109]
Cherry picks:

- Improve performance of dependency graph computations https://phabricator.mesosphere.com/D476
- Performance improvements in 1.1 branch: 334734390f0c22ea10e5b9746f5430168dcd43cb (see also https://phabricator.mesosphere.com/D481)

**Comment by janisz** [comment]
Duplicates: https://github.com/mesosphere/marathon/issues/5039

**Comment by timcharper** [comment]
Thanks Janis!

**Comment by unterstein** [comment]
PRs to pick:
#4986
#4978

**Comment by unterstein** [comment]
Phabricator reviews Tim mentioned matches this GH PRs:
#5107
#5094

**Comment by janisz** [comment]
Added one PR that is using `MarathonEvent#jsonString` in http callbacks https://github.com/mesosphere/marathon/pull/5114

**Comment by unterstein** [comment]
- [ ] #5114 
- [ ] 5124

**Comment by jdef** [comment]
why is this milestone set to 1.4? shouldn't we have a 1.3?
