### ISSUE TITLE
external volumes extra options

### ISSUE THREAD

**Issue by drajen** [mesosphere/marathon#5125]
I'm using the experimental external_volumes feature with a Docker Volume driver. We've modified our driver to allow a 'null' Options map to do on-the-fly provisioning but there seems to be something quirky how the external volumes code validates extra options. I've been reading the docs here: https://mesosphere.github.io/marathon/docs/external-volumes.html and from what I can tell, this should work:
```json
"external": {
    "name": "volname",
    "provider": "dvdi",
    "options": { 
        "dvdi/driver": "nimble",
        "sizeInGiB": "4",
        "description": "Apache Mesos"
    }
}
```
**Note:**  sizeInGiB and description are "nimble" driver specific options.

Yet, this is what I get back:
```bash
curl -X POST http://localhost:8080/v2/apps -d @app.json -H "Content-type: application/json"
{"message":"Object is not valid","details":[{"path":"/container/volumes(0)/external/options","errors":["must only contain dvdi/driver"]},{"path":"/container/volumes(0)/external/optionskeys","errors":["must match regular expression '^[a-z0-9](?:[-a-z0-9]*[a-z0-9])?/[A-Za-z0-9](?:[-A-Za-z0-9\\._:]*[A-Za-z0-9])?$'"]}]}
```
This is marathon 1.3.9 on CentOS using the official repos.

**Comment by jdef** [comment]
can you try prefixing your custom options names with "dvdi/"?

**Comment by jdef** [comment]
@sascala i suspect that we've under-documented how to specify additional driver options for external volumes

**Comment by drajen** [comment]
Thanks @jdef, I think I've tried something similar before, anyhow, I now have a volume section like this:
```json
    "volumes": [
      {
        "containerPath": "/volpath",
        "external": {
          "name": "volname5",
          "provider": "dvdi",
          "options": {
	    "dvdi/sizeInGiB": "4",
	    "dvdi/description": "Apache Mesos",
            "dvdi/driver": "nimble"
	  }
        },
        "mode": "RW"
      }
    ],
```
Which produces:
```bash
curl -X POST http://localhost:8080/v2/apps -d @app.json -H "Content-type: application/json"
{"message":"Object is not valid","details":[{"path":"/container/volumes(0)/external/options","errors":["must only contain dvdi/driver"]}]}
```

**Comment by jdef** [comment]
Ah, ok. You must be using the docker containerizer: the implementation of
that containerizer on the Mesos side doesn't support a variety of options.

Do you have the option of running the mesos containerizer instead
(container.type: MESOS)? The mesos containerizer can leverage docker
images, and the DVDI isolator used by the mesos containerizer should
support the additional options you're trying to use.

**Comment by drajen** [comment]
I've copied the example verbatim from: https://mesosphere.github.io/marathon/docs/external-volumes.html

```json
{
  "id": "hello",
  "instances": 1,
  "cpus": 0.1,
  "mem": 32,
  "cmd": "/usr/bin/tail -f /dev/null",
  "container": {
    "type": "MESOS",
    "volumes": [
      {
        "containerPath": "test-rexray-volume",
        "external": {
          "size": 100,
          "name": "my-test-vol",
          "provider": "dvdi",
          "options": {
            "dvdi/sizeInGiB": "4",
            "dvdi/description": "Apache Mesos",
            "dvdi/driver": "nimble"
          }
        },
        "mode": "RW"
      }
    ]
  },
  "upgradeStrategy": {
    "minimumHealthCapacity": 0,
    "maximumOverCapacity": 0
  }
}
```

```bash
curl -X POST http://localhost:8080/v2/apps -d @vol.json -H "Content-type: application/json"
{"id":"/hello","cmd":"/usr/bin/tail -f /dev/null","args":null,"user":null,"env":{},"instances":1,"cpus":0.1,"mem":32,"disk":0,"gpus":0,"executor":"","constraints":[],"uris":[],"fetch":[],"storeUrls":[],"backoffSeconds":1,"backoffFactor":1.15,"maxLaunchDelaySeconds":3600,"container":{"type":"MESOS","volumes":[{"containerPath":"test-rexray-volume","mode":"RW","external":{"size":100,"name":"my-test-vol","provider":"dvdi","options":{"dvdi/sizeInGiB":"4","dvdi/description":"Apache Mesos","dvdi/driver":"nimble"}}}]},"healthChecks":[],"readinessChecks":[],"dependencies":[],"upgradeStrategy":{"minimumHealthCapacity":0,"maximumOverCapacity":0},"labels":{},"acceptedResourceRoles":null,"ipAddress":null,"version":"2017-02-08T18:09:15.409Z","residency":null,"secrets":{},"taskKillGracePeriodSeconds":null,"ports":[0],"portDefinitions":[{"port":0,"protocol":"tcp","labels":{}}],"requirePorts":false,"tasksStaged":0,"tasksRunning":0,"tasksHealthy":0,"tasksUnhealthy":0,"deployments":[{"id":"6de25433-7e1e-43ba-8257-30b542a314fd"}],"tasks":[]}
```

The job will be stuck 'Delayed'. Looking at the logs:
```txt
==> /var/log/mesos/mesos-slave.mesos-emerald.invalid-user.log.WARNING.20170208-174337.1325 <==
E0208 18:10:10.687224  1536 slave.cpp:4423] Container 'a472a747-374f-4161-ad36-543c039c3737' for executor 'hello.d472ed15-ee29-11e6-b037-02422ddc1e0f' of framework bbbb643b-ec40-45a7-af63-e5d64aea8fb9-0000 failed to start: Volumes in ContainerInfo is not supported
```

**Comment by jdef** [comment]
Ah, ok. I think we're getting closer. What isolators do you have enabled for your Mesos agents? I suspect you're using the `posix` filesystem isolator instead of the `linux` one.

https://github.com/apache/mesos/blob/9fc2901d23659ca0912ad42fb79828b1a8ab9691/src/slave/containerizer/mesos/isolators/filesystem/posix.cpp#L95

**Comment by jdef** [comment]
FWIW on my development machine, my agent uses this:
```
--isolation=cgroups/cpu,cgroups/mem,filesystem/linux
```

**Comment by drajen** [comment]
I started my agent with those params and the container now starts properly. However, I can't see any attempts of actually created nor mounting the volume I specified.

If I inspect the application in the UI it says it has an external volume:
```json
{
  "type": "MESOS",
  "volumes": [
    {
      "containerPath": "test-rexray-volume",
      "mode": "RW",
      "external": {
        "size": 100,
        "name": "my-test-vol",
        "provider": "dvdi",
        "options": {
          "dvdi/sizeInGiB": "4",
          "dvdi/description": "Apache Mesos",
          "dvdi/driver": "nimble"
        }
      }
    }
  ]
}
```

**Comment by jdef** [comment]
sorry, one more isolator: `docker/volume` (to enable DVDI support). you'll also need `dvdcli` in your path (https://github.com/codedellemc/dvdcli)

**Comment by drajen** [comment]
Thanks @jdef, much appreciated! It's up and running now. I don't know much about the mesos isolator but I can now read/write files on the volume from inside the sandbox.

It does however not solve my initial ask on how to provide external volume options to the docker containerizer. Will this issue serve as a bug report for that ask?

**Comment by jdef** [comment]
additional options: underlying mesos issue is the root cause,
https://issues.apache.org/jira/browse/MESOS-6384

**Comment by sascala** [comment]
@jdef -- Am I on the right track to look [here](https://github.com/mesosphere/marathon/blob/24c9deadb660866b5df2a943128bdc5f99027c26/src/test/scala/mesosphere/marathon/core/externalvolume/impl/providers/DVDIProviderVolumeValidationTest.scala) for the complete rules on specifying additional driver options for external volumes?

**Comment by jdef** [comment]
that's a unit test that validates syntax, but not the entire set of
possible options. it's possible to specify key/value option pairs, the
values for which Marathon will never attempt to interpret. There are
**some** validation rules for common rexray parameters in Marathon (only to
be helpful) but DVDI doesn't actually require that you use rexray at all.

What's the specific task you're attempting to complete?

**Comment by sascala** [comment]
Way back at the top you wrote, "@sascala i suspect that we've under-documented how to specify additional driver options for external volumes", so I'm trying to be more thorough.

After that I was going to ask if anything else in the conversation that followed needed to be documented. It looks like users need `dvdcli` installed and that the app definition is missing the `docker/volume` parameter?

**Comment by jdef** [comment]
@sascala there's a couple of places where configuration is important:
* mesos agent
  * configuration: `--isolation` needs to include `filesystem/linux` and `docker/volume`
  * this allows apps using `MESOS` container types to use DVDI
  * in addition, the `dvdcli` binary must be installed (on the agent)
* in app definition JSON, volume option names must have a particular format:
  * syntax is `{provider-name}/{option-name}`
  * if `provider` is `dvdi` then an option name (for some fake docker driver) might be `dvdi/fakeoption`
  * different docker volume drivers have different options, we cannot hope to enumerate all the possibilities in our documentation

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1693. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
