### ISSUE TITLE
additionalProperties should be false for most pod API objects

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#5127]
Use case: Alice creates a pod via JSON. Her JSON is flawed in that it defines a field that's not defined for the Marathon pod API. Marathon accepts the JSON as-is and run the pod. Alice queries Marathon for the pod JSON and it differs from her original. She's confused.

Alternates:
She defines a field XYZ that's required in the wrong place. Marathon reports an error that field XYZ is undefined. She's confused.

I'm strongly questioning the conclusion that we came to, when developing the pod API, that `additionalProperties` would be unset (`true` by default). This causes confusion when Marathon blindly accepts JSON with fields that don't actually map to the Marathon API.

I'm flagging this as a blocker for 1.4 until we discuss further.

**Comment by jdef** [comment]
For example, Marathon accepts this pod JSON (I curl'd it directly to the server):
```
{
  "boo": "hoo",
  "id": "/nginx",
  "containers": [
    {
      "name": "container-1",
      "resources": { "cpus": 1, "mem": 128 },
      "endpoints": [
        {
          "name": "http",
          "containerPort": 80,
          "hostPort": 0,
          "protocol": [ "tcp" ],
          "labels": { "VIP_0": "1.1.1.1:80" }
        }
      ],
      "image": { "id": "nginx", "kind": "DOCKER" }
    }
  ],
  "scaling": { "kind": "fixed", "instances": 1 },
  "networks": [ { "name": "dcos", "mode": "container" } ]
}
```

**Comment by jdef** [comment]
quoting jason, from slack: "we probably _should_ reject additional fields"

**Comment by jdef** [comment]
there's probably a notable doc change that should go along with this as well: it should be clear to users up front that it is an error to specify JSON properties that aren't declared by the API

**Comment by aquamatthias** [comment]
That is correct. The same problem applies to AppDefinitions.
We already scoped this for 1.5.

**Comment by jdef** [comment]
Any reason that we can't enforce this for pods in 1.4? Since we're
introducing pods in 1.4 it would be nice to get right before we actually
release it

**Comment by jdef** [comment]
/cc @kensipe @artemharutyunyan 

this actually just bit US again w/ respect to writing system integration tests. marathon accept invalid pod definitions, so test authors think there's a bug in the system when some accidentally misplaced field is accepted but the system doesn't respond in the way that they're expecting.

there's a distinct difference between the app spec and the pod spec: the app schema specifically advertises `additionalProperties: false` for many fields. the pod spec advertises that for NONE.

it's a valid point that Marathon doesn't enforce `additionalProperties: false` for apps. however, that doesn't provide justification for us to incorrectly specify pods via the new RAML API. publishing the pods API now without `additionalProperties: false` and then adding it later is technically a breaking API change.

PLEASE PLEASE let's address this **now** before we launch 1.4

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1764. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
