### ISSUE TITLE
#5037 Create dashboard for Marathon

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#5130]
Parent: https://github.com/mesosphere/marathon/issues/5037

**Comment by zen-dog** [comment]
Still w.i.p for now.:
https://app.datadoghq.com/screen/152854/marathon-soak-cluster

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2452. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
