### ISSUE TITLE
Launch Cluster with Specific Version and Trigger Scale Test Job

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#5135]
As a Marathon developer I would like the cluster to start with a specific version automatically so that I don’t have to know how to start a cluster.

This job creates a cluster based on the following parameters:
- DC/OS branch or commit id
- Security mode: Strict, Permissive, None
- Number of nodes

The jobs tries to create a cluster with CCM. It does not retry in case of an error but reports it.
The number of nodes has an arbitrary limit of 500 nodes for now. That does not mean we support up to 500 nodes. In this first iterations it is up to the user to investigate why a cluster did not start.

**Comment by kensipe** [comment]
needs:
1. determine the association of dcos branch or commit to a launchable artifact

notes:
may want to launch small cluster and interact with cloud api for scaling
this is AWS only
may use the new dcos-launcher

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1735. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
