### ISSUE TITLE
How to execute Marathon healthchecks with backticks in command

### ISSUE THREAD

**Issue by bbayani** [mesosphere/marathon#5136]
For the heathcheck commands that contain expressions inside `` or $(), the expressions inside $() are being evaluated before docker-exec heathcheck command.

E.g. My heathcheck command was: 

"healthChecks": [
{
"command":
{ "value": "if [ -z '$(ps -e | grep java)' ]; then exit 1; fi" },
"gracePeriodSeconds": 100,
"intervalSeconds": 10,
"maxConsecutiveFailures": 3,
"protocol": "COMMAND",
"timeoutSeconds": 10
}
]

But in spite of a java process running inside the container, the heathcheck kept failing. That was because the expression $(ps -e | grep java) was run on mesos-agent which did not have a java process running.

sh-4.2# ps -e | grep java
No Ouput

sh-4.2# docker exec ContainerID sh -c "echo $(ps -e | grep java)”
No Output

sh-4.2# docker exec ContainerID sh -c "ps -e | grep java”
 5 ?        00:00:00 java

I could work-around in this case by specifying the healthcheck command only as 'ps -e | grep java'. But there are several other cases in which we need healthcheck commands to get evaluated inside docker container and not on mesos-agent.

Is there any known way to achieve the same?

**Comment by jdef** [comment]
related? https://issues.apache.org/jira/browse/MESOS-4812

**Comment by jdef** [comment]
please vote on the above mesos issue to improve visibility

**Comment by bbayani** [comment]
I dont think this issue is with escaping the healthcheck command. Basically, this behavior I am seeing is as per the docker design and as expected. The docker exec command is being run on mesos-agent (in my case containerized mesos-agent) and thus the expressions in $() are evaluated first on mesos-agent and then passed the actual healthcheck command being run inside marathon app. 

I wish to have a way from mesos/marathon probably, so that i can evaluate these expressions in $() inside marathon app. 

E.g. Instead of running the  command as it, they create healthcheck.sh from it. and run 'docker exec ContainerID sh healthcheck.sh' this would enable the expression evaluation inside container.

**Comment by aquamatthias** [comment]
@bbayani You are totally right. The behaviour will be fixed on the Mesos side. See here: https://reviews.apache.org/r/54846/
I will close this ticket here, since there is nothing Marathon can do.

**Comment by bbayani** [comment]
@aquamatthias ok, Thanks.
