### ISSUE TITLE
Marathon overscales apps when updating instances of multiple apps via API

### ISSUE THREAD

**Issue by moonkev** [mesosphere/marathon#5141]
Hi

We have witnessed an issue where when calling the API to simply scale multiple apps using the /v2/apps PUT call, that marathon will often times overscale the apps way past what was requested.  Usually we are running single instances of an app (and are even setting the SINGLE_INSTNACE_APP label).  When we request multiple apps at a time to scale from just 0 to 1, we are seeing that many times these apps will scale to 5 or 6 instances.  Please let me know if you would require any more information.

Thanks
Kevin

**Comment by moonkev** [comment]
Just to add - we have been seeing with all versions up to 1.3.10

**Comment by janisz** [comment]
Could you attach request you sent and logs?

**Comment by aquamatthias** [comment]
@moonkev The default upgrade strategy is `1.0`(see: https://mesosphere.github.io/marathon/docs/rest-api.html#post-v2-apps)
This means during an upgrade the new version is started, before the old version is killed.

Please adjust your upgradeStrategy to your expected behaviour.

**Comment by moonkev** [comment]
Hi, we actually have an upgrade strategy of 0 already set.  It is a little hard to upload logs and request from my work as we have massive restrictions on what we can post internally.  but essentially we are calling the PUT call on /v2/apps with a list of objects that simply has the "id" and "instances" field set (so not changing any other fields.

**Comment by moonkev** [comment]
I will note that if we make this call on a single app (so to /v2/app instead of /v2/apps) we see the expected behavior and do not see overscaling.

**Comment by janisz** [comment]
Interesting. Previously I've done performance tests deploying hundreds of apps and updating them using `PUT /v2/groups` (template that I used to generate payload http://beta.json-generator.com/EkldYe-GM) but I haven't experienced overscaling. 
@moonkev Can you provide template similar to your payload and steps to reproduce?

**Comment by moonkev** [comment]
It would be pretty simplistic - essentially this to ```PUT /v2/apps``` - http://beta.json-generator.com/4kjTlkvOG

However, if doing individually to ```POST /v2/apps/{appId}``` we do not see the overscale

**Comment by aquamatthias** [comment]
@moonkev the definition you have provided will use the default upgrade strategy (  minimumHealthCapacity=1  ==> deploy 100% of the instances of the new version side by side,
maximumOverCapacity=1 ==> use 100% overcapacity ==> 200% of the capacity for this app).
The behaviour that you describe is expected with such definition.
Please use something like:
```
{
  "id": "foo",
  "cmd": "sleep 1000",
  "upgradeStrategy": {
    "maximumOverCapacity": 0,
    "minimumHealthCapacity": 0
  }
}
```

Please reopen this thicket, if you still see this behaviour with such a definition.

**Comment by moonkev** [comment]
Thank you for the advice @aquamatthias .  Unfortunately, we have already deployed the app with an with maximumOverCapacity and minimunHealthCapacity set to 0.  The payload above is simply to scale the apps to a single instance when their instance count is currently set to 0 - so scaling a pre-existing deployment.  What is actually worse, is that the overscaling does not stop at 200% capacity of the instance count.  We set the instance count to 1 and see the app scale sometimes to 4 or 5 instances.  I would reopen the ticket, but do not have permission to do so.

**Comment by janisz** [comment]
@moonkev Can you post steps to reproduce this bug,  including what is posted to Marathon and result it gets. Use curl or httpie so we can easily reproduce this problem?

1. Post 10 applications with `curl... `
2. Get following Marathon and Mesos state... 
3. Update previously deployed apps with `curl.... `
4. Got following Marathon and Mesos state...

**Comment by aquamatthias** [comment]
@moonkev reopened the Ticket. Please provide steps to reproduce or logs (scramble sensitive information).

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2480. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
