### ISSUE TITLE
Marathon fails to release reserved resources for deleted apps

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#5142]
As of this writing, with the head of e62695b, I've encountered a case in which Marathon cannot release reserved resources because they are identified as spurious, which [results in a force expunge](https://github.com/mesosphere/marathon/blob/e62695bca927dbcb99c1f7b135447d3a5e095079/src/main/scala/mesosphere/marathon/core/matcher/reconcile/impl/OfferMatcherReconciler.scala#L75). Down the line, the [force expunge fails because the app does not exist].

Expunge should probably be made idempotent, such that if it doesn't exist, then the result is successful.

**Comment by aquamatthias** [comment]
I agree - the same logic as `rm -f`, which does not give you an error, if it is already deleted.
