### ISSUE TITLE
Should marathon remove data automatically when destroy an unused application with Persistent Volumes?

### ISSUE THREAD

**Issue by Thinkwp** [mesosphere/marathon#5145]
When I destroy an unused application with Persistent Volumes, I need remove the data on disk by ssh'ing into the agent and running the rm -rf <volume-path>/* command. However mesos's HTTP API '/destroy-volumes' can remove the data. Should marathon support auto remove data when destroy an unused application to avoid disk leak?

**Comment by aquamatthias** [comment]
When the app is deleted, all resources should be released and all persistent volumes get deleted.
Duplicates #5142.
