### ISSUE TITLE
Migration prior Marathon 1.1 to Marathon 1.4 fails for invalid apps

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#5146]
Marathon 1.4 handles constraints more strict than prior versions.
A migration makes sure to repair wrong apps.

The migration to 1.1.5 uses validation from 1.4 that breaks.

**Comment by jdef** [comment]
why is tagged milestone 1.4?

**Comment by aquamatthias** [comment]
Because it fails in 1.4
