### ISSUE TITLE
Deletion of a service endpoint is not possible

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#5149]
https://mesosphere.atlassian.net/browse/DCOS-12659

As is:
1. Create a Docker app with a Bridge network with 2 or more service endpoints
2. Edit the app and delete one of the endpoints
3.1 Observe that the app got redeployed with the same amount of endpoints
3.2 Observe that the deleted endpoint now has containerPort: 0
4. Go to the edit form again
5. Observe that the form section for that deleted endpoint is back with containerPort: 0
Expected:
Deleted Service endpoint should be gone.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1697. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
