### ISSUE TITLE
Need Version Test Flag

### ISSUE THREAD

**Issue by kensipe** [mesosphere/marathon#5158]
We need a way to denote a feature version on a test such that a test is ignored because that version of marathon doesn't have that feature.  For this iteration of the feature, assume the feature doesn't go away.

ignore if less than vx.y

we should pass it on major.minor.sub-minor on major and minor.   
marathon 1.3.9 = 1.3.9  = 1.3
marathon 1.4.0-RC8 = 1.4.0 = 1.4
marathon1.5-snap = 1.5

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1742. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
