### ISSUE TITLE
Use Alpine instead of Ubuntu for Docker Image

### ISSUE THREAD

**Issue by jeschkies** [mesosphere/marathon#5159]
This could reduce the image size from 1.6GB (or 900MB) down to 250MB.

There is a [libmesos bundle](https://mesosphere.atlassian.net/wiki/display/CORE/%5BWIP%5D+Libmesos+Bundle) that should work with Alpine.

**Comment by JiraImporter** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4239. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4239. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
