### ISSUE TITLE
Automate MoM 1.3.x EE system integration tests

### ISSUE THREAD

**Issue by kensipe** [mesosphere/marathon#5160]
We need tests for MoM EE 

https://wiki.mesosphere.com/display/DCOS/MoM+EE+1.3.6?focusedCommentId=102498556#comment-102498556

**Comment by JiraImporter** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1738. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1738. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
