### ISSUE TITLE
add support for PATCH because we're deprecating partial-update semantics for PUT in 1.4

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#5161]
see https://github.com/mesosphere/marathon/pull/5157#issuecomment-279020931

**Comment by jdef** [comment]
http://stackoverflow.com/questions/17897171/how-to-have-a-patch-annotation-for-jax-rs

**Comment by meichstedt** [comment]
Fixed in 1ba8ea7352045119b9d4803010f03b88ee79e861

**Comment by jdef** [comment]
I don't see a changelog note for the new PATCH API call
