### ISSUE TITLE
forward-port PATCH related code to master

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#5162]
* related 1.4 code: #5157, #5217
* also see #5161

**Comment by unterstein** [comment]
Going to pick from bottom to top:
```
* e1b7952 - Fixes #5211 by defining the jersey annotated methods explicitly. (#5217) (4 days ago) <Johannes Unterstein>
* 1ba8ea7 - Add support for PATCH updates to apps in 1.4 (#5183) (7 days ago) <Matthias Eichstedt>
* 8df2a5d - PUT on /v2/apps has a PATCH semantic. (#5157) (2 weeks ago) <Matthias Veit>
```

**Comment by unterstein** [comment]
phab review https://phabricator.mesosphere.com/D552

**Comment by JiraImporter** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2576. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2576. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
