### ISSUE TITLE
Fix Pod Constraint Example in RAML

### ISSUE THREAD

**Issue by kensipe** [mesosphere/marathon#5167]
https://github.com/mesosphere/marathon/blob/94efcee727612559ca227af4adce3a458281ee2c/docs/docs/rest-api/public/api/v2/types/constraint.raml#L29
looks like a copy and paste which is incorrect.

It should look something like 
' [{'operator': 'LIKE', 'fieldName': 'hostname', 'value': '10.0.0.133'}]}}'

**Comment by aquamatthias** [comment]
This is an example of an app constraint and correct.
