### ISSUE TITLE
Add Pod Constraint Example in RAML

### ISSUE THREAD

**Issue by kensipe** [mesosphere/marathon#5168]
https://github.com/mesosphere/marathon/blob/94efcee727612559ca227af4adce3a458281ee2c/docs/docs/rest-api/public/api/v2/types/constraint.raml#L29
looks like a copy and paste which is incorrect.

It should look something like 
' [{'operator': 'LIKE', 'fieldName': 'hostname', 'value': '10.0.0.133'}]}}'

**Comment by jdef** [comment]
the line you linked to is for app constraints, not pod constraints. arguably, we could have picked more clear names. that said, the example IS correct.

the definition for a pod constraint is here: https://github.com/mesosphere/marathon/blob/94efcee727612559ca227af4adce3a458281ee2c/docs/docs/rest-api/public/api/v2/types/constraint.raml#L10

and the `constraints` array field itself is defined here https://github.com/mesosphere/marathon/blob/94efcee727612559ca227af4adce3a458281ee2c/docs/docs/rest-api/public/api/v2/types/pod.raml#L84, albeit without an example. we should provide one

**Comment by JiraImporter** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2341. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2341. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
