### ISSUE TITLE
#5197 Archive Build Artifacts to S3

### ISSUE THREAD

**Issue by jeschkies** [mesosphere/marathon#5174]
This is part of the story "Tag Commit, Change version.sbt and Push Automatically". 
The build artifacts should be archived to S3 instead of Jenkins for each build.

**Comment by jeschkies** [comment]
Is blocked by https://jira.mesosphere.com/browse/VELOCITY-1253

**Comment by jeschkies** [comment]
In review https://phabricator.mesosphere.com/D563

**Comment by JiraImporter** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1832. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1832. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
