### ISSUE TITLE
#5134 Create demo to show plotted scale test results

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#5175]
We need this as part of the user story. This is due by 24 Feb 2017

**Comment by marcomonaco** [comment]
If we'll not have the results visualised, we are good with having at least the results in a table or something to show them as a demo.

**Comment by JiraImporter** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2552. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2552. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
