### ISSUE TITLE
 export GULP_ENV="development" DISABLE_SOURCE_MAP=false && gulp serve  'export' is not recognized as an internal or external command, operable program or batch file.

### ISSUE THREAD

**Issue by vijaypabothu** [mesosphere/marathon#5177]
Hi,
I followed the steps  mentioned in git hub link for marathon webui 
https://github.com/mesosphere/marathon-ui  

and I stuck in between .

Getting the subjected error .  Please advise to proceed further. 

C:\Users\vpabothu\Downloads\marathon-ui-master\src\js\config> npm run serve

> marathon-ui@1.1.8 serve C:\Users\vpabothu\Downloads\marathon-ui-master
> export GULP_ENV="development" DISABLE_SOURCE_MAP=false && gulp serve

'export' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "serve"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! marathon-ui@1.1.8 serve: `export GULP_ENV="development" DISABLE_SOURCE_MAP=false && gulp serve`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the marathon-ui@1.1.8 serve script 'export GULP_ENV="development" DISABLE_SOURCE_MAP=false && gulp serve'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the marathon-ui package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     export GULP_ENV="development" DISABLE_SOURCE_MAP=false && gulp serve
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs marathon-ui
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls marathon-ui
npm ERR! There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\vpabothu\Downloads\marathon-ui-master\src\js\config\npm-debug.log

**Comment by orlandohohmeier** [comment]
Hi @vijaypabothu! Unfortunately,  we're using directives that aren't supported by Windows and only test our build scripts on Unix using `bash` and `zsh`. You might be able to get the build working by changing `export GULP_ENV="development" DISABLE_SOURCE_MAP=false` to `set GULP_ENV=production && set DISABLE_SOURCE_MAP=false` but chances are that there are other incompatibilities. I recommend to use the fully containerize the development environment introduces in mesosphere/marathon-ui#797 to workaround these issues.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2437. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
