### ISSUE TITLE
Release Marathon 1.4

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#5178]
- Promoting the latest RC to v1.4.0	
- Updating the change log for Marathon 1.4	
- Write release notes for Marathon 1.4
- Make sure that GitHub milestone is empty	
- Create Marathon 1.4 MoM Universe package	 	
- Add Marathon 1.4 PR against DC/OS 1.9 EE	 	
- Add Marathon 1.4 PR against DC/OS 1.9 Open
- Make sure the Marathon 1.4 documentation is complete	
- Smoke test the Marathon UI 1.1.7

**Comment by jasongilanfarr** [comment]
- [x] Promoting the latest RC to v1.4.0
- [x] Updating the change log for Marathon 1.4
- [x] Write release notes for Marathon 1.4
- [x] Make sure that GitHub milestone is empty
- [ ] Create Marathon 1.4 MoM Universe package
- [x] Add Marathon 1.4 PR against DC/OS 1.9 EE
- [x] Add Marathon 1.4 PR against DC/OS 1.9 Open
- [x] Make sure the Marathon 1.4 documentation is complete

**Comment by marcomonaco** [comment]
@jasongilanfarr I think we can close that, ok?
