### ISSUE TITLE
appc image labels aren't properly generated for pods

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#5186]
>>>
there's actually some wacky things that happen with labels for pods when Marathon generates the protobufs for Mesos to consume:

(1) appc image labels are built from Marathon API container image labels + container labels + pod labels
(2) task labels are built from Marathon API container labels
(3) executor labels are built from Marathon API pod labels
(4) command info envvars are augmented with vars generated from labels (we do this for apps too), and for pods the labels are sourced from Marathon API pod + container
(5) network labels are propagated from Marathon API to Mesos network-infos
(6) port labels are propagated from Marathon API to Mesos task DI port labels

There's some behavioral bugs up there. I'd suggest the following changes:

(a) appc image labels should probably not be sourced from the API container + pod labels as in (1); we're actually ***missing*** Marathon API image labels in our RAML spec/model (because this is ideally where the appc image labels should be sourced from); also, we should document the default labels that Marathon injects for appc image protobufs (os -> linux, arch -> amd64 (these should be overridable by Marathon API image labels)).

(b) the behavior of (4) implies that the behavior of (2) is incorrect; (2) should also incorporate pod labels (this would be consistent w/ how envvars declared at the API pod level are copied to all subtasks)

**Comment by aquamatthias** [comment]
The appc containerizer in Mesos is experimental and the proto model is completely broken. I would not like us to spend time on this before this is fixed on the Mesos side.

**Comment by jdef** [comment]
what makes you think the proto model is completely broken? do you have
specific Mesos JIRAs in mind that would block **us** from fixing our API
and inconsistent label handling? I'd really like to get the API as right as
possible for the 1.4 launch

Marathon is clearly doing bad/inconsistent things w/ labels and we should
fix for the 1.4 milestone.

**Comment by aquamatthias** [comment]
By broken I mean a half baked model, which defines values by specifying labels:

```
    // Optional labels. Suggested labels: "version", "os", and "arch".
    optional Labels labels = 3;
  }
```

The "suggestion" is mandatory by the way (Marathon will render defaults here, if the user does not specify them.). 

The app and pod spec makes the mesos values available. 
The labels are taken from the app / pod+container.

**Comment by jdef** [comment]
Image labels are used (AFAIK) to identify images not become associated with
the running container. Marathon confuses the purpose of container labels
and applies them to the image. This is wrong.

**Comment by jdef** [comment]
https://github.com/appc/spec/blob/master/spec/aci.md#image-manifest-schema

**Comment by jdef** [comment]
fixes for (a) are here https://phabricator.mesosphere.com/D540

**Comment by jdef** [comment]
what's the plan to tackle proposed problem (b) ?

**Comment by aquamatthias** [comment]
@jdef please create another issue for the (b)
