### ISSUE TITLE
#5063 Change Package Version Before Release

### ISSUE THREAD

**Issue by jeschkies** [mesosphere/marathon#5196]
The Marathon version is defined in `version.sbt`. That means a package has to be rebuilt once the version numbers changes. However, we do not want to rebuild a package for release but just graph the binaries and push them to S3 and so on. So we have to define the version number in a different way that also to change it without recompiling.

**Comment by jeschkies** [comment]
As discussed with @aquamatthias the version number will be moved into the Manifest [as proposed by Oracle](https://docs.oracle.com/javase/tutorial/deployment/jar/packageman.html).

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2427. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
