### ISSUE TITLE
plugins are loaded inconsistently by PluginManagerImpl

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#5198]
problem is this statement `val providers = serviceLoader.iterator()` which creates a one-shot iterable that's later (potentially) used more then once. the net effect is that if there are multiple variants of the same plugin type then (a) only one of those variants is loaded, and; (b) which variant isn't deterministic

Should transform this iterator to a Seq, or some other structure that supports multiple iteration cycles.

xref DCOS-13975

**Comment by jdef** [comment]
please xref GH tickets with phab reviews https://phabricator.mesosphere.com/D526

**Comment by unterstein** [comment]
Will do in future, but this information can also be found in commit message, click `...`.
