### ISSUE TITLE
Add event type filtering to the docs

### ISSUE THREAD

**Issue by tobilg** [mesosphere/marathon#5200]
With https://github.com/mesosphere/marathon/pull/4671/commits/6f5ad0332ac729bc2c2de876e166d4fb0f5bf84c (being part of https://github.com/mesosphere/marathon/pull/4671) , the filtering by event types was enabled for the Event Bus.

I guess it would make a lot of sense to add this to the docs at https://github.com/mesosphere/marathon/blob/master/docs/docs/event-bus.md as this is already shipped with current 1.3 versions, and will be part of 1.4 as well.

**Comment by janisz** [comment]
@tobilg mentioned commit includes changes to api documentation both legacy Markdown and raml. I think docks only need to be regenerated.

Do you think we should directly include information about filtering in event bus docs? 

BTW I found broken link in event bus docs:

> Other subscribers are easy to add. See the code in marathon/event/http for guidance.

**Comment by tobilg** [comment]
@janisz Thanks for the feedback. I think the commit is not containing the "normal" docs, but the Rest API part and the RAML.

**Comment by janisz** [comment]
Indeed user could be confused becouse there is no example how to use SSE nor how to filter events. I'll fix it with `curl` to show  how to attach to the stream and how to filter it.

**Comment by janisz** [comment]
@tobilg @sascala Can you take a look at https://github.com/mesosphere/marathon/pull/5212

**Comment by tobilg** [comment]
@sascala Can you please have a look? Thanks!

**Comment by sascala** [comment]
👍

**Comment by tobilg** [comment]
Can this be closed, or is there still something to do @sascala? Thanks!

**Comment by sascala** [comment]
I left some edits on the PR, but I think we can close the issue here. https://github.com/mesosphere/marathon/pull/5212

**Comment by tobilg** [comment]
Great, thanks a lot @sascala
