### ISSUE TITLE
PodSpec plugin interface missing labels

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#5204]
labels and envvars need to be filtered for security. marathon combines pod-level labels w/ container-level levels and exposes the aggregate to each task.

if a plugin can't filter/validate labels defined at the pod level then there's an inherent security risk for plugins enforcing a security context via labels.

**Comment by aquamatthias** [comment]
Added labels for plugins.
Patch is here: https://phabricator.mesosphere.com/D534
