### ISSUE TITLE
Release Marathon 1.4.2

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#5206]
Serialization picks:
- [ ] #5300 app killSelection ( [backported patch](https://github.com/mesosphere/marathon/pull/5309) )
- [ ] #5303 persistent volume maxSize ( [patch for master](https://phabricator.mesosphere.com/D577) )

**Comment by timcharper** [comment]
Picks:

- 5ff4ca062060026eb5cdd0f413cea7a03e20a4dd - Disable UnreachableStrategy for resident tasks
- dad4e1f2b3e45fc13b207c21dc9936e901d7b47b - Read LaunchedOnReservation and Reserved tasks
- f441c571beb445271be6b00fa097ed2f4c6ad7f3 -  ForceExpunge for missing task is a no-op, rather than a failure

**Comment by timcharper** [comment]
This needs to be done and picked: https://github.com/mesosphere/marathon/issues/5209

**Comment by jasongilanfarr** [comment]
Unless there is a major pressing need, I'd like to not publish 1.4.1 until
at least March 2nd. If the known issues are blocking you, please thumbs up
this comment to increase the urgency.

**Comment by timcharper** [comment]
D529 should be included, too (fixing #5207). As of this writing it is not yet applied to master.

**Comment by timcharper** [comment]
Also, [D533](https://phabricator.mesosphere.com/D533) should be included. (Fix for #5155 )

**Comment by aquamatthias** [comment]
[D534](https://phabricator.mesosphere.com/D534)

**Comment by aquamatthias** [comment]
Already picked d08a0d1c1a8d489d7d723a9ab2068bc99360c869 which addresses #5237 Group serialization violates declared schema
Already picked c07c8e36ae7f3fbfb113d4aa23db93fb3f72497b which addresses #5204 PodSpec plugin interface missing labels

**Comment by jasongilanfarr** [comment]
Already picked d08a0d1 which addresses #5237 Group serialization violates declared schema -> as stated, this patch was *wrong*

**Comment by jasongilanfarr** [comment]
I revertted #5237 on both 1.4 and master. The docs were correct to begin with.

**Comment by timcharper** [comment]
I have collected all of my resident task picks into a single check list so it is easier

**Comment by timcharper** [comment]
- [ ] We should manually test the migration prior to the release. See test plan in 97cf12a4df64480c00245c4d406a6b580371e5ea

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2409. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
