### ISSUE TITLE
Killing a lost resident task results in expunge

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#5207]
In [KillServiceActor.scala](https://github.com/mesosphere/marathon/blob/4e962a32c75a0076cb18dceda5754da148c7e2e5/src/main/scala/mesosphere/marathon/core/task/termination/impl/KillServiceActor.scala#L155) we decide to expunge a task if it is lost or terminated. This should be fixed such that we transition the task back to `Reserved`, and only expunge if explicitly asked to do so.

**Comment by meichstedt** [comment]
@timcharper I see you have this in progress but since it's a public holiday on your side and I had some time while being on-call, I've provided https://phabricator.mesosphere.com/D529

Please consider this a WIP and feel free to take over if you see fit.

**Comment by timcharper** [comment]
Thanks @meichstedt for starting this ! I'll commandeer the change and push it to completion.

**Comment by timcharper** [comment]
I've finished the patch and it's confirmed to work
