### ISSUE TITLE
ActorLogging Actors do not abide `--logging_level=debug`

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#5208]
When we start Marathon using the `--logging_level=debug` flag, `StrictLogging` / other logging modules will have their log level affected appropriately, but for reasons not yet understood `ActorLogging` does not register the change. Could it be that our actor logging filter is not configured properly?

Solutions include finding and fixing, or, switching to StrictLogging for all the things.

**Comment by timcharper** [comment]
@jasongilanfarr seems to vote for `StrictLogging` all the things

**Comment by jasongilanfarr** [comment]
Yup.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1726. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
