### ISSUE TITLE
Data migration for UnreachableDisabled

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#5209]
Resident appSpecs will require that UnreachableStrategy is disabled in 1.4.1. We need a data migration so that appSpecs don't fail validation.

**Comment by timcharper** [comment]
https://phabricator.mesosphere.com/D543

**Comment by jdef** [comment]
xref #5245

**Comment by timcharper** [comment]
https://github.com/mesosphere/marathon/commit/809b9f96dec3278097e12f44bd6c8d4b8fbdc3e9 closed
