### ISSUE TITLE
Error Scaling Application

### ISSUE THREAD

**Issue by damok6** [mesosphere/marathon#5213]
Since the 1.4 release, there is an error scaling applications using the Marathon web UI. It occurs with a very simple single-master, single-agent Mesos cluster.

When you try to scale via the Scale Application button for a given application, it gives the following error.

![image](https://cloud.githubusercontent.com/assets/12734497/23102197/a2e8b91c-f69c-11e6-806a-2400a9c45246.png)

It is still possible to create a multiple-instance application, however it is only possible by manually destroying the application and recreating the application with a different number of instances.

**Comment by janisz** [comment]
Related to #5211 It's not GUI it's Marathon issue with handling PUTs

**Comment by wavesoft** [comment]
Hey @damok6 . This looks like a Marathon issue : https://github.com/mesosphere/marathon/issues/5211

**Comment by wavesoft** [comment]
Ah, I didn't see @janisz already provided an answer for this 😄

**Comment by damok6** [comment]
Ah cool, thanks @janisz and @wavesoft. That was fast! :)
