### ISSUE TITLE
How to disable HTTP?

### ISSUE THREAD

**Issue by shining-snail** [mesosphere/marathon#5218]
Hello to All, I'd like to enable https and disable http for security reasons.  
According to the doc:
https://mesosphere.github.io/marathon/docs/command-line-flags.html

_--disable_http (Optional.): Disable HTTP completely. This is only allowed if you configure HTTPS._ 

Here is my configuration:

[root@centos7-01 conf]# pwd
/etc/marathon/conf
[root@centos7-01 conf]# ls -l
total 24
-rw-r--r-- 1 root root  0 Feb 20 20:41 disable_http
-rw-r--r-- 1 root root 14 Feb  3 23:29 hostname
-rw-r--r-- 1 root root 15 Feb 14 22:15 http_credentials
-rw-r--r-- 1 root root 68 Feb  3 23:33 master
-rw-r--r-- 1 root root  9 Feb 15 19:36 ssl_keystore_password
-rw-r--r-- 1 root root 36 Feb 16 22:56 ssl_keystore_path
-rw-r--r-- 1 root root 71 Feb  3 23:34 zk

[root@centos7-01 conf]#service marathon start

The service failed to start:

Feb 20 20:49:01 centos7-01 systemd[1]: Started Marathon.
Feb 20 20:49:01 centos7-01 systemd[1]: Starting Marathon...
Feb 20 20:49:01 centos7-01 marathon[5609]:run_jar --hostname 192.168.1.101 --master zk://192.168.1.101:2181,192.168.1.102:2181,192.168.1.103:2181/mesos --zk zk://192.168.1.101:2181,192.168.1.102:2181,192.168.1.103:2181/marathon --ssl_keystore_password pass.789 --http_credentials dandy:pass.123 --ssl_keystore_path /home/mesosuser/keydir/marathon.jks --disable_http
**Feb 20 20:49:02 centos7-01 marathon[5634]: [scallop] Error: Excess arguments provided: ''**
Feb 20 20:49:03 centos7-01 systemd[1]: marathon.service: main process exited, code=exited, status=1/FAILURE
Feb 20 20:49:03 centos7-01 systemd[1]: Unit marathon.service entered failed state.
Feb 20 20:49:03 centos7-01 systemd[1]: marathon.service failed.

**Marathon works if the configuration "disable_http" is removed.** Then both http and https are enabled.

What's the mistake in my configuration?

Any help will be appreciated.

**Comment by janisz** [comment]
Can you post response from `/v2/info`? I think you filename should be prefixed with `?` so it should be like `?disable_http`

**Comment by shining-snail** [comment]
@janisz 
It works!Sincerely thank you for your help!

How to post response from /v2/info? I'm unfamiliar with REST API......

I encounter another problem. I use zookeeper for HA.
[root@centos7-01 conf]# cat zk
zk://192.168.1.101:2181,192.168.1.102:2181,192.168.1.103:2181/marathon

After adding "?disable_http", I can only access the master marathon homepage. The other two hang on an blank page.When http is enabled ,these three marathon pages are all accessiable.

Here is the error log:
Feb 20 21:47:02 centos7-01 marathon[10189]: [2017-02-20 21:47:02,255] INFO Session establishment complete on server 192.168.1.103/192.168.1.103:2181, sessi
Feb 20 21:47:02 centos7-01 marathon[10189]: [2017-02-20 21:47:02,258] INFO State change: CONNECTED (org.apache.curator.framework.state.ConnectionStateManag
Feb 20 21:47:31 centos7-01 marathon[10189]: [2017-02-20 21:47:31,832] INFO Proxying request to GET https://192.168.1.102:8443/ from 192.168.1.101:8443 (mes
Feb 20 21:47:31 centos7-01 marathon[10189]: [2017-02-20 21:47:31,905] WARN / (org.eclipse.jetty.servlet.ServletHandler:qtp1701798620-41)
Feb 20 21:47:31 centos7-01 marathon[10189]: java.lang.RuntimeException: while proxying
Feb 20 21:47:31 centos7-01 marathon[10189]:         at mesosphere.marathon.api.LeaderProxyFilter.doFilter(LeaderProxyFilter.scala:117)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1668)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:581)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:513)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1160)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:511)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1090)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at com.codahale.metrics.jetty9.InstrumentedHandler.handle(InstrumentedHandler.java:240)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.server.handler.gzip.GzipHandler.handle(GzipHandler.java:437)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:119)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.server.Server.handle(Server.java:517)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:308)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:242)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.io.ssl.SslConnection.onFillable(SslConnection.java:192)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:261)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.io.FillInterest.fillable(FillInterest.java:95)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.io.SelectChannelEndPoint$2.run(SelectChannelEndPoint.java:75)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.produceAndRun(ExecuteProduceConsume.jav
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.util.thread.strategy.ExecuteProduceConsume.run(ExecuteProduceConsume.java:147)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:654)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:572)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at java.lang.Thread.run(Thread.java:745)
Feb 20 21:47:31 centos7-01 marathon[10189]: Caused by: javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building f
Feb 20 21:47:31 centos7-01 marathon[10189]:         at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at sun.security.ssl.SSLSocketImpl.fatal(SSLSocketImpl.java:1949)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:302)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at sun.security.ssl.Handshaker.fatalSE(Handshaker.java:296)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at sun.security.ssl.ClientHandshaker.serverCertificate(ClientHandshaker.java:1509)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at sun.security.ssl.ClientHandshaker.processMessage(ClientHandshaker.java:216)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at sun.security.ssl.Handshaker.processLoop(Handshaker.java:979)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at sun.security.ssl.Handshaker.process_record(Handshaker.java:914)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1062)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1375)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1403)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1387)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at sun.net.www.protocol.https.HttpsClient.afterConnect(HttpsClient.java:559)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnec
Feb 20 21:47:31 centos7-01 marathon[10189]:         at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1546)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at mesosphere.marathon.api.JavaUrlConnectionRequestForwarder.copyConnectionResponse$1(LeaderProxyFilter
Feb 20 21:47:31 centos7-01 marathon[10189]:         at mesosphere.marathon.api.JavaUrlConnectionRequestForwarder.forward(LeaderProxyFilter.scala:282)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at mesosphere.marathon.DebugModule$MetricsBehavior$$anonfun$invoke$1.apply(DebugConf.scala:87)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at mesosphere.marathon.metrics.Metrics.timed(Metrics.scala:28)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at mesosphere.marathon.DebugModule$MetricsBehavior.invoke(DebugConf.scala:86)
Feb 20 21:47:31 centos7-01 marathon[10189]:         at mesosphere.marathon.api.LeaderProxyFilter.doFilter(LeaderProxyFilter.scala:114)
Feb 20 21:47:31 centos7-01 marathon[10189]:         ... 31 common frames omitted

**Comment by janisz** [comment]
`/v2/info` is an endpoint that presents marathon configuration. Useful to debug what config is accutally running. You cen get it with broser pointing at `<HOST>:<PORT>/v2/info` e.g., https://192.168.1.102:8443/v2/info

I think you need to set following option:

> [--leader_proxy_ssl_ignore_hostname (Optional. Default: false): Do not verify that the hostname of the Marathon leader matches the one in the SSL certificate when proxying API requests to the current leader.](https://mesosphere.github.io/marathon/docs/command-line-flags.html#optional-flags-1)

**Comment by shining-snail** [comment]
@janisz 
Thank you so much! I've set the option:
[root@centos7-01 conf]# ls -l
total 24
-rw-r--r-- 1 root root  0 Feb 20 21:39 ?disable_http
-rw-r--r-- 1 root root 14 Feb  3 23:29 hostname
-rw-r--r-- 1 root root 15 Feb 14 22:15 http_credentials
-rw-r--r-- 1 root root  0 Feb 21 21:27 ?leader_proxy_ssl_ignore_hostname
-rw-r--r-- 1 root root 68 Feb  3 23:33 master
-rw-r--r-- 1 root root  9 Feb 15 19:36 ssl_keystore_password
-rw-r--r-- 1 root root 36 Feb 16 22:56 ssl_keystore_path
-rw-r--r-- 1 root root 71 Feb  3 23:34 zk

Then I start the marathon service.

The master is  192.168.1.101. The "/v2/info" is below:
{"name":"marathon","version":"1.3.6","buildref":"unknown","elected":true,"leader":"192.168.1.101:8443","frameworkId":"a98fd49b-5f86-4659-9946-8fffafeab5fd-0032","marathon_config":{"master":"zk://192.168.1.101:2181,192.168.1.102:2181,192.168.1.103:2181/mesos","failover_timeout":604800,"framework_name":"marathon","ha":true,"checkpoint":true,"local_port_min":10000,"local_port_max":20000,"executor":"//cmd","hostname":"192.168.1.101","webui_url":null,"mesos_role":null,"task_launch_timeout":300000,"task_reservation_timeout":20000,"reconciliation_initial_delay":15000,"reconciliation_interval":600000,"mesos_user":"root","leader_proxy_connection_timeout_ms":5000,"leader_proxy_read_timeout_ms":10000,"features":[],"mesos_leader_ui_url":"http://192.168.1.103:5050/"},"zookeeper_config":{"zk":"zk://192.168.1.101:2181,192.168.1.102:2181,192.168.1.103:2181/marathon","zk_timeout":10000,"zk_session_timeout":10000,"zk_max_versions":25},"event_subscriber":null,"http_config":{"http_port":8080,"https_port":8443}}

The other two still hang on an  blank page.

**Comment by shining-snail** [comment]
@janisz 
I've found the cause of this problem!
After I try to use the same certificate on all  three server, I can access the every marathon page in the cluster.

I'm really confused......This only happened after disabling http. Even different certificates works well when http is enabled , why problem occurs when http is disabled......
