### ISSUE TITLE
Readiness checks: support TCP/Command

### ISSUE THREAD

**Issue by pierrecdn** [mesosphere/marathon#5223]
Right now, readiness checks supports only HTTP.

For non-HTTP processes it would be interesting to support the same feature as for healthchecks, meaning TCP and COMMAND methods.

I guess that it also implies some work on https://issues.apache.org/jira/browse/MESOS-6171 since these checks are specific to the executor and do not prevent the task to be considered as healthy from all points of view.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4728. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
