### ISSUE TITLE
UpgradeStrategy: moving from percent to instance number ?

### ISSUE THREAD

**Issue by pierrecdn** [mesosphere/marathon#5225]
It is not very clear to me why the upgradeStrategy has to be expressed as percent instead of number of instances.
In any case, once #5521 is fixed, it should be easy to precompute a policy depending on the user requirements, so this is more an open discussion.

Related to : #4416, #5221

**Comment by meichstedt** [comment]
@pierrecdn I totally agree, it doesn't make much sense and it's not very flexible. The way deployments are handled right now (and the cases where upgradeStrategy is considered) are suboptimal.

We have mid- to long term plans to generally improve the upgrade mechanism, but this will take some time. In the meantime, various related components will be adjusted to allow for a general overhaul.

**Comment by pierrecdn** [comment]
> various related components will be adjusted to allow for a general overhaul

You're talking about which ones ? DC/OS things ? other ?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1867. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
