### ISSUE TITLE
update app fail

### ISSUE THREAD

**Issue by qiankunli** [mesosphere/marathon#5227]
![image](https://cloud.githubusercontent.com/assets/8024725/23149749/207ceba4-f829-11e6-8734-1fd477c9d190.png)

I use marathon deploy a dockerize app, two instances. when update the app, the container running old image(test/docker-profile-proxy-testout:2) is retainning.

update commnad

    curl -sH "content-type: application/json" -XPUT -d @$WORKSPACE/marathon.json http://192.168.60.8:8080/v2/apps/${JOB_NAME}

marathon.json

`
{
  "id": "$JOB_NAME",
  "cmd": null,
  "cpus": 1,
  "mem": 2048,
  "disk": 0,
  "instances": 2,
  "labels":{"appType":"$APP_TYPE", "author":"$BUILD_USER"},
  "constraints": [
  	["type", "CLUSTER","app-test"]
  ],
  "container": {
    "type": "DOCKER",
    "volumes": [
      {
        "containerPath": "/logs",
        "hostPath": "/var/log/app",
        "mode": "RW"
      }
    ],
    "docker": {
      "image": "test/docker-profile-proxy-testout:$BUILD_NUMBER",
      "network": "USER",
      "privileged": false,
      "forcePullImage": true,
      "parameters": [
      	   { "key": "network", "value": "macvlan96" }
      ]
    }
  },
  "ipAddress": {
	"networkName": "macvlan96"
  },
  "healthChecks": [{
    "port": 8080,
    "protocol": "TCP",
    "gracePeriodSeconds": 180,
    "intervalSeconds": 15,
    "timeoutSeconds": 30,
    "maxConsecutiveFailures": 0
  }],
  "upgradeStrategy": {
    "minimumHealthCapacity": 0,
    "maximumOverCapacity": 1
  }
}

`

**Comment by meichstedt** [comment]
@qiankunli Not sure I get the problem correctly. Can you share some relevant logfiles from Marathon?

**Comment by qiankunli** [comment]
To begin with, the container running old image(test/docker-profile-proxy-testout:2) has two instances. however , the container still has a instance after executing the update command.

 It is right that the new container running the new image(test/docker-profile-proxy-testout:5) has two instances.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4718. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
