### ISSUE TITLE
marathon v1.1.2 three marathons for ha,but could not access

### ISSUE THREAD

**Issue by yugongpeng** [mesosphere/marathon#5229]
web ui error info:

HTTP ERROR: 503

Problem accessing /. Reason:

    Could not determine the current leader

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4615. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
