### ISSUE TITLE
Dynamic Volume for Logging

### ISSUE THREAD

**Issue by arunkabraham** [mesosphere/marathon#5233]
Hi 
In my application the logs will be written to a  specific folder in the file system. Please find below the mounting of volume which is working for me.

    "volumes": [
      {
        "containerPath": "/var/log",
        "hostPath": "/var/log",
        "mode": "RW"
      }
I need to specify a folder inside /var/log with container ID and get the logs written there to avoid conflict from multiple containers in the same host.

  "volumes": [
      {
        "containerPath": "/var/log",
        "hostPath": "/var/log/Container_ID",
        "mode": "RW"
      }

I am new to it, I have seen people asking the same question, but no solution is mentioned. so can someone help on this?

**Comment by meichstedt** [comment]
@arunkabraham you could use `$MESOS_TASK_ID` to achieve this. Please reopen if that doesn't fit your needs.

**Comment by arunkabraham** [comment]
@meichstedt I tried it as below, but it created a file or folder called $MESOS_TASK_ID in /var/log/. Can you please  give more details on this? I am new to DCOS and Marathon so please help.

"volumes": [
{
"containerPath": "/var/log",
"hostPath": "/var/log/$MESOS_TASK_ID",
"mode": "RW"
}
