### ISSUE TITLE
 "acceptedResourceRoles": "slave_public" Deployment Stuck with Waiting state

### ISSUE THREAD

**Issue by 91vikash** [mesosphere/marathon#5234]
I am trying to deploy a nginx container inside Marathon with "acceptedResourceRoles": "slave_public" as set. But then the container deployment stuck. I am using the following json file. I have launched the DCOS cluster from the cloudformation stack provided by DCOS.

```
{
  "id": "/nginx-vikash",
  "cmd": null,
  "cpus": 2,
  "mem": 256,
  "disk": 0,
  "instances": 1,
  "acceptedResourceRoles": [
    "slave_public"
  ],
  "container": {
    "type": "DOCKER",
    "volumes": [],
    "docker": {
      "image": "nginx:1.7.7",
      "network": "BRIDGE",
      "portMappings": [
        {
          "containerPort": 80,
          "hostPort": 80,
          "servicePort": 10000,
          "protocol": "tcp",
          "labels": {}
        }
      ],
      "privileged": false,
      "parameters": [],
      "forcePullImage": true
    }
  },
  "healthChecks": [
    {
      "path": "/",
      "protocol": "HTTP",
      "portIndex": 0,
      "gracePeriodSeconds": 10,
      "intervalSeconds": 2,
      "timeoutSeconds": 10,
      "maxConsecutiveFailures": 10,
      "ignoreHttp1xx": false
    }
  ],
  "portDefinitions": [
    {
      "port": 10000,
      "protocol": "tcp",
      "labels": {}
    }
  ]
}
```
If i remove "acceptedResourceRoles": "slave_public" it works fine and in healthy state

**Comment by meichstedt** [comment]
@91vikash Only private agents have resources reserved for that role. Can you verify there are enough resources available for the requested role?

**Comment by 91vikash** [comment]
@meichstedt How do I check that. What I understand there is nothing running on Public Server as I just launched the DCOS cluster from the scratch using AWS Cloudformation Template.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2282. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
