### ISSUE TITLE
Unknown task health status

### ISSUE THREAD

**Issue by meichstedt** [mesosphere/marathon#5235]
See https://github.com/mesosphere/marathon/issues/2104#issuecomment-281339588 for context

Similar to reservation info not surviving the ser/deser via the InstanceRepo, healthCheck information (as stored in the Mesos TaskStatus on a task) is lost when re-constructing instances from the repo.

Update: ser/deser of health status information seems fine, could not reproduce. JHowever it seems strange that the health status information is missing at some point.

**Comment by meichstedt** [comment]
@heww in #2104 you wrote
> At 17:00 (9:00 utc), the instance health check become to unknow

when did you update to Marathon 1.4.1? right before that? hours before?
Can you provide logs from the time when that task's health status became unknown and attach them here?

I can't seem to find evidence for the bug I assumed.

**Comment by heww** [comment]
update to v1.4.1 at 2017-02-21T06:08:17.634954754Z

**Comment by meichstedt** [comment]
thanks @heww 
So, roughly 3 hours after switching to 1.4.1, the health check status information became unknown. I'll investigate if that's possible when the instance becomes unreachable.

**Comment by heww** [comment]
the unknown instance is still reachable from marathon ui, i can click the address in the marathon to access my website.

**Comment by meichstedt** [comment]
@heww Can you share the complete AppDefinition please? Feel free to cross out any confidential information I'm mostly interested in the complete structure regarding networking config, healthCheck config, etc., in order to reproduce the problem.

**Comment by heww** [comment]
my AppDefinition is very simple, no more other things special
```json
{
  "id": "/foo",
  "cmd": null,
  "cpus": 0.3,
  "mem": 512,
  "disk": 0,
  "instances": 1,
  "constraints": [
    [
      "node",
      "LIKE",
      "worker"
    ]
  ],
  "acceptedResourceRoles": [],
  "container": {
    "type": "DOCKER",
    "volumes": [
      {
        "containerPath": "/app/media",
        "hostPath": "/mnt/container-volumes/foo/app/media",
        "mode": "RW"
      }
    ],
    "docker": {
      "image": "index.foo.com/foo/foo:2d4631f0",
      "network": "BRIDGE",
      "portMappings": [
        {
          "containerPort": 5000,
          "hostPort": 0,
          "servicePort": 10102,
          "protocol": "tcp",
          "labels": {}
        }
      ],
      "privileged": false,
      "forcePullImage": true
    }
  },
  "env": {

  },
  "healthChecks": [
    {
      "gracePeriodSeconds": 300,
      "intervalSeconds": 60,
      "timeoutSeconds": 20,
      "maxConsecutiveFailures": 3,
      "portIndex": 0,
      "path": "/",
      "protocol": "HTTP",
      "ignoreHttp1xx": false
    }
  ],
  "labels": {
    "HAPROXY_0_VHOST": "foo.example.com",
    "HAPROXY_GROUP": "external",
    "MARATHON_DNS": "true"
  },
  "uris": [
    "file:///etc/docker.tar.gz"
  ],
  "upgradeStrategy": {
    "minimumHealthCapacity": 0.6,
    "maximumOverCapacity": 1
  }
}
```

**Comment by meichstedt** [comment]
Thanks @heww for the app definition. I couldn't reproduce the reported behavior from 1.3.10 to 1.4.1, but I will try to figure out if some edge case can lead to this.

Do you by chance have any logs (Mesos master/agent and Marathon) from the time of the incident?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2045. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
