### ISSUE TITLE
Group serialization violates declared schema

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#5237]
while rebasing D201 I noticed some bits that wouldn't compile any more because Group serialization MUST output PodStatus objects, not Pod objects.

I'll fix the serialization dissonance for 1.5 with D201, but the code on releases/1.4 is still broken w/ respect to the declared schema.

code: https://github.com/mesosphere/marathon/blob/fdd8d99238a60a51c65c9dc411a93d640433dedf/src/main/scala/mesosphere/marathon/api/v2/json/Formats.scala#L1471

If we decide **not** to fix this for 1.4, then we should at least document it as a known issue.

**Comment by jasongilanfarr** [comment]
We should check, is this for deployment plans only (where status doesn't actually make sense - and thus our schema is kind of wrong) or groups too? If its just deployments, I would argue the declared schema is wrong instead.

**Comment by aquamatthias** [comment]
This happens for every group serialisation including Deployments and Groups via /v2/groups.
I would not change the behaviour for 1.4, but instead change the api docs.
Patch is here: https://phabricator.mesosphere.com/D535

**Comment by jasongilanfarr** [comment]
As commented in the review _and me before you added the comment_. The RAML was only wrong for *deployments* _not_ for *groups*

`
 ✘ jason@marvin  ~/src/marathon   master  http POST :8080/v2/pods <<EOF
heredoc> >....                                                                                                                                                                                                                                                                                                                            
      ],
      "image": {
        "id": "mesosphere/marathon:latest",
        "kind": "DOCKER",
        "forcePull": false
      },
      "environment": {},
      "user": "root",
      "volumeMounts": [
        {
          "name": "etc",
          "mountPath": "/mnt/etc",
          "readOnly": true
        }
      ],
      "labels": {
        "owner": "zeus",
        "note": "Away from olympus"
      },
      "lifecycle": {
        "killGracePeriodSeconds": 60
      }
    }
  ],
  "executorResources": {
    "cpus": 0.2,
    "mem": 64,
    "disk": 50
  }
}

heredoc> EOF
HTTP/1.1 201 Created
Cache-Control: no-cache, no-store, must-revalidate
Content-Type: application/json; qs=2
Date: Wed, 22 Feb 2017 22:55:14 GMT
Expires: 0
Location: http://localhost:8080/v2/pods/foo
Marathon-Deployment-Id: a68e331b-379a-4b1c-b908-535388eb9408
Pragma: no-cache
Server: Jetty(9.3.6.v20151106)
Transfer-Encoding: chunked
X-Marathon-Leader: http://marvin:8080

{
    "containers": [
        {
            "endpoints": [
                {
                    "containerPort": 80, 
                    "hostPort": 0, 
                    "name": "httpendpoint", 
                    "protocol": [
                        "tcp"
                    ]
                }
            ], 
            "exec": {
                "command": {
                    "shell": "sleep 100"
                }, 
                "overrideEntrypoint": true
            }, 
            "image": {
                "forcePull": false, 
                "id": "mesosphere/marathon:latest", 
                "kind": "DOCKER"
            }, 
            "labels": {
                "note": "Away from olympus", 
                "owner": "zeus"
            }, 
            "lifecycle": {
                "killGracePeriodSeconds": 60
            }, 
            "name": "container1", 
            "resources": {
                "cpus": 1, 
                "disk": 0, 
                "gpus": 0, 
                "mem": 128
            }, 
            "user": "root", 
            "volumeMounts": [
                {
                    "mountPath": "/mnt/etc", 
                    "name": "etc", 
                    "readOnly": true
                }
            ]
        }
    ], 
    "environment": {
        "XPS1": "Test", 
        "XPS2": "Rest"
    }, 
    "executorResources": {
        "cpus": 0.2, 
        "disk": 50, 
        "mem": 64
    }, 
    "id": "/foo", 
    "labels": {
        "note": "Away from olympus", 
        "owner": "zeus"
    }, 
    "networks": [
        {
            "mode": "container", 
            "name": "my-network"
        }
    ], 
    "scaling": {
        "instances": 1, 
        "kind": "fixed"
    }, 
    "scheduling": {
        "backoff": {
            "backoff": 1, 
            "backoffFactor": 1.15, 
            "maxLaunchDelay": 3600
        }, 
        "killSelection": "YOUNGEST_FIRST", 
        "unreachableStrategy": {
            "expungeAfterSeconds": 600, 
            "inactiveAfterSeconds": 300
        }, 
        "upgrade": {
            "maximumOverCapacity": 1, 
            "minimumHealthCapacity": 1
        }
    }, 
    "user": "root", 
    "version": "2017-02-22T22:55:14.765Z", 
    "volumes": [
        {
            "host": "/hdd/tools/docker/registry", 
            "name": "etc"
        }
    ]
}

 jason@marvin  ~/src/marathon   master  http :8080/v2/groups
HTTP/1.1 200 OK
Cache-Control: no-cache, no-store, must-revalidate
Content-Encoding: gzip
Content-Type: application/json; qs=2
Date: Wed, 22 Feb 2017 22:55:20 GMT
Expires: 0
Pragma: no-cache
Server: Jetty(9.3.6.v20151106)
Transfer-Encoding: chunked
Vary: Accept-Encoding, User-Agent
X-Marathon-Leader: http://marvin:8080

{
    "apps": [
        {
            "args": null, 
            "backoffFactor": 1.15, 
            "backoffSeconds": 1, 
            "cmd": "cat", 
            "constraints": [], 
            "container": null, 
            "cpus": 1, 
            "dependencies": [], 
            "disk": 0, 
            "env": {}, 
            "executor": "", 
            "fetch": [], 
            "gpus": 0, 
            "healthChecks": [], 
            "id": "/as", 
            "instances": 1, 
            "ipAddress": null, 
            "killSelection": "YOUNGEST_FIRST", 
            "labels": {}, 
            "maxLaunchDelaySeconds": 3600, 
            "mem": 128, 
            "portDefinitions": [
                {
                    "labels": {}, 
                    "name": "default", 
                    "port": 10000, 
                    "protocol": "tcp"
                }
            ], 
            "ports": [
                10000
            ], 
            "readinessChecks": [], 
            "requirePorts": false, 
            "residency": null, 
            "secrets": {}, 
            "storeUrls": [], 
            "taskKillGracePeriodSeconds": null, 
            "unreachableStrategy": {
                "expungeAfterSeconds": 600, 
                "inactiveAfterSeconds": 300
            }, 
            "upgradeStrategy": {
                "maximumOverCapacity": 1, 
                "minimumHealthCapacity": 1
            }, 
            "uris": [], 
            "user": null, 
            "version": "2017-02-17T23:32:00.358Z", 
            "versionInfo": {
                "lastConfigChangeAt": "2017-02-17T23:32:00.358Z", 
                "lastScalingAt": "2017-02-17T23:32:00.358Z"
            }
        }
    ], 
    "dependencies": [], 
    "groups": [], 
    "id": "/", 
    "pods": [
        {
            "id": "/foo", 
            "instances": [], 
            "lastChanged": "2017-02-22T22:55:20.726Z", 
            "lastUpdated": "2017-02-22T22:55:20.726Z", 
            "spec": {
                "containers": [
                    {
                        "endpoints": [
                            {
                                "containerPort": 80, 
                                "hostPort": 0, 
                                "name": "httpendpoint", 
                                "protocol": [
                                    "tcp"
                                ]
                            }
                        ], 
                        "exec": {
                            "command": {
                                "shell": "sleep 100"
                            }, 
                            "overrideEntrypoint": true
                        }, 
                        "image": {
                            "forcePull": false, 
                            "id": "mesosphere/marathon:latest", 
                            "kind": "DOCKER"
                        }, 
                        "labels": {
                            "note": "Away from olympus", 
                            "owner": "zeus"
                        }, 
                        "lifecycle": {
                            "killGracePeriodSeconds": 60
                        }, 
                        "name": "container1", 
                        "resources": {
                            "cpus": 1, 
                            "disk": 0, 
                            "gpus": 0, 
                            "mem": 128
                        }, 
                        "user": "root", 
                        "volumeMounts": [
                            {
                                "mountPath": "/mnt/etc", 
                                "name": "etc", 
                                "readOnly": true
                            }
                        ]
                    }
                ], 
                "environment": {
                    "XPS1": "Test", 
                    "XPS2": "Rest"
                }, 
                "executorResources": {
                    "cpus": 0.2, 
                    "disk": 50, 
                    "mem": 64
                }, 
                "id": "/foo", 
                "labels": {
                    "note": "Away from olympus", 
                    "owner": "zeus"
                }, 
                "networks": [
                    {
                        "mode": "container", 
                        "name": "my-network"
                    }
                ], 
                "scaling": {
                    "instances": 1, 
                    "kind": "fixed"
                }, 
                "scheduling": {
                    "backoff": {
                        "backoff": 1, 
                        "backoffFactor": 1.15, 
                        "maxLaunchDelay": 3600
                    }, 
                    "killSelection": "YOUNGEST_FIRST", 
                    "unreachableStrategy": {
                        "expungeAfterSeconds": 600, 
                        "inactiveAfterSeconds": 300
                    }, 
                    "upgrade": {
                        "maximumOverCapacity": 1, 
                        "minimumHealthCapacity": 1
                    }
                }, 
                "user": "root", 
                "version": "2017-02-22T22:55:14.765Z", 
                "volumes": [
                    {
                        "host": "/hdd/tools/docker/registry", 
                        "name": "etc"
                    }
                ]
            }, 
            "status": "DEGRADED", 
            "statusSince": "2017-02-22T22:55:20.726Z", 
            "terminationHistory": []
        }
    ], 
    "version": "2017-02-17T23:32:00.358Z"
}
`

That looks like podStatus to me!

**Comment by jasongilanfarr** [comment]
Interestingly, this is not actually a bug at all, only the fix is a bug. I'm going to revert the "fix". As I verified, the Groups.raml matches GroupsResource (GroupInfoWrites in Formats.scala is actually not used at all).

**Comment by jasongilanfarr** [comment]
Furthermore, the raml doesn't specify Deployments as a proper raml type and the Groups aren't in it anyways.
