### ISSUE TITLE
HA is broken if marathon is not leading from the same host as the mesos-master

### ISSUE THREAD

**Issue by tomwganem** [mesosphere/marathon#5239]
versions:
```
Mesos 1.0.0
Marathon 1.3.0
```
Setup is three servers, each running the zookeeper, mesos-master and marathon services (plus consul and dnsmasq for internal hostname resolution) Additionally, there are 6 slaves running the mesos-agent service (as well as consul and dnsmasq).

Command line flags for mesos-master
```
  --cluster='dev' \
  --credentials='/var/lib/mesos/credentials' \
  --hostname='01.mesos-master.service.internal.asperafiles.com' \
  --ip='10.114.81.17' \
  --log_dir='/var/log/mesos' \
  --logging_level='INFO' \
  --port=5050 \
  --quorum=2 \
  --work_dir='/var/lib/mesos' \
  --zk='zk://01.zookeeper.service.internal.asperafiles.com:2181,02.zookeeper.service.internal.asperafiles.com:2181,03.zookeeper.service.internal.asperafiles.com:2181/mesos'
```

Command line flags for marathon
```
--hostname 01.marathon.service.internal.asperafiles.com 
--master zk://01.zookeeper.service.internal.asperafiles.com:2181,02.zookeeper.service.internal.asperafiles.com:2181,03.zookeeper.service.internal.asperafiles.com:2181/mesos
--zk zk://01.zookeeper.service.internal.asperafiles.com:2181,02.zookeeper.service.internal.asperafiles.com:2181,03.zookeeper.service.internal.asperafiles.com:2181/marathon
```

all hostnames are resolvable

I'm starting with mesos-master and marathon leading on server 01.mesos-master.service.internal. with no tasks running.

![screen shot 2017-02-21 at 11 59 14 am](https://cloud.githubusercontent.com/assets/4089491/23237810/f45d386c-f913-11e6-9b2e-bdc62565675c.png)
![screen shot 2017-02-21 at 11 59 16 am](https://cloud.githubusercontent.com/assets/4089491/23237826/fd293b1c-f913-11e6-8609-64b4933fe9a3.png)
I start a simple task:
![screen shot 2017-02-21 at 11 59 53 am](https://cloud.githubusercontent.com/assets/4089491/23237834/072fbd70-f914-11e6-8166-ccbf2817ebb6.png)
See that marathon is running it fine.
![screen shot 2017-02-21 at 12 01 12 pm](https://cloud.githubusercontent.com/assets/4089491/23237841/0f6bfab2-f914-11e6-9964-ac3e269d39f7.png)
I force a leader election. marathon is now leading at 03.mesos-master.service.internal/03.marathon.service.internal
![screen shot 2017-02-21 at 12 01 38 pm](https://cloud.githubusercontent.com/assets/4089491/23237855/1e194a1a-f914-11e6-8bed-5709bd7ce570.png)
I then try to suspend the task in the marathon ui. I use the ui for the leading marathon service.
![screen shot 2017-02-21 at 12 02 55 pm](https://cloud.githubusercontent.com/assets/4089491/23237881/3ef7b8ca-f914-11e6-90ee-a5b46908f046.png)
![screen shot 2017-02-21 at 12 03 14 pm](https://cloud.githubusercontent.com/assets/4089491/23237888/43c2c142-f914-11e6-8566-2c02df0e2fc4.png)
The task is still running
![screen shot 2017-02-21 at 12 03 23 pm](https://cloud.githubusercontent.com/assets/4089491/23237899/515c4abc-f914-11e6-93a3-7478a5cc2e90.png)
Eventually marathon marks the task as suspended, but I still see that the task is running in the mesos ui
![screen shot 2017-02-21 at 12 27 01 pm](https://cloud.githubusercontent.com/assets/4089491/23237915/68092a32-f914-11e6-9abe-78cbc0ac29d4.png)
![screen shot 2017-02-21 at 12 27 06 pm](https://cloud.githubusercontent.com/assets/4089491/23237923/6fa269c0-f914-11e6-9560-e69f1b0067f1.png)

I've been experimenting with all sorts of different configurations. I've tried upgrading marathon and mesos. I've tried ips instead of hostnames. I can't seem to resolve this issue. We've actually been running mesos and marathon for a year and a half and it seems that this issue exists in all of our clusters. If this is a configuration issue, please help me figure out what I'm doing wrong. As is it, any errant marathon leader election keeps us from deploying/controlling our applications.

**Comment by tomwganem** [comment]
[logs.zip](https://github.com/mesosphere/marathon/files/795199/logs.zip)

Here are some logs from my experiment above.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4093. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
