### ISSUE TITLE
Dont want marathon to relaunch a job which was running on the slave node after the node goes for a reboot

### ISSUE THREAD

**Issue by swati1909** [mesosphere/marathon#5247]
I have a single node cluster and submitted a job to marathon. I rebooted this node while the job was running. when the node comes up, I see that marathon still shows the job in RUNNING state though the job is actually not running on the mesos-master. I see that marathon gets a TASK_LOST status for this job and reschedules this job.

I want to be able to configure marathon to not restart once the job is LOST, How can I achieve this?

**Comment by tobilg** [comment]
Have you seen https://mesosphere.github.io/marathon/docs/configure-task-handling.html

**Comment by swati1909** [comment]
Thanks  for the reply, but, I guess this is available only on marathon version 1.4+. I have marathon version 1.3.6 and looking for a way to do this in this version.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4259. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
