### ISSUE TITLE
Pick all test-fixes from master to 1.4 branch

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#5249]

**Comment by unterstein** [comment]
https://github.com/mesosphere/marathon/pull/5290

**Comment by unterstein** [comment]
Currently in testing on CI, could be rebased and pushed to release/1.4 if tests passed

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2241. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
