### ISSUE TITLE
Submitting an invalid `killSelection` to `/app` will return an empty error message

### ISSUE THREAD

**Issue by mlunoe** [mesosphere/marathon#5252]
---
ℹ️ Related PR: https://github.com/dcos/dcos-ui/pull/1952
ℹ️ Related Jira Ticket: https://jira.mesosphere.com/browse/DCOS_OSS-653

---

Submitting this app configuration:
```js
{
  "id": "/mlunoe/marathon-errors",
  "instances": 1,
  "cpus": 0.01,
  "mem": 0,
  "container": {
  "type": "DOCKER",
    "docker": {
      "image": "redis"
    }
  },
  "killSelection": "YoungestFirst"
}
```
will make Marathon return and empty error message:
`{message: null}`

Expected: An error message with details to fix the issue. `killSelection` might not be appropriate to submit initially, but I still would not expect Marathon to ever provide me with an empty error message.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4310. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
