### ISSUE TITLE
Odd value accepted by Marathon API, and not explanatory error message.

### ISSUE THREAD

**Issue by mlunoe** [mesosphere/marathon#5253]
---
ℹ️ Related to this issue: https://github.com/mesosphere/marathon/issues/5077

---

Marathon version: 1.4.0-RC9

When I submit this app config:
```js
{
  "id": "/mlunoe/constraints",
  "cmd": "sleep 9999",
  "instances": 1,
  "cpus": 0.1,
  "constraints": [
    [
      "five",
      "MAX_PER"
      "foo"
    ]
  ]
}
```
I receive this API response:
```js
{
  "message": "Object is not valid",
  "details": [
    {
      "path": "/constraints",
      "errors": [
        "Value was specified but is not a number"
      ]
    }
  ]
}
```

Expected a more explanatory error message like: "Must only contain characters between 0-9 for operator MAX_PER" (or GROUP_BY for that matter).
I also would expect to be able to provide the number `2`, which the API does not accept at this point.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4284. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
