### ISSUE TITLE
Missing buildref in Marathon 1.4 deb

### ISSUE THREAD

**Issue by janisz** [mesosphere/marathon#5255]
Marathon installed from Mesosphere deb does not have buildref

* **Log:**
> Starting Marathon 1.4.1/unknown with  (mesosphere.marathon.MarathonApp:main)

* **GET** `/v2/info`:

```json
"name": "marathon",
"version": "1.4.1",
"buildref": "unknown",
```

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4723. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
