### ISSUE TITLE
Marathon API call using private docker Hub Image  causes Mesos Agent not to find image

### ISSUE THREAD

**Issue by pvcon13** [mesosphere/marathon#5256]
Where do I get support if not here? Please see this thread:
**https://groups.google.com/forum/#!topic/marathon-framework/pKSPbEQmuyo**

**Marathon** Version  **1.1.1**           (as deployed by rancher catalog -Rancher v 1.41) 
     **Docker** Version      **1.12.6**
         **Mesos** Version       **0.28.1**         (as deployed by rancher catalog -Rancher v 1.41) 
            **Ubuntu** Version      **16.04.01 LTS**

Docker Logs report "not authenticated". Mesos Slave (agent) Sandbox, sees the referenced Credentials File and stores correctly in the Sandbox. Sandbox stderror cannot find the docker image if private and never loaded, or if private and previously loaded and forcepull=true.

Have tried manually creating creds file (ssh in marathon instance, login into docker , finds .docker in HOME.) Can do docker pull of private image once logged in as such. Have created a remote API endpoint that returns those creds as well. 

Curling the private repo with auth token/repo ID shows only public not private repos. But as I said logging in (to docker) with those creds let me pull the image from same server when private. According to docker doc, that is correct, the creds should not list private docker images as per **https://docs.docker.com/docker-hub/repos/#private-repositories**

Where can I get help with Mesos Agent not finding a private docker hub image when call by Marathon script? With all  Marathon scripts running and failing, actively changing the private repo to public suddenly unblocks the process without any additional incident. 

Attached are the **creds that sandbox stored**, and the **marathon calling script**, the **docker logs** on the marathon instance, the **container logs** of one of the mesos agents, the **sandbox standarderror** and **Marathon Logs**. 

Thanks for pointing me in the correct directiion :)

[config.txt](https://github.com/mesosphere/marathon/files/802200/config.txt)

[marathonscript.txt](https://github.com/mesosphere/marathon/files/802203/marathonscript.txt)

[dockerlog.txt](https://github.com/mesosphere/marathon/files/802204/dockerlog.txt)

[mesos slave logs.txt](https://github.com/mesosphere/marathon/files/802207/mesos.slave.logs.txt)

[stderr.txt](https://github.com/mesosphere/marathon/files/802209/stderr.txt)

[Marathon-1.1.1-logs-launching from private docker hub.txt](https://github.com/mesosphere/marathon/files/802212/Marathon-1.1.1-logs-launching.from.private.docker.hub.txt)

Thank you

**Comment by pvcon13** [comment]
Can anyone tell me where I can post this to get some guidance?  

Even if I manually add the credentials to every Mesos Slave Agent, as long as forcePullimage is true, or if that container never used that image before, if the image is in a private docker hub repo, it errors out on mesos agent slave as not being able to"find" the file. if public no issue.

Could this older version of mesos and especially Marathon not be working correctly with the newer docker version listed above? If so should I downrev to an older version of docker?  How old would that docker version be?

Where/who can I contact to trouble shoot this? Only being able to run public images is a show stopper.....

Too bad I cannot just pass in the info and let marathon/mesos build it own image..  

Thank you anyone that can point me to help

**Comment by janisz** [comment]
I think it's an issue with Docker containerizer. Post your question on [mesos mailing list](http://mesos.apache.org/community)

**Comment by pvcon13** [comment]
Thank you sir

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4140. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
