### ISSUE TITLE
Deleting groups broken?

### ISSUE THREAD

**Issue by b0e** [mesosphere/marathon#5257]
Marathon: 1.4.1
Mesos: 1.1.0
openjdk: 1.8.0
OS: Ubuntu 16.04.2

Hi,

since the update to marathon 1.4.0/1.4.1 i cannot delete groups with running applications inside. Both, UI and API, return HTTP 200 and i also get a deployment id, but nothing happens. Deleting empty groups still works fine.

Can somebody confirm/deny this behavior? Do you need more information? How can i collect more detailed information for debugging? Setting --logging_level=debug didn't provide more information for group deletion. Since there was only 1 day between 1.4.0 and 1.4.1 i'm not sure which release introduced this behavior. With 1.3.10 deleting groups worked as expected.

Marathon log: 
Feb 27 14:10:50 mymaster marathon[14232]: [2017-02-27 14:10:50,499] INFO  10.10.10.10 - nwsadmin [27/Feb/2017:13:10:49 +0000] "DELETE https://mymaster:8443/v2/groups//products/development/foobar HTTP/1.1" 200 92

Mesos log:
nothing at all

Regards, b0e

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4767. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
