### ISSUE TITLE
write migration unit test for D201

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#5258]
discussed with @aquamatthias and decided that, in the interest of landing D201 sooner than later, unit tests would be added after D201 lands.

**Comment by jdef** [comment]
xref #4972

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4105. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
