### ISSUE TITLE
Define System Integration Test Matrix in Jenkinsfile.si

### ISSUE THREAD

**Issue by jeschkies** [mesosphere/marathon#5259]
So far we define [nightly-marathon-master-matrix-si](https://jenkins.mesosphere.com/service/jenkins/view/Marathon/job/System%20Integration%20Tests/job/nightly-marathon-master-matrix-si) which creates a cluster and triggers the SI test defined in `Jenkinsfile.si`. We should define the job in a Jenkinsfile so that it is code reviewed.

We can probably avoid calling another job by executing several jobs in parallel on different nodes.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2639. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
