### ISSUE TITLE
Resident tasks, if killed while unreachable, results in no effect

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#5261]
When we kill an ephemeral unreachable task, it is marked for kill if it comes back. This behavior is explicitly not applied for resident tasks because, with the way things are implemented, it would lead to the reservations to be released, also (even though "kill and wipe" is not specified).

Kill and wipe is still supported while the task is unreachable.

This issue is to make note of the limited fix state for https://github.com/mesosphere/marathon/issues/5207

Reserved resources and tasks are tightly coupled, and fixing this completely led to some very awkward work-arounds. We decided to postpone fixing this aspect of the behavior, for now.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4570. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
