### ISSUE TITLE
MESOS_xx health checks not listed in GUI

### ISSUE THREAD

**Issue by turb** [mesosphere/marathon#5262]
Since 1.4.0, MESOS_xxx has been introduced (#4168).

However, MESOS_HTTP and MESOS_TCP are not listed in the available health check protocols drop-down in the configuration editor.

![health](https://cloud.githubusercontent.com/assets/490098/23411924/2c0cdc94-fdd4-11e6-8356-068775e14060.PNG)

This is non-blocking since it is still possible to change it using "JSON" mode, and of course using the API.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4811. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
