### ISSUE TITLE
Create Cancellation Context

### ISSUE THREAD

**Issue by jasongilanfarr** [mesosphere/marathon#5263]
In preparing for more robust Deployment Plans (supporting rollback, cancellation, etc) and other Actions, we should add an opt-in Thread Local Storage like entity for Cancellation.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2665. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
