### ISSUE TITLE
KillServiceActorTest is unstable

### ISSUE THREAD

**Issue by jeschkies** [mesosphere/marathon#5273]
marathon-unstable-loop report from March 1st

```
    20 mesosphere.marathon.core.task.termination.impl.KillServiceActorTest:The KillServiceActor when asked to kill a single known instance should issue a kill to the driver
Sample size: 93
```

**Comment by unterstein** [comment]
Runs for hours on local machine and on nuc without failures. Closing this issue therefore

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2215. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
