### ISSUE TITLE
RestartIntegrationTest is unstable

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#5278]

**Comment by jdef** [comment]
https://jenkins.mesosphere.com/service/jenkins/job/public-test-marathon-phabricator/1622/testReport/junit/mesosphere.marathon.integration/RestartIntegrationTest/Restarting_Marathon_when_readiness_should_deployment_with_1_ready_and_1_not_ready_instance_is_continued_properly_after_a_restart/

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1840. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
