### ISSUE TITLE
Move packer script for Jenkins nodes to Marathon master

### ISSUE THREAD

**Issue by jeschkies** [mesosphere/marathon#5283]
We want to maintain a script that provisions an AMI for Jenkins nodes so we save time during builds.

**Comment by jeschkies** [comment]
In review https://phabricator.mesosphere.com/D568

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1996. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
