### ISSUE TITLE
Improving Marathon Scaling Up

### ISSUE THREAD

**Issue by kensipe** [mesosphere/marathon#5285]
Apparently it is possible to reduce the time of scaling by controlling the scaling external to marathon, resulting in a reduction of deployment time from 4 hours to less than 1 hour.   This is handled by an exponential decay: https://github.com/mesosphere/marathon/blob/master/tests/scale/test_marathon_cap.py#L37

If this is the case, this should just be a feature inside of marathon.

**Comment by jdef** [comment]
I'm sure it's lack of caffeine, but I don't understand what this is saying.
Can you elaborate?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1778. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
