### ISSUE TITLE
Adapt documentation for PATCH

### ISSUE THREAD

**Issue by unterstein** [mesosphere/marathon#5291]
As follow up for the pure `forward port` for `PATCH` support in https://github.com/mesosphere/marathon/issues/5162, documentation should be adapted accordingly, like described in review comments https://phabricator.mesosphere.com/D552

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2670. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
