### ISSUE TITLE
List bugfixes on master not on releases/1.4

### ISSUE THREAD

**Issue by unterstein** [mesosphere/marathon#5292]

**Comment by unterstein** [comment]
+ 456af52b3aa39b31930e7d031d5ce1639694cdb7 Hide Pod and AppRepository - Group owns them (#4824).
+ 6c0149d0d1592bb0bc5509a1b5e4770605f87905 Disallow usage of Command Checks on Pods until mesos supports them (#4872)
+ c8924aa8d3a21346a7728c881d6378dc969e320c Inform the rate limiter for pods and apps (#4863)
+ eeb2fb94433b3e8b976b1876816fd87d50a8f71b Fixes #4902 by removing maxInstances from the Raml spec and all usages of this property.
+ 40d19f4ad0e2871adff0132365d836de4438c0a6 Apply NetworkInfo changes introduced in 1.4
+ 14177b0119c91c8687296893a9755ad71ee79b3a Fixes #4932 | GET on empty apps list result 500 exception (#4940)
+ cbb1df7f49ebc751643c323b9cf522997a0f47d3 Fixes #4948 | Lazy event parsing (#4986)
+ a8a8bc140de11e08de41ca5feab17517d14d1336 fixing recovery errors for groups.  adding metadata resource file
+ f441c571beb445271be6b00fa097ed2f4c6ad7f3 ForceExpunge for missing task is a no-op, rather than a failure
+ 94efcee727612559ca227af4adce3a458281ee2c Initial stab at making deployment plans cheaper.
+ f924d81cc1756c11d1b778700081616f820035a5 Fixes #4901 by removing the short circuit for root group changes.
+ c3be7e07d16f791abe0aa4cd8abbdd41911ab28b Use the latest stable Marathon UI build (#5181)

**Comment by unterstein** [comment]
All commits subject to discuss if they should be picked to 1.4

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2312. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
