### ISSUE TITLE
Queue with Reject Statistics Doesn't have Rate Limiting Reasons

### ISSUE THREAD

**Issue by kensipe** [mesosphere/marathon#5296]
The marathon `/v2/queue` contains a summary of reasons tasks were rejected regarding resources and constraints.   It does NOT contain rate limiting reasons like launch token.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-2410. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
