### ISSUE TITLE
Group Endpoint (for UI) at high scale creates a 22M response

### ISSUE THREAD

**Issue by kensipe** [mesosphere/marathon#5298]
This endpoint is commonly called by the DCOS UI:  https://35.185.52.108/service/marathon/v2/groups?_timestamp=1488473593961&embed=group.groups&embed=group.apps&embed=group.pods&embed=group.apps.deployments&embed=group.apps.counts&embed=group.apps.tasks&embed=group.apps.taskStats&embed=group.apps.last

It produces a 22M response and can take around 9s.

**Comment by jdef** [comment]
Can we add gzip compression to the response entity as a partial bandaid?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1982. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
