### ISSUE TITLE
Docker Containerizer and GPU resources

### ISSUE THREAD

**Issue by EMChamp** [mesosphere/marathon#5299]
Are there any plans to add GPU resources support to the docker containerizer. I see in this issue it was planned to add after the docker containerizer is finished: https://github.com/mesosphere/marathon/pull/4112

For those who want to use the docker containerizer and also consume/isolate GPU resources, what are our options currently?

**Comment by jdef** [comment]
AFAIK we're awaiting Mesos support for GPU in the docker containerizer: https://issues.apache.org/jira/browse/MESOS-5795

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4794. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
