### ISSUE TITLE
app killSelection isn't persisted

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#5300]
AppDefinition's `toProto` and `fromProto` don't do anything to save or load `killSelection` from protobuf.

The fix for this should probably be backported to 1.4.

**Comment by jdef** [comment]
blocking for D201

**Comment by jdef** [comment]
the commit (https://github.com/mesosphere/marathon/commit/f1d3f7b43499b14401dcd567134038f2fab6cf9f) looks reasonable to me, but it should land in master first, then backport to 1.4

**Comment by timcharper** [comment]
Agreed, I was planning on doing this.

Patch for master: https://phabricator.mesosphere.com/D581

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1682. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
