### ISSUE TITLE
Unsupported Media Type for POST requests

### ISSUE THREAD

**Issue by krestjaninoff** [mesosphere/marathon#5301]
After the latest update (1.3.8), I noticed that my script, which restarts the app, fails with HTTP Error 415: Unsupported Media Type".

I specified all the headers from the [API documentation](https://github.com/mesosphere/marathon/blob/master/docs/docs/rest-api.md#user-content-post-v2appsappidrestart) for POST method (btw, why do we need them for "restart" endpoint?) but without any luck:

```
curl -X POST -H "Accept-Encoding: gzip, deflate, compress" -H "Content-Length: 0" -H "Accept: application/json" "http://example.org/marathon/v2/apps/datalore/hazelcast/restart?force=true"

{"message":"Unsupported Media Type"}
```

Once I added "Content-type: application/json" (which is actually the only mandatory header), my problem was solved.

Do I miss something or that is a bug in the docs?

**Comment by jdef** [comment]
It doesn't look like we parse a request entity here, so I'd argue that the
docs are right and the impl is wrong

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4645. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
