### ISSUE TITLE
Unable to establish SSL communication between  zookeeper and marathon

### ISSUE THREAD

**Issue by sriram-ranga** [mesosphere/marathon#5302]
I am having issues in enabling SSL communication  between zookeeper and marathon. I followed the steps given in https://cwiki.apache.org/confluence/display/ZOOKEEPER/ZooKeeper+SSL+User+Guide to enable to enable SSL. When I start marathon after making the changes , I see the following error messages and marathon is not launching. 

zookeeper logs :

EXCEPTION: org.jboss.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record:
0000002d0000000000000000000000000000ea600000000000000......
org.jboss.netty.handler.ssl.NotSslRecordException: not an SSL/TLS record:
0000002d0000000000000000000000000000ea6000000000000000000010000000000000
at org.jboss.netty.handler.ssl.SslHandler.decode(SslHandler.java:857)
at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:425)
at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)........

marathon logs:
ZOO_ERROR@handle_socket_error_msg@1643: Socket [<HOST>:2281] zk retcode=-7, errno=110(Connection timed out): connection to <HOST>:2281 timed out (exceeded timeout by 11ms)

marathon version used  : **0.16-SNAPSHOT**
zookeeper version : **3.5.2-alpha** 

The changes suggested in the zookeeper WIKI are very simple. But it doesnt seem to work . 

Can someone help in resolving the issue ?

**Comment by jasongilanfarr** [comment]
We don't currently support ssl + zk. If I'm not mistaken, it's only
available in alpha editions.

**Comment by jasongilanfarr** [comment]
Of zk.

**Comment by sriram-ranga** [comment]
Thanks for prompt response.  I am using zookeeper version : 3.5.2-alpha. I did change the zookeeper version marathon is using and rebuilt marathon jar. Still I am getting the same error. 
Can you clarify on when we can expect the support for   ssl + zk?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4454. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
