### ISSUE TITLE
persistent volume maxSize isn't persisted to ZK

### ISSUE THREAD

**Issue by jdef** [mesosphere/marathon#5303]
https://github.com/mesosphere/marathon/blob/366697b7274053b1612609d6c8e7b9810c7aaf27/src/main/scala/mesosphere/marathon/api/serialization/ContainerSerializer.scala#L112

**Comment by jdef** [comment]
funny enough, the protobuf has a field called `maxSize` but volume serialization doesn't actually save it. however `fromProto` does appear to read it in.

whoever fixes this might want to consolidate the `toProto` and `fromProto` in the same source file - surely that played a part in oversight leading to this bug.

**Comment by jdef** [comment]
xref https://github.com/mesosphere/marathon/blob/366697b7274053b1612609d6c8e7b9810c7aaf27/src/main/scala/mesosphere/marathon/state/Volume.scala#L201

**Comment by jdef** [comment]
https://phabricator.mesosphere.com/D577

**Comment by jdef** [comment]
blocking for D201

**Comment by jdef** [comment]
decided against relocating any toProto/fromProto code to make for an easier cherry-pick back to 1.4. relocation can happen after D577 lands

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1725. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
