### ISSUE TITLE
After scaling application definition is lost when Marathon restarts

### ISSUE THREAD

**Issue by ojagodzinski** [mesosphere/marathon#5305]
```
Marathon version: 1.3.10 
Mesos version: 1.0.2
```

When app scaling action is made more than _zk_max_version_ times and then Marathon is restarted application configuration (and health checks conf) are lost.

There is WARN in log:
> WARN Cannot find health check configuration for [appname] and version [date], using most recent one. (mesosphere.marathon.core.health.impl.MarathonHealthCheckManager:ForkJoinPool-2-worker-151)

but as in: https://github.com/mesosphere/marathon/blob/17d27b6acf3e202f5113a401ab39e176135efb46/src/main/scala/mesosphere/marathon/core/health/impl/MarathonHealthCheckManager.scala#L172 health check configuration is not copied and task is in _Unknown_ state.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4338. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.

**Comment by janisz** [comment]
It looks like it could be solved by https://github.com/mesosphere/marathon/pull/4178 in 1.4
