### ISSUE TITLE
Test: create new issue in github should be closed automatically and create a new JIRA ticket.

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#5339]
This is the comment.

**Comment by aquamatthias** [comment]
The issue was closed by the bot. What happens to comments in the issue?

**Comment by janisz** [comment]
@aquamatthias Once bot migrate an issue it should [lock conversation](https://help.github.com/articles/locking-conversations/) to prevent comments or migrate comments when they appears. IMHO github issues should be disabled.

**Comment by aquamatthias** [comment]
I locked all existing issues. 
@artemharutyunyan can you change your script, so new github issues are also closed and locked?
