### ISSUE TITLE
Issues with deploying rabbitmq exporter via mesos marathon

### ISSUE THREAD

**Issue by xbblq7n** [mesosphere/marathon#5340]
Hi,

I am facing issues with deploying rabbitmq exporter via marathon.
I have deployed rabbitmq via marathon as well.
The below command works fine when deployed directly from the server.
docker run -d --net=container:my-rabbit kbudde/rabbitmq-exporter

But in Marathon the network settings allows only bridged,host and user settings and there is no option for container network.
**--net=container:my-rabbit**
Also, since the rabbitmq is deployed via marathon the containerID and Container Name will change after every restart so this will also create problem with container network mapping.

Without the container network map the image works but does not captures the metrics.

Is there a way to run this using bridged mode.

https://docs.docker.com/engine/reference/run/#network-settings
https://docs.mesosphere.com/1.8/usage/managing-services/service-ports/

Regards
Dinesh KR

**Comment by jeschkies** [comment]
@xbblq7n I replied on JIRA. Could you comment there?

**Comment by ichernetsky** [comment]
@vivekbny, I replied in JIRA too. Could you please take a look at it?
