### ISSUE TITLE
Port 10000 in portDefinitions instead of specified port on first deploy

### ISSUE THREAD

**Issue by mrkam** [mesosphere/marathon#5346]
I deploy my app to Marathon using Jenkins plugin. It uses marathon.json document containing the following port definitions:

```
  "portDefinitions": [
    {
      "port": 31609,
      "protocol": "tcp",
      "labels": {}
    }
  ],
  "requirePorts": true
```

When the app is deployed for the first time, it always ends up with the following port definitions instead:

```
  "portDefinitions": [
    {
      "port": 10000,
      "protocol": "tcp",
      "labels": {}
    }
  ],
  "requirePorts": true
```

And I have to manually edit the config in Marathon UI so it can deploy (port 10000 is not available).

Marathon Version 1.3.6

**Comment by timcharper** [comment]
@mrkam hi! Please follow the JIRA link and be sure to click "watch this issue" in order to receive updates
