### ISSUE TITLE
Documentation related to ports is not clear enought

### ISSUE THREAD

**Issue by jorgenota** [mesosphere/marathon#5357]
I'm trying to understand how ports configuration works in Marathon and I've found that documentation (https://mesosphere.github.io/marathon/docs/ports.html) about it is not clear enought (at least for me...). There are lots of networking modes and attributes to set ports and I feel it's a bit confusing.

For example:

- Definitions of USER and BRIDGE networking seem to be the same. 
- Definition of servicePort doesn't explain what it is used for. It's explained in a different paragraph, in the examples section...

In general, there is a lot of text but I think it could be more concise and better organized, taking into account that it's a key section.

**Comment by unterstein** [comment]
Hey @jorgenota,

thanks for reporting. The complete networking configuration was re-written recently and therefore the documentation changed a lot. In you go to https://github.com/mesosphere/marathon/blob/master/docs/docs/ports.md you should find a better description.

To address one of your questions directly:
- User network mode is different to bridge mode. If you are using a bridged network, this is related to your one host bridge network. On the other hand you can install multiple network providers (e.g. https://www.weave.works/) you could join multiple of those CNI networks and get a ip per container.

If you have further questions, just comment on jira.

Best
Johannes
