### ISSUE TITLE
Why am I using instance to create pods wrong?

### ISSUE THREAD

**Issue by big-loser** [mesosphere/marathon#5367]
Why am I using instance to create pods wrong?

https://mesosphere.github.io/marathon/docs/pods.html#endpoints

{
  "id": "/pod-with-healthcheck",
  "scaling": { "kind": "fixed", "instances": 1 },
  "containers": [
    {
      "name": "sleep1",
      "exec": { "command": { "shell": "sleep 1000" } },
      "resources": { "cpus": 0.1, "mem": 32 },
      "image": {
        "id": "nginx",
        "kind": "DOCKER"
      },
      "endpoints": [ { "name": "web", "containerPort": 80, "protocol": [ "http" ] } ],
      "healthCheck": { "http": { "endpoint": "web", "path": "/ping" } }
    }
  ],
  "networks": [ { "mode": "container", "name": "my-virtual-network-name" } ]
}

![qq 20170424182925](https://cloud.githubusercontent.com/assets/10458694/25333258/1da5b464-291c-11e7-9760-9a4993832678.jpg)

I think it should be the name of the network. 

After I changed the name of the virtual network, the problem still exists

![image](https://cloud.githubusercontent.com/assets/10458694/25333344/6233dab6-291c-11e7-8458-4bd3b483452b.png)

**Comment by jeschkies** [comment]
@big-loser, could check out the linked JIRA. We will reply there. Thanks.
