### ISSUE TITLE
How can I run multiple instances of an App on one same mesos slave node ?

### ISSUE THREAD

**Issue by sfwn** [mesosphere/marathon#5377]
Detail:
CONTAINER RUNTIME: Docker Engine

For now, I cannot find how to deploy multiple instances of an same app on one same mesos slave node. 

Please help me. Thank you !

**Comment by jeschkies** [comment]
@sfwn, could take a look at the JIRA ticket [MARATHON-7294](https://jira.mesosphere.com/browse/MARATHON-7294). What are your thoughts?
