### ISSUE TITLE
how to recover inactive marathon framework in mesos

### ISSUE THREAD

**Issue by modeyang** [mesosphere/marathon#5382]
env : mesos 1.0.1 + marathon 1.3.0
- I found marathon framework id changed in mesos after upgrade marathon version from 1.1.2 to 1.3.0, and the previous framework  with all running tasks moved to inactive frameworks, then the new version marathon has nothing apps on it;  
- even degrade marathon to 1.1.2,  the framework id also changed and could not saw any apps. this's so Weird,!   
- and  more in mesos path ```/var/lib/mesos/slaves/f4d7eb5a-5ec5-440f-b41a-ddf2e17c7434-S32/frameworks```,  only found old framework folder ```2b2a4298-7855-46f5-97bb-0e9879325e5c-0000```, the new running framework ```af404bcf-df0d-4f29-b542-adc635031512-0004``` folder not exists. 

question is how to recover inactive marathon framework in mesos and control all running apps/tasks again with marathon?  any help will appreciate. 
![mesos framework info](https://github.com/modeyang/marathon-uitls/blob/master/imgs/mesos-marathon.png)

**Comment by jeschkies** [comment]
@modeyang could check out the JIRA linked. We will reply there. Thanks a lot.
