### ISSUE TITLE
Missing some deployment_success events

### ISSUE THREAD

**Issue by erickrmz** [mesosphere/marathon#5414]
Mesos 1.1.0
Marathon 1.4.2 
OS: Ubuntu 14.04.2 LTS \n \l
Kernel: Linux 3.13.0-24-generic

Hello

I wrote a small app which serves different purposes, one of them is to notify upon a deployment attempt, failure or success via email (or hipchat).

I capture all "api_post_events" and "deployment_success_event", and using information provided by these two events, I'm able to determine if an app is attempting to be deployed ("api_post_event") and once I get the related "deployment_success" event, I know that the app was successfully deployed. If I don't receive the "deployment_success" event in 10 minutes, I consider the deployment to be a failure (and notify accordingly).

The app has been working quite smoothly until yesterday. I discovered several apps did not get the "deployment_success" event, so my app thinks these app were never successfully deployed. I checked my application logs and noticed I never received these events.

It's important to mention that out of roughly 30 deployments, only 4 "failed". And also that they didn't actually fail, they were deployed fine, it's just that I never got the related deployment_success event.

Could you please help me get this sorted out? I would like to make sure the event stream is reliable.

Thanks

Erick

**Comment by unterstein** [comment]
Hi @erickrmz,

thanks for reporting! I added some questions to the JIRA ticket.

Best
Johannes
