### ISSUE TITLE
NPM Exception during running with different DEFAULT-ACCEPTED-RESOURCE-ROLES

### ISSUE THREAD

**Issue by MarcinMilewski** [mesosphere/marathon#5417]
Using the advanced installation of marathon 1.4.2 from Universe and changing DEFAULT-ACCEPTED-RESOURCE-ROLES from * to different role (for example "other") cannot start Marathon

Full stderr:
```
(AT BEGINNING OF FILE)
I0606 09:31:26.550317 13113 exec.cpp:162] Version: 1.2.1
I0606 09:31:26.555346 13129 exec.cpp:237] Executor registered on agent c7c73522-0340-4f5e-94cf-4bcb6f5c3755-S4
WARNING: Your kernel does not support swap limit capabilities, memory limited without swap.

Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "main"
```

**Comment by unterstein** [comment]
Hi @MarcinMilewski,

can you please comment the jira ticket to my following question:
- Do you have an agent which carries resources to the used resource role?

Thanks
Johannes
