### ISSUE TITLE
What is the 'instance_health_changed_event'?

### ISSUE THREAD

**Issue by oscchun** [mesosphere/marathon#5434]
Hello

I struggle to use marathon for production, then
I'm stucked in strange situation.

I have made my APP with two health check configurations.
One is always succeeds and the other is always fails. (for making container pool with my own agent)
Because I don't wanna kill my unhealthy process, I changed the 'always fail' health check config with "maxConsecutiveFailures: 0".

then with used event bus, I watched the event stream when I made APP.

*********************************************************************
event: failed_health_check_event
data: {"appId":"/test-04","instanceId":"test-04.marathon-f16ce949-65fc-11e7-bbb2-3e4c59999dee","healthCheck":{"gracePeriodSeconds":0,"intervalSeconds":10,"timeoutSeconds":5,"maxConsecutiveFailures":0,"portIndex":1,"path":"/","protocol":"HTTP","ignoreHttp1xx":false},"eventType":"failed_health_check_event","timestamp":"2017-07-11T05:51:16.480Z"}

event: health_status_changed_event
data: {"appId":"/test-04","instanceId":"test-04.marathon-f16ce949-65fc-11e7-bbb2-3e4c59999dee","version":"2017-07-11T05:51:11.435Z","alive":true,"eventType":"health_status_changed_event","timestamp":"2017-07-11T05:51:16.498Z"}

event: instance_health_changed_event
data: {"instanceId":"test-04.marathon-f16ce949-65fc-11e7-bbb2-3e4c59999dee","runSpecId":"/test-04","healthy":true,"runSpecVersion":"2017-07-11T05:51:11.435Z","timestamp":"2017-07-11T05:51:16.498Z","eventType":"instance_health_changed_event"}
*********************************************************************

above I discovered 'instance_health_changed_event' with "healty: true", though this app could never succeed to health check completely.

please explain what this situation is.

Thank you.

**Comment by unterstein** [comment]
Hi @oscchun,

please see the jira ticket.

Thanks :)
