### ISSUE TITLE
Using multiple attributes when building constraints 

### ISSUE THREAD

**Issue by rbrown-rms** [mesosphere/marathon#5462]
I'm planning on deploying a multi-tenancy environment where our DC/OS cluster will be using multiple attributes for different teams to target nodes allocated to them. 

One issue I have right now is how do I allow a specific team to target a set of nodes allocated for their use only. 

Lets assume my cluster has 6 slaves being shared by 3 different teams. 
Team 1 will have 3 nodes
Team 2 will have 2 nodes 
Team 3 will have 1 node
 
My attributes on the agent nodes would look something like 
-	clientid:1;nodetype:marathon
-	team:1;nodetype:spark
-      team:1;nodetype:marathon
-	team:2;nodetype:sandbox
-       team:2;nodetype:spark
-       team:3;nodetype:marathon

With this setup will it be possible for me to create a constraint that allows team:1 to launch their marathon jobs only on nodes where nodetype:marathon and team:1 ? 

Maybe attributes isn't the right fit here but sadly where unable to use roles as we're stuck with DC/OS and it does not have the ability to offer different roles to multiple frameworks.

**Comment by meichstedt** [comment]
@rbrown-rms sorry for the uhm late reply – I've commented on [MARATHON-7693 ](https://jira.mesosphere.com/projects/MARATHON/issues/MARATHON-7693) so in case you didn't figure it out yet, there you go.
