### ISSUE TITLE
Command health check not executed

### ISSUE THREAD

**Issue by YP28** [mesosphere/marathon#5488]
#### Issue
Command health checks do not seem to be working properly. The first health check when a deployment of the new app is running, it executes the command and the instances are healthy. However, when observing the health check debug info (first success, last success, last failure, etc.), they do not appear to be executed after that first time.

#### Reproduce
1. Add a new app to Marathon (with multiple processes, watching the process the docker container livelyhood does not rely on) with a health check like following:
```json
{
  "gracePeriodSeconds": 120,
  "intervalSeconds": 10,
  "timeoutSeconds": 5,
  "maxConsecutiveFailures": 2,
  "delaySeconds": 15,
  "command": {
    "value": "ps ax | grep -v grep | grep $process | wc -l"
  },
  "protocol": "COMMAND"
}
```
2. Wait for the instance to be marked as healthy
3. Observe the health check debug info
4. To be sure it's not being executed, kill the process you're monitoring

#### General info
**Marathon version:** 1.4.6
**Framework Id:** 6af3e03a-9431-4d81-af17-03de6267670a-0002

**Comment by kensipe** [comment]
@YP28 thank you!  as it turns out...  I was just discovery this myself.  I'm not sure if it is exactly the same... but command health checks seem to be broken in 1.5...   It is likely the same issue with 1.4.6.  I will confirm.

**Comment by kensipe** [comment]
details will be in the jira
