### ISSUE TITLE
Document PATCH-like PUTs

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#594]
It's unclear what values need to be supplied when updating an app or group via the REST API.

**Comment by kolloch** [comment]
Related to #1418

**Comment by janisz** [comment]
Fixed by https://github.com/mesosphere/marathon/pull/5157

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3918. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
