### ISSUE TITLE
can not delete ipAddress field

### ISSUE THREAD

**Issue by VilsonYuan** [mesosphere/marathon#5955]
I create my app using USER network mode, but can not use PUT to delete ipAddress filed when i want to change it to BRIDGE

**Comment by VilsonYuan** [comment]
can anyone solve this problem?

**Comment by alenkacz** [comment]
@VilsonYuan the docs say

http://mesosphere.github.io/marathon/api-console/index.html
 partialUpdate default: true string
Without specifying this parameter, this method has a patch like semantic:
All values that are not defined in the json, will not change existing values.
This was the default behaviour in previous Marathon versions.
For backward compatibility, we will not change this behaviour, but let users opt in for a proper PUT.
Note: We will change the default behaviour in the next Marathon version to support PATCH and PUT as HTTP methods.

So maybe you can do a PUT with partialUpdate=false and put the full JSON. Then the PUT should replace your old app definition with new one.

Let me know if it helped...

**Comment by alenkacz** [comment]
I'll close this. Please reopen if it does not help
