### ISSUE TITLE
Version event JSON formats

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#608]
Right now the format of events published to the event bus (in the form of HTTP POST requests) is independent of the API version used to subscribe that callback.  That should be fixed to prepare for subsequent API revisions.

See #607 
See #1505 (and the work-in-progress PR #1536)

**Comment by kolloch** [comment]
If you want to reopen this, please describe your intention.

**Comment by ConnorDoyle** [comment]
@kolloch: added detail, labels, links, and updated the title to make this more concrete.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3784. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
