### ISSUE TITLE
Mesos and Marathon out of sync: orphaned tasks and "ghost" tasks

### ISSUE THREAD

**Issue by tnolet** [mesosphere/marathon#616]
Hi,

over the stretch of a week I've been deploying Docker containers to a Marathon cluster on Google Compute Engine. I'm now in a state where in the Mesos UI, I can see five running containers under the Marathon framework. In the Marathon UI, I see one running container. Moreover, I cannot seem to kill any of these. Deleting the one container reported by Marathon does not raise any error. I just stays put. 
This pretty bad, as I now have to check Mesos for orphaned tasks and I can't rely on Marathon's interface anymore. I'm running Mesos 0.20.0 and Marathon 0.7.0-SNAPSHOT.

One in Marathon

```
$ http http://10.69.177.224:8080/v2/apps
HTTP/1.1 200 OK
Content-Type: application/json
Server: Jetty(8.y.z-SNAPSHOT)
Transfer-Encoding: chunked

{
    "apps": [
        {
            "args": [], 
            "backoffFactor": 1.15, 
            "backoffSeconds": 1, 
            "cmd": null, 
            "constraints": [], 
            "container": {
                "docker": {
                    "image": "tnolet/mesos-tester"
                }, 
                "type": "DOCKER", 
                "volumes": []
            }, 
            "cpus": 0.2, 
            "dependencies": [], 
            "disk": 0.0, 
            "env": {}, 
            "executor": "", 
            "healthChecks": [], 
            "id": "/vrn-container-3fe5143d", 
            "instances": 1, 
            "mem": 512.0, 
            "ports": [
                32768
            ], 
            "requirePorts": false, 
            "storeUrls": [], 
            "tasksRunning": 1, 
            "tasksStaged": 0, 
            "upgradeStrategy": {
                "minimumHealthCapacity": 1.0
            }, 
            "uris": [], 
            "user": null, 
            "version": "2014-09-16T11:06:40.862Z"
        }
    ]
}

```

But more in Mesos. Please note that `framework_id` is indeed pointing to Marathon. It is the only framework installed on this Mesos setup

```
$ http http://10.69.177.224:5050/master/tasks.json
HTTP/1.1 200 OK
Content-Encoding: gzip
Content-Length: 533
Content-Type: application/json
Date: Sun, 21 Sep 2014 22:15:02 GMT

{
    "tasks": [
        {
            "executor_id": "", 
            "framework_id": "20140917-082040-3769713930-5050-25964-0000", 
            "id": "vrn-container-54e6f672.6dee28a2-3f52-11e4-8a4d-42010a45b1e0", 
            "name": "vrn-container-54e6f672.6dee28a2-3f52-11e4-8a4d-42010a45b1e0", 
            "resources": {
                "cpus": 0.2, 
                "disk": 0, 
                "mem": 512, 
                "ports": "[31191-31191]"
            }, 
            "slave_id": "20140917-082040-3769713930-5050-25964-1", 
            "state": "TASK_RUNNING", 
            "statuses": [
                {
                    "state": "TASK_RUNNING", 
                    "timestamp": 1411058401.67118
                }
            ]
        }, 
        {
            "executor_id": "", 
            "framework_id": "20140917-082040-3769713930-5050-25964-0000", 
            "id": "vrn-container-5845b383.66c60931-3f52-11e4-8a4d-42010a45b1e0", 
            "name": "vrn-container-5845b383.66c60931-3f52-11e4-8a4d-42010a45b1e0", 
            "resources": {
                "cpus": 0.2, 
                "disk": 0, 
                "mem": 512, 
                "ports": "[31391-31391]"
            }, 
            "slave_id": "20140917-082040-3769713930-5050-25964-0", 
            "state": "TASK_RUNNING", 
            "statuses": [
                {
                    "state": "TASK_RUNNING", 
                    "timestamp": 1411058389.67871
                }
            ]
        }, 
        {
            "executor_id": "", 
            "framework_id": "20140917-082040-3769713930-5050-25964-0000", 
            "id": "vrn-container-9308ce3f.c6561b20-3f51-11e4-8a4d-42010a45b1e0", 
            "name": "vrn-container-9308ce3f.c6561b20-3f51-11e4-8a4d-42010a45b1e0", 
            "resources": {
                "cpus": 0.2, 
                "disk": 0, 
                "mem": 512, 
                "ports": "[31034-31034]"
            }, 
            "slave_id": "20140830-114324-3769713930-5050-2099-2", 
            "state": "TASK_RUNNING", 
            "statuses": [
                {
                    "state": "TASK_RUNNING", 
                    "timestamp": 1411058124.13837
                }
            ]
        }, 
        {
            "executor_id": "", 
            "framework_id": "20140917-082040-3769713930-5050-25964-0000", 
            "id": "vrn-container-854730d9.97d559ef-3f51-11e4-8a4d-42010a45b1e0", 
            "name": "vrn-container-854730d9.97d559ef-3f51-11e4-8a4d-42010a45b1e0", 
            "resources": {
                "cpus": 0.2, 
                "disk": 0, 
                "mem": 512, 
                "ports": "[31504-31504]"
            }, 
            "slave_id": "20140917-082040-3769713930-5050-25964-0", 
            "state": "TASK_RUNNING", 
            "statuses": [
                {
                    "state": "TASK_RUNNING", 
                    "timestamp": 1411058042.44566
                }
            ]
        }, 
        {
            "executor_id": "", 
            "framework_id": "20140917-082040-3769713930-5050-25964-0000", 
            "id": "vrn-container-036767c5.c801a9e0-3e77-11e4-9d4b-42010a45b1e0", 
            "name": "vrn-container-036767c5.c801a9e0-3e77-11e4-9d4b-42010a45b1e0", 
            "resources": {
                "cpus": 0.2, 
                "disk": 0, 
                "mem": 512, 
                "ports": "[31438-31438]"
            }, 
            "slave_id": "20140917-082040-3769713930-5050-25964-1", 
            "state": "TASK_KILLED", 
            "statuses": [
                {
                    "state": "TASK_RUNNING", 
                    "timestamp": 1410964494.1324
                }, 
                {
                    "state": "TASK_KILLED", 
                    "timestamp": 1411336361.56436
                }
            ]
        }, 
        {
            "executor_id": "", 
            "framework_id": "20140917-082040-3769713930-5050-25964-0000", 
            "id": "vrn-container-60a6af7c.bd45672f-3e77-11e4-9d4b-42010a45b1e0", 
            "name": "vrn-container-60a6af7c.bd45672f-3e77-11e4-9d4b-42010a45b1e0", 
            "resources": {
                "cpus": 0.2, 
                "disk": 0, 
                "mem": 512, 
                "ports": "[31945-31945]"
            }, 
            "slave_id": "20140917-082040-3769713930-5050-25964-1", 
            "state": "TASK_KILLED", 
            "statuses": [
                {
                    "state": "TASK_RUNNING", 
                    "timestamp": 1410964475.11256
                }, 
                {
                    "state": "TASK_KILLED", 
                    "timestamp": 1411336353.56442
                }
            ]
        }, 
        {
            "executor_id": "", 
            "framework_id": "20140917-082040-3769713930-5050-25964-0000", 
            "id": "vrn-container-3fe5143d.373a74aa-3e49-11e4-9d4b-42010a45b1e0", 
            "name": "vrn-container-3fe5143d.373a74aa-3e49-11e4-9d4b-42010a45b1e0", 
            "resources": {
                "cpus": 0.2, 
                "disk": 0, 
                "mem": 512, 
                "ports": "[31160-31160]"
            }, 
            "slave_id": "20140830-114324-3769713930-5050-2099-2", 
            "state": "TASK_RUNNING", 
            "statuses": [
                {
                    "state": "TASK_RUNNING", 
                    "timestamp": 1410944492.97175
                }
            ]
        }
    ]
}

```

**Comment by tnolet** [comment]
Hi, 

I'm not sure why this is closed. I have the exact same situation again. Apps running in Marathon with associated tasks, but no tasks running in Mesos. This is quite unnerving and blocking for any serious production usage. This bug is no 1 year old.

Setup:

- 4 mesos slaves and 2 masters running Mesos 0.25.0
- marathon running 0.11.1

output from mesos `/tasks` endpoint:

```json
{"tasks":[]}
```

output from marathon's `apps/<some app>/tasks` endpoint (abbreviated):

```json
{
    "tasks": [
        {
            "id": "mesos-consul.67e0ab0d-7c46-11e5-8886-0242fdc2dab2",
            "host": "mesos01.bva.nu",
            "ports": [
                31866
            ],
            "startedAt": "2015-10-27T01:02:42.310Z",
            "stagedAt": "2015-10-27T01:02:33.930Z",
            "version": "2015-10-01T15:19:10.936Z",
            "slaveId": null,
            "appId": "/mesos-consul"
        }
    ]
}


```
@ConnorDoyle : Any updates on how/why this happens? Do other Mesos frameworks have this behaviour or is Marathon just not stable yet?

**Comment by tnolet** [comment]
P.S: the only error I can see in the Marathon logs (reported under INFO(!)) is:

```
[INFO] [10/26/2015 13:28:09.320] [marathon-akka.actor.default-dispatcher-14] [akka://marathon/deadLetters] Message [mesosphere.marathon.MarathonSchedulerActor$TasksReconciled$] from Actor[akka://marathon/user/MarathonScheduler/$a#223371711] to Actor[akka://marathon/deadLetters] was not delivered. [5] dead letters encountered. This logging can be turned off or adjusted with configuration settings 'akka.log-dead-letters' and 'akka.log-dead-letters-during-shutdown'.
[2015-10-26 13:28:09,323] INFO Syncing tasks for all apps (mesosphere.marathon.SchedulerActions:442)
```

**Comment by memelet** [comment]
I have this problem after upgrading for 0.10 to 0.11.1. I have several marathon tasks that do not exist in mesos. I cannot destroy, scale, or anything.

**Comment by flyinprogrammer** [comment]
I'm running marathon 0.15.1, mesos 0.27 and definitely just had this happen. To fix it, I nuked the ghost tasks and bounce the elected marathon leader. I can definitely trace this back to deployments happening on top of slaves that were being restarted and wiped.

**Comment by jgarcia-mesosphere** [comment]
Hi! If you're effected by this issue, please file a support ticket at support@mesosphere.com

**Comment by jaimelive** [comment]
I'm still experiencing this on Marathon 1.0-RC1 and Mesos 0.28.0 any updates to this bug?

**Comment by ianjw11** [comment]
Effected by this as well. Marathon 0.15.3 Mesos 0.28.0

**Comment by timcharper** [comment]
I'm hitting it, too; in a local cluster I've provisioned in VMs. If I bring the whole thing down, then back up, Marathon remembers the tasks but Mesos has no recollection of them. I can't kill them / get Marathon to believe that they're gone. It should be able to query mesos and realize that no such task exists anymore.

**Comment by thepolina** [comment]
Experiencing this recently. One of the tasks stuck in state described here https://github.com/mesosphere/marathon/issues/3892
finally disappeared from Marathon but keeps spinning in Mesos

**Comment by JustinVenus** [comment]
I am able to reproduce with Marathon==0.15.5 and Mesos==0.28.2 in a HA setup.  Like others have reported before only manually removing information from Zookeeper resolves the issue.

**Comment by XANi** [comment]
same thing happens with marathon 1.1.2/mesos 0.28.2 after few node restarts (cluster of 3) when we were testing resilience of the setup

**Comment by rbucchi** [comment]
problem still here. I got a three node cluster in HA. If master goes down and up task hang forever and cannot be destroyed or scaled down. Tasks seem killed for mesos, but hanging on deployment in marathon

mesos-0.28.2-2.0.27.centos701406.x86_64
marathon-1.1.2-1.0.482.el7.x86_64
zookeeper-3.4.5

any workaround before fixing?

**Comment by timcharper** [comment]
@rbucchi I was able to reproduce it in that version as well. I've found a happy version at around a1d330312d66996dd02920112fa3e268d79f7584 which I'm running (with some patches).

You can remove them with the zookeeper cli. I have `zkCli.sh` aliased to `zk`, and maybe this one-liner could help you:

```
zk ls /marathon/state | egrep '^\[' | sed 's/, */\n/g' | sed 's/^\[//' | sed 's/\]$//' | grep task:registry | while read task; do echo zk rmr /marathon/state/$task; done
```

(this won't actually remove anything but will output the zk commands to run in order to remove things)

**Comment by XANi** [comment]
@rbucchi in my case dropping GC interval/timeout helped, after dropping it to around hour task disappeared reasonably fast (restarting few nodes in short interval didn't screwed cluster completely)

**Comment by hellgorithm** [comment]
Experienced this issue when my network suddenly crash, now i have 3 staged app and 3 running app (originally scaled 3) and they cant be killed or destroyed.

**Comment by joelstewart** [comment]
i am experiencing marathon showing tasks / apps that cannot be removed, and that mesos does not show the tasks at all, which occurred when all nodes were restarted.

mesos 1.0.0 / marathon 1.1.2

**Comment by x-cray** [comment]
@timcharper Thanks for the hint. Manual ZK database cleanup solves the issue.

**Comment by tsaridas** [comment]
I still have this with version 1.1.2 of marathon.

**Comment by erSitzt** [comment]
Same here, needed a config change on the mesos-slaves and now i'm stuck with tasks i cant kill/scale/deploy.


Marathon 1.1.2
Mesos 0.28

**Comment by XANi** [comment]
that  "fixed" (tasks eventually go away) it for me :`--task_lost_expunge_gc 3600000 --task_lost_expunge_interval 900000`

**Comment by franktranhb** [comment]
Same for me...

**Comment by kjelle** [comment]
I just experienced this problem with Marathon 1.1.12-1.0.488.el7 and mesos 1.0.1-2.0.93.centos701406. Deployments get "stuck" with orphan tasks.

**Comment by erSitzt** [comment]
Check the task_lost values that are coming with the next release, they basically went from24 hours down to a few seconds ...

https://github.com/mesosphere/marathon/blob/master/changelog.md

**Comment by kjelle** [comment]
And it just happened again. What we do is call DELETE on a app-group with ?force=true, then wait 20 seconds and then call POST creating the app group.
When we "relaunch" we do this for 85 app groups..

Marathon doesnt seem to handle this too well..

**Comment by eromoe** [comment]
@timcharper 's method not work for me:
```
[root@zk1 bin]# zk ls /marathon/state | egrep '^\[' | sed 's/, */\n/g' | sed 's/^\[//' | sed 's/\]$//' | grep task:registry | while read task; do echo zk rmr /marathon/state/$task; done
log4j:WARN No appenders could be found for logger (org.apache.zookeeper.ZooKeeper).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.
```
add server option is same
```
[root@zk1 bin]# zk -server 10.142.55.190:2181,10.142.55.196:2181,10.142.55.202:2181 ls /marathon/state | egrep '^\[' | sed 's/, */\n/g' | sed 's/^\[//' | sed 's/\]$//' | grep task:registry | while read task; do echo zk rmr /marathon/state/$task; done
log4j:WARN No appenders could be found for logger (org.apache.zookeeper.ZooKeeper).
log4j:WARN Please initialize the log4j system properly.
log4j:WARN See http://logging.apache.org/log4j/1.2/faq.html#noconfig for more info.

```

**Comment by crumley** [comment]
Marathon 1.11.1 and Mesos 0.28.2: I lost a mesos slave due to a network disconnect. When the slave came back online the marathon launched docker process persisted, but marathon UI did not reflect that and marathon restarted the tasks on another host.... the end result is a marathon app that is running many more instances than what the marathon configuration specifies (and what marathon thinks is running). 

Possibly related to this bug?

**Comment by nashasha1** [comment]
I hit this error on Marathon 1.1.1 and Mesos 0.28.1. Marathon and Mesos are running in docker container. When I restart mesos-slave , Marathon losts this task from UI. After 15mins later, Marathon schedules this task to another mesos-slave. But the old container on the slave which I just restarted is still there. It becomes an orphaned container.

**Comment by gvenka008c** [comment]
We are seeing the same issue. When we lost one of the VM and it came back online, there are no jobs running. But marathon shows job is running. It's a stale data. Any fix?

```
mesos-1.0.1-2.0.93.centos701406.x86_64
mesosphere-el-repo-7-3.noarch
mesosphere-zookeeper-3.4.6-0.1.20141204175332.centos7.x86_64
marathon-1.1.3-1.0.503.el7.x86_64

```

**Comment by moyara** [comment]
Thanks for @timcharper I was able to write script to restart all my services on shutdown. (I don't wanted to wait for 15 mins...)

zk="$(find /opt/mesosphere/packages | grep zookeeper/bin/zkCli.sh)"
$zk ls /marathon/state | egrep '^\[' | sed 's/, */\n/g' | sed 's/^\[//' | sed 's/]]$//' | grep task: | while read task; do $zk rmr /marathon/state/$task; done
systemctl restart dcos-marathon

**Comment by Devatoria** [comment]
I have the same issue on Marathon 1.1.5 and Mesos 1.1.0. I had 3 instances of an app, distributed on 3 agents. One of these agents went down and I rebooted it. The task appears as lost in Mesos because of an unreachable agent, but Marathon keeps showing the app as healthy (but the container is not up anymore) and I can't kill it (the task reappears a few seconds after). Also, the task doesn't count as an instance (the app scale is 0, even if the task appears as healthy in the UI).
