### ISSUE TITLE
Move Mesos message wrappers to mesos-utils

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#651]
We recently added several classes to handle marshaling/un-marshaling Mesos protobuf messages.  These should be moved to the [mesos-utils](http://github.com/mesosphere/mesos-utils) library.

**Comment by Ferdiism** [comment]
@ConnorDoyle has this happened? Can we close this one?

**Comment by ConnorDoyle** [comment]
We still have wrappers for Parameter and Command that could be moved.  ResourceUtils probably also belongs in mesos-utils.

**Comment by jasongilanfarr** [comment]
We no longer use mesos-utils. no longer relevant.
