### ISSUE TITLE
Lack of information when a deployment stalls

### ISSUE THREAD

**Issue by chendo** [mesosphere/marathon#652]
When a deployment has stalled for some reason, it's extremely difficult to figure out why.

In our particular use case, we forgot we had a `GROUP_BY` constraint and spent a while trying to figure out why our app wouldn't scale to three as one of our three slaves was out of CPU capacity.

**Comment by air** [comment]
Cc'ing myself.

**Comment by kolloch** [comment]
This should be somewhat improved by now.

One part that is till missing is showing information about rejected offers. That's what #1090 is about. If you feel that another aspect of this issue has not been captured by this issue yet, please open a more focused issue about that.
