### ISSUE TITLE
/v2/groups PUT doesn't honor previous instances value

### ISSUE THREAD

**Issue by sttts** [mesosphere/marathon#659]
Create an application group and scale an app to some value other than 1. Use the same json definition, but leave out the "instances" lines. Use a PUT on /v2/groups/<group-id> to update the group. Marathon scales down to 1.

**Comment by gkleiman** [comment]
@stts: I couldn't reproduce what you describe and this issue is pretty old. Please reopen this if you think the problems still exist.
