### ISSUE TITLE
Rethink ports API

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#670]
The way ports are defined is confusing and should be redesigned.
1. Using our recommended HAProxy configuration, users have to think about an app's "local" ports, ports bound on the host, plus any NAT rules done by the containerizer.
2. Ports may be defined via `app.ports` or `app.container.docker.portMappings`.
3. The `app.ports` array is overloaded, with bearing on both "local" and host ports depending on the value of the `app.requirePorts` flag.

@lloesche @BenWhitehead @lingmann @guenter

**Comment by cmaloney** [comment]
I like three classes of ports: Host ports, Container ports (Used for port mapping with docker primarily), and Service Ports (Used purely for haproxy-marathon-bridge type setups, deprecated hopefully).

Any port which is given as a zero should get replaced with some port from the offer the task ends up being launched with.

I'd personally like for Service Ports to leave the scope of marathon entirely (I like them either as mesos task labels or magic envrionment variables which a service discovery service can scoop up). If they need to stick around I'd say they are a separate array which specifies which host port should map to a service port.

Let me know if anything in there could use more clarification for what I'd like to see.

**Comment by kolloch** [comment]
@cmaloney I agree with your assessment of the global service ports but we have to continue supporting them for a while.

**Comment by jasongilanfarr** [comment]
We have like 4 ways of doing this today, we need to fix it completely in v3, but otherwise out of scope.
