### ISSUE TITLE
Container IP as hostname using bridged networking

### ISSUE THREAD

**Issue by gregory90** [mesosphere/marathon#674]
It would be really helpful if there was option for marathon to report container IP as hostname when using docker bridged networking. Right now it's always mesos-slave hostname.
With bridged networking there's sometimes no need to expose ports as we can use container IP (which is reachable on all of our hosts using some kind of overlay network).

**Comment by gregory90** [comment]
Related: https://issues.apache.org/jira/browse/MESOS-2044

**Comment by gregory90** [comment]
It should be possible now with https://issues.apache.org/jira/browse/MESOS-3061 resolved.

**Comment by Ralnoc** [comment]
I see this is being marked as an enhancement. Is there a version ETA this is expected to show up in?

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3820. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
