### ISSUE TITLE
bug suspend application not working on the applications and application page

### ISSUE THREAD

**Issue by f1-outsourcing** [mesosphere/marathon#6795]
When I scale manually to 0, it works.

Version 1.7.189

![marathon](https://user-images.githubusercontent.com/13450219/52804588-dc383c00-3084-11e9-95b3-62162712a1d4.png)

**Comment by alenkacz** [comment]
Hello @f1-outsourcing This should be filed under https://github.com/mesosphere/marathon-ui

Unfortunately we now longer support marathon UI :( We accept community contributions though! :-)
