### ISSUE TITLE
Provide way to upgrade Docker containers without changing Mesos environment

### ISSUE THREAD

**Issue by papile** [mesosphere/marathon#681]
Currently if you just need to upgrade an application Docker container you need to create a change in the Mesos/Marathon environment to trigger Mesos/Marathon to upgrade your running container according to the specified minimumHealthCapacity parameters. 

 It is a frequent use case to have a code change, build a new container, and push the container to a Docker registry.  Then to make those changes live you would want Mesos/Marathon to do a rolling upgrade of your running nodes.  Right now I am having to change a dummy environment variable to have this happen.  It would be nice if Marathon could have a PUT rest call to the running application name where you can place a flag like upgradeContainer=true in order for it to know to pull the Docker container again and upgrade your nodes.  Or this could also be accomplished by storing the hash of the pulled containers and triggering upgrades if there is a change on a subsequently pulled container.

**Comment by mindscratch** [comment]
An option has been added to [DockerInfo](https://github.com/apache/mesos/blob/0.22.0/include/mesos/mesos.proto#L1032) which is now available in Mesos 0.22.0. Any thoughts on when this might be added to Marathon?

**Comment by Pindar** [comment]
+1 - it's useful for snapshot deployments on staging systems...

**Comment by jasongilanfarr** [comment]
We support the usage of force_pull.
