### ISSUE TITLE
Command exited with status 1 while running Flink on Mesos with Marathon Framework

### ISSUE THREAD

**Issue by marzieh-ghasemi** [mesosphere/marathon#6819]
I want to run my flink program on Mesos cluster via marathon. I created an application with this Json file in Marathon:

{
          "id": "flink",
          "cmd": "/home/flink-1.7.0/bin/mesos-appmaster.sh -Djobmanager.heap.mb=1024 -Djobmanager.rpc.port=6123 -Drest.port=8081 -Dmesos.resourcemanager.tasks.mem=1024 -Dtaskmanager.heap.mb=1024 -Dtaskmanager.numberOfTaskSlots=2 -Dparallelism.default=2 -Dmesos.resourcemanager.tasks.cpus=1",
          "cpus": 1.0,
          "mem": 1024
}

  The task became failed with this error:

I0303 09:41:52.841243     2594 exec.cpp:162] Version: 1.7.0
I0303 09:41:52.851898     2593 exec.cpp:236] Executor registered on agent d9a98175-b93c-4600-a41b-fe91fae5486a-S0
I0303 09:41:52.854436     2594 executor.cpp:182] Received SUBSCRIBED event
I0303 09:41:52.855284     2594 executor.cpp:186] Subscribed executor on 172.28.10.136
I0303 09:41:52.855479     2594 executor.cpp:182] Received LAUNCH event
I0303 09:41:52.855932     2594 executor.cpp:679] Starting task ffff.933fdd2f-3d98-11e9-bbc4-0242a78449af
I0303 09:41:52.868172     2594 executor.cpp:499] Running '/home/mesos-1.7.0/build/src/mesos-containerizer launch <POSSIBLY-SENSITIVE-DATA>'
I0303 09:41:52.872699     2594 executor.cpp:693] Forked command at 2599
I0303 09:41:54.050284     2596 executor.cpp:994] Command exited with status 1 (pid: 2599)
I0303 09:41:55.052323     2598 process.cpp:926] Stopped the socket accept loop

I configured Zookeeper, Mesos, Marathon and Flink. Moreover, they are all on docker. I ran a simple program like "echo "hello" >> /home/output.txt" without any problems. 

I really do not know what is going on, I am confused. Would you please any one tell me what is wrong here?

Any help would be appreciated. 

Many thanks.

**Comment by zen-dog** [comment]
Hm, it seems that our Github-Jira bot is disabled. While it being re-enabled: you could look into the tasks sandbox `stdout`, `stderr` to see why the task failed (`Command exited with status 1`). Most probably explanation: every task is started isolated in a sandbox where `/home/flink-1.7.0/bin/mesos-appmaster.sh` does not exist.

There are multiple ways to get around it, most notably:
- fetch what you need into the sandbox, unpack and execute it [using fetcher](https://mesosphere.github.io/marathon/docs/application-basics.html#using-resources-in-applications)
- use a docker image which already has all necessary dependencies

**Comment by marzieh-ghasemi** [comment]
Dear zen-dog, thank you for your feedback.

**Comment by alenkacz** [comment]
Hi @marzieh-ghasemi if you have any follow up questions, please reach out at Mesos slack or create a JIRA issue. Thanks! https://jira.mesosphere.com/projects/MARATHON/issues/
