### ISSUE TITLE
Packages for Debian Stretch

### ISSUE THREAD

**Issue by eLvErDe** [mesosphere/marathon#6875]
Hello,

Changelog says you now provides Debian Stretch packages. Well, that's not true.
I mean, there're mesos package, but now marathon ones.

`deb http://repos.mesosphere.io/debian stretch main` returns nothing while `deb http://repos.mesosphere.io/debian jessie main` does.

Btw, Debian Buster will be released soon, you may consider starting to provide package already.

You can check using:

```
curl --silent http://repos.mesosphere.com/debian/dists/stretch/main/binary-amd64/Packages | grep -e 'Package:'
curl --silent http://repos.mesosphere.com/debian/dists/jessie/main/binary-amd64/Packages | grep -e 'Package:'
```

Regards, Adam.

**Comment by alenkacz** [comment]
Hello @eLvErDe we have a JIRA issue for this here https://jira.mesosphere.com/browse/MARATHON-7995 ... you can +1 it if it will make your life easier and we can bump the priority.

Thanks for submitting this!
