### ISSUE TITLE
how to supply CNI_ARGS in json

### ISSUE THREAD

**Issue by f1-outsourcing** [mesosphere/marathon#6902]
I already posted this on Jira 6 months ago or so, how to get this CNI_ARGS  environment ip being used by the cni networking plugin?

This does not seem to work (also without the single quotes)

```
{
  "id": "/server",
  "user": "nobody",
  "cmd": "python -m SimpleHTTPServer 8080",
  "cpus": 0.1,
  "mem": 32,
  "disk": 0,
  "instances": 1,
  "acceptedResourceRoles": ["*"],
  "constraints": [["hostname","CLUSTER","m03.local"]],
  "backoffSeconds": 10,
  "networks": [ { "mode": "container", "name": "test-macvtap-cniip" } ],
  "env": { "CNI_ARGS" : "'IP=192.168.122.178'" }
}
```

https://jira.mesosphere.com/browse/MARATHON-8582

**Comment by alenkacz** [comment]
@f1-outsourcing thanks for submitting, I replied in the JIRA. Please let's keep the discussion in JIRA.

I am afraid that might not be supported on the mesos level though. You can try asking on the mesos slack but I pinged the person who might know more in your issue
