### ISSUE TITLE
 Framework authentication dosent work in DCOS

### ISSUE THREAD

**Issue by zaalizadeh** [mesosphere/marathon#6942]
My goal is Framework authentication in DC/OS mesosphere.
But I get  Marathon error configuration:

my configuration in **/opt/mesosphere/etc/mesos-master**

```
#Framework authentication
#MESOS_AUTHENTICATORS="crammd5"
MESOS_AUTHENTICATE_FRAMEWORKS=true
#MESOS_AUTHENTICATE_HTTP_FRAMEWORKS=true
MESOS_HTTP_FRAMEWORK_AUTHENTICATORS="basic"
MESOS_AUTHENTICATE=true
MESOS_CREDENTIALS=/opt/mesosphere/etc/mesos_credentials_auth.json
```

my configuration in **/opt/mesosphere/etc/marathon**
```
#authentication section
MARATHON_MESOS_AUTHENTICATION=enabled
#MARATHON_HTTP_CREDENTIALS=marathon:123456
MARATHON_MESOS_AUTHENTICATION_PRINCIPAL=marathon
MARATHON_MESOS_AUTHENTICATION_PRINCIPAL=12345678A!
#MARATHON_MESOS_ROLE=foo
```
But Marathon restart fails when I use these commands for truble shouthing:

```
$systemctl status dcos-marathon.service
$journalctl -o verbose _PID=4742
```

I get this error in marathon log:

    MESSAGE=[scallop] Error: Bad arguments for option 'mesos_authentication': 'enabled' - wrong arguments format

I tried following values and all of them fails too.
MARATHON_MESOS_AUTHENTICATION=true
MARATHON_MESOS_AUTHENTICATION=1

I have no idea about this question.Any help will be appreciated.

**Comment by meichstedt** [comment]
@zaalizadeh The error you see is because you're trying to define a value but the flag is a **toggle**.

The command line flag to enable/disable mesos auth is simply
`--mesos_authentication` and `--disable_mesos_authentication`, respectively. 

With env vars, you'd simply set
```
MARATHON_MESOS_AUTHENTICATION
```

And that should work just fine :)

**Comment by zaalizadeh** [comment]
Hi Matthias,
Thank you for your response,
I tried following setting and it doesn't work.

my configuration in */opt/mesosphere/etc/marathon*
#Authentication section
MARATHON_MESOS_AUTHENTICATION
MARATHON_MESOS_AUTHENTICATION_PRINCIPAL=marathon
MARATHON_MESOS_AUTHENTICATION_PRINCIPAL=12345678A!
MARATHON_MESOS_ROLE=foo


my configuration in */opt/mesosphere/etc/mesos-master*
#Authentication part
MESOS_LOG_DIR=/var/log/mesos
#Framework authentication
MESOS_AUTHENTICATORS="crammd5"
MESOS_AUTHENTICATE_FRAMEWORKS=true
MESOS_HTTP_FRAMEWORK_AUTHENTICATORS="basic"
MESOS_ACLS=/opt/mesosphere/etc/acls
MESOS_CREDENTIALS=/opt/mesosphere/etc/mesos_credentials_auth.json
MESOS_ROLE=foo
MESOS_AUTHENTICATE_HTTP_FRAMEWORKS=true


I got this error in marathon log and marathon is  unhealthy in DC/OS UI.

    MESSAGE=[2019-06-20 08:12:57,639] INFO  Opening socket connection to
server dcos-e2e-default-8efea-master-0/172.17.0.2:2181. Will not attempt to
authenticate using SASL (unknown error)
(org.apache.zookeeper.ClientCnxn:main-SendThread
Thu 2019-06-20 08:12:57.645376 UTC
[s=9e399e33096e4f4e984d44223caa58a1;i=8b038e;b=c96467cfc37644dc94398ba4eef41763;m=af1a390b89;t=58bbce9e32d40;x=3d86a2a719988013]

**Comment by zaalizadeh** [comment]
After search, finally I got my answer: 

These security features are only available on "DC/OS mesosphere"  Enterprise and you cant config it in open source version.
