### ISSUE TITLE
App with null ID causes issues

### ISSUE THREAD

**Issue by chendo** [mesosphere/marathon#704]
We've managed to get Marathon 0.7.3 (Mesos 0.20.1) into a weird state by accidentally creating an app with no ID it shows up as `/`.

We are unable to destroy the app as it seems to always come back. Killing off the deployment for it doesn't seem to help either.

We're going to restart the master to see if it helps.

**Comment by guenter** [comment]
This issue seems to be fixed in 0.8.1-RC1. Creating an app with empty or `null` ID results in a 400 Bad Request. @drexin close?

**Comment by drexin** [comment]
Yes, thanks.
