### ISSUE TITLE
Need to use --volumes-from flag to use share data between containers

### ISSUE THREAD

**Issue by defender** [mesosphere/marathon#719]
Hi
--volumes-from is missing

To use this flag we need to know / set container name - we cannot set container name by marathon API, also container id is not appears in localhost:8080/v2/apps/app_name so it is impossible link between two containers.

My suggestion is 
1.to extend existing json structure to :

"volumes": [
          {
              "containerPath": "",
              "hostPath": "",
              "mode": "RO"
              "from" : app_name
          }
] 
In case "from" will be filled "containerPath" , "hostPath" & "mode" can be optional 

2.provide container id inside localhost:8080/v2/apps/app_name

Thanks,

**Comment by kopax** [comment]
how can i mount a volume from  ?

**Comment by junneyang** [comment]
any update on how this could be achieved as of current versions ?
Thanks
