### ISSUE TITLE
No start hook file found ($HOOK_MARATHON_START). Proceeding with the start script. [2020-07-16 19:48:55,289] INFO  Successfully loaded libmesos: version 1.9.0 (mesosphere.marathon.MarathonApp:main) [scallop] Error: Unknown option 'event_subscriber'

### ISSUE THREAD

**Issue by wenchangming211** [mesosphere/marathon#7197]
No start hook file found ($HOOK_MARATHON_START). Proceeding with the start script.
[2020-07-16 19:48:55,289] INFO  Successfully loaded libmesos: version 1.9.0 (mesosphere.marathon.MarathonApp:main)
[scallop] Error: Unknown option 'event_subscriber'

**Comment by timcharper** [comment]
Are you defining MARATHON_EVENT_SUBSCRIBER env var somewhere, or providing this as an option? If so, just remove it. It is not a supported option.
