### ISSUE TITLE
non-leader mangles /v2/eventSubscriptions POST requests when proxying to the leader

### ISSUE THREAD

**Issue by chrono** [mesosphere/marathon#726]
When sending a POST request trying to register a new event subscriber to a non-leader, I'd expect the request to be proxied to the current leader. However, this:

```
$ http POST http://non-leader:8080/v2/eventSubscriptions\?callbackUrl\=http://localhost:9292/callback
HTTP/1.1 415 Unsupported Media Type
Content-Length: 36
Content-Type: application/json
Server: Jetty(8.y.z-SNAPSHOT)

{
    "message": "Unsupported Media Type"
}
```

versus sending to the leader directly

```
$ http POST http://leader:8080/v2/eventSubscriptions\?callbackUrl\=http://localhost:9292/callback
HTTP/1.1 200 OK
Content-Type: application/json
Server: Jetty(8.y.z-SNAPSHOT)
Transfer-Encoding: chunked

{
    "callbackUrl": "http://localhost:9292/callback",
    "clientIp": "10.10.11.1",
    "eventType": "subscribe_event",
    "timestamp": "2014-10-21T19:18:16.425Z"
}
```

In order to work around this issue I tried to discover the leader via `/v2/info`. The hostname in the `leader` value is neither an ip address nor a fully qualified hostname. Not useful for discovering the leader.

Observed with marathon 0.7.3

**Comment by jasongilanfarr** [comment]
This API is moments from being deprecated.
