### ISSUE TITLE
why are java 1.8 versions used in the docker images of 1.9, 1.11? (did not check 1.10)

### ISSUE THREAD

**Issue by f1-outsourcing** [mesosphere/marathon#7260]
Newer java versions better communicate resource limits in container environments. I would say these make them preferred to be used in docker images.

**Comment by timcharper** [comment]
I think it just simply hasn't been updated because doing so would require extensive testing. I think such a change would not happen in a minor release of Marathon, and given this [news](https://d2iq.com/blog/d2iq-takes-the-next-step-forward), it's unlikely to happen now.

**Comment by f1-outsourcing** [comment]
:'( I liked my lean and mean mesos+marathon solution
