### ISSUE TITLE
Create new instance when application goes unhealthy

### ISSUE THREAD

**Issue by lukaswelte** [mesosphere/marathon#729]
When my application instance is determined unhealthy I would want marathon to spin up a new one..
This would achieve high available apps and less maintenance.

Is there already an option doing this, cause it didn't work for me.

I tried it by setting up an instance (2 mesos slaves available) on just one instance and rebooted the slave node the app was running on afterwards. I would have expected marathon to take over (cause he detected the app to be unhealthy) to spin up a new instance on the second mesos slave. But marathon did not do any action…

Thoughts?

**Comment by aquamatthias** [comment]
Please reopen, if problem persists.
