### ISSUE TITLE
Add a Contributor License Agreement

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#730]
@willfry @ssk2 @drexin as discussed in #715.

**Comment by aquamatthias** [comment]
@ConnorDoyle what are the next steps here? Who has the lead here?

**Comment by ConnorDoyle** [comment]
We need to get input from Nathan on this one.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3877. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
