### ISSUE TITLE
Failed to start: Container destroyed during launch

### ISSUE THREAD

**Issue by pangbingqiang** [mesosphere/marathon#734]
hi ,when i use marathon(0.6.1) i found a problem,my job.json is:
{
"id": "helloworld",
"cmd": "./Hello/hello -Dhttp.port=$PORT",
"mem": 512,
"cpus": 1.0,
"instances": 1,
"uris": [
"http://10.175.100.231/Hello.zip"
]
}
hello is a exe file just printf hello world,i find it cannot work,task failed then restart soon,error log is:

E1022 16:40:13.883605 15124 slave.cpp:2484] Container 'bc31a168-663d-47f8-9a62-4588f836f8a3' for executor 'hello.ae37e94f-5a0a-11e4-8b22-283152ac61ed' of framework '20141008-182043-16777343-5050-8143-0000' failed to start: Container destroyed during launch
E1022 16:40:13.883955 15122 slave.cpp:2577] Termination of executor 'hello.ae37e94f-5a0a-11e4-8b22-283152ac61ed' of framework '20141008-182043-16777343-5050-8143-0000' failed: Unknown container: bc31a168-663d-47f8-9a62-4588f836f8a3
E1022 16:40:13.884119 15125 slave.cpp:2863] Failed to unmonitor container for executor hello.ae37e94f-5a0a-11e4-8b22-283152ac61ed of framework 20141008-182043-16777343-5050-8143-0000: Not monitored

But when i change then "cmd" as :
"cmd": "./Hello/hello -Dhttp.port=$PORT && sleep 10",
it works ,the task status is finish,i dont know why?

**Comment by Ferdiism** [comment]
Please re-open if problem persists
