### ISSUE TITLE
Better Task Killing Logic

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#756]
When scaling down, Marathon should make like a lion and cull the weakest tasks first:
1. Out-of-date tasks that are unhealthy or not-yet-healthy
2. Any out-of-date tasks
3. Unhealthy tasks for the current app version
4. Not-yet-healthy tasks for the current app version

**Comment by rasathus** [comment]
This appears to fit with some slightly odd behaviour I was seeing.  

In the case of a growing cluster, where the number of app instances was being scaled with a target of 30.  If a request was made to scale back to 1 all the the healthy instances would be killed, dropping the running instance count to 0 until one of the instances in a state of 'deploying' came online to fulfil the requirement.

**Comment by jasongilanfarr** [comment]
We've made major improvements here.
