### ISSUE TITLE
How can marathon know the each mesos slave resources

### ISSUE THREAD

**Issue by pangbingqiang** [mesosphere/marathon#770]
in my mesos cluster,  slave is different(different cpu number and mem), i deploy an app to cluster,the app have xx instances,and each instance will creat many process, i want to use all  of each slave's cpus, so how to set the  "cpus"  parameter in my json? If i set cpu's value > slave machine cpu value, the task deploy that slave will not work, if i set cpu's value too small ,the resource is waste, so how can i know the each slave resource? thanks~

**Comment by aquamatthias** [comment]
Please reopen, if problem persists.
