### ISSUE TITLE
Add support for custom app data structures

### ISSUE THREAD

**Issue by nickandrew** [mesosphere/marathon#773]
The definition of an app should include a place to add data structures usable by Marathon clients, e.g. service discovery.

Use case: deploying a non-web application such as redis and configuring HAProxy so it knows that application is TCP not HTTP and to listen on the correct public port.

Use case: My corporation wants to associate additional data with each deployment, including patch levels or commit ID and configuration to be consumed by bespoke tools - data usable only within the organisation.

Suggestion: add an opaque key "vendor": {} to the app JSON, which can be filled in with whatever data. Also some kind of definition of the protocol being used on each of the exposed ports may be useful for configuring service discovery. It must be very common to want HAProxy to proxy only a tcp connection from some well-known port number, to the correct slave host:port.

**Comment by defender** [comment]
+1

**Comment by kolloch** [comment]
This should be solved by labels. Reopen if you disagree.
