### ISSUE TITLE
Issue launching project with SBT

### ISSUE THREAD

**Issue by mhamrah** [mesosphere/marathon#775]
* I cloned this repo
* cd'd into the marathon directory
* ran sbt

I received and error when sbt tried to launch:

[error] java.lang.NoSuchMethodError: org.apache.http.impl.conn.DefaultClientConnectionOperator.<init>(Lorg/apache/http/conn/scheme/SchemeRegistry;Lorg/apache/http/conn/DnsResolver;)V

which seems to stem from the Amazon S3 setting:

 at MarathonBuild$$anonfun$publishSettings$1.apply(build.scala:87)

I cleared my ivy cache- not sure what could be going on.

Thanks,

Mike

**Comment by aquamatthias** [comment]
Please reopen, if problem persists.
