### ISSUE TITLE
output from /v2/tasks is corrupted after scaling up

### ISSUE THREAD

**Issue by zaargy** [mesosphere/marathon#786]
Ran into a problem with /v2/tasks starting to return output like this after scaling:

rufus:src:% curl -H "Content-Type: application/json" --socks5-hostname localhost:9999 http://hwd1-mesos-01:8080/v2/tasks

devint-widgetshop-api	0	hwd1-dock-59:31000	hwd1-dock-61:31012	hwd1-dock-59:31008	hwd1-dock-59:31002	hwd1-dock-61:31011	hwd1-dock-60:31005	hwd1-dock-59:31004....

This caused our load balancer config script to fail as it expected JSON. This endpoint was returning JSON before.  Other endpoints (/apps) and the UI work as expected.

Let me know if you need anything else. 

Update: okay after changing the curl to..

curl -H 'Accept: application/json' -H "Content-Type: application/json" http://hwd1-mesos-03:8080/v2/tasks

..it works as expected. It was behaving inconsistently though.

**Comment by Ferdiism** [comment]
Please re-open if problem persists
