### ISSUE TITLE
Get rid of the Modal/lightbox

### ISSUE THREAD

**Issue by mlunoe** [mesosphere/marathon#810]
Get rid of the Modal/lightbox

In marathon the modal was introduced early on, but have since been filled with A LOT of content. It doesn't really makes sense to have this anymore, so let's get rid of if. Take contents of the modal and move it out to a single page, so it looks something like this:

![Task list](http://cl.ly/image/2E0s1C3d403g/marathon-task-list.png)
![Task details](http://cl.ly/image/2G1Z1C0N3W2z/marathon-task-details.png)

**Comment by aldipower** [comment]
@mlunoe I've tried to implement the breadcrumbs ```Apps > /my-app```, but decided not to integrate it into #1123 because it looks a little bit messy. I can show you this in a separate branch, if you like.

**Comment by mlunoe** [comment]
@aldipower: Ok, just to make sure that we are aligned. It is only the app-modal we are trying to move out into pages.
