### ISSUE TITLE
Marathon loses connection to running task

### ISSUE THREAD

**Issue by lukaswelte** [mesosphere/marathon#821]
Marathon loses the connection after some amount of time (varies between an hour and multiple hours).
The Task is still running and healthy on Mesos, but Marathon no longer displays the task instead it wants to fill the gap (0/1 for example) but does not even start a new instance. Just happens on one task not on all the same time, what feels a bit strange.

Any ideas and how I can debug this. Can I delete all data stored in Marathon for one specific task id? 

Using Marathon 0.7.5 running on each of 3 Mesos Master Nodes (0.20.1)

**Comment by aquamatthias** [comment]
Please reopen, if problem persists.
