### ISSUE TITLE
Provide abstract interface to State

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#825]
Implementations of the Mesos state API may differ in expected performance for read and update operations.  For example, while writing large binary blob snapshots to the ZK backed state is an anti-pattern, the replicated log backed state with binary diffs enabled performs very well when used this way.  These differences could be handled behind an abstract interface for state-backed collections in Marathon.  To this end, we (@ConnorDoyle and @drexin) propose an internal wrapper type to do just that:

_Mesos state wrapper pseudocode:_

``` scala
trait StateWrapper[T: MarathonState[T]] {

  protected[this] var collections: Map[String, StateCollection[T]]

  trait StateCollection[T]

  trait StateSeq[T] extends StateCollection[T] { /* ... */ }
  trait StateSet[T] extends StateCollection[T] { /* ... */ }
  trait StateMap[String, T] extends StateCollection[T] { /* ... */ }

  def makeSeq(name: String): StateSeq[T]
  def makeSet(name: String): StateSet[T]
  def makeMap(name: String): StateMap[String, T]

  def getSeq(name: String): Option[StateSeq[T]]
  def getSet(name: String): Option[StateSet[T]]
  def getMap(name: String): Option[StateMap[String, T]]

}
```

The intended usage is that the trait can be implemented with special optimizations for each supported state implementation.

**Comment by jasongilanfarr** [comment]
This trait is dying anyways.
