### ISSUE TITLE
Port range support

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#835]
Some caching services can do automatic sharding of keys across many nodes. Memcached with ketama can do that, for example. You just provide list of servers and sharding is handled automatically.

For memcached `host:port` string matters, since it is used for hashing. However, with marathon you get new hostname and port each time you start the task. Proxying with something like bundled haproxy script can fix hostname, but all instances will be accessible from one port with round-robin balancing.

Solution I can think of:

1. Provide "port range" (may be range `X-Y` or list `X,Y,Z`) for app, which is bigger or equal to number of instances.
2. When task from the app starts, it picks the port from range
3. Haproxy or similar solution is using instance port from range to provide access for specific instance

Are there any other options that don't require reloading app configuration each time some tasks are rescheduled on marathon? twemproxy does not support reloading without downtime and requires watching marathon changes for haproxy and twemproxy.

If task order in marathon api is static, then task offset could be used as increment for port number in haproxy, but this is even more hacky than described "port range" solution. Moreover, there should be some indicator that app is required to have instances on different ports of haproxy.

**Comment by bobrik** [comment]
#773 could help.

**Comment by bobrik** [comment]
I was able to implement that in [marathoner](http://github.com/bobrik/marathoner) with labels. Now I'm able to run memcached cluster as a single application.

**Comment by sttts** [comment]
@bobrik Cool project!

**Comment by bobrik** [comment]
Looks like with twitter/twemproxy#321 and another marathoner listener I'll be able to write twemproxy that is mararhon-friendly.

Closing this since it's better to solve that issue outside of marathon anyway.
