### ISSUE TITLE
A "*" Constraint for unique should exist

### ISSUE THREAD

**Issue by florianleibert** [mesosphere/marathon#846]
This constraint would ensure that a command is run on all slaves in the cluster.

**Comment by pigeonflight** [comment]
+1

**Comment by defender** [comment]
Hi ConnorDoyle
A "*" Constraint for unique should exist #846 do you think it will be released at 0.8.1, this bug was already reassign several times :)

thanks.

**Comment by drexin** [comment]
We can't ensure that a task is running on all slaves in the cluster for following reasons:

1. we can't guarantee that there are enough resources on every machine
2. in a multi framework cluster, we don't know if we will ever receive offers for all the machines
3. we could never tell if it has been deployed successfully, because we don't know about all the machines in the cluster

I think this would need direct support from Mesos.

**Comment by EmileVauge** [comment]
+1

**Comment by drexin** [comment]
Moving this to backlog, as it is not possible to implement this in a reliable manner without support from Mesos.

**Comment by matt-deboer** [comment]
@drexin, you mentioned: 
> &nbsp;3. we could never tell if it has been deployed successfully

Can't you just query the Mesos REST api for the cluster topology, and then keep track of whether the offers received (within some time-limit) covered all the hosts? 
  
    GET http://{mesos-master}:5050/registrar(1)/registry

You'd probably also have to have some way of listening for changes to the mesos registry such that you could deploy the "once-per-host" apps to newly added hosts.

For the other two, 
> 1. we can't guarantee enough resources on every machine
> 2. in a multi framework cluster, we don't know if we will ever receive offers for all the machines

...aren't these true for any deployment? I.e., a deployment asks for N instances, there's no guarantee that there are N instances worth of resources available (and that we'll get offers for them)?

Maybe some of the resource contention problem could be alleviated by having some way to load these once-per-host apps on framework startup...(of course, that might require an ordered startup of frameworks--i.e., make marathon start first)?

Am I on the right track here?

**Comment by wricardo** [comment]
:+1:

**Comment by rewiko** [comment]
+1

**Comment by kolloch** [comment]
Basically, we would need to query the Mesos api for the available slaves regularly. We only get events for lost slaves. It's possible but this is the only use case so far.

But much more important: You somehow need to provision your slaves. If you make something that you want to run on all slaves part of your slave provisioning, you are _sure_ that it runs on all slaves. Implementing this in Marathon is complicated AND by nature fragile.

**Comment by air** [comment]
See #1264 for additional chat on this.

**Comment by BrickXu** [comment]
join this thread

**Comment by clehene** [comment]
Here's a the equivalent from Kubernetes - it's called ["Daemon Sets"](http://kubernetes.io/v1.1/docs/admin/daemons.html) 
Curious if Kubernetes on Mesos supports this. 

@drexin I understand the complexity, I think the right way to go about this is to figure out what exactly is needed and discuss this with Mesos devs.

**Comment by philipnrmn** [comment]
Some great documentation on using `GROUP_BY` and another feature request for this in #3220

**Comment by scatterbrain** [comment]
+1 really important for many kinds of services (monitoring etc)

**Comment by graphex** [comment]
+1 a very useful addition. Yes, this could be done with less complexity _to Marathon_ by provisioning all services on all slaves up front, but that just shifts the complexity and burden of updates and redeploys. If a frequently changing app needs to be on each host, having marathon manage redeployment/restarting/configuration in a consistent manner would be very helpful. Would be worth coordinating any necessary changes to Mesos, and appropriate separation of concerns. Is there a corresponding thread in Mesos for this?

**Comment by drewrobb** [comment]
I have been doing this by setting an autoscaling rule against the metrics we populate for the number of running slaves against an app with a hostname:UNIQUE constraint that we want on every slave. (I also have a simple internally written autoscaling service for our marathon apps). We also configured each slave to have a small amount of resources reserved for a specific role, and that role is only used by apps that need to run on every slave. It has been working pretty nicely in practice.

**Comment by mvanholsteijn** [comment]
Being able to define a application that needs to run on every slave is essential functionality of a scheduler.

In [Nomad](https://www.nomadproject.io/docs/jobspec/) these are called system Jobs, in [CoreOS Fleet](https://coreos.com/fleet/docs/latest/unit-files-and-scheduling.html) the are called global units.

So, what will the Marathon equivalent be called and how do we activate them?

It would make our live really easy. We need it now.......

**Comment by edurdias** [comment]
+1

**Comment by clehene** [comment]
Marathon shouldn't guarantee that resources exist.
We can guarantee resources in Mesos through reservations. 

The 1-1 framework - role "binding" may become the next issue, though as we'd need / like to ensure resources by workloads (in Marathon) rather than have it for the entire framework.

**Comment by vkhatri** [comment]
+1

**Comment by JamieCressey** [comment]
+1 this would be hugely beneficial for monitoring and log extraction etc.

**Comment by mimmus** [comment]
We need this now :+1:

**Comment by fksimon** [comment]
+1

**Comment by sybrandy** [comment]
@JamieCressey is correct.  We're in the same situation where we want to make sure telegraf and logspout are running on all of the slaves for metrics and log collection.  It would be great if Marathon/Mesos can ensure that we have instances of each on every node in case failed nodes come back online or we add additional nodes to the cluster.

**Comment by jdef** [comment]
Running daemons on every node in the cluster in an efficient, robust manner will almost certainly require assistance from Mesos. If you want this feature then I encourage you to vote for support in Mesos because without that we're a bit stranded in Marathon-land.

A workaround meanwhile is to use a `hostname UNIQUE` constraint with `instances` set to a greater number of agents than you ever expect to have in your cluster.

https://issues.apache.org/jira/browse/MESOS-6595

**Comment by silvamerica** [comment]
@jdef Does your workaround leave hanging deployments around, since Marathon will never be able to satisfy the number of instances specified?

**Comment by jdef** [comment]
Using a greater number of instances is not ideal for interaction w/ the
deployment manager. If you're running a fairly static cluster then you
could set # instances to match the number of agents you expect to have. If
you expect to increase the number of agents in the cluster, then increase
`instances` to match just prior to adding the agent(s). It's a workaround,
not a "solution".

**Comment by gengmao** [comment]
@jdef probably a dumb question - why Marathon can't deploy a daemon (with `instances=*` and `hostname UNIQUE`) to any new agents offered by Mesos? What specific supports have to be provided by Mesos?

**Comment by hampsterx** [comment]
+1

**Comment by dlaidlaw** [comment]
+1 1 per instance per role. If an agent has a specific role, and the acceptedResourceRoles matches then deploy there. This is like an autoscaling that is performed as soon as a new instance is detected and before any other deployments can happen on that new instance.

**Comment by janisz** [comment]
👎 
What if there are no resources to run this app on every agent? If service needs to be running on all agents then there are better ways to put it there (upstart/systemd/supervisor  + ansible/puppet/chef/salt).

**Comment by dangra** [comment]
@janisz the resources for these  services is something you usually plan and reserve ahead of time. I am not interested on "before any other deployments can happen", just running a service on all agents that meets the criteria is enough for me.

**Comment by mimmus** [comment]
On CoreOS (systemd-based), I'm solving dropping-in a unit file to run and restart a monitoring Docker container but it would be great having a way to manage this by Marathon.

**Comment by tobilg** [comment]
Question I see regarding this:

- What should happen if there are agent nodes added to the cluster? Should Marathon automatically be able to schedule the app on these new nodes as well? 

This would mean IMO that Marathon would need to to utilize the `/slaves` endpoint of the masters (I guess it does so already?), and compare the list of slave from the current call to the list of slaves from the last call... Not sure about the implications.

- Concerning mixing string and integer in a property as @janisz said, I think this wouldn't be a good idea either. 

This would effectively mean to change the type of the `instances` property to string, and then testing and potentially parsing it as integer. It could be discussed if the value `-1` could replace `*`, but maybe there's a better idea.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3791. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
