### ISSUE TITLE
Unable to assign servicePort or hostPort

### ISSUE THREAD

**Issue by sivaramsk** [mesosphere/marathon#847]
The below configuration works properly with hostPort and servicePort getting assigned a random port. But If I set a value to hostPort and servicePort, it is not binding to that port and value is not getting shown in the UI itself.
For example 
{ "containerPort": 6379, "hostPort": 0, "servicePort": 10000, "protocol": "tcp"}

with the above config, the service port is not getting bind to 10000. What am i doing wrong?

{
  "id": "redis-master",
  "instances": "1",
  "cpus": "0.2",
  "mem": "128",
  "container": {
    "type": "DOCKER",
    "docker": {
      "image": "dockerfile/redis",
      "network": "BRIDGE",
      "portMappings": [
	{ "containerPort": 6379, "hostPort": 0, "servicePort": 0, "protocol": "tcp"}
	]
    }
  }
}

**Comment by aquamatthias** [comment]
Is that problem still there? Please reopen, if yes.
