### ISSUE TITLE
Groups and Applications may not have the same identifier

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#851]
I created app `/something/app`, but then I decided that I'd better have `/something/app/service`. I removed `/something/app`, but when I try to create `/something/app/service`, I get an error:

```
Groups and Applications may not have the same identifier
```

I think there should be no error here.

_UPDATE_

The steps to reproduce this problem are:

1. `PUT /v2/apps/something/app`
2. `DELETE /v2/apps/something/app`
3. `PUT /v2/apps/something`, not `PUT /v2/apps/something/app/service`

**Comment by kolloch** [comment]
I am preparing a PR for this.

@bobrik if you need a workaround, you should be able to delete the empty groups explicitly with the corresponding [DELETE calls](https://mesosphere.github.io/marathon/docs/rest-api.html#delete-/v2/groups/{groupid}).

**Comment by kolloch** [comment]
@ConnorDoyle @bobrik: I thought about this some more. Actually, I do not agree that empty groups should be automatically removed. 

= The problem with ignoring empty groups

At least with my PR, empty groups are allowed (= the request is not rejected) but creating them with a PUT/POST has no effect. That is strange. Rejecting empty groups is an API change and not an option right now.

What is more, groups contain information besides the contained apps/groups. Right now, the dependencies and the timestamp. It is plausible that we add something like a description in the future.

I would be unexpected by a user that deletes all apps in a group with DELETE app requests if that information would be deleted without further notice. Especially, if he planned to recreate the apps later on with other definitions. 

= Proposal

I propose that [PUT app](https://mesosphere.github.io/marathon/docs/rest-api.html#put-/v2/apps/%7Bappid%7D) and the [PUT group](https://mesosphere.github.io/marathon/docs/rest-api.html#put-/v2/groups/%7Bgroupid%7D) requests, substitute the item at the path -- whether it is a group or a path. They also create missing parent groups as before.

Therefore, you can substitute a group with an app and vice-versa.

= @bobrik's initial Problem

Actually, I do not really understand it. Maybe, it was an issue with an older version of Marathon or you used other API requests?

Step 1) Create something/app
```http
PUT /v2/apps/something/app HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 194
Content-Type: application/json
Host: localhost:8080
User-Agent: HTTPie/0.9.2

{
    "cmd": "python -m SimpleHTTPServer $PORT", 
    "cpus": 0.0001, 
    "disk": 0, 
    "healthChecks": [], 
    "id": "something/app", 
    "instances": 1, 
    "mem": 8, 
    "ports": [
        0
    ], 
    "uris": []
}

HTTP/1.1 201 Created
Cache-Control: no-cache, no-store, must-revalidate
Content-Type: application/json
Expires: 0
Location: http://localhost:8080/v2/apps/something/app/something/app
Pragma: no-cache
Server: Jetty(8.1.15.v20140411)
Transfer-Encoding: chunked

{
    "deploymentId": "cb2a1553-cf8f-4836-9c98-2185bfb47b7c", 
    "version": "2015-04-13T12:14:32.987Z"
}
```

2) Stop something/app again
```http
DELETE /v2/apps/something/app HTTP/1.1
Accept: */*
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 0
Host: localhost:8080
User-Agent: HTTPie/0.9.2



HTTP/1.1 200 OK
Cache-Control: no-cache, no-store, must-revalidate
Content-Type: application/json
Expires: 0
Pragma: no-cache
Server: Jetty(8.1.15.v20140411)
Transfer-Encoding: chunked

{
    "deploymentId": "a5d3242a-fdca-41f4-a003-2f2e393715af", 
    "version": "2015-04-13T12:14:38.648Z"
}
```

3) Start something/app/service

```http
PUT /v2/apps/something/app/service HTTP/1.1
Accept: application/json
Accept-Encoding: gzip, deflate
Connection: keep-alive
Content-Length: 202
Content-Type: application/json
Host: localhost:8080
User-Agent: HTTPie/0.9.2

{
    "cmd": "python -m SimpleHTTPServer $PORT", 
    "cpus": 0.0001, 
    "disk": 0, 
    "healthChecks": [], 
    "id": "something/app/service", 
    "instances": 1, 
    "mem": 8, 
    "ports": [
        0
    ], 
    "uris": []
}

HTTP/1.1 201 Created
Cache-Control: no-cache, no-store, must-revalidate
Content-Type: application/json
Expires: 0
Location: http://localhost:8080/v2/apps/something/app/service/something/app/service
Pragma: no-cache
Server: Jetty(8.1.15.v20140411)
Transfer-Encoding: chunked

{
    "deploymentId": "53438ef6-d1dc-42d4-aaad-b0383c272f5a", 
    "version": "2015-04-13T12:15:01.500Z"
}

```

=> app is up and running

**Comment by bobrik** [comment]
1. `PUT /v2/apps/something/app`
2. `DELETE /v2/apps/something/app`
3. `PUT /v2/apps/something`, not `PUT /v2/apps/something/app/service`

**Comment by kolloch** [comment]
Ok, @bobrik. Makes sense. I was just worried that it doesn't work for you the other way around.

I agree that this should work and it is covered by my proposal.

**Comment by bobrik** [comment]
I'm okay with overwriting an empty group with an application, not sure if that's okay with:

* application with empty group
* application with non-empty group (application `/app`, then application `/app/service`)
* non-empty group with application

From 4 options only one seems sane for me.

**Comment by kolloch** [comment]
Thanks for your thoughts.

I can think of use cases for all of them:

A) replacing an empty group with an app: That was the original request.
B) replacing an application with a non-empty group: Leave the dependencies intact but replace a single app definition service with something more complex.
C) replacing a non-empty group with an application: The reverse.
D) Replacing an application with an empty group is an unusual way of stopping that app. But people use Marathon in different ways. While I generally think that group PUTs are awesome, someone else might prefer first creating the group and the create the apps inside with additional requests.

I generally think that the semantics of PUT should be: Replace the current entity at that path with something new. It is just a bit strange that groups and apps use the same namespace but different endpoints.

I would like to hear what other people think about that. Technically, it is entirely possible to only allow selected use cases of the above, e.g. only A.

**Comment by kolloch** [comment]
Ok, basically we are talking about allowing some more requests than are permissible right now. If we are not sure about what is best, maybe we should only extend it the least necessary.

I think everyone agrees that one should be able to substitute an empty group with an application by using an app PUT request. Empty group is defined as a group that neither directly or indirectly contains any apps. 

This makes sense especially considering that the current GUI doesn't expose groups at all except as a path element.

**Comment by bobrik** [comment]
:tada:

**Comment by nugend** [comment]
Kinda skimmed the thread: was the behavior of what happens when you POST a non-emtpy group to an empty group discussed? I think it'd make sense to allow overwrite. Right now I think a 409 status code is being returned.

**Comment by kolloch** [comment]
Hi @nugend, Use a PUT for that instead of a POST. A PUT can be used to update existing groups.

**Comment by nugend** [comment]
I suppose you're right. I went with a DELETE then a POST (in case there's something there already).
