### ISSUE TITLE
Docs site cleanup

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#854]
A problem right now is that the docs currently do not indicate which version they describe.
It would be better if we hosted a snapshot of the docs site for every release (git tag).

Here's a good template to emulate (from Typesafe): https://github.com/typesafehub/doc-template.

**Comment by Ferdiism** [comment]
We have started to tag all versions in the documentation (should suffice).
Please re-open if you think that is wrong.
