### ISSUE TITLE
E: Package 'mesos' has no installation candidate for Ubuntu 14.10

### ISSUE THREAD

**Issue by sukenneth** [mesosphere/marathon#869]
Hello, I installed Ubuntu 14.10 server and I tried to install Mesos.  I did add the key and also the following commands, however, I still got the error which Ubuntu is not able to find the repo for Mesophere? I google and found the commands and steps are right, but just Ubuntu 14.04 is different than 14.10 which I use. 

Any idea? Thanks for your answer

commands:
$sudo apt-key adv --keyserver keyserver.ubuntu.com --recv E56151BF
$echo "deb http://repos.mesosphere.io/${DISTRO} ${CODENAME} main" | sudo tee /etc/apt/sources.list.d/mesosphere.list
$ cat mesosphere.list
deb http://repos.mesosphere.io/ubuntu utopic main

error:
$ sudo apt-get -y install mesos marathon
Reading package lists... Done
Building dependency tree
Reading state information... Done
Package mesos is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'mesos' has no installation candidate

**Comment by rv0147** [comment]
hello, same error for me but with ubuntu 12.04. should i replace precise with the same(trusty)

Thanks

**Comment by lingmann** [comment]
Hi @rv0147 There are mesos and marathon packages for precise available. Please make sure to check your /etc/apt/sources.list.d/mesosphere.list. It should look something like:
```
deb http://repos.mesosphere.io/ubuntu precise main
```

Then run an `apt-get update && apt-get install mesos marathon`
