### ISSUE TITLE
Setting 'cmd' parameter via POST does not change in certain circumstances

### ISSUE THREAD

**Issue by andrewortman** [mesosphere/marathon#874]
I'm able to reproduce an interesting bug introduced in 0.7.6 -

1) Launch a docker app (PUT) with cmd being an empty string
2) After the app started, do a POST to update the app by changing the cmd parameter to something other than an empty string (like a while loop)
3) A deployment will start, but the app isn't actually updated to include the new cmd.

Something interesting is that if you restart Marathon itself, it will redeploy that app with the proper command.

We have a docker container that has an integrated development debug command. We got around this by launching the container with an argument instead of a CMD overwrite.

**Comment by aquamatthias** [comment]
Is that still a problem? Please reopen, if this is the case.
