### ISSUE TITLE
Jump to Mesos sandbox from UI

### ISSUE THREAD

**Issue by chendo** [mesosphere/marathon#878]
It would be fantastic to be able to jump to the relevant Mesos sandbox for the task in the task list view.

**Comment by xor-xor** [comment]
+1

**Comment by quamilek** [comment]
Currently in [Allegro Group](https://github.com/allegro) we are working on this.
See below visualization for this feature.
![mesos-task-url-example](https://cloud.githubusercontent.com/assets/695791/8649614/44b81b34-296c-11e5-9741-5ce977df4055.png)

What do you think?

**Comment by kamilchm** [comment]
@MarathonDevs - what do you think about the labels?
I think that we could put empty header and ``Sandbox`` link in each row. It'll be consistent with Mesos UI.

**Comment by philipnrmn** [comment]
@quamilek that's great to hear! We'd be really interested to see more. 

@kamilchm I've just done a bit of hallway testing, the consensus seems to be that it would be neat either to have a separate row, or to link to the sandbox directly from the node name (`mesos-slave1.local:12345` in this case). The extra column consumes space, and the sort option is a little confusing.

**Comment by wendigo** [comment]
@philipnrmn maybe we can inline this link after the node name? I think that node name with port alone is a valuable information and personally I would leave it as it is.

**Comment by janisz** [comment]
I'm working on this ([here](https://github.com/janisz/marathon/commit/15110a749e6b0f68198b18133d62316fc3955bec) you can see progress). Simply I extended `MarathonTask` with field that contains URL to sandbox, it's populated in `DefaultTaskFactory.scala` with information from offer. I've problem with obtaining mesos api host and port. On first sight it could be `config.mesosMaster` but it's zk address. 
What is the best way to get mesos api url in Marathon?

**Comment by quamilek** [comment]
I prepared two proposal of link location

**1. located after node name:**
![mesos_details_example2](https://cloud.githubusercontent.com/assets/695791/8716845/39693eae-2b95-11e5-9f97-1e5e7094c81a.png)
**2. located on task details page:**
![mesos_details_example1](https://cloud.githubusercontent.com/assets/695791/8716850/42603634-2b95-11e5-9d25-ce60584d5ee0.png)

**Comment by pierlo-upitup** [comment]
@quamilek thanks for your suggestions, we are going to look into the best solution for this shortly!

**Comment by pierlo-upitup** [comment]
https://github.com/mesosphere/marathon/pull/1882

**Comment by aldipower** [comment]
https://github.com/mesosphere/marathon-ui/pull/114
