### ISSUE TITLE
Non-leader marathon holds on to "phantom" tasks

### ISSUE THREAD

**Issue by sdwr98** [mesosphere/marathon#885]
I have a Mesos 0.21.0 + Marathon 0.7.5 (now 0.7.6, but same issue is happening) cluster set up and I'm seeing an odd behavior.  I have 3 masters set up, and one of the marathon masters (not the current leader) seems to have a phantom task that it thinks is alive and keeps trying to kill.  Here's the relevant log detail:

    12:36:50.062  host=mesosmaster2-staging tag=marathon[11591]:  [WARN] [12/08/2014 09:36:50.020] [marathon-akka.actor.default-dispatcher-127] [akka://marathon/user/IO-HTTP/host-connector-2/13] Connection attempt to mesosnode1-staging:32000 failed in response to GET request to /about-us with 5 retries left, retrying... Context
    12:36:50.064  host=mesosmaster2-staging tag=marathon[11591]:  [WARN] [12/08/2014 09:36:50.020] [marathon-akka.actor.default-dispatcher-132] [akka://marathon/user/IO-HTTP/host-connector-2/12] Connection attempt to mesosnode1-staging:32000 failed in response to GET request to /about-us with 4 retries left, retrying... Context
    12:36:50.064  host=mesosmaster2-staging tag=marathon[11591]:  [WARN] [12/08/2014 09:36:50.021] [marathon-akka.actor.default-dispatcher-135] [akka://marathon/user/IO-HTTP/host-connector-2/13] Connection attempt to mesosnode1-staging:32000 failed in response to GET request to /about-us with 3 retries left, retrying... Context
    12:36:50.064  host=mesosmaster2-staging tag=marathon[11591]:  [WARN] [12/08/2014 09:36:50.021] [marathon-akka.actor.default-dispatcher-130] [akka://marathon/user/IO-HTTP/host-connector-2/12] Connection attempt to mesosnode1-staging:32000 failed in response to GET request to /about-us with 2 retries left, retrying... Context
    12:36:50.065  host=mesosmaster2-staging tag=marathon[11591]:  [WARN] [12/08/2014 09:36:50.022] [marathon-akka.actor.default-dispatcher-129] [akka://marathon/user/IO-HTTP/host-connector-2/13] Connection attempt to mesosnode1-staging:32000 failed in response to GET request to /about-us with 1 retries left, retrying... Context
    12:36:50.065  host=mesosmaster2-staging tag=marathon[11591]:  [WARN] [12/08/2014 09:36:50.022] [marathon-akka.actor.default-dispatcher-135] [akka://marathon/user/IO-HTTP/host-connector-2/12] Connection attempt to mesosnode1-staging:32000 failed in response to GET request to /about-us with no retries left, dispatching error... Context
    12:36:50.065  host=mesosmaster2-staging tag=marathon[11591]:  [INFO] [12/08/2014 09:36:50.022] [marathon-akka.actor.default-dispatcher-129] [akka://marathon/user/$a] Received health result: [Unhealthy(web-redirect.e40bfd46-7b18-11e4-99ff-005056a0430e,2014-12-02T21:45:29.000Z,ConnectionAttemptFailedException: Connection attempt to mesosnode1-staging:32000 failed,2014-12-08T17:36:50.022Z)] Context
    12:36:50.065  host=mesosmaster2-staging tag=marathon[11591]:  [INFO] [12/08/2014 09:36:50.022] [marathon-akka.actor.default-dispatcher-129] [akka://marathon/user/$a] Killing task web-redirect.e40bfd46-7b18-11e4-99ff-005056a0430e on host mesosnode1-staging Context
    12:36:50.150  host=mesosmaster2-staging tag=marathon[11591]:  [2014-12-08 09:36:50,022] WARN Task [web-redirect.e40bfd46-7b18-11e4-99ff-005056a0430e] for app [/web-redirect] was killed for failing too many health checks (mesosphere.marathon.MarathonScheduler:222) Context
    12:36:50.150  host=mesosmaster2-staging tag=marathon[11591]:  [2014-12-08 09:36:50,024] INFO Task launch delay for [/web-redirect] is now [3600] seconds (mesosphere.util.RateLimiter:34) Context

However, that task does not show up in the REST API under /v2/tasks or in the Marathon UI.  I've verified that there is no such container running on mesosnode1-staging and the current leader doesn't try to do anything about it.  

I can clear the behavior by restarting that marathon process, but the next time I do a deployment, that non-leader marathon instance starts complaining about one of the tasks that just got killed during the most recent deployment.

**Comment by sttts** [comment]
This should be fixed due to the fix of #356.

**Comment by drexin** [comment]
Yep, closing this.
