### ISSUE TITLE
play.api.libs.json.JsResultException when submitting tasks using REST API

### ISSUE THREAD

**Issue by tregoreg** [mesosphere/marathon#887]
Version 0.7.6.
When trying to submit tasks (using the call that worked before last upgrade to 0.7.6), I'm getting the following exception which results in HTTP 500. I don't know what the problem could be.

    @40000000548a286c334c4554 [2014-12-12 00:27:30,860] WARN  (mesosphere.marathon.api.MarathonExceptionMapper:27)
    @40000000548a286c334c704c play.api.libs.json.JsResultException: JsResultException(errors:List((/env/NICE,List(ValidationError(error.expected.jsstring,WrappedArray()))), (/env/FWD_BACKEND,List(ValidationError(error.expected.jsstring,WrappedArray()))), (/env/MQLR_BACKEND,List(ValidationError(error.expected.jsstring,WrappedArray())))))
    @40000000548a286c334c7c04       at play.api.libs.json.JsValue$$anonfun$2.apply(JsValue.scala:67)
    @40000000548a286c334c83d4       at play.api.libs.json.JsValue$$anonfun$2.apply(JsValue.scala:67)
    @40000000548a286c334c87bc       at play.api.libs.json.JsResult$class.fold(JsResult.scala:77)
    @40000000548a286c334c8f8c       at play.api.libs.json.JsError.fold(JsResult.scala:13)
    @40000000548a286c334c9374       at play.api.libs.json.JsValue$class.as(JsValue.scala:65)
    @40000000548a286c334c975c       at play.api.libs.json.JsObject.as(JsValue.scala:166)
    @40000000548a286c334cbe6c       at mesosphere.marathon.api.v2.AppsResource.create(AppsResource.scala:84)
    @40000000548a286c334cc254       at sun.reflect.GeneratedMethodAccessor212.invoke(Unknown Source)
    @40000000548a286c334cc63c       at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    @40000000548a286c334cce0c       at java.lang.reflect.Method.invoke(Method.java:606)
    @40000000548a286c334cd9c4       at com.sun.jersey.spi.container.JavaMethodInvokerFactory$1.invoke(JavaMethodInvokerFactory.java:60)
    @40000000548a286c334cddac       at com.sun.jersey.server.impl.model.method.dispatch.AbstractResourceMethodDispatchProvider$ResponseOutInvoker._dispatch(AbstractResourceMethodDispatchProvider.java:205)
    @40000000548a286c334ce57c       at com.sun.jersey.server.impl.model.method.dispatch.ResourceJavaMethodDispatcher.dispatch(ResourceJavaMethodDispatcher.java:75)
    @40000000548a286c334ce964       at com.codahale.metrics.jersey.InstrumentedResourceMethodDispatchProvider$TimedRequestDispatcher.dispatch(InstrumentedResourceMethodDispatchProvider.java:30)
    @40000000548a286c334ced4c       at com.sun.jersey.server.impl.uri.rules.HttpMethodRule.accept(HttpMethodRule.java:302)
    @40000000548a286c334cf51c       at com.sun.jersey.server.impl.uri.rules.ResourceClassRule.accept(ResourceClassRule.java:108)
    @40000000548a286c334cf904       at com.sun.jersey.server.impl.uri.rules.RightHandPathRule.accept(RightHandPathRule.java:147)
    @40000000548a286c334cfcec       at com.sun.jersey.server.impl.uri.rules.RootResourceClassesRule.accept(RootResourceClassesRule.java:84)
    @40000000548a286c334d00d4       at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1542)
    @40000000548a286c334d0c8c       at com.sun.jersey.server.impl.application.WebApplicationImpl._handleRequest(WebApplicationImpl.java:1473)
    @40000000548a286c334d1074       at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1419)
    @40000000548a286c334d339c       at com.sun.jersey.server.impl.application.WebApplicationImpl.handleRequest(WebApplicationImpl.java:1409)
    @40000000548a286c334d3784       at com.sun.jersey.spi.container.servlet.WebComponent.service(WebComponent.java:409)
    @40000000548a286c334d3b6c       at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:540)
    @40000000548a286c334d3f54       at com.sun.jersey.spi.container.servlet.ServletContainer.service(ServletContainer.java:715)
    @40000000548a286c334d433c       at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
    @40000000548a286c334d4724       at com.google.inject.servlet.ServletDefinition.doService(ServletDefinition.java:263)
    @40000000548a286c334d4b0c       at com.google.inject.servlet.ServletDefinition.service(ServletDefinition.java:178)
    @40000000548a286c334d52dc       at com.google.inject.servlet.ManagedServletPipeline.service(ManagedServletPipeline.java:91)
    @40000000548a286c334d56c4       at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:62)
    @40000000548a286c334d5e94       at mesosphere.marathon.api.LeaderProxyFilter.doFilter(LeaderProxyFilter.scala:56)
    @40000000548a286c334d627c       at com.google.inject.servlet.FilterDefinition.doFilter(FilterDefinition.java:163)
    @40000000548a286c334d6664       at com.google.inject.servlet.FilterChainInvocation.doFilter(FilterChainInvocation.java:58)
    @40000000548a286c334d6a4c       at com.google.inject.servlet.ManagedFilterPipeline.dispatch(ManagedFilterPipeline.java:118)
    @40000000548a286c334d6e34       at com.google.inject.servlet.GuiceFilter.doFilter(GuiceFilter.java:113)
    @40000000548a286c334d721c       at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1467)
    @40000000548a286c334d7604       at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
    @40000000548a286c334d79ec       at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
    @40000000548a286c334d81bc       at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:429)
    @40000000548a286c334d915c       at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
    @40000000548a286c334d9544       at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    @40000000548a286c334d992c       at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    @40000000548a286c334da0fc       at com.codahale.metrics.jetty8.InstrumentedHandler.handle(InstrumentedHandler.java:192)
    @40000000548a286c334da4e4       at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
    @40000000548a286c334da8cc       at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    @40000000548a286c334dacb4       at org.eclipse.jetty.server.Server.handle(Server.java:370)
    @40000000548a286c334db09c       at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:494)
    @40000000548a286c334db484       at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:982)
    @40000000548a286c334db86c       at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1043)
    @40000000548a286c334dbc54       at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
    @40000000548a286c334dc03c       at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
    @40000000548a286c334dc424       at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    @40000000548a286c334dc80c       at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:696)
    @40000000548a286c334dcbf4       at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:53)
    @40000000548a286c334dd7ac       at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    @40000000548a286c334ddb94       at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    @40000000548a286c334ddf7c       at java.lang.Thread.run(Thread.java:745)
    @40000000548a286c33522924 [2014-12-12 00:27:30,860] INFO 10.0.0.25 -  -  [11/Dec/2014:23:27:30 +0000] "POST /v2/apps HTTP/1.1" 500 284 "-" "Ruby" (mesosphere.chaos.http.ChaosRequestLog:15)

**Comment by drexin** [comment]
Fixed in https://github.com/mesosphere/marathon/issues/908
