### ISSUE TITLE
Invalid task data

### ISSUE THREAD

**Issue by chendo** [mesosphere/marathon#896]
Marathon 0.7.6, Mesos 0.21.0.

We've seen an issue where Marathon restarted abnormally and lost a bunch of task data, including the hostname and the port, which causes the haproxy script to write an invalid config and fail.

We have no idea what caused the issue at this stage.

**Comment by sttts** [comment]
This one really is a blocker. I get this quite often on our production cluster, using Docker. I only saw it once I think in my dev environment.

Any new insights on this?

**Comment by sttts** [comment]
Seeing a lot of "No staged task for ID ...." lines in the logs, coming from TaskTracker.running. I believe this code is responsible for creating the bad tasks, i.e. the second "case _" branch in that function.

**Comment by ConnorDoyle** [comment]
Is anyone still seeing this behavior with latest master?

**Comment by sttts** [comment]
Never seen again since #945.
