### ISSUE TITLE
Need a way to set docker_stop_timeout

### ISSUE THREAD

**Issue by lcarstensen** [mesosphere/marathon#898]
Related Mesos feature is here:

https://github.com/apache/mesos/commit/eb075f9b7b518a72249f5a68538f356ba63aa79d

This was implemented in Mesos to allow daemons in a Docker container an ability to gracefully shutdown.  It would be desirable to set a similar stop timeout via Marathon.

**Comment by nevins-b** [comment]
related to #712

**Comment by raghu999** [comment]
Is there any Work around for this . We want to set the docker_set_timeout in marathon when its killing the container or when the process is getting automatically killed/Redeployed. It would be nice to provide an option where we can initiate a gracefull shutdown or if we can make marathon to  delay the docker_stop time.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3817. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
