### ISSUE TITLE
Introduce abstraction for leader election

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#900]
Open the door to other leader election mechanisms besides Zookeeper.

**Comment by kolloch** [comment]
Let's first focus on #1310. I wouldn't currently plan this. We can recreate/open this issue if it comes up again.

**Comment by ConnorDoyle** [comment]
Agree #1310 should be done first (ASAP) but don't think closing this is appropriate since it's not fixed, unless you've decided for sure it's not something that should be done.  AFAIK once an issue is closed it gets forgotten forever.  On the other hand, Mesos is actively (albeit slowly) moving to drop its requirement on Zookeeper.

**Comment by kolloch** [comment]
But should we really introduce an "abstraction" for leader election? Isn't one working solution (later without zookeeper) ok? Or do we really need to support multiple mechanisms for leader elections?

I guess that would be a support hassle.
