### ISSUE TITLE
Optimize task queueing

### ISSUE THREAD

**Issue by drexin** [mesosphere/marathon#902]
Currently an app is being added n times to the task queue during a deployment. It would be a lot more efficient to add it only once and include a counter, so that we only match it once against an offer.

**Comment by sttts** [comment]
Just for my understanding: what exactly is so expensive that it deserves this big optimization of the task queue?

**Comment by drexin** [comment]
I think we can expect hundreds of thousands of tasks on up to hundreds of thousands of machines. Finding a matching task has quadratic complexity, so if we just add the same app N times, we have a worst case of 100.000 x 100.000 calls to the matching function. Matching also is very expensive. We have seen cases, where Marathon couldn't catch up with the offers.

**Comment by sttts** [comment]
Ok, O(n^2) is a good reason.
