### ISSUE TITLE
Environments variables in BRIDGE mode (PORT, PORTS)

### ISSUE THREAD

**Issue by AlexGaspar** [mesosphere/marathon#905]
Hey,

Why are the PORT(s) environments variables set to hostPort in bridge mode?

e.g. with this configuration : 
```json
"network": "BRIDGE",
"portMappings": [
    { "containerPort": 8080, "hostPort": 0, "servicePort":  11100, "protocol": "tcp" }
]
```

The environments variables will be for example : 

```bash
 "PORT=31000",
 "PORTS=31000",
 "PORT0=31000",
```

When I'd expect them to be set at `8080`.

Is this the expected behaviour ?
Alex

**Comment by kolloch** [comment]
Hi @AlexGaspar ,

I guess that this is intended. @ConnorDoyle is just extending the documentation a bit. See [environment variables](https://github.com/mesosphere/marathon/pull/1319/files).

I think it is not entirely intuitive but it makes sense. Since the container port is fixed anyway for typical docker deployments, you can hard-code it in your configuration. You usually do not need to know your host port in your docker container but if you need it, it's there.

What do you think?

**Comment by stuart-warren** [comment]
I agree with @AlexGaspar.
If I'm running a 12factor app which is expecting a PORT env var to start on, then the PORT variable that I explicitly set gets overwritten in bridge mode and so starts on the wrong port. In host network mode it works, but it's really confusing.

Try out:
```
{
    "id": "/example-java-jetty",
    "args": [
        "start",
        "web"
    ],
    "container": {
        "type": "DOCKER",
        "docker": {
            "image": "stuartwarren/example-go:060da68",
            "network": "BRIDGE",
            "portMappings": [
                {
                    "containerPort": 5000,
                    "hostPort": 0,
                    "servicePort": 5000,
                    "protocol": "tcp"
                }
            ]
        }
    },
    "cpus": 0.1,
    "env": {
        "POWERED_BY": "you!",
        "PORT": "5000"
    },
    "ports" : [5000],
    "healthChecks": [
        {
            "protocol": "HTTP",
            "gracePeriodSeconds": 30,
            "intervalSeconds": 10,
            "maxConsecutiveFailures": 3,
            "timeoutSeconds": 5
        }
    ],
    "instances": 1,
    "mem": 32
}
```
```
vagrant@mesos:~$ sudo docker exec -ti c8e bash
root@c8e25c977ccf:/# env
HOSTNAME=c8e25c977ccf
HOST=mesos
PORT0=31000
MESOS_TASK_ID=example-java-jetty.c0222c09-d232-11e4-bcab-5a4db12a9abd
GIT_SHA1=060da68
POWERED_BY=you!
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
PWD=/
PORT_5000=31000
PORTS=31000
SHLVL=1
HOME=/
MARATHON_APP_ID=/example-java-jetty
GIT_BRANCH=master
MARATHON_APP_VERSION=2015-03-24T14:33:29.775Z
PORT=31000
MESOS_SANDBOX=/mnt/mesos/sandbox
_=/usr/bin/env
```
If it's not going to use the containerPort value, then I think at least it should not overwrite variables set by the user.

unless I'm doing something really stupid?

**Comment by kolloch** [comment]
@stuart-warren : I agree that it should not overwrite the user specified environment variables and that should be easy to change.

I think it might be problematic to change the default meaning though. If anyone already depends on the current semantics, I do not want to break their code.

**Comment by stuart-warren** [comment]
Thats understandable, thanks for the quick fix @kolloch!
