### ISSUE TITLE
Create job using port forwarding (`ports` in JSON), worked in 0.6.0 - not in 0.7.5

### ISSUE THREAD

**Issue by andypetrella** [mesosphere/marathon#907]
## Goal
What we would like to do is to forward the port on the slave created using `$PORT0` in the command by Chronos (the app to deploy).

## Statement
Before we were using marathon v0.6.0, and it used to work by posting the below JSON -- which specifies a `ports` field containing the local port (marathon machine) that will forward to Chronos.

So that we can use http://<marathon-host>:8888 to access Chronos.

```{json}
{
  "id": "core-service-chronos",
  "instances": 1,
  "cpus": 0.1,
  "mem": 200.0,
  "ports": [
    8888
  ],
  "requirePorts": false,
  "cmd": "java -cp 'target/*' com.airbnb.scheduler.Main --master zk://zk0:2181,zk1:2181,zk2:2181/mesos -z zk0:2181,zk1:2181,zk2:2181 --http_port $PORT0",
  "uris": [
    "hdfs://<hdfs-nnode>:8020/marathon/jobs/core-service-chronos/chronos.tar.gz"
  ]
}
```

## Problem
Since upgrading to 0.7.5, using the same JSON is well deploying Chronos on Mesos, however the port is not opened on the Marathon node.

We dug here and there (we might have left some holes opened, sorry about that... we'll clean :-D).
So we found that a parameter `requirePorts` might be needed, which is per default set to `false`.
Setting it to true will indeed require Mesos to offer port ranges. Our Mesos slaves (0.20.0) aren't configured to do so.

And actually, it should be okay, because we don't want the slave to allow the port `8888` to be opened by the Marathon host to forward request on its `8888` port to the Slave's port `$PORT0`.

We also found that a _containerizer_ for Mesos could help us by providing the `portMappings` but we didn't find any examples of such use case. ATM, we only found Docker examples, which we aren't using (yet).

## Questions
The `port`, `requirePorts` and `portMappings` should be the right combination, AFAIU.
The `port` and `requirePorts` to enable HAProxy. And `portMappings` to allow access from a static host, the Marathon one.

Hence, how the JSON should look like to enable this? 

And will that require our Mesos installation to be adapted?

### Our case
For the note, we don't require HAProxy now, but only the port forwarding.

**Comment by ConnorDoyle** [comment]
Closing for now, feel free to re-open if you run into more questions.
