### ISSUE TITLE
Marathon is unsure when task was started

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#918]
Notice that between two invocations `startedAt` changed:

* `2014-12-27T16:47:36.852Z`
* `2014-12-27T16:48:06.907Z`

Everything else is not changed.

```
~ λ curl -s http://marathon:8080/v2/tasks | jq .tasks[0]
{
  "appId": "/topface/collectd/es/analytics/web487",
  "id": "topface_collectd_es_analytics_web487.0b9cc007-8d5b-11e4-9c4e-56847afe9799",
  "host": "web566",
  "ports": [
    31313
  ],
  "startedAt": "2014-12-27T16:47:36.852Z",
  "stagedAt": "2014-12-26T23:58:10.432Z",
  "version": "2014-12-03T17:36:32.503Z",
  "servicePorts": [
    10008
  ]
}
~ λ curl -s http://marathon:8080/v2/tasks | jq .tasks[0]
{
  "appId": "/topface/collectd/es/analytics/web487",
  "id": "topface_collectd_es_analytics_web487.0b9cc007-8d5b-11e4-9c4e-56847afe9799",
  "host": "web566",
  "ports": [
    31313
  ],
  "startedAt": "2014-12-27T16:48:06.907Z",
  "stagedAt": "2014-12-26T23:58:10.432Z",
  "version": "2014-12-03T17:36:32.503Z",
  "servicePorts": [
    10008
  ]
}
```

Diff for the whole fleet of services running on marathon shows the same picture: `startedAt` changes from time to time.

**Comment by ConnorDoyle** [comment]
The startedAt field should only be set upon receiving a TASK_RUNNING for the first time.  See: https://github.com/mesosphere/marathon/blob/71f8ad035bc593076fcef4effc4572280901d606/src/main/scala/mesosphere/marathon/tasks/TaskTracker.scala#L77.

**Comment by sttts** [comment]
This bug breaks the grace period because the calculation depends on the startedAt value. Hence, a task which is unhealthy from the beginning will never be killed because it is assumed that it's still in the grace period.

I will prepare a patch.
