### ISSUE TITLE
Marathon, docker, consul. containerPort = hostPort = 0 for udp and tcp

### ISSUE THREAD

**Issue by amiorin** [mesosphere/marathon#929]
I would like to be able to do this with docker bridge :

```json
      "portMappings": [
        { "containerPort": 0, "hostPort": 0, "protocol": "all" },
      ]
```

Consul requires same udp and tcp port for container and host.
I use ``-advertise`` switch of consul.
https://consul.io/docs/agent/options.html

**Comment by amiorin** [comment]
@tnachen I like your idea of named ports.

**Comment by ConnorDoyle** [comment]
@amiorin, did you see issue https://github.com/mesosphere/marathon/issues/751?

Allowing the ports to be named could help in other circumstances, but I don't see how it would solve this specific problem.  What is the `docker run` command you would use to run the consul image in bridged networking mode at the command line?

**Comment by amiorin** [comment]
@ConnorDoyle 40000 (ssh) and 40001 (consul) are used only in development mode.
I don't use marathon during development. I start the container manually with the docker command.
In production everything is supposed to be dynamic.

```
docker run \
  -d \
  --net bridge \
  -p 0.0.0.0:40000:22 \
  -p 0.0.0.0:40001:40001/tcp \
  -p 0.0.0.0:40001:40001/udp \
  -e PORT0=40000 \
  -e PORT1=40001 \
  container
```

**Comment by sanjana-bhat** [comment]
Hello,

We have the same requirement where containerPort and hostPort can be set to 0 so that both are dynamically generated and are mapped. Currently setting both container and host ports to 0 causes an error in submitting the tasks. I can submit a patch for it if the issue isn't being looked into.

Thanks!

**Comment by amiorin** [comment]
@sanjana-bhat 
That would be nice.

**Comment by sanjana-bhat** [comment]
@amiorin 
Can you please review the changes? https://github.com/mesosphere/marathon/pull/1468

**Comment by sttts** [comment]
The commit https://github.com/mesosphere/marathon/commit/445dc4e966eaea27634b0518d6b80e7a68ab009f does not fix the problem of this issue. The issue asks for dynamically chosen ports with tcp *and* udp in parallel.

E.g. I have a Kerberos KDC here which wants to provide services on port X with tcp and udp. This cannot be expressed in Marathon.
