### ISSUE TITLE
Race condition when updating an existing group and deployments

### ISSUE THREAD

**Issue by samccone** [mesosphere/marathon#935]
When issuing a request to update an existing group and then checking the list of deployments via `/v2/deployments` the `deploymentId` that I got back from a successful update of the group is not always present. 

I had an assumption that when I received a `deploymentId` back from an update of a group that the deployment would be present in the api end point for deployments. 

This is something that does not happen every time, however is does happen enough that I think it is a racey condition.

**Comment by drexin** [comment]
Will it eventually appear, or never?

**Comment by samccone** [comment]
It does eventually appear, this only happens sometimes.

**Comment by drexin** [comment]
That's just the normal effect of concurrency. The call to the HTTP endpoint returns as soon as the deployment has been accepted, which doesn't mean, that it is already running.

**Comment by aquamatthias** [comment]
Please reopen, if that is still a problem.

**Comment by bobrik** [comment]
@aquamatthias this is still an issue, I believe #1407 describes the same.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3680. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
