### ISSUE TITLE
How to use a Private registry

### ISSUE THREAD

**Issue by djannot** [mesosphere/marathon#938]
Here is the error message when I want to launch an image called 10.64.231.45:5000/s3pics :

09:54:14.958 deimos.containerizer.docker.launch() STDERR // Error response from daemon: wait: No such container: 706a8ae90e097825fd43c8a5ed3222ec1b4b5ab4cbdacc4c30c2c30281591395
2015/01/06 09:54:14 Error: failed to wait one or more containers

**Comment by djannot** [comment]
I'm now using docker as the containerizer and it works this way

**Comment by drexin** [comment]
Yes, support for Deimos has been dropped when Mesos got the native Docker support.
