### ISSUE TITLE
What advantage does mesos add on top of zookeeper

### ISSUE THREAD

**Issue by sourav82** [mesosphere/marathon#939]
I was trying to schedule some memory intensive task on mesos. Scenario is like below-

Let us assume that we have 2 nodes each having 16 GB RAM that runs Mesos slaves. I have a task that requires 30 GB of RAM. Can I run this single task on Mesos? 

If yes, how is it possible in mesos? 
If no, then, what additional benefit Mesos provide over Zookeeper?

**Comment by ssk2** [comment]
Hi @sourav82, I'm afraid that Mesos isn't able to run your task if it is larger than the available amount of memory on a single node. 

While Mesos provides a layer of abstraction to resources, this is primarily used for scheduling of tasks on a cluster. Once an application runs an instance of a task, it is run within a cgroups constrained environment on the underlying node. This will constrain it to the resources specified (so for instance, if you launch two tasks that require 10GB of memory each, it will ensure those tasks are unable to use more than 10GB of memory). However, if the task requires, as in your example, 30GB and attempts to run on a 16GB node, it's likely that the task will fail - exactly how depends on your executor.

Mesos itself is not analogous to ZooKeeper - although if you've found a way to use ZooKeeper to orchestrate tasks on a cluster, I would love to see it :). Mesos provides an easy way to run tasks on a cluster of nodes - you register your application (as a framework) with the Mesos master and it is able to launch tasks easily on the entire cluster. On the other hand, ZooKeeper provides a service to share configurations, name data and various other primitives. If you use ZooKeeper with your distributed application, it is still necessary to handle the actual orchestration of tasks - i.e. to figure out where to run them, to actually launch them and to react when, for various reasons, they fail to launch or unexpectedly quit. Mesos (and Marathon) are able to handle this for you.

Hope this helps!

**Comment by sourav82** [comment]
@ssk2 Thanks a lot for great explanation. Really helped. Thanks!
