### ISSUE TITLE
Populate healthCheckResults even no checks performed yet

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#940]
I'm trying to improve our service discovery for marathon (http://github.com/bobrik/marathoner) and found that marathon does not populate `healthCheckResults` for new tasks in `/v2/tasks` api.

Here's an example of task that was started and had some health checks:

``` json
    {
      "appId": "/topface/docker/registry-mirror",
      "id": "topface_docker_registry-mirror.5fe0171e-9593-11e4-892e-56847afe9799",
      "host": "web14",
      "ports": [
        31000
      ],
      "startedAt": "2015-01-06T11:03:56.408Z",
      "stagedAt": "2015-01-06T11:01:32.922Z",
      "version": "2015-01-06T11:01:32.250Z",
      "servicePorts": [
        5000
      ],
      "healthCheckResults": [
        {
          "taskId": "topface_docker_registry-mirror.5fe0171e-9593-11e4-892e-56847afe9799",
          "firstSuccess": "2015-01-06T11:01:58.361Z",
          "lastSuccess": "2015-01-06T11:04:15.725Z",
          "lastFailure": null,
          "consecutiveFailures": 0,
          "alive": true
        }
      ]
    },
```

And here's a very new task for the same app that has no `healthCheckResults`:

``` json
    {
      "appId": "/topface/docker/registry-mirror",
      "id": "topface_docker_registry-mirror.c01ffb9f-9593-11e4-892e-56847afe9799",
      "host": "web359",
      "ports": [
        31000
      ],
      "startedAt": "2015-01-06T11:04:15.389Z",
      "stagedAt": "2015-01-06T11:04:14.401Z",
      "version": "2015-01-06T11:04:13.848Z",
      "servicePorts": [
        5000
      ]
    }
```

Since we do not see that task has health checks, we add it to lb pool. A moment later health check is performed and task becomes unhealthy (startup did not happen yet), so we remove task from lb pool. Then task becomes healthy again and we add it to lb pool for the last time. This could be avoided if we populate `healthCheckResults` with empty data like this:

``` json
      [
        {
          "taskId": "topface_docker_registry-mirror.5fe0171e-9593-11e4-892e-56847afe9799",
          "firstSuccess": null,
          "lastSuccess": null,
          "lastFailure": null,
          "consecutiveFailures": 0,
          "alive": false
        }
      ]
```

I'm on marathon 0.7.5.

**Comment by bobrik** [comment]
That said, marathon 0.7.6 is missing on docker hub.

**Comment by bobrik** [comment]
Still an issue in master, btw.

**Comment by bobrik** [comment]
Readiness Checks were introduced, but this is still broken.

**Comment by tysonnorris** [comment]
I'm seeing this as well

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3841. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
