### ISSUE TITLE
Health red even when health checks are ok

### ISSUE THREAD

**Issue by djannot** [mesosphere/marathon#942]
Marathon version: 0.7.6

Here is the api result showing health checks are ok:
{"app":{"id":"/s3pics","cmd":"cd /s3pics; ./s3pics -AccessKey=denis@ad.forest -SecretKey=sREvJOCLvj9ELxtwIvkuANkmE/C5uB18ePBpbflH -EndPoint=http://denisnamespace.ns.viprds.ad.forest:9020 -Namespace=denisnamespace","args":null,"user":null,"env":{},"instances":1,"cpus":0.5,"mem":64.0,"disk":0.0,"executor":"","constraints":[],"uris":[],"storeUrls":[],"ports":[10000],"requirePorts":false,"backoffSeconds":1,"backoffFactor":1.15,"container":{"type":"DOCKER","volumes":[],"docker":{"image":"10.64.231.45:5000/s3pics","network":"BRIDGE","portMappings":[{"containerPort":8080,"hostPort":0,"servicePort":10000,"protocol":"tcp"}],"privileged":false,"parameters":{}}},"healthChecks":[{"path":"/","protocol":"HTTP","portIndex":0,"gracePeriodSeconds":10,"intervalSeconds":20,"timeoutSeconds":20,"maxConsecutiveFailures":3}],"dependencies":[],"upgradeStrategy":{"minimumHealthCapacity":1.0},"version":"2015-01-06T16:26:21.165Z","tasksStaged":0,"tasksRunning":1,"deployments":[],"tasks":[{"id":"s3pics.c326b2e8-95c0-11e4-93a0-0242ac110003","host":"coreos3.ad.forest","ports":[31000],"startedAt":"2015-01-06T16:27:44.533Z","stagedAt":"2015-01-06T16:26:26.833Z","version":"2015-01-06T16:26:21.165Z","appId":"/s3pics","healthCheckResults":[{"taskId":"s3pics.c326b2e8-95c0-11e4-93a0-0242ac110003","firstSuccess":"2015-01-06T16:26:41.629Z","lastSuccess":"2015-01-06T16:27:41.487Z","consecutiveFailures":0}]}],"lastTaskFailure":null}}

**Comment by drexin** [comment]
This is a known issue and has been fixed in master.

**Comment by djannot** [comment]
Thanks

**Comment by lukaswelte** [comment]
Look at #930 and #871 ;)
