### ISSUE TITLE
Marathon should pull the latest image before running it

### ISSUE THREAD

**Issue by djannot** [mesosphere/marathon#943]
I have a 3 nodes cluster and I've started an app with 4 instances, then I found that one instance was running an old version of the image

**Comment by lukaswelte** [comment]
A duplicate of #880 

Quick answer.. use tagged docker images. Then you will be fine and you get some versioning in addition for free ;)

**Comment by drexin** [comment]
Right, we recommend using tags, because otherwise rollbacks would not be possible.

I will close this, as this is a duplicate.

**Comment by djannot** [comment]
Perfect, thanks guys

**Comment by ConnorDoyle** [comment]
See also #899 -- this will be added to Marathon after Mesos 0.22.0 is released.

**Comment by djannot** [comment]
Awesome !
