### ISSUE TITLE
'hello world' for GUI users

### ISSUE THREAD

**Issue by air** [mesosphere/marathon#949]
Marathon needs a Hello World. A first-time user brings up the GUI, and wants to deploy something simple. It's difficult to find something to run - you need a Command and possibly a URI as well.

Maybe we have a hello-world.zip in the Marathon distro (/examples), or at a well-known location?

**Comment by ssk2** [comment]
:+1:

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3838. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
