### ISSUE TITLE
Health checks are broken after 0.7.5 -> 0.7.6 upgrade

### ISSUE THREAD

**Issue by bobrik** [mesosphere/marathon#955]
In UI some checks are red, but `/v2/tasks` says that everything is ok (it is ok actually):

![screen shot 2015-01-07 at 15 31 53](https://cloud.githubusercontent.com/assets/89186/5645567/5ab86902-9682-11e4-89fc-b39ef18f63f0.png)

```json
    {
      "appId": "/topface/lenny/whatever",
      "id": "topface_lenny_whatever.0408ee11-9658-11e4-b11b-56847afe9799",
      "host": "web564",
      "ports": [
        31421
      ],
      "startedAt": "2015-01-07T12:26:26.863Z",
      "stagedAt": "2015-01-07T10:29:09.695Z",
      "version": "2015-01-07T10:29:05.750Z",
      "servicePorts": [
        12001
      ],
      "healthCheckResults": [
        {
          "taskId": "topface_lenny_whatever.0408ee11-9658-11e4-b11b-56847afe9799",
          "firstSuccess": "2015-01-07T12:27:03.656Z",
          "lastSuccess": "2015-01-07T12:31:01.276Z",
          "lastFailure": null,
          "consecutiveFailures": 0,
          "alive": true
        }
      ]
    }
```

For other tasks it is unknown, but `/v2/tasks` says that there are no health checks:

![screen shot 2015-01-07 at 15 33 57](https://cloud.githubusercontent.com/assets/89186/5645583/a96320a6-9682-11e4-8924-7af291880f67.png)

```json
{
      "appId": "/topface/lenny/whatever",
      "id": "topface_lenny_whatever.2af15b43-958f-11e4-892e-56847afe9799",
      "host": "web308",
      "ports": [
        31672
      ],
      "startedAt": "2015-01-07T12:32:00.155Z",
      "stagedAt": "2015-01-06T10:31:26.130Z",
      "version": "2015-01-06T10:31:24.593Z",
      "servicePorts": [
        12001
      ]
    }
```

That app was scaled after upgrade, but I don't see any dependency between having health checks and being started after upgrade. Some new tasks have health checks, some don't.

Upgrade was rolling, then I also restarted each of 3 marathon servers to see if that could help.

**Comment by drexin** [comment]
This is a know issue and has been fixed in https://github.com/mesosphere/marathon/pull/906. Please search the existing issues before opening a new one to avoid duplication.

**Comment by bobrik** [comment]
Sorry, my bad. I saw an issue before, but though that is was in earlier version. Fixing health checks in the latest release probably deserves an extra 0.6.6.1 release or at least a note on releases page.

I deployed 0.7.7-SNAPSNOT and it doesn't work very well too.

Scaling from 18 to 30 is stuck at 28/30, rollback to 18 worked, then scale to 22 worked, then scale to 30 stuck at 28/30 again. No tasks are scheduled in marathon and mesos at 28/30 state. Task get lost with other values too, thay are `FAILED` in mesos with empty stdout and stderr.

When scaling to 22 health checks are started too late. Tasks hang in started state without health checks:

```json
    {
      "appId": "/topface/lenny/whatever",
      "id": "topface_lenny_whatever.bffe34a0-9716-11e4-b3f7-56847afe9799",
      "host": "web419",
      "ports": [
        31569
      ],
      "startedAt": "2015-01-08T09:15:06.851Z",
      "stagedAt": "2015-01-08T09:14:29.415Z",
      "version": "2015-01-08T09:14:28.494Z",
      "servicePorts": [
        12001
      ]
    }
```

And then they are "restarted":

```json
    {
      "appId": "/topface/lenny/whatever",
      "id": "topface_lenny_whatever.bffe34a0-9716-11e4-b3f7-56847afe9799",
      "host": "web419",
      "ports": [
        31569
      ],
      "startedAt": "2015-01-08T09:17:27.584Z",
      "stagedAt": "2015-01-08T09:14:29.415Z",
      "version": "2015-01-08T09:14:28.494Z",
      "servicePorts": [
        12001
      ],
      "healthCheckResults": [
        {
          "taskId": "topface_lenny_whatever.bffe34a0-9716-11e4-b3f7-56847afe9799",
          "firstSuccess": "2015-01-08T09:17:29.348Z",
          "lastSuccess": "2015-01-08T09:20:08.932Z",
          "lastFailure": null,
          "consecutiveFailures": 0,
          "alive": true
        }
      ]
    }
```

Docker says that container is started at `2015-01-08T09:15:05.24820739Z`. Turns out that marathon is changing start time. 2m25s to the first health check is a lot.

I'll stick to 0.7.5 then

**Comment by bobrik** [comment]
I actually downgraded to 0.7.3, because 0.7.5 decided that my app does not have any running tasks twice in one day. 0.7.3 picked up all running tasks from mesos.
