### ISSUE TITLE
Enable the ability to delete groups from the web UI.

### ISSUE THREAD

**Issue by samccone** [mesosphere/marathon#958]
This would be a handy feature and something that I think is useful to most marathon users.

Let me know if you are interested, more than willing to PR this up.

**Comment by mlunoe** [comment]
Deleting a group will delete all the apps from that group as well. This should be handled very carefully.

Maybe you could create a group Modal that will display basic information about the group and put a delete button in there. Like this screenshot, but without "Running", the suspend and scale buttons, and Tasks and Configuration tabs:
![Screenshot of a similar situation](https://s3.amazonaws.com/f.cl.ly/items/3g243900083u0m1s3p1v/Image%202015-01-08%20at%2012%3A02%3A15.png "Screenshot of a similar situation")

The information could be something along the line:
- id (which would display as the name)
- version
- list dependencies
- maybe list sub-group names (you could link to open their info-modal here)

Following the rest of the UI, please make sure to put in a confirm alert on clicking "destroy".

Thank you again for these suggestions!

**Comment by alexraju** [comment]
Any update on this?

**Comment by pierlo-upitup** [comment]
Hi @alexraju this feature was implemented in https://github.com/mesosphere/marathon-ui/releases/tag/v0.15.0
