### ISSUE TITLE
Marathon should not reschedule tasks that end in TASK_ERROR.

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#965]
`TASK_ERROR` signifies some misconfiguration such that the failed task should not be expected to succeed if rescheduled, in contrast to `TASK_LOST`.

**Comment by drexin** [comment]
This needs some more changes, as we also have to notify the user that we will not try to reschedule this app.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-3896. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
