### ISSUE TITLE
Allow users to create new groups

### ISSUE THREAD

**Issue by aatumanova** [mesosphere/marathon#966]
Similar to the "+ new app" button on the applications page, allow users to create groups on the groups page.

Here is documentation for how to creating new application groups: https://mesosphere.github.io/marathon/docs/rest-api.html#post-/v2/groups

**Comment by aquamatthias** [comment]
We should see the groups in the UI first :) But yes :+1:

**Comment by philipnrmn** [comment]
Bumped to 0.14.0 as it does not block 0.13.0

**Comment by aldipower** [comment]
I would like to use the groups-endpoint also for retrieving the available applications for the app-list, so I am able to remove the request on the apps-endpoint.
Unfortunately these embeded data isn't available on the groups-endpoint:
```apps.tasks, apps.count, apps.deployments, apps.lastTaskFailure, apps.failures, apps.taskStats```
Is there a way to enable this at the groups-endpoint returned applications?

@kolloch @aquamatthias 

If not this is a real blocker to introduces advanced group functionality.

**Comment by kolloch** [comment]
@aldipower Currently, it is not possible to obtain the details that you mentioned from the groups endpoint. In theory, it is fairly easy to allow the same embeds as for app endpoints. It is some work for every endpoint involved and some upfront work as well. I'd estimate that I would need about three days including (speedy) reviews.

**Comment by aldipower** [comment]
@kolloch OK, I understand. Thanx for your answer.
Is it maybe possible to do it the other way around?
Requesting the groups-endpoint, with a very limited amount of information on the applications to reduce the payload? So I could request both endpoints (groups, apps) with less cost and match the relation by the app id.

**Comment by kolloch** [comment]
@aldipower yes, it would be possible and a bit less work to provide an argument (e.g. `?onlyAppIds=true`) to the group endpoints to e.g. skip all app fields except the id. I would only want to do it if it makes sense on its own for other use cases.

**Comment by aldipower** [comment]
Cool, exactly such an argument I had in mind.
And does it makes sense for other use cases?

**Comment by kolloch** [comment]
Yes, but the advanced group functionality in the UI should be even faster if you have to perform only one request delivering all required information. It also reduces the load on the backend.

**Comment by aldipower** [comment]
That is true. So the only real solution is to wait on the embed-params at the groups-endpoint. :(
