### ISSUE TITLE
Marathon service can't find Mesos libs

### ISSUE THREAD

**Issue by guidoilbaldo** [mesosphere/marathon#967]
Hi,

 I just installed marathon 0.7.6 on Mesos 0.21.1 on CentOS 7. Following the procedure mentioned here http://mesosphere.com/docs/getting-started/datacenter/install/ I tried to setup a simple cluster with 3 master nodes. Upon finishing Marathon installation and trying to start it (using systemctl start marathon.service command), I got the following exception:

an  8 14:52:33 meslpbm1 marathon[46496]: [2015-01-08 14:52:33,297] INFO Initiating client connection, connectString=meslpbm1.gcio.unicredit.eu:2181,meslpbm2.gcio.unicredit.eu:2181,meslpbm3.gcio.unicredit.eu:2181 sessionTimeout=10000 watcher=com.twitter.common.zookeeper.ZooKeeperClient$3@5b20d371 (org.apache.zookeeper.ZooKeeper:379)
Jan  8 14:52:33 meslpbm1 marathon[46496]: [2015-01-08 14:52:33,308] INFO Opening socket connection to server meslpbm3.gcio.unicredit.eu/10.254.47.161:2181 (org.apache.zookeeper.ClientCnxn:1061)
Jan  8 14:52:33 meslpbm1 marathon[46496]: [2015-01-08 14:52:33,318] INFO Socket connection established to meslpbm3.gcio.unicredit.eu/10.254.47.161:2181, initiating session (org.apache.zookeeper.ClientCnxn:950)
Jan  8 14:52:33 meslpbm1 marathon[46496]: [2015-01-08 14:52:33,330] INFO Session establishment complete on server meslpbm3.gcio.unicredit.eu/10.254.47.161:2181, sessionid = 0x34ac98586880004, negotiated timeout = 10000 (org.apache.zookeeper.ClientCnxn:739)
Jan  8 14:52:33 meslpbm1 marathon[46496]: [2015-01-08 14:52:33,365] INFO Using HttpCallbackEventSubscriber for eventnotification (mesosphere.marathon.Main$:67)
Jan  8 14:52:33 meslpbm1 marathon[46496]: Failed to load native Mesos library from /usr/local/lib
Jan  8 14:52:33 meslpbm1 marathon[46496]: Exception in thread "main" java.lang.UnsatisfiedLinkError: no mesos in java.library.path
Jan  8 14:52:33 meslpbm1 marathon[46496]: at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1886)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at java.lang.Runtime.loadLibrary0(Runtime.java:849)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at java.lang.System.loadLibrary(System.java:1088)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at org.apache.mesos.MesosNativeLibrary.load(MesosNativeLibrary.java:54)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at org.apache.mesos.MesosNativeLibrary.load(MesosNativeLibrary.java:79)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at org.apache.mesos.state.AbstractState.<clinit>(AbstractState.java:36)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at mesosphere.marathon.MarathonModule.provideMesosState(MarathonModule.scala:72)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at java.lang.reflect.Method.invoke(Method.java:606)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.ProviderMethod.get(ProviderMethod.java:104)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.Scopes$1$1.get(Scopes.java:65)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.Scopes$1$1.get(Scopes.java:65)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.SingleParameterInjector.inject(SingleParameterInjector.java:38)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.SingleParameterInjector.getAll(SingleParameterInjector.java:62)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:84)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:254)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.FactoryProxy.get(FactoryProxy.java:54)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1031)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.Scopes$1$1.get(Scopes.java:65)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:40)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:204)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.InternalInjectorCreator$1.call(InternalInjectorCreator.java:198)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1024)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.InternalInjectorCreator.loadEagerSingletons(InternalInjectorCreator.java:198)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.InternalInjectorCreator.injectDynamically(InternalInjectorCreator.java:179)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.internal.InternalInjectorCreator.build(InternalInjectorCreator.java:109)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.Guice.createInjector(Guice.java:95)
Jan  8 14:52:33 meslpbm1 marathon[46496]: at com.google.inject.Guice.createInjector(Guice.java:72)
Jan  8 14:52:34 meslpbm1 marathon[46496]: at mesosphere.chaos.App$class.injector(App.scala:17)
Jan  8 14:52:34 meslpbm1 marathon[46496]: at mesosphere.marathon.Main$.injector$lzycompute(Main.scala:18)
Jan  8 14:52:34 meslpbm1 marathon[46496]: at mesosphere.marathon.Main$.injector(Main.scala:18)
Jan  8 14:52:34 meslpbm1 marathon[46496]: at mesosphere.chaos.App$$anonfun$run$2.apply(App.scala:35)
Jan  8 14:52:34 meslpbm1 marathon[46496]: at mesosphere.chaos.App$$anonfun$run$2.apply(App.scala:34)
Jan  8 14:52:34 meslpbm1 marathon[46496]: at scala.collection.IndexedSeqOptimized$class.foreach(IndexedSeqOptimized.scala:33)
Jan  8 14:52:34 meslpbm1 marathon[46496]: at scala.collection.mutable.WrappedArray.foreach(WrappedArray.scala:35)
Jan  8 14:52:34 meslpbm1 marathon[46496]: at mesosphere.chaos.App$class.run(App.scala:34)
Jan  8 14:52:34 meslpbm1 marathon[46496]: at mesosphere.marathon.Main$.run(Main.scala:18)
Jan  8 14:52:34 meslpbm1 marathon[46496]: at mesosphere.marathon.Main$.delayedEndpoint$mesosphere$marathon$Main$1(Main.scala:86)
Jan  8 14:52:34 meslpbm1 marathon[46496]: at mesosphere.marathon.Main$delayedInit$body.apply(Main.scala:18)
Jan  8 14:52:34 meslpbm1 marathon[46496]: at scala.Function0$class.apply$mcV$sp(Function0.scala:40)
Jan  8 14:52:34 meslpbm1 marathon[46496]: at scala.runtime.AbstractFunction0.apply$mcV$sp(AbstractFunction0.scala:12)
Jan  8 14:52:34 meslpbm1 marathon[46496]: at scala.App$$anonfun$main$1.apply(App.scala:76)
Jan  8 14:52:34 meslpbm1 marathon[46496]: at scala.App$$anonfun$main$1.apply(App.scala:76)
Jan  8 14:52:34 meslpbm1 marathon[46496]: at scala.collection.immutable.List.foreach(List.scala:381)
Jan  8 14:52:34 meslpbm1 marathon[46496]: at scala.collection.generic.TraversableForwarder$class.foreach(TraversableForwarder.scala:35)
Jan  8 14:52:34 meslpbm1 marathon[46496]: at scala.App$class.main(App.scala:76)
Jan  8 14:52:34 meslpbm1 marathon[46496]: at mesosphere.marathon.Main$.main(Main.scala:18)
Jan  8 14:52:34 meslpbm1 marathon[46496]: at mesosphere.marathon.Main.main(Main.scala)

which clearly points out that Marathon is searching for libmesos under /usr/local/lib, while I have them installed under /usr/lib. I installed Mesos and Marathon via yum and also tried to set MESOS_NATIVE_JAVA_LIBRARY and MESOS_NATIVE_LIBRARY environment variables to no avail. Still, I get this exception while starting Marathon service.
I fixed this by creating symbolic links to libs under /usr/lib.
Regards,
Stefano

**Comment by cgbaker** [comment]
How/where are you trying to set the MESOS_NATIVE_JAVA_LIBRARY environment variable? I ran into this problem in the same circumstance, so I added the following to my systemctl file for that service (located at /usr/lib/systemd/system/marathon.service for me):
Environment="MESOS_NATIVE_JAVA_LIBRARY=/usr/lib/libmesos.so"

This cleared the issue up. I was unable to find a way to address this using  /etc/default/marathon

**Comment by kolloch** [comment]
@lloesche has that been solved? If yes, please close this issue.

**Comment by guidoilbaldo** [comment]
Yes it had been solved as pointed out in my comment.

**Comment by testzlx** [comment]
you can add libmesos.so into /usr/lib ,it solve my problem

**Comment by shreyagarwal** [comment]
This problem occurred when I installed mesosphere instead of installing mesos and marathon on ubuntu 14.04

**Comment by crystalfuns** [comment]
where to find this file ?

**Comment by janisz** [comment]
@crystalfuns You can find Mesos native lib in `mesos/build/src/.libs/libmesos.so` if you follow official [build manual](https://mesos.apache.org/gettingstarted/) or you can get it with Mesospheres [Mesos Packages](https://open.mesosphere.com/downloads/mesos/)

**Comment by crystalfuns** [comment]
do we need to keep this files in all the client locations ?

**Comment by janisz** [comment]
You need this file always you want to talk to Meos using deprecated mechanism build on top of this lib. Marathon use Java bindings that just wraps C interface with Java code. If you want to start schedulers on Marathon then yes you probably need this file on all slaves where scheduler could be spawned.
