### ISSUE TITLE
Expose a way to identify "fragile" marathon apps in the web UI (failure history)

### ISSUE THREAD

**Issue by samccone** [mesosphere/marathon#968]
So this is as much a question as an idea, based off of a need and problem we have run into while working on our app.

One of our apps will boot, and show 1/1 (all is good at this point)  ... however a specific action will trigger the task to die, however it will almost instantly switch back to 1/1 (tasks) . The only way to see that something bad happened is to see the side effect of the app going down in the user facing part of the app, or to look at the mesos panel to see the FAILED slave(s). 

It would be dandy to expose some sort of historical (limited to browser session) info on the app tasks. Something like, how often is it dropping tasks, when was the last time it did it... anything really, just to aid a user in the debugging process. 

Thanks again for your time and hearing me out.

**Comment by ConnorDoyle** [comment]
Note to implementer: see the description of #686 for a good explanation of the `lastTaskFailure` key in the JSON response.

**Comment by sttts** [comment]
:+1:
