### ISSUE TITLE
Option to pass Mesos slave attributes to Docker containers as environment variables

### ISSUE THREAD

**Issue by alberts** [mesosphere/marathon#969]
It would be very useful to us if one could configure something in the Marathon app JSON that will let it pass Mesos slave attributes (especially things like rack) to Docker containers as environment variable(s).

This allows things like rack placement to be passed through to clustered apps running inside the container so that they can report it or use it to make decisions.

**Comment by cmoro-deusto** [comment]
+1

**Comment by vishramachandran** [comment]
+1

**Comment by zhitaoli** [comment]
+1

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-4198. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
