### ISSUE TITLE
Docker 'parameters' constrained to single value per key

### ISSUE THREAD

**Issue by LLParse** [mesosphere/marathon#970]
map[string, string] doesn't work in this case because many docker parameters may be passed in multiple times. list(tuple(string, string)) or map[string, list(string)] would fix

For example:
docker run --rm -P -e HEAP_MIN=512M -e HEAP_MAX=1G -e OTHEROPTS=blah blah/java_app

https://github.com/mesosphere/marathon/blob/master/src/main/scala/mesosphere/marathon/api/v2/json/Formats.scala#L167

**Comment by ConnorDoyle** [comment]
You're right, this was an oversight in the implementation.

**Comment by tnachen** [comment]
+1 we need to get this fixed for a number of folks

**Comment by ConnorDoyle** [comment]
Submitted PR #1003.
