### ISSUE TITLE
Out of Memory Exception - Memory usage does not seem bounded

### ISSUE THREAD

**Issue by andrewortman** [mesosphere/marathon#974]
I'm using 0.7.6 on Mesos 0.21.0 - with OpenJDK 7:

OpenJDK Runtime Environment (IcedTea 2.5.3) (7u71-2.5.3-0ubuntu0.14.04.1)
OpenJDK 64-Bit Server VM (build 24.65-b04, mixed mode)

Marathon's memory consumption grows over time, until the GC has to kick in - when that happens, the CPU slowly increases over the period of a few hours until no more space can be reclaimed, causing an OOM exception on java.

**Comment by andrewortman** [comment]
One way I got around this was increasing the Heap by putting -Xmx2G in the JAVA_OPTS variable the upstart script for marathon - and that got me about 10 days before the GC had to really kick in

**Comment by drexin** [comment]
Thanks for reporting this. Could you try to monitor the memory consumption and see what uses so much memory? You can for example do that with [Java Mission Control](http://www.oracle.com/technetwork/java/javaseproducts/mission-control/java-mission-control-1998576.html). If you could provide us with a memory snapshot, that would be even more helpful.

**Comment by elmalto** [comment]
Same issue here. Will investigate

**Comment by aquamatthias** [comment]
This ticket looks orphaned and will be closed. Please reopen, if this is a Marathon problem, that still exists.
