### ISSUE TITLE
REST API: Add meta-data tag for applications/tasks

### ISSUE THREAD

**Issue by yaronr** [mesosphere/marathon#980]
Hi

It would be very helpful if it were possible to add arbitrary key-value mappings as meta-data for tasks/applicaitons, something like the example below.

The goal is to support other applications that use Mesos.
An example (actually something I've been working for) is service discovery. From the /tasks api, I can get the name of the app, the host, and the port. But I would also like to have some meta-data, such as - host header, url regular expression and other parameters - that are needed for the HAProxy configuration template (see example here: https://gist.github.com/yaronr/c3d527145a3b0f2459ee  )

I'm very new to Mesos, so please excuse me if there's a better way of doing this and I'm missing it. But if not, I'm sure that a lot of other people would come up with clever ways to use this capability.

"tasks":[  
      {  
         "appId":"/wiki",
         "id":"wiki.8d43ba25-99af-11e4-ba59-9ec51a17f73c",
         "host":"multicloud-mesos-slave-3.weave.local",
         "ports":[  
            31000
         ],
         "metadata": [
                "key"="value", "key2"="value"
         ],
         "startedAt":"2015-01-11T16:39:13.775Z",
         "stagedAt":"2015-01-11T16:33:19.633Z",
         "version":"2015-01-11T14:26:40.398Z",
         "servicePorts":[  
            8080
         ]
      }

**Comment by alberts** [comment]
Anybody looking at this? I might give it a try.

**Comment by alberts** [comment]
It would be useful to get some guidance from main developers on how they want to model this.

```
diff --git a/src/main/proto/marathon.proto b/src/main/proto/marathon.proto
index 9ebf22b..f0f0314 100644
--- a/src/main/proto/marathon.proto
+++ b/src/main/proto/marathon.proto
@@ -63,6 +63,7 @@ message ServiceDefinition {
   repeated string storeUrls = 17;
   optional bool require_ports = 18 [default = false];
   optional ExtendedContainerInfo container = 19;
+  repeated Tag tags = 20;
 }
 
 message MarathonTask {
@@ -161,3 +162,7 @@ message TaskFailure {
   required string timestamp = 7;
 }
 
+message Tag {
+  required string key = 1;
+  required string value = 1;
+}
```

Yes? No?

**Comment by yaronr** [comment]
Hey @alberts 
Thank you for taking this!!

**Comment by alberts** [comment]
@yaronr Looks like a non-trivial amount of work, so I'd like to get some feedback before I start. In the mean time, if you want to hack it, you could abuse the "env" map in the application definition to put some tags in (maybe with some prefix like MARATHON_TAG_ so as not to confuse them with other environment variables).

https://mesosphere.github.io/marathon/docs/rest-api.html#post-/v2/apps

**Comment by yaronr** [comment]
Yeah, I was thinking about the same hack. Thanks

**Comment by felixb** [comment]
I'd like to see something like metadata too.

**Comment by rasputnik** [comment]
Do the labels in marathon 0.8 solve this? See 'Apps can now have labels' at:

    https://mesosphere.com/2015/02/06/marathon-0.8.0-has-been-released/

**Comment by yaronr** [comment]
I think so, from the few description lines in the link. Can you share more info? I would like to see an example.

**Comment by yaronr** [comment]
@rasputnik  ping :)
Information on 'labels' is very scarce.
Can you / someone shed some light on this new capability?
REST API also doesn't seem to be documented (or I may be looking in the wrong place)

Thanks

**Comment by kolloch** [comment]
there were some delays in publishing the updated documentation on github pages.

There is some documentation for labels on this page: https://mesosphere.github.io/marathon/docs/rest-api.html.

In the current master there is also code which adds these labels to the corresponding tasks in Mesos.

See https://github.com/mesosphere/marathon/commit/252992dbee1e8c89b195dd932436114d6f883ec4

Thus I will close this issue now. If I am missing something, we can reopen it.
