### ISSUE TITLE
Lost App Instances?

### ISSUE THREAD

**Issue by samccone** [mesosphere/marathon#982]
I (and my team) have encountered this issue several times and have yet to come up with a good "fix".

When I attempt to create a new group (deployment)

My marathon instance will have several apps that are listed as running (but not healthy - green), however they are not backed by a docker container. (`docker ps` tells me this)

When I attempt to remove the entire deployment the rollback simply sits because I am guessing mesos is unable to cleanup the container since it is no longer tracked. 

Any thoughts on this? Or I very well could be totally off base and doing something very wrong. Thanks again for the time. :+1:

**Comment by drexin** [comment]
What versions of Marathon and Mesos do you use?

**Comment by samccone** [comment]
mesos:           0.20.1-1.0
  marathon:        0.7.5-1.0

**Comment by drexin** [comment]
There have been some issues regarding container registration and also task reconciliation in Mesos < 0.21.0. Do you see these tasks in the Mesos UI, or only in Marathon? No Matter what, this should work with Mesos 0.21.0. Can you please try and report your results here?

**Comment by samccone** [comment]
great will try on that version and will close this issue unless I am able to reproduce on .21

thanks @drexin
