### ISSUE TITLE
Execute One-Off Task

### ISSUE THREAD

**Issue by jamescun** [mesosphere/marathon#983]
We are currently building out our infrastructure of long running services on top of marathon and were wondering if there were a way to execute a task once (or at least once) and then not relaunched if something like the exit code was zero?

The use case, for us, is to run database migrations from our Docker containers.

**Comment by elingg** [comment]
Have you looked into chronos for this scenario? It seems to be a fit.

**Comment by mlunoe** [comment]
https://github.com/mesosphere/chronos

**Comment by clehene** [comment]
@jamescun @elingg @mlunoe 
For such a simple use case, I don't think it's worth having a dedicate framework that you need to care for like Chronos.

Also there is (and was when this was created) an issue for this feature in marathon already https://github.com/mesosphere/marathon/issues/344
