### ISSUE TITLE
Exponential backoff is stored locally, so backoff timers are rest after a failover

### ISSUE THREAD

**Issue by solarkennedy** [mesosphere/marathon#985]
Context:
Imaging the situation where, over the course of a month you build 100 marathon apps with 100 instance each, and they all fail all the time. Exponential backoff happens normally so this not a big deal.

But when a marathon failover happens, the backoff delay state is lost and now you have a thundering herd of tasks that, the old marathon knew were probably not going to run anyway, but the new leader doesn't know any better and dos's your mesos.

I think the core line is here:
https://github.com/mesosphere/marathon/blob/e412648377aa646a81a66a15d55fa98cedd20f99/src/main/scala/mesosphere/util/RateLimiter.scala#L20

I think the fix is to store this in the delays in the zookeeper state?

Or, if the delay is not populated, maybe it could default to calculate what the initial delay *should be* based of the list of failed tasks or something?

**Comment by drexin** [comment]
I don't think this can be a real problem. First of all, the backOff will be built up again pretty fast. Second, if you really have hundreds of apps, that fail all the time, you should probably do something about that, rather than ignoring them.

However, if you have a real case where this is a problem, I'm happy to evaluate it.

**Comment by ConnorDoyle** [comment]
With the default backoff settings (1 second with a factor of 1.15), it only takes 25 consecutive failed tasks for the delay to reach 30 seconds between launches for each app.  At 50 failed tasks the delay is already 20 minutes.  If this does become an issue, increasing the backoff factor can help to mitigate it.  One reason for not doing this is that it would increase the frequency of writes to the persistent state.  As Dario mentioned, hopefully this isn't a problem in practice.

**Comment by solarkennedy** [comment]
@drexin I agree that hundreds of failing apps is a problem, but when teams are distributed and things are constantly in development, having many broken apps seems like a legit situation to me.

@ConnorDoyle I agree that the default settings are pretty good, and I have raised my backoff factor to make it quickly reach the max backoff. 

I agree that increasing the frequency of writes is bad. This really did happen to me in real life last week, where I was trying to debug something, a marathon failover happened, and mesos started to churn through all of these failing tasks and I was like, wtf? and almost panicked. Or monitoring failed task rates on mesos is now no longer a good indicator if something is "wrong", and more of a "oh marathon failed over again probably"


I'll close the issue for now. Someone else might re-open with better ideas on what to do, or maybe I'll come back with a PR to fix if I can think of something really clever.
