### ISSUE TITLE
Marathon kills container when requests increase

### ISSUE THREAD

**Issue by dohaivu** [mesosphere/marathon#994]
I deploy Docker containers on Mesos(0.21) and Marathon(0.7.6) on Google Cloud Engine (Ubuntu 14.04)
I use JMeter to test a REST service that run on Marathon. When the concurrent requests are less than 10, it works normal, but when the concurrent requests are over 50, the container is killed and Mesos start another container. I increase RAM, CPU but it still happens.

This is log in mesos slave:
```text
E0116 09:33:31.554816 19298 slave.cpp:2344] Failed to update resources for container 10e47946-4c54-4d64-9276-0ce94af31d44 of executor dev_service.2e25332d-964f-11e4-9004-42010af05efe running task dev_service.2e25332d-964f-11e4-9004-42010af05efe on status update for terminal task, destroying container: Failed to determine cgroup for the 'cpu' subsystem: Failed to read /proc/612/cgroup: Failed to open file '/proc/612/cgroup': No such file or directory
```

**Comment by drexin** [comment]
Marathon only kills tasks, when it has health checks defined and they fail consecutively for the configured amount of time. Are you sure that Marathon sends a kill command? Could you please post the relevant log lines?

**Comment by dohaivu** [comment]
I solved this issue by increase the RAM for container
