### ISSUE TITLE
sbt assembly should also compile front end assets 

### ISSUE THREAD

**Issue by samccone** [mesosphere/marathon#999]
Currently `sbt assembly` assumes the front end has been compiled, this is problematic because it means that any changes to the front end require the entire build file(s) for the front end to be compiled.

This is noisy to the diff, and adds complexity to doing releases of the project.

I propose to have `sbt assembly` also build the front end assets.

re: 
https://github.com/mesosphere/marathon/commit/0b6560420ccbfeaeadb07fa55f244c3361117c5a#commitcomment-9283899

**Comment by aquamatthias** [comment]
The idea was to have a self contained frontend project - right?
Than this does not make that much sense.

**Comment by aquamatthias** [comment]
UI is a separate project.
